### ISSUE TITLE
Table 'teampass.teampass_statistics' doesn't exist

### ISSUE THREAD

**Issue by mobilefactor** [nilsteampassnet/TeamPass#1001]
I'm getting the following error in Views Icon --> Logs Tab --> Errors:

SELECT view FROM teampass_statistics WHERE scope = 'item' AND item_id = 100<br />Table 'teampass.teampass_statistics' doesn't exist@/teampass/sources/main.queries.php

I'm running 2.1.22.  I verified that the table is missing.  How should I resolve this?

**Comment by nilsteampassnet** [comment]
You should migrate to 2.1.23.

I remember this is an old bug.

**Comment by mobilefactor** [comment]
Thanks.
