### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Hellbartonio** [nilsteampassnet/TeamPass#1002]
Unable to move items created by other user using mouse (there is no icon with dots to click on). Both users have same roles and permissions on folders. However moving items using "edit" menu works like it should.
v2.1.23, CentOS 6.6
![capture-tp](https://cloud.githubusercontent.com/assets/12493230/8457453/0ccb9ab2-201a-11e5-8b70-6ce07d3fd559.PNG)

**Comment by nilsteampassnet** [comment]
For a reason that I don't have found, when using drag and drop feature, you need to drag more on the left of the target folder.

By doing this, you will see that this target folder will become overlayed and you will be able to drop.

![image](https://cloud.githubusercontent.com/assets/1197546/8894362/bef3a89a-33b3-11e5-9840-22d9c1da2e37.png)

**Comment by Hellbartonio** [comment]
The problem is that I can't even start dragging: some items are moveable with mouse, and others are not. There are cross icons at every item on your screenshot and only one icon like this on mine. So you can drag'n'drop every listed item, but I can only drag that one that highlighted.

**Comment by nilsteampassnet** [comment]
An item can be moved only if user can edit it.
Are you sure you can edit those items?

**Comment by Hellbartonio** [comment]
Yes I do, both users can edit item and even move it using "edit" menu, but can't drag'n'drop.

**Comment by nilsteampassnet** [comment]
Strange ... what version do you use?

I'm wondering why only on one item it is possible. Could you check and try
to identify the difference that exist between this "dragable" ​object and
the others.
I'm wondering about the related rights.

This can help in debuging the source code because I cannot reproduce.

**Comment by Hellbartonio** [comment]
I use [v2.1.23] (https://github.com/nilsteampassnet/TeamPass/tree/master). Checked everything and haven't found anything suspicious. The one and only difference between items - user, who originally created them. If I create new item, then I can drag'n'drop it and other user can't. If other user create item, he is able to drag'n'drop it and I am not. I can edit his item, can change it's folder using edit menu can delete and copy it. If I copy other user's item, then I can drag this copy, but not source. Same with another user, he can drag item which he created, but not copy made by me.

**Comment by nilsteampassnet** [comment]
​This is very interesting.

I will check the source code against what you described.

THanks​

**Comment by ArthurGuy** [comment]
I have just upgraded to 2.1.23.1 and I am still having this issue.
Items created by others don't seem to have the draggable option

**Comment by nilsteampassnet** [comment]
By design, an item is draggable if:
* item has attribute "can be modified by anyone" enabled
OR
* user who see the list is the author of the item

As a result, it is not draggable if you are not the author or if the author
has not indicated that the item can be modified by anyone.
