### ISSUE TITLE
Item Details frame sometimes doesn't work in Firefox

### ISSUE THREAD

**Issue by toptnc** [nilsteampassnet/TeamPass#1004]
This issue only happens with Firefox, in Chrome it works ok.

In some folders, items details are not showed.

Looking in code with Firebug, I have modified that line and removed "overflow-y:auto"
![seleccion_073](https://cloud.githubusercontent.com/assets/1016579/8497595/d2ad39e2-217e-11e5-8dcf-cbe9e41c6ece.png)

After doing that I can see items details outside the frame.

![seleccion_074](https://cloud.githubusercontent.com/assets/1016579/8497610/e4cbc5b2-217e-11e5-8c3c-adf770c02f36.png)

I don't know why item details works ok in some folders and doesn't work in some others.

**Comment by nilsteampassnet** [comment]
Hum this one will be difficult to find. 
What version of firebox do you use? 
You confirm that it happens only on firefox ? 
Can you think about something you do before it happens?

**Comment by toptnc** [comment]
Latest version of Chrome and Firefox.
Unfortunately, it happens in chrome too. I have just confirmed, but it doesn't happens in the same folders.

It's a weird problem, I know.

**Comment by toptnc** [comment]
Removing "overflow-y:auto", in Chrome, seems to fix the problem.

**Comment by toptnc** [comment]
I think, i have found a solution.

Giving more space to "items_center" fixes the problem, just 3 or 4 pixels more.

Where is it calculated?

**Comment by toptnc** [comment]
I have a Fix.

in items.load.php, line 1957, give 10px more to "items_center" and "items_tree"

BEFORE:
```php
    $("#items_center").height(window_height-390);
    $("#items_list").height(window_height-440);
    $(".items_tree").height(window_height-160);
    $("#jstree").height(window_height-185);
```
AFTER
```php
    $("#items_center").height(window_height-380);
    $("#items_list").height(window_height-440);
    $(".items_tree").height(window_height-150);
    $("#jstree").height(window_height-185);
```

**Comment by borzel** [comment]
This issue always occoures to me, when a folder path is too long and the darker grey box (with the path and search field) increases in height.
The `overflow-y:auto` seems to hide that detail pane in the right of the browser.
If I manually remove the `overflow-y:auto` via the firefox developer tools, it work's as expected.

**Issue with long path:**
![grafik](https://user-images.githubusercontent.com/5782951/57861663-4af97280-77f7-11e9-99da-b712b62f6ed9.png)


**Works with short paths:**
![grafik](https://user-images.githubusercontent.com/5782951/57861642-3ddc8380-77f7-11e9-9bf6-3f72066fb208.png)

**Comment by borzel** [comment]
so I would suggest to remove `overflow-y:auto`
