### ISSUE TITLE
Unable to upload attachments

### ISSUE THREAD

**Issue by bcwhittle** [nilsteampassnet/TeamPass#1011]
At one point, I was able to upload attachments. Since then, I have changed the location of the uploads directory. I do not know if that is the cause, but I can no longer upload attachments. It goes through the process and even shows 100% uploaded, but nothing shows up in the password entry, nothing shows up in the password history, nothing shows up in the log_items table, and there are no additional files in the upload or files directories. Is there a way of tracking down what might be preventing the files from actually uploading? I am using version 2.1.23.

**Comment by nilsteampassnet** [comment]
Have you check the apache log errors file. 
I'm pretty sure you will found some error messages. 
Can you provide the ones corresponding to the upload? 
You may also use Firebug to detect any javascript error. 
Please provide data.
