### ISSUE TITLE
Teampass QR-Code for GoogleAuthenticator not working

### ISSUE THREAD

**Issue by Dirk23** [nilsteampassnet/TeamPass#1014]
I tried to set up a GoogleAuthenticator OTC for my Users. But everytime i scan the QR-Code wich comes as link in an Email GoggleAutheticator tells me:
Invalid Barcode
![image1](https://cloud.githubusercontent.com/assets/4200682/8718792/54a9247e-2ba7-11e5-8f38-f4cdbb978150.JPG)
Is there something missconfigured by me, or is this an issue?

Regards

Dirk

**Comment by Dirk23** [comment]
I just realised, that other Users can use the Barcode perfectly. I guess there is an Issue with Google Authenticator and iOS9 Beta i use.

**Comment by Dirk23** [comment]
I now realised, that the issue also exists on iOS8.x, but it is no OS error. I found out that the "Name displayed Google Authenticator for Teampass" should not have a blank Space in the String. After removing the Spaces i managed to add the Account with the QR-Code in GoogleAuthenticator

**Comment by rodehoed** [comment]
FYI FreeOTP (app from Redhat) also cannot handle the QR code. It crashes :-)

**Comment by nilsteampassnet** [comment]
I need to check this space issue. 
The strange thing is that on my test server I have a space inside and works. 

Choose review is needed here.

**Comment by jeanorwin** [comment]
Hi Dirk,
we have the same problem in our company, it only occurs on iOS. You can however fix the problem quite easily, even though it takes some time: Scan the QR-Code with a normal QR-Code app and read out the text string. In the Google Authenticator App, you may add the information manually via the menu - this way, everything works fine.

Best regards
Michael
