### ISSUE TITLE
Teampass 2.1.23 errors out on startup

### ISSUE THREAD

**Issue by ufp32633** [nilsteampassnet/TeamPass#1019]
After not having updated teampass since version 2.1.9 (because I was happy with how it worked) I've decided to upgrade to 2.1.23. The upgrade went smooth. Unfortunately it refuses to startup.There are two errors:

Warning: require_once(/site/cpassman/includes/settings.php): failed to open stream: No such file or directory in /site/teampass/index.php on line 44

Fatal error: require_once(): Failed opening required '/site/cpassman/includes/settings.php' (include_path='.:/usr/share/php:/usr/share/pear') in /site/teampass/index.php on line 44

I notice that it apparently tries to find a file in '/site/cpassman/' while it should be '/site/teampass/'. I don't understand why it is doing this.

I did restart and removed all existing cookies and other related things.

Software: Apache 2.4, PHP 5.5.26, MySQL 5.5.44. Browser: Mozilla Firefox 39.

Further observations: sk.php contains no salt value.

**Comment by gyoza** [comment]
I bet there is a hardcoded path somewhere in the database. you should check that.

**Comment by ufp32633** [comment]
Thanks, that might be worth investigating. Do you have a suggestion where it could be?
The database contains a lot of different fields.

**Comment by gyoza** [comment]
Just dump the DB to a .sql file and grep/awk for the URL

**Comment by ufp32633** [comment]
You were totally correct. The table cpm_misc contains references to folders and a few were wrong. I noticed that all URL's are absolute URL's. Do you know if they're supposed to be absolute? I access teampass from both an internal IP address and an external IP address so I'm not particularly happy with absolute URL's. I notice that the internal address redirects to the external address because that one is defined in the database.

**Comment by gyoza** [comment]
Not really sure, but this is a common problem with most PHP/Apache type setups.
