### ISSUE TITLE
Can't add new passwords

### ISSUE THREAD

**Issue by firetiger86** [nilsteampassnet/TeamPass#1022]
Hello TeamPas community

If I want to add a new Password to my TeamPass I get the following error:
---------------------------------------------------------------------
"An error appears. Answer from Server cannot be parsed!
Returned data:
Error: 
Query: INSERT INTO `teampass_log_items` (`id_item`,`date`,`id_user`,`action`) VALUES (222, 1438700374, '3', 'at_creation')"

This message appears when I click on "Save password". In the database he only make one entry in the table  "teampass_items" 
---------------------------------------------------------------------

The Dialog is generated by this funktion: index.php?page=items
---------------------------------------------------------------------
function(data) {
                    //decrypt data
                    try {
                        data = prepareExchangedData(data , "decode", "3JZVu7GeWvGagkXL9QWtLfThaaUdVuvu4mzTGpPc3e6DaJJVoa");
                    } catch (e) {
                        // error
                        $("#div_loading").hide();
                        $("#request_ongoing").val("");
                        $("#div_dialog_message_text").html("An error appears. Answer from Server cannot be parsed!<br />Returned data:<br />"+data);
                        $("#div_dialog_message").dialog("open");

                        return;
                    }
---------------------------------------------------------------------
I use version 2.1.22

Thank you for your help

**Comment by rverchere** [comment]
A column in the mysql table `teampass_items` is missing.

You have to create manually the column `pw_iv`.

**Comment by iddqd2** [comment]
Same problem on fresh 2.1.23 version.
Why that column is missing and what type should it be?

**Comment by nilsteampassnet** [comment]
Yep I confirm.

I don't know what happened during my last merge to master, but some files were not updated.
(New 2.1.23 release)[https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.23.2] was created

**Comment by iddqd2** [comment]
Works for me)

**Comment by matthebu** [comment]
I have the same encryption error and i was missing the column as well.  Have tried to reload many different times with different variables.

**Comment by firetiger86** [comment]
I've updated to Version 2.1.24 and now it works fine. 
Thank you very much :-)
