### ISSUE TITLE
Upgrade from old version (cPassMan 2.00b3) to Teampass 2.1.22

### ISSUE THREAD

**Issue by jaimemunera** [nilsteampassnet/TeamPass#1023]
I've got stuck in the Salt Key step where is asking me to enter the Absolute Path to store the SK.php file, by default that field loads up "/includes". When I enter the path it says "Please wait" and stays there. I've check the error logs and the error states "PHP Notice:  Undefined variable: abs_path in /var/www/password/install/upgrade.php on line 427, referer: http://localhost/password/install/upgrade.php"

Can you please advice?

Thanks

**Comment by Mitchou** [comment]
Got it too !

**Comment by techdarko** [comment]
Same issue. Updating from 2.1.9 to 2.1.23
