### ISSUE TITLE
2.1.22 - Unable to create new folder in Personal tree

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1024]
I just noticed that after upgrading to 2.1.22 that I can view items and to personal folders but unable to add new folder under personal items tree. The new folder button is disabled from clicking. I also cannot add items. The save button is disabled. I just realized that there is another issue similar to this. I will try that fix.

**Comment by hexxamillion** [comment]
I was able to get new item added by following suggestion from #875. I enabled in admin settings "Allow items with similar label in a common folder", which is weird. Who would know or expect to have to do that? 

I still cannot add new folder in personal tree. The add new folder button is disabled from clicking.

**Comment by hexxamillion** [comment]
It seems that although I was able to add a personal item now I cannot delete it. The dialog appears to allow deleting but after the page refreshes the item is still there.

**Comment by nilsteampassnet** [comment]
Creating sub-folder in the personal one is not implemented.
It was in a very old version but it has been removed since a while.
This had a lot of impacts so it was removed.

Could be added as a Request for the future

**Comment by hexxamillion** [comment]
This is a shame because we have been using the feature with no problems. It is great for organizing/categorizing your personal items rather than just having a single long list. This would be great to have added back. Thanks!

**Comment by hexxamillion** [comment]
Is there a chance this gets added for 2.1.23?

**Comment by hexxamillion** [comment]
I just noticed that 2.1.24 is upcoming..soo is there a chance this can be added to 2.1.24 especially since some changes have been made around salt key and personal items?

**Comment by nilsteampassnet** [comment]
​T​his one is not simple (I think).
I will add it for 2.1.25 (I promise)

**Comment by hexxamillion** [comment]
Super.

**Comment by hexxamillion** [comment]
Was this feature added back in 2.1.25?
