### ISSUE TITLE
www.teampass.net "Account Suspended"

### ISSUE THREAD

**Issue by miroslavkokrda** [nilsteampassnet/TeamPass#1028]
"This Account Has Been Suspended" is only text visible on webpage :(

**Comment by skynet** [comment]
:(

**Comment by hexxamillion** [comment]
Wow.

**Comment by gyoza** [comment]
:( I hope nils is ok!

**Comment by hexxamillion** [comment]
Looks like the site is back up. That's good news.

**Comment by nilsteampassnet** [comment]
Yes I'm still here, but on holidays ... and forgot to pay the domain :-(

**Comment by skynet** [comment]
:8ball:
