### ISSUE TITLE
ETA on 2.1.23 release? Would like to implement all the LDAP changes.

### ISSUE THREAD

**Issue by gyoza** [nilsteampassnet/TeamPass#1029]
I tried to upgrade based off the branch but the upgrade_ajax.php just sat and spins.

Attempted an upgrade from 2.1.22 to 2.1.23.. 

Thanks for all your hard work on this! Also, I just donated to your project as I've been using it for such a long time I think it is only right to do so!

**Comment by Masejoer** [comment]
2.1.23 was released in January?

We upgraded from 2.1.16 to 2.1.23 without a problem.

http://teampass.net/installation/release-2.1.23.html
