### ISSUE TITLE
404 error at http://teampass.net/about.html

### ISSUE THREAD

**Issue by MagicFab** [nilsteampassnet/TeamPass#1030]
At http://teampass.net/about.html there is mention of "It has been entirely developed by Nils Laumaillé ..." which links to http://teampass.net/nils@teampass.net - this link then throws a 404 - Not found error.

**Comment by miroslavkokrda** [comment]
http://teampass.net is completely unavailable


404
There isn't a GitHub Pages site here.
If you're trying to publish one, read the full documentation to learn how to set up

**Comment by MagicFab** [comment]
Teampass.net works for me at the moment, there was a hosting issue a couple of weeks ago which is now solved. Perhaps reload/clean your cache, etc. and check with http://www.downforeveryoneorjustme.com/

**Comment by BcTpe4HbIu** [comment]
Also 404 here ![screenshot](http://i.imgur.com/HUaPAPz.png)

**Comment by MagicFab** [comment]
Strange, now I do get the same error as you. It was fine when I commented above.

**Comment by nilsteampassnet** [comment]
​Website is currently being moved to github jekyll.
A redirection of the teampass.net domain is also on going.

The propagation of the dns changes should now be done.

I still have to adapt some url to fit the domain, and I think the complete
website will be back in a couple of days​.

**Comment by MagicFab** [comment]
The site is back, thanks for the explanation @nilsteampassnet
