### ISSUE TITLE
api add item wrong query

### ISSUE THREAD

**Issue by ZUNbado** [nilsteampassnet/TeamPass#1031]
Hello, i'm testing API, but i found some errors:

1st
In api/functions.php i see this line (482):
                                    "inactif" => $item_login,
This like a typo, is needed to change to
                                    "login" => $item_login,

2n
When i execute query i get this error, but item is saved
add/item/Admin;passwd;Admin;1084;Admin;;;tag1 tag2;1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '
              label='INSERT INTO `teampass_keys` (`table`,`id`,`rand_key`) VALU' at line 3<br>
Query: INSERT INTO `teampass_keys` (`table`,`id`,`rand_key`) VALUES ('items', 416, '65c916e7bfe1038')<br>

thanks

**Comment by chnusti** [comment]
I am not successful at all to add an item.

could you please be so kind to show me what complete url you have called to successful add an item?
