### ISSUE TITLE
Teampass 2.1.23 - LDAP option not recognized

### ISSUE THREAD

**Issue by sandman42** [nilsteampassnet/TeamPass#1034]
Hi,

I've set up teampass from scratch. It works fine with mysql autentication.

I have set up LDAP authentication againt an AD but if I set in the LDAP options:

Enable users authentification through LDAP server YES
Teampass local users only NO

When I try to log in with an AD user/password, I get an error that says

MYSQL Error

user_not_exists

So it seams it tries to authenticate against mysql anyway.

I've tried to use these three syntaxes:

user
user@domain
domain\user

But the result is the same: no way.

How can I solve it?

Thanks and ciao

**Comment by hexxamillion** [comment]
Did you set the LDAP configuration under Settings -> LDAP Options?
I also had to modify the file \includes\libraries\LDAP\adLDAP\adLDAP.php to work with our ldap config as well. It works for me.

Config these under Settings -> LDAP Options
LDAP account suffix for your domain  
LDAP base dn for your domain  
LDAP array of domain controllers
