### ISSUE TITLE
2.1.23 - Stuck on loading data..please wait and missing some navigation buttons

### ISSUE THREAD

**Issue by d1df9** [nilsteampassnet/TeamPass#1036]
![2015-09-01 11_07_27-collaborative passwords manager](https://cloud.githubusercontent.com/assets/14079193/9612545/17723672-509b-11e5-8450-2b27e74fd9f5.png)

I am seeing this "Loading data ... please wait" message that never seems to progress anywhere, and from other screen shots I've seen, I'm missing some buttons from the navigation.

I am running TeamPass on Ubuntu server 14.04.3 (64bit) and I do not see any errors in apache2 or mysql. I am able to add folders and add users without error. But I don't see any option to start adding passwords to these folders.

Thank you!

**Comment by hexxamillion** [comment]
Are you behind a proxy or anything? It's just trying to load the Teampass info. There is an option under settings to disable that. That's what I do.

**Comment by d1df9** [comment]
I am behind a firewall which will probably explain why I can't load that data. I have tried disabling it, but the main issue is that I am unable to add entries to the folders I create.

**Comment by nilsteampassnet** [comment]
​You need to click on the Hammer icon.

Does this work?​

**Comment by d1df9** [comment]
Yes, I can click the hammer icon and I am able to get in.

**Comment by hexxamillion** [comment]
Admin does not have access to passwords. You need to create a user account and assign a role and folder. That user account can add passwords.

**Comment by d1df9** [comment]
Got it! Thank you.
