### ISSUE TITLE
IE 11 Buggs

### ISSUE THREAD

**Issue by 607452189** [nilsteampassnet/TeamPass#1039]
hi i installed version 2.1.23 and have problem with IE11 the hole interface is bugi. What i can do to fix this?

**Comment by 607452189** [comment]
![ie11](https://cloud.githubusercontent.com/assets/13537944/9755146/d0c3a13a-56cf-11e5-83aa-dca42705437f.JPG)

**Comment by hexxamillion** [comment]
I have IE11 and it works fine for me. Try disabling Compatibility Mode.

**Comment by 607452189** [comment]
thx now it´s working :)

**Comment by hexxamillion** [comment]
Cool! Dog gone IE.
