### ISSUE TITLE
Upgrade from 2.1.7 to 2.1.22 Release - cannot login

### ISSUE THREAD

**Issue by miroslavkokrda** [nilsteampassnet/TeamPass#1040]
Hi,
I have one old instance of teampass and new separated server for actual version.

Downloaded TeamPass-Release_2.1.22.zip, unpacked, renamed to teampass in /var/www.
Dumped actual db teampass2 on old server, created new database teampass2 on new server, and imported sql backup to this DB.
Copied old includes/settings.php to new location and do "chown -R www-data:www-data teampass".
After this, in browser I did step by step "teampass/install/upgrade.php" without any problem.
But I cannot login to new version of teampass as admin nor any other user.

I detected, that sk.php file is empty (without my SALT key), and fullfiled it, and added row contains "COST", so this file is:
<?php
@define('SALT', 'someSaltKey'); //Never Change it once it has been used !!!!!
@define('COST', '13'); // Don't change this.
?>

Reloaded apache2 service and I am still unable to login to teampass.
Server is running on Debian Linux 8.2, and I am using LDAP for user autentization.
No error messages anywhere ...

Any idea?

**Comment by nilsteampassnet** [comment]
Don't you have any apache errors in the log?

**Comment by miroslavkokrda** [comment]
I have in error.log these lines:
[Wed Sep 23 14:38:04.764579 2015] [authz_core:debug] [pid 25494] mod_authz_core.c(809): [client 192.168.23.108:41410] AH01626: authorization result of Require all granted: granted, referer: http://teampass.i.cz/teampass/
[Wed Sep 23 14:38:04.764689 2015] [authz_core:debug] [pid 25494] mod_authz_core.c(809): [client 192.168.23.108:41410] AH01626: authorization result of <RequireAny>: granted, referer: http://teampass.i.cz/teampass/
[Wed Sep 23 14:38:04.820976 2015] [deflate:debug] [pid 25494] mod_deflate.c(855): [client 192.168.23.108:41410] AH01384: Zlib: Compressed 75 to 67 : URL /teampass/sources/identify.php, referer: http://teampass.i.cz/teampass/

in access.log:
192.168.23.108 - - [23/Sep/2015:14:40:21 +0200] "POST /teampass/sources/identify.php HTTP/1.1" 200 473 "http://teampass.i.cz/teampass/" "Mozilla/5.0 (X11; Linux i686 on x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"

Nothing more ...

**Comment by nilsteampassnet** [comment]
Can you check errors with Firebug?

Check [THIS PAGE](http://teampass.net/2014-02-09-how-to-communicate-an-error-log/) if you don't know about it.

**Comment by miroslavkokrda** [comment]
Which tab and informations exactly? These?


### start console post
POST http://teampass.i.cz/teampass/sources/identify.php
	
200 OK
		65ms	
jquery-1.9.1.js (řádek 8526)
HlavičkyPostOdezvaHTMLCookies
Parametryapplication/x-www-form-urlencodedDo not sort
data	
rzEEVv////9R0dur6o1uQ9dRNblXDpS0ejYd9KU6WO3GRgsH207/yFjDCj5NdVAEqUAJDUsIs18ZSF9hOTt/j9vzyR3kRZOOlAj6CCDxhceF5jr38arxGejGQlTBcFXfd
/Kgq6Ja6c/L0BOjQaL+AsWo2LjIJn1d8kyfqpJ7QqvLa5GH/5kM0qA4Nk977quX374g8Xd2jA==
type	
identify_user
Zdroj
type=identify_user&data=rzEEVv%2F%2F%2F%2F9R0dur6o1uQ9dRNblXDpS0ejYd9KU6WO3GRgsH207%2FyFjDCj5NdVAEqUAJDUsIs18ZSF9hOTt
%2Fj9vzyR3kRZOOlAj6CCDxhceF5jr38arxGejGQlTBcFXfd%2FKgq6Ja6c%2FL0BOjQaL%2BAsWo2LjIJn1d8kyfqpJ7QqvLa5GH
%2F5kM0qA4Nk977quX374g8Xd2jA%3D%3D
### end console post

### start console reply
POST http://teampass.i.cz/teampass/sources/identify.php
	
200 OK
		65ms	
jquery-1.9.1.js (řádek 8526)
HlavičkyPostOdezvaHTMLCookies

[{"value" : "false", "user_admin":"", "initial_url" : "",
			"error" : ""}]
### end console reply

**Comment by nilsteampassnet** [comment]
Can you provide me an access? You can contact me nils@teampass.net

**Comment by miroslavkokrda** [comment]
I will prepare new instance, in which passwords in DB will be purged, or changed to non active passwords. I will contact you by mail ... thanks

**Comment by yssvic** [comment]
I have this same problem, can you tell me how you fixed this please? Thank you.
