### ISSUE TITLE
Feature Request - 2.1.23 - Pagination on Users Page

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1042]
I wanted to request to have pagination added to the users page. Could this be done? Maybe add an option in settings for the defined user count for pagination. This is mostly useful for admin since the admin will see all users. This is no good for 100's of users that are listed.

Can the pagination also include by alphabet? Such as [A-C] [D-F], etc? If not, just by page number dropdown is fine.

**Comment by toptnc** [comment]
+1

**Comment by nilsteampassnet** [comment]
Currently in progress.
