### ISSUE TITLE
Server connection is impossible ... check your Internet/firewall configuration

### ISSUE THREAD

**Issue by jbonatelli** [nilsteampassnet/TeamPass#1046]
Hi,

I have a new fresh install to this tool with version TeamPass 2.1.23
i´m install follow the steps on the website, besides, i have this messagem when i connect to an administrator

Server connection is impossible ... check your Internet/firewall configuration

Anyone have this issue ? and how to solve this ? and i don´t have the all buttons like the screenshot of the project site...

**Comment by jbonatelli** [comment]
Issue solved

**Comment by clearzale** [comment]
And then,How did u resolved it?I have the same problem.
