### ISSUE TITLE
How to Create Items in Dashboard

### ISSUE THREAD

**Issue by jbonatelli** [nilsteampassnet/TeamPass#1047]
guys,

I installed the latest version of TeamPass, but I can not see the buttons to insert the data I see in the screenshot of the site. It appears only the buttons that are in the image below, would like to have full access to the tool.

Installation - Linux Ubuntu Sever + Xampp

Help me

This is my Dashboard
![teampass](https://cloud.githubusercontent.com/assets/14629741/10020108/83f5c52a-6117-11e5-8431-0cfb1ec3fdac.png)

I attached a image with my dashboard. I like this tool, but this issue cause some trouble.

This is the Dashboard that i want
![capture1](https://cloud.githubusercontent.com/assets/14629741/10020206/03a937ac-6118-11e5-83d3-ed7aa6ca0b59.PNG)

![capture2](https://cloud.githubusercontent.com/assets/14629741/10020207/067ccc00-6118-11e5-8f25-78926488fb14.PNG)

So, what i need to do, to take this Menu and can be useful

**Comment by nilsteampassnet** [comment]
The home page doesn't exist anymore since 2.1.23.

You now have access to the different features either from the "items" page or from the user profile dialogbox.

**Comment by jbonatelli** [comment]
Yeah,

So, i can create the folders, and some roles for users, but, when i create a value inside the folder, i receive this message

An error appears. Answer from Server cannot be parsed!
Returned data:
Error: 
Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('Sulu', 'IPS Server', 'f07d637c067e3487c53cc91b87c01112', '8a5de2915fc0f6e1f7479351f114a9dd', 'root@localhost', 'http://172.16.16.10', '16', 'root', '0', '', '0', '1', '31')

Do you now why ?

**Comment by nilsteampassnet** [comment]
There was an error in 2.1.23 release.

I've regenerated it this afternoon. You should [download it](https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.23.2) and use this package.

**Comment by jbonatelli** [comment]
Don´t worry, 

so, can i unzip this package directly in htdocs ? or i need to make a fresh install ?

Thanks

**Comment by nilsteampassnet** [comment]
As you want.

If you overwrite the files and reuse same DB, then you need to perform the upgrade (<teampass url>/install/upgrade.php)

**Comment by jbonatelli** [comment]
Works !

Thank Nils...
