### ISSUE TITLE
Error encryption of the password! - Problem after installation

### ISSUE THREAD

**Issue by matthebu** [nilsteampassnet/TeamPass#1048]
I have installed TeamPass 2.1.23 using Internet Explorer (chrome install hung at first step).

I am able to create folders, create passwords, but once they have been created I cannot see the password due to this encryption error. The error is displayed to the right of each password in a red triangle.

Has anyone else encountered this problem??

**Comment by nilsteampassnet** [comment]
Yes it was a bug linked to the bad merge I've done when creating the 2.1.23 release.

I've created a new one, [you can download it](https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.23.4) and update.

Sorry for this mistake from me.
