### ISSUE TITLE
Can't save password

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#1049]
Hi 

I've just installed the newest version without any problems.
If I try to store a password it saves only 0-2 charactes, and I see a lot of messages in  the apache error log:

<code>
[Tue Sep 29 08:58:28.567463 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in /var/www/TeamPass/sources/main.functions.php on line 287, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.567565 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Warning:  CBC mode requires an IV or the IV is empty in /var/www/TeamPass/includes/libraries/phpcrypt/Mode.php on line 213, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.569741 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 0 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.569839 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 1 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.569919 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 2 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.569995 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 3 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570073 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 4 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570127 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 5 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570173 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 6 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570220 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 7 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570293 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 8 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570342 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 9 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570407 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 10 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570459 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 11 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570504 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 12 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570550 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 13 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570595 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 14 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.570640 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Notice:  Uninitialized string offset: 15 in /var/www/TeamPass/includes/libraries/phpcrypt/modes/CBC.php on line 143, referer: http://teampass.mtfcloud.ch/index.php?page=items
[Tue Sep 29 08:58:28.572163 2015] [:error] [pid 15630] [client 172.29.5.140:33474] PHP Warning:  Incorrect IV size. Supplied length: 2 bytes, Required: 16 bytes in /var/www/TeamPass/includes/libraries/phpcrypt/Mode.php on line 190, referer: http://teampass.mtfcloud.ch/index.php?page=item
</code>

**Comment by nilsteampassnet** [comment]
​Is crypt extension enabled on server?​
​Perhaps retry to upload all files.
Clear server cache.​
