### ISSUE TITLE
 Key verification for Query is not correct!

### ISSUE THREAD

**Issue by ariostea74** [nilsteampassnet/TeamPass#1051]
I Install the Version 2.1.23.1. Allready is ok, but when i want create a new Password i get this error message : 
Key verification for Query is not correct!.

What i make wrong ??

Thanks for the help

![2015-10-02 23_04_26-fotos](https://cloud.githubusercontent.com/assets/14946732/10257849/04701ff8-695a-11e5-8882-bda3e26b1786.png)

**Comment by nilsteampassnet** [comment]
In order to get a kind of return of experience in case other users are
having this issue, can you tell us how you get rid of the message?

Thank You​

**Comment by ariostea74** [comment]
Hi Nils, 

I was ashamed, the solution was simple.
Just here the tick remove. Thats All :-)

cheers

![2015-10-05 16_26_03-collaborative passwords manager](https://cloud.githubusercontent.com/assets/14946732/10283050/21f0bf4e-6b7e-11e5-96d8-dfe1c7576f0c.png)

**Comment by funkypenguin** [comment]
Just had the same problem, which will no doubt confuse my read-only users. Could I request a better error message?

**Comment by nilsteampassnet** [comment]
In next release, read only use will not have access to this dialog box. 
Instead a message will be prompted with "not allowed to do that".
