### ISSUE TITLE
Teampass - Windows Edge Compatibility

### ISSUE THREAD

**Issue by nextret** [nilsteampassnet/TeamPass#1052]
Hello,

Because the flash is increasingly used, I'd like to know the compatibility between Teampass and Edge browser. In our company we're using Teampass with Windows 8 but next year we'll upgrade to Windows 10.
Kind Regards

**Comment by nilsteampassnet** [comment]
This has no impact.
Currently I'm developping and performing some test on a Win10 computer
without any change versus Win8.
Indeed, Teampass doesn't rely on Windows but on the installed Apache server.

So for me this is not an issue, and you can safely continue to use Teampass
even when migrated to W10.

**Comment by nextret** [comment]
Thank you very much.
I asked because depends on which browser we use, some features didn't work fine. Since 2.1.23 version everthing goes well... for me.
Again, thank you. For me this issue is closed.
