### ISSUE TITLE
Once session timeout occurs, the next login attempt doesn't work.

### ISSUE THREAD

**Issue by supportNMS** [nilsteampassnet/TeamPass#1053]
Once session timeout occurs, the next login attempt doesn't work (identifications information login/password). The result is that the login start page is loading indefinitely.

We have to refresh the login start page, and authenticate again (enter his identifications information login/password), to solve the issue.

Here is my teampass version :
Linux : Ubuntu 14.04.3 LTS 
Mysql : Ver 14.14 Distrib 5.5.44
Apache : 2.4.7
Php : 5.5.9-1ubuntu4.11
Teampass : 2.1.23

**Comment by nilsteampassnet** [comment]
​I've tried on my test server, and could not reproduce.
Indeed after session is over, and new login page displayed, I can relog
without having to refresh the login page.

Could you check if an error occurs in the Apache error logs?​

**Comment by supportNMS** [comment]
Hi, 
Sorry, there is no log concerning this problem in the Apache2 error logs...
Once I've refresh the login page, then I can log, and then a log appears in the Apache2 error logs, see below if it can help...
-----------------------------------------------------------------------------------------------------------------------------
apache2[30137]: User logged in - 42 - 2015/10/05 14:47:37 10.85.46.32 (Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0)
------------------------------------------------------------------------------------------------------------------------------

To be very clear, the problem appears only when you try to reconnect after the deconnection for inactivity more 30 min. If you trie to reconnect before 30min it's working.
The "Session duration (minutes)" field is configure at 30 min, so to test, I have to connect, dont touch teampass for more than 60min and then try to reconnect.

**Comment by supportNMS** [comment]
I've put apache in debug log, and tried to find what the difference in the logs between a reconnection after 60min that don't work and another before 60min that work. Here is the differences (difference comes just after use of modul mod_authz_core.c) : 

[Thu Oct 08 10:26:08.325690 2015] [ssl:info] [pid 7813] [client X.X.X.X:3938] AH01964: Connection to child 4 established (server myteampass.domain.com:443)
[Thu Oct 08 10:26:08.325980 2015] [ssl:debug] [pid 7813] ssl_engine_kernel.c(1918): [client X.X.X.X:3938] AH02044: No matching SSL virtual host for servername myteampdnsname.otherdomain.com found (using default/first virtual host)
[Thu Oct 08 10:26:08.326984 2015] [ssl:debug] [pid 7813] ssl_engine_kernel.c(1844): [client X.X.X.X:3938] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Thu Oct 08 10:26:08.333002 2015] [ssl:debug] [pid 7813] ssl_engine_kernel.c(222): [client X.X.X.X:3938] AH02034: Initial (No.1) HTTPS request received for child 4 (server myteampass.domain.com:443), referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
[Thu Oct 08 10:26:08.333098 2015] [authz_core:debug] [pid 7813] mod_authz_core.c(802): [client 10.69.115.5 :3938] AH01626: authorization result of Require all granted: granted, referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
[Thu Oct 08 10:26:08.333111 2015] [authz_core:debug] [pid 7813] mod_authz_core.c(802): [client 10.69.115.5 :3938] AH01626: authorization result of <RequireAny>: granted, referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
------ Below the lines that appears when connection is ok ----------------------------------------------
apache2[7813]: User logged in - 42 - 2015/10/08 10:26:08 X.X.X.X (Mozilla/5.0 (Windows NT 5.2; rv:38.0) Gecko/20100101 Firefox/38.0)
[Thu Oct 08 10:26:08.719608 2015] [deflate:debug] [pid 7813] mod_deflate.c(849): [client X.X.X.X:3938] AH01384: Zlib: Compressed 119 to 112 : URL /teampass/sources/identify.php, referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
[Thu Oct 08 10:26:08.729930 2015] [ssl:debug] [pid 7813] ssl_engine_kernel.c(222): [client X.X.X.X:3938] AH02034: Subsequent (No.2) HTTPS request received for child 4 (server myteampass.domain.com:443), referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
[Thu Oct 08 10:26:08.730025 2015] [authz_core:debug] [pid 7813] mod_authz_core.c(802): [client 10.69.115.5 :3938] AH01626: authorization result of Require all granted: granted, referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true
[Thu Oct 08 10:26:08.730057 2015] [authz_core:debug] [pid 7813] mod_authz_core.c(802): [client 10.69.115.5 :3938] AH01626: authorization result of <RequireAny>: granted, referer: https://myteampdnsname.otherdomain.com/teampass/index.php?page=items&session_over=true


Do you have any ideas?

**Comment by nilsteampassnet** [comment]
​I finally perform the 60 minutes idle test.
But on my side, it was working, I could relog without reloading the page.

Unfortunately I have no idea on how to resolve this (even by reading your
logs). It seems to be related to https. For info, I do also use https on my
development and test configuration.

Can't there be a kind of cache session on the ssl virtual server?
