### ISSUE TITLE
"Error Encryption of the Password" while importing

### ISSUE THREAD

**Issue by prozit** [nilsteampassnet/TeamPass#1054]
Hi,

Thanks for the great tool!
On a fresh install of version 2.1.23, I want to import passwords in Teampass, but when I try to do so, I receive the error "error encryption of the password!".

I have seen another issues which was resolved, but I believe this might also still need to be resolved for the imports.

Kind regards,
Francis Claessens.

**Comment by nilsteampassnet** [comment]
​What kind of import do you perform (csv or keepass)?
Does this error appears when you try to see the password of an imported
item, or during the importation process?

But I discovered yesterday a bug in password encryption during import
process. I have commited yesterday a correction in "development" branch
(for 2.1.24 version).​

**Comment by prozit** [comment]
Hi Nils,

The error appears when I try to see the password of an item. The import I did was with an CSV file.
The items show an exclamation mark with the error as a tooltip attached to it.

Can I use the import.queries.php file from the 2.1.24 version to try it out in 2.1.23? Or won't that work?

Kind regards,
Francis.

**Comment by nilsteampassnet** [comment]
Yes I think it should work

**Comment by prozit** [comment]
I have tried copying the file from 2.1.24 but it doesn't work. Once I selected the CSV file, the dialog screen keeps spinning on "please wait!".

**Comment by frankenstein91** [comment]
I do not see the passwords after a keepass import, but username an titel is okay.

**Comment by nilsteampassnet** [comment]
Yes this was a bug. 
It is corrected in 2.1.24

**Comment by frankenstein91** [comment]
Have you a release date?

**Comment by nilsteampassnet** [comment]
​On my side, I still have a couple of tests to perform.
And I'm waiting for a feedabck of users that may have tested the
"pre-production" version.
Once done, I will release the package ... I think during next week.​
