### ISSUE TITLE
2.1.23.4 - Entry/Element in a personal folder wasn’t deleted after Action “Delete Element”

### ISSUE THREAD

**Issue by frankenstein91** [nilsteampassnet/TeamPass#1055]
The Entry/Element was still there after the command/Action “Delete Element” was performed, but the content from this entry/element was not viewable for the user (If you tried to open or view this entry/element, the message was “You don’t have the rights to view this element”). Only the administrator was able to delete the element in the database.

**Comment by nilsteampassnet** [comment]
I forgot to check this issue. 
I will and give you a feedback
