### ISSUE TITLE
feature request - Backup over API

### ISSUE THREAD

**Issue by frankenstein91** [nilsteampassnet/TeamPass#1056]
it is possible to make a backup over the API?
I would like to make backups with curl and cron.

Thank you in advice

**Comment by nilsteampassnet** [comment]
​In tab "backup" from settings page, you need to fill in the expected
fields for backup.
Then add an entry in your cron file by calling file
/backups/script.backup.php

**Comment by frankenstein91** [comment]
Okay after my installation from github no backup folder exists.
Am 08.10.2015 14:14 schrieb "Nils Laumaillé" <notifications@github.com>:

**Comment by nilsteampassnet** [comment]
​This is a terrible mistake from me.
It should not have been removed from repository.
I will add it.

In between, you can get this folder from a previous release as 2.1.22.​

**Comment by frankenstein91** [comment]
we did so.

**Comment by nilsteampassnet** [comment]
Did this close the point?

**Comment by frankenstein91** [comment]
yes, i think so.
But you should provide a .htaccess file to protect the backups.
