### ISSUE TITLE
Install: sanitizeString is not defined

### ISSUE THREAD

**Issue by Cryjack** [nilsteampassnet/TeamPass#1057]
Hanging at Step 4 (Preparation) of the installer with no errormessage. Can't get further.

Gives error (Firefox Debug):
ReferenceError: sanitizeString is not defined install.js:90:13

**Comment by nilsteampassnet** [comment]
... what version do you install?

​Have you tried to reupload the package (perhaps a file was not completly
uploaded on your server)?

**Comment by frankenstein91** [comment]
A list of installed plugins would certainly be helpful.
