### ISSUE TITLE
teampass api add item

### ISSUE THREAD

**Issue by chnusti** [nilsteampassnet/TeamPass#1058]
I just download the master from github and try to add items via the api function without success.

when I try to an item with:
curl http://<myserverurl>/api/index.php/add/item/testentry2342,abc123,test,1,root,,,servers,1?apikey=<myapikey>

what am I missing here?

I get:
{"err":"Item definition not complete"}

And when I try to read a manually added value thru web interface with "curl http://<myurl>/api/index.php/read/items/1?apikey=<myapikey>  I get:
ERROR: Badly formatted SQL query: Expected array, got scalar instead!<br>

Any help is appreciated.

**Comment by nilsteampassnet** [comment]
The first point is related an error in the usage instructions. You should use ; instead of, as a separator. I will update this. 
Concerning the second one, if it's clearly a bug that I will correct.

**Comment by chnusti** [comment]
Yeah, thanks for this hint! ( wrong in documentation )
Even though the item is added but password can't be read on the web interface.
I see on the database that password are inserted.
Do I need to configure the sk.php for the api? looks like wrong key for de-/entcryption...

**Comment by nilsteampassnet** [comment]
In order to have password correctly stored, you should download api/functions.php from Development branch. 
I just commited the correction.

**Comment by chnusti** [comment]
Yes, the function.php from developement tree is working well!

Thanks
