### ISSUE TITLE
This page doesn't exist

### ISSUE THREAD

**Issue by silvermoon18** [nilsteampassnet/TeamPass#1059]
When I login to TeamPass I get the message " This page doesn't exist" error on the main page. 

When I click the icons on top it automatically log me out and bring me back to login screen. 

Is this a bug?

I am using CentOS 7 with TeamPass version 2.1.23. 

My TeamPass is installed in our wiki server but in different directory of course.

![teampass](https://cloud.githubusercontent.com/assets/12426101/10454985/c8aebcf6-71b8-11e5-8532-8a10f7840bf0.JPG)

**Comment by nilsteampassnet** [comment]
Very strange. 
Can you try to re-upload all files? 

If it is a new installation, I recommend to use the "development" branch.

**Comment by silvermoon18** [comment]
I re-upload all files and it is now working like a charm.

Never seen that error before. 

Big thanks for the response.
