### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gleisonbaioco** [nilsteampassnet/TeamPass#1060]
Hi Nils,

First of all, I would like to congratulate TeamPass project.

I've followed the TeamPass improvements and I've appreciated all of them!

Regarding logging, do you have any plan in order to improve this feature?

kind regards, Gleison.

**Comment by nilsteampassnet** [comment]
In next release, I've added the next tracked events, "shown password" and "copied password". 

If you have specific events to be logged, please don't hesitate to share.
