### ISSUE TITLE
Can not import password from keepass xml

### ISSUE THREAD

**Issue by djzippo** [nilsteampassnet/TeamPass#1061]
Hello,
I exported data from keepass 2.28 in xml files , after this I imported in teampass 2.1.23 . The structure and the username are ok, but the password are empty.
I tried also to export from keepass 1.28 but had the same problem.
How can I solve it? Thank you.

**Comment by nilsteampassnet** [comment]
​This is a known bug in 2.1.23.
It is solved in 2.1.24 that is currently in pre-production.​

**Comment by niafrond** [comment]
I needed a hotfix without switching to preprod ....
So i added this after line 1116 of sources/import.queries.php 
    if(empty($pw)){
        $pw = decrypt($dataItem['pw']);
    }
