### ISSUE TITLE
hex2bin error (on php <5.4)

### ISSUE THREAD

**Issue by NicolasPaccaud** [nilsteampassnet/TeamPass#1062]
Hello

After upgrading to last release I have the following php error :
Call to undefined function hex2bin() in /path/to/teampass/sources/main.functions.php on line 286

hex2bin appeared on php 5.4, I'm running on a php 5.3, so there's a problem.
The installer/upgrader checked the requirements against php 5.3, not 5.4

I've seen that the phpcrypt lib has a kind of wrapper for php < 5.4, maybe the solution ?

Thanks

**Comment by nilsteampassnet** [comment]
I have no real suggestion for this.
hex2bin is used for encryption/decryption of passwords.

I've added a check in isntall / upgrade process.
