### ISSUE TITLE
Forgot password in CentOS 7 teampass ver. 2.1.23 not working

### ISSUE THREAD

**Issue by silvermoon18** [nilsteampassnet/TeamPass#1063]
Hello, 

i have fresh install of teampass in my mediawiki server. 

Everything is working properly except from "Forgot Password" on the login page. 

When I click "Forgot Password" nothing is happening. No pop-up window. Not doing anything at all.

Tried several browser but with no go.

It seems that the javascript is broken. 

I tried to check it in Developers view I get this message "Error: cannot call methods on dialog prior to initialization; attempted to call method 'open' "

**Comment by nilsteampassnet** [comment]
​This bug has been corrected​ in 2.1.24.

Thanks for reporting

**Comment by silvermoon18** [comment]
Hi nil, 

Wat is the link to download the 2.1.24 update?

**Comment by nilsteampassnet** [comment]
​You need to download the package from the branch "development"​
