### ISSUE TITLE
Installed but cannot manage or see passwords

### ISSUE THREAD

**Issue by glippi** [nilsteampassnet/TeamPass#1065]
It keeps asking for creating salt key
passwords created in personal folder do not show in menu, but it shows there is from tree.
passwords complexity not met error multiple occasions

Passwords created in folder are not viewable (do not open)

I must have done something wrong with setting correct rights somewhere.
Let me know what you need to help me with the issue! :)

**Comment by glippi** [comment]
Here you can see that the loading gear stays on trying to open password
![error](https://cloud.githubusercontent.com/assets/15252823/10674051/36f09e90-78f9-11e5-9b09-1c628ec5fab8.PNG)

here you can see there is a personal password created to manage but not visible
![error2](https://cloud.githubusercontent.com/assets/15252823/10674050/36ecb276-78f9-11e5-934f-577ffff33bce.PNG)

**Comment by glippi** [comment]
The never disappearing screen from password viewer/find 
![error3](https://cloud.githubusercontent.com/assets/15252823/10674273/59826988-78fa-11e5-95d2-41199f2ad1b1.PNG)

**Comment by nilsteampassnet** [comment]
What version do you use?
​Can you provide the answers from server by using Firebug?​

If it is a new installation, I recommend to use version 2.1.24 that is
currently on test phase (and soon released). It can be downloaded from
branch "development"

**Comment by glippi** [comment]
Hi,

Thank you for the response, I have abandoned that installation for now and have a new one on CentOS.

What I am currently experiencing is minor, but I cannot find where to set it and that is the password complexity setting for personal folders, I cannot create any passwords now, since the complexity is not set and I cannot find for the life of me where to do it
![error_tp](https://cloud.githubusercontent.com/assets/15252823/10688531/38b03340-7975-11e5-804a-5327db4319cd.PNG)

**Comment by nilsteampassnet** [comment]
​In Personnal folder, there is no minimum complexity level defined for
passwords.
So that means that you can create your Item with the complexity level for
your password you want, there is no restriction​.

So just write the password you want and click "save"

**Comment by glippi** [comment]
Well, after you said it it is not giving that error anymore and it is accepting  to enter passwords in the personal folder, but now it does not show the keys and keeps telling to add personal salt key.

Anything would be appreciated  :)

Here we can see 1 pass on my personal folder and the salkey message still there instead of the password:
![error_tp2](https://cloud.githubusercontent.com/assets/15252823/10694069/715c5a62-799c-11e5-8f29-4c5253551f24.PNG)

Here you can see it in find
![error_tp3](https://cloud.githubusercontent.com/assets/15252823/10694131/bee386e8-799c-11e5-9743-c56710afe9bf.PNG)

**Comment by glippi** [comment]
by setting the salt key from login and store in cookie I have solved that part.

Now it seems the deletion of a created key does not delete the key and makes it..... in limbo

Here you see 1 personal pass still mentioned where test is deleted, but it is there..... :)
![error_remove](https://cloud.githubusercontent.com/assets/15252823/10694513/de3b7fb2-799e-11e5-8cff-5dec9dba85c7.PNG)

**Comment by nilsteampassnet** [comment]
​It seems that this issue is not more existing in 2.1.24 version
("development" branch).
I've several deletion of personal items and they are clearly removed from
the list of items​.

**Comment by glippi** [comment]
currently I am running 2.1.23, so you advice me to upgrade it to the new version? Can I just replace the files in the current directory? How do you advice to upgrade or is there a link for it? :) I go google after I have asked it :p

**Comment by peppeska** [comment]
I have the same problem with 2.1.23

**Comment by peppeska** [comment]
whit 2.1.24 all is ok!

**Comment by glippi** [comment]
I tried to do the upgrade according to the manual and installed phpmyadmin as required and stuff, not passing step 1
