### ISSUE TITLE
Suggestion feature not working

### ISSUE THREAD

**Issue by funkypenguin** [nilsteampassnet/TeamPass#1067]
Hey :)

In 2.1.23, I haven't been able to get the "suggestion" feature to work. I enabled it, and my read-only users are able to submit suggestions but:

1.) Nobody is notified of the suggestion (is this expected?)
2.) A manager / admin logs in and tries to approve the suggestion. They get the message "You have decided to add this Suggestion to the Items list ... please confirm.", but when they click "Add", there is no result. The dialogue box does not disappear, and the item is not added.

Thanks!
D

**Comment by nilsteampassnet** [comment]
​In 2.1.24 (branch "development"), I've added a notification sent by email
to the Managers.

I've also tested the "validate suggestion"​ and it works (I previously
performed some changes on it so maybe I corrected this bug you are facing
in 2.1.23)

Thanks for the notification idea!
