### ISSUE TITLE
Cannot copy passwords or logins to clipboard Safari 9

### ISSUE THREAD

**Issue by Spikeophant** [nilsteampassnet/TeamPass#1070]
This worked fine in Safari 8, after updating my browser this no longer works, it makes it difficult to use TeamPass for our team.

**Comment by nilsteampassnet** [comment]
Can you please give a try to 2.1.24 as copy to clipboard now uses HTML5 possibilities.

**Comment by Spikeophant** [comment]
Yep 2.1.24 fixed my issues, sorry for the extremely late response, I didn't realize this was still open.
