### ISSUE TITLE
New AD user can see all passwords first login time

### ISSUE THREAD

**Issue by thesNu** [nilsteampassnet/TeamPass#1071]
1) There are some passwords in some folders. 
2) As admin I deleted user  'test' (user in LDAP/AD) from TeamPass. 
3) Then, first time login 'test' user can see all folders with passwords. 
4) After logoff or reload page, everything is OK, user 'test' can see only personal folder. 

 TeamPass 2.1.23 (clean install)
To reproduce: **Enable Personal folder** feature must be **On**

**Comment by thesNu** [comment]
To reproduce: **Enable Personal folder** feature must be **On**

**Comment by KDennisOD** [comment]
Same here.
Without Personal folder all is ok.

**Comment by juanfalguera** [comment]
I've got the same issue here with version 2.1.23. This is a very serious security issue and we should alert everyone.

**Comment by thesNu** [comment]
How to do this?

**Comment by nilsteampassnet** [comment]
Please look at #1153

**Comment by chetanpachare** [comment]
Finally, I have reached to the problem.
This problem can be solved by setting the option "Enable Personal folder feature= No " in team pass setting page.

Then try to login via LDAP users. You will not see any exiting folders.

Thanks.
