### ISSUE TITLE
User can create folder on root without permission - Teampass 2.1.23.4 

### ISSUE THREAD

**Issue by Ricardo-Custodio** [nilsteampassnet/TeamPass#1073]
With option: "Authorize new folder to be created at Root level = NO" any user can create a folder a folder on root by doing:
![screen shot 2015-11-03 at 16 04 43](https://cloud.githubusercontent.com/assets/12646960/10913428/c3e7f6a4-8245-11e5-942e-5f3358b2a462.png)
1 - click on "Add a Folder" anywhere you have access (Ex: test_1) (Dependent on: has 1 folder selected)
  1.1 - Name it and Save (ex: test_2)
2 - Remove the previous created folder (ex: test_2)
3 - Click on "Add a Folder" again
  3.1 - now "Dependent on:" has no folder selected (do not select anything)
  3.2 - Name the new folder and Save it (ex: test_on_root)
![screen shot 2015-11-03 at 16 03 21](https://cloud.githubusercontent.com/assets/12646960/10913437/cf88f2c4-8245-11e5-8d89-50f424ebab10.png)
4 - Now is created on root without permission
![screen shot 2015-11-03 at 16 04 09](https://cloud.githubusercontent.com/assets/12646960/10913446/d6135a62-8245-11e5-825d-9503d0673e13.png)
![folder](https://cloud.githubusercontent.com/assets/12646960/10913451/d9c436f4-8245-11e5-950c-075ea7bd05f9.png)

**Comment by nilsteampassnet** [comment]
Absolutely ... it is corrected in 2.1.24
