### ISSUE TITLE
Read only user can create folders + wipe out all items on remove folder - Teampass 2.1.23.4

### ISSUE THREAD

**Issue by Ricardo-Custodio** [nilsteampassnet/TeamPass#1074]
1 - A readonly user can create folder;
![screen shot 2015-11-03 at 16 43 21](https://cloud.githubusercontent.com/assets/12646960/10914488/9ad8466a-824a-11e5-8d55-5839323c43d8.png) 
![screen shot 2015-11-03 at 16 38 48](https://cloud.githubusercontent.com/assets/12646960/10914493/a1e1edbc-824a-11e5-818b-dec46701c5ba.png)
![screen shot 2015-11-03 at 16 42 39](https://cloud.githubusercontent.com/assets/12646960/10914500/a73a48a4-824a-11e5-83b2-0751d335568e.png)

2- Removing folders is also possible, and all the items on teampass disappear, not only for this user but for everyone.
So, after removing the folder, teampass items are wiped out and the below message apears.
![screen shot 2015-11-03 at 16 39 26](https://cloud.githubusercontent.com/assets/12646960/10914602/1c28b236-824b-11e5-805a-a07f66a05cc7.png)

**Comment by nilsteampassnet** [comment]
Absolutely ... it is corrected in 2.1.24
