### ISSUE TITLE
Administrator usage type changed...still can't access items page

### ISSUE THREAD

**Issue by yavuzaydin** [nilsteampassnet/TeamPass#1075]
Using latest git development version: I have changed administrator usage type as per the instructions on http://teampass.net/2014-04-19-change-administrator-usage/

I still can't access the items page as seen on the following screenshot:
![screenshot16](https://cloud.githubusercontent.com/assets/13795916/10935012/817aec60-82e3-11e5-84a5-fcbf95480a2e.png)

**Comment by nilsteampassnet** [comment]
​Can you clear the cache of your webbrowser?

And retry.​

**Comment by yavuzaydin** [comment]
Just tried in Private mode and in a different browser, still no go.

**Comment by nilsteampassnet** [comment]
​Confirmed.

I need to investigate.​

**Comment by yavuzaydin** [comment]
Great, works perfectly fine! Thank you.

**Comment by nilsteampassnet** [comment]
Great
