### ISSUE TITLE
Send events to syslog

### ISSUE THREAD

**Issue by nunompad** [nilsteampassnet/TeamPass#1078]
Hi there, can you add a feature to send logged events to syslog, this will be a major help in the tracking of the actions on the application.

Tks,

Nuno.

**Comment by frankenstein91** [comment]
i think it's a nice idea. Maybe someone can make a config for fail2ban

**Comment by nunompad** [comment]
Working on this.

**Comment by frankenstein91** [comment]
Is there a log of failed login attempts?
Am 23.12.2015 14:06 schrieb "nunompad" <notifications@github.com>:
