### ISSUE TITLE
Collab Request - Twitter Bootstrap Design

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1080]
I have been tinkering a bit on development with trying to convert the design to use bootstrap. If teampass could be designed to be html5 responsive then that would enhance for mobile. I am interested in collaborating to work on this. There is a bit of a challenge do to so much code.

**Comment by nilsteampassnet** [comment]
​This is the plan for 2.2

For this I would like to be able to "finalize" 2.1.X with major bug fix and
then move on 2.2 which should be "iso-features" but with bootstrap
implementation.
This to permit multi-supports usage​.

I will come back to you when I get a first idea of the product architecture.

**Comment by hexxamillion** [comment]
Super!!

**Comment by hexxamillion** [comment]
Cool because with bootstrap you can make mobile responsive without the need to require a mobile app. All my sites are using bootstrap now.

**Comment by drewlsvern** [comment]
Any updates on 2.2 with boostrap?

**Comment by alebupal** [comment]
Some news?

**Comment by nilsteampassnet** [comment]
No progress on this branch.
It will be a big work that I haven't initiated yet.
