### ISSUE TITLE
Users now unable to login

### ISSUE THREAD

**Issue by darren-harrison** [nilsteampassnet/TeamPass#1081]
Hi,
I installed and setup TeamPass fine, and it was just starting to be used by our company, and then without any changes to TeamPass, suddenly no users can login.
I can still login as the admin user, but I can't login as myself and other users can't login. As the admin user, changing their password doesn't seem to do anything, and using the "Forgot your password?" never seems to send email (sits with the 'Knight Rider progress bar' running for at least several minutes). The admin email test does work.
As I mentioned I haven't done an update to TeamPass, but I have done system updates as previous.

The install is on Debian (OpenMediaVault), running Nginx, although as I mentioned it had worked fine previously, for one or two weeks. TeamPass is version 2.1.23.

Thanks for any suggestions or help,
Darren.

**Comment by nilsteampassnet** [comment]
This seems to be more related to an incompatibility with some Apache extensions.
If it was working previously and that suddenly TP doesn't work for any user then something happens on the server. Now we need to identify what?

Can you get the error logs from Apache?
While loggin into TP, get the answer from the server with Firebug. See instructions [HERE](http://teampass.net/2014-02-09-how-to-communicate-an-error-log/). And post this answer here.

TP requires PHP 5.4 at least.

**Comment by darren-harrison** [comment]
Hi,
Thanks very much, I appreciate a response.
I checked the Nginx logs and there are no errors in the logs, the access logs are as I would expect, and nothing useful in the php log.
With firebug it firstly showed my certificates weren't quite set up right, but I fixed that and it was still operating the same.
The console response from the forgot my password feature shows:
```
    <div style="width:800px;margin:auto;">
        <div class="ui-state-error ui-corner-all error" >You are not allowed to see this page.</div>

</div>
```
and the headers
```
https://<server>/teampass/sources/main.queries.php?email=darren.harrison%40<company-domain>&login=darren.harrison&type=send_pw_by_email
```
For a normal login (where everyone except the admin user gets "Bad password for this account!", I get the following.
```
[{"value" : "false", "user_admin":"", "initial_url" : "index.php?page=items",
            "error" : ""}]
```
Headers:
```
https://<server>/teampass/sources/identify.php?data=zP1IVq2tra1ct0gWFUriHT5BKdAhTHCe96pw%2FDJzMVfvMBFRr1RF7OSgTFtp4DUTKx%2FZ5PyMk0B2L4VqlUn7gi8%2BnpdkUuWXu9nhdSPUeurIM2LfBag%2Fw4q4E0uZl9hG2nX3aEr%2FHMChYxz%2B1SlOA9jb39eiiBCAXMyec0bQJzhwdpUihIS12OihOr0kOTMMLVbGze2K%2FDdZ2%2FMBtAHcPiseUYO9G6U5zpyPhis%3D&type=identify_user
```

Again, thanks for your help, I hope this points to something.

Darren.

**Comment by darren-harrison** [comment]
As a software developer I struggle to write this but I have no idea how it happened (it's got to be the user right?), however the LDAP setting had been turned on which effectively blocked anyone except the admin user from logging in.
I switched that off and it's all working fine.
