### ISSUE TITLE
The 2.0 to 2.1.7 upgrade didn't update the database schema properly

### ISSUE THREAD

**Issue by Nathariel** [nilsteampassnet/TeamPass#109]
Hey guys, 

After upgrading to 2.1.7 I was left with inconsistent db schema. The upgrade process went smooth without any errors but the following columns were missing in the end: users/user_language, roles_title/complexity. I had to manually add them because I had problems adding groups. 

Regards, 
Boyan

**Comment by vmindru** [comment]
@nilsteampassnet  why do we keep issues open?  shouldn't we close them?
