### ISSUE TITLE
Export from Passwords

### ISSUE THREAD

**Issue by Arne-Hee6v** [nilsteampassnet/TeamPass#1090]
Hi @nilsteampassnet !

 I am testing Teampass 2.1.24-development. I found two issues with the export from Passwords.

**1) Offline-Mode**
The Offline-Mode does not work. It stops right after it is started throwing a HTTP 500 Error in the Apache access-Log.

AAA.BBB.CCC.DDD - - [17/Nov/2015:09:24:25 +0100] "POST /teampass/sources/export.queries.php HTTP/1.1" 500 358 "http://EEEEEEEEEE.de.local/teampass/index.php?page=items&session_over=true" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

**2) Export as PDF**

I have three Folders for Passwords. Folder A contains Folder B and C. All three Folder contains two Password. If I select all Folders (excluding the root) the generated PDF contains always the Passwords from Folder A and Folder B, but never the Passwords from Folder C.

Even if I select Folder B and C, the PDF contains only Passwords from Folder B, but not from Folder C.
Or if I select Folder A and C, the PDF contains only the Passwords from Folder A, but again not from Folder C.

If only Folder C is selected, I am able to export the Passwords.

The export as CSV works as desired.

Best regards

Arne

**Comment by fpaquet** [comment]
The 500 comes from two typo's in the file sources/export.queries.php
When using a Linux system, path is case-sensitive, thus

/includes/libraries/encryption/GibberishAES/GibberishAES.php
should be
/includes/libraries/Encryption/GibberishAES/GibberishAES.php

souces/export.queries.php, lines 320 and 425


diff --git a/sources/export.queries.php b/sources/export.queries.php
index 18943bf..280fb31 100644
--- a/sources/export.queries.php
+++ b/sources/export.queries.php
@@ -317,7 +317,7 @@ switch ($_POST['type']) {
         // - prepare export file
         // - get full list of objects id to export
         include $_SESSION['settings']['cpassman_dir'].'/includes/include.php';
-        require_once $_SESSION['settings']['cpassman_dir'].'/includes/libraries/encryption/GibberishAES/GibberishAES.php';
+        require_once $_SESSION['settings']['cpassman_dir'].'/includes/libraries/Encryption/GibberishAES/GibberishAES.php';
         $idsList = array();
         $objNumber = 0;
 
@@ -422,7 +422,7 @@ Enter the decryption key : <input type="password" id="saltkey" />
 
         $full_listing = array();
         include $_SESSION['settings']['cpassman_dir'].'/includes/include.php';
-        require_once $_SESSION['settings']['cpassman_dir'].'/includes/libraries/encryption/GibberishAES/GibberishAES.php';
+        require_once $_SESSION['settings']['cpassman_dir'].'/includes/libraries/Encryption/GibberishAES/GibberishAES.php';
 
         $rows = DB::query(
             "SELECT i.id as id, i.url as url, i.perso as perso, i.label as label, i.description as description, i.pw as pw, i.login as lo(END)

**Comment by fpaquet** [comment]
Private items cannot be decrypted from exported html file (due to missing private SALTKEY).
Public items are working fine.

**Comment by Arne-Hee6v** [comment]
Thanks! It works like a charm.


Best regards

Arne Hofmann
