### ISSUE TITLE
Upgrade to 2.1.24 stuck at Step 1

### ISSUE THREAD

**Issue by Lovecannon** [nilsteampassnet/TeamPass#1092]
Trying to upgrade to 2.1.24 but the upgrade process gets stuck at Step 1 and just displays the loading bar indefinitely. Anyone know how to fix this?

**Comment by nilsteampassnet** [comment]
Please check the Apache errors.

You may also communicate answer from server using Firebug (see [PAGE](http://teampass.net/2014-02-09-how-to-communicate-an-error-log/))

**Comment by Lovecannon** [comment]
I use nginx, but I checked the error logs and there are no errors being triggered.

**Comment by nilsteampassnet** [comment]
​This is not really possible, or perhaps the level of log is too high and
in this case it will not really help us solving your problem.
Can you please install firebug and copy here the content of the tab
"response".

**Comment by Lovecannon** [comment]
Well I figured out what it is. I followed your upgrade documentation at http://teampass.net/2014-06-28-upgrade/ and it doesn't mention anything about doing anything with sk.php. I saw some errors in Nginx about sk.php being missing but those errors weren't being thrown during the upgrade process. I copied the sk.php file from my old install and put it in the new one and it worked.

**Comment by nilsteampassnet** [comment]
Correct.
I will update the page.
