### ISSUE TITLE
After upgrading to 2.1.24 Items menu stuck at 'Loading'

### ISSUE THREAD

**Issue by Lovecannon** [nilsteampassnet/TeamPass#1093]
I managed to get my install to upgrade, but now the Items menu is stuck at "Loading..." and does not complete. I checked with Firebug and there are no Javascript errors being reported.

**Comment by peppeska** [comment]
same with old version

**Comment by Ricardo-Custodio** [comment]
I have this too, after upgrade from 2.1.23 to 2.1.24.4 (stable release).
Upgrade ok, no Javascript errors after login with new version, but when I clicked on refresh button I had the following error:
![teampass_2 1 24 4_stable](https://cloud.githubusercontent.com/assets/12646960/11781206/12bd104a-a260-11e5-9a1c-189f2c7cb3b1.png)
No errors on teampass log files.

**Comment by ElGranLoky** [comment]
Idem

**Comment by oliviermarie** [comment]
The same thing append for me.
