### ISSUE TITLE
Installer get stuck at Add table "suggestion" 

### ISSUE THREAD

**Issue by charlesrg** [nilsteampassnet/TeamPass#1094]
Everything passes but stops at:
V Add table "otv" 
Add table "suggestion"

**Comment by nilsteampassnet** [comment]
Hum ... difficult to help with so few info.
Version?
Logs errors?

**Comment by codeman1161** [comment]
I am having the same issue. Version 2.1.23. on table creation I get check marks all the way to the "Add table 'Suggestion" and then it hangs. Looking at the db it has created that table. nothing in apache logs. Where else should I look for info.

**Comment by codeman1161** [comment]
I created new DB and attempted the install again and now it will not create any tables. It just hangs on the entire step 5 "Tables creation".

**Comment by codeman1161** [comment]
So I deleted the line "<li>Add table "suggestion"&nbsp;<span id="res5_check27"></span></li>" and then it allowed me to click next and the install finished. I am able to login and everything seems functional. Not sure if anything is missing yet.
