### ISSUE TITLE
Item delete problem -> track lost.

### ISSUE THREAD

**Issue by nunompad** [nilsteampassnet/TeamPass#1097]
When we delete an item/user we lose all the tracking of what was the item/user. The items should be marked as deleted in the database and not show in the user interface.This is the best for audit.

Tks.

**Comment by nilsteampassnet** [comment]
​I don't really understand.
When you delete an item, it is removed from the "Items" page, and stored as
deleted in the database.​
In Views page, tab "Deletions", an Admin can restore or purge the deleted
Items.

**Comment by nunompad** [comment]
When you have a user with history when you delete it you lose the info about it.
You just know that the user that had the id x did something.

**Comment by nilsteampassnet** [comment]
Ok I understand the point. 
You are right this should be the way teampass should handle such case. I will improve it
