### ISSUE TITLE
Creating 2 Password in different folder with same Label

### ISSUE THREAD

**Issue by Arne-Hee6v** [nilsteampassnet/TeamPass#1100]
HI!

I have a few folders stacked like this:
- Root
  - RRZ
    - VSS
      - Server 1
      - Server 2

I created an Item within folder "Server 1" using the label "Admin". When I try to create a second Item in Folder "Server 2" using the label "Admin" Teampass gives en error "This Item already exits!".

But if I create a second item in Folder "Server 2" using the label "Admin 2" I am able to rename the label to "Admin" afterwards. 

It does not make sense to me, not allowing to create items with the same label in different folders, if i can rename them afterwards to use the same label.

I would like to be able to create items with the same label but in different folders. 

Best regards

Arne

**Comment by nilsteampassnet** [comment]
You should enable the option permiting to create similar items. 
You will find this option in the settings page and tab called customize.

**Comment by Arne-Hee6v** [comment]
Hi!

I have a suggestion for the E-Mail-Helptext for the Item "Test the 
E-Mail configuration" in the Configuration-Tab -> Emails:

The Text says: "This test should send an e-mail to the address 
indicated. ..."

On that in Page there is only the field "Sender Email (from Email)" 
where an adress can be entered. But even though this field contains an 
adress, the test fails.

The reason is, I had no E-Mail-adress entered for the admin-user. 
Probably the text should be

"This test should send an e-mail to the *e-mail-adress of the current 
user/admin user*. ...".

I hope, you understand, what I mean.


Best regards!


-- 
Arne Hofmann
Universität Hamburg
Regionales Rechenzentrum
Gruppe Zentrale Dienste
Schlüterstr. 70
20146 Hamburg
Tel.: +49 (0)40 42838 - 7961
Fax: +49 (0)40 42838 - 6270
E-Mail: Arne.Hofmann@uni-hamburg.de

---------------------------------------------------------------------
Diese E-Mail wurde digital signiert. Falls Ihr E-Mail-Programm nicht
ueber die notwendigen Prueffunktionen verfuegt, ignorieren Sie bitte
die angehaengte Signatur-Datei.
This e-mail contains a digital signature. If your e-mail-client does
not support digital signatures, please ignore the attached
signature-file.
---------------------------------------------------------------------
