### ISSUE TITLE
DataTables warning: table id=t_users - Invalid JSON response

### ISSUE THREAD

**Issue by alinos38** [nilsteampassnet/TeamPass#1101]
I have installed the version 2.1.24 twice and each time when I click on users icon I get this error:
DataTables warning: table id=t_users - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
Could you please fix this problem or tell me if there is a workaround?
Alinos

**Comment by OSAccount** [comment]
I have the same problem, version 2.1.24.4 installed.
Once first user created, message Invalid JSON response appeared when i click on users
I have tried to delete user under mysql in table teampass_users, all is ok, but when creating it again, error is back.
Regards.

**Comment by jamesBru** [comment]
same problem, firebug inspect : [["<i class="fa fa-external-link tip" style="cursor:pointer;" onclick="user_edit('29')" title="Editer [29]"></i>", "depac", "", 11 more...], ["<i class="fa fa-external-link tip" style="cursor:pointer;" onclick="user_edit('74')" title="Editer [74]"></i>", "supportdc", "Support", 11 more...]]

**Comment by jamesBru** [comment]
fix it by changing this line in /teampass/sources/datatable/datatable.users.php : $listAlloFcts .= '<i class="fa fa-angle-right"></i>&nbsp;'.@htmlspecialchars($fonction['title'], ENT_COMPAT, "UTF-8").'<br />';  

by this one : $listAlloFcts .= '<i class="fafa-angle-right"></i>&nbsp;'.@htmlspecialchars($fonction['title'], ENT_COMPAT, "UTF-8").'<br />';

I use french language there is an error with " n\'a" 
then I replace in /teampass/includes/language/french.php
the line :  'user_alarm_no_function' => 'Cet utilisateur n\'a aucune Rôle associée !',
by : 'user_alarm_no_function' => 'Cet utilisateur n a aucun Rôle associée !',

**Comment by OSAccount** [comment]
Thanks for tip, but there's no difference between these 2 lines.
What is the correct syntax ?

**Comment by jamesBru** [comment]
I add re-post my comment in a text file =).

**Comment by OSAccount** [comment]
Great, it works !
But i don't think first modification is usefull, i've only modified the language file.

**Comment by hexxamillion** [comment]
I get the same error but when trying to sort the Error logs by the date column.
