### ISSUE TITLE
Users cannot create folders 2.1.24

### ISSUE THREAD

**Issue by Vampir1c** [nilsteampassnet/TeamPass#1102]
I'm wondering if it's something on my end, but users cannot create a folder even when I have Create folder at root enabled for them. Whether it's personal, a folder, and a sub-folder, user's cannot do anything besides add passwords to it and when tried I get this message " You are not allowed to do that!". Instead of admin access I could give users Manager rights and then they can do so without access to the already created users, but they have access to current roles which I wouldn't want.

**Comment by nilsteampassnet** [comment]
Did you set the correct right access in Roles vs Folders matrix?

**Comment by Vampir1c** [comment]
Thank you for replying. Yep, I have set everything I could think of to allow this process. I have attached pictures of what I have. For the user, nothing changes when I add allowed folders.

http://i.imgur.com/VYex9Dq.png
http://i.imgur.com/KJIQVk4.png
http://i.imgur.com/GctRQbq.png
http://i.imgur.com/dpidKLI.png
http://i.imgur.com/5xFYTeQ.png

**Comment by frankenstein91** [comment]
i do not have the problem on my server.
My system is no fresh installation, it updated.

**Comment by nilsteampassnet** [comment]
Indeed option "Customize > Users are allowed to manage folders in allowed
parent folders​" is the one that permits users to create new folders.

I'm investigating and will come back

**Comment by nilsteampassnet** [comment]
​You found a bug.
Please do next change.

In file /sources/folders.queries.php
Find
```
                if (
                    $isPersonal == 1
                    || $_SESSION['is_admin'] == 1
                    || ($_SESSION['user_manager'] == 1)
                    ||
(isset($_SESSION['settings']['subfolder_rights_as_parent'])
                    && $_SESSION['settings']['subfolder_rights_as_parent']
== 1)
                ) {
```​
and replace by
```
                if (
                    $isPersonal == 1
                    || $_SESSION['is_admin'] == 1
                    || ($_SESSION['user_manager'] == 1)
                    ||
(isset($_SESSION['settings']['enable_user_can_create_folders'])
                    &&
$_SESSION['settings']['enable_user_can_create_folders'] == 1)
                ) {
```​

​
In file /sources/items.queries.php
Find
```
                    if (
                        $_SESSION['is_admin'] == 1
                        || ($_SESSION['user_manager'] == 1)
                        || (

isset($_SESSION['settings']['subfolder_rights_as_parent'])
                            &&
$_SESSION['settings']['subfolder_rights_as_parent'] == 1
                        )
                    ) {
```​
and replace by
```
                    if (
                        $_SESSION['is_admin'] == 1
                        || ($_SESSION['user_manager'] == 1)
                        || (

isset($_SESSION['settings']['enable_user_can_create_folders'])
                            &&
$_SESSION['settings']['enable_user_can_create_folders'] == 1
                        )
                    ) {
```​
​
​Please confirm correction​

**Comment by Vampir1c** [comment]
Replacing those lines worked! Thanks so much!
