### ISSUE TITLE
Error adding new item to folder

### ISSUE THREAD

**Issue by luidoc** [nilsteampassnet/TeamPass#1104]
An error appears. Answer from Server cannot be parsed!
Returned data:
Error:
Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('proba', '', '45240a070ebc706d23481dc5c6c12c67', '7ceea763364baac0fd1be64b0b660b46', '', '', '1', 'proba', '0', '', '0', '0', '58')
Add item
 admins_windows
proba

```
Definition
Password & Visibility
Files & Images
```

Label :
Description :

Folder :
Login (if needed) :
Email :
URL :
 Please wait!...

When i try to execute this query in mysql this is the output:
INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('proba', 'Una contraseña de prueba', '33b99ea3baccd1a49c379878aaac5b53', '09f5e6d6732522a053edf1362effb455', '', '', '1', 'root', '0', '', '0', '0', '59')
#1364 - Field 'pw_len' doesn't have a default value

you have forgotten the pw_len in the query.

**Comment by luidoc** [comment]
I found a workaround, execute this query:
ALTER TABLE `teampass_items` CHANGE `pw_len` `pw_len` INT(5) NULL DEFAULT NULL;

**Comment by nilsteampassnet** [comment]
What Teampass release?

**Comment by Dureaghin** [comment]
Same issue with Release 2.1.24 (4).

Thank you "luidoc", works after executing this query!
