### ISSUE TITLE
Problem with teampass performance with a large tree

### ISSUE THREAD

**Issue by paulojjs** [nilsteampassnet/TeamPass#1109]
Hi,

We have a large tree of nested password folders (total 300+ folders) and we are having performance issues during the page load (/index.php?page=items).

We noticed that during the tree load there is an update and a select made in the database for each folder in our tree and this seems to be responsible for the slow load:

update cpassman_nested_tree set nlevel = 4, nleft = XXX, nright = YYY where id = ZZZ 
select id,parent_id,title,nleft,nright,nlevel,personal_folder from cpassman_nested_tree where id = AAA

Is there any way to prevent the update from being made?

**Comment by nilsteampassnet** [comment]
​What version of Teampass do you use?​

**Comment by paulojjs** [comment]
TeamPass 2.1.24

**Comment by nilsteampassnet** [comment]
​In 2.1.24, there is no update query when the tree is loaded. But there is
a select of course.
I could improve this making the subfolders of the tree loaded on demand.

If option "Show more counters in folders tree" is enabled, you should
disable it for performance reason.​

**Comment by paulojjs** [comment]
After doing a check in the code I think there are updates due to a $tree->rebuild(); on file 
sources/tree.php (line 56).
If the rebuild function is the one defined in includes/libraries/Tree/NestedTree/NestedTree.php this should cause several updates.

Can you confirm this?

**Comment by nilsteampassnet** [comment]
​Yes I confirm.
Tree rebuild is done when it is loaded to ensure that it is not corrupted
if some other users create new folders.

I've improved the code and created a new "user setting" which permits him
to select a full load of the Tree or a sequential one. This permits to load
only the part of the Tree you want to access to.

It will be committed today in the context of release 2.1.25.

**Comment by paulojjs** [comment]
Hi,

In the 2.1.25 release I've seen the change on the tree load but I was wondering if that update is really needed when someone loads the tree for the first time.

I've tried to comment the update from the NestedTree.php file and the tree loading was a lot faster.
