### ISSUE TITLE
[2.1.24] Howto working LDAP authentication

### ISSUE THREAD

**Issue by polcape** [nilsteampassnet/TeamPass#1112]
I have made fresh install of version 2.1.24 and I can't set a working LDAP authentication with AD of windows server.

Please tell me if there's a guide to setting the LDAP option in correct way.

Thanks

**Comment by BiarnGamer** [comment]
Hi, for a single domain LDAP authentication, you can use the following settings : 

LDAP account suffix for your domain : @domain.local
LDAP base dn for your domain : dc=domain,dc=local
LDAP array of domain controllers : dc1.domain.local,dc2.domain.local
Use LDAP through SSL (LDAPS) : NO
Use LDAP through TLS : NO
Teampass local users only : NO

I have just installed TeamPass 2.1.24 and with these settings I can use LDAP authentication, even with a not existing user in TeamPass.
My AD domain : domain.local
My two domain controllers : dc1.domain.local and dc2.domain.local

To connect to TeamPass, use your AD credentials without specifying the domain. Example : 
login : username
password : password

**Comment by polcape** [comment]
I have used this setting but not work.
I have also try with LDAP base dn for your domain : ou=nameOfOu,dc=domain,dc=local
(this work with previous version of Teampass).

When I try to login appear: This user do not exist!

**Comment by BiarnGamer** [comment]
Ok,
I have this error sometimes, I don't know why. Try to refresh the page or use another browser. I have some problems when I try to login an LDAP user and, after some refresh it works.

Can you also enable ldap debug ? In the file /sources/identify.php, set the variable $debugLdap to 1. Then, try to login with your AD account and watch the file /files/ldap.debug.txt. This can help you to know if TeamPass can connect to the AD.

**Comment by fabiofbra** [comment]
Hello,

I already activated $debugldap and the text files was created but still blank during attempts to login.

I have 389-DS LDAP (working with couple of other services), with following configurations:

LDAP server type : Posix / OpenLDAP SearchBased

LDAP configuration
User attribute to search: uid
Ldap Bind Dn: uid=teampass,cn=directory administrators,dc=abctest,dc=com,dc=br
Ldap Bind Passwd: XXXXX
Ldap Search Base : dc=abctest,dc=com,dc=br
LDAP array of domain controllers: home.abctest.com.br
Use LDAP through SSL (LDAPS): no
Use LDAP through TL: no
Teampass local users only  : no

No login. Only "This user do not exist!".

Any advice?
Thanks

**Comment by fabiofbra** [comment]
Any?

**Comment by polcape** [comment]
I have made a fresh install and now authentication with windows server (2012) AD work fine.
With suffix @domain.local, base DN ou=nameOfOu,dc=domain,dc=local

**Comment by 46Wil** [comment]
Did any of you actually get this working with either LDAPS or TLS?

**Comment by abvillanueva** [comment]
I have the same issue too with Teampass version 2.1.26, with error "Login credentials do not correspond!"

Any advice on this?
