### ISSUE TITLE
2.1.24 Cannot Delete Favorites Due to "undefined function prefix_table() "

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1114]
I was testing delete favorites and I received a 500 error.

Call to undefined function prefix_table() in favourites.queries.php on line 43

This is what is defined on line 43:
$data = DB::queryfirstrow("SELECT favourites FROM ".prefix_table("users")." WHERE id = %i", $_SESSION['user_id']);

**Comment by zephilou** [comment]
Hi hexxamillion,
I had the same error, to resolve this issue you need to add the call to main.functions.php  like this :

require_once('sessions.php');
session_start();
require_once $_SESSION['settings']['cpassman_dir'].'/sources/main.functions.php';

**Comment by hexxamillion** [comment]
Thanks for the tip.

**Comment by hexxamillion** [comment]
I confirmed that this sort of works. I can delete now but it seems that once I delete 2 favorites, all my other favorites get deleted as well that I do not want to delete. So if I delete one favorite, it works just fine. If I delete 2 in a row all favorites get deleted.

**Comment by hexxamillion** [comment]
Just wanted to follow up on this to see if there is additional ideas for this. I tried the suggested solution and I can delete but after deleting 2 favorites the rest all delete as well. It seems to be always after deleting 2 at a time.
