### ISSUE TITLE
[2.1.24] - Change the main SALT Key - Not Working

### ISSUE THREAD

**Issue by nunompad** [nilsteampassnet/TeamPass#1117]
When I tried to change the system salt it does not work.

The problem is that the table users don't have pw_iv column.

Line on admin.queries.php:

$rows = DB::query("SELECT id, pw, pw_iv FROM ".prefix_table("users"));

Error label on the table teampass_log_system:

SELECT id, pw, pw_iv FROM teampass_users<br />Unknown column 'pw_iv' in 'field list'@/TeamPass-development/sources/admin.queries.php

**Comment by nilsteampassnet** [comment]
​I totally forgot to include this function in my test batch, and wasn't
tested for 2.1.24.

This is of course totally wrong and I need to rewrite it.

Will be included in 2.1.25​
