### ISSUE TITLE
Uploadify filter upload of file extensions

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#112]
You should be able to upload any file you need independently from file extension used or in that way it worked before, I fixed commenting those lines on uploadifu, maybe there is a better way:

```
# diff /usr/src/TeamPass_2.1.7/includes/libraries/uploadify/uploadify.php /usr/src/TeamPass_FIXED/includes/libraries/uploadify/uploadify.php
88,89c88,89
< if (!in_array($ext, $valid_exts))
<       HandleError('Invalid file extension');

---
> #if (!in_array($ext, $valid_exts))
> #     HandleError('Invalid file extension');
```

**Comment by allburov** [comment]
We use teampass for saving ssh-keys. We use "txt" extension for save it :) I really want load non-extension or '.rsa'
