### ISSUE TITLE
When deleting an item, confirmation modal doesn't show the name of the item to be deleted.

### ISSUE THREAD

**Issue by pajtai** [nilsteampassnet/TeamPass#1122]
This makes it relatively easy to accidentally delete the wrong item.
![screen shot 2015-12-15 at 16 33 43](https://cloud.githubusercontent.com/assets/1643937/11828457/c33b140a-a349-11e5-8a8a-7711c80fde08.png)

v2.1.23

**Comment by nilsteampassnet** [comment]
Good practice ... implemented in 2.1.25
