### ISSUE TITLE
No Item to show in a folder after upgrading to 2.1.24

### ISSUE THREAD

**Issue by bouba9431** [nilsteampassnet/TeamPass#1123]
Hello,
In 2 subfolders of my tree, I lost after upgrading to 2.1.24 the ability to view the items and password. The counter tell me that there are some items but I can't see them.
I tried to move the folder, change the role etc., but I can't see the items any more.

Thank you for your help.

**Comment by nilsteampassnet** [comment]
​Hello,

Do a complete check of the roles​ in the "roles vs folders" matrix.
Ensure that the role your account is related has at least read access on
them.

From what version did you upgrade?

**Comment by bouba9431** [comment]
Hi,
I upgraded from 2.1.23.
The matrix is correct. On the left part of the screen, I can see the folder and the number of items in it.
When I click on the folder, I can see briefly the items then there is a refresh that says that there are no item to show.

**Comment by nilsteampassnet** [comment]
​Can you share with me your screen with teamviewer?

Contact me at nils@teampass.net​

**Comment by bouba9431** [comment]
Working after the fix.
Thank you
