### ISSUE TITLE
No Passwords in Teampass

### ISSUE THREAD

**Issue by Dirk23** [nilsteampassnet/TeamPass#1126]
Hi,

i tried to update from 2.1.23 to 2.1.24. I backed up my complete folder unter /var/www/html and tried to update like it is described here http://teampass.net/2014-06-28-upgrade/ but that didn't work. The Upgrade process stops at Step 1 - Check Server. There is a Marquee Progressbar never stops and no checks are done. After copying back my backup could access all entrys but without Passwords, they are all empty on the Webpage!
I recovered my sk.php, because i thougth it could have changed, but still no passwords.

What have i done wrong? Is there a chance to get back all passwords?

Regards

Dirk

**Comment by frankenstein91** [comment]
please look in your database.
Maybe you see an error there.

**Comment by Dirk23** [comment]
What do you mean by "look in your Database"?
There are no Errors in the MySQL Error log.

**Comment by frankenstein91** [comment]
try a "seclect * from <table>;" and look for something unusual.

2015-12-21 9:14 GMT+01:00 Dirk <notifications@github.com>:

**Comment by Dirk23** [comment]
I have data in some tables, some are Empty.......Noting unusual for me to find.
Maybe you can give me a hint what i should look for?

**Comment by bouba9431** [comment]
Hi,
I've got the same error, upgrading from the same version.

**Comment by nilsteampassnet** [comment]
​I'm afraid to not understand.

You say that you have performed a backup of folder and database of your
current instance 2.1.23 before starting upgrading.
Then 2.1.24 upgrade process did not pass "Step 1"​.
Finally, after restoring your backup, there is no passwords any more.

That's it?

**Comment by Dirk23** [comment]
Yes, thats it!

**Comment by nilsteampassnet** [comment]
​Ok so here you have an issue related to your "restore" or perhaps of your
backup.

How did you performed the backup of your database? With a mylsqdump command
or with PhpMyAdmin?

Same question with you "restore"?

**Comment by Dirk23** [comment]
Teampass did backup the Database. I didnt restore it to the original Database.

**Comment by nilsteampassnet** [comment]
​OK so you did not restore the database.

But as the upgrade did not go through step 1, no change was done on it, and
no change was done on any data existing in your current instance of
teampass.

Indeed, the changes occur only from step 4.

I only see here as a root cause a change related to your sk.php file or
settings.php file
Can you check this?​

**Comment by Dirk23** [comment]
in settings.php: everything looks fine:
```php
<?php
global $lang, $txt, $k, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "localhost";
$user = "user";
$pass = "pass";
$database = "databasename";
$pre = "pre_";
$port = 3306;
$encoding = "utf8";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/home/user/teampass/saltkey');
require_once "/home/user/teampass/saltkey/sk.php";
?>
```

in the sk.php everything seems to be ok. I recovered a salt from a delete sk.php and i found a newer saltkey, but with either of them i can see the passwords.
 ´´´php
<?php
@define('SALT', 'OLD-SALT'); //Never Change it once it has been used !!!!!
@define('COST', '13'); // Don't change this.
//@define('SALT', 'NEWER-SALT'); //Never Change it once it has been used !!!!!
//@define('COST', '13'); // Don't change this.
?>
´´´
I switched from one sk to an other by commenting out the lines!
There is nothing i must "restart" after changing the salt, rigth?

Thank you for help!

**Comment by nilsteampassnet** [comment]
​No you don't need to restart anything.

Did you changed back all the files to the initial 2.1.23?​

**Comment by Dirk23** [comment]
i hope i did...... i removed the folder with the Updated Files and renamed the backup folder back to it's normal Name.

**Comment by frankenstein91** [comment]
This should work. Maybe some problems with file owner and file rights? Can
you look in the httpd log?
Am 21.12.2015 13:30 schrieb "Dirk" <notifications@github.com>:

**Comment by Dirk23** [comment]
I found that the Saltkey was wrong. I recovered a external Backup (i didnt know we had one), and found a different Saltkey. After copying the recovered sk, i can access all Passwords!!

Thank you anyway.

**Comment by nilsteampassnet** [comment]
​It was sure something link this occurred ;)

Anyhow, you should now think about migrating to latest release.

**Comment by Dirk23** [comment]
but how can upgrade to it?

**Comment by nilsteampassnet** [comment]
​It would be interesting to have the Apache error message that encounter
the server while performing step 1.

**Comment by Dirk23** [comment]
i will make a copy of my teampass folder, dump MySQL Database with MySQLdump, restore the dump to a different Database and try to update the backupfolder and Database. I will post Apache Error Log if there is any Error.

**Comment by Dirk23** [comment]
where can i find that setting, that redirects my backupfolder to the productive URL?

**Comment by frankenstein91** [comment]
make a .htaccess and add (with your data

RewriteEngine on
RewriteCond %{HTTP_HOST} ^old.domain$
RewriteRule (.*)$ https://new-doma.in/$1 [R=307,L]

**Comment by Dirk23** [comment]
ok, copy folder for test scenario is not working. I changed settings in apache to make that copied folder accessible, but all i get is a blank screen.
in the Sourceview all i see is:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```
nothing else!

**Comment by Dirk23** [comment]
The .htaccess didnt help!
```html
RewriteEngine on
RewriteCond %{HTTP_HOST} ^sub.domain.local/teampass$
RewriteRule (.*)$ https://sub.domain.local/migtest/$1 [R=307,L]
```

**Comment by Dirk23** [comment]
@nilsteampassnet i tried to install 2.1.24 from the scratch and it wont go further than:
Add table "otv"

Add table "suggestion" is never selected as finisched and i can not klick on "Next" Button.
Apache Error Log doesnt show any error.
MySQL Error log doesnt show any error.

What can i do?

**Comment by nilsteampassnet** [comment]
No "green tick" appears on table "suggestion" but the table is created (it
is improved in 2.1.25).
If the NEXT button is not enabled, that means that there is an error during
the tables creation, and in this case there must be an error in Apache log.
Remark that the log level depends on what is defined on the server.​

**Comment by Dirk23** [comment]
I changed to Loglevel debug, now thats what i can see when it comes to:"Add table "suggestion""
```shell
[Mon Dec 21 16:15:35.355962 2015] [authz_core:debug] [pid 26187] mod_authz_core.c(802): [client 192.168.2.164:51289] AH01626: authorization result of <RequireAny>: granted, referer: https://sub.domain.local/migtest/install/install.php
[Mon Dec 21 16:15:35.363687 2015] [headers:debug] [pid 26195] mod_headers.c(845): AH01502: headers: ap_headers_output_filter()
[Mon Dec 21 16:15:35.364511 2015] [headers:debug] [pid 26187] mod_headers.c(845): AH01502: headers: ap_headers_output_filter()
[Mon Dec 21 16:15:35.563994 2015] [headers:debug] [pid 26185] mod_headers.c(845): AH01502: headers: ap_headers_output_filter()
[Mon Dec 21 16:15:40.315438 2015] [ssl:info] [pid 26188] (70007)The timeout specified has expired: [client 192.168.2.164:51283] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.315498 2015] [ssl:debug] [pid 26188] ssl_engine_io.c(1003): [client 192.168.2.164:51283] AH02001: Connection closed to child 4 with standard shutdown (server 127.0.1.1:443)
[Mon Dec 21 16:15:40.323423 2015] [ssl:info] [pid 26268] (70007)The timeout specified has expired: [client 192.168.2.164:51291] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.323454 2015] [ssl:debug] [pid 26268] ssl_engine_io.c(1003): [client 192.168.2.164:51291] AH02001: Connection closed to child 8 with standard shutdown (server 127.0.1.1:443)
[Mon Dec 21 16:15:40.347436 2015] [ssl:info] [pid 26269] (70007)The timeout specified has expired: [client 192.168.2.164:51281] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.347486 2015] [ssl:debug] [pid 26269] ssl_engine_io.c(1003): [client 192.168.2.164:51281] AH02001: Connection closed to child 9 with standard shutdown (server 127.0.1.1:443)
[Mon Dec 21 16:15:40.367430 2015] [ssl:info] [pid 26187] (70007)The timeout specified has expired: [client 192.168.2.164:51289] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.367430 2015] [ssl:info] [pid 26195] (70007)The timeout specified has expired: [client 192.168.2.164:51285] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.367486 2015] [ssl:debug] [pid 26187] ssl_engine_io.c(1003): [client 192.168.2.164:51289] AH02001: Connection closed to child 3 with standard shutdown (server 127.0.1.1:443)
[Mon Dec 21 16:15:40.367486 2015] [ssl:debug] [pid 26195] ssl_engine_io.c(1003): [client 192.168.2.164:51285] AH02001: Connection closed to child 5 with standard shutdown (server 127.0.1.1:443)
[Mon Dec 21 16:15:40.569206 2015] [ssl:info] [pid 26185] (70007)The timeout specified has expired: [client 192.168.2.164:51287] AH01991: SSL input filter read failed.
[Mon Dec 21 16:15:40.569280 2015] [ssl:debug] [pid 26185] ssl_engine_io.c(1003): [client 192.168.2.164:51287] AH02001: Connection closed to child 1 with standard shutdown (server 127.0.1.1:443)
```

**Comment by Dirk23** [comment]
Seems its because of the Domainname. When i try to install with the DNS Name, the next Button wont be enabled. When i try to install with the IP Adress in the URL, the Nextbutton is enabled.

I am confused now, because the DNS Name points to the IP of the server!

**Comment by nilsteampassnet** [comment]
​I'm not an expert but it seems related to time out on SSL???
How long is the max_execution_time variable?
Perhaps does it exist a similar one for SSL connection???

**Comment by Dirk23** [comment]
max_execution_time = 90
When i use the IP Adress for installation, it installs via SSL too, but with the IP Adress it is working like you described.
Maybee it is because of my Server, i dont know exactly. Maybee a Update may work the sameway too.

**Comment by nilsteampassnet** [comment]
​Yes absolutely this is related to the server configuration, so that an
upgrade of Teampass will not change this behavior.

But any how, SSL is not the cause of this. I do use an SSL certificate on
my servers and don't have this​.
What is strange in your log is that those messages are only at level "info"
and "debug" so no "error" really occurs. Can you try to change your log
level to ignore "debug" and "info"?

Note: 90 is largely enough and shouldn't be the cause of this.

**Comment by Dirk23** [comment]
Sorry, i dont know how to filter that logs. I can set those LogLevels:
https://httpd.apache.org/docs/2.2/de/mod/core.html#loglevel

Eache Level will show all lower Levels too. So Debug is thr highest and now it logs everything.
I can set it to info and retry!

**Comment by Dirk23** [comment]
I guess i figuered out, that the apache Config file was the source for this foo. 

I changed from
```bash
<IfModule mod_ssl.c>
<VirtualHost _default_:443>
```

to 
```bash
<IfModule mod_ssl.c>
<VirtualHost 192.168.0.1:443>
```
now the Next Button will appear......

**Comment by nilsteampassnet** [comment]
​Nice to read :)
