### ISSUE TITLE
[2.1.24] Requested Json Parse Failed

### ISSUE THREAD

**Issue by SylvainGuibert** [nilsteampassnet/TeamPass#1128]
I'm trying to use TeamPass since an old password application manager.

I have create lot of entry without any problem, but after one entry (I think), I obtain a "pop-up" box which said "Requested Json parse Failed". This box appears only when I try to see an entry. 

On the admin account, they are no problem.

With a user account, if I not seeing a password entry (folder navigation for example, they are no problem).

I have checked the log, one error: 

INSERT INTO `teampass_log_items` (`id_item`,`date`,`id_user`,`action`,`raison`) VALUES (NULL, 1450778774, '2', 'at_modification', 'at_moved : -> FOURNISSEURS')<br />Column 'id_item' cannot be null@/sources/items.queries.php

**Comment by fd4485** [comment]
seme problem. I thought that it was correct with another issue, but error is always here.

**Comment by SylvainGuibert** [comment]
If i debug it with Chrome Dev Tools and JSON validator, this is the error what i have : 

Query : 

----------------
```
[{
	"error": "",
	"text": "<li onclick=\"displayItemNumber(33, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - USER 1</li><li onclick=\"displayItemNumber(28, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - USER 2 </li><li onclick=\"displayItemNumber(30, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - USER 3</li><li onclick=\"displayItemNumber(34, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - USER 4</li><li onclick=\"displayItemNumber(31, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - USER 5</li><li onclick=\"displayItemNumber(32, 20)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Creative Cloud - Communication</li><li onclick=\"displayItemNumber(5, 9)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Abix</li><li onclick=\"displayItemNumber(105, 34)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Blackberry ID - USER 6</li><li onclick=\"displayItemNumber(101, 34)\"><i class=\"fa fa-hand-o-right fa-fw\"></i>&nbsp;Blackberry Expert Support Center</li>",
	"existing_suggestions": 0
}]
```
Error with JSON validation tools: 
```
Error: Parse error on line 3:
...rror": "",	"text": "
```

**Comment by mhglover** [comment]
This appears to be related to a role that doesn't have permissions to view/edit certain folders. I was able to get rid of this error by removing the roles that were affected and re-creating them.

**Comment by armourtommy** [comment]
I've done some testing, and found that I get a Requested Json Parse Failed when a folder or item is set to read only.  If everything is either read or write then this error does not occur

**Comment by SylvainGuibert** [comment]
The user accounts, where I have the issue have read & write permissions. One particularity, in this entry, url contains a "#' . 

I can reproduce this issue easily: 

-> Create an entry with a url that contains a # like "https://creative.adobe.com/#apps"
-> Click on it
-> To remove the "pop-up Json Error", click on 1 to 10 entries ... after that pop-up disappear. I think "password view history" recreate this error. 

Can you try to reproduce?

**Comment by armourtommy** [comment]
I tested this, by taking a limited access test user and created a new item in an existing folder.  I was able to create, view and then click on the link that you provided without any issues.

Haven't tried extensive testing with different users though, so I can't say for sure that its not reproducible.

**Comment by SylvainGuibert** [comment]
Ok, after many tests, I think I have found the issue. In the Item Label, I have a simple quote ('). When I remove it, problem disappears. 

Json data are not correctly formatted when you add a simple quote in your item label. Simple quote is used in French Language. [The Team => L'équipe].

Can you try to reproduce? TeamPass work in French language, but I think with English or another language it's the same issue.

**Comment by armourtommy** [comment]
Hi, I can confirm that using a single quote raises a json error.  So it looks like there are 2 issues with json parsing at the moment, parsing single quotes and read only values.  Hopefully these are simple fixes that can be put into the next release.

**Comment by SylvainGuibert** [comment]
Thanks for your help #armourtommy. Can you create Pull Request for this fixes ?

**Comment by nilsteampassnet** [comment]
​I will check this ... thank you for your investigations, they are a good
start of work to debug this.​

**Comment by armourtommy** [comment]
This also happens when I try to give users access to a folder in a different role

**Comment by nickalleyne** [comment]
I just upgraded to 2.1.24 from .23 and it is happening to me with every password I click on.

To reproduce, I just click on the folder on the left, and the passwords appear on the right, and then any password I click on the right and the JSON error pops up.

It only seems to happen to me so far, of the 3 users tested (total of under 15 use it).

**Comment by armourtommy** [comment]
Hi nickalleyne,

To get around this, I am currently only using full write or no access for role access to folder.  If a folder is given read or the user cannot delete check box is ticked, etc, then all users of that role get a json fail for all folders.

Hope that helps.

**Comment by SylvainGuibert** [comment]
@nickalleyne : Please try to debug it, to help @nilsteampassnet 

On Google chrome , F12 for debugging Tools, On the network tab, click on filter, the click on XHR option. Reproduce your issue, and you must have json data witch are parsed on the tab below.

After that, try to validate your json data with a json validator Tools like http://jsonlint.com/ .

Then post the debug, and if it's possible the json data too.

**Comment by nickalleyne** [comment]
Sorry for the delay in responding.  The very next day it stopped happening, so I cannot get any info unfortunately.  Bright side is no more issue for me, but I am not sure what caused it.

**Comment by SylvainGuibert** [comment]
@nilsteampassnet About which issue ? the ' or about @armourtommy issue ?

**Comment by armourtommy** [comment]
I'm still getting the same issue in 2.1.25, is there a way that I can check why the json is not being parsed?

**Comment by SylvainGuibert** [comment]
try to validate your json data with a json validator Tools like http://jsonlint.com/ .
