### ISSUE TITLE
Teampass 2.1.24 update error when try to change settings

### ISSUE THREAD

**Issue by mfonnegrae** [nilsteampassnet/TeamPass#1142]
hello, this is my first time configuring Teampass, I am trying to convince my coworkers that this is right tool to use for our needs but when I try to setup the Teampass 2.1.24 settings and error occurs and changes are not being taken, here it is the error that appears.

 Maintenance mode is activated. Users currently can not access TeamPass.
Error:
Query: UPDATE `teampass_misc` SET `valeur`=NULL WHERE type = 'admin' AND intitule = 'ga_website_name'

Can somebody help me out.

Best regards,

Mauricio Fonnegra

**Comment by nilsteampassnet** [comment]
Looking to this issue.
Just to get confirmation, this occurs when you change a specific option in
"Settings page" or for any option?

**Comment by nilsteampassnet** [comment]
​It seems your issue happen when changing the 2FA settings, can you confirm?
Please send a screenshot with the value you set so that I can reproduce.

**Comment by mfonnegrae** [comment]
Hello Nils,

The issue happends when I change any option.

Here there are the screen shots.

Before the change (I am changing the Timezone selection from UTC to America Eastern Time New York)


Best regards.

Mauricio A. Fonnegra Escalante
Department of Information and Technology Services
Secretariat for Administration and Finance
Organization of American States
1889 F Street N.W., Washington, D.C. 20006
Phone. 202.370.4531
F. 202-458-6212
mfonnegra@oas.org<mailto:mfonnegra@oas.org>
www.oas.org<http://www.oas.org/>
Jn 3:16

**Comment by mfonnegrae** [comment]
Nils here it is

Mauricio A. Fonnegra Escalante
Department of Information and Technology Services
Secretariat for Administration and Finance
Organization of American States
1889 F Street N.W., Washington, D.C. 20006
Phone. 202.370.4531
F. 202-458-6212
mfonnegra@oas.org<mailto:mfonnegra@oas.org>
www.oas.org<http://www.oas.org/>
Jn 3:16

**Comment by flamarionjorge** [comment]
Same here. When I chante the any option on system configuration I get this error:

Query: UPDATE `teampass_misc` SET `valeur`=NULL WHERE type = 'admin' AND intitule = 'ga_website_name'

This is a fresh installation, so I can do any test that you want.

Regards,

Flamarion Jorge
