### ISSUE TITLE
Teampass 2.1.24 import csv double quotes issue - Fixed

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#1143]
There is an issue when you try to import a CSV in Teampass 2.1.24 with a double quote " in a password. The problem revolves around the import.queries.php file where the creator has made a mysql typo. Anywhere in this file where &quote is written should be changed to &quot. This will allow you to import passwords with double quotes in them.

Regards,
Aleks

**Comment by nilsteampassnet** [comment]
​Corrected in 2.1.25

Thanks for reporting!
