### ISSUE TITLE
Changing a users list of roles doesn't update until after log out

### ISSUE THREAD

**Issue by ahh3ah** [nilsteampassnet/TeamPass#1145]
I'm finding that changing a users roles doesn't get updated until the user logs out, so they are still able to make changes to the roles they have been removed from.

**Comment by nilsteampassnet** [comment]
​Yes this is "normal" as the roles are evaluated at user login.
It would be too long to refresh this regularly.

What you should do is to force the user to get disconnected.
Either you inform him
Either you force him to be disconnected by selecting page "Views", tab
"Database", select "online users", wait for the list of connected users to
be refreshed, and click the red icon to disconnect the user.
