### ISSUE TITLE
Roles on seperate pages

### ISSUE THREAD

**Issue by ahh3ah** [nilsteampassnet/TeamPass#1146]
I have multiple roles that are split across 2 pages when logged in as an admin.  When I use a normal account, if I have access to 2 roles, 1 which is on the 1st page in admin mode and 1 that is on the 2nd page then as the normal user they are still on the separate pages, but separated by white space where the other roles should be.

**Comment by nilsteampassnet** [comment]
​Can you provide screencaptures because I cannot understand the point?

**Comment by armourtommy** [comment]
Hi, apologies for the crap pics, hopefully they convey what i mean.

Page1 Full Access
![page1_full_access](https://cloud.githubusercontent.com/assets/16490185/12173417/8fc0f88a-b54e-11e5-9cf9-10aa552a3b2c.png)

Page2 Full Access
![page2_full_access](https://cloud.githubusercontent.com/assets/16490185/12173423/97e2994c-b54e-11e5-8ceb-e9d06f61e5d9.png)

Page1 Partial Access
![page1_partial_access](https://cloud.githubusercontent.com/assets/16490185/12173428/a06b7b06-b54e-11e5-8076-9b727db528c6.png)

Page2 Partial Access
![page2_partial_access](https://cloud.githubusercontent.com/assets/16490185/12173430/a87a30c6-b54e-11e5-8450-e5c64e304ee1.png)

**Comment by nilsteampassnet** [comment]
​Understood and I could reproduce.
Will work on it

**Comment by armourtommy** [comment]
thanks
