### ISSUE TITLE
An error appears. Answer from Server cannot be parsed!

### ISSUE THREAD

**Issue by jaann1** [nilsteampassnet/TeamPass#1148]
Hello,
After install Teampass version 2.1.24 will add item a period of inactivity when i return on TeamPass i got a error:
"An error appears. Answer from Server cannot be parsed!
Returned data:
Error:
Query: INSERT INTO `teampass_categories_items` (`item_id`,`field_id`,`data`,`data_iv`) VALUES (9, 'undefined', '13d5629ac7dcd1bc1b8dece00c04de98', '1bfe272e93bdbd1ef8870181889c24fb')"
Error is Field_id have Value Integer but Datenbank save undefind.

i need helf solve this problem.

**Comment by nilsteampassnet** [comment]
​Sorry but I didn't understood the context in which this error appears.
Can you please describe with more details how you get it?​

**Comment by nilsteampassnet** [comment]
​Ok understood how it could occur.
I will correct this.​

**Comment by jaann1** [comment]
i wana add new Entroy (add Password) when you press die Botten "Save" then show this message..

**Comment by nilsteampassnet** [comment]
​Do you confirm that you use "Categories" with specific fields?
Can you make a screenshot of the page with the categories setup?

**Comment by jaann1** [comment]
![einstellung1](https://cloud.githubusercontent.com/assets/16592774/12193296/2bfdc9d8-b5e7-11e5-8728-5657c26ee37a.PNG)
![einstellung2](https://cloud.githubusercontent.com/assets/16592774/12193297/30b1f260-b5e7-11e5-9c9e-e551d7002060.PNG)
This is both Settingspage.
