### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by Harry-89** [nilsteampassnet/TeamPass#1151]
Hello,

I've installed the latest master version on an IIS server.
After installation i switch directly to the users menu and get the following error.

DataTables warning:table_id=t_users - Ajax error. For morge information about this error, please see http://datatables.net/tn/7

Edit:
Debug Console says:

404

..sources/datatable/datatable.users.php?...

When I remove all GET Parameters it's working and the 404 is gone and I get a JSON return, but when I add all GET Parametes it gets a 404

The whole URL is exactly 3105 Characters long.
Isn't that too long?

Can you help me with this?

Thank you

**Comment by Harry-89** [comment]
I solved it by turning the max query_string on my IIS up to 4096.

**Comment by nilsteampassnet** [comment]
This is a bug previously corrected.
From where did you get your Teampass package? Can you give the release url?

**Comment by Harry-89** [comment]
I got it from there.

https://github.com/nilsteampassnet/TeamPass/releases
https://github.com/nilsteampassnet/TeamPass/archive/2.1.24.4.zip

**Comment by nilsteampassnet** [comment]
In file "sources/datatables/datatable.users.php", find
```
    $sWhere .= "isAdministratedByRole IN (".implode(",", $_SESSION['user_roles']).")";
```
and replace by
```
    $sWhere .= "isAdministratedByRole IN (".implode(",", array_filter($_SESSION['user_roles'])).")";
```
