### ISSUE TITLE
Error while saving settings

### ISSUE THREAD

**Issue by juanfalguera** [nilsteampassnet/TeamPass#1152]
I just installed Teampass v 2.1.24.4 on Wampserver 3, running on Windows Server 2012. 
The installation process was ok, with no errors. But,  when I try to save any change in the Team Pass settings section I get this error:

Error: 
Query: UPDATE `teampass_misc` SET `valeur`=NULL WHERE type = 'admin' AND intitule = 'ga_website_name'

I already tried to run on Wampserver 2, tried to use XAMPP but the same error persists. Any ideas?

Thanks.

**Comment by nilsteampassnet** [comment]
​Can you please make the next try.

In file sources/admin.queries.php, found:
```
        DB::query("SELECT * FROM ".prefix_table("misc")." WHERE type = %s
AND intitule = %s", "admin", "ga_website_name");
        $counter = DB::count();
        if ($counter == 0) {
            DB::insert(
                prefix_table("misc"),
                array(
                    'type' => "admin",
                    "intitule" => "ga_website_name",
                    'valeur' =>
htmlspecialchars_decode($dataReceived['ga_website_name'])
                )
            );
        } else {
            DB::update(
                prefix_table("misc"),
                array(
                    'valeur' =>
htmlspecialchars_decode($dataReceived['ga_website_name'])
                ),
                "type = %s AND intitule = %s",
                "admin",
                "ga_website_name"
            );
        }
        $_SESSION['settings']['ga_website_name'] =
htmlspecialchars_decode($dataReceived['ga_website_name']);
```​
​replace by
```
        if (!is_null($dataReceived['ga_website_name'])) {
            DB::query("SELECT * FROM ".prefix_table("misc")." WHERE type =
%s AND intitule = %s", "admin", "ga_website_name");
            $counter = DB::count();
            if ($counter == 0) {
                DB::insert(
                    prefix_table("misc"),
                    array(
                        'type' => "admin",
                        "intitule" => "ga_website_name",
                        'valeur' =>
htmlspecialchars_decode($dataReceived['ga_website_name'])
                    )
                );
            } else {
                DB::update(
                    prefix_table("misc"),
                    array(
                        'valeur' =>
htmlspecialchars_decode($dataReceived['ga_website_name'])
                    ),
                    "type = %s AND intitule = %s",
                    "admin",
                    "ga_website_name"
                );
            }
            $_SESSION['settings']['ga_website_name'] =
htmlspecialchars_decode($dataReceived['ga_website_name']);
        } else {
            $_SESSION['settings']['ga_website_name'] = "";
        }
```​​

**Comment by juanfalguera** [comment]
Sorry, it didn't work. Then I tried version 2.1.23.4 and now is working. Thanks.

**Comment by Dureaghin** [comment]
Didn't work for me too on version 2.1.24.

**Comment by nilsteampassnet** [comment]
I don't understand, I've retested on fresh 2.1.24(4) downloaded from Github and I cannot reproduce.
There must be a combination of settings on your instance that I cannot found.
Could you perform screenshots of tabs "Teampass Settings", "Customize" and "2FA Options"?
If you don't want to share you can send at nils@teampass.net

**Comment by juanfalguera** [comment]
Here they are:

![image](https://cloud.githubusercontent.com/assets/16647133/12263797/205b235c-b919-11e5-9eed-755534daafbb.png)
![image](https://cloud.githubusercontent.com/assets/16647133/12263813/39440438-b919-11e5-896f-5874800eaced.png)
![image](https://cloud.githubusercontent.com/assets/16647133/12263826/53c9a47a-b919-11e5-9dcb-75f87ed52cc9.png)
![image](https://cloud.githubusercontent.com/assets/16647133/12263860/9f245758-b919-11e5-9441-d00cba3186af.png)
![image](https://cloud.githubusercontent.com/assets/16647133/12263866/acf58d52-b919-11e5-8228-b058c1fa6bd4.png)

**Comment by nilsteampassnet** [comment]
I've tried with those settings with no issue.
Where do you get this error, in your logs?

**Comment by juanfalguera** [comment]
The error message appears on the screen:

![image](https://cloud.githubusercontent.com/assets/16647133/12295023/8339709c-b9e5-11e5-9975-ef5ed4d1df29.png)

**Comment by juanfalguera** [comment]
I just ran this query on phpadmin and figured out that field "valeur" doesn't accept null values. I changed the structure to allow nulls and the error stoped. I don't know if this will result in other problems in the future, but it is working so far.

**Comment by juanfalguera** [comment]
Another information that could help to identify the problem. I have to instances of Teampass running on the same server. Version 2.1.23 is running well and 2.1.24 wasn't. Then I compare the table teampass_misc to figure out what the property 'ga_website_name is about. I found that this property is about option "Name displayed Google Authenticator for Teampas" on the Tempass Settings screen. In version 2.1.23, this field exists:

![image](https://cloud.githubusercontent.com/assets/16647133/12295436/39e12950-b9e8-11e5-854b-3c1207193dc5.png)

In versions 2.1.24 it doesn't:

![image](https://cloud.githubusercontent.com/assets/16647133/12295459/4ecc99e4-b9e8-11e5-9bf8-a9959b481193.png)

This is why version 2.1.24 is passing "null" to the field 'valeur' when you press "save"

**Comment by nilsteampassnet** [comment]
Yes this has changed between the 2 versions, because 2FA options have been
moved to a new tab.
But the queries have also moved.
And there is no such query in this part of code, that's why I don't
understand.
If it is an update, are you sure you have overwrite the existing files with
the newest package?

**Comment by nilsteampassnet** [comment]
In file admin.settings.php, can you remove this:
```
    // Update ga_website_name
    if (isset($_SESSION['settings']['ga_website_name']) && $_SESSION['settings']['ga_website_name'] != @$_POST['ga_website_name']) {
        updateSettings('ga_website_name', @$_POST['ga_website_name']);
    }
```

**Comment by juanfalguera** [comment]
It worked! Thanks!
