### ISSUE TITLE
Very serious security issue on version 2.1.23

### ISSUE THREAD

**Issue by juanfalguera** [nilsteampassnet/TeamPass#1153]
I am using LDAP integration with personal folder option enabled. So, when a user from my domain logs for the first time on Teampass, it creates a Teampass account automatically with no rights and attached to no folders or roles, as desired.

But, this same user can see all the passwords stored in all folders, as the image shows:

![image](https://cloud.githubusercontent.com/assets/16647133/12264139/abfa5dfe-b91b-11e5-8f49-821037922ca0.png)

When he logs off and logs on for the second time, only the personal folder appears, as desired.
If whe disable "personal folder" option this issue doesn't happen. 

This is a very serious security issue and thank God I am in test fase, so it didn't compromise my passwords. 

I saw other 2 users complaining about that in other posts. It seems in version 2.1.20 this doesn't happen.

If you are using versions 2.1.21 to 2.1.24 with personal folder enable and LDAP integration, I suggest you make a test and log a domain user on Teampass for the first time and see if it can see all passwords.

**Comment by nilsteampassnet** [comment]
Thanks for reporting.

LDAP things are not easy for me as I cannot test.
So only serious code review is done.

I think I found a way to get rid of this.
I have committed in "development" branch file sources/identify. Can you
replace it on your test server and tell me if it corrects the point?

Thanks

**Comment by juanfalguera** [comment]
Sorry, it didn't work. Now I get stucked in login page trying to logon with a domain user or admin acount:

![image](https://cloud.githubusercontent.com/assets/16647133/12292689/ece97150-b9d5-11e5-919e-128baf24eba2.png)

**Comment by juanfalguera** [comment]
Restarted server and now I can login again, but the first time logon issue persists. 

When AD users logs on for the first time, Teampass creates an account automatically for them, right? But, as the users don't have any permissions yet, probably the session variables used to store users id, roles, etc are null or blank, and somehow the system lets users in this condition to see all the items.

When the user logs on for the second time, the account is already created and the session variables are written correctly (I am guessing). This is way the issue happens only at first login.

Maybe there is a way to solve this, denying first time users to log on Teampass. If the account doesn't exists, Teampass creates it and gives a message on login screen informing that the account has been created and asking user to log on again.

Sorry if I am guessing to much... just trying to help...

**Comment by nilsteampassnet** [comment]
Any news?

**Comment by juanfalguera** [comment]
I think my guess was wrong. I saw you implemented the changes I suggested to block first login and reload the page, but when the new user logs on he still can see all the passwords. Loging off and loging on again and he can see nothing. Same thing then before. Issue continues, unfortunatelly.

**Comment by nilsteampassnet** [comment]
I don't see how it is possible because if the user is new and created I set a variable to true.
If it is set to true then identification cannot occurs and the page is reloaded.
So the only possibility that the case you are describing appear is that the user already exists in the Teampass DB.

Can you make me connected to your server with TeamViewer?

**Comment by juanfalguera** [comment]
This happens with new users recently create in Active Directory. So, I am sure they don't exists in Teampass DB before the first login.

I found another thing today:  at first login, user can see all passwords, but if you reload the page (F5), they are gone. It is not necessary to logoff and login again as we were thinking before.
I asked my IT Manager to open a Teamviewer connection, but the security policies of our company doesn't allow that. Sorry.

**Comment by juanfalguera** [comment]
Images showing sequence of events:

Fisrt login:

![image](https://cloud.githubusercontent.com/assets/16647133/12352344/56bc934a-bb6c-11e5-8c22-5d8319122b19.png)

Second Login:

![image](https://cloud.githubusercontent.com/assets/16647133/12352433/2c3a5912-bb6d-11e5-894b-5db5cd0abd93.png)

After "F5":

![image](https://cloud.githubusercontent.com/assets/16647133/12352460/6101511e-bb6d-11e5-8e53-f32bd542a5fd.png)


Notice that after F5 I can see only my personal folder. 

Also, a strange grey bar appears at the top in all pages for all users. I found there is something in the new version of page "load.php" that is doing that, because when I roolback to version 2.1.24 of that page, the grey bar is gone.

**Comment by Dureaghin** [comment]
This happens with me too. I'm using the latest Release 2.1.24 (4)

**Comment by nilsteampassnet** [comment]
Could it be possible for you to perform the next debug things for me (as I cannot reproduce)?

In file /sources/tree.php, find
```
	global $ret_json, $listFoldersLimitedKeys, $listRestrictedFoldersForItemsKeys, $tree, $LANG;
	
	
	// Be sure that user can only see folders he/she is allowed to
```
and replace by
```
	global $ret_json, $listFoldersLimitedKeys, $listRestrictedFoldersForItemsKeys, $tree, $LANG;

	// DEBUG ONLY
	$dbg1153 = fopen($_SESSION['settings']['path_to_files_folder']."/_debug.1153.txt", "a");
    fputs(
        $dbg1153,
        "\n\n-----\n\n".
        "forbiden_pfs : ".print_r($_SESSION['forbiden_pfs'], true)."\n" .
        'groupes_visibles : ' . print_r($_SESSION['groupes_visibles'], true) . "\n" .
        'list_restricted_folders_for_items : ' . print_r($_SESSION['list_restricted_folders_for_items'], true) . "\n" .            
        'listFoldersLimitedKeys : ' . print_r($listFoldersLimitedKeys, true) . "\n" .
        'listRestrictedFoldersForItemsKeys : ' . print_r($listRestrictedFoldersForItemsKeys, true). "\n"
    );
	
	// Be sure that user can only see folders he/she is allowed to
```

Then in file /sources/identify.php, find
```
                $_SESSION['nb_roles'] = 0;
```
and replace by
```
                $_SESSION['nb_roles'] = 0;
                $_SESSION['fonction_id'] = 0;
```

Can you then run on a new user and send me the debug file /files/_debug.1153.txt?

**Comment by s0ufiane** [comment]
Hello,
I encounter the same bug, the first connecting an AD user, all files are visible and password
you have found a solution to this bug

Thanks

**Comment by kcorupe** [comment]
@nilsteampassnet - I tried putting your debug info but it's not producing a debug file. This issue is preventing us from using teampass. Any fix for this yet?

`    global $ret_json, $listFoldersLimitedKeys, $listRestrictedFoldersForItemsKeys, $tree, $LANG;

   // DEBUG ONLY
    $dbg1153 = fopen($_SESSION['settings']['path_to_files_folder']."/_debug.1153.txt", "a");
    fputs(
        $dbg1153,
        "\n\n-----\n\n".
        "forbiden_pfs : ".print_r($_SESSION['forbiden_pfs'], true)."\n" .
        'groupes_visibles : ' . print_r($_SESSION['groupes_visibles'], true) . "\n" .
        'list_restricted_folders_for_items : ' . print_r($_SESSION['list_restricted_folders_for_items'], true) . "\n" .
        'listFoldersLimitedKeys : ' . print_r($listFoldersLimitedKeys, true) . "\n" .
        'listRestrictedFoldersForItemsKeys : ' . print_r($listRestrictedFoldersForItemsKeys, true). "\n"
    );`

`                $_SESSION['nb_roles'] = 0;
                $_SESSION['fonction_id'] = 0;
`

**Comment by kcorupe** [comment]
There is sort of a work around, if you enable "Teampass local users only" under LDAP settings. It works as you expect, although the downside is users need to be manually added but will still authenticate via Active Directory.

**Comment by jhrasko** [comment]
Hi there, I'm having the same problem as documented in #1297.
If there is some way I can assist you, just let me know, I'm fully virtualized so I can test literally everything for you. (I'm not very skilled in php but)
Currently we are on TP *26 but if needed I should be to find some snapshot from *25
 It is really important for us.
Thank you

**Comment by nilsteampassnet** [comment]
Can you do the next things?

* open file sources/identify.php
* set variables $debugLdap and $debugDuo to 1

* open file load.php
* search for `} else if (data[0].value == "new_ldap_account_created") {`
* inside this loop you will see `window.location.href="index.php"`
* replace by `window.location.href="logout.php"`

* Make a new try
* provide me the 2 generated files /files/duo.debug.txt and
/files/ldap.debug.txt

**Comment by ylysak** [comment]
Hi,
I have same problem too.
Are any way for fixing it?
Does developer plan to correct it?

thx

**Comment by jcboysha** [comment]
This is still a large issue.

**Comment by nilsteampassnet** [comment]
I can't test this as no LDAP system.

Please can someone provide access by Teamviwer so that I can debug?

**Comment by jcboysha** [comment]
Given the recent problems with Teamviewer, I would suggest a different solution, but I'm not sure what. 

Further, I'm trying my hardest to resolve the issue as well, I'll provide code to you if I can resolve the problem.

**Comment by nilsteampassnet** [comment]
With ammyy then? or Skype?

**Comment by jcboysha** [comment]
Those would be better, but regrettably, I can't allow you access to my environment for various reasons. Although, within the next week I may be able to set up a less critical environment for testing that I could allow you access to.

**Comment by chetanpachare** [comment]
Hi, 
I have the same Problem.

**Comment by tehnotronic** [comment]
Are you sure, that TeamPass should create a new account in TP database if new AD / LDAP user logs on? In my case it seems to give just login error and not let the user in, if it doesn't have TP account.

**Comment by tehnotronic** [comment]
Do you have "Teampass local users only" set to "no" under LDAP settings? In my setup, I have "yes".

**Comment by chetanpachare** [comment]
Finally, I have reached to the problem.
This problem can be solved by setting the option "Enable Personal folder feature= No " in team pass setting page.

Then try to login via LDAP users. You will not see any exiting folders.

Thanks.

**Comment by ylysak** [comment]
It's not a decision of problem: I have folders for all, but I haven't personal folder. this feature need for me and other staff

**Comment by klou** [comment]
#1381

**Comment by Qutianer** [comment]
Just to highlight workaround:
1. In "LDAP settings" set "Teampass local users only".
2. Precreate account for LDAP users (auth still works via LDAP)
https://github.com/nilsteampassnet/TeamPass/issues/1153#issuecomment-210125944

**Comment by jsandova** [comment]
This issue still is present with the latest version of 2.1.27. What is taking so long to fix this bug? Also on version 2.1.27 my MAF with DUO is no longer working.

**Comment by nilsteampassnet** [comment]
Can you please refer to #1530

**Comment by lukasi** [comment]
I have also experiancing the same issue on 2.1.27
