### ISSUE TITLE
2.1.24 Cannot login after fresh install

### ISSUE THREAD

**Issue by KuroNeko-san** [nilsteampassnet/TeamPass#1154]
After fresh installation of TeamPass version 2.1.24 i cant login as "admin", /sources/identify.php says "Hacking attempt..."

var_dump($_SESSION) after session_start() on line 20 says "array => empty"

My system:

# uname -a
Linux srvwww 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/centos-release
CentOS release 6.7 (Final)
# nginx -v
nginx version: nginx/1.8.0
# php -v
PHP 5.5.31 (cli) (built: Jan  6 2016 13:07:32)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
# mysql -V
mysql  Ver 14.14 Distrib 5.5.44, for Linux (x86_64) using readline 5.1

Session storage for PHP - Memcached

# memcached -V
memcached 1.4.22

If you want to debug this on my server - contact me by Skype "raven_kuroneko-san".
Thanks.

**Comment by nilsteampassnet** [comment]
Did you take release 2.1.24.4?

**Comment by KuroNeko-san** [comment]
Yes, i install 2.1.24.4 from https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.24.4

**Comment by jjurkus** [comment]
What is the output of 'yum list installed | grep php'?

**Comment by KuroNeko-san** [comment]
All tests during installation was OK, output:

# yum list installed | grep php
php55.x86_64                         2.1-1.el6.remi                   @remi
php55-php-bcmath.x86_64              5.5.31-1.el6.remi                @remi
php55-php-cli.x86_64                 5.5.31-1.el6.remi                @remi
php55-php-common.x86_64              5.5.31-1.el6.remi                @remi
php55-php-devel.x86_64               5.5.31-1.el6.remi                @remi
php55-php-fpm.x86_64                 5.5.31-1.el6.remi                @remi
php55-php-gd.x86_64                  5.5.31-1.el6.remi                @remi
php55-php-imap.x86_64                5.5.31-1.el6.remi                @remi
php55-php-ldap.x86_64                5.5.31-1.el6.remi                @remi
php55-php-mbstring.x86_64            5.5.31-1.el6.remi                @remi
php55-php-mcrypt.x86_64              5.5.31-1.el6.remi                @remi
php55-php-mysqlnd.x86_64             5.5.31-1.el6.remi                @remi
php55-php-opcache.x86_64             5.5.31-1.el6.remi                @remi
php55-php-pdo.x86_64                 5.5.31-1.el6.remi                @remi
php55-php-pear.noarch                1:1.10.1-1.el6.remi              @remi
php55-php-pecl-apcu.x86_64           4.0.8-1.el6.remi                 @remi
php55-php-pecl-geoip.x86_64          1.1.0-2.el6.remi                 @remi
php55-php-pecl-jsonc.x86_64          1.3.9-1.el6.remi                 @remi
php55-php-pecl-jsonc-devel.x86_64    1.3.9-1.el6.remi                 @remi
php55-php-pecl-memcache.x86_64       3.0.8-5.el6.remi                 @remi
php55-php-pecl-rar.x86_64            3.0.2-3.el6.remi                 @remi
php55-php-pecl-xdebug.x86_64         2.3.3-1.el6.remi                 @remi
php55-php-pecl-zip.x86_64            1.13.1-1.el6.remi                @remi
php55-php-process.x86_64             5.5.31-1.el6.remi                @remi
php55-php-xml.x86_64                 5.5.31-1.el6.remi                @remi
php55-runtime.x86_64                 2.1-1.el6.remi                   @remi

**Comment by KuroNeko-san** [comment]
Any suggestions?

**Comment by jjurkus** [comment]
Not much from me. I was wondering how you got PHP5.5 on CentOS6, because the default is PHP5.3, that's why I asked. I see you have used that remi repository, and it seems to be up to date.
You probably have checked out if it's not trying to use a part of PHP5.3, right? The only other thing I can say is; you might want to try Apache (httpd) as webserver. After installing PHP it makes a .conf file in /etc/httpd/conf.modules.d/ which tells httpd to load libphp5.so
I'm not sure if nginx needs a similiar .conf file and if that is created automatically. The default .conf in my apache setup of course refers to the libphp5.so in the default location.

**Comment by KuroNeko-san** [comment]
Yes, php55 installed from remi and i have plans to migrate on php7.

I have Apache, but i use it only for SVN. On my server installed more than one site, Apache is slow on high load.

Config files is not a problem for me. If needed, i will test TeamPass on php53+apache and php53+nginx on OpenVZ containers, but developer team must keep in mind - php53 NOT SUPPORTED ANYMORE.
Another thing - try to change session storage to default (files).

**Comment by nilsteampassnet** [comment]
​As described [HERE](http://teampass.net/requirements​) the minimum version
is 5.4.0.
Development is done with version 5.5.

@KuroNeko-san, tried to contact you yesterday evening by Skype to check
with you what is going wrong.

**Comment by KuroNeko-san** [comment]
Thanks @nilsteampassnet for debugging, most likely problem in my session storage mechanism. It fixed for now.
