### ISSUE TITLE
2.1.24. Cant install 

### ISSUE THREAD

**Issue by vicspb** [nilsteampassnet/TeamPass#1155]
Hi!
When I'm try to install, I'm have error in apache log:
PHP Fatal error:  Uncaught exception 'Exception' with message 'I cannot generate a secure pseudo-random key. Please install OpenSSL or Mcrypt extension' in /var/www/webapps/teampass/sources/sessions.php:42\nStack trace:\n#0 /var/www/webapps/teampass/sources/sessions.php(81): CryptSession->_randomKey(32)\n#1 [internal function]: CryptSession->open('/tmp', 'PHPSESSID')\n#2 /var/www/webapps/teampass/install/install.queries.php(15): session_start()\n#3 {main}\n  thrown in /var/www/webapps/teampass/sources/sessions.php on line 42, referer: http://10.0.4.41/teampass/install/install.php

but in web-interface openssl and mcrypt loaded.

**Comment by jjurkus** [comment]
I think if the maintainer responds he will ask you more information about your OS and php version.

**Comment by vicspb** [comment]
Distrib: AltLinux P7
in attachment of this message: phpinfo in pdf file and screen of instllation process.
[screen_and_phpinf.zip](https://github.com/nilsteampassnet/TeamPass/files/95490/screen_and_phpinf.zip)

**Comment by jjurkus** [comment]
Well, if it hangs like that there is a module missing, I've had that problem too.
Can you use your package manager to make a list of installed packages?

**Comment by nilsteampassnet** [comment]
PHP Version 5.5.15

Loaded modules are on my test computer

core
mod_win32
mpm_winnt
http_core
mod_so
mod_access_compat
mod_actions
 mod_alias
mod_allowmethods
mod_asis
mod_auth_basic
mod_authn_core
 mod_authn_file
mod_authz_core
mod_authz_groupfile
mod_authz_host
 mod_authz_user
mod_autoindex
mod_cgi
mod_dav_lock
mod_dir
mod_env
 mod_headers
mod_include
mod_info
mod_isapi
mod_log_config
mod_cache_disk
 mod_mime
mod_negotiation
mod_proxy
mod_proxy_ajp
mod_rewrite
 mod_setenvif
mod_socache_shmcb
mod_ssl
mod_status
mod_version mod_php5

**Comment by vicspb** [comment]
# rpm -qa |grep php
php5-mysqli-5.5.24.20150415-alt1
php5-cgi-5.5.24.20150415-alt0.M70P.1
phpMyAdmin-apache2-4.2.8.1-alt1
phpMyAdmin-4.2.8.1-alt1
php5-memcache-2.2.6-alt9.5.5.24.20150415.alt1
php5-pgsql-5.5.24.20150415-alt1.2
php5-mysql-5.5.24.20150415-alt1
php5-fileinfo-5.5.24.20150415-alt1
php5-dom-5.5.24.20150415-alt1
php-base-2.7-alt3
php5-xsl-5.5.24.20150415-alt1
php5-ldap-5.5.24.20150415-alt0.M70P.1.1
php5-mcrypt-5.5.24.20150415-alt1
php5-5.5.24-alt0.M70P.1
php5-exif-5.5.24.20150415-alt1
php5-suhosin-0.9.35-alt5.5.24.20150415.alt1
php5-xmlrpc-5.5.24.20150415-alt1
apache2-mod_php5-5.5.24.20150415-alt0.M70P.1
php5-curl-5.5.24.20150415-alt1
php5-facedetect-5.5.24.20150415-alt1
php5-dba-5.5.24.20150415-alt1
php5-gd2-5.5.24.20150415-alt1
php5-imap-5.5.24.20150415-alt1.1
php5-libs-5.5.24-alt0.M70P.1
php5-imagick2-5.5.24.20150415-alt0.M70P.1.1
php5-mbstring-5.5.24.20150415-alt1
php5-zip-5.5.24.20150415-alt0.M70P.1

**Comment by jjurkus** [comment]
I am on CentOS 7, so you can't compare directly, however;

I had to use php5-mysqlnd instead of php5-mysql
Also php5-bcmath is installed, but this was (I think) a dependency of another php module.

yum list installed | grep php
php.x86_64                            5.4.16-36.el7_1                 @base
php-bcmath.x86_64                     5.4.16-36.el7_1                 @base
php-cli.x86_64                        5.4.16-36.el7_1                 @base
php-common.x86_64                     5.4.16-36.el7_1                 @base
php-ldap.x86_64                       5.4.16-36.el7_1                 @base
php-mbstring.x86_64                   5.4.16-36.el7_1                 @base
php-mcrypt.x86_64                     5.4.16-3.el7                    @epel7
php-mysqlnd.x86_64                    5.4.16-36.el7_1                 @base
php-pdo.x86_64                        5.4.16-36.el7_1                 @base

**Comment by nilsteampassnet** [comment]
Is your php compiled with mysqlnd?

**Comment by vicspb** [comment]
At the same server installed GLPI (glpi-project.org) and work fine.

**Comment by nilsteampassnet** [comment]
@vicspb  I don't know how works GLPI and if it uses mysqlnd.
But what is sure is that based on the grep you performed, your server doesn't have mysqlnd installed as I can view `php5-mysql-5.5.24.20150415-alt1`

**Comment by vicspb** [comment]
php-mysqlnd installed.
How I can test it?

**Comment by nilsteampassnet** [comment]
Just launch the installer

**Comment by vicspb** [comment]
I'm launch the installer. All tests was OK, but after press "Launch" the system hangs.
![screen](https://cloud.githubusercontent.com/assets/16699458/12635888/070e96e0-c599-11e5-82d4-196de251fec1.png)

**Comment by nilsteampassnet** [comment]
Please provide me an access with Teamviewer.
Skype me at nils.teampass

**Comment by nilsteampassnet** [comment]
Problem was PHP version.
It is required to have at least version 5.5.0

**Comment by jjurkus** [comment]
I have TeamPass working with PHP 5.4 on CentOS 7:

# yum list installed | grep php
php.x86_64                            5.4.16-36.el7_1                 @base
php-bcmath.x86_64                     5.4.16-36.el7_1                 @base
php-cli.x86_64                        5.4.16-36.el7_1                 @base
php-common.x86_64                     5.4.16-36.el7_1                 @base
php-ldap.x86_64                       5.4.16-36.el7_1                 @base
php-mbstring.x86_64                   5.4.16-36.el7_1                 @base
php-mcrypt.x86_64                     5.4.16-3.el7                    @epel7
php-mysqlnd.x86_64                    5.4.16-36.el7_1                 @base
php-pdo.x86_64                        5.4.16-36.el7_1                 @base
