### ISSUE TITLE
do not use flash for clipboard

### ISSUE THREAD

**Issue by frankenstein91** [nilsteampassnet/TeamPass#1157]
can you change the clipboard to something like this http://stackoverflow.com/questions/17527870/how-does-trello-access-the-users-clipboard

I shoud help some flash haters.

**Comment by nilsteampassnet** [comment]
​Since 2.1.24, copy to clipboard don't rely on Flash but HTML5 data
attributes.

**Comment by frankenstein91** [comment]
I think not. Some of my users have problems to copy if the flash version is
to old.
Am 14.01.2016 13:09 schrieb "Nils Laumaillé" <notifications@github.com>:

**Comment by frankenstein91** [comment]
To supplement we use 2.1.24.

**Comment by coiladn** [comment]
Same PB
copy/paste, OK under linux, KO under Windows
