### ISSUE TITLE
Can't Change admin Password

### ISSUE THREAD

**Issue by Harry-89** [nilsteampassnet/TeamPass#1158]
Hello,

when I try to change the admin Password, nothing is happening.

The Console puts the follwing.

Error: <br>
Query: SELECT complexity
                FROM teampass_roles_title
                WHERE id IN ()
                ORDER BY complexity DESC<br>

Can you help me with this?

**Comment by jjurkus** [comment]
# mysql -u root -p
> grant all privileges on teampassdb.* to teampassuser@localhost identified by "your passwordhere";
> \q

Of course change teampassdb and teampassuser if you have created a different database and/or user.

**Comment by Harry-89** [comment]
That's allready done.
The DB User has root privileges on his Database.

**Comment by jjurkus** [comment]
Sorry, I was mistaken. I was thinking incorrectly the dbuser password and admin password were the same. I already looked at my installation notes and failed to see they were different. :-(

**Comment by nilsteampassnet** [comment]
Is this solved?

**Comment by Harry-89** [comment]
No the problem is still there.
Still getting the error from my initial post

**Comment by nilsteampassnet** [comment]
Can you provide me an access with Teamviewer?

Skype me at nils.teampass

**Comment by Harry-89** [comment]
Unfortunately that's not possible, sorry.
But if you tell me what to do, I can provide Screenshots.

I'm very fit in php and jquery.

Thank you

**Comment by Harry-89** [comment]
Is there any update so far?

**Comment by MannyC** [comment]
This is happening to me too.  The error doesn't get reported on the front end, it just keeps saying "Please wait".   I have to warn you, that's pretty disconcerting for a user!  It's what happened when I first tried to create a folder too (I think because I didn't select a parent).

The error is also somewhat different, and I'm changing the password of an administrative user, not the admin user itself.

```
Error: <br>
Query: SELECT complexity
                FROM teampass_roles_title
                WHERE id IN (,1)
                ORDER BY complexity DESC<br>
```

**Comment by chc88** [comment]
With the latest version (2.1.26 - 10) I still have a problem while changing the admin-password.

If i look at the communicaties, it is strange that the queries file is called, but says that is has nothing to do...

POST https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx/sources/main.queries.php
200 OK

Parameters: application/x-www-form-urlencoded
94afe3bbdb18fbae93e66e04c...	: aec477dd8cccc350dd93b92e0e362e5f53c0a0cebb27f758b1
change_pw_origine	: user_change
complexity	: 60
data	: {"new_pw":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
type	: change_pw

Answer: [ { "error" : "nothing_to_do" } ]

**Comment by nilsteampassnet** [comment]
This is correct in commit https://github.com/nilsteampassnet/TeamPass/commit/7c619d2ecb0403c4016a57509f0acfcd28d7c18c
