### ISSUE TITLE
Feature Request: Dual Contol Passwords.

### ISSUE THREAD

**Issue by cenasmynet** [nilsteampassnet/TeamPass#1161]
The dual control option provides an added level of security for users to see passwords.
It ensures that no single user knows or controls this kind of password.

This option requires that two users participate when accessing and resetting a password.
Each user defines/see only a portion of the password. 
The set of the password becomes the union of the two passwords.

**Comment by nilsteampassnet** [comment]
Could be done.
What is the context of use?

**Comment by cenasmynet** [comment]
So basically my idea of this, is a password with to parts, left and right, when a user access a password only access the left side, if other user try to access this item he can only see the right part.

So the first user only see the left side and everybody else see the right part.

Other way

Some other option is to simply have left and right users, and the left see the left part and the right see the rest. That can be defined in user creation and can not be changed. 

I think the best option is the first one, but a is more risky to.

**Comment by nunompad** [comment]
That would is a good featute.
