### ISSUE TITLE
DataTables warning: table id=t_users - Invalid

### ISSUE THREAD

**Issue by pokidov** [nilsteampassnet/TeamPass#1162]
Redirect from IIS RewriteURL to Apache, have this issue.
In local environment with local IP addres there no problems.
Only when i want to add new user. 
Russian Language.
Thank you.

**Comment by pokidov** [comment]
IIS Request Filtering Edit  and change maximum parameters

**Comment by nilsteampassnet** [comment]
Does this mean that you solved it?

Can you explain with what settings on your server?

Thanks

**Comment by pokidov** [comment]
Yes, it is solved. The parameters was changed maximum allowed conten length, url length, query string.

**Comment by ilfrigorifero** [comment]
Worked for me.

**Comment by ajmell** [comment]
I get this error with Firefox/Apache (no IIS or IE involved!).
Unfortunately now I'm not getting to see any users at all in Users management.
The url is 2295 characters long .. which seems to be within limits set by Apache and FF.
