### ISSUE TITLE
lpad data is not encrypted even if specifiying "ldap SSL on"

### ISSUE THREAD

**Issue by vmindru** [nilsteampassnet/TeamPass#1163]
how to reproduce: 
enble ldap with SSL 
start tcpdump 
observ that ldap data is not encrypted 

What is strange is that even if remove entirely the adLDAP.php file, teampass still somehow authentificates against LDAP  with non encrypted data.

**Comment by adamminter4** [comment]
This is happening for version 2.1.24, btw.

**Comment by vmindru** [comment]
Can someone fix typo ? It's LDAP not lpad.
