### ISSUE TITLE
.

### ISSUE THREAD

**Issue by paragonie-scott** [nilsteampassnet/TeamPass#1164]

**Comment by nilsteampassnet** [comment]
Do we have examples that permits to "crack" an existing encrypted string?
Any suggestions of similar library  to use?

**Comment by paragonie-scott** [comment]
I outlined the vulnerabilities in my email to oss-sec, and also made recommendations based on my experience with crypto/appsec: http://www.openwall.com/lists/oss-security/2016/01/16/3

In short, libsodium is your best bet, but if you can't install PHP extensions, use [defuse/php-encryption](https://github.com/defuse/php-encryption).

**Comment by nilsteampassnet** [comment]
Thanks.

libsodium seems indeed very good but requires this PHP extension that some users of Teampass may not have the right to install.
So I will go on in implemented Defuse one.
This will be done for 2.1.26 ... I'm too close to 2.1.25 to not release it now.
