### ISSUE TITLE
2.1.24 IE11 Bug for Unmasking Passwords

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1165]
Unable to unmask passwords using IE11. It just flashes real quick but does not work for long press. In the developer tools console I see this message every time I try to unmask a password. I think it may have to do with the code on the items.load.php but I have not been able to successfully fix this.

Tooltipster: one or more tooltips are already attached to this element: ignoring. Use the "multiple" option to attach more tooltips.

**Comment by tiruser** [comment]
Have a similar problem.
If I click on the eye "Show Password" or "Mask/Display the Password" then the Password disappears. The field gets White and the Password is gone. I have to logout and Login again to get the Passwords back.

Copy Password to clipboard didn't work too

**Comment by tiruser** [comment]
We tested 2.1.24 and 2.1.25.2 with Firefox Version 44 and there is the same problem.
It just flashes real quick but does not work for long press.
