### ISSUE TITLE
Problem with creating new passwords

### ISSUE THREAD

**Issue by Prideth** [nilsteampassnet/TeamPass#1170]
In the versions 2.1.24, 2.1.23, 2.1.22 there are not all icons. For example the icons for creating passwords, adding favourites, ...

Is this a bug or does anybody know how to fix it?

**Comment by nilsteampassnet** [comment]
I don't really understand th point.
Do you have screen-captures?
Did you enable the options you want?
Did you set up Folders, Roles and Users access rights?

**Comment by Prideth** [comment]
I can not add/show any passwords. 
I set up 2 Folders, 2 Roles and 3 Users. 
Screenshots will be attached later

**Comment by ilfrigorifero** [comment]
Hi,
whenever I want to create a new password, this is what I get:
![screenshot_2](https://cloud.githubusercontent.com/assets/16708728/12549110/4527809e-c35b-11e5-9718-5e05e9111ad9.png)
System's running an IIS 8 with MariaDB and PHP 5.6, if that helps.

**Comment by ilfrigorifero** [comment]
Complete error, sorry.
![screenshot_3](https://cloud.githubusercontent.com/assets/16708728/12549165/a85345b8-c35b-11e5-907a-b929e0e6dc1b.png)

**Comment by nilsteampassnet** [comment]
Can you try to run this query

ALTER TABLE teampass_items CHANGE pw_len pw_len INT(5) NULL DEFAULT NULL;

**Comment by Prideth** [comment]
I have added the Screenshots. Hope you know where the problem could be

**Comment by nilsteampassnet** [comment]
Did you try the query indicated jsut before?

**Comment by Prideth** [comment]
ok works now
