### ISSUE TITLE
Top-level folder entry count is 0

### ISSUE THREAD

**Issue by fthiery** [nilsteampassnet/TeamPass#1172]
The count should be recursive; otherwise, it makes you think that no passwords are there unless you unfold them

**Comment by nilsteampassnet** [comment]
Good proposition

**Comment by paratustelco** [comment]
Agreed I also find it is strange to have 0 displayed even though there are subfolders with passwords in that folder.

**Comment by nilsteampassnet** [comment]
You use feature `Show more counters in folders tree` to show this.
