### ISSUE TITLE
TeamPass 2.1.25 is unable to write LDAP settings to the teampass_misc table

### ISSUE THREAD

**Issue by jamesepwelch** [nilsteampassnet/TeamPass#1175]
I would just like to say that I am really liking this product and am very grateful that you created it and made it open source. 

So I did a fresh install of 2.1.25 and when attempting to turn on LDAP I would hit save and it would bring me back to TeamPass settings tab and wouldn't save that it switched over. I was finally able to get it to switch over to LDAP by changing a settings somewhere else, going back to LDAP, enabling it and then clicking save. I would then change the LDAP default options, however when attempting to log in with the LDAP user I had setup it would always state inactive user.

So what I did to get around this was install 2.1.24, configure the LDAP settings and then change over to 2.1.25 and everything works just fine, so I am assuming the issue is that 2.1.25 is writing to the misc table. I could be wrong as I didn't do a whole lot of testing.

I am running CentOS 7 64 bit minimal install 1511 with XAMPP 5.5.30.

Thank you again and cheers.

**Comment by nilsteampassnet** [comment]
Thanks.

Could you find back the error you get in your server's logs?
Indeed with the explanation I could not understand where is the issue and I can't test LDAP things as I don't have such server. This part is only checked by deep code reading.

**Comment by nilsteampassnet** [comment]
I think I understand why "enable ldap" was not stored.
I will commit a quick change
