### ISSUE TITLE
Query for List of Users with Personal Items

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1176]
Last time I was helped to obtain a query that could list the users with subfolders under their person folder. Now I am wondering if there is a query to get a list of users that have personal items in general. My goal is to email just those users in prep for upgrading to 2.1.24 and give instructions around changing their personal salt key.

**Comment by nilsteampassnet** [comment]
This one is more easy 

`SELECT u.`name`,u.`lastname`,u.`email` FROM `teampass_users` AS u RIGHT JOIN `teampass_nested_tree` AS t ON (t.title = u.id) WHERE t.title = u.id AND t.personal_folder = 1 `

**Comment by hexxamillion** [comment]
Super! Thanks!
