### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by xFRaNeRx** [nilsteampassnet/TeamPass#1177]
I've seen, in php files, that API supports the find operator, but documentation don't speak about them. There's any complete documentation about API?

I would like to modify items from API. Is this possible? Is this feature in roadmap?

Thanks for your job !
Fran

**Comment by nilsteampassnet** [comment]
"Find" is called "Read" in [API documentation](http://teampass.net/2014-05-18-teampass-api/).
So check chapter, "Read data" and it should fit what you want.

> I would like to modify items from API. Is this possible? Is this feature in roadmap?
Yes absolutely. It should have been delivered for 2.1.25 but I could not do it (time issue).
So it will be for next version ;)

**Comment by xFRaNeRx** [comment]
Folder id is the numeric id from database? Can I get the id having item label only?

I'll wait for next version to modify items !

**Comment by xFRaNeRx** [comment]
Hello,

Anybody has an answer for my latest question?

There is any way to get the numeric id of an item getting only his name? I need this feature to use the API.

Thanks.

**Comment by nilsteampassnet** [comment]
> Folder id is the numeric id from database?
Yes. The ID of a folder is also visible with tooltip when mouse cursor is over a folder

> There is any way to get the numeric id of an item getting only his name?
Can you please reformulate because I'm not sure to understand?

**Comment by xFRaNeRx** [comment]
Sorry for the bad explanation.

What I like to do is make an api call passing the folder or item label (text) as argument and get the item id as answer.
