### ISSUE TITLE
Role Management

### ISSUE THREAD

**Issue by houstek** [nilsteampassnet/TeamPass#1179]
On a fresh installation of Teampass 2.1.25 on CENTOS 7, no role is displayed on the Management Role page and I have an error in the log.
I can create roles and assign them to users
![2016-01-30_19h32_14](https://cloud.githubusercontent.com/assets/16977281/12697594/37a7f864-c788-11e5-9660-0c66d44410ca.png)

`SELECT * FROM teampass_roles_title WHERE id IN (,1)<br />You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1)' at line 1@/sources/roles.queries.php`

**Comment by MarMarAba** [comment]
same problem in a upgrade installation

**Comment by nilsteampassnet** [comment]
Can you please try the next?

In file /sources/roles.queries.php, find (around line 234)

`else  $where = " WHERE id IN (".str_replace(";", ",", $_SESSION['fonction_id']).")";`

replace it by

`else  $where = " WHERE id IN (".array_filter(str_replace(";", ",", $_SESSION['fonction_id'])).")"`

**Comment by houstek** [comment]
> new

sh

**Comment by nilsteampassnet** [comment]
Ok if this occurs, this means that you have no roles set as allowed on your user.
So indeed the query is not good.
Here below a complete change

`            //count nb of roles
            $arrUserRoles = array_filter(str_replace(";", ",", $_SESSION['fonction_id']));
            if (empty($_SESSION['fonction_id']) || count($arrUserRoles) == 0) $where = "";
            else  $where = " WHERE id IN (".array_filter(str_replace(";", ",", $_SESSION['fonction_id'])).")";
            DB::query("SELECT * FROM ".prefix_table("roles_title").$where);`

**Comment by nilsteampassnet** [comment]
Oops I did the change too fast.
I made a mistake in my proposed solution.
Let post a correction

**Comment by nilsteampassnet** [comment]
Here is the correct fix.
In file /sources/roles.queries.php, replace by
```
            //count nb of roles
            if (empty($_SESSION['fonction_id'])) $where = "";
            else  $where = " WHERE id IN (".str_replace(";", ",", $_SESSION['fonction_id']).")";
```
by
```
            //count nb of roles
            $arrUserRoles = array_filter($_SESSION['user_roles']);
            if (count($arrUserRoles) == 0) $where = "";
            else  $where = " WHERE id IN (".implode(',', $arrUserRoles).")";
```

**Comment by houstek** [comment]
perfect :) 
thx for this fix

**Comment by MarMarAba** [comment]
Now works fine.

The new version is more stable and reliable, Very good work! Thanks!!

**Comment by juranich** [comment]
Fixed my issue. Thank you

**Comment by necarnot** [comment]
Bonjour,

In the TeamPass **2.1.25** web GUI logs page, I have many errors like this : 

`SELECT complexity FROM teampass_roles_title WHERE id IN (,1,3,2,4) ORDER BY complexity DESC<br />You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1,3,2,4) ORDER BY complexity DESC' at line 3@/sources/main.queries.php`

Looking at sources/main.queries.php, and looking at the users table, I see that some lines in the fonction_id column contains strings like "**;**1;3;2;4" (Pay attention to the first semi-colon).
That leads to str_replace to generate a string like "**,**1,2,3,4" (Pay attention to the first comma), that fails when used in a SQL query.

I saw that you proposed a patch in another query to change str_replace in favor of something more clever.
Might I ask you to patch this **line 95 of sources/main.queries.php** ?

Thank you.
