### ISSUE TITLE
Teampass 2.1.25 : Ldap AD Authentification

### ISSUE THREAD

**Issue by houstek** [nilsteampassnet/TeamPass#1180]
The authentification LDAP does not work. Having activated the mode DEBUG, the connection with the Active Directory is OK, but the users cannot authenticate.

`Get all LDAP params : 
mode : 1
type : windows
base_dn : DC=xxxxx,DC=local
search_base : 
bind_dn : 
bind_passwd : 
user_attribute : 0
account_suffix : dc=xxxxx,dc=local
domain_controllers : serxxdc02.xxxxx.local
use_ssl : 0
use_tls : 0

---

Get all ldap params : 
base_dn : DC=xxxxx,DC=local
account_suffix : dc=xxxxx,dc=local
domain_controllers : servxxdc02.xxxxx.local
use_ssl : 0
use_tls : 0

---

Create new adldap object : Success

After authenticate : Success

ldap status : `

![image](https://cloud.githubusercontent.com/assets/16977281/12712816/7396b786-c8cb-11e5-96de-7022403b6253.png)

**Comment by houstek** [comment]
The LDAP authentification works with IE...

**Comment by jjurkus** [comment]
You might want to try changing your LDAP suffix, to "@ldapserver.local", this worked for me.

**Comment by miroslavkokrda** [comment]
I have in this row suffix: @ad.i.cz 
And it works fine ...

**Comment by Nepharus** [comment]
I made this mistake at first as well, but resolved it by setting the first row to: @somename.local
