### ISSUE TITLE
Don't load server information

### ISSUE THREAD

**Issue by gusfersa** [nilsteampassnet/TeamPass#1182]
Don't load server information
Release 2.1.25.0 and 2.1.25.2

http://domain.com/index.php?page=manage_main
<img width="637" alt="captura de pantalla 2016-02-01 a las 16 25 03" src="https://cloud.githubusercontent.com/assets/3491987/12732074/d4b47d60-c901-11e5-9154-a0d186d2d6af.png">

**Comment by jjurkus** [comment]
Also the same with 2.1.24(4), so I guess something is offline.
Which isn't a shame, last time I saw it it still said the current TeamPass version was 2.1.22
