### ISSUE TITLE
Syntax Error on personal folders option

### ISSUE THREAD

**Issue by paratustelco** [nilsteampassnet/TeamPass#1183]
Under admin, users page. Turning the Personal Folder option on or off gives a "SyntaxError: Syntax error" popup.
The option is however turned on or off, so the error has no effect on the setting it seems, but still annoying.

**Comment by Ricardo-Custodio** [comment]
Same error for me too
firebug screenshot to help 

![teampass](https://cloud.githubusercontent.com/assets/12646960/12821708/712045b0-cb5c-11e5-9a2a-3be2c1c37401.png)
