### ISSUE TITLE
upgrade to 2.1.25 results in 500 error, cannot access at all

### ISSUE THREAD

**Issue by bcwhittle** [nilsteampassnet/TeamPass#1187]
I tried today to upgrade to 2.1.25. When I did so, and ran the upgrade.php, then I only get a http 500 server error in response.

Looking at the Apache logs, I see
"GET /index.php HTTP/1.1" 500 343 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari 537.36"

So I copied the files back from 2.1.24, and it works again.

**Comment by Hellbartonio** [comment]
I second that.
