### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by Roman112** [nilsteampassnet/TeamPass#1191]
I cannot upload files as attachments to items after TeamPass (2.1.25) installation. 
1. I go to item's "Files & Images", press "select "and choose file on my computer
2. Press "Start uploading files" button there
3. it adds 100% after filename
   ![image](https://cloud.githubusercontent.com/assets/8392446/12847248/8a938e9e-cc1a-11e5-934c-090fa6000e1d.png)
4. The I press "Save" but I don't see file in " Files & Images:" or any errors.
   Also I don't see new file in folder "/files" or "/upload".
   Permissions to those folders are 777 with "www-data" owner

**Comment by gusfersa** [comment]
I have the same problem

**Comment by dunz0r** [comment]
I have this issue as well. It seems that the _POST isn't passed in it's entirety to `upload.attachments.php`.
Adding `error_log("####".print_r($_POST));` to line 34 just produces
`[Mon Feb 08 13:41:10 2016] [error] [client 10.210.0.118] FastCGI: server "/fcgi-bin-php5-fpm" stderr: PHP message: ####1, referer: https://teampass.domain/index.php?page=items` in my log.
If I look at the response in the POST from `upload.attachments.php` I see
`    Array
    (
    )
    {"jsonrpc" : "2.0", "error" : {"code": 110, "message": "No Session was found."}, "id" : "id"}`

**Comment by gtslide** [comment]
I found the issue by accident by comparing my local and production environments.
If /includes/libraries/csrfp/js/csrfprotector.js is not loaded, then the upload and import csv/xml will work.

I have not found the root cause yet but for those who need this features (upload/import) urgently you can rename the jsUrl in includes/libraries/csrfp/libs/csrfp.config.php to something else so that it does not load the actual js file.

**Comment by gusfersa** [comment]
Is working, but configuration have this issue #1181

**Comment by ilfrigorifero** [comment]
Having the same problem, unfortunately. No errors in log, though (apache2/error.log)
Ubuntu LTS Server

**Comment by redowk** [comment]
same problem

**Comment by dataegg** [comment]
same problem also here

**Comment by morrthal** [comment]
Same problem. Is there any workaround?

**Comment by redowk** [comment]
Sorry, I don't remember what I did to bypass this. It was some time ago!
If I come by it again, I'll mail you.
Regards and good luck

**Comment by redowk** [comment]
Thanks for sharing your experience.

Teampass should run as the apache user (in case of apache or any other user
your webserver uses).
Knowing that you can even do a chmod 700 on that folder, as long as it is
owned by the user where the webserver was spawned from.
I'll probably do a "chown -R apapche.apache /path/to/folder/" and a " chmod
-R 750 /path/to/folder/"
Hope this helps you.
(I don't have remote access from where I am to the site where I have
teampass installer but I think my setup has those permissions).
Regards
Tiago

**Comment by ptcuops** [comment]
I have the exact same experience as the original poster (everything seems to work, but after saving and returning, no files are displayed), however I "do" see a new file in the upload folder. It just doesn't show up in the UI. I have verified that jsUrl has the correct URL in the csrfp.config.php file and the permissions/ownership of the upload folder appear to be correct. 

I'm not sure it's relevant, but I'm using the docker image.

**Comment by nilsteampassnet** [comment]
what version?

**Comment by ptcuops** [comment]
2.1.27 - I see that there appears to be a newer version at docker hub. I'll give it a try.

**Comment by ptcuops** [comment]
No, no difference using teampass/teampass:latest.

I see the following in the logs
>4/13/2017 2:20:30 PM==> /var/log/apache2/error.log <==
>4/13/2017 2:20:30 PM[Thu Apr 13 20:20:29.283035 2017] [:error] [pid 15] [client 10.42.226.88:56884] PHP Notice:  Undefined variable: link in /teampass/www/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.mydomain.com/index.php?page=items
>4/13/2017 2:20:30 PM[Thu Apr 13 20:20:29.283077 2017] [:error] [pid 15] [client 10.42.226.88:56884] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /teampass/www/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.mydomain.com/index.php?page=items
>4/13/2017 2:20:30 PM[Thu Apr 13 20:20:29.452805 2017] [:error] [pid 16] [client 10.42.226.88:56892] PHP Notice:  Undefined variable: link in /teampass/www/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.mydomain.com/index.php?page=items
>4/13/2017 2:20:30 PM[Thu Apr 13 20:20:29.452836 2017] [:error] [pid 16] [client 10.42.226.88:56892] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /teampass/www/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.mydomain.com/index.php?page=items
