### ISSUE TITLE
Cannot set up encryption of attachments

### ISSUE THREAD

**Issue by Roman112** [nilsteampassnet/TeamPass#1192]
I cannot set up encryption of attachments in TeamPass (2.1.25), Ubuntu 14.04:
1. I go to "TeamPass settings" under admin user
2. I change "No" to "Yes" in "Enable encryption of Items attachments"
   ![image](https://cloud.githubusercontent.com/assets/8392446/12847420/bcce3dfe-cc1b-11e5-9696-6c04fb18ee29.png)
3. Then I press "Save" but after that I still see "No" in "Enable encryption of Items attachments".
   Browser refresh doesn't help and it works for other similar settings on that web page.

**Comment by nilsteampassnet** [comment]
THere was a bug on this.
Your change was never stored.
Commit in branch development done today.

**Comment by scbnmoody** [comment]
Awesome! Looking forward to the next release
