### ISSUE TITLE
Unable to import xlm and csv files

### ISSUE THREAD

**Issue by matiasba** [nilsteampassnet/TeamPass#1198]
I´m unable to do any kind of importing in version 2.1.25

This is the simplest text that and tried to import as an csv file:

"Account","Login Name","Password","Web Site","Comments"
"vmware","root","apass","192.168.1.68","site.com"
"xen","root","somepass","192.168.9.77","test.com"

The only thing that i get on return is:
> Select the items to import:
> undefined

Attempting to import an XML file exported from keepass returns the following: Can´t read the file! It must be a KeePass file.

**Comment by ericxuo** [comment]
Hi,

I've got exactly the same issue. And I have more than 260 passwords to import !!

Regards.

Xuo.

**Comment by Mordalo** [comment]
Same.  tried the most basic csv file so as to avoid any gotchas.
"label","login","Password","Web Site","description"
"User1","User01","Password01","","test user1"
"User2","User02","Password02","","test user2" and all I get is this:
![igiveup](https://cloud.githubusercontent.com/assets/18295241/14299451/b51b0488-fb47-11e5-8f0e-9182b23891d4.png)

**Comment by nilsteampassnet** [comment]
Please refer to #1206
