### ISSUE TITLE
Update from 2.1.24 to 2.1.25 not working

### ISSUE THREAD

**Issue by polcape** [nilsteampassnet/TeamPass#1201]
When I press launch in the step 3 of upgrade procedure i get error "Unable to access to dabase" but credentials are ok.

**Comment by frankenstein91** [comment]
i do not hve this problem.

**Comment by polcape** [comment]
There are some way to see a log?
In the apache error.log there is anything.

**Comment by yssvic** [comment]
I have the same problem on version 2.1.25 and nothing is in the log.

**Comment by ImNtReal** [comment]
I'm getting the same thing. I'm using a mariadb cluster. I've tried two different load balancers, and going to each of the nodes directly. I've also tried both php-mysql and php-mysqlnd. This is on a new server with a copy of the database I'm using to test upgrades. I get nothing in error_log. I'm running this on an up to date CentOS 7 box with selinux disabled. Interestingly, sometimes, I get (using password: YES) and sometimes NO.
