### ISSUE TITLE
Error creating folders

### ISSUE THREAD

**Issue by enydrueda** [nilsteampassnet/TeamPass#1202]
Hi, when I try to create a folder the browser console show the error "Uncaught TypeError: Cannot read property 'replace' of null index.php?page=manage_folders:1154" and the folder didn't created. Version 2.1.25

**Comment by frankenstein91** [comment]
i do not have this issue. 
Please send me your browser version

**Comment by enydrueda** [comment]
The error appears to not select a parent folder, I think you should show an understandable message
