### ISSUE TITLE
Avatar does not work

### ISSUE THREAD

**Issue by ouafnico** [nilsteampassnet/TeamPass#1203]
Hello

Using the last version, the upload of an avatar for a user does not works.
No error are shown, and no error in apache logs.

It's not a big functionality, but I think it's a good idea to tell it :)

Thanks

**Comment by nilsteampassnet** [comment]
You need to import a png file.
Just tried on test environment and it works.
Not with other format of file.
I could improve this.

**Comment by ouafnico** [comment]
The pictures I tried was png file.
Is there any resolution limit? They are small pictures.

When i upload it, no error the profile page is shown but still no picture.

**Comment by ouafnico** [comment]
On 2.1.24, it doesn't work too, and on the error.log I got:

PHP Fatal error:  Call to undefined function imagecreatefrompng() in /var/www/html/TeamPass/sources/main.functions.php on line 1065, referer: http://teampass/index.php?page=items

**Comment by ouafnico** [comment]
Solved:

miss php-gd on the server.

Sorry.
