### ISSUE TITLE
Cannot Import from Keepass

### ISSUE THREAD

**Issue by mskrishna20051974** [nilsteampassnet/TeamPass#1206]
Hi,

I am using the latest version of Teampass and not able to import items from Keepass XML.

The following error is shown 

Can't read the file! It must be a KeePass file.

In the apache log, i see this error

PHP Notice:  Undefined variable: prevLevel in /var/www/html/TeamPass/items.import.php on line 113 referer: http://abc.xyz/TeamPass/index.php?page=items

Please help me out.

**Comment by wyverneximus** [comment]
The same problem occurs with the CSV import as well, when you have to select what to import it just displays "undefined".

**Comment by ouafnico** [comment]
Same problem on last version. 
Will try the previous and tell here.

**Comment by scbnmoody** [comment]
Also had this problem. Recently setup a 2.1.25 server from scratch and was unable to import via csv or keypass xml. Ended up manually importing the 144 passwords.

**Comment by Nepharus** [comment]
Adding my two bits to this issue. Using 2.1.25 on fresh server install. Unable to import. Screenshot attached:
![tp_importerror_030916](https://cloud.githubusercontent.com/assets/11967738/13648819/e90cb0bc-e5f7-11e5-8b35-8ae04f258d0c.png)

**Comment by nilsteampassnet** [comment]
The implementation of csrf protection has a negative impact on upload library. 
A bug has been identified in this csrf library, the author has been warned and is working on it. 
Once corrected, I will update teampass with it.

**Comment by nilsteampassnet** [comment]
A possible work-around is to comment the csrf protector library call and init in the first line of index.php file. 
Reload the page and it should work.

**Comment by nilsteampassnet** [comment]
Can you tell me if you have performed a try with Chrome?

**Comment by ouafnico** [comment]
Hello,

Does not works with chrome too :s

**Comment by drsadmin** [comment]
For me the best workaround rather than disabling csrf is to transfer the file to directory teampass/files manually yourself using the exact same filename. Make sure it is owned by the apache user which in my case is www-data. I made it read only just in case but that might not be necessary. Then go through the import process again and it will work.

The other workaround given for this problem which disables csrf breaks the teampass login for me so this is the best work around I found.

**Comment by elxinside** [comment]
Any news on solving this?

**Comment by drsadmin** [comment]
It seems to be a browser / client side related issue e.g. browser settings, version, vendor. The problem is knowing where to start looking because some folks report no issues after testing with chrome and firefox and also CSRF enabled as well.

I asked for a simpler non-javascript pure HTML5 based upload tool for testing this as we don't need the features of plupload just to get a single file into the "teampass/files" directory. If HTML5 upload tool works then perhaps it's not a CSRF issue after all, if it does not work with HTML5 then that's a bit more problematic but at least it's probably then not a plupload issue?

**Comment by Mordalo** [comment]
I did try disabling CSRF and it also broke my authentication.  I also tried copying a file with the same name to the files directory but got a JSON parsing error. 

![jsonparsefailed](https://cloud.githubusercontent.com/assets/18295241/14300904/c33314b2-fb50-11e5-9660-efb170dfaede.png)

**Comment by nilsteampassnet** [comment]
It is corrected in branch Development for 2.1.26 release.

It was related the issue with CSRFProtector

**Comment by ericxuo** [comment]
Hi,

Do you know when the version 2.1.26 will be available for downlowd ?

Regards.

Xuo.

**Comment by nilsteampassnet** [comment]
Available in branch 2.1.26-RC1.

It will be released officially in 1 or 2 weeks after test phase finished.

**Comment by 46Wil** [comment]
Nils or anyone else who knows,
  So I looked in my previous install, 2.1.26 (13), and I just upgraded to (15), and for the life of me I cannot find where to perform this import.  Help!  I don't really want to have to hand jam every one of my passwords in.

Thanks

**Comment by FelipeLemus** [comment]
Greetings,

We are migrated the server with TeamPass to another with a more modern OS.

When we try to import the items we have the same issue despite we have the newest version of TeamPass 2.1.26 (16). 

I have tested in Firefox, Chrome, Safari, IE, Edge and Opera without succes. Probably we will have to introduce the items manually but I thought that you should know.

![2016-08-18 12_15_58-teampass](https://cloud.githubusercontent.com/assets/21101272/17770450/0d03058c-653e-11e6-8978-040bfb9b5f52.png)

Regards.

**Comment by nilsteampassnet** [comment]
I'm surprise as it should work with this last package. Are you sure to have enabled this option and to have selected the yet gros allowed to import?
Can you make a screenshot of those settings ?

**Comment by CCT1** [comment]
I know that this is a bit dated, but came upon the same problem with the "You need to select a Folder" issue.  I discovered that this was a SELINUX issue for me and after entering the following commands importing worked correctly:

cd /var/www/html
chown -R apache:root TeamPass
cd /var/www/html/TeamPass
chcon -R -t httpd_sys_rw_content_t install/
chcon -R -t httpd_sys_rw_content_t includes/
chcon -R -t httpd_sys_rw_content_t files/
chcon -R -t httpd_sys_rw_content_t upload/

Colin

**Comment by CCT1** [comment]
However, I am having problems importing xml files - only the last entry in the XML file is being imported!  Anyone experienced this problem?

**Comment by edzoe** [comment]
I have the same problem, importing xml and cvs files. I disabled SELinux and experience the same error message. I checked also the consistence of xml and cvs files and are readable... I can send any logs if needed.

**Comment by Rengine1** [comment]
I have a Windows 2016 server setup, with WAMPServer installed.
What I found as a work around is, if I copy the .xml export to the www\teampass\files folder then try the import.

I have a large Keepass database so I had to break it down to smaller chunks, and still got a few that had JSON errors, but most imported.
