### ISSUE TITLE
Teampass 2.1.25.2 - mysqli_fetch_all not available

### ISSUE THREAD

**Issue by sandman42** [nilsteampassnet/TeamPass#1216]
Hi,

I've this problem on a freshly installed debian 8.3. with Apache 2.4.10 and PHP  5.6.17-0+deb8u1

mysqlnd is installed:

`root@teampass:~# dpkg -l php5-my*
Voluto=U (non noto)/I (installato)/R (rimosso)/P (rimosso totale)/H (in attesa)
| Stato=Non/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(nessuno)/R (reinstallazione richiesta) (Stato,Err: maiuscolo=grave)
||/ Nome                                          Versione                    Architettura                Descrizione
+++-=============================================-===========================-===========================-===============================================================================================
un  php5-mysql                                    <nessuna>                   <nessuna>                   (nessuna descrizione disponibile)
un  php5-mysqli                                   <nessuna>                   <nessuna>                   (nessuna descrizione disponibile)
ii  php5-mysqlnd                                  5.6.17+dfsg-0+deb8u1        amd64                       MySQL module for php5 (Native Driver)`

I've enabled it with php5enmod mysqlnd

But I get the error while running the install web page saying it's not available.

How can I solve it?

Thanks

**Comment by d-stephane** [comment]
Same problem for me...
PHP 5.6.17-0+deb8u1 on Debian Jessie
Apache 2.4.10
