### ISSUE TITLE
Cannot install TeamPass

### ISSUE THREAD

**Issue by Guilloma** [nilsteampassnet/TeamPass#1218]
On the Server Check section on the Install screen I get this message: 

[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!

I'm trying to install in debian with PHP 5.6.14 installed. What am I missing?

**Comment by budicom** [comment]
Hi,
Same problem with Ubuntu 14.04 and php 5.5.9.

**Comment by ymakhloufi** [comment]
Hi,

I posted about this very issue several days ago. No solution yet :(
https://github.com/nilsteampassnet/TeamPass/issues/1204

**Comment by mbartele** [comment]
Hi,

I just found a solution for the problem. I answered it in #1105 

I hope this helps you.

Mark

**Comment by taten14** [comment]
I have seen  this error in /var/log/apache2/error.log
Call to undefined function mcrypt_get_iv_size()
So i google it and the answer came, i have to enable mcrypt mod and then restart the apache2 service
php5enmod mcrypt
sudo service apache2 restart

Dante

**Comment by phfsobhan** [comment]
@taten14
Worked for me getting "Answer from server is empty" ( php version error )
Thanks

**Comment by andresju** [comment]
Hi,

I had the same problem. I had everything configured ok but it didn't worked for me. I tried different mysql and php versions and it didn't work for me.

Finally I found a solution that worked for me. I ran the installer in a "Private mode". I think there are any javascript which doesn't work fine and if you run the installer from a private mode or other different browser it has to get all the javascript again and it works.

Andres

**Comment by FlorentChamault** [comment]
Hi 

Do you have another solution for this problem ?
i can't install teampass.. 

thanks

**Comment by nilsteampassnet** [comment]
Did you get through proposed solutions in this ticket? 
Can you provide information such as teampass version, environment, extensions,...

**Comment by FlorentChamault** [comment]
yep, i try all solutions in this ticket but nothing.. 
yep, i can

teampass version => Master on GitHub
environment => debian, apache(Apache/2.4.100, mysql(5.5.50-MariaDB), php (PHP 5.6.29)
extension => 
PHP extension "mcrypt" is loaded 
PHP extension "mbstring" is loaded 
PHP extension "openssl" is loaded 
PHP extension "bcmath" is loaded 
PHP extension "iconv" is loaded 
PHP extension "xml" is loaded 
PHP extension "gd" is loaded 
PHP function "mysqli_fetch_all" is available 
PHP version is greater or equal to 5.5.0 

after push the launch button on server check page, i have this error message : [ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!

do you have an idea ? 

Thanks

**Comment by gairhald** [comment]
Hello, i have the same error to try install teampass on the next server:

CentOS 7.3
MySQL 5.7.16
TeamPass Release 2.1.26

When try to install by web, and launch it, web report the same error

`[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!`

And, if i go to the httpd error log, i see the next

`[Thu Feb 09 11:19:14.972112 2017] [:error] [pid 23262] [client 172.x.x.x:49587] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/TeamPass/sources/sessions.php on line 77, referer: http://172.x.x.x/TeamPass/install/install.php`

Any idea to solve this error? thanks

**Comment by nilsteampassnet** [comment]
The log error is quite interesting.

http://stackoverflow.com/questions/27633584/php-fatal-error-call-to-undefined-function-mcrypt-get-iv-size-in-appserv
