### ISSUE TITLE
403 Access Forbidden by CSRFProtector! on users (not in admin)

### ISSUE THREAD

**Issue by vestelar** [nilsteampassnet/TeamPass#1219]
I get this error when try to log with users in 2.1.25 and 2FA. If i try with admin user don't. I use the upgrade script.

**Comment by nilsteampassnet** [comment]
Did you cleared cache?
Could not reproduce.
Can you test with the last commit in Development branch? https://github.com/nilsteampassnet/TeamPass/tree/development
