### ISSUE TITLE
Unable to Access OTV Link

### ISSUE THREAD

**Issue by bhhavya** [nilsteampassnet/TeamPass#1225]
I am successfully able to generate OTV Link however, when I try to open the OTV link in the browser it looks as seen in attached screenshot.
![teampass-otv](https://cloud.githubusercontent.com/assets/16620516/13392491/ee0f4abe-df00-11e5-9306-05634c5d2da0.png)

**Comment by lachmex** [comment]
same problem...
@version TeamPass 2.1.24

it seems that table 'teampass_keys' doesn't exist anymore on fresh installation... isn't it connected with the table teampass_otv somehow ?

thank you

**Comment by ilfrigorifero** [comment]
2.1.25 can create the link, but when opening it says "Item not found" and afterwards gives me an "unexpected token" message and after refreshing the page I have to login again

**Comment by nilsteampassnet** [comment]
Bug cleared up in next release

Thanks for reporting.

**Comment by bublboblz** [comment]
I confirm the following error in the logs, after 2.1.25 fresh install "SELECT * FROM teampass_keys WHERE `id` = 1 AND `sql_table` = 'items'<br />Table 'typms.teampass_keys' doesn't exist@/sources/admin.queries.php".
For the impatients, what is the structure of the missing table or is there a workaround ?  
Thank you

**Comment by sodul** [comment]
I'm on a fresh install of 2.1.26 and the feature does not work and the teampass_keys table is missing.

**Comment by nilsteampassnet** [comment]
it should work.

@sodul what package did you install?
Can you provide logs and screen capture?

**Comment by bublboblz** [comment]
Salut Nils, 

une petite remarque sur la phrase "accroche" de ton site : "Give to Passwords a Deeper Dimension" 
Je ne suis pas très bon en anglais, mais il me semble que le "to" est en trop ( https://forum.wordreference.com/threads/to-give-somebody-or-to-give-to-somebody.748444/ ), fais le valider par un anglophone si possible 

Bonne journée, 
Fabrice 
----- Mail original -----

De: "Nils Laumaillé" <notifications@github.com> 
À: "nilsteampassnet/TeamPass" <TeamPass@noreply.github.com> 
Cc: "bublboblz" <f.roussin@laposte.net>, "Comment" <comment@noreply.github.com> 
Envoyé: Samedi 29 Juillet 2017 08:15:45 
Objet: Re: [nilsteampassnet/TeamPass] Unable to Access OTV Link (#1225) 



Closed #1225 .

**Comment by nilsteampassnet** [comment]
Salut Fabrice,

Oui tout à tout fait raison.
Je vais faire la correction.

Tu as tout à fait raison concernant la relecture ... mais tellement de choses à faire, ça va venir ;)

A bientot
