### ISSUE TITLE
403 Access Forbidden by CSRFProtector! 

### ISSUE THREAD

**Issue by eric-seekas** [nilsteampassnet/TeamPass#1229]
i meet this error when i Restore the database  in Backups sheet

**Comment by ItecorSupport** [comment]
Same problem for me!! 
I saw another ticket (#1181) with this error but when they save settings.
Saving settings doesn't generate error on my Teampass version 2.1.25. Problem came after browsing and select the backup file for a restoration in the backups tab.

**Comment by ItecorSupport** [comment]
same error after changing the file includes/libraries/csrfp/libs/csrfp.config.php with:

"jsUrl" => $_SESSION['settings']['cpassman_url']."/includes/libraries/csrfp/js/csrfprotector.js",

**Comment by ItecorSupport** [comment]
Please add a solution we need to restore Teampass. It's an important critical part of your application (backup and restoration must work fine).
Thanks a lot

**Comment by nilsteampassnet** [comment]
Can you try with Google Chrome please?

**Comment by juranich** [comment]
I have the same error when I'm trying to login after enabling Duo 2FA. If I disable the Duo 2FA, no error

**Comment by ItecorSupport** [comment]
Same thing with Google Chrome

**Comment by nilsteampassnet** [comment]
Can you test with last committed package in Development branch => https://github.com/nilsteampassnet/TeamPass/tree/development

I think I found a solution for this.

**Comment by ItecorSupport** [comment]
Rhooo a new error when installing development branch at the "Tables creation " par of the installation. FYI all tables are created in the DB and I've got PHP 5.6 version:
[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!

**Comment by nilsteampassnet** [comment]
Correct. I've committed the fix.

**Comment by ItecorSupport** [comment]
The installation is successed now. But I've got error 500 when accessing on the home page :(

**Comment by Dureaghin** [comment]
Not working installation on Release 2.1.25 (2), Release 2.1.24 (4) and Development version 2.1.26.

**Comment by Dureaghin** [comment]
I got the same 500 message.

Error log: 
PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /var/www/html/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82\nStack trace:\n#0 /var/www/html/index.php(31): csrfProtector::init()\n#1 {main}\n  thrown in /var/www/html/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82

**Comment by juranich** [comment]
i get 500 error as well. any idea how to fix it?

**Comment by ItecorSupport** [comment]
I deleted the ' " ' at the end of "jsUrl" => "http://../includes/libraries/csrfp/js/csrfprotector.js",
error 500 go away but I can't access to the home page too. Only a blanck screen

**Comment by ItecorSupport** [comment]
I'm waitinf for a solution to use TeamPass in production...

**Comment by ItecorSupport** [comment]
Just give us any news

**Comment by rodehoed** [comment]
I can confirm that we have the problem also when DUO 2FA is active. When DUO is disabled it does work!

**Comment by nilsteampassnet** [comment]
Confirmed with DUO enabled.
Fix committed soon
