### ISSUE TITLE
Password entries not showing, error with multiple sessions

### ISSUE THREAD

**Issue by Alfred-BE-X** [nilsteampassnet/TeamPass#1231]
Hi Nils!

Our company recently switched to Teampass and so far the feedback from the users has been overwhelmingly positive, so let me use this opportunity to thank you for developing/providing this excellent tool!

There are, however, a couple of issues we have that I would like to bring to your attention with this post.
1. Some folders do not show entries in the pane on the bottom right. The entries are there and can be accessed from the pane on the right, but they do not show up in the pane on the bottom right. The error seems to crop up either once you reach a certain depth of folders or by using numbers in the name, we are not quite sure what the culprit is.

Working:
![folder_error_working](https://cloud.githubusercontent.com/assets/17747207/13696539/4b30120a-e767-11e5-84e5-9b323d7ced79.png)

Not working:

![folder_error_notworking](https://cloud.githubusercontent.com/assets/17747207/13696546/55f50b14-e767-11e5-8a09-9e3c45dbaf58.png)
1. Logging in with a second session on another computer (or a private session on the same computer) produces an error on clicking on a folder name in the first session. Please see attached screenshot for the error message:

![teampass_json_error](https://cloud.githubusercontent.com/assets/17747207/13696514/2d5c1670-e767-11e5-8ad5-cf15f0a34ce4.png)

Just closing the second session does not get rid of the error, you also have to log out in the first session and then log back in to clear it up. 

My last point is actually more of a feature request than an issue per se. We would really like to see the description field of the bottom right pane to be able to fold out like the folders do on the left pane (by clicking on the triangle). It would be even better if there was the possibility to customize the fields of the bottom right pane. For example we could really use a field called „IP Address :“, whereas we don't really need the „Restricted to :“ field.

Anyway, thanks again for the tool and any help you could provide with our issues would be greatly appreciated.

Thanks

**Comment by nilsteampassnet** [comment]
Hi,

I will try to answer your points.

1/ I've launched several tests and couldn't reproduce. 
When it occurs, can you check in the apache logs to get the error. Or please use Firebug that will permit to get the errors.

2/ It is normal, you cannot be logged with the same account on the same database with 2 different browsers.
THe error you get is because of this "corruption" of token between your browser and the database.
I've done a change that should give  a more explicit message.

3/ THis a feature called "Categories and Fields". Please refer to http://teampass.net/2013-03-25-custom-categories-and-fields/

You'r welcome

**Comment by Alfred-BE-X** [comment]
Bonjour Nils,

thank you for your answer. I consider points 2 and 3 as answered and closed, which leaves us with the matter of the missing entries. We now think that this phenomenon may be a problem with the rendering engine of Firefox, as a test with Google Chrome does not exhibit the same error.
 
![teampass_debug_detailstable_location_firefox](https://cloud.githubusercontent.com/assets/17747207/13842262/891052e0-ec2d-11e5-8a01-e99149140413.png)

As you can see from the screenshot, when the problem occurs, the table containing the entries somehow gets moved outside the viewable area. There are no errors associated with this that we could find in the logs. 

I can reproduce this phenomenon at will just by renaming one of the folders from "name" (everything is as it should be) to "name01" (error occurs). I am really at a loss to explain what is the cause, though, as renaming that same folder to "name0021" does not trigger the error, while renaming it to "nameab" does.

I hope that this information is helpful in any way to solve this issue and thanks again for your support.
