### ISSUE TITLE
Cannot Export to HTML

### ISSUE THREAD

**Issue by ilfrigorifero** [nilsteampassnet/TeamPass#1232]
Hi,

I'm using Teampass 2.1.25 on an Ubuntu LTS server.
Unfortunately, I cannot export passwords as I am getting an Internal Server Error.
Trying to copy the response body in firebug, but there is none, so I can only paste the Header :(

Header:
Cache-Control  
no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection  
close
Content-Length  
0
Content-Type  
text/html; charset=utf-8
Date  
Fri, 11 Mar 2016 08:53:28 GMT
Expires 
Thu, 19 Nov 1981 08:52:00 GMT
Pragma  
no-cache
Server  
Apache/2.4.7 (Ubuntu)
X-Powered-By  
PHP/5.5.9-1ubuntu4.14

Request;
Accept  
application/json, text/javascript, _/_; q=0.01
Accept-Encoding 
gzip, deflate, br
Accept-Language 
de,en-US;q=0.7,en;q=0.3
Content-Length  
139
Content-Type  
application/x-www-form-urlencoded; charset=UTF-8
Cookie  
KEY_PHPSESSID=VfjsMBPpaZUrXytHf1RSovjaHtpy1UuzZJYGyvBXlYo%3D%3AlONcpoqPK2q7vxrSLI09n0nUY%2F0rZEN4eqrsLEAHs2w
%3D; PHPSESSID=psk0l1efhpkb1rmiicj3feq623; 4dccecf10b6971c2c26e779c780160c16b558fb9882a363632=a6f70cc05b23b87017fd2e9a9
; TeamPass_PFSK_c81e728d9d4c2f636f067f89cc14862c=V2NwcFBuMTJjcXBqajFObStwd254Z0o2K1Vqa0FoMVkxM1ZrbUVWUEV4b7Lf8QmiE4au9CjOK2nOOxho1BAF
%2FlOaIXTbKI%2F1FxsANmMwNDE1MTMyNjRmYWM4YTNiMTNmODdlNzFhMjQxMTljODQ5Yjk0OTM4ZDdmYzA5MzhkYjU4ODI2YmYwYjQ1NnFqeGw1eDR0NGgxMDdoZnptZTRwcm9xNHplbXZneG81Y3A5MW43OW9sYjJwdWxvdnBvNGtvZTJveWRwanNxbG0
%3D; jstree_select=1
Host  
10.1.0.50
Referer 
https://10.1.0.50/index.php?page=items
User-Agent  
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
X-Requested-With  
XMLHttpRequest

"NetworkError: 500 Internal Server Error - https://10.1.0.50/sources/export.queries.php"

Address including parameters:
https://10.1.0.50/sources/export.queries.php?4dccecf10b6971c2c26e779c780160c16b558fb9882a363632=a6f70cc05b23b87017fd2e9a9&ids=1&pdf_password=Testpassword1234&type=export_to_html_format

There's nothing in the Apache error.log

**Comment by ElGranLoky** [comment]
idem
