### ISSUE TITLE
403 Access Forbidden by CSRFProtector!, but only when saving configuration

### ISSUE THREAD

**Issue by churusaa** [nilsteampassnet/TeamPass#1234]
Just like #1181 but I don't see anything that looks out of place in the config file, and the jsUrl path is correct (tested). Works when I copy it out of the config file and paste it into a browser.

I'm also getting this same 403 Access Forbidden by CSRFProtector error when trying to save settings.

I have tried your robustified jsUrl in place of the usual jsUrl in the config file, and I still get the same thing. This is a brand new, virgin install of the latest version of TeamPass, and I have confirmed that with the exact URL copied and pasted from my config file, I actually get the text of csrfprotector.js. The distribution I'm running is CentOS 7, but I have made sure to allow write access by the server account. Build is 2.1.25 (2). I see a note indicating that this may be resolved in 2.1.26. I'll keep an eye out for that to drop or test the beta for this condition if you want. This system isn't doing anything critical yet, so I'd be happy to play the test subject in this case.

I played around with the time, as well, just to see if it was expecting UTC on the system clock, but no dice there either. Everything else seems to work well.

`"jsPath" => "../js/csrfprotector.js", "jsUrl" => $_SESSION['settings']`
`['cpassman_url']."/includes/libraries/csrfp/js/csrfprotector.js",`
Also tried:
`"jsUrl" => "https://sub.domain.com/teampass/includes/libraries/csrfp/js/csrfprotector.js",`

I did have to do the following to get even this far, but it's just because this is an Enterprise Linux distro:

```
find teampass -type d -exec chmod 755 {} \;
find teampass -type f -exec chmod 644 {} \;
```

```
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/install'
restorecon '/var/www/html/teampass/install'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes'
restorecon '/var/www/html/teampass/includes'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/files'
restorecon '/var/www/html/teampass/files'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/upload'
restorecon '/var/www/html/teampass/upload'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes/avatars'
restorecon '/var/www/html/teampass/includes/avatars'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes/libraries/csrfp/log'
restorecon '/var/www/html/teampass/includes/libraries/csrfp/log '
```

**Comment by nilsteampassnet** [comment]
same as #1181
