### ISSUE TITLE
Wrong password timeout 2.1.25

### ISSUE THREAD

**Issue by OlegSmirnov** [nilsteampassnet/TeamPass#1237]
Hi Nils,

I got an issue with sources/identity.php - if the password is wrong nothing happens, i.e. the page presents ajax-loader.gif and that's about it. Just wonder if that's expected behavior or not?

Thanks,
Oleg

**Comment by nilsteampassnet** [comment]
You should get a message in red saying "bad credentials ..."

**Comment by OlegSmirnov** [comment]
I managed to find the cause of the issue.
The database didn't accept NULL value for the field 'field_1' in table 'log_system' so I had to comment it out in sources/main.functions.php:

```
    DB::insert(
        prefix_table("log_system"),
        array(
            'type' => $type,
            'date' => time(),
            'label' => $label,
            'qui' => $who
     //       'field_1' => $field_1
        )
    );
```
mariadb-server-5.5.44-2.el7.centos.x86_64

Thanks,
Oleg

**Comment by OlegSmirnov** [comment]
Actually I might want to re-open that so you can see the solution.

**Comment by nilsteampassnet** [comment]
THis is strange because database should accept null for this field as it is its default value.

Can you run this query
````
ALTER TABLE teampass_log_system CHANGE `field_1` `field_1` VARCHAR( 250 ) NULL;
```

This query is the one from the upgrade process.

**Comment by OlegSmirnov** [comment]
Yeah, I see. Well, for some reason that didn't work during upgrade in all my tries.

MariaDB [teampass]> select default(field_1) from teampass_log_system;
ERROR 1364 (HY000): Field 'field_1' doesn't have a default value

Thanks anyway!
