### ISSUE TITLE
Teampass Upgrade Error

### ISSUE THREAD

**Issue by Andyl057** [nilsteampassnet/TeamPass#1238]
Hi,

When upgrading teampass 2.1.23.4 to 2.1.24.4 and above the upgrade script keeps freezing at step 4 with an apache error of undefined function mysql_result() on line 70. From research this seems to be due to this function having been depreciated in all php versions since 5.5.

Is there any work around currently available for this?

**Comment by nilsteampassnet** [comment]
THis is a mistake

In file /install/upgrade_ajax.php change mysql_result to mysqli_result.
There is 2 instances of this instruction.
Don't understand how I could missed them and why I don't get any warning on it.
