### ISSUE TITLE
Error load tree with personal folders request JSON 

### ISSUE THREAD

**Issue by ElGranLoky** [nilsteampassnet/TeamPass#1239]
Versión 2.1.25 .(2)

I dont know why, but sometimes the users in the same role of another have problems with the load of the tree becouse the personal folder of these user.

I found a workaround update the file tree.php. Change the lines of:

196 `$text .= ' (<span class=\'items_count\' id=\'itcount_'.$node->id.'">'.count($_SESSION['list_folders_limited'][$node->id]).'</span>'; `
to

`$text .= ' (<span class=\'items_count\' id=\'itcount_'.$node->id.'\'>'.count($_SESSION['list_folders_limited'][$node->id]).'</span>';`

the quotes after the itcount

the same in line 328.

And in the lines after 199, 331 the same change.

After the changes, i dont have the error of json, but the tree load the id of the personal folder of the user, but the other users in the same role cant access or edit any items.

**Comment by nilsteampassnet** [comment]
Correct change you did. I was a mistake from me.

Now I don't really understand the issue in your last sentence.
Do you mean that other users don't see anything?
Or that they don't see the personal folders of a specific user?

**Comment by ElGranLoky** [comment]
I fix it, is a problem with the personal folder of the user. After delete de user and create, the other users dont see the personal folder of the user.

**Comment by nilsteampassnet** [comment]
OK
