### ISSUE TITLE
OTV visible more than one time

### ISSUE THREAD

**Issue by ElGranLoky** [nilsteampassnet/TeamPass#1241]
In versión 2.1.25.(2)

After send the link I can open the link multiple times before the end of the timeout in the OTV.

**Comment by nilsteampassnet** [comment]
Perhaps an issue with server time?

I've checked the condition that permits to reject old OTV, and don't see why it could fail.
Can you check this please?

Or give us your settings.

THnks

**Comment by ElGranLoky** [comment]
What settings do you need?

The date in the server is correct. And i set the timeout of the item in one day the otv link is available for one day, after this time i can'nt access to the item.

But during this time i can access multiple times in the otv link from different computers without problem, ¿it have to be one time,isn´t it?

**Comment by nilsteampassnet** [comment]
OK understood the point.

The delete query was commented out. I'm correcting it and commit.
