### ISSUE TITLE
Global Search don´t show all items

### ISSUE THREAD

**Issue by ElGranLoky** [nilsteampassnet/TeamPass#1242]
In versión 2.1.25.(2)

When i do a global search, the footer show there are filtered items but i have the "No matching records found" message. I have edit permission in the items dont show.

Example:
![2016-03-18 10_31_06-teampass](https://cloud.githubusercontent.com/assets/2712200/13875002/84d7c202-ecfb-11e5-8d6d-72ac78661237.png)

**Comment by nilsteampassnet** [comment]
Please can you provide more details concerning the settings related the items that are not shown.

Is there some specific right access on those? Give any detail so that I can reproduce.

**Comment by ElGranLoky** [comment]
I think in the txt file are all the values you need, if you need more, please let me know.

If i search "DEM" in the global search the program show me the three values, but if i search "DEA" with the same user the program show me 2 values filter but "No matching records found" message.

[Values DDBB.txt](https://github.com/nilsteampassnet/TeamPass/files/181782/Values.DDBB.txt)
