### ISSUE TITLE
Can not login with admin

### ISSUE THREAD

**Issue by Prideth** [nilsteampassnet/TeamPass#1246]
HI i created a new teampass (tested version 24 and 25). But if i want to login the login spinner keeps and nothing happens. What could be the problem?

**Comment by nilsteampassnet** [comment]
Please check your server log errors file

**Comment by boube** [comment]
Hi, the same here: 

PHP Notice:  Undefined variable: debug in error.php on line 20, referer: https://TEAMPASS_URL/index.php?session=expired
PHP Notice:  Undefined index: session in error.php on line 24, referer: https://TEAMPASS_URL/index.php?session=expired
PHP Warning:  fputs() expects parameter 1 to be resource, null given in error.php on line 26, referer: https://TEAMPASS_URL/index.php?session=expired

Thanks!

**Comment by Prideth** [comment]
The logs are empty. https://TEAMPASS_URL/index.php?session=expired has not worked either

**Comment by nilsteampassnet** [comment]
Try to clear cache perhaps.

Use the developer console of your browser to get the "real-time" error, and post here the results

**Comment by Prideth** [comment]
Teampass was just fresh installed. Tryed it with chrome and Firefox on Windows and Linux. The Developerconsole says loaded in 34s, no errors or console output
