### ISSUE TITLE
Cutting folder names

### ISSUE THREAD

**Issue by Seledko** [nilsteampassnet/TeamPass#1248]
Hi!

I recently installed teampass on our NAS Synology. It works well, but I have a question.
When I create a folder with a long name, the name is cutting and it's difficult to understand. For example, if folder name is "Уровни доступа сайта", i recieve only "Уровни до...".
Can I manualy change any properties to set off the automaticly-cuttiing-long-folder-name?

**Comment by nilsteampassnet** [comment]
Where do you mean, in the Tree or in the top navigation bar?

**Comment by Seledko** [comment]
I mean Tree and top navigation bar. 
Now I understand, how it's work.

If name of the folder consists of English letters, then it's work good till 20 symbols.
If name of the folder consists of Cyrillic (Russian) letters, then it's work good only till 10 symbols. If there is more than 10 symbols, the name is cutting down.

Screenshot of attachment.
![teampass](https://cloud.githubusercontent.com/assets/18160579/14177614/c496a9d0-f75f-11e5-9846-5f2b41e2d16e.PNG)

**Comment by nilsteampassnet** [comment]
it seems you are using an old version.
I don't know if what I will write is implemented in this one, but I don't think.
The navigation bar compares the available width with the total width of the "folder depth text". If text is too long, the font size is decreased. If still too long, then folders text is truncated.
Now concerning the tree structure, the folder names are no more truncated.

**Comment by reginfo** [comment]
I have 2.1.25 and 20 Russian letters displays as normal.
![tp](https://cloud.githubusercontent.com/assets/4628571/14199074/9ed8e782-f7e9-11e5-91e0-8cabdfb787e7.PNG)

**Comment by Seledko** [comment]
Thank you all!
Really, in 2.1.25 it's work well.

![2 1 25](https://cloud.githubusercontent.com/assets/18160579/14205672/bc54edc0-f815-11e5-93a3-96a0742208dd.PNG)


Now I will think about how to update the current database. But that's another story :)

Thanks you all again!
