### ISSUE TITLE
Access Forbidden by CSRFProtector

### ISSUE THREAD

**Issue by Seledko** [nilsteampassnet/TeamPass#1249]
Hello, guys!
I have a little problem and I need you help again.

I need to backup a database and restore it later.

I did test backup. When i try to restore it, I get an error: 403: Access Forbidden by CSRFProtector.
![default](https://cloud.githubusercontent.com/assets/18160579/14206356/33092846-f81b-11e5-9e6f-9264a4b479b7.PNG)
I did it several times, but it always fail.

Does anyone know where could be the problem?

**Comment by cgkelleher** [comment]
I am also having this issue when attempting to restore the database?
