### ISSUE TITLE
[Feature Request] SingelSignOn

### ISSUE THREAD

**Issue by IT-Ulven** [nilsteampassnet/TeamPass#1250]
We are using Citrix NetScaler to access internal tools and would like to be able to pass credentials trough to TeamPass.
I have tried to sett up a "Form SSO Profile" like most other internal sites, but are stopped by "403 Access Forbidden by CSRFProtector!"

Any solution is acceptable (GET/POST request, SAML, Basic Auth)

**Comment by andreashuther** [comment]
Hi,
I do need a solution to authenticate via Citrix Netscaler as well. IT-Ulven, how did you reach your goal?
CNS-Formfill, did not succeed, SAML or 401 appreciated..
BR Andreas

**Comment by IT-Ulven** [comment]
@andreashuther We have yet to find a solution to this. At the moment our NetScaler project has come to a halt, so I haven't had much time to look into this.

**Comment by DeltaLima** [comment]
SAML 2.0 to use Google SSO would be a very cool thing! Are there any news for this topic meanwhile?
