### ISSUE TITLE
CSRFP token length + access during upgrade (it seems at least the token length is still present in the .26 (test) version too)

### ISSUE THREAD

**Issue by zhanko73** [nilsteampassnet/TeamPass#1251]
Hi,

First of all thank you for your effort to update the script doing bugfixes and created this tool.

2 possible problem that I'd like to report.
1) During upgrade not all direcotry access is checked. The access right of the directory where the csrfp.config.sample.php (includes) is not checked against the really necessary access right. This resulted in a not created csrfp.config.php file. I had to create it manually that caused the problem 2)

SUGGESTED SOLUTION: check (review) the include directory necessary access right before manipulating the csrfp.config.php file.

-------------------
2) csrfp.config.sample.php contains these lines too:
a)
"CSRFP_TOKEN" => "", 
"tokenLength" => 25,
b)
Install script do this:
If csrfp.config.php does not exists then csrfp.config.sample.php will be copied as csrfp.config.php.
Then a CSRFP_TOKEN will be created with the length of 25 then converted to hex and finally replaced in the file:
$newdata = str_replace('"CSRFP_TOKEN" => ""', '"CSRFP_TOKEN" => "'.bin2hex(openssl_random_pseudo_bytes(25)).'"', $data);
The length of the token in the file left as 25. But when you convert a 25 byte to hexa then each byte will be represented by 2 characters. So actually the token length is double of the 25, it should be 50.
But the installation script actually does not change this token length.

SUGGESTED SOLUTION:
So probably to either change the sample file token length to 50 from 25 or change the update script to calculate the real token length can be a solution

Thanks and keep up the good work! :)

Zoli

**Comment by nilsteampassnet** [comment]
Absolutely right!

Implementing the changes and commit today.

Thanks
