### ISSUE TITLE
Configuration file not found for CSRFProtector!

### ISSUE THREAD

**Issue by Dureaghin** [nilsteampassnet/TeamPass#1254]
I've got error 500 when I'm accessing the home page after installation TeamPass-2.1.25.2.

Error log: 
`PHP Fatal error: Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /var/www/html/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82\nStack trace:\n#0 /var/www/html/index.php(31): csrfProtector::init()\n#1 {main}\n thrown in /var/www/html/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82`

**Comment by nilsteampassnet** [comment]
I've just committed a fix in Development branch.
Try to download "install" folder inside your Teampass instance, and run upgrade.

**Comment by Dureaghin** [comment]
Hi Nils,
Thank you for answering so quickly. 

I replaced old "install" folder with new one + I replaced other files "core.php, csrfprotector.js, include.php, items.logs.php and items.queries.php" from last development commit. 
Now I don't see 500 error on home page, but after saving settings I get blank page.
Also I see error in browser inspector: 
```
index.php?page=manage_settings:3197 GET https://localhost/teampass/includes/libraries/csrfp/js/csrfprotector.js net::ERR_CONNECTION_REFUSED
index.php?page=manage_settings:3200 Uncaught ReferenceError: csrfprotector_init is not definedwindow.onload @ index.php?page=manage_settings:3200

```
Here is my php log:
`PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/includes/include.php on line 21, referer: http://www.project.com/install/upgrade.php`

**Comment by Dureaghin** [comment]
Also I found typo in "include.php" line 21.
`$k['copyright'] = "2009 - ".date('Y');;`

Should be: 
`$k['copyright'] = "2009 - ".date('Y');`

**Comment by Dureaghin** [comment]
I fixed browser errors. Manually changed line 15 in "includes/libraries/csrfp/libs/csrfp.config.php". For some reason it was path "https://localhost/teampass/includes/libraries/csrfp/js/csrfprotector.js", I set my domain name and now I don't see errors. Only blank page after saving settings.
```
index.php?page=manage_settings:3197 GET https://localhost/teampass/includes/libraries/csrfp/js/csrfprotector.js net::ERR_CONNECTION_REFUSED
index.php?page=manage_settings:3200 Uncaught ReferenceError: csrfprotector_init is not definedwindow.onload @ index.php?page=manage_settings:3200
```
