### ISSUE TITLE
Active Directory LDAPS or TLS not working

### ISSUE THREAD

**Issue by meyeaard** [nilsteampassnet/TeamPass#1256]
OS: Windows 2012 R1
WAMP Stack 3.0.0 (Apache 2.4.17, PHP 5.6.16, MySQL 5.7.9)
TeamPass 2.1.23

I have successfully enabled Active Directory user authentication via LDAP with the following settings.
LDAP users authentication through LDAP: YES
LDAP server tyle: Windows / Active Directory
LDAP suffix @my.domain
LDAP base dn DC=my,DC=domain
LDAP array of domain controllers: dc1.my.domain
Use LDAP through SSL (ldaps): NO
Use LDAP through TLS: NO
Teampass local users only: YES

The problem is that while this works, users' passwords would be sent in clear text over the network between this application and the domain controller which is a huge deal breaker. If I enable LDAP SSL or LDAP TLS it immediately breaks authentication until I disable them.

Googling around I find nothing related on teampass + LDAPS/TLS configurations where anyone has them working with AD. Is this a known issue? Does anyone have this working? Any advice?

Looking forward to any community insight. :-)

in your service,
Aaron

**Comment by meyeaard** [comment]
Update: 
I upgraded my installation to 2.1.25 and LDAPS/TLS is still not working.

As also noted by issue #1184 I noted that the LDAPS button does not retain it's state and always reverts to 'off'. I followed his comment and prefixed by DC hostname with ldaps:// without resolution.

Any comments out there? Surely I'm not the only one wanting to use AD without having my users' passwords on the network in clear text...

**Comment by oscarangeli** [comment]
Same situation here.

**Comment by 46Wil** [comment]
Same issue here.  Installed the latest, 2.1.26.  Has any fix been identified for this?  Really bad practice to not secure LDAP traffic.

**Comment by mweber88** [comment]
On the server where Teampass resides, from a command prompt, you should be able to do an ldapsearch using -ZZ option to force TLS and it should work.  If it doesn't, you don't have TLS configured correctly on either the AD server, the Teampass server, or both.

First thing to ensure is that your Teampass server can verify the certs on the AD box.  That will be with command 'openssl verify'.  Once you get that to have "OK" in the very last line, then move onward to ldapsearch.  It will involve setting the ldap.conf file to point at your certificate directory.  For either of these to work, you need the correct root/intermediate certs on the server and hashed properly.

Once you get ldapsearch to function properly, you will ensure that PHP's LDAP plugin is using the correct ldap.conf configuration, and then if so, your Teampass config with AD should work.

Keep in mind that you may need to include your domain suffix when you test ldapsearch and Teampass authentication.  That is, not just username as the bind DN, but rather username@domain.tld.

I struggled with this until wee hours this morning, and got it working.  But, as I said, if ldapsearch doesn't work, something is incorrectly configured and that's outside the scope of Teampass.
