### ISSUE TITLE
What is the cause of the yellow exclamation?

### ISSUE THREAD

**Issue by motigaittech** [nilsteampassnet/TeamPass#1258]
![image](https://cloud.githubusercontent.com/assets/13107753/14334708/13412e02-fc0b-11e5-860f-904941901d77.png)

I created several items in my personal folder and new ones started showing the Yellow Exclamations and I don't know why.
Please help.

**Comment by frankenstein91** [comment]
we have the same problem

**Comment by nilsteampassnet** [comment]
It should not be considered as a problem but as a information. 
Indeed this indicates that the item has a limited access. Which is normal as it us limited to the user.

**Comment by motigaittech** [comment]
Thanks for the information. I did not see any help files describing this behavior and suspect it's because I started using Saltkey.
