### ISSUE TITLE
Personal folder: password empty after password changed

### ISSUE THREAD

**Issue by frankenstein91** [nilsteampassnet/TeamPass#1259]
We have a problem with the personal folders.
In our config we use the Login as SALT for better usability.

The problem is that you can't see any password after you changed your password. It's means the password feld looks empty for the user.
We set "Users' password life duration before expiration" config option to some weeks and the users changed there passwords but the personal folder is not recrypted.

If we change the password back to the old one, the user can read the password again.

I do not know if it is a bug or a missing features.

**Comment by frankenstein91** [comment]
it's not about a very heavy password.

**Comment by mernstsen** [comment]
We are seeing the same problem.
