### ISSUE TITLE
Copy to clipboard in Mac OS X

### ISSUE THREAD

**Issue by duncanallwood** [nilsteampassnet/TeamPass#1261]
The "Copy password" button does not copy the password to the clipboard on a macbook running OS X.

**Comment by duncanallwood** [comment]
Found in teampass 2.1.24

**Comment by ibaivalencia** [comment]
Same issue here with 1.23. Is this fixed in 1.25?

**Comment by Spikeophant** [comment]
Fixed in 1.25 for me, I use chrome on OS X.
