### ISSUE TITLE
Error on suggestion page

### ISSUE THREAD

**Issue by chc88** [nilsteampassnet/TeamPass#1263]
This is a complete new installation of version XXX

When accessing the suggestion-page I see the following error message at the top of the page:
`Warning: in_array() expects parameter 2 to be array, null given in /volume1/web/teampass/suggestion.php on line 75 Warning: in_array() expects parameter 2 to be array, null given in /volume1/web/teampass/suggestion.php on line 75 Warning: in_array() expects parameter 2 to be array, null given in /volume1/web/teampass/suggestion.php on line 75 `

This seems to be only happening while logged in as administrator. There are no suggestions yet to be shown.

**Comment by frankenstein91** [comment]
looks like a synology nas

**Comment by chc88** [comment]
Correct. Seems like a device which is always on anyways and has the power for this.
