### ISSUE TITLE
Can't save objects with "very heavy password"

### ISSUE THREAD

**Issue by claumagagnotti** [nilsteampassnet/TeamPass#1264]
When I try to save an object with "very heavy password" I get the next error "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

<img width="506" alt="screen shot 2016-04-10 at 12 48 56 pm" src="https://cloud.githubusercontent.com/assets/13765147/14411300/b9236274-ff1a-11e5-9ec4-ed94c5cb26f8.png">
<img width="506" alt="screen shot 2016-04-10 at 12 49 04 pm" src="https://cloud.githubusercontent.com/assets/13765147/14411301/bbc67a84-ff1a-11e5-9839-0ea8aceb77dc.png">

**Comment by claumagagnotti** [comment]
Teampass version: 2.1.25

**Comment by claumagagnotti** [comment]
<img width="830" alt="screen shot 2016-04-10 at 6 21 51 pm" src="https://cloud.githubusercontent.com/assets/13765147/14413221/ab8a5cce-ff49-11e5-8572-172272c9fb22.png">

**Comment by nilsteampassnet** [comment]
duplicate #1259
