### ISSUE TITLE
[2.1.25.2] Blank screen after upgrading

### ISSUE THREAD

**Issue by pzmw** [nilsteampassnet/TeamPass#1267]
Today I've tried upgrading from TeamPass 2.1.23 to 2.1.25.2. In the upgrade process we didn't encounter any problems.
However, after upgrading, the login page will not show, just a blank screen.

Restored backup and tried upgrading fdrom TeamPass 2.1.23 to 2.1.24.4 (no problems, login possible, but very slow loading of folder tree) and afterwards upgrading from 2.1.24.4 to 2.1.25.2, but the same problem exists.

No login page is shown, just a blank screen.

I've only found the following errors in error_log:
[Tue Apr 12 14:46:07 2016] [error] [client **_.**_.**_.**_] PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /var/www/public_html/TeamPass/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82\nStack trace:\n#0 /var/www/public_html/TeamPass/index.php(31): csrfProtePHP Notice:  Undefined index:ctor::init()\n#1 {main}\n  thrown in /var/www/public_html/TeamPass/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82,referer: http://www.mydomain.com/TeamPass/install/upgrade.php

**Comment by keir-ru** [comment]
I have a new install and same problem.
Workaround: in ./includes/libraries/csrfp/libs/ copy file csrfp.config.sample.php to csrfp.config.php
