### ISSUE TITLE
Bad URL in mail notification

### ISSUE THREAD

**Issue by QIONIS** [nilsteampassnet/TeamPass#1270]
Hello,

In a notification by mail of the change of elements, the URL points to ".@ $ _ SESSION [".

Sorry for my English. Do you speak French ?
Waiting for your return.
Regards,

**Comment by reginfo** [comment]
The same. My colleague noticed it today! Is there any progress with it?

**Comment by MikeyHoef** [comment]
Yap! We've got the same issus.. Is there a workaround?
