### ISSUE TITLE
Password Copy includes spave

### ISSUE THREAD

**Issue by paratustelco** [nilsteampassnet/TeamPass#1274]
When editiing a password and then clicking the eye button to show the password next to "Used Password:". When you select and copy that and then paste - the pasted password includes a space at the end.

Very confusing when you paste the password somewhere and it does not work because you cannot see that it includes a space.

**Comment by nilsteampassnet** [comment]
Why don't you just use the copy button ?

I've not added this "clear view" to do a manual copy-paste, but just to know what is entered.
Very curious ... I have not imagined that it could be used this way.
I will improve this anyhow.

**Comment by paratustelco** [comment]
IE asks to whether the copy should be allowed or not when you use the copy button. I accidentally clicked Don’t Allow. So then just copied it there instead of opening and closing the browser again.

Also different people will do things differently, some will use the copy button which is easier, others will possibly not even know about the copy button until someone shows them.

Cobus Burger
IP Core Engineer

Paratus Telecommunications (PTY) Ltd
Office:

+264 83 300 1000

Skype:

pt-cburger

Mail:

cobus.burger@paratustelco.com<mailto:cobus.burger@paratustelco.com>

Web:

http://www.paratustelco.com<http://www.paratustelco.com/>

[cid:DCF3F62E-62C6-4527-A3BE-9D964FB754BD]


Disclaimer:
The  information contained  in  this communication is confidential and may be
legally privileged.  It  is intended solely  for  the  use of  the individual or entity
to  whom  it is addressed  and  others authorised to  receive it.  If  you  are not
the intended recipient you  are  hereby  notified  that  any disclosure,  copying,
distribution or taking  action in reliance  of the  contents of  this information is
strictly prohibited and may be unlawful.

**Comment by nilsteampassnet** [comment]
I've tried to reproduce as you explained, but I have no space added.
What version do you use?
