### ISSUE TITLE
After system upgrade from 15.10 to 16.04 Ubuntu, I get sql error??

### ISSUE THREAD

**Issue by robmorin** [nilsteampassnet/TeamPass#1276]
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' label='SELECT * FROM teampass_languages GROUP BY name ORDER BY na' at line 3
Query: SELECT * FROM teampass_languages GROUP BY name ORDER BY name ASC

This si even after a re-install, of which i dropped the db and then installed fres with Ubuntu 16.04 which has php7.0 and Mysql 5.7

Any ideas?

**Comment by robmorin** [comment]
More info:

When running the query manually in mysql prompt I get this error:

mysql> SELECT * FROM teampass_languages GROUP BY name ORDER BY name ASC;
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'teampass.teampass_languages.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I am no mysql/sql guru, but the column "id" does exist.

**Comment by BradStephens** [comment]
I have the same error with a fresh installation on CentOS 7 with PHP 5.6.

**Comment by BradStephens** [comment]
Editing line 104 of sources/core.php to look as follows resolved the issue.

`$rows = DB::query("SELECT * FROM ".prefix_table("languages")." GROUP BY name, label, code, flag, id ORDER BY name ASC");`

This is due to new behavior in MySQL 5.7 covered here:

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by robmorin** [comment]
Yuppers this solution worked for me!
Thanks

**Comment by nilsteampassnet** [comment]
Thanks for reporting and debugging :+1:
