### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by Spikeophant** [nilsteampassnet/TeamPass#1277]
Hello,

  When I attempt to attach a file to an item it says it uploads, and is successful, however I click save, then look at the item and the files are not present.  Here's the output from httpd access log.
10.2.48.126 - - [28/Apr/2016:13:45:58 -0400] "POST /sources/items.queries.php HTTP/1.1" 200 20
10.2.48.126 - - [28/Apr/2016:13:46:11 -0400] "POST /sources/upload/upload.attachments.php HTTP/1.1" 200 93
10.2.48.126 - - [28/Apr/2016:13:46:26 -0400] "POST /sources/upload/upload.attachments.php HTTP/1.1" 200 93
10.2.48.126 - - [28/Apr/2016:13:46:28 -0400] "POST /sources/items.queries.php HTTP/1.1" 200 8612
10.2.48.126 - - [28/Apr/2016:13:46:28 -0400] "POST /sources/items.queries.php HTTP/1.1" 200 -

No entries in the error logs.

**Comment by nilsteampassnet** [comment]
You need to get the server error using a console (Developer tools in web browser or Firebug)

**Comment by oackerma** [comment]
Same issue with me, identical messages as Spikeophant in ssl_request_log, though.
But there is not a single error message in /var/log/apache2/error.log.

**Comment by jaccoh** [comment]
We have this issue as well. I used Chrome developer tools to debug a little and found:

csrfprotector.js:286 Uncaught TypeError: Cannot read property 'split' of undefined(anonymous function) @ csrfprotector.js:286

**Comment by nilsteampassnet** [comment]
Please refer to #1295
