### ISSUE TITLE
SyntaxError: Unexpected token î in JSON at position 0

### ISSUE THREAD

**Issue by BradStephens** [nilsteampassnet/TeamPass#1279]
I'm seeing a popup box with an "Unexpected token" message every time I browse to the passwords page if there is any password created in the tree. It looks like the reported token is different each time I log in - if I log out and log back in as the same user, the token changes, but I always get the same message aside from the token:

```
SyntaxError: Unexpected token î in JSON at position 0
SyntaxError: Unexpected token ¯ in JSON at position 0
SyntaxError: Unexpected token j in JSON at position 0
```

If I delete the only password I have created, the page loads fine. I also see the "Unexpected token" message as soon as I create the first password in the system, and if I click on any folder in the tree.

This is a fresh install of 2.1.25 using Percona DB 57 and PHP 5.6 on CentOS 7. I have created a few users, two roles, and a few folders.

**Comment by BradStephens** [comment]
This is a fresh install of 2.1.25 using Percona DB 57 and PHP 5.7 on CentOS 7. I have created a few users, two roles, and a few folders.

**Comment by OptimusOS** [comment]
I have the same problem 
"SyntaxError: Unexpected token y in JSON at position 0"

only when i used ä,ö,ü,?,ß (German Keybord Layout)

**Comment by raphaelvigee** [comment]
I have the exact same issue...

**Comment by chc88** [comment]
I know that php json_encode function is utf-8 only. 
Perhaps this is the issue here?

**Comment by nilsteampassnet** [comment]
I've done a lot of tests with those characters and couldn't reproduce.

![2016-05-10 22_09_12-teampass](https://cloud.githubusercontent.com/assets/1197546/15160858/f9afda4a-16fb-11e6-923f-56a18b5d49b4.png)

Can you describe me some elements that could help me to reproduce?

**Comment by BradStephens** [comment]
This was a fresh installation, and my password didn't contain any of those characters in any field. I simply installed TeamPass, added one password, and this happens every time.

**Comment by raphaelvigee** [comment]
Here is the error I got when TP tries to query the `items.queries.php` page after update to MySQL 5.7 and any TP version  (2.25) :

```
Error: 
Query: SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso, i.label as label, i.description as description, i.pw as pw, i.login as login, i.pw_iv AS pw_iv, i.anyone_can_modify as anyone_can_modify, l.date as date, n.renewal_period as renewal_period, l.action as log_action, l.id_user as log_user FROM teampass_items as i INNER JOIN teampass_nested_tree as n ON (i.id_tree = n.id) INNER JOIN teampass_log_items as l ON (i.id = l.id_item) WHERE (i.id_tree=26) AND (i.inactif=0) AND (l.action='at_creation') GROUP BY i.id ORDER BY i.label ASC, l.date DESC LIMIT 0,22
```

**Comment by nilsteampassnet** [comment]
what happens if you copy this query inside phpmyadmin "php" tab?
Please copy the error sent back

I do have mysql 5.7.9 installed

**Comment by raphaelvigee** [comment]
MySQL a répondu: Documentation

#1055 - Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'teampass.l.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by nilsteampassnet** [comment]
Exactly, this is what I was reading on mysql documentation page.
It seems that GROUP BY function now needs to fit the columns.

In the same phpmyadmin sql box, can you test:
SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso, i.label as label, i.description as description, i.pw as pw, i.login as login, i.pw_iv AS pw_iv, i.anyone_can_modify as anyone_can_modify, l.date as date, n.renewal_period as renewal_period, l.action as log_action, l.id_user as log_user 
FROM teampass_items as i 
INNER JOIN teampass_nested_tree as n ON (i.id_tree = n.id) 
INNER JOIN teampass_log_items as l ON (i.id = l.id_item)
 WHERE (i.id_tree=26) AND (i.inactif=0) AND (l.action='at_creation') 
 GROUP BY i.id, l.date, l.id_user
 ORDER BY i.label ASC, l.date DESC 
 LIMIT 0,22

**Comment by BradStephens** [comment]
That's the same issue as another issue I commented on:

https://github.com/nilsteampassnet/TeamPass/issues/1276#issuecomment-215851818

**Comment by raphaelvigee** [comment]
@nilsteampassnet Yes, new feature from MySQL 5.7, but all the queries in TP needs to be rewritten...

**Comment by nilsteampassnet** [comment]
Yes absolutely ... I need to understand more this new constraint and update existing queries

**Comment by nilsteampassnet** [comment]
@raphaelvigee Did you make the try with the change done in phpmyadmin?

**Comment by nilsteampassnet** [comment]
Quickly checked the queries where GROUP BY is used.
I think this one is the one that could generate errors.

**Comment by BradStephens** [comment]
My understanding is that ever column you select must also appear in the GROUP BY clause if you're using GROUP BY in a query. Would probably work to search the entire code base for GROUP BY and review the relevant queries.

**Comment by raphaelvigee** [comment]
@nilsteampassnet I'm sorry, I don't have time to do it, I just noticed that nothing is working anymore...

**Comment by nilsteampassnet** [comment]
In file ./sources/items.queries.php, replace
```
                        GROUP BY i.id
```
by
```
                        GROUP BY i.id, l.date, l.id_user
```
Checked other queries, and should be ok

**Comment by raphaelvigee** [comment]
It works ;)

**Comment by BradStephens** [comment]
Seems to have worked. I think there are some other GROUP BY issues here:

https://github.com/nilsteampassnet/TeamPass/blob/2.1.26-RC1/sources/items.queries.php
lines 1715 and 1734.

https://github.com/nilsteampassnet/TeamPass/blob/2.1.26-RC1/sources/views.queries.php
Line 142

**Comment by BradStephens** [comment]
Actually, I'm sorry Nils - this didn't correct my original issue with the unexpected token. I'm not sure whether raphael's issue was actually related at all...

**Comment by BradStephens** [comment]
And now I understand what raphael was referring to - the ajax request - and your query does appear to have fixed the issue. I'm not sure why I was still seeing it earlier, but on my Ubuntu instance with PHP 7.0.4, it's working fine.

**Comment by nilsteampassnet** [comment]
Perfect!

**Comment by BradStephens** [comment]
Nils,

I'm still seeing this error on a fresh installation of the 2.1.26 (2) release. Here is the query returned from items.queries.php, and the error when executed in MySQL.

```
mysql> SELECT i.id AS id, i.restricted_to AS restricted_to, i.perso AS perso,
    ->                         i.label AS label, i.description AS description, i.pw AS pw, i.login AS login,
    ->                         i.pw_iv AS pw_iv,
    ->                         i.anyone_can_modify AS anyone_can_modify, l.date AS date,
    ->                         n.renewal_period AS renewal_period,
    ->                         l.action AS log_action, l.id_user AS log_user
    ->                         FROM teampass_items AS i
    ->                         INNER JOIN teampass_nested_tree AS n ON (i.id_tree = n.id)
    ->                         INNER JOIN teampass_log_items AS l ON (i.id = l.id_item)
    ->                         WHERE (i.id_tree=1) AND (i.inactif=0) AND (l.date=(SELECT date FROM teampass_log_items WHERE action IN ('at_creation', 'at_modification') AND id_item=i.id ORDER BY date DESC LIMIT 1))
    ->                         GROUP BY i.id, l.date, l.id_user
    ->                         ORDER BY i.label ASC, l.date DESC LIMIT 0,15;
ERROR 1055 (42000): Expression #12 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'teampass_ubuntu.l.action' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by BradStephens** [comment]
I changed line 1727 of sources/items.queries.php to read as the following, and the issue is resolved:

`GROUP BY i.id, l.date, l.id_user, l.action`
