### ISSUE TITLE
How to change owner of item in the database

### ISSUE THREAD

**Issue by dataegg** [nilsteampassnet/TeamPass#1282]
Hi

Does anybody know how I can change the owner of items in the database. One user entered all the information in teampass. Is the database layout documented somewhere?

Kind regards,
Martin

**Comment by dataegg** [comment]
nobody?

**Comment by nilsteampassnet** [comment]
You will need some time.
The author of an item is logged in table `log_items` using the keyword "at_creation" and the user_id.

So you need to identify the user_id (using table `users`), the item_id (using table `items`), and then go back to table `log_items` to perform a search on it using previous data. This will give you the correct entry that you can now associate with new author.

But such practice is not really recommanded for traceability as you change the history directly in DB ;)

**Comment by dataegg** [comment]
ok thanks. I think this is no problem, I'm a database administrator bij profession. I'll post the queries/update statements here for anybody else who needs this but I'm a little short in time currently so it may take a few days.
