### ISSUE TITLE
MySQL Error when trying to access site

### ISSUE THREAD

**Issue by rashidx** [nilsteampassnet/TeamPass#1283]
After successfully installing Team Pass, I was taken to the homepage, where I was presented with a MySQL syntax error.
`Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' label='SELECT * FROM teampass_languages GROUP BY name ORDER BY na' at line 3
Query: SELECT * FROM teampass_languages GROUP BY name ORDER BY name ASC`

`mysql --version
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper`

**Comment by nilsteampassnet** [comment]
Closed in #1276

Thanks
