### ISSUE TITLE
upgrade 2.1.25 to 2.1.26-RC1

### ISSUE THREAD

**Issue by BenoitPel** [nilsteampassnet/TeamPass#1284]
hi,

I try to upgrade 2.1.25 to 2.1.26-RC1 and i have a problem on step4

> Step 4
> The upgrader will now update the database by running several upgrade scripts.
> An error occurred. Please check and relaunch.
> 13:54:6 - ERROR: An error appears when adding field can_manage_all_users to table Users! !
> 13:54:06 - upgrade_run_2.1.26.php - Loop #1
> 13:54:05 - upgrade_run_db_original.php - Loop #1

**Comment by nilsteampassnet** [comment]
Just tried to upgrade from 2.1.25 to 2.1.26-RC1 and could not reproduce.
![2016-05-09 19_35_44-teampass installation](https://cloud.githubusercontent.com/assets/1197546/15121981/46685d9c-161d-11e6-90f0-adbcf4d5b3c3.png)
When did you download the RC1 package?
Can you check the structure of table `Users` and tell me if field `can_manage_all_users` exists?

**Comment by BenoitPel** [comment]
hi,

i try this yesterday morning.

can_manage_all_users exists.

**Comment by nilsteampassnet** [comment]
Confirmed if this field already exists.

Corrected in 2.1.26-RC1 branch

**Comment by BenoitPel** [comment]
thanks, i will try this today and get you feedback !

**Comment by BenoitPel** [comment]
nice resolution, its work :)
