### ISSUE TITLE
[feature] Roles management UI improvement

### ISSUE THREAD

**Issue by michmich9337** [nilsteampassnet/TeamPass#1285]
Hi Nils,

Do you know if it would be hard to add a filter function on root folder to simplify their right management ?
For roles.php / roles.load.php

**Comment by nilsteampassnet** [comment]
Can you give more details?
I don't understand what would be the feature.

**Comment by michmich9337** [comment]
Ah, okay, no problem :)
So...
As example, you have root folder called "A,B,C,D,[...]X,Y,Z"
And roles "role1,role2,[...]role10"

When you will have some subfolder for each root folder, their right management will be really difficult.
Adding some filter based on root folder and roles, to limit the number of rows/columns should simplify it.

Like : Want to manage folder B, and subfolders for role2,3,4 ? Select root folder B and role2,3,4 and manage it !
I hope its more comprehensive :D
