### ISSUE TITLE
Import from file not working

### ISSUE THREAD

**Issue by jcboysha** [nilsteampassnet/TeamPass#1287]
I'm attempting to import a file. When I select the "Import a File" option from the menu, I get the pop-window and a spinning gear. It sat like this for 1 hour before I stopped it. 

Steps to reproduce:
- Login as standard user
- In dropdown menu to left of "Folders" select import file

Can anyone give me a hand with this?

**Comment by nilsteampassnet** [comment]
What version?
Can you try with 2.1.26?

**Comment by nilsteampassnet** [comment]
I think it is similar to #1277.

**Comment by yasiryagi** [comment]
Hi guys,

I am running 2.1.26 and I cannot upload too, seeing the same as above!

**Comment by yasiryagi** [comment]
Fixed, bad config!!
