### ISSUE TITLE
Error when Enabling Personal Folder

### ISSUE THREAD

**Issue by ivan-exness** [nilsteampassnet/TeamPass#1288]
Can't enable Personal folder to user

TeamPass 2.1.25  2009 - 2015 

![screenshot 2016-05-13 18 15 30](https://cloud.githubusercontent.com/assets/17728801/15252484/c84b0cc6-1936-11e6-93ba-2759bbc48c80.png)

**Comment by nilsteampassnet** [comment]
I cannot reproduce this.

Could it be possible to have the answer from the server in the console?
What version of TP do you use? 2.1.25-2?

If it is a new install, I recommend to directly jump to 2.1.26-RC1 available in "development" branch and released tomorrow.
