### ISSUE TITLE
Error & UI Issue with copying/showing password

### ISSUE THREAD

**Issue by BradStephens** [nilsteampassnet/TeamPass#1289]
TeamPass 2.1.25

When I copy or show a password on the tree view page, I see a 500 error popup due to a syntax issue - there's a "break" statement on line 86 of sources/items.logs.php. I assume this should be an exit.

After changing that to an exit to fix the syntax error, clicking "show password" shows the password for only a few milliseconds - it disappears right away.

**Comment by nilsteampassnet** [comment]
Can you perform a screen-capture?
I don't see where it is.

Thanks

**Comment by BradStephens** [comment]
Here ya go: https://drive.google.com/open?id=0B14smXLf4BWUZm51bGNPbVQ1Xzg

**Comment by nilsteampassnet** [comment]
Well this is by design.

The password is displayed during the time you press your mouse button.
If you want to copy it, you need to use the button "copy to clipboard" that is at the left of the password.

**Comment by BradStephens** [comment]
I see. Perhaps this should be indicated in the tooltip like "Click and hold to display the password" - this wasn't intuitive to me, as almost nothing in the web browser requires a click-and-hold.

**Comment by nilsteampassnet** [comment]
Yes you're right.
The tooltip could be improved as propose
