### ISSUE TITLE
Update Problems

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1290]
Hello!
Trying to update Teampass from 2.1.25 to 2.1.26.
But after checking screen where all is green and clicking next I see this window and that all.
Help me update to latest version.

![update 1](https://cloud.githubusercontent.com/assets/4628571/15295915/a48b23f4-1b9b-11e6-83fd-4957d7045a42.jpg)
![update 2](https://cloud.githubusercontent.com/assets/4628571/15295914/a487d74e-1b9b-11e6-836c-444e9301e97d.PNG)

My update procedure:
1.mysqldump of database
2.Rename teampass folder to teampass_old
3.Downloaded and unziped teampass to teampass folder
4.Copy settings, files, upload folder from old install to new one
5. Run teampass\install\upgrade.php

**Comment by nilsteampassnet** [comment]
What is the error received from server using the console?

**Comment by reginfo** [comment]
So, to get an console output I`ve installed FF.
Because it is my production environment and we use it all day I revert changes. Now I repeated my steps and open ./install/upgrade.php in FF and voila - I can move forward. But after checking absolute path to SaltKey and selecting Next I receive window (post above 2nd picture). Get Error in upgrade.js (51 row, 1 column).
But now my TeamPass version is 2.1.26.1
![teampass error](https://cloud.githubusercontent.com/assets/4628571/15333873/1b8adfca-1c74-11e6-82dc-a5674b6dcea5.jpg)

**Comment by reginfo** [comment]
Another Update problem from 2.1.26.1 to 2.1.26.4
Error at 	
jquery.min.js (row 18)
![teampass1](https://cloud.githubusercontent.com/assets/4628571/15835222/a07f2cb8-2c37-11e6-9bf4-e8dfd87390dd.png)

Please Help
