### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by andy-kosinski** [nilsteampassnet/TeamPass#1292]
TeamPass-2.1.26.2 is working on Ubuntu 14.04 but on Ubuntu 16.04 is failing with error:
 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
![teampass_-_2016-05-18](https://cloud.githubusercontent.com/assets/10500636/15353694/2267e2f2-1ce2-11e6-8276-ebe22c2f9ec1.png)

**Comment by BradStephens** [comment]
Check this thread - seems the error is slightly different, but it may be a similar issue.

https://github.com/nilsteampassnet/TeamPass/issues/1279

**Comment by nilsteampassnet** [comment]
Please give the error sent back by server using Firebug console.

**Comment by andy-kosinski** [comment]
POST https://teampass/sources/main.queries.php 200 OK 	128ms	jquery.js (line 8706)

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create clipboard.min.js (line 7, col 7185)

Use of getPreventDefault() is deprecated. Use defaultPrevented instead. jquery.js (line 5375, col 28)

Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
functions.js (line 256)

TypeError: data is undefined index.p...e=items (line 1712, col 1)

NS_ERROR_IN_PROGRESS: Component returned failure code: 0x804b000f (NS_ERROR_IN_PROGRESS) [nsICacheEntry.dataSize] netCacheReader.js (line 307) <System>

NS_ERROR_IN_PROGRESS: Component returned failure code: 0x804b000f (NS_ERROR_IN_PROGRESS) [nsICacheEntry.dataSize] netCacheReader.js (line 283) <System>
2
NS_ERROR_IN_PROGRESS: Component returned failure code: 0x804b000f (NS_ERROR_IN_PROGRESS) [nsICacheEntry.dataSize]
netCacheReader.js (line 307)

**Comment by nilsteampassnet** [comment]
Can you activate XMLHTtpRequest so that we can see the answer from server?

Can you also try to disable feature
![image](https://cloud.githubusercontent.com/assets/1197546/15403595/1179ccda-1dfa-11e6-89ff-c7438ddf32b0.png)

And make a try.
I suspect there is bad configuration somewhere on server and a extension is not correctly set.

**Comment by havelockit** [comment]
Hi, I tried your above suggestion but to no avail - the error message is still appearing.

Is there anything else I can try to resolve or help to debug the issue?

**Comment by havelockit** [comment]
Forget that, I amended the lines 1752 and 1771 to 
`GROUP BY i.id, l.date, l.id_user, l.action`

as per [#1279](https://github.com/nilsteampassnet/TeamPass/issues/1279)
