### ISSUE TITLE
New Install - What should I do?

### ISSUE THREAD

**Issue by BradStephens** [nilsteampassnet/TeamPass#1293]
Hi Nils,

I really need to get a TeamPass instance into production. I currently have a working 2.1.26 (2) pre-release version setup. I'm concerned that if I start in production with this version, changes that come in the final 2.1.26 release will require that I start over with a fresh installation again when 2.1.26 final is released. Is there a safe upgrade path for this scenario? If there are database changes, will they take effect using the upgrade script?

Thanks.

**Comment by nilsteampassnet** [comment]
Hi Brad,

No there will not be any update of DB.
I'm still keeping 2.1.26 as pre-release to finalize some code part (minor correction) and clean some unused files.

But 2.1.27 will be quickly released just after, because it will only introduce one thing which is the change of encryption protocol .

**Comment by BradStephens** [comment]
Thanks. It sounds like I can easily get 2.1.26 final working when it's done. In order to do this the best way, would I extract the 2.1.26 final over top of my existing installation, or create a fresh directory and copy config files over? If the latter, what config files or directories need to be moved into the new path?

**Comment by nilsteampassnet** [comment]
As I will try to clean up un-needed files away, I would suggest the second solution.
Don't forget to give the exact same name as the original folder once you have copied the config files.
You will also have to copy the files inside "files" folders.
