### ISSUE TITLE
Files don't upload 2.1.26

### ISSUE THREAD

**Issue by gaborveres-planorama** [nilsteampassnet/TeamPass#1295]
Hi Nils,

I have a problem uploading any files & images to items.
- File browse / selection works ok, although as soon as the file chooser opens, I receive a 
  `csrfprotector.js:286 Uncaught TypeError: Cannot read property 'split' of undefined` error in the console (might be unrelated)
- File upload starts but percentage counter stops at seemingly random values between 1% and 8% and won't move further (the exact percentage seems to be depending on the total file size, with smaller files the percentage is higher, and it seems to be always the same for the same file)
- No error message in console (except for the above one thrown again after clicking Start uploading files) and apache error.log
- No file created on server

Stuff I've checked with no luck:
- directory permissions on the server - OK
- mod_security disabled / enabled - same results
- originally I was on 2.1.24 (same problem), so I did an upgrade to 2.1.26 - same results
- uploading different file types: jpg, txt, pem - same results

I'm pretty much lost here, any help would be appreciated.

Config: Teampass 2.1.26, Ubuntu 14.04.4, stock Apache 2.4.7
Client side: OSX El Capitan 10.11.4 (15E65), Chrome Version 50.0.2661.102 (64-bit), Safari Version 9.1 (11601.5.17.1)

**Comment by gaborveres-planorama** [comment]
I've experimented with a 1-byte long txt file and the results are somewhat different:
- counter reaches 100%
- TypeError mentioned above still thrown
- file is not saved

**Comment by nilsteampassnet** [comment]
The error is indeed related to the issue you are experimenting.
Can you please rename the file ...\Teampass\includes\libraries\csrfp\js\csrfprotector.js to something else and copy the one I've attached to this file at the same place.
Then change the variable CSRFP_TOKEN at line 15 with the one existing in your old file.

Clear the cache. Close browser. And retry.

Please give me a feedback.

**Comment by gaborveres-planorama** [comment]
Thanks, the upload works fine with the new .js file, although a new error is thrown related to it during page load to the console:
`csrfprotector.js:146 Uncaught TypeError: Cannot read property 'value' of null`

**Comment by Spikeophant** [comment]
Can confirm the fix.  I did the above and I can now upload files.

**Comment by bublboblz** [comment]
Hi Nils,

I experienced the same issue (as well as #1287) until I replaced csrfprotector.js, I can now upload.
At line 15 of each files, only the CSRFP_FIELD_URLS variable is declared, their content don't differ.
Do I need to change line 18
    CSRFP_TOKEN: 'csrfp_token',
to 
    CSRFP_TOKEN: '',
as in my original file ?

Thank you,
Fabrice

**Comment by nilsteampassnet** [comment]
Hi

Did you get and installed the last release?

**Comment by bublboblz** [comment]
Salut Nils,

c'est Fabrice, de Poitiers
je suis content d'avoir de tes nouvelles, mes derniers mails étant 
restés sans réponse j'espère que tu vas bien et que ton nouveau taf te plait
oui, je suis bien sur la dernière version

Fab

**Comment by andreyoc** [comment]
Work fine on TeamPass 2.1.25  2009 - 2015
