### ISSUE TITLE
Encrypted field for other text besides passwords

### ISSUE THREAD

**Issue by sorinpaduraru** [nilsteampassnet/TeamPass#1296]
Hello,

I've recently had the need to add ssh private keys to TeamPass so at first:
1. I tried using the description field to keep that private key but then found out the description field is not encrypted.
2. I tried increasing the length of the password field to > 2000 characters which worked in that I could save the private key & access it by API. What I couldn't do is see it afterwards in TeamPass (guess it's some kind of glitch).

Some solutions I'm thinking of would be:
1. Encrypting the description field and make it a multi-purpose container for all kinds of text you want secured, besides passwords
2. Modify the password field & transform it in a free-form encrypted field that could store ssh keys, putty private keys etc? 

L.E. 
Maybe it would be better to change this to some kind of bug? 
As in: You can insert a 2000 character password but when trying to see that password in Teampass you just get an empty line.
You can however see it through the API.

Thank you,
Sorin

**Comment by nilsteampassnet** [comment]
I recommend you to use ["Categories"](http://teampass.net/2013-03-25-custom-categories-and-fields)

**Comment by sorinpaduraru** [comment]
Thank you for your suggestion!
I will try this as it seems it's exactly what I need.

**Comment by sorinpaduraru** [comment]
I've tested the functionality and it works like a charm.

There's two more things that I would like to ask for your help into:
1. I would like to ask if there's any possibility of accessing these fields through the API at this time or you have any plans of providing this in the near future.
2. Is there any way of setting these categories/fields to other types ? Like: text box instead of line... Ex: Saving a private key in a default custom field and copying it back results in a long line of text instead of a properly formatted private key.

Sorry if re-opening the issue is not the proper way of asking for help.
Thank you again and congratulations for this great tool!

**Comment by dimumlik** [comment]
Hello!
Join the question.
Keeping of private keys of certificates is the necessary function of the password manager!
I would like to be able to save just the text field and copy the key, similar to copying the password.

Thank you!

**Comment by dimumlik** [comment]
And one more problem. Do not work Category order sorting:
![default](https://cloud.githubusercontent.com/assets/7734544/26731652/669d243a-47bd-11e7-9c00-0d0785bcc8a7.png)
![default](https://cloud.githubusercontent.com/assets/7734544/26731716/95bc6ee2-47bd-11e7-9199-3979a66625e2.png)
