### ISSUE TITLE
New user can see all records (LDAP)

### ISSUE THREAD

**Issue by jhrasko** [nilsteampassnet/TeamPass#1297]
Hi there,
I would like to ask you for help with our issue. Our case is:

When a new user (not existing in TeamPass db) will perform first login. During first logon user receives message that his account was created then page is reloaded to login again. I believe this is normal and it should be this way.
Problem is that after login such fresh user this user can see all folders and keys that are defined in TeamPass. And by all I mean all including personal folders of other users. User is able to browse all folder and see all records and view all passwords that are salted with general salt key. The only thing that user can not see are salted personal passwords but records are visible.

These are the default rights after user login - no role assigned (that should imply no acces except own home folder)
![tp1](https://cloud.githubusercontent.com/assets/19485452/15421049/8f982d92-1e71-11e6-84ac-33cfb4c1f5d3.PNG)

And this is the problem itself as you can see user sees everything with no role set:
(missing folder descriptions were removed, numbered folders are personal folders of other users)

![tp2](https://cloud.githubusercontent.com/assets/19485452/15421050/8f9cc834-1e71-11e6-8ed1-015083ad05d2.PNG)

Some facts that I discovered during testing:
1. in some cases relog will fix this
2. in some cases while browsing "Hacking attempt" appear and that will fix it
3. in some cases user can browse keys even after relog
4. it is fully replicable by deleting the user and login again it only differs in behavior points 1-3

Is there any fix for this? Or any workaround? For example is there way to define/hard-code default role for new user?
For now I'm going to limit logging users on OU level only to admins. But the original idea was to share general passwords with all users authentificted through LDAP in TeamPass

TeamPass 2.1.26 (the problem persists from *25 upgrade to *26 did not fix this issue)
CentOS Linux release 7.2.1511
mariadb  1:5.5.47-1.el7_2
php 5.5.35-1.el7.remi
LDAP backend is AD

Thank you.

**Comment by jhrasko** [comment]
Sorry for the duplicate same problem already discussed here I was unable to find it before :( wrong keywords.
https://github.com/nilsteampassnet/TeamPass/issues/1153

**Comment by chetanpachare** [comment]
Finally, I have reached to the problem.
This problem can be solved by setting the option "Enable Personal folder feature= No " in team pass setting page.

Then try to login via LDAP users. You will not see any exiting folders.

Thanks.
