### ISSUE TITLE
Export to pdf or csv shows  htmlencoded

### ISSUE THREAD

**Issue by chc88** [nilsteampassnet/TeamPass#1299]
Hello,

When making a PDF or CSV export formatting paths like \192.168.0.1\path\to\my\folder
or in username like domain\username is messed up due to html-encoding:

In description: &#92|&#92|192.168.0.1&#92|path&#92|to&#92|my&#92|folder
In login: domain&#92;username

Also I see that not all fields are being exported (including URL, Email, Tags and KB which should be very nice to have in the export).

**Comment by nilsteampassnet** [comment]
Corrected in 2.1.27
