### ISSUE TITLE
How to import password files into team pass

### ISSUE THREAD

**Issue by praburaj06** [nilsteampassnet/TeamPass#1303]
HI I am new to teampass,How to import password files into team pass as i couldn't see any import options in menu???

**Comment by nilsteampassnet** [comment]
You need to enable the feature from admin settings page.

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass  from admin settings page and I do not get the option to import in the folder menu. What I do?

**Comment by Calanon** [comment]
I also do not get the option to import after setting allow in the admin settings page, any answer to this?
