### ISSUE TITLE
constructive criticism

### ISSUE THREAD

**Issue by sputnik99** [nilsteampassnet/TeamPass#1304]
Hello, 
I've tried this software in the last release 2.1.26 and I've found some inconsistencies:
- **Roles**: For all admin people a role its a method to give more or less permissions inside an application. Here its seems like a groups. I recommend author to look how it works roles in other apps like ESXi.
- **Labels**: I suppose author know how it work keepass. There you have a field where you can specify what you want to keep. Example "domain admin" and you can have more than one "domain admin" labels in different folders. Here is not possible! In my case I use folders like clients or a place where you keep credentials that have some in common like credentials of a server. Example, root of linux, user of linux, user and passwd of database for Teampass, etc,.. If I have more than equal structure in different places I can't use because labels can't be the same.

**Errors**:
1. If you create a role and folder and you assign for a role permission for read only to this folder, You must to specify to the user that the permission is for read only. It doesn't work inherit permissions. This doesn't occurs if you mark write permissions without delete or edit.
2. If you create a user without permissions to administer anything, this user can add roles inside of his profile than later the administrator can't see or delete. You know that they exist because if you want to create new one with the same name the application give a warning telling you that this role exists.

I will hope this comments help to improve the application because I like the concept but I think it needs to change some aspects to be better.

Thanks for reading and for the great job of Nils Laumaillé.

**Comment by nilsteampassnet** [comment]
Thank for those constructive remarks. I'm always interested in what users think ;)
So I will try to answer.

- **Roles**: You are probably right but it is more that a simple group. I've always been unsatisfied of this word "role" inside this tool, and "group" doesn't suit too. I could imagine to restart my reflection on this point as now the tool is more mature.

-  **Labels**: Similar labels can be used but requires from your admin to enable this option.

-  **Error#1**: Very interesting. I need to investigate to answer in a better way.

-  **Error#2**: Can you explain more in details how to reproduce this. I don't catch from where you do this.

Thanks for opening this interesting topic, and if you could detail for error#2
