### ISSUE TITLE
Can't login using admin user

### ISSUE THREAD

**Issue by rligocki** [nilsteampassnet/TeamPass#1305]
After fresh installation I can't login using admin user. I can see that after pressing login button I am redirected to main menu, but right after it redirect me into login screen. I tried other versions, but nothing works.

**Comment by nilsteampassnet** [comment]
Something is wrong with your configuration.

Have you set a password during installation?
Perhaps some files are missing.

Can you get the errors returned by server (using [Firebug](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))?

**Comment by rligocki** [comment]
Hi,

thanks for your response. Right now it’s ok. Problem was in session duration. Time of server was different from time of client and when it was too small, it thought that session ended.

Right now we are testing whole system and it is great.
Thanks a lot.
Romek
