### ISSUE TITLE
Import csv file created from older teampass version

### ISSUE THREAD

**Issue by silvarius** [nilsteampassnet/TeamPass#1306]
Hello,

We would like to import a csv file exported from a teampass instance 2.1.15 into an teampass instance 2.1.26. Up to now, we haven't succeded. I get this error:

![image](https://cloud.githubusercontent.com/assets/8503909/15497993/04659d76-21a6-11e6-842e-c3d886bbc432.png)

I can't choose a folder, as none are proposed.

Trying to understand how export/import was working, I created a cvs export from 2.1.26 that I could successfully import in the same instance afterwards. I checked and saw that the 2 csv files (from 2.1.15 and 2.1.26) have exactly the same csv data structure. Exploring further, I also noticed that if I changed one letter from the file name created from 2.1.16 (that I could previously successfully import),  I then couldn't import it anymore.

All in all, In don't understand the role of file names in export/import structure, and more globally, what are the conditions to be able to successfully import. It would be very helpful to get some explanations about this subject. Up to now, I'm stuck with my csv file from 2.1.15 without the possibility to import it in my new 2.1.26 instance.

Finally, I would like to take advantage of this post to thank you for all the work and energy you put in this project. We've been using Teampass for years now and have been very satisfied of it.

Cheers

Jérôme ULRICH

**Comment by nilsteampassnet** [comment]
Did you download the last release 2.1.26.3?

The bug you are encountering is normally corrected in the last one

**Comment by silvarius** [comment]
Hello,

We installed the latest release and I faced on import attempt a 500 error. A dev of ours spent some time to research this error and got this error details:

_"[:error] [pid 6237] [client 192.168.7.118:40005] PHP Fatal error:  Uncaught exception 'Goodby\\CSV\\Import\\Standard\\Exception\\StrictViolationException' with message 'Column size should be 1, but 4 columns given' in /var/www/html/other-projects/p.atalan.net/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php:119\nStack trace:\n#0 /var/www/html/other-projects/p.atalan.net/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php(42): Goodby\\CSV\\Import\\Standard\\Interpreter->checkRowConsistency(Array)\n#1 /var/www/html/other-projects/p.atalan.net/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(68): Goodby\\CSV\\Import\\Standard\\Interpreter->interpret(Array)\n#2 /var/www/html/other-projects/p.atalan.net/sources/import.queries.php(136): Goodby\\CSV\\Import\\Standard\\Lexer->parse('/var/www/html/o...', Object(Goodby\\CSV\\Import\\Standard\\Interpreter))\n#3 {main}\n  thrown in /var/www/html/other-projects/p.atalan.net/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php on line 119"._

It seems there is an error in column management.

Maybe you can help with this?

Thanks in advance.

Kind regards

Jérôme ULRICH

**Comment by nilsteampassnet** [comment]
I've published some changes on CSV import some minutes ago.

Don't know if your error is related but I suggest you make the evolution (see [Development branch](https://github.com/nilsteampassnet/TeamPass/tree/development))
