### ISSUE TITLE
Add Estonian translation

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1310]
Request: Please add Estonian translation from POEditor and language selection flag. Thank you!

**Comment by nilsteampassnet** [comment]
will do

**Comment by tehnotronic** [comment]
In "install/upgrade_run_2.1.26.php" you insert new language "Estonia", but I think it should be "Estonian" like the translation file "includes/language/estonian.php"

**Comment by tehnotronic** [comment]
Thank you for fixing update script! I found that the same typo was also in "install" script. Please fix that one too: [https://github.com/nilsteampassnet/TeamPass/blob/master/install/install.queries.php#L609](https://github.com/nilsteampassnet/TeamPass/blob/master/install/install.queries.php#L609)

**Comment by tehnotronic** [comment]
Currently it doesn't display "users", "folders" and "roles" pages content, when estonian language is active. It works with frontpage, settings and views. In other languages all pages are working. Using latest code from master repo.

**Comment by tehnotronic** [comment]
Looks like missing language/estonian_admin_help.php - adding with english content seemed to solve the problem

**Comment by nilsteampassnet** [comment]
Correct, I will check this entirely
