### ISSUE TITLE
API write call fails with "Method not authorized"

### ISSUE THREAD

**Issue by sorinpaduraru** [nilsteampassnet/TeamPass#1311]
When I try to do an API call like:
`curl https://teampass.example.com/api/index.php/write/item/mytestItem?apikey=XXXX`

I always get a "Method not authorized" message.
I've checked the code a bit and added:
` $_SESSION['user_id'] = "'api'";`
under the rest_delete function as I thought it lacked authentication of some sorts but it is still not working.

Should I be doing this differently? 
Thank you!

**Comment by nilsteampassnet** [comment]
The format you give doesn't fit the expected one. 
Please refer to documentation in website

**Comment by sorinpaduraru** [comment]
Sorry mate, I cannot seem to find any documentation related to the `write` call.
I've been using the source code & this: [http://teampass.net/2014-05-18-teampass-api](url) as documentation. 
Do you have any resource available?
Thank you!

**Comment by nilsteampassnet** [comment]
http://teampass.net/2014-05-18-teampass-api chapter "Add new Item"

**Comment by sorinpaduraru** [comment]
Thank you for that.
What I wanted to achieve with the write methid was to be able to DELETE items.

I am able to add items, users and to read items.
The only thing missing is deletion of items which I thought one would do through WRITE.

Thanks!

**Comment by sorinpaduraru** [comment]
So i've been checking the documentation a bit more and I tried to pass the DELETE method to the API via curl:
`curl -X "DELETE" https://teampass.example.com/api/index.php/write/item/MyCategory/mytestItem?apikey=XXXX`

Now the logs state:

> PHP Fatal error:  Cannot redeclare getBits() (previously declared in /srv/www/teampass/TeamPass-2.1.26.3/sources/main.functions.php:37) in /path/to/teampass/TeamPass-2.1.26.3/sources/main.functions.php on line 37

I really don't know if I'm headed the wrong direction or if it's just not possible to delete items via API at this time.

**Comment by sorinpaduraru** [comment]
I found the fix with the help of the pull request here: api rest_delete fix #1281 by **orkunkaraduman**.
I don't know the implications or making this change or other issues that might go wrong with using this but it sure works for me when issuing:

`curl -X DELETE https://teampass.example.com/api/index.php/write/item/MyCategory/mytestItem?apikey=XXXX`

**Comment by nilsteampassnet** [comment]
I've reworked completely this part of the API.

It has been committed in "development" branch.
You can over-write file "./api/functions.php"

Call formalism:
>Expected call format: .../api/index.php/delete/folder/<folder_id1;folder_id2;folder_id3>?apikey=<VALID API KEY>
>Expected call format: .../api/index.php/delete/item>/<item_id1;item_id2;item_id3>?apikey=<VALID API KEY>

**Comment by sorinpaduraru** [comment]
Thank you very much.
I'll do just that & wait for the code to reach the stable branch.

**Comment by sanch333z** [comment]
Hi all.
I don't understand are mobile application teampass needs installation teampass-api on server for working properly?
Help please.
