### ISSUE TITLE
No users in User management list (Version 2.1.26)

### ISSUE THREAD

**Issue by zidz** [nilsteampassnet/TeamPass#1312]
I get {"recordsTotal": 13, "recordsFiltered": 13, "data": [] } as response even though no search been done in UI.
Anyone else that has this problem?

**Comment by nilsteampassnet** [comment]
Can you make a screenshot and explain how you get this (the steps)?

Thanks

**Comment by zidz** [comment]
1. Login
2. Press the "User management" button.
3. "No matching records found" is showing in the list, even though it counts the users in the botton left as 13 entries.

![teampass-nomatchingrecordsfound](https://cloud.githubusercontent.com/assets/1188080/15664495/b19a3926-2704-11e6-9166-7c6e7e43a432.png)

**Comment by infostrada-systeembeheer** [comment]
I have a similar issue. When selecting all users with "a", i get a wrong count. There are 2 users matching, but it shows the count of all 101 users.
![teampass-users](https://cloud.githubusercontent.com/assets/8045342/15675823/fec21aea-2743-11e6-8f41-934b64473c7c.png)

**Comment by nilsteampassnet** [comment]
I believe you are connected with a manager account.

The thing is that the "counter" gives the complete view of all existing data but depending on your account and related privileges, you will not be able to see them (or only a part).
So this could indeed lead to this case where the list is empty but the counter is not.

Can you try using an Admin account?

**Comment by zidz** [comment]
I'm very sorry, there was a confusion regarding admin accounts.
