### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by jahantech** [nilsteampassnet/TeamPass#1313]
Hi, 
I am currently in process of setting up teampass with LDAP Auth. Everything is working fine. However I would like to export the password as pdf or csv for backup purposes. 

I have enabled "printing items to PDF file" via admin portal, but I don't see the export/print icon in users home page. 

Would you know what could be causing this?
Thanks,
JahanS

**Comment by nilsteampassnet** [comment]
Hello,

Once enabled, this feature is available as shown in next screen-capture.

![image](https://cloud.githubusercontent.com/assets/1197546/15683752/2b392ee0-2764-11e6-9686-8114c529801a.png)

**Comment by jahantech** [comment]
Thank you for reply. Unfortunately I don't see the export items options even if I enable the PDF export from admin settings. 

Steps:
Logged into as administrator (AD user), changed the export flag to yes. 
![pdf-file option](https://cloud.githubusercontent.com/assets/13733348/15702453/fb6d3566-27d7-11e6-83da-2de257fb753b.JPG)
Logged in as a normal user and tried to export entries to pdf:
![no_export_option](https://cloud.githubusercontent.com/assets/13733348/15702493/3640650a-27d8-11e6-9c69-c3587ed19698.JPG)

Do you think I need to make any changes to roles to enable export?

**Comment by jahantech** [comment]
Is it reading the flag from the database, if so would I be able to change the value in the database directly?

**Comment by jahantech** [comment]
Managed to identify the issue. It was print for each user role that I had to select too!.
