### ISSUE TITLE
Teampass upgrade 2.1.22 to release 2.1.26

### ISSUE THREAD

**Issue by rstoever** [nilsteampassnet/TeamPass#1315]
### Teampass version:

2.1.22
### Operating system (Linux / Windows):

Linux
### Apache version:

Server version: Apache/2.2.15 (Unix)
Server built:   Oct 16 2014 14:48:21
### MariaDB version:

mysql  Ver 14.14 Distrib 5.6.25, for Linux (x86_64) using  EditLine wrapper
### PHP version:

PHP 5.3.3 (cli) (built: Jul  9 2015 17:39:00)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
### Browser and version

Chrome
### Ask

For upgrade 2.1.22 to 2.1.26, I need to step 23,24,25 and 26 ? or I can to jump to 26 directly ?
Have a list of requirements on library of php or others ?

**Comment by nilsteampassnet** [comment]
I think you should at least upgrade to 2.1.23 because this release introduced a new encryption protocol.
Then I think you can go on directly with 2.1.26.
Notice that 2.1.26 introduce a new upgrade manager that will handle in a better way "gig" upgrades.

Please make a DB dump before every upgrade, and a zip package of /teampass/ folder.
Just in case ...

**Comment by rstoever** [comment]
I was upgrade from 22 to 23 and ok.
But when I was to upgrade to 26 the passwords is blank
Or when I was to upgrade from 23 to 24 the passwords is blank
Why ?

And I was to tests to upgrade in test environment. But I need to upgrade it.

**Comment by marcguilemany** [comment]
Hi nil,

I can't upgrade to 2.1.7 to 2.1.26, the upgrade can not work. I see others issues for upgrade and I change browser and the step 3 it's ok, but when I continue to step 4, can not continue.

It's possible access other version Like for example 2.1.23 for upgrade?

Ty to respond me.

Marc.

**Comment by rstoever** [comment]
I noticed that there were changes in the validation and migration of authentication keys of the items, and I think the problem is not successfully upgrade to migrate passwords.

**Comment by prozit** [comment]
I am having the same issue. The upgrade seems to work fine, but all the passwords are blank. Actually I tried this with all versions from 2.1.22 to 2.1.24, 2.1.25, 2.1.26. All with the same result. The only version it is working with is 2.1.23.

**Comment by jgeget** [comment]
I am also have an issue with this. After upgrading to 2.1.26 we can't see the password at all. It is still in the database. We are using PHP 7 Apache 2.2.15 MYSQL 5.5. I have attached screenshots. Please let me know if there is anything we should try.  Thanks in advanced. 
![image1](https://cloud.githubusercontent.com/assets/21061730/17702812/7b93f242-639d-11e6-906c-c88537c4ccc5.png)
![image2](https://cloud.githubusercontent.com/assets/21061730/17702813/7ea3c1d8-639d-11e6-99ca-5146e097ce89.png)

**Comment by nilsteampassnet** [comment]
Too difficult to debug without concret data.
Can you provide me an access to server with AMMYY?
I would like to perform the update to monitor the data and identify the bug.

**Comment by jgeget** [comment]
We can do that. How do you want to set this up? We wouldn't be able to do it today though. Most likely tomorrow.

**Comment by BMWOdin** [comment]
I am also have an issue with this. Describe the method of solution. Versions from 2.1.13 to 2.1.26,
