### ISSUE TITLE
Teampass upgrade 2.1.25 to 2.1.56 RC4 - error on upgrade.php

### ISSUE THREAD

**Issue by nexosone** [nilsteampassnet/TeamPass#1316]
### Teampass version:

2.1.25 to 2.1.56 RC4
### Operating system (Linux / Windows):

Debian 8.5
### Apache version:

Server version: Apache/2.4.10 (Debian)
### mysql version:

mysql-server                   5.5.49-0+deb8u1
### PHP version:

PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
### Browser and version

Version 50.0.2661.102 m
### Expected behavior

normal teampass upgrade to 2.1.26 -RC4
### Actual behavior

After pressing next on step 1 in the upgrade php we get an empty page, with the the buttons launch and next. The apache error.log is empty. The folder of teampass has read, write and execute rights.
### Steps to reproduce

Is easy to reproduce on our system. It should be the same on other systems.

**Comment by reginfo** [comment]
Try to use different Browser. I try thru IE - problem as yours. With FF - all Ok!
