### ISSUE TITLE
Different default settings for password generation?

### ISSUE THREAD

**Issue by jonathan-chin** [nilsteampassnet/TeamPass#1318]
### Teampass version:

2.1.26
### Expected behavior

Default settings for password generation would be nice. I like them all alpha numeric (no punctuation) and 16 characters. Every time I generate a new password, I have to make the same changes.
### Actual behavior

Settings are always set to 8 characters long, secure.

**Comment by nilsteampassnet** [comment]
I could make those settings customizable through Settings page.

**Comment by jonathan-chin** [comment]
in the mean time, can you tell me where in the source code these defaults are set? I can patch it while I wait for an update.

thanks! this is the best open source solution to password management. I've tried almost all of them before landing here.

**Comment by fjnalta** [comment]
I would also be interested in knowing where i can change the default password generation settings. I don't need the setting in the web-gui urgently as it is only a 'one time change'.
