### ISSUE TITLE
Lost a creating new sub-folder when I log out 

### ISSUE THREAD

**Issue by abdelbassit** [nilsteampassnet/TeamPass#1319]
Hello, 

I Installed TeamPass 2.1.26, but I have this problem: that when I create a new folder or sub-folder and after I log out and log in I can't see this new folder, to see it I have to enter as Admin and give permissions to the user (even if the user is the same that created this folder), Any Suggestion to resolve this problem?

Thanks,

**Comment by nilsteampassnet** [comment]
This is a known bug that was corrected in 2.1.26(4).

Are you sure you didn't install a release before (4) ?

**Comment by nilsteampassnet** [comment]
I need to know what intermediate draft release you have.

**Comment by abdelbassit** [comment]
Hello,

I don't know the intermediate draft release, I Installed this docker, I think is yours: https://hub.docker.com/r/teampass/teampass/

Thanks,
