### ISSUE TITLE
LDAP Users see everything on login

### ISSUE THREAD

**Issue by jcboysha** [nilsteampassnet/TeamPass#1324]
Teampass version: Latest

Operating system (Linux / Windows): Ubuntu

Browser and version: Firefox Latest

Users, upon login, see all items and can access them.

**Comment by chetanpachare** [comment]
I have same issue......LDAP users are able to see everything at first login.
Plz provide proper solution.

Thanks.

**Comment by tehnotronic** [comment]
I cannot reproduce that on my LDAP setup. AD user that had no corresponding account on TeamPass, didn't get in and was given an error on login. If user had a corresponding local TP account, but no folders or roles associated and logged in with AD / LDAP, he didn't see any folders or items. 

Please describe the conditions - does the users have TP accounts also but no folders assigned and they see them anyway?

**Comment by jcboysha** [comment]
Upon initial login, with the user being assigned no groups or permissions, the user can see every password in the database until either a page is refreshed or they re-log.

**Comment by T3chC0rp** [comment]
I can confirm, if you use LDAP Option with "Teampass local users only" set to NO, you can see each entry if you take the intial login.

**Comment by OptimusOS** [comment]
i have the same problem by first login User can see all folders. After relogin is the Permission right.

**Comment by chetanpachare** [comment]
Finally, I have reached to the problem.
This problem can be solved by setting the option  "Enable Personal folder feature= No "  in team pass setting page.

Then try to login via LDAP users. You will not see any exiting folders.


Thanks.

**Comment by nilsteampassnet** [comment]
Very strange!

Can you please make the next change for me (as I can't debug ldap)?

Open file ./sources/identify.php

Find
```
                // is new LDAP user. Show only his personal folder
                if ($_SESSION['settings']['enable_pf_feature'] == "1") {
                    $_SESSION['personal_visible_groups'] = array($data['id']);
                    $_SESSION['personal_folders'] = array($data['id']);
                } else {
                    $_SESSION['personal_visible_groups'] = array();
                    $_SESSION['personal_folders'] = array();
                }
```
Replace by
`
                $_SESSION['personal_visible_groups'] = array();
                $_SESSION['personal_folders'] = array();
`

Please if Personal Folder is disabled, then reactivate it.

Thanks

**Comment by juanfalguera** [comment]
Tried to make those changes but they didn't work. Same issue. At first login, new user can see everybodys passwords if personal folder is enable.

**Comment by nilsteampassnet** [comment]
Ok thanks ... it was a try to check something ... please go back to initial code.

**Comment by kdubowik** [comment]
I confirm. I have the same problem.

When personal folder feature is disabled in settings, new users can see no content.

When personal folder feature is enabled, new users will see all passwords. Then, if they click refresh they only see their personal folder.

**Comment by klou** [comment]
Duplicates #1381
