### ISSUE TITLE
Minimum password complexity for folders and items

### ISSUE THREAD

**Issue by ben-git-hub99** [nilsteampassnet/TeamPass#1328]
### Teampass version:
2.1.26
### Feature Request
I would like to see a minimum password complexity be able to be enforced. This should prevent folders and items from being created with a lower complexity (unless the override flag is set for that role).
### Use Case
Currently, folders under a parent do not inherit. I don't wish to limit my users in creating folders, but I can not force them to use a minimum complexity. This creates an issue as weak credentials can be stored instead of forcing enterprise password requirements.

**Comment by nilsteampassnet** [comment]
The idea is good.

What I can suggest is that a sub-folder cannot be created with a "password complexity level" lower than the one of the top-folder.

This could be done easily (I think)

**Comment by ben-git-hub99** [comment]
Works like a charm @nilsteampassnet!
