### ISSUE TITLE
Unable to import big Keepass XML file with duplicate name of items

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1331]
### Actual behavior : Only the half is imported. The KeepassImport file trace said : 

14:53:49 Writing XML File Test.xml
14:53:49 Nombre de répertoires 7
14:53:49 Nombre d'éléments 1464
14:53:49 Creating Folders
14:53:49 Setting User Rights
14:54:00 Rebuilding Tree
14:54:01 Importing Items
[...]
14:54:15 Import finished
14:54:15 Statistics
14:54:15 Folders imported: 7
14:54:15 Items imported: 788

General\toto - Inserting
General\toto - Skipped
General\toto - Skipped

### Steps to reproduce : Big file with duplicate name.

I have watched int the MySQL table "teampass_misc" and the option for duplicate name is True : 

mysql> select * from teampass_misc where intitule LIKE '%duplicate%';
+-------+-------------------------------+--------+
| type  | intitule                      | valeur |
+-------+-------------------------------+--------+
| admin | duplicate_folder              | 1      |
| admin | item_duplicate_in_same_folder | 1      |
| admin | duplicate_item                | 1      |
+-------+-------------------------------+--------+

Thanks in advance for your help.

**Comment by nilsteampassnet** [comment]
Tested in 2.1.26 and it works.
Several changes were done during 2.1.26 for correcting importation.

Still one thing is not good. In case you have folders with the same name at the same level, then importation will store all items of those folders in a unique one (even if all folders were created).
I will fix this in futur.

**Comment by Hellnino18** [comment]
Thanks it works.
