### ISSUE TITLE
FIX - API not allowing roles separation of pipe '|'

### ISSUE THREAD

**Issue by ben-git-hub99** [nilsteampassnet/TeamPass#1332]
### Teampass version:
2.1.26
### Operating system (Linux / Windows):
Linux
### Apache version:
Server version: Apache/2.2.15 (Unix)
### MariaDB version:
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
### PHP version:
PHP 7.0.7 (cli) (built: May 26 2016 12:40:00) ( NTS )
### Expected behavior
When using http://teampass.net/2014-05-18-teampass-api (Add new USer) - Unable to add multiple roles for user using '|'.
This appears to be caused by simple conversion of utf-8 into hex (as caused by the browser).
### Steps to reproduce and fix
```
diff ./api/functions.php*
576c576
<                         foreach (explode('%7C', $roles) as $role) {//echo $role."-";
---
>                         foreach (explode('|', $roles) as $role) {//echo $role."-";
```

**Comment by nilsteampassnet** [comment]
Correct.

Pipe symbol is not good.
Changed to single comma.
