### ISSUE TITLE
This page doesn't exist

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1335]
### Steps to reproduce : After migration from 2.1.25.2 to 2.1.26.8, page on disconnect says that

In error.log of apache : 
[Thu Jun 16 17:14:05.227126 2016] [:error] [pid 1790] [client 10.194.11.6:64740] PHP Warning:  include(/error.php): failed to open stream: No such file or directory in /var/www/html/sources/main.queries.php on line 22, referer: https://teampass.mipih.net/index.php
[Thu Jun 16 17:14:05.227147 2016] [:error] [pid 1790] [client 10.194.11.6:64740] PHP Warning:  include(): Failed opening '/error.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/sources/main.queries.php on line 22, referer: https://teampass.mipih.net/index.php

This file is really present.

Thanks in advance.

**Comment by ben-git-hub99** [comment]
I have this same error.

**Comment by ben-git-hub99** [comment]
The pushed commit resolved this error.

**Comment by nilsteampassnet** [comment]
@ben-git-hub99  Thanks for feedback
