### ISSUE TITLE
PHP 7 upgrade issues solved

### ISSUE THREAD

**Issue by ben-git-hub99** [nilsteampassnet/TeamPass#1336]
### Teampass version:

2.1.20 - 2.1.26
### Operating system (Linux / Windows):

Linux
### Apache version:

Server version: Apache/2.2.15 (Unix)
### MariaDB version:

mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
### PHP version:

PHP 7.0.7 (cli) (built: May 26 2016 12:40:00) ( NTS )
### Browser and version

Chrome - latest (mac)
Firefox - latest (mac)
### Expected behavior

Upgrade should have gone smoothly.
Upgrade from 2.1.20 - 2.1.23
Upgrade from 2.1.23 - 2.1.26
### Actual behavior

Ran into several issues with the upgrade:
A. Steps for upgrade - (Repeat for each version, update path)

```
cp -Rf htdocs.2120/includes/settings.php htdocs/includes/
cp -Rf htdocs.2120/backups/ htdocs/backups
cp -Rf htdocs.2120/files/ htdocs/files/
cp -Rf htdocs.2120/upload/ htdocs/upload
find . -exec chmod 777 {} \; (DONT forget to change this back later)
```

(Note: I ran into an issue wgeting the zip from github and had to download locally and then SCP to server)
1. Various PHP 7 issues [fixed]:

Call to undefined function mysql_result() - Update to use mysqli_result (./install/upgrade_ajax.php:70, :80)

PHP Fatal error:  'break' not in the 'loop' or 'switch' context in ./install/upgrade_run_2.1.26.php:199 - change break to return

Call to undefined function mysql_num_rows() - Update to use mysqli_num_rows
Call to undefined function mysql_query() - Update to use mysqli_query (./install/upgrade_run_encryption_pwd.php:134)
### Post upgrade

```
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
```

**Comment by nilsteampassnet** [comment]
Version 2.1.27 developed and tested with php7
