### ISSUE TITLE
Failed to authenticate LDAP users with OpenLDAP

### ISSUE THREAD

**Issue by julvortex** [nilsteampassnet/TeamPass#1337]
##### Actual behavior : login failed and get a "user_not_exists"

Works with 2.1.24.4 but not with higher versions like 2.1.26.8

**In 2.1.24.x,** when a LDAP user which doesn't exist in Teampass database try to athenticate, Teampass try to bind this ldap user on OpenLDAP and then create the user in Teampass database if succeed (with a mysql INSERT query).

**In 2.1.26.x**, Teampass doesn't try to bind the user on OpenLDAP. Then instead of send a mysql INSERT request to Teampass database, Teampass still looking for user in database and finally failed because it doesn't exist.

![teampass_ldap-auth-issue](https://cloud.githubusercontent.com/assets/19995326/16152736/8a2a388a-34a3-11e6-8c00-48b465bdcfea.png)

Thanks for your help
@nilsteampassnet : congratulation for this project ! It's a very nice and successful product

**Comment by tehnotronic** [comment]
What does your ldap debug log say in files folder? To turn on, go to sources/identify.php line 16 and change $debugLdap = 0; from 0 to 1.
Also hide your passwords before posting log here.

**Comment by julvortex** [comment]
ldap.debug.txt says : 

> Get all LDAP params :
> mode : 1
> type : posix-search
> base_dn : 0
> search_base : 0
> bind_dn : cn=admin,dc=rit
> bind_passwd : password
> user_attribute : uid
> account_suffix : 0
> domain_controllers : 127.0.0.1
> use_ssl : 0
> use_tls : 0
> *********
> 
> LDAP connection : Connected
> LDAP bind : Bound
> Search filter (group): memberUid=test
> Results : Array
> (
>     [count] => 1
>     [0] => Array
>         (
>             [count] => 0
>             [dn] => uid=test,ou=users,dc=rit
>         )
> 
> )
> 
> Search filter : (&(uid=test)(objectClass=posixAccount))
> Results :

Like on screenshots of packet capture i've posted before, ldap user is found but nothing happend next. Do you have an idea ?

**Comment by julvortex** [comment]
I've found that if the "_LDAP Search Base_" field of the administration page (in section LDAP Options) is leaved to 0, the ldap authentication doesn't work because following functions in identify.php seems not to be called when $result is null... (['ldap_search_base'] beeing null too...).

As it happend, I had this issue because I couldn't update the "LDAP Search Base" field of the ldap config page. No value can set the field. It return to 0 whatever you type. I'm not a IT developer so I can see what's going wrong in the code. Do I have to close this issue to open a new one (subject changing) ?

Thanks

**Comment by tehnotronic** [comment]
Please update you code from github, it should have been just fixed. 
https://github.com/nilsteampassnet/TeamPass/pull/1333/commits/f95230145137459cac71c960ba8fc594db99fffc

**Comment by julvortex** [comment]
Thank you, it works with this fix.
