### ISSUE TITLE
Change my password screen loop

### ISSUE THREAD

**Issue by reignofterr0r** [nilsteampassnet/TeamPass#1342]
### Teampass version:
2.1.26
### Operating system (Linux / Windows):
Windows Server 2012 R2 Datacenter/IIS 8.5
### PHP version:
PHP 7.0.7
### Browser and version
Firefox 47.0

Whenever I create a new administrator user, following the link in the received email and signing in with the correct password causes a loop in the "Change my password" screen. Whatever password is entered, no matter how strong or weak returns right to the same screen. Also, pressing any of the buttons on the site will bring it back to the "Change my password" screen, INCLUDING log-out. The only way to get out of this loop is to delete the new user's account in mysql.

![wtfteampass](https://cloud.githubusercontent.com/assets/3211393/16237009/1a05d6a4-37a0-11e6-8159-c939801ea452.PNG)

**Comment by girishkg** [comment]
Hi,
I have observed this behavior and found an unusual  fix. Change the settings to be exactly as shown in below image. This should get you out of loop.

![tp_loop](https://cloud.githubusercontent.com/assets/4685602/16266980/1bc23bd0-38a5-11e6-80d8-86c16f3695ca.png)

**Comment by girishkg** [comment]
This file at line 22 has the code for "error.php"

**require_once 'sessions.php';
session_start();
if (!isset($_SESSION['CPM']) || $_SESSION['CPM'] != 1) {
    $_SESSION['error']['code'] = "1004"; //Hacking attempt
    include $_SESSION['settings']['cpassman_dir'].'/error.php';
    exit();
}**

**Comment by girishkg** [comment]
Hi @reignofterr0r ,
My version is the latest one from here: https://github.com/nilsteampassnet/TeamPass/releases
Try that.

**Comment by nilsteampassnet** [comment]
Corrected in last commit
