### ISSUE TITLE
Admin, password change and logoff not working

### ISSUE THREAD

**Issue by Hyrules** [nilsteampassnet/TeamPass#1345]
### Teampass version:
2.1.26.8

### Wamp Version:
wampserver3_x64_apache2.4.17_mysql5.7.9_php5.6.16_php7.0.0

### Operating system (Linux / Windows):
Windows server 2012 R2

### Apache version:
2.4.17

### MySQL version:
5.7.9

### PHP version:
5.6.16

### Browser and version
Chrome 51.0.2704.103 and IE 11.0.96000.18314

### Expected behavior
Create an admin user and allow password change as well as logoff

### Actual behavior
Does not create admin user at setup and does not allow first password change and well as logoff.

### Steps to reproduce
Install TeamPass.
Try to login with admin. ( no admin user is created in the user table and admin does not work)
if for any reason I was able to login the logoff and password change does not work.

Installation goes well. There is no error in the console of Chrome. 

Here is the error log : 

[22-Jun-2016 11:49:22 UTC] PHP Notice:  Undefined index: settings in D:\wamp64\www\teampass\sources\main.queries.php on line 22
[22-Jun-2016 11:49:22 UTC] PHP Stack trace:
[2-Jun-2016 11:49:22 UTC] PHP   1. {main}() D:\wamp64\www\teampass\sources\main.queries.php:0
[22-Jun-2016 11:49:22 UTC] PHP Warning:  include(/error.php): failed to open stream: No such file or directory in D:\wamp64\www\teampass\sources\main.queries.php on line 22
[22-Jun-2016 11:49:22 UTC] PHP Stack trace:
[22-Jun-2016 11:49:22 UTC] PHP   1. {main}() D:\wamp64\www\teampass\sources\main.queries.php:0
[22-Jun-2016 11:49:22 UTC] PHP Warning:  include(): Failed opening '/error.php' for inclusion (include_path='.;C:\php\pear') in D:\wamp64\www\teampass\sources\main.queries.php on line 22
[22-Jun-2016 11:49:22 UTC] PHP Stack trace:
[22-Jun-2016 11:49:22 UTC] PHP   1. {main}() D:\wamp64\www\teampass\sources\main.queries.php:0

I have tested it in Internet explorer and it seems to work as intended for the install  but the password change function and the logoff does not work.

When I login with a created user and try to change my password as soon as I enter my password for the first time there is an error on the console of IE when I change from the first password field to the second. On line 5094 of jquery : object does not manage the property or method "apply". Clicking on change on refreshes the page then logoff and other pages does not work,

**Comment by girishkg** [comment]
Logoff throwing an error. Have to hit logoff icon twice to get logged off.

TeamPass 2.1.26  2009 - 2016

![tp_logoff_error](https://cloud.githubusercontent.com/assets/4685602/16267811/52938cdc-38a9-11e6-8838-f861503cf222.png)

**Comment by girishkg** [comment]
This is the error in error.log
----------------------------------
[Wed Jun 22 18:52:46.541073 2016] [:error] [pid 26161] [client 192.168.120.8:44062] PHP Notice:  Undefined index: settings in /var/www/html/sources/main.queries.php on line 22, referer: https://192.168.126.47/index.php
[Wed Jun 22 18:52:46.541217 2016] [:error] [pid 26161] [client 192.168.120.8:44062] PHP Warning:  include(/error.php): failed to open stream: No such file or directory in /var/www/html/sources/main.queries.php on line 22, referer: https://192.168.126.47/index.php
[Wed Jun 22 18:52:46.541253 2016] [:error] [pid 26161] [client 192.168.120.8:44062] PHP Warning:  include(): Failed opening '/error.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/sources/main.queries.php on line 22, referer: https://192.168.126.47/index.php

**Comment by Hyrules** [comment]
Similar but the logout for me does not work at all it just reload the actual page which is the page the changes the user password at first login.

**Comment by girishkg** [comment]
Hi @Hyrules ,
Please check this thread may fix four issue temporarily.
https://github.com/nilsteampassnet/TeamPass/issues/1342

**Comment by girishkg** [comment]
This is the code in file (main.queries.php) at 22

**require_once 'sessions.php';
session_start();
if (!isset($_SESSION['CPM']) || $_SESSION['CPM'] != 1) {
    $_SESSION['error']['code'] = "1004"; //Hacking attempt
    include $_SESSION['settings']['cpassman_dir'].'/var/www/html/error.php';
    exit();
}**

**Comment by Hyrules** [comment]
Does not seems to work in my case. I still cannot change the user passwords. it loops around. Same goes for the logout function.

![image](https://cloud.githubusercontent.com/assets/3161577/16270545/af12ac94-3864-11e6-9fa4-9e9fb1156041.png)

**Comment by girishkg** [comment]
@Hyrules 
Set below two items to **"NO"** under "Settings --> Customize" tab and try.

  Enable passwords expiration   	
  Item consulted can be automatically deleted

**Comment by Hyrules** [comment]
Theses settings are already at NO :

![image](https://cloud.githubusercontent.com/assets/3161577/16271464/23ba0c88-3868-11e6-8d42-523029ed74d5.png)

Note that i'm not using IIS. I'm on wamp (apache) the thread you refer to points to IIS.

**Comment by girishkg** [comment]
Hi @Hyrules 
Sorry for messing it up. I have edited the comment. Please refresh the page and check it.

**Comment by Hyrules** [comment]
No joy. Still can't logout and change password.

![image](https://cloud.githubusercontent.com/assets/3161577/16272241/0d6ca60e-386b-11e6-8d7a-26e01065f12b.png)

**Comment by girishkg** [comment]
Hi @Hyrules ,
My version is the latest one from here: https://github.com/nilsteampassnet/TeamPass/releases
Try that.

**Comment by Hyrules** [comment]
Unless I was mistaken I was already on the latest release. I have tried you version and I still have the same problem. Thanks for you help.

**Comment by Hyrules** [comment]
It seems for some reason that when I log in with the admin everything goes well I can logout but I still get the error message. When logging out the following error message show in chrome console : 
Uncaught SyntaxError: Unexpected token H in JSON at position 0
parseJSON @ jquery.js:550
(anonymous function) @ index.php:348
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778

in VM4770 the content is this : Hacking attempt...

**Comment by nilsteampassnet** [comment]
Corrected in last commit in Development branch

**Comment by Hyrules** [comment]
Thank you @nilsteampassnet I can confirm that the dev version is working properly. Thanks alot.

**Comment by nilsteampassnet** [comment]
Great

**Comment by modalex** [comment]
Hi.
Please, can you tell me how did you fix the : Try to login with admin. ( no admin user is created in the user table and admin does not work) Issue ?

I have completed a new install and I can't login with admin/admin

Thank you very much
