### ISSUE TITLE
On upgrade settings.php not found

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1346]
Lately you changed the location of settings.php from includes/ to includes/config/. 
It tried to update to latest version and was given an error, that settings.php is not found. That was because the file itself was in the old location. After manual movement, it worked.

I suggest that in https://github.com/nilsteampassnet/TeamPass/blob/master/install/upgrade_run_2.1.26.php#L26 there should be another control before the error is given, to see, if the file exists in old location and to move it.

**Comment by ben-git-hub99** [comment]
I agree. I had to copy settings.php into includes/config/ to continue upgrade.

**Comment by reginfo** [comment]
I didn`t receive any error about setting.php

**Comment by reginfo** [comment]
Need some changes in http://teampass.net/2014-06-28-upgrade procedure about copy setting.php into appropriate folder

**Comment by ben-git-hub99** [comment]
Awesome. This works for me!
