### ISSUE TITLE
Bad code for connecting via OpenLDAP with search_base

### ISSUE THREAD

**Issue by jadjay** [nilsteampassnet/TeamPass#1352]
### Actual behavior : Setting StartTLS is useless there's nothing in sources/identify.php near lines 220-223 like "ldap_start_tls($ldapconn)". I had to put it myself to make it working...
Thus ldap_search_base is misconfigured in the code you called it sometimes ldap_search_base and somtimes settings_ldap_search_base and sometimes settings_ldap_search_base_tip
So search_base stay with 0 in the setting page... And put ldap_debug=1 in sources/identify.php doesn't give any log anywhere...

**Comment by jadjay** [comment]
See pull-request :  Add ldap_start_tls if set #1353

**Comment by nilsteampassnet** [comment]
Duplicate #1353
