### ISSUE TITLE
Json Error when sharing a folder with more than 1 role

### ISSUE THREAD

**Issue by juanfalguera** [nilsteampassnet/TeamPass#1354]
### Expected behavior

In my enviroment, we have 3 roles and each role has it's own group of folders and subfolders. Now we want to share some folders that belong to one role to another role.
### Actual behavior

When we change a folder permission to be visible to another role we get a JSON error.
### Steps to reproduce

In the roles managment, initially, each folder is accessed by a single role:

![image](https://cloud.githubusercontent.com/assets/16647133/16386734/1dc18334-3c68-11e6-83cc-3b91d871cd07.png)

This works fine, but when we give access to any folder to another role, like this:

![image](https://cloud.githubusercontent.com/assets/16647133/16386779/52edc036-3c68-11e6-97b2-4ad531a69d63.png)

When a user logs in, we get this error:

![image](https://cloud.githubusercontent.com/assets/16647133/16386797/677313d0-3c68-11e6-994f-f4567543ff48.png)

And the folders screen stays always "loading":

![image](https://cloud.githubusercontent.com/assets/16647133/16386818/7de9a002-3c68-11e6-98f8-e162d6a2391d.png)

**Comment by juanfalguera** [comment]
The error I got at console is:

jstree.min.js:2 Uncaught TypeError: this.settings.core.error.call is not a function

**Comment by nilsteampassnet** [comment]
Related to #1309 
Fix committed in Development branch.
