### ISSUE TITLE
Little parsing Bug in german.php

### ISSUE THREAD

**Issue by andreasrichardf** [nilsteampassnet/TeamPass#1355]
### Teampass version:

2.1.26(10)
### Operating system (Linux / Windows):

Linux 4.4.0-24-generic 43-Ubuntu
### Apache version:

Server version: Apache/2.2.15 (Unix)
### MariaDB version:

10.0.25-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
### PHP version:

PHP 7.0.4-7ubuntu2.1 (cli)
### Issus
```php
'can_manage_all_users' => 'Personalverwalter<br><i>Kann alle Benutzer unabhängig deren Gruppenzugehörigkeit verwalten.<br>Erhält zusätzlich die Rolle "Manager".<br> Ist nicht befugt einen Administrator-Account zu bearbeiten (Nur Administratoren können administrative Rechte entziehen).</i>',
```
The " makes a Style Bug in the user Managing Tab:
![erorr](https://cloud.githubusercontent.com/assets/20123093/16410794/6fb104a0-3d24-11e6-92cb-cfd027a22653.PNG)
### Fix
```php
'can_manage_all_users' => 'Personalverwalter<br><i>Kann alle Benutzer unabhängig deren Gruppenzugehörigkeit verwalten.<br>Erhält zusätzlich die Rolle <b>Manager</b>.<br> Ist nicht befugt einen Administrator-Account zu bearbeiten (Nur Administratoren können administrative Rechte entziehen).</i>',
```
![fix](https://cloud.githubusercontent.com/assets/20123093/16410832/9ce3183c-3d24-11e6-9f63-18a352448f10.PNG)

**Comment by nilsteampassnet** [comment]
Thanks
