### ISSUE TITLE
Active Directory authentication 

### ISSUE THREAD

**Issue by Aviad48** [nilsteampassnet/TeamPass#1357]
i am using  the latest version of teampass and i want to set Active Directory  authentication  and i have  issues with that.
i am setting up the settings in the Ldap Option and trying to connect by Active Directory and i get the   problem below:

[http://prntscr.com/bmw8nq](url)

Happy to get an answer fore that problem.

**Comment by w3yd61enliey** [comment]
Setting "Teampass local users only" is enabled? If yes, then you need to disable it, or create users in Teampass similar domain accounts (user logins must match).

**Comment by guannais** [comment]
Same configuration works in previous versions (2.26.8) but not in 2.26.10. 

When I activate debug mode I see this log:

Get all LDAP params :
mode : 1
type : 0
base_dn : dc=xx,dc=local
search_base : 0
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @xx.local
domain_controllers : xxdc01.xx.local
use_ssl : 0
use_tls : 0
*********
Get all ldap params :
base_dn : dc=xx,dc=local
account_suffix : @xx.local
domain_controllers : xxdc01.xx.local
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success
After authenticate : Success
ldap status :

The field ldap status is always empty.

**Comment by WojTecH94** [comment]
There are few strange things with LDAP authentication for example in one of the previous versions of TeamPass I was able to login with just login name, now (v. 2.1.26.10) I need to type like DOMAIN_NAME\login in most cases althought there is one account which is able to login with just login. So if I were you I would try to login with a DOMAIN\ before loginname
