### ISSUE TITLE
API restrictions?

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1358]
Is it correct that at the moment API doesn't have any restrictions - if you have the key, you can add, modify and read everything? 
Would it be possible to add a key field to each user and use these keys to access API? So after that there would be a possibility to use the common roles functionality and limit API user either to certain folders or actions (read-only, modify etc).

**Comment by sorinpaduraru** [comment]
Hey,

Yes, if you have the API key, you can add, delete or read items or create new users.
Check [this](http://teampass.net/2014-05-18-teampass-api) for more details.

You could however use the **Authentication credentials for a web page** section in the URL above to build access only to URLs like `https://localhost/api/index.php/auth` while denying access to `https://localhost/api/index.php/**read**` or ~/**write** or ~/**delete** etc...
This is something I tried doing but the way information is presented through ~/auth is not really that useful (at least for me) at this time.

**Comment by tehnotronic** [comment]
@nilsteampassnet would it be possible to limit folders per API key in future? 
I would like to allow some people to use API to read their items, but I don't want them to see everything. 

I think maybe easyest would be, if every user can have their corresponding API key and API queries the user rights by API key. So we can reuse existing rights management.
