### ISSUE TITLE
Duo prevents the ability to add/edit items

### ISSUE THREAD

**Issue by ben-git-hub99** [nilsteampassnet/TeamPass#1361]
### Teampass version:

2.1.26.10
### Operating system (Linux / Windows):

Linux
### Apache version:

Server version: Apache/2.2.15 (Unix)
### MariaDB version:

mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
### PHP version:

PHP 7.0.7 (cli) (built: May 26 2016 12:40:00) ( NTS )### Browser and version
### Actual Behavior:

When attempting to add an entry, all is well until a password is added. When clicking on the password tab, the JS starts refreshing the main frame with the folders and all ability to continue is lost.

I tried to follow this via firebug, but the page looks like it is in a constant refresh.
Dsabling duo corrects the issue.
### Expected Behavior

Would like to be able to use DUO as 2FA and edit items.

**Comment by nilsteampassnet** [comment]
Can you give more details?
I could not managed to get this reproduce?
With DUO and when creating a new item, I have no issue.

**Comment by nilsteampassnet** [comment]
OK I could reproduce but not on clicking "password" tab but on "Files"

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by ben-git-hub99** [comment]
Still having the issue when going to "password and visibility" in firefox and chrome. Tries to load frame again in endless loop. Also noticing the below issue as well (logs obfuscated):

[Tue Jul 05 09:58:36 2016] [error] [client 1.1.1.1] PHP Fatal error:  Uncaught logFileWriteError: OWASP CSRFProtector: Unable to write to the log file in /www/teampass.xxxx.com/htdocs/includes/libraries/csrfp/libs/csrf/csrfprotector.php:440\nStack trace:\n#0 /www/teampass.xxxx.com/htdocs/includes/libraries/csrfp/libs/csrf/csrfprotector.php(257): csrfProtector::logCSRFattack()\n#1 /www/teampass.xxxx.com/htdocs/includes/libraries/csrfp/libs/csrf/csrfprotector.php(188): csrfProtector::failedValidationAction()\n#2 /www/teampass.xxxx.com/htdocs/includes/libraries/csrfp/libs/csrf/csrfprotector.php(145): csrfProtector::authorizePost()\n#3 /www/teampass.xxxx.com/htdocs/index.php(31): csrfProtector::init()\n#4 {main}\n  thrown in /www/teampass.xxxx.com/htdocs/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 440, referer: https://teampass.xxxx.com/index.php?page=items&type=duo_check&[removed]=[removed]

**Comment by nilsteampassnet** [comment]
Is folder libraries/csrfp/logs with chmod 777?

**Comment by evilsi** [comment]
if it helps, this bug only happens if you use Duo 2FA. When you login you are taken to a page similar to: http://xxx.xxx.xxx.xxx/index.php?page=items&type=duo_check&016f0ca2e3909dcfd0......
Navigating to either add or edit an item results in an unhandled exception and the page reload loop. Instead after you login you click on the password button the page url changes to /index.php?page=items then by clicking on either add or edit item the loop doesn't occur. 

i suspect its something to do with csrfprotector.js
