### ISSUE TITLE
Unable to download image attachments teampass 2.1.26 (10)

### ISSUE THREAD

**Issue by dataegg** [nilsteampassnet/TeamPass#1363]
While testing this new release I'm not able to download image files (.png, .jpg) attached to entries, teampass  show the message 'Error: The file is missing!'

Other files types like .pptx or .txt are ok.

When uploading an images file (.png, .jpg) eveything seems to be ok, the file is available on the server but it can't be found when I try to download/open it.

**Comment by nilsteampassnet** [comment]
Could not reproduce with last changes done in Development branch.
I did some changes in "attachment" files.

**Comment by dataegg** [comment]
thanks for your prompt reply. I tested development branch but the issue remained so digged a little further.

I found out URL to upload dir (url_to_upload_folder) was not correct in the database. I updated the value and now everything is ok.

update teampass_misc set valeur='https://mysite.com/upload' where intitule='url_to_upload_folder';
