### ISSUE TITLE
Folder tree

### ISSUE THREAD

**Issue by adrianalvpa** [nilsteampassnet/TeamPass#1364]
Hello!

I have installed Teampass, and i have one question, is possible import an folder tree? If it is possible how can I do that? Wich is the file column format to import the folder tree?

Thanks in advanced!

**Comment by nilsteampassnet** [comment]
Please have a look to this page => http://teampass.net/2013-03-26-importing-items

**Comment by nilsteampassnet** [comment]
You cannot create folders with CSV.
Only with Keepass XML format.
