### ISSUE TITLE
upgrade from TeamPass 2.1.25 to TeamPass 2.1.26

### ISSUE THREAD

**Issue by panzo19** [nilsteampassnet/TeamPass#1365]
im trying to upgrade from TeamPass 2.1.25 to TeamPass 2.1.26 and proccess  stuck on - upgrade_run_2.1.26.php - Loop #1 is now running ...

**Comment by nilsteampassnet** [comment]
Sorry I cannot help such few information.
Try to follow the template ...

**Comment by panzo19** [comment]
Yes sorry, i think the following will help:

Teampass version:

2.1.25 -> 2.1.26(10)

Operating system (Linux / Windows):

Windows (XAMPP)

Apache version:

Apache/2.4.18

MariaDB version:

10.1.13-MariaDB 

PHP version:

PHP/7.0.6 

Browser and version

Firefox,chrome

Expected behavior

Next button getting active or errors being shown

Actual behavior

 stuck on - upgrade_run_2.1.26.php - Loop #1 is now running ...

**Comment by ben-git-hub99** [comment]
Did you check you web server error log? I bet it will provide something useful such as a PHP error or a permission denied error.

**Comment by nilsteampassnet** [comment]
We need the error sent back from server when launching  upgrade_run_2.1.26.php

See http://teampass.net/2014-02-09-how-to-communicate-an-error-log
