### ISSUE TITLE
Passwords blank after upgrade from 2.1.20 to 2.1.26

### ISSUE THREAD

**Issue by sourmonkey** [nilsteampassnet/TeamPass#1366]
Hi,

Existing passwords are blank after the upgrade, if I change a password on an item (after the upgrade) it is working correctly.
I have been trying to trace the issue, it seems the database has the password (pw) stored, but after the cryption() function, it returns blank.
I noticed the salt on this system (carried over from v2.1.20) is 25 characters long, where as on a new system of this version is 16 long.

teampass/sources/items.queries.php
1055:

`  
         } else {
//print "debug: 1:: " . $dataItem['pw'] . " 2:: " . $dataItem['pw_iv'];
                $pw = cryption(
                    $dataItem['pw'],
                    SALT,
                    $dataItem['pw_iv'],
                    "decrypt"
                );
//print "debug: pw:: " . $pw . "<<";
`

System details
Ubuntu server 16.04
php 7.0
apache 2.4.18

Thanks

**Comment by sourmonkey** [comment]
I'm going to try again, upgrade first to  2.1.23 then to 2.1.26

**Comment by sourmonkey** [comment]
Ok that worked, after some php 7 and mysqli fixes!

**Comment by The-Loeki** [comment]
HI @sourmonkey, would you care to elaborate a bit? We've just hit the exact same issue :(

**Comment by sourmonkey** [comment]
Hi @The-Loeki ,

Not sure what you mean.
So I have v2.1.20, I had to upgrade first to 2.1.23, this version apparently changes the encrypt, then to 2.1.26.
Hope that helps?

**Comment by The-Loeki** [comment]
Well we just upgraded from 2.1.23 to 2.1.26 and we have the exact same problem (and judging from other issues here we're not alone); you mentioned 'some php 7 and mysqli fixes' and I'm curious if those might have had anything to do with it.

**Comment by sourmonkey** [comment]
I don't think the PHP etc issue related, for me at least.
It was just that certain things didn't work properly.
There is mention in other issues of PHP fixes.
Look into using Firefox + firebug plugin, use the console tab to see if you are getting errors.
Perhaps open a new issue as your initial version is different.

**Comment by The-Loeki** [comment]
OK, well thanks anyway ;)
