### ISSUE TITLE
Cannot login after fresh install (TeamPass-2.1.26.10)

### ISSUE THREAD

**Issue by shoekstra** [nilsteampassnet/TeamPass#1367]
Hi,

After installing TeamPass 2.1.26.10 following the [Linux instructions](http://teampass.net/2013-12-31-installation-on-linux-server) I open a new tab and the page shows "You are not allowed to see this page".  

I'm using Apache 2.4, MariaDB, PHP 7.0.8 on Centos 7.  SELinux is set to Permissive.  I don't see anything in the logs indicating a problem.  I want to assume that because the setup was completed successfully, my system configuration should be OK.

How suggestions how to make TeamPass not show "You are not allowed to see this page"?

**Comment by nilsteampassnet** [comment]
Hello

Share a screen capture because I don't understand what you try to do here?
I need to know what account you are using, if you created folders, roles, items, ...
