### ISSUE TITLE
Finalisation fails in (TeamPass-2.1.26.10)

### ISSUE THREAD

**Issue by shoekstra** [nilsteampassnet/TeamPass#1368]
![image](https://cloud.githubusercontent.com/assets/3757382/16609919/e6185baa-4357-11e6-9543-af65d0140d93.png)

I'm not sure what is failing or what needs to be fixed, but I did the below as it seems sensible.

```
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
```

**Comment by ben-git-hub99** [comment]
It's not the best security practice, but I chmod recursively everything to 777 during the upgrade/install to allow all files/dirs to be written and then chmod to 644/755 afterwards.

**Comment by giannakopoulosj** [comment]
i encountered the same i just changed the directories to 755
