### ISSUE TITLE
Can't save Timezone settings

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1369]
![asdf](https://cloud.githubusercontent.com/assets/20316918/16613263/8902b24e-436b-11e6-89c8-91af9b593f17.jpg)
Hello, 

I want to edit 'Timezone selection', 'Date format', 'Time format' and 'Default Language'.

What I select for my requirements:

Timezone selection: Europe/Berlin
Date format: d/m/Y
Time format: H:i:s

Define the Default Language: german

After that the tool reset all changes after I reload the page. What can I do? I use the newest TeamPass Version: 2.1.26.10

Thank you :)

**Comment by monino** [comment]
Same problem here.

**Comment by f3035** [comment]
Hello!

Same problem.
TeamPass 2.1.26(10).

Nginx: 1.10.1
PHP: 5.5.37
MySQL: 5.6
FreeBSD 10.3

Thank you!

**Comment by nilsteampassnet** [comment]
Corrected in last commit in "Development" branch 
https://github.com/nilsteampassnet/TeamPass/commit/8fbd3317c4e740effb4f3c3c0c6735244a1898a8

**Comment by fferraro87** [comment]
I'm using 2.1.27 but i've still this problem, i cannot change default language.
Also i can't modify login language.
Can you help me?
