### ISSUE TITLE
2.1.26 upgrade: multiples bugs

### ISSUE THREAD

**Issue by ouafnico** [nilsteampassnet/TeamPass#1370]
Hi, 
trying to upgrade from 2.1.24 to 2.1.26.
Got a lot of bugs:
- the step where asking for database info fails, and say can't connect to database. The password is good. To pass out, I had to put the password on upgrade_ajax.php file in place of variables.
- the next step, directly failed on #1 with just "Mysql Error".

I think it should be great to echo the real mysql error to debug on code.

Thanks

**Comment by ben-git-hub99** [comment]
This sounds like the upgrade can't read $pass from /htdocs/includes/config/settings.php. 

While doing the upgrade, try chmoding 777 according to http://teampass.net/2013-12-31-installation-on-linux-server and then chmod files to 644 and dirs to 755.

Also check this for reference:
http://teampass.net/2014-06-28-upgrade

Lastly, check the http error logs for more information and feel free to post the obfuscated logs here

**Comment by ouafnico** [comment]
Hi

With chmod 777 (not very safe:p) I still got : 
09:54:22 - upgrade_run_db_original.php - Loop #1 

Nothing on apache error log.

**Comment by nilsteampassnet** [comment]
Please provide server's answers using Firebug.
See how to on http://teampass.net/2014-02-09-how-to-communicate-an-error-log
