### ISSUE TITLE
Can't install v 2.1.26.11

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1371]
Fresh installation of 2.1.26.11:
On the Server checks step I get stuck because of this:
![tp](https://cloud.githubusercontent.com/assets/19763370/16707757/52da8504-45da-11e6-8871-06a3661dcb5c.PNG)

**Comment by fodor99** [comment]
I have the same issue, both master and 2.1.26.11. I checked apache2 server error log, and I see the following: syntax error, unexpected 'case' (T_CASE) in install.queries.php on line 801, referrer install.php

**Comment by tb095** [comment]
Same here as well, brand new fresh install.

[error] [client <ip>] PHP Parse error:  syntax error, unexpected 'case' (T_CASE) in /var/www/html/teampass/install/install.queries.php on line 801, referer: https://<host>/tp/install/install.php

**Comment by fodor99** [comment]
o.k. after I add } to 800. line, next problem is : Call to undefined function mcrypt_get_iv_size() in session.php line 77, I may miss something from my installation...

**Comment by fodor99** [comment]
sudo php5enmod mcrypt, sudo service apache2 restart, so the second step of installation run

**Comment by fodor99** [comment]
on second step where looking form mysql_fetch, it is misleading, actual must install and enable GD! maybe a typo exists in the template

**Comment by fodor99** [comment]
and last todo is when it writes mysqli_fetch_all is missing (in the line of php 5.5 check), You should install and enable mysqlnd

**Comment by fodor99** [comment]
I cannot login, "prefix"_ users table is empty, not uploaded at least with administrator user :-(

**Comment by WojTecH94** [comment]
I also had problem with emty users table in v 2.1.26.10 I installed it again end the problem disappeard.

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by abhayghatpande** [comment]
The error persists in release candidate 12. Still necessary to add a `}` at line 800 in `/home/motsai/public_html/teampass/install/install.queries.php`

**Comment by nilsteampassnet** [comment]
Sorry my mistake, I did the release too fast yesterday during the Football Euro finale.
I forgot the merge of the change in master ...

Created a new Release package.
