### ISSUE TITLE
PHP max execution time 

### ISSUE THREAD

**Issue by abhayghatpande** [nilsteampassnet/TeamPass#1372]
Trying to install 2.1.26.12. During the server checks task, I receive the following error.

`Directory "/includes/avatars/" is writable  PHP "Maximum execution time" is set to 30 seconds. Please try to set to 60s at least during installation.`

How to resolve this?

**Comment by abhayghatpande** [comment]
So I managed to get around this by adding `ini_set('max_execution_time', 100)` to the file, `install/install.queries.php` just before the check for the execution time.

**Comment by craiglondon** [comment]
@abhayghatpande Thanks for posting this, I used your fix.   I'd propose that this just be part of the `install/install.queries.php` file instead of having to modify the production environment php.ini file.

**Comment by PPJunior2** [comment]
![image](https://user-images.githubusercontent.com/47351854/52337074-eadc7e80-2a06-11e9-8ace-9a9b798972df.png)
Where exactly ?

**Comment by nam-pd7** [comment]
echo '[{"error" : "PHP \"Maximum execution time\" is set to ' . ini_get('max_execution_time', 100) . ' seconds. Please try to set to 30s at least during installation.", "index" : "' . $post_index . '", "multiple" : "' . $post_multiple . '"}]';
