### ISSUE TITLE
Unable to login after installation

### ISSUE THREAD

**Issue by abhayghatpande** [nilsteampassnet/TeamPass#1373]
So I completed all the installation steps and on resuming, I'm not able to log in. What are the admin credentials? I tried `admin:admin` and `admin` with the password I set.

Also why does it say that maintenance mode is activated? How to get out of that?

![screenshot 2016-07-10 17 45 52](https://cloud.githubusercontent.com/assets/3515670/16716302/b9eca46a-46c6-11e6-809b-7fd22e939abd.png)

**Comment by abhayghatpande** [comment]
I reinstalled the application several times, with the same results -- unable to login after install. Firebug response:
```
[{"value" : "user_not_exists", "text":""}]
```
Location info:
```
http://<servername>/sources/identify.php?b78f42cd9c4566f55486d58aaa533220c1bb7f2ee3d6d5f3e6=35dc930345d0aefb8fbb3310102d96f7b41c57908687c2e067&data=aumCV4GBgYFXLHlTRrlRJXShPj%2B1AX2yQmWPwWAms%2FvaVqOfCKpoZoWiEY%2F05IPdK7iZDoAKxsQhH6PHkpsRP5uH1kDc2%2BJfHN0V2jTod8iHFyTO2nEw46lwKrAj0hVjye%2B3UnbWvZQ937gWYobMYSPEbTr2Noe3fvonx4Qhn5xwKxUvwFss4ySPEOld%2B6E%3D&type=identify_user
```

**Comment by nilsteampassnet** [comment]
Sorry my mistake, I did the release too fast yesterday during the Football Euro finale.
I forgot the merge of the change in master ...

Created a new Release package.
