### ISSUE TITLE
One time view link incomplete if there is character "<" in the password

### ISSUE THREAD

**Issue by Franckboby** [nilsteampassnet/TeamPass#1375]
If you share a key with the ovt function,
With for example this password "rDad<dzSDs", if you share it you will see only that : 

Password : rDad

**Comment by nilsteampassnet** [comment]
It will take time ... I don't understand why after 1h debugging :(

**Comment by Franckboby** [comment]
Great,

If I can suggest something, may be you can exlude this character from the Pass Gen ?

**Comment by marksteward** [comment]
https://github.com/nilsteampassnet/TeamPass/blob/master/otv.php#L123 has no call to htmlspecialchars. I hope you don't mind, but I strongly suggest you get someone to do a proper security review of this app, or maybe sign up for HackerOne. I've found a large number of issues from a quick scan of the codebase and a junior pentester would love this sort of thing as a project.

**Comment by nilsteampassnet** [comment]
This app has been regularly audited against security and all of them have permit to increase its security to a high level. Automatic tools get a large number of false positive results that need to be analyzed point by point.
Here this suggestion could permit to get rid of error but needs to be tested to be sure. It has nothing to do with security (for my point of view) as it is a "display" function, and not a "store" one. So in the line indicated, there is no impact on data security.
But nevertheless, I didn't knew this site and will have a look on it. Thanks for your suggestion.
