### ISSUE TITLE
Teampass 2.1.26 - AD authentication - non AD user connection impossible

### ISSUE THREAD

**Issue by florck** [nilsteampassnet/TeamPass#1376]
Hi,
I would like to report the following bug in TeamPass 2.1.26.
- Our Teampass is plugged on an AD.
- admin connexion is working well.
- AD connexion of user registered in teampass is working well.

However, if I want to create a non AD user (let name it "emergency") whatever how I proceed to set him a password I can't connect with it.
What I tried:
- forgot you password link
- admin set the password

Should you need precise elements, please let me know.
Thank you a lot for your great job.

**Comment by nilsteampassnet** [comment]
I don't think it is a bug.
AsTeampass is set to be used with AD, the password verification is done through AD.

NOt sure to understand, what do you expect in fact? A mix of AD and non AD users, that's it?

It is quite complexe feature to implement but feasible in the future

**Comment by florck** [comment]
Hi Nils,  
Thank you for, feedback. This is what I meant. 

I thought this was working in previous versions the mix between AD and non AD.
 
What I need is one non AD account that could read only everything in case of AD failure. 

What do you think could be a work around ? 

Thank you

On 13 juillet 2016 22:10:03 GMT+02:00, "Nils Laumaillé" <notifications@github.com> wrote:
>I don't think it is a bug.
>AsTeampass is set to be used with AD, the password verification is done
>through AD.
>
>NOt sure to understand, what do you expect in fact? A mix of AD and non
>AD users, that's it?
>
>It is quite complexe feature to implement but feasible in the future
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nilsteampassnet/TeamPass/issues/1376#issuecomment-232471810

-- 
Envoyé de mon téléphone avec Kaiten Mail. Excusez la brièveté.
