### ISSUE TITLE
Cannot download oneshot backup

### ISSUE THREAD

**Issue by cgkelleher** [nilsteampassnet/TeamPass#1377]
Hi, 

I am unable to download the backup created via "one shot backup and restore"

The backup runs and the .sql file created in ../htdocs/teampass/files but when click to download receive the error:
Access forbidden!
        You don't have permission to access the requested object. It is either read-protected or not readable by the server.
        If you think this is a server error, please contact the webmaster
Error 403

I have set the chmod 777 -R teampass

but i am still unable to download the file.

**Comment by nilsteampassnet** [comment]
Yes `/teampass/sources/downloadFile.php`s protected by .htaccess file.
Indeed it is a sensitive file that needs to be adapted with your network environment.

Replace the `Deny from all` by something else. For example, the IP of the Administrator.
