### ISSUE TITLE
2.1.26 when changing user password: "requested JSON parse failed"

### ISSUE THREAD

**Issue by xmurphy** [nilsteampassnet/TeamPass#1378]
as title: when user try to change his account's password this is the error: requested JSON parse failed

**Comment by nilsteampassnet** [comment]
not in 2.1.26.13 I beleive

**Comment by xmurphy** [comment]
i think it is the last version please try on your

**Comment by Tokalanz** [comment]
I have the same issue, when a user tries to use 'change my password' in their profile they get requested JSON parse failed.

The logs for the user show:

Query: SELECT complexity FROM teampass_roles_title WHERE id IN (Array) ORDER BY complexity DESC<br />Error: Unknown column 'Array' in 'where clause'<br />@

I'm used 2.1.26 up to fix 1346

Thanks

**Comment by evilsi** [comment]
This error also occurs in the latest version except with a variant SQL error in the logs. 
You can replicate the issue by creating a new user account and then immediately creating another new user account.  If you reload the user list between creating accounts the error doesn't happen.  It appears the action page processing the SQL is missing something to complete the creation of a new user once the submit is complete.

**Comment by tchraibi** [comment]
Hello, 

With the last version, we have the same error when a user try to change it's account password

Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ';2;3;4;5) ORDER BY complexity DESC' at line 3
Query: SELECT complexity FROM teamp455_roles_title WHERE id IN (1;2;3;4;5) ORDER BY complexity DESC

**Comment by nilsteampassnet** [comment]
Could reproduced. It appears only when user has several roles.

**Comment by tchraibi** [comment]
How can i solve it? there is any update to fix it?

Regards
