### ISSUE TITLE
 Teampass 2.1.26 - CSV or KeePass Import - Title as "0"

### ISSUE THREAD

**Issue by florck** [nilsteampassnet/TeamPass#1380]
When importing from csv or keepass xml, there is a bug that sets 0 to every lines as the title instead of what was in the original file.
Thank you for help.

**Comment by florck** [comment]
Hi ! I found where it comes from... 
The file sources/import.queries.php around line 850 does (and above for csv import) :
```
substr(stripslashes($item[KP_TITLE]), 500)
```
From the way substr works in php, I think it means "start after the 500th letter" whereas I think you would like to say "stop before the 500th letter" which I think (even if I'm not a PHP master) would be written like:
```
substr(stripslashes($item[KP_TITLE]), 0,500)
```
What do you think?

**Comment by nilsteampassnet** [comment]
How ridiculous I feel

I don't know if it solve the bug you have but at least it is an enormous bug!

Thanks

**Comment by florck** [comment]
Hi Nils,
I confirm that it corrects the bug !

I think that the substr could be misused at few other place, maybe if you get time to make a search all and have a global check you would find some!

Regards

**Comment by cgkelleher** [comment]
I had the same issue - this fix did not resolve it for me but using an older version of import.queries.php fixed it for me

**Comment by florck** [comment]
@cgkelleher
I had to modify the function at several places in import.queries.php
