### ISSUE TITLE
Export to PDF - Incorrect formatting

### ISSUE THREAD

**Issue by jahantech** [nilsteampassnet/TeamPass#1383]
Hi, 
(Version 2.1.26)
Not sure if this issue is fixed already. But when you try to export very large entries ("long strings") as user names , the pdf file loses its formatting. You can still see all the records but "long string" gets overwritten.

Thanks, 
Jahan Syed

**Comment by nilsteampassnet** [comment]
Hi
Yes it is something I know.
It is one of the long list of "lower priority" bugs I need to correct.

Thanks for reporting.

**Comment by jahantech** [comment]
Hi, 
This was an easy fix. Please see my pull request for the required change. 

You just need to add row calculation for login too in sources/export.queries.php around line 191:
`                 $nb = max($nb, nbLines($table_col_width[0], $record['label']));
-                $nb = max($nb, nbLines($table_col_width[3], $record['description']));
+                $nb = max($nb, nbLines($table_col_width[1], $record['login']));
+		$nb = max($nb, nbLines($table_col_width[3], $record['description']));`

**Comment by nilsteampassnet** [comment]
Thanks
