### ISSUE TITLE
SyntaxError: Invalid Character

### ISSUE THREAD

**Issue by cgkelleher** [nilsteampassnet/TeamPass#1384]
Hi

I am receiving this error message when clicking on a password entry. Has anyone had the same issue?

SyntaxError: Invalid Character

![syntaxerror](https://cloud.githubusercontent.com/assets/20399542/16915637/917c48ac-4cf0-11e6-9e96-528bb7b22344.JPG)

**Comment by cgkelleher** [comment]
Update on this - its only seems to present this error if I have "Enable log to SYSLOG" enabled - 

Also when changing the server from localhost to my syslog server the entry does not save and reverts back to localhost?

**Comment by nilsteampassnet** [comment]
> -Update on this - its only seems to present this error if I have "Enable log to SYSLOG" enabled -

Confirmed ...
