### ISSUE TITLE
403 Access Forbidden by CSRFProtector! LDAP feature

### ISSUE THREAD

**Issue by duss69** [nilsteampassnet/TeamPass#1385]
Hi , 

This is my issue When I try to configure LDAP Option. 

![2016_07_18_15_50_44_error teampass](https://cloud.githubusercontent.com/assets/19535785/16916937/b9aa2236-4cff-11e6-9df5-2bbf9a967bde.png)

before : 

![2016-07-18 15_54_01-teampass_ldapoption](https://cloud.githubusercontent.com/assets/19535785/16916999/f74b3a12-4cff-11e6-87ae-45622c81b29c.png)

My config : 
Teampass 1.26
Centos 7.2.1511  kernel 3.10

I change my /var/www/html/toto/includes/libraries/csrfp/libs/csrfp.config.php

<?php
/**
- Configuration file for CSRF Protector z
  */

return array(
   "CSRFP_TOKEN" => "Key",
   "logDirectory" => "../log",
   "failedAuthAction" => array(
      "GET" => 0,
      "POST" => 0),
   "errorRedirectionPage" => "",
   "customErrorMessage" => "",
   "jsPath" => "../js/csrfprotector.js",
   "jsUrl" =>  # $_SESSION['settings']['cpassman_url']."/includes/libraries/csrfp/js/csrfprotector.js",
   "tokenLength" => 50,
   "disabledJavascriptMessage" => "This site attempts to protect users against <a href=\"https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29\">
   Cross-Site Request Forgeries </a> attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work corre
ctly for you.
    See details of your web browser for how to enable JavaScript.",
    "verifyGetFor" => array()
);

If anyome have a solve ...

Think

**Comment by nilsteampassnet** [comment]
Do you use the last package (#13)?

If not, please use it

**Comment by duss69** [comment]
thinks for your help. 

Ldap work (test environnement) 

but When I  upgrade new version on product environnement 

I have this issue with upgrade 

![2016-07-21 17_00_52-teampass installation](https://cloud.githubusercontent.com/assets/19535785/17027734/5c2412c6-4f65-11e6-876c-12a275f37bf9.png)
![2016-07-21 17_03_01-multi putty manager](https://cloud.githubusercontent.com/assets/19535785/17027738/622cd1c6-4f65-11e6-82a6-773e19f07741.png)
![2016_07_21_17_03_59_multi_putty_manager](https://cloud.githubusercontent.com/assets/19535785/17027752/6d991cc2-4f65-11e6-905f-9c4f69ebbfed.png)

why I have an error , and I don't know if is it an error of right 

thank for you reply

**Comment by nilsteampassnet** [comment]
Copy settings.php to folder config.

**Comment by duss69** [comment]
think 

All is ok Teampass is working in prod ;)
