### ISSUE TITLE
JSON parse failed (history item view)

### ISSUE THREAD

**Issue by adrianalvpa** [nilsteampassnet/TeamPass#1386]
Hi

We are receiving this error when clicking on the history item. Tested in two different environments. I explain them in the attached file.

Thank you for help
[Teampass_github.docx](https://github.com/nilsteampassnet/TeamPass/files/369456/Teampass_github.docx)

**Comment by nilsteampassnet** [comment]
I don't have this issue using the Development branch.

I will create  a new package this evening ... hopefully the last one.

**Comment by adrianalvpa** [comment]
Perfect! 

We have tested it and it runs perfectly after the upgrade!

Thx!

**Comment by nilsteampassnet** [comment]
Thanks for feedback
