### ISSUE TITLE
Mixed content being sent over content over HTTPS

### ISSUE THREAD

**Issue by abhayghatpande** [nilsteampassnet/TeamPass#1387]
Ver 2.1.26 on Ubuntu 14.04, with Lighttpd webserver. Valid SSL certificate installed, `Enforce strict HTTPS` selected in settings. Still get the following error in console:

```
Mixed Content: The page at 'https://<domain>/index.php?page=items' was loaded over HTTPS, but requested an insecure image 'http://<domain>/includes/images/photo.jpg'. This content should also be served over HTTPS.
Mixed Content: The page at 'https://<domain>/index.php?page=items' was loaded over HTTPS, but requested an insecure script 'http://<domain>/includes/libraries/csrfp/js/csrfprotector.js'. This request has been blocked; the content must be served over HTTPS.
```

In `lighttpd.conf` file, all port `:80` requests are redirected to https:

```
$SERVER["socket"] == ":80" {
    url.redirect = (
        "^/(.*)" => "https://<domain>/$1"
    )
}
```

How to resolve this? Thanks.

**Comment by nilsteampassnet** [comment]
It seems you get this error because the script is launched through http:// and not http**s**://

In settings page, are you sure to have set https://
![image](https://cloud.githubusercontent.com/assets/1197546/16965053/a17a9fa6-4dfe-11e6-9e91-49c2cda4ed16.png)

Ensure also that you have https:// for variable jsUrl in includes/libraries/csrfp/libs/csrfp.config.php

**Comment by abhayghatpande** [comment]
Ah ha! Thank you! That fixed it. I changed all the URLs in the settings to https://. (Like the Upload folder and Files folder, etc.) Hope that is all right.

Now the only message is `csrfprotector.js:248`
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

**Comment by evilsi** [comment]
_Now the only message is csrfprotector.js:248_

We have just had the same issue when forcing HTTPS, when the index.php page loads there is a hard coded reference to the local IP (our original config form install) and http. Its hidden here: includes/libraries/csrfp/libs/csrfp.config.php 

This also was a fail point when we blocked pot 80 traffic and  a URL re-write didn't resolve it.
