### ISSUE TITLE
Requested JSON parse failed when copying item

### ISSUE THREAD

**Issue by oackerma** [nilsteampassnet/TeamPass#1389]
Hi,
we get a "Requested JSON parse failed" when copying any password item.
TeamPass Version: 2.1.26, reproducible: always

**Comment by gfvirga** [comment]
I am getting the same error

**Comment by nilsteampassnet** [comment]
To solve this via SQL query
ALTER TABLE `_teampassitems` CHANGE `pw` `pw` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `_teampassitems` CHANGE `pw_iv` `pw_iv` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `_teampassitems` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

**Comment by gfvirga** [comment]
Worked perfectly, thank you so much. Although my table was named 'teampass_items"

**Comment by oackerma** [comment]
That does not work for me. Maybe I'm missing something.
I issue the three queries for the table "teampass_items" within the teampass database and restart the mysql service afterwards.
Are there any additional SQL statements necessary that are not obvious to a SQL rookie?

**Comment by sfrlaurent** [comment]
I also get the same trouble even with the 2.1.26-3 version and the SQL commands did'nt change anything.
Normal because the table already have the right values.
Does someone have a solution?
Do I need to open a new issue?
