### ISSUE TITLE
2.1.26 Testing mail is not clear where to put a recipient address

### ISSUE THREAD

**Issue by luberti** [nilsteampassnet/TeamPass#1390]
In Settings->Email the  "Test the Email configuration" fails with 
"You must provide at least one recipient email address."

error message.

But I cannot find where to put the test recipient address

**Comment by reginfo** [comment]
> But I cannot find where to put the test recipient address
Set email for admin in profile.

**Comment by luberti** [comment]
Thanks it worked but I had to logout, otherwise the address was in the profile but was not seen by the test mail funcionality.
