### ISSUE TITLE
Personal folder script : where is it located?

### ISSUE THREAD

**Issue by luberti** [nilsteampassnet/TeamPass#1391]
In Settings->TeamPass Settings I have activated the option "Enable Personal folder feature".
But It is not working.
I have noticed that beside the above option there is a hint with the following message:

"Once activated, you need to manually run a script that will create the personal folders for the existing users. Notice that this will only create personal folders for Users that do not have such a folder. The script "

Looking at the html source I see:

<i class="fa fa-question-circle tip" title="Once activated, you need to manually run a script that will create the personal folders for the existing users. Notice that this will only create personal folders for Users that do not have such a folder. The script '".$txt['admin_action_check_pf']."' is available in tab '".$txt['admin_actions_title']."'"

Only this way I was able to find where the script is

**Comment by nilsteampassnet** [comment]
Run the script located at this place

![image](https://cloud.githubusercontent.com/assets/1197546/17001088/d21d8bce-4ec5-11e6-9bb8-b46979d711dd.png)

**Comment by luberti** [comment]
Thanks, I was able to run the script I was only pointing out that in order to find it I had to look at the HTML source and interpret the placeholders I found there: Something is broken in the script that generates the TeamPass settings tab
