### ISSUE TITLE
FEATURE - Search include url

### ISSUE THREAD

**Issue by otrochavon** [nilsteampassnet/TeamPass#1393]
Hi Nils, 

I finish import keepass database and  see I don't  found some items because Teampass do not search in URL and email fields.
I think maybe you can CONCAT some fields only for search and also avoid the lot of.. "WHERE like "%%"

Seeng code, perjaps adding this fields in TAG field in cache table?

Thanks a lot again.
Javier.

**Comment by nilsteampassnet** [comment]
When you are in the "find page", URL is used to perform the search.

What search field you are talking about?

**Comment by otrochavon** [comment]
Hi, when I install teampass, it do not search using URL... 
I will try again whith last release.
thanks!!
