### ISSUE TITLE
Erorr when password copy to Clipboard.

### ISSUE THREAD

**Issue by djooberlee** [nilsteampassnet/TeamPass#1394]
ASCII Codes are copied to the clipboard instead of actual password symbols.
E.g. if I have password "iF\fz", then "iF&#92;fz" is copied to the clipboard.
\ symbol is replaced with it's ASCII Code #92;

TeamPass 2.1.26  2009 - 2016

**Comment by zuernBernhard** [comment]
Only see the problem when the password contains spaces. Can you confirm that ?
