### ISSUE TITLE
Slow performance when there is some password in a folder

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1396]
Hi,

Since we use Teampass, there is a lack of performance... We have about 300 passwords in a folder and it take almost 5min to list all these passwords...

![perf-1](https://cloud.githubusercontent.com/assets/14218330/17060723/a55a9bb0-502b-11e6-8657-833486ee9931.PNG)

When we take a look to a mysql "show processlist;" (because it's a mysql problem I think), we see always a slow select with a sorting result, example : 

`SELECT i.id AS id, MIN(i.restricted_to) AS restricted_to, MIN(i.perso) AS perso,[...]`

Is it possible to optimize Mysql request plz ? because we came from Keepass, and the reactivity is really not the same, it's too bad.

Thanks!

**Comment by nilsteampassnet** [comment]
This query is the main one to retreive the passwords, it will be difficult to optimize it or it would request a change in the structure of the DB. 
It is something that could be done in a major version.
In the meantime, I will check how to set better indexes on the tables, this could help.

But a short term solution would also be to organize in a more detailled way your folders so that you reduce the number of passwords inside each of them.

It is difficult to compare the performance of Teampass and Keepass, as (if we talk of queries) Keepass only performs a "SELECT" on an Items table, where Teampass does the same + evaluate all associated users rights and items permissions including all items logs ... it is really not the same ;)

**Comment by Hellnino18** [comment]
Thx for your answer! I understand that we need to organize our passwords in a better way, but for 300 passwords, I find that this is really really slow (even if Teampass needs to evaluate all associated users rights and items permissions). I use Centreon for 3000 hosts and 30000 services, with ACL, and the speed is really not the same :)

Let me know if you find a quick fix with index.

Thx!

**Comment by chc88** [comment]
Could you please let us know the full query which is responsible for the low performance?
Some of us also know a bit about db's, so maybe the community can help you here.

**Comment by Doccrazy** [comment]
I was having the same problem, and I was able to improve performance by adding the following index:
```sql
CREATE INDEX teampass_log_items_id_item_IDX ON teampass.teampass_log_items (id_item,date);
```
You can see the full query by running `show full processlist;`.

**Comment by Hellnino18** [comment]
Hi @Doccrazy ,

Thanks for your feedback, the full slow request is this one : 

`SELECT i.id AS id, MIN(i.restricted_to) AS restricted_to, MIN(i.perso) AS perso,
                   MIN(i.label) AS label, MIN(i.description) AS description, MIN(i.pw) AS pw, MIN(i.login) AS login,
                   MIN(i.pw_iv) AS pw_iv,
                   MIN(i.anyone_can_modify) AS anyone_can_modify, l.date AS date,
                   MIN(n.renewal_period) AS renewal_period,
                   MIN(l.action) AS log_action, l.id_user AS log_user
                   FROM teampass_items AS i
                   INNER JOIN teampass_nested_tree AS n ON (i.id_tree = n.id)
                   INNER JOIN teampass_log_items AS l ON (i.id = l.id_item)
                   WHERE (i.id_tree=2351) AND (i.inactif=0) AND (l.date=(SELECT date FROM teampass_log_items WHERE action IN ('at_creation', 'at_modification') AND id_item=i.id ORDER BY date DESC LIMIT 1))
                   GROUP BY i.id, l.date, l.id_user, l.action
                   ORDER BY i.label ASC, l.date DESC LIMIT 0,22`

I guess this one was yours too ?

The performance is really better with this INDEX ? I will try your index.

Thx!

**Comment by chc88** [comment]
If I see the query from @Hellnino18 then I would expect that the INDEX from @Doccrazy should indeed exist. As there is a Join to the log_items table with filter on both those fields. 

Let us know your experience after adding the index.

**Comment by jahantech** [comment]
I was facing exactly the same issue and I can confirm that creating the index actually improved the performance alot. 

For me each fetch was a mysql slow query with 2+ seconds execution time. After adding the index, its pretty much instant.

**Comment by nilsteampassnet** [comment]
Yes I confirm this index is really good.

Thank you, I will add it
