### ISSUE TITLE
SMTP Username containing backslash, cause error

### ISSUE THREAD

**Issue by infectormp** [nilsteampassnet/TeamPass#1397]
Just run TeamPass 2.1.26 @ php 7.0.8 and got warning in logs 

> PHP Notice:  Undefined variable: link in /xxx/includes/libraries/Database/Meekrodb/db.class.php on line 618
> PHP message: PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /xxx/includes/libraries/Database/Meekrodb/db.class.php on line 618" while reading response header from upstream, referrer: "https://xxx/index.php?page=manage_settings"

**Comment by nilsteampassnet** [comment]
I do use 7.0.4 and on last development branch, don't have those errors.
Can you indicate what you were performing?
Can you upgrade using last commit on Development branch?
In the php message, can you scroll down, you will have the sql error, and paste it here?

**Comment by infectormp** [comment]
problem occur when "Authentification Username" contain "/", as example xxx\yyy, and when i switch "SMTP server needs authentification" to "On".

additionally i get this error on screen
> SyntaxError: Unexpected token _ in JSON at position 0

**Comment by infectormp** [comment]
maybe of top:

at install stage i set "Authentification Username" to `xxx\yyy` and "SMTP server needs authentification" to "On" but after installation finished in settings a get username `xxxyyy` and SMTP auth toggle off

**Comment by infectormp** [comment]
tested with last dev branch

**Comment by nilsteampassnet** [comment]
I think I will remove the smtp setup from the install.

Email setup should only be done through the admin settings page.

Thanks for reporting this issue.
