### ISSUE TITLE
Click and maintain to show password

### ISSUE THREAD

**Issue by cgkelleher** [nilsteampassnet/TeamPass#1398]
Sorry if this has already been logged (I'm sure ive seen it before but cant seem to find it)

When I click to view the password it just flashes and does not stay visible even whilst holding the mouse button. 

Does anyone have a fix for this?

Many thanks

**Comment by nilsteampassnet** [comment]
What version? what browser?

**Comment by cgkelleher** [comment]
latest version, IE11

seems to work ok in chrome, not checked in firefox

**Comment by TheKingKai** [comment]
same problem with IE11

I checked it in FireFox and it works

**Comment by nilsteampassnet** [comment]
Works nicely with Edge.

I think that the library used by Teampass is perhaps not compatible with "older" browser.

**Comment by mpohlbmu** [comment]
Same Problem with Chrome v. 55.0.2883.87 m (64-bit)

**Comment by sfoglema** [comment]
I have this same problem.
In IE11 (Which we are being forced to use), clicking and holding the eye icon displays and then hides the password immediately.  It also does not work for us in Edge.
Running Windows 10, latest patches.
Firefox and Chrome don't have an issue, but we are being required to use IE 11 in our corporate environment.
TeamPass 2.1.26, IE 11.420.10586.0
