### ISSUE TITLE
Error step 4 upgrade

### ISSUE THREAD

**Issue by QUEMSX** [nilsteampassnet/TeamPass#1399]
Bonjour Nils, 

Merci encore pour ce travail, nous utilisons votre solution tous les jours et en sommes ravis ! 

Malheureusement, j'ai une erreur lors de la mise à jour de Teampass depuis la version 2.1.23 à 2.1.25. 
Lors de l'encryptage des mots de passe, l'avancement reste à 0% et rien ne se passe. 

![2016-07-25 16_46_26-teampass installation - opera](https://cloud.githubusercontent.com/assets/20644304/17105602/3d701890-5288-11e6-9916-36fabde8962d.png)

J'ai essayé de débugger un peu et apparemment il manquerait une colonne dans un tableau... 

![2016-07-25 16_46_42-photos](https://cloud.githubusercontent.com/assets/20644304/17105414/6f3fab02-5287-11e6-9b2a-f56c3750c1dd.png)

Avez vous une solution à ce problème ? 

Merci d'avance. 

Cordialement, 
QUEMSX

**Comment by nilsteampassnet** [comment]
Bonjour,

Pourquoi ne pas migrer vers 2.1.26 directement?

Y'a-t-il moyen que je me connecte à votre serveur par TeamViewer ou AMMYY ? Vous pouvez voir ce que je fais ... car le debuggage pour une migration depuis la 2.1.23 est un peu "chaude".
