### ISSUE TITLE
CSV import doesn't work

### ISSUE THREAD

**Issue by ben-git-hub99** [nilsteampassnet/TeamPass#1400]
### Steps to reproduce
1. Login
2. Import Items
3. Select CSV
### Expected behaviour

Be able to upload and import a CSV
### Actual behaviour
- The tokens table wasn't created. So, I created it. May want to include CREATE TABLE IF NOT EXIST for tokens in upgrade.
- The upload never completes. Lines are read as "undefined" and do not allow selection for import.
- If uploading a file that already exists in ./files/, it will read the file in that directory (e.g. test.csv).
### Server configuration

**Operating system**:
Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Web server:**
Server version: Apache/2.2.15 (Unix)
**Database:**
mysql Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
**PHP version:**
PHP 7.0.8 (cli) (built: Jun 23 2016 11:34:22) ( NTS )
**Teampass version:** 
latest stable (Release 2.1.26 (14))
**Updated from an older Teampass or fresh install:**
Updated from 2.1.25 (10)
### Client configuration

**Browser:**
Chrome/Firefox
**Operating system:**
MacOSX
#### Web server error log

No error logs.
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
[{"token" : "quuoKeek4ohneime7dee4reex"}]
https://teampass.xxxxx.com/sources/main.queries.php?17cc01ecc9591d9beb59880e72045bc83faa38da4b13caacbe=729d4c84a258880962530456a66ca7cb2284a80ea2f33ac9bb&ambiguous=true&capital=true&duration=10&numeric=true&reason=import_items_from_csv&size=25&type=save_token
——

{"jsonrpc" : "2.0",
                "error" : {"code": 102, "message": "Failed to open output stream."},
                "id" : "id"}
https://teampass.xxxx.com/sources/upload/upload.files.php?

——
[{"error":"cannot_open"}]

https://teampass.xxxx.com/sources/import.queries.php?17cc01ecc9591d9beb59880e72045bc83faa38da4b13caacbe=729d4c84a258880962530456a66ca7cb2284a80ea2f33ac9bb&file=btest.csv&folder_id=132&type=import_file_format_csv
```

**Comment by nilsteampassnet** [comment]
Correct concerning the old csv file that is not deleted after importation. I've corrected this.

Now can you tell me if once the Tokens table is created if you could do the import?

Once you have uploaded 2.1.26.14 package, did you run upgrade.php. Indeed it is during the upgrade that this table is created.

**Comment by ben-git-hub99** [comment]
I ran upgrade.php, but had to create the table manually. CSV is not working.

I found a work around of uploading a CSV into /files and then using the TP ui, import a file with the same name. It's not ideal though.

**Comment by nilsteampassnet** [comment]
I can't reproduce.

Connection to your server is possible?
