### ISSUE TITLE
Cannot log in to TeamPass

### ISSUE THREAD

**Issue by Marcvander** [nilsteampassnet/TeamPass#1402]
### Steps to reproduce
1. Go on our TeamPass log in page
2. Try to log in
### Expected behaviour

It should log in to TeamPass
### Actual behaviour

Instead it loads, looks like the log in worked, but 1 sec after goes back to log in page, while the user is still not logged in. It only does that for a few people, for instance it works all the time for me (on Mac OS), also for one on my colleague (Windows), but not for others (both Mac and Windows). It might be an issue with their browser, though tried on both Safari and Chrome.
### Server configuration

**Operating system:** Ubuntu 14.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.5

**Teampass version:** latest

**Updated from an older Teampass or fresh install:** fresh install
### Client configuration

**Browser:** Chrome, Safari

**Operating system:** Mac and windows
#### Web server error log

```
[Wed Jul 27 14:08:30.235336 2016] [:error] [pid 21909] [client 188.60.229.232:50984] PHP Notice:  Undefined index: settings in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php
[Wed Jul 27 14:08:30.235391 2016] [:error] [pid 21909] [client 188.60.229.232:50984] PHP Warning:  include(/error.php): failed to open stream: No such file or directory in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php
[Wed Jul 27 14:08:30.235400 2016] [:error] [pid 21909] [client 188.60.229.232:50984] PHP Warning:  include(): Failed opening '/error.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php
[Wed Jul 27 14:08:38.562498 2016] [:error] [pid 22138] [client 188.60.229.232:50996] PHP Notice:  Undefined index: settings in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php
[Wed Jul 27 14:08:38.562568 2016] [:error] [pid 22138] [client 188.60.229.232:50996] PHP Warning:  include(/error.php): failed to open stream: No such file or directory in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php
[Wed Jul 27 14:08:38.562579 2016] [:error] [pid 22138] [client 188.60.229.232:50996] PHP Warning:  include(): Failed opening '/error.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/teampass/sources/main.queries.php on line 22, referer: http://password.versus-alternative.ch/index.php

```

**Comment by nilsteampassnet** [comment]
If it works for some and not for others (for whose you get thelog errors), there is maybe an issue with the CMOD of the files on the server.
Indeed the log errors you report are quite explicite "failed to open stream", "Failed opening"

**Comment by Marcvander** [comment]
Thanks for your answer. 
The issue didn't come from that. It came from the fact that the server time is GMT, while the time in here is GMT+2. So when someone who had a computer set on time GMT+2 and tried to log in, since the autodisconnect time was set on 60 min, it automatically disconnected the person. One solution is to set the time to more than 120 min, since we have 2 hours time difference with GMT.

**Comment by nilsteampassnet** [comment]
Interesting ... I will try to improve something regarding user local time.

**Comment by nilsteampassnet** [comment]
Could you please do the next change?

Open file /sources/identify.php

Search
`                $userTime = $serverTime + $dataReceived['TimezoneOffset'];`
Replace by
`                $userTime = $serverTime + abs($dataReceived['TimezoneOffset']);`

Can you tell me if it solves the issue you discovered?

**Comment by rodnertj** [comment]
Good afternoon, NILS, okay?

	I come through this request your help with Teampass, I created a Docker Container CentOS 7, and after downloading this container, I can no longer see the passwords of my intes, remembering that I have everything exposed on my host, bank and teampass itself, my docker-compose.yml looks like this:


version: "2"
services:
  teampass:
    image: teampass/teampass:latest
    container_name: teampass
    restart: always
    volumes:
      - "/opt/docker/scripts/teampass/teampass-instalado:/var/www/html"
      #- "/opt/docker/scripts/teampass/teampass-seckey.txt:/var/www/html/teampass-seckey.txt"
    ports:
      - "8070:80"
    environment:
      - "CATTLE_DB_CATTLE_MYSQL_HOST=192.168.0.32"
      - "CATTLE_DB_CATTLE_MYSQL_PORT=3306"
      - "CATTLE_DB_CATTLE_MYSQL_NAME=teampass"
      - "CATTLE_DB_CATTLE_USERNAME=teampass"
      - "CATTLE_DB_CATTLE_PASSWORD=Pa55@w0rd1"
    volumes:
      - "/opt/docker/data/mysql:/var/lib/mysql"

NOTE: When I start the container with the "docker-compose up d" it asks to do the whole installation.

Thanks in advance and help.

RodnerTJ.

**Comment by rodnertj** [comment]
Good afternoon, NILS, okay?

	I come through this request your help with Teampass, I created a Docker Container CentOS 7, and after downloading this container, I can no longer see the passwords of my intes, remembering that I have everything exposed on my host, bank and teampass itself, my docker-compose.yml looks like this:


version: "2"
services:
  teampass:
    image: teampass/teampass:latest
    container_name: teampass
    restart: always
    volumes:
      - "/opt/docker/scripts/teampass/teampass-instalado:/var/www/html"
      #- "/opt/docker/scripts/teampass/teampass-seckey.txt:/var/www/html/teampass-seckey.txt"
    ports:
      - "8070:80"
    environment:
      - "CATTLE_DB_CATTLE_MYSQL_HOST=192.168.0.32"
      - "CATTLE_DB_CATTLE_MYSQL_PORT=3306"
      - "CATTLE_DB_CATTLE_MYSQL_NAME=teampass"
      - "CATTLE_DB_CATTLE_USERNAME=teampass"
      - "CATTLE_DB_CATTLE_PASSWORD=Pa55@w0rd1"
    volumes:
      - "/opt/docker/data/mysql:/var/lib/mysql"

NOTE: When I start the container with the "docker-compose up d" it asks to do the whole installation.

Thanks in advance and help.

RodnerTJ.
