### ISSUE TITLE
SAML Authentication

### ISSUE THREAD

**Issue by bensoae87** [nilsteampassnet/TeamPass#1404]
### Feature Request

TeamPass has the option for LDAP, but you don't have the option for SAML Authentication. This could become a really useful addition to your project as many companies use SAML 2.0 for user authentication to many different applications within their corporate environments.

**Comment by nilsteampassnet** [comment]
A good idea.

**Comment by andreashuther** [comment]
I strongly support that!
(what are next steps? timeline?)

**Comment by zimage** [comment]
Why was this feature request closed?
