### ISSUE TITLE
2FA Option - Google 2 Factors Authentication is not working

### ISSUE THREAD

**Issue by mfonnegrae** [nilsteampassnet/TeamPass#1407]
I had recently install teampass 2.1.26 and enable the 2FA Options with google Authentication, but is not working, right now I want to disable it but when I save the change it says "Done" but the functionality stay enable all the time.

Question "There is any other way to disable this option rather than the web interface"

Mauricio Fonnegra

 
### Steps to reproduce
1. log into the web administration
2. go to settings and then 2FA Options
3. Enable Google 2-Factors authentication and try to login using this method
4. Disabled again and Save
5. click at any other option for sample the information TAB and them repeat the steps 1-3 and check if the option
6. log out and login again and check if the 2FA Authentication change.
### Expected behaviour

Tell us what should happen is that the 2FA Google Authentication will never disable it says done when apply the changes but once you go out the 2FA-Options the value of the google Authentication stays in "YES"
### Actual behaviour

Tell us what happens instead the 2FA Authentication is always on and is not working neither.
### Server configuration

*_Operating system_Debian 3.16.0-4*:

*_Web server:_Apache*

*_Database:_Mysql 5.6.31*

*_PHP version:_5*

*_Teampass version:_2.1.26\* 

*_Updated from an older Teampass or fresh install:_No*
### Client configuration

*_Browser:_Firefox, Explorer, Chorome*

*_Operating system:_Windows 7 and Windows 10*
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Sorry for the delay, I was in holidays with no internet access.

So just tested this and Google 2 factors is working on my test environment.
The button `save` is not used (and should have been removed from GUI).
Save is done while clicking on the slider.
What package is installed of 2.1.26 release?

You can disable using phpmyadmin.
In table `misc`, search for entry with:
- `type` = admin
- `intitule` = 2factors_authentication
and set `valeur` to 0

**Comment by mfonnegrae** [comment]
Thank you for replay nils, the reléase is 2.1.26 and I will try the workaround.

Best regards I will let you how it goes.

Mauricio A. Fonnegra Escalante

**Comment by dtochilo** [comment]
I have the same issue where disabling 2FA does not work, but the DB table update as listed works for me.

**Comment by qubez** [comment]
This can be closed. a3f697e is in master to fix toggling on/off, and #1471 in development branch puts a save button back on the Google name setting, so everything works as expected.

**Comment by mfonnegrae** [comment]
Yes nils,

The  workaround work.

Thanks

Mauricio A. Fonnegra Escalante
Department of Information and Technology Services
Secretariat for Administration and Finance
Organization of American States
1889 F Street N.W., Washington, D.C. 20006
Phone. 202.370.4531
mfonnegra@oas.org<mailto:mfonnegra@oas.org>
www.oas.org<http://www.oas.org/>
Jn 3:16
