### ISSUE TITLE
Folder Right Management

### ISSUE THREAD

**Issue by frankstuttgart** [nilsteampassnet/TeamPass#1408]
If you have multiple folder and multiple user it is sometimes difficult to have a right overview for a single folder.
It is possible to go to user management and check each user to see if he can access the folder.

It would be very usefull to see effective allowed users on a folder. # @

**Comment by chc88** [comment]
Why not using roles for this matter? The roles have a clear overview in my opinion

**Comment by frankstuttgart** [comment]
In this case I'd have to make one role per user.

Because every user has different rights.


We use teampass to manage customer specific passwords.

And for each customer we choose the supporting users.


It is possible but it's not like a role...


________________________________
Von: chc88 <notifications@github.com>
Gesendet: Mittwoch, 3. August 2016 11:09
An: nilsteampassnet/TeamPass
Cc: Frank Ruthardt; Author
Betreff: Re: [nilsteampassnet/TeamPass] Folder Right Management (#1408)


Why not using roles for this matter? The roles have a clear overview in my opinion

-

**Comment by nilsteampassnet** [comment]
Sorry for the delay, I was in holidays with no internet access.

I will try to think about a kind of report page.
I'm marking this as a Feature Request.

**Comment by nilsteampassnet** [comment]
IMplemented in 2.1.27
