### ISSUE TITLE
regression: PDF/CSV export broken in 2.1.26

### ISSUE THREAD

**Issue by daku69** [nilsteampassnet/TeamPass#1409]
I have made new installation in version 2.1.26. I can not export to PDF or csv.
In a new installation on version 2.1.25 is it possible.
 
### Server configuration
**Operating system**: Debian 8.4

**Web server:** Apache 2

**Database:** Mariadb

**PHP version:** 5.5

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** No

**Comment by ashmonger** [comment]
Same thing here.
Export to pdf is [YES] but I can't really select group/role.
And I don't have the line in the menu.

**Server configuration**
_Operating system:_ Debian Ubuntu 14.04 LTS
_Web server:_ Apache 2
_Database:_ mysql 
_PHP version:_ 5.5
_Teampass version:_ 2.1.26.15
_Updated from an older Teampass or fresh install:_ Fresh

**Comment by vfrazao** [comment]
Same thing here.

Operating system: Ubuntu 14.04

Web server: Apache 2

PHP version: 5.5.9

Teampass version: 2.1.26(15)

**Comment by nilsteampassnet** [comment]
Sorry for the delay, I was in holidays.

There is a bug in the selection of the groups.
I will correct this.

**Comment by vfrazao** [comment]
I noticed this yesterday.
So, I solved the problem by setting a user as manager and "in charge" for
the report. If I don´t apply any role for a manager user, I´ll be able to
export to a PDF file.
Thank you for the reply, and let me know when you correct the bug, please!

Best Regards,

Victor Frazão

2016-08-12 5:04 GMT-03:00 Nils Laumaillé <notifications@github.com>:

**Comment by nilsteampassnet** [comment]
What I've discovered until now.

If PHP version is 5.6.19 I have no issue.
But if PHP version is 7.0.4, then the problem arises.

So it seems that the PDF class call is broken in php 7.x. More investigation is needed

**Comment by nilsteampassnet** [comment]
Found a solution by updating the PDF libraries
