### ISSUE TITLE
Migrate from 2.1.19 to 2.1.26 on a new server

### ISSUE THREAD

**Issue by Laayem** [nilsteampassnet/TeamPass#1411]
Hi, 

Today I tried to upgrade my teampass on the last version. I made my backup, put it on the new server, downlad last version and start the upgrade. 

I can't find the settings.php file. So no upgrade.
Made a fresh install and try to restore a sql file from old server : 
> Error: -600, Message: File size error., File: db-backup-1470228658.sql

If anyone have a clue on this, I will apreciate a hint.

### Old Server configuration 
**Operating system**: Centos 6.3
**Web server:** Apache 2.2.15
**Database:** MySQL 14.14
**PHP version:** 5.3.3
**Teampass version:** 2.1.19 

### New Server configuration 
**Operating system**: Centos 6.8
**Web server:** Nginx 1.0.15
**Database:** MySQL 14.14
**PHP version:** 5.6.24
**Teampass version:** 2.1.26

### Client configuration
**Browser:** Firefox 47
**Operating system:** Ubuntu 15.10

**Comment by nilsteampassnet** [comment]
What is the size of your sql file?

**Comment by Laayem** [comment]
Sorry for the late reply.
The sqlfile has a size of 13,3 Mo.

**Comment by nilsteampassnet** [comment]
Take a look to your error message

> Error: -600, Message: File size error., File: db-backup-1470228658.sql

You will see that by default the maximum size for an uploaded file is 10mb.
So the message is normal.
You need to change this through settings page.

**Comment by Laayem** [comment]
I looked in php & nginx settings but didn't think at teampass settings.
Thanks

**Comment by volrod64** [comment]
Hello,

Personally, I still have the problem.
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/9a39c5db-9fbd-4512-af00-923fe59a489b)
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/faf83f71-1dd2-47f7-b579-b90851ebeece)

may you help me ? Thanks !

**Comment by volrod64** [comment]
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/4d2111f0-b1c5-4378-83aa-0aea8d9af82e)
I also changed settings in php.ini
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/65dbdc7d-303e-406e-9247-5c8b2de29a8a)
