### ISSUE TITLE
Can not drug&drop created by other users  items. 

### ISSUE THREAD

**Issue by rgalexey** [nilsteampassnet/TeamPass#1412]
### Steps to reproduce
1. Ask someone from managed users to create Item.
2. The element with cross-line-image not shown.
3. So can not drug and drop.
### Expected behaviour

All items with write access should be movable
### Actual behaviour

Can not drug&drop. No element for that shown.
### Server configuration

**Operating system**:
Centos 6.5
**Web server:**
Apache 2.4

**Database:**
Mysql

**PHP version:**
5.6

**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
Updated from 2.1.22
### Client configuration

**Browser:**
Any
**Operating system:**
Any

**Comment by giannakopoulosj** [comment]
Hello,

This could be very usefull. It will save huge time for reorganization of keys that users create. As currently in our project want to migrate from local keypass to TeamPass.

Teampass version used: TeamPass 2.1.26

**Comment by rgalexey** [comment]
Yes.
I am using for the same.

**Comment by panzo19** [comment]
Hello this feature it could be very useful +100  :+1: on this.

**Comment by nilsteampassnet** [comment]
Sorry for answer delay, I'm currently in holidays.

So currently, drag and drop of an item is not possible if user is not the author of the item.
To do so, you need to enable "Anyone can modify" option.

What could be done as an option that could permit any "managers" to have by-default the "move feature" enabled.
Is it something that is suitable for your needs guys?

**Comment by giannakopoulosj** [comment]
Currently we are having enabled as the following:
![image](https://cloud.githubusercontent.com/assets/2518387/18084624/31349588-6ea8-11e6-80f3-1b2c6f7ec3bb.png)

My account is Manager Account 

![image](https://cloud.githubusercontent.com/assets/2518387/18084684/67e5a2ca-6ea8-11e6-827f-86c9b7f135d4.png)

Answer to your question (What could be done as an option that could permit any "managers" to have by-default the "move feature" enabled.
Is it something that is suitable for your needs guys)

Yes it would be suitable if Managers could drug n drop as it will help to organize

**Comment by nilsteampassnet** [comment]
Implemented in 2.1.27
