### ISSUE TITLE
On creating a new folder first user role (and all it's members) will gave access to the new folder

### ISSUE THREAD

**Issue by makhorkin** [nilsteampassnet/TeamPass#1413]
### Steps to reproduce
1. Enable "New sub-folder inherits rights from parent folder = yes"
2. Create new user "Krtestuser"
3. Assign role "Arena QA"
4. Logon user
5. Assign role "DBA"
6. Refresh page (Ctrl+F5) to apply new permissions
7. Add subfolder to the only DBA-role allowed folder
8. At this moment parent folder became unavailable while page will not be refreshed via Ctrl+F5  - that is second separate issue
   ![image](https://cloud.githubusercontent.com/assets/2950577/17404474/6ac8e8b0-5a64-11e6-83b0-bd82ac24347b.png)
9. When we have page refresh, new folder is presented correctly
   ![image](https://cloud.githubusercontent.com/assets/2950577/17404500/827fb790-5a64-11e6-9956-cd845c0f3dbe.png)
10. In Roles Management we see that all ArenaQA role members gave access to the private DBA folder:
    ![image](https://cloud.githubusercontent.com/assets/2950577/17404581/e80761f8-5a64-11e6-99ec-8b35ccd9aa47.png)
11. Issue doesn't reproduced with addtional user roles - Add role VSOUsers
12. Refresh page (Ctrl+F5) to apply new permissions
13. Add subfolder to only-DBA allowed folder
14. All ArenaQA role members give access to private DBA folder, but VSOUsers role – doesn’t:
    ![image](https://cloud.githubusercontent.com/assets/2950577/17404650/2f31b01a-5a65-11e6-92f1-8d3761e8fb4f.png)
### Expected behaviour

Permissions for the new folder should be inherited from the parent folder and noone other shouldn't have access to the new folder.
### Actual behaviour

User have several roles. User creating new folder in the folder which is allowed for it by second role (in order of assignment). All members of the first user role will gave access to the new folder.
### Server configuration

**Operating system**: Ubuntu 16.04 LTS (GNU/Linux 4.4.0-28-generic x86_64)

**Web server:** apache 2.4.18-2ubuntu3.1

**Database:** mariadb-server (10.0.25-0ubuntu0.16.04.1)

**PHP version:** (7.0.8-0ubuntu0.16.04.2)

**Teampass version:** Release 2.1.26 (14)

**Updated from an older Teampass or fresh install:** Updated from Release 2.1.26 (13)
### Client configuration

**Browser:** Chrome 51.0.2704.103 m (64-bit)

**Operating system:** Windows 10.0.10586
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Thanks for reporting with such details.
But not sure I've understood the point.
Of course if a new folder is created, all users part of a same Role will also have access to it.
Now what is not normal is that a Role for which the parent folder is not allowed, this new folder becomes "allowed". I will correct this

**Comment by fpicot** [comment]
As of commit 8cc0cba, it seems that the "inherit permissions from parent folder" option does the exact opposite of what would be expected : 
* With the option active, new folders are created with full access for each roles assigned to the manager who creates the folder, and parent's permission for the other roles. 
* With the option inactive, new folders are created with the exact same permissions of the parent folder.

**Comment by Tmkrth** [comment]
Hello! I also expected that, with set inherit permissions, every subfolder to a folder has the same permission settings as a parent folder. Instead a user, who cannot see a parent folder, can see the same parent folder after creation of a subfolder in it. Permissions need to be set again for every new folder and it's parent to have the desired "who can see what"-settings.
