### ISSUE TITLE
LDAP password change 

### ISSUE THREAD

**Issue by MikeyHoef** [nilsteampassnet/TeamPass#1418]
We've enabled LDAP auth and personal folders. The saltkey is is using users passwords. Our policy is forcing LDAP users to change their password every 3 months. But.....

Changing the users active directory password will destroy all saved passwords because the salt key isn't the same as before. Is there any solution or workaround for this?

**Comment by makhorkin** [comment]
Could you please see https://github.com/nilsteampassnet/TeamPass/issues/613? I think it's the same issue.
