### ISSUE TITLE
Unable to login with new local user

### ISSUE THREAD

**Issue by Akiha** [nilsteampassnet/TeamPass#1419]
### Steps to reproduce
1. Login to the web interface with 「admin」and「LDAP options」 to link Teampass with a Windows AD
2. Add a new local user from the 「User Management」 page and give it a password.
3. Logout and try to login with the new local user.

### Expected behaviour
Normally logged in with that new local user.

### Actual behaviour
Login failed with error message "Login credentials do not correspond!"

### Server configuration
**Operating system**:
CentOS 6.5

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.1.10

**PHP version:**
5.6.19

**Teampass version:** 
2.1.26.8

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26.1

### Client configuration
**Browser:**
Any

**Operating system:**
Any

Here is some screen shots of my setting.

![teampass3](https://cloud.githubusercontent.com/assets/748749/17479662/b4dc142a-5dae-11e6-9923-857e9fcbf16e.JPG)
![teampass2](https://cloud.githubusercontent.com/assets/748749/17479661/b4c56b1c-5dae-11e6-82e3-9075e7e62865.JPG)
![teampass1](https://cloud.githubusercontent.com/assets/748749/17479663/b4dc5dea-5dae-11e6-869e-b12666b08d1a.JPG)

More information is to be given if needed.

**Comment by nilsteampassnet** [comment]
Sorry for the delay, I'm currently in holidays.

If you have enabled LDAP, it is not possible to get connected with a "local Teampass" user.
It is by design.

**Comment by Akiha** [comment]
Thank you very much for your reply.

My AD goes wrong sometimes so I need to log in with a local user at such circumstances.
So I'm going to first disable LDAP before doing this.
