### ISSUE TITLE
One time view link - "Blank" page- Fix

### ISSUE THREAD

**Issue by Aggerone** [nilsteampassnet/TeamPass#1420]
### Steps to reproduce
1. On a item, menu, click One time view link
2. The link will result in a blank page

### Expected behaviour
Show the page with the user/pw

### Actual behaviour
Blank page

### FIX in otv.php - there is a missing ) on line 54 in otv.php, see diff:

--- org.otv.php 2016-08-09 11:30:21.178568559 +0200
+++ otv.php     2016-08-09 11:36:33.572854520 +0200
@@ -51,7 +51,7 @@
         $data['timestamp'] == $_GET['stamp']
     ) {
         // otv is too old
-        if ($data['timestamp'] < ( time() - ($_SESSION['settings']['otv_expiration_period'] * 86400) ) {
+        if ($data['timestamp'] < ( time() - ($_SESSION['settings']['otv_expiration_period'] * 86400) ) **)** {
             $html = "Link is too old!";
         } else {
             $dataItem = DB::queryfirstrow(

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:** nginx

**Database:** mysql 

**PHP version:** PHP 5.6.23-2+deb.sury.org~xenial+1 (cli) 

**Teampass version:** 2.1.26.5

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:** Any

**Operating system:**
Any

#### Web server error log
2016/08/09 11:31:17 [error] 1257#1257: *9137 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: otv_id in /var/www/TeamPass-2.1.26.5/otv.php on line 90" while reading response header from upstream, client: 1.2.3.4, server: x.y.com, request: "GET /index.php?otv=true&code=352fffcd34ad820864d4fc728ac52491&stamp=1470734742 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:"

Insert your webserver log here
1.2.3.4 - - [09/Aug/2016:11:31:17 +0200] "GET /index.php?otv=true&code=352fffcd34ad820864d4fc728ac52491&stamp=1470734742 HTTP/1.1" 200 10598 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"

**Comment by nilsteampassnet** [comment]
Thanks.

But since 2.1.26.5, it was fixed.

But really appreciated

**Comment by Aggerone** [comment]
Nice, and Thank you :)
