### ISSUE TITLE
Feature - TeamPass should prevent deleting of a folder with any subfolder

### ISSUE THREAD

**Issue by makhorkin** [nilsteampassnet/TeamPass#1422]
As mentioned in #1347, TeamPass allow drop a folder with subfolders.
Therefore, folder structure may become inconsistent.
It would be nice if TeamPass will be checking that a folder have any subfolder before deleting it.
I think TeamPass should prevent deleting of the folder with any subfolder.

**Comment by nilsteampassnet** [comment]
Some changes were performed here.
- A warning is sent to the user if sub-folder exists
- Selection of a "top-folder" will select the "sub-folders" ... it is visible.
