### ISSUE TITLE
Fixes for many critical issues with OTV in 2.1.26

### ISSUE THREAD

**Issue by SonofLiberty90** [nilsteampassnet/TeamPass#1423]
First of all, all the old OTV-links are getting deleted (even those that were not accessed) when new OTV is created. That happens because of a wrong time calculation in items.queries.php at line 2703:
**CURRENTLY:**
`$rows = DB::query("SELECT id FROM ".prefix_table("otv")." WHERE timestamp < ".(time() - $_SESSION['settings']['otv_expiration_period']));`

**SHOULD BE**:
`$rows = DB::query("SELECT id FROM ".prefix_table("otv")." WHERE timestamp < ".(time() - $_SESSION['settings']['otv_expiration_period'] * 86400));`

Secondly, every time OTV link is accessed main SALT is being exposed, which is kinda horrible security issue. I think Nils just forgot to comment this code in otv.php, line 68.
**CURRENTLY:**
**echo $dataItem['pw']. " ;; ".SALT." ;; ". $dataItem['pw_iv']. " ;; ".$pw['string'] ;**

I GUESS THIS LINE SHOULD BE REMOVED OR COMMENTED OUT.

And the last one that i found. OTV is not working properly each time we create it, sometimes it just says "Not a valid page" even with a first access.
I spent much time figuring out what the problem is, then i found two issues:

Line 47 in otv.php:
**CURRENTLY:**
`WHERE code = %i",`

Here we have placeholder for integer type, but our code is string. So we should replace it with:
WHERE code = %s",

And the last thing which related to this issue is that we are converting code to int using intval at line 48 of otv.php:
**CURRENTLY:**
`intval($_GET['code'])`

Which could result in an empty query results, so I just replaced it with:
`$_GET['code']`

After this changes were made all the issues with OTV's creation, storing and deletion were gone.

**Comment by nilsteampassnet** [comment]
You are absolutely right!

Many thanks for sharing this.

**Comment by SonofLiberty90** [comment]
Nils,
Are you going to commit these changes?
