### ISSUE TITLE
Feature Request: Context Menu

### ISSUE THREAD

**Issue by crouch766** [nilsteampassnet/TeamPass#1425]
Hi,
thanks for the excellent work that you have done.

What do you think to implement a context menu for items/folders with the basic actions (add, delete, modify, show password, ecc..)?

Thanks,
Bye,
Stefano

**Comment by nilsteampassnet** [comment]
Sorry for late answer, it is holidays period for me ;)

The GUI will be reworked in 2.2 release and Context Menu could be part of it.

Thanks for suggestion

**Comment by crouch766** [comment]
Thanks for your work! And good holidays!
Bye!

Il 13 ago 2016 9:44 AM, "Nils Laumaillé" <notifications@github.com> ha
scritto:
