### ISSUE TITLE
I can't export to pdf.

### ISSUE THREAD

**Issue by ericxuo** [nilsteampassnet/TeamPass#1427]
Hi,

I am currently using version 2.1.26.15 of Teampass.
I can't get the icon to export in pdf. As admin, I have selected the field " Enabling PDF printing of elements" (translated from french !!) in the "Personalize" page, but no icon is available when I log as user ericxuo (who is a manager).
I could modify manually the file includes/config/tp.config.php but I don't know what field to add.

Can you help me ?

Regards.

Ericxuo.

**Comment by nilsteampassnet** [comment]
Have you enabled the export for the group of users in which your account is ? 
Just bellow the export cursor you need to select the roles that can export.

**Comment by ericxuo** [comment]
Hi,

Yes, I did. There is only one possibility in my case.
Shouldn't it be displayed in the file tp.config.php ?

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I've added some screen snapshots. Hope this helps.

Regards.

Xuo.
![teampass_users](https://cloud.githubusercontent.com/assets/9089499/17671075/4f84ce02-6315-11e6-8153-4b9b2b7b75c5.png)
![teampass_personalize](https://cloud.githubusercontent.com/assets/9089499/17671076/4fa36830-6315-11e6-9a96-241b5483bd8a.png)

**Comment by nilsteampassnet** [comment]
Don't you have this button?
![image](https://cloud.githubusercontent.com/assets/1197546/17673169/3f403c74-6320-11e6-9772-3533205cddb5.png)

**Comment by ericxuo** [comment]
Hi,

No, I don't have it. My last one is "Import Items".

Regards.

Xuo.

**Comment by nilsteampassnet** [comment]
Oops you are right, it is a bug I've corrected in commit a3f697e
Refer to #1409

**Comment by ericxuo** [comment]
Great. I'll wait for the commit to be added in the next main release (2.1.26.16 maybe ?).

Regards.

Xuo.
