### ISSUE TITLE
Can only create one password at a time

### ISSUE THREAD

**Issue by cgkelleher** [nilsteampassnet/TeamPass#1431]
### Steps to reproduce

1.Create one password in a folder
2.Try to create another - entry box does not show up
3.need to refresh page to enter another password
### Expected behaviour

as above - should be able to enter more than one password without refresh of page
### Actual behaviour

need to refresh page
### Server configuration

ubuntu 16.04 lts

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7.0.8

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
Fresh
### Client configuration

IE11 (this is our only supported browser)

**Operating system:**
ubuntu 16.04 lts

**Comment by TheKingKai** [comment]
Same Problem. But it works with Mozilla FireFox. I only have this problem with the IE 11!
