### ISSUE TITLE
2.1.26.16 cannot delete folder

### ISSUE THREAD

**Issue by mweber88** [nilsteampassnet/TeamPass#1432]
### Steps to reproduce
1. Log in as admin user
2. create a folder
3. delete a folder

### Expected behaviour
Folder is deleted

### Actual behaviour
If folder checkbox is checked and trash can button is clicked, "are you sure" and ok, folder remains and blue spinning gear lingers indefinitely.

If Edit link in front of folder is clicked, and Delete is chosen, "are you sure" and ok, folder remains but there is an apparent screen refresh, no blue spinning gear.

### Server configuration
**Operating system**:
Mac OS X 10.11.6

**Web server:**
apache 2.4.18

**Database:**
MySql 5.7.13

**PHP version:**
5.5.36

**Teampass version:** 
2.1.26.16

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Firefox or Chrome

**Operating system:**
Mac OS X 10.11.6 or Windows 10

#### Web server error log
```
No errors in Apache log, no errors in Mysql log

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
No errors in Firebug

```

**Comment by mweber88** [comment]
I should also note that items within a folder CAN be deleted without any problems.

**Comment by nilsteampassnet** [comment]
There is a bug in file install/install.queries.php that prevent the création of table "cache ". 

To correct, open this file and search for "cache" 
In the query you will see a coma just before à closing parenthis which need to be deleted. 

Copy the query in phpmyadmin and run it to create this table. 

I will commit the fix tonight

**Comment by mweber88** [comment]
Yes, this definitely fixed it.  Thank you!

**Comment by nilsteampassnet** [comment]
It was really a stupid bug ...
Thanks for the feedback.
