### ISSUE TITLE
Link Open TeamPass dont works

### ISSUE THREAD

**Issue by OptimusOS** [nilsteampassnet/TeamPass#1435]
### Steps to reproduce
1. start the upgrade 
2. upgrade is done without errors
3. Push link [Open TeamPass] -> (https://teampass-test.internaldomainname.de/install/upgrade.php)

### Expected behaviour
Tell us what should happen
Startsite for login Teampass
### Actual behaviour
Tell us what happens instead
Browser say
his site is not reachable
The DNS server address of  https://teampass-test.internaldomainname.deindex.php was not found.
DNS_PROBE_FINISHED_NXDOMAIN
it lacks a slash between .de and index.php

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS 
**Web server:**
Apache/2.4.18
**Database:**
Mysql  5.7.13-0
**PHP version:**
PhP 7
**Teampass version:** 
2.1.26.16
**Updated from an older Teampass or fresh install:**
upgrade from 2.1.26.8 -> 2.1.26.16
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7

**Comment by nilsteampassnet** [comment]
Strange, the link url is calculated only using server variables.
Perhaps is it relating redirection on your domain or sub-domain definition.

Here is how it is calculated.
`<a href="#" onclick="javascript:window.location.href=\'', (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1) || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ? 'https' : 'http', '://'.$_SERVER['HTTP_HOST'].substr($_SERVER['PHP_SELF'],0,strrpos($_SERVER['PHP_SELF'],'/')-8).'\';"><b>Open TeamPass</b></a>`
