### ISSUE TITLE
HTML tags in title="" attribute used for tooltips

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1436]
I'm working my way through a big HTML fix to reduce the 300+ validation errors, and found something that is beyond the mismatched <td> tags, unclosed elements, etc. An error by design.

The language files provide tooltip text, which is rendered in a title="tooltop" element in various elements. However, some of the tooltips have HTML markup in them. **title** attributes can contain _only_ text. HTML delimiters are not permitted as contents of a title, only data.

### Steps to reproduce
1. View admin's "Teampass settings"
2. Hover over "Path to Upload folder"'s (?) tooltip to enjoy HTML-coded tooltip
3. view source to see broken HTML with elements like title="<span style='font-size:11px;max-width:30

### Expected behaviour
Valid HTML is generated in compliance with the XHTML doctype

### Actual behaviour
Bad HTML

### Server configuration
**Teampass version:** 
2.1.26 - master, 2016-08-17

The quick solution is to strip all HTML out of language files, reducing the tooltip appearance quality, but I am reluctant to do that without quorum. 
Restoring the multiline, formatted appearance of some tooltips would require css styling/javascript if deemed necessary.

Want a pull request for non-html language files?

**Comment by qubez** [comment]
I found additional problems in the language files relating to tool tips - there is PHP code in tips that not interpreted, and is rendered incorrectly in browser.

An example is 'enable_personal_folder_feature_tip', which has text like:
The script \'".$txt[\'admin_action_check_pf\']."\' is available in tab \'".$txt[\'admin_actions_title\']

This causes HTML output which including the unparsed php which breaks the tooltip at the very least.

The language files must have the code here removed and replaced with the other translated text.

**Comment by qubez** [comment]
Among other fixes, this is fixed by language file entries inserted into html elements is sanitized in pull https://github.com/nilsteampassnet/TeamPass/pull/1441/commits/7510d6f58bd42e83d7ddde6f6ee7ad41eee51fb9

Language files could still use cleaning, and fancy markup could be restored with characters safe to insert into title="" tags and new javascript to process them.

**Comment by nilsteampassnet** [comment]
Thanks for your correction here.
It is something that I would have liked to improve since a long time but no time for it.
Many thanks.

**Comment by qubez** [comment]
Fancy tooltips can be returned with the current language file markup, by using other tooltipster insertion methods.

**Comment by qubez** [comment]
Fixed in development and looking good. Thanks for all your work! Closing.
