### ISSUE TITLE
How to upgrade using git.

### ISSUE THREAD

**Issue by ericxuo** [nilsteampassnet/TeamPass#1437]
Hi,

This is not a bug but a help request and I'm not sure this is the correct place to ask for help.
I have installed TeamPass using : 
git clone https://github.com/nilsteampassnet/TeamPass.git
I want to upgrade with :
git pull 
and I get :

```
error: Your local changes to the following files would be overwritten by merge:
        admin.settings.load.php
        admin.settings.php
        admin.settings_duo.php
        api/functions.php
        changelog.md
        find.load.php
        find.php
        includes/config/include.php
        includes/libraries/Database/Meekrodb/db.class.php
        includes/libraries/Pdf/Tfpdf/font/courier.php
        includes/libraries/Pdf/Tfpdf/font/helvetica.php
        includes/libraries/Pdf/Tfpdf/font/helveticab.php
        includes/libraries/Pdf/Tfpdf/font/helveticabi.php
        includes/libraries/Pdf/Tfpdf/font/helveticai.php
        includes/libraries/Pdf/Tfpdf/font/symbol.php
        includes/libraries/Pdf/Tfpdf/font/times.php
        includes/libraries/Pdf/Tfpdf/font/timesb.php
        includes/libraries/Pdf/Tfpdf/font/timesbi.php
        includes/libraries/Pdf/Tfpdf/font/timesi.php
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSans-Bold.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSans-BoldOblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSans-ExtraLight.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSans-Oblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSans.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansCondensed-Bold.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansCondensed-BoldOblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansCondensed-Oblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansCondensed.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansMono-Bold.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansMono-BoldOblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansMono-Oblique.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSansMono.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerif-Bold.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerif-BoldItalic.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerif-Italic.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerif.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerifCondensed-Bold.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerifCondensed-BoldItalic.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerifCondensed-Italic.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/DejaVuSerifCondensed.ttf
        includes/libraries/Pdf/Tfpdf/font/unifont/dejavusanscondensed.mtx.php
        includes/libraries/Pdf/Tfpdf/font/unifont/ttfonts.php
        includes/libraries/Pdf/Tfpdf/font/zapfdingbats.php
        includes/libraries/Pdf/Tfpdf/fpdf.php
        includes/libraries/Pdf/Tfpdf/tfpdf.class.php
        items.export.php
        items.load.php
        load.php
        otv.php
        profile.php
        sources/admin.queries.php
        sources/core.php
        sources/datatable/datatable.users.php
        sources/export.queries.php
        sources/find.queries.php
        sources/folders.queries.php
        sources/import.queries.php
        sources/items.queries.php
        sources/main.functions.php
        sources/main.queries.php
        sources/users.queries.php
        users.load.php
Please, commit your changes or stash them before you can merge.
Aborting
```
1. Is it possible to upgrade from git ?
2. If yes, what is the correct procedure to follow (i.e. how to upgrade the mysql database if necessary) ?

Regards.

Xuo.

**Comment by qubez** [comment]
This is a place for bugs, not help, although Teampass lacking a reliable install or upgrade system is certainly feature-request worthy.

You should not replace your installation with all the files from the git archive or a complete download, or mirror the archive directly on your active webserver directory - this will reintroduce the "install" folder and install.php, which are not protected and can damage your install if run again. There is no upgrade provision were database entries to change.

Additionally, the permissions on files should have been set more securely than default after install; replacing with git files would reset these. The owner and group should have been changed to the webserver's account (www-data or apache). The chmod permissions of all files except /upload and /files and a few config files should be set to write only, even for web server account.
.
If you have done no special editing or customization on the teampass source files, you can:
- make a complete copy of the install directory for backup (cp -a /var/www/teampass /var/www/teampass.old as a Linux command, for example)
- back up your MySQL database
- extract the git zip or sync files to their own location on the same system
- put system in maintenance mode to prevent inconsistencies
- excluding the install directory, overwrite files on your running system
- reset the permissions of files to match the backup directory
- test all pages including admin, hope that nothing large has changed requiring restoration of backup.

**Comment by ericxuo** [comment]
Hi,

Thanks for your help. I'll do that.

Regards.

Xuo.
