### ISSUE TITLE
Automatic User creation via AD missing information

### ISSUE THREAD

**Issue by mweber88** [nilsteampassnet/TeamPass#1440]
### Steps to reproduce
1. New User login via Active Directory
2. New user created in Teampass missing name, last name, email, all accessible in AD
3.

### Expected behaviour
User should really be created in Teampass with the attributes from AD, which are available to any user (which has reader access to AD by default).

### Actual behaviour
Only login is used from AD

If you wish, you can direct me to the files where this happens, and I can dig into it and see if it is possible to do.  I believe it is, so I'm willing to help... and I'm a seasoned developer, very experienced with LDAP and many RDBMS, but with minimal PHP experience.

Mike

**Comment by TheKingKai** [comment]
It is a good idea and very helpful to identify new user!!

**Comment by nilsteampassnet** [comment]
This could be added, but I cannot debug LDAP, so I need you.

Open file /sources/identify.php

Find
`        $data['pw'] = $pwdlib->createPasswordHash($passwordClear);  // create passwordhash`
Replace by
`        $data['pw'] = $pwdlib->createPasswordHash($passwordClear);  // create passwordhash
        
        // get user info from LDAP
        $user_info_from_ad = $adldap->user_info($auth_username, array("mail", "name", "lastname"));`

Find
`        DB::insert(
            prefix_table('users'),
            array(
                'login' => $username,
                'pw' => $data['pw'],
                'email' => "",`
Replace
`        DB::insert(
            prefix_table('users'),
            array(
                'login' => $username,
                'pw' => $data['pw'],
                'email' => $user_info_from_ad['mail'],
                'name' => $user_info_from_ad['name'],
                'lastname' => $user_info_from_ad['lastname'],`

Please come back to me.

**Comment by mweber88** [comment]
Nils--

Do you wish for the "name" field in Teampass to be:

Michael A. Weber

or do you wish it to be only firstname:

Michael

?  If you wish firstname, the attribute is givenName.  If you wish fullname, the attribute is name.

Additionally, lastname is not an attribute of Active Directory ldap (nor do I believe it is standard for other LDAP); rather it is sn.

Please return back to me and I will give you the final code snippet which you desire.

Mike

**Comment by mweber88** [comment]
Also, I'm going to attempt to debug why the ldap_suffix is not being used when authenticating users while I'm in here.

**Comment by nilsteampassnet** [comment]
Hi @mweber88 
Thanks for feedback.
What I expect is:
 * name = Weber
 * lastname = Michael A.

So if I foolow your instructions, I should use:
 * givenName (should return "Micheal A.")
 * name (will return "Michael A. Weber" => so I need to remove givenName from name to obtain what I need)

Correct?

**Comment by mweber88** [comment]
I think that is backwards, logically.  ;)

Here is what I have in my Teampass user settings:

![image](https://cloud.githubusercontent.com/assets/2997292/18064169/cf89399c-6df3-11e6-9e17-5685d82b3ce1.png)

The label, "Last name," corresponds to my last name, which is Weber.  I have put "Michael" in for the "name" field, which is my first name.  I know you do not wish to see my first name (Michael) and middle initial (A.) in the "lastname" field.

I hope the image shows above.

Mike

**Comment by nilsteampassnet** [comment]
Ok thanks

Did you manage to perform the change in identify.php file (using the fields you want), just to perform a test and check if AD return some data.

**Comment by mweber88** [comment]
Doing that now.  I'll report back in a few minutes what happens.

**Comment by mweber88** [comment]
Unfortunately, it looks like there is a problem and it is hanging here:

![image](https://cloud.githubusercontent.com/assets/2997292/18066247/2dc6dbe6-6dfd-11e6-9a3c-2cdb3e6d08c1.png)

How do I enable debugging, and where do the debug logs go?

Mike

**Comment by mweber88** [comment]
Nevermind... I found how to enable LDAP debugging and where the file goes.  I'm going to debug it and see the problem.

**Comment by mweber88** [comment]
Nils--

There is a problem in the adLDAP.php file (v3.3.1).  In the user_info function,

if ($isGUID === true) {
            $username = $this->strguid2hex($username);
            $filter = "objectguid = ".$username;
        } else {
            $filter = "samaccountname = ".$username;
        }

Must be:

if ($isGUID === true) {
            $username = $this->strguid2hex($username);
            $filter = "objectguid=".$username;
        } else {
            $filter = "samaccountname=".$username;
        }

(no spaces after objectguid and samaccountname when setting up the $filter variable.

Rather than fixing this in a library to make the function work, do you think we should replace this library with the newer version since 3.3.1 seems to be dated back to 2009, do you think we should update the library to the latest, v4.0.4?  If only using the authenticate function, it's a direct update to 4.0.4; otherwise, there are changes to make.  Since we are only now implementing the use of the user_info function, I think it would be fine to update this library, and also fix any outstanding LDAP issues in identify.php (and I'm willing to do that if you can tell me the mindset behind the three different LDAP configurations (posix-search, posix, AD) and why two of them use the AD library.

Also, to make the user creation work, the code for identify.php needed more than just the array variable name:

                'email' => $user_info_from_ad[0]['mail'][0],
                'name' => $user_info_from_ad[0]['givenname'][0],
                'lastname' => $user_info_from_ad[0]['sn'][0],

But, it does work perfectly:

![image](https://cloud.githubusercontent.com/assets/2997292/18073896/7627b8d4-6e2e-11e6-9f00-3fa7fad86c1c.png)

Let me know what you think and how we should proceed.

Mike

**Comment by nilsteampassnet** [comment]
Hi Mike. 

Good job. 
I will update LDAP library as the current version used in Teampass has no specific local changes. 
And also do the adaptation you have identified to make this work. 

Concerning your proposal to improve LDAP issues in identify.php, you are ce to do a PR, but unfortunately I can't help with the LDAP configurations (posix-search, posix, AD) as they are merged PR. 
I have really no knowledge on LDAP and only implemented the initial bridge. The improvements came from Users. 

Thanks

**Comment by mweber88** [comment]
Sounds good.  I will investigate what it takes to do a PR, setup a test LDAP directory, and check what is needed and what can be modified/cleaned up.  However, I will wait for your changes.

In my investigation, I found a problem for another LDAP-related issue I opened (#1433).  Since this also has roots in identify.php possibly as well as admin.settings.php, do you think you'll address these together?

Learning PHP is fun!  :)

**Comment by nilsteampassnet** [comment]
No issue to address both in one PR.

I've committed the simple changes for the original aim of this ticket.
I've updated the adLDAP library to 4.0.4.
This implies some different calls of adLDAP library.
Can you please check if this still works?

The commit is done in a new branch fix_1440

**Comment by mweber88** [comment]
In checking, at this point in identify.php, it appears to fail:

$adldap = new LDAP\adLDAP\adLDAP(
                array(
                    'base_dn' => $_SESSION['settings']['ldap_domain_dn'],
                    'account_suffix' => $ldap_suffix,
                    'domain_controllers' => explode(",", $_SESSION['settings']['ldap_domain_controler']),
                    'use_ssl' => $_SESSION['settings']['ldap_ssl'],
                    'use_tls' => $_SESSION['settings']['ldap_tls']
                )

The debug lines immediately following do not execute, and I have no errors in my PHP log file, or in apache log file.  So, there is apparently something different and I am having trouble trying to debug it since I cannot get any debug exceptions.

**Comment by mweber88** [comment]
I managed to debug and learn at least part of what is going on.

In the new adLDAP/adLDAP.php file, at the very bottom, the adLDAPException class.  I had to put a \ in front of Exception class to get things to partially work so I can at least debug, and I learned this by looking at the 3.3.1 class file used previously.

Now, it appears to fail when it tries to return the userclass with the user() function.  It fails at this line, but I get no errors.

Could any of this be cause by using the SplClassLoader rather than doing a require_once of the adLDAP class file?

**Comment by mweber88** [comment]
OK!  I debugged this, and I am now successful, although the ldap library 4.0.4 was problematic.  I upgraded to 4.0.5, located here:

https://github.com/Adldap2/Adldap2/releases/tag/v4.0.5

changed the SplClassLoader for adldap to:

 $adldap = new SplClassLoader('adLDAP', '../includes/libraries/LDAP');

changed the line which includes:

$adldap->user->authenticate

to:

$adldap->authenticate

and it functions correctly.

Note:  the authenticate method is located in the adLDAP class, so it is not needed to go into the adLDAPUsers class, then come back out to the parent class.

If you would like to put the 4.0.5 LDAP library into place in the fix1440 branch, make the changes to the lines I listed above, I will gladly download the branch and test again.

Mike

**Comment by nilsteampassnet** [comment]
Did you manage to test if fix1440 branch is okay?

**Comment by mweber88** [comment]
I did a lot of testing and debugging, and as I noted in the comment above, I recommend upgrading to adLDAP 4.0.5 (linked above), leaving it intact, and changing two lines of code in identify.php (also noted above).  Once this is done, I can test again, and I am certain we will be successful and ready to proceed.

**Comment by mweber88** [comment]
Nils--

This can be closed with #1486 which you closed today.
