### ISSUE TITLE
Uploading files with Microsoft Edge doesn't work

### ISSUE THREAD

**Issue by ramondeklein** [nilsteampassnet/TeamPass#1442]
It is not possible to upload files with Microsoft Edge. It does work with Google Chrome.
### Steps to reproduce
1. Upload a file
### Expected behaviour

The file selection window should appear.
### Actual behaviour

Nothing happens with Google Chrome.
### Server configuration

**Operating system**: Windows 10
**Teampass version:** 2.1.26
**Browser:** Microsoft Edge 38.14393.0.0

**Comment by nilsteampassnet** [comment]
This seems to be an Plupload/Edge issue.
Will be correct once library updated.
