### ISSUE TITLE
Error on Teampass Upgrade 2.1.25 to 2.1.26.17 STEP 2

### ISSUE THREAD

**Issue by SylvainGuibert** [nilsteampassnet/TeamPass#1444]
Thx nils for your job, Teampass is a great product !

When i try to update Teampass 2.1.25 to 2.1.26.17, on step 2 i obtain : error "Impossible to get connected to server. Error is: Access denied for user 'teampass_admin'@'localhost' (using password: YES)" appears. [ I need to upgrade because i have an CSRF issue on 2.1.25 when i save my settings]

**What i have checked :** 
- try to connect with "teampass_admin" user on mysql CLI Using password : OK
- Privilegies on Teampass Database are OK (ALL PRIVILEGIES)
- I have test database connexion with php script gave on #186 : OK
- Create another user on mysql with all privileges on Teampass Database and test with #186 script : Same Issue
- Checked log on /var/log/mysql/error.log : Nothing
 

### Steps to reproduce
1. Perform an upgrade to 2.1.25 to 2.1.26.17

### Server configuration
**Operating system**: Ubuntu 14.04.1 LTS
**Web server:** : Apache 2.4.7
**Database:** : Mysql 5.5.4
**PHP version:** 5.5.9
**Teampass version:** 2.1.25 
**Updated from an older Teampass or fresh install:** Updated from an older Teampass

### Client configuration
**Browser:** Chrome 50.0
**Operating system:** : Windows 10

Any ideas ?

**Comment by qubez** [comment]
Saw before also, a second click on "launch" and it would say OK, a third click on "launch" and this error again.

**Comment by SylvainGuibert** [comment]
I test today.....dans.....at the first "click" on "LAUNCH"...connection is successful ... I don't know why ... so i close this thread...thx for your help.
