### ISSUE TITLE
Advertise password by mail

### ISSUE THREAD

**Issue by si62000** [nilsteampassnet/TeamPass#1446]
Hello, i'm sorry in advance for my English , I'm French .
I have a problem with teampass version :  2.1.26, when i would like to advertise password by mail.

But i have a problem when the mail it's in french, the link of the mail not work, and the link correspond to : ".@$_SESSION[".
I verified, and the problem it's the language. In english i have no problem, the link work.

I test with other version of php and i have a problem, can you help me ? thanks you

**Comment by qubez** [comment]
The problem is in the translation file for many languages:

Bad:
TeamPass\includes\language\french.php(181):
    'email_body_item_updated' => 'Bonjour,<br><br>Le mot de passe de l\'élément \'#item_label#\' a été mis à jour.<br /><br />Vous pouvez le vérifier <a href=\'".@$_SESSION[\'settings\'][\'cpassman_url\']."/index.php?page=items&group=#item_category#&id=#item_id#\'>ICI</a><br /><br />Salutation',

English file is good:
english.php:
    'email_body_item_updated' => 'Hello,<br><br>Password for \'#item_label#\' has been updated.<br /><br />You can check it <a href=\'#url#/index.php?page=items&group=#item_category#&id=#item_id#\'>HERE</a><br /><br />Cheers',

To repair french.php, change the line to:
    'email_body_item_updated' => 'Bonjour,<br><br>Le mot de passe de l\'élément \'#item_label#\' a été mis à jour.<br /><br />Vous pouvez le vérifier <a href=\'#url#/index.php?page=items&group=#item_category#&id=#item_id#\'>ICI</a><br /><br />Salutation',

**Comment by nilsteampassnet** [comment]
Thanks @qubez
