### ISSUE TITLE
Delete category hangs UI and crashes PHP

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1449]
### Steps to reproduce
1. In admin interface, on categories tab, create a new category
2. select the category, and press delete
3. UI locks up

### Expected behaviour
Category should be removed from database with no problems

### Actual behaviour
User interface hangs with progress icon.

### Server configuration
**Operating system**:
Ubuntu Server 16.04.1 LTS Linux 4.4.0-34-generic on i686

**Web server:**
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips 

**Database:**
5.7.13-0ubuntu0.16.04.2 - (Ubuntu)

**PHP version:**
PHP Version 7.0.8-0ubuntu0.16.04.2

**Teampass version:** 
2.1.26 (17)

**Updated from an older Teampass or fresh install:**
fresh

### Client configuration
Firefox 48

**Operating system:**
Windows 7 x64

#### Teampass error log:
```
[22-Aug-2016 15:01:40 UTC] PHP Notice:  Undefined variable: link in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[22-Aug-2016 15:01:40 UTC] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
teampass errorlog: 23/08/2016 06:08:13 am	Query: DELETE FROM `teampass_categories_folders` WHERE category_id = 4<br />Error: Unknown column 'category_id' in 'where clause'<br />@ 	admin

```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

No errors

**Comment by nilsteampassnet** [comment]
Thanks for reporting
