### ISSUE TITLE
Purge log feature - purges nothing

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1450]
### Steps to reproduce
1. As admin or user with rights, navigate to views -> logs
2. Select a page with entries you would like to remove (errors probably has some...)
3. Select a date range, and press Purge now!

### Expected behaviour
Selected date range of log entries being viewed should be removed.

### Actual behaviour
No action, no confirmation from button press, and no changes to logs.

### Server configuration
**Operating system**:
Ubuntu Server 16.04.1 LTS Linux 4.4.0-34-generic on i686

**Web server:**
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips 

**Database:**
5.7.13-0ubuntu0.16.04.2 - (Ubuntu)

**PHP version:**
PHP Version 7.0.8-0ubuntu0.16.04.2

**Teampass version:** 
2.1.26 (17)

**Updated from an older Teampass or fresh install:**
fresh

### Client configuration
Firefox 48

**Operating system:**
Windows 7 x64

### Logs

No errors

**Comment by nilsteampassnet** [comment]
Correct.
I will commit a fix today.
