### ISSUE TITLE
API outputs deleted passwords

### ISSUE THREAD

**Issue by jgherb** [nilsteampassnet/TeamPass#1454]
This is a security issue, deleted passwords must not be output over a API.
In my opinion it is also not OK, that deleted passwords are stored in the database, but maybe you want to add an recovery function later.

**Comment by nilsteampassnet** [comment]
Hi Julius,
Thanks for your input. 
But I don't really see why according you deleting item through an api as a security issue.
It is a provided feature of the api.

Concerning second point, yes there is a recycling-bin which permits to restore deleted items.

Note: in your pull-request, I just see code change proposal corresponding to  #1453. Did I miss something?

Thanks.

**Comment by qubez** [comment]
jgherb can _view_ deleted passwords via API.

**Comment by nilsteampassnet** [comment]
Ah didn't understood this. 
Yes this is to bad. 
But easy to fix. 
I will check the proposed PR or provide the fix. 

Thanks

**Comment by jgherb** [comment]
In my pull request I only fixed the issues in the new function "read/userpw". I forgot to change the "read/categories" and "read/items" function. I'm sorry, but it is an easy fix.

**Comment by nilsteampassnet** [comment]
Thanks for this.

Now corrected
