### ISSUE TITLE
Knowledge base feature exposes unauthorized password labels

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1456]
The Knowledge base beta has many problems, but this is a large one disclosing information about other users.

### Steps to reproduce
1. Create a low-privileged account
2. Create a high-privileged account with roles and folder only they can access
3. With high-privileged account, create password items with private labels
4. Log in as low user, go to knowledge base, create entry, see a list of all the item labels including ones the user should not be able to access.

### Expected behaviour
Users should never be able to glean information about passwords/sites from disallowed folders

### Actual behaviour
Users can see password labels in knowledge base they can't otherwise access, resulting in information disclosure

### Server configuration

**Teampass version:** 
2.1.26 (17)

**Updated from an older Teampass or fresh install:**
fresh test install on Ubuntu 16.04

### Client configuration
Firefox 48 / Win7 x64

**Comment by nilsteampassnet** [comment]
Thanks for reporting.
I will check this carefully.
