### ISSUE TITLE
New email address not used until logoff & logon

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1457]
Some unintuitive email behaviour: 

### Expected behaviour
A user changing their email address should immediately take effect

### Actual behaviour
New email address is not used or shown until logoff and logon.

### Steps to reproduce
1. Checkout development branch 2016-08-29, install on new db,
2. login as admin, set outgoing email server settings,
3. Press "test the Email configuration"
4. See error message (no documentation that it requires admin's email account to be set).
...
5. Let's set the email: click on admin's profile icon in upper right,
6. (The pencil icon looks like it should be a link, but it is not),
7. Click on the "email" words to change.
8. Type your email address (the text box is too small).
9. Press the checkmark icon. Press close.
10. Test the email configuration again - still unsuccessful with same error message.
11. Press profile icon again, no email address in box. Edit again, address still blank.
12. Check MySQL database via phpmyadmin - email address has been stored.

and then:

1. Logoff and logon,
2. Click profile icon, finally you can see the email address.
3. edit the email address,
4. press checkmark icon,
5. press close,
6. press profile icon again, the old email address is still there.

### Server configuration
**Operating system**:
Ubuntu Server 16.04.1 LTS Linux 4.4.0-34-generic on i686

**Web server:**
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips 

**Database:**
MySQL 5.7.13-0ubuntu0.16.04.2 - (Ubuntu)

**PHP version:**
PHP Version 7.0.8-0ubuntu0.16.04.2

**Teampass version:** 
2.1.26 (17) - development branch

**Updated from an older Teampass or fresh install:**
fresh

### Client configuration
**Web browser:**
Firefox 48

**Operating system:**
Windows 7 x64

### Suggested improvement
\includes\language\english.php (175) (and other languages)

`    'admin_email_test_configuration_tip' => 'Send a test email to the logged-in user. You must first set your email address by clicking the user profile icon.',`

**Comment by nilsteampassnet** [comment]
Thanks for your details in your report.
It helps me a lot to correct and improve.
