### ISSUE TITLE
Password complexity levels explanation

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1458]
Please explain the difference and requirements for password complexity levels. 
I mean, what is the difference between "very weak" and "weak" password? Is is documented somewhere?

**Comment by qubez** [comment]
Complexity is determined by putting the password text through a formula in the jQuery plugin simplepassmeter, which returns a value 0-100.

https://github.com/jakerella/jquerySimplePassMeter

It's pretty stupid sometimes. It has short-circuit detectors that return a low value when they see all lower case, for example. This is an example of a "very weak" password:

uixevxtpnyhfrhgcjbrqnqyogylsetuqwtxitnzcoolejahppfpwesdgopasxhov


Teampass has these score levels:

            {"minScore": 0,
                "className": "meterFail",
                "text": "<?php echo $LANG['complex_level0'];?>"
            },
            {"minScore": 25,
                "className": "meterWarn",
                "text": "<?php echo $LANG['complex_level1'];?>"
            },
            {"minScore": 50,
                "className": "meterWarn",
                "text": "<?php echo $LANG['complex_level2'];?>"
            },
            {"minScore": 60,
                "className": "meterGood",
                "text": "<?php echo $LANG['complex_level3'];?>"
            },
            {"minScore": 70,
                "className": "meterGood",
                "text": "<?php echo $LANG['complex_level4'];?>"
            },
            {"minScore": 80,
                "className": "meterExcel",
                "text": "<?php echo $LANG['complex_level5'];?>"
            },
            {"minScore": 90,
                "className": "meterExcel",
                "text": "<?php echo $LANG['complex_level6'];?>"
            }

"meterGood" is just used internally. In English, based on the complex_level.

    'complex_level0' => 'Very weak',
    'complex_level1' => 'Weak',
    'complex_level2' => 'Medium',
    'complex_level3' => 'Strong',
    'complex_level4' => 'Very strong',
    'complex_level5' => 'Heavy',
    'complex_level6' => 'Very heavy',
