### ISSUE TITLE
search issue

### ISSUE THREAD

**Issue by plcd** [nilsteampassnet/TeamPass#1459]
### Steps to reproduce
1. Logon to Admin console
2. Switch to 'Specific Actions' tab
3. Run 'Reload cache table' command
### Expected behaviour

Cache should be cleared, which would hopefully resolve the current search issue
### Actual behaviour

The gearwheel keeps running and the command does not seem to complete
### Server configuration

**Operating system**:
Win 2012R2
**Web server:**
Wamp Server 64bit 3.0.0
**Database:**
MySQL 5.7.9
**PHP version:**
7.0.0
**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
No
### Client configuration

**Browser:**
Chrome and IE
**Operating system:**
Windows 7 and 8.1
#### Firebug log

```
Error: <br>
Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`tags`,`id_tree`,`perso`,`restricted_to`,`login`,`folder`,`author`,`renewal_period`,`timestamp`) VALUES ('595', 'Cisco - Cisco ID/password for Cisco Service Contract Center', 'Cisco contracts<br /><br />http://www.cisco.com/en/US/customer/services/networking_solutions_products_genericcontent0900aecd806a0c7f.html', '', '13', '0', '', 'johndoe', 'Servicedesk » Web Admin Accounts', '4', '0', '1471008095')<br>
```

**Comment by nilsteampassnet** [comment]
What package do you have?

The query error you show is missing one field.
But the code in the file is correct. So I think either you have an old package or you didn't correctly overwrite existing file.

**Comment by plcd** [comment]
Thanks Nils! We are using package TeamPass-2.1.26.3. How can we fix it?

**Comment by nilsteampassnet** [comment]
I suggest to upgrade.
You should use development branch.
I will perform a package tomorrow evening from it.
