### ISSUE TITLE
error upgrade to 2.1.26.17

### ISSUE THREAD

**Issue by p0larf0x** [nilsteampassnet/TeamPass#1460]
### Steps to reproduce
1. upgrade from 2.1.23 to 2.1.26.17
2. login in teampass
3. get error
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**: CentOS Linux release 7.2.1511 (Core) 3.10.0-327.28.3.el7.x86_64
**Web server:**httpd-2.4.6-40.el7.centos.x86_64
**Database:**mysql-community-server-5.6.32-2.el7.x86_64
**PHP version:**php-5.6.24-1.el7.remi.x86_64

**Teampass version:** 2.1.26.17

**Updated from an older Teampass or fresh install:**2.1.23
### Client configuration

**Browser:**firefox 48.0

**Operating system:**Fedora 24
#### Web server error log

```
[Wed Aug 31 17:35:18.422723 2016] [:error] [pid 2834] [client 10.64.3.10:52486] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php?page=items
[Wed Aug 31 17:35:18.422776 2016] [:error] [pid 2834] [client 10.64.3.10:52486] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php?page=items
[Wed Aug 31 17:35:18.698397 2016] [:error] [pid 2841] [client 10.64.3.10:52488] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php?page=items
[Wed Aug 31 17:35:18.698463 2016] [:error] [pid 2841] [client 10.64.3.10:52488] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php?page=items
[Wed Aug 31 17:37:43.879530 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php
[Wed Aug 31 17:37:43.879584 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://teampass.office.saratov.emk/index.php
[Wed Aug 31 17:37:44.492773 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[Wed Aug 31 17:37:44.492826 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[Wed Aug 31 17:37:45.643829 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[Wed Aug 31 17:37:45.643897 2016] [:error] [pid 2832] [client 10.64.3.10:52612] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[Wed Aug 31 17:39:42.236538 2016] [:error] [pid 2843] [client 10.64.3.10:52632] PHP Notice:  Undefined variable: link in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618
[Wed Aug 31 17:39:42.236589 2016] [:error] [pid 2843] [client 10.64.3.10:52632] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /data/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618

```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Error: Unknown column 'can_manage_all_users' in 'field list'<br>
Query: SELECT admin, gestionnaire, can_manage_all_users, groupes_visibles, groupes_interdits, fonction_id
 FROM teampass_users WHERE id=2<br>
```

**Comment by nilsteampassnet** [comment]
Did you run /install/upgrade.php?

Your users table is missing a field added.

**Comment by p0larf0x** [comment]
thanks for the tip! automatically start the install.php
when launched upgrade.php the update was

But I receive an error after updating - "Error encryption of the password!"
![error ecriptions 2](https://cloud.githubusercontent.com/assets/12912570/18161900/fed75064-7044-11e6-88fc-4eb5a50a53dc.png)
![error ecriptions 1](https://cloud.githubusercontent.com/assets/12912570/18161902/feda2fc8-7044-11e6-88e3-b98a3dd4d7a8.png)
![error ecriptions 3](https://cloud.githubusercontent.com/assets/12912570/18161901/fed98aaa-7044-11e6-8aa8-3151f6475435.png)

file /data/www/html/teampass/includes/sk.php exist
SALT not changed

**Comment by jeanorwin** [comment]
Did you try to replace the Meekrodb-Files with the newest verison of MeekroDB (http://meekro.com/download_page.php)?

**Comment by djatwork** [comment]
I have the same "error encyrption password" issue after an upgrade from 2.1.23 to 2.1.26

i tried different versions between 2.1.23 and the actual master... everytime the same issue.  
not salt change!!

upgrade.php ok
login ok
database connection ok
displaying the items ok,
BUT no passwords
NO error in Firebug
NO error entries in the apache log!

The only problem i see, is that my saltkey has only a lenght of 7. could that be a problem. i tried already to change the salt with now luck, everytime after a change i can´t login any more an the salt in the sk.php was misformed...

i tried also to replace the meekrodb, no luck

**Comment by nilsteampassnet** [comment]
During upgrade, did you see the step during which the new encryption is performed on all items?
Could you provide me an access to your server for investigation?

**Comment by djatwork** [comment]
hi nils
yeah only green thumbs
- upgrade_run_db_original.php - Loop #1
- upgrade_run_2.1.26.php - Loop #1 
- upgrade_run_encryption_pwd.php  (40 loops)
- upgrade_run_encryption_suggestions.php
- upgrade_run_final.php 

How should i contact you, with the credentials? What should database should i pepare for you? the old database 2.1.23  or the not working version after the upgrade?

**Comment by nilsteampassnet** [comment]
By email please (nils@teampass.net).
With the old database.

**Comment by tiruser** [comment]
Are there new insights to this error?
i have the same Problem after clicking on the eye for showing the Password.

**Comment by djatwork** [comment]
Pls check your length of the main saltkey! It should be 16.

Mine was too short (15), so the upgrade failed. I patched an old version to decrypt the passwords with the short key and reencrypt with a correct key. Since that the error is gone and the update worked fine!

**Comment by tiruser** [comment]
thanks, now it works for me too.
thank you very much for this info.

**Comment by bhakimi** [comment]
i did a upgrade from 2.1.23 to 2.1.26.17 and i have the same error, the column was never added, my salt key is bigger then 16 charatcers, any suggestion how to fix this?
