### ISSUE TITLE
ldap_object_class multiple times in misc DB table

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1461]
With latest version I have run upgrade script a couple of times and each time a new ldap_object_class row is added to misc table.

Please correct the SQL in upgrade script for checking if the row exists.

`// add new setting - ldap_object_class
$tmp = mysqli_fetch_row(mysqli_query($dbTmp, "SELECT COUNT(*) FROM '".$_SESSION['tbl_prefix']."misc' WHERE intitule = 'admin' AND valeur = 'ldap_object_class'"));
if ($tmp[0] == 0 || empty($tmp[0])) {
    mysqli_query($dbTmp, "INSERT INTO '".$_SESSION['tbl_prefix']."misc' VALUES ('admin', 'ldap_object_class', '0')");
}`

This should be:

`WHERE type = 'admin' AND intitule = 'ldap_object_class'`

**Comment by qubez** [comment]
Confirmed. This is an annoyance. Without uniqueness, one cannot set a primary key or edit the table.

**Comment by qubez** [comment]
#1469 to fix this.
