### ISSUE TITLE
Password not show

### ISSUE THREAD

**Issue by iSheol** [nilsteampassnet/TeamPass#1466]
Hi Nils,

My TS disappeared inexplicably folder / opt, but I have a current backup of the bunch.
Reconfigured and restarurei the bank, I succeeded, but the passwords are not shown.

you have no idea whats is?

version 2.1.23.4
ubuntu server 14.04

**Comment by qubez** [comment]
Did you also input the original saltkey used to encrypt all items? The salt key is the "password" used for all password items in the database. It is stored in the sk.php file, which you are instructed during installation to save in a different folder than the www folder.

You can also use a database browser such as phpmyadmin to look at the SQL server teampass database, and see that the _items table contains all the passwords you expect to be there.

**Comment by iSheol** [comment]
The other administrator of this server did not leave any documentation.
Neither the key in another folder. I had looked at the table items, but they are all encrypted.

> Did you also input the original saltkey used to encrypt all items? The salt key is the "password" used for all password items in the database. It is stored in the sk.php file, which you are instructed during installation to save in a different folder than the www folder.

> You can also use a database browser such as phpmyadmin to look at the SQL server teampass database, and see that the _items table contains all the passwords you expect to be there.

**Comment by iSheol** [comment]
Done, i have the saltkey. Ty for help.

Cya!
