### ISSUE TITLE
Issue in adding a folder with sql command

### ISSUE THREAD

**Issue by ThomasVaxelaire** [nilsteampassnet/TeamPass#1470]
### Steps to reproduce
1. Connect to DB
2. Add folder with sql request :
 INSERT INTO teampass_nested_tree VALUES ($newid,40,'$Sclientname',0,0,3,0,0,0,0)
3. folder password complexity = not defined

### Expected behaviour
I think it should create a folder with no password complexity defined but it should allow me to create or edit passwords.

### Actual behaviour
Password complexity is not defined and it isn't allowing me to create any password manually in the folder. It is telling me that the password complexity is not compliant.
Adding a password with the API is working.

I think there is a table where the password complexity requirement is alterable but i can not find it.

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:**Maria DB

**PHP version:** 

**Teampass version:** 2.1.24

**Updated from an older Teampass or fresh install:** fresh

### Client configuration
**Browser:** Chrome or firefox

**Operating system:** W7

**Comment by qubez** [comment]
You also need to add

INSERT INTO teampass_misc VALUES ('complex', $newid, 25)

The 25 is the password strength, documented #1458

You also need to compute the nested tree logic values nested_tree_nleft and nested_tree_nright when adding, which is best done using the nested tree code in TeamPass. Just like the best way to add a folder is through teampass.

**Comment by nilsteampassnet** [comment]
I dont recommend what you are doing. 
As said previously, the creation of a folder doesn't consist only in adding an entry in neested_tree table.  Several other info need to be computer. 
Why not to use teampass UI or the API ?

**Comment by ThomasVaxelaire** [comment]
Hello,

Thanks for your help !

@qubez 
I tried this step and my problem seems to be resolved

@nilsteampassnet
I am currently trying to automatize this step and create several passwords at the same time.
I checked the documentation http://teampass.net/2014-05-18-teampass-api , but I'm not very comfortable with API and I wasn't able to find a way to add a folder with the API like I do for password.

Since it is not very recommended to create a folder by adding a line in the databate. Do you have an example to do it with the API ?

**Comment by nilsteampassnet** [comment]
Currently API doesn't permit to add a folder.

It is something that could be added.

**Comment by ThomasVaxelaire** [comment]
Thanks a lot :)
