### ISSUE TITLE
Improvement: "folder access" and "role" settings when adding new user

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1472]
### Steps to reproduce
1. Add a new user,
2. Fill out all options in dialog box,
3. User gets an email with their login,
4. User still can access nothing,
### Expected behaviour

After a manager completes all options when making a new user, the user should have the desired access.
### Actual behaviour

_Folder access_ and _role membership_ configuration is not asked during account creation, making these easy for a manager to forget.

The "edit user" requirement after "new user" is illogical. 

It is cumbersome to train managers/HR to edit the user account again, and tedious to manually choose folder access for every member of a department that will have the same rights.
### Feature recommendations
1. Within create user dialog, the same folder and role options should be present as in edit user,
2. Better, a step 2 and step 3 screen shows checkboxes for roles and folders to ensure the manager views and selects correct permissions.
3. Even better, a _add multiple user_ dialog would allow you to add usernames like you add email addresses to an email (press + next the the username field to add one more). The options selected would apply to all users.
4. Finally, checkboxes in the user list, and an _edit multiple user_ feature. This could be very useful, for example, add a new folder, and then give access to 50 users.
5. Instead of (4), a "copy rights" option could copy one user's folder and role access to multiple other users.

**Teampass version:** 
Current

**Notes**
After finishing other improvements and bugs, I'll see if I've the skills in programming and in French to figure out how this is currently done and if the edit options can easily be added to the new user options.

**Comment by nilsteampassnet** [comment]
It is indeed a feature I not recently retested.
The source code is ready for this using case "reencrypt_personal_pwd_start".

I need to call it in this specific case.

**Comment by nilsteampassnet** [comment]
Implemented in 2.1.27
