### ISSUE TITLE
User loses all passwords after change password with password as salt

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1473]
### Steps to reproduce

As admin:
1. _Enable personal folder feature_
2. Select _Use the login password as SALTkey_
3. Specific Actions -> Actualize Personal Folders

As user:
1. Create items with passwords in personal folder
2. Change user account password
3. logoff and logon
### Expected behaviour

This bug was expected.

User should be blocked from changing password, or get a strong warning, when Select _Use the login password as SALTkey_ is enabled. Best would be to re-encrypt all user passwords with new password salt.

User does not have technical knowledge that their password is the salt if these options are chosen by admin.

Admin can also inadvertently reset password without warning of implications. If the user has forgotten password, there is no solution, though.
### Actual behaviour

User loses all saved passwords
### Bug 2

New user password not used as salt until logoff and logon. Password reset should force logoff.
### Bug 3

Undecryptable passwords from bad salt keys should decode to warning and reason, not just be blank.
### Server configuration

All

**Teampass version:** 
2.1.26 (development 2016-09-04)

**Updated from an older Teampass or fresh install:**
Fresh Install

**Comment by nilsteampassnet** [comment]
It is indeed a feature I not recently retested.
The source code is ready for this using case "reencrypt_personal_pwd_start".

I need to call it in this specific case.

**Comment by nilsteampassnet** [comment]
I will disable this feature for 2.1.26
and make a complete refactor on 2.127

**Comment by nilsteampassnet** [comment]
Is corrected in 2.1.27
