### ISSUE TITLE
Cant create a item without a password

### ISSUE THREAD

**Issue by jeanmassumi** [nilsteampassnet/TeamPass#1474]
Hello,

When i tried to create or edit a new item without a password returns a message saying that "A password is mandatory!"

It will have some way to resolve this?

Thanks =D

**Comment by nilsteampassnet** [comment]
It is the normal behavior of the tool.
Its aim is to store a password so it requires a password ;)

**Comment by qubez** [comment]
Maybe worth adding an admin setting to disable the requirement. I've made many fake passwords for storing PDFs or notes.

**Comment by nilsteampassnet** [comment]
Implemented in 2.1.27
