### ISSUE TITLE
The next ERROR occurred: '/includes is not a Directory!' Please correct and relaunch. 

### ISSUE THREAD

**Issue by mohammad-69** [nilsteampassnet/TeamPass#1478]
### Actual behaviour

on step 4 when i leave Absolute path to SaltKey  empty i get the above error and when i give it a valid path i also get this error message.
### Server configuration

**Operating system**: virtual centos 6.7

**Web server:  kloxo administration panel

**Database: mysql

**PHP version 5.6.25

**Teampass version = 2.1.26.17
### Client configuration

**Browser = firefox

**Operating system =  ubuntu

**Comment by qubez** [comment]
This is likely a file or directory permission problem.

When you upload new files, they have owner set to your username, and permissions set to your default mask. This is not appropriate for web server files, and Apache needs write access to the directories to proceed with TeamPass install and write access to delete the install folder after finished.

I just installed CentOS 6.7, upgraded PHP to 5.6.25-1 with the required php yum packages. Was able to complete installation successfully after configuring php.ini, _mysql_update_ to fix distro root mysql permissions, and other server minutae.

Attached is a script I use for quickly recursively resetting permissions when doing an install, modified for CentOS Apache. Save this as resetpermissions.sh:

```
_dir="${1:-.}"
_fperm="0664"
_dperm="0775"
_ugperm="apache:apache"
_chmod="/bin/chmod"
_chown="/bin/chown"
_find="/usr/bin/find"
_xargs="/usr/bin/xargs"
 
echo "Change the file permission for \"$_dir\""
read -p "Your current dir is ${PWD}. Are you sure (y / n) ?" ans
if [ "$ans" == "y" ]
then
	echo "Changing file ownership to $_ugperm for $_dir..."
	$_chown -R "${_ugperm}" "$_dir"
 
	echo "Setting $_fperm permission for $_dir directory...."
	$_chmod -R "${_fperm}" "$_dir"
 
	echo "Setting $_dperm permission for $_dir directory...."
	$_find "$_dir" -type d -print0 | $_xargs -0 -I {} $_chmod $_dperm {}
fi
```
to actually run the file, SSH in, `chmod 775 resetpermissions.sh` to make it executable, and then `./resetpermissions.sh` to run.

Permissions also need to be given to any directories outside the web directory, such as storing your config file at /var/teampass.

**Comment by mohammad-69** [comment]
Thanks for responding but I've tried everything you said and even the bash script. but still I get the same error message and have no idea what to do. 
I've attached my project root file and directory permissions for you :
![342432](https://cloud.githubusercontent.com/assets/6370182/18407907/6520f024-7733-11e6-8a81-38a81385c255.png)

**Comment by qubez** [comment]
Do you have root on the server, or is this a shared host? I see the folder is /media/local-server/home/teampass, which is a strange location; looks like your personal home folder, not a web server directory.

It doesn't seem like the script ran correctly. I don't see resetpermissions.sh in your directory where it should have been placed before it was run.

This is what it should look like:
```
[root@cent html]# ./resetpermissions-cent.sh
Change the file permission for "."
Your current dir is /var/www/html. Are you sure (y / n) ?y
Changing file ownership to apache:apache for ....
Setting 0664 permission for . directory....
Setting 0775 permission for . directory....
[root@cent html]# ls -la
total 1080
drwxrwxr-x.  9 apache apache   4096 Sep  8 03:06 .
drwxrwxr-x.  8 root   root     4096 Sep  8 10:19 ..
-rw-rw-r--.  1 apache apache   3126 Sep  8 02:51 admin.php
-rw-rw-r--.  1 apache apache  16674 Sep  8 02:51 admin.settings_api.php
-rw-rw-r--.  1 apache apache   9822 Sep  8 02:51 admin.settings_categories.php
-rw-rw-r--.  1 apache apache  15199 Sep  8 02:51 admin.settings_duo.php
-rw-rw-r--.  1 apache apache  34557 Sep  8 02:51 admin.settings.load.php
-rw-rw-r--.  1 apache apache 113404 Sep  8 02:51 admin.settings.php
-rw-rw-r--.  1 apache apache    349 Sep  8 02:51 apache-default.conf
drwxrwxr-x.  2 apache apache   4096 Sep  8 02:51 api
drwxrwxr-x.  2 apache apache   4096 Sep  8 02:51 backups
-rw-rw-r--.  1 apache apache  23368 Sep  8 02:51 changelog.md
-rw-rw-r--.  1 apache apache    933 Sep  8 02:51 composer.json
-rw-rw-r--.  1 apache apache    376 Sep  8 02:51 docker-compose.yml
-rw-rw-r--.  1 apache apache    750 Sep  8 02:51 Dockerfile
-rw-rw-r--.  1 apache apache   2233 Sep  8 02:51 duo.load.php
```


Your permission are incorrect. In your screenshot, the owner of the file is teampass, and the group is apache. The owner has permissions rw- (read/write) but the group only has r-- (read only) permission - the middle three permissions on each file. This prevents group apache from changing files.

To give members of the group full access to all files, run this command from the web server home directory: `chmod -R g=rwx *`

**Comment by mohammad-69** [comment]
I've tried all way possible to change permissions but still no success : 
```

[root@ordme teampass]# ./resetperms.sh
Change the file permission for "."
Your current dir is /home/teampass. Are you sure (y / n) ?y
Changing file ownership to apache:apache for ....
Setting 0664 permission for . directory....
Setting 0775 permission for . directory....
[root@ordme teampass]# cd teampass.kb/
[root@ordme teampass.kb]# ls -la
total 9624
drwxrwxr-x 10 apache apache    4096 Sep 10 09:13 .
drwxrwxr-x  6 apache apache    4096 Sep 10 10:53 ..
-rw-rw-r--  1 apache apache    3051 Aug 21 13:16 admin.php
-rw-rw-r--  1 apache apache   14039 Aug 21 13:16 admin.settings_api.php
-rw-rw-r--  1 apache apache    9174 Aug 21 13:16 admin.settings_categories.php
-rw-rw-r--  1 apache apache   14459 Aug 21 13:16 admin.settings_duo.php
-rw-rw-r--  1 apache apache   33690 Aug 21 13:16 admin.settings.load.php
-rw-rw-r--  1 apache apache  109027 Aug 21 13:16 admin.settings.php
-rw-rw-r--  1 apache apache     333 Aug 21 13:16 apache-default.conf
drwxrwxr-x  2 apache apache    4096 Aug 21 13:16 api
drwxrwxr-x  2 apache apache    4096 Aug 21 13:16 backups
-rw-rw-r--  1 apache apache   22364 Aug 21 13:16 changelog.md
-rw-rw-r--  1 apache apache     904 Aug 21 13:16 composer.json
-rw-rw-r--  1 apache apache     356 Aug 21 13:16 docker-compose.yml
-rw-rw-r--  1 apache apache     728 Aug 21 13:16 Dockerfile
-rw-rw-r--  1 apache apache    2150 Aug 21 13:16 duo.load.php
-rw-rw-r--  1 apache apache    3357 Aug 21 13:16 error.php
-rw-rw-r--  1 apache apache   99678 Aug 21 13:16 favico.ico
-rw-rw-r--  1 apache apache    2874 Aug 21 13:16 favorites.php
drwxrwxr-x  2 apache apache    4096 Aug 21 13:16 files
-rw-rw-r--  1 apache apache    6887 Aug 21 13:16 find.load.php
-rw-rw-r--  1 apache apache    3297 Aug 21 13:16 find.php
-rw-rw-r--  1 apache apache   12627 Aug 21 13:16 folders.load.php
-rw-rw-r--  1 apache apache    8058 Aug 21 13:16 folders.php
drwxrwxr-x  2 apache apache    4096 Aug 21 13:16 .github
drwxrwxr-x 10 apache apache    4096 Sep  8 11:45 includes
-rw-rw-r--  1 apache apache   39340 Aug 21 13:16 index.php
drwxrwxr-x  5 apache apache    4096 Aug 21 13:16 install
-rw-rw-r--  1 apache apache    9194 Aug 21 13:16 items.export.php
-rw-rw-r--  1 apache apache   18918 Aug 21 13:16 items.import.php
-rw-rw-r--  1 apache apache  162213 Aug 21 13:16 items.load.php
-rw-rw-r--  1 apache apache   10005 Aug 21 13:16 items.offline.php
-rw-rw-r--  1 apache apache   52022 Aug 21 13:16 items.php
-rw-rw-r--  1 apache apache    7052 Aug 21 13:16 kb.load.php
-rw-rw-r--  1 apache apache    5857 Aug 21 13:16 kb.php
```

**Comment by qubez** [comment]
The permissions you show above are now correct, but the directory is strange. Normally you would have the pages at /var/www/html or another virtual host directory in /var/www. If you have user-hosted files, the user web directory would usually be home/USERNAME/public_html.

Is this your own server, or a managed or shared host? If you do not have root on the server, you may not be able to overcome particular restrictions placed by the ISP. You may need all files to be owned by your user account. You may not be able to correctly install extensions or change PHP values as required by Teampass.
