### ISSUE TITLE
After changing Url page need reload to view the new value

### ISSUE THREAD

**Issue by giannakopoulosj** [nilsteampassnet/TeamPass#1479]
### Steps to reproduce
1. Login to Teampass
2. Modify a url of an item
3. 

### Expected behaviour
When changing the url of an item then the view should be automaticaly refreshed.

### Actual behaviour
Need manual refresh of the page in order the change to be able to view.

**Teampass version:** Latest Master branch

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7

**Comment by nilsteampassnet** [comment]
Please always use the lastest RELEASE (or development branch if you are doing a fresh install).

Nevertheless, not sure to have understood the point, but normally the field URL of an item is automatically refreshed with new value after "SAVE" button is clicked (without any page refresh).
![image](https://cloud.githubusercontent.com/assets/1197546/18409299/d87bca84-7743-11e6-9c8f-03fec54a881d.png)

**Comment by giannakopoulosj** [comment]
Thank you for the responce Nil.
I rechecked after the Firefox upgrade. 

1. Initialy my probelm was the one  your also described.
2. Currentrly this problem has been fixed.

Seems that old versions of browsers having unexpected behaviors.
I should close this case if its ok.
