### ISSUE TITLE
Link passwords into Folder

### ISSUE THREAD

**Issue by gerbsen** [nilsteampassnet/TeamPass#1480]
Hello,
I'm trying to implement a "need to know" password policy in our company. So what I've done so far is to add all passwords for the Admin user. My plan is know to generate personal folders for each employee and copy the passwords they need to know in their personal folder. But of course since I would copy them, I would have to reshare/copy the password in case it is changed. So is it possible to link items into folders? And in case it's not, are there any alternative approaches?
Cheers,
Daniel

**Comment by nilsteampassnet** [comment]
Hi Daniel,

I would not suggest to have this approach. Indeed this requiers you to copy items from folders to folders, and an item update will become a nightmare.
And above this, as a user, you cannot interact with items in a personal folder of other users (as the saltkey is specific to each user).

I would suggest to organize in the other way. Meaning that you need to organize your items by "Categories" (which would be Folders) and access groups (which would be Roles).
Doing this, you just need to associate a User to as many Roles he can see.

And for specific Items, you can enable options "Enable Restricted To functionality on Items" and "Allow to restrict items to Users and Roles". Those 2 options will permit you to select a set of Users and/or Groups that will be allowed to access a specific Item in a Folder (by passing existing access rights on the current folder).

By doing this, you don't have to do any item copy and it will be really more clear and maintenable.

I really suggest to take time on the strategy to organize your Folders and Roles/Groups to permit an optimized usage after.

**Comment by gerbsen** [comment]
thanks nils! not that familiar with teampass yet but I will try your suggestions!
