### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1481]
In development branch, you have changed api/functions.php, but on line 440 you have a missing comma at the end.

`"SELECT id, label, login, pw, pw_iv, id_tree
FROM ".prefix_table("items")."
WHERE 
inactif = %i 
AND id_tree = (%s)
AND label LIKE %ss",
"0"
$category_query,
$item` 

should be:

`"SELECT id, label, login, pw, pw_iv, id_tree
FROM ".prefix_table("items")."
WHERE 
inactif = %i 
AND id_tree = (%s)
AND label LIKE %ss",
"0",
$category_query,
$item` 

Please fix, at the moment API request get all error 500.

**Comment by tehnotronic** [comment]
Also I suggest adding urldecode() in line 616 and 618, because these values come from URL and could have a space in the role name and so we must convert %20 to space.
`                $adminby = $array_user[5];
                $isreadonly = $array_user[6];
                $roles = $array_user[7];`

like:

`                $adminby = urldecode($array_user[5]);
                $isreadonly = $array_user[6];
                $roles = urldecode($array_user[7]);`

**Comment by nilsteampassnet** [comment]
Thank you.

Corrected in next commit
