### ISSUE TITLE
New Install, Can't login with default creds

### ISSUE THREAD

**Issue by kenpachi429** [nilsteampassnet/TeamPass#1483]
### Steps to reproduce
1.go to teampass server url
2.Cannot login with default admin/admin credentials
3.teampass 2.2.0

### Expected behaviour
Should login to portal

### Actual behaviour
Circle spins indefinitely

### Server configuration
CentOS 6.8:

**Apache/2.2.15:**

**mysql  Ver 15.1 Distrib 10.0.27-MariaDB:**

**PHP 5.3.3:**

**Teampass 2.2.0:** 

**Fresh install:**

### Client configuration
**Google Chrome:**

**Windows 10:**

#### Web server error log
```
PHP Parse error:  syntax error, unexpected ';' in /var/www/html/teampass/keys/sk.php on line 2
Only semicolons are after salt key and after cost line
:
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by qubez** [comment]
Where does someone get a version 2.2.0? The current version is 2.1.16.
There is not a default password, you set it when you install.

The current version of TeamPass requires PHP 5.5 or greater.

**Comment by nilsteampassnet** [comment]
Correct.

Please use [latest Release](https://github.com/nilsteampassnet/TeamPass/releases) or development branch.

Branch 2.2.0 is just a try for the futur.
