### ISSUE TITLE
2.1.26.18 Install - Finalization Step

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1488]
### Steps to reproduce
1. New installation of TeamPass Version 2.1.26.18

### Expected behaviour
New installtion of TeamPass without any problems.

### Actual behaviour
One Error at the Finalization Step in the installation process.

### Server configuration
**Operating system:** Windows Server 2012 R2

**WampServer:** 3.0.6 x64

**Web server:** Apache 2.4.23

**Database:** MySQL 5.7.14

**PHP version:** PHP 5.6.25 / 7.0.10

**Teampass version:** 2.1.26.18

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** IE 11.0.9600.18427

**Operating system:** Windows Server 2012 R2

![error](https://cloud.githubusercontent.com/assets/20316918/18428382/ede52b46-78cd-11e6-87f3-263e3521f2eb.png)

**Comment by TheKingKai** [comment]
Ok, please close this issue! With TeamPass 2.1.26.19 it all works without any problems :)

**Comment by reginfo** [comment]
Go to includes\libraries\csrfp\libs
and rename file "csrfp.config.php" to for example csrfp.config.php.save
And click Launch.

**Comment by reginfo** [comment]
You can close it by your own.
There is a button "Close Issue"
![capture1](https://cloud.githubusercontent.com/assets/4628571/18429555/be66ff16-78dc-11e6-8b77-1eff40a32482.PNG)

**Comment by nilsteampassnet** [comment]
Sorry 2.1.26.18 was including some files that should have been ignored.
That why I deleted it.
