### ISSUE TITLE
SyntaxError: Unexpected token X in JSON at position 0 / "missing table "teampass_log_items"

### ISSUE THREAD

**Issue by jeanorwin** [nilsteampassnet/TeamPass#1490]
### Steps to reproduce
1. Had to move TeamPass to a new server due to a disc problem
2. Made a DB dump and put it on the new servers DB (same DB credentials)
3. Upgraded to TeamPass 2.1.26.19 by using the upgrade guide (I stlil had the sk.php etc. from the old install)
4. Installation was only possible by using this fix: https://github.com/nilsteampassnet/TeamPass/issues/1105
5. Upon opening logging in, I only receive the error "SyntaxError: Unexpected token ¤ in JSON at position 0", regardless which file/folder I want to open. The Token is different on every login. I can not access the items.

### Expected behaviour
Display the items/folders as usual 

### Actual behaviour
alert(); with notice "SyntaxError: Unexpected token ¤ in JSON at position 0"

### Server configuration
**Operating system**:
Linux raspberrypi 4.4.13-v7 (Debian)

**Web server:**
Apache/2.4.10 (Raspbian)

**Database:**
5.5.50 MySQL

**PHP version:**
CGI/1.1 PHP Version 5.6.24-0+deb8u1

**Teampass version:** 
2.1.26.19

**Updated from an older Teampass or fresh install:**
2.1.26.X (not exactly known)

### Client configuration
Chrome

**Operating system:**
Win 7

#### Web server error log
[Mon Sep 12 10:15:58.163825 2016] [:error] [pid 3307] [client 192.168.178.55:56276] PHP Notice:  Undefined variable: link in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: http://192.168.178.14$
[Mon Sep 12 10:15:58.164130 2016] [:error] [pid 3307] [client 192.168.178.55:56276] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/teampass/includes/libraries/Database/Meekrodb/db.clas$

This error disappears if I manually update the meekdrodb.php file

#### Firebug log

Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
functions.js (Zeile 256)
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
	
return window.JSON.parse( data );

jquery.js (Zeile 550, Spalte 11)
TypeError: data is undefined
	
if (data.error == "not_allowed") {

----

Response:

Error: Table 'teampass_2_1_26.teampass_log_items' doesn't exist<br>
Query: SELECT i.id AS id, MIN(i.restricted_to) AS restricted_to, MIN(i.perso) AS perso,
                        MIN(i.label) AS label, MIN(i.description) AS description, MIN(i.pw) AS pw, MIN
(i.login) AS login,
                        MIN(i.pw_iv) AS pw_iv,
                        MIN(i.anyone_can_modify) AS anyone_can_modify, l.date AS date,
                        MIN(n.renewal_period) AS renewal_period,
                        MIN(l.action) AS log_action, l.id_user AS log_user
                        FROM teampass_items AS i
                        INNER JOIN teampass_nested_tree AS n ON (i.id_tree = n.id)
                        INNER JOIN teampass_log_items AS l ON (i.id = l.id_item)
                        WHERE (i.id_tree=54) AND (i.inactif=0) AND (l.date=(SELECT date FROM teampass_log_items
 WHERE action IN ('at_creation', 'at_modification') AND id_item=i.id ORDER BY date DESC LIMIT 1))
                        GROUP BY i.id, l.date, l.id_user, l.action
                        ORDER BY i.label ASC, l.date DESC LIMIT 0,21<br>

So I am suspecting I am missing the teampass_log_items table - I did execute the "install/upgrade" though. How can I get rid of this error?

**Comment by jeanorwin** [comment]
I just found a copy of the "old" TeamPass files. I only get an error 500 after installing. After fixing the aefsctr.php-bug I am able to see the login-page, however I receive an error 500 on sources/identify.php when trying to login with the correct credentials. If I replace the sources/identify.php with a file from a newer version, I can finally login, however, I still receive the "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" bug.

**Comment by nilsteampassnet** [comment]
How is this possible that you don't have table teampass_log_items?
It could never had worked in a previous version too.
Indeed this table is existing since years and is required.
So without it, you could have never used Teampass ... that's why I'm surprised.

As upgrade is doing some insert in this table, I don't see how you could upgrade without error. You should have this table definition in your dump.
Please check and restore it from the dump.

**Comment by jeanorwin** [comment]
Dear Nils,

thank you very much for your reply. I just double-checked my install - in fact, you're right! It looks like the spcific the table wasn't exported as the sector is damaged on the disc (I dumped the DB with phpmyadmin, "Error reading data (..) can't finde file). It is included in an older backup from june 2016. Is the log actually relevant for displaying items or is it a log only, i.e. can I use the older version from june 2016 and hope it works?

Best regards,
Michael

**Comment by nilsteampassnet** [comment]
Hi Michael

Ah great ... because here I was really surprised

Yes I think it will work, but you may loose some data related Users and/or System logs, and perhaps some folder settings if you created some new folders and/or changed their security level.

**Comment by jeanorwin** [comment]
Alright, I'll try my best - thanks again!
