### ISSUE TITLE
Untranslated label in views_logs.php

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1491]
In views_logs.php @ line 55 there is an untranslated label that should be added to poeditor:

`<input type="radio" id="radio66" name="radio" onclick="manage_div_display(\'tab6_6\'); loadTable(\'t_failed_auth\');" /><label for="radio66">Failed authentications</label>`

**Comment by qubez** [comment]
For your discovery, an element name _admin_utils_failed_auth_button_ would indicate where to find this. I think "Login Attempts" would be simpler to translate.

I found the admin tab name "2FA Options" is also hard-coded. It should be the word "Authentication". The name should be a word that users already know.

_admin_2factors_authentication_tab_ for the language files would be consistent with past use. 

LDAP options could be moved to this tab, as they are a form of authentication.

There are likely more phrases to be found in the code.

**Comment by qubez** [comment]
If new language entries are to be added, I also need a string _"Folder label can not be just a number. Please give your folder a name which includes letters."_ to be used when creating or editing folders.

Blocking number-only labels on new folders will prevent query conflicts I discovered in #1476, where personal root folders also use numbers as labels.

**Comment by nilsteampassnet** [comment]
I've added the next strings
`'failed_logins' => 'Failed Logins',
    'admin_2factor_authentication_tab' => '2FA Options',
    'error_only_numbers_in_forlder_name' => 'Folder label can not be just a number. Please give your folder a name which includes letters.',`

I will also add a check against only numeric folder title.

**Comment by qubez** [comment]
Triggered the number-only label error when testing out stuff, so it works. Thanks!
