### ISSUE TITLE
nb_items_to_display_once problem in items.queries.php

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1492]
Even after the latest commit I can see sometimes error: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` if I open password items page.

On the background firebug shows two POST request to:
https://localhost/sources/items.queries.php

With parameters: 
type=lister_items_groupe&id=19&restricted=&start=0&key=cccyyy444333nnn888777hhhjjjdddeebbbaaa111zzzxxx000&nb_items_to_display_once=-5

Note, that there is -5 at the end! Why?
In "misc" table nb_items_by_query = "auto".

And the response is:

Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-5' at line 12<br>
Query: SELECT i.id AS id, MIN(i.restricted_to) AS restricted_to, MIN(i.perso) AS perso,
                        MIN(i.label) AS label, MIN(i.description) AS description, MIN(i.pw) AS pw, MIN(i.login) AS login,
                        MIN(i.pw_iv) AS pw_iv,
                        MIN(i.anyone_can_modify) AS anyone_can_modify, l.date AS date,
                        MIN(n.renewal_period) AS renewal_period,
                        MIN(l.action) AS log_action, l.id_user AS log_user
                        FROM items AS i
                        INNER JOIN nested_tree AS n ON (i.id_tree = n.id)
                        INNER JOIN log_items AS l ON (i.id = l.id_item)
                        WHERE (i.id_tree=19) AND (i.inactif=0) AND (l.date=(SELECT date FROM log_items WHERE action IN ('at_creation', 'at_modification') AND id_item=i.id ORDER BY date DESC LIMIT 1))
                        GROUP BY i.id, l.date, l.id_user, l.action
                        ORDER BY i.label ASC, l.date DESC LIMIT 0,-5<br>

**Comment by qubez** [comment]
I can replicate the problem. The auto size is based on your viewport. If you have Firebug open, the main window is likely too small, and the auto computation returns negative numbers. I made it very small and this is the query URL:
_type=lister_items_groupe&id=6&restricted=&start=0&key=ou0uix3veej5OoShohpheet2hu3queeduyae7ui4iehei1aiqu
&nb_items_to_display_once=-12_

It seems like it should be easy to code a minimum and maximum number to restore sanity.
