### ISSUE TITLE
csrfp.config.php URL not updated when Full URL to TeamPass changes

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1494]
### Steps to reproduce
1. Log in as admin, go to the settings tab,
1. Change the site URL (done when moving or correcting site URL),
2. See that includes\libraries\csrfp\libs\csrfp.config.sample.php still has old URL.

### Expected behaviour
One setting should change all options required for the site to function. cpassman_url should be written into the CSRFP config file whenever a users changes the site URL setting.

### Actual behaviour
Users must manually edit this config file, which has an unusual file location.

### Server configuration
All

**Teampass version:** 
2.1.25 through current development

**Comment by nilsteampassnet** [comment]
Corrected.
