### ISSUE TITLE
DataTables warning table id=t_items

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1496]
Hi, we have a problem when we try, in administrator, to go in Views => Logs => Items.

See the screen in attachment please.

After that, when we click on "OK", nothing is shown in the table.

**Teampass version:** 2.1.26.17

Nothing in logs...

Another problem with the view display, nothing is shown since June 2016 in connections tab.
![teampass-pb-datatables](https://cloud.githubusercontent.com/assets/14218330/18476536/c01011ba-79ca-11e6-9009-437c4234ed3b.PNG)

Thanks in advance!

**Comment by qubez** [comment]
You have 2.1.26 (17) which was not out in June 2016, so you likely upgraded from a previous version. 
You should have run the /install/upgrade.php script after copying the latest files. Something may have changed in how data is stored or expected in the logs.

It does work correctly in 2.1.26, so something may be bad in the previously stored data preventing you from viewing items:
![tp-itemlog](https://cloud.githubusercontent.com/assets/1425520/18479270/3f6bd486-7989-11e6-8fc3-ff4df5190d53.png)


These two logs are contained in these two database tables: _prefix___log_items and _prefix__log_system. The tables refer to other database information; if you made any manual changes to the database, that may cause such problems.

You may clear the old logs in your database as a possible solution to restore function - In a database tool such as phpmyadmin, export the contents of the _log_items table_ to make a backup (or back up your whole database). Then issue the SQL query to clear logs:
`DELETE FROM teampass_log_items WHERE 1 `
(replace _teampass_ with your database prefix)

**Comment by Hellnino18** [comment]
Thanks!

I have deleted all tables log items and system. And the problem disappears. Now I need to see if all log well now.
