### ISSUE TITLE
Nothing happen when "Remove orphan items from database" is clicked

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1497]
Hi, we have a problem when we try, in administrator, to go in Settings => Specific Actions and we click on "Remove orphan items from database".

All the rest of specific action show a little green icon, except this action.

Teampass version: 2.1.26.17

Nothing in logs...

Thanks in advance.

**Comment by nilsteampassnet** [comment]
I cannot reproduce locally.

Can you please [read instruction](http://teampass.net/2014-02-09-how-to-communicate-an-error-log) to get the error using Firebug?

**Comment by Hellnino18** [comment]
Hi,

Like said in instruction, the URL is not in red. For firebug, everything is fine. But the green icon isn't present.

This is the Response body :  
[{"result":"db_backup" , "href":"sources/downloadFile.php?name=1473834828-vishurahneeSheiva4ae.sql&sub=files&file=1473834828-vishurahneeSheiva4ae.sql&type=sql&key=eikeiJ5eitooph4ingiechahCah2ceeghoWahwaith0aiyua6c&key_tmp=p8wDh9AN6CxlYALDATc7&pathIsFiles=1"}]

This is the location with parameters : 

https://this.example.com/sources/admin.queries.php?ef38b31a2d88f424229addd95ff4cd454a04cc1c79c0302367=fd5f1bec38c9eb2d7ad79d0534982ac07cc5a5166e66e533ee&option=&type=admin_action_db_backup

Thanks!
