### ISSUE TITLE
Untranslated text in 

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1500]
Another little phrase that needs translation in items.php (823):
 `The folder <b><span id="move_folder_title"></span></b> will be moved below folder:<br />`

**Comment by nilsteampassnet** [comment]
New string added:

`'folder_will_be_moved_below' => 'The folder <b><span id=\'move_folder_title\'></span></b> will be moved below folder:'`

Please use this ticket to localize untranslated string.

**Comment by qubez** [comment]
Thanks. The English for this line is good.

All other language files will need these recent language additions in their array, even if just English. Maybe that is planned with next merging to master.

English as a second language users would benefit from the new English being used in half-translated language files. Merging would take a bit of work to do manually, hopefully it is easier in poeditor management.

I registered for Poeditor to have a look. Poeditor's help does not show the backslash in:
`Single quote character ' must be escaped by using \'`
If poeditor users do not need to escape the ' character, then this message can be removed, otherwise it should be corrected.

Cheers!

**Comment by nilsteampassnet** [comment]
It is the advantage to use Poeditor.
Indeed while adding a string, it is propagated to all the languages.
When exporting the language files, it embeds all the strings and the natural language translation if exists, otherwise it takes the English one (as English is defined as "reference" language on this project).

**Comment by qubez** [comment]
I see that this is how it works.

I saw that the Japanese translation had a lot of "translations" that were just the old original English, so I cleared them to allow the new English to come through. Other languages might need the same treatment.

**Comment by tehnotronic** [comment]
If possible, please export the changes from poeditor to github. At the moment, with development code, some text and labels are missing in UI, if using other languages than english.

**Comment by nilsteampassnet** [comment]
Yes it is normal as raison operation is only done once releasing a major version in Master. 

I've never done it on development  as it takes time to perform it.
