### ISSUE TITLE
Adding user through API causes error 500 and no JSON response, if successful

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1504]
Adding user through API causes error 500 and no JSON response, if successful. 
This is beacause at api/functions.php line 703:
`logEvents('user_mngt', 'at_user_added', 'api - '.$GLOBALS['apikey'], $new_user_id);`

This logging causes error, if commented out, I can see JSON message, that user was added.

---

Also, please add urldecode() to lines 612-613, because umlaut characters in names will be otherwise messed up:
`                $name = urldecode($array_user[1]);
                $lastname = urldecode($array_user[2]);`

**Comment by nilsteampassnet** [comment]
Corrected.

Please run upgrade.php to alter one field in database
