### ISSUE TITLE
Error installing TeamPass

### ISSUE THREAD

**Issue by s3cur3n3t** [nilsteampassnet/TeamPass#1505]
### Steps to reproduce
1. Install CentOS minimal and then install mysql, httpd, php55w
2. Access http://machine_name/install/install.php 
3. Start installation

### Expected behaviour
TeamPass should know that I have my php 5.5.38 installed and proceed with installation, I checked with php -v

### Actual behaviour
Stops on server checks with following error:
[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!

### Server configuration
**Operating system**: 
CentOS 7 minimal install --> CentOS Linux release 7.2.1511 (Core)
uname -a : Linux 3.10.0-327.28.3.el7.x86_64 #1 SMP

**Web server:** 
Apache/2.4.6 (CentOS)

**Database:**
5.6.33 MySQL Community Server (GPL)

**PHP version:**
PHP 5.5.38 (cli) (built: Jul 21 2016 12:25:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Teampass version:** 
Latest stable: 2.1.26

**Updated from an older Teampass or fresh install:**
No
### Client configuration
**Browser:** Firefox latest version

**Operating system:**
CentOS 7 Minimal

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
THis message is just a indication to help solving your issue.
If you have the correct php version then the error is somewhere else.

You should have an eye on Apache error log and also to run FIrebug to get the real message back from the server.

**Comment by s3cur3n3t** [comment]
Ok I'll get into it today. And then I'll tell something. Thank you very much for your support.

**Comment by s3cur3n3t** [comment]
Hi @nilsteampassnet Nilsteampassnet,

I solve that problem! ;) 

I looked into the logs of httpd an found this: PHP Fatal error:  Call to undefined function mcrypt_get_iv_size()

Then solve it with: 

# yum install php55w-mcrypt
# service httpd restart

Thank you.
