### ISSUE TITLE
SyntaxError: Unexpected token ý in JSON at position 0

### ISSUE THREAD

**Issue by andresguisado** [nilsteampassnet/TeamPass#1506]
### Steps to reproduce
1. Create any item with the following passwords: $K%zWu3e4RhZfk=z and XC;9%+F\Qa"Cy)B’
2. It works if I replace $K%zWu3e4RhZfk=z to KzWu3e4RhZfk=z  
3. It works if I replace XC;9%+F\Qa"Cy)B’ to XC;9FQa"Cy)B’
### Expected behaviour

Teampass accepts any kind of password.
### Actual behaviour

Teampass doesn't accept above passwords. 
I have changed the complexity of the folder to different one but not luck.

When I use Chrome I got:  SyntaxError: Unexpected token ý in JSON at position 0
When I use Firefox I got:  SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
### Server configuration

**Operating system**: Centos 7

**Web server:**: Apache 2.4

**Database:**: Mysql Distrib 5.6.31

**PHP version:** PHP 5.6.22

**Teampass version:** Teampass 2.1.26

**Updated from an older Teampass or fresh install:** fresh install
### Client configuration

**Browser:** Chrome  53.0.2785. and Firefox 48.0.2

**Operating system:** Mac
#### Web server error log

```
No errors on error-logs.
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Error: <br>
Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login
`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('test', '', 'a5df6ec1df69d2084e6b56c09a6ece41'
, '75f30a6dce923f8e0bcf6a2fc23e1764', '', '', '21', '', '0', '', '0', '0', '100')<br>

Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
functions.js (line 256)
TypeError: data is undefined index.p...e=items (line 2186, col 1)
```

**Comment by nilsteampassnet** [comment]
I can't reproduce with latest release.

What release do you use? 2.1.26.XX?

**Comment by andresguisado** [comment]
2.1.26.1

Should I update to the last pre-release?

If so, Is there any doc to follow for upgrading?

Thank you very much

**Comment by nilsteampassnet** [comment]
Yes, the version you have is a pre-release.

You can follow instructions at http://teampass.net/2014-06-28-upgrade

But here, the easiest is to make a dump of DB and overwrite the existing files with the new ones.

**Comment by nilsteampassnet** [comment]
Yes, the version you have is a pre-release.

You can follow instructions at http://teampass.net/2014-06-28-upgrade

But here, the easiest is to make a dump of DB and overwrite the existing files with the new ones.

**Comment by andresguisado** [comment]
All 2.1.26.XX are pre-release. 

Which one should I get? Last one?
Should I install a release instead of pre-release?

On the another hand, I saw a teampass v2.1.15 with buttons and a  menu more friendly than v2.1.26.XX, 
Was it changed at v2.1.26.XX?  Could I customize that?

**Comment by nilsteampassnet** [comment]
Yes only pre-release until now.
Final 2.1.26 will be release in October.

> Was it changed at v2.1.26.XX?
There is a changelog with all changes.

> Could I customize that?
Yes you can but you will loose your changes when upgrading.

**Comment by andresguisado** [comment]
Do you know what day of October is going to be released v2.1.26?

I would like to install it instead of update to another pre-release of v2.1.16.

Thanks.

**Comment by andresguisado** [comment]
I have installed Teampass v2.1.26 Final Version and it worked!

I don't get this issue anymore.

Thanks!

**Comment by andresguisado** [comment]
I was using "posix-search" instead of Active Directory so you forget above details despite thisI am getting same load looping but without any error this time when I tried to log in with ldap user which doesn't exist in Teampass DB..:-(
