### ISSUE TITLE
Unauthenticated SMTP broken

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1509]
Before the recent mail fix, SMTP authentication did not work. I had to set up a local mail server without authentication. Now, _unauthenticated_ email doesn't work...

Upgraded 2.1.26 (16) to development branch on production server.
### Steps to reproduce
1. Have a local SMTP mail server (mail forwarder)
2. Configure teampass to use it:
3. Working OK on 2.1.26 (16),
4. install development branch, run upgrade script,
5. Get error as displayed, with settings previously working (no amount of reconfiguring fixes)

![teampass-email-unauth-prob](https://cloud.githubusercontent.com/assets/1425520/18655391/52987f78-7e9d-11e6-828e-d0b9a3040815.png)
(I just typed localdomain in here because there was company info previously; the correct localhost or 127.0.0.1 doesn't work either)
1. No system emails are sent either.
### Expected behaviour

Email should be sent.
### Actual behaviour

Error message:  SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
### Server configuration

**Operating system**:
Ubuntu 16.04.2 32 bit

**Web server:**
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-fips

**Database:**
MySQL 5.7.13-0ubuntu0.16.04.2 - (Ubuntu) 

**PHP version:**
PHP Version 7.0.8-0ubuntu0.16.04.2

**Teampass version:**
Teampass development branch

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26 (16) w upgrade script
### Client configuration

**Browser:**
Firefox 48 32 Bit
**Operating system:**
Windows 7 x64

**Comment by pitisk** [comment]
i have same problem...
edit $teampassdir/includes/libraries/Email/Phpmailer/class.smtp.php
add to line 249 
`if(count($options)==0){
        $options["ssl"]=array("verify_peer"=>false,"verify_peer_name"=>false,"allow_self_signed"=>true);
        }`

and now working for me.
