### ISSUE TITLE
Long folder names break UI

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1512]
After giving a folder long name, most browsers don't display item details inside that folder.
Safari displayed everything correctly on Mac, but on Windows computer all IE, FF and Chrome didn't display. So it might have something to do with JS rendering?
There are no errors in firebug or server logs. Using latest 2.1.26 development repo.

This is a normal working folder:
![screenshot_2](https://cloud.githubusercontent.com/assets/6266189/18689463/e469d1e6-7f91-11e6-9d26-a4cb9c1ac8fe.png)

This is a folder with long name. Note, that the item inside is selected, but nothing is displayed below: 
![screenshot_3](https://cloud.githubusercontent.com/assets/6266189/18689464/e46e41cc-7f91-11e6-98d6-ed3c76bfd86e.png)

Solution was to shorten the folder name.

**Comment by tehnotronic** [comment]
Sorry, something happened with the screenshots before, these are correct: 

![screenshot_3](https://cloud.githubusercontent.com/assets/6266189/18689742/5de922b4-7f93-11e6-9fb2-0b9f83ef9fad.jpg)

And the one with problem:
![screenshot_2](https://cloud.githubusercontent.com/assets/6266189/18689743/5ded7ada-7f93-11e6-9e76-b98c7027a44d.jpg)

**Comment by qubez** [comment]
You mean a long "description"? The contents within [brackets] is the item description.

The type of that database field is "text". It should hold 65535 bytes, but that may be as few as 16000 unicode characters. You probably aren't exceeding this limit...?

Do you ever see a scroll bar on the bottom white detail area? If I have a long description or more custom fields, then Firefox shows a scroll bar to the right of the details.

I found that the description on the top item display completely disappeared if it had characters such as (:) colon in it, and maybe other characters. I did not yet see the effect where the bottom panel is just gone.

Perhaps we can attempt to find exactly when the bottom panel completely disappears.

**Comment by tehnotronic** [comment]
I meant folder name, not item name or item description - issue is with
folder names.
You can see it on the last picture, left side the folder name is between
20-30 alfabet characters and there is a scrollbar on the bottom left side.
So nothing extreme, no special symbols or extreme long names.

2016-09-21 16:40 GMT+03:00 qubez <notifications@github.com>:

**Comment by nilsteampassnet** [comment]
OK I see what you mean.

![image](https://cloud.githubusercontent.com/assets/1197546/18724106/765aba9e-803b-11e6-8e73-46d2df794ec9.png)

I will try fix this ... thanks for reporting
