### ISSUE TITLE
Languages should not be indicated by country flags

### ISSUE THREAD

**Issue by qubez** [nilsteampassnet/TeamPass#1514]
Just putting this here for comment, the improvements I was thinking of coding would take a bit of work.
- The flag images take many HTTP requests to load on every page, quick fix is to remove them.
- Removing flags fixes the basic problem --- **country_flag != language**.

I can be in Canada and want French. I can be in USA and want Spanish. I may be in Australia and want UK English. Indians may want Kannada, Hindi, Tamil...
- The language flag is a user setting. This setting should be moved into the "user profile" dialog. The user will only set it once, it should not persist in the menu.
- Languages should be displayed in a list, as first the spelling in native language, then the system or user's language's translation. For example, with default language set to French, we should show:

[en]English - anglais
[fr]français - français
[de]Deutsch - allemand 
[ja]日本語 - japonais
...

This means Teampass has the native language representation hard-coded, and gets the French translation from the language file. Or to allow for better translations, coded in English, but get both displayed languages from language files (but we don't want to hit 20+ language files for this function).

**Comment by nilsteampassnet** [comment]
Hi @qubez 

Good idea. It can be easily done ;)

**Comment by qubez** [comment]
After digging into the language settings, and realizing I'd want to remove all the manual styling throughout the code (and then need to re-style), I got a bit distracted...:
![screenshot-style](https://cloud.githubusercontent.com/assets/1425520/18915013/4f3d1bb0-8544-11e6-9836-8ceb319f4dd2.png)
Somewhat responsive css now; hopefully this can still merge when finished...

**Comment by reginfo** [comment]
Is it new design coming?

**Comment by nilsteampassnet** [comment]
@qubez, can you please contact me

**Comment by qubez** [comment]
@nilsteampassnet sent a message via teampass.net contact form.
Email qubez@comcast.net

**Comment by nilsteampassnet** [comment]
Language selection is now done in the Profile dialogbox.
