### ISSUE TITLE
Cannot add new users if similar user name exists

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1515]
I added user "maria" and now I cannot add user "mari" or "mar", it shows, that the user already exists, but actually not.

I tired to debug and it seems, that the issue is in
https://github.com/nilsteampassnet/TeamPass/blob/development/sources/users.queries.php#L151 
There is a check if user exists with WHERE login LIKE %ss

**Comment by nilsteampassnet** [comment]
Correct. The query is badly done. It should be = %s instead of LIKE %ss. 
I will correct this.
