### ISSUE TITLE
Teampass/LDAP

### ISSUE THREAD

**Issue by kenpachi429** [nilsteampassnet/TeamPass#1516]
### Steps to reproduce

1.Setup Teampass 2.1.26
2. Configure LDAP
3. activate LDAP features in teampass
### Expected behaviour

Log into teampass with ldap user
### Actual behaviour

"Login credentials do not correspond" message
### Server configuration

CentOS 7:

2.2.15:**

Ver 15.1 Distrib 10.0.27-MariaDB:**

PHP 5.6.26:**

**Teampass version:** 

Updated from 2.1.20 to 2.1.26:**
### Client configuration

Chrome:**

Windows 10:**
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by F0ob4r** [comment]
It looks like the adLDAP library has been exchanged but sources/identify.php has not been updated for me it works with following changes:

--- identify.php.old    2016-09-28 09:08:36.672322593 +0200
+++ identify.php        2016-09-28 09:09:25.808320762 +0200
@@ -184,7 +184,9 @@ function identifyUser($sentData)
     /* LDAP connection */
     if ($debugLdap == 1) {
         // create temp file
-        $dbgLdap = fopen($_SESSION['settings']['path_to_files_folder']."/ldap.debug.txt", "w");
+
+
+       $dbgLdap = fopen($_SESSION['settings']['path_to_files_folder']."/ldap.debug.txt", "w");
         fputs(
             $dbgLdap,
             "Get all LDAP params : \n" .
@@ -303,9 +305,8 @@ function identifyUser($sentData)
                     'use_tls' => $_SESSION['settings']['ldap_tls']
                 )
             );
-
             if ($debugLdap == 1) {
-                fputs($dbgLdap, "Create new adldap object : ".$adldap->get_last_error()."\n\n\n"); //Debug
+            //    fputs($dbgLdap, "Create new adldap object : ".$adldap->getLastError()."\n\n\n"); //Debug
             }

             // openLDAP expects an attribute=value pair
@@ -334,7 +335,7 @@ function identifyUser($sentData)
             if ($debugLdap == 1) {
                 fputs(
                     $dbgLdap,
-                    "After authenticate : ".$adldap->get_last_error()."\n\n\n" .
+                    "After authenticate : ".$adldap->getLastError()."\n\n\n" .
                     "ldap status : ".$ldapConnection."\n\n\n"
                 ); //Debug
             }
@@ -392,7 +393,7 @@ function identifyUser($sentData)
         $data['pw'] = $pwdlib->createPasswordHash($passwordClear);  // create passwordhash

         // get user info from LDAP
-        $user_info_from_ad = $adldap->user_info($auth_username, array("mail", "givenname", "sn"));
+        $user_info_from_ad = $adldap->user()->info($auth_username, array("mail", "givenname", "sn"));

         DB::insert(
             prefix_table('users'),
@@ -842,4 +843,3 @@ function identifyUser($sentData)
         $_SESSION['settings']['cpassman_dir'] = ".";
     }
 }
-

**Comment by nilsteampassnet** [comment]
Thank you.
It seems logical with what is the library.

Can someone else confirm?

**Comment by mweber88** [comment]
Confirmed, although the patch has debug line 309 commented out.  I have left this uncommented, and it functions correctly.
