### ISSUE TITLE
POSSIBLE issue: Failed opening required file

### ISSUE THREAD

**Issue by mweber88** [nilsteampassnet/TeamPass#1517]
I found an error in my php_errors log, and I may have found the cause, but I'm not sure.

Here are the errors:

.
.
.
PHP Warning:  require_once(/includes/language/english.php): failed to open stream: No such file or directory in /Volumes/WAIDisk0/Library/Server/Web/Data/Sites/intranetTeampass/index.php on line 110
PHP Fatal error:  require_once(): Failed opening required '/includes/language/english.php' (include_path='.:/usr/local/lib/php') in /Volumes/WAIDisk0/Library/Server/Web/Data/Sites/intranetTeampass/index.php on line 110
.
.
.

This is what I think is causing the problem:
.
.
.
require_once @$_SESSION['settings']['cpassman_dir'].'/includes/language/'.$_SESSION['user_language'].'.php';
.
.
.
There is that "@" sign before the $_SESSION variable.  I'm not sure if that's the problem, but I don't find it elsewhere in that file.

Is it really a problem?

Mike

**Comment by tehnotronic** [comment]
I can see this as well in logs...

`[22-Sep-2016 16:16:56 Europe/Tallinn] PHP Warning:  require_once(/includes/language/estonian.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/index.php on line 110
[22-Sep-2016 16:16:56 Europe/Tallinn] PHP Fatal error:  require_once(): Failed opening required '/includes/language/estonian.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/localhost/htdocs/index.php on line 110
`

@-sign is just to ignore errors: http://php.net/manual/en/language.operators.errorcontrol.php

**Comment by gfvirga** [comment]
Where you able to fix this?
