### ISSUE TITLE
Upgrade from 2.1.23 fails with 500 (Internal Server Error)

### ISSUE THREAD

**Issue by dave-martin** [nilsteampassnet/TeamPass#1518]
### Steps to reproduce
1. Initiate upgrade from TeamPass 2.1.23 to 2.1.24.4 or 2.1.26.20
2.Click Launch button
3.

### Expected behaviour
Server elements should be checked.

### Actual behaviour
Activity bar animates.  Apache throws a '500 (Internal Server Error) on line 71 of upgrade.js (xhr_object.send(data);).

### Server configuration
**Operating system**:

Ubuntu 14.04.5 LTS

**Web server:**

Apache/2.4.7

**Database:**

MySQL 5.5.52-0ubuntu0.14.04.1

**PHP version:**

 5.5.9-1ubuntu4.19

**Teampass version:** 

2.1.23

**Updated from an older Teampass or fresh install:**

Fresh install - trying to upgrade to 2.1.24 or higher.

### Client configuration
**Browser:**

Chrome Version 53.0.2785.116 (64-bit)
Firefox 48.0.1
Safari Version 9.1.3 (10601.7.8)

**Operating system:**

Mac OS X 10.10.5 

#### Web server error log

no errors logged by Apache.

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

Cache-Control	 no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection close
Content-Length 0
Content-Type	text/html
Date	  Mon, 26 Sep 2016 00:58:25 GMT
Expires	Thu, 19 Nov 1981 08:52:00 GMT
Pragma	no-cache
Server	Apache/2.4.7 (Ubuntu)
X-Powered-By	PHP/5.5.9-1ubuntu4.19

Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate, br
Accept-Language	en-US,en;q=0.5
Content-Length	86
Content-Type	application/x-www-form-urlencoded; charset=utf-8
Cookie KEY_PHPSESSID=G8tM3gl2DdBTutujopONzCdY66ClT5sOVkx5sbLHP%2BQ%3D%3AhP4fXlIo11tYIX64yvAytrsgL%2Fwo6wHyn7WwlDdUo8w
%3D; PHPSESSID=tk342ifkij8ra2ka0riigsoh13
Host	redacted.example.com
Referer	https://redacted.example.com/install/upgrade.php
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by Laayem** [comment]
Hi, 

Is your problem solved? I've got the same issue on upgrade.
Thanks

**Comment by dave-martin** [comment]
I was able to successfully upgrade to 2.1.26-final-2.  It has been long enough ago that I don't recall if I had to make any changes to the TeamPass or Apache configurations in order to fix the problem.

**Comment by Laayem** [comment]
Good for you.
Thanks for answering.
