### ISSUE TITLE
Advice for HTTPS - Only secure content is displayed

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1519]
I`ve enabled HTTPS on test VM. I used company COMODO Wildcard certificate. Enabled HTTPS strict transport security.
"Only secure content is displayed" when I try to open main page or move between pages (for IE right now, for mozilla and google chrome there is another prodecure of viewing message). 
Is it needs to be like this? How avoid it (except turn off Use mised mode in browser) or there is missmatch in configuration? 

### Server configuration
**Operating system**:
Ubuntu 16.04.1
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
Ver 14.14 Distrib 5.7.15
**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
**Teampass version:** 
2.1.26.20
**Updated from an older Teampass or fresh install:**
Clean
### Client configuration
**Browser:**
IE11
**Operating system:**
Windows 10 Ent x64

**Comment by reginfo** [comment]
Hi, I figure it out. I`ve didn`t change path to https in teampass settings.

**Comment by jathanblackred** [comment]
In which file did you do the path change to https please reginfo?
