### ISSUE TITLE
Folder label can't be only a number (2.1.26.20)

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1520]
### Steps to reproduce
1. create a new folder
2. only numbers as name
3. save

### Expected behaviour
That TeamPass create the folder only with numbers as names. It worked in older versions like 2.1.26 (17)

### Actual behaviour
It shows me this error message:

![123](https://cloud.githubusercontent.com/assets/20316918/18867132/4d57bfc2-84a3-11e6-8f7a-392eed6e9461.png)

Is it possible to fix it that I can use only numbers again?

### Server configuration
**Operating system**: Windows Server 2012 R2 Standard

**Web server:** Apache 2.4.23

**Database:** MySQL 5.7.14

**PHP version:** 5.6.25

**Teampass version:** 2.1.26.20

**Updated from an older Teampass or fresh install:** fresh install 2.1.26 (20)

### Client configuration
**Browser:** Firefox Portable

**Operating system:** Windows Server 2012 R2

**Comment by nilsteampassnet** [comment]
No sorry.

This practice had drawbacks and could compromise personal folders.
That's why it was decided to consider it not allowed anymore.

Perhaps can you just prefix your number?

**Comment by qubez** [comment]
Personal folders in the database are given just a number as the name of the folder, the user's ID number. Let users also make folders with numbers as the name, and there will be (and were) unforeseen consequences.

Long ago, personal folders could have been given a folder name like "personalpersonalpersonal###12" in the database to make namespace collisions less likely, but now such a change would be difficult to make backwards-compatible.

**Comment by TheKingKai** [comment]
Ok I have a solution for my case. I added "-" in my label name and it works.
Thank you for your help.. I will close this issue.
