### ISSUE TITLE
Q : TeamPass / Yubikey

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1521]
Hello.

I see that in the files there is Yubikey folder.
Does the Teampass support it?

**Comment by nilsteampassnet** [comment]
No not yet.

Only a plan to add it ;)

**Comment by pavelpavlovic** [comment]
+1 please

**Comment by nilsteampassnet** [comment]
Can you please add it to https://teampass.userecho.com/?

I'm not managing Request from Github.
