### ISSUE TITLE
Issue with mysqli_fetch_all

### ISSUE THREAD

**Issue by s3cur3n3t** [nilsteampassnet/TeamPass#1524]
### Steps to reproduce
1. Install TeamPass 
2. Launch install 
3. Server Checks --> Function mysqli_fetch_all is not available!
### Expected behaviour

Tell us what should happen
It should evaluate the mysqli_fetch_all but it gives the following error
Function mysqli_fetch_all is not available!
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:
CentOS 7 minimal install --> CentOS Linux release 7.2.1511 (Core)
uname -a : Linux 3.10.0-327.28.3.el7.x86_64 #1 SMP

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
5.6.33 MySQL Community Server (GPL)

**PHP version:**
PHP 5.5.38 (cli) (built: Jul 21 2016 12:25:20)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Teampass version:** 
Latest stable: 2.1.26

**Updated from an older Teampass or fresh install:**
Fresh install
### Client configuration

**Browser:**
Firefx 48.0.2

**Operating system:**
CentOS 7 minimal install --> CentOS Linux release 7.2.1511 (Core)
uname -a : Linux 3.10.0-327.28.3.el7.x86_64 #1 SMP
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
is mysqlnd is installed?

**Comment by s3cur3n3t** [comment]
Weel I had to remove php55w-mysql and install php55w-mysqlnd, all good but having another error: PHP Fatal error:  Call to a member function fetch_array() on a non-object
