### ISSUE TITLE
Characters in previous password converted to HTML markup

### ISSUE THREAD

**Issue by deadpoint** [nilsteampassnet/TeamPass#1525]
### Steps to reproduce
1. Set a password to include the '<' or '>' characters, i haven't checked others
2. Change the password to something else
3. View the password and it displays the password but '<' is displayed as `&lt;`

### Expected behaviour
`A password of 'sT<4VdT?#zcN' should displayed as 'sT<4VdT?#zcN'`

### Actual behaviour
`A password of 'sT<4VdT?#zcN' is displayed as 'sT&lt;4VdT?#zcN'`

### Server configuration
**Operating system**:
SLES_12_SP1

**Web server:**
Apache 2.4.16

**Database:**
mariadb-10.0.27

**PHP version:**
php5-5.5.14

**Teampass version:** 
2.1.26.20

**Updated from an older Teampass or fresh install:**
Fresh installation

### Client configuration
**Browser:**
Chrome 53.0.2785.101
Firefox 49.0
**Operating system:**
Windows 7 64-bit

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Sorry I don't understand the point.

If I store an Item with password = `'sT<4VdT?#zcN'` then I can see `'sT<4VdT?#zcN'`

**Comment by deadpoint** [comment]
I've attached a screen capture so you can see what I'm talking about.

![teampass-1525](https://cloud.githubusercontent.com/assets/1321818/18928310/7dbf2458-858d-11e6-80b8-abdd53173318.png)

**Comment by deadpoint** [comment]
I've update the issue and wrapped the Expected and Actual behavior in code tags

**Comment by nilsteampassnet** [comment]
Ok thank you

**Comment by deadpoint** [comment]
I've noticed is behavior also in the Description that's displayed in the Label in some instances. This appears to occur when the character in the Description is at position 28, so if you take the following code and add it to the Description you'll see the behavior. Let me know if I should submit a new issue or not.

`Testing online account for "`
