### ISSUE TITLE
[Security] Backup of config files are readable by a client browser

### ISSUE THREAD

**Issue by blakkheimgw** [nilsteampassnet/TeamPass#1526]
### Steps to reproduce
1. Upgrade to a new version
2. Use your browser to go at URL <yourteampass.org>/includes/config
3. If you didn't forbid the directory listing on your web server, you'll see some backup of PHP files (settings.php and tp.config.php) of which names contain a suffix after the .php extension (eg. settings.php.2016_09_29) which make them readable by a browser.

### Expected behaviour
You shouldn't be able to read these files as one of them contain the clear database password

### Actual behaviour
Files are readable because they don't have a php extension. Even if you forbid the directory listing, someone can guess the file name, trying multiple dates and find a readable one.

### Server configuration
**Operating system**:
Ubuntu Server

**Web server:**
Apache 2.4

**Database:**
MySQL 5.5

**PHP version:**
5.5

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
Updated from 2.1.25

```

**Comment by nilsteampassnet** [comment]
It is correct.

I've committed a .htaccess file to protect this.

You can easily add an .htaccess file in folder ./includes/config/ with this content:
```
<Files>
Options -Indexes 
IndexIgnore *
Order Allow,Deny
Deny from all
</Files>
```
