### ISSUE TITLE
Error Field 'timestamp' doesn't have a default value

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1527]
I am adding users over API and seeing error:
`Error: Field 'timestamp' doesn't have a default value<br>
Query: INSERT INTO`teampass_cache`(`id`,`label`,`description`,`tags`,`id_tree`,`perso`,`restricted_to`,`login`,`folder`,`author`) VALUES (12, 'testname', 'testdesc', 'test', '20', '0', '', 'testlogin', '', '9999999')`

Timestamp column was added recently to cache table, I belive it might be missing (value not filled) in:
https://github.com/nilsteampassnet/TeamPass/blob/development/api/functions.php#L118
and: 
https://github.com/nilsteampassnet/TeamPass/blob/development/api/functions.php#L577

**Comment by nilsteampassnet** [comment]
You are right.

After L118, can you add:
```
            "author" => API_USER_ID,
            "renewal_period" => "0",
            "timestamp" => time(),
            "url" => "0"
```

L557
```
                                    "author" => API_USER_ID,
                                    "renewal_period" => "0",
                                    "timestamp" => time(),
                                    "url" => "0"
```
