### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by NiMarie** [nilsteampassnet/TeamPass#1528]
I can't import big xml file from keepass.
It's run before near version 2.1.26(11) , I'm not sure
But now 2.1.26(17) for the same files I can't.
I test it with the same xml file (59ko) I could before and I can now in 2.1.26(17)
I test it with the same xml file (1 249ko) I could before but I can't now

I think it's the size but I don't know
### Steps to reproduce
1. I export an xml files from Keepass 2
2. I choose import keepass file
3. I Have an error "Lecture du fichier impossible ! Il ne semble pas etre généré par KeePass
   ![import error](https://cloud.githubusercontent.com/assets/22522820/19041535/c4ce05cc-8988-11e6-9c8c-cdfcf454176b.PNG)

Could you help me ?

```

```

**Comment by nilsteampassnet** [comment]
Can you provide the log from Firebug?
What is the maximum size for a file to be uploaded in your teampass settings?
Isn't there any restriction on size upload on the server?

**Comment by NiMarie** [comment]
Hi,
My administrator give me this informations in log :
[Mon Oct 03 16:22:48.947216 2016] [:error] [pid 4536] [client 10.194.1.70:57011] PHP Warning:  rename(/var/www/html/files/o_1au5epuat1h2h1emn1e7u1271evqm.xml,/var/www/html/files/eserviceV1.xml): No such file or directory in /var/www/html/sources/upload/upload.files.php on line 263, referer: https://teampass-test.XXXXXX.XXXX/index.php?page=items
[Mon Oct 03 16:23:37.441990 2016] [:error] [pid 5315] [client 10.194.1.70:57030] PHP Warning:  rename(/var/www/html/files/o_1au5erdos2ail0t1g67la6qbom.xml,/var/www/html/files/Newinfo-DBADatabase.xml): No such file or directory in /var/www/html/sources/upload/upload.files.php on line 263, referer: https://teampass-testXXXXXX.XXXX/index.php?page=items

The size upload is 8Mo.

**Comment by NiMarie** [comment]
Finally I tested to copy file in /html/files before import and the import is ok. But PHP warning message appeared.
