### ISSUE TITLE
Servertime not running (2.1.26 Final)

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1529]
### Steps to reproduce
1. refresh TeamPass site
2. look at the servertime bottom right

### Expected behaviour
The current time should be displayed. 
accurate to the seconds.

### Actual behaviour
But the clock-freezes. It only shows me the time where I refresh the TeamPass site.

![time](https://cloud.githubusercontent.com/assets/20316918/19064354/1f244f52-8a0d-11e6-9a79-77fdf4283116.png)

### Server configuration
**Operating system**: Win Server 2008 R2

**Web server:** Apache 2.4.23

**Database:** 

**PHP version:** MySQL 5.7.14

**Teampass version:** 2.1.26 Final

**Updated from an older Teampass or fresh install:** Update from 2.1.26.20

### Client configuration
**Browser:** FireFox, IE

**Operating system:** Windows 7

**Comment by nilsteampassnet** [comment]
Yes it is normal.
It is the time when the page was built.

**Comment by qubez** [comment]
Does anybody use or need this time? I was thinking of putting the logged-in user down there instead.

**Comment by nilsteampassnet** [comment]
Could be an idea.

**Comment by TheKingKai** [comment]
hmm I don't need the time :D The logged-in user time is better on this place :)

Thank you, I close this issue.
