### ISSUE TITLE
Database otv table originator field should be int instead of tinyint

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1531]
If I share a link to item, firebug shows error:

`Error: Out of range value for column 'originator' at row 1<br>
Query: INSERT INTO 'tp_otv' ('id','item_id','timestamp','originator','code') VALUES (NULL, 4, 1475656651, 10000000, 'Iehagzapardook7dojz4eiPaae3igh1O')<br>`

Otv table originator is TINYINT(12), but this can only contain values from 0 to 255 and should be changed to INT(12).
http://dev.mysql.com/doc/refman/5.7/en/integer-types.html

**Comment by nilsteampassnet** [comment]
Corrected
