### ISSUE TITLE
The change of the main SALT Key doesn't work

### ISSUE THREAD

**Issue by limavrik1** [nilsteampassnet/TeamPass#1533]
### Steps to reproduce
1. Press the button "Change the main SALT Key"
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
Now happens infinite loop with gear icon
### Server configuration

**Operating system**:
CentOS 7.2.1511

**Web server:**
Apache 2.4.23

**Database:**
MariaDB 5.5.50

**PHP version:**
php 5.6.24

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
Fresh install
### Client configuration

**Browser:**
Chrome 53 and FF 49
**Operating system:**
Windows 10
#### Web server error log

No error

Insert your webserver log here
No error
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

No error

Insert the Firebug log here
No error

![screenshot_14](https://cloud.githubusercontent.com/assets/22640457/19118950/f9da80b0-8ad2-11e6-9f14-102260df317c.jpg)

**Comment by limavrik1** [comment]
How can I see this log?
Syslog server	
127.0.0.1
Syslog port 514
My syslog server is working but I don's see teampass title in the message log.

**Comment by TheKingKai** [comment]
same problem

**Comment by ErKinox** [comment]
même problème

**Comment by nilsteampassnet** [comment]
Corrected in 2.1.27
