### ISSUE TITLE
Homepage not loading in French

### ISSUE THREAD

**Issue by TotoBino007** [nilsteampassnet/TeamPass#1537]
### Steps to reproduce
1. Connect on teampass
2. Change the language to French
3. Re-login

### Expected behaviour
See the full home page
Everything works perfectly in English

### Actual behaviour
I stay on the page that you can see in attachment :

![2016-10-06 17_16_08-teampass](https://cloud.githubusercontent.com/assets/22663168/19158509/4d69f136-8be9-11e6-996b-f9c46799bbb2.png)

### Server configuration
WAMP :
Apache 2.4.18
PHP : 5.6.19
MySQL : 5.7.11

**Teampass version:** 
Last one : 2.1.26

**Updated from an older Teampass or fresh install:**
Both

### Client configuration
**Browser:**
IE11 - Chrome 53 - Firefox 48

**Operating system:**
Windows 7

**Comment by jjtronics** [comment]
Hello,

I have the same problem with the last version.
I dont have a problem in the apache logs.

Server configuration

WAMP :
Apache 2.4.10
PHP : 5.6.26
MySQL : 5.5.52

Teampass version: 
Last one : 2.1.26

Updated from an older Teampass or fresh install:
fresh

Client configuration

Browser:
IE11 - Chrome - Firefox

Operating system:
Mac Os/Windows 7

Good luck !

**Comment by nilsteampassnet** [comment]
Damned!

It is so stupid ... totally forgot to escape this.

**Comment by jjtronics** [comment]
Thank you,
if needed, do not hesitate

**Comment by TotoBino007** [comment]
Sorry for the delay.
Everything is functionnal now.
Thank you.
