### ISSUE TITLE
Cannot login after a fresh installation

### ISSUE THREAD

**Issue by Vertux** [nilsteampassnet/TeamPass#1538]
### Steps to reproduce
1. Install Teampass
2. Try to login
### Expected behaviour

First admin login after a fresh installation
### Actual behaviour

If you enter the username (here: admin) and password the wheel keeps spinning and nothing happens.
### Server configuration

**Operating system**:  Ubuntu 14.0.4

**Web server:** Apache v2.4

**Database:** MySQL v5.5.52

**PHP version:** PHP v5.5.9

**Teampass version:**  v2.1.26
### Client configuration

**Browser:** Safari, Chrome, Firefox no difference

**Operating system:** macOS Sierra
#### Web server error log

_no errors_
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

_No error_ but Answer: "Hacking attempt..." for https://xxxx.xxxxx.xx/sources/identify.php?

**Comment by nilsteampassnet** [comment]
Please give the error log using firebug, check the `How to?` link

**Comment by Kamixo** [comment]
Hallo,

I have the same problem. Teampass freshly installed. No problems and no error messages. I can not log in as admin. I can not select the language (top right) too.
After entering the login information is displayed: Please identify yourself
Otherwise, nothing happens

I have deleted the following myself:
- install folder (ftp)
- install data in mysql

Nothing happens!

system: Linux
PHP version: 5.6.26
mysql: 5.0.11
TeamPass 2.1.26

Firebug
![bildschirmfoto 2016-10-13 um 20 40 49](https://cloud.githubusercontent.com/assets/22822745/19362067/6d129b36-9185-11e6-9ef2-b945e34e63fa.jpg)

`/** 
 * =================================================================
 * Javascript code for OWASP CSRF Protector
 * Task it does: Fetch csrftoken from cookie, and attach it to every
 *      POST request
 *      Allowed GET url
 *          -- XHR
 *          -- Static Forms
 *          -- URLS (GET only)
 *          -- dynamic forms
 * =================================================================
 */

var CSRFP_FIELD_TOKEN_NAME = 'csrfp_hidden_data_token';
var CSRFP_FIELD_URLS = 'csrfp_hidden_data_urls';

var CSRFP = {
    CSRFP_TOKEN: '',
    /**
     * Array of patterns of url, for which csrftoken need to be added
     * In case of GET request also, provided from server
     *
     * @var string array
     */
    checkForUrls: [],
    /**
     * Function to check if a certain url is allowed to perform the request
     * With or without csrf token
     *
     * @param: string, url
     *
     * @return: boolean,    true if csrftoken is not needed
     *                      false if csrftoken is needed
     */
    _isValidGetRequest: function(url) {
        for (var i = 0; i < CSRFP.checkForUrls.length; i++) {
            var match = CSRFP.checkForUrls[i].exec(url);
            if (match !== null && match.length > 0) {
                return false;
            }
        }
        return true;
    },
    /** 
     * function to get Auth key from cookie Andreturn it to requesting function
     *
     * @param: void
     *
     * @return: string, csrftoken retrieved from cookie
     */
    _getAuthKey: function() {
        var re = new RegExp(CSRFP.CSRFP_TOKEN +"=([^;]+)(;|$)");
        var RegExpArray = re.exec(document.cookie);
        
        if (RegExpArray === null) {
            return false;
        }
        return RegExpArray[1];
    },
    /** 
     * Function to get domain of any url
     *
     * @param: string, url
     *
     * @return: string, domain of url
     */
    _getDomain: function(url) {
        if (url.indexOf("http://") !== 0 
            && url.indexOf("https://") !== 0)
            return document.domain;
        return /http(s)?:\/\/([^\/]+)/.exec(url)[2];
    },
    /**
     * Function to create and return a hidden input element
     * For stroing the CSRFP_TOKEN
     *
     * @param void
     *
     * @return input element
     */
    _getInputElt: function() {
        var hiddenObj = document.createElement("input");
        hiddenObj.name = CSRFP.CSRFP_TOKEN;
        hiddenObj.type = 'hidden';
        hiddenObj.value = CSRFP._getAuthKey();
        return hiddenObj;
    },
    /**
     * Returns absolute path for relative path
     * 
     * @param base, base url
     * @param relative, relative url
     *
     * @return absolute path (string)
     */
    _getAbsolutePath: function(base, relative) {
        var stack = base.split("/");
        var parts = relative.split("/");
        // remove current file name (or empty string)
        // (omit if "base" is the current folder without trailing slash)
        stack.pop(); 
             
        for (var i = 0; i < parts.length; i++) {
            if (parts[i] == ".")
                continue;
            if (parts[i] == "..")
                stack.pop();
            else
                stack.push(parts[i]);
        }
        return stack.join("/");
    },
    /** 
     * Remove jcsrfp-token run fun and then put them back 
     *
     * @param function
     * @param reference form obj
     *
     * @retrun function
     */
    _csrfpWrap: function(fun, obj) {
        return function(event) {
            // Remove CSRf token if exists
            if (typeof obj[CSRFP.CSRFP_TOKEN] !== 'undefined') {
                var target = obj[CSRFP.CSRFP_TOKEN];
                target.parentNode.removeChild(target);
            }
            
            // Trigger the functions
            var result = fun.apply(this, [event]);
            
            // Now append the csrfp_token back
            obj.appendChild(CSRFP._getInputElt());
            
            return result;
        };
    },
    /**
     * Initialises the CSRFProtector js script
     *
     * @param void
     *
     * @return void
     */
    _init: function() {
        CSRFP.CSRFP_TOKEN = document.getElementById(CSRFP_FIELD_TOKEN_NAME).value;
        try {
            CSRFP.checkForUrls = JSON.parse(document.getElementById(CSRFP_FIELD_URLS).value);
        } catch (err) {
            console.error(err);
            console.error('[ERROR] [CSRF Protector] unable to parse blacklisted url fields.');
        }

        //convert these rules received from php lib to regex objects
        for (var i = 0; i < CSRFP.checkForUrls.length; i++) {
            CSRFP.checkForUrls[i] = CSRFP.checkForUrls[i].replace(/\*/g, '(.*)')
                                .replace(/\//g, "\\/");
            CSRFP.checkForUrls[i] = new RegExp(CSRFP.checkForUrls[i]);
        }
    
    }
    
}; 

//==========================================================
// Adding tokens, wrappers on window onload
//==========================================================

function csrfprotector_init() {
    
    // Call the init funcion
    CSRFP._init();
    
    //==================================================================
    // Adding csrftoken to request resulting from <form> submissions
    // Add for each POST, while for mentioned GET request
    //==================================================================
    for(var i = 0; i < document.forms.length; i++) {
        document.forms[i].addEventListener("submit", function(event) {
            if (typeof event.target[CSRFP.CSRFP_TOKEN] === 'undefined') {
                event.target.appendChild(CSRFP._getInputElt());
            } else {
                //modify token to latest value
                event.target[CSRFP.CSRFP_TOKEN].value = CSRFP._getAuthKey();
            }
        });
    }
    
    /**
     * Add wrapper for HTMLFormElements addEventListener so that any further 
     * addEventListens won't have trouble with CSRF token
     */
    HTMLFormElement.prototype.addEventListener_ = HTMLFormElement.prototype.addEventListener;
    HTMLFormElement.prototype.addEventListener = function(eventType, fun, bubble) {
        if (eventType === 'submit') {
            var wrapped = CSRFP._csrfpWrap(fun, this);
            this.addEventListener_(eventType, wrapped, bubble);
        } else {
            this.addEventListener_(eventType, fun, bubble);
        }   
    }

    /**
     * Add wrapper for IE's attachEvent
     */
    if (typeof HTMLFormElement.prototype.attachEvent !== 'undefined') {
        HTMLFormElement.prototype.attachEvent_ = HTMLFormElement.prototype.attachEvent;
        HTMLFormElement.prototype.attachEvent = function(eventType, fun) {
            if (eventType === 'submit') {
                var wrapped = CSRFP._csrfpWrap(fun, this);
                this.attachEvent_(eventType, wrapped);
            } else {
                this.attachEvent_(eventType, fun);
            }
        }
    }


    //==================================================================
    // Wrapper for XMLHttpRequest & ActiveXObject (for IE 6 & below)
    // Set X-No-CSRF to true before sending if request method is 
    //==================================================================

    /** 
     * Wrapper to XHR open method
     * Add a property method to XMLHttpRequst class
     * @param: all parameters to XHR open method
     * @return: object returned by default, XHR open method
     */
    function new_open(method, url, async, username, password) {
        this.method = method;
        var isAbsolute = (url.indexOf("./") === -1) ? true : false;
        if (!isAbsolute) {
            var base = location.protocol +'//' +location.host 
                            + location.pathname;
            url = CSRFP._getAbsolutePath(base, url);
        }
        if (method.toLowerCase() === 'get' 
            && !CSRFP._isValidGetRequest(url)) {
            //modify the url
            if (url.indexOf('?') === -1) {
                url += "?" +CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
            } else {
                url += "&" +CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
            }
        }

        return this.old_open(method, url, async, username, password);
    }

    /** 
     * Wrapper to XHR send method
     * Add query paramter to XHR object
     *
     * @param: all parameters to XHR send method
     *
     * @return: object returned by default, XHR send method
     */
    function new_send(data) {
        if (this.method.toLowerCase() === 'post') {
            if (data !== null && typeof data === 'object') {
                data[CSRFP.CSRFP_TOKEN] = CSRFP._getAuthKey();
            } else {
                if (typeof data != "undefined") {
                    data += "&";
                } else {
                    data = "";
                }
                data += CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
            }
        }
        return this.old_send(data);
    }

    if (window.XMLHttpRequest) {
        // Wrapping
        XMLHttpRequest.prototype.old_send = XMLHttpRequest.prototype.send;
        XMLHttpRequest.prototype.old_open = XMLHttpRequest.prototype.open;
        XMLHttpRequest.prototype.open = new_open;
        XMLHttpRequest.prototype.send = new_send;
    }
    if (typeof ActiveXObject !== 'undefined') {
        ActiveXObject.prototype.old_send = ActiveXObject.prototype.send;
        ActiveXObject.prototype.old_open = ActiveXObject.prototype.open;
        ActiveXObject.prototype.open = new_open;
        ActiveXObject.prototype.send = new_send;    
    }
    //==================================================================
    // Rewrite existing urls ( Attach CSRF token )
    // Rules:
    // Rewrite those urls which matches the regex sent by Server
    // Ignore cross origin urls & internal links (one with hashtags)
    // Append the token to those url already containig GET query parameter(s)
    // Add the token to those which does not contain GET query parameter(s)
    //==================================================================

    for (var i = 0; i < document.links.length; i++) {
        document.links[i].addEventListener("mousedown", function(event) {
            var href = event.target.href;
            if(typeof href === "string")
            {
                var urlDisect = href.split('#');
                var url = urlDisect[0];
                var hash = urlDisect[1];

                if(CSRFP._getDomain(url).indexOf(document.domain) === -1
                    || CSRFP._isValidGetRequest(url)) {
                    //cross origin or not to be protected by rules -- ignore
                    return;
                }

                if (url.indexOf('?') !== -1) {
                    if(url.indexOf(CSRFP.CSRFP_TOKEN) === -1) {
                        url += "&" +CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
                    } else {
                        url = url.replace(new RegExp(CSRFP.CSRFP_TOKEN +"=.*?(&|$)", 'g'),
                            CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey() + "$1");
                    }
                } else {
                    url += "?" +CSRFP.CSRFP_TOKEN +"=" +CSRFP._getAuthKey();
                }

                event.target.href = url;
                if (typeof hash !== 'undefined') {
                    event.target.href += '#' +hash;
                }
            }
        });
    }

}

window.addEventListener("DOMContentLoaded", function() {
    csrfprotector_init();
}, false);
`
Can you help me?
Best Regards

**Comment by nilsteampassnet** [comment]
Permissions correctly set on csrfp folders and files?
file csrfp.config.php correctly updated?

**Comment by Kamixo** [comment]
Permissions of csrfp folder 755 in includes.

Should I now check all permissions?
I have installed fresh TeamPass!
Where exactly should I look?

Correctly update?
Fresh installed!

**Comment by Vertux** [comment]
I have decided not to install Teampass on my main server. So unfortunately I can not give you any further details. Do not get me wrong but there are some weird issues. Today I did test installation in a VM with plain **Ubuntu v14.04** and LAMP (**PHP 5.5.9, MySQL v5.5.52, Apache v2.4**) and stumbled into another problem:

`[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!`

It seems to be a well known issue which is still unsolved - [#1218](https://github.com/nilsteampassnet/TeamPass/issues/1218)

To be honest, meanwhile I got a bad feeling with Teampass.

**Comment by nilsteampassnet** [comment]
I would be interesting to share this VM as this error I didn't reproduce.
I'm pretty sure it is related to server configuration and as you can imagine, it is impossible to test on all configuration.

@Vertux, could you share this VM or enable it and let me have an access to it (direct or with AMMYY if prefered).

**Comment by Vertux** [comment]
@nils Unfortunately I have deleted the VM already. Maybe I give it another try, so I can share it with you. I guess you are right about the server configuration, maybe I did a silly mistake, but the error message is not very helpful.

**Comment by nilsteampassnet** [comment]
Yes this message is not enough but I know I've once got this behavior and notice that it was related to the php version. That's the reason ... I would be happy to improve this ;)

Thanks for the proposal to share.

**Comment by Vertux** [comment]
Ok, now I have installed it again and it seems to work now, but I have some suggestion to avoid issues.  The LAMP/phpmyadmin installation of Ubuntu 14.04 seems to install mcypt not correctly - see [here](http://askubuntu.com/questions/460837/mcrypt-extension-is-missing-in-14-04-server-for-mysql) to fix it - ok, that's not your part.
I did my installation with git
```
cd /var/www/html
sudo git clone https://github.com/nilsteampassnet/TeamPass.git  teampass
```
It is uncommon to use "sudo" here but because of the default directory permission I had to do it.
So the whole tree got "root:root" as owner. The manual says now: `chmod -R 777 teampass` - that's a kind of weird if you think about security and you do not tell the user, that you will change the rights later.
![bildschirmfoto 2016-10-22 um 15 32 38](https://cloud.githubusercontent.com/assets/10457918/19619930/2073e7be-9872-11e6-94b8-4cfd1943308e.png)
It is very annoying that you cannot paste a complex password for the administrator. As consequence the user probably will choose a simple password and maybe forget to change it later - it remembers me of the Steam GUI there copy&paste is disabled too, IMHO it makes no sense to me.  btw, the [screenshot](http://teampass.net/2013-12-31-installation-on-linux-server) does not match the current Teampass version - the input field for the admin password is missing.
![bildschirmfoto 2016-10-22 um 15 34 23](https://cloud.githubusercontent.com/assets/10457918/19619968/161db078-9873-11e6-967a-41063995a34f.png)
And now I run into a permission problem, it was not really a surprise for me, but maybe for an unexperienced user. Sadly Teampass gives no hint what to change and:
![bildschirmfoto 2016-10-22 um 15 45 06](https://cloud.githubusercontent.com/assets/10457918/19620005/ec62ad0a-9873-11e6-846e-fb74e07f7408.png)
you have no chance to test it out ("Launch") like in the setup steps before - if you choose to restart you will run into another problem with the sk.php file which is already there and cannot be overwritten. So far so good, when I change the owner:
```
cd /var/www/html
sudo chown -R www-data:www-data teampass
```
the setup process does not complain about permissions anymore. 
There is another very little issue. When I change the language on the login page to e.g. german and then login, it is switched back to the default ("english") setting on the following page:
![bildschirmfoto 2016-10-22 um 15 48 45](https://cloud.githubusercontent.com/assets/10457918/19620121/1d393050-9876-11e6-90bb-fe46b0845aef.png)
btw, it was the same server configuration as above.

**Comment by Vertux** [comment]
Just a complement - I do not wanted to open further issues:
I have created my first user as "Manager" when i log in I get this error:
![bildschirmfoto 2016-10-22 um 17 00 27](https://cloud.githubusercontent.com/assets/10457918/19620319/6e847104-987b-11e6-9821-e5b3e17b1ae5.png)
If I click the search button in the menu I get this error:
![bildschirmfoto 2016-10-22 um 17 11 47](https://cloud.githubusercontent.com/assets/10457918/19620331/a6fc7284-987b-11e6-9f52-9b5e8e36801f.png)
And I am very confused by the status information at the bottom of the page:
![bildschirmfoto 2016-10-22 um 17 12 45](https://cloud.githubusercontent.com/assets/10457918/19620347/eac849c0-987b-11e6-986b-8ad18193b8fd.png)
There is only one user logged in, why it shows two users ?

Do not get me wrong, but for a password manager there are many weird issues - in my humble option too many.

**Comment by nilsteampassnet** [comment]
I'm very surprise of all the errors you get. 
It is not normal. 
There must be an explanation as a package that is not in expected version. Perhaps your server embeds version that are recent and not well manage by teampass. 
I would be very interest to get connected to it

**Comment by nilsteampassnet** [comment]
Install process is if course not perfect. 
It needs to be improved and your return of experience is very interesting.  I will improve for next version. 
You know I'm most focusing on issues related to items management. My time is limited as all of us. 
But sincerely your experience sounds strange to me as I never experiment such behavior and that is why I suggest something related to server configuration. I'm mostly using Windows and testing on Centos only.

**Comment by nilsteampassnet** [comment]
But thinking that I've also tested using lubuntu which is quite similar to Ubuntu. 
And I didn't experiment this but I didn't install using Git as you did

**Comment by Vertux** [comment]
I have used the official Ubuntu Server v14.04.x 64bit image ([Download-Link](http://releases.ubuntu.com/14.04.5/ubuntu-14.04.5-server-amd64.iso)). First I did an apt update and while the installation I have set language to german, and at the end I have chosen SSH server and LAMP. After the Ubuntu installation I have installed myphpadmin. Everything else I have explained before. I think it should be possible for you to simulate all my errors by yourself.  My VM runs on a VMWare EXSi 6.0 Server. I did almost no changes, I only increased the php execution time in the php.ini to 60sec. I did not touch the apache or MySQL configuration in any way. If you need any further information please do not hesitate to ask me.
I agree with you lubuntu souldn't be very different, beside the fact that I have used the server image.

**Comment by aragornol** [comment]
I am using 

Teampass : 2.1.26-3
CentOS 7.2
Apache 2.4.6
with all dependencies installed.

I`ve experienced few hiccups during installation which were resolved. I was stucked after installation when visting page i`ve got message that "You are not allowed to see this page". After looking into index.php and bit of debugging I`ve found out $languagesList is empty array. 

After inserting 

$languagesList = array ("english" => "english");

I`ve finally come to login page but i can neither login with admin/admin, nor with admin / password during installation, administrator / password during installation.

All of my SQL tables are empty but misc.

I don`t know what to do next ?!
