### ISSUE TITLE
Bug Running Automatic Password Changes via Cron

### ISSUE THREAD

**Issue by bdd4329** [nilsteampassnet/TeamPass#1540]
### Steps to reproduce
1. Run the password change cron script (script.ssh.php) from the CLI (or cron)
### Expected behaviour

This should run and change passwords as necessary
### Actual behaviour

I receive errors because the file isn't built to operate from the CLI (although the tooltip says to do this). There are references to headers and session variables. Here's the initial errors that I receive:

PHP Warning:  include(../includes/config/settings.php): failed to open stream: No such file or directory in /var/www/html/backups/script.ssh.php on line 15
PHP Warning:  include(): Failed opening '../includes/config/settings.php' for inclusion (include_path='.:/var/www/html:/var/www/html/includes:/usr/share/pear:/usr/share/php') in /var/www/html/backups/script.ssh.php on line 15
PHP Warning:  require_once(../sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/html/backups/script.ssh.php on line 19
PHP Fatal error:  require_once(): Failed opening required '../sources/SplClassLoader.php' (include_path='.:/var/www/html:/var/www/html/includes:/usr/share/pear:/usr/share/php') in /var/www/html/backups/script.ssh.php on line 19

I hacked around and fixed this error, but I still received errors due to the use of the header() function and the $_SESSION variables.
### Server configuration

**Operating system**:
Centos 7.2

**Web server:**
Apache 2.4

**Database:**
Mysql 5.5.50

**PHP version:**
5.4.16

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration

**Browser:**
Chrome

**Operating system:**
OS X El Capitan
#### Web server error log

```

PHP Warning:  include(../includes/config/settings.php): failed to open stream: No such file or directory in /var/www/html/backups/script.ssh.php on line 15
PHP Warning:  include(): Failed opening '../includes/config/settings.php' for inclusion (include_path='.:/var/www/html:/var/www/html/includes:/usr/share/pear:/usr/share/php') in /var/www/html/backups/script.ssh.php on line 15
PHP Warning:  require_once(../sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/html/backups/script.ssh.php on line 19
PHP Fatal error:  require_once(): Failed opening required '../sources/SplClassLoader.php' (include_path='.:/var/www/html:/var/www/html/includes:/usr/share/pear:/usr/share/php') in /var/www/html/backups/script.ssh.php on line 19

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```

Insert the Firebug log here

```

```

**Comment by nilsteampassnet** [comment]
Strange errors, it seems the script.ssh.php file is not at his correct place.
Can you make a screenshot of folders and files in /backups and /includes/config?

**Comment by bdd4329** [comment]
[root]@coe-password /var/www/html/backups> (09:11:17 10/10/16)
:: ls
script.backup.php  script.ssh.php

[root]@coe-password /var/www/html/backups> (09:11:17 10/10/16)
:: cd ../includes/config/

[root]@coe-password /var/www/html/includes/config> (09:11:34 10/10/16)
:: ls
include.php  settings.php  tp.config.php

**Comment by qubez** [comment]
_PHP version:
5.4.16_

Teampass should give an install warning that PHP 5.5 is required.

I also have seen hosting systems that have a different PHP version used for CLI than that used for Apache - even 5.2 when Apache is set to 5.6. Run **php -v** in the context of the cronjob user.

The error at line 15 is that '../includes/config/settings.php' could not be loaded. Is that file present? It seems like you must have specified the full location to fix it? The settings file is only fully implemented in recent versions, and can be recreated in admin's task tab.

**Comment by bdd4329** [comment]
The script does exist is in the proper location. When I start the script from the backup location I get the following:

[root]@coe-password /var/www/html/includes> (09:45:49 10/11/16)
:: php script.ssh.php 
PHP Notice:  Undefined variable: _SESSION in /var/www/html/backups/script.ssh.php on line 30
PHP Notice:  Undefined variable: _SESSION in /var/www/html/backups/script.ssh.php on line 31
PHP Warning:  include(/includes/libraries/Authentication/phpseclib/Net/SSH2.php): failed to open stream: No such file or directory in /var/www/html/backups/script.ssh.php on line 31
PHP Warning:  include(): Failed opening '/includes/libraries/Authentication/phpseclib/Net/SSH2.php' for inclusion (include_path='/var/www/html:/var/www/teampass-api.:/usr/share/pear:/usr/share/php') in /var/www/html/backups/script.ssh.php on line 31
PHP Notice:  Undefined variable: _SESSION in /var/www/html/backups/script.ssh.php on line 50
PHP Notice:  Undefined variable: _SESSION in /var/www/html/backups/script.ssh.php on line 50
PHP Fatal error:  Call to undefined function prefix_table() in /var/www/html/backups/script.ssh.php on line 55
