### ISSUE TITLE
Modify Automatic first-login email 

### ISSUE THREAD

**Issue by andresguisado** [nilsteampassnet/TeamPass#1542]
Hello, 

By the time is created an new user teampass send an email to the user address email as follows:

"
An administrator has created an account you on the password manager. Secure passwords for your organization are just a click away! 

Use these credentials for your first login:
- Login: XXX
- Password: undefined

Click this link to log in and reset your password.  
"

Could I modify the message of this message?

My version is v2.1.26(final version) and it is a fresh installation.

Thanks

**Comment by qubez** [comment]
The messages are in the language file, for example **/includes/language/english.php** for English.

**Comment by andresguisado** [comment]
Cool!

I have been able to manage this with you comment.

Thanks!

**Comment by boffen** [comment]
The text
"An administrator has created an account you on the password manager."
should be
"An administrator has created an account for you on the password manager."

The text can be found on line 234 of the below mentioned files and has the array item name 'email_new_user_mail' 
teampass/includes/language/arabic.php
teampass/includes/language/bulgarian.php
teampass/includes/language/catalan.php
teampass/includes/language/chinese.php
teampass/includes/language/english.php
teampass/includes/language/greek.php
teampass/includes/language/japanese.php
teampass/includes/language/norwegian.php
teampass/includes/language/portuguese.php
teampass/includes/language/swedish.php
teampass/includes/language/turkish.php
teampass/includes/language/ukrainian.php
teampass/includes/language/vietnamese.php

**Comment by qubez** [comment]
"An administrator has created an account you on the password manager."

Thanks, this is already fixed in Poeditor.
