### ISSUE TITLE
Wrong Saltkey message after setting 

### ISSUE THREAD

**Issue by andresguisado** [nilsteampassnet/TeamPass#1543]
### Steps to reproduce
1. Setup the Salt key for personal folder
2. Create an item
3. Log out
4. Log in
5. "You must create a personal salt key to use the personal folder feature"

![screen shot 2016-10-09 at 18 22 13](https://cloud.githubusercontent.com/assets/13769361/19222317/5e269dc4-8e4d-11e6-8fd2-f7d594dc7511.png)
### Expected behaviour

After setting up the salt key the message that you should be is something like : " You should enter your personal saltkey if you need to use your personal items."
### Actual behaviour

After setting up saltkey you can still seeing  "You must create a personal salt key to use the personal folder feature"
### Server configuration

**Operating system**:Centos7

**Web server:**Apache 2.4

**Database:**Mysql 5.7

**PHP version:**PHP 5.6

**Teampass version:** v.2.1.26 (final version)

**Updated from an older Teampass or fresh install:** Fresh install 
### Client configuration

**Browser:**Chrome Version 53.0.2785.143 (64-bit)

**Operating system:**Mac

```

```

**Comment by nilsteampassnet** [comment]
In 2.1.27, saltkey process has changed and this message is now managed
