### ISSUE TITLE
LDAP distinguished name with + inside not working

### ISSUE THREAD

**Issue by justinc1** [nilsteampassnet/TeamPass#1544]
On (outdated) installation of teampass (2.1.18, ea67daf3021048ec255702545cef36e8798ed951) I noticed minor problem with particular LDPA user: The guy has a "+" in its DN

```
dn: cn=First Second+sn=Second,ou=people,dc=example,dc=com
uid: f_second
```

And search/bind log looked like:

```
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359637 op=0 BIND dn="BIND_USER" method=128
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359637 op=0 BIND dn="BIND_USER" mech=SIMPLE ssf=0
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359637 op=0 RESULT tag=97 err=0 text=
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359637 op=1 SRCH base="ou=people,ou=example,dc=com" scope=2 deref=0 filter="(uid=f_second)"
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359637 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359638 fd=64 ACCEPT from IP=xxx:60717 (IP=0.0.0.0:389)
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359638 op=0 BIND dn="cn=First Second,ou=people,ou=example,dc=com" method=128
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359638 op=0 RESULT tag=97 err=49 text=
Oct 10 09:52:19 auth2 slapd[28048]: conn=29359638 op=1 UNBIND
```

So after successful search, a wrong user DN is used - part after + is missing.

I did rename the particular user DN to allow the guy to login (I could that, as his new DN was still free). But in general, we could have two persons with the same "first second" name (actually we have exactly that case - but lucky us, one is used to be called say John, and second say Johnny :).

**Comment by chc88** [comment]
Have you tried this with the latest version? No LDAP user, but I have seen many changes in this area during the development of 2.1.26

**Comment by justinc1** [comment]
No, I have not. To do that, I would have to install new teampass etc.

Is there a chance to reuse existing tests? I assume there are unit tests and CI tests somewhere - but I didn't search for them.
