### ISSUE TITLE
Folder not visible to user

### ISSUE THREAD

**Issue by gerbsen** [nilsteampassnet/TeamPass#1545]
Hello,
I'm trying to share directories (which contain passwords) to registered users. I've edited the user in the users view to have a set of allowed directories. But the user in question can only see the following:

![screenshot 2016-10-10 11 41 44](https://cloud.githubusercontent.com/assets/1186245/19232194/c63d928c-8ede-11e6-90c6-30737129c668.png)

I also tried this based on roles but the user can not see the allowed items. I also tried these options:
- Enable Restricted To functionality on Items  
- Allow to restrict items to Users and Roles

But this does not seem to work.

Cheers,
Daniel

**Comment by abenrob** [comment]
I'm the user in question...
I am able to see some (but not all) of the entries by selecting the "find" button. If I choose to open in new page, I see the contents of the one folder in the right-side panel, but the left-side folder navigator is __always spinning__ and never lists the folders I should have access to view.

**Comment by nilsteampassnet** [comment]
What are the log errors?
If no errors, then it is related to given rights.
Need full details to give some tips.

**Comment by chc88** [comment]
Are you giving users access to subfolders, but no read-access to the parent-folders?

**Comment by gerbsen** [comment]
Yes, is there any way to circumvent this? I would have to reorganise everything :/
