### ISSUE TITLE
Details are not loading after upgraded to 2.1.26 from 2.1.18

### ISSUE THREAD

**Issue by vadivelkishore** [nilsteampassnet/TeamPass#1546]
Hi, 

After upgrading teampass from 2.1.18 to 2.1.26, we see the GUI , details are not getting loaded as expected.

Please find the details below.
### Steps to reproduce
1. Login to Teampass
2. Search for any user/system for which we need to load details for. Auto filter is working as expected.
3. For selected row, by clicking on see details(Eye symbol), the details should be displayed in new dialogue box. The details in new dialogue is not loading and it is blank which is unexpected behavior.
### Expected behaviour

Tell us what should happen
Details of selected user/system in new dialogue box should be displayed without any issue
### Actual behaviour

Tell us what happens instead
Details of selected user/system is missing in new dialogue box.
### Server configuration

**Operating system**:
Linux, x86_64

**Web server:**

**Database:**
MySQL

**PHP version:**
PHP 5.1.6

**Teampass version:** 
current version : 2.1.18 (There is no issue in this version)
Upgraded to 2.1.26 (after upgrade we have issue with details loading)

**Updated from an older Teampass or fresh install:**
Older version : 2.1.18
### Client configuration

**Browser:**
Chrome :  No error message seen on browser.
using firebug in chrome : VM1381:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0
Firefox : SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Operating system:**
Windows 7
#### Web server error log

VM1381:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0

Insert your webserver log here
Logs from server : AES-128 requires a 16 byte key, 15 bytes received in /opt/lampp/htdocs/teampass/includes/libraries/phpcrypt/Cipher.php on line 245
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

VM1381:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0

Insert the Firebug log here
VM1381:1 Uncaught SyntaxError: Unexpected token  in JSON at position 0

**Comment by qubez** [comment]
You indicate PHP 5.1.6. There's this file here, https://github.com/nilsteampassnet/TeamPass/blob/master/readme.md, that indicates PHP 5.5 or greater is required.
