### ISSUE TITLE
Disable smtp certificate validation ?

### ISSUE THREAD

**Issue by Keithsc** [nilsteampassnet/TeamPass#1548]
Emails are not getting sent from teampass. A connection is made to our mail server but the certificate fails verification and so nothing gets sent. I am unable to make changes to the mail server just now so need to figure out how to disable the verification in teampass.

The error i get is...
[13-Oct-2016 16:15:08 Europe/London] PHP Warning:  stream_socket_enable_crypto(): Peer certificate CN=`our_cert_name' did not match expected CN=`192.168.x.y' in /usr/share/nginx/html/includes/libraries/Email/Phpmailer/class.smtp.php on line 358

In the email settings in TeamPass I have...
 SMTP server address    our_mail_servers_is
  Server requires authentication    YES
  Mail server username  our_mail_server_username
  Mail server password  our_mail_server_password
  Customize URL for links       blank
  SMTP server port  25
  SMTP security type    None
  From: Email address   do_not_reply@our_domain
  From: Display name    Our Team Name

This is what I see on our mail servers logs...
"SENT: 220 our.domain"
"RECEIVED: EHLO _"
"SENT: 250-our.domain[nl]250-SIZE 20480000[nl]250-STARTTLS[nl]250-AUTH LOGIN PLAIN[nl]250 HELP"
"RECEIVED: STARTTLS"
"SENT: 220 Ready to start TLS"
### Steps to reproduce
1. 
   2.
   3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Updated from an older Teampass or fresh install:**
### Client configuration

**Browser:**

**Operating system:** 
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by Keithsc** [comment]
I have figured out how to get email to send by making changes to the following file...

Edit the file....   = includes/libraries/Email/Phpmailer/class.phpmailer.php

Find.
    public $SMTPOptions = array();

Replace with...
     public $SMTPOptions = array (
        'ssl' => array(
            'verify_peer'  => false,
            'verify_peer_name'  => false,
            'allow_self_signed' => true));

Emails are being sent now and I guess I should get a real certificate for our mail server although I did set "SMTP Security type" to None. is this a bug ?

**Comment by chc88** [comment]
In your log the server advertises STARTTLS.
By default PHPMailer autostarts TLS when available.

See line 265 of includes/libraries/Email/Phpmailer/class.phpmailer.php

The certificate-error you receive is different though. It just notices that the certificate is issued to a named-server, while you are trying to connect using the ip-address. Which should be quite easy to fix right?
