### ISSUE TITLE
View permissions on personal folder

### ISSUE THREAD

**Issue by cgermanb** [nilsteampassnet/TeamPass#1549]
hi people, i have a problem,

when i put a user with only view, he cant add or edit your personal folder, for me this is no correct, i want only view for all folder but write in your personal folder.

i am doing something wrong?

Kings regards.

 
### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**: centos 7

**Web server:**

**Database:** mysql

**PHP version:**5.6.26

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:**
### Client configuration

**Browser:** Mozilla

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Correct.

I will improve this.

**Comment by cgermanb** [comment]
Thanks!

**Comment by nilsteampassnet** [comment]
Implemented
