### ISSUE TITLE
Items not shown in folders and http request hanging

### ISSUE THREAD

**Issue by luberti** [nilsteampassnet/TeamPass#1554]
### Steps to reproduce
1. login
2. access any folder
3.

### Expected behaviour
I should see the list of items in the folder

### Actual behaviour
There is no item shown and I see the rotating icon next to the search field keep on rotating

### Server configuration
**Operating system**:
Linux Centos
**Web server:**
Apache/2.2.15 (CentOS)
**Database:**
MySQL
**PHP version:**
5.5
**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration
**Browser:**
Firefox or Chrome
**Operating system:**
Windows
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```
There is no erro in firbug but looking at the requrest issued I see there are three requests  like this 

http://teampass.archicoop.it/index.php?page=items

and one is hanging

**Comment by luberti** [comment]
Sorry forget it: the server where the MySQL db is running had the disk full.....you can close it and hope it can be useful to someone else someday

**Comment by nilsteampassnet** [comment]
thanks for REX
