### ISSUE TITLE
Error Encrypting Password only in personal folder

### ISSUE THREAD

**Issue by MarcArbour** [nilsteampassnet/TeamPass#1558]
Hi.

I have all my posix search user that cannot create items in their personnal folder without being told "error encrypting password ".

Passwords imported from keepass via xml file work fine ONCE. They show the password once after which, nothing.

Creating new items lead to same red triangle with message.

An imported items moved to a public folder works fine.

Any suggestions on the problem? I rebuild the database, reset salts, reimported twice....

Thanks.

**Comment by teresamp** [comment]
I have the same problem, with version 2.1.26-3final  in debian 8. A icon red is showed , however the passwords are showed properly.

**Comment by ErKinox** [comment]
I have the same problem,with version 2.1.26-3 final.
