### ISSUE TITLE
teampass.net domain expired October 30 2016?

### ISSUE THREAD

**Issue by doughnet** [nilsteampassnet/TeamPass#1564]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by dam09fr** [comment]
![Screenshot from teampass.net](http://nsa37.casimages.com/img/2016/10/31/161031102907774879.jpg)

**Comment by nilsteampassnet** [comment]
Strange.  It is paid until August 2017.

**Comment by jibiwaba** [comment]
@nilsteampassnet are you talking about the web hosting or the domain registration? The domain expired yesterday.

Domain Name: TEAMPASS.NET
Registrar: PDR LTD. D/B/A PUBLICDOMAINREGISTRY.COM
Sponsoring Registrar IANA ID: 303
Whois Server: whois.PublicDomainRegistry.com
Referral URL: http://www.publicdomainregistry.com
Name Server: NS1.HALFDOLLARHOSTING.US
Name Server: NS2.HALFDOLLARHOSTING.US
Status: clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
Updated Date: 01-oct-2015
Creation Date: 30-oct-2011
Expiration Date: 30-oct-2016
