### ISSUE TITLE
[TeamPass 2.1.26] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by SylvainGuibert** [nilsteampassnet/TeamPass#1567]
This issue is similar to #1292 but i can't solve it with advice on that post.

### Steps to reproduce

I don't now... any time when we create an entry.

### Expected behaviour

Any time we create an entry, we obtain " SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" . Error messages are different between browers : 

Chrome : SyntaxError: Unexpected token À in JSON at position 0
Firefox : SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Edge : SyntaxError: Syntax error 

### Actual behaviour
Error comes from TeamPass 2.1.25. I upgrade it today, to check if issue still occur....and the issue still occured !

### Server configuration
**Operating system**: Ubuntu 14.04.2

**Web server:** Apache 2.4.7

**Database:** Mysql 5.5.41

**PHP version:** Php 5.5.9

**Teampass version:** : 2.1.26 (Upgraded from 2.1.25 this morning...)

### Client configuration
**Browser:** Chrome, Firefox, Edge

**Operating system:** W 10

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
----------------------------------------
Error: Field 'pw_len' doesn't have a default value<br>
Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login
`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('TEST TP', 'Test
 TeamPass', '6551540bf12403421611ab045bd9e9e4', '8815e3731341ac729f89042fde3ad82a', '', '', '28', 'TESTP'
, '0', '', '0', '0', '45')<br>
---------------------------------------
http://xxx.xxxx.xxxx/sources/items.queries.php?9b9838d8be13bcc9a2d2ccddd058f02d317714bfc1d152f027=8d9095840441290085c6fccf9c81f5d30059df2d8af5cc57b1&data=jksbWHJycnJ6HSH15RqgRFUuXRgazpa4MnETnDjKWuWi9kvzi1k7jSYjydt1iNz5dtcgb6WuuRbCJ4KArIzRwkje4Q0mV8JUqmCQcnrI35x5A59OKzjyEiCTT%2F8upNqRkIS53TWaxK%2Bft8dNMVIwIDqX2gLyj%2Br2nRVgf5Uo%2FLxhRwLhGzvUW%2Bzd%2BGQepRpLjuR9lk5poNSZz9o6fNSphskGTuuaDhVMV%2BdqGmV5hw5b3y3pohA7F8l5Ipsl09LaZeyvi9yuDz6VFZn94hFAeS3YXEWqdvWHJgeERr16WQyEf0geKGOyroE7ENRUey8JC1JEqmrJbbYTKHawu9ttPYB5DtVYjvS%2Fy7ZBu3F%2BXQ8NW5Ici9CQeN206lN0Ndg6a6DImC7KWbRj6gglleBGheHtWqj%2BZ%2FHsXJ564CbRN6SYj0f5Yh%2FmK2yH6J5FTlESJ0zHhTITqFrdtTzgjyYJbqULanENqav4bdy8RhTb1t8LWJ%2FVmqLwHoYN47uhrWRf&key=ezeigaenuroojo7anai4ahsai7uni3eeVai6biu7Ahie4quoh0&type=new_item

**Comment by nilsteampassnet** [comment]
In phpmyadmin (or similar) select the table 'items'.

Search pw_len field and set 0 as a default value.

**Comment by SylvainGuibert** [comment]
Good ! Issue is solved. thx !
