### ISSUE TITLE
identify.php returns zero-length response -- can't log in!

### ISSUE THREAD

**Issue by Epi-JJones** [nilsteampassnet/TeamPass#1568]
### Steps to reproduce
1. Attempt to sign into TeamPass with valid username/password
2. Observe developer tools XHR request for "identify.php"

### Expected behaviour
Normal response should be returned, and user should be logged in

### Actual behaviour
identify.php returns with status code 200, and "Content-Length: 0" (and no content). There are no errors in Apache or PHP logs, and nothing in the browser console.

This started happening after running an `apt-get update`; subsequent attempts to remove/reinstall PHP, Apache, and/or modules have not yielded any results.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySQL 5.5.53

**PHP version:** 5.5.9

**Teampass version:** 2.1.22

**Updated from an older Teampass or fresh install:** Don't remember

### Client configuration
**Browser:** Google Chrome 54.0.2840.71

**Operating system:** Mac OS 10.11.5

#### Web server error log
```
No errors in apache or PHP logs
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
No console errors or other output
```

#### Response header for /sources/identify.pp
```
HTTP/1.1 200 OK
Date: Fri, 04 Nov 2016 21:43:37 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.20
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

**Comment by nilsteampassnet** [comment]
You perhaps have a php extension that is not loaded any more.
Have you checked this?

**Comment by Epi-JJones** [comment]
The following extensions are loaded (as per `phpinfo()`)

```
mcrypt support			enabled
mcrypt_filter support	enabled
Version					2.5.8

Multibyte Support		enabled
Multibyte string engine	libmbfl
HTTP input encoding translation	disabled
libmbfl version			1.3.2

OpenSSL support			enabled
OpenSSL Library Version	OpenSSL 1.0.1f 6 Jan 2014
OpenSSL Header Version	OpenSSL 1.0.1f 6 Jan 2014

GD Support				enabled
GD Version				2.1.1-dev

BCMath support			enabled

iconv support			enabled
iconv implementation	glibc
iconv library version	2.19

XML Support				active
XML Namespace Support	active
libxml2 Version			2.9.1
```

According to the requirements page, that's everything that's needed, so I don't think it has to do with extensions. Is there anything else I can check?

**Comment by Epi-JJones** [comment]
Anything? Our passwords are effectively inaccessible because of this issue. I've tried upgrading, downgrading, reinstalling (libraries/etc as well as TeamPass)... have gotten nowhere.

**Comment by Epi-JJones** [comment]
Is there anything we can do to at least recover the passwords manually or something (we have full access to the server, and know the login accounts/passwords)? It's been almost a month since I provided the requested information 😞

**Comment by nilsteampassnet** [comment]
IT is difficult to give an advice there as it seems to be related to the server configuration.
Have you tried on a local WAMPserver for example if you get this issue?
