### ISSUE TITLE
Langue par défaut

### ISSUE THREAD

**Issue by QIONIS** [nilsteampassnet/TeamPass#1569]
### Steps to reproduce
1. Quand je sélectionne la langue "french" je n'ai aucune validation. Malgré que je le sélectionne quand je change de page et je retourne dedans la langue est revenu sur "english"

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Debian 8

**Web server: XAMPP

**Database: XAMPP

**PHP version: 5.6.5

**Teampass version: 2.1.26 Patch 1

**Updated from an older Teampass or fresh install: Fresh install

### Client configuration
**Browser: Chrome et Firefox

**Operating system: Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Very strange behavior.

When you are connected and that you change the language, you should be disconnected.

Then once reloged, Teampass is reloaded with the selected language.

If this is not the case, you should have some error logs somewhere on your server. Can you please share?

**Comment by drmanu33** [comment]
Hi,

I have the same issue.
I used this workaround ;-)

mysql> update teampass_misc set valeur = 'french' where intitule = 'default_language';

**Comment by QIONIS** [comment]
Thanks for your reply.

Regards,
De : drmanu33 [mailto:notifications@github.com]
Envoyé : mardi 8 novembre 2016 10:07
À : nilsteampassnet/TeamPass <TeamPass@noreply.github.com>
Cc : Patrick TEIXEIRA <p.teixeira@qionis.fr>; Author <author@noreply.github.com>
Objet : Re: [nilsteampassnet/TeamPass] Langue par défaut (#1569)


Hi,

I have the same issue.
I used this workaround ;-)

mysql> update teampass_misc set valeur = 'french' where intitule = 'default_language';

**Comment by alebupal** [comment]
@nilsteampassnet 

- Does not work in this option http://image.prntscr.com/image/3a0b6ca897eb42e58b0333b5694a2000.png

- This option works http://image.prntscr.com/image/f048c1f34bc9477c84dbe56b0fcc184b.png

**Comment by nilsteampassnet** [comment]
THis is corrected in 2.1.27
