### ISSUE TITLE
 Server connection is impossible ... check your Internet/firewall configuration

### ISSUE THREAD

**Issue by Loktis** [nilsteampassnet/TeamPass#1570]
### Steps to reproduce
1. Connect
2. Wait
3. See the error instead of items list

### Expected behaviour
The items list should be displayed

### Actual behaviour
We have an error :
-->  Server connection is impossible ... check your Internet/firewall configuration

### Server configuration
**Operating system**:
Debian Jessie 8

**Web server:**
Apache 2

**Database:**
10.0.27-MariaDB

**PHP version:**
PHP 5.6.27

**Teampass version:** 
TeamPass 2.1.26  2009 - 2016 

**Updated from an older Teampass or fresh install:**
Fresh install 

### Client configuration
**Browser:**
Mozilla Firefox 49.0.1

**Operating system:**
Archlinux

#### Web server error log
```
Nothing 
```
#### Firebug log
```

After 1 min : 
Méthode Post 
http://monserv/teampass/TeamPass/sources/admin.queries.php

return this : 
[{"error":"connection" , "output":""}]
```

Cordially,
Loowkis

**Comment by nilsteampassnet** [comment]
This message error is not displayed on the Items page but on admin information page.
It occurs when it was not possible to connect to Teampass server.
You can disable this through settings page
![image](https://cloud.githubusercontent.com/assets/1197546/20075796/08f8bb20-a536-11e6-8828-4fcec1c91fef.png)
It will disable the check and a message is displayed instead
![image](https://cloud.githubusercontent.com/assets/1197546/20075823/22682776-a536-11e6-9de5-35e710d27bdc.png)

**Comment by Loowkis** [comment]
Thanks for the quick reply, my bad didn't see the option.

**I have another problem :** 

I haven't the menu icons to access the folders to create credentials.
I created a folder test and a role test assigned to a user test but nothing.
When I login I haven't the icons to display the items.

Could you help me please ? 

**The following screen  :**

![menulist](https://cloud.githubusercontent.com/assets/20761117/20104128/1060dfc2-a5cd-11e6-9d2a-5ce7c368ea81.png)

**Comment by qubez** [comment]
Administrators cannot see password items. You must create and login as a standard user, with appropriate permissions (edit the user after creating), to create passwords in folders.

**Comment by Loowkis** [comment]
Ok I'll try. But I think I already tried it. I'm coming back to you after this test.
