### ISSUE TITLE
Create items out of personal folder fails

### ISSUE THREAD

**Issue by Libeccio84** [nilsteampassnet/TeamPass#1571]
Hi all,
I am new to teampass and I am currently running version 2.1.26-RC1. I am experiencing problems in creating items out of personal folder chosing "Add item" from personal folder.
Indeed I created a folder "First" under root as admin and I gave r/w grants to a test user (myself). 

![screen shot 2016-11-07 at 18 20 26](https://cloud.githubusercontent.com/assets/23318355/20067709/91b510aa-a516-11e6-8067-b71fbe357490.png)

Once logged in as the test user, I can add items in "First" from the menu

![screen shot 2016-11-07 at 18 14 18](https://cloud.githubusercontent.com/assets/23318355/20067508/b61d9eb8-a515-11e6-8741-9200c6275905.png)

only while I am in the "First" folder itself, but if I open the same menu from my personal folder and I chose "First" from the dropdown menu as below

![screen shot 2016-11-07 at 18 18 29](https://cloud.githubusercontent.com/assets/23318355/20067649/4a58cb2a-a516-11e6-8990-b7b8c3e68f57.png)

the item is created in my folder regardless the chosen folder. A subsequent drag and drop of the item makes it unreadable and unrecoverable. Any idea?

Thanks in advance

**Comment by nilsteampassnet** [comment]
You detected a bug.

In sources/items.queries.php, replace
```
                $encrypt = cryption(
                    $decrypt,
                    mysqli_escape_string($link, stripslashes($_SESSION['my_sk'])),
                    "",
                    "encrypt"
                );
```
by
```
                $encrypt = cryption(
                    $decrypt['string'],
                    mysqli_escape_string($link, stripslashes($_SESSION['my_sk'])),
                    "",
                    "encrypt"
                );
```

and

```
                $encrypt = cryption(
                    $decrypt,
                    SALT,
                    "",
                    "encrypt"
                );
```
by
```
                $encrypt = cryption(
                    $decrypt['string'],
                    SALT,
                    "",
                    "encrypt"
                );
```

**Comment by Libeccio84** [comment]
Many thanks for the fast reply.
Now I can move items between my personal folder and an external one, but moving it back makes it unreadable and unrecoverable again.
I am sorry to say that creating an item as described above shows the same issue...

**Comment by Libeccio84** [comment]
Hi Nils, I have just installed the development version with the fix, now it looks like I am not able to store items in my personal folder.
I don't know if it might help you, but my profile is "Human Resources"+"Create folder @ root level".
Sorry... :(

**Comment by nilsteampassnet** [comment]
What are the error message you get? What is the Firebug message when the query fails? What is the steps to reproduce?

**Comment by Libeccio84** [comment]
I simply try to create a new item in my personal folder having the wrights to do that.
These screenshot should provide the information you asked me.

1. dneri user privileges
![screen shot 2016-11-18 at 09 22 00](https://cloud.githubusercontent.com/assets/23318355/20423494/da9533ce-ad70-11e6-911a-9c289fe9c6b9.png)

2. Creating the item in my personal folder
![screen shot 2016-11-18 at 09 22 27](https://cloud.githubusercontent.com/assets/23318355/20423510/fbe0ec76-ad70-11e6-8076-296d98033408.png)

3. Error message after confirm
![screen shot 2016-11-18 at 09 22 49](https://cloud.githubusercontent.com/assets/23318355/20423525/117fd3ee-ad71-11e6-882b-36f1b957e7c7.png)

Moreover I am running a CentOS 7 VM with php7.

Hope this might help you. Many thanks again.
