### ISSUE TITLE
Utilities -> Logs -> Items - Error Pop-Up

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1574]
### Steps to reproduce
1. Login as Admin
2. Open Utilities -> Logs -> Items
3. Error pop-up will shows

### Expected behaviour
Show Items

### Actual behaviour
Error Pop-UP : DataTables warning: table id=t_items - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.5.49

**PHP version:** PHP 5.5.9-1ubuntu4.17

**Teampass version:** 2.1.26 Final 2

**Updated from an older Teampass or fresh install:** Updated from 2.1.26 (20)

### Client configuration
**Browser:** FF, IE

**Operating system:** Windows 10 Ent x64

#### Web server error log
```
[Mon Nov 14 23:07:43.010719 2016] [core:notice] [pid 41219] AH00051: child pid 62699 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Mon Nov 14 23:08:35.745203 2016] [:error] [pid 47505] [client 192.168.10.24:60861] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/install/upgrade.php
[Mon Nov 14 23:08:35.887646 2016] [:error] [pid 47505] [client 192.168.10.24:60861] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Mon Nov 14 23:08:47.998800 2016] [:error] [pid 62704] [client 192.168.10.24:60872] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 14 23:08:53.670355 2016] [:error] [pid 62694] [client 192.168.10.24:60873] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_main
[Mon Nov 14 23:08:57.722524 2016] [:error] [pid 62694] [client 192.168.10.24:60873] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1024 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Mon Nov 14 23:09:02.508878 2016] [:error] [pid 1083] [client 192.168.10.24:60875] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Mon Nov 14 23:09:14.898178 2016] [:error] [pid 1083] [client 192.168.10.24:60879] PHP Fatal error:  Cannot redeclare class CryptSession in /var/www/html/teampass/sources/sessions.php on line 15, referer: https://teampass/index.php?page=manage_views
[Mon Nov 14 23:09:15.106247 2016] [core:notice] [pid 41219] AH00051: child pid 1083 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Mon Nov 14 23:09:21.113406 2016] [:error] [pid 62800] [client 192.168.10.24:60880] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Mon Nov 14 23:09:50.491623 2016] [:error] [pid 47505] [client 192.168.10.24:60884] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_views
[Mon Nov 14 23:21:03.808505 2016] [:error] [pid 62704] [client 192.168.10.24:60921] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_settings
[Mon Nov 14 23:21:04.318887 2016] [:error] [pid 62704] [client 192.168.10.24:60921] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Mon Nov 14 23:21:10.788995 2016] [:error] [pid 63141] [client 192.168.10.24:60933] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 14 23:21:12.099310 2016] [:error] [pid 62800] [client 192.168.10.24:60937] PHP Fatal error:  Cannot redeclare class CryptSession in /var/www/html/teampass/sources/sessions.php on line 15, referer: https://teampass/index.php?page=items
[Mon Nov 14 23:21:12.473841 2016] [core:notice] [pid 41219] AH00051: child pid 62800 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Mon Nov 14 23:21:30.831637 2016] [:error] [pid 62604] [client 192.168.10.24:60941] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_settings
[Mon Nov 14 23:21:30.951001 2016] [:error] [pid 62604] [client 192.168.10.24:60941] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Mon Nov 14 23:21:40.459315 2016] [:error] [pid 1281] [client 192.168.10.24:60942] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 14 23:21:53.664730 2016] [:error] [pid 945] [client 192.168.10.24:60949] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 14 23:21:53.879323 2016] [:error] [pid 945] [client 192.168.10.24:60949] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Tue Nov 15 08:39:23.388715 2016] [:error] [pid 62604] [client 192.168.10.79:54288] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Tue Nov 15 08:39:23.480149 2016] [:error] [pid 62604] [client 192.168.10.79:54288] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Tue Nov 15 08:40:02.360398 2016] [:error] [pid 1285] [client 192.168.10.79:54291] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Tue Nov 15 08:40:03.280084 2016] [:error] [pid 62694] [client 192.168.10.79:54289] PHP Fatal error:  Cannot redeclare class CryptSession in /var/www/html/teampass/sources/sessions.php on line 15, referer: https://teampass/index.php?page=items
[Tue Nov 15 08:40:04.354328 2016] [core:notice] [pid 41219] AH00051: child pid 62694 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Nov 15 08:45:59.205933 2016] [:error] [pid 48307] [client 192.168.10.24:63724] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Tue Nov 15 08:45:59.249549 2016] [:error] [pid 48307] [client 192.168.10.24:63724] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Tue Nov 15 08:46:03.768413 2016] [:error] [pid 48307] [client 192.168.10.24:63724] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Tue Nov 15 08:54:10.453539 2016] [:error] [pid 62704] [client 192.168.10.24:64360] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Tue Nov 15 08:54:10.564815 2016] [:error] [pid 62704] [client 192.168.10.24:64360] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Tue Nov 15 08:54:13.382888 2016] [:error] [pid 1285] [client 192.168.10.24:64364] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Tue Nov 15 08:54:16.652616 2016] [:error] [pid 1282] [client 192.168.10.24:64374] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Tue Nov 15 08:54:16.719501 2016] [:error] [pid 1282] [client 192.168.10.24:64374] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Tue Nov 15 08:54:22.446226 2016] [:error] [pid 62706] [client 192.168.10.24:64378] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Tue Nov 15 08:54:27.934342 2016] [:error] [pid 62704] [client 192.168.10.24:64379] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_main
[Tue Nov 15 08:54:41.356561 2016] [:error] [pid 1282] [client 192.168.10.24:64393] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=manage_settings
[Tue Nov 15 08:54:44.698143 2016] [:error] [pid 1282] [client 192.168.10.24:64393] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 75 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Tue Nov 15 08:56:00.500004 2016] [:error] [pid 6770] [client 192.168.10.24:64487] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 75 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Cache-Control : no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection : close
Content-Length : 0
Content-Type : text/html; charset=utf-8
Date	: Tue, 15 Nov 2016 06:54:44 GMT
Expires : Thu, 19 Nov 1981 08:52:00 GMT
Pragma : no-cache
Server : Apache/2.4.7 (Ubuntu)
X-Powered-By : PHP/5.5.9-1ubuntu4.17

https://teampass/sources/datatable/datatable.logs.php?action=items&sEcho=1&iColumns=5&sColumns=%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&sSearch=&bRegex=false&iSortCol_0=1&sSortDir_0=asc&iSortingCols=1&_=1479192882636
```

**Comment by nilsteampassnet** [comment]
I don't have the issue but I think I'm not in the same configuration as you.
You seem to have enabled HTTPS option.

Regarding your error log, I see that a php notice is on $cert_issuer variable.

In file sources/core.php, find
````
    $server_cert=openssl_x509_parse($_SERVER['SSL_SERVER_CERT']);
    $cert_name=$server_cert['name'];
    foreach ($server_cert['issuer'] as $key => $value) {
```
replace by
````
    $server_cert=openssl_x509_parse($_SERVER['SSL_SERVER_CERT']);
    $cert_name=$server_cert['name'];
    $cert_issuer = "";
    foreach ($server_cert['issuer'] as $key => $value) {
```

I can see also a redeclaration
In file sources/sessions.php, find
````
new CryptSession();
```
replace by
````
if(!class_exists('CryptSession')) {
    new CryptSession();
}
```

**Comment by reginfo** [comment]
Hello. 
I have made changes to these files but error still occurs. =(
`https://teampass/sources/datatable/datatable.logs.php?action=items&sEcho=1&iColumns=5&sColumns=%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&sSearch=&bRegex=false&iSortCol_0=1&sSortDir_0=asc&iSortingCols=1&_=1479711372325`

`Cache-Control : no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection : close
Content-Length : 0
Content-Type : text/html; charset=utf-8
Date	: Mon, 21 Nov 2016 06:56:27 GMT
Expires : Thu, 19 Nov 1981 08:52:00 GMT
Pragma : no-cache
Server : Apache/2.4.7 (Ubuntu)
X-Powered-By : PHP/5.5.9-1ubuntu4.17`

`[Sun Nov 20 06:41:51.770457 2016] [ssl:warn] [pid 41219] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Sun Nov 20 06:41:51.770533 2016] [mpm_prefork:notice] [pid 41219] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Nov 20 06:41:51.770539 2016] [core:notice] [pid 41219] AH00094: Command line: '/usr/sbin/apache2'
[Sun Nov 20 13:43:05.284597 2016] [:error] [pid 9377] [client 192.168.10.24:50768] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Sun Nov 20 13:43:05.335292 2016] [:error] [pid 9377] [client 192.168.10.24:50768] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Sun Nov 20 13:43:20.818757 2016] [:error] [pid 13413] [client 192.168.10.24:50783] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Sun Nov 20 13:43:21.649356 2016] [:error] [pid 9378] [client 192.168.10.24:50792] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Sun Nov 20 13:43:26.651920 2016] [:error] [pid 9376] [client 192.168.10.24:50784] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Sun Nov 20 13:43:36.720682 2016] [:error] [pid 13414] [client 192.168.10.24:51086] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Sun Nov 20 14:43:33.527184 2016] [:error] [pid 13718] [client 192.168.10.24:53713] PHP Notice:  Undefined index: settings in /var/www/html/teampass/index.php on line 110, referer: https://teampass/index.php?session=expired
[Sun Nov 20 14:43:33.527226 2016] [:error] [pid 13718] [client 192.168.10.24:53713] PHP Warning:  require_once(/includes/language/english.php): failed to open stream: No such file or directory in /var/www/html/teampass/index.php on line 110, referer: https://teampass/index.php?session=expired
[Sun Nov 20 14:43:33.527237 2016] [:error] [pid 13718] [client 192.168.10.24:53713] PHP Fatal error:  require_once(): Failed opening required '/includes/language/english.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/teampass/index.php on line 110, referer: https://teampass/index.php?session=expired
[Mon Nov 21 08:34:34.065019 2016] [:error] [pid 9378] [client 192.168.10.24:49698] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php
[Mon Nov 21 08:34:39.212601 2016] [:error] [pid 9378] [client 192.168.10.24:49698] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 21 08:46:53.109794 2016] [:error] [pid 13418] [client 192.168.10.79:54981] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279
[Mon Nov 21 08:46:53.164640 2016] [:error] [pid 13418] [client 192.168.10.79:54981] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/
[Mon Nov 21 08:47:02.235877 2016] [:error] [pid 13413] [client 192.168.10.79:54985] PHP Notice:  Undefined variable: cert_issuer in /var/www/html/teampass/sources/core.php on line 279, referer: https://teampass/index.php?page=items
[Mon Nov 21 08:54:29.941801 2016] [:error] [pid 24616] [client 192.168.10.24:50590] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 93 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Mon Nov 21 08:54:40.764069 2016] [:error] [pid 13418] [client 192.168.10.24:50597] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 93 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
zend_mm_heap corrupted
[Mon Nov 21 08:55:49.241750 2016] [core:warn] [pid 41219] AH00045: child process 13418 still did not exit, sending a SIGTERM
[Mon Nov 21 08:55:51.243838 2016] [core:warn] [pid 41219] AH00045: child process 13418 still did not exit, sending a SIGTERM
[Mon Nov 21 08:55:52.244951 2016] [core:notice] [pid 41219] AH00051: child pid 13418 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Mon Nov 21 08:55:52.245007 2016] [mpm_prefork:notice] [pid 41219] AH00169: caught SIGTERM, shutting down
[Mon Nov 21 08:55:52.952468 2016] [ssl:warn] [pid 24671] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Nov 21 08:55:52.972951 2016] [ssl:warn] [pid 24672] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Nov 21 08:55:52.974954 2016] [mpm_prefork:notice] [pid 24672] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Nov 21 08:55:52.974968 2016] [core:notice] [pid 24672] AH00094: Command line: '/usr/sbin/apache2'
[Mon Nov 21 08:56:19.723721 2016] [:error] [pid 24684] [client 192.168.10.24:50676] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
[Mon Nov 21 08:56:27.515823 2016] [:error] [pid 24688] [client 192.168.10.24:50693] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 669, referer: https://teampass/index.php?page=manage_views
`

**Comment by nilsteampassnet** [comment]
Yes sure it is related to this as we can see in the logs . 
Now how to solve requires time to read code and experimentation that I cannot do I have no way to test it. 
Perhaps can you suggest your screen with me?

**Comment by reginfo** [comment]
So, I repair "PHP Fatal error: Allowed memory size of...." error. No I can see Items. But I receive a new error when I trying to log out from admin profile. 
**https://teampass/logout.php -  [HTTP/1.0 500 Internal Server Error 15m]**

Yes, we can do Remote Session when you will have time.

**Comment by fiskn** [comment]
I had just had this issue and I fixed it by bumping up the php memory size in my php.ini
