### ISSUE TITLE
TypeError: k[c[o].parent.toString(...)] is undefined

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1575]
### Steps to reproduce
1. Open teampass as user
2.
3.

### Expected behaviour
Folders tree should be displayed

### Actual behaviour
Tree keeps loading and no folders show up

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6
**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
Fresh
### Client configuration
**Browser:**
Firefox, Edge
**Operating system:**
Windows
#### Web server error log
```
Insert your webserver log here
```
No errors in webserver log, all request are 200 OK.

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```
Firefox console shows error: 
TypeError: k[c[o].parent.toString(...)] is undefined

Looks like jquery doesn't know how to parse input from database or something strange is returned.

**Comment by tehnotronic** [comment]
[http://i.imgur.com/YaVKBI9.png](http://i.imgur.com/YaVKBI9.png)

**Comment by nilsteampassnet** [comment]
Difficult to help here. I don't see in what file the error is. 
This basic feature is always tested. So I'm wondering if you have any special setting for this user? 
Are all users impacted?

**Comment by tehnotronic** [comment]
So I went deep, upgraded to current development. Only some users are affected. The reason is roles matching to folders. If a role has read or write access to level 3 folder, but not to level 1, the tree is not loaded. For example I have folders:
1) linux servers
1.1) production
1.1.1) file_share
2) windows

If my role has access to linux or windows, folder tree is loaded. If my role has only access to file_share and not to linux_server, tree is not loaded. If I give access to whole linux servers, everything is ok.
I see this as a bug, because some users should only have access to subfolders and not to first level folders also.

**Comment by nilsteampassnet** [comment]
Strange, I've tried similar context.
Here is the config for user "Jean" in group "Users"
![image](https://cloud.githubusercontent.com/assets/1197546/20365574/9fc48ab2-ac47-11e6-8c40-e2675133ad1e.png)

Now when Jean is connected, he sees this
![image](https://cloud.githubusercontent.com/assets/1197546/20365483/55371190-ac47-11e6-977a-5b281d4eaf41.png)

I have some difficulties to understand this error you get.
Can you also provide the result of the query that loads the tree?

**Comment by tehnotronic** [comment]
This is my output of tree.php when it only shows the loading ring and no tree content:
`[{"id":"li_2", "parent":"#", "text":"user (<span class='items_count' id='itcount_2'>0</span>|0|0)"
, "li_attr":{"class":"jstreeopen", "title":"ID [2] "}, "a_attr":{"id":"fld_2", "class":"folder" , "onclick"
:"ListerItems('2', '0', 0)", "ondblclick":"LoadTreeNode('2')"}}, {"id":"li_38", "parent":"#", "text"
:"Linux (<span class='items_count' id='itcount_38'>2</span>|2|1)", "li_attr":{"class":"jstreeopen"
, "title":"ID [38] "}, "a_attr":{"id":"fld_38", "class":"folder" , "onclick":"ListerItems('38', '0',
 0)", "ondblclick":"LoadTreeNode('38')"}}, {"id":"li_50", "parent":"li_38", "text":"Samba servers 
(<span class='items_count' id='itcount_50'>0</span>|0|0)", "li_attr":{"class":"jstreeopen", "title":"ID
 [50] "}, "a_attr":{"id":"fld_50", "class":"folder" , "onclick":"ListerItems('50', '0', 0)", "ondblclick"
:"LoadTreeNode('50')"}}, {"id":"li_43", "parent":"li_30", "text":"<i class='fa fa-eye'></i>&nbsp;Some Lv3 folder
 (<span class='items_count' id='itcount_43'>0</span>|0|0)", "li_attr":{"class":"jstreeopen", "title"
:"ID [43] Ainult vaatamiseks"}, "a_attr":{"id":"fld_43", "class":"folder_not_droppable" , "onclick":"ListerItems
('43', '1', 0)", "ondblclick":"LoadTreeNode('43')"}}]`

**Comment by nilsteampassnet** [comment]
I think the error is somewhere else as this json array is perfectly formed.
So it cannot be the source of the issue you have.

Can you share your screen with me for better debug?

**Comment by tehnotronic** [comment]
Ok, it seems like a jstree timing issue reported here: http://stackoverflow.com/questions/38520980/jstree-cannot-read-property-children-of-undefined-timing-issue 
Maybe the issue is that tree.php loading takes 10 seconds and I have to speed it up somehow?
http://i.imgur.com/b6KMEtR.png

**Comment by nilsteampassnet** [comment]
Perhaps a direction to investigate.

I will try to put some "pauses" in the script to reproduce this long tree load.

**Comment by nilsteampassnet** [comment]
I finally could reproduce.
THis issue doesn't appear if option "Hide inaccessible password folders" is set to NO.

With the last commit, it is corrected.
Please test and tell me.

**Comment by tehnotronic** [comment]
Confirmed, fixed. Thank you!
