### ISSUE TITLE
why "No SSL in docker container"

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#1576]
In https://github.com/nilsteampassnet/TeamPass#docker-installationuse you explain that there is no ssl support in the docker container?

Why is it that way?

In this one https://hub.docker.com/r/appcontainers/teampass/ is ssl encryption supported, but it has not that up-to-date builds like the official ones?

Is this something that will change in the future?

**Comment by nilsteampassnet** [comment]
I'm not the owner of this docker repo. Perhaps can you add a comment directly on the docker page? 
I will try to help if I can
