### ISSUE TITLE
Wrong column name: `$pre_users`.`IsAdministratedByRole`

### ISSUE THREAD

**Issue by nixargh** [nilsteampassnet/TeamPass#1578]
I done upgrade from '2.1.25' to '2.1.26 + #1550'. 
Then I saw an error at the user management interface and found an error at apache log:
`PHP Notice:  Undefined index: isAdministratedByRole in /var/www/password.domain.com/sources/datatable/datatable.users.php on line 225, referer: https://password.domain.com/index.php?page=manage_users
`

During investigation I found a discrepancy between column name at code and database:
'IsAdministratedByRole' instead of 'isAdministratedByRole'  (capital letter 'I').

Rename of the column solved my issue, so it's just for the record.

P.S. Also I upgraded from php5.4 to php5.5, maybe it's related somehow.

**Comment by nilsteampassnet** [comment]
Thanks for reporting.
Just added a check in upgrade process to ensure correct naming.
