### ISSUE TITLE
Can't change users roles after upgrade

### ISSUE THREAD

**Issue by nixargh** [nilsteampassnet/TeamPass#1579]
I done upgrade from '2.1.25' to '2.1.26 + #1550'.
Also I upgraded from php5.4 to php5.5, maybe it's related somehow.

Under user admin my UI got stuck when I tried to do some change at 'Manage User' page.
Apache error was:
`PHP Fatal error:  Can't use function return value in write context in /var/www/password..domain.com/sources/users.queries.php on line 30, referer: https://password..domain.com/index.php?page=manage_users`

Please consider to add my monkey patch or maybe you know the better way.
Here is patch I used to make it works: [monkey patch](https://gist.github.com/nixargh/0171c098d23ce2491802b7ebacd1c680)

**Comment by nilsteampassnet** [comment]
Strange that you get this error and not others.

I totally understand why you have this error but don't understand why on my test environment, it is not shown. I'm using php 7.0.1 and .5.6.19.

I've changed this .

Thanks for reporting
