### ISSUE TITLE
File Upload security problem. More filename sanitization needed.

### ISSUE THREAD

**Issue by nunompad** [nilsteampassnet/TeamPass#1580]
### Steps to reproduce
1. upload a special string to the profile photo and you will be Administrator.

### Expected behaviour
The expected behaviour is to say that the file name is invalid.

### Actual behaviour
The user that execute this post, will became Administrator.

### Server configuration
**Operating system**:
Linux Fedora 24

**Web server:**
Apache 2.4

**Database:**
Mysql

**PHP version:**
php 5.6

**Teampass version:** 
2.1.26

**Comment by nilsteampassnet** [comment]
THanks for reporting this.

Can you please confirm that next changes solves this issue?

In file, **sources/upload/upload.files.php**, find
```
$fileName = isset($_REQUEST["name"]) ? $_REQUEST["name"] : '';
```
by
```
$fileName = isset($_REQUEST["name"]) ? filter_var($_REQUEST["name"], FILTER_SANITIZE_STRING) : '';
```

In file, **sources/upload/upload.files.php**, find
```
$file_name = preg_replace('[^'.$valid_chars_regex.']', '', strtolower(basename($_FILES['file']['name'])));
```
by
```
$file_name = preg_replace(
    '[^'.$valid_chars_regex.']',
    '',
    filter_var(
        strtolower(basename($_FILES['file']['name'])),
        FILTER_SANITIZE_STRING
    )
);
```

In file, **sources/profile.php**, find
```
                    "PHPSESSID":"<?php echo $_SESSION['user_id'];?>",
                    "fileName":file.name,
                    "newFileName":"user<?php echo $_SESSION['user_id'];?>"+tmp,
```
by
```
                    "PHPSESSID":"<?php echo $_SESSION['user_id'];?>",
                    "newFileName":"user<?php echo $_SESSION['user_id'];?>"+tmp,
```

**Comment by nunompad** [comment]
Hi there is issue is remains, if you set the file name to something like this {"filename" : "x', admin=1 -- .png"} you will be admin in teampass.

**Comment by nilsteampassnet** [comment]
OK my regex was not complete.

In file sources/upload/upload.file.php, replace `'[^'.$valid_chars_regex.']'` by `'/[^'.$valid_chars_regex.'\.]/'`.

It sanitizes correctly the name.

**Comment by nunompad** [comment]
Hi there the problem is on the function _upload_profile_photo_ and the _$_POST['newFileName']_ is not sanitized so maybe same thing like this will help:

} else if (isset($_POST["type_upload"]) && $_POST["type_upload"] == "upload_profile_photo") {
    $ext = pathinfo($filePath, PATHINFO_EXTENSION);
    **$_POST['newFileName'] = preg_replace('/[^'.$valid_chars_regex.'\.]/', '', strtolower(basename($_POST['newFileName'])));**
    rename($filePath, $targetDir . DIRECTORY_SEPARATOR . $_POST['newFileName'] . '.' . $ext);

**Comment by nunompad** [comment]
I there, sorry for the late reply, the problem is still there:
In the db update should be $newFileName and not $_POST['newFileName'].
Tks.

    // store in DB the new avatar
    DB::query(
        "UPDATE ".$pre."users
        SET avatar='".**$_POST['newFileName']** . '.' . $ext."', avatar_thumb='".$newFileName ."_thumb" . '.' . $ext."'
        WHERE id=%i",
        $_SESSION['user_id']
    );

**Comment by nilsteampassnet** [comment]
Yes absolutely ... sorry for this.
I will commit the change
