### ISSUE TITLE
TeamPass Search Problem

### ISSUE THREAD

**Issue by Obus20** [nilsteampassnet/TeamPass#1582]
### Steps to reproduce
1. Update to Version 2.1.26
2. Search for newer passwords
3.

### Expected behaviour
In our installation we expect that we cannot find newer passwords over the search

### Actual behaviour
No results in the search are displayed

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2 2.4.10-10+deb8u7

**Database:** MySQL 5.5.53-0+deb8u1

**PHP version:** PHP5 5.6.27+dfsg-0+deb8u1

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** Updated from 2.1.18

### Client configuration
**Browser:** Chrome

**Operating system:** Win8

#### Web server error log
No error in the logs

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
No error in Chrome log

Thank you!

**Comment by Obus20** [comment]
It looks like only the cached items are in the search.

**Comment by nilsteampassnet** [comment]
Yes it is based upon cache table.

But when creating a new item, each new item is added to cache table.

If you just upgraded, perhaps need you to run "admin task" called rebuild cache table.

**Comment by Obus20** [comment]
Can I start that task also from the server? Because it does not work if I start it from the browser.

**Comment by Obus20** [comment]
Errors in error.log when I try to rebuild that tables:

[Wed Nov 23 13:13:09.926663 2016] [:error] [pid 15549] [client X.X.X.X:26134] PHP Notice:  Undefined variable: link in /var/www/teampass.kl.int/public_html/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: https://teampass.kl.int/index.php?page=manage_settings
[Wed Nov 23 13:13:09.926974 2016] [:error] [pid 15549] [client X.X.X.X:26134] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/teampass.kl.int/public_html/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: https://teampass.kl.int/index.php?page=manage_settings
[Wed Nov 23 13:13:09.951410 2016] [:error] [pid 15486] [client X.X.X.X:26128] PHP Notice:  Undefined variable: link in /var/www/teampass.kl.int/public_html/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: https://teampass.kl.int/index.php?page=manage_settings
[Wed Nov 23 13:13:09.951551 2016] [:error] [pid 15486] [client X.X.X.X:26128] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/teampass.kl.int/public_html/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: https://teampass.kl.int/index.php?page=manage_settings

Thank you!

**Comment by nilsteampassnet** [comment]
Please go down this error log, you will see a query error including the
query performed on the server.
This is the information I need.
Or you can send me the error log file.


----
*Nils @ teampass.net <http://teampass.net>*
*Teampass *- *A collaborative passwords manager*
Visit Teampass.net
Visit Github repository <https://github.com/nilsteampassnet/TeamPass>


2016-11-23 13:15 GMT+01:00 Obus20 <notifications@github.com>:

**Comment by Obus20** [comment]
I don't see more information in the error log. It only shows the errors above and I can see the loading gear untill I'm getting logged off.

Does that help or can I find the query error you need in another way?

Thank you!

**Comment by nilsteampassnet** [comment]
Please use Firebug and its console.
You will have a complete report.
I'm pretty sure it is realated a special data you have in one of the item.
So the query fails. And this query is normally displayed at the very bottom of the error send back from the server

**Comment by Obus20** [comment]
Could it be something like that?

Error: Column 'id_tree' cannot be null<br>
Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`url`,`tags`,`id_tree`,`perso`,`restricted_to
`,`login`,`folder`,`author`,`renewal_period`,`timestamp`) VALUES ('523', 'adminuser', '', '0', '', NULL
, '1', '0', 'adm-kl-XXXXXX', '', '29', '0', '1361435289')<br>

**Comment by Obus20** [comment]
I deleted all the passwords with id_tree Null. That solves the issue. 

Thank you very much for your help!
