### ISSUE TITLE
TeamPass session timeout is +hours for timezone

### ISSUE THREAD

**Issue by brianara3** [nilsteampassnet/TeamPass#1583]
### Steps to reproduce
1. Install TeamPass 2.1.26-patch-1 on a server in non-UTC timezone (I assume)
2. Login to TeamPass
3. See session time remaining doesn't match login page setting.

### Expected behaviour
Session timeout should reflect remainder of time specified on login page. (ie. 60 min minus session time)

### Actual behaviour
Session timer shows session time from login page + timezone difference from UTC.

For example, I am in the America/New_York timezone (GMT -5), my session timer shows 05:59:14 remaining on a 60 minute session time.

I have tried changing the timezone setting (both UTC and America/New_York) in TeamPass, php.ini, and apache http.conf with no change to the session timer result. Also, changing the session timer does change relative to the specified time on the login page, but is always +5 hours. This has been an issue since 2.1.25 and stil existis (was hoping would be fixed in latest release).

Also of note, the "Server time" displayed on the footer is correct and matches my client system time and when I change to UTC timezones on server this time updates as expected.

This also appears to be the same issue as #853 but there wasn't a resolution to the problem and the suggestions are from a much older version (2.1.22/23).

### Server configuration
**Operating system**: CentOS 7.2.1511
**Web server:** Apache 2.4.6
**Database:** MariaDB 5.5.50
**PHP version:** PHP 7.0.10
**Teampass version:** 2.1.26-patch-1
**Updated from an older Teampass or fresh install:** Both

### Client configuration
**Browser:** Firefox 49.0.2
**Operating system:** Fedora 24

#### Web server error log
```
N/A - No errors for time
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
N/A not an error issue
```

**Comment by nilsteampassnet** [comment]
Can you please confirm that the shown "time server" is correct in the bottom bar of Teampass?
Can you indicate the TimeZone selection in the settings? and the one from your user profile?

When on login page,  if you select 60 minutes as session time, what is seen in the bottom bar for the "session expiration in" just after being logged?

**Comment by brianara3** [comment]
The server time on the web interface matches both my client and the server's time (within about 15-20 seconds).

The timezone is currently set to America/New_York on the server and my client machine. On the server I have set the timezone for the OS, php.ini, httpd.conf, and on the settings page for TeamPass.

I wanted to mention that if I change the timezone on the server to any other timezone the server time displayed on the TeamPass application also seems to change by the correct time offset, however it doesn't seem to change the session remaining value.

With the session time set to 60 minutes I see "session expiration in 05:59:34" immediately after login.

Also of note, this happens on any of my clients/browsers... Linux, Mac, and Windows with Chrome, Firefox, IE or Safari.

**Comment by nilsteampassnet** [comment]
Can you please make the following test?

in file, `sources/identify.php`, change
```
            $serverTime = time();
            $dateTimeZoneServer = new DateTimeZone($_SESSION['settings']['timezone']);
            $dateTimeServer = new DateTime("now", $dateTimeZoneServer);
            $serverTimeOffset = $dateTimeZoneServer->getOffset($dateTimeServer);

            if ($dataReceived['TimezoneOffset'] > 0) {
                $userTime = $serverTime + $dataReceived['TimezoneOffset'];
            } else {
                $userTime = $serverTime;
            }
            $_SESSION['fin_session'] = $userTime + $dataReceived['duree_session'] * 60;
```
by
```
            $_SESSION['fin_session'] = time() + $dataReceived['duree_session'] * 60;
```

**Comment by scbnmoody** [comment]
Changing the line of code above fixed this for me. I have been having the same issue.

**Comment by agoetz00** [comment]
I had the same issue with UTC.  This change fixed the issue for me.

**Comment by brianara3** [comment]
I have modified the code as requested and it seems to fix the issue. Now whatever time I set on the long page is actually applied as the time remaining.

**Comment by nilsteampassnet** [comment]
ok seems good then ;)
