### ISSUE TITLE
Please explain: Passwords security if access to server data

### ISSUE THREAD

**Issue by nodens** [nilsteampassnet/TeamPass#1585]
Hi,

just a question: are password secure when one has root access to the data on the server (off-line access for instance) ?

That is, is there any kind of encryption done using the user password as well as the sks file for instance ? Is it also true for shared data ?

I used to work in a company that had an in-house password management app that used asymmetric encryption for this purpose, but I couldn't confirm from the code that it's the case here.

Thanks for enlightening me !

Cheers.

nodens

**Comment by nilsteampassnet** [comment]
Not sure I've understood your question.

Encryption in Teampass is explained here => http://teampass.readthedocs.io/en/latest/features/feat-encrypt/

> are password secure when one has root access to the data on the server (off-line access for instance) ?
Do you mean a user that has access to the database?

> is there any kind of encryption done using the user password as well as the sks file for instance ?
Do you mean that the encryption uses 2 different saltkeys? If yes, the answer is no, it makes no sense. Indeed if you want another user to decrypt an encrypted string, he needs the key too. So for public Items, the saltkey used is the global one.
Now for Personal Items, the key is personal key defined by the user himself.

> Is it also true for shared data ?
Not sure about what you called 'shared data'

> that used asymmetric encryption for this purpose, but I couldn't confirm from the code that it's the case here.
No here we use AES which is a symmetric key algorithm as it uses the same key to encrypt and decrypt.
But you know asymmetric encryption is generally not used to protect payload data but more for data transfert with secure channels
