### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by billu260** [nilsteampassnet/TeamPass#1586]
### Steps to reproduce
1. Log in to Teampass as a regular user
2.
3.

### Expected behaviour
Teampass should display the user's entries for the current folder.

### Actual behaviour
Teampass loads the user screen but before it populates the user's entries for the current folder, the browser pops up the error message "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" Clicking OK makes the popup go away and leaves the folder contents blank. Clicking on a new folder pops up the same error message.

### Server configuration
**Operating system**:
Centos 7.2  kernel 3.10.0-327.36.3.el7.x86_64

**Web server:**
Server Version: Apache/2.4.6 (CentOS) PHP/5.6.27 mod_perl/2.0.9dev Perl/v5.16.3

**Database:**
mariadb-5.5.50-1.el7_2.x86_64

**PHP version:**
php56w-5.6.27-1.w7.x86_64

**Teampass version:** 
TeamPass-2.1.26-final-2

**Updated from an older Teampass or fresh install:**
Updated from TeamPass 2.1.23

### Client configuration
**Browser:**
Firefox 50.0

**Operating system:**
Windows 7

#### Web server error log
The only error in the log seems to be this and doesn't seem to be related. This error is repeated numerous times. It seems to occur for pages that are working, such as the initial login page. This has been edited.

[Mon Nov 28 07:20:19.928656 2016] [:error] [pid 3079] [client 172.31.252.34:60868] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/sites/teampass/includes/config/include.php on line 21, referer: http://teampass/index.php?page=items

#### Web server log
172.31.252.34 - - [28/Nov/2016:09:04:00 -0500] "GET /logout.php HTTP/1.1" 302 - "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:00 -0500] "GET /index.php HTTP/1.1" 200 45558 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:00 -0500] "GET /index.php?page=items HTTP/1.1" 200 45868 "http://teampass/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:27 -0500] "POST /sources/identify.php HTTP/1.1" 200 121 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:28 -0500] "GET /index.php?page=items HTTP/1.1" 200 249748 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:29 -0500] "POST /sources/main.queries.php HTTP/1.1" 200 1652 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:29 -0500] "POST /sources/main.queries.php HTTP/1.1" 200 1 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:29 -0500] "GET /sources/tree.php HTTP/1.1" 200 15114 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:29 -0500] "POST /sources/items.queries.php HTTP/1.1" 200 4709 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.31.252.34 - - [28/Nov/2016:09:04:29 -0500] "POST /sources/items.queries.php HTTP/1.1" 200 28681 "http://teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
Firebug Response Body "
" - Inserted between the quotes. Seems to be a blank line with a newline char.

Firebug Location with Parameters-
http://teampass/sources/main.queries.php?type=send_waiting_emails

## Notes
In the process of troubleshooting the error, I found several places where there appears to be a typo. You can find it if you grep the entire tree for "wainting" One place looked like a comment but the other looked like it might be related so I tried changing it to waiting. That had no effect.

I believe the string In the Firebug Location... above was where I originally found the 'wainting' mentioned above. This is what lead me to try changing it to waiting. I also tried logging in as the admin to check settings to see if there had been any changes for email. While I didn't see any, I did update several of the settings and each time a JSON error would pop up when the setting was changed from off to on.

My original Teampass 2.1.23 doesn't use email and none is configured. The new server also has no email configuration.

I also tested the site with chrome and get a similar error. "SyntaxError: Unexpected token  in JSON at position 0"

**Comment by gslongo** [comment]
Same here. Did you found the solution?

Thanks

**Comment by billu260** [comment]
Hi,

I did not. I ran out of time and tried importing my old Teampass 2.1.23
site to the new server built with all of the updated installation
information I could find. The old site worked fine so I moved on for the
moment. i would like to find the solution as I would like to upgrade and
take advantage of some of the new features and fixes, but for now, I can
get back to work.

Bill

**Comment by gslongo** [comment]
I will try 2.1.23 too... If not working I will do the same. Keep the old version... :-/
