### ISSUE TITLE
e-mail to administrator on logon does not seem to work after upgrade to 2.1.26

### ISSUE THREAD

**Issue by dataegg** [nilsteampassnet/TeamPass#1587]
### Steps to reproduce
1. Enable 'Email administrators upon any user login'
2. Log in as a user
3. There is no mail send to the Administrator, this worked in 2.1.25

### Expected behaviour
An email should be send to the Administrator

### Actual behaviour
No email is send

### Server configuration
Centos 7

Apache

Mysql

**PHP version:**
5.5

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
upgrade from 2.1.25

### Client configuration
**Browser:**
Firefox 

**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Correct ... bad spelling of the function called.

**Comment by dataegg** [comment]
I fixed it in 2.1.26 for now, file items.load.php line 3421

Change: 

type : "send_wainting_emails"
to 
type : "send_waiting_emails"

I will wait for the 2.1.27 release. Thanks for fixing this.
