### ISSUE TITLE
TeamPass passwords gone after upgrade 2.1.19 > 2.1.26

### ISSUE THREAD

**Issue by AlanKl** [nilsteampassnet/TeamPass#1589]
### Steps to reproduce
1. done upgrade from 2.1.19 to 2.1.26
2.  i used this instruction > http://teampass.net/2014-06-28-upgrade

### Expected behaviour
Tell us what should happen
Temapass should work on 2.1.26 version

### Actual behaviour
Tell us what happens instead
After upgrade i cant see hidden passwords, they are just blank
Some other errors appear from time to time like "Hack attempt" or SyntaxError: Invalid character

### Server configuration
**Operating system**:
CentOS release 6.6

**Teampass version:** 
2.1.19>2.1.26
**Updated from an older Teampass or fresh install:**
update
### Client configuration
**Browser:** Internet explorer / Chrome

**Operating system:**
win10

Anyone had similar issues?

**Comment by qubez** [comment]
This is likely a problem with the system salt that encrypts passwords.
You must also run the upgrade script /install/upgrade.php when updating to any newer version.
Others have had success in making smaller upgrade steps between versions when things don't work upgrading an old version to the latest.

**Comment by Suuria** [comment]
Yes i had the same issue. For me it worked only to go through every minor version.
2.1.19 -> 2.1.20 -> 2.1.21 -> 2.1.22 ->2.1.23.4 -> 2.1.24.4 ->2.1.25.2 -> 2.1.26 (i think now you schould use 	
2.1.26-final-3 )

**Comment by AlanKl** [comment]
Thanks Suria /qubez for reply, i went back to 2.1.19 and then straightaway to 2.1.23
It looks like there was some major change in password storing in version 2.1.23 (seems like whole DB was rebuilt during installation process?)
There was no need to restore DB when i moved back to 2.1.19 as DB wasn't corrupted.

If anyone else has the same problem please install 2.1.23 first and then you should be able to move further.
