### ISSUE TITLE
Cannot download attached files

### ISSUE THREAD

**Issue by Libeccio84** [nilsteampassnet/TeamPass#1590]
Hello, I am having troubles with attached files. I can successfully upload images and see them once uploaded, regardless whether they are encrypted or not, but there appears to be an issue with other files. I have tried with a simple txt file (encrypted and unencrypted): I am sure it has been uploaded and encrypted (if required), since it appears in the "upload" folder, but clicking on the link "prova.txt" next to "Files & Images" (see the picture below)

![screen shot 2016-12-05 at 16 17 56](https://cloud.githubusercontent.com/assets/23318355/20890220/639f950e-bb06-11e6-879f-f0277889e363.png)

causes this error

![screen shot 2016-12-05 at 16 19 36](https://cloud.githubusercontent.com/assets/23318355/20890292/9ba1d41c-bb06-11e6-804c-5c5b0593e61b.png)

This happens both if the file has been uploaded in the personal folder or in another, shared, one.

I am using TeamPass 2.1.27 on CentOS 7 with php 7, mariadb and this thing happens either with Chrome and Safari.

Can anyone help me?

Thanks in advance.

**Comment by Libeccio84** [comment]
I am doing some basic debug and it looks like it doesn't event tries to open the downloadFile.php. I've checked all the permissions and it looks like those are the same of identify.php; as a matter of fact I made recursively apache the owner of the whole TeamPass directory and for those files the permissions are all 755

**Comment by Libeccio84** [comment]
Problem solved: it was a matter of .htaccess.
The policy for downloadFile.php was set to "Deny from all" and this caused the issue

**Comment by nilsteampassnet** [comment]
Yes absolutely, the .htaccess needs to be adapted with your own policies.

Came to late to help.

**Comment by Libeccio84** [comment]
Never mind :)
