### ISSUE TITLE
Insert duplicate label with API

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1593]
Currently it is not possible to insert item with existing label with API, but it is possible from GUI. Please allow the duplicate insert in API also at: https://github.com/nilsteampassnet/TeamPass/blob/development/api/functions.php#L635 
In GUI it is located in: https://github.com/nilsteampassnet/TeamPass/blob/development/sources/items.queries.php#L163 where $_SESSION['settings']['duplicate_item'] = 1

**Comment by nilsteampassnet** [comment]
Good suggestion.

Implemented in 2.1.27
