### ISSUE TITLE
Suggestion: disable items if the saltkey is wrong

### ISSUE THREAD

**Issue by Libeccio84** [nilsteampassnet/TeamPass#1594]
Hi all,
this is not actually an issue, but a solution to a common error which could happen when editing an entry ignoring the wrong saltkey warning, which caused password deletion.

I am using Teampass 2.1.27 and I wanted to disable the double click effect and item dragging for all those items not related with the current saltkey. I did it commenting the following lines in sources/items.queries.php (lines 1980-6)
`

                       // Prepare full line
                       $html .= '<li name="'.strip_tags(htmlentities(cleanString($record['label']))).'" ondblclick="'.$action_dbl.'" class="';
                       if ($canMove == 1) {
                            $html .= 'item_draggable';
                        } else {
                            $html .= 'item';
                        }
`

and adding
`

                            if ($need_sk == true && isset($_SESSION['my_sk'])) {
                                $pw = cryption($record['pw'], $_SESSION['my_sk'], $record['pw_iv'], "decrypt");
                            } else {
                                $pw = cryption($record['pw'], SALT, $record['pw_iv'], "decrypt");
                            }

                            // test charset => may cause a json error if is not utf8
                            $pw = $pw['string'];
                            if (!isUTF8($pw) || empty($pw)) {
                                $html .= '<li name="'.strip_tags(htmlentities(cleanString($record['label']))).'" class=item"';
                            } else {
                                    $html .= '<li name="'.strip_tags(htmlentities(cleanString($record['label']))).'" ondblclick="'.$action_dbl.'" class="';
                                if ($canMove == 1) {
                                    $html .= 'item_draggable';
                                } else {
                                      $html .= 'item';
                                }
                            }

`
Hope this might be useful for somebody else.

**Comment by nilsteampassnet** [comment]
In 2.1.27, the encryption protocol will change and I've added a sanitize check of the personal saltkey.
So this will be included in next version ;)

Thanks for proposal.
