### ISSUE TITLE
User token expired during upload

### ISSUE THREAD

**Issue by Laayem** [nilsteampassnet/TeamPass#1596]
Hi there,

I am trying to restore a 2.1.19 backup sql file in a freshly installed 2.1.26, but the file isn't upload completely (1MB on a 17,4MB).
I've set modify nginx and php to upload 100MB files :
- php.ini
    - upload_max_filesize 100M
    - upload_max_size 100M
    - post_max_size 100M
- nginx.conf
    - client_max_body_size 100M;
- teampass.conf
    - client_max_body_size 100M;

Is this a bug or is a parameter that I forgot to update?
Thanks

### Steps to reproduce
1. Log in with admin
2. Go to Settings, Backup
3. Click on Restore, select a sql backup file

### Expected behaviour
Upload of the sql file, ask for decryption key and execute sql file

### Actual behaviour
Upload of a 1MB chunk of the sql file, ask for decryption key and nothing.
No error displayed.

### Server configuration
**Operating system**: CentOS 6.8

**Web server:** Nginx 1.0.15

**Database:** MySQL 5.1.73

**PHP version:** PHP-FPM 5.6.24

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Firefox 50.0.2 (oddly I don't have the window to select file to upload with chromium)

**Operating system:** Ubuntu 16.04

#### Web server error log
No error in nginx log

#### Php error log
```
[13-Dec-2016 10:36:42 Europe/Paris] PHP Warning:  rename(/usr/share/nginx/teampass/files/o_1b3rol3h4hui120c12araks1vnj7.sql,/usr/share/nginx/teampass/files/db-backup-1481620684.sql): No such file or directory in /usr/share/nginx/TeamPass-2.1.26-final-2/sources/upload/upload.files.php on line 305
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
Here is some of the answer of Firebug console.
```

POST http://tp.applicam.local/sources/main.queries.php
	
200 OK
		58ms	
csrfprotector.js (ligne 272)
EntêtesPostRéponseHTMLCookies

[{"token" : "ip3joPh9PhohZaekoog4eeThu"}]

POST http://tp.applicam.local/sources/upload/upload.files.php
	
200 OK
		153ms	
csrfprotector.js (ligne 272)
EntêtesPostRéponseHTMLJSONCookies

{"jsonrpc" : "2.0", "result" : null, "id" : "id"}

POST http://tp.applicam.local/sources/upload/upload.files.php
	
200 OK
		152ms	
csrfprotector.js (ligne 272)
EntêtesPostRéponseHTMLCookies

User token expired.

POST http://tp.applicam.local/sources/upload/upload.files.php
	
200 OK
		154ms	
csrfprotector.js (ligne 272)
EntêtesPostRéponseHTMLCookies

User token expired.
```

**Comment by eveltwerk** [comment]
@Laayem @nilsteampassnet Was this resolved and how?

I have the same issue
