### ISSUE TITLE
Can create and login under new local user with LDAP enabled?

### ISSUE THREAD

**Issue by Antoniano** [nilsteampassnet/TeamPass#1602]
### Steps to reproduce
1. Enable LDAP
2. Go to Manage Users and click plus button to add new user. No password field is available on new user creation. 
3. Can't login under newly created local account.

Changing a password using a "key" button on Manage Users tab doesn't help, it changes password in the DB (checked), but still doesn't allow to log in.
Enabling option in Settings --> LDAP --> Teampass local users only doesn't help also.
Log in under local accounts that were created before LDAP was enbled - is possible.

### Expected behaviour
It would be nice to be able to create local users and log in under them even if LDAP is enabled.

### Actual behaviour
Can't log in under newly created local users if LDAP is enabled.

### Server configuration
**Operating system**: Ubuntu 14.04 server edition

**Web server:** apache2

**Database:** mysql

**PHP version:** 5.5.9

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Mozilla

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by mtpreston** [comment]
I am having the exact same problem and wnated to know if this issue has been addressed. If so, please reply.

**Comment by JTR1991** [comment]
I absolutly can confirm that. 
Also i would appreciate it if there will be a future option to test your ldap connection. The actual case of "edit this file and insert your ldap connection data" is not pratically or somehow useful.

Im pretty sure that some old releases had included some functions like that. 

To sum it up:
In this actual state, this release is not useable for bigger cases (>10 users).

**Comment by mtpreston** [comment]
Antoniano

Test this possible solution to your problem.

Edit /var/www/html/teampass/sources/identify.php at line 548 as follows:

Change && $username == "admin" && $userPasswordVerified == true && $data['disabled'] == 0

to

&& $username = array("admin","user1") && $userPasswordVerified == true && $data['disabled'] == 0

and save the changes.

I hope that this workaround addresses your problem.

**Comment by nilsteampassnet** [comment]
I will try to implement something to handle this.
