### ISSUE TITLE
Syntax Error: Unexpected token in JSON when logging in as normal user

### ISSUE THREAD

**Issue by tiredofit** [nilsteampassnet/TeamPass#1604]
### Steps to reproduce
1. Create User, Folders, Roles, 
2. Remove Maintenance Mode
3. Login as User

### Expected behaviour
To display the contents of a folder.

### Actual behaviour
SyntaxError: Unexpected token in JSON at position 0

### Server configuration
Dockerized Alpine Linux edge
With nginx, and following php components.   php7-fpm php7-openssl php7-mbstring php7-redis php7-xml php7-pdo php7-intl php7-openssl php7-ldap php7-mysqlnd php7-gd php7-iconv php7-mcrypt php7-curl php7-opcache php7-ctype php7-apcu php7-intl php7-bcmath php7-json php7-xml php7-dom

**Web server:**
Nginx
**Database:**
MariaDB:latest - Database created with UTF8 support.

**PHP version:**
PHP7
**Teampass version:** 
Master and Development
**Updated from an older Teampass or fresh install:**
Fresh Install.
### Client configuration
Any

#### Web server error log
```
Only output in errorlog is as follows:
2016/12/20 22:09:32 [error] 24#24: *29 FastCGI sent in stderr: "PHP message: PHP Notice:  iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed in /www/teampass/sources/items.queries.php on line 2070" while reading response header from upstream, client: 172.23.0.26, server: , request: "POST /sources/items.queries.php HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "xx", referrer: "https://xx/index.php?page=items"

```
![screenshot](https://cloud.githubusercontent.com/assets/23528985/21370054/c39c4ce0-c6be-11e6-81ec-2c1c31401bc7.jpg)

**Comment by kyleewalters** [comment]
I had this issue today. 

Went to do a database dump before troubleshooting and my SQL client wouldn't connect. I as getting "Got error 28 from storage engine" errors from MySQL workbench. It turned out my /tmp directory was full. Cleared that directory and MySQL workbench and TeamPass started working properly again.
