### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by woitekd123** [nilsteampassnet/TeamPass#1605]
Hello, on database connection step is error:

The next ERROR occurred: 'Access denied for user "www-data"@"localhost" (using password: NO)'
Please correct and relaunch.

i don't use this user in field login so from where is this www-data?

second bug is in Preparation step:

The next ERROR occurred: '/includes is not a Directory!'
Please correct and relaunch.

filed Absolute path to SaltKey is empty, folder where is teampass is writable by www user and any folder back even if i was change this path to any other(writable by www) error still exist.

release 2.1.26

**Comment by nilsteampassnet** [comment]
www-data is typically an internal user of your server.
So you have something wrong in the server / mysql settings.
You should check this.

I didn't understand the second point, can you please describe with more precision.

**Comment by dromaniuk** [comment]
> The next ERROR occurred: 'Access denied for user "teampass"@"172.29.0.3" (using password: YES)'
> Please correct and relaunch.
I have approximately the same situation.

But I'm running it in a docker container. Seems like mysql doesn't allow to auth into database, because only local connections are permitted.
And I have no idea hot to continue the introducing with the application xD
It's sad.
