### ISSUE TITLE
Preview fails with "long paths" in the folders hierarchy

### ISSUE THREAD

**Issue by Tarrerator** [nilsteampassnet/TeamPass#1606]
### Steps to reproduce
1. Install Teampass
2. Create a **folder structure with a resoulting long path** (i think it's limit is around 50 chars)
3. Navigate the folder: no item preview below item list

### Expected behaviour
It should show the preview

### Actual behaviour
It shows blank, neither error nor preview

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Nging + php-fpm 5

**Database:** MySQL

**PHP version:** 5

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** fresh like a lemon

### Client configuration
**Browser:** Firefox

**Comment by nilsteampassnet** [comment]
Couldn't reproduce
![image](https://cloud.githubusercontent.com/assets/1197546/21465719/cf317858-c9ae-11e6-9d39-bfa42c400fc6.png)

Can you please share a screenshot?
