### ISSUE TITLE
Question on upgrade_run_encryption_pwd

### ISSUE THREAD

**Issue by PhilJung** [nilsteampassnet/TeamPass#1610]
I have trouble after migration from 2.1.16 to 2.1.26. No password displayed. After digging in the code I see this in upgrade_run_encryption_pwd.php:

    if (!empty($data['pw_iv'])) {
       // compute $pw
    } else {
        if (!empty($data['pw_iv'])) {    <============= will always be FALSE
              // compute pw and pw_iv

I wonder if the second if should be checking pw

Philippe

**Comment by nilsteampassnet** [comment]
Yes absolutely.

THis has been corrected in the development branch.
You can manually change it.
