### ISSUE TITLE
Cannot change the main saltkey

### ISSUE THREAD

**Issue by Libeccio84** [nilsteampassnet/TeamPass#1612]
When I log in as administrator and I select "_Change the main salt key used for encryption_" under "_Settings_" -> "_Tasks_" I simply get a spinning gear and nothing else happens.

Furthermore I have seen that the "_onclick_" associated to this action is "_LaunchAdminActions('div_change_salt_key')_", but no "_div_change_salt_key_" action is taken into account for _LaunchAdminActions_ function under _admin.settings.load.php_.

 am using TeamPass 2.1.27 on CentOS 7 with php 7 and mariadb.

Any idea?

**Comment by nilsteampassnet** [comment]
Are you sure you use the latest commit in development branch?
Indeed this has been fixed since a couple of weeks.

Please update to latest commit and check back.

**Comment by Libeccio84** [comment]
Ok, I will try as soon as I can.
Thanks

**Comment by Libeccio84** [comment]
I am sorry, but with the development version I can successfully bind to LDAP, but the login process hangs and it does not let me use TP and test the fix. The strange fact is that, from the debug, TeamPass not only binds to LDAP, but it also recognises my full distinguished name. Despite this fact the email string $user_info_from_ad[0]['mail'][0] (line 536) is blank, as well as  $user_info_from_ad[0]['givenname'][0] and $user_info_from_ad[0]['sn'][0].
For testing purpose I have also modified
`tedt gr`
I am currently investigating the reason for this behaviour.

**Comment by Libeccio84** [comment]
No way, it keeps on hanging and showing the spinning gear... :(

**Comment by nilsteampassnet** [comment]
Only changes performed on LDAP are #1553 and #1551, but they should not impact the authentication.

Have you run the update process? it is mandatory for this version as the encryption process changes.

**Comment by Libeccio84** [comment]
I actually installed it on a new virtual machine for testing purposes.
I will keep on trying and I will let you know as soon as I have any news.
