### ISSUE TITLE
Slash / backslash bug in TwoFactorAuth.php

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1613]
currently I receive error, that required files are not found. 
https://github.com/nilsteampassnet/TeamPass/blob/development/includes/libraries/Authentication/TwoFactorAuth/TwoFactorAuth.php#L5 
slashes should be like:

`
require_once(dirname(__FILE__)."/Providers/Qr/GoogleQRCodeProvider.php");
require_once(dirname(__FILE__)."/Providers/Qr/IQRCodeProvider.php");
require_once(dirname(__FILE__)."/Providers/Rng/CSRNGProvider.php");
require_once(dirname(__FILE__)."/Providers/Rng/IRNGProvider.php");
`

after fixed, error is gone.

**Comment by nilsteampassnet** [comment]
Thanks.
