### ISSUE TITLE
Bug in IE11: Cannot show password

### ISSUE THREAD

**Issue by misterunknown** [nilsteampassnet/TeamPass#1616]
### Steps to reproduce
1. Open Teampass in IE11
2. Select a password
3. Click on the little eye symbol: Password shows off for a second and then disappears.

### Expected behaviour
As long as the mouse key is pressed the password should be visible.

### Actual behaviour
The password disappears immediately

### Server configuration
Nothing special

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6

**PHP version:**
PHP 5.6

**Teampass version:**
Teampass 2.1.26

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
IE11

**Operating system:**
Windows 7, Windows 10

**Comment by nilsteampassnet** [comment]
Corrected.
