### ISSUE TITLE
OTV gives no result in the page (2.1.26)

### ISSUE THREAD

**Issue by jpa3nos** [nilsteampassnet/TeamPass#1618]
### Steps to reproduce
1. Use the OTV option from the item's menu
2. Open the link in another browser to view the item
3.

### Expected behaviour
The user should see the item 

### Actual behaviour
The page has no results

### Server configuration
**Operating system**: 
Ubuntu 14.04.5

**Web server:**
Apache 2.4.7

**Database:**
mysql 5.5.53

**PHP version:**
php 5.5.9

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
Updated from 2.1.24

### Client configuration
**Browser:**
Firefox

**Operating system:**
fedora
#### Web server error log
```
Insert your webserver log here
PHP Parse error:  syntax error, unexpected '[', expecting ',' or ';' in /var/www/Teampass/otv.php on line 103

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```


BUG correction
----------------------
LINE 103 in otv.php
LANG should be changed to $LANG

Please confirm the correction and that it does not break something else.

Thanks for the great software.

**Comment by nilsteampassnet** [comment]
Thank you
