### ISSUE TITLE
 After make a search and double click on the result the folder field is incorrect

### ISSUE THREAD

**Issue by albernieto** [nilsteampassnet/TeamPass#1619]
### Steps to reproduce
1. I make a search. For example I need found a name of user. The result is correct
2. After press double click in the result i can see all fields but the field folder is wrong. Always show this element is in the first folder in the tree
3. Curiosly, If I press click in the result and after press double click the field folder is correct

### Expected behaviour
I need open the result of the search with double click and show the item´s folder field correct

### Actual behaviour
Actually the filed folder always show the first folder in the tree

### Server configuration
**Operating system**: Debian

**Web server:** Apache/2.4.23 (Debian)

**Database:** Server version: 5.6.30-1

**PHP version:** php7

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** chrome version 55

**Operating system:** Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by albernieto** [comment]
Hi,

Any comment?

Thanks

**Comment by nilsteampassnet** [comment]
Can you please make a screenshot? I don't see where this happens.

**Comment by albernieto** [comment]
[Steps.docx](https://github.com/nilsteampassnet/TeamPass/files/708717/Steps.docx)

Attach the screenshots

Thanks
Regards

**Comment by nilsteampassnet** [comment]
Thank you for details.

I will try to debug

**Comment by albernieto** [comment]
Hi Team,

Can you reproduce the issue in your lab? Any update?

**Comment by albernieto** [comment]
Good morning,

Any update?

Thanks
Regards

**Comment by albernieto** [comment]
Hi,
Could you give me an estimated date of publication of the new version of teampass (2.1.27)?

Thanks

**Comment by nilsteampassnet** [comment]
End of this month.

This has been fixed by changing the way to handle the "double-click" inside the search results.
Editing is done on clicking on the orange key only.
