### ISSUE TITLE
Direct copy password from seach results and large folders

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1620]
Hi! 

Thank you for great product! I am now doing a bit stress testing with large data sets to see how the systems operates.

First, if I have a large folder (lets say 1000 items) and in that folder before the items are fully loaded, I search for an item (the most right side seach box), I get the result, but below are still loaded other items in that folder, that are not related to the search. This is because I have set "Number of items to retrieve per query" to 25 and system is still loading batches of 25 items until all 1000 are loaded. After searching the loading of regular items in folder should stop.

Secondly, I cannot change the folder until all 1000 items are loaded. If I press on a folder name in left folders tree, nothing happens. Solution is to reload page and choose other folder.

Third, I would like to see a copy password "lock" icon in search results if I have enabled the option "Enable copy password icon on item list". At the moment, the icon is only while browsing, not in search.

![screenshot_111](https://cloud.githubusercontent.com/assets/6266189/21930228/85acc8be-d99d-11e6-8c4d-eddce6943b93.jpg)

**Comment by nilsteampassnet** [comment]
Very good suggestions.

Done in 2.1.27

**Comment by tehnotronic** [comment]
@nilsteampassnet Sadly, now there is a new bug: large folders only display first 25 items in my case. So it seems that the script stops immediately, even if I don't do a search or change folder. Just regular opening folder shows only first batch of items and not the others.

**Comment by nilsteampassnet** [comment]
Yes I know.  Implementation of this fix is not yet finished. I will commit tonight the last part
