### ISSUE TITLE
Disable OTV not possible

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [nilsteampassnet/TeamPass#1621]
Version: TeamPass 2.1.26

We could not find a possibility to deactivate One-Time-View in Teampass.

For security reason in our company we need to disable this feature, but the only value to modifiy is period of link validity.

Is there a way to disable this?

**Comment by nilsteampassnet** [comment]
You cannot disable it.

But I could easily implement an option for this.

Temporary you can do some changes in the code.
In file sources/items.queries.php
Replace
```
        /*
        * CASE
        * Check if Item has been changed since loaded
        */
        case "generate_OTV_url":
``` 
by
```
        /*
        * CASE
        * Check if Item has been changed since loaded
        */
        case "generate_OTV_url":
            break;
``` 

In file items.load.php
Replace
```
/*
* Launch the redirection to OTV page
*/
function prepareOneTimeView()
{
``` 
by
```
/*
* Launch the redirection to OTV page
*/
function prepareOneTimeView()
{
    return false;
``` 

FInally, In file items.php
Replace
```
                                        <li id="menu_button_otv" onclick="prepareOneTimeView()"><i class="fa fa-users fa-fw"></i>&nbsp; '.$LANG['one_time_item_view'].'</li>
``` 
by
```
                                        <!--<li id="menu_button_otv" onclick="prepareOneTimeView()"><i class="fa fa-users fa-fw"></i>&nbsp; '.$LANG['one_time_item_view'].'</li>-->
``` 

It is quite ugly but efficient temporary.

**Comment by sitzmoebelchronograph** [comment]
This looks good as a workaround, but it would be really great to have an option in a future version.

I'll test the code tomorrow. Thx a lot for your fast help :)
