### ISSUE TITLE
Password tree issue

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [nilsteampassnet/TeamPass#1622]
Version: Teampass 2.1.26

Reproduce:
- Create a new root folder named foobar1
- Create a subfolder named foobar_sub
- Create a new root folder named foobar2
- Create a subfolder named foobar_sub
- Create a normal User
- Give user only access to both foobar_sub folders.
- Login with normal User

Now you could see in your password tree 2 Folder with same name foobar_sub, but you don't know from which main folder the entry is.

A real example for understanding:
- Root folder: "Entrance Code US"
-- Subfolder: Mainfloor
--- Item: Left door with Password
- Root folder "Entrance Code GB"
-- Subfolder: Mainfloor 
--- Item: Left door with Password

Did you allow a user to see both Mainfloor folder, the user could not verify from which on is the entry for GB or for US, becaue teh user can't see parent folder.

Better is:
If you allow a user to see only subfolder, the user needs to see the parent but not the items in parent folder.

Is it, possible in a new version?

**Comment by chc88** [comment]
Possible option is to not have any items (except folders) in the parent folder.

**Comment by nilsteampassnet** [comment]
I need to investigate to decide how to go on with this
