### ISSUE TITLE
403 Access Forbidden by CSRFProtector!

### ISSUE THREAD

**Issue by jronzon** [nilsteampassnet/TeamPass#1623]
### Steps to reproduce
1. remove favourites
2. https://teampass/teampass/index.php?page=favourites --> 403 Access Forbidden by CSRFProtector!
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: RedHat EL 7.2 x64

**Web server:** XAMPP for Linux 7.0.9-1

**Database:**XAMPP for Linux 7.0.9-1

**PHP version:**PHP 7.0.9 (cli) (built: Aug 26 2016 11:17:16)

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Firefox or chrome

**Operating system:** Windows 8.1

#### Web server error log
```
Insert your webserver log here
'log csrfp'
'{"timestamp":1484724951,"HOST":"teampass","REQUEST_URI":"\/teampass\/index.php?page=favourites","requestType":"POST","query":[],"cookie":{"7c32e3588d18d9f48e95d8edaa18f1c6e437c4f8652988723e":"f0499938b22e31fcdaeaabae2824c244ed220b334ce01edf66","jstree_select":"14","KEY_PHPSESSID":"hLl70YQOMYshzmdyBQKaoLveNx4Y9HBe9z67BEIAjcc=:eVzczZt1GrMYT8F3gXUvu0PJWgZy43SMj1qnku0ZMWA=","PHPSESSID":"h6okbcm47daljuc30du8i6f9a5"}}'


#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
`Cache-Control	
no-store, no-cache, must-revalidate
Connection	
Keep-Alive
Content-Length	
0
Content-Type	
text/html; charset==utf-8
Date	
Wed, 18 Jan 2017 07:50:00 GMT
Expires	
Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive	
timeout=5, max=97
Pragma	
no-cache
Server	
Apache/2.4.23 (Unix) OpenSSL/1.0.2h PHP/7.0.9 mod_perl/2.0.8-dev Perl/v5.16.3
X-Powered-By	
PHP/7.0.9
voir le code source
Accept	
*/*
Accept-Encoding	
gzip, deflate
Accept-Language	
fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Content-Length	
120
Content-Type	
application/x-www-form-urlencoded; charset=UTF-8
Cookie	
7c32e3588d18d9f48e95d8edaa18f1c6e437c4f8652988723e=f14d31ade0ccdb9199d1cbd65b36d6ef2d77b088beb173d58e
; jstree_select=43; KEY_PHPSESSID=hLl70YQOMYshzmdyBQKaoLveNx4Y9HBe9z67BEIAjcc%3D%3AeVzczZt1GrMYT8F3gXUvu0PJWgZy43SMj1qnku0ZMWA
%3D; PHPSESSID=h6okbcm47daljuc30du8i6f9a5
Host	
teampass
Referer	
https://teampass/teampass/index.php?page=favourites
User-Agent	
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
X-Requested-With	
XMLHttpRequest``

**Comment by nilsteampassnet** [comment]
Absolutely! Thanks.

Corrected in 2.1.27

**Quick patch:**
In file `favorites.php`,
Replace
````
            if (!empty($data['label'])) {
                echo '
                    <tr class="ligne'.($cpt%2).'">
``
by
````
            if (!empty($data['label'])) {
                echo '
                    <tr class="ligne'.($cpt%2).'" id="row-'.$data['id'].'">
``

In file `load.php`,
Replace
````
                    $.post(
                        "sources/favourites.queries.php",
                        {
                           type    : "del_fav",
                           id    : $("#detele_fav_id").val()
                        },
                        function(data) {
                            document.form_favourites.submit();
                        }
                   );
``
by
````
                    $.post(
                        "sources/favourites.queries.php",
                        {
                           type    : "del_fav",
                           id    : $("#detele_fav_id").val()
                        },
                        function(data) {
                            $("#row-" + $("#detele_fav_id").val()).remove();
                            $("#div_delete_fav").dialog("close");
                        }
``
