### ISSUE TITLE
[Request] - Request to add/change password

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1625]
Hi,

Is there any possibility to add request feature?

Explanation:
Organization give write rights to user without any possibility to change or delete record (security purposes).
This record can edit only administrators.  
It will be great if there can be possibility that user can request a password change (Select record -> Choose Request password change -> enter new password and send request to an administrator). Administrator approve or manually change it. And like this it can be Request for a new password record.

BR,
DENISS

**Comment by nilsteampassnet** [comment]
Currently, you have 'Suggestion" feature permitting to suggest new items.

It could be improved to also suggest changes.

I will see this for 2.1.28

**Comment by reginfo** [comment]
Is it available for 2.1.26 version? Or it is in new 2.1.27?

**Comment by reginfo** [comment]
It is available, but I have a question. 
From regular User I do not see suggestion icon. From User with manager permission - It is ok. 
But if i will use link https://teampass/index.php?page=suggestion with user credentials - all OK. 

Is it so? Or ?

**Comment by nilsteampassnet** [comment]
It is as this by design.

Indeed the idea was that only "ReadOnly" users could propose new items and Manager/admin could approve them.

Now it could be logic that any one suggests new items. I could do such change.

**Comment by reginfo** [comment]
It will be 👍 .
Thanks

**Comment by nilsteampassnet** [comment]
I will commit this in 2.1.27

Temporarily you can do the next change.
In index.php, replace
```
    // SUGGESTION menu
    if (
        isset($_SESSION['settings']['enable_suggestion']) && $_SESSION['settings']['enable_suggestion'] == 1
        && ($_SESSION['user_read_only'] == 1 || $_SESSION['user_admin'] == 1 || $_SESSION['user_manager'] == 1)
    ) {
        echo '
```
by
```
    // SUGGESTION menu
    if (isset($_SESSION['settings']['enable_suggestion']) && $_SESSION['settings']['enable_suggestion'] == 1) {
        echo '
```

**Comment by reginfo** [comment]
It works.

P.S. When will be 2.1.27 available?

**Comment by nilsteampassnet** [comment]
I hope end of january

**Comment by reginfo** [comment]
Great news.

**Comment by nilsteampassnet** [comment]
This has been implemented
