### ISSUE TITLE
Error when ppgrade to 2.1.26 via upgrade_ajax.php

### ISSUE THREAD

**Issue by italovalcy** [nilsteampassnet/TeamPass#1631]
### Steps to reproduce
1. Follow the upgrade instruction in http://teampass.net/2014-06-28-upgrade, which means:
1.1. create a dump of database
1.2. rename the current Teampass folder (example: Teampass_old)
1.3. Download lastest package on your server (2.1.26-final-3),
1.4. Unzip package into Teampass folder
1.5. Copy from Teampass_old to Teampass folder: the file /includes/settings.php to include/config/settings.php; the folders backups, files and upload; if you have your sk.php inside includes/ folder, then copy it inside the new Teampass folder;
1.6. Enter url http://your_domain/teampass/install/upgrade.php

### Expected behaviour
You will get stuck when checking the elements...

### Logs

After enabling error log reporting, you will get:

```
PHP Warning:  mkdir(): File exists in /path/to/teampass/install/upgrade_ajax.php on line 144, referer: https://teampass.here/install/upgrade.php
```

In the specific line of upgrade_ajax.php, there is a possible wrong creation of folder when the elements can be a file (possible introduced in commit 5c74a5e8e80915796c7f4cde4ed92bdea48f7a96):

```
            $tab = array(
                $abspath."/includes/config/settings.php",
                 ...
            foreach ($tab as $elem) {
                // try to create it if not existing
                if(!is_dir($elem)) {
                    mkdir($elem);
                }
               ...

```

According to is_dir() documentation (), it returns TRUE if "the filename exists and is a directory", i.e. when the filename exists, it will return FALSE and the condition will break.

Maybe a fix would be:

                if(substr($elem, 0, -1) == '/' && !is_dir($elem)) {

**Comment by nilsteampassnet** [comment]
I see what you mean.
Nevertheless not sure about the fix if the idea is to isolate a file from a folder.
if $elem = "my_folder/"
then substr($elem, 0, -1) will return myfolder
But I think that you want to get the last / 
so we should have
```
if(substr($elem, -1) === '/' && !is_dir($elem)) {
```
Do you confirm your point?

**Comment by italovalcy** [comment]
Hello Nils,

Yes, the idea was to get the last / (intersting but that solution worked in a test environment we made.. but your solution is best).

THanks, italo
