### ISSUE TITLE
upgrade_ajax.php fail to get SALT from sk.php when using double-quotes

### ISSUE THREAD

**Issue by italovalcy** [nilsteampassnet/TeamPass#1632]
### Steps to reproduce
1. Define your sk.php for something like:
```
<?php
@define('SALT', "foobarfoobarfoobarfoobarfoob\0\0\0\0"); //Never Change it once it has been used !!!!!
@define('COST', '13'); // Don't change this.
?>
```
2. Run your upgrade.php according to Issue #1631
3. You should get stuck waiting for upgrade step1 to finish, no error logs
3. Look for debug information in your favorite browser (developer helper), then you should see that the response from Launch onclick "Check('step')" event would be a unformated result, like:
```
$("#session_salt").val("foobarfoobarfoobarfoobarfoob\0\0\0\0"); //Never Change it once it has");document ......
```
Furthermore, this return will result in a "SyntaxError: missing ; before statement" on your browser.

### Expected behaviour

The correct response from upgrade_ajax.php would be something like:
```
$("#session_salt").val("foobarfoobarfoobarfoobarfoob\0\0\0\0");document ......
```

### Proposed patch

An possible fix for this can be (upgrade_ajax.php:76):
```
-                        $_SESSION['encrypt_key'] = substr($val, 17, strpos($val, "')")-17);
+                        $_SESSION['encrypt_key'] = substr($val, 17, strpos($val, ")")-18);
```

Regards, Italo

**Comment by nilsteampassnet** [comment]
Thank you for your feedback.
But here it seems you have manually changed single-quote by double-quotes, as the install and upgrade scripts only use single-quote no?
So for sure, to retrieve the SALT, you must adapt the script with the proposed code.

Nevertheless this is removed from 2.1.27

**Comment by italovalcy** [comment]
Hello  Nils,

I'm not sure if it was manually or default in past, or even a workaround when we upgrade from php 5.4 to 5.6 because of changes in mcrypt libs (which was necessary to add \0 in end of salt).

In any case, the idea was to be robust on having single  or double quote.

Thanks,  Italo
