### ISSUE TITLE
local users unable to login

### ISSUE THREAD

**Issue by eyadgh** [nilsteampassnet/TeamPass#1633]
Hi ,
i have teampass on centos 7 , i can login by admin user only , but i can't login with normal users 

![image](https://cloud.githubusercontent.com/assets/24644790/22621227/ab2b0c2e-eb2f-11e6-999d-ff71ffb5e9c0.png)

**Comment by nilsteampassnet** [comment]
Please provide apache logs

**Comment by eyadgh** [comment]
sorry it was my mistake , it's fine now .
