### ISSUE TITLE
Inheritance of parent folder settings for ignoring required password complexity

### ISSUE THREAD

**Issue by misterunknown** [nilsteampassnet/TeamPass#1634]
### Steps to reproduce
1. Create folder in which you can create passwords ignoring the complexity
2. Create subfolder as a normal user.
3. The subfolder does not inherit the settings for ignoring the complexity.

### Expected behaviour
I really think it would be useful if subfolders inherit this setting. Otherwise my users create their own directory structures, but I have to set this options for every subfolder they add. The problem is, that we want to use the "generate password" functionality for new passwords with the given complexity, but can't influence existing passwords.

### Actual behaviour
The settings (bloquer_creation, bloquer_modification) are not inherited.

**Comment by nilsteampassnet** [comment]
Yes it is correct.
I will merge this
