### ISSUE TITLE
Is mobile client Teampass needs to install teampass-api on server?

### ISSUE THREAD

**Issue by sanch333z** [nilsteampassnet/TeamPass#1636]
Hi all.
I don't understand are mobile application teampass needs installation teampass-api on server for working properly?
Help please.

**Comment by nilsteampassnet** [comment]
Hello

I don't really understand the question so perhaps my answer is not adapted.
If you want to use Teampass-Connect, yes it requires a Teampass instance with API enabled.

**Comment by sefter25** [comment]
hi,

i think sanch333z means if we need to install teampass-api on our teampass server for the Teampass App from Alpeinsoft?
When yes in which directory? in Teampass/api ? or as own instance ?

thank you
