### ISSUE TITLE
enable https for teampass 2.1.26

### ISSUE THREAD

**Issue by pietergrauwet** [nilsteampassnet/TeamPass#1638]
teampass 2.1.26
Ubuntu 16.04.1 LTS
PHP 7.0.13
mysql 14.14
Apache 2.4.18

Hi,

I have teampass running on the installation stated above.  I didn't use any package like xamp/lamp but just installed the components separately and I managed to setup teampass smoothly.  SMTP, LDAP connection to our AD servers, ... works but I'm stuck on enabling HTTPS. 

I have a wildcard certificate for my company's domain from godaddy and I copied the cert and key to apache2/ssl/, made a conf based on the default-ssl.conf in apache, enabled the conf, restarted apache but teampass doesn't react on it.
I found an apache-default.conf file in the teampass www directory but changes there don't work either.  Changing the URL in the teampass settings page reacts immediately but I don't get where those settings are applied in the apache configuration.  Can you point me in the right direction where to define my SSL certificate file and how to get it working in teampass?  I read the FAQ and googled but I don't find a clear answer.  

Thanks

**Comment by Jeff-Solberg** [comment]
I am needing this same assistance. I cannot find "Any" documentation on how to enable SSL for Teampass. I am running XAMPP 7.0.13 on Debian running Teampass ver 2.1.26. Any help would be appreciated.

**Comment by elvisnawa** [comment]
Hi,

I am having the same issue, i think it would be great if a clear guide could me written.
Please let me know if there a link to a clear documentation.

I have Debian 9 
teampass 2.1.27
php 7.0.14
MySQL/MariaDB

**Comment by nilsteampassnet** [comment]
There is no particular settings for https in teampass.
You must ensure that all settings are consistent and that's all.
Please take a look to https://teampass.readthedocs.io/en/latest/errors/#error-403-500-blank-page where you will read what settings and files to adapt.
