### ISSUE TITLE
Manage Roles table Folders column not wide enough

### ISSUE THREAD

**Issue by gerbsen** [nilsteampassnet/TeamPass#1640]
### Steps to reproduce
1. Log in as sysadmin
2. Go to manage roles
3. folders (1st) column to short

### Expected behaviour
The first column should be as wide as it takes. Due to this line break after approx. 180px the complete hierarchy is not visible any more and the table can not be easily read.

### Actual behaviour
Hierarchy broken due to fixed column width

### Server configuration
**Teampass version:** 2.1.26

### Client configuration
**Browser:** All

![screenshot 2017-02-13 10 53 40](https://cloud.githubusercontent.com/assets/1186245/22879097/ae350a60-f1dc-11e6-82c7-eeb76ce6c60f.png)

**Comment by nilsteampassnet** [comment]
I think it could be added in https://teampass.userecho.com/topics/3-improve-usage-of-roles-matrix/
