### ISSUE TITLE
Estonian language is missing

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1641]
Seems like estonian language has gone missing from admin settings.

https://github.com/nilsteampassnet/TeamPass/blob/development/install/upgrade_run_db_original.php#L951

**Comment by nilsteampassnet** [comment]
Estonian is added in upgrade_run_2.1.26.php

Thanks

**Comment by tehnotronic** [comment]
Just tried today with latest development code and upgrade scripts deleted my manually added estonian language and didn't put it back. So currently there is no estonian language in my database:

mysql> select * from devtp_languages;
+----+------------+------------+------+--------+
| id | name       | label      | code | flag   |
+----+------------+------------+------+--------+
|  1 | french     | French     | fr   | fr.png |
|  2 | english    | English    | us   | us.png |
|  3 | spanish    | Spanish    | es   | es.png |
|  4 | german     | German     | de   | de.png |
|  5 | czech      | Czech      | cz   | cz.png |
|  6 | italian    | Italian    | it   | it.png |
|  7 | russian    | Russian    | ru   | ru.png |
|  8 | turkish    | Turkish    | tr   | tr.png |
|  9 | norwegian  | Norwegian  | no   | no.png |
| 10 | japanese   | Japanese   | ja   | ja.png |
| 11 | portuguese | Portuguese | pr   | pr.png |
| 12 | chinese    | Chinese    | cn   | cn.png |
| 13 | swedish    | Swedish    | se   | se.png |
| 14 | dutch      | Dutch      | nl   | nl.png |
| 15 | catalan    | Catalan    | ct   | ct.png |
| 16 | vietnamese | Vietnamese | vi   | vi.png |
+----+------------+------------+------+--------+
16 rows in set (0.00 sec)

**Comment by tehnotronic** [comment]
@nilsteampassnet please review this issue, it is not fixed. upgrade_run_2.1.26.php is never run during upgrade and upgrade_run_db_original.php is replacing the contents of languages table without estonian. So if I currently pull latest development code and run install/upgrade scripts, then the language dissappears again, even if I have it manually inserted it into db.
