### ISSUE TITLE
[TeamPass 2.1.26] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by UniFre** [nilsteampassnet/TeamPass#1642]
Search error in item field.
Firebug:
TypeError: data is undefined
http://localhost/teampass/index.php?page=items
Line 5202

**Comment by nilsteampassnet** [comment]
Sorry it is really difficult to understand the bug you are reporting.

Please follow the template provided to describe a bug.
