### ISSUE TITLE
Email server configuration

### ISSUE THREAD

**Issue by eyadgh** [nilsteampassnet/TeamPass#1644]
hi all ,
i,m trying to setup email configuration for Teampass onn centos 7 . it's showing the below configuration 

![image](https://cloud.githubusercontent.com/assets/24644790/23056087/9316e296-f4fa-11e6-9dab-60cf027f2f9e.png)

![image](https://cloud.githubusercontent.com/assets/24644790/23056106/afba64c2-f4fa-11e6-9e84-a135d52363ee.png)

**Comment by eyadgh** [comment]
you kind support please

**Comment by nilsteampassnet** [comment]
Have you watch out the Troubleshooting page for PhpMailer?

**Comment by Bbully** [comment]
Hi! eyadgh, check error-log in your web-server. if error is: 

> routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

edit file **includes/libraries/Email/Phpmailer/class.smtp.php** and add strings in function
` public function connect($host, $port = null, $timeout = 30, $options = array())`
```
if(count($options)==0){
      $options["ssl"]=array("verify_peer"=>false,"verify_peer_name"=>false,"allow_self_signed"=>true);
}
```

**Comment by eyadgh** [comment]
it was internet issue and it's fine now .
