### ISSUE TITLE
login error [object Object] login attempts on 4

### ISSUE THREAD

**Issue by eyadgh** [nilsteampassnet/TeamPass#1645]
Hi ,
Have a nice Day ! 
i'm facing the below once i enter wrong password . i'm using Teampass version 2.1.26 with  centos 7

![image](https://cloud.githubusercontent.com/assets/24644790/23065924/01dfc49e-f529-11e6-8ffe-89438baee026.png)

**Comment by nilsteampassnet** [comment]
Corrected in 2.1.27

Thank you

**Comment by eyadgh** [comment]
Thanks, is it released?

**Comment by nilsteampassnet** [comment]
In development branch.

**Comment by eyadgh** [comment]
Thanks.
