### ISSUE TITLE
Error encrypting password move/copy between personal and public folders

### ISSUE THREAD

**Issue by troptop** [nilsteampassnet/TeamPass#1647]
Hi,

I am using the team pass 2.1.26-final-3 and installed it with the compose.yml file you give in your GitHub

When I create an item in my personal folder and want to move/copy this item to a shared folder, the item is not readable in this new folder. a red sign shows that an error encrypting password message.

I read a lot of different issues about this kind of error, and I would like to know if you already fixed this issue or if you are still working on it?

thank you

**Comment by nilsteampassnet** [comment]
Yes it is something that has been fixed in the `development` branch and included in 2.1.27
