### ISSUE TITLE
Upload file to a new item -> requested json parse failed

### ISSUE THREAD

**Issue by troptop** [nilsteampassnet/TeamPass#1648]
Hi,

 I am using the team pass 2.1.26-final-3 and installed it with the compose.yml file you give in your GitHub

When I create an item in my personal folder and want to add a file to this item but I get an json parse error.

I tried to follow different of your solution finding online like https://github.com/nilsteampassnet/TeamPass/issues/1295
but it did not work.
Can you help me? What kind of information do you need?

thank you

**Comment by nilsteampassnet** [comment]
Can you provide the logs please?
