### ISSUE TITLE
Passwords dissapear in password window after No-IP domain change instead of TeamPass server public IP

### ISSUE THREAD

**Issue by jathanblackred** [nilsteampassnet/TeamPass#1649]
Hello everyone. After set up a No-IP domain in my TeamPass 2.1.26, when I try to access to some password in the password window, in the preview side the password dissapear when I click on it. I am using TeamPass in Debian Jessie amd64, using Apache 2.4, MariaDB 10.0.29 and PHP 5.6 Could someone help me please?
```

**Comment by ErKinox** [comment]
same problem
