### ISSUE TITLE
Upload folder open to anyone by default

### ISSUE THREAD

**Issue by LadraoDeCalcinha** [nilsteampassnet/TeamPass#1651]
### Steps to reproduce
1.Access http://server:port/teampassSite/Upload
2.Enjoy

### Expected behaviour

This folder contains all users files attached on passwords entrys and need protection because of unwanted access.

### Actual behaviour

The folder is open and acessibly by everyone, authenticated or not.

**Comment by nilsteampassnet** [comment]
A .htaccess file is available in `upload` folder.
Customize it to fit your protection expectation.
