### ISSUE TITLE
Internet Explorer setting document type to 7

### ISSUE THREAD

**Issue by eM-dzeJ** [nilsteampassnet/TeamPass#1652]
teampass 2.1.26 patch 1

IE on Windows 10 and 8.1 setting document type to 7. All "normal" browsers work OK. Compatibility mode is disabled. When you use developer tool in IE and force document type to 9 website looks correctly 

see attached screen.

![capture](https://cloud.githubusercontent.com/assets/25964559/23296423/4781028c-fa75-11e6-820c-a52511cdcd39.JPG)

**Comment by DamienOReilly** [comment]
Is it possible you are using this in work behind an intranet ? https://blogs.msdn.microsoft.com/ie/2009/06/17/compatibility-view-and-smart-defaults/

Anyway, try putting `<meta http-equiv="X-UA-Compatible" content="IE=edge">` in the head part in index.php around like 126:

```
// Load links, css and javascripts
@require_once $_SESSION['settings']['cpassman_dir'].'/load.php';
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title>Teampass</title>
<script type="text/javascript">
    //<![CDATA[
    if (window.location.href.indexOf("page=") == -1 && (window.location.href.indexOf("otv=") == -1 && window.location.href.indexOf("action=") == -1)) {
```

And here is more info on what this tag does: http://stackoverflow.com/a/6771584/3899529

**Comment by eM-dzeJ** [comment]
Yes I tested it on PC with disabled GPOs, but I don't remember if I delete URLs from all zones. I check it on monday. Thanks for the hint :)

I forced IE to use specyfic settings for this website by Enterprise Mode
[https://technet.microsoft.com/en-us/itpro/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode](url)

**Comment by eM-dzeJ** [comment]
Yep, It's intranet zone. Thanks for the hint
