### ISSUE TITLE
Navigation buttons on users page are disabled.

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1654]
### Steps to reproduce
1. Login to TeamPass as Administrator/Manager
2. Go to Manage Users
3. Try to use navigation (First,Previous,[numbers],Next,Last) buttons

### Expected behaviour
Well... if there is more users than listed I suppose that buttons should be active :)

### Actual behaviour
Buttons (First,Previous,[numbers],Next,Last) on users page are disabled. If there is more users than 100 I don't know how to list them while you can show max 100 entries.

### Server configuration
**Operating system**:
Debian

**Web server:**
Xampp

**Database:**  	
5.5.5-10.1.13-MariaDB

**PHP version:**
5.6.23

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
updated from 2.1.26-final-3

### Client configuration
**Browser:**
any

**Operating system:**
Windows 10

#### Web server error log
I dont see any.

**Comment by nilsteampassnet** [comment]
Certainly a bug. I must check this.

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by WojTecH94** [comment]
Still there is something wrong with this:

I have 43 users, but I can see only 20 of them (1-10 on the 1st and 11-20 on the 2nd page) when i go to 2nd page it looks like it would be the last one. Increasing show ... entries value is helping, but its not the case I believe :)
