### ISSUE TITLE
2.1.27 no changes on file and folders permissions during the installation steps

### ISSUE THREAD

**Issue by mapalom** [nilsteampassnet/TeamPass#1655]
### Steps to reproduce
1. Prepare server and copy the master branch of teampass (2.1.27)
2. chmod 777 all files and folders permissions for teampass location
2. Got to teampass with your browser and finish the installation

### Expected behaviour
during the "finalization" step of teampass installation, a script should update the permissions of files and folders of teampass location. Well, that's how it worked for me when I installed teampass 2.1.26.

### Actual behaviour
When I go to the location of teampass 2.1.27 I tested this morning, I can still see all files and folders with 777 permissions.

### Server configuration
**Operating system**: 
ubuntu 16.04

**Web server:** 
Apache 2.4.18

**Database:** 
mysql 5.7.17

**PHP version:** 
php 7.0.15

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
new installation

### Client configuration
**Browser:**
firefox 51.0.1

**Operating system:**
ubuntu 14.04

#### Web server error log
```
no log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
no log
```

**Comment by vmindru** [comment]
Not sure that this behavior is expected actually. I would not expect an web app to chmod my files. 
Giving urwx grwx orwx  is not a proper approach, in the first place.  Not sure this is a bug at all. 

VM
