### ISSUE TITLE
Personal folder doesn't appear

### ISSUE THREAD

**Issue by mapalom** [nilsteampassnet/TeamPass#1656]
### Steps to reproduce
1. prepare server and install teampass
2. create a user with personal folder
3. log in to teampass with user

### Expected behaviour
The personal folder should appear in the folders tree.

### Actual behaviour
When login to teampass with a user who has personal folder, the personal folder doesn't appear in the tree (although it seems to be created in the database).

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
mysql 5.7.17

**PHP version:**
php 7.0.15

**Teampass version:**
2.1.27 

**Updated from an older Teampass or fresh install:**
new installation

### Client configuration
**Browser:**
firefox 51.0.1

**Operating system:**
ubuntu 14.04

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Strange.

From admin page, select `Settings`, tab `Tasks`, click on `Create personal folders for all users without one` to regenerate data.

What's the result?

**Comment by mapalom** [comment]
ok, working now. Thank you.
