### ISSUE TITLE
Can't import/export/download files when URL set to HTTPS

### ISSUE THREAD

**Issue by martinetwork** [nilsteampassnet/TeamPass#1658]
Whenever I have my teampass URL set to use https, I no longer am able to import/export/or download any files.

When I click in import/export etc. the gear simply turns and nothing happens. When I set the URL back to regular http, then I can work with files just fine. Is this a bug or am I doing something wrong?

Everything else seems to work fine in https.

I'm running Centos 7.

**Comment by martinetwork** [comment]
Anyone?

**Comment by nilsteampassnet** [comment]
Could you provide the apache log error please?

Is this happening on selection of the file to import, or when process is on-going?

**Comment by ImNtReal** [comment]
I had an issue where this was happening, and it turned out that even though I had changed the URLs in the settings from http to https, it wasn't showing up in the running config, so I had to use the Regenerate Config under the Tasks tab to get it working.
