### ISSUE TITLE
Search is failing for some entries - appears to be a cache size limit issue

### ISSUE THREAD

**Issue by CCT1** [nilsteampassnet/TeamPass#1661]
### Steps to reproduce
1. Add new entry (eg with a label fred)
2. Run cache refresh utility to be sure
3. Search for password fails
4. From the database select * from teampass_cache where label like "%fred%";  - Returns empty set
5. from the database: select * from teampass_cache returns "1629 rows in set" - we have over 2,500 passwords in the database.

Passwords not in the cache do not appear to be able to be found from the search function.  Is this a hard limit on number of rows in this table?

### Expected behaviour
It should locate the password

### Actual behaviour
Returns 0 items found

### Server configuration
**Operating system**: CentOS Linux release 7.3.1611 (Core)

**Web server:** Apache

**Database:** Mariadb

**PHP version:**php56u-5.6.30-1

**Teampass version:**  2.1.26

**Updated from an older Teampass or fresh install:**
Updated

### Client configuration
**Browser:** Firefox; IE; Chrome

**Operating system:**
Windows 7

#### Web server error log
No entries regarding passwords

Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
THere is no limit in the table entries.

Is this new entry added in the cache table ?

If it is not, then you must have an error in the log. Can you find it and share please ?

**Comment by aigark** [comment]
We had exactly the same problem. Search was failing on some of the items.
Discovered that there is inconsistency between teampass_items and teampass_cache tables.

mysql> describe teampass_cache;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| id              | int(12)      | NO   |     | NULL    |       |
| label           | varchar(50)  | NO   |     | NULL    |       |

mysql> describe teampass_items;
+---------------------------+--------------+------+-----+---------+----------------+
| Field                     | Type         | Null | Key | Default | Extra          |
+---------------------------+--------------+------+-----+---------+----------------+
| id                        | int(12)      | NO   | PRI | NULL    | auto_increment |
| label                     | varchar(500) | YES  |     | NULL    |                |

As you can see, label is only 50 symbols in cache table and 500 in items table.
So you can make longer than 50 symbols label on your password item, but cache table generation fails.

This fixed it for me: alter table teampass_cache modify label varchar(500);
And after that regenerate cache table again.

**Comment by CCT1** [comment]
As installed:

MariaDB [teampass]> describe teampass_cache;
+----------------+--------------+------+-----+---------+-------+
| Field          | Type         | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+-------+
| id             | int(12)      | NO   |     | NULL    |       |
| label          | varchar(500) | YES  |     | NULL    |       |

MariaDB [teampass]> describe teampass_items;
+---------------------------+--------------+------+-----+---------+----------------+
| Field                     | Type         | Null | Key | Default | Extra          |
+---------------------------+--------------+------+-----+---------+----------------+
| id                        | int(12)      | NO   | PRI | NULL    | auto_increment |
| label                     | varchar(500) | YES  |     | NULL    |                |

I tried:
alter table teampass_cache modify label varchar(500);

Rebuilt the cache, but still get:
1629 rows in set (0.01 sec)

And I am still not finding passwords in a search that I know are in the database.

**Comment by CCT1** [comment]
Any clues as to why all of the database entries are not being cached when a "Reload cache table" is done?  If there is an error and this error is logged, where should I be looking?

The only error I can see in /var/log/httpd/error_log is
PHP Notice:  Undefined variable: link in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 618, referer: https://teampass.niwa.local/TeamPass/index.php?page=manage_settings

**Comment by CCT1** [comment]
I moved some entries from our largest folder to another folder and the caching started working correctly.
I am unable to reproduce the problem now.
