### ISSUE TITLE
Teampass 2.1.27.0 - I can not delete folders

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1662]
### Steps to reproduce
1. Select folder
2. In menu use the delete folder link
3. Check the box
4. Push the Delete Button
![teampass_delete_popup](https://cloud.githubusercontent.com/assets/26093484/23451060/81a056ce-fe5e-11e6-8568-0e01b95d5325.png)

### Expected behaviour
I expect the folder will be deleted

### Actual behaviour
1. In the Personal Folder, no message in popup and the folder is not deleted.
    After use the refresh button, the folder is not removed.

2. In the other folder the following popup message is comming:
![teampass_delete_popup0](https://cloud.githubusercontent.com/assets/26093484/23451558/b54502fc-fe60-11e6-8ba1-51343b9020b4.png)
I see the folder and push the button again and the following message is comming.
![teampass_delete_popup2](https://cloud.githubusercontent.com/assets/26093484/23451175/206baa4c-fe5f-11e6-9be0-8f8c94eed77e.png)
After use the refresh button, the folder is removed.

### Server configuration
**Operating system**:CentOS Linux release 7.3.1611

**Web server:** httpd.x86_64 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.0

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.26-final-3

### Client configuration
**Browser:**Newest Firefox

**Operating system:**Windows 10 64Bit

#### Web server error log
```
We don't have any errors in the log File
```

**Comment by reginfo** [comment]
I also have the same situation. 
I have a root folder TEST. Inside I create a new folder Test 1. 
When I try to delete Test 1 folder, I receive "SyntaxError : Syntax error" for IE and "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" for FF.
When I click OK, it shows me Delete folder options. 
If I choose delete one more time, an error came up "This folder cannot be deleted as at least one subfolder exists"
If I choose cancel I see "No items to display" in item window.
But If I refresh the IE, folder is gone.

**Comment by jronzon** [comment]
I have the same problem.

**Comment by nilsteampassnet** [comment]
Confirmed and corrected
