### ISSUE TITLE
can't add password in folder directly under root

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1663]
### Steps to reproduce
1.Login into TeamPass
2.Try to add password in the folder which is directly under root

### Expected behaviour
Password is added.

### Actual behaviour
No one can add password in folders which are directly under root (i.e root->admin), warning 

> You must enter your personal salt key!

occurs. There is no such problem when adding items in deeper folders (i.e. root->admin->accounts)

Operating system:
Debian

Web server:
Xampp

Database:
5.5.5-10.1.13-MariaDB

PHP version:
5.6.23

Teampass version:
2.1.27

Updated from an older Teampass or fresh install:
updated from 2.1.26-final-3
Client configuration

Browser:
any

Operating system:
Windows 10

**Comment by nilsteampassnet** [comment]
What do you call "root"?
In teampass, you cannot create items at the root.
They must be added in folders.

What kind of user do you use when this occurs (normal user, admin, manager)?

By looking to the message you get, I think you are tryuing to add an item inside the personal folder of the user. For this you need to add a personal saltkey using the profile dialogbox or the top right menu

**Comment by WojTecH94** [comment]
I know you can't add folders straight at the root, so what I meant is **I also can't add them at one level lower** in folders which are in the root directory, but if there are folders inside folders, inside root then there is no problem. I hope this is now a bit more clear :) 

I've tried to do it on several accounts - normal user, manager, administrator. What is more I am pretty sure I already have proper saltkey configured and I am not able to change it, but this is maybe for another Issue report :)

**Comment by nilsteampassnet** [comment]
I can't reproduce this.

Performed most conditions possible by playing with users, roles, and settings.
Nevertheless I have no ldap server so can't reproduce with your exact configuration.

What do you have in those settings?
![image](https://cloud.githubusercontent.com/assets/1197546/23577380/f0596ab8-00bd-11e7-9b8f-9737b706742f.png)

**Comment by WojTecH94** [comment]
I have the same settings as on the pic.

**Comment by WojTecH94** [comment]
I restored my Virtual Machine with teampass to checkpoint before upgrade and upgraded it once more. However now the problem is slightly different:
when adding password in mentioned folders sometimes I either get empty information popup:
![popup](https://cloud.githubusercontent.com/assets/19763370/23586680/3db461f0-019a-11e7-9294-31a2e7ae5e82.PNG)
or entry is added but without a password (i need to edit it and add the password)

**Comment by nilsteampassnet** [comment]
Please get the apache logs and share

**Comment by WojTecH94** [comment]
Seems like it's fixed in 2.1.27.1 (I've upgraded 2.1.26.3 straight to 2.1.27.1)
