### ISSUE TITLE
Teampass 2.1.27.0 - Can`t set avatar

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1666]
### Steps to reproduce
1. Set avatar
2. Refresh the page

### Expected behaviour
You need see user avatar

### Actual behaviour
No avatar

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7
**Database:**
 Ver 14.14 Distrib 5.5.54
**PHP version:**
 5.5.9-1ubuntu4.21
**Teampass version:** 
2.1.27.0
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26-Final 3
### Client configuration
**Browser:**
IE11, FF
**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Corrected.

Thanks
