### ISSUE TITLE
Release 2.1.25 upgrade to Release 2.1.27.0 - upgrade does not start

### ISSUE THREAD

**Issue by vmindru** [nilsteampassnet/TeamPass#1667]
When upgrading from Release 2.1.25 following instructions @http://teampass.readthedocs.io/en/latest/install/upgrade/  after accessing http://your_domain/teampass/install/upgrade.php clicking LAUNCH for performing a precheck will do nothing.
A simple progress bar will be running forever. 

One has to include following steps to actually make this process work:
```
cp secrets/includes/settings.php secrets/includes/config/
cp secrets-old/includes/libraries/csrfp/csrfp* secrets/includes/libraries/csrfp/
cp secrets-old/includes/libraries/csrfp/libs/csrfp.config.php secrets/includes/libraries/csrfp/libs/
cp secrets-old/includes/sk.php secrets/includes/
```

please amend the docs if possible

**Comment by pingax** [comment]
Hi @vmindru You don't have to copy all these files. Copy only includes/sk.php (I encountered the same issue earlier and it was resolved by copying sk.php from backup teampass' folder).

**Comment by vmindru** [comment]
you might be very right @pingax  I copied those due to errors in PHP log. 

```
#0 /var/www/secrets/index.php(31): csrfProtector::init()
#1 {main}
  thrown in /var/www/secrets/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 123
[01-Mar-2017 14:08:06 Europe/Prague] PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'OWASP CSRFProtector: configuration file not found for CSRFProtector!' in /var/www/secrets/includes/libraries/csrfp/libs/csrf/csrfprotector.php:123
Stack trace:
```

**Comment by nilsteampassnet** [comment]
I think that this is realted to #1670 too.
As the upgrade to 2.1.26 was not performed, this could not work.
