### ISSUE TITLE
Teampass 2.1.27.0 - Files encryption

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1668]
### Steps to reproduce
1. Enable Files Encryption
2. Add file to Item
3. Check file for readability 
4. De-crypt files
5. Disable Files Encryption
6. Check file for readability

### Expected behaviour
After Decryption file needs to be readable

### Actual behaviour
File context is broken

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7
**Database:**
Ver 14.14 Distrib 5.5.54
**PHP version:**
5.5.9-1ubuntu4.21
**Teampass version:** 
2.1.27.0
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26-Final 3

### Client configuration
**Browser:**
IE11, FF
**Operating system:**
Windows 10

#### Web server error log
```
After Decrypt procedure:
[Wed Mar 01 15:20:31.586008 2017] [:error] [pid 21483] [client 192.168.xx.xx:55406] PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/html/teampass/sources/admin.queries.php on line 842, referer: https://teampass/index.php?page=manage_settings
[Wed Mar 01 15:20:31.586112 2017] [:error] [pid 21483] [client 192.168.xx.xx:55406] PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/html/teampass/sources/admin.queries.php on line 844, referer: https://teampass/index.php?page=manage_settings
[Wed Mar 01 15:20:31.586153 2017] [:error] [pid 21483] [client 192.168.xx.xx:55406] PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/html/teampass/sources/admin.queries.php on line 845, referer: https://teampass/index.php?page=manage_settings

```
Enabled Files Encryption;
File is added to Item;
File is readable;
![file1](https://cloud.githubusercontent.com/assets/4628571/23461416/8a68ba4c-fe92-11e6-9dfc-f2dbbef3c0fd.JPG)
![file2](https://cloud.githubusercontent.com/assets/4628571/23461418/8ded82e2-fe92-11e6-8b79-cc4e65e5aefe.JPG)
Decrypting files
![file3](https://cloud.githubusercontent.com/assets/4628571/23461479/c357a7dc-fe92-11e6-95c2-ce65f3e2b56e.JPG)
Check file - It`s not Readable
![file4](https://cloud.githubusercontent.com/assets/4628571/23461532/f95fcf6c-fe92-11e6-919c-08d00f749729.JPG)

**Comment by nilsteampassnet** [comment]
Something more deep exists here.
I need to investigate and change massively the encode/coding strategy.
The complete process is not enough robust to support all cases.

Thank you, I have run minimal test on this as I didn't change anything since a long time.
By improving my test cases, I've seen what you discovered.

Big fix needed. I'm adding a warning to the pre-release description.

Thanks

**Comment by reginfo** [comment]
You are welcome

**Comment by nilsteampassnet** [comment]
Corrected.

If you already run upgrade to 2.1.27 with "file encryption" option enabled, you will need to re-run the upgrade, and to set the orignal files in *upload* folder. 
Indeed files need to be re-encrypted.
