### ISSUE TITLE
Teampass 2.1.27.0 - Logout - Errors

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1669]
### Steps to reproduce
1. Log in
2. Log Out

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7
**Database:**
Ver 14.14 Distrib 5.5.54
**PHP version:**
5.5.9-1ubuntu4.21
**Teampass version:** 
2.1.27.0
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26-Final 3

### Client configuration
**Browser:**
IE11, FF
**Operating system:**
Windows 10

#### Web server error log
```
After LogOff:

[Wed Mar 01 15:13:14.316206 2017] [:error] [pid 21474] [client 192.168.xx.xx:55260] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/html/teampass/logout.php on line 16, referer: https://teampass/index.php?page=items
[Wed Mar 01 15:13:14.316337 2017] [:error] [pid 21474] [client 192.168.xx.xx:55260] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/html/teampass/logout.php on line 40, referer: https://teampass/index.php?page=items
```
After Log-OFF I receveive errors in apache2 error.log

**Comment by jronzon** [comment]
Hello,
I have the same problems and at the first user's connection, the user sees all directories.
If it reconnects, it no longer sees directories (it have no roles)

Log http : 
[Thu Mar 02 13:45:25.963842 2017] [:error] [pid 5320] [client xx.xx.xx.xx:52570] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/html/teampass/logout.php on line 16, referer: https://teampass/index.php?page=items
[Thu Mar 02 13:45:25.963899 2017] [:error] [pid 5320] [client xx.xx.xx.xx:52570] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/html/teampass/logout.php on line 40, referer: https://teampass/index.php?page=items

**Comment by reginfo** [comment]
Made changes but still one error:
[Thu Mar 02 15:55:06.730456 2017] [:error] [pid 47612] [client 192.168.xx.xx:59363] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/html/teampass/logout.php on line 16, referer: https://teampass/index.php?page=items

**Comment by nilsteampassnet** [comment]
New fix done

**Comment by SoftwarePerfectionist** [comment]
I'm using plain PHP and doing every last test known to man to check if a session was started or not before calling session_start() and  I still get this BS error. At this point  I am 2 seconds away from saying F())(&*()& it and rolling my own Sessions Solution PHP Sessions are fail

**Comment by SoftwarePerfectionist** [comment]
PHP sessions in general are a spastic POS mess

**Comment by SoftwarePerfectionist** [comment]
This causes an error for no good reason.
if (empty(session_id()) && session_status() !== PHP_SESSION_ACTIVE) {
        session_start();
    }

Results in 
Warning: session_start(): Failed to decode session object. Session has been destroyed in

Every damn time. Time to roll my own apparently. This happens after calling session start then moving to another page or reloading, after the first reload the problem is gone. I have fooled with this for 2 damn days now and I am 100% over it and PHP's BS The above code should not ever cause the damn error it causes.
