### ISSUE TITLE
Release 2.1.25 upgrade to Release 2.1.27.0 - upgrade failed to alter users table 

### ISSUE THREAD

**Issue by vmindru** [nilsteampassnet/TeamPass#1670]
### Steps to reproduce
attempt TeamPass upgrade from 2.1.25 to 2.1.27 version. 

### Expected behavior
The upgrade will error if fails to alter MySQL tables. 

### Actual behavior
Upgrade finishes successfully without reporting any issue, after attempt login to teampass
following error is encountered 
```
Error: Unknown column 'can_manage_all_users' in 'field list'
Query: SELECT admin, gestionnaire, can_manage_all_users, groupes_visibles, groupes_interdits, fonction_id FROM users WHERE id=1
```

### Server configuration
```
[root@srv3 secrets]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@srv3 secrets]# 
```

**Web server:**
```
[root@srv3 secrets]# /opt/rh/httpd24/root/usr/sbin/httpd -V
[Wed Mar 01 14:32:50.385213 2017] [so:warn] [pid 14721] AH01574: module php5_module is already loaded, skipping
[Wed Mar 01 14:32:50.386030 2017] [so:warn] [pid 14721] AH01574: module ssl_module is already loaded, skipping
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using XXXX Set the 'ServerName' directive globally to suppress this message
Server version: Apache/2.4.18 (Red Hat)
Server built:   Jul 19 2016 22:15:59
Server's Module Magic Number: 20120211:52
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/opt/rh/httpd24/root/etc/httpd"
 -D SUEXEC_BIN="/opt/rh/httpd24/root/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/opt/rh/httpd24/root/var/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
[root@srv3 secrets]# 
```
**Database:**
```
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.
```
**PHP version:**
```
PHP Version 5.5.21
```

**Updated from an older Teampass or fresh install:**
Release 2.1.25 upgrade to Release 2.1.27.0 

### Client configuration
**Browser:**
Chrome

**Operating system:**
Fedora  25

**Comment by vmindru** [comment]
will attempt incremental upgrade instead of the direct upgrade.  I guess if an incremental upgrade is not an option an error must be issued and upgrade must be aborted.

**Comment by nilsteampassnet** [comment]
THis is really strange.
Sure the upgrade process integrate incremental upgrade.
It is part of the 2.1.26 upgrade as seen in file `upgrade_run_2.1.26.php` we have this code:

```
// add field can_manage_all_users to users table
$res = addColumnIfNotExist(
    $_SESSION['pre']."users",
    "can_manage_all_users",
    "tinyint(1) NOT NULL DEFAULT '0'"
);
if ($res === false) {
    echo '[{"finish":"1", "msg":"", "error":"An error appears when adding field can_manage_all_users to table Users! '.mysqli_error($dbTmp).'!"}]';
    mysqli_close($dbTmp);
    exit();
}
```
If it fails, it should stop the upgrade.
I don't understand, can you confirm the field is not existing in your table with phpmyadmin?
Don't you have errors in the apache log appearing during install process?

**Comment by nilsteampassnet** [comment]
I've discovered the source of your problem. 

In file install/upgrade_scripts_manager.php, line 23, it should be 2.1.26 instead of 2.1.27.

That's why the incremental upgrade does not work.

**Comment by vmindru** [comment]
Nice 10x ! :)  in the meanwhile I have simply rolled back to 2.1.25 upgraded to 2.1.26 and then to 2.1.27.
Thank you for the fix anyway !
