### ISSUE TITLE
Teampass 2.1.27.0 - Anonymous statistics page

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1672]
### Steps to reproduce
1. Log in with administrator Login/Password
2. On Sending anonymous page deselect all items 
3. Save 
4. Log Off/Log On

### Expected behaviour
None of checkbox needs to be selected

### Actual behaviour
All checkboxes are selected

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7
**Database:**
Ver 14.14 Distrib 5.5.54
**PHP version:**
5.5.9-1ubuntu4.21
**Teampass version:** 
2.1.27.0
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26-Final 3

### Client configuration
**Browser:**
IE11, FF
**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Corrected.

But why to not send any statistics. It will really be usefull for me to evaluate the usage of Teampass.
What could make you change choice?

**Comment by reginfo** [comment]
For me it's not a problem. 
Here I can select what I want to send. 
But most are concerned about security and about data, which can be send somewhere.
