### ISSUE TITLE
install/upgrade.php leaks sensitive information

### ISSUE THREAD

**Issue by TopazA** [nilsteampassnet/TeamPass#1675]
### Steps to reproduce
1. http://TeamPass/install/upgrade.php
2. Click continue
3. Click launch

You'll now see a list of valid files and determine which extensions are installed on the server in addition to exact version information and the Encryption Key (SALT). 

### Expected behaviour
After initial setup or upgrade this file should be locked to administrators only or be entirely removed

### Actual behaviour
It appears to be present by default, allowing unauthenticated attackers access to read it

### Server configuration
**Operating system**:
Unknown
**Web server:**
Unknown
**Database:**
Unknown
**PHP version:**
7.0.15-0ubuntu0.16.04.4
**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
Unknown
### Client configuration
**Browser:**
Chrome
**Operating system:**
OS X

Note, have found this as part of a client pen-test so information about the exact version and server information is unknown

**Comment by TopazA** [comment]
Also applies to http://TeamPassinstall/install.php

**Comment by nilsteampassnet** [comment]
Thank you. 

Already fixed in 2.1.27
