### ISSUE TITLE
Pre-auth XSS in index.php

### ISSUE THREAD

**Issue by TopazA** [nilsteampassnet/TeamPass#1676]
### Steps to reproduce
1. Access https://teampass/index.php?page=itemsxfedz%20"/><script>alert('1')</script>-'uye4c&group=
![image](https://cloud.githubusercontent.com/assets/10678727/23533958/ef166a6c-0008-11e7-82f0-32c0c438c359.png)

Other sample URLs

https://teampass/index.php?page=items&ltw7a'-alert(1)-'j88pc=1
https://teampass/index.php?page=items&group=jr4i2'-alert(1)-'idc96

### Expected behaviour
Should sanitise input

### Actual behaviour
"Malicious" Code is returned unescaped/unsanitized as per screenshot above. Browser protection kicks in, but browser bypass protection is possible with more complicated query

### Server configuration
*Teampass version:** 
2.1.26

**Comment by nilsteampassnet** [comment]
You are right.
I didn't identified those entries and as so didn't protected them.
The fix will be to fiter_var them with correct sanitize parameter as I did for the other entries.

Thank you.
