### ISSUE TITLE
Can´t view and create items after upgrade 2.1.26 to 2.1.27

### ISSUE THREAD

**Issue by albernieto** [nilsteampassnet/TeamPass#1680]
### Steps to reproduce
1. Upgrade 2.1.26 to 2.1.27
2. After that, I can´t view, edit and create items
3. Apache Log show errors

### Expected behaviour
The ugrade from 2.1.26 to 2.1.27 is correct

In The upgrade process execute:

    - Backup copy Settings - backup
    - mv /var/www/html/teampass/ /var/www/html/teampass_old
    - wget https://github.com/nilsteampassnet/TeamPass/archive/2.1.27.0.zip
    - unzip 2.1.27.0.zip
    - mv TeamPass-2.1.27.0 teampas
    - cp /var/www/html/teampass_old/includes/config/settings.php /var/www/html/teampass/includes/config/
    - cp -r /var/www/html/teampass_old/backups/ /var/www/html/teampass/
    - cp -r /var/www/html/teampass_old/files/ /var/www/html/teampass/
    - cp -r /var/www/html/teampass_old/upload/ /var/www/html/teampass/
    - cp /var/www/html/teampass_old/sk.php /var/www/html/teampass/
    - chmod -R 777 * in teampass folder
    -http://your_domain/teampass/install/upgrade.php. All checks are right

### Actual behaviour
I can´t view, create or modify items after upgrade

### Server configuration
**Operating system**:Debian

**Web server:**Apache/2.4.23 (Debian)

**Database:** mysql Server version: 5.6.30-1

**PHP version:** php7

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:** 2.1.26

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### Web server error log

Insert your webserver log here

Tue Mar 07 08:59:45.702058 2017] [:error] [pid 19667] [client 10.69.100.5:46870] PHP Warning:  file_get_contents(/var/www/html/teampass/teampass-seckey.txt): failed to open stream: No such file or directory in /var/www/html/teampass/sources/main.functions.php on line 377, referer: http://localhost:10005/teampass/index.php?page=items

[Tue Mar 07 08:59:45.702542 2017] [:error] [pid 19667] [client 10.69.100.5:46870] PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF0\\x00\\x00', false)\n#1 /var/www/html/teampass/sources/main.functions.php(381): Defuse\\Crypto\\Key::loadFromAsciiSafeString(false)\n#2 /var/www/html/teampass/sources/items.queries.php(1260): cryption('def50200c2981cf...', false, 'decrypt')\n#3 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: http://localhost:10005/teampass/index.php?page=items

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by albernieto** [comment]
Hi,

Any update for this case???

Thanks

**Comment by foi** [comment]
We have same after upgrade from 2.1.26 to 27 . We use php (7.0.16) + php-fpm (7.0.16) + nginx 1.20.2 + mariadb 10.1.21
in php-fpm www-error.log 
`
#1 {main}
  thrown in /var/www/html/teampass/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 123
[01-Mar-2017 04:43:19 UTC] PHP Fatal error:  Uncaught configFileNotFoundException: OWASP CSRFProtector: configuration file not found for CSRFProtector! in /var/www/html/teampass/includes/libraries/csrfp/libs/cs$
Stack trace:
#0 /var/www/html/teampass/index.php(31): csrfProtector::init()
`

**Comment by albernieto** [comment]
Hi,

Any update in this case??

We are waiting solve this issue to upgrade

Thanks

**Comment by nilsteampassnet** [comment]
Did you checked this error?
`PHP Warning: file_get_contents(/var/www/html/teampass/teampass-seckey.txt)`

Where is your sk.php file?

**Comment by albernieto** [comment]
The file teampass-sckey.txt not exist
My sk.php:
/var/www/html/teampass/sk.php
/var/www/html/teampass_old/sk.php

**Comment by albernieto** [comment]
Hi,

Any comment???

**Comment by nilsteampassnet** [comment]
Did you run upgrade?

One step must have been skipped as this file is generated during one of them.
You must have other errors in log while performing upgrade.

Can you please re-run the upgrade and check your logs?

**Comment by albernieto** [comment]
Hello

In the ugrade procedure i can read:
**_If you have your sk.php inside includes/ folder, then copy it inside the new Teampass folder"_**
In the version 2.1.26 my sk.php is inside /var/www/html/teampass ¿Is necesary copy it to the new folder in 2.1.27?

The steps to execute the upgrade are:

Backup copy Settings - backup
- mv /var/www/html/teampass/ /var/www/html/teampass_old
- wget https://github.com/nilsteampassnet/TeamPass/archive/2.1.27.0.zip
- unzip 2.1.27.0.zip
- mv TeamPass-2.1.27.0 teampas
- cp /var/www/html/teampass_old/includes/config/settings.php /var/www/html/teampass/includes/config/
- cp -r /var/www/html/teampass_old/backups/ /var/www/html/teampass/
- cp -r /var/www/html/teampass_old/files/ /var/www/html/teampass/
- cp -r /var/www/html/teampass_old/upload/ /var/www/html/teampass/
- cp /var/www/html/teampass_old/sk.php /var/www/html/teampass/
- chmod -R 777 * in teampass folder
-http://your_domain/teampass/install/upgrade.php. All checks are right. NO errors

**Comment by albernieto** [comment]
Hello Nil,

Can I help me? Can you read my last comment??
Thanks

**Comment by nilsteampassnet** [comment]
Can you share your screen with AMMYY?

**Comment by albernieto** [comment]
I installed the version 2.1.27.0. After configure all folders, permisións, users, option, I initiate the upgrade to the version 2.1.27.1


    Start by creating a dump of your database
    Rename the current Teampass folder (example: Teampass_old)
    Download lastest package on your server,
    Unzip package into Teampass folder (could be another name),
    Copy from Teampass_old to Teampass folder:
        the file /includes/config/settings.php
        the file /includes/config/tp.config.php
        the folders backups, files and upload
    Enter url http://your_domain/teampass/install/upgrade.php
    Now follow the upgrade pages

When write the login (teampass_admin) and password don´t access and in the apache logs show an error 500

10.69.100.5 - - [24/Mar/2017:13:05:23 +0100] "GET /teampass/install/upgrade.php HTTP/1.1" 200 3636 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

10.69.100.5 - - [24/Mar/2017:13:05:41 +0100] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 500 295 "http://localhost:10005/teampass/install/upgrade.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

> 
![captura](https://cloud.githubusercontent.com/assets/24434136/24295704/5aa32222-109c-11e7-8801-91794bd944f1.JPG)

**Comment by albernieto** [comment]
Hello,

Any comment?????

Thanks
Regards

**Comment by albernieto** [comment]
Hello,

Any update in this case

Thanks
Regards

**Comment by albernieto** [comment]
Hello,

Can I help me with this issue

thanks
Regards

**Comment by albernieto** [comment]
Hi,

Any update???

Thanks
Regards

**Comment by mariaczi** [comment]
Hello. I have the same kind of issue. After upgrade from 2.1.26 to 2.1.27 I'm not able to create new folder/item (probably the new item i s not saved).
What I do:
1. Create new folder
2. In this new folder, create new item
Both operation finish with success and the folder and item inside in is visible. Logout and logon again, and I can find the newly createtd folder and item. In "Utilities" -> "Logs" I see that items was created.
![Selection_079](https://user-images.githubusercontent.com/25037132/54760022-8577d200-4bef-11e9-9851-a4f9b0d6c1eb.png)

**Comment by mariaczi** [comment]
@nilsteampassnet Could you be able to check where can be a problem, in source code?
