### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by c0fe** [nilsteampassnet/TeamPass#1681]
Does the team have any interest in improving the user interface for TeamPass?

**Comment by dam09fr** [comment]
I think can have a look here: 
  Collab Request - Twitter Bootstrap Design
  https://github.com/nilsteampassnet/TeamPass/issues/1080

And here :
  Mobile Interface 
  https://github.com/nilsteampassnet/TeamPass/issues/676

**Comment by nilsteampassnet** [comment]
It is already in progress with branch 'tst' where I'm evaluating the usage of bootstrap V4.
It will be release 2.2 or 3.0

**Comment by macwinnie** [comment]
Hi @nilsteampassnet,
within your last post on 7 Mar 2017 you announced bootstrap V4 for release 2.2 or 3.0 ... 11 month later, neither 2.2 nor 3.0 but 2.1.27.x is the current release of Teampass.
When will the mobile view be ported to master release?
Thank you for your work!

**Comment by nilsteampassnet** [comment]
Hi @macwinnie 

Unfortunately I'm focused on the current branch to make it more robust, and also redevelop TeampassConnect extension for browsers.
This couldn't permit me to do big progress on the bootstrapped version of TEampass. 
I'm just at mockup level, selection of framework is done and also impact on architecture.
But now design is requested.
