### ISSUE TITLE
hacking attempt when downloading attached file

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#1682]
when trying to download a txt file , I'm getting the message : Hacking attempt
It's working OK with jpg files

I don't know how to check what's wrong
can you help me?

**Operating system**:
Ubuntu 16.04.1
**Web server:**
Apache 2.4.18
**Database:**
Mysql 5.7.17
**PHP version:**
Php 7.0.15
**Teampass version:** 
2.1.26
**Updated from Teampass 2.1.23

### Client configuration
**Browser: Firefox 52.0

**Operating system: windows7

**Comment by nilsteampassnet** [comment]
is there any log?
provide the query results from console.

**Comment by sfrlaurent** [comment]
Is it what you need ?

[cid:image001.png@01D298C5.C9C5AC00]

Cordialement,
Patrick LAURENT

SFR
DRSIO/DT/SI Réseau/Ingénierie Outils Opération

De : Nils Laumaillé [mailto:notifications@github.com]
Envoyé : mercredi 8 mars 2017 21:40
À : nilsteampassnet/TeamPass
Cc : LAURENT, Patrick; Author
Objet : Re: [nilsteampassnet/TeamPass] hacking attempt when downloading attached file (#1682)


is there any log?
provide the query results from console.

**Comment by nilsteampassnet** [comment]
It works with jpg file? very strange ... if you get this error, it means that no session is found.
So either you are unlogged (time out), or something else occurs.

Can you check your apache logs too?

**Comment by sfrlaurent** [comment]
I agree it's strange.
I confirm the session is opened and I do not wait for the timeout.
The apache log is simple, there is only one line after I have clicked on the file icon to download it:
 - - [13/Mar/2017:09:13:22 +0100] "GET /teampass/sources/downloadFile.php?name=nessus_rsa.txt&key=thaithe4phaeJoh7faiS9ep1phiuf1gaekongei3eeSh7veith&key_tmp=96ec3e63a81ab4df9d15e478a847a656&fileid=33 HTTP/1.1" 200 527 "https://teampass.private.sfr.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
nothing into the error.log

**Comment by sfrlaurent** [comment]
more strange:
after comparing between Firefox and Chrome I found this:
with Chrome, the download is OK
with FFox, I noticed the test in downloadFile.php fail because $_SESSION['key_tmp'] does'nt exist.
where is this value initialized ?
