### ISSUE TITLE
Login password not really deleted. Inactif=1 in database

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1683]
Hi,

I have seen that delete a login/password from http, pass it to "inactif=1" in database teampass_items. How can we delete these useless passwords definitely ?

Thanks in advance.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** MySQL

**PHP version:**  5.6.19

**Teampass version:** 2.1.26 last

**Updated from an older Teampass or fresh install:** updated

Thanks for your help !

**Comment by nilsteampassnet** [comment]
from the View page with a Manager or Admin account

**Comment by Hellnino18** [comment]
Oh thanks! I didn't notice that.

It's ok for me.

**Comment by Hellnino18** [comment]
Hmmm actually, there are always account in "inactif" in database (136 rows), but nothing is displayed in View page. So I can only delete them directly by the database.

**Comment by nilsteampassnet** [comment]
If you have this database since a couple of Teampass version it may be normal.
Indeed I have a bug in the past where the clean up was not successfull and you may have remaining items.
In fact they are not restorable as the logs related to those have been deleted but not in the items table.

**Comment by Hellnino18** [comment]
OK. So I can delete them direct from the table or there is join with other tables than teampass_items?
