### ISSUE TITLE
Error 500 after upgrading from 2.1.26  to 2.1.27.1

### ISSUE THREAD

**Issue by dataegg** [nilsteampassnet/TeamPass#1686]
1. Download 2.1.27,1
2. Unzip over 2.1.26
3. open upgrade.php in browser
4. upgrade finisches succesfull
5.After logging in I get an pop up with the message 'Internal Server Error [500]'
6.When choosing an folder from the tree I get the same Internal Server Error message, no password items are shown

Apache error log show me following:

xxx.xxx.xxx.xxx - - [13/Mar/2017:21:04:17 +0100] "POST /sources/items.queries.php HTTP/1.1" 500 - "https://teampass-test.mydomain.com/index.php?page=items&language=english" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

php-fpm log:
[13-Mar-2017 21:04:17 Europe/Amsterdam] PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /webroot/teampass-test/html/sources/items.queries.php on line 3727

### Expected behaviour
No errors

### Actual behaviour
See above

### Server configuration
**Operating system**: Centos 7

**Web server:**
Apache/2.4.6 

**Database:**
MySQL 

**PHP version:**
5.5

**Teampass version:** 
Upgrade from 2.1.26 (release) to 2.1.27.1

**Updated from an older Teampass or fresh install:**
Updated

### Client configuration
**Browser:**
Firefox 51.0.1

**Operating system:**
windows 10

#### Web server error log
```
Insert your webserver log here
xxx.xxx.xxx.xxx - - [13/Mar/2017:21:04:17 +0100] "POST /sources/items.queries.php HTTP/1.1" 500 - "https://teampass-test.mydomain.com/index.php?page=items&language=english" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

php-fpm log:
[13-Mar-2017 21:04:17 Europe/Amsterdam] PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /webroot/teampass-test/html/sources/items.queries.php on line 3727

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by dataegg** [comment]
Tried to uprade two times with the same result

**Comment by nilsteampassnet** [comment]
Strange error.

Nevertheless I can see an error in this line. Can you please do the next change?
IN /webroot/teampass-test/html/sources/items.queries.php
Replace
```
                        '<td style="">'.(!empty($record['raison'] && $record['action'] !== "at_creation") ? (count($reason) > 1 ? $LANG[trim($reason[0])].' : '.handleBackslash($reason[1]) : ($record['action'] == "at_manual" ? $reason[0] : $LANG[trim($reason[0])])):'').'</td>'.
```
by
```
                        '<td style="">'.(!empty($record['raison']) && $record['action'] !== "at_creation") ? (count($reason) > 1 ? $LANG[trim($reason[0])].' : '.handleBackslash($reason[1]) : ($record['action'] == "at_manual" ? $reason[0] : $LANG[trim($reason[0])])):'').'</td>'.
```

**Comment by dataegg** [comment]
This resolves the issue. Thank you. Now I'll look further why my encrypted attachements are unreadble after the upgrade.
