### ISSUE TITLE
Unable to Generate 2FA for Google

### ISSUE THREAD

**Issue by Eric072691** [nilsteampassnet/TeamPass#1687]
### Steps to reproduce
1. Installed TeamPass
2. Created user accounts
3. Enabled google twoFA
4. Sent and received the generated first connection identification code
5. attempt to login to TeamPass using user account with identification code.
6. TeamPass sits at Please identify yourself with gear rotating and makes no progress after 2 mins.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu 14.something

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP5.6

**Teampass version:** 2.1.27.1

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```
[PHP Fatal Error $rror: Call to undefinied function Authenitcation\\TwoFactorAuth\\Providers\Qr\\curl_init() in /opt/TeamPass-2.1.27.1/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCS$TTPQRCodeProvider.php on line 12
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by odelay** [comment]
I'm experience exact the same behavour and error.
Only difference: Ubuntu 16.04 php7.0

**Comment by nilsteampassnet** [comment]
I think you are missing the PHP extension CURL.

I have improved install/upgrade to check that this extension is loaded.

Please confirm it corrects the point.

**Comment by mrmodolo** [comment]
Hi!

After installing php-curl I can already use the Google authenticator.

Thanks

**Comment by odelay** [comment]
Hi,
It is working correctly now!
Thanks
