### ISSUE TITLE
error during upgrade from 2.1.26-final-3

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1689]
### Steps to reproduce
1. Follow steps of upgrade
2.
3.

### Expected behaviour
upgrade is successful

### Actual behaviour
Error during 2nd script of 4th step:
![timestamp](https://cloud.githubusercontent.com/assets/19763370/23903301/5a5fb2c4-08c4-11e7-9602-60d32eff1e87.PNG)

Operating system:
Debian

Web server:
Xampp

Database:
5.5.5-10.1.13-MariaDB

PHP version:
5.6.23

Updated from an older Teampass or fresh install:
upgrade from 2.1.26-final-3 to 2.1.27.1

Client configuration

Browser:
any

Operating system:
Windows 10

**Comment by userrst** [comment]
Hello

I had the same problem.
You can fix the problem with changing the following content from file TeamPass-2.1.27.1/install/upgrade_run_2.1.26.php

**from**
$dbTmp = mysqli_connect(
    $_SESSION['db_host'],
    $_SESSION['db_login'],
    $_SESSION['db_pw'],
    $_SESSION['db_bdd'],
    $_SESSION['db_port']
);

**to**
$dbTmp = mysqli_connect(
    $_SESSION['server'],
    $_SESSION['user'],
    $_SESSION['pass'],
    $_SESSION['database'],
    $_SESSION['port']
);

**Comment by WojTecH94** [comment]
Thanks man! Works like a charm 👍
