### ISSUE TITLE
Unable to set/save personal salt key with LDAP user

### ISSUE THREAD

**Issue by davidwaze** [nilsteampassnet/TeamPass#1690]
### Steps to reproduce
1. Create personnal salt key for local user => OK
2. Create personnal salt key for LDAP user => KO

### Expected behaviour
Can use personal folder

### Actual behaviour
Can't user personal folder, error while creating personal salt key

[capture](https://cloud.githubusercontent.com/assets/26407047/23903735/d0d605f6-08c5-11e7-9743-b363974e62c2.JPG)

### Server configuration
Windows Server 2008 R2

WAMP 3.0.6

MySQL 5.7.14

PHP 5.6.25/7.0.10

Teampass 2.1.27

Fresh install

### Client configuration
Browser : Chrome/IE

Windows 10 / Server 2008 R2

**Comment by mrmodolo** [comment]
Hi,

I am having the same problem in AD accounts. I have not tested with local users. I am running version 2.1.27 on an Ubuntu 16.04 server.

**Comment by WojTecH94** [comment]
Same problem in 2.1.26.3

**Comment by odelay** [comment]
Same for me with LDAP users. New install 2.1.27 on Ubuntu 16.04.
The error while creating personal salt key is a popup with "Internal Server Error [500]"

**Comment by hmodrow** [comment]
Running 2.1.27 on a docker container.

This is what we saw on the logs.

`PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', NULL)\n#1 /var/www/html/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString(NULL)\n#2 /var/www/html/teampass/sources/main.queries.php(564): defuse_validate_personal_key('PersonalKey', NULL)\n#3 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: http://localhost/teampass/index.php?page=items`

**Comment by nickanti** [comment]
I have also verified the issue - is there a patch I can help to test?

**Comment by nilsteampassnet** [comment]
Can you provide the apache log? and the server answer while using the **developer console** of your webbrowser?

**Comment by DantesPop** [comment]
Having the same issue here with TeamPass 2.1.27 on Debian 8.8. 
From developer console: 
csrfprotector.js:272 
POST https://password.compresllc.com/teampass/sources/main.queries.php 500 (Internal Server Error). Apache2 error log attached.
[error.txt](https://github.com/nilsteampassnet/TeamPass/files/1075945/error.txt)

**Comment by DantesPop** [comment]
I just upgraded successfully, but still no joy, I am still getting the internal server error 500.
Chrome debug info
/teampass/sources/main.queries.php Failed to load resource: the server
responded with a status of 500 (Internal Server Error)

Apache2 error log
[Thu Jun 15 17:25:31.371934 2017] [mpm_prefork:notice] [pid 1860] AH00169: caught SIGTERM, shutting down
[Thu Jun 15 17:25:32.506250 2017] [ssl:warn] [pid 13950] AH01906: password.compresllc.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Jun 15 17:25:32.670516 2017] [ssl:warn] [pid 13951] AH01906: password.compresllc.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Jun 15 17:25:32.693167 2017] [mpm_prefork:notice] [pid 13951] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Thu Jun 15 17:25:32.693293 2017] [core:notice] [pid 13951] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jun 15 17:33:31.013420 2017] [:error] [pid 14059] [client 192.168.1.214:60474] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /var/www/html/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /var/www/html/teampass/sources/main.queries.php(616): defuse_validate_personal_key('0', '')\n#3 /var/www/html/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://password.compresllc.com/teampass/index.php?page=items
~

**Comment by RenardPale** [comment]
Same here, just upgraded from 2.1.26 to 2.1.27.8 without problems. But logging in with an ldap user (just as everywhone else here except admin account) gives notification about saltkey upgrade and prompts to enter, but form fields are missing. Trying to set saltkey via personal settings menu results in 500.

Errorslog similiar, especially "encoded data is too short".

[error.log.txt](https://github.com/nilsteampassnet/TeamPass/files/1325048/error.log.txt)

**Comment by nilsteampassnet** [comment]
The errors shows also issues in language.
I've updated the package 2.1.27.8 with new language files.
You can take them and overwrite existing ones.
