### ISSUE TITLE
Item folder not shown in search

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#1691]
Searching doesn't show the folder item is in, the same happens with URL:

![image](https://cloud.githubusercontent.com/assets/1955581/23952198/ebf631c8-0990-11e7-93cf-c5eac36719c8.png)

![image](https://cloud.githubusercontent.com/assets/1955581/23952203/efff9ac0-0990-11e7-8d1a-e40fd950cb05.png)

**Comment by nilsteampassnet** [comment]
Refresh your cache table ... check results.

PLease confirm

----
*Nils @ teampass.net <http://teampass.net>*
*Teampass *- *A collaborative passwords manager*
Visit Teampass.net
Visit Github repository <https://github.com/nilsteampassnet/TeamPass>


2017-03-15 15:06 GMT+01:00 alarido <notifications@github.com>:

**Comment by alarido** [comment]
That was it.

Thank you very much.
