### ISSUE TITLE
frameoptions sameorigin invalid character

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#1692]
I have a apache error because this line in index.php has an invalid character, version 2.1.27.1:

header("X-Frame-Option=SameOrigin: 1; mode=block");

It should be:

header("X-Frame-Option: SameOrigin");

```
# diff fixed/index.php  original/index.php 
17c17
< header("X-Frame-Option: SameOrigin");
---
> header("X-Frame-Option=SameOrigin: 1; mode=block");
761c761
< </html>
---
> </html>
```

**Comment by nilsteampassnet** [comment]
Correct

Thank you

**Comment by GTSLiDe** [comment]
Thanks for the patch alarido! 
Experiencing the same issue and the patch solved the error.
