### ISSUE TITLE
{Feature request] Support U2F two-factor

### ISSUE THREAD

**Issue by Steltek** [nilsteampassnet/TeamPass#1693]
Please support FIDO U2F tokens as second factor for two-factor authentication, ideally as an additional option to TOTP/Google Authenticator so that users can chose to use the latter if the former isn't accessible. (e.g. on mobile, where USB-only U2F tokens can't be used)

A library you could use can be found here:
https://github.com/Yubico/php-u2flib-server

**Comment by reginfo** [comment]
For Questions and Feature Requests, please use UserEcho. 
http://teampass.userecho.com/
