### ISSUE TITLE
Create folder at root-level

### ISSUE THREAD

**Issue by jronzon** [nilsteampassnet/TeamPass#1695]
### Steps to reproduce
1. Root-level folder creation by users enabled --> NO
2. connect to user with manager permission
3. In menu add folder, create folder to root-level not possible
4. In view Manage folders, create folder to root-level it's possible

![image](https://cloud.githubusercontent.com/assets/25194811/24036442/d94ad5f0-0af9-11e7-8891-845473f24dc1.png)

![image](https://cloud.githubusercontent.com/assets/25194811/24036464/e985ac38-0af9-11e7-908f-6e2454252217.png)

![image](https://cloud.githubusercontent.com/assets/25194811/24036476/f7a7c72e-0af9-11e7-978e-228e67633be2.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: 
RedHat EL 7.2
**Web server:**
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built: Aug 3 2016 08:33:27
**Database:**
mysql Ver 15.1 Distrib 10.1.21-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version:**
PHP 7.0.16 (cli) (built: Feb 14 2017 17:22:12) ( NTS )
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
update from 2.1.26
### Client configuration
**Browser:**
FF and chrome
**Operating system:**
Windows 8.1
#### Web server error log
```No logs
Insert your webserver log here
```No logs

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```No logs
Insert the Firebug log here
```No logs

**Comment by nilsteampassnet** [comment]
Yes there is an inconsistency here.

By design, a Manager could create a Folder at Root level.
I will correct this so that a `Manager` can create from the `Items` page.

Thanks
