### ISSUE TITLE
KeePass Import Error

### ISSUE THREAD

**Issue by jleleux** [nilsteampassnet/TeamPass#1697]
### Steps to reproduce
I'm trying to import a KeePass XML, KeePass2.3.5 KBDX, file using the import feature using the command from the webui, but it fails with the following error "Error: -200, Message: HTTP Error, File: NewDatabase.xml" in a red bar.  

### Server configuration
CentOS 7

Apache 2.4.6.45

 mysql-community-server
Arch        : x86_64
Version     : 5.6.35

**PHP version:**
Name        : php
Arch        : x86_64
Version     : 5.6.30
Release     : 1.el7.remi

**Teampass version:** 
2.1.26 
Fresh Install

### Client configuration
Tried it in IE, Firefox, and Chrome all with the same outcome

**Operating system:**
Windows 7 and 10

**Comment by nilsteampassnet** [comment]
I think it is a cross-domain issue.
Don't you use a certificate on the server?
Check that there is no `encrypted alert`

**Comment by jleleux** [comment]
Sorry for the long delay in response, I do use a cert on the server.  Where do I need check for the no encrypted alert?  Also tried to import with CSV and get "Failed to parse JSON" error for that import.
