### ISSUE TITLE
Upgrade script requests wrong salt key when upgrading from 2.1.27.0 to 2.1.27.1

### ISSUE THREAD

**Issue by maxallen123** [nilsteampassnet/TeamPass#1698]
When upgrading from 2.1.27.0 to 2.1.27.1, I was presented with a message "Salt Key not stored in database, please input salt key". It instructed me to retrieve the salt key from sk.php - found no salt key in sk.php, but I did find it in the backup that was taken when upgrading from 2.1.26 to 2.1.27. I put that it, it claimed it was successful, and the upgrade proceeded. After upgrading, all passwords were blank. I rolled back the VM snapshot I took prior and tried again. Copied the data from teampass-seckey.txt, and it worked.

Installer should not instruct you to get salt key from teampass-seckey.txt if upgrading from 2.1.27.0 and if possible do a sanity check to confirm the correct salt key was given.

### Server configuration
**Operating system**:
Ubuntu 16.04.2 LTS 4.4.0-66-generic x86_64

**Web server:**
Apache/2.4.18 

**Database:**
mysql  Ver 14.14 Distrib 5.7.17

**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.4 

**Teampass version:** 
2.1.27.1

**Updated from an older Teampass or fresh install:**
Updated from 2.1.27.0

**Comment by nilsteampassnet** [comment]
Really strange.

Indeed the value you indicate in this field is not used in the "encryption" of passwords.
It is only used for the files "re-encryption".
So I don't see how it can have an influence on your passwords.
And moreover, the items "re-encryption" has been performed when you upgraded from 2.1.26 to 2.1.27.0.
So I think we are facing another issue.

![image](https://cloud.githubusercontent.com/assets/1197546/24114504/ccc3b8ac-0da0-11e7-9264-c60ced4dd47c.png)


As it is a VM, could you perform a new upgrade using the original SK from a sk.php backup file?
It would be really useful.

**Comment by maxallen123** [comment]
Actually, the first attempt at upgrading was from the SK from a sk.php backup file - the file sk,php did not have anything in it - sk.php currently has:
<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>

... so what I first to update using was from was the file sk.php.2017_02_28.1488326111, taken when I originally updated from 2.1.26 to 2.1.27.
