### ISSUE TITLE
Teampass 2.1.27.1 - Personal salt key re-encoded problem

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1699]
### Steps to reproduce
1. Login
2. Set personal salt key

### Expected behaviour
Ugrade is running and Message come never again.

### Actual behaviour
1. Following message is coming
![image](https://cloud.githubusercontent.com/assets/26093484/24094231/fb479ef8-0d57-11e7-92df-bc5ac6c0e64b.png)
2. I use the Start Button
![image](https://cloud.githubusercontent.com/assets/26093484/24094130/8e346e54-0d57-11e7-9647-a2cd75e952f5.png)
3. I use the start and the cancel Button 
4. Re login and the Message is now coming again
![image](https://cloud.githubusercontent.com/assets/26093484/24094233/feb249da-0d57-11e7-8091-cc15db4630fc.png)

### Server configuration
**Operating system:** CentOS Linux release 7.3.1611

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.0

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.27

### Client configuration
**Browser:** Newest Firefox

**Operating system:** Windows 10 64Bit

#### Web server error log
```
No log File
```

**Comment by WojTecH94** [comment]
Try to use "X" button.

**Comment by userrst** [comment]
When i use the X button i have the same problem.
After reboot or set the salt key again, the message is coming again.

**Comment by nilsteampassnet** [comment]
Don't you have an error in the log?
It must be an error as this message relies on a parameter that is set once the "upgrade" is done.
So if it is not set, it means that the upgrade process didn't finished as it should.
Can you please have a look to the logs?

**Comment by userrst** [comment]
Sorry I don't have any Apache error message but i use now the Firebug and had the following message by use the Start Button:

POST https://teampass.aaaa.com/teampass/sources/utils.queries.php	200 OK		63ms
	[{"error" : "" , "pws_list" : "" , "currentId" : "" , "nb" : "0"}]
POST https://teampass.aaaa.com/teampass/sources/utils.queries.php	200 OK		16ms
	[{"error" : "No ID provided"}]

**Comment by userrst** [comment]
I fixed the error as follows:
I deleted the user with the Satl Key Migrations error and created again.

**Comment by userrst** [comment]
Now i have the same problem with the update to the version 2.1.27.7.
I can not remove and add the user now to fix the problem, because we are using the software now Live and we have passwords in this folders.

We can we fix the Problem without delete the User?

**Firebug:**

ReferenceError: reference to undefined property "timer"

POST https://teampass.dom.com/teampass/sources/utils.queries.php 200 OK 15ms	csrfprotector.js (line 272)
Headers
Cache-Control	max-age=0, no-cache, no-store, must-revalidate, private
Connection	Keep-Alive
Content-Length	30
Content-Type	text/html; charset=utf-8
Date	Mon, 10 Jul 2017 15:53:49 GMT
Expires	-1
Keep-Alive	timeout=5, max=99
Pragma	no-cache
Server	Apache
Strict-Transport-Security	max-age=31536000; includeSubDomains
X-Content-Type-Options	nosniff
X-Frame-Options	SAMEORIGIN
X-Permitted-Cross-Domain-...	master-only
X-Powered-By	PHP/5.5.38
X-XSS-Protection	1; mode=block

Accept	application/json, text/javascript, */*; q=0.01
Accept-Encoding	gzip, deflate, br
Accept-Language	en-US,en;q=0.5
Content-Length	211
Content-Type	application/x-www-form-urlencoded; charset=UTF-8
Cookie	aed441022c25ec61bfc8d4d751199107a4c3f9a41b451729bc=4a272e80f950e8309fd965861d86f1655d660e881f332a9768
; 0d02afed592c60d8f3dd0099b3bdad3091a71e195bd716d6bf=7ff47aad4abf836308c4d0090e8615b5586d8f72844d6cd887
; KEY_PHPSESSID=WieIUeIuPj9nSz6UX254jSjaFnamoiYfr1NFG1gM0Hhjr8cYfgwLiJ63CDWe4yHJZB2HBbKd4arFFmCJuoXQWw
%3D%3D; PHPSESSID=5bt003uh3mbprlpn01pd378kc1; jstree_select=214; TeamPass_PFSK_c0b9ef40f5d27ec41ad2bb5614ada454
=a3JWTS9ya216SU1JeTd1ejlsT0RTckcydFlhbkFuTUZFSXNUck1YWUFwSQOZJfh8zS4UwhydI1YwMGVkYjA0MTIwNDAyMWY3MjQ
0ZTcyZjlhZDUxYjQzZjA4MGE4OTliYmZjNjhjYmQ0NzI3Y2VhYTZiM2MxNmI3c3RnY21xNGtjc3VtMzRpd2dnd2hsdHcyZnh0cGF4dWIxMGhyNGQ1cXQ0M29zODFucHQ1dWVmcTZuNTc4emo4dg
%3D%3D
Host	teampass.dom.com
Referer	https://teampass.dom.com/teampass/index.php?page=items
User-Agent	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
X-Requested-With	XMLHttpRequest

**Comment by nilsteampassnet** [comment]
Can you share your screen?
Contact me by email
