### ISSUE TITLE
Can't download Attachments 403 Access Denied

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1700]
### Steps to reproduce
1. Add file attachment to entry (different than image format)
2. Try to open/download it
3.

### Expected behaviour
I should be able to download file.

### Actual behaviour
I get 403 Access Denied page instead :(

### Server configuration
Operating system:
Debian

Web server:
Xampp

Database:
5.5.5-10.1.13-MariaDB

PHP version:
5.6.23

Teampass version:
2.1.26-final-3

Client configuration

Browser:
any

Operating system:
Windows 10

#### Web server error log
error_log file:
> [Mon Mar 20 15:49:23.416920 2017] [access_compat:error] [pid 27046] [client IP:53659] AH01797: client denied by server configuration: /opt/lampp/htdocs/teampass/sources/downloadFile.php, referer: http://TPSite/teampass/index.php?page=items

access_log file:
> 10.196.200.137 - - [20/Mar/2017:15:56:18 +0100] "GET /teampass/index.php?page=items HTTP/1.1" 200 247247
> 10.196.200.137 - - [20/Mar/2017:15:56:20 +0100] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 1539
> 10.196.200.137 - - [20/Mar/2017:15:56:21 +0100] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 -
> 10.196.200.137 - - [20/Mar/2017:15:56:21 +0100] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 2772
> 10.196.200.137 - - [20/Mar/2017:15:56:21 +0100] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 1920
> 10.196.200.137 - - [20/Mar/2017:15:56:22 +0100] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 816
> 10.196.200.137 - - [20/Mar/2017:15:56:22 +0100] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 1208
> 10.196.200.137 - - [20/Mar/2017:15:56:22 +0100] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 1539
> 10.196.200.137 - - [20/Mar/2017:15:56:24 +0100] "GET /teampass/sources/downloadFile.php?name=nieaktywni.csv&key=xahheiS1coo7ahpuviruChohrail4egeo4AhphigeiThoog2zi&key_tmp=1f4dd6ac5978a3b0eec87097398d02b8&fileid=5 HTTP/1.1" 403 1095
> 10.196.200.137 - - [20/Mar/2017:15:56:20 +0100] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 102124

**Comment by nilsteampassnet** [comment]
You need to adapt the .htaccess file inside "sources/" folder to fit your security requirements.

**Comment by WojTecH94** [comment]
Thanks! 

BTW shouldn't it be adapted from the begining? :)

**Comment by nilsteampassnet** [comment]
Yes it is better.

I need to add this in the documentation
