### ISSUE TITLE
Pen Test Findings

### ISSUE THREAD

**Issue by petegriggs** [nilsteampassnet/TeamPass#1701]
Hello,

My organisation has been evaluating TeamPass.net and as part of our due diligence I have carried out a Pen Test using our corporate solution. Do you have an email I could use to discuss the results and share the findings?

Best Wishes
Peter.

**Comment by nilsteampassnet** [comment]
Hello

Yes please, use nils@teampass.net

Thanks

**Comment by chc88** [comment]
Is there any information about this to be shared? For instance, were there huge issues, of just multiple minor issues?

Thanks!

**Comment by petegriggs** [comment]
I have emailed the report to Nils, nothing of major concern just wanted to share findings with him.

**Comment by nilsteampassnet** [comment]
Fixed
