### ISSUE TITLE
Upgrade from TeamPass 2.1.23

### ISSUE THREAD

**Issue by OpenAai** [nilsteampassnet/TeamPass#1703]
Can you please tell me how to upgrade from TeamPass 2.1.23 to the last version. I have followed http://teampass.readthedocs.io/en/latest/install/upgrade/, but when I start the upgrade procedure, the process doesn't continue.

**Comment by nilsteampassnet** [comment]
You need to upgrade version by version.
Only since 2.1.26, the upgrade is incremental.
