### ISSUE TITLE
Error import from XML, CSV  TeemPass stable 2.3

### ISSUE THREAD

**Issue by teccem** [nilsteampassnet/TeamPass#1705]
There are 2 issues 

### Steps to reproduce
1. Create 1 record with password manually in personal folder 
2. Import XML file from Keepass or plain *csv.
3. Press on "eye" in importing record to see password 
4. Switch to record created manually.

### Expected behaviour
1. When do point 3 password don't displayed (field is empty) and "eye" are disappears
2. When do point 4 password is displayed (must be hidden under ******)

### Server configuration
**Operating system**:
Centos 7.3
**Web server:**
apache2.4
**Database:**
Mysql 5.6
**PHP version:**
5.6.3
**Teampass version:** 
stable 2.3
**Updated from an older Teampass or fresh install:**
fresh
### Client configuration
**Browser:**
Firefox/Chrome/IE11
**Operating system:**
Windows/Linux

1 - manually created record
![1](https://cloud.githubusercontent.com/assets/26600090/24200230/863f5dc2-0f1d-11e7-87e6-6dd897c20246.png)
2 - record, that has been imported from XML
![2](https://cloud.githubusercontent.com/assets/26600090/24200232/8a23c0fe-0f1d-11e7-976b-ca2ed023c293.png)
3 - press "eye" in 2nd record
![3](https://cloud.githubusercontent.com/assets/26600090/24200236/8db17a5e-0f1d-11e7-800b-3873a7dc7abe.png)
4 - switch to 1st record
![4](https://cloud.githubusercontent.com/assets/26600090/24200241/912feca6-0f1d-11e7-9c1a-bb3325fad7ee.png)

**Comment by nilsteampassnet** [comment]
What you describe as a bug here is the fact that the password is visible, correct?

**Comment by teccem** [comment]
Yes is it.
And second fact  - password that imported from CSV (XML) don't visible when
press on "eye"

2017-04-08 8:48 GMT+03:00 Nils Laumaillé <notifications@github.com>:
