### ISSUE TITLE
User can edit & delete items without rights

### ISSUE THREAD

**Issue by tomk91** [nilsteampassnet/TeamPass#1706]
### Steps to reproduce
1. I set  access rights "Write but no edit or delete" to a folder for a role
2. I assigned the role to a user
3. The user can edit and detele items in this folder

### Expected behaviour
User can't detete and edit items like in version 2.1.26-final-3

### Actual behaviour
User can edit and detele items in this folder.

### Server configuration
**Operating system:** Ubuntu 16.04.2 LTS

**Web server:**  Apache 2.4.18

**Database:** MariaDB 10.0.29

**PHP version:** 7.0.15

**Teampass version:** TeamPass-2.1.27.1

**Updated from an older Teampass or fresh install:** Updated from 2.1.26-final-3

**Comment by jacen05** [comment]
I'm facing the same problem. I was on 2.1.26.10, I upgraded to 2.1.26-final-3 and then to 2.1.27.36 to see if the fix 
1dd4d19 corrected the problem, but I still have the bug.

### Server configuration
**Operating system**: Debian 8.11

**Web server:** Apache 2.4.10

**Database:** MySQL 5.5.62

**PHP version:** 5.6.40

**Teampass version:** 2.1.27.36
