### ISSUE TITLE
"Restricted To" not working correctly when creating new items

### ISSUE THREAD

**Issue by yavin48** [nilsteampassnet/TeamPass#1707]
### Steps to reproduce
1.Create a new password item
2.Fill in the desired information
3.Click on "Restricted to:"
4.Select a role
5.Save item. It will not be restricted to the role you selected, but a random user instead. If you go back and edit the item, un-check the user and check the role it will work correctly.

### Expected behaviour
It should list all users and roles, with the users at the top and the roles at the bottom. It should also restrict to the role you select, and not a random user.

### Actual behaviour
It shows the roles at the top and the users at the bottom, with some of the roles showing up twice. If you select a role, you are actually restricting it to someone who has that role assigned. If you create the item and leave the "Restricted to" alone, you can then go back and edit the item and the list will show up correctly, and work as designed.

### Server configuration
**Operating system**:
sles 11 sp4

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
5.6.22

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
updated from 2.1.25, where we noticed the same behavior

### Client configuration
**Browser:**
Chrome/Firefox

**Operating system:**
suse/Windows 7

#### Web server error log
There are no entries in any logs

**Comment by nilsteampassnet** [comment]
Corrected
