### ISSUE TITLE
LDAP issue on version 2.1.27

### ISSUE THREAD

**Issue by ccoque** [nilsteampassnet/TeamPass#1708]
### Steps to reproduce
1. Configure LDAP (Windows / Active Directory)
2. Login with AD user typing the wrong password
3. Login with AD user typing the right password

### Expected behaviour
When logging on with the wrong password, the system should show an error message.
When logging on with the right password, the system should grant the user access to Teampass.

### Actual behaviour
When logging on with the wrong password, the system correctly shows "Login credentials do not correspond!".
When logging on with the right password, the system shows "Please identify yourself" with a spinning gear besides that message, and gets stuck there forever.

### Server configuration
**Operating system**:
UBUNTU 16.04

**Web server:**
Apache (don't know the version)

**Database:**
MySQL 5.7.17-0ubuntu0.16.04.1

**PHP version:**
7.0.15-0ubuntu0.16.04.4

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

![ldap](https://cloud.githubusercontent.com/assets/26610223/24221143/20f9ef9c-0f1b-11e7-8422-5106406d1cf6.jpg)
![logginon](https://cloud.githubusercontent.com/assets/26610223/24221144/261d8d94-0f1b-11e7-8cfd-4accc4dbe308.jpg)
![wrongpass](https://cloud.githubusercontent.com/assets/26610223/24221172/3dd3d48e-0f1b-11e7-88ff-153370eb4b12.jpg)

**Comment by Libeccio84** [comment]
I don't know if this might help you, but when I did it last time, I installed the LDAP client on TeamPass server, being sure that it was able to bind to LDAP.
After this everything run smoothly.

Hope this will help you.

**Comment by ccoque** [comment]
Well, I'm a very newbie person on linux, so I tried doing that but it didn't work anyways.
Do you have any reference on where I could follow the steps?
By the way, I tried doing a LDAP query from linux terminal, but it's apparently not working, so maybe the problem is there.

**Comment by jsanzharovskaya** [comment]
I've got the same problem. I've installed on TeamPass server another web application (GLPI) that uses LDAP (Active Directory) for user authentification and it's working well. So I'm sure everything is ok with php-ldap and connection to LDAP server.

**Comment by olgagerassimova** [comment]
I have the same issue right now with newly installed OS and teampass 2.1.27 on it. How did you manage to solve the problem?

**Comment by jsanzharovskaya** [comment]
I've just installed the older version of teampass. I think there is a promlem in code, but I'm not a programmer and don't know how to fix it.

**Comment by jaqflash** [comment]
I am currently experiencing this issue.  However mine is an upgrade from what was a fully working system  We were on 2.1.25 and I updated to 2.1.27. Since then I am unable to use a new set of LDAP credentials (It doesn't seem to create the user in the teampass schema) However if I manually create a user with the same name, from that point onwards that user is able to log in using the LDAP credentials.
