### ISSUE TITLE
Unable to Upload Files

### ISSUE THREAD

**Issue by Eric072691** [nilsteampassnet/TeamPass#1709]
### Steps to reproduce
1. Installed TeamPass
2. Created user accounts
3. Created an item
4. Attempted to upload a file, file reaches 100% but doesn't show up in the list. I tried following directions from issue #1295 but didn't work or fix. 

### Expected behaviour
File is uploaded and we can view it.

### Actual behaviour
File is uploaded, I can see an encrypted doc in Upload, but I don't see anything show up on the item.

Under logs, the following error is shown: 

Query: INSERT INTO `teampass_files` (`id_item`,`name`,`size`,`extension`,`type`,`file`,`status`) VALUES ('1', 'image_uploaded_from_ios.jpg', 134128, 'jpg', 'image/jpeg', 'beb772a35855203851cf96488f215ea6', 'encrypted')<br />Error: Unknown column 'status' in 'field list'<br />@

Query: INSERT INTO `teampass_files` (`id_item`,`name`,`size`,`extension`,`type`,`file`,`status`) VALUES ('1', 'test_sheet.xlsx', 53046, 'xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '70ad7816b843aaabdb1abe8435cf4bf0', 'encrypted')<br />Error: Unknown column 'status' in 'field list'<br />@

### Server configuration
**Operating system**: Ubuntu 14.something

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP5.6

**Teampass version:**  2.1.27.1

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Chrome/Firefox

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by david-we** [comment]
exactly the same problem here with 2.1.27.1 (docker-container)

**Comment by chc88** [comment]
Have you tried manually adding the column to the table? Maybe there was somehting wrong during the creation of the table.

**Comment by Eric072691** [comment]
Duh - I just checked the columns in the teampass_files table and would you believe it, status is missing. I went ahead and inserted the status column into the table. The error no longer appears in the logs, but there's still no files uploaded.

I'm not able to dig into the logs right now, but will update as soon as I can.

**Comment by d1storder** [comment]
Hi everybody !

Same issue for me. 

Add the file to the item , click on upload , upload show 100% , the file is perfectly upload on filesystem.
But impossible to see in Teampass webapp (don't appear). 

I'am using  : CentOS Linux 7.
With DB : 5.5.52-MariaDB
PHP : 5.5.38
Teampass : 2.1.27

I will be happy to help to fix it  (not in coding cause i'am a Systadmin dude).

My logs : 

[ FROM : /var/log/httpd/error_log ]

krodb/db.class.php on line 623, referer: https://teampass.xxxxx.com/teampass/index.php?page=items
[Thu Mar 30 11:45:08.970936 2017] [:error] [pid 19432] [client 172.16.2.25:60478] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.xxxxx.com/teampass/index.php?page=items

[ FROM : /var/log/httpd/acces_log ]

172.xx.xx.xx - - [30/Mar/2017:13:57:10 +0200] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 41 "https://teampass.xxxx.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"


I can provide anythings else on demands !

**Comment by d1storder** [comment]
So, Eric072691 and me seem had Almost the same version of PHP.
I will try to upgrade PHP if i had the time.

**Comment by d1storder** [comment]
After upgrade to PHP 7.0.16 the problem still the same.

And the same log in httpd error logs : 

[:error] [pid 23143] [client 172.16.2.25:36686] PHP Notice:  Undefined variable: link in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.xxxx.com/teampass/index.php?page=items
[Thu Mar 30 15:34:14.823570 2017] [:error] [pid 23143] [client 172.16.2.25:36686] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass.xxxx.com/teampass/index.php?page=items

**Comment by nilsteampassnet** [comment]
I confirm that a field is missing in DB on a fresh install.
I will commit this.

In your log, it is missing the most important part.
Can you also share the query that failed. It must be present.

**Comment by d1storder** [comment]
Many thanks!

I'm going to do this but i'm a sysadmin and i'm quite weak regarding
databases skills. Tell me where to find the logs and I'll share them.

And, also i'd like to say you're doing an awesome work with this project,
It's fyreally helpful !

Ludovic.

Le 30 mars 2017 22:36, "Nils Laumaillé" <notifications@github.com> a écrit :

I confirm that a field is missing in DB on a fresh install.
I will commit this.

In your log, it is missing the most important part.
Can you also share the query that failed. It must be present.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nilsteampassnet/TeamPass/issues/1709#issuecomment-290537248>,
or mute the thread

**Comment by Eric072691** [comment]
Likewise, I'll provide the logs as long as you tell me what you need.

From my end, after adding the database column, I do not see an error in the log. I do see a file appear in the uploads section, encrypted of course. However teampass_files only has null values.  Which query do you need?

**Comment by blady214** [comment]
Hello,

I've got the same error in apache server logs:

`[Fri Mar 31 11:24:04.293010 2017] [:error] [pid 44938] [client 192.168.0.125:37140] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: http://192.168.0.100/index.php?page=items`

but there is no additional informations about this error or I am unable to find them.

**Comment by d1storder** [comment]
Hi, many thanks !

I confirm, the fix provide by @blady214 solve the issue.

Exact manipulation to fix is : 

1) - Logon serveur (ssh)
2) - Connect to your database with teampass db user : `mysql -u teampass -p `
3) - Go on TeamPass database with this sql line : `USE TeamPass;`
4) - Use the solution provide by @blady214 : `ALTER TABLE teampass_files ADD COLUMN status VARCHAR(20) NULL;
5) - Exit the database : `quit`

**Result in shell should be like :** 

> mysql -u teampass -p
> Enter password:
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 13334
> Server version: 5.5.52-MariaDB MariaDB Server
> 
> Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MariaDB [(none)]> USE TeamPass;
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Database changed
> MariaDB [TeamPass]> ALTER TABLE teampass_files ADD COLUMN status VARCHAR(20) NULL;
> Query OK, 0 rows affected (0.01 sec)
> Records: 0  Duplicates: 0  Warnings: 0
>

**Comment by mrmodolo** [comment]
ALTER TABLE teampass_files ADD COLUMN status VARCHAR(20) NULL;

Works for me!
