### ISSUE TITLE
Teampass 2.1.27.1 - Change my personal salt key is not correct working

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1710]
### Steps to reproduce
   1. Login
   2. Set personal salt key
   3. My Profile
   4. Change my personal salt key
   5. Put in the "Nwe sal key:" my new password
   6. Put in the "Old salt key:" my old passowrd
   7. Push the Change button
   8. Relogin
   9. Set the new personal salt key

### Expected behaviour
Change my personal salt key and after Relogin i can view after set the salt key with the new password all privat passwords.

### Actual behaviour
After Change the personal salt key, i can not view my password with set the new password or. set the old password.

OK: Set the Salt key first time and create a test password.
OK: Relogin and set the salt key
![image](https://cloud.githubusercontent.com/assets/26093484/24350484/b090c6e2-12e2-11e7-95df-8201fdd92084.png)

Set the old and new salt key and push the change button:
![image](https://cloud.githubusercontent.com/assets/26093484/24350612/21b98746-12e3-11e7-8bf9-92f026c651fb.png)

After Push the change button we had the following message:
![image](https://cloud.githubusercontent.com/assets/26093484/24350668/567d0e8a-12e3-11e7-9da4-5a10b223fa90.png)

Push OK and close Button
After reset the salt key we have the done message but we can not view any password in the personal folder (All Password lost).
![image](https://cloud.githubusercontent.com/assets/26093484/24351088/c179e4be-12e4-11e7-9d89-156ccaf2df40.png)

### Server configuration
**Operating system:** CentOS Linux release 7.3.1611

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.0

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.27

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
No Apache error log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
https://teampass.alabus.com/teampass/sources/main.queries.php
  ReferenceError: reference to undefined property "href" netUtils.js (line 315, col 9)
  ReferenceError: reference to undefined property "text/html" fontViewer.js (line 110, col 9)

Key event not available on some keyboard layouts: key=“b” modifiers=“accel,alt” id=“key_firebug_toggleBreakOn”
ReferenceError: reference to undefined property 5 netUtils.js (line 256, col 1)
ReferenceError: reference to undefined property "text/html" jsonViewer.js (line 158, col 9)
Key event not available on some keyboard layouts: key=“b” modifiers=“accel,alt” id=“key_firebug_toggleBreakOn”
Key event not available on some keyboard layouts: key=“b” modifiers=“accel shift alt” id=“key_firebug_customizeFBKeys”
ReferenceError: reference to undefined property "id" menu.js (line 63, col 13)
```

**Comment by nilsteampassnet** [comment]
Corrected
