### ISSUE TITLE
doubleclick on directory shows items twice

### ISSUE THREAD

**Issue by david-we** [nilsteampassnet/TeamPass#1713]
### Steps to reproduce
1. doubleclick on directory in directory-tree 
2. some or all items are displayed twice

### Expected behaviour
display all items in clicked directory
### Actual behaviour
some or all items are displayed twice

### Server configuration
docker container from https://hub.docker.com/r/teampass/teampass/

**Database:** mysql 5.7

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:** fresh install / docker container

### Client configuration
**Browser:**all

**Operating system:**all

#### Web server error log
```
Insert your webserver log here
```
no error
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```
no error

**Comment by nilsteampassnet** [comment]
Corrected
