### ISSUE TITLE
Cannot login after fresh install: Login credentials do not correspond!

### ISSUE THREAD

**Issue by RG-035** [nilsteampassnet/TeamPass#1714]
I'm a bit new to TeamPass, installed it first in a test enviroment on OSX with MAMP. So i went on and installed a deployment version on ubuntu 16.04. After the installation (everything was ok) i was redirected to the login screen. Login was failed due to: Login credentials do not correspond! Like i said, it was a fresh install so i reinstalled in for multiple times. The last time i just used a very simple admin password but the issue still occurs. What to do? 

### Server configuration
**Operating system**: ubuntu 16.04

**Web server: Apache 2.4.18

**Database: MySQL installed with apt also tried MariaDB

**PHP version: PHP 7.0.15

**Teampass version: Latest version

Fresh install

### Client configuration
**Browser: Firefox

**Operating system: W10

**Comment by teha75** [comment]
Same here!

**Comment by nilsteampassnet** [comment]
You have php 7.1.x installed for sure.

Please see #1630

**Comment by RG-035** [comment]
No, running version 7.0.15. Thought the latest version was the standard stable install. I'll change my first post with the correct versions

**Comment by craiglondon** [comment]
I am having the same issue.   Installed on a Ubuntu 16.04 server  `PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )`

**Comment by craiglondon** [comment]
I have tried to login with the user `admin` and the password that was setup during the install process, this did not work.   I have also tried to login with username `admin` and password `admin`, this does not work.  When I look in the database on the `teampass.teampass_log_system` table here are the error messages.

```
'1', 'failed_auth', '1490979485', 'user_not_exists', '192.168.200.110', ''
'2', 'failed_auth', '1490979506', 'user_not_exists', '192.168.200.110', ''
'3', 'failed_auth', '1490979860', 'user_not_exists', '192.168.200.110', ''
'4', 'failed_auth', '1490980041', 'user_not_exists', '192.168.200.110', ''
'5', 'failed_auth', '1490980102', 'user_not_exists', '192.168.200.110', ''
```

**Comment by nilsteampassnet** [comment]
What is the extract from the table Users?

**Comment by kartnico** [comment]
Hi,

I have the same problem from a fresh installation :
CentOS/7.2
Apache/2.4.6
PHP/5.5.21
MariaDB Server/5.5.50 

Extract from Teampass database :

MariaDB [teampass]> select * from teampass_log_system
    -> ;
+----+-------------+------------+-----------------+----------------+---------+
| id | type        | date       | label           | qui            | field_1 |
+----+-------------+------------+-----------------+----------------+---------+
|  1 | failed_auth | 1491342643 | user_not_exists | 10.254.100.121 |         |
|  2 | failed_auth | 1491342654 | user_not_exists | 10.254.100.121 |         |
|  3 | failed_auth | 1491342887 | user_not_exists | 10.254.100.121 |         |
|  4 | failed_auth | 1491379773 | user_not_exists | 10.254.100.121 |         |
+----+-------------+------------+-----------------+----------------+---------+
4 rows in set (0.00 sec)

MariaDB [teampass]> select * from teampass_users;
Empty set (0.00 sec)

MariaDB [teampass]>

**Comment by nilsteampassnet** [comment]
If it is not created, you have errors in your apache log.
Can you please share them here?
Thank you

**Comment by kartnico** [comment]
Hi have no error in my Apache log. I reinstall 3 times from scratch.

In my lab environment I have 3 files in "/var/teampass" :

```
::::::::::::::
sk.php
::::::::::::::
<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>
::::::::::::::
sk.php.2017_04_05
::::::::::::::
<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>
::::::::::::::
teampass-seckey.txt
::::::::::::::
def00000a092e7b0d7d6ad42305fa84f9d0f464f64b2f4294bff82a0dff544ff93de814924b1bf9e507c5977e8f3729e5dc1c025d3f07c1bf28aeb766fa956759c30202d
```

**Comment by nilsteampassnet** [comment]
Are you sure your apache server is set to display errors?
You are installing pre-release 2.1.27.2?

Can you please run the next SQL query?
```
INSERT INTO `teampass_users` (`id`, `login`, `pw`, `groupes_visibles`, `derniers`, `key_tempo`, `last_pw_change`, `last_pw`, `admin`, `fonction_id`, `groupes_interdits`, `last_connexion`, `gestionnaire`, `email`, `favourites`, `latest_items`, `personal_folder`) VALUES ('1', 'admin', 'afakepassword', '', '', '', '', '', '1', '', '', '', '0', '', '', '', '0');
```
It is the query run during install.

**Comment by kartnico** [comment]
Yes my PHP was configured to display errors, and there was no error during installation. I tried the SQL query and the test was OK.

After that, I tried a 4th time to reinstall from scratch, but this time I restarted my Apache, and now it works.

```

MariaDB [teampass]> select * from teampass_users
    -> ;
+----+-------+--------------------------------------------------------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
| id | login | pw                                                           | groupes_visibles | derniers | key_tempo | last_pw_change | last_pw | admin | fonction_id | groupes_interdits | last_connexion | gestionnaire | email | favourites | latest_items | personal_folder | disabled | no_bad_attempts | can_create_root_folder | read_only | timestamp | user_language | name | lastname | session_end | isAdministratedByRole | psk  | ga   | ga_temporary_code | avatar | avatar_thumb | upgrade_needed | treeloadstrategy | can_manage_all_users | usertimezone | agses-usercardid | encrypted_psk | user_ip |
+----+-------+--------------------------------------------------------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
|  1 | admin | $2y$13$6544ce7a7b28103837e2cOl0lvMgtmYh9f1zeHGSRtbgkGFBLlyeS |                  |          |           |                |         |     1 |             |                   |                |            0 |       |            |              |               0 |        0 |               0 |                      0 |         0 | 0         | 0             | NULL | NULL     | NULL        |                     0 | NULL | NULL | none              | NULL   | NULL         |              0 | full             |                    0 | not_defined  | 0                | NULL          | none    |
|  2 | API   |                                                              |                  | NULL     | NULL      | NULL           | NULL    |     0 | NULL        | NULL              | NULL           |            0 |       | NULL       | NULL         |               0 |        0 |               0 |                      0 |         1 | 0         | 0             | NULL | NULL     | NULL        |                     0 | NULL | NULL | none              | NULL   | NULL         |              0 | full             |                    0 | not_defined  | 0                | NULL          | none    |
+----+-------+--------------------------------------------------------------+------------------+----------+-----------+----------------+---------+-------+-------------+-------------------+----------------+--------------+-------+------------+--------------+-----------------+----------+-----------------+------------------------+-----------+-----------+---------------+------+----------+-------------+-----------------------+------+------+-------------------+--------+--------------+----------------+------------------+----------------------+--------------+------------------+---------------+---------+
```
Thanks for your help and sorry for the inconvenience.

Regards

**Comment by janstockem** [comment]
Hi there, i am experiencing the same issue.
My Stack is:
- Ubuntu 16.0.4 LTS
- Apache 2.4.18
- PHP 7.0.15
- MySQL 5.7.17
- Teampass 2.1.27

After fresh install i am unable to login via admin credentials. 
As i can see in the database there is no user added.

**Comment by markp93** [comment]
I had to manually add the 'admin' user as well, then it said the install folder had to be removed. After manually removing the install folder, I was able to log in.

**Comment by Cr0wl3r** [comment]
I had the same issue with the config like janstockem.
After manually adding the admin user and removing the install folder it's not possible to login with the admin user. In the apache log I have the following error:

`[Tue Apr 18 11:55:01.951517 2017] [:error] [pid 1300] [client 192.168.102.62:52412] PHP Fatal error: Uncaught DomainException: Unsupported Password Hash Supplied in /var/www/html/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\Password\Factory->verifyHash('admin', '6x3H90Ja')\n#1 /var/www/html/teampass/sources/identify.php(766): PasswordLib\PasswordLib->verifyPasswordHash('admin', '6x3H90Ja')\n#2 /var/www/html/teampass/sources/identify.php(200): identifyUser('lQNb73Xi9VhI5JV...')\n#3 {main}\n thrown in /var/www/html/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://192.168.101.45/teampass/index.php?page=items`

**Comment by ptcuops** [comment]
1. Cloned repo 
2. ran "docker build -t teampass" to build docker image
3. ran " docker run --rm -d -p 88:80 -v /home/mwelch/temp/teampass/vol:/teampass --name teampass teampass"
4. Initial check determined that php curl module was not installed
5. Modified line3 of Dockerfile to add php5-curl
6. Re-built and ran docker image
7. Install wizard runs successfully connecting to a database prepared for the purpose
8. Removed /teampass/www/install folder
9. Try to login with admin password I provided during login wizard - no go. Doesn't work.

Thinking I must have mistyped the password, I repeated this process 4 times before finally determining that I hadn't made a mistake. The teampass_log_system table shows a "user_not_exists" entry. I ran the script provided above to manually create the admin user, and now the same table shows user_password_not_correct despite trying both my own password and "afakepassword" from the sql command.

**Comment by adick** [comment]
I have the same issue. Fresh install, but no user was added after the install steps. 

PHP 7.0, 
MySQL 5.5
Teampass release 2.1.27.3

The tip above with the insert query (admin user and "afakepassword") doesn't work either, still no login possible.

Unfortunately I'm unable to use this product!

**Comment by bartmeuris** [comment]
Have the same problem with the docker-compose setup, with the default teampass/teampass:latest image. 

First I had to manually delete the install directory, but then I could still not login and got the message "Login credentials incorrect!".

Inserting the admin user manually in the database failed:
```
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY
```

So I checked, and there was already an admin record present, but it fails to verify the password on login.

**Comment by kumaip** [comment]
I get the same issue
 fresh install.
What's the problem with this product?

**Comment by futureweb** [comment]
Any News on that? Same Problem here ... PHP 7.0.19 - Teampass Version 2.1.27.4.
After installation the ADMIN user is missing in the DB, the INSTALL Folder is still present on the FS ... but even after fixing that I'm not able to log in ...

Endless loading:
![grafik](https://cloud.githubusercontent.com/assets/1698881/26676842/bb0f8ec6-46c9-11e7-8ef5-4256d8102cb5.png)

PHP Error Log:
```
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: PHP Fatal error:  Uncaught DomainException: Unsupported Password Hash Supplied in /var/www/vhosts/MyPath/httpdocs/includes/libraries/PasswordLib/Password/Factory.php:87, referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: Stack trace:, referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: #0 /var/www/vhosts/MyPath/httpdocs/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('myPass', 'myPass'), referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: #1 /var/www/vhosts/MyPath/httpdocs/sources/identify.php(768): PasswordLib\\PasswordLib->verifyPasswordHash('myPass', 'myPass'), referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: #2 /var/www/vhosts/MyPath/httpdocs/sources/identify.php(200): identifyUser('xxxxxxxxxx...'), referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr: #3 {main}, referer: https://MyPath/index.php?page=items
[Thu Jun 01 12:54:43 2017] [warn] [client 80.110.31.221] mod_fcgid: stderr:   thrown in /var/www/vhosts/MyPath/httpdocs/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: https://MyPath/index.php?page=items
```

Any ideas on that?

Thank you, bye from Austria
Andreas Schnederle-Wagner

**Comment by futureweb** [comment]
alright ... found the Source of the Problem ... the Query to create the admin User mentioned above can't work as the PW is inserted as Plain-Text ...

Use this Query to create the admin User with a default Pass of "admin":
`INSERT INTO `teampass_users` (`id`, `login`, `pw`, `groupes_visibles`, `derniers`, `key_tempo`, `last_pw_change`, `last_pw`, `admin`, `fonction_id`, `groupes_interdits`, `last_connexion`, `gestionnaire`, `email`, `favourites`, `latest_items`, `personal_folder`) VALUES ('1', 'admin', '$2y$13$98cbaa0c0d89b45c41022ui2F7veV.PCw1gkAppqK13ozBnEdYfSa', '', '', '', '', '', '1', '', '', '', '0', '', '', '', '0');`

**Comment by RG-035** [comment]
wasn't able to test it for some time now, but the last comment from futureweb solved my issue aswell!

thanks @futureweb, case closed.

**Comment by pedrofsl** [comment]
Is unbeliviable. Lot´s of people with the same problema and the developer has no clue about wahat´s going on....a developer that doesn´t test his products cannot be taken as serious.

**Comment by nilsteampassnet** [comment]
How can you say that?
Do you imagine how much sacrifices it is to manage such a project? Are you even able to invest yourself as I do for something free?
Do you imagine the number of server configurations that can exist and yes I performing a lot of tests but I'm alone managing such a big piece of code and often working on nights and weekends to provide some users with it.  Tests configuration are a nightmare and I need to decide and use a configuration that I imagine to be a standard one.
But you know what, such comments just make me sick! I chance that a lot of users are sending me congratulations and for them I will fight to provide the best solution, and for the other, I just don't force them to use Teampass ...
And by the way what are your contribution and questions?
