### ISSUE TITLE
Can not install because of the error "Unexpected token < in JSON"

### ISSUE THREAD

**Issue by Negossia** [nilsteampassnet/TeamPass#1715]
When I launch the server checking, this page doesn't respond
### Steps to reproduce
1. Go to http://pass.myserver.ru/install/install.php
2. "Next", then "Launch"

### Expected behaviour
Server checking

### Actual behaviour
The page doesn't respond. I see an error in my browser's console:

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16)
    at Object.complete (install.js:127)
    at Object.resolveWith (jquery.min.js:16)
    at w (jquery.min.js:18)
    at XMLHttpRequest.d (jquery.min.js:18)
```

### Server configuration
**Operating system**: Debian 8

**Web server:** apache 2.4

**Database:** mysql 5.7

**PHP version:** 5.6.9

**Teampass version:** 2.1.27 

**Updated from an older Teampass or fresh install:** No

### Client configuration
**Browser:** Firefox, chrome

**Operating system:** Linux mint

#### Web server error log
the logfile is empty
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
this code is from Firebug console:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]  jquery.min.js:16:11702
	f</<.parseJSON http://pass.myserver.ru/install/js/jquery.min.js:16:11702
	CheckPage/<.complete http://pass.myserver.ru/install/install.js:127:32
	._Deferred/e.resolveWith http://pass.myserver.ru/install/js/jquery.min.js:16:15483
	w http://pass.myserver.ru/install/js/jquery.min.js:18:8572
	.send/d http://pass.myserver.ru/install/js/jquery.min.js:18:14247
```
Request headers:
```
Host: pass.myserver.ru
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://pass.myserver.ru/install/install.php
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Content-Length: 356
Cookie: name=value
Connection: keep-alive
```
Response headers:
```
Connection: Keep-Alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Thu, 30 Mar 2017 11:51:43 GMT
Keep-Alive: timeout=5, max=99
Server: Apache/2.4.25 (Debian)
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Frame-Options: SameOrigin
X-Powered-By: PHP/5.6.9
```

**Comment by nilsteampassnet** [comment]
Strange error, never seen this!

Try to re-upload the files.

**Comment by Negossia** [comment]
I re-uploaded tar.gz instead of zip, and it works. There is no such problem. May be, it was my fault.
