### ISSUE TITLE
Teampass slow

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1716]
Teampass is really slow. We have around 100 folders and 200 users with personal folders. Some folders contain 1000 items, but they are loaded in batches for minutes and that is understandable. But even tree and small folders with 10 items load 10 seconds. We have tuned MySQL for performance, but the bottleneck seems to be PHP. 

Can you please comment and give suggestions how to tune Teampass for speed?

I see that in the code there are many tree_rebuild() calls, even when there are no changes, like reloading page, are they all needed? items.querys.php is also slow, but it contains many complex checks and joined SQL statements to display folder contents, can't do anything about that I quess?

![screenshot_103](https://cloud.githubusercontent.com/assets/6266189/24507918/8f3e9fa2-156a-11e7-9738-ad7376f09854.png)
![screenshot_104](https://cloud.githubusercontent.com/assets/6266189/24507919/8f63a838-156a-11e7-863a-3389690a8c21.png)

**Comment by nilsteampassnet** [comment]
Yes it is a work that need to be done.
Unfortunetaly I need first to finalize the 2.1.27 release.
I will then take time to check how to optimize this.

But many of those checks are needed today due to various number of possible configuration of Teampass.
Definitively it can be optimized, it is just a heavy work.

It is a TODO action

**Comment by emrahcetiner** [comment]
Is there any improvement?

**Comment by pancakedaemon** [comment]
I have had the same issue and changed

mysqli_query($link, $query);
to
mysqli_query($link, $query, MYSQLI_ASYNC);

in includes/libraries/Tree/NestedTree/NestedTree.php

This caused the directory tree to be loaded a lot faster, but I'm not
sure if this breaks anything.

**Comment by Calanon** [comment]
> I have had the same issue and changed
> 
> mysqli_query($link, $query);
> to
> mysqli_query($link, $query, MYSQLI_ASYNC);
> 
> in includes/libraries/Tree/NestedTree/NestedTree.php
> 
> This caused the directory tree to be loaded a lot faster, but I'm not
> sure if this breaks anything.

This makes a lot of difference, thanks

**Comment by franck56590** [comment]
Hi
Old post, I try to modify but all directories has disappeared.
Roll back.
