### ISSUE TITLE
Deleting a folder not working as expected

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#1717]
### Steps to reproduce
1. Create a new folder;
2. Create an item under the created folder;
3. Delete the folder and all its associated items.

### Expected behaviour
The folder and all the associated items should be deleted.

### Actual behaviour
The folder and all the associated items are removed from the Password menu. However, the item created still appears in the Search menu and is not automatically deleted. 

![bug-1_0](https://cloud.githubusercontent.com/assets/19646582/24601184/db4f91ca-184f-11e7-8675-351ccf373be4.png)

![bug-1_1](https://cloud.githubusercontent.com/assets/19646582/24601193/e105790e-184f-11e7-80df-4693823c7233.png)

### Server configuration
**Operating system:** CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** PHP 7.0.17

**Teampass version:** TeamPass 2.1.27.1

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Chrome

**Operating system:** CentOS 7

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by darrais** [comment]
Hello @nilsteampassnet,

First of all, thank you for your response!

Although you have identified this issue as "corrected", it appears that it is not.
After testing the solution, I came to the conclusion that if a folder contains more than one item, only one item gets deleted and the others still appear in the search menu.

Here are the screenshots illustrating this problem:
![screenshot from 2017-04-06 17-30-59](https://cloud.githubusercontent.com/assets/19646582/24765324/4fb962ce-1aef-11e7-9a96-9d45215c98ec.png)

![screenshot from 2017-04-06 17-31-49](https://cloud.githubusercontent.com/assets/19646582/24765336/58bf9370-1aef-11e7-8a07-0717b5f8d74f.png)

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by darrais** [comment]
Yes, now it is corrected :)

Thank you very much!
