### ISSUE TITLE
Moving a folder to itself

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#1718]
### Steps to reproduce
1. Create a new folder;
2. Move the folder to itself.

### Expected behaviour
In my opinion, what should happen is that TeamPass should not allow to perform this action, showing for example a warning.

### Actual behaviour
The folder disappears from the Password menu tree-structure but it is still visible in the select menus for either the options "Copy Folder", "Delete Folder", etc.

![bug-2_0](https://cloud.githubusercontent.com/assets/19646582/24601591/5a572da6-1851-11e7-9f13-d31f5498f7e9.png)

### Server configuration
**Operating system:** CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** PHP 7.0.17

**Teampass version:** TeamPass 2.1.27.1

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Chrome

**Operating system:** CentOS 7

**Comment by nilsteampassnet** [comment]
Corrected

**Comment by darrais** [comment]
This issue is indeed corrected!

Thank you very much :)

**Comment by darrais** [comment]
Hello @nilsteampassnet,

Sorry to bother you again with this issue. 
I expect the same result when trying to move a folder to a **sub-folder** of itself. 
With the current implementation, the same problem exists: The folder disappears from the Password menu tree-structure but it is still visible in the select menus for either the options "Copy Folder", "Delete Folder", etc.

Regards!

**Comment by nilsteampassnet** [comment]
I'm not sure to understand.
Can you give me the way to reproduce?

**Comment by darrais** [comment]
The problem that I'm trying to describe is... 

Imagine, for example, that you have the following tree structure:
- Folder_A
  - Folder_B 

If you try to move Folder_A into Folder_B, I would expect TeamPass to, at least, not allow to perform this action. But what actually happens is that the folders completely disappear from the Password menu tree-structure. 

So, moving a folder to itself (an issue that is already corrected) or to any of its sub-folders, sub-sub-folders, etc., should not be allowed.
