### ISSUE TITLE
PHP version mismatch error

### ISSUE THREAD

**Issue by Negossia** [nilsteampassnet/TeamPass#1719]
### Steps to reproduce
Go to http://pass.myserver.ru/install/install.php
"Next", then "Launch"

### Expected behaviour
Server checking

### Actual behaviour
When I launch the server checking, this page gives me an error:

> [ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!

### Server configuration
**Operating system**:Debian 8

**Web server:**apache 2.4

**Database:**mysql 5.7

**PHP version:**5.6.9

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:**no

### Client configuration
**Browser:**Firefox, chrome

**Operating system:**Linux mint

#### Web server error log
```
the logfile is empty
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
I see an error in Firefox console:
```
POST XHR http://pass.myserver.ru/install/install.queries.php [HTTP/1.1 500 Internal Server Error 16мс]
```
Request headers:
`Acceptapplication/json, text/javascript, */*; q=0.01Accept-Encodinggzip, deflateAccept-Languageru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3Connectionkeep-aliveContent-Length345Content-Typeapplication/x-www-form-urlencodedCookiePHPSESSID=a0d7b612dccc5fda35ecb44804d8ba44Hostpass.myserver.ruRefererhttp://pass.myserver.ru/install/install.phpUser-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0X-Requested-WithXMLHttpRequest`

Response headers:
`Cache-Controlno-store, no-cache, must-revalidate, post-check=0, pre-check=0ConnectioncloseContent-Typetext/html; charset=UTF-8DateMon, 03 Apr 2017 11:49:46 GMTExpiresThu, 19 Nov 1981 08:52:00 GMTPragmano-cacheServerApache/2.4.25 (Debian)Transfer-EncodingchunkedX-Frame-OptionsSameOriginX-Powered-ByPHP/5.6.9`

**Comment by nilsteampassnet** [comment]
Can you please provide the apache log error?

**Comment by Negossia** [comment]
There are no entries in the apache log file.

Yes, I've read that issue, but it didn't help me. mbstring and mcrypt are installed and enabled, I see that in the phpinfo();

**Comment by Negossia** [comment]
I found an interesting thing.
If I set "display_errors = Off" in my php.ini, I have this in the browser:
`[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!`
But if I set "display_errors = On", I have such behavior:
https://github.com/nilsteampassnet/TeamPass/issues/1715

**Comment by nilsteampassnet** [comment]
Have you tried to re-upload once again the files?
Maybe one file has been corrupted during tranfert.

**Comment by Negossia** [comment]
Yes, I have. I'm sure it's not a file transfer error.

**Comment by berrydejager** [comment]
I experience the same problem here (Ubuntu Server LTS 16.04 with tasksel LAMP enabled). My phpinfo.php page tells that PHP 7.0 is installed.

However when starting the installation the following error is shown:

`
    Directory "/install/" is writable 
    Directory "/includes/" is writable 
    Directory "/includes/config/" is writable 
    Directory "/includes/avatars/" is writable 
    Directory "/files/" is writable 
    Directory "/upload/" is writable 
    Directory "/includes/libraries/csrfp/libs/" is writable 
    Directory "/includes/libraries/csrfp/js/" is writable 
    Directory "/includes/libraries/csrfp/log/" is writable 
    PHP extension "mcrypt" is loaded 
    PHP extension "mbstring" is loaded 
    PHP extension "openssl" is loaded 
    PHP extension "bcmath" is loaded 
    PHP extension "iconv" is loaded 
    PHP extension "xml" is loaded 
    PHP extension "gd" is loaded 
    PHP extension "curl" is loaded 
    PHP function "mysqli_fetch_all" is available 
    PHP version is greater or equal to 5.5.0 
    Execution time limit 

[ERROR] Answer from server is empty. This may occur if PHP version is not at least 5.5. Please check this this fit your server configuration!`

The /var/log/apache2/error.log give the following errors on each click on the "Launch":

`[Tue Aug 22 13:05:02.285151 2017] [:error] [pid 6925] [client #.#.#.#.:58564] PHP Fatal error:  Uncaught RuntimeException: You need the Multibytes extension to use PHPSecureSession\\SecureHandler in /var/www/html/teampass/sources/SecureHandler.php:35\nStack trace:\n#0 /var/www/html/teampass/sources/SecureHandler.php(207): PHPSecureSession\\SecureHandler->__construct()\n#1 /var/www/html/teampass/install/install.queries.php(14): require_once('/var/www/html/t...')\n#2 {main}\n  thrown in /var/www/html/teampass/sources/SecureHandler.php on line 35, referer: https://SERVERNAME/install/install.php`

What can i do to resolve this?

**Comment by cdsgalaxy** [comment]
Same here:
[php7:error] [pid 21566] [client 172.19.39.226:60560] PHP Fatal error:  Uncaught RuntimeException: You need the Multibytes extension to use PHPSecureSession\\SecureHandler in /var/www/html/teampass/sources/SecureHandler.php:35\nStack trace:\n#0 /var/www/html/teampass/sources/SecureHandler.php(208): PHPSecureSession\\SecureHandler->__construct()\n#1 /var/www/html/teampass/install/install.queries.php(14): require_once('/var/www/html/t...')\n#2 {main}\n  thrown in /var/www/html/teampass/sources/SecureHandler.php on line 35, referer:

**Comment by nilsteampassnet** [comment]
Please clear the web-browser cache and reload the page

**Comment by cdsgalaxy** [comment]
Tried, no luck. Also tried different browser that had not be to the site before.

**Comment by cdsgalaxy** [comment]
Thank you for the pointers, all is good now.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
