### ISSUE TITLE
cannot upload attachment 2.1.27

### ISSUE THREAD

**Issue by GTSLiDe** [nilsteampassnet/TeamPass#1721]
### Steps to reproduce
1. Edit Item
2. Upload a file
3. Click start file upload button

### Expected behaviour
Click file upload button should upload the file and save it on the server

### Actual behaviour
AJAX error: {"jsonrpc" : "2.0", "error" : {"code": 115, "message": "Invalid file extension."}, "id" : "id"}

### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache2

**Database:**
MYSQL 5.5.54-cll

**PHP version:**
5.5.32 
**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**
Chrome
**Operating system:**
OSX

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

I did some debugging and found out that the $_REQUEST["name"] in /sources/upload/upload.attachments.php (line #181) equals "value"

Here is print_r of $_REQUEST (I omitted some values):
Array
(
    [name] => value
    [chunk] => 0
    [chunks] => 1
    [PHPSESSID] =>
    [itemId] => 1126
    [type_upload] => item_attachments
    [edit_item] => true
)

Please investigate when you get a chance.

Thank You!

**Comment by nilsteampassnet** [comment]
Have you read #1709?

**Comment by GTSLiDe** [comment]
Hi Nils, I have reviewed #1709 and checked my database. I do have "status" column in "teampass_files" table.

I will try to troubleshoot more and give you more info.
Thanks.

**Comment by nilsteampassnet** [comment]
Yes please because I cannot reproduce

**Comment by GTSLiDe** [comment]
I have verified that the file extension I uploaded was allowed in the settings.

More troubleshooting:

in file sources/upload/upload.attachments.php line #181
If I change the $_REQUEST to $_POST, I will get the correct file name.
`$ext = strtolower(getFileExtension($_REQUEST["name"]));`
To
`$ext = strtolower(getFileExtension($_POST["name"]));`

Seems like $_REQUEST does not have all the valid values.

I also get this msg when upload:

`Warning: Cannot modify header information - headers already sent by (output started at sources/upload/upload.attachments.php:51) in sources/upload/upload.attachments.php on line 138

{"jsonrpc" : "2.0", "result" : null, "id" : "id"}

Warning: SessionHandler::write(): open(/tmp/sess_5, O_RDWR) failed: Permission denied (13) in sources/SecureHandler.php on line 74`

I have got a feeling I may have multiple issues and it was not caused by inside the TeamPass application. Wondering if you can guide me through on how to troubleshoot this.

Thanks.

**Comment by nilsteampassnet** [comment]
It seems you have an issue related the apache user to access folder upload_tmp_dir.

Check what is the user with `<?php echo exec('whoami'); ?>`
Check in php.ini where is located this folder, and ensure correct permissions (at least wx I beleive).

**Comment by GTSLiDe** [comment]
So, I had to replaced everything $_REQUEST to $_POST in upload.attachments.php to get the attachment to work. Looks like access was not the issue.

**Comment by baydeniz1** [comment]
@GTSLiDe $_REQUEST to $_POST in upload.attachments.php = Fixed your upload problem?

I had changed it and restarted TP Linux still uploads stucks at %93 or so. Need help.
