### ISSUE TITLE
Misleading error during KeePass import (SELinux issue)

### ISSUE THREAD

**Issue by aairey** [nilsteampassnet/TeamPass#1722]
### Steps to reproduce
1.Import KeePass 2 XML
2.Fails with error: `Can't read the file! It must be a KeePass file.`
3.Redirects to index

### Expected behaviour
It should mention that it has no write access.

### Actual behaviour
It says it is expecting a KeePass database and redirects to index.

### Server configuration
**Operating system**: CentOS 7.3.1611

**Web server:** Apache HTTPD httpd-2.4.6-45.el7.centos.x86_64

**Database:** sqlite-3.7.17-8.el7.x86_64

**PHP version:** php-5.6.30-1.el7.remi.x86_64

**Teampass version:** v2.1.27

**Updated from an older Teampass or fresh install:** fresh

### Client configuration
**Browser:** Chrome 57

**Operating system:** Fedora 25

#### Web server error log
```
[Wed Apr 05 13:27:38.185777 2017] [:error] [pid 3490] [client x.x.x.x:44888] PHP Warning:  fopen(/var/www/TeamPass/files/o1bcv4p4i41pus1g6q1kh31a852lnm.xml.part): failed to open stream: Permission denied in /var/www/TeamPass/sources/upload/upload.files.php on line 210, referer: https://......com/index.php?page=items
```

### Solution

Changed the SELinux context type of the upload directory and it is now working.

```bash
sudo chcon -R -t httpd_sys_rw_content_t /var/www/TeamPass/files/
```

There was a file ldap.debug.txt there, which I truncated as it contained a password.
Maybe to check if no unncesseray files are there.

**Comment by nilsteampassnet** [comment]
Here the issue is not related to keypass importation but to the most general `file upload` feature.
Indeed the permissions are not correct on the Teampass `files` folder.

So I've added a `is_writable` check on this folder.

What sounds strange to me, is that this check is also performed during installation.

Did you change your permissions on the folders after installation?

**Comment by aairey** [comment]
Not sure, too long ago, closing issue.
