### ISSUE TITLE
Reset salt key does not work, "please wait" forever

### ISSUE THREAD

**Issue by Cytrian** [nilsteampassnet/TeamPass#1723]
### Steps to reproduce
1. Install Teampass by building the Docker container using provided dockerfile.
2. Install mysql, create database. For simplicity, use "root" user.
3. Configure teampass.
4.  Add a user, folder, role. Enable personal folders. Disable maintenance mode.
5. Log in as the new user.
6. Go to profile, choose "Reset salt key"
7. Enter a new salt key, Press "change"
8. A "Please wait" message appeard, but nothing happens.

Tested with version 2.1.27 ("Master") and current development branch.

### Expected behaviour
Changed personal salt key.

### Actual behaviour
"Please wait!" forever.

### Server configuration
**Operating system**: ubuntu 14.04.5

**Web server**: apache 2.4.7-1ubuntu4.13

**Database**: 5.5.54-0ubuntu0.14.04.1

**PHP version*+: PHP 5.5.9-1ubuntu4.20 

**Teampass version:** master, development as of 2017-04-06

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Firefox 52.0.2 or Chromium

**Operating system:** Kubuntu 14.04

#### Web server error log
nothing

**Comment by Cytrian** [comment]
This is strange: 
In reset_personal_saltkey, data is read from POST parameter "data":
        //decrypt and retreive data in JSON format
        $dataReceived = prepareExchangedData($_POST['data'], "decode");
But my browser sends it in parameter "data_to_share" (at least in version 2.1.26)

**Comment by nilsteampassnet** [comment]
Seems to be related to #1710 

Did you use latest commit in Development branch?

**Comment by Cytrian** [comment]
Yes, tried it also with the latest commit; same problem. I'm not really sure, how this is supposed to work. When I change the case 'reset_personal_saltkey' to use the POST parameter "data_to_share' instead of 'data', the new salt is eventually stored in the session, in clear. But then, when trying the 'store_personal_saltkey' afterwards, I still have to enter the old key.

**Comment by nilsteampassnet** [comment]
Ok understood the point.
Indeed the spin is left once the operation is done.
But the reset is performed, I'm correcting this bug.

But don't change anything in the code if you want it to work.

My question now is why do you reset a saltkey if it has never been set?
You need to set a saltkey first 
![image](https://cloud.githubusercontent.com/assets/1197546/24795603/2916c9e0-1b8a-11e7-816c-e7d16fd5d1a4.png)

**Comment by Cytrian** [comment]
Okay, tested the commit f4ee395. 'Please wait' now disappears, good. But still: After a reset, when trying to "Set the salt key" I have to enter the previous key.
The same is true for "Change my personal salt key". I can change it, but for "Set the salt key" I still have to enter the previous one.

**Comment by nilsteampassnet** [comment]
Not sure to understand.
When you reset a user sk, it will delete all the personal items.
Once you have resteted a user SK, you need to "set the SK" to create new items.
Keep this SK in your mind, it is the key to decrypt your personal items.

Function "change SK" permits to change an existing valid user SK. It will re-encrypt the existing personal items with the new SK.
