### ISSUE TITLE
LDAP fails to bind

### ISSUE THREAD

**Issue by dafta** [nilsteampassnet/TeamPass#1724]
I've been trying to set up LDAP, but I can't get it to work. I have installed PHP 7.0 and all the necessary PHP modules (And some extra, just in case):
```
php7.0
php7.0-cgi
php7.0-common
php7.0-fpm
php7.0-json
php7.0-mbstring
php7.0-mysql
php7.0-readline
php7.0-xml
php7.1-common
php-common
php7.0-bcmath
php7.0-cli
php7.0-curl
php7.0-gd
php7.0-ldap
php7.0-mcrypt
php7.0-opcache
php7.0-sqlite3
php7.0-zip
php7.1-ldap
php-ldap
```

I'm running Ubuntu 14.04 LTS server, nginx and mysql server version 5.6. 
This is what I have configured in TeamPass:
![selection_002](https://cloud.githubusercontent.com/assets/13968651/24756047/b2de80d6-1adc-11e7-9aad-372bd70f734e.png)

This is my nginx configuration:
```
server {
        listen 80 default_server;
        server_name XXXXXXXXXXXXXXXXXXXXXXXXX;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl default_server;
        server_name XXXXXXXXXXXXXXXXXXXXXXXXX;

        root /var/www/html/teampass;

        access_log /var/log/nginx/teampass.access.log;
        error_log /var/log/nginx/teampass.error.log info;

        ssl_certificate /home/vaultadmin/ssl_certs/fullchain.pem;
        ssl_certificate_key /home/vaultadmin/ssl_certs/privkey.pem;

        location /{
                try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_read_timeout 300;
                fastcgi_index index.php;
                include /etc/nginx/fastcgi.conf;
        }
}
```

This is what's written in the ldap.debug.txt file:
```
Get all LDAP params : 
mode : 1
type : posix-search
base_dn : dc=XXXXXXXXXXXX
search_base : ou=People,XXXXXXXXXXXXX
bind_dn : XXXXXXXXXXXXXXXXXXXXXXXXXXX
bind_passwd : XXXXXXXXXXXXX
user_attribute : uid
account_suffix : @YYYYYYYYYYYYY
domain_controllers : YYYYYYYYYYYYYYYY
port : 636
use_ssl : 1
use_tls : 0
*********

LDAP URIs : ldaps://YYYYYYYYYYYYYY:636 
LDAP connection : Connected
LDAP bind : Failed
```

And this is what I get in the log of the OpenLDAP server:
```
Apr  6 15:02:08 ldap-server slapd[27406]: conn=15397 fd=29 ACCEPT from IP=XXX.XXX.XXX.XXX:38814 (IP=0.0.0.0:636)
Apr  6 15:02:08 ldap-server slapd[27406]: conn=15397 fd=29 TLS established tls_ssf=128 ssf=128
Apr  6 15:02:08 ldap-server slapd[27406]: conn=15397 fd=29 closed (connection lost)
```

The LDAP configuration is definitely correct. What am I doing wrong?

**Comment by nilsteampassnet** [comment]
I cannot help here, I have no knowledge of LDAP.

Perhaps some other users may help?

**Comment by WojTecH94** [comment]
Firstly I would try a not secure connection (port 389 without SSL), because LDAPS often causes some trouble.

**Comment by dafta** [comment]
It works over LDAP, but that's not an option. I need to get LDAPS to work.

**Comment by paulojjs** [comment]
Are you using a self-signed certificate on OpenLDAP or a valid one?

**Comment by dafta** [comment]
It's self-signed.

**Comment by paulojjs** [comment]
I think you are having this problem: http://stackoverflow.com/a/25425078

**Comment by dafta** [comment]
Ah, I have added the root CA, but I didn't change /etc/ldap/ldap.conf. It works now, thanks!

**Comment by burnbabyburn** [comment]
@nilsteampassnet close?

**Comment by nilsteampassnet** [comment]
Yes I think so

Thanks ... I will "FAQ" this ticket

**Comment by brandonwagner** [comment]
@dafta Is it possible to include in this thread how you turned on debugging logs and/or where you found that ldap.debug.txt file?
