### ISSUE TITLE
Teampass 2.1.27.2 - I can not edit or. delete entry in the Personal folder

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1727]
### Steps to reproduce
1. Login
2. Set personal salt key
3. Add new password in the Personal folder = OK
4. Edit or. Delete a entry in the Personal folder can not use (Not allowed)

### Expected behaviour
I can edit or. delete entry in the Personal folder.

### Actual behaviour
I can not edit or. delete entry in the Personal folder.
![image](https://cloud.githubusercontent.com/assets/26093484/24948791/c7a0e746-1f6b-11e7-8c40-6a0b86f81755.png)

### Server configuration
Operating system: CentOS Linux release 7.3.1611

Web server: httpd 2.4.6

Database: mariadb 5.5.52

PHP version: 5.5.38

Teampass version: 2.1.27.2

Updated from an older Teampass or fresh install: Update from TeamPass-2.1.27.1

### Client configuration
Browser: Newest Firefox

Operating system: Windows 10 64Bit

#### Web server error log
```
No errors in the web server error log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
```

**Comment by elflan** [comment]
Hello,

same issue for me.
Same version of TeamPass (2.1.27.2, updated from 2.1.26)

**Comment by userrst** [comment]
Hello

I install now the version 2.1.27.3 from Teampass and now i can edit the entry from personal folder but not delete.
Same message:
![image](https://cloud.githubusercontent.com/assets/26093484/25425064/f556c2d2-2a6a-11e7-8e44-30a2f5eaf548.png)

**Comment by userrst** [comment]
Hi
I install now the new version 2.1.27.4 and the problem was fixed.

**Comment by abdoulayeAziz** [comment]
on teampass 2.1.27.9 i could not see the items option: some issue for that?

**Comment by mmance** [comment]
TeamPass 2.1.27.16   I have this same issue.

**Comment by nilsteampassnet** [comment]
what is your exact problem?
Please provide instruction

**Comment by mmance** [comment]
if I use my email for a user account mmance@spiritkeepers.church.  It
tells me that it is not an email.  If I add .com to the end of it, it
passes whatever validation your doing.

**Comment by christovamps** [comment]
Hello.
Same problem. Both to edit and delete.
Any outline solution?
TeamPass 2.1.27.16

**Comment by christovamps** [comment]
Hi,
Updated to TeamPass 2.1.27.17, same problem. Solution?

**Comment by christovamps** [comment]
Hi,
Reapplied all permissions in "Manage Roles" and it worked.
Strange having to do this. This had not happened after an upgrade.
thank you.

**Comment by asantar0** [comment]
Hi @christovamps, I have the same problem, but I could not solve it in the way you indicated previously. I can create items, but I can not delete or edit them, being the manager of all of them. Could you show with images what you did in detail? @nilsteampassnet
