### ISSUE TITLE
Uploaded images are getting deleted after first time viewed.

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1728]
### Steps to reproduce
1. Upload an image (.jpg, .png) to an item.
2. View the image.
3. Reload the page and view the image again.

### Expected behaviour
You should be able to view the image again.

### Actual behaviour
The picture gets deleted at the upload folder after I watched the image once and reload the page.
The record at the database is still there.
Error message displayed: "Error: The file is missing!"

### Server configuration
Debian 8.7

Apache2.4.10

MySQL Ver 14.14 Distrib 5.5.54

php5.6.30

Teampass 2.1.26-final3

Fresh Install.

### Client configuration
Reproduced on Firefox, IE and Chrome.

Windows 7.

#### Web server error log
```
No entry concecring that problem.
```

#### Firebug log
```
Firebug log says just that the file does not exist.
```

**Comment by nilsteampassnet** [comment]
This has been fixed.
