### ISSUE TITLE
[2.1.27.2] Empty password field after upgrade

### ISSUE THREAD

**Issue by gslongo** [nilsteampassnet/TeamPass#1730]
### Steps to reproduce
1. Upgrade from 2.1.14 to 2.1.27.2

NOTE: Might be related (missing lib?) : I had to change the admin password in database because I was not able to launch the upgrade process (Exception saying it cannot detect the hash type/lib)

I noticed the sk.php was in a new format and variables was "empty" after upgrade :
`<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>
`
My original format was :

`<?php
@define('SALT', 'XXXXXXXXXXXXXXXXXXXXXXXXX'); //Never Change it once it has been used !!!!!
?>
`

Also, the teampass-seckey.txt was not created. I did but not sure of the content it should have...

### Expected behaviour
... See my password

### Actual behaviour
After update, all items are presents but not possible to show the password. 

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.6.30

**Teampass version:** 2.1.27.2

**Updated from an older Teampass or fresh install:** Update from 2.1.14 

### Client configuration
**Browser:** Firefox ESR / Chrome

**Operating system:** Debian 8

#### Web server error log
```
==> /var/log/httpd/ssl_error_log <==
[Thu Apr 13 10:16:26.200611 2017] [:error] [pid 26024] [client 10.17.252.12:59570] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoding::hexToBin() input is not a hex string.' in /var/www/TeamPass-2.1.27.2/includes/libraries/Encryption/Encryption/Encoding.php:65\nStack trace:\n#0 /var/www/TeamPass-2.1.27.2/includes/libraries/Encryption/Encryption/Encoding.php(164): Defuse\\Crypto\\Encoding::hexToBin('URmLGqtxSVajwx3...')\n#1 /var/www/TeamPass-2.1.27.2/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF0\\x00\\x00', 'URmLGqtxSVajwx3...')\n#2 /var/www/TeamPass-2.1.27.2/sources/main.functions.php(378): Defuse\\Crypto\\Key::loadFromAsciiSafeString('URmLGqtxSVajwx3...')\n#3 /var/www/TeamPass-2.1.27.2/sources/items.queries.php(1261): cryption('def50200d1acd13...', '', 'decrypt')\n#4 {main}\n  thrown in /var/www/TeamPass-2.1.27.2/includes/libraries/Encryption/Encryption/Encoding.php on line 65, referer: https://teampass//index.php?page=items
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by xelgand** [comment]
I'm experiencing the same issue, upgrading from 2.1.9.
The sk.php had an empty salt too and even if the upgrade script finished with no errors, I can't see any passwords.
I wonder if the upgrade from 2.1.9 works for an older version.

**Comment by gslongo** [comment]
I tried a lot of versions to upgrade. Everytime, there is something which goes wrong >_>

I've heard 2.1.23 could work... I will try

**Comment by nilsteampassnet** [comment]
One solution

> Finally I found a solution. I didn't tried all the upgrade scenarios.
The good way to proceed is to upgrade directly from the 2.1.13 to the 2.1.24, then update manually to the wanted version.

Sorry for those troubles ... Teampass has now found the correct way to encrypt the data from 2.1.27, and it will not change anymore.

**Comment by xelgand** [comment]
Where can I get a copy of the 2.1.13 version?
I only see 2.1.20 and newer in this repository.
