### ISSUE TITLE
Teampass slow after fresh install

### ISSUE THREAD

**Issue by pokix** [nilsteampassnet/TeamPass#1732]
Hello, I have some troubles with the latest version of Teampass (2.1.27-2). On a very fresh install without creating anything, the options "Manage folders" and "settings" are very slow to load (30 seconds). On the same server, I don't have this problem with the 2.1.26.

### Steps to reproduce
1.Install 2.1.27-2
2.Go to Manage folders, settings, or even disconnect user
3.Wait 30 seconds

### Server configuration
The server is running on a Debian base OS, with 8Go RAM, 8 CPU, and works on Docker containers (without hardware restriction)

### Client configuration
Google Chrome

Did you face the same trouble ?

Thanks in advance.

**Comment by nilsteampassnet** [comment]
I could not reproduce this.
Currently using the last development commit

**Comment by jraigneau** [comment]
Hello,

I have the same issue with 2.1.27, Fresh install with 3 users and 5 folders
- VM Ubuntu 16.04+mysql+PHP7 // 1vCPU // 2Go RAM
- Safari

Regards,

**Comment by emrahcetiner** [comment]
Is there any improvement?

**Comment by Didldu-Florian** [comment]
I got the same problem here
