### ISSUE TITLE
"Copy Item" doesn't work

### ISSUE THREAD

**Issue by elflan** [nilsteampassnet/TeamPass#1733]
### Steps to reproduce
1. Select any item
2. Chose Copy Item

### Expected behaviour
Tell us what should happen

### Actual behaviour
Form appears to select de destination folder
when clicking "OK" Nothing happens

### Server configuration
QNAP QTS 4.3.3

**Web server:**
Apache 2.2

**Database:**
5.5.51-MariaDB

**PHP version:**
5.6.29

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
Update from 2.1.26 to 2.1.27

### Client configuration
**Browser:**
Chrome, Opera, Firefox

**Operating system:**
QTS 4.3.3

#### Web server error log

Insert your webserver log here

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

Insert the Firebug log here

[{"error" : "case_not_managed"}, {"error_text" : "ERROR - case is not managed"}]

**Comment by reginfo** [comment]
The same problem in 2.1.27.2
