### ISSUE TITLE
Disabling the use of Saltkey for Personal Folder?

### ISSUE THREAD

**Issue by mbottos** [nilsteampassnet/TeamPass#1734]
Hi, 
first time questioner, long time user.

I recently setup the new release 2.1.27.
Everythings functioning as expect however, when I try to add a password to my personal folder, it states that I must create my saltkey.
In an older release we setup a few year ago, we didn't have to use Saltkeys to use the personal folder.

I've looked everywhere but found no way to disable the need for creating a Saltkey.

Do I have any options here?  I don't want our users to have to remember another passcode or risk them losing it and then not being able to recover their passwords.

This is LDAP'ed by the way.

Thank you!

 
### Steps to reproduce
1. Add password entry to Personal Folder on fresh install
2.
3.

### Expected behaviour
Tell us what should happen

Shouldn't require a Saltkey creation to create a password entry in personal folder

### Actual behaviour
Tell us what happens instead

Forces you to create Saltkey before allowing you to add a password to the Personal Folder

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Apache 

**Database:**
MariaDB

**PHP version:**
5.5

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration

**Browser:**
Edge, Chrome

**Operating system:**
Win10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Teampass always had a personal saltkey from the 1st version.
But it exists a feature permitting to use the user password as personal saltkey.

I think it was enabled in your previous instance.

**Comment by mbottos** [comment]
That would make sense. Thanks for the response.
Could I trouble you for the steps involved in using the password as the saltkey?
I cant seem to find instructions and I don't see a checkbox to allow for this.

Worth mentioning, users will login with their windows AD credentials which is LDAP;
If they change their windows password, would the password now not match the saltkey?
thanks!

**Comment by WojTecH94** [comment]
How can I asure that the feature you @nilsteampassnet mentioned is disabled? I am asking because my users change their passwords every 30 days due to Domain restrictions, so I understand that there is a possibility that they can loose all their personal passwords every month.
