### ISSUE TITLE
PHP extension "curl" is loaded   Extension curl is not loaded!

### ISSUE THREAD

**Issue by Toutzn** [nilsteampassnet/TeamPass#1735]
insert in your Dockerfile

**php5-curl**

`RUN apt-get update && apt-get install -y git apache2 php5 libapache2-mod-php5 php5-mcrypt php5-mysqlnd php5-ldap php5-gd php5-curl`

and add the row

`RUN php5enmod curl`

**Comment by nilsteampassnet** [comment]
Thank you

**Comment by Toutzn** [comment]
You welcome. 
Can i open a new feature? How can i do that for you?

**Comment by nilsteampassnet** [comment]
I just need to update the Dockerfile file from the root of Teampass project

**Comment by nilsteampassnet** [comment]
@Toutzn, you can open new feature request from http://teampass.userecho.com/
