### ISSUE TITLE
Dear Nils, Is there a feature that i can get a notification for password renewal . so that i can change the password before it gets expired and change the renewal date.

### ISSUE THREAD

**Issue by selvamaniaj** [nilsteampassnet/TeamPass#1736]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
There is currently no such feature.

It could be added in the future.
