### ISSUE TITLE
Cannot import KeePass 2.x XML

### ISSUE THREAD

**Issue by Tmkrth** [nilsteampassnet/TeamPass#1737]
Good day, I seem to be unable to import a KeePass 2.x xml-file into TeamPass. The page replies "cannot read file, must be a KeePass file" and no import takes place.

The webserver shows errors: `[Thu Apr 20 14:55:35.729932 2017] [:error] [pid x] [client x] PHP Warning:  SessionHandler::write(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /var/lib/teampass/sources/SecureHandler.php on line 74, referer: https://x/teampass/index.php?page=items` and `[Thu Apr 20 14:55:35.729948 2017] [:error] [pid x] [client x] PHP Warning:  session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in Unknown on line 0, referer: https://x/teampass/index.php?page=items`

The upload from my browser to the server's teampassroot/files/ works, I can find the to-be-imported files there afterwards, renamed.

I also tried with KeePass 1.x xml and csv files, on TeamPass 2.1.26, 2.1.27.1 and now 2.1.27.2. All TeamPass folders belong to the webserver, permissions are 750 for directories and 640 for files. It is a standard LAMP (Apache2, MySQL5, php7) on Ubuntu 16.04 LTS.

I have read the other issues here with similar problems depicted but am still unable to make the import happen. It would be really nice if I would not have to migrate thousands of passwords by hand. How can I make it work?

**Comment by Tmkrth** [comment]
Hello again, I read all the issues returning from search request "is:issue import" and tried all of the approaches and suggested workarounds discussed there. It is not importing.

If I want to import from a .csv it tells "you need to choose a folder" in red. But there is nothing and nowhere to chosse a folder from. If I copy the .csv to teampassroot/files/ beforehand, the error stays the same and the file gets deleted.

If I try to import a .xml it tells me that this is not a KeePass file, please note the header in my .xml: `<?xml version="1.0" encoding="utf-8" standalone="yes"?>`. If I copy that .xml to teampassroot/files/ beforehand it gives the "JSON parse error" instead and actually does create files "cpassman_..." in which I can see the correct directory structure and passwords from KeePass, but it is not landing in the WebUI.

Apache error.log constantly gives the two php warnings shown a post before which i cannot find anything related that I can do about it.

I have double checked ownership and permissions, phpmods, installed packages and all that.

Please help.

**Comment by edzoe** [comment]
no feedback on this from developers? ... I experience the same problem.

**Comment by giantsquidman** [comment]
I also experience the same issue. Didn't experience this problem in version 2.1.26.

I have the exact same setup as Tmkrth:

_I also tried with KeePass 1.x xml and csv files, on TeamPass 2.1.26, 2.1.27.1 and now 2.1.27.2. All TeamPass folders belong to the webserver, permissions are 750 for directories and 640 for files. It is a standard LAMP (Apache2, MySQL5, php7) on Ubuntu 16.04 LTS._

**Comment by nilsteampassnet** [comment]
I confirm that a bug exists here.
It requires deep investigation as I couldn't found the bug during simple code review.

**Comment by nilsteampassnet** [comment]
Cause identified.
Commit with fix was performed https://github.com/nilsteampassnet/TeamPass/commit/79440104f5eeda75ed1626f90706987012b8d12b

Quick change. Open file `items.import.php`
Replace
```
                        "PHPSESSID":"'.$_SESSION['user_id'];?>",
```
by
```
                        "PHPSESSID":"<?php echo $_SESSION['user_id'];?>",
```

**Comment by nutt318** [comment]
I've changed the code in the file and restarted all services. I'm still getting an error while importing 'Can't read the file! It must be a KeePass file.' I've also removed the master password from the KeePass database and export the xml file but still no luck.

TeamPass 2.1.27 with above fix applied, added in both places
Running on Windows WAMP stack, tried both version of PHP and restarted all services
KeePass XML file is 2,908KB

Still getting the above error while importing KeePass xml file.

**Comment by nilsteampassnet** [comment]
Did you perform the upgrade then?

**Comment by nutt318** [comment]
The upgrade would never complete so I downloaded the new .3 version and did a new install. It still wouldn't import and looking back at the files they still had old code. Not sure if I didn't get the correct version but it did say TeamPass-2.1.27.3.zip and the old code still was in there. 

Any ideas? I'll do a new install again if thats the easiest.

**Comment by nilsteampassnet** [comment]
Perhaps something relating to the size of the file imported.
With the browser console, can you get the result of the execution of upload.files.php?
It should contain interesting things.

**Comment by nutt318** [comment]
@nilsteampassnet Not sure exactly what I'm looking at but I think this is what your wanting. Hope this helps.
![image](https://cloud.githubusercontent.com/assets/1442171/26126885/f15664c0-3a4c-11e7-9517-0e8cec53384c.png)

**Comment by nilsteampassnet** [comment]
There doesn't seem to have an error  during the file transfert itself.

I don't really understand what happen here.
I would need to access the server, possible?

**Comment by nutt318** [comment]
@nilsteampassnet Sure, do you have an email I can send a webex invite to?

**Comment by nilsteampassnet** [comment]
nils@teampass.net

**Comment by nilsteampassnet** [comment]
Fixed on user server.

@nutt318, I'm looking for testimonials for the new website. Could I hope to have yours?
A small one would be great. We can discuss by email.

**Comment by nutt318** [comment]
@nilsteampassnet  email sent :)

**Comment by nilsteampassnet** [comment]
@nutt318, I did not received your email. can you resend it please?

Thanks

**Comment by nutt318** [comment]
Nils,

Here is some feeedback, thanks again for the help. Look forward to .4 release.

We've been using TeamPass for a few weeks and will be rolling it out to the entire company soon. You can't find a better team password solution out there for free with as many features as this one! Highly recommended.

Thanks,
Jake

**Comment by 009thomas** [comment]
> Nils, Here is some feeedback, thanks again for the help. Look forward to .4 release. We've been using TeamPass for a few weeks and will be rolling it out to the entire company soon. You can't find a better team password solution out there for free with as many features as this one! Highly recommended. Thanks, Jake
> […](#)
> Sent from my iPhone
> On May 27, 2017, at 8:01 AM, Nils Laumaillé ***@***.***> wrote: @nutt318, I did not received your email. can you resend it please? Thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.



> Nils, Here is some feeedback, thanks again for the help. Look forward to .4 release. We've been using TeamPass for a few weeks and will be rolling it out to the entire company soon. You can't find a better team password solution out there for free with as many features as this one! Highly recommended. Thanks, Jake
> […](#)
> Sent from my iPhone
> On May 27, 2017, at 8:01 AM, Nils Laumaillé ***@***.***> wrote: @nutt318, I did not received your email. can you resend it please? Thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hi Jake,
Any best practices for keeping the folder names and subfolder names ?
