### ISSUE TITLE
saltkey disappear after logout?

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1738]
### Steps to reproduce
1. login after upgrade
2. navigate to personal folder
3. create saltkey
4. encrypt passwords
5. logout

### Expected behaviour
after new login your personal passwords are visible

### Actual behaviour
need to create saltkey again after every login to your account to be able to see passwords in personal folder
![tp](https://cloud.githubusercontent.com/assets/19763370/25332570/46bdf4f4-28e7-11e7-8886-237eb5922caf.PNG)

### Server configuration
Operating system:
Debian

Web server:
Xampp

Database:
5.5.5-10.1.13-MariaDB

PHP version:
5.6.23

Teampass version:
2.1.27.3

Updated from an older Teampass or fresh install:
updated from 2.1.26-final-3
Client configuration

Browser:
any

Operating system:
Windows 10

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
It is normal.

It doesn't ask you to create a new saltkey, it asks you to enter it.
After being unloged, this key is deleted from the session and you need to re-enter it.

The personal saltkey guarantees  each user that his personal passwords could not be uncrypted by any one
