### ISSUE TITLE
Missing some navigation buttons on users page

### ISSUE THREAD

**Issue by WojTecH94** [nilsteampassnet/TeamPass#1740]
similar to #1654 

### Steps to reproduce
1. Have more than 20 users registered
2. Go to Manage Users
2. Try to use navigation (3,4...n,next,last)

### Expected behaviour
if there is more users than listed, some more buttons (3,4...n,next,last) should be active

### Actual behaviour
I have 46 users but I can see only 20 of them (1-10 on the 1st and 11-20 on the 2nd page) when i go to 2nd page it looks like it would be the last one but it shouldn't. Increasing show ... entries value is helping.

### Server configuration
**Operating system**:
Debian

**Web server:**
Xampp

**Database:**  	
5.5.5-10.1.13-MariaDB

**PHP version:**
5.6.23

**Teampass version:** 
2.1.27.3

**Updated from an older Teampass or fresh install:**
updated from 2.1.26-final-3

### Client configuration
**Browser:**
any

**Operating system:**
Windows 10

#### Web server error log
I dont see any.

**Comment by nilsteampassnet** [comment]
I'm starting to investigate this
