### ISSUE TITLE
Add Category button isn't available in translations

### ISSUE THREAD

**Issue by roru69** [nilsteampassnet/TeamPass#1745]
Found a button that is not translated!

### Steps to reproduce
1. Log in as Admin
2. Goto setup, and then to Categories.
3. Find the "Add Category" button.

### Expected behaviour
When another language is selected (In my case dutch) , the button should show the text in the selected language.

### Actual behaviour
When "Dutch" is selected as language the text in the button is still  in "English"

### Server configuration
Debian 8.7
Apache 2.5
Mysql 5.5
PHP 5.5
Teampass 2.1.27 

--------------------------------
Found in: admin.settings_categories.php - Line 191 

Kind regards roru69

**Comment by nilsteampassnet** [comment]
COrrect.

I missed this string.
