### ISSUE TITLE
Unable to download Picture attachments. Teampass 2.1.27

### ISSUE THREAD

**Issue by roru69** [nilsteampassnet/TeamPass#1746]
I'm not able to download image files (.png, .jpg) attached to entries, teampass throws the message 'Error: The file is missing!'. Uploading works just fine. When when the file is added to the entry, it appears on the server.

Other files types like XLS, DOC, PDF open ok.

When I try to access the image files, I get the message: "The file is missing". And on the server "_delete" is added to the filename.

Kind regards,

Roru69

**Comment by nilsteampassnet** [comment]
It makes me think to an old bug.
I've tested and couldn't reproduce on 2.1.27.3.

Can you please confirm that you have the latest release installed?

**Comment by roru69** [comment]
I have the latest master installed. Tried the latest developement, same result.

Debian = 8.7
MySQL= 5.5.55-0+deb8u1
PHP Version = 7.0.18-1~dotdeb+8.1

/var/www/example.com/public_html/teampass
https://www.example.com/teampass
/media/shares/teampass/upload
https://www.example.com/teampass/upload
/media/shares/teampass/files
https://www.example.com/teampass/
https://www.example.com/teampass/favico.ico

The upload and the file share are on another server these shares (upload and files) are mounted via fstab at boot  in the: /media/shares/teampass/ directory. 

When I upload the jpg file. It is encrypted and created on the share (as expected). When i try to view it, a decrypted copy is created, "_delete" is added to the filename of the decrypted copy. 

When i delete the uploaded jpg in Teampass, the encrypted file gets deleted on the share, the decrypted "_delete" files stays on the server.

When i relocate the upload and file folders back to their default location on the webserver. Same result. Jpg/png won't load. Other files like xls, pdf and such load just fine.

**Comment by roru69** [comment]
Tried to do the same in my local network. (No reverse proxy). Same issue. File encryption on or off gave the same results. In every case i can upload the jpg/png, and the file is present on the server, but wen I try to view the file in Teampass, is says it cannot be found.

**Comment by nilsteampassnet** [comment]
You must have an error in your log.

I've just tried once again, and the "_delete" file is created when the user is asking to see the image.
Once you close the "viewer", this file is deleted.

**Comment by roru69** [comment]
As I mentioned before, the "upload" and "files" folders are made available via a "CIFS" share named "teampass" which is mounted in: "/media/shares/teampass".

"//***.***.local/teampass /media/shares/teampass cifs credentials=/******/.tpcredentials,uid=33,gid=33"

When I configure the website to directy look in the "/media/shares/teampass/upload" folder I can't view image files. When I create a symbolic link called upload in the root of the teampass webfolder (Original location of the upload folder) then everything works just fine..

**Comment by nilsteampassnet** [comment]
It seems too complex for me. I'm not an expert in Linux.
All my tests are performed on a "normal" server settings based upon "real" folders.

Here I would need to access your server to debug the code in your specific configuration.
This can be done with screen-sharing.

**Comment by free-14** [comment]
I have the same problem, upload .jpg it writes that 100%. But when you try to download it, he writes. (Error: file not found) . It happened after this fixation. https://github.com/nilsteampassnet/TeamPass/commit/a8877c43a47f3ab5124179b08f6a9d76200b6fd8

**Comment by roru69** [comment]
If you like, I can host a teamviewer session.

**Comment by free-14** [comment]
Thank you. I solved this question. In. Htaccess stood (deny from all). There are three problems in the teampass that I would like to correct. 1) In standalone mode, in the description column shows the question marks (?????) instead of the Russian text. 2) Why is the column descriprions itself not encrypted? 3) Duration of the session, if you put 20 minutes. Then when you do to extend the session, he writes that he extended for 1 hour.

**Comment by free-14** [comment]
I'm new on this forum. If you need to split these issues into topics, tell me how?

**Comment by nilsteampassnet** [comment]
@roru69, can you contact me by mail for organizing a screensharing session?

nils@teampass.net

**Comment by roru69** [comment]
﻿Hi Nils,



I can provide an teamviewer session to my desktop where we can make an SSH connection to the Teamviewer server. We can use skype to communicate.



The only thing is that I am very busy this weekend, but next week I am free every evening.



Is Monday 20:00 hours ok for you? (Assuming that you are in the same timezone as I am?)



Kind regards,



Edwin Koning



-----Oorspronkelijk bericht-----
Afzender: Nils Laumaillé <notifications@github.com>
Verstuurd: Donderdag 15 Juni 2017 22:30
Aan: nilsteampassnet/TeamPass <TeamPass@noreply.github.com>
Cc: Edwin EH. Koning <edwin@koninkrijk.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [nilsteampassnet/TeamPass] Unable to download Picture attachments. Teampass 2.1.27 (#1746)

@roru69, can you contact me by mail for organizing a screensharing session?

nils@teampass.net <mailto:nils@teampass.net>

**Comment by nilsteampassnet** [comment]
Perfect. NExt monday will make a try.

Thank you

**Comment by roru69** [comment]
Im ready, already sent you a skype request.

**Comment by micrie** [comment]
Was the error fixed? :)

**Comment by SP00kYDuD3** [comment]
Sorry to bump an old ticket but.....

I'm seeing this error in an upgrade from 2.1.27 Ubuntu 16.04 to 2.1.27.36 on Ubuntu 18.04. All other attachments appear to work correctly.
[Sun Nov 10 23:12:19.391362 2019] [php7:warn] [pid 1956] [client 192.168.122.1:46626] PHP Warning:  file_get_contents(/data/www/smcpwd/upload/e520294d47e30471fb1a303ad9534f8d_delete.jpg): failed to open stream: No such file or directory in /data/www/smcpwd/sources/items.queries.php on line 4101

Uploads folder is accessible from a web browser it just appears that the *_delete file is never created.

**Comment by giacomin22** [comment]
I have the same problem reported by "SP00kYDuD3".
