### ISSUE TITLE
Unable to Login after a fresh install - PHP7 

### ISSUE THREAD

**Issue by sjansen1** [nilsteampassnet/TeamPass#1747]
### Steps to reproduce
1. Fresh installation of Teampass 2.1.27.3
2. Successfull configured using the installation wizard
2. Try to login as admin

### Expected behaviour
Logging into Teampass

### Actual behaviour
Nothing, just an endless spinning wheel after entering credentials.

### Server configuration
**Operating system**:
CentOS 7 64bit (selinux disabled)

**Web server:**
Apache 2.4.6-45

**Database:**
MariaDB 5.5.52

**PHP version:**
PHP 7.1.4

**Teampass version:** 
2.1.27.3

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
Chrome, Firefox, IE

**Operating system:**
Windows 10

#### Web server error log
```
From Access Log: opening site + login
a.b.c.d - - [04/May/2017:14:43:33 +0200] "GET / HTTP/1.1" 200 49731 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
a.b.c.d - - [04/May/2017:14:43:33 +0200] "GET /index.php?page=items HTTP/1.1" 200 51112 "https://teampass.xxx.yyy/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
a.b.c.d - - [04/May/2017:14:43:33 +0200] "GET /favicon.ico HTTP/1.1" 404 209 "https://teampass.xxx.yyy/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
a.b.c.d - - [04/May/2017:14:43:48 +0200] "POST /sources/identify.php HTTP/1.1" 200 18 "https://teampass.xxx.yyy/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"

Error Log: nothing
```
Checked table teampass.teampass_log_system and it is empty.

**Comment by nilsteampassnet** [comment]
Please refer to #1630

**Comment by sjansen1** [comment]
Same issue after downgrading PHP (Apache Version Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.18)

I setup a new machine a try Ubuntu 16.04. with default PHP Packages.

**Comment by nilsteampassnet** [comment]
You have exactly those error logs?
Can you please check?

**Comment by MagicFab** [comment]
Description should be renamed to include mention of PHP7 to make this distinct from #1744.
