### ISSUE TITLE
Can't save any passwords (solved)

### ISSUE THREAD

**Issue by StraderCGN** [nilsteampassnet/TeamPass#1748]
**### Steps to reproduce**
1. On a fresh install i tried to create a password item
2. in password & visibility i type a password according the required password streng, in this example weak with 9 characters with only
3. if i tried to save it

**### Expected behaviour**
It should be saved a password

**### Actual behaviour**
It dont save the password.  The interface show the message 
Password longer than system maximum (default 40 characters).

**### Server configuration**
**Operating system**:

Ubuntu 16.04

**Web server:**
Apache2 - 2.4.18-2ubuntu3.1

**Database:**
Mysql Server version: 5.6.34-79.1-79.1 Percona XtraDB Cluster

**PHP version:**
7.0.15-0ubuntu0.16.04.4 

**Teampass version:** 
TeamPass 2.1.27  

**Updated from an older Teampass or fresh install:**
nope

### Client configuration
**Browser:**
Chrome, Firefox, Safari

**Operating system:**
MacOS 10.12.13

#### Web server error log
[Thu May 04 13:19:57.506443 2017] [:error] [pid 1273] [client 10.68.69.10:55511] PHP Notice:  Undefined index: pwd_maximum_length in /var/www/html/sources/items.queries.php on line 143, referer: http://teampass1.****/index.php?page=items

It seems it can't match the maximum password lenght. I guess it matched to zero so every password can't be saved. If i comment the following lines then it works:

            // Check length
            if (strlen($pw) > $_SESSION['settings']['pwd_maximum_length']) {
                echo prepareExchangedData(array("error" => "ERR_PWD_TOO_LONG"), "encode");
                break;
            }

**Comment by StraderCGN** [comment]
Strange, i change the global Maximum password length and now it works normaly...

**Comment by nilsteampassnet** [comment]
Thank you for the tip
