### ISSUE TITLE
upgrade from 2.1.26.17 to 2.1.27 : teampass-seckey.txt does not exist!

### ISSUE THREAD

**Issue by ericxuo** [nilsteampassnet/TeamPass#1749]
Hi,

I've followed this (http://teampass.net/2014-06-28-upgrade) to upgrade my teampass version from 2.1.26.17 to 2.1.27 :

Step 1 had one error (red stuff displayed) on the php bcmath missing. I run NEXT as it was not a stopping issue.
Steps 2 and 3 : ok
Step 4 : An error occurred. Please check and relaunch.
18:14:38 - ERROR: /export2/TeamPass/teampass-seckey.txt does not exist!
18:14:38 - upgrade_run_defuse_for_files.php - Loop #1 (RED STUFF)

For debugging, I run :
chmod -R 777 /export2/TeamPass/
chown -R apache:apache /export2/TeamPass/

ls -als /export2/TeamPass/
4 drwxrwxrwx  2 apache apache 4096 août  14  2016 .
4 -rwxrwxrwx  1 apache apache  220 août  14  2016 sk.php

But I still have the same error after I LAUNCH again.

my teampass directory is under /var/www/html/teampass  which is a symbolic link to /usr/share/TeamPass
/export2/TeamPass is the directory that contains my sk.php file. It is outside the main teampass directory.

### Server configuration
**Operating system**:
Mageia x86_64
**Web server:**
Apache
**Database:**

**PHP version:**
PHP 5.6.30 (cli) (built: Jan 26 2017 00:22:46) 

#### Web server error log
I don't have any error in /var/log/httpd/*

The install/upgrade.log :
Starting suggestion.

All finished.

Could you help me on this teampass-seckey.txt issue. The post I've read didn't help me.

Regards.

Xuo.

**Comment by nilsteampassnet** [comment]
Curious, you didn't upgrade to 2.1.27 previously?
The error you encounter with teampass-seckey is shown when the upgrade process identified a specific field in Items table that is only created during 2.1.27 installation.
Can you please do the next check?
With phpmyadmin (or any other mysql mean), open the structure of Items table, and check if field `encryption_type` exists.

**Comment by ericxuo** [comment]
Hi,

Thank you for your help.
I don't use git to update (I should if it is possible) but I download each time a new zip file. So I think my current teampass version is 2.1.26.17 if I trust my teampass directory name.
The field encryption_type exists in the "Items" table. All values are set to "defuse".

Regards.

Xuo.

**Comment by nilsteampassnet** [comment]
If you have this field in `Items` table then you have upgraded to 2.1.27.

What you need to do, is to restore the backup of your 2.1.26.x database, and then restart upgrading.

**Comment by ericxuo** [comment]
Hi,

I did what you suggested and now the upgrade process finished properly. I don't know what I did but it was probably/surely/effectively something wrong.
Thank you for your help.

Regards.

Xuo.
