### ISSUE TITLE
Can I find back my personal salt key?

### ISSUE THREAD

**Issue by troptop** [nilsteampassnet/TeamPass#1750]
Hi,

I dont remember my personal salt key.
Is there any wait to get it back?
Is it stored somewhere?
If the salt key works like a password, Is it possible to bruteforce the salt key to find it back?

Thank you

Cyril

**Comment by nilsteampassnet** [comment]
No there is no way to get it back.
Bruteforce is always possible because no system is unbreakable, but defuse is known to have a good level of resistance as the passwords are hashed
Teampass relies on this library to guarantee that the passwords are stored in a secure manner.
Personal Saltkey is a key to hash the password.
By design it is not stored to guarantee that the user's data will never been "visible" by an administrator for example.
So for me, try to guess it back or your personal items are lost.

**Comment by troptop** [comment]
Thank you for your quick answer.
There is different location where we can change the salt key and I am a little bit lost.
I have one in my profile -> to change the personal salt key (can not get it back)
there is one in a config file -> for the global configuration (readable in the config file)
and there is one on the password item page (see the attachment).
Is it possible to get back this salt key ?

Thank you

Cyril
![screenshot at may 09 13-40-37](https://cloud.githubusercontent.com/assets/16471920/25849032/1ffdf9ae-34bd-11e7-8765-abab351506f7.png)

**Comment by nilsteampassnet** [comment]
You are mixing some data here.

Keep in mind 2 things.
"Public" passwords are encrypted with "global saltkey", meaning the one that is defined in the teampass-seckey.txt (from 2.1.27) or sk.php (before 2.1.27).
"Personal" passwords are encrypted with a personal saltkey (only known by each user).

Now

- `Set the salt key` feature permits you (as a user) to enter your personal saltkey that will be used during your session to decrypt your personal passwords.

- `Change personal saltkey` => http://teampass.readthedocs.io/en/latest/features/feat-prof/#change-personal-saltkey

- Don't change the saltkey inside the config file. You would break all public passwords.


> Is it possible to get back this salt key ?

As explained, this is not possible to get back the personal saltkey. It is only known by the user.

**Comment by troptop** [comment]
Hi,

What can be the issue if I can not read the public password.
I have never change the public salt key in the config file sk.php, I did not know it was in the file before you told me.(you can find how it looks like in the picture in attachment).
When I see that I am afraid that I lost all my password.
After a reboot the password were lost

Do you have a idea about what happened?

Cyril
![screenshot at may 12 16-13-08](https://cloud.githubusercontent.com/assets/16471920/26001825/e964ba90-372d-11e7-883c-2156436bfbd1.png)

**Comment by nilsteampassnet** [comment]
If you have this message, it means that the decryption failed.
Typically the encryption is performed with a saltkey that is different than the one used for the decryption.
Nothing can explain this unless the sk.php file content has changed.

We need to know what has been done on the server.
Can I access with screensharing to your instance? to much things to check to help you.

**Comment by troptop** [comment]
Yes, we can schedule a time to perform the screensharing session.
I am using docker with teampass, and I just found in my bash history, a command line that could explain the error : 
docker run -p 80:80 -v /teampass .... teampass 
instead of 
docker run -p 80:80 -v /teampass:/path/teampass .... teampass 

So Maybe when I first install teampass, I export the config from /teampass inside of the container to /path/teampass outside of the container, but maybe I executed it without to externalize the /teampass then it was in the container.

And I get this problem after a server reboot. 
My memory is not very good so I have a lot of doubt.

We can make a quick screensharing session though, in case you find something else.

I really like this Teampass Project, I hope you will maintain it for a long time and if you need any kind of contribution (documentation, code....), I would be really interested

Thank you 

Cyril

**Comment by nilsteampassnet** [comment]
Yes perhaps something is wring in the install itself.
Can you please confirm the docker issue?
It is nevertheless stange because many installation have been done through docker.

> I really like this Teampass Project, I hope you will maintain it for a long time and if you need any kind of contribution (documentation, code....), I would be really interested
Thank you and don't worry, it will not end ;) 
I will need testimonials for new website, so I would be please to have yours.
I would also need help for documentation and testing.

Question: are you French?

**Comment by troptop** [comment]
I will test it again and confirm the docker issue. I will let you know when done.

Yes i am french... normally people notices it when I speak because of my accent, but it is the first time that someone figures it out just by my writing :P
Very impressive

**Comment by nilsteampassnet** [comment]
Don't worry, I did not identify this whole reading your messages. But your name is typical French so that's why. 
As I'm French we could perhaps exchange in our common natural language 😉
Tu peux me contacter par mail si tu veux:nils@teampass.net

**Comment by troptop** [comment]
Oups, je viens de t'envoyer un email mais j'ai oublié de me presenter dedans.
Donc l'email provenant de Cyril Moreau c'est moi ;)
