### ISSUE TITLE
What ist my new Main Salt Key?

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1751]
### Steps to reproduce
1. Change the Main Salt Key

### Expected behaviour
I should get asked to set my new Salt Key

### Actual behaviour
There is no query to set a new Main Salt Key.
Instead Teampass runs a scipt and gets also finished but what ist my new Salt Key?

### Server configuration
**Operating system**:
Debian 8.8

**Web server:**
Apache2 2.4.10

**Database:**
MySQL 5.5

**PHP version:**
PHP 5.6

**Teampass version:** 
2.1.27-3

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26 Final 3

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7 32Bit

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Since 2.1.27, the saltkey is not displayed anymore during upgrade.

It is stored inside file teampass-seckey.txt at the same place as the sk.php file.

**Comment by andyshilton** [comment]
I'm having this issue too upgrading 2.1.27 to 2.1.27-3. But when I copy and paste the key from the teampass-seckey.txt and click "launch" is doesn't seem to accept it.

**Comment by andyshilton** [comment]
I have now tried rolling back our installation, changing the salt key and trying again, but the upgrade still won't take the new salt key so I can't get the upgrade to launch.

**Comment by nilsteampassnet** [comment]
Do you have an error or something like this inside the logs?

**Comment by andyshilton** [comment]
Sorry, I should know to check the logs. I didn't think about that. I found the following in our apache2 error.log

"PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/html/teampass/sources/main.functions.php on line 208,"

**Comment by nilsteampassnet** [comment]
I think to much things are mixed on your server.
Use your backup to restore 2.1.26 version you previously had.
Then upgrade to 2.1.27.3.

**Comment by andyshilton** [comment]
Hi,

I would happily do that, except we started on v2.1.27 so there is no backup of 2.1.26 to roll back to.
