### ISSUE TITLE
Blank passwords after upgrade from 2.1.23>2.1.24

### ISSUE THREAD

**Issue by AlanKl** [nilsteampassnet/TeamPass#1752]
### Steps to reproduce
1. Install version 2.1.24 on 2.1.23
2. used instruction http://teampass.net/2014-06-28-upgrade

### Expected behaviour
Tell us what should happen
Teampass should show passwords

### Actual behaviour
Tell us what happens instead
All passwords fields are blank

### Server configuration
**Operating system**:
CentOS
**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 
2.1.23 > 2.1.24
**Updated from an older Teampass or fresh install:**
updated
### Client configuration
**Browser:**
All browsers
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by AlanKl** [comment]
I took a backup of 2.1.23 db within teampass, but i cant restore it in 2.1.23
I just get spinning gearwheel.

**Comment by AlanKl** [comment]
ok, we have this sorted, i will post solution shortly.
This was related to high amount of "enters" in description field.
They were causing problems with DB in version 2.1.24

**Comment by AlanKl** [comment]
Before change

INSERT INTO teampass_cache VALUES("54","client","<br />&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;root<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1t3l<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;192.168.1.252<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asterisk 1.4.18<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Zaptel<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />&nbsp;&nbsp;&nbsp;&nbsp;<br /><br /><br />","","4","0","","","Phone Systems","2");



After change:

INSERT INTO teampass_cache VALUES("54","client","<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;client<br />&nbsp;<br />&nbsp;root<br />&nbsp;<br />&nbsp;1t3l<br />&nbsp;<br />&nbsp;192.168.1.252<br />&nbsp;<br />&nbsp;Asterisk 1.4.18<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;Zaptel<br />&nbsp;<br />&nbsp;<br /><br /><br />","","4","0","","","Phone Systems","2");

we opened the DB in notepad ++ and replaced all ;&nbsp;&nbsp; to ;&nbsp;


hope this helps someone who have users pressing enter everywhere in description :)

After this we were able to restore DB in version 2.1.23 even though gearwheel is still spinning, DB was restored properly.

**Comment by AlanKl** [comment]
![image](https://cloud.githubusercontent.com/assets/24319704/25846830/4decd48c-34ab-11e7-9acb-5e5b9a8d1f4c.png)

hope this helps someone who have users pressing enter everywhere in description :)

**Comment by nilsteampassnet** [comment]
Very interesting.

Thank you for your return of experience.

**Comment by srihas619** [comment]
replacing ;&nbsp;&nbsp; with ;&nbsp; did not solve my problem, I am still getting the same blank password fields for all items

**Comment by AlanKl** [comment]
Hi srihas619,
Originally i had above problem but i took the backup before upgrade to 2.1.24.0
I rolled back teampass to 2.1.23.0 but i couldn't restore the db, it was giving me spinning gearwheel.
So i applied above fix and i was able to restore old db in 2.1.23.0
After that i haven't tried yet to go to 2.1.24.0

Have you tried to go back to 2.1.23.0?

**Comment by srihas619** [comment]
Hi Alan, 
I have a vm snapshot for each step so that I can switch back :) but the problem that exists is "sometimes, it logs me out as soon as I login to web page", when I examine the console on browser it informs some error in CSRF js handling. Did you get through it?

**Comment by realfm** [comment]
Hi everyone!

I have same problem - Blank passwords after upgrade from 2.1.23.4>2.1.24.0.
How can I update to latest version of teampass without loosing passwords?

**Comment by AlanKl** [comment]
Hi Realfm,

I never made the upgrade to 2.1.24.0 as i don't have time and test environment.
Anyway we are also stuck here on 2.1.23
It would be nice to know how to upgrade this

**Comment by mflage** [comment]
No answer here either, no.

This project is dead. Each upgrade step has its own nightmares. The project has become too complex and complicated for a single developer. We're looking for other solutions to keep our passwords collectively safe.
