### ISSUE TITLE
TeamPass API 2.0 : read/userpw doesn't return JSON (2.1.27.3)

### ISSUE THREAD

**Issue by gwMuraro** [nilsteampassnet/TeamPass#1754]
# The problem
## Steps to reproduce
1. enable the api, generate salt key, whitelist the ip, etc. 
2. use the following URL on  web client or with curl :
      https://.../api/index.php/userpw/m.clerc?apikey=... 
    (m.clerc is my test user)
3. Watch the server reply (I'm using Firefox)

### My (wraped) items :
![image](https://cloud.githubusercontent.com/assets/27951028/25941934/7d0851e2-363b-11e7-9e68-83754230a3d6.png)
Everything is in order ; passwords are correct, files are correct. 

### Header : 
![image](https://cloud.githubusercontent.com/assets/27951028/25942071/ff05721a-363b-11e7-87a6-97774d238cfc.png)
And status code 200

## Actual behaviour (TeamPass 2.1.27)
On the web client (firefox): 
Blank page.
Status code 200.

# Trials
I worked on ./api/functions.php
I first looked at the differences between 2.1.26 and 2.1.27. 

## api/functions.php  Line 430 : crypt
I commented this line :
```php
 $crypt_pw = cryption($data['pw'], "", "decrypt");`
```
This modification have an effect : 
I can see 2 (empty) items. 
![image](https://cloud.githubusercontent.com/assets/27951028/25943584/a8115cc6-3640-11e7-927c-65724c0316b9.png)
These items are not expected. 
However, these passwords exist in my database from the beginning. 

I uncommented the line for the following steps. 

## api/functions.php Line 391 : folder_str
I changed this line :  
```php
$folder_str = array_filter(implode(";",$folder_arr));
```
by
```php
$folder_str = implode(";",$folder_arr);
```

This time, the results matched to the expected behavior : 
![image](https://cloud.githubusercontent.com/assets/27951028/25943812/729ad26a-3641-11e7-831d-bfd953d17bf0.png)

# Questions
1. Is the "crypt" trial result is a bug ?
2. Is the array_filter function is essential ?
3. Is the suppression of the "array_filter" function trial is a good idea ?

# Configurations 
## Server configuration
**Operating system**:
Debian 8.
**Web server:**
Apache 2.4
**Database:**
MySQL Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
**Teampass version:** 
2.1.26 for successful tests
2.1.27 for failed tests
**Updated from an older Teampass or fresh install:**
updated order : 2.1.13 > 2.1.24 > 2.1.25 > 2.1.16 >2.1.27

## Client configuration
**Browser:**
Mozilla Firefox 53.0.2 (32 bits)
**Operating system:**
Windows Server 2012 (Virtual Machine)

**Comment by nilsteampassnet** [comment]
Thank you for your very detailed ticket.
So I did the next change in this file.
```
                $folder_str = array_filter(implode(";",$folder_arr));

                // get ids
                if (strpos($folder_str,";") > 0) {
                    $condition = "id_tree IN %ls";
                    $condition_value = explode(';', $folder_str);
                } else {
                    $condition = "id_tree = %s";
                    $condition_value = $folder_str;
                }
```
is changed by
```
                $folder_str = array_filter($folder_arr);

                // get ids
                if (is_array($folder_str)) {
                    $condition = "id_tree IN %ls";
                    $condition_value = $folder_str;
                } else {
                    $condition = "id_tree = %s";
                    $condition_value = $folder_str;
                }
```
Can you make a feedback. This change should make this more robust.

**Comment by gwMuraro** [comment]
It works for me, thank you Nils !
