### ISSUE TITLE
Click and hold password feature not working in IE 11 and Chrome

### ISSUE THREAD

**Issue by Jeff-Solberg** [nilsteampassnet/TeamPass#1756]
### Steps to reproduce
1.Log into to Teampass
2.Find password you want to display
3. You press and hold on the "eyeball" icon to display password and it only displays for a millisecond

### Expected behaviour
Tell us what should happen
The password should display as long as you press and click on the Eye ball icon
### Actual behaviour
Tell us what happens instead
the password goes back to all asterisks 
### Server configuration
**Operating system**:
Debian Linux
**Web server:**
XAMPP Apache 2.4.33
**Database:**
XAMP MYSQL
**PHP version:**
7.0.9
**Teampass version:** 
2.1.26
**Updated from an older Teampass or fresh install:**
Fresh INstall
### Client configuration
**Browser:**
IE 11 and Chrome ver 58 intermittently 
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
For IE11, I don't test this version. It is too old and requires too much specific code. So I'm not surprised.

But concerning Chrome, it is strange, I'm using it since years to debug Teampass.
But please update to latest version.
