### ISSUE TITLE
Backslash in username inside item

### ISSUE THREAD

**Issue by francogobbo** [nilsteampassnet/TeamPass#1757]
Hi,

In login/account field inside a stored item, if I have login name with backslash I get visualization error (probably depending on being '\\' a special character on mysql database).
esample:
instead of "domain\username"
I get    "domain&amp;#92;username"

### Server configuration
Debian 8 x64
Apache/2.4.10
mysql  Ver 14.14 Distrib 5.5.49
PHP 5.6.20-0+deb8u1
TeamPass 2.1.26 Fresh install

### Client configuration
Firefox 53.0.2 (32 bit)
Windows 7 (64 bit)

**Comment by nilsteampassnet** [comment]
In 2.1.27.4, I have this
![image](https://cloud.githubusercontent.com/assets/1197546/26743203/4b8801e6-47e1-11e7-8ca0-855d658a9be5.png)
Did I tried in the same field as you expect?

**Comment by nilsteampassnet** [comment]
Also tried with field `login`
![image](https://cloud.githubusercontent.com/assets/1197546/26752633/d04eb7b2-4854-11e7-89bc-9e2689b47e96.png)

**Comment by francogobbo** [comment]
Do you think upgrading to 2.1.27.4 will solve the problem?

What I see in 2.1.26 is the following:

![teampass01](https://cloud.githubusercontent.com/assets/23033179/26759783/ee64f1d0-4908-11e7-9166-9277889f945a.jpeg)
![teampass02](https://cloud.githubusercontent.com/assets/23033179/26759784/f2c97804-4908-11e7-8f99-2aedb1cf58bb.jpeg)

this is a query on the database:
![teampass03](https://cloud.githubusercontent.com/assets/23033179/26759786/f5a1628a-4908-11e7-9fd6-25e977a6d411.jpeg)

**Comment by Jojesp** [comment]
I do have a similar problem.

I see the backslash but when i copy the username and then paste it, it has removed it completely. When I look in MySQL the entry has &#92; where the slash should be and if I access the entry thru API I see &#92; where the slash should be. 

I run version 2.1.27.22 which seems to be the latest version.
