### ISSUE TITLE
Local User Profiles are not loading profiles in 2.1.27 and performance issues

### ISSUE THREAD

**Issue by Seemakarthik** [nilsteampassnet/TeamPass#1758]
### Steps to reproduce
1. Login to Teampass, User
2. Create a local users
3.when we login from different user who has manager role, he cant see the password contents created by another user with manager role. Both Users are part of same group and have access to folder

### Expected behaviour
He should be able to see the password items listed with folders

### Actual behaviour
when we login from different user who has manager role, he cant see the password contents created by another user with manager role. Both Users are part of same group and have access to folder

### Server configuration
RHEL 7.2

**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
PHP 5.6.30 (cli) (built: Jan 19 2017 22:31:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
FreshInstall
### Client configuration
**Browser:**
Google Chrome Version 58.0.3029.96 (64-bit)
**Operating system:**
Windows 10 Enterprise
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Very strange.
PLease provide screenshots showing this.

**Comment by Seemakarthik** [comment]
When a local user tries to login, it takes longer time , more than 10mins

![image](https://cloud.githubusercontent.com/assets/28385156/26140795/5e46079e-3af6-11e7-9873-eced509bde92.png)

When logs in by waiting 10mins or more. the access to the folder is denied. even when he is provided access to folders in user properties and by roles

![image](https://cloud.githubusercontent.com/assets/28385156/26140860/abe451c2-3af6-11e7-92e0-0e1a286c444d.png)

![image](https://cloud.githubusercontent.com/assets/28385156/26140869/b22c93c8-3af6-11e7-9330-48b8f2059010.png)

![image](https://cloud.githubusercontent.com/assets/28385156/26140876/b745b542-3af6-11e7-95a9-475ec5872b3b.png)

![image](https://cloud.githubusercontent.com/assets/28385156/26140975/33249052-3af7-11e7-8d3c-730116a6fbe6.png)

Please check.

**Comment by nilsteampassnet** [comment]
Why do you fill in "Allowed folders" as this user has role "InfriAdmins" which already contain those folders?

**Comment by Seemakarthik** [comment]
This time, as input provided by you, created an account added to InfraAdmin Role. still the same error

![image](https://cloud.githubusercontent.com/assets/28385156/26235876/1db6f832-3c8b-11e7-9ac0-8c666c1b6158.png)

![image](https://cloud.githubusercontent.com/assets/28385156/26235917/5a5df434-3c8b-11e7-81d5-b42edf9cac6b.png)

![image](https://cloud.githubusercontent.com/assets/28385156/26235971/94d2533a-3c8b-11e7-94ff-0ff6e879819b.png)
