### ISSUE TITLE
The server encountered an internal error or misconfiguration

### ISSUE THREAD

**Issue by jtthecanadian** [nilsteampassnet/TeamPass#1759]
Hi, we are experiencing a problem and can't figure out how to fix it.
When trying to access the server with a web browser, we get this error page.
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

We went through the Apache logs and found these.
[Fri May 12 06:25:28.506956 2017] [mpm_prefork:notice] [pid 1462] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri May 12 06:25:28.506997 2017] [core:notice] [pid 1462] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 12 14:24:28.541379 2017] [http:error] [pid 21496] [client 10.1.1.106:62819] AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request
[Fri May 12 14:31:54.108922 2017] [http:error] [pid 21498] [client 10.1.1.109:61221] AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request
[Fri May 12 14:41:59.106827 2017] [http:error] [pid 21494] [client 10.1.1.106:63622] AH02429: Response header name 'X-Frame-Option=SameOrigin' contains invalid characters, aborting request

Thanks for the help!

**Comment by nilsteampassnet** [comment]
Please use the latest 2.1.27.3 of it is not the case. 
It contains a fix for this.
