### ISSUE TITLE
Reset of my Personal Saltkey

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1761]
### Steps to reproduce
1. Login and go to "MyProfile"
2. Click on "Tasks" then on "Reset my personal salt key"
3. Enter a new personal salt key (e.g. "newsaltkey") and klick "change"

### Expected behaviour
The personal folder should be cleaned and the new salt key should be "newsaltkey"

### Actual behaviour
There is no error or something, there is also the "Done!" textfield.
![grafik](https://cloud.githubusercontent.com/assets/27355139/26052932/4b6a8630-3967-11e7-96cb-a6e738e47402.png)
But my personal salt key is still "oldsaltkey" and the contained passwords inside of my personal folder are still there.

### Server configuration
**Operating system**:
Debian 8.8

**Web server:**
Apache2 2.4.10

**Database:**
MySQL 5.5

**PHP version:**
PHP 5.6

**Teampass version:** 
2.1.27-3

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26 Final 3

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7 32Bit

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by dwratex** [comment]
I also observe this error using the same "Reset" process.  A new personal saltkey is not set.  The personal items remain, encrypted with the original saltkey.

Server: CentOS 7  , Apache 2.4.7 , MYSQL 5.5, PHP 5.5.9
Updated from Teampass 2.1.27.2 to 2.1.27.4
Browser: IE/Edge
OS: Windows 10 x64

php error.log when clicking change: 

[Mon Jun 05 12:22:04.045869 2017] [:error] [pid 10168] [client 192.168.101.67:62873] PHP Notice:  Use of undefined constant SALT - assumed 'SALT' in /var/www/html/teampass/sources/main.functions.php on line 205, referer: https://[my url]/teampass/index.php?page=items

browser console on clicking change:

csrfprotector.js:272 XHR finished loading: POST "https://tp002.ratex.com/teampass/sources/main.queries.php".
new_send	@	csrfprotector.js:272
send	@	jquery.js:8706
ajax	@	jquery.js:8136
jQuery.(anonymous function)	@	jquery.js:8282
(anonymous)	@	VM1994:323
dispatch	@	jquery.js:5095
elemData.handle	@	jquery.js:4766

**Comment by nilsteampassnet** [comment]
Confirmed.
Will be fixed

**Comment by nilsteampassnet** [comment]
I'll commit a fix this evening for this.
