### ISSUE TITLE
Share user rights works backwards

### ISSUE THREAD

**Issue by franrebo** [nilsteampassnet/TeamPass#1762]
### Steps to reproduce
1. Select Share User rights
2. Select user
3. Notice the allowed folders

### Expected behaviour
It should show the allowed folders.

### Actual behaviour
The Allowed folders are shown in the denied folder field.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server**: Apache  Apache/2.4.18 (Ubunt

**Database**: mysql 5.7.18-0ubuntu0.16.04.1

**PHP version**: 5.6

**Teampass version**: 2.1.27

**Updated from 2.1.26

### Client configuration
**Browser: chrome

**Operating system:  Windows 10

**Comment by BernhardK91** [comment]
Tested in Version 2.1.27.4 an approved

User-Settings:
![image](https://cloud.githubusercontent.com/assets/5526334/26492769/35706270-4216-11e7-9892-fb4e2cea07e3.png)

Share user rights-Modal:
![image](https://cloud.githubusercontent.com/assets/5526334/26492811/64395cf6-4216-11e7-8bef-9b7a8fb08d05.png)
