### ISSUE TITLE
Personal salt is not persistent

### ISSUE THREAD

**Issue by misterunknown** [nilsteampassnet/TeamPass#1763]
### Steps to reproduce
1. Install teampass
2. configure LDAP users (AD)
3. set private salt and create a password
4. logout and login again
5. You are requested to insert a private salt again

### Expected behaviour
We would expect to see our saved passwords.

### Actual behaviour
We are requested to insert a private salt.

### Server configuration
**Operating system**:
Debian 8 Jessie 64 bit

**Web server:**
Apache2.4

**Database:**
MySQL 5.6 with InnoDB

**PHP version:**
PHP 5.6.30

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**/**Operating system:**
Firefox 52.1/Debian8, Chromium 57/Debian8, Firefox 53/Windows7, IE11/Windows7

#### Web server error log
```
No information in error log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
No errors in Firebug log
```

**Comment by nilsteampassnet** [comment]
Yes by design personal saltkey is not persistent to ensure security.
It is clean-up when the session is terminated.

**Comment by misterunknown** [comment]
Ah, thanks for your clarification! Can you give me a brief explanation of what the personal salt key is used for and how it works? As far as I can see it is not stored in the database, so I guess it is not used to salt the passwords in the personal folder.

**Comment by misterunknown** [comment]
Ah, I just found the documentation of [teampass](http://teampass.readthedocs.io/en/latest/features/feat-encrypt/). This explained a lot, now I understand how this works.
