### ISSUE TITLE
TeamPass API 2.0 : delete API-made folder suppress all folders (TeamPass 2.1.27.3)

### ISSUE THREAD

**Issue by gwMuraro** [nilsteampassnet/TeamPass#1764]
Hello community, 

# Problem
#### 2. Know the folders' IDs of your test database.
Here are mine before doing anything :
![image](https://cloud.githubusercontent.com/assets/27951028/26106486/57f2506a-3a46-11e7-8f50-d84e3779ec84.png)
#### 3. Create a folder via API in a folder that already exists.
I'm using Curl for this. The 146th folder is the EXTERNE folder. 
```sh
curl -k -X GET https://.../api/index.php/add/folder/$(echo "unBonTitre;25;146;0;0" | base64)?apikey=
```
Returning the next JSON : 
![image](https://cloud.githubusercontent.com/assets/27951028/26106849/9552554e-3a47-11e7-8073-6f09b9c39be1.png)

And adding a new row in the database : 
![image](https://cloud.githubusercontent.com/assets/27951028/26107280/07351eb6-3a49-11e7-930f-b1c7bc6ec806.png)

#### 4. Delete the API-made folder.
```sh
curl -k -X GET https://.../api/index.php/delete/folder/781?apikey=
```
If you did the 0th point, you will have this return : 
![image](https://cloud.githubusercontent.com/assets/27951028/26106906/d3f36fe0-3a47-11e7-9697-f516c004df1c.png)

## Expected behaviour
The API-made folder is deleted, and all his childrens too (items, folders, etc.).

## Actual behaviour
All the non-personal folders are deleted instead (from root). 
Here is the database after deletion : 
![image](https://cloud.githubusercontent.com/assets/27951028/26107007/27ab2ce0-3a48-11e7-9fc5-8d7ea963acc9.png)

# Trials 
## Database 
I've found that the folder has a nlevel 0 ; It should be at 3. It nleft and nright values are 0 too. I've tried to chage manually the nlevels to 3. Nothing new happens, the problem is still here. I suspect the add/folder function being the cause of our problem, but I'm not sure. 

## api/functions.php
I suspect this line of code : 
L.1631
```php
$folders = $tree->getDescendants($array_category[$i], true);
```
In debug mode, I can see that `$folders` is composed of ones (which corresponds to the INF folder). It's coherent with the nlevel of API-made folders (as it is a level 0, all the non-personal level 1 folders are his descendant). But it should not have any descendant, because it is empty.

Moreover, I don't understand this condition very well (L.1635) : 
```php
if (($folder->parent_id > 0 || $folder->parent_id == 0) && $folder->personal_folder != 1)
```

# Questions 
1. What is this condition supposed to test ? 
2. Is the "add/folder" function supposed to create a level 0 folder ? 
3. Where does the problem come from (addition or deletion) ?
4. How could it be fixed ?
5. What are the "nleft" and "nright" values ? 

# Configuration 
## Server configuration
**Operating system**:
Debian 8.
**Web server:**
Apache 2.4
**Database:**
MySQL Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb 8 2017 08:50:21)
**Teampass version:** 
2.1.27.3
**Updated from an older Teampass or fresh install:**
updated order : 2.1.13 > 2.1.24 > 2.1.25 > 2.1.16 >2.1.27
## Client configuration
**Browser:**
Mozilla Firefox 53.0.2 (32 bits)
**Operating system:**
Windows Server 2012 (Virtual Machine)

**Comment by nilsteampassnet** [comment]
Thank you.
I need to check this carefully.

**Comment by nilsteampassnet** [comment]
I've done some fix. Can you test using the `api/functions.php` file you can download from "development" branch?
