### ISSUE TITLE
Script error when users try to access some folders

### ISSUE THREAD

**Issue by tiagojonatas** [nilsteampassnet/TeamPass#1765]
### Steps to reproduce
1.Create folder structure by departments
2. All folders must be accessed by users in their departments
3.View information for each folder

### Expected behaviour
Access and view the contents of all folders

### Actual behaviour
When users try to access some folders from browsers (Mozzila, IE and Chrome) they crash and the following error occurs in browsers:
"A script on this page may be running or stopped responding. You can stop it now and open it in a debugger or wait for the script to finish.
"Script: https://192.168.10.10/teampass/.../js/jquery-ui/jquery-ui.min.js:6"

### Server configuration
Operating system: Centos 6.7 64x

Web server: Apache

Database: Mysql

PHP version:5.4

Teampass version: 2.1.26

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:Mozzila, IE and Chrome

**Operating system: Windows 10

**Comment by tiagojonatas** [comment]
![teampass error1](https://cloud.githubusercontent.com/assets/28762919/26212421/e8a84c50-3bcb-11e7-88d5-6f4ac3c4b938.JPG)

**Comment by nilsteampassnet** [comment]
Teampass requires php 5.5.x at least.

http://teampass.net/requirements

**Comment by tiagojonatas** [comment]
sorry.

I use version 5.5 really. I just informed the version wrong.

Any suggestions for solving this problem?

Thank you

**Comment by nilsteampassnet** [comment]
Really strange error in this case.

What is your browser version?

**Comment by tiagojonatas** [comment]
I use Mozzila 53.0.2, Chome last version and IE. This error occurs with all browsers. I tried to access another computer on the network and the error continues. :(

**Comment by nilsteampassnet** [comment]
jqueryui is a standard library.
never heard about such error.
Perhaps is there other errors in the logs?

**Comment by tiagojonatas** [comment]
I did not find any information about this error. Access the folder and run the tail -f / var / log / httpd / access_log command but nothing appears.

I installed a new teampass server with version 2.1.27. I made a dump of the mysql base of the server that is in trouble.

I will try to restore the base on the new server. It's possible?

**Comment by tiagojonatas** [comment]
I updated the version to 2.1.27 and the problem continues when I try to access some subfolders. I have already installed a new server and performed the database restore and the error continues. Is there a limit to the number of folders and subfolders? I do not know what else to do :(.

**Comment by tiagojonatas** [comment]
Good evening.

The problem was in the amount of characters (16 characters) in the folder. I renamed the folder to 11 characters and it worked. :) Thank you!!!

Sorry for the translation of the language.

Tiago
