### ISSUE TITLE
Teampass 2.1.27.3 - No more then 2 sides in the Manage Users menu

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1766]
### Steps to reproduce
1. Login to the Admin Page
2. Go to the Manage Users Menu

### Expected behaviour
In the manage users menu we have 21 Users and don't see the 21 User because we set the show 10 entry.
We have only two sides in the lower right corner.
![image](https://cloud.githubusercontent.com/assets/26093484/26236942/414fe30c-3c73-11e7-8118-b3e66dca0f7a.png)

### Actual behaviour
More the 2 sides in the lower right corner.
![image](https://cloud.githubusercontent.com/assets/26093484/26236973/64064210-3c73-11e7-9917-9aac8a97d79d.png)

### Server configuration
**Operating system:** CentOS Linux release 7.3.1611

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.3

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.27.2

### Client configuration
**Browser:** Newest Firefox

**Operating system:** Windows 10 64Bit

**Comment by BernhardK91** [comment]
Hi userrst,

I've testet that issue in 2.1.27.4 and there the issue seems to be fixed (didn't testet in 2.1.27.4) So I would reccommend updating to the newest version.

Best Regards,

Bernhard

**Comment by userrst** [comment]
Hi
I install now the new version 2.1.27.4 and the problem was fixed.

**Comment by nilsteampassnet** [comment]
reopen if needed
