### ISSUE TITLE
Cannot view items in folders

### ISSUE THREAD

**Issue by BrianSidebotham** [nilsteampassnet/TeamPass#1767]
### Steps to reproduce
1. Add a user, a role and a folder. 
2. Add write permissions for the role to the folder
3. Login as the user and add items to the folder

### Expected behaviour
I expect to be able to view the items in the folder

### Actual behaviour
I get the folder name in the treeview with the number of items I've created, but in the right pane I get `No items to display`.

### Server configuration
**Operating system**:
Debian Linux

**Web server:**
Apache2

**Database:**
mysql (on another VM)

**PHP version:**
5.6.30

**Teampass version:** 
21.27

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
Latest Chrome + Firefox

#### Web server error log
I don't think this will help

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

There are no errors on the console or anything

**Comment by nilsteampassnet** [comment]
Did you add the role to the User?

**Comment by BrianSidebotham** [comment]
Hi @nilsteampassnet Sorry for the late reply - I had added the role to the user. Still those original items are unable to be viewed, but now everything I create can be viewed. So I think we can close this ticket because I can't reproduce the original problem.

If I come across it again, I'll re-open this issue with more information.
