### ISSUE TITLE
Difficulties installing TeamPass 2.1.27

### ISSUE THREAD

**Issue by ricardoclaus** [nilsteampassnet/TeamPass#1768]
Dear,
I've come for help.
I'm trying to implement Teampass for the first time version 2.1.27.
Fresh installation.
But I'm having problems.
My Environment:
Centos 7, Apache 2.4.6, PHP 5.5.38 and MariaDB

Problems I found:
Both problems I encountered with the version of PHP 5.5 and 7.0.
The installation folder is not removed after the Wizard finishes;
I can not authenticate because the admin user is not created in the users table;
I created the user in the table, but I can not authenticate. In the Apache log I see problems with the password hash.  "Unsupported Password Hash Supplied in"

Can anybody help me?

**Comment by nilsteampassnet** [comment]
Did you installed the 2.1.27.4 release?

**Comment by ricardoclaus** [comment]
Hello Friend,
I downloaded the latest version I found in the repository. 2.1.27 has been installed.
I downloaded it this way:
# wget https://github.com/nilsteampassnet/TeamPass/archive/master.zip

**Comment by smadruga** [comment]
I was installing teampass and having the same problem. Searching, I found the #492 issue and notice that my password contained the '$' character. Without it, the installation process created the admin user and everything worked nicely.

Try to put a password without some special characters.
