### ISSUE TITLE
Difficulties installing TeamPass 2.1.27

### ISSUE THREAD

**Issue by ricardoclaus** [nilsteampassnet/TeamPass#1769]
Unintentionally I closed the previous topic.

Dear,
I've come for help.
I'm trying to implement Teampass for the first time version 2.1.27.
Fresh installation.
But I'm having problems.
My Environment:
Centos 7, Apache 2.4.6, PHP 5.5.38 and MariaDB

Problems I found:
Both problems I encountered with the version of PHP 5.5 and 7.0.
The installation folder is not removed after the Wizard finishes;
I can not authenticate because the admin user is not created in the users table;
I created the user in the table, but I can not authenticate. In the Apache log I see problems with the password hash.  "Unsupported Password Hash Supplied in"
The version that is running is 2.1.27.

I downloaded it this way:
# wget https://github.com/nilsteampassnet/TeamPass/archive/master.zip

Can anybody help me?

**Comment by smadruga** [comment]
I was installing teampass and having the same problem. Searching, I found the #492 issue and notice that my password contained the '$' character. Without it, the installation process created the admin user and everything worked nicely.

Try to put a password without some special characters.

**Comment by nilsteampassnet** [comment]
This is really strange. 
I cannot reproduce.
Just download the master zip, installed it on new database, and selected a password with special characters such as $ ! @ # and the user was created correctly in users table.
Are you sure to use the latest package from master?

**Comment by ricardoclaus** [comment]
Hello friends,
I thank the help of all you.
But unfortunately I could not run the system.
I always download the latest version of master.zip.
All attempts were made in a virtual machine. I created a snapshot before preparing TeamPass. In my attempts, I always return the snapshot and try again.
I even tried to give 777 permission in the Teampass folder.
The problems are the same: the install folder is not removed after the wizard is finished, and the admin user is not created in the database.
So I can not login as admin.
In the wizard process I get ok in every step.
The admin passwords I tried were:

ricardo#12345
ricardo123$
123ricardo
adminricardo

However, in both tests the system does not create the admin user and therefore I can not login.

**Comment by nilsteampassnet** [comment]
Can you please share your screen with me?
We can use AMMYY. Contact me by email: nils@teamapss.net

**Comment by ricardoclaus** [comment]
Nils
I sent you an email with access data by AMMYY

**Comment by nilsteampassnet** [comment]
@ricardoclaus, thank you for sharing your screen.
It helped a lot to identify the issue maybe some other users have.
I will provide  a fix and commit it.

**Comment by kumaip** [comment]
same issue here,
hope you find a solution.
Can login with admin

**Comment by nilsteampassnet** [comment]
Can you share your screen with join.me or other?
Contact me : nils@teampass.net

**Comment by kumaip** [comment]
yes i downloaded the last version

**Comment by pablomfc** [comment]
I got this problem too

During the install the entered password was:   !#f9\P/b3#!    (I stripped some letters)

Which produced the following error:

error.log:[Mon Jun 05 14:42:19.355744 2017] [:error] [pid 8301] [client 192.168.xxx.xxx:54978] PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /var/www/html/TeamPass-2.1.27.4/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/html/TeamPass-2.1.27.4/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('!#f9\\\\P/b3#!', NULL)\n#1 /var/www/html/TeamPass-2.1.27.4/install/upgrade_ajax.php(164): PasswordLib\\PasswordLib->verifyPasswordHash('!#f9\\\\P/b3#!', NULL)\n#2 {main}\n  thrown in /var/www/html/TeamPass-2.1.27.4/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: https://pw.psafe.com/install/upgrade.php

To overcome this problem  I made a workaround editing  (install/upgrade_ajax.php)

    164             // if ($pwdlib->verifyPasswordHash(Encryption\Crypt\aesctr::decrypt(base64_decode($_POST['pwd']), "cpm", 128), $user_info['pw']) === true && $user_info['admin'] === "1") {
    165             if ( true ) {

Then I was able to do the update.


Regards,
Pablo
