### ISSUE TITLE
 I can't backup teampass 2.1.26

### ISSUE THREAD

**Issue by maiconstedille** [nilsteampassnet/TeamPass#1771]
I tried to back up the web in the backup tab, but when I go to download it it throws the error:
Forbidden

You have no permission to access /teampass/sources/downloadFile.php on this server.

I tried running the shell backup by running the php script by running the command:
php script.backup.php, and the backup was run.

What permission do I need to make so that the backup can also occur over the web?

### Server configuration
CentOS Linux release 7.3.1611 (Core)

Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28

5.5.52-MariaDB  

PHP 5.6.30 (cli) (built: Jan 19 2017 22:31:39)

Teampass 2.1.26 

fresh install

### Client configuration
browser chrome
S.O Windows 10

**Comment by nilsteampassnet** [comment]
`sources/downloadFile.php` file is protected by `.htaccess`.
Please adapt to fit your security policies.

**Comment by maiconstedille** [comment]
I have no idea where to put it and which htaccess should I adjust. I tried to put in .htaccess the root of the site, the following line:
Allow from all
But it did not work.
Do you know if I should add a .htaccess inside teampass/ or if it is another location?
Can you tell me what the correct syntax would be to allow this file?

**Comment by nilsteampassnet** [comment]
In folder `sources`, you will find it.

You can edit it this way
```
<Files "downloadFile.php">
Order Allow,Deny
Allow from all
</Files>
```

This will allow all ip to access downloadFile.php.

----
*Nils @ teampass.net <http://teampass.net>*
*Teampass *- *A collaborative passwords manager*
Visit Teampass.net
Any bug? Please report in Github repository
<https://github.com/nilsteampassnet/TeamPass>
Any feature request? Propose and vote at userEcho
<http://teampass.userecho.com>​
Support? please post at Reddit <https://www.reddit.com/r/TeamPass/>​
Need help? Read the Doc <http://teampass.readthedocs.io/en/latest/>



2017-05-30 21:09 GMT+02:00 Maicon Stedille <notifications@github.com>:

**Comment by nilsteampassnet** [comment]
You will found it in `sources` folder.

You may edit it this way
```
<Files "downloadFile.php">
Order Allow,Deny
Allow from all
</Files>
```

This will alllow all IPs to execute `downloadFile.php`.

**Comment by nilsteampassnet** [comment]
Reopen if needed
