### ISSUE TITLE
Docker Container still on 2.1.26

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#1772]
### Steps to reproduce
1. install teampass via docker compose
2. finish inital setup
3. check version number

### Expected behaviour
latest stable version should be installed (2.1.27.4 atm)

### Actual behaviour
2.1.26 is installed

### Server configuration
**Operating system**:
Ubuntu Server 16.04 64bit

**Comment by nilsteampassnet** [comment]
I'm not a Docker specialist but I'm surprised as when looking to the Docker build details, I can see
![image](https://cloud.githubusercontent.com/assets/1197546/26595152/b86c7ff4-456a-11e7-811e-dad849350e67.png)
How to confirm this? or what should I check?

**Comment by mr-gosh** [comment]
the fault was on our side...
...the config yaml hat a wrong target.
it seems you only have two tags: "latest" and "development" awesome would be do have each version tagged with its version and the latest tagged additionally with "latest"

semms to be fixed for me now - thanks!
