### ISSUE TITLE
Passwords containing backslash character are not correctly stored

### ISSUE THREAD

**Issue by amatacchieri** [nilsteampassnet/TeamPass#1773]
### Steps to reproduce
1. Create an item and set a password containing escape character, for instance 14as\daad
2. Try to retrieve the password with the "copy to clipboard" function. The whole password is copied but the backslash has been deleted from the password

### Expected behaviour
retrieve the following password:
14as\daad

### Actual behaviour
Instead I obtain the following password:
14asdaad

**Teampass version:** 
2.1.26

### Client configuration
**Chrome:**

**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Yes this bug is known and was fixed.
In 2.1.27
![image](https://cloud.githubusercontent.com/assets/1197546/26751377/1bc811b0-4838-11e7-9b39-058d46e4db66.png)
