### ISSUE TITLE
Teampass 2.1.27.4 - Announce this Item by email

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1774]
### Steps to reproduce
1. Create new Item
2. Announce it by email

### Expected behaviour
Receive a new e-mail with link

### Actual behaviour
Using 2.1.27.4 version when creating new password and try to announce it by e-mail I do not receive any e-mail.

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.55
**PHP version:**
PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
**Teampass version:** 
2.1.27.4
**Updated from an older Teampass or fresh install:**
2.1.27.3
### Client configuration
**Browser:**
IE 11, FF
**Operating system:**
Windows 10 Ent 1703

We had similar problem, but it was resolved in #1417

**Comment by nilsteampassnet** [comment]
Thank you for reporting

Fixed
