### ISSUE TITLE
Teampass 2.1.27.4 - Can not decrypt a created crypted Backup

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1775]
### Steps to reproduce
1. Open Teampass in Admin Mode
2. Go to Backup menu
3. Put in the backup name without .sql
4. Push the Start Button

### Expected behaviour
Decrypt a created crypted Backup file like bck_teampass-1496260837.sql

### Actual behaviour
I can not decrypt a created crypted backup

![image](https://cloud.githubusercontent.com/assets/26093484/26687268/98e8f596-46ef-11e7-933a-e821d246b80e.png)

### Server configuration
**Operating system**: CentOS Linux release 7.3.1611

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.4

### Client configuration
**Browser:** Newest Firefox

**Operating system:** Windows 10 64Bit

#### Web server error log
```
No error Log
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
ReferenceError: reference to undefined property 0
jquery.js (line 3990, col 1)

ReferenceError: reference to undefined property "_defaultEngine"
content...chUI.js (line 76, col 5)
```

**Comment by nilsteampassnet** [comment]
I have improved this.
It now uses defuse encryption to speed up the decrypt and encrypt process.
