### ISSUE TITLE
2.1.27.4 - Allow restricting items to users and roles - Wrong Item Owner

### ISSUE THREAD

**Issue by futureweb** [nilsteampassnet/TeamPass#1776]
### Steps to reproduce
1. Activate Enable restricted-to function on items + Allow restricting items to users and roles in Options
2. Create an Entry
3. Restrict that Entry to User A (myself)
4. Try to access this Entry with User B
4a. You get Error "Access to password item denied" - Author: API [test] - Request access to modify
4b. Click Request access to modify
5. nothing happens as there is no E-Mail Address stored for User API

### Expected behaviour
The Items should belong to User A who created the Item - and "Request access to modify" should send E-Mail to User A Mail Addy ...

### Actual behaviour
nothing happens as there is no E-Mail Address stored for User API

### Server configuration
**Operating system**:
Centos 7.3.1611

**Web server:**
Apache  2.4.6

**Database:**
MariaDB 10.1

**PHP version:**
7.0.19

**Teampass version:** 
2.1.27.4

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
all

**Operating system:**
Windows 10

**Comment by futureweb** [comment]
See Screenshot:

![teampass](https://cloud.githubusercontent.com/assets/1698881/26697781/91738ad2-4713-11e7-88b8-f22cd93c03f3.jpg)

**Comment by nilsteampassnet** [comment]
I will postpone this to 2.1.28 as I will rework the API.

This Item was created via API, correct?

**Comment by futureweb** [comment]
unfortunately this Items was NOT created by API - it was created by User "reischl" ... :-/

**Comment by nilsteampassnet** [comment]
OK reproduced and fixed
