### ISSUE TITLE
2.1.27.4 - New Account Mail is sent as TEXT Mail with HTML formatting

### ISSUE THREAD

**Issue by futureweb** [nilsteampassnet/TeamPass#1778]
### Steps to reproduce
1. Create new USer Account
2. New Account Mail is sent - formattet with HTML Tags - but as TEXT MAil - not HTML
3. Mail Display is broken

### Expected behaviour
Mail should be formatted TEXT only or should be sent out as HTML Mail

### Actual behaviour
Broken Mail Display

**Comment by futureweb** [comment]
See Screenshot of Mail within Outlook:

![grafik](https://cloud.githubusercontent.com/assets/1698881/26716896/9826c318-477b-11e7-9330-f609e8d788fe.png)

**Comment by nilsteampassnet** [comment]
This is strange as HTML option is enabled.

I will investigate

**Comment by nilsteampassnet** [comment]
I've tested, and it is ok in my mailbox.
![image](https://cloud.githubusercontent.com/assets/1197546/26751195/0ec88d5e-4834-11e7-812b-65bedbbb7f3c.png)
Perhaps something related to the configuration of your mailbox?

**Comment by futureweb** [comment]
weird - seems like a Problem on our Side ... tried it again today and HTML is working ... (no changes)
Microsoft Exchange + Outlook 2016
