### ISSUE TITLE
Tree->rebuild removal to speed loading

### ISSUE THREAD

**Issue by tehnotronic** [nilsteampassnet/TeamPass#1784]
Hi

I tested removing $tree->rebuild() from https://github.com/nilsteampassnet/TeamPass/blob/master/sources/tree.php#L56 
It reduced page loading time multiple times, as tree is not rebuild in the database each time page is refreshed. I didn't notice any faults after that. Please verify, that it won't affect intended behavior and consider removing the line for better performance. 

Also items.queries.php for loading folder contents is slow, but i haven't found any solution. Looks like both JOINed SQL statements are slow and also PHP code with all the checks. Maybe you can optimize that file in the future?

**Comment by nilsteampassnet** [comment]
Yes you are absolutely right.
This rebuild is not needed there as it is called when an item is added, moved, deleted, ...

I will also try to improve the big list loading ... i have some ideas but don't know the incidence on performance.
We will see.
