### ISSUE TITLE
Error in index page with French locale enabled (2.1.27.4)

### ISSUE THREAD

**Issue by N-Mi** [nilsteampassnet/TeamPass#1785]
### Steps to reproduce
1. Set profile language to French
2. Log out
3. Log in

### Expected behaviour
Index page should load and display password tree

### Actual behaviour
Index page loads incorrectly and only displays menu entries. Browser console complains with the following message : "SyntaxError: missing ) after argument list".

See this screen capture :

![teampass](https://user-images.githubusercontent.com/3135085/26882261-2b5f575e-4b9a-11e7-8a66-83e4281e1e46.jpg)

### Server configuration
**Operating system**: 
Debian Jessie
**Web server:**
Apache 2.4.10-10+deb8u8
**Database:**
MySQL 5.5.55-0+deb8u1
**PHP version:**
5.6.30+dfsg-0+deb8u1
**Teampass version:** 
2.1.27.4
**Updated from an older Teampass or fresh install:**
Updated
### Client configuration
**Browser:**
Tested with Firefox, Chrome, Safari and Internet Explorer
**Operating system:**
Windows and Debian Unstable
#### Web server error log
```
no logs
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
16:03:06,308 SyntaxError: missing ) after argument list 1 index.php:3341:121
```

Translated string triggering the error is in includes/language/french.php line 1030. The quote character seems to be correctly escaped in this file, but it seems there's a bug somewhere that unescapes the quote when processing the page.

**Comment by romainlombart** [comment]
Hello,
It is not complete
The line 1038 must be changed as follows :
'check_data_after_reencryption' => 'Merci d\\\'effectuer une vérification de vos données. Une table de sauvegarde <b>Backup</b> a été créée durant l\\\'opération de ré-encryptage.',

**Comment by N-Mi** [comment]
Thanks, added a commit for this message also.

**Comment by nilsteampassnet** [comment]
Really strange as I'm also using French as language and don't have such issue.
Can you use the french.php file from "development" branch to make a test?

Note that language is not managed from the language files but from poeditor.
