### ISSUE TITLE
email notifications are not sent if there are any admins with empty email address

### ISSUE THREAD

**Issue by aokunev** [nilsteampassnet/TeamPass#1787]
I've updated teampass to 1.27 using git clone method. DB has been updated without issues. Noticed email notifications stopped arriving. During troubleshooting noticed OPV user was created without email address in teampass_users. That code failed to create a list of recipients and invoking @sendMail with empty recipients argument. Attaching a simple patch that fixed the issue, please consider adding to the mainline.

--- /tmp/identify.php        2017-06-05 23:02:57.490778648 -0400
+++ sources/identify.php        2017-06-05 22:40:15.048011210 -0400
@@ -996,7 +996,7 @@
             ) {
                 // get all Admin users
                 $receivers = "";
-                $rows = DB::query("SELECT email FROM ".prefix_table("users")." WHERE admin = %i", 1);
+                $rows = DB::query("SELECT email FROM ".prefix_table("users")." WHERE admin = %i and email !=''", 1);
                 foreach ($rows as $record) {
                     if (empty($receivers)) {
                         $receivers = $record['email'];

**Comment by nilsteampassnet** [comment]
Correct. 
Thank you
