### ISSUE TITLE
Absolute redirect to /index.php 

### ISSUE THREAD

**Issue by oblomov88** [nilsteampassnet/TeamPass#1788]
Hey, 
the following path in index.php (Line 131) seems to be incorrect:

`location.replace("<?php echo $_SESSION['settings']['cpassman_url'];?>/index.php?page=items");`

My installation resides in /var/www/html/teampass, so if i want to visit the page via 'localhost/teampass', i get instead redirected to 'localhost/index.php?page=items', which does not exist. This is the same for logout.php...

### Server configuration
**Operating system**: Debian Jessie 8.8

**Web server:** Apache 2.4.10

**Database:** MySQL 14.14

**PHP version:** 5.6.30

**Teampass version:**  2.1.26-final-3

**Updated from an older Teampass or fresh install:** Fresh

### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** Ubuntu 16.04

**Comment by nilsteampassnet** [comment]
Do you see the pages or a blank page?

**Comment by oblomov88** [comment]
No i get a 404 because the pages do not exist in the root directory of the webserver.

**Comment by nilsteampassnet** [comment]
Point is fixed.

Reopen on need.
