### ISSUE TITLE
2.1.26 - LDAP Integration breaks existing (local) users logging on

### ISSUE THREAD

**Issue by TheJaysH** [nilsteampassnet/TeamPass#1789]
### Steps to reproduce
1. Have Local users set up (with roles, folders etc.)
2. Add Microsoft LDAP connection 
3. Log on as LDAP user
4. Temp 3 second redirect then successful login as LDAP User.
5. logout
6. Login as previously working local user (NOT ADMIN)

### Expected behaviour
Should log in just fine as it did before LDAP

### Actual behaviour
Claims the Credentials do not exist. and refuses to let me log on to anything other than LDAP/Admin
Even after removing LDAP I can no longer log on. 

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-79-generic x86_64)

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
5.6.30-11+deb.sury.org~xenial+3

**Teampass version:**
TeamPass 2.1.26

**Updated from an older Teampass or fresh install:** 
Created on 2.1.26, Not updated. Been using for 6 months

### Client configuration
**Browser:**
Chome/firefox (tested on both)

**Operating system:**
Windows 10 x64

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Reopen on need.
