### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by StarCrate** [nilsteampassnet/TeamPass#1791]
### Steps to reproduce
1. Drag-n-drop the files in the 'www' folder
2. Goto "yourdomain.com/TeamPass-master
3. Click through anything but Preparation
4. On the Preparation site fill out everything but the salt key (or fill it out, the result is the same)

### Expected behaviour
The website should skip to "Tables creation"

### Actual behaviour
I'm getting the following error code:
"The next ERROR occurred: 'C:\inetpub\vhosts\dplusb.de\ is not a Directory!'
Please correct and relaunch."

### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Microsoft IIS 8.5
**Database:**
MySQL 5.6 Server 5.6.35 
**PHP version:**
7.1.5
**Teampass version:** 
Newest (fresh download)
**Updated from an older Teampass or fresh install:**
Fresh install
### Client configuration
**Browser:**
Firefox / Chrome
**Operating system:**
Windows Server 2012R2 / Windows 7 64bit
#### Web server error log
N/A
Insert your webserver log here
N/A

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
N/A
Insert the Firebug log here
N/A

**Comment by nilsteampassnet** [comment]
Seems related to your server.

Check paths and rights.

**Comment by burnbabyburn** [comment]
It's shitty IIS fault (i am trying to migrate my Teampass from apache to IIS)
Your path should be:

C:/inetpub/vhosts/dplusb.de

FS Checks will be okay after that.

**Comment by nilsteampassnet** [comment]
Point is fixed.

Reopen on need.
