### ISSUE TITLE
Can't add folder from API

### ISSUE THREAD

**Issue by SebAubin** [nilsteampassnet/TeamPass#1796]
Hi, I have an issue in the API that is keeping me to add a folder. I'm currently trying to create a wrapper around the API to integrate TeamPass in Remote Desktop Manager.

### Steps to reproduce
1. Add a folder throught the API like: "[...]/api/index.php/add/folder/New folder;0;0;0;0?apikey=<APIKEY>"

### Expected behaviour
The API is expecting à complexity level as a number. This should create a folder named: New folder with a Very Weak complexity level.

### Actual behaviour
Instead, it returns:
```
{
    "err": "No data exists"
}
```

The problem is that the PHP method Empty return false when the parameter is 0 as the Very Weak complexity level (http://php.net/manual/en/function.empty.php).
Line 904 in the functions.php file.

```
...
904.     if (!empty($params[0]) && ----> !empty($params[1]) <--- ) {                        
905.          if (empty($params[3])) {
906.                 $params[3] = 0;
907.           }
...
```

Thank you

**Comment by nilsteampassnet** [comment]
Correct and fixed
