### ISSUE TITLE
How to get back Admin's Right

### ISSUE THREAD

**Issue by ammajis** [nilsteampassnet/TeamPass#1797]
Hello,
After installing by mistake i made myself from admin to read only user and now can't access admin account anymore! Please guide how do I find admin rights again? Thank you very much
 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
From database manager (like phpmanager), open table `users`, edit the account that is your admin and in the field `admin` set `1` and for `readonly` set to `0`.

This should work
