### ISSUE TITLE
Upgrade from 2.1.26 to last 2.1.27.4 not working

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1800]
Hi,

I upgraded from 2.1.26 on test plateform, all the process of migration worked (like described in https://teampass.readthedocs.io/en/latest/install/upgrade/) but when I connect on the interface (cache cleared), I'm stuck on the page in attachment, no log on nginx.

![pb-teampass](https://user-images.githubusercontent.com/14218330/27644416-c67eab4c-5c23-11e7-8850-e509bcd9775d.PNG)

Everything works in 2.1.26.

By the way, it says in changelog of the 2.1.27.4 : 

New during upgrade

When upgrading, you need to indicate a valid administrator name/password, and you will also need to copy the saltkey into a password filed. It will be saved inside your database.
No database data are shown anymore. If the database information are changing, you need to update the file /includes/config/settings.php before starting upgrade.

The upgrade process doesn't answer me about that. It continues to ask to me, the path for saltkey file. Is it normal  ?

Thanks for your help.

**Comment by Hellnino18** [comment]
Et voici ce que j'obtiens dans la page de configuration : 

![pb-teampass-1](https://user-images.githubusercontent.com/14218330/27645123-a9bf5662-5c25-11e7-957b-49a7fe00933d.PNG)

**Comment by nilsteampassnet** [comment]
Something is broken in the files.

You should restart from scratch and first re-download the package ... perhaps it was corrupted.

**Comment by Hellnino18** [comment]
Hi,

I tried to download another time (zip file of 2.1.27.4, first time was the .tar.gz) replayed the entire process of upgrading, and the result was exactly the same and no log in nginx error logs.

I tried your link of teampass-master and now, I can't launch the admin connection for the upgrade process, cf attachment below : 

![pb-teampass-3](https://user-images.githubusercontent.com/14218330/27679722-cdc5f72a-5cb9-11e7-8b01-722f7455e5dd.PNG)

Thanks for your help.

**Comment by nilsteampassnet** [comment]
What is the result of the query if you select the tab "Network"?

**Comment by Hellnino18** [comment]
![pb-teampass-4](https://user-images.githubusercontent.com/14218330/27684421-39c6a216-5cca-11e7-9847-60f2ee3a3bd0.PNG)

**Comment by nilsteampassnet** [comment]
click on the upgrade_ajax.php and select "answer"
copy here the result

**Comment by Hellnino18** [comment]
I am sorry, I don't undestand why, this time settings.php and tp.config.php wasn't copied right... Sorry for the waste of time. This time all the process of upgrade is fine, but I always have the same problem that I said in my first post. None of items is loaded and the display is broken (event after clear cache) and this error : 

![pb-teampass-5](https://user-images.githubusercontent.com/14218330/27684992-9d8ea468-5ccc-11e7-9e2d-22472084adb5.PNG)

**Comment by Hellnino18** [comment]
And for example, if I try to change a value on admin page : 

![pb-teampass-6](https://user-images.githubusercontent.com/14218330/27685609-4ae058d0-5ccf-11e7-904e-059c428708f5.PNG)

**Comment by nilsteampassnet** [comment]
PLease provide me an access with TeamViewer for example (tomorrow evening) ?

**Comment by Hellnino18** [comment]
Hi, I can give you an access with Teamviewer. How can you give you information ?

When are you available ? I can only be available until 5 pm (France). Thanks.

**Comment by Hellnino18** [comment]
Hi,

For information, I tried this morning the 2.1.27.5 you provide yesterday, and now the user part is working. No more problem, every item (user/password) is loaded.

But there is always a problem in admin part with the 'Uncaught SyntaxError : missing ) after argument'. Attachment in my previous post.

Thanks.

**Comment by Hellnino18** [comment]
Hi,

Tried Teampass 2.1.27.7, same result. Could you help me plz ?

**Comment by Hellnino18** [comment]
Hi @nilsteampassnet ,

I think it's related to #1810. In english no problem, I will try the solution proposed by @B0T0B

**Comment by nilsteampassnet** [comment]
Language files have been committed
