### ISSUE TITLE
Call to undefined function logEvents() on logout.php (2.1.27.5)

### ISSUE THREAD

**Issue by thnilsen** [nilsteampassnet/TeamPass#1803]
### Steps to reproduce
1. After logging on, select Logoff

### Expected behaviour
Login screen should reappear.

### Actual behaviour
Page errors in Apache - error 500. 

### Server configuration
**Operating system**:
Centos7

**Web server:**
Apache 2.4

**Database:**
MySQL 
**PHP version:**
5.6.x

**Teampass version:** 
2.1.27.5

**Updated from an older Teampass or fresh install:**
Upgrade from 2.1.27

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
[Mon Jul 03 14:00:28.342451 2017] [:error] [pid 60604] [client 10.0.0.235:53288] PHP Fatal error:  Call to undefined function logEvents() in /var/www/html/teampass/logout.php on line 56, referer: https://srv-web01/teampass/index.php?page=items
[Mon Jul 03 14:00:34.076569 2017] [:error] [pid 19844] [client 10.0.0.235:53290] PHP Fatal error:  Call to undefined function logEvents() in /var/www/html/teampass/logout.php on line 56
[Mon Jul 03 14:01:13.925336 2017] [:error] [pid 60604] [client 10.0.0.186:35891] PHP Fatal error:  Call to undefined function logEvents() in /var/www/html/teampass/logout.php on line 56, referer: https://srv-web01/teampass/index.php?page=manage_users
[Mon Jul 03 14:03:03.840985 2017] [:error] [pid 20383] [client 10.0.0.235:53339] PHP Fatal error:  Call to undefined function logEvents() in /var/www/html/teampass/logout.php on line 56, referer: https://srv-web01/teampass/index.php?page=items

How to fix:
The logout.php script is missing: require_once 'sources/main.functions.php';
Once that is included the logEvent() function is available.

**Comment by nilsteampassnet** [comment]
This is strange as I don't have this error on my testing environment.

In this file, replacing
```
        logEvents('user_connection', 'disconnection', $user_id, @$_SESSION['login']);
```
by
```
        require_once 'sources/main.functions.php';
        logEvents('user_connection', 'disconnection', $user_id, @$_SESSION['login']);
```
solved the issue?

**Comment by thnilsen** [comment]
Yes, adding the required main.function.php include file prior to the logEvents() has fixed the issue.

```
        ),
        "id=%i",
        $user_id
    );
    //load main functions needed
    require_once 'sources/main.functions.php';

    //Log into DB the user's disconnection
    if (isset($_SESSION['settings']['log_connections']) && $_SESSION['settings']['log_connections'] == 1) {
        logEvents('user_connection', 'disconnection', $user_id, @$_SESSION['login']);
    }
```

**Comment by nilsteampassnet** [comment]
Thank you.
I will commit a change
