### ISSUE TITLE
access to password item denied

### ISSUE THREAD

**Issue by Adam-Perform** [nilsteampassnet/TeamPass#1804]
Hi I have upgrade teampass from 2.1.24 to 2.1.27 without any problem during upgrade process, but after when i login i get this error "access to password item denied" I see all username but no pass...

Server configuration

Operating system:
Centos6.5

Web server:
Apache 2.2.15-47

Database:
MySQL 5.6.20-68.0
PHP version:
5.5.22-1

Teampass version:
2.1.27

Updated from an older Teampass or fresh install:
Upgrade from 2.1.24

**Comment by nilsteampassnet** [comment]
Can you please restore to your 2.1.24 environment.

Then upgrade version by version. 
As a tip, I would suggest to test after each upgrade.
If everything is ok, then perform a dump and continue to next version.

Teampass supports incremental upgrade only since 2.1.26

**Comment by Adam-Perform** [comment]
i have 2.1.26.20 working fine... after update do 2.1.27.0 still this error...

**Comment by Adam-Perform** [comment]
any idea ?

**Comment by nilsteampassnet** [comment]
From 2.1.26.x installed, download and install latest package.

**Comment by Adam-Perform** [comment]
HI
Just tried from 2.1.26x to 2.1.27.7 still the same problem...

**Comment by nilsteampassnet** [comment]
Can you provide me an access to your teampass instance with teamviewer for example? 
Please contact me at nil@teampass.net

**Comment by Adam-Perform** [comment]
i send email to you thx

**Comment by Adam-Perform** [comment]
fixed thx

**Comment by srihas619** [comment]
Hi @Adam-Perform , i am having the same issue: can you please tell me how is it fixed?

**Comment by Ovski4** [comment]
Hi,
I am having the exact same issue too. Everything is fine with my coworkers, I'm the only one having this issue with my account

**Comment by srihas619** [comment]
hello @nilsteampassnet , can you help with in solving with the same error?

**Comment by nilsteampassnet** [comment]
Can you tell more about your issue?
You migrated "from-to" what versions?

**Comment by nilsteampassnet** [comment]
If you migrate from an older version than 2.1.27, then I suggest to migrate to 2.1.26 and only then to the latest in `development` branch.

**Comment by srihas619** [comment]
@nilsteampassnet the migration has been done and that "message" comes to certain colleagues only, Remaining have no issues; I am guessing its related to passwords in personal folders before migration. Migration took place from 2.1.23.4 to 2.1.26-final-3 (realease). The persons with that error can still access passwords but only when searched via "binocular" section but cannot load the folder structure view. Your suggestions are appreciated, thank you.

**Comment by nilsteampassnet** [comment]
Can you share your screen with me? Contact me at Nils@teampass.net

**Comment by tadela** [comment]
Hello, i was installed fresh 2.1.27 version and now i have problem : access to password item denied
Can you help me?

**Comment by cheechmarino** [comment]
Hi. Same issue on fresh install when trying to view created item in personal folder. Basically no problems with item creation in personal folder, but after creation item becomes unavailable for view, edit or delete operations. 
Debian 9.1.0
Apache/2.4.25
mysql Ver 15.1 Distrib 10.1.26-MariaDB
PHP 7.0+49
Teampass 2.1.27.9
Fresh install

**Comment by cheechmarino** [comment]
MySQL version - 5.5.5-10.1.26-MariaDB-0+deb9u1
PHP version - 7.0.19-1
Teampass version - 2.1.27.9
![passitemdenied](https://user-images.githubusercontent.com/24827950/32492935-ab9d1166-c3c4-11e7-8aab-aefc18820c03.PNG)

**Comment by cheechmarino** [comment]
Commit https://github.com/nilsteampassnet/TeamPass/commit/a7990cfb99ad3d1b8981221860b9910546895b17 works for me. Thanks.
