### ISSUE TITLE
LDAP configuration & Documentation

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#1805]
running 2.1.27
### Steps to reproduce
1. Enable users authentication through LDAP server set to yes 
2. Posix / OpenLDAP (RFC2407)   <--- not search based
3. has 2 LDAP account suffix fields 

difficult to understand how to set the user attribute

LDAP account suffix for your domain is listed twice in the settings the popup help is not helpful 
lets say  the following is how I have configured teampass I still lack the component that Identifies the user
eg cn=user,ou=CMS,ou=ADM,o=company
or cn=%username,ou=CMS,ou=ADM,o=company

here is my configuration and test results keep in mind I didnt know howto set that cn=%someuser

LDAP configuration: Yes 
LDAP server type: Posxix / OpenLDAP(RFC2307)
LDAP account suffix for your domain: ou=CMS,ou=ADM,o=company
LDAP base DN for your domain: o=company
LDAP account suffix for your domain: ou=CMS,ou=ADM,o=company
LDAP domain controller(s) : server.ldap.com
LDAP port  : 636
Use LDAP through SSL (LDAPS) : yes
Use LDAP through TLS 	: no
Teampass local users only  : no

	
Test current configuration
Username: VALIDUSER
Username password: VALIDPASSWORD	

Get all ldap params:
- base_dn : o=company
- account_suffix : ou=CMS,ou=ADM,o=company
- domain_controllers : server.ldap.com
- port : 636
- use_ssl : 1
- use_tls : 0
*********
Create new adldap object : Success
After authenticate : Can't contact LDAP server
ldap status : Not possible to get connected with this user

### Actual behaviour
not working

### Server configuration
**Operating system**: 
ubuntu 16.04

**Web server:** 
apache

**Database:** 
mysql

**PHP version:** 
7.0.18-0ubuntu0.16.04.1 

**Teampass version:**  
2.1.27

**Updated from an older Teampass or fresh install:**
Fresh

**Comment by burnbabyburn** [comment]
remove LDAPS and it worked for me in 2.1.27
in 2.1.23 LDAPS is working with the exact same config!

**Comment by nilsteampassnet** [comment]
The LDAP has been updated.
Perhaps a change in the configuration needs to be set to enable LDAPS?
Are the certificates installed on the server?

**Comment by burnbabyburn** [comment]
@twotwenty did you verify a ldapsearch is working?
Look at adldap.php he used here. He commented this in the ldaps part: http://adldap.sourceforge.net/wiki/doku.php?id=ldap_over_ssl
Does Apache know the path to your cert file? 

@nilsteampassnet 
in my case it's a missing cert/ssl config. i didn't see he was coming from a fresh install and assumed the same missconfiguration :) Thx for updating the ldap account suffix desciption for MSAD! Posix Users will me smart enough to translate it :) OR you also add the old desc.

**Comment by spgeblg** [comment]
For me it is not working in 2.1.27, I have tested on different machine with 2.1.26 and I am able to perform LDAP queries. For 2.1.27 I receive this error.

Create new adldap object : SuccessAfter authenticate : Invalid credentialsldap status : Not possible to get connected with this user
--

**Comment by nilsteampassnet** [comment]
@spgeblg, the library has evolved. Do you have the cert file correctly set?
