### ISSUE TITLE
403 Access Forbidden by CSRFProtector! with DUO login

### ISSUE THREAD

**Issue by shasemann** [nilsteampassnet/TeamPass#1807]
### Steps to reproduce
1. Log into Teampass with DUO user
2. 
3.

### Expected behaviour
Log in and send push to device.  Approve DUO request and have response log you in.

### Actual behaviour
Log in with DUO user, accept push.  DUO frame says successful and then receive 403 Access Forbidden by CSRFProtector! error.  DUO was not functioning for me on 2.1.26 so I upgraded to 2.1.27.5.  It would send me a push and then redirect back to the log on page.  Local accounts are still able to log on successfully.

### Server configuration
**Operating system**:
Ubuntu 16.04.2
**Web server:**
Apache/2.4.18
**Database:**
MySQL 5.7.18-0
**PHP version:**
7.0.18-0
**Teampass version:** 
2.1.27.5
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26.-final-3
### Client configuration
**Browser:**
Chrome and Firefox
**Operating system:**
Windows 10
#### Web server error log
```
[Thu Jul 06 08:57:53.192939 2017] [:error] [pid 1351] [client 10.10.100.142:54569] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185
[Thu Jul 06 08:57:55.624347 2017] [:error] [pid 1351] [client 10.10.100.142:54569] PHP Notice:  Undefined index: agses_authentication_enabled in /var/www/html/sources/main.functions.php on line 1104, referer: http://teampass/index.php?page=manage_main
[Thu Jul 06 08:57:55.624397 2017] [:error] [pid 1351] [client 10.10.100.142:54569] PHP Notice:  Undefined index: item_extra_fields in /var/www/html/sources/main.functions.php on line 1108, referer: http://teampass/index.php?page=manage_main
[Thu Jul 06 08:59:28.284409 2017] [:error] [pid 1515] [client 10.10.100.142:54611] PHP Fatal error:  Uncaught Error: Call to undefined function logEvents() in /var/www/html/logout.php:56\nStack trace:\n#0 {main}\n  thrown in /var/www/html/logout.php on line 56, referer: http://teampass/index.php?page=manage_settings
[Thu Jul 06 08:59:30.762251 2017] [:error] [pid 1351] [client 10.10.100.142:54616] PHP Fatal error:  Uncaught Error: Call to undefined function logEvents() in /var/www/html/logout.php:56\nStack trace:\n#0 {main}\n  thrown in /var/www/html/logout.php on line 56
[Thu Jul 06 08:59:54.158976 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/
[Thu Jul 06 08:59:54.449139 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:54.668637 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:54.863294 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:55.050488 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:55.241025 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.001229 2017] [:error] [pid 1351] [client 10.10.100.142:54627] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.173658 2017] [:error] [pid 1352] [client 10.10.100.142:54628] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.306439 2017] [:error] [pid 1353] [client 10.10.100.142:54629] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.446404 2017] [:error] [pid 1353] [client 10.10.100.142:54629] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.593236 2017] [:error] [pid 1353] [client 10.10.100.142:54629] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 08:59:57.739704 2017] [:error] [pid 1353] [client 10.10.100.142:54629] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185, referer: http://teampass/index.php
[Thu Jul 06 09:11:00.083855 2017] [:error] [pid 1354] [client 10.10.100.142:54893] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185
[Thu Jul 06 09:23:53.075314 2017] [:error] [pid 1352] [client 10.10.100.142:55409] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185
[Thu Jul 06 09:39:40.262272 2017] [:error] [pid 1354] [client 10.10.100.142:55906] PHP Notice:  Undefined index: login in /var/www/html/sources/core.php on line 185
[Thu Jul 06 09:39:43.584504 2017] [:error] [pid 1354] [client 10.10.100.142:55906] PHP Notice:  Undefined index: agses_authentication_enabled in /var/www/html/sources/main.functions.php on line 1104, referer: http://teampass/index.php?page=manage_main
[Thu Jul 06 09:39:43.584563 2017] [:error] [pid 1354] [client 10.10.100.142:55906] PHP Notice:  Undefined index: item_extra_fields in /var/www/html/sources/main.functions.php on line 1108, referer: http://teampass/index.php?page=manage_main

```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Retested on my test server and I could get it work.
So I believe there is a configuration issue.
Can you send me the file tp.config.php?
What type of account is the one for which DUO fails?
I you disable DUO for this user, can you get connected?

Regarding the error, I see agses_authentication_enabled is not known but you are using DUO which sounds strange.

Did you clean the cache?

**Comment by shasemann** [comment]
I can, do you want me to email it?

It is a LDAP user, if I try with a non-DUO user is brings up the DUO window for a second and then goes to the  403 Access Forbidden by CSRFProtector! error page.  

I did clear browser cache and tried a few different browsers.

**Comment by nilsteampassnet** [comment]
yes please send it to nils@teampass.net

What if you try with a "non ldap user" and duo enabled?

**Comment by shasemann** [comment]
Email sent.  

The admin account logs in just fine and never shows the DUO screen.

**Comment by nilsteampassnet** [comment]
Can you create a local user to Teampass and associate it also to a DUO account?

I want to check if this error is related to LDAP

**Comment by shasemann** [comment]
My DUO admin is out right now.  Might have to test that tomorrow.

**Comment by shasemann** [comment]
Ok, I got a non-LDAP user into DUO and it produced the same results.

**Comment by nilsteampassnet** [comment]
Can you please edit the file
`includes\libraries\csrfp\libs\csrfp.config.php` and replace
```
    "verifyGetFor" => array("*page=items&type=duo_check*",
"*upload.attachments.php*", "*upload.files.php*")
```
by
```
    "verifyGetFor" => array("*type=duo_check*", "*upload.attachments.php*",
"*upload.files.php*")
```

**Comment by nilsteampassnet** [comment]
Can you please edit the file
`includes\libraries\csrfp\libs\csrfp.config.php` and replace
```
    "verifyGetFor" => array("*page=items&type=duo_check*", "*upload.attachments.php*", "*upload.files.php*")
```
by
```
    "verifyGetFor" => array("*type=duo_check*", "*upload.attachments.php*", "*upload.files.php*")
```

**Comment by shasemann** [comment]
That fixed the 403 Access Forbidden by CSRFProtector! error but now it is doing the same as it did for me on 2.1.26.  DUO authenticates just fine and then reloads the log in page.  Behaves the same with non-LDAP users as well.

**Comment by shasemann** [comment]
Just saw that in the logs for failed logins, it's reporting "user_password_not_correct" even though it is?

**Comment by nilsteampassnet** [comment]
Can you please enable debug for ldap?

Change `$debugLdap = 0;` to `$debugLdap = 1;` in file `sources/identify.php`.
Try to login
Send me the file `files/ldap.debug.txt`

**Comment by zilikodev** [comment]
@nilsteampassnet Just want to confirm that on our installation your fix to replace  "*page=items&type=duo_check*" for "*type=duo_check*" worked as intended and we can now use DUO and LDAP.

I'd suggest you include this in future versions.

Thanks!

**Comment by nilsteampassnet** [comment]
Thanks for the feedback. 

The fix has been committed

**Comment by charmeen** [comment]
i am using opendocman and i hosted it on our localserver, thing is when i try to login from another system it gives me 403 access forbidden by csrfprotector

**Comment by charmeen** [comment]
please help me

**Comment by charmeen** [comment]
this system i'm trying to login is connected to the local server, when i open the link, it takes me to the login page but when i try to login it gives this error 403 access forbidden by csrfprotector

**Comment by nilsteampassnet** [comment]
Please give details and explain the context, I don't have a crystal ball to divine your context and environment.

**Comment by Henrychuks25** [comment]
"jsUrl" => $GLOBALS['CONFIG']['base_url'] . "/vendor/owasp/csrf-protector-php/js/csrfprotector.js",

this is not working on my windows computer

**Comment by nilsteampassnet** [comment]
Sorry you are not in the correct git project.
Here it is the support for Teampass.
