### ISSUE TITLE
Settings page unsusable with French Language

### ISSUE THREAD

**Issue by B0T0B** [nilsteampassnet/TeamPass#1810]
### Steps to reproduce
1. Login
2. Go to Settings
3. Select French on Default user interface language
4. Logout
5. Login
6. Go to Settings

### Expected behaviour
Well formated page with tabs

### Actual behaviour
Wrong formated page with no tabs, can't change settings, missing some css

### Server configuration
**Operating system:** Debian 8.8 Fresh install

**Web server:** Apache2 v2.4.10

**Database:** Mariadb-server v10.0

**PHP version:** 5.6.30

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox 54.0.1 (64 bits) / IE 11.0.9600

**Operating system:** Windows 7

#### Firebug log 
SyntaxError: missing ) after argument list : index.php:3132:197

To fix this : [settingspage.diff.txt](https://github.com/nilsteampassnet/TeamPass/files/1133506/settingspage.diff.txt)

**Comment by nilsteampassnet** [comment]
Language files have been committed.
