### ISSUE TITLE
Can't add item

### ISSUE THREAD

**Issue by roger-link** [nilsteampassnet/TeamPass#1811]
### Steps to reproduce
1. Log in with user.
2.  Select folder and click "Add Item".
3. Fill out fields and save.
4. error pop up:

 _**Access to password item denied!
Author: API
Restricted to:**_ 

**_Request access to modify_**

### Expected behaviour
New password item should be saved in a folder.

### Actual behaviour
Item is not saved. Error pop up.

### Server configuration
**Operating system**:  
ubuntu:14.04

**Web server:** 
apache

**Database:** 
mysql

**PHP version:** 
5.5.0

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
chrome Version 59.0.3071.115 (Official Build) (64-bit)
**Operating system:**
osx el capitan

#### Web server error log
```
Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`tags`,`url`,`id_tree`,`perso`,`restricted_to`,`login`,`folder`,`author`,`timestamp`) VALUES (NULL, NULL, NULL, 'None', '0', NULL, '0', 'None', '', '', '2', NULL)<br />Error: Column 'id' cannot be null<br />@ /sources/items.queries.php
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```
### Screenshots

<img width="869" alt="screen shot 2017-07-11 at 8 30 10 am" src="https://user-images.githubusercontent.com/1907149/28070736-971809bc-6613-11e7-87bd-1efb6ac10b13.png">

**Comment by nilsteampassnet** [comment]
What package did you install?
You must have other error because the query is full of null values.

**Comment by nilsteampassnet** [comment]
No feedback since 15 days.

Please reopen if needed.
