### ISSUE TITLE
Problems with encoding in description

### ISSUE THREAD

**Issue by free-14** [nilsteampassnet/TeamPass#1813]
### Steps to reproduce
1. Update 2.1.27.3 to 2.1.27.7
2.
3.
### Expected behaviour
After updating 27.3 to 27.7, question marks appeared in the items description instead of Russian text. ONLY IN DESCRIPTION.

![5](https://user-images.githubusercontent.com/28634449/28130030-42ae788a-673e-11e7-9bec-c67457198fb3.jpg)

### Server configuration
**Operating system: Debian 7u11**

**Web server: Apache 2.2.22** 

**Database: Mysql 5.6.35**

**PHP version: PHP 5.6.30**

**Teampass version: 2.1.27.7** 

**Updated from an older Teampass or fresh install: 2.1.27.3**

### Client configuration
**Browser: Opera**

**Operating system: Win10**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Nothing was changed on encoding on 27.x versions.

Perhaps an issue in cache. Did you try to clear cache?

**Comment by free-14** [comment]
Yes, I cleared the cache. It is very strange that only in the descriptions the Russian text has changed.

**Comment by free-14** [comment]
I understand this problem is not solved? Need to make a return to 27.3?

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nilsteampassnet** [comment]
it is very complicated to evaluate as I cannot reproduce.
Even more knowing the fact that no change has been done on encoding and source code regarding creating, updating and displaying items.

Are you sure that no changes occurred on your server?

You can tr to revert on your "test" environment and check if you still have or not the issue.

**Comment by free-14** [comment]
I understand you ... I'll try to update on the test server from 27.3 to 27.7 I'll write as there will be information.

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by free-14** [comment]
Tell me, do you have a full description of the migration to another server?

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by free-14** [comment]
I've tested on another server. And he found a regularity. 1. I went into the description of the task changed the text, instead of (?????) I wrote a Russian text. 2. And did /upgrade.php and the text again became (?????).

**Comment by nilsteampassnet** [comment]
This is really strange.

I can't understand why. I need to perform deep code review to check this.
Can you check if the charset of tables in mysql changes after update?

**Comment by free-14** [comment]
The encoding does not change in mysql. I understand that this happens when the update_db_original.php script is run during the update. And in mysql immediately the text becomes (???)

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nilsteampassnet** [comment]
Thank you for identifying the file in cause.

But what is strange is that this file I didn't changed since a long time.
But perhaps it contains a bug that is now revealed by settings on the server.
I need to make it more robust.

**Comment by nilsteampassnet** [comment]
Is the description field impacted in `cache` table or in `items`?

**Comment by nilsteampassnet** [comment]
What you can also do is to re-run the update and removing this file to be executed.
Just to test if this file is the root cause.

To do so, open file `./install/upgrade_scripts_manager.php` and replace
```
    array('upgrade_run_db_original.php', ""),
```
by
```
    //array('upgrade_run_db_original.php', ""),
```

**Comment by free-14** [comment]
![cache](https://user-images.githubusercontent.com/28634449/28635013-beef1a0e-7241-11e7-8ee8-5b3f1b0c1ec6.jpg)
![items](https://user-images.githubusercontent.com/28634449/28635012-bee65d10-7241-11e7-8838-09624ae42dae.jpg)

**Comment by free-14** [comment]
And in cache and in items it changes.

**Comment by nilsteampassnet** [comment]
Indeed this is really unreadable.

Please do the test I propose in my previous message.

**Comment by free-14** [comment]
Checked without it there is no change. It's all right.

**Comment by free-14** [comment]
Sorry there are no changes to the items. But in the cache is.

**Comment by free-14** [comment]
Have not you found a solution yet? And another question is whether I can get back (question marks) Russian

**Comment by Hellbartonio** [comment]
I have same issue while upgrading from 2.1.23.0 to any other version (even 2.1.23.3). Cyrillic descriptions become unreadable after upgrade.

**Comment by free-14** [comment]
I understand this issue will not be resolved. type (sanctions) ... this also happens in offline mode. I solved this problem so simply changed the English text. But I could not wait while they helped me. (((

**Comment by Hellbartonio** [comment]
In my case this issue was solved by adding parameters in /etc/my.cnf file before upgrade:
[mysqld]
character-set-server = utf8
collation-server = utf8_unicode_ci
init_connect=‘SET collation_connection = utf8_unicode_ci’
[client]
default-character-set = utf8

**Comment by free-14** [comment]
Hellbartonio : In my case this issue was solved by adding parameters in /etc/my.cnf
Can you mean /etc/mysql/my.cnf?
