### ISSUE TITLE
Bug : passwords with <> marks not shown correctly

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#1814]
Hi, 

We have the version 2.1.27, and our bug report is simple,

though the find pane, we don't see correct password.

This password has < > marks and that's why we can't see all the password.

### Steps to reproduce
1. login and go to find page
2. chose a password with < >
3. the password is incorrect cause the marks<> are interpreted incorrectly

### Expected behaviour
should see the correct password

### Actual behaviour
the part of the password between marks disappears

### Server configuration
**Operating system**:
linux 7

**Web server:**
apache

**Database:**
mariadb (latest)

**PHP version:**
7.0,20
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
updated
### Client configuration
**Browser:**
mozila
**Operating system:**
windows 10
#### Web server error log
``` not needed
Insert your webserver log here
``` not needed

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
``` not needed
Insert the Firebug log here
``` not needed
![bug_ss](https://user-images.githubusercontent.com/1770475/28160984-c264e610-67b9-11e7-8311-f015c8e74d7f.jpg)

sent this screenshot so you can see the whole password in the right, and what is seen in the actual password in teampass

Ty,
Best Regards,
André Gomes

**Comment by nilsteampassnet** [comment]
I could not reproduce. 
Can you give exact procedure to get this?

**Comment by asgomes** [comment]
I can give you what we have, here are the screenshots.

we have a password like this (we can check it correctly in the tree folder view) :
nHo:'U3<M<_>p5L)ublBX>=$

in the "find" view it display :
nHo:'U3p5L)ublBX>=$

so in the "find" view it ommits :
<M<_>p5L)

I've upgraded our DEV environment and we still have this problem (2.1.27.7).

![capture1](https://user-images.githubusercontent.com/1770475/28360769-5aa33d06-6c6e-11e7-9765-05e26d5e3e46.JPG)
![capture2](https://user-images.githubusercontent.com/1770475/28360771-5e61c9ee-6c6e-11e7-9060-2913fded16e4.JPG)

**Comment by nilsteampassnet** [comment]
Thank you for the details.
I could reproduce, but still not fixed.

**Comment by ewheelerinc** [comment]
Nils,

What do you think about using htmlentities when displaying user-generated content?

https://www.php.net/manual/en/function.htmlentities.php
