### ISSUE TITLE
Delete item when  Personal Saltkey is not known

### ISSUE THREAD

**Issue by meeck** [nilsteampassnet/TeamPass#1815]
Hi,

When I lost my saltkey I can't select item for delete. Teampass always quest for saltkey. When I click 'Cancel' Item is not selected and can't delete them.

### Expected behaviour
Select item without open.

### Actual behaviour
Item is not selected.

### Server configuration
**Operating system**:
debian 8
**Web server:**
apache2
**Database:**
mysql 5.5
**PHP version:**
5.6
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration
**Browser:**
firefox latest
**Operating system:**
ubuntu 16.04
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Can you describe all the steps you do so that I can reproduce?
