### ISSUE TITLE
Upgrade from 2.1.9(!)->2.1.27

### ISSUE THREAD

**Issue by floyd871** [nilsteampassnet/TeamPass#1817]
Where do i find Versions prior to 2.1.20??
I need them from 2.1.9 ongoing...to do the upgrade process step by step.

Regards,
Michael

**Comment by nilsteampassnet** [comment]
I have found some old releases.
They are available for download [here](https://github.com/nilsteampassnet/nilsteampassnet.github.io/tree/master/old_releases).

For more recent, you will found in [Releases page](https://github.com/nilsteampassnet/TeamPass/releases)

**Comment by floyd871** [comment]
Thank you, that helps
