### ISSUE TITLE
Cannot view the contents of any folders

### ISSUE THREAD

**Issue by mattmole** [nilsteampassnet/TeamPass#1818]
### Steps to reproduce
1. Log in to team pass
2. Click to view contents of a folder
3. Red cog icon spins forever and passwords do not show. When this happens, the browser tab can only be closed using the task manager in chrome. This also occurs in other 

### Expected behaviour
I would expect to see the list of passwords

### Actual behaviour
Reading folder... shows and red cog icon spins forever and passwords do not show. When this happens, the browser tab can only be closed using the task manager in chrome. This also occurs in firefox and internet explorer

### Server configuration
**Operating system**: Ubuntu 14.04.5

**Web server:** Apache 2.4.7

**Database:** MySQL 5.5

**PHP version:** 5.5.9

**Teampass version:** 2.1.26

**Updated from an older Teampass or fresh install:** Updated from an older version

### Client configuration
**Browser:** Google Chrome / Firefox / Internet explorer

**Operating system:** Windows 7

#### Web server error log
```
Nothing obvious shows in the error.log file
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by mattmole** [comment]
Dev Tools suggest that the issue could be here: items.queries.php

**Comment by nilsteampassnet** [comment]
Can you please provide the log errors?

**Comment by mattmole** [comment]
[Sun Jul 16 06:55:17.181125 2017] [ssl:warn] [pid 22079] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Sun Jul 16 06:55:17.181440 2017] [mpm_prefork:notice] [pid 22079] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Jul 16 06:55:17.181451 2017] [core:notice] [pid 22079] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 17 06:31:21.152497 2017] [mpm_prefork:notice] [pid 22079] AH00171: Graceful restart requested, doing restart
[Mon Jul 17 06:31:22.286725 2017] [ssl:warn] [pid 22079] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Mon Jul 17 06:31:22.287002 2017] [mpm_prefork:notice] [pid 22079] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Jul 17 06:31:22.287016 2017] [core:notice] [pid 22079] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 18 08:55:51.472322 2017] [autoindex:error] [pid 26596] [client 10.241.12.11:59543] AH01276: Cannot serve directory /var/www_ssl/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Tue Jul 18 20:50:06.452127 2017] [mpm_prefork:notice] [pid 22079] AH00169: caught SIGTERM, shutting down
[Tue Jul 18 20:55:23.606884 2017] [ssl:warn] [pid 28387] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 20:55:23.658765 2017] [ssl:warn] [pid 28388] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 20:55:23.661950 2017] [mpm_prefork:notice] [pid 28388] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jul 18 20:55:23.661986 2017] [core:notice] [pid 28388] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 18 20:55:36.256298 2017] [:error] [pid 28392] [client 10.241.12.11:8684] PHP Warning:  require_once(/var/www_ssl/teampass/includes/language/english.php): failed to open stream: No such file or directory in /var/www_ssl/teampassCOPY/index.php on line 110
[Tue Jul 18 20:55:36.256341 2017] [:error] [pid 28392] [client 10.241.12.11:8684] PHP Fatal error:  require_once(): Failed opening required '/var/www_ssl/teampass/includes/language/english.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www_ssl/teampassCOPY/index.php on line 110
[Tue Jul 18 20:55:40.096176 2017] [:error] [pid 28394] [client 10.241.12.11:8690] PHP Warning:  require_once(/var/www_ssl/teampass/includes/config/settings.php): failed to open stream: No such file or directory in /var/www_ssl/teampassCOPY/index.php on line 44
[Tue Jul 18 20:55:40.096220 2017] [:error] [pid 28394] [client 10.241.12.11:8690] PHP Fatal error:  require_once(): Failed opening required '/var/www_ssl/teampass/includes/config/settings.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www_ssl/teampassCOPY/index.php on line 44
[Tue Jul 18 20:57:02.455130 2017] [mpm_prefork:notice] [pid 28388] AH00169: caught SIGTERM, shutting down
[Tue Jul 18 20:57:03.500918 2017] [ssl:warn] [pid 28461] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 20:57:03.535023 2017] [ssl:warn] [pid 28462] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 20:57:03.537655 2017] [mpm_prefork:notice] [pid 28462] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jul 18 20:57:03.537686 2017] [core:notice] [pid 28462] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 18 21:16:03.797410 2017] [mpm_prefork:notice] [pid 28462] AH00169: caught SIGTERM, shutting down
[Tue Jul 18 21:16:04.860414 2017] [ssl:warn] [pid 28688] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:16:06.287008 2017] [ssl:warn] [pid 28689] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:16:06.289494 2017] [mpm_prefork:notice] [pid 28689] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jul 18 21:16:06.289520 2017] [core:notice] [pid 28689] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 18 21:21:08.836525 2017] [mpm_prefork:notice] [pid 28689] AH00169: caught SIGTERM, shutting down
[Tue Jul 18 21:24:22.283358 2017] [ssl:warn] [pid 28917] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:24:22.329034 2017] [ssl:warn] [pid 28918] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:24:22.332022 2017] [mpm_prefork:notice] [pid 28918] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jul 18 21:24:22.332059 2017] [core:notice] [pid 28918] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jul 18 21:28:26.466501 2017] [mpm_prefork:notice] [pid 28918] AH00169: caught SIGTERM, shutting down
[Tue Jul 18 21:28:27.533669 2017] [ssl:warn] [pid 28996] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:28:27.570078 2017] [ssl:warn] [pid 28997] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Tue Jul 18 21:28:27.572627 2017] [mpm_prefork:notice] [pid 28997] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jul 18 21:28:27.572657 2017] [core:notice] [pid 28997] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jul 23 06:43:10.364725 2017] [mpm_prefork:notice] [pid 28997] AH00171: Graceful restart requested, doing restart
[Sun Jul 23 06:43:12.122170 2017] [ssl:warn] [pid 28997] AH01909: RSA certificate configured for srv-secureweb1.windsor.internal:443 does NOT include an ID which matches the server name
[Sun Jul 23 06:43:12.122437 2017] [mpm_prefork:notice] [pid 28997] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun Jul 23 06:43:12.122447 2017] [core:notice] [pid 28997] AH00094: Command line: '/usr/sbin/apache2'

**Comment by nilsteampassnet** [comment]
You seem to have issues with your server configuration especially regarding Certificates. 

Regarding teampass you seem to miss a lot of files. Did you run installation ?

**Comment by mattmole** [comment]
Hi again,

I've used teampass for years without problem, I can only think that I did
something wrong when I upgraded to the version I'm currently running.

I was considering setting up a new instance and then when it's working
copying over the config file from the old to the new.

Is that feasible?

**Comment by nilsteampassnet** [comment]
No it is not possible as the database structure may have changed since your version.

**Comment by nilsteampassnet** [comment]
I could help by getting connected to your server. Contact me by email.

**Comment by mattmole** [comment]
Ok, what do you suggest then please?

**Comment by nilsteampassnet** [comment]
In the log, I can see this
`Failed opening required '/var/www_ssl/teampass/includes/language/english.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www_ssl/teampassCOPY/index.php on line 110`

Seems really strange ... did you mix some path in the configuration?
open the DB table  `misc` and check for your paths

**Comment by mattmole** [comment]
Nils, thanks a lot for all of the hints. I've tried upgrading to 2.1.27.7 and this now seems to work nicely.

Thanks again!

**Comment by nilsteampassnet** [comment]
Good to read.

Closed.
