### ISSUE TITLE
group vertical scroll bar not work correctly

### ISSUE THREAD

**Issue by meeck** [nilsteampassnet/TeamPass#1820]
There is problem with vertical scroll bar of groups. When it is up its not possible to move them. When is down work as expected. The problem is with too wide div.item_list that covers the bar.

### Work around
In file items.css add new class 
.liste_items { margin-left: -35px }
find and change
#items_list { margin-left: 0px; width: 680px }
save the file & reload.

### Server configuration
**Operating system**:
Ubuntu / windows
**Web server:**
apache2.4
**Database:**
mysql 5.5
**PHP version:**
5.6
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
fresh
### Client configuration
**Browser:**
IE, firefox, chrome
**Operating system:**
Ubuntu / windows
### Logs
not aplicable

![zrzut ekranu z 2017-07-20 15-13-04](https://user-images.githubusercontent.com/8951111/28419359-00f4254e-6d5f-11e7-938d-694e5debbc2f.png)

**Comment by nilsteampassnet** [comment]
I never experimented this during usage and test.
But sure you investigation is right, but how could I not see this.

I will fix this.

Thank you

**Comment by nilsteampassnet** [comment]
Fix has been committed in Development branch
