### ISSUE TITLE
Login credentials do not correspond!

### ISSUE THREAD

**Issue by rafalin** [nilsteampassnet/TeamPass#1821]
![sem titulo](https://user-images.githubusercontent.com/30321447/28424098-25681d84-6d43-11e7-9d2f-0fe833e6f3dd.png)

I did the entire installation and configuration process, but when I typed the administrator password that was created it says that the login is not correct, I checked the database and it did not create the login in the "teampass_user" table.
What could be happening?

I downloaded the latest version of the site https://github.com/nilsteampassnet/TeamPass/archive/master.zip (2.1.27)

**Comment by baudettespiria** [comment]
I have the same problem on Debian stretch with php7

**Comment by rafalin** [comment]
I solved the problem, I undone the whole process and started again by placing chmod 777 permission on the teampass and saltkey folders, and after doing the installation I deleted the install folder (var / www / html / teampass), since it does not delete itself and hence Does not allow access giving error.

**Comment by nilsteampassnet** [comment]
Interesting.

Thank you for the feedback.
