### ISSUE TITLE
Can not create sub folder under user ..

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#1823]
![snimek obrazovky 2017-07-23 v 21 21 21](https://user-images.githubusercontent.com/18729181/28502174-e838a1c0-6fec-11e7-9947-09a27b527e57.png)

### Steps to reproduce
1. Create account 
2. Add role IT
3. Login in (user)

### Expected behaviour
User can create sub folder .. Account has permission to Folder.

### Actual behaviour
 You are not allowed to do that!

### Server configuration

**Teampass version:** 
TeamPass 2.1.27

**Updated from an older Teampass or fresh install:**
New installed

**Comment by nilsteampassnet** [comment]
What level of sub folder cannot be created?

**Comment by michaldejmek** [comment]
I created in root folder SW and user not can create new sub folder "Server" in folder SW.

ROOT
 - SW  
    - - user not can create new sub folder Server.

**Comment by nilsteampassnet** [comment]
I need to investigate because it seems something is wrong in the code.

**Comment by nilsteampassnet** [comment]
Did you enable the option 
![image](https://user-images.githubusercontent.com/1197546/28617970-de618104-7202-11e7-8cef-8aab9e50c498.png)

**Comment by michaldejmek** [comment]
Yes, I have it allowed.

**Comment by nilsteampassnet** [comment]
In file `folders.queries.php`, can you please replace
```
                    // rebuild tree
                    $tree = new Tree\NestedTree\NestedTree(prefix_table("nested_tree"), 'id', 'parent_id', 'title');
                    $tree->rebuild();

                    if ($isPersonal != 1
                        && isset($SETTINGS['subfolder_rights_as_parent'])
                        && $SETTINGS['subfolder_rights_as_parent'] == 1
                        && $_SESSION['is_admin'] !== 0
                        || ($isPersonal != 1 && $parentId === "0")
                    ) {
                        //Get user's rights
```
by
```
                    // rebuild tree
                    $tree = new Tree\NestedTree\NestedTree(prefix_table("nested_tree"), 'id', 'parent_id', 'title');
                    $tree->rebuild();

                    if ($isPersonal !== 1
                        && isset($SETTINGS['subfolder_rights_as_parent'])
                        && $SETTINGS['subfolder_rights_as_parent'] === 1
                        || ($isPersonal !== 1 && $parentId === "0")
                    ) {
                        //Get user's rights
```

**Comment by michaldejmek** [comment]
In version TeamPass 2.1.27  2009 - 2017 not this code :(

                    // rebuild tree
                    $tree = new Tree\NestedTree\NestedTree(prefix_table("nested_tree"), 'id', 'parent_id', 'title');
                    $tree->rebuild();

                    if (
                        $isPersonal != 1
                        && isset($_SESSION['settings']['subfolder_rights_as_parent'])
                        && $_SESSION['settings']['subfolder_rights_as_parent'] == 1
                        && $_SESSION['is_admin'] !== 0
                        || ($isPersonal != 1 && $parentId === "0")
                    ) {
                        //Get user's rights
                        identifyUserRights(
                            array_push($_SESSION['groupes_visibles'], $newId),
                            implode(";", $_SESSION['groupes_interdits']),
                            $_SESSION['is_admin'],
                            $_SESSION['fonction_id'],
                            true
                        );

                        //add access to this new folder
                        foreach (explode(';', $_SESSION['fonction_id']) as $role) {
                            if (!empty($role)) {
                                DB::insert(
                                    prefix_table("roles_values"),
                                    array(
                                        'role_id' => $role,
                                        'folder_id' => $newId,
                                        'type' => "W"
                                    )
                                );
                            }
                        }
                    }

**Comment by nilsteampassnet** [comment]
Correct

```
                    // rebuild tree
                    $tree = new Tree\NestedTree\NestedTree(prefix_table("nested_tree"), 'id', 'parent_id', 'title');
                    $tree->rebuild();

                    if ($isPersonal != 1
                        && isset($_SESSION['subfolder_rights_as_parent'])
                        && $_SESSION['subfolder_rights_as_parent'] == 1
                        && $_SESSION['is_admin'] !== 0
                        || ($isPersonal != 1 && $parentId === "0")
                    ) {
                        //Get user's rights
```
by
```
                    // rebuild tree
                    $tree = new Tree\NestedTree\NestedTree(prefix_table("nested_tree"), 'id', 'parent_id', 'title');
                    $tree->rebuild();

                    if ($isPersonal !== 1
                        && isset($_SESSION['subfolder_rights_as_parent'])
                        && $_SESSION['subfolder_rights_as_parent'] === 1
                        || ($isPersonal !== 1 && $parentId === "0")
                    ) {
                        //Get user's rights
```

**Comment by michaldejmek** [comment]
The probem is same. - You are not allowed to do that!

**Comment by nilsteampassnet** [comment]
Please provide your config file /includes/config/tp.config.php

**Comment by michaldejmek** [comment]
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1177808/tp.config.txt)

**Comment by nilsteampassnet** [comment]
I've committed a fix

**Comment by michaldejmek** [comment]
When will the new version be downloaded ..?

**Comment by nilsteampassnet** [comment]
In August ... I have  a lot to finish on this release to make the code more secure.

Or perhaps will I deliver a new "pre-release" quickly (2.1.27.8).

**Comment by michaldejmek** [comment]
Thank you very much.
