### ISSUE TITLE
Salt key field has already a character filled in.

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1830]
### Steps to reproduce
1. Login as user
2. Click on "Set the salt key"

### Expected behaviour
The salt key field should be clear

### Actual behaviour
There is already a character filled in
![grafik](https://user-images.githubusercontent.com/27355139/28620955-80fb8f34-720f-11e7-8ae3-38ab389f4892.png)

This appeared after upgrading from 2.1.27.5 to 2.1.27.7

### Server configuration
**Teampass version:** 
2.1.27.7

**Comment by nilsteampassnet** [comment]
A fix was committed recently for this in 'development' branch.

Thanks for reporting
