### ISSUE TITLE
No password by importing a Keepass.xml

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1831]
### Steps to reproduce
1. Create a Keepass.xml which contains at least one password
2. Import the .xml to Teampass 

### Expected behaviour
Password gets imported to Teampass and works perfectly.

### Actual behaviour
Sometimes there is no password imported, and sometimes it works without any problems.
(The same .xml file)

![grafik](https://user-images.githubusercontent.com/27355139/28622206-ff25c344-7213-11e7-8fd0-42fb7d3a14c0.png)

And sometimes there appears the little orange circle with the exclamation mark although the password is filled in.

### Server configuration

**Teampass version:** 
2.1.27.7

**Updated from an older Teampass or fresh install:**
Upgraded from 2.1.27.5

**Comment by nilsteampassnet** [comment]
Perhaps for the empty password can you identify if there is special characters in the original password?
THis could help to debug.

Note: Orange Information Mark informs that the Item doesn't have any password.

**Comment by benjamin2501** [comment]
The Password is: "ed36543937" this was just generated by Keepass for testing purposes.
Sometimes the import works and sometimes it doesn't work with the same file.

Concerning the Orange information mark: The "problem" is, that this mark appears although a password is filled in (the password was correctly imported from keepass.xml)

**Comment by benjamin2501** [comment]
@nilsteampassnet Any news concerning the import bug?

**Comment by nilsteampassnet** [comment]
I cannot reproduce this random behavior of the importation.
Perhaps is there a condition in the xml file that generates the special event.

Still trying...

**Comment by benjamin2501** [comment]
Update:
I used an other Keepass.xml created by a workmate. This importation worked fine ... there seems to be something wrong with my Keepass.xml

**Comment by nilsteampassnet** [comment]
Thank you for feedback.
