### ISSUE TITLE
The admin / parameters UI is broken

### ISSUE THREAD

**Issue by richardthibault** [nilsteampassnet/TeamPass#1832]
### Steps to reproduce
I don't really know : I was trying to make LDAP work
I deactivatied the maintenance mode, logout and login again from admin account and I have now an unsusable admin UI : CSS are wrong and impossible to change values (please see screenshot)

I have reactivated the maintenance mode from the DB, but the admin UI is still unusable

### Expected behaviour
A working parameters UI

### Actual behaviour
No style in the UI and impossible to change anything

### Server configuration
**Operating system**: CentOS

**Web server:** Apache 2.4

**Database:** MySQL 5.6

**PHP version:** 5.6

**Teampass version:**  2.1.27

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Google chrome

**Operating system:** Windows 10

#### Web server error log
```
No error in the log
```
![admin ui broken](https://user-images.githubusercontent.com/4078050/28627601-9384ca54-7222-11e7-86ba-dfbc9117533c.png)

**Comment by richardthibault** [comment]
![admin ui broken](https://user-images.githubusercontent.com/4078050/28627496-49f3988e-7222-11e7-8531-e7c1d15d6dae.png)

**Comment by richardthibault** [comment]
OK, found it !
It's the french localization !
I came back to english from the DB, and it's ok now...

Don't use french translation !

**Comment by Hellnino18** [comment]
Hi,

Don't close this bug, if there is a problem with french translation, it need to be repaired. I will test to pass in english on my platform, because I have the same issue.

**Comment by richardthibault** [comment]
OK, I let this issue open :-)

**Comment by ArkaineHeinlein** [comment]
Thx i have the same at "No menu in webinterface #1827"

**Comment by nilsteampassnet** [comment]
THis is related to language strings.
Only English shall be used when the Release is in "pre-release" as it is currently the case with 2.1.27.
All strings will be updated once the release will be mature enough.
