### ISSUE TITLE
Opening a one time view page give a notice: A session had already been started....

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1833]
### Steps to reproduce
1. Select the "One time view link" and copy the link
2. Open the link on another pc
3. The One time view link page opens with the notice

### Expected behaviour
To see only the one time view page, without notice.

### Actual behaviour
It displays the requested page and an extra message: 
Notice: A session had already been started - ignoring session_start() in C:\wamp64\www\teampass\otv.php on line 16

1 | 0.0022 | 527456 | {main}(  ) | ...\index.php:0
2 | 0.0738 | 3376584 | include( 'C:\wamp64\www\teampass\otv.php' ) | ...\index.php:451
3 | 0.0739 | 3376584 | session_start (  ) | ...\otv.php:16

### Server configuration
**Operating system**: Windows server 2012 R2

**Web server:** Apache 2.4.23

**Database:**  MySQL 5.7.14

**PHP version:** 7.0.10

**Teampass version:** Latest, 2.1.27.7

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:**: Firefox 54.0.1 and Edge

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
A fix was committed recently for this in 'development' branch.

Thanks for reporting
