### ISSUE TITLE
Typo in sources/main.functions.php

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#1834]
Hi,

Could you change typo in file sources/main.functions.php plz for syslog action : 

line 1408, replace : 

send_syslog("The User ".$login." perform the acction off ".$label." to the user ".$field_1." - ".$type, "teampass", $_SESSION['settings']['syslog_host'], $_SESSION['settings']['syslog_po     rt']);

By : 

send_syslog("The User ".$login." perform the action of ".$label." to the user ".$field_1." - ".$type, "teampass", $_SESSION['settings']['syslog_host'], $_SESSION['settings']['syslog_po     rt']);

line 1409, replace : 

send_syslog("The User ".$login." perform the acction off ".$label." - ".$type, "teampass", $_SESSION['settings']['syslog_host'], $_SESSION['settings']['syslog_port']);

By : 

send_syslog("The User ".$login." perform the action of ".$label." - ".$type, "teampass", $_SESSION['settings']['syslog_host'], $_SESSION['settings']['syslog_port']);

Thanks.

**Comment by nilsteampassnet** [comment]
Thank you
