### ISSUE TITLE
Opening two tabs simultaneously

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#1835]
### Steps to reproduce
1. Open one window, or tab, and access TeamPass web platform;
2. Open another window, or tab, and again access TeamPass web platform, while maintaining the previous one open.

### Expected behaviour
I would expect to be able to use TeamPass web platform on both windows, or tabs, without any problem.

### Actual behaviour
Opening two different tabs, or windows, causes the session to be closed on both and a new login is required.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** PHP 7.1.7

**Teampass version:** TeamPass 2.1.27.7

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Mozilla Firefox 52.2.0

**Operating system:** CentOS 7

**Comment by nilsteampassnet** [comment]
Sorry but this also will not work.
Only one tab can be used to guarantee the consistency of tokens, data and other security aspects expected by users in security environments.
So this cannot be changed.
