### ISSUE TITLE
Closing and reopening TeamPass tab

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#1836]
### Steps to reproduce
1. Open TeamPass web platform on a new window, or tab;
2. Close the tab;
3. Again, open TeamPass web platform on a new tab.

### Expected behaviour
I would expect that, by closing and reopening the tab, the session would still remain valid (as long as the time set for the session duration has not yet expired). 

### Actual behaviour
Closing and reopening the tab requires the user to perform the login authentication process again.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** PHP 7.1.7

**Teampass version:** TeamPass 2.1.27.7

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Mozilla Firefox 52.2.0

**Operating system:** CentOS 7

**Comment by nilsteampassnet** [comment]
Hello

No sorry, this is the correct way Teampass should work to provide maximum security.
If user closes the Teampass tab, then the session is killed or at least is not consistent anymore.
A clean authentification is then requested.
