### ISSUE TITLE
Invalid JSON Response

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#1837]
### Steps to reproduce
1. Create a new user without any folders associated with the account;
2. Login with that user;
3. Enter the "Search" menu.

### Actual behaviour
If a user has an empty tree-structure, an "Invalid JSON Response" message is presented when entering the "Search" menu.
![warning_teampass](https://user-images.githubusercontent.com/19646582/28666232-6d3030a4-72be-11e7-8221-0cb2c446af06.png)

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** PHP 7.1.7

**Teampass version:** TeamPass 2.1.27.7

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Mozilla Firefox 52.2.0

**Operating system:** CentOS 7

**Comment by nilsteampassnet** [comment]
I've committed a fix in `development` branch

Thank you
