### ISSUE TITLE
Custom fields not encrypted?

### ISSUE THREAD

**Issue by emroom** [nilsteampassnet/TeamPass#1838]
### Steps to reproduce
1. Install teampass on Ubuntu 16.04 (using PHP7).
2. Login as admin, under Settings goto "Custom Fields" tab, create category "Bank", with encrypted field "account number", link this category to a folder "Bank" that is linked to a user.
3. Login as a user that is linked to folder "Bank" and create an item.

### Expected behaviour
On the "More" tab of the "create item" popup, I would expect to see the field "account number" with a preview icon next to it (the "eye" icon that you see on password fields) and when I enter any content, I would expect to see "dot" characters (just like for password fields). Also, when saving such an item, and then selecting it, so the fields are shown at the bottom of the page, I would expect to see the account number field with hidden content instead of the actual typed content.

### Actual behaviour
Custom field content is not "hidden" behind "dot" characters, like a password field, and no "eye" icon is shown that you could click-and-hold to view the content.

![custom field not encrypted](https://user-images.githubusercontent.com/30502855/28679586-ee226364-72f3-11e7-9110-3cca189bd905.PNG)

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1180554/tp.config.php.txt)

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.7.19

**PHP version:**
PHP 7.0

**Teampass version:** 
2.1.27.7

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install.

### Client configuration
**Browser:**
Google Chrome v. 59.0.30, Firefox 54.0.1

**Operating system:**
MS-Windows 10 Professional

### Logs

No errors in mysql.log

#### Web server error log
```
No errors in apache error log. In other_vhost_access.log:
127.0.1.1:443 192.168.1.161 - - [27/Jul/2017:18:06:16 +0200] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 408 "https://hostname.mydomain.nl/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
The link does not work... However, I don't see any error in the javascript console.
```

**Comment by nilsteampassnet** [comment]
PLease leave your feature request in https://teampass.userecho.com/forums/1-feature-requests/
