### ISSUE TITLE
Automatic LDAP Integration

### ISSUE THREAD

**Issue by rafalin** [nilsteampassnet/TeamPass#1839]
There is some way to do the automatic integration of TeamPass with LDAP, that is, to search all users of AD and create the accounts alone.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
LDAP user is created in Teampass at first user login.
