### ISSUE TITLE
Unknown character in input field when entering personal salt key

### ISSUE THREAD

**Issue by Jurik81** [nilsteampassnet/TeamPass#1842]
### Steps to reproduce
1. Login 
2. Click on "Set the salt key"
3. See attachment
![enter your personal salt key](https://user-images.githubusercontent.com/5330316/28707852-3d544aac-737a-11e7-8337-b1fd06605c41.png)

### Expected behaviour
There should be an empty input field to set the salt key.

### Actual behaviour
There is always one character in the field, which you've to delete first.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
fresh install 

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Windows10, MacOSX
#### Web server error log
```
-
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
-
```

**Comment by free-14** [comment]
I have the same problem. Appeared after the update. Constantly have to delete and re-write. Even when you enter the password, the enter button does not work. You have to press the mouse. Please correct.

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nilsteampassnet** [comment]
This has been reported and fixed in `Development` Branch.

Thank you for reporting
