### ISSUE TITLE
"Item has no password" in personal folder

### ISSUE THREAD

**Issue by Jurik81** [nilsteampassnet/TeamPass#1844]
### Steps to reproduce
1. Login
2. Create new item in your private folder
3. Take a look into your private folder

### Expected behaviour
There should be two icons. One for instant copy username and one for instant copy password.

### Actual behaviour
It shows an exclamation mark with title "Item has no password". See attachment:
![thisitemhasnopassword](https://user-images.githubusercontent.com/5330316/28719767-614f18e8-73ab-11e7-86ad-3fe2ed5ae464.png)

### Server configuration
**Operating system**:
debian
**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.6
**Teampass version:** 
2.1.27
**Teampass configuration file:**

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1183199/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
fresh

### Client configuration
**Browser:**
Chrome
**Operating system:**
MacOSX
#### Web server error log
```
-
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
-
```

**Comment by free-14** [comment]
The main key .. psk you have a new one? Or the old one? If the new one it will not be able to decrypt the old one.

_Sent from my Xiaomi MI 4W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nilsteampassnet** [comment]
I have fixed something relating the bad display of this icon in the Personal Folders.
This is fixed in `Development` Branch.

Thank you for reporting
