### ISSUE TITLE
Custom Fields: Visibility when Empty, and Masking

### ISSUE THREAD

**Issue by wirerydr** [nilsteampassnet/TeamPass#1845]
This refers to **Feature Request 63** ([_Custom Fields - Visibility-when-Empty, and Masking_](https://teampass.userecho.com/topics/63-custom-fields-visibility-when-empty-and-masking/)), which I believe you implemented (thank you very much) in commit 3d4d6388348d141a03c5cf8aac481ac83864c83b on July 1st.

The feature request was made in two parts:  The first part (**_visibility when empty_**) looks good - I've tested it in various scenarios and custom fields become visible / non-visible depending on their contents.  Thank you very much.

The second part (**_masking_**) appears not to work at all.  Was this part of the feature request implemented, or am I just testing it incorrectly?  Incidentally, although not raised by me, Git Issue #1838 appears to describe a similar request, although with bit more detail.
```

**Comment by nilsteampassnet** [comment]
No you are right, I missed the "masking" part of FR.
I will add it.

Can you please use original UE ticket to comment. Opening too many tickets make it complicated for me to handle ;).

I'm closing this one
