### ISSUE TITLE
Clicking on "My Profile" causes hang then logout.

### ISSUE THREAD

**Issue by Tillco** [nilsteampassnet/TeamPass#1846]

**Comment by ImNtReal** [comment]
Tillco, did you solve this problem? I'm having what I believe to be the same issue.

**Comment by Tillco** [comment]
No, i have not yet. I was contacted by someone who said I should look into
my apache and SSL logs and see if there is something about my SSL
configuration that needs corrected. Linux is not my primary OS, though I do
work with several of them, and many things that heavy linux users take for
granted, are still a challenge for me.

Please let me know if you come up with a solution.

Thanks,

Jairus
