### ISSUE TITLE
With STS option enabled, external query calls fail

### ISSUE THREAD

**Issue by Tillco** [nilsteampassnet/TeamPass#1848]
### Steps to reproduce
1. Select a folder
2. Click the drop down menu
3. Select Export Items

### Expected behaviour
Should be able to export passwords in PDF or CSV

### Actual behaviour
A window opens with a infinite spinning gear that says "Please wait!". I've allowed several minutes of this, waiting for it to process a folder with only a few entries. You can click close, and you can continue on with normal use, but no option to download the CSV or PDF appears.

### Server configuration
**Operating system**: CentOS 7

**Web server: Apache

**Database: 5.5.52-MariaDB

**PHP version: 5.6.30

**Teampass version:** 

**Teampass configuration file:2.1.27

**Updated from an older Teampass or fresh install:
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1188426/tp.config.php.txt)

PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:IE and Chrome

**Operating system: Windows 7 and Windows 10

#### Web server error log
```

[ssl_error_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188431/ssl_error_log.txt)
[ssl_request_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188430/ssl_request_log.txt)
[ssl_access_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188432/ssl_access_log.txt)
[error_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188434/error_log.txt)
[access_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188433/access_log.txt)

```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by Tillco** [comment]
I used this for the initial setup "http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/"

I also enable SSL, using a godaddy signed certificate.

**Comment by nilsteampassnet** [comment]
The 2 issues you are opening seem to be linked.
Indeed in both cases, the dialogboxes are built with the content of the result of an ajax query.
You didn't provided the error log but I'm pretty sure there is a message "hacking attempt ...".

You should check your configuration and SSL setup.
Track the apache logs to identify the cause.
