### ISSUE TITLE
'//  Fixing items not being displayed ' section bug

### ISSUE THREAD

**Issue by jcoquery** [nilsteampassnet/TeamPass#1850]
--> 
### Steps to reproduce
1. Fresh Teampass install (docker)
2. create folder, role, users and new item
3. try to view items into a folder

### Expected behaviour
Displaying items

### Actual behaviour
Items are not showing (like on the screenshot in issue #415)
After comment the '//  Fixing items not being displayed ' section in items.load.php, items are displayed.

### Server configuration
**Operating system**:
Centos 7
**Web server:**
nginx
**Database:**
mysql 5.7
**PHP version:**

**Teampass version:** 
2.1.27
**Teampass configuration file:**

### Client configuration
**Browser:**
All

**Operating system:**
Windows

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Can you please indicate what part of the code you commented out?

**Comment by jcoquery** [comment]
Sorry, it's in "items.queries.php"
I commented the following part:
`            //  Fixing items not being displayed`
`            $html = iconv(`
`                'UTF-8',`
`                'UTF-8//IGNORE',`
`                mb_convert_encoding(`
`                    $html,`
`                    "UTF-8",`
`                    "UTF-8"`
`                )`
`            );`

**Comment by nilsteampassnet** [comment]
This is strange that by removing this your items become visible.
IT permits to remove invalid UTF-8 characters, unless you have only invalid UTF8 characters ...
What charset do you use?

**Comment by jcoquery** [comment]
I know this is strange ;)
How do I check my charset?

**Comment by noose** [comment]
> Notice: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed in /var/www/html/www/sources/items.queries.php on line 2508

**Comment by nilsteampassnet** [comment]
Thank you for this information.

I need to check what changed in iconv().

**Comment by noose** [comment]
@nilsteampassnet nothing has changed. You have no support for iconv in docker image. My pull request https://github.com/nilsteampassnet/TeamPass/pull/1858 fixes that.

**Comment by nilsteampassnet** [comment]
Great!

Thank you.

**Comment by jcoquery** [comment]
I have iconv support
`bash-4.3# php -i | grep -i "iconv support"
`
`iconv support => enabled
`
But I still have this issue

**Comment by nilsteampassnet** [comment]
Can you please give more details?
Screenshot? Teampass version? Docker? Attach tp.config.php file?

**Comment by jcoquery** [comment]
Hi,
There is the screenshot 
<img width="517" alt="tp" src="https://user-images.githubusercontent.com/30726879/29414999-cd9afc54-8361-11e7-8b83-9e7bf702bd2b.png">

The TP version is 2.1.27 runing from docker-composer.yml

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1231369/tp.config.php.txt)

Thanks

**Comment by jcoquery** [comment]
The issue is always present, is it possible to reopen this ticket?
