### ISSUE TITLE
Passwords deleted or disappear

### ISSUE THREAD

**Issue by testingO** [nilsteampassnet/TeamPass#1852]
### Steps to reproduce
1. Upgrade from 2.1.20 to 2.1.24
2. Upgrade from 2.1.20 to 2.1.25
3. Upgrade from 2.1.20 to 2.1.27

### Expected behaviour
Tell us what should happen

> all passwords available

### Actual behaviour
Tell us what happens instead

1. Version not available on Github
2. Personal passwords are deleted
3. All passwords are deleted

### Server configuration
**Operating system**:

debian 8

**Web server:**

apache2.4.10

**Database:**

mysql 5.5.57

**PHP version:**

5.6.30

**Teampass version:** 

2.1.20

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
You need to migrate version to version.
The versions of Teampass are available in Release page from 2.1.20

**Comment by testingO** [comment]
Hi
I don't see all the versions on GIT or on the home page?
Could you please post the URL  to all versions!

**Comment by testingO** [comment]
Hi
please, tell us how the right upgrade path is, from 2.1.20 with the available versions on Github?
