### ISSUE TITLE
Cannot add new folder - Wheel keeps spinning - Please Wait

### ISSUE THREAD

**Issue by Sailing74** [nilsteampassnet/TeamPass#1853]
I'm trying to add a new folder. Irrespective of whether I do this as a user, manager, or admin, and irrespective of the parent folder I choose, all I ever get is a spinning wheel and the message "Please wait" until I'm clicking on "abort" or the x in the upper right corner. There is no error in Apache's error log.

Please tell me what I could do to debug/correct this behavior.

**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.19

**PHP version:** PHP 7.0.18-0ubuntu0.16.04.1

**Teampass version:** 2.1.27 (github master as of today, same issue with 2.1.26)

**Teampass configuration file:** 

`<?php
    global $SETTINGS;
    $SETTINGS = array (
        'max_latest_items' => '10',
        'enable_favourites' => '1',
        'show_last_items' => '1',
        'enable_pf_feature' => '1',
        'log_connections' => '0',
        'log_accessed' => '1',
        'time_format' => 'H:i:s',
        'date_format' => 'd/m/Y',
        'duplicate_folder' => '0',
        'duplicate_item' => '1',
        'number_of_used_pw' => '3',
        'manager_edit' => '1',
        'cpassman_dir' => '/var/www/teampass',
        'cpassman_url' => 'http://www.domain.com/teampass',
        'favicon' => 'http://www.domain.com/teampass/favico.ico',
        'activate_expiration' => '0',
        'pw_life_duration' => '0',
        'maintenance_mode' => '0',
        'cpassman_version' => '2.1.27',
        'ldap_mode' => '0',
        'richtext' => '0',
        'allow_print' => '0',
        'show_description' => '1',
        'anyone_can_modify' => '0',
        'nb_bad_authentication' => '0',
        'utf8_enabled' => '1',
        'restricted_to' => '0',
        'restricted_to_roles' => '0',
        'custom_logo' => '',
        'custom_login_text' => '',
        'default_language' => 'english',
        'send_stats' => '0',
        'send_mail_on_user_login' => '0',
        'send_stats_time' => '1342850915',
        'ldap_ssl' => '0',
        'ldap_tls' => '0',
        'enable_kb' => '0',
        'copy_to_clipboard_small_icons' => '1',
        'enable_user_can_create_folders' => '1',
        'enable_send_email_on_user_login' => '1',
        'menu_type' => 'context',
        'nb_items_by_query' => 'auto',
        'enable_delete_after_consultation' => '0',
        'path_to_upload_folder' => '/var/www/teampass/upload',
        'url_to_upload_folder' => 'http://www.domain.com/teampass/upload',
        'enable_personal_saltkey_cookie' => '1',
        'personal_saltkey_cookie_duration' => '31',
        'path_to_files_folder' => '/var/www/teampass/files',
        'url_to_files_folder' => 'http://www.domain.com/teampass/files',
        'pwd_maximum_length' => '40',
        'email_smtp_server' => 'mail.comain.com',
        'email_smtp_auth' => '1',
        'email_auth_username' => 'username',
        'email_auth_pwd' => 'password',
        'email_post' => '25',
        'email_from' => 'teampass@domain.com',
        'email_from_name' => 'Teampass',
        '2factors_authentication' => '0',
        'delay_item_edition' => '0',
        'allow_import' => '0',
        'proxy_port' => '0',
        'ldap_elusers' => '0',
        'enable_email_notification_on_item_shown' => '0',
        'email_port' => '25',
        'insert_manual_entry_item_history' => '0',
        'anyone_can_modify_bydefault' => '0',
        'upload_maxfilesize' => '10mb',
        'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
        'upload_imagesext' => 'jpg,jpeg,gif,png',
        'upload_pkgext' => '7z,rar,tar,zip',
        'upload_otherext' => 'sql,xml,lic',
        'upload_imageresize_options' => '0',
        'upload_imageresize_width' => '800',
        'upload_imageresize_height' => '600',
        'upload_imageresize_quality' => '90',
        'enable_sts' => '0',
        'encryptClientServer' => '1',
        'tree_counters' => '0',
        'can_create_root_folder' => '1',
        'use_md5_password_as_salt' => '0',
        'get_tp_info' => '1',
        'ga_website_name' => '',
        'ldap_type' => 'windows',
        'ldap_suffix' => '0',
        'ldap_domain_dn' => '0',
        'ldap_domain_controler' => '0',
        'ldap_user_attribute' => '0',
        'api' => '0',
        'subfolder_rights_as_parent' => '0',
        'show_only_accessible_folders' => '1',
        'enable_suggestion' => '0',
        'item_duplicate_in_same_folder' => '0',
        'roles_allowed_to_print' => '1',
        'email_security' => 'none',
        'enable_email_notification_on_user_pw_change' => '1',
        'email_server_url' => '',
        'otv_expiration_period' => '7',
        'default_session_expiration_time' => '60',
        'duo' => '0',
        'item_extra_fields' => '0',
        'enable_attachment_encryption' => '1',
        'settings_offline_mode' => '0',
        'offline_key_level' => '0',
        'bck_script_filename' => 'bck_cpassman',
        'bck_script_path' => '/var/www/teampass/backups',
        'enable_server_password_change' => '0',
        'syslog_enable' => '0',
        'syslog_host' => 'localhost',
        'syslog_port' => '514',
        'ldap_object_class' => '0',
        'saltkey_ante_2127' => 'saltkey',
        'google_authentication' => '0'
    );`

**Updated from an older Teampass or fresh install:**
update from 2.1.26

### Client configuration
**Browser:** Firefox, Safari, Edge, all tested

**Operating system:** Linux, MacOS, Win10, all tested

#### Web server error log
Apache logs are empty

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
Sorry, the link above is not working for me. Again, happy to provide any additional information required.

**Comment by Sailing74** [comment]
FYI, I tried optimizing the database and removing orphaned items, but that didn't help.

**Comment by nilsteampassnet** [comment]
If you have the same with 2 versions, there is an error related to the server.

Please give us the errors from the server log.

**Comment by Sailing74** [comment]
Do you mean the apache error log with the server log? I'm really sorry, but the apache log is empty. I just tried adding a folder again - the wheel is still spinning. And the last entry in error.log is:

`[Tue Aug 08 07:36:34.490112 2017] [core:error] [pid 28842] (36)File name too long: [client 137.226.113.10:48448] AH00036: access to /YesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScann failed (filesystem path '/var/www/mailgate/YesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScanningForResearchPurposePleaseHaveALookAtTheUserAgentTHXYesThisIsAReallyLongRequestURLbutWeAreDoingItOnPurposeWeAreScann')`

(obviously something very different)

But access.log shows clearly that I was using teampass:

`192.168.1.3 - - [08/Aug/2017:10:16:53 +0200] "GET /teampass/ HTTP/1.1" 200 14790 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jeditable/jquery.jeditable.js HTTP/1.1" 200 2786 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/jquery-ui.theme.min.css HTTP/1.1" 200 3033 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/jquery-ui.min.css HTTP/1.1" 200 7951 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/jquery-ui.structure.min.css HTTP/1.1" 200 5416 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/nprogress/nprogress.css HTTP/1.1" 200 1043 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/tooltipster/js/jquery.tooltipster.min.js HTTP/1.1" 200 5387 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/simplePassMeter/simplePassMeter.js HTTP/1.1" 200 3246 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/nprogress/nprogress.js HTTP/1.1" 200 4112 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/tooltipster/css/tooltipster.css HTTP/1.1" 200 2185 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/functions.js HTTP/1.1" 200 3647 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 7576 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/libraries/Plupload/plupload.full.min.js HTTP/1.1" 200 37249 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/css/passman.css HTTP/1.1" 200 2938 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/jquery-ui.min.js HTTP/1.1" 200 65229 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/external/jquery/jquery.js HTTP/1.1" 200 82609 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_flat_55_eeeeee_40x100.png HTTP/1.1" 200 631 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/images/canevas/menu_top_bckg.png HTTP/1.1" 200 572 "https://www.domain.com/teampass/includes/css/passman.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_glass_60_eeeeee_1x400.png HTTP/1.1" 200 674 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_inset-soft_50_c9c9c9_1x100.png HTTP/1.1" 200 693 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/images/canevas/background_cell.jpg HTTP/1.1" 200 1359 "https://www.domain.com/teampass/includes/css/passman.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/images/canevas/logo_home.png HTTP/1.1" 200 17221 "https://www.domain.com/teampass/includes/css/passman.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:54 +0200] "GET /teampass/includes/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77667 "https://www.domain.com/teampass/includes/font-awesome/css/font-awesome.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:59 +0200] "POST /teampass/sources/identify.php HTTP/1.1" 200 703 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:16:59 +0200] "GET /teampass/index.php?page=items HTTP/1.1" 200 48508 "https://www.domain.com/teampass/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jstree/jquery.cookie.js HTTP/1.1" 200 2210 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/bgiframe/jquery.bgiframe.min.js HTTP/1.1" 200 1708 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/ckeditor/adapters/jquery.js HTTP/1.1" 200 1808 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/multiselect/jquery.multiselect.filter.css HTTP/1.1" 200 699 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/tinysort/jquery.tinysort.min.js HTTP/1.1" 200 1535 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jstree/jstree.min.js HTTP/1.1" 200 30245 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jstree/themes/default/style.css HTTP/1.1" 200 4556 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/multiselect/jquery.multiselect.min.js HTTP/1.1" 200 4083 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/multiselect/jquery.multiselect.filter.js HTTP/1.1" 200 2683 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/multiselect/jquery.multiselect.css HTTP/1.1" 200 1198 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/css/items.css HTTP/1.1" 200 1441 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/clipboard/clipboard.min.js HTTP/1.1" 200 3847 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/ckeditor/ckeditor.js HTTP/1.1" 200 111091 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/images/photo.jpg HTTP/1.1" 200 2102 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/images/canevas/fond_items_tree.png HTTP/1.1" 200 894 "https://www.domain.com/teampass/includes/css/items.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/images/canevas/tree_lock.png HTTP/1.1" 200 13893 "https://www.domain.com/teampass/includes/css/items.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/images/canevas/lock_open.png HTTP/1.1" 200 8566 "https://www.domain.com/teampass/includes/css/items.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-icons_999999_256x240.png HTTP/1.1" 200 7400 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jstree/themes/default/throbber.gif HTTP/1.1" 200 2133 "https://www.domain.com/teampass/includes/js/jstree/themes/default/style.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/sources/tree.php HTTP/1.1" 200 1222 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_glass_35_dddddd_1x400.png HTTP/1.1" 200 674 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_inset-hard_75_999999_1x100.png HTTP/1.1" 200 664 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_flat_55_c0402a_40x100.png HTTP/1.1" 200 617 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_glass_100_f8f8f8_1x400.png HTTP/1.1" 200 674 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 7802 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:00 +0200] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 3307 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:01 +0200] "GET /teampass/includes/images/canevas/fond_item_li.png HTTP/1.1" 200 571 "https://www.domain.com/teampass/includes/css/items.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:01 +0200] "POST /teampass/sources/items.queries.php HTTP/1.1" 200 1427 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:01 +0200] "GET /teampass/includes/js/jstree/themes/default/32px.png HTTP/1.1" 200 3534 "https://www.domain.com/teampass/includes/js/jstree/themes/default/style.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:04 +0200] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 423 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:04 +0200] "GET /teampass/index.php?page=manage_folders HTTP/1.1" 200 15577 "https://www.domain.com/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:05 +0200] "GET /teampass/sources/datatable/datatable.folders.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=-1&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1502180225013 HTTP/1.1" 200 2015 "https://www.domain.com/teampass/index.php?page=manage_folders" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:08 +0200] "POST /teampass/sources/main.queries.php HTTP/1.1" 200 423 "https://www.domain.com/teampass/index.php?page=manage_folders" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:10 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-icons_70b2e1_256x240.png HTTP/1.1" 200 4963 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:10 +0200] "GET /teampass/includes/js/jquery-ui/images/ui-bg_flat_0_eeeeee_40x100.png HTTP/1.1" 200 631 "https://www.domain.com/teampass/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
192.168.1.3 - - [08/Aug/2017:10:17:21 +0200] "POST /teampass/sources/folders.queries.php HTTP/1.1" 200 756 "https://www.domain.com/teampass/index.php?page=manage_folders" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
`

Could it be that the table for the folders in the database has somehow been corrupted causing this?

**Comment by Sailing74** [comment]
![grafik](https://user-images.githubusercontent.com/5119859/29064338-eacb2c58-7c28-11e7-87ed-6ebbc7477392.png)
I have pasted above the contents from teampass_nested_tree in case that gives you any clue as to what the issue might be. I could also try to test manually adding a folder there, if I new what would need to go into the columns nleft and nright. (The rest is pretty self explanatory.)
Thanks!

**Comment by nilsteampassnet** [comment]
What is the size of the folder name you create?

**Comment by Sailing74** [comment]
"Test" :-)

**Comment by Sailing74** [comment]
Just by way of update: I did a fresh reinstall of TeamPass (and am still in the process of typing in again all saved passwords...). With this, new folders can be created again (which, I think, confirms my guess that something with the database may have been wrong, carried on over various versions of TeamPass since years). However, when I first create a new folder as a user, strange things are being displayed: The user typicalls gets to see a folder he is not supposed to see, or he sees no change at all. After logging out and logging in again, everything is ok.
