### ISSUE TITLE
Auto-creation of LDAP users broken after update to 2.1.27

### ISSUE THREAD

**Issue by mkszuba** [nilsteampassnet/TeamPass#1855]
Hello,

A while ago I enabled LDAP authentication, with automatic creation of TeamPass users on first login, in our instance of TeamPass 2.1.26. Had to set some settings (the user suffix, IIRC) directly in the database because there was no corresponding field in the Web configuration form but that aside, it worked perfectly and users did get auto-created. Unfortunately, the latter broke after updating to 2.1.27 - if a new user attempts to access TeamPass, they get stuck on the log-in page with the "please wait" wheel spinning, whereas TP logs show a "user_not_exists" error.

Having spent some time trying to debug the problem, LDAP integration itself seems to work fine - not only are existing users still able to log in but also if a new user types an incorrect password, the login page immediately returns an error. I have also confirmed that the problem is **not** due to the "only allow local users" option having been enabled - on one hand it was off, on the other switching it on again causes login attempts of new LDAP users to fail immediately. 

Observed with several different Web browsers running on different systems.

Please let me know if you need any more information.

### Steps to reproduce
1. Enable LDAP authentication
2. Make sure the option only allowing local users is disabled
3. Attempt to log in as user without an existing entry in the TeamPass database

### Expected behaviour
TeamPass should create the user in CPM and the user should be able to log in.

### Actual behaviour
* The user gets stuck on the spinning wheel
* TeamPass reports user_not_exists in the log

### Server configuration
**Operating system**: GNU/Linux (Debian Jessie)

**Web server:** Apache HTTPD 2.4.10

**Database:** MySQL 5.5.57

**PHP version:** 5.6.30

**Teampass version:** 2.1.27

**Teampass configuration file:** I'd rather not post the whole thing here for privacy reasons but if you do need it, let me know and I'll prepare a sanitised version

**Updated from an older Teampass or fresh install:** updated

### Client configuration
**Browser:** Mozilla Firefox, Chromium, Google Chrome, Microsoft Edge

**Operating system:** Linux, Windows

**Comment by Maltazar** [comment]
I have the same issue as reported here.

**Comment by nilsteampassnet** [comment]
I think this is fixed in Development branch.

I will create a new pre-release in the next days.
You could test from it.

**Comment by Maltazar** [comment]
Great! :) Thanks

**Comment by Maltazar** [comment]
This problem is still not solved in the develop branch.

**Comment by Maltazar** [comment]
Okay i can confirm that after an alter of the Users table to allow NULL on column 'email', can new users be created.

**Comment by heangratha** [comment]
Hi @mkszuba,

I also try with 2.1.26 but not able to get it works with ldap authentication.
Can you provide me the steps how to get it works?

This is what I got from ldap debug

> 5a3a3a19 daemon: activity on 1 descriptor
5a3a3a19 daemon: activity on:
5a3a3a19 slap_listener_activate(8): 
5a3a3a19 daemon: epoll: listen=8 busy
5a3a3a19 daemon: epoll: listen=9 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=10 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=11 active_threads=0 tvp=zero
5a3a3a19 >>> slap_listener(ldap:////)
5a3a3a19 daemon: listen=8, new connection on 19
5a3a3a19 daemon: added 19r (active) listener=(nil)
5a3a3a19 conn=1008 fd=19 ACCEPT from IP=192.168.56.1:36694 (IP=0.0.0.0:389)
5a3a3a19 daemon: activity on 2 descriptors
5a3a3a19 daemon: activity on: 19r
5a3a3a19 daemon: read active on 19
5a3a3a19 daemon: epoll: listen=8 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=9 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=10 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=11 active_threads=0 tvp=zero
5a3a3a19 connection_get(19)
5a3a3a19 connection_get(19): got connid=1008
5a3a3a19 connection_read(19): checking for input on id=1008
ber_get_next
ldap_read: want=8, got=8
  0000:  30 41 02 01 01 60 3c 02                            0A...`<.          
ldap_read: want=59, got=59
  0000:  01 03 04 2b 30 3d 70 65  74 68 72 61 2c 6f 75 3d   ...+0=pethra,ou=  
  0010:  70 65 6f 70 6c 65 2c 64  63 3d 64 75 6d 6d 79 2d   people,dc=dummy-  
  0020:  68 6f 77 74 6f 2c 64 63  3d 6c 6f 63 61 6c 2c 80   howto,dc=local,.  
  0030:  0a 70 61 73 73 77 6f 72  64 24 24                  .password$$       
ber_get_next: tag 0x30 len 65 contents:
ber_dump: buf=0x7f0638102c70 ptr=0x7f0638102c70 end=0x7f0638102cb1 len=65
  0000:  02 01 01 60 3c 02 01 03  04 2b 30 3d 70 65 74 68   ...`<....+0=peth  
  0010:  72 61 2c 6f 75 3d 70 65  6f 70 6c 65 2c 64 63 3d   ra,ou=people,dc=  
  0020:  64 75 6d 6d 79 2d 68 6f  77 74 6f 2c 64 63 3d 6c   dummy-howto,dc=l  
  0030:  6f 63 61 6c 2c 80 0a 70  61 73 73 77 6f 72 64 24   ocal,..password$  
  0040:  24                                                 $                 
5a3a3a19 op tag 0x60, time 1513765401
ber_get_next
ldap_read: want=8 error=Resource temporarily unavailable
5a3a3a19 conn=1008 op=0 do_bind
ber_scanf fmt ({imt) ber:
ber_dump: buf=0x7f0638102c70 ptr=0x7f0638102c73 end=0x7f0638102cb1 len=62
  0000:  60 3c 02 01 03 04 2b 30  3d 70 65 74 68 72 61 2c   `<....+0=pethra,  
  0010:  6f 75 3d 70 65 6f 70 6c  65 2c 64 63 3d 64 75 6d   ou=people,dc=dum  
  0020:  6d 79 2d 68 6f 77 74 6f  2c 64 63 3d 6c 6f 63 61   my-howto,dc=loca  
  0030:  6c 2c 80 0a 70 61 73 73  77 6f 72 64 24 24         l,..password$$    
ber_scanf fmt (m}) ber:
ber_dump: buf=0x7f0638102c70 ptr=0x7f0638102ca5 end=0x7f0638102cb1 len=12
  0000:  00 0a 70 61 73 73 77 6f  72 64 24 24               ..password$$      
5a3a3a19 >>> dnPrettyNormal: <0=pethra,ou=people,dc=dummy-howto,dc=local,>
=> ldap_bv2dn(0=pethra,ou=people,dc=dummy-howto,dc=local,,0)
ldap_err2string
<= ldap_bv2dn(0=pethra,ou=people,dc=dummy-howto,dc=local,)=-4 Decoding error
5a3a3a19 conn=1008 op=0 do_bind: invalid dn (0=pethra,ou=people,dc=dummy-howto,dc=local,)
5a3a3a19 send_ldap_result: conn=1008 op=0 p=3
5a3a3a19 send_ldap_result: err=34 matched="" text="invalid DN"
5a3a3a19 send_ldap_response: msgid=1 tag=97 err=34
ber_flush2: 24 bytes to sd 19
  0000:  30 16 02 01 01 61 11 0a  01 22 04 00 04 0a 69 6e   0....a..."....in  
  0010:  76 61 6c 69 64 20 44 4e                            valid DN          
ldap_write: want=24, written=24
  0000:  30 16 02 01 01 61 11 0a  01 22 04 00 04 0a 69 6e   0....a..."....in  
  0010:  76 61 6c 69 64 20 44 4e                            valid DN          
5a3a3a19 conn=1008 op=0 RESULT tag=97 err=34 text=invalid DN
5a3a3a19 daemon: activity on 1 descriptor
5a3a3a19 daemon: activity on:
5a3a3a19 daemon: epoll: listen=8 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=9 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=10 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=11 active_threads=0 tvp=zero
5a3a3a19 daemon: activity on 1 descriptor
5a3a3a19 daemon: activity on: 19r
5a3a3a19 daemon: read active on 19
5a3a3a19 daemon: epoll: listen=8 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=9 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=10 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=11 active_threads=0 tvp=zero
5a3a3a19 connection_get(19)
5a3a3a19 connection_get(19): got connid=1008
5a3a3a19 connection_read(19): checking for input on id=1008
ber_get_next
ldap_read: want=8, got=7
  0000:  30 05 02 01 02 42 00                               0....B.           
ber_get_next: tag 0x30 len 5 contents:
ber_dump: buf=0x7f0638002020 ptr=0x7f0638002020 end=0x7f0638002025 len=5
  0000:  02 01 02 42 00                                     ...B.             
5a3a3a19 op tag 0x42, time 1513765401
ber_get_next
ldap_read: want=8, got=0

5a3a3a19 ber_get_next on fd 19 failed errno=0 (Success)
5a3a3a19 connection_read(19): input error=-2 id=1008, closing.
5a3a3a19 connection_closing: readying conn=1008 sd=19 for close
5a3a3a19 connection_close: deferring conn=1008 sd=19
5a3a3a19 conn=1008 op=1 do_unbind
5a3a3a19 conn=1008 op=1 UNBIND
5a3a3a19 connection_resched: attempting closing conn=1008 sd=19
5a3a3a19 connection_close: conn=1008 sd=19
5a3a3a19 daemon: removing 19
5a3a3a19 conn=1008 fd=19 closed
5a3a3a19 daemon: activity on 1 descriptor
5a3a3a19 daemon: activity on:
5a3a3a19 daemon: epoll: listen=8 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=9 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=10 active_threads=0 tvp=zero
5a3a3a19 daemon: epoll: listen=11 active_threads=0 tvp=zero
