### ISSUE TITLE
API: Folders created at level 0 instead of correct level

### ISSUE THREAD

**Issue by jjlimepoint** [nilsteampassnet/TeamPass#1857]
To reproduce:

http://[teampass-server]/teampass/api/index.php/add/folder/ZWxlcGhhbnQ7MDswOzA7MAo=?apikey=[omitted]

Expected: Folder created at level #1 
Actual: Folder created at level #0.  All root folders behave like children of it, at this point, so if you delete it, everything is deleted!  - this is the same behaviour as #1764 

Mitigation: If you log in as a user to the web ui, and select folders, it DOES get resolved, and then behaves correctly.  Of course that's no good in a script - I couldn't find any API way to poke it in a way that causes that update to happen....

(Note: this also happens with folders that are children of non-root - exactly the same unfortunate behaviour :( )

**Comment by nilsteampassnet** [comment]
Thank you.

Corrected.
