### ISSUE TITLE
install.php looks broken

### ISSUE THREAD

**Issue by gbisschops** [nilsteampassnet/TeamPass#1859]
Hello,

I'm installing team pass on an amazon linux machine.
I mostly followed this procedure http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/

I used httpd and php5.6

After having setup ssl and db I was ready to start the install.php but here is what I'm facing : 

<img width="1210" alt="screen shot 2017-08-10 at 12 12 28" src="https://user-images.githubusercontent.com/30896353/29166055-4703a7e6-7dc5-11e7-850f-4540df7372e5.png">

I tried to click on next, the page look the same except the welcome message is gone.
So I enter the values in the 2 texts box and click on Launch, then nothing happens : 

<img width="1207" alt="screen shot 2017-08-10 at 12 14 58" src="https://user-images.githubusercontent.com/30896353/29166150-8c6af514-7dc5-11e7-806c-50d80ab12bdf.png">

The only "strange" messages I can see in error.log and ssl_error.log are : 
[Thu Aug 10 09:25:13 2017] [error] [client 10.6.66.14] Directory index forbidden by Options directive: /var/www/html/
[Thu Aug 10 09:56:41 2017] [error] [client 10.6.66.14] File does not exist: /var/www/html/favicon.ico
...
[Thu Aug 10 09:09:29 2017] [error] [client 10.6.66.14] Directory index forbidden by Options directive: /var/www/html/
[Thu Aug 10 09:09:29 2017] [error] [client 10.6.66.14] File does not exist: /var/www/html/favicon.ico, referer: https://10.1.0.148/

Looking at the layout of the page, I notice that the checks seems broken at the step "    Execution time limit 

'; echo ' '; echo ' '; echo ' '; echo ' '; echo ' '; echo ' '; ?> "

On my setup, the php ini file is located at /etc/php.ini
and I've set the value : 
max_execution_time = 120

Just to be sure, here is the php ll result in etc : 

drwxr-xr-x  2 root root    4096 Aug  9 14:52 php-5.6.conf
drwxr-xr-x  2 root root    4096 Aug 10 10:00 php-5.6.d
-rw-r--r--  1 root root   67146 Aug  9 15:08 php-5.6.ini
lrwxrwxrwx  1 root root      23 Aug  9 14:52 php.d -> /etc/alternatives/php.d
lrwxrwxrwx  1 root root      25 Aug  9 14:52 php.ini -> /etc/alternatives/php.ini
drwxr-xr-x  2 root root    4096 Aug  9 14:55 php-zts-5.6.d
lrwxrwxrwx  1 root root      27 Aug  9 14:52 php-zts.d -> /etc/alternatives/php-zts.d

Do someone have an idea about this issue ? 

Thanks,

Greg

**Comment by B0T0B** [comment]
Hello Greg,
What is your Teampass version?
Did you clone (or download zip) from the master branch?

**Comment by gbisschops** [comment]
Hello Botob,

I think yes, I used the link provided in the tutoriel I've followed : https://github.com/nilsteampassnet/TeamPass/archive/master.zip

Best regards,

**Comment by B0T0B** [comment]
It looks like php is not enable on your server.
I remove the php5.conf and php5.load from my /etc/apache2/mods-enabled/ and then reload apache, and the result is pretty much the same as yours
Did you launch this command ?
`yum install -y php56w php56w-opcache php56w-common php56w-mcrypt php56w-ldap php56w-mysqlnd php56w-mbstring php56w-bcmath php56w-gd`
(not sure if the packages names are correct not working on centos)

**Comment by gbisschops** [comment]
Ho god, it looks like php is not active.
I used the commands : 
sudo yum install php56.x86_64 --skip-broken
sudo yum install php56-opcache.x86_64
sudo yum install php56-mcrypt.x86_64
sudo yum install php56-ldap.x86_64
sudo yum install php56-mysqlnd.x86_64
sudo yum install php56-mbstring.x86_64
sudo yum install php56-bcmath.x86_64

If I create a phpinfo.php in /var/www/html and I browse the page, I got the source code...

If I try sudo yum install php_mod I got this : 

[ec2-user@ip-10-1-0-148 conf]$ sudo yum install mod_php
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                                | 2.1 kB  00:00:00
amzn-updates                                                             | 2.3 kB  00:00:00
4 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package php56.x86_64 0:5.6.30-1.133.amzn1 will be installed
--> Processing Dependency: httpd-mmn = 20120211x86-64 for package: php56-5.6.30-1.133.amzn1.x86_64
--> Processing Dependency: httpd24 for package: php56-5.6.30-1.133.amzn1.x86_64
--> Running transaction check
---> Package httpd24.x86_64 0:2.4.27-3.71.amzn1 will be installed
--> Processing Dependency: httpd24-tools = 2.4.27-3.71.amzn1 for package: httpd24-2.4.27-3.71.amzn1.x86_64
--> Running transaction check
---> Package httpd24-tools.x86_64 0:2.4.27-3.71.amzn1 will be installed
--> Processing Conflict: httpd24-2.4.27-3.71.amzn1.x86_64 conflicts httpd < 2.4.27
--> Processing Conflict: httpd24-tools-2.4.27-3.71.amzn1.x86_64 conflicts httpd-tools < 2.4.27
--> Finished Dependency Resolution
Error: httpd24-tools conflicts with httpd-tools-2.2.32-1.9.amzn1.x86_64
Error: httpd24 conflicts with httpd-2.2.32-1.9.amzn1.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


The install looks broken :/

**Comment by gbisschops** [comment]
OK, I found out that httpd 2.2 has conflicts with php56, so the command
sudo yum install php56.x86_64 --skip-broken
didn't install the main package ...

I use this script witch worked like a charm : 

https://gist.github.com/diogoca/98cf2ea05e91f3f6ee60235bcd38be1e

Now I have php56 running on my machine with httpd 24 :)

The install.php looks ok, but it will be for my return of vacation :)

Thanks for the hints !

Greg
