### ISSUE TITLE
Missing versions

### ISSUE THREAD

**Issue by testingO** [nilsteampassnet/TeamPass#1860]
We've Version 2.1.20 up and running since some time.

In Issue #1852 I described the problems occured during different upgrades we tried!
You answered that we've to migrate from version to version!
I asked for the repository of all the missing intermediate versions, but we've never received an answer!

So please tell us, which are the intermediate versions we've to go through?
Where are these versions?

On Github are versions like: 2.1.23, 2.1.25.2, 2.1.27, fix_api, fix_2.1.24, ...
but NOT the version which I would expect to go through, after your answer!

Thanks in advance!

**Comment by B0T0B** [comment]
Actually you can get everything you want either by going : 
- https://github.com/nilsteampassnet/TeamPass/tags
- https://github.com/nilsteampassnet/TeamPass then clic on Branch : master, and clic on the Tags tab
I have nerver made upgrade, but i think you need to do 2.1.20, 2.1.21, 2.1.22, 2.1.23.4 and so on...
I hope the author will correct me if i'm wrong. But anyway, before making any update, backup everything!

**Comment by nilsteampassnet** [comment]
This is absolutely correct.

Thank you @B0T0B

**Comment by testingO** [comment]
Thanks B0T0B 
for your help, but all this intermediate version are completely shit!
Even the upgrade for 2.1.21 doesn't work in step 1 (install works, but destroys the data!)
From my point of view, this software is not upgradeable without dataloss! Very nice.

**Comment by testingO** [comment]
Upgrade 2.1.20 > 2.1.21: doesn't work in Step1
Upgrade 2.1.20 > 2.1.22: doesn't work in Step1
Upgrade 2.1.20 > 2.1.23.4: works, but private password can't be changed, cause no possibility to enter salt!
Upgrade 2.1.23.4 > 2.1.24.4: passwords gone!!! private passwords work, cause entering salt is possible

So these intermediate steps don't work and finally loosing passwords!

Has anybody ever made normal upgrades with success????

**Comment by nilsteampassnet** [comment]
Yes it works, I've done an upgrade for some users from 2.1.19 to latest.
You should try to upgrade from 2.1.20 to 2.1.24 directly.
You know it exists so many configuration of servers and use cases, so indeed I try to have all of them put inside the upgrade process.
Since those old versions, Teampass has evolved a lot for being in version 2.1.27 quite good in term of security, encryption protocols, ... 
Please don't be  too rude in your words, Teampass is free of use, I spend days and nights to work on it, I have never neglected help to users, so I would appreciate more respect.
If you need my help, you are free to contact me

**Comment by testingO** [comment]
Hi Nils
Sorry to be a bit rude, but I tried the whole weekend to upgrade as recommended without success!
And now you suggest to go directly to 2.1.24 ... that's a pity! (without VM snapshots, this would be horrible!)
Thanks and I'll come back with the results when I find time for the next round of upgrades ...

**Comment by testingO** [comment]
Hi Nils
We're now on 2.1.24. Global passwords are all available, Personal passwords ha a successful conversion rate of about 50%, but we've still an old copy up and running.

should we now upgrade to 2.1.25.2 and afterwards directly to 2.1.26-final-3 ?
--

**Comment by testingO** [comment]
Hi Nils

We’re using Teampass 2.1.26 since long time.

Which upgrade-path would you propose to reach the latest version?

Thanks for your help and this great software!

Freundliche Grüsse | Meilleures salutations | Cordiali saluti | Kind regards
Ludwig Raffler



Von: Nils Laumaillé ***@***.***>
Gesendet: Montag, 31. Oktober 2022 05:49
An: nilsteampassnet/TeamPass ***@***.***>
Cc: Ludwig Raffler ***@***.***>; Author ***@***.***>
Betreff: Re: [nilsteampassnet/TeamPass] Missing versions (#1860)


Closed #1860<https://github.com/nilsteampassnet/TeamPass/issues/1860> as completed.
