### ISSUE TITLE
[Installation] Some fields are missing

### ISSUE THREAD

**Issue by sonbinome** [nilsteampassnet/TeamPass#1861]
Hi everybody.
In the first time, i'm a french boy so I'm sorry in advance for my English.

### Steps to reproduce
1. Install Debian 9 with all prerequisites but not mysql-server (I use an external server)
2. Download Teampass 2.1.27 and unzip it in /var/www/teampass
3. Change teampass folder's owner for www-data
4. Lunch install

### Actual behaviour
On the "preparation" page some fields are missing

![teampass](https://user-images.githubusercontent.com/30912487/29194344-653c06a4-7e29-11e7-9dc7-00eb656e40b0.png)

So I can't continue to next step.

### Server configuration
**Operating system**:
Debian 9 (64 bits)
**Web server:**
Apache 2
**Database:**
Externe Mysql 5
**PHP version:**
PHP 7
**Teampass version:** 
Teampass 2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox, IE
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by B0T0B** [comment]
Bonjour @sonbinome 
Que veux-tu dire par il manque des champs? 
Lors de l'installation, je n'ai pas remarqué de problème particulier. Sur le screenshot : 
- Table prefix : Si tu souhaite ajouter un prefix aux tables qui seront créées 
- Absolute Path to SaltKey : Un chemin pour stocker la clé (tu peux le laisser vide, ou indiquer un répertoire ou www-data à la droit de lecture / ecriture
- Administrator password : Tu choisis le mot de passe que tu veux.
Je viens de refaire un test d'installation avec le master.zip, et pas de problème
Par contre attention, ne passe pas le site en Français, il y a un bug (résolu mais pas encore commit dans la branche master)

**Comment by sonbinome** [comment]
Bonjour @B0T0B 

Mon problème est que lorsque je clique sur "Launch" après avoir indiquer un mot de passe, rien ne se passe (tentative avec Firefox et IE)
Au depart j'avais indiqué un chemin pour la "SaltKey" comme préconisé et je pensais que cela venait de la (Prb de droit ou autre). Du coup j'ai laisse le champs vide car j'ai vu que par défaut Teampass se servira du dossier "includes". Mais tjrs sans succès.
De ce fait en regardant les tutos, je me suis aperçu qu'il y avait un champs pour générer la saltkey. Chose que moi je n'ai pas. Après c'est peut-être un champs qui n'est plus présent lors de l'installation dans les dernières versions. Du coup je pensais à un problème d'installation et c'est pour cela que j'ai posté ici.
 
Je ne maitrîse pas très bien Linux mais je vais tenter de refaire l'installation en Debian 8 avec PHP5 comme je l'ai fait pour mon entreprise. Je n'ai rencontré aucun souci la bas et ca fonctionne même super bien :-).
Je posterai un message pour indiquer si cela à résolu mon problème. Mais c'est dommage car je voulais profiter d'une nouvelle installation pour passer à Debian9.

Un grand merci en tout cas pour ta réponse.

**Comment by sonbinome** [comment]
Je me permet d'ajouter un dernière chose à laquelle je viens de penser.
Pour mon installation, je ne suis pas en direct (pour le moment) car je suis en train de refaire mon réseau.
Du coup je passe par un reverse proxy. Le problème pourrait peut-être venir de là?
Avant la solution radicale de tout réinstaller je vais supprimer l'accès depuis le reverse proxy.

**Comment by B0T0B** [comment]
Je ne pense pas que le soucis vienne du reverse proxy.
Concernant le champ pour générer la clé, il n'est effectivement plus présent. Si tu laisses vide, il prendra un dossier par défaut dans le dossier www/teampass.
J'ai fais un test d'installation sur une Debian 9, pas eu de problème.
Du coup, si tu renseignes uniquement le mot de passe administrateur, tu arrives à continuer le setup?
Pour information, si tu veux préciser un chemin pour la clé, il faut que tu fasses un dossier, et que www-data puisse écrire dedans.
Par exemple : 
`sudo mkdir /home/www-data/
sudo chown www-data. /home/www-data/
sudo chmod 700 /home/www-data/`
Et tu peux mettre /home/www-data/ dans le champ "Absolute path to slated key"

**Comment by sonbinome** [comment]
Désolé de mon retour tardif mais le problème ne venait, en effet, pas du côté du serveur.
Par un heureux hasard, mon ordi m'a laché cette semaine et j'ai du en installé à nouveau et en relançant mon navigateur pour tester l'installation, celle-ci à aboutie.
Merci d'avoir pris du temps pour essayer de diagnostiquer un problème qui était mal ciblé.

**Comment by nilsteampassnet** [comment]
Merci de ton retour.
