### ISSUE TITLE
Import from Keepass.xml to Personalfolder no access to Item

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1862]
### Steps to reproduce
1. Login as user "_test.user_"
2. Set personal salt key
3. Import the .xml to your personal area

### Expected behaviour
You can edit and watch your imported passwords.

### Actual behaviour
Teampass tells me, I got no access to this item.
And the author is: "_test.user_" 

With some research I found out that the the id of this Item is wrong.
Go to your Teampass database. Inside of the table "_Teampass_items_" in the collumn id_tree there is something added to the id. 

e.g:
Expected: id_tree = "_100_"
Actual: idtree = "_100-perso_"
If you delet the "_-perso_" in your table you can watch the item.

### Server configuration
**Teampass version:** 
2.1.27.7

**Comment by nilsteampassnet** [comment]
Thank you for your feedback and investigation (this helps a lot).

I will check this.

**Comment by B0T0B** [comment]
I've made some tests too. I got the sae behavior.
But if I create a folder on my personal space, and then import xml into it, no read / write problem :)
