### ISSUE TITLE
Create folder as a normal user

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1864]
I don't know if I'm right or wrong but is it possible as a normal user to create a folder (But not at Root)?

The user got normal permissions:
Role: "e.g. Folder"
Administrated by "Admin"
Allowed folders: None
Denied folders: None
User is **no**: Admin, Manager, Read only, Human Resource
and is not allowed to create folder at root

e.g.
- Root
     - Main Folder (created by admin)
          - Subfolder (created by user)

![grafik](https://user-images.githubusercontent.com/27355139/29273369-53af9f4e-8104-11e7-90b6-b194a82fe3b4.png)

### Server configuration
**Teampass version:** 
2.1.27.7

**Comment by B-o-t** [comment]
Hello,
According to the documentation : https://teampass.readthedocs.io/en/latest//manage/manage-users/

Users can only deal with item.
Only Admin, Manager and HR can manage folders.

But it would be a nice feature to let users create subfolder, or make a "Folder creation request" that Manager or HR can validate :)

**Comment by Sailing74** [comment]
I think users can create sub-folders, if the option "Sub-folders managed by anyone who can manage parent" is enabled. At least in my setup normal users can create folders within folders accessible (writeable) to/by them.

**Comment by benjamin2501** [comment]
> [...]users can create sub-folders, if the option "Sub-folders managed by anyone who can manage parent" is enabled.

That workes for me too, thanks!
