### ISSUE TITLE
First connection issue

### ISSUE THREAD

**Issue by nrenault** [nilsteampassnet/TeamPass#1865]
Hello,

I installed TeamPass with LDAP authentification but i have an issue.

When an user login on TeamPass for the first time, he get access to all folders/passwords until he refresh his browser.

Anyone have the same issue ?
It can be a cache/web server issue ?

TeamPass version: 2.1.27
Webserver: Apache 2.4.6
PHP version: 7.0.22
OS: CentOS

Thanks,
Regards,

Nicolas

**Comment by nilsteampassnet** [comment]
Thank you.

This bug should be fixed in next release.

**Comment by gulikoza** [comment]
This seems like a pretty critical issue. I've just noticed it myself.
Is there an ETA when this will be fixed? How can we add passwords, when users will see every folder on first login?

**Comment by benjamin2501** [comment]
@nilsteampassnet: Bug still exists in 2.1.27.8

**Comment by gulikoza** [comment]
Hi @nilsteampassnet,

Is there an ETA when this LDAP issues will be fixed?
Thanks!
