### ISSUE TITLE
Import items into personal causes crash or doesnt allow viewing/copying

### ISSUE THREAD

**Issue by cbabs** [nilsteampassnet/TeamPass#1866]
### Steps to reproduce
1. Import passes into personal folder.  Use excel and save as csv
2. One csv with URL field with an IP and one csv without url field

### Expected behaviour
Passwords import and clicking on them displays pass and doesn't freeze

### Actual behaviour
For csv with ip address in url teampass freezes and I have to refresh
For csv with url blank the password goes into db but I cant view it.  When I copy then paste into notepad this is what it pastes: "You must create a personal salt key to use the personal folder feature."
NOTE: I already did enter my salt for the session.

### Server configuration
**Operating system**:
Linux FRCIT-IPAM 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache 2.4.7

**Database:**
mysql 5.5.57

**PHP version:**
 5.5.9-1ubuntu4.22

**Teampass version:** 
2.1.27.4

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome Version 60.0.3112.90 (Official Build) (64-bit)
**Operating system:**
Win 7 64

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
I've tried to reproduced without success.
Nevertheless I have noticed that empty url is replaced by value `0`, I will fix this.

Perhaps can you share the apache errors related to those operation you did?

**Comment by nilsteampassnet** [comment]
Reopen if not fixed in your environment.
