### ISSUE TITLE
SMTP Security Type setting ignored in 2.1.27, always uses "TLS"

### ISSUE THREAD

**Issue by Sailing74** [nilsteampassnet/TeamPass#1867]
While I had sending e-mails running with previous versions, I cannot get it to work with my fresh 2.1.27 install, because the "SMTP Security Type setting" is ignored. Even if I set it to SSL or even None, TeamPass still tries to send with TLS:

´Aug 15 09:20:14 server642 postfix/smtpd[15729]: connect from unknown[192.168.1.103]
Aug 15 09:20:14 server642 postfix/smtpd[15729]: Anonymous TLS connection established from unknown[192.168.1.103]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Aug 15 09:20:14 server642 postfix/smtpd[15729]: lost connection after STARTTLS from unknown[192.168.1.103]
Aug 15 09:20:14 server642 postfix/smtpd[15729]: disconnect from unknown[192.168.1.103] ehlo=1 starttls=1 commands=2`

**Comment by roru69** [comment]
Hi,

I have/had the same problem.

The file that causes this is: includes/libraries/Email/Phpmailer/class.phpmailer.php

At line 265 you will find:    public $SMTPAutoTLS = true;
Change it to:    public $SMTPAutoTLS = false;

And all should work well.. The only problem is when Teampass updates, it will be changed back to "true".


Kind Regards,

RoRu69

**Comment by Sailing74** [comment]
Ok, maybe the option to configure TLS should be removed, if code adding is required.

For what it's worth, I solved the issue by using the host name (appropriate for the certificate) rather than the IP address in the configuration. This way, TLS works and I don't have to keep disabling it for updates.
