### ISSUE TITLE
Docker version: Attempting to import a password file fails

### ISSUE THREAD

**Issue by jandrews65** [nilsteampassnet/TeamPass#1868]
### Steps to reproduce
1. Created Docker Container Host on Vagrant
2. Created Docker Swarm consisting of Apache 2 server and MySQL containers
3. Installed Teampass as per instructions
4. Created folder below Root, created Role with access
5. Enabled import of Lastpass XML

### Expected behaviour
What should happen (and does with the github version) is that a Window should immediately open to select the file in a directory on the client machine

### Actual behaviour
The spinner spins and nothing else happens

### Server configuration
**Operating system**: Container Host - PhotonOS Docker version 1.13.1

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6

**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh install
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome or Firefox
**Operating system:**
Windows 10 or Linux
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Can you please share the Apache log?

I believe a PHP extension is not included in the Docker file.

**Comment by jandrews65** [comment]
Hi Nils

Could you tell me where the Apache log is likely to be found?

John

**Comment by nilsteampassnet** [comment]
Sure, you should found them inside folder /var/log/httpd

**Comment by jandrews65** [comment]
Nils,

In this case the Apache2 instance is inside a Docker Container.. There is
no /var/log./httpd

John

**Comment by nilsteampassnet** [comment]
Fix provided in branch `development`.
Version of nginx-php-fpm shall be 1.3.5
