### ISSUE TITLE
link in password/item description seems not to work

### ISSUE THREAD

**Issue by TrueType** [nilsteampassnet/TeamPass#1871]
### Steps to reproduce
1. Create a password (Add item)
2. Within the description add a link

### Expected behaviour
I type the link text; I mark the text; I click the button; I add the link URL; save the item and in the display of the item/password in the lower pane I can see the link, click it and come to the desired linked web page.

### Actual behaviour
* the link created is http://password.mydomain.de/%22http://linked-domain.de%22 not http://linked-domain.de
* additionally the link is not formatted (underline or color) in a way I can recognize it as a link.

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL 5.6.19

**PHP version:**
5.5.3

**Teampass version:** 
2.1.27.7 tagged version

### Client configuration
Firefox v54

**Operating system:**
Window 7

**Comment by nilsteampassnet** [comment]
Just tried to reproduce but couldn't.
Here is what I see when showing an item I just created with a link
![image](https://user-images.githubusercontent.com/1197546/29700367-30259296-8964-11e7-8cde-ad8cebc9d504.png)

Note that the link is not "colorized", a small chain icon is added to open the link in a new window.

**Comment by TrueType** [comment]
Hey. I got some mail about this thread, but cannot see it here... ?
Well, please see above - I created the link within the "description" of the item. Not in the special "url" field.

**Comment by TrueType** [comment]
Another one: There is a link in the lower left footer and it links to here - http://teampass.net/about
btw: pretty nice project, but it looks like you should losen up a bit, meaning, having others take a bigger part in it. And you should build up some whatsoever automated testing.
