### ISSUE TITLE
 New Admin User login not working -JSON Parse file failure

### ISSUE THREAD

**Issue by tcranston** [nilsteampassnet/TeamPass#1872]
### Steps to reproduce
1. Create a new User and set as an Administrator
2. Login in as new User
3. Login and see 'This page does not exist' and an alert popup stating 'Requested JSON parse failed.'

### Expected behaviour
User should beable to login with Admin privileges 

### Actual behaviour
Login and see 'This page does not exist' and an alert popup stating 'Requested JSON parse failed.'

Looking at chrome console - there is a 'Hacking attempt...' returned which is coming from '/sources/admin.queries.php'

![screen shot 2017-08-17 at 13 10 02](https://user-images.githubusercontent.com/7591038/29411914-9e0936c6-834e-11e7-87ca-6afe8b5f8cce.png)

### Server configuration
**Operating system**:
CentOS 6.9

**Web server:**
cPanel & WHM 64.0 (build 36)

**Database:**
mySQL version: 5.6.35

**PHP version:**
PHP 5.5

**Teampass version:** 
TeamPass 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Now Fixed
