### ISSUE TITLE
Teampass Android App stops working after upgrade from 2.1.26 -> 2.1.27

### ISSUE THREAD

**Issue by rdeangel** [nilsteampassnet/TeamPass#1875]
Hi,

I have the Teampass Android app working correctly and tried to upgrade from 2.1.26 to 2.1.27 but after that the new secret files was generate and a much longer global salt key was used.

I tried entering this on the Teampass API server for the app but the app still failed the decript password.

All items on the app loaded sucessfully but the passwords were all empty as they could no longer decrypt.
In the normal web gui teampass everything was working and the password were showing correctly after the upgrade.

In case you are wondering I did not enable the personal salt key feature.

The new file long global salt, is that an hashed salt key or is it the plain salt key I need to use in the android APP API config file.

Any help you can provide is much appreciated

BTW is there any plan to provide a phone sized webinterface or perhaps an official app in the near future, the ALPEIN SOFTWARE one it seems not up to date as far as I can see.

Thanks

**Comment by Tacioandrade** [comment]
So the problem is this, I sent an email to the developers of the App to see if they had some tutorial on how to put it to work and I'm waiting for their return .....

But it really would be a great option for a native app of the team (even if paid), but I believe that it will not be created due to the time that this post was created and to this day is unanswered.

**Comment by nilsteampassnet** [comment]
Just for your information.
Teampass will evolve 1st quarter of 2018 focusing on multi-support usage.
Meaning that in version 3.0, the goal is that Teampass becomes usage from a smartphone, tablet and computer. This will permit to limit the usage of a dedicated application.
