### ISSUE TITLE
install - finalisation error but no errors visible

### ISSUE THREAD

**Issue by gbisschops** [nilsteampassnet/TeamPass#1877]
Hello,

I'm trying to install team pass on an amazon linux machine.
I already got an issue previously ( https://github.com/nilsteampassnet/TeamPass/issues/1859 ) but it is solved now.

I'm having a new one ; 
![teampass_install](https://user-images.githubusercontent.com/30896353/29618165-8657c2b8-8817-11e7-8407-257e38507800.png)

I thought it was the salt key location that was causing the issue, but the files are correctly written in the correct folder.

I do not see any relevant errors in the log files.

How can I debug that one with the install.php. ?

Thanks in advance,

Greg

EDIT ;

It seems the setup is somehow complete, if I try to access the application and try to login I got this :

![screen shot 2017-08-23 at 16 09 03](https://user-images.githubusercontent.com/30896353/29620188-8c287f7e-881d-11e7-9acb-85360000519f.png)

But I want to be sure the installation is correct, if I delete manually the install directory, how am I sure everything is correct ?

**Comment by gbisschops** [comment]
as an update, I've move the install folder to another location and I'm setting up team pass, it looks like this is working quiet fine.

**Comment by B-o-t** [comment]
Hello,
It looks like this issue : https://github.com/nilsteampassnet/TeamPass/issues/1863 :)

**Comment by gbisschops** [comment]
Hello,

Yes indeed, but I'm using team pass right now so I would not try the install again. Because it is working fine, I think it can be closed.

Thanks,

Greg
