### ISSUE TITLE
Error while trying to create a new item in personal folder

### ISSUE THREAD

**Issue by Fernando-Sousa** [nilsteampassnet/TeamPass#1879]
### Steps to reproduce
1. Access my personal folder
2. Set the personal salt key
3. Try to create an item with an @ in the login field.
4. Creation of the item fails  

### Expected behaviour
Should be able to create the item

### Actual behaviour
TeamPass throws an information message and does not create the item.
This is happening with all the users

### Server configuration
**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache 2
**Database:**
10.0.31-MariaDB-0ubuntu0.16.04.2

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1

**Teampass version:** 
TeamPass 2.1.27 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome  60.0.3112.101
**Operating system:**
Windows 10 x64 1703
#### Web server error log
``
Insert your webserver log here
[Fri Aug 25 14:48:24.121472 2017] [:error] [pid 1391] [client xxx.xxx.xxx.xxx:56112] PHP Notice:  Undefined variable: link in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:48:24.121539 2017] [:error] [pid 1391] [client xxx.xxx.xxx.xxx:56112] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:49:30.126247 2017] [:error] [pid 1389] [client xxx.xxx.xxx.xxx:56159] PHP Notice:  Undefined variable: link in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:49:30.126332 2017] [:error] [pid 1389] [client xxx.xxx.xxx.xxx:56159] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:50:49.533149 2017] [:error] [pid 1500] [client xxx.xxx.xxx.xxx:56174] PHP Notice:  Undefined variable: link in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:50:49.533230 2017] [:error] [pid 1500] [client xxx.xxx.xxx.xxx:56174] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:51:27.981416 2017] [:error] [pid 1388] [client xxx.xxx.xxx.xxx:56178] PHP Notice:  Undefined variable: link in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:51:27.981481 2017] [:error] [pid 1388] [client xxx.xxx.xxx.xxx:56178] PHP Warning:  mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 623, referer: https://teampass/index.php?page=items
[Fri Aug 25 14:55:14.326547 2017] [:error] [pid 1512] [client xxx.xxx.xxx.xxx:56205] PHP Notice:  Undefined variable: dataItem in /var/www/html/teampass/sources/items.queries.php on line 2699, referer: https://teampass/index.php?page=items

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
I believe this error is not any more as I couldn't reproduce in `development` branch.
I don't think that it is the value inside login field that leads to your error.
Perhaps something else that would be interesting to discover but here I couldn't, I've tried several conditions and all succeeded.

![image](https://user-images.githubusercontent.com/1197546/30575938-737afdac-9d04-11e7-8d19-13329778b322.png)

Please re-open if issue come back
