### ISSUE TITLE
Google Authenticator Get Link Not working

### ISSUE THREAD

**Issue by difi80211g** [nilsteampassnet/TeamPass#1883]
I enabled the Google 2FA authentication but users can not set it up.  When they go to the login screen, they click the "I need a new QR code. Please send me by email a temporary Identification Code."  A gear will pop up in the middle the screen and just spin for ours.  I never get any way to setup 2FA as a user.

**Comment by nilsteampassnet** [comment]
Can you please follow the ticket template. I don't have the version, the logs ...

Nevertheless I re-performed a test and I could send the QR to myself
![image](https://user-images.githubusercontent.com/1197546/29762514-18644590-8bcf-11e7-8c57-5b92a1d64a2e.png)

Now if it loops indefinitely, have you checked that emails can be sent from `Settings > Admin` configuration page? User have an email? Provide the Apache log, ...

**Comment by difi80211g** [comment]
Sorry for skipping over that data.  

### Server configuration
**Operating system**: Ubuntu 16.04.1
**Web server:** - Apache/2.4.18
**Database:** - mysql 5.0.12
**PHP version:** - 7.0.22
**Teampass version:** - 2.1.27
Fresh Install of Teampass
I have tried on Windows 10 and MAC OS X in Firefox, Chrome and Edge
[apache-log.zip](https://github.com/nilsteampassnet/TeamPass/files/1257686/apache-log.zip)

**Comment by nilsteampassnet** [comment]
OK, I think your Teampass instance is installed from a Release. I believe the error you have in the log file are not any more in the `development` branch.

Indeed in latest commits in `development` branch, I've improved:

* the error.php file preventing the 2 errors you have
`PHP Warning:  require_once(./sources/SecureHandler.php): failed to open stream: No such file or directory in /var/www/html/teampass/error.php on line 16, referer: https://....`
and
`PHP Fatal error:  require_once(): Failed opening required './sources/SecureHandler.php' `

* for the error `PHP Notice:  Undefined index: SSL_SERVER_CERT in /var/www/html/teampass/sources/core.php on line 286`, I believe you have have enabled `HTTPS Strict Transport Security`.
Here I need to improve the code by testing this value before using it.
But nevertheless, you have an issue in your configuration.
Is your certificate is not self signed?
In apache's SSL configuration is the option "SSLOptions +ExportCertData" enabled?

Now concerning your original issue, I would need to connect to your server. Contact me by email.

**Comment by KB7777** [comment]
I have got the same error with GA 2FA. Gear jus spinning.
[Tue Aug 29 09:14:57.618971 2017] [php7:warn] [pid 30061] [client 10.151.40.57:39204] PHP Warning:  require_once(./sources/SecureHandler.php): failed to open stream: No such file or directory in /var/www/html/teampass/error.php on line 16, referer: https://caprica.domain.pl/index.php
[Tue Aug 29 09:14:57.619039 2017] [php7:error] [pid 30061] [client 10.151.40.57:39204] PHP Fatal error:  require_once(): Failed opening required './sources/SecureHandler.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/teampass/error.php on line 16, referer: https://caprica.domain.pl/index.php

Sending e-mails works. Sending GA temporary Identification Code from admin panel works too.

**Comment by KB7777** [comment]
I checked it further...
After login with LDAP login (with Teampass local users only "yes") and copying Identification Code there is no QR code:

![teampass](https://user-images.githubusercontent.com/23165598/29809389-430c17f0-8c9c-11e7-9b6a-dc7e9c880eaf.png)

**Comment by difi80211g** [comment]
I installed from the master branch.  I did not have the "SSLOptions +ExportCertData" option enabled.  I just added it and I am going to install the server from fresh using the guide on teampass.readthedocs.io.  The SSL certificate i am using a purchased certificate, not self-signed.

**Comment by difi80211g** [comment]
I sent you an email through your contact page on your website.  Also, my Generate Offline File is doing the same thing now. I click on it and it just spins.  Eventually i will get an error message though that says "Requested JSON parse failed"

**Comment by juniorcesar** [comment]
I have the same problem. Did you resolve this problem?

**Comment by mikerwilson** [comment]
This works for me now in 2.1.27.8.  It did not work in 2.1.27.7.

**Comment by KB7777** [comment]
It didn't work. I have the same issue with all versions from 2.1.27.7 to 2.1.27.10.
Reopen pls.

**Comment by Marc-Michot-NXO-France** [comment]
Same problem with 2.1.27-dev.
Is it possible to re-open the issue please ?

![image](https://user-images.githubusercontent.com/32137401/35566648-694f6ee0-05c2-11e8-966d-bbd2f94b7f4a.png)
