### ISSUE TITLE
JSON Error when importing with an apostrophe (‘) 

### ISSUE THREAD

**Issue by cbabs** [nilsteampassnet/TeamPass#1886]
### Steps to reproduce
1. Login
2. Create csv with an apostrophe (‘) 
3. Import passwords from csv
 

### Expected behaviour
Should import successfully.  Using special chars is common

### Actual behaviour
Fails with JSON error

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
mysql  Ver 14.14 Distrib 5.5.57

**PHP version:**
PHP 5.5.9-1ubuntu4.22

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 
**Operating system:**
Win7
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

The fix is committed inside `development` branch.
