### ISSUE TITLE
You are not allowed to see this page.

### ISSUE THREAD

**Issue by pedrodaltoe1** [nilsteampassnet/TeamPass#1887]
### Steps to reproduce
1. Install all software
2. Link with LDAP
3. Import some Keepass passwords
4. Click on My Profile

### Expected behaviour
I Was expected to see my profile

### Actual behaviour
Please wait! (With rotating gear), and i Can See the Close Button, I Click there and show me "You are not allowed to see this page." and Bellow "Please identify yourself" With inputs and Bellow "Server time : -" (Only with the dash)

### Server configuration
Oracle Linux Server release 7.4

**Web server: Server version: Apache/2.4.6 () Server built:   Aug 15 2017 12:38:49

**Database: mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version: PHP 5.6.31

**Teampass version:** TeamPass 2.1.27

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install: fresh install

global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '5',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://teampass.xxx.com.br/teampass',
    'favicon' => 'http://teampass.xxx.com.br/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://teampass.xxx.com.br/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://teampass.xxx.com.br/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@xxx.com.br',
    'ldap_domain_dn' => 'DC=xxx,DC=com,DC=br',
    'ldap_domain_controler' => 'ad5503.xxx.com.br,192.168.xxx.xxx,ad1301.xxx.com.br,ad5501.xxx.com.br,ad5502.xxx.com.br,ad1302.xxx.com.br,192.168.xxx.xxx',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'http://www.xxx.com.br/files/resources/_img/super/logo.gif',
    'custom_login_text' => 'Aviso,  O uso deste sistema Ã© restrito somente a usuÃ¡rios autorizados. O acesso ou uso nÃ£o autorizado deste sistema acarretarÃ¡ em processos criminais.',
    'default_language' => 'portuguese_br',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1501036583',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'xxx.xxx.com.br',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => 'none',
    'email_server_url' => 'https://teampass.xxx.com.br',
    'email_from' => 'teampass@xxx.com.br',
    'email_from_name' => 'Teampass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '1',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'enable_attachment_encryption' => '1',

### Client configuration
**Browser: Version 60.0.3112.101 64 bits

**Operating system: WIndows 10 X64

### Logs

This is the last error, but it does not show me one at the same time I execute the procedure ..

[Tue Aug 29 14:20:58.987943 2017] [:error] [pid 12045] [client 10.55.3.53:16475] PHP Notice:  Undefined index: login in /var/www/html/teampass/sources/core.php on line 185, referer: https://teampass.xxx.com.br/teampass/index.php
[Tue Aug 29 14:26:42.584554 2017] [:error] [pid 11951] [client 10.55.3.53:16669] PHP Notice:  Undefined index: login in /var/www/html/teampass/sources/core.php on line 185, referer: https://teampass.xxx.com.br/teampass/index.php
[Tue Aug 29 14:31:50.159867 2017] [:error] [pid 12045] [client 10.55.3.50:52254] PHP Notice:  Undefined index: login in /var/www/html/teampass/sources/core.php on line 185, referer: https://teampass.xxx.com.br/teampass/logout.php
[Tue Aug 29 14:40:26.040533 2017] [:error] [pid 950] [client 10.55.3.53:17084] PHP Notice:  Undefined index: file_is_now_ready in /var/www/html/teampass/admin.settings.load.php on line 337, referer: https://teampass.xxx.com.br/teampass/index.php?page=manage_main
[Tue Aug 29 14:51:19.516257 2017] [:error] [pid 5579] [client 10.55.3.53:17445] PHP Notice:  Undefined index: file_is_now_ready in /var/www/html/teampass/admin.settings.load.php on line 337, referer: https://teampass.xxx.com.br/teampass/index.php?page=manage_main

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

GET http://teampass.xxx.com.br/teampass/profile.p...XiW7eephei6the5ahshyeiyahc3saiCh6dei4aibiemos6ms (Ball with X)

**Comment by nilsteampassnet** [comment]
I believe it has something to do with the language selection.
Can you try to use English and perform the same thing you did?

**Comment by pedrodaltoe1** [comment]
Hello, 

Thank you a lot about your return, i changed on mysql by phpmyadmin my language (changed to 0 like admin user), and I also changed in "Default user interface language".. Dont works.. I see the same error :(
I cant see My profile With my user or admin user, same error.

**Comment by Guirlande** [comment]
Can you try to capture traffic between the client and the server using wireshark as example, reproduce the issue and check if in a response from the server you see a "Hacking attempt..." entry. 
It would be the CSRF protection that's blocking you, I had this kind of issues before.
Additionnally, do you use multiple url to access the web server, through the use of virtual hosts ?

**Comment by roru69** [comment]
Same problem here..

Debian Jessie, Mariadb, Php 7.0.x

commit 775e691

Fresh install.

After enabeling LDAP and enter the required information the first thing i notice when i try to test te configuation is when i click on the gears the result is "no options" instead of the expected "Succes" or something.

When I login with an Active Directory User, the system says that the user is created and after 3 seconds the screen refreshes and i can login with the AD user.

Then when i go to "My Profile" and try to change the language or load strategy, i get i big red sign saying. "You are not allowed to see this page". When i try again i get "Hacking attempt..."

Kind regards,

Roru69

**Comment by pedrodaltoe1** [comment]
Hello, 

I tried everything, but only what really worked was reinstall everything and not change the language.

**Comment by miathos** [comment]
Debian Strech / 5.5.5-10.1.26-MariaDB-0+deb9u1 / PHP 7.0

If I go to the profile page with any user, the "Your Personal Information" window pops up, with the "Please wait!" text and the spinning cogwheel. And that all that's happening. If I click on cancel or close the window, it redirects me to a nearly blank page, with only the tiles to log in with the information. And from there on nothing works.

**Comment by Guirlande** [comment]
I see a lot of people having the same issue, I think this is related to CSRFprotection. Do you use multiple domain names ? Do the following value match the url you enter to access the application :
- jsUrl, found in includes/libraries/csrfp/libs/csrfp.config.php. If the value is "https://my.beautiful.password.manager/includes/libraries/csrfp/js/csrfprotector.js, the url which you use to access the web application should be https://my.beautiful.password.manager/index.php. Otherwise, a "Hacking attempt..." will be sent through a POST response by the server and your session will be terminated.

You should really assert that those URL matches, and not think about disabling the CSRF protection.

How are you accessing the application ? Through domain name or direct IP ?
