### ISSUE TITLE
Export to CVS --> empty file (0 kb)

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#1888]
Hello.

My export to CVS not working :( The file is empty.
There are no errors at httpd SSL errors log.

While export to PDF just works fine.

Server configuration
Operating system:
CentOS 7.3

Web server:
Server version: Apache/2.4.6 (CentOS)

Database:
mysql Ver 15.1 Distrib 10.2.8-MariaDB, for Linux (x86_64) using readline 5.1

PHP version:
PHP 7.1.8 (cli) (built: Aug 2 2017 12:13:05) ( NTS )

Teampass version:
2.1.27.7

Client configuration

Browser:
Chrome, Opera

Operating system:
Windows 10

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Indeed you found a bug. The fix is committed into `development branch`.
You may want to correct immediately by applying the next patch.

Open file `/sources/export.queries.php`
Replace the next part of the code
```
            //save the file
            $csv_file = '/print_out_csv_'.time().'_'.generateKey().'.csv';
            $outstream = fopen($SETTINGS['path_to_files_folder'].$csv_file, "w");

            function outPutCsv(&$vals, $outstream)
            {
                fputcsv($outstream, $vals, ";"); // add parameters if you want
            }

            array_walk($full_listing, "outPutCsv", $outstream);
            fclose($outstream);
```
by
```
            // Save the file
            $csv_file = '/print_out_csv_'.time().'_'.generateKey().'.csv';
            $outstream = fopen($SETTINGS['path_to_files_folder'].$csv_file, "w");

            // Loop on Results, decode to UTF8 and write in CSV file
            foreach ($full_listing as $value) {
                $value = array_map("utf8_decode", $value);
                fputcsv($outstream, $value, ";");
            }

            // Close and display
            fclose($outstream);
```

**Comment by KB7777** [comment]
After aplying the patch there is an error at web browser:
The requested URL /files/print_out_csv_1504166790_93f49bfdcfe7d81.csv was not found on this server.

**Comment by nilsteampassnet** [comment]
After some new tests, it is working on m environment.

So I believe something either is wrong on your environment (rights on folder) or you missed something when applying the patch.
As you can see the patch is very basic and doesn't change a lot from previous code. So if the file isn't created, perhaps do you have some other entries inside the logs?

**Comment by KB7777** [comment]
But it didn't work :(

systemctl restart httpd.service
drwxrwxrwx  2 apache apache   4096 Aug 31 10:50 files
-rw-r--r-- 1 apache apache 43192 Sep  1 07:19 /var/www/html/teampass/sources/export.queries.php


```
                    $id_managed = $record['id'];
                }
            }
        }
 // Save the file
            $csv_file = '/print_out_csv_'.time().'_'.generateKey().'.csv';
            $outstream = fopen($SETTINGS['path_to_files_folder'].$csv_file, "w");

            // Loop on Results, decode to UTF8 and write in CSV file
            foreach ($full_listing as $value) {
                $value = array_map("utf8_decode", $value);
                fputcsv($outstream, $value, ";");
            }

            // Close and display
            fclose($outstream);

```

access log:

10.151.40.57 - - [01/Sep/2017:07:20:12 +0200] "GET /index.php HTTP/1.1" 200 9270
10.151.40.57 - - [01/Sep/2017:07:20:12 +0200] "GET /index.php HTTP/1.1" 200 50997
10.151.40.57 - - [01/Sep/2017:07:20:13 +0200] "GET /favicon.ico HTTP/1.1" 200 99678
10.151.40.57 - - [01/Sep/2017:07:20:15 +0200] "GET /index.php HTTP/1.1" 200 9270
10.151.40.57 - - [01/Sep/2017:07:20:15 +0200] "GET /includes/images/canevas/logo.png HTTP/1.1" 200 4715
10.151.40.57 - - [01/Sep/2017:07:20:15 +0200] "GET /includes/libraries/csrfp/js/csrfprotector.js HTTP/1.1" 200 11589
10.151.40.57 - - [01/Sep/2017:07:20:15 +0200] "GET /index.php HTTP/1.1" 200 50997
10.151.40.57 - - [01/Sep/2017:07:20:15 +0200] "GET /favicon.ico HTTP/1.1" 200 99678
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "POST /sources/identify.php HTTP/1.1" 200 100
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /index.php?page=items HTTP/1.1" 200 267417
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/jstree/jstree.min.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/jstree/themes/default/style.css HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/jstree/jquery.cookie.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/multiselect/jquery.multiselect.css HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/bgiframe/jquery.bgiframe.min.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/multiselect/jquery.multiselect.filter.css HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/css/items.css HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/ckeditor/ckeditor.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/ckeditor/adapters/jquery.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/multiselect/jquery.multiselect.min.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/multiselect/jquery.multiselect.filter.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/tinysort/jquery.tinysort.min.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/js/clipboard/clipboard.min.js HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/images/photo.jpg HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/images/canevas/tree_lock.png HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/images/canevas/fond_items_tree.png HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:21 +0200] "GET /includes/images/canevas/lock_open.png HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "GET /includes/js/jstree/themes/default/throbber.gif HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "GET /includes/js/jstree/themes/default/32px.png HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "GET /sources/tree.php HTTP/1.1" 200 820
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 1512
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 14212
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "GET /includes/images/canevas/fond_item_li.png HTTP/1.1" 304 -
10.151.40.57 - - [01/Sep/2017:07:20:22 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 1312
10.151.40.57 - - [01/Sep/2017:07:20:24 +0200] "GET /items.export.php?key=Kie7zoj4dah0iegh9ienieKeel1ow4zeipheingae2EiPh3ohR HTTP/1.1" 200 6321
10.151.40.57 - - [01/Sep/2017:07:20:25 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 62
10.151.40.57 - - [01/Sep/2017:07:20:28 +0200] "POST /sources/export.queries.php HTTP/1.1" 200 142
10.151.40.57 - - [01/Sep/2017:07:20:30 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 -
10.151.40.57 - - [01/Sep/2017:07:20:30 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 34
10.151.40.57 - - [01/Sep/2017:07:20:32 +0200] "GET /files/print_out_csv_1504243228_84b5f30e24659f5.csv HTTP/1.1" 404 248

error log:
[Fri Sep 01 07:20:12.848560 2017] [php7:notice] [pid 25726] [client 10.151.40.57:8256] PHP Notice:  Undefined index: login in /var/www/html/teampass/sources/core.php on line 185, referer: https://caprica.kruk-inkaso.com.pl/logout.php
[Fri Sep 01 07:20:12.993306 2017] [php7:notice] [pid 25726] [client 10.151.40.57:8256] PHP Notice:  Array to string conversion in /var/www/html/teampass/sources/core.php on line 290, referer: https://caprica.domain.pl/index.php
[Fri Sep 01 07:20:15.507460 2017] [php7:notice] [pid 25726] [client 10.151.40.57:8256] PHP Notice:  Undefined index: login in /var/www/html/teampass/sources/core.php on line 185, referer: https://caprica.domain.pl/index.php
[Fri Sep 01 07:20:15.628046 2017] [php7:notice] [pid 25726] [client 10.151.40.57:8256] PHP Notice:  Array to string conversion in /var/www/html/teampass/sources/core.php on line 290, referer: https://caprica.domain.pl/index.php
[Fri Sep 01 07:20:21.621495 2017] [php7:notice] [pid 25725] [client 10.151.40.57:8255] PHP Notice:  Array to string conversion in /var/www/html/teampass/sources/core.php on line 290, referer: https://caprica.domain.pl/index.php

And the result is:
The requested URL /files/print_out_csv_1504243228_84b5f30e24659f5.csv was not found on this server.

When I get back to the previuos export.queries.php the file was downloded but is empty as i describe at first post :(

**Comment by nilsteampassnet** [comment]
Sorry, my fault ... in 2.1.27.7, the $SETTINGS variable is not yet deployed.
So in your current code, change
`$outstream = fopen($SETTINGS['path_to_files_folder'].$csv_file, "w");`
to
`$outstream = fopen($_SESSION['settings']['path_to_files_folder'].$csv_file, "w");`

It should then work.

**Comment by KB7777** [comment]
Works fine! Thnx :)
