### ISSUE TITLE
Multiple LDAP Server is not working

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1889]
### Steps to reproduce
1. Set up multiple LDAP Servers (defined in Teampass at LDAP 'domain controller' and separated with comma)
2. Log in with valid User to dc1 (account suffix, base dn etc. is set up to dc1 ) --> Works!
3. Log in with another valid User to dc2 --> Doesn't work!
4. If i change the account suffix, base dn etc. to dc2 the User from dc2 is able to login but not the user from dc1. (So both domains are working)

LDAP debug file:
[LDAP_debug_dc1.txt](https://github.com/nilsteampassnet/TeamPass/files/1263089/LDAP_debug_dc1.txt)
[LDAP_debug_dc2.txt](https://github.com/nilsteampassnet/TeamPass/files/1263090/LDAP_debug_dc2.txt)

This settings worked at version 2.1.27.4

If I test the configuration within Teampass web I get this:
![grafik](https://user-images.githubusercontent.com/27355139/29866739-9f2d3c3e-8d79-11e7-802c-4b6566da1c1f.png)

### Expected behaviour
Log in sould work

### Actual behaviour
Log in does not work

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 
2.1.27.7

**Teampass configuration file:**
[Teampass_config.txt](https://github.com/nilsteampassnet/TeamPass/files/1262933/Teampass_config.txt)

**Updated from an older Teampass or fresh install:**
Updated

**Comment by nilsteampassnet** [comment]
Took time to watch this ticket.
I don't understand why it doesn't work.
Code review shows nothing wrong.
It is I think more related to adldap library that has been updated in 2.1.27.7.
But the calls are still the same as with older version.

So it requires more time to investigate.

**Comment by benjamin2501** [comment]
@nilsteampassnet: Problem is still in 2.1.27.8

I wrote a "wrong" Config above the right Config is:

`- LDAP server Type: Windows / Active Directory`
`- LDAP account Suffix: @my-domain.de`
`- LDAP base DN: DC=my-domain,DC=de`
`- LDAP domain controllers(s): dc1.my-domain.de,dc1.another-domain.local`
`- LDAP port 636`
`- Use LDAP SSL: NO`
`- Use LDAP TLS: YES`
`- Teampass local users only: YES`

**Login examples:**
_user.name_
_passw0rd_
--> Works!

_another-domain.local\user.name2_
_passw00rd_
--> Doesn't work! 

I hope you can understand what I'm doing here.

Besides that i got a _no options_ message if I try "_Test current configuration_" at Teampass LDAP config
![grafik](https://user-images.githubusercontent.com/27355139/30739072-6bc0907e-9f8c-11e7-8bd1-012778be1f56.png)
