### ISSUE TITLE
access rights in manage roles

### ISSUE THREAD

**Issue by jronzon** [nilsteampassnet/TeamPass#1890]
### Steps to reproduce
1. select foler with right access and connot delete items and cannot edit items for the roles
2. test edit items in the same foler --> authorized
3. test delete items in the same foler --> authorized

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
REDHAT EL7
**Web server:**
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Aug  3 2016 08:33:27
**Database:**
 mysqld (mysqld 10.1.26-MariaDB) 
**PHP version:**
PHP 7.0.16 (cli) (built: Feb 14 2017 17:22:12) ( NTS )
**Teampass version:** 
2.1.27.7 ( git clone today 01/09/2017)
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
Update 2.1.27.4
### Client configuration
**Browser:**
firefox
**Operating system:**
windows 10 and  8.1
#### Web server error log
```no error
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Absolutely ... it is fixed in latest commit.
Notice that the edition would be blocked when user would have stored the changes.
