### ISSUE TITLE
Upgrade error - PHP Parse error:  syntax error, unexpected ')', expecting '('

### ISSUE THREAD

**Issue by wirerydr** [nilsteampassnet/TeamPass#1892]
_**NOTE:**_ This issue may appear similiar to #1856, and in-fact it is the same problem.  That other issue was specific to upgrading from one development commit to another.  Since it didn't involve any released versions and therefore wouldn't impact many people, I closed it.

This report is more general - it is an attempt to upgrade from (what I think is) the latest released version (master commit 11fb31e) to any development commit after cdf1327.  I'm worried this may illustrate what might happen when the next version of TeamPass is released and everyone tries to upgrade to it.

### Steps to reproduce
1. Complete a fresh install of the most recent master commit (11fb31e, on 2017-Jul-27), either from the release ZIP file or from a cloned repo (I tried both).
2. Log into the fresh install as administrator (after manually deleting _install/_) to verify the install was good.
3. Start an upgrade to any development commit after cdf1327.  I have tried several commits, including 6bb32ae, the latest as of 2017-Sep-02.
4. Continue the upgrade until **_Step 5 - Miscellaneous_** is reached.
5. Provide the current SK directory, and click <**_LAUNCH_**>

### Expected behaviour
The step should complete successfully, after-which it should become possible to click <**_NEXT_**> to move to the next step.

### Actual behaviour
As shown in the screenshot below, **Please wait...** appears with a spinning icon which then halts.  Repeatedly clicking <**_LAUNCH_**> repeats these results. The following error appears in the Apache log each time:
```
[Sun Sep 03 01:28:34.000420 2017] [php7:notice] [pid 6878] [client 192.168.240.120:53004] PHP Parse error:  syntax error, unexpected ')', expecting '(' in /opt/teampass/teampass__TEST__20170902-6bb32ae/includes/config/tp.config.php on line 4, referer: https://www.example.com/tptest/install/upgrade.php
```
### Failure Screenshot
![image](https://user-images.githubusercontent.com/4572687/30000937-2f11ec86-904b-11e7-9767-f2042ba13fbb.png)

### DB Table _misc
I think you mentioned earlier that this problem might occur if the **_misc_** table had been emptied.  After observing the failure my **_misc_** table contains 119 rows.  Here's the first page:
![image](https://user-images.githubusercontent.com/4572687/30000957-2d39007e-904c-11e7-9d9e-235a74a5e2e2.png)

### Server configuration
**Operating system**: Fedora 26 (x86_64)

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.1

**Teampass version:** master commit 11fb31e, upgrading to anything after cdf1327.

**Teampass configuration file:**
```
<?php
global $SETTINGS;
$SETTINGS = array
);
```

**Updated from an older Teampass or fresh install:** Updated

**Comment by wirerydr** [comment]
Tested this against latest development commit a2214c1.  Was successfully able to get past the _**Step 5 - Miscellaneous**_ screen, and complete the installation.  Successfully logged into Teampass (with one caveat - see **NOTE** below) with administrator credentials.

I am unsure if you are finished with your code-review regarding this issue, so I am leaving it open for your final decision.

### NOTE
The _**install/**_ directory was not automatically removed by the upgrade process.  My first attempt to log in after completing the upgrade failed with a displayed warning about this.  After I manually deleted it, I was able to successfully log in.  If you want, let me know and I will raise and document a new issue about this.

**Comment by nilsteampassnet** [comment]
Thank you @wirerydr 

I'm still working on it and need to perform some more tests and code review before closing.
I didn't notice that the install folder was not deleted on first home page opening.

**Comment by nilsteampassnet** [comment]
I think this point is now closed.
