### ISSUE TITLE
teampass on ubuntu ladp authentication

### ISSUE THREAD

**Issue by abu1993** [nilsteampassnet/TeamPass#1895]
### Steps to reproduce
1. installed teampass 2.1.27
2. trying to bind with existing windows AD
3.

### Expected behaviour
Tell us what should happen
should succesfully bind 
### Actual behaviour
Tell us what happens instead
the server 
Get all ldap params: 
- base_dn : DC=dl,DC=example,DC=co,DC=za
- account_suffix : @dl.examble.co.za
- domain_controllers : 0
- port : 389
- use_ssl : 0
- use_tls : 0
*********
Create new adldap object : Success

After authenticate : Can't contact LDAP server

ldap status : Not possible to get connected with this user
### Server configuration
**Operating system**:
ubuntu 16.04 
**Web server:**
linux
**Database:**

**PHP version:**
php -v 7.0.22 
**Teampass version:** 
 teampass 2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
chrome
**Operating system:**
linx 17
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Config file please

**Comment by nicoladegara** [comment]
I have the same issue on a fresh installation on Centos7

**Comment by nilsteampassnet** [comment]
Could you share the config file?
Do you use the development branch or what release?

**Comment by abu1993** [comment]
Hi,


Its the latest realease

kindest regards
Abulele Mgxabayi

**Comment by nilsteampassnet** [comment]
Does this mean that you use `development` branch?
Or did you download from https://github.com/nilsteampassnet/TeamPass/releases

**Comment by abu1993** [comment]
http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/

i followed that link

**Comment by abu1993** [comment]
@nilsteampassnet 

How do i check the config file , i am new in this industry

**Comment by abu1993** [comment]
@nilsteampassnet 
this is how i installed it
 root@demohost:/var/www/html# wget -q https://github.com/nilsteampassnet/TeamPass/archive/master.zip
root@demohost:/var/www/html# unzip master.zip

**Comment by nilsteampassnet** [comment]
If you are started using Teampass with release 2.1.27, I suggest you to install the development branch.

https://github.com/nilsteampassnet/TeamPass/archive/development.zip

**Comment by abu1993** [comment]
@nilsteampassnet 

i am  no longer get the below error i just get no options, does this mean its working because i am now trying to login using a different user but takes forever to load 
{ base_dn : DC=dl,DC=example,DC=co,DC=za
account_suffix : @dl.examble.co.za
domain_controllers : 0
port : 389
use_ssl : 0
use_tls : 0
Create new adldap object : Success

After authenticate : Can't contact LDAP server

ldap status : Not possible to get connected with this user}
