### ISSUE TITLE
LDAP and local accounts

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#1896]
Hello.

My TeamPass is LDAP connected (AD) and logons of AD users works fine.
But I want to add the next local admin account (like an account "admin" is and I can do local login with it). After creating new user (admin_kb7777) I can't login, beacuse there is no such account at my ldap (and I don't want to add it to my AD; it has to be local teampass account).

Is it possible to do?

Regards.

**Comment by nilsteampassnet** [comment]
Currently this case is not taken into account.

It would require some changes by adding on each user account a new field (such as "local user").
This is feasible.

**Comment by KB7777** [comment]
I would be great :)
The scenarios is -- every admin has local account to maintain TeamPass but the users account are from AD. in such case if we loose AD we can login by many local account and we haven't to share local "admin" account :)

**Comment by nilsteampassnet** [comment]
Can you please create your Feature Request at https://teampass.userecho.com/forums/1-feature-requests/

**Comment by KB7777** [comment]
Created :)

**Comment by KB7777** [comment]
@nilsteampassnet 

Don't get it -- http://teampass.userecho.com/forums/1-feature-requests/topics/81-ldap-and-local-accounts/

**Comment by aaronSkar** [comment]
Not sure I understand either.  Maybe he didn't like how it was phrased? Opening a new feature request for this.

https://teampass.userecho.com/forums/1-feature-requests/topics/111-add-option-to-have-local-and-remote-accounts-when-ldap-is-enabled/
