### ISSUE TITLE
Should administrator NOT be able to see any content in the system?

### ISSUE THREAD

**Issue by nneul** [nilsteampassnet/TeamPass#1897]
### Steps to reproduce
1. Set up user in system as non admin
2. Log in
3. See folders
4. Make that user an administrator
5. Log in
6. Don't see folders?

### Expected behaviour

Should an administrator be able to see any folder content? Right now it looks like if you have sys admin perms you cannot see any content. If that's intentional, that's fine - just wasn't clear anywhere.

### Actual behaviour

Lose ability to see folders if user is a system admin.

### Server configuration
**Operating system**: ubuntu amd64

**Web server:** apache

**Database:**

**PHP version:**

**Teampass version:** latest from git

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

**Comment by nilsteampassnet** [comment]
Absolutely normal.
This is done by design to protect the data.
Indeed an administrator could select to see folders he should not have access to.

**Comment by nneul** [comment]
Thank you, that makes perfect sense.

It would save a lot of headache for other users if this were called out in UI somehow -- maybe in the hover text for the administrator toggle.

**Comment by nilsteampassnet** [comment]
Yes, you are right. I could be a plus.
