### ISSUE TITLE
Active Directory authentication not working on fresh installed Cent OS 7 [SOLVED]

### ISSUE THREAD

**Issue by nicoladegara** [nilsteampassnet/TeamPass#1899]
### Steps to reproduce
1. Installation of a new CentOS 7 
2. Follow instruction  from http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/
3. Configure Active Directory connection

### Expected behaviour
The AD authentication should work! 

### Actual behaviour
Create new adldap object : Success
After authenticate : Can't contact LDAP server
ldap status : Not possible to get connected with this user
--> Login credentials do not correspond! <-- 

-------------- files/ldap.debug.txt --------------

Get all ldap params :
base_dn : OU=ACompany,DC=ap,DC=lan
account_suffix : @ap.lan
domain_controllers : ap.lan
port : 389
use_ssl : 0
use_tls : 0
*********
Create new adldap object : Success
After authenticate : Can't contact LDAP server
ldap status :
----------------------------------------------------

### Server configuration
**Operating system**: CENTOS 7

**Web server:** Apache/2.4.6

**Database:**5.5.52-MariaDB

**PHP version:**5.6.31

**Teampass version:** 2.1.27 (https://github.com/nilsteampassnet/TeamPass/archive/2.1.27.7.zip) 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://192.168.0.1/teampass',
    'favicon' => 'http://192.168.0.1/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://192.168.0.1/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://192.168.0.1/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@ap.lan',
    'ldap_domain_dn' => 'OU=ACompany,DC=ap,DC=lan',
    'ldap_domain_controler' => 'ap.lan',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1502614809',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done'

### Client configuration
**Browser:** Any

**Operating system:** Any

#### Web server error log
```
[Tue Sep 12 11:21:45.787258 2017] [:error] [pid 21128] [client 1xxxxxxx:52349] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/teampass/includes/config/include.php on line 24, referer: http://1xxxxxxxx/teampass/index.php?page=manage_settings

```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Nothing interesting
```

**Comment by nilsteampassnet** [comment]
Can you please make a try using package from "development" branch?

**Comment by nicoladegara** [comment]
Hi, thank you 

I will try!

**Comment by nicoladegara** [comment]
Hi,
   now I've the development branch installed  (https://github.com/nilsteampassnet/TeamPass/archive/development.zip) 

The application proposes the install wizard again. Unfortunately it seems that there are some issue because nothing happens when I try to click on LAUNCH button in "Server checks" module. Also the JS issues in background.

Could you please tell me what kind of trick/shortcut I can use to skip the installation wizard?

Thank you

**Comment by nicoladegara** [comment]
Ok. I think I've found the problem why the button LAUNCH is not working. In JS inclusion yuo have a method called **C**heckPage() but in your code you refer to the method with first letter lowercase (**c**heckPage())

**Comment by nicoladegara** [comment]
On login (.. and after) Keep getting animated gif in frontend 

![image](https://user-images.githubusercontent.com/2182858/30389847-59f697fa-98b4-11e7-8e3a-c151b1e970b0.png)

**Comment by nicoladegara** [comment]
I still have two fields for domain suffix. Is it right? 

![image](https://user-images.githubusercontent.com/2182858/30389946-c211931c-98b4-11e7-9e22-49bdbde9b547.png)

**Comment by nicoladegara** [comment]
If I try to test Active Directory connection i get a 'No Options' message
![image](https://user-images.githubusercontent.com/2182858/30390054-20f02dbc-98b5-11e7-972c-5114f34102a5.png)

**Comment by nilsteampassnet** [comment]
Ok, in the order ;)

1st regarding checkPage, I don't see where in the code there is an issue regarding case letters.
Indeed while doing a global search, I get this.
![image](https://user-images.githubusercontent.com/1197546/30392095-0890e8cc-98bc-11e7-8b3e-07d635322d98.png)
As you can see, there is a consistency in the file naming.
Perhaps have you not cleaned up the folders before installing "development" branch.

2d point regarding the cog always visible. It is an issue regarding the cache of our web-browser. You should clear it as the strategy regarding hiding it has change. So please clear the cache.

3rd point regarding the duplication of ldap suffix field, you are right, I need to fix this. But this has no impact on LDAP settings.

4th point regarding the "no options" message, what are the ldap settings you defined?
Can you share screenshot?

**Comment by nicoladegara** [comment]
Hi. Now I cannot show you the "CheckPage" underscore in the install.php/install.js because there is no more install fodder on Development branch in Git.

2d. I will check. Even if the icon disappear if any in between ajaxRequest.

3d. ok

4th I've added BaseDN, port, suffix, test username and test password ..

Anyway it is still not working :-(

**Comment by nicoladegara** [comment]
I can confirm you that the loading animated icon disappeared after cleaning the browser cache

**Comment by nicoladegara** [comment]
I've found the login problem with AD through development Branch:

You have a blankspace in the ldap_mode check 

![image](https://user-images.githubusercontent.com/2182858/30513711-429d604c-9b08-11e7-99d3-9ffcc2b8a35f.png)

**Comment by nicoladegara** [comment]
Now AD works! 

I've tried to add a new user and to be able to add a new one (after having created a couple of Roles and nothing more ) I've to apply the following fix to JS

if string !== undefined

![image](https://user-images.githubusercontent.com/2182858/30513973-3bfac0a4-9b0d-11e7-87d7-56b926de7d30.png)

![image](https://user-images.githubusercontent.com/2182858/30513996-a099a732-9b0d-11e7-9956-3b3ba18e417c.png)

**Comment by nilsteampassnet** [comment]
Thank you for sharing the fix.
