### ISSUE TITLE
Forgot your password --> Page reload automatic

### ISSUE THREAD

**Issue by jronzon** [nilsteampassnet/TeamPass#1900]
SORRY for my bad english !!!
### Steps to reproduce
1. Clic to "Forgot your password?"
2. Open the link in email received with Firefox 55.0.2 (ESR) (Firefox is already open)
3. The page is reload automatic to login page and the email (STEP 2) not reveived.
4. If test with Firefox Closed, it's OK. I can clic to "Send my new password" and email STEP 2 is reveived.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
REDHAT EL7
**Web server:**
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built: Aug 3 2016 08:33:27
**Database:**
mysqld (mysqld 10.1.26-MariaDB)
**PHP version:**
PHP 7.0.16 (cli) (built: Feb 14 2017 17:22:12) ( NTS )
**Teampass version:** 
2.1.27.7 ( git clone 01/09/2017)
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
firefox
**Operating system:**
windows 10 and 8.1
#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Found a fix

**Comment by jronzon** [comment]
It's OK after change.
