### ISSUE TITLE
Rights Problem when user change roles.

### ISSUE THREAD

**Issue by jronzon** [nilsteampassnet/TeamPass#1901]
### Steps to reproduce
1. An user at role A 
2. the user create the sub-folder "Test" with right to role A
3. The role B not have access to sub-folder "Test"
3. The manager change role for the user to role B
4. The sub-folder "Test" is accessible to role A and B

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
REDHAT EL7
**Web server:**
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built: Aug 3 2016 08:33:27
**Database:**
mysqld (mysqld 10.1.26-MariaDB)
**PHP version:**
PHP 7.0.16 (cli) (built: Feb 14 2017 17:22:12) ( NTS )
**Teampass version:** 
2.1.27.7 ( git clone 01/09/2017)
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
firefox ESX 55.0.2
**Operating system:**
windows 10 and 8.1

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
I could not reproduce following your instructions.

Can you confirm that following those steps leads to this issue?

**Comment by jronzon** [comment]
I have this problem only if the user does not disconnect of teampass.

**Comment by nilsteampassnet** [comment]
Yes this makes sense as the privileges are stored in session.

Once a manager or admin has changed such rights, it is recommended to close the session of the impacted users.
![image](https://user-images.githubusercontent.com/1197546/30643298-9a600556-9e0e-11e7-9c2c-8330897a7c48.png)
