### ISSUE TITLE
SSH Password Change does not work

### ISSUE THREAD

**Issue by la10859** [nilsteampassnet/TeamPass#1903]
### Steps to reproduce
1. TeamPass fresh install
2. Add new "linus server" item
3. Try to use the "update server password function"

### Expected behaviour
Password should be changed on the linux server and updated on the TeamPass item profile.

### Actual behaviour
Password change fails with this error:

```
Server reply: 
New password: Retype new password: Sorry, passwords do not match.
New password: Retype new password: Password change aborted.
New password: Password change aborted.
Changing password for user root.
passwd: Have exhausted maximum number of retries for service

 The server replied with an error. Check the error response and try again.

```

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611 (Core) - 3.10.0-514.26.2.el7.x86_64

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2

**Database:**
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.2.0RC2 (cli) (built: Sep 13 2017 08:31:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Firefox 55.0.3 (64-bit)

**Operating system:**
Windows 10

#### Web server error log
192.168.56.1 - - [14/Sep/2017:14:46:24 -0300] "POST /teampass/sources/utils.queries.php HTTP/1.1" 200 900 "http://apache/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0"

#### OS Log
==> messages <==
Sep 14 14:46:24 apache systemd: Started Session 53 of user root.
Sep 14 14:46:24 apache systemd-logind: New session 53 of user root.
Sep 14 14:46:24 apache systemd: Starting Session 53 of user root.

==> secure <==
Sep 14 14:46:24 apache sshd[18294]: pam_unix(sshd:session): session opened for user root by (uid=0)
Sep 14 14:46:24 apache passwd: pam_pwquality(passwd:chauthtok): pam_get_authtok_verify returned error: Failed preliminary check by password service
Sep 14 14:46:24 apache passwd: pam_pwquality(passwd:chauthtok): pam_get_authtok_verify returned error: Authentication token manipulation error
Sep 14 14:46:24 apache passwd: pam_pwquality(passwd:chauthtok): pam_get_authtok_noverify returned error: Authentication token manipulation error
Sep 14 14:46:26 apache sshd[18294]: Received disconnect from 192.168.56.104: 11:
Sep 14 14:46:26 apache sshd[18294]: pam_unix(sshd:session): session closed for user root

==> messages <==
Sep 14 14:46:26 apache systemd-logind: Removed session 53.

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Thank you for reporting this.
I've corrected it.
