### ISSUE TITLE
Authenticate a user via AD group

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1904]
Is it possible to authenticate a user by his group ownership?
It should work like this:
_UserA_ is inside of group _"admin"_
_UserB_ is inside of group _"users"_
So that _UserA_ is able to login but _UserB_ can't login.

Both users were created localy by Teampass Admin. (Because of security reason #1865)
The backstory is: we like to see and manage the users which can use Teampass

P.S.: Concerning the next update, is there any release date?
### Server configuration
**Teampass version:** 
2.1.27.7

**Comment by nilsteampassnet** [comment]
I'm not sure to understand.
You want to enable/disable users belonging to an AD group, that's it?

**Comment by benjamin2501** [comment]
Exactly that's what I want to do
P.S.: We got a Windows AD

**Comment by cdn123** [comment]
Would be also interested for us

**Comment by dunz0r** [comment]
I suggest not setting a default-role for the users instead. This is how I've solved it, it's an extra manual step, but it works.
As in if a user logs in, they can't see anything at all until I set a role for them, this is handy when people from different departments that might not be in the correct AD-group needs access to passwords for another group.

**Comment by nilsteampassnet** [comment]
I've committed an improvement regarding this.
I hope I have correctly understood.

In Windows AD context, a new criteria is added called "LDAP allowed user group".
If used, once the user is found in the AD, his group will be checked against the group name written in this field. If they don't correspond, the user will not be allowed to connect to Teampass.
If they match, connection is granted.

**Comment by KB7777** [comment]
Hello.

"LDAP allowed user group" -- is it just the name of group, ie. "teampass_users" or is it have to be "Distinguished Name" string?

**Comment by nilsteampassnet** [comment]
You can refer to http://teampass.readthedocs.io/en/latest/install/ldap/

It is the group name defined in LDAP
