### ISSUE TITLE
"My profile" doesn't work on HTTPs and forces logout

### ISSUE THREAD

**Issue by guikolt** [nilsteampassnet/TeamPass#1905]
### Steps to reproduce
1. Login via https
2. Click on User account -> My profile
3. Please wait shows up forever and if you click anywhere it will log you out

### Expected behaviour
List my profile and let me change stuff

### Actual behaviour
Hangs and forces logout

### Server configuration
**Operating system**: CentOS 7.4

**Web server:** Apache 2.4.25

**Database:**  Percona Server 5.7.19-17

**PHP version:** 5.6.25

**Teampass version:** 2.1.27.7

**Teampass configuration file:** https://pastebin.ca/3874102

#### Web server error log
There are no errors being shown in error_log while clicking on My profile.

This bug doesn't appear while navigating without https.
I am using HTTPS with SSLOptions +ExportCertData

**Comment by gregulator85** [comment]
I also am having this issue, only on HTTPS.  It looks like the profile is attempting to load from http page while logged into https.
![image](https://user-images.githubusercontent.com/7906169/33504070-a6047560-d6ab-11e7-8da1-05a0088cfedd.png)

**Comment by nilsteampassnet** [comment]
Take a look to this page http://teampass.readthedocs.io/en/latest/errors/

Ensure all paths are consistent.

**Comment by gregulator85** [comment]
Perfect, this resolved the issue of https.

**Comment by nilsteampassnet** [comment]
Great.
