### ISSUE TITLE
install.php and supporting files missing from latest development branch commits

### ISSUE THREAD

**Issue by mikerwilson** [nilsteampassnet/TeamPass#1906]
### Steps to reproduce
1. Clone repo
2. cd <target dir>/install
3. ls -la

### Expected behaviour
Should see install.php and others in the resultant directory listing.

### Actual behaviour
Files are missing.

### Server configuration
Ubuntu 16.04 LTS

apache2 2.4.18-2ubuntu3.4

mysql 5.7.19-0ubuntu0.16.04.1

php 7.0.22-0ubuntu0.16.04.1

teampass development branch commit: 4f298b280efcb18fcff7e7fd503a1a1a09b5aed0
n/a

Fresh install
PLEASE attach to this message the file `/includes/config/tp.config.php`.
n/a

### Client configuration
n/a

#### Web server error log
```
n/a
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
n/a
```

**Comment by nilsteampassnet** [comment]
It is fixed.
I did a mistake in the latest commits
