### ISSUE TITLE
Backup still requires Encryption Key, even when no key is used

### ISSUE THREAD

**Issue by newburns** [nilsteampassnet/TeamPass#1907]
### Steps to reproduce
1. Create a backup from Teampass version 2.1.26. It will create a .sql file. Do not set an encryption key
2. Setup a fresh Teampass 2.1.27. Login while in Maintenance Mode is enabled and select restore under settings
3. A box requesting the encryption key pops up. No encryption key was set. Cannot press ok, only cancel.

### Expected behaviour
Tell us what should happen

No encryption key was set, so no encryption key should be needed to restore.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
I didn't test this. I will.

Just one thing, you should not restore a backup performed on 2.1.26 into a 2.1.27 instance.
Everything will be messed up as the data is not compliant.
