### ISSUE TITLE
Roles Management - Problem with acess rights "Edit" "Delete"

### ISSUE THREAD

**Issue by stephan115** [nilsteampassnet/TeamPass#1909]
### Steps to reproduce
1. With "ADMIN" user "GOD ACCOUNT"
2. Acess "Roles Management" 
3. Click on any user folder acess rights
4. Select "Write" and "Cannot Delete Items"
5. Click Save

### Expected behaviour
The user will be able to "Create", "Read" and "Edit" Items on the folder that the acess rights was set, only the "Delete" option will be not allowed to use.

### Actual behaviour
The user can "Create" and "Read" Items on the folder that the acess rights was set, but the "Delete" and "Edit" option is not allowed to use. The system is blocking "Delete Item" and "Edit Item" options.

### Server configuration
**Operating system**:
DEBIAN 7 32Bits
**Web server:**
Apache/2.2.22 (Debian)
**Database:**
MySQL: mysqlnd 5.0.11-dev - 20120503
**PHP version:**
PHP Version 5.5.38-1~dotdeb+7.1
**Teampass version:** 
TeamPass 2.1.27
**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1317982/tp.config.zip)

### Client configuration
**Browser:**
Mozilla Firefox 55
**Operating system:**
Windows 7 64Bits

**Comment by nilsteampassnet** [comment]
Corrected.

Thank you for reporting.

**Comment by KneeGrowTest01** [comment]
I still encounter this issue. Kindly help me on this please. Thanks.
