### ISSUE TITLE
Admin user not created on new installation

### ISSUE THREAD

**Issue by guikolt** [nilsteampassnet/TeamPass#1910]
### Steps to reproduce
1. git clone https://github.com/nilsteampassnet/TeamPass.git .
2. create database (create database teampass character set utf8 collate utf8_bin; grant all privileges on teampass.* to teampass_admin@localhost identified by 'test1234-';)
3. install teampass
4. teampass page says password do not match
5. check table teampass_users and there is nothing there:

mysql> select * from teampass_users;
Empty set (0.01 sec)

### Expected behaviour
admin user should be created during installation

### Actual behaviour
no user is created at all

### Server configuration
**Operating system**: CentOS 7.4

**Web server:** Apache 2.4.25

**Database:** Percona-Server 5.7.19-17

**PHP version:** PHP 5.6.25

**Teampass version:** current from git

**Comment by nilsteampassnet** [comment]
This is a known bug currently fixed in development branch.

Thank you
