### ISSUE TITLE
After new Install Problem

### ISSUE THREAD

**Issue by elvesibeiro** [nilsteampassnet/TeamPass#1911]
Hi guys I have the following problem
**[Wed Sep 20 13:29:07.000851 2017] [:error] [pid 23811] [client 172.30.200.105:57593] PHP Warning: require_once(./sources/SecureHandler.php): failed to open stream: No such file or directory in /var/www/html/teampass/error.php on line 16, referer: http://teampass.local.com/index.php?page=manage_main
[Wed Sep 20 13:29:07.000904 2017] [:error] [pid 23811] [client 172.30.200.105:57593] PHP Fatal error: require_once(): Failed opening required './sources/SecureHandler.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/teampass/error.php on line 16, referer: http://teampass.local.com/index.php?page=manage_main
**

I also have tried to use this command ( UPDATE teampass_users SET last_pw_change = '1499336944' WHERE login = 'admin';) but didn't works.

I have tried to use a lot of other versions, but each version I have had the different problems. Now, I am using the https://github.com/nilsteampassnet/TeamPass/archive/master.zip in my installation.

**Comment by nilsteampassnet** [comment]
New release delivered today.

If it is new install, then remove and restart with it.

**Comment by elvesibeiro** [comment]
Hi, I installed the last version today and now I can't login on teampass.

I did a test using the post on postman and I am receiving 403 Access Forbidden by CSRFProtector!

**Comment by elvesibeiro** [comment]
Hi, I have resolved my problem only fix my date using ntpd.

Thanks.
