### ISSUE TITLE
Admin account not found or matching?

### ISSUE THREAD

**Issue by hayd555** [nilsteampassnet/TeamPass#1913]
### Steps to reproduce
1.Install successfull
2.unable to log in with an admin account
3.teampass_users only displays API and OTV 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 
2.1.27.6
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
What version do you use?

Release 2.1.27.8 just being delivered => https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.8

**Comment by hayd555** [comment]
I just installed version 2.1.27.6, does that have known issues?

**Comment by hayd555** [comment]
Installed the new version working fine although I have a spinning Kog in every menu, is there a way to remove this?

**Comment by nilsteampassnet** [comment]
PLease clear your cache to force css files to be reloaded

**Comment by hayd555** [comment]
Thanks, also sorry to be an issue, when I have created new user accounts and turned off maintenance mode I am still not able to log on?

**Comment by nilsteampassnet** [comment]
Please share information that permits to help.
Screenshot? did you set up Roles? have the new users been associated to at least one? what messages do you get?

**Comment by hayd555** [comment]
I get log on credentials do not correspond message. 

Test user account set up and assigned to two groups 

![capture](https://user-images.githubusercontent.com/32161193/30696397-66e5065c-9ed3-11e7-9b77-cafafb59f780.PNG)

**Comment by hayd555** [comment]
Ah, the reason is perhaps having LDAP enabled. can you not have LDAP enabled and use local accounts?
