### ISSUE TITLE
Cannot Edit or Delete items in the Personal folder

### ISSUE THREAD

**Issue by TriEs752** [nilsteampassnet/TeamPass#1915]
Steps to reproduce

Login
Set personal salt key
Add new password in the Personal folder = OK
Edit or. Delete a entry in the Personal folder can not use (Not allowed)
Expected behaviour

I can edit or. delete entry in the Personal folder.

Actual behaviour

I can not edit or. delete entry in the Personal folder.
image

Server configuration

Operating system: CentOS Linux release 7.3.1611

Web server: httpd 2.4.6

Database: mariadb 5.5.52

PHP version: 5.5.38

Teampass version: 2.1.27.8

Updated from an older Teampass or fresh install: Update from TeamPass-2.1.26

Client configuration

Browser: newest Chrome

Operating system: Windows 7 64Bit

Logs

Web server error log

No errors in the web server error log

**Comment by TriEs752** [comment]
Same problem #1727 but in my case teampass is 2.1.27.8

**Comment by nilsteampassnet** [comment]
Yes I confirm.

I have fixed this.
The Release [2.1.27.8](https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.8) has been updated.
