### ISSUE TITLE
Single quotes in translation cause invalid JS to be generated

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#1916]
### Steps to reproduce
1. Set your language to french
2. Log back in (I think this should take you to the password page with its tree view, but if not then go there)

### Expected behaviour
This should display the usual tree view

### Actual behaviour
The page's structure is displayed (header, background, etc.) but the tree is missing (and this breaks the layout a little but that's really not the point)

### Server configuration
**Operating system**: Debian Jessie 8.8

**Web server:** Nginx (1.6.2-5+deb8u5)

**Database:** MySQL 5.5

**PHP version:**  PHP5 (5.6.30+dfsg-0+deb8u1)

**Teampass version:** 2.1.27

**Teampass configuration file:** I don't understand what's required here and anyway I know the cause of the issue and I'm just filling this to be nice and can guarantee that this has no link whatsoever with the bug I've found but if you really want it just ask and I'll add it

**Updated from an older Teampass or fresh install:** no, installed fresh on a new host

### Client configuration
**Browser:** Epiphany ? User reproduced on something ugly running on a Mac, Safari or Chrome I guess ? This is completely out of the point, you know ?

**Operating system:** Well I'm Debian 9 and he has some kind of MacOS as I said

#### Client
I don't have it right now, but the JS console wails about not knowing what to do with the global keyword `évolution` (and also, it not being properly separated from the previous argument in the function call they're both part of).

### What happens ?

French translation is full of single quotes `'` (U+27). In `items.load.php` there are a bunch of JS lines that follow this regexp : `"('.*<?php echo \$LANG\["`

Ex:
```
                $("#item_extra_info").prepend('<i class="fa fa-lightbulb-o fa-sm mi-yellow tip" title="<?php echo $LANG['item_has_change_proposal'];?>" onclick=""></i>&nbsp;');
                optgroup.attr('label', "<?php echo $LANG['users'];?>");
            optgroup.attr('label', "<?php echo $LANG['roles'];?>");
                    .attr('title','<?php echo $LANG['disable_notify'];?>')
```

What happens in the first line (but could in theory happen on others, and with other languages too, english have simple quotes too, seriously I'm very surprised this hasn't never occurred before) is that the french translation for the `item_has_change_proposal`, containing a simple quote, gets replaced which closes the string opened after `prepend(`, the whole thing looking like :
```
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1321944/tp.config.txt)


$("#item_extra_info").prepend('<i class="fa fa-lightbulb-o fa-sm mi-yellow tip" title="Une proposition d'évolution est disponible pour cet objet" onclick=""></i>&nbsp;');
```

Which is not valid JS (I have to agree with my browser on that).

### Fix suggestions
- use a different character like that weird round single quote ?
- properly escape the simple quotes in all translations expanded everywhere in the source code ?

**Comment by nilsteampassnet** [comment]
What release of 2.1.27 do you use?

**Comment by greygjhart** [comment]
It's the 2.1.27.4. Is the problem already known ? I've searched the other issues, found old ones that sounded a bit similar (like #344 for instance) but didn't have the same impact.

**Comment by nilsteampassnet** [comment]
I see what you mean.

Yes you are right, since some releases I'm trying to fix all those kind of issues.
As an example, in the latest code, you will see that the example you took has been escaped.

`$("#item_extra_info").prepend('<i class="fa fa-lightbulb-o fa-sm mi-yellow tip" title="<?php echo addslashes($LANG['item_has_change_proposal']); ?>" onclick=""></i>&nbsp;');`

So it is on-going.
