### ISSUE TITLE
No login after new install

### ISSUE THREAD

**Issue by dude1756** [nilsteampassnet/TeamPass#1917]
### Steps to reproduce
1. Install teampass
2. Login as 'admin' first time
3.

### Expected behaviour
After a successful installation process, login as admin and set password during installation process should be possible.

### Actual behaviour
Installation process is successful. There is no warning that php extensions are missing or anything else (however an error
[tp.txt](https://github.com/nilsteampassnet/TeamPass/files/1322087/tp.txt)
 in apache logfile). Installation folder is deleted automatically and user 'admin' can be found in the database. However, login is not possible. The first page just shows "Please identify yourself" and the little wheel is turning and turning...

### Server configuration
**Operating system**:

**Web server:**
Apache 2.4

**Database:**
mariadb 5.5.54
**PHP version:**
7.016
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
-.

### Client configuration
**Browser:**
Chrome/ Edge
**Operating system:**
Windows10

#### Web server error log
```
Insert your webserver log here
2017-09-21T18:41:13+02:00 XXSERVER [Thu Sep 21 18:41:13.732535 2017] [core:alert] [pid 30302:tid 139963035244288] [client xxx.xxx.xxx.xxx:xxx] /var/services/web/teampass/sources/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration, referer: http://xxx.xxx.xxx.xxx/teampass/index.php


[tp.txt](https://github.com/nilsteampassnet/TeamPass/files/1322077/tp.txt)

**Comment by nilsteampassnet** [comment]
Clear cache or something like that/

**Comment by dude1756** [comment]
Thx for your quick reply. Unfortunately no effect.
Console in Chrome shows following:

![image](https://user-images.githubusercontent.com/31192919/30712695-25dd95f4-9f0d-11e7-8bd0-de9d14adf0d1.png)

Any other hint?

**Comment by nilsteampassnet** [comment]
You have something wrong on your server.
As you can see, it is an error 500 related to jquery library not defined (1st error).
THis can only be related missing or corrupted files.
I would suggest to redownload the package and overwrite all files.

**Comment by dude1756** [comment]
Complete overwrite and reinstallation does not help. If I use Nginx as Backend instead of Apache 2.4 it works...
