### ISSUE TITLE
Not included in my personal profile

### ISSUE THREAD

**Issue by free-14** [nilsteampassnet/TeamPass#1920]
Does not go into my personal profile. Nowhere.
![personalprofile](https://user-images.githubusercontent.com/28634449/30777024-8716c094-a0ba-11e7-9884-3025f4c77752.jpg)
### Steps to reproduce
1. Upgrade 27.7 to 27.8
2. 
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Ubuntu server 16.04

**Web server:Apache: 2.4

**Database: Mysql 5.6

**PHP version: 7.0

**Teampass version: 27.8 

**Teampass configuration file: 

**Updated from an older Teampass or fresh install: Updated from an older
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: OPera 46

**Operating system: Win10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
Please provide the errors from the apache log?

**Comment by free-14** [comment]
The question is resolved, you can close the question.
