### ISSUE TITLE
Cannot set or change my saltkey (LDAP login)

### ISSUE THREAD

**Issue by cdn123** [nilsteampassnet/TeamPass#1922]
### Steps to reproduce
1. LDAP authentication
2. Reset PSK (no dialog to enter a new salt key)
3. Change salt key requires an old salt key. 0 or nothing will give you an error, that the psk is wrong. 

### Expected behaviour
Change or set my salt key!

### Actual behaviour
Nothing really

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 5.6.30

**Teampass version:** 2.1.27

**Teampass configuration file:**

### Client configuration
**Browser:** FF, Chrome, IE

**Operating system:** Win10

#### Web server error log
```

[Mon Sep 25 11:50:17.797987 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /path/to/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168, referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798076 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: Stack trace:, referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798087 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: #0 /path/to/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', ''), referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798095 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: #1 /path/to/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString(''), referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798103 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: #2 /path/to/teampass/sources/main.queries.php(580): defuse_validate_personal_key('', ''), referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798111 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: #3 /path/to/teampass/sources/main.queries.php(39): mainQuery(), referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798118 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr: #4 {main}, referer: https://domain.tld/teampass/index.php?page=items
[Mon Sep 25 11:50:17.798124 2017] [fcgid:warn] [pid 2579] [client IP:62591] mod_fcgid: stderr:   thrown in /path/to/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://domain.tld/teampass/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
Reset salt key
![1](https://user-images.githubusercontent.com/5982298/30802819-030ac64a-a1e8-11e7-9a48-9fbfb64737d0.JPG)
Change salt key
![2](https://user-images.githubusercontent.com/5982298/30802820-030ed424-a1e8-11e7-8cb6-8d8adbea23c9.JPG)

**Comment by nilsteampassnet** [comment]
What package do you have installed?

**Comment by cdn123** [comment]
May you can concretize your Q? What packages do you mean?

**Comment by nilsteampassnet** [comment]
OK.
What is the Teampass package you have installed and using? 2.1.27.1? 2.1.27.2? ....

**Comment by cdn123** [comment]
Version 2.1.27.7

**Comment by nilsteampassnet** [comment]
Thank you.

Reset PSK doesn't require any psk as the aim of this feature is to reset it as explained in the warning message when you select it.

Change PSK requires the new and old psk. If you don't indicate them nothing will happen.

But I'm not sure to get your point.
Notice that this has been tested in 2.1.27.8 and the feature work as they are designed for.

**Comment by cdn123** [comment]
Yes, but I cannot set a new salt key. As you can see in the pictures, there is no possibility to.

**Comment by nilsteampassnet** [comment]
But based upon the screenshot, I can see that you haven't given the old psk.
Why this?

**Comment by cdn123** [comment]
Ok let‘s start again:
Someone forgot his saltkey. So I have to reset it (pic1). I cannot set a new one as you can see.
Next I try to change the key (pic2), but I have no old key because I don‘t know the old one and after reset I cannot set a new one.

**Comment by nilsteampassnet** [comment]
Oh I understand better now.

So the first action has reseted the existing user PSK and deleted all his items.

Now you don't need to change the psk (as it has been deleted), you just have to `set the psk`.
![image](https://user-images.githubusercontent.com/1197546/30873420-7f1e848c-a2ed-11e7-9b38-7aa4ca10b930.png)

**Comment by cdn123** [comment]
Thanks a lot. A little bit tricky ;-)

**Comment by cdn123** [comment]
Yes please.


Am 26.09.2017 um 20:38 schrieb Nils Laumaillé <notifications@github.com<mailto:notifications@github.com>>:


Yes you are right.
The help could be improved.

Can i close?
