### ISSUE TITLE
Red wheel keeps turning, blocks display of new items

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1923]
### Steps to reproduce
1. Fresh install of 2.1.27.8 or upgrade from 2.1.27.7 to 2.1.27.8
2. Add items to a folder, at least 20 to 30
3. Click on the folder

### Expected behaviour
Normal behaviour

### Actual behaviour
At some point, 1 Teampass installation has this problem as of more than 24 items in 1 folder,  another installation with more than 28. The difference in number could be explained because somehow the folders are also counted. But the problem is that next to the search window a red wheel keeps turning and never goes away. ![2017-09-25_15-06-45](https://user-images.githubusercontent.com/29922616/30809792-4c3c525a-a203-11e7-8e1b-bf3c5e494230.png)
When trying to add a new item in this folder it does not display this new item. Only after deleting a few items the red icon disappears and the newly added items suddenly appear.
So this problem only occurs upward of a certain number of items in a folder.

### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.7.19
**PHP version:**
PHP 7.0.23
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install of 2.1.27.8 and upgrade from 2.1.27.7 to 2.1.27.8

PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 47.0.2526.106, IE 11
**Operating system:**
Windows 7, Windows Server 2012 R2
#### Web server error log
``` 
Insert your webserver log here
```
 
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Would it be possible for you to check the error log.
It must contain errors when you have this spining cog staying visible.

**Comment by byeight** [comment]
Hi Nils, 

This is the Apache errorlog when the spinning cog is visible. Also when viewing a folder with 60 or more items only about 28 will be visible with the red cog spinning. This is something new with the latest release.


[Mon Sep 25 22:01:46.911553 2017] [mpm_winnt:notice] [pid 1720:tid 448] AH00428: Parent: child process 3628 exited with status 3221226356 -- Restarting.
[Mon Sep 25 22:01:46.974063 2017] [auth_digest:notice] [pid 1720:tid 448] AH01757: generating secret for digest authentication ...
[Mon Sep 25 22:01:47.599065 2017] [mpm_winnt:notice] [pid 1720:tid 448] AH00455: Apache/2.4.23 (Win64) OpenSSL/1.0.2h PHP/7.0.10 configured -- resuming normal operations
[Mon Sep 25 22:01:47.599065 2017] [mpm_winnt:notice] [pid 1720:tid 448] AH00456: Apache Lounge VC14 Server built: Jul  1 2016 11:43:51
[Mon Sep 25 22:01:47.599065 2017] [core:notice] [pid 1720:tid 448] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.23\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.23'
[Mon Sep 25 22:01:47.599065 2017] [mpm_winnt:notice] [pid 1720:tid 448] AH00418: Parent: Created child process 1640
[Mon Sep 25 22:01:48.005322 2017] [auth_digest:notice] [pid 1640:tid 376] AH01757: generating secret for digest authentication ...
[Mon Sep 25 22:01:48.239703 2017] [mpm_winnt:notice] [pid 1640:tid 376] AH00354: Child: Starting 64 worker threads.

**Comment by byeight** [comment]
Latest commit fixed it, thx for quick response.

**Comment by hayd555** [comment]
May as ask how to resolve? it just states a latest commit fixed the issue? what commit is that exactly?
