### ISSUE TITLE
Passwords not readable 2.1.27.8

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1926]
### Steps to reproduce
After upgrading from 2.1.27.7 to 2.1.27.8, users who are granted to read some password items aren't able to read it.
This message appears:
![grafik](https://user-images.githubusercontent.com/27355139/30813037-974832b0-a20c-11e7-9d74-3351c7f51ac3.png)

After some research I found the problem:
In MySQL Database Table _teampass_items_ all of the old passwords got a "_1_" in collumn "_perso_" instead of a "_0_"

**Comment by nilsteampassnet** [comment]
You mean that when you compare the DB .8 with the .7 one, you can see that all items have now the field `perso` is set to 1?
I don't see how this is posssible as no such query exists.
I must understand why you have this ... it is really surprising me!

**Comment by benjamin2501** [comment]
Here I got a screenshot:
![grafik](https://user-images.githubusercontent.com/27355139/30898125-f4edbf5e-a359-11e7-9d86-d0554a7a810c.png)
These are all the items saved at Teampass. The yellow marked "0" is a password I created after the update to .8 This item is readable and if I change any item wich contains a "1" to "0" this changed item is also readable.

Could this correlate with issue #1894 ?

**Comment by nilsteampassnet** [comment]
Could you restore the databse corresponding to 2.1.27.7 inside another database and do the same query?
This to check if it was not already present in the old database (but revealed due to a code change).
I want to isolate the issue as I cannot reproduce.

Thank you

**Comment by benjamin2501** [comment]
@nilsteampassnet 
Sorry but I don't have any database backup from .7 I'm pretty shure I created one but it disappeared?!
I will just change the database by my hand (Luckily, I haven't saved that many passwords)
Thanks for your support
(I will close this issue)
