### ISSUE TITLE
Passwords created now showing the true amount

### ISSUE THREAD

**Issue by hayd555** [nilsteampassnet/TeamPass#1929]
I have 16 passwords created under the folder, only 11 are showing but when I search the tag I created it also displays all 16.

Why is the main menu not displaying all 16 entries created?

Also to add that there is still a red kog spinning, DB is also showing the creations

**Comment by hayd555** [comment]
Just tested with another machine and different account, the query takes a long time but it loads with all 16 entries, so something is cached on my local machine? I did clear google chrome cache.

The query did take a while - only 16 entries too with redkog? what does this suggest and how can i speed this up?

**Comment by nilsteampassnet** [comment]
Duplicate of #1923
