### ISSUE TITLE
Upgrade from 2.1.20 to 2.1.21 not possible 

### ISSUE THREAD

**Issue by thorstenkramm** [nilsteampassnet/TeamPass#1931]
### Steps to reproduce
1. Install Teampass 2.1.21 having 2.1.20 running
2. Try to upgrade using /install/upgrade.php

I'm trying to upgrade from2.1.19 to the latest version. The upgrade from 2.1.19 to 2.1.20 could be executed flawless. Now I'm struggling with the upgrade to 2.1.21

When I start the upgrade process be calling http://teampass.local/install/upgrade.php the second step, which says "Next elements will be checked" can not be executed. When I click launch nothing happens. I get a java script error `ReferenceError: $ is not defined  install.js:5:1` 

From my understanding this error means, some function tries to use Jquery which is not loaded.

I looked into `install/upgrade.php` at line 74 and I noticed that functions are declared before Jquery is loaded.
I changed the order of the includes to:
```
 <title>TeamPass Installation</title>
<link rel="stylesheet" href="install.css" type="text/css" />
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="../includes/js/functions.js"></script>
<script type="text/javascript" src="install.js"></script>
<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/aes.min.js"></script>
``` 
The JS error disappeared, but the "Launch Button" disappeared too.

### Expected behaviour
Upgrade happens

### Actual behaviour
The "Next" Button is disabled.

### Server configuration
Debian Jessie, PHP PHP 5.6.30-0+deb8u1, Apache2, Firefox 54.0, Chrome 61.0.3163.100

``` 
 cat settings.php
<?php
global $lang, $txt, $k, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db;

### DATABASE connexion parameters ###
$server = "10.64.254.20";
$user = "teampass";
$pass = "xxx";
$database = "teampass";
$pre = "teampass_";
$port = "3306";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/srv/keys/teampass');
require_once "/srv/keys/teampass/sk.php";
@define('COST', '13'); // Don't change this.
``` 
**Updated from an older Teampass or fresh install:**
Upgrade from 2.1.20 to 2.1.21
PLEASE attach to this message the file `/includes/config/tp.config.php`.
> This file is not present in Version 2.1.21

#### Web server error log
> no errors in /var/log/apache2/error.log

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
ReferenceError: $ is not defined[Learn More]  install.js:5:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.min.js:17:3553
ReferenceError: httpRequest is not defined[Learn More]  upgrade.php:82:17
```

**Comment by nilsteampassnet** [comment]
Have you cleared the cache of your browser?

**Comment by thorstenkramm** [comment]
Yes, I executed `rm -rf ~/.mozilla` first. I checked "history" in Firefox and deleted everything. No luck.
Here you can see exactly what I did. https://www.screencast.com/t/6919dWrVu1

**Comment by nilsteampassnet** [comment]
Well, I don't really know here what is going on.
At the time of this version, I haven't this issue, so I believe it is not related to the code itself.
I believe there must be some other errors perhaps due to deprecated functions if using a too recent php version. 

I've done the exercice to install 2.1.20, add some items and upgrade to 2.1.21 and it works.
At the step where you have this error, I don't have one.
![image](https://user-images.githubusercontent.com/1197546/32320178-39186a1a-bfbd-11e7-995e-4b97df169dd3.png)


So I would bet on something regarding the server parameters, the browser, ...

**Comment by thorstenkramm** [comment]
Thank you for having tried it. You did it on windows. I can try that too. But I'll wait for your new version 2.1.27.9. Does this version support a direct upgrade from 2.1.19 or 2.1.20?

**Comment by nilsteampassnet** [comment]
The direct upgrade mechanism in 2.1.27 works only from 2.1.26 and the future versions.
This means that you need to reach 2.1.26 to upgrade to 2.1.27.

**Comment by thorstenkramm** [comment]
I tried an upgrade from 2.1.20 to 2.1.21 using Wamp64. Unfortunately, I get the same errors like on Linux. The first step throws errors and I cannot proceed. In your screenshot above I've seen you tried to upgrade to 2.1.20. That has always been working for me.

**Comment by albarki** [comment]
Hi, 

I have the same issue, I am not able to upgrade from `2.1.20` to `2.1.21`
![error image](https://i.imgur.com/ZLQSRMB.png)

I tried to update from `2.1.20` to `2.1.22` directly, it completed sucessuflly but i lost some passwords i dont know why.

Thanks
Ibrahim

**Comment by albarki** [comment]
Hi, 

I copied the file `install/upgrade.php` from version `2.1.22` to version `2.1.21` and tried to upgrade from `2.1.20` to `2.1.21` and it works for me without any password loss.
```
git checkout 2.1.22
cp install/upgrade.php ../teampass/install/
```
Thanks
