### ISSUE TITLE
2.1.27.8 - Keepass.xml upload

### ISSUE THREAD

**Issue by benjamin2501** [nilsteampassnet/TeamPass#1932]
### Steps to reproduce
1. Login as LDAP user
2. Try to upload Keepass.xml
3. "Can't Read the file! It must be a KeePass file."
![grafik](https://user-images.githubusercontent.com/27355139/30906471-448e8b60-a378-11e7-8e37-fcf712a477b2.png)

### Server configuration
**Teampass version:** 
2.1.27.8

**Comment by nilsteampassnet** [comment]
Confirmed

Thank you for reporting
