### ISSUE TITLE
Trying to move folder results in error message

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1933]
### Steps to reproduce
1. Click on a folder
2. Select Move folder and choose a folder to move the folder to
3. Click save

### Expected behaviour
Folder will be moved

### Actual behaviour
Message: You are not allowed to do that!
![move](https://user-images.githubusercontent.com/29922616/30917418-41ef25e4-a39c-11e7-8a8f-e3f23509a4f3.JPG)
### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.7.19
**PHP version:**
PHP 7.0.23
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install of 2.1.27.8 and upgrade from 2.1.27.7 to 2.1.27.8

### Client configuration
**Browser:**
Chrome 47.0.2526.106, IE 11
**Operating system:**
Windows 7, Windows Server 2012 R2
#### Web server error log
``` 
Insert your webserver log here
```
 
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Confirmed

Thank you for reporting
