### ISSUE TITLE
Add folder results in Requested JSON parse failed

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1935]
### Steps to reproduce
1. Click on a folder
2. Select Add folder, type folder name
3. Click save

### Expected behaviour
Folder will be created

### Actual behaviour
Message: Requested JSON parse failed.

![addfolder](https://user-images.githubusercontent.com/29922616/30930308-a0927766-a3c1-11e7-928b-8ad393d8f28e.JPG)

(Using latest commit at this time)

### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.7.19
**PHP version:**
PHP 7.0.23
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install of 2.1.27.8 and upgrade from 2.1.27.7 to 2.1.27.8

### Client configuration
**Browser:**
Chrome 47.0.2526.106, IE 11
**Operating system:**
Windows 7, Windows Server 2012 R2
#### Web server error log
``` 
Insert your webserver log here
```
 
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Confirmed.
Stupid debug remaining.

**Comment by Husky110** [comment]
Sorry, but I gotta reopen this one...
I'm using the latest release-tag (2.1.27.9) on Ubuntu 16.04.3 with Apache, MySQL 5.7.20 and PHP 7.1.
Client: Chrome Version 61.0.3163.100
