### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by elvesibeiro** [nilsteampassnet/TeamPass#1936]
Hi, Guys.

I have a doubt about the feature. When I enable this configuration using the user admin the feature is disabled without intervention. Is it normal this comportment?

Server configuration
Operating system:
CentOS 7

Web server:
Server version: Apache/2.4.6 (CentOS)
Server built: Aug 23 2017 15:47:21
Server's Module Magic Number: 20120211:24
Server loaded: APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture: 64-bit
Server MPM: prefork
threaded: no
forked: yes (variable process count)
Server compiled with....
-D APR_HAS_SENDFILE
-D APR_HAS_MMAP
-D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
-D APR_USE_SYSVSEM_SERIALIZE
-D APR_USE_PTHREAD_SERIALIZE
-D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
-D APR_HAS_OTHER_CHILD
-D AP_HAVE_RELIABLE_PIPED_LOGS
-D DYNAMIC_MODULE_LIMIT=256
-D HTTPD_ROOT="/etc/httpd"
-D SUEXEC_BIN="/usr/sbin/suexec"
-D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
-D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
-D DEFAULT_ERRORLOG="logs/error_log"
-D AP_TYPES_CONFIG_FILE="conf/mime.types"
-D SERVER_CONFIG_FILE="conf/httpd.conf"

Database:
mysql Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

PHP version:
7.0

Teampass version:
Release 2.1.27.8

Updated from an older Teampass or fresh install:
Fresh Install

Client configuration

Browser:
Chrome

Operating system:
Windows 7 64

**Comment by nilsteampassnet** [comment]
Tested and retested, I cannot reproduce.

Try to clear the cache, try to check the error logs and share please.

**Comment by elvesibeiro** [comment]
It's working now.

Thanks.
