### ISSUE TITLE
Backup script "script.backup.php" and backups from team pass portal isnt working

### ISSUE THREAD

**Issue by sasiharshav** [nilsteampassnet/TeamPass#1937]
Hi,

Not sure if this is already reported but i am experiencing issues in taking database backup via "script.backup.php" and also from teampass web portal. Experiencing below errors:

1. When executing "script.backup.php", getting error 

root@testnode:/var/www/html/teampass/backups# php -f script.backup.php
PHP Fatal error:  Uncaught Error: Call to undefined function defuse_return_decrypted() in /var/www/html/teampass/backups/script.backup.php:22
Stack trace:
#0 {main}
  thrown in /var/www/html/teampass/backups/script.backup.php on line 22

2. When trying to take backup from teampass web portal using default options in " Settings for optional backup script" i get "File not found: /var/www/html/teampass/backups/.sql" error.

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**

2.4.18-2ubuntu3.5

**Database:**

5.7.19

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 

**Teampass version:** 
2.1.27

**Teampass configuration file:**

/var/www/html/teampass/backups/script.backup.php

**Updated from an older Teampass or fresh install:**
freshinstall

PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Bug is confirmed when using this file in standalone.

I will provide a fix tonight.
