### ISSUE TITLE
Unable to change page (role management)

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#1939]
### Steps to reproduce
1. Create almost 8 roles (needed roles for cover all page Width)
2. Create another role
3. CLick on the right arrow on lower (under role matrix)
4. The roles matrix cannot scroll for view the 9th role

### Expected behaviour
I can see the next role

### Actual behaviour
The page show the same 8 roles

### Server configuration
**Operating system**:
Windows 2008 R2
**Web server:**
Apache 2.4.27
**Database:**
Mysql 5.7.19
**PHP version:**
5.6.31
**Teampass version:** 
2.27.8
**Teampass configuration file:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => 'C:/wamp64/www/teampass',
    'cpassman_url' => 'http://10.21.20.53/teampass',
    'favicon' => 'http://10.21.20.53/teampass/favicon.ico',
    'path_to_upload_folder' => 'C:/wamp64/www/teampass/upload',
    'url_to_upload_folder' => 'http://10.21.20.53/teampass/upload',
    'path_to_files_folder' => 'C:/wamp64/www/teampass/files',
    'url_to_files_folder' => 'http://10.21.20.53/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@discoveryinside.local',
    'ldap_domain_dn' => 'dc=discoveryinside,dc=local',
    'ldap_domain_controler' => 'dc_discovery.discoveryinside.local',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1503833449',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => 'proxy.reply.it',
    'proxy_port' => '8080',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,ppk,pem,der,csr,key,cer',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => 'C:/wamp64/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Rome',
);
**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome/Firefox/IE11
**Operating system:**
Windows 7 and WIndows 10
#### Web server error log
``` No error log
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
16:28:03.636 csrfprotector.js:272 XHR finished loading: POST "http://10.21.20.53/teampass/sources/roles.queries.php".
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
refresh_roles_matrix @ index.php?page=manage_roles:1486
onclick @ index.php?page=manage_roles:1144

Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Fixed.

Thank you for reporting it

**Comment by antoweb** [comment]
Thanks for the fix!
