### ISSUE TITLE
Teampass 2.1.27.8 - Visualisation problems

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1941]
### Steps to reproduce
1. Open any folder with many items

### Expected behaviour
See all 4 icons on right side (Editing, Copy Username, Copy Password, Favorite)
![error2](https://user-images.githubusercontent.com/4628571/31020029-6458e2d8-a53a-11e7-978e-7e2117b94ebc.JPG)

### Actual behaviour
If I have to many items, Favorite icons hides behind Slider (Up/Down)
![error1](https://user-images.githubusercontent.com/4628571/31020028-6456bb66-a53a-11e7-9f20-94082f841d38.JPG)

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Sep 18 2017 16:37:54
**Database:**
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28)
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**
[Settings.txt](https://github.com/nilsteampassnet/TeamPass/files/1344638/Settings.txt)
**Updated from an older Teampass or fresh install:**
Update from earlier version 2.1.27.8 where this issue appeared first time.

PLEASE attach to this message the file `/includes/config/tp.config.php`.
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1344639/tp.config.txt)
### Client configuration
**Browser:**
IE, Firefox, Chrome
**Operating system:**
Windows 10 Ent 1703

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

CSS issue. I will commit a fix.

**Comment by nirG95** [comment]
An other problem CSS when you search with long path :

![image](https://user-images.githubusercontent.com/17385158/31118476-c9375450-a82d-11e7-81d8-6903b7697fe7.png)
