### ISSUE TITLE
File upload results in error

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1944]
### Steps to reproduce
1. Add new item
2. Type label name, Click Files and Images Tab
3. Click select, select file, click Start file upload, click Save

### Expected behaviour
File should be added to item.

### Actual behaviour
Error message is shown:
![addfile](https://user-images.githubusercontent.com/29922616/31055741-b1f3eacc-a6c7-11e7-8c4e-f8bfbd9db4c7.JPG)

File is written encrypted to upload folder, but not visibile in Teampass.

### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.7.19
**PHP version:**
PHP 7.0.23
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install of 2.1.27.8 and upgrade from 2.1.27.7 to 2.1.27.8 (latest commit)

### Client configuration
**Browser:**
Chrome 47.0.2526.106, IE 11
**Operating system:**
Windows 7, Windows Server 2012 R2
#### Web server error log
``` 
Insert your webserver log here
```
 
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
OK I understand why you have this error.
I have made a mistake yesterday while committing some changes.
I committed them into 'master' branch.
It should have been done in 'development'.

I have fixed this after my tests shown the same.

Thank you

**Comment by byeight** [comment]
Hi Nils, thx for the fix.

When uploading a file to an item for the second time (and any time after that) the message "Please wait!...." is permanently visable. The buttons work normally, the upload works also, so no problem there.
