### ISSUE TITLE
Cannot delete items

### ISSUE THREAD

**Issue by byeight** [nilsteampassnet/TeamPass#1945]
### Steps to reproduce
1. Click any item
2. Click delete item
3. Click in message: Delete

### Expected behaviour
Item should be deleted.

### Actual behaviour
Item is not deleted.

### Server configuration
**Operating system**:
Windows Server 2012 R2
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.7.19
**PHP version:**
PHP 7.0.23
**Teampass version:** 
2.1.27.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install of 2.1.27.8 and upgrade from 2.1.27.7 to 2.1.27.8 (latest commit)

### Client configuration
**Browser:**
Chrome 47.0.2526.106, IE 11
**Operating system:**
Windows 7, Windows Server 2012 R2
#### Web server error log
``` 
Insert your webserver log here
```
 
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
OK I understand why you have this error.
I have made a mistake yesterday while committing some changes.
I committed them into 'master' branch.
It should have been done in 'development'.

I have fixed this after my tests shown the same.

Thank you
