### ISSUE TITLE
2.1.28 upgrade missing sk.php issue

### ISSUE THREAD

**Issue by newburns** [nilsteampassnet/TeamPass#1949]
### Steps to reproduce
1. Upgrade from 2.1.27 to 2.1.28 with sk.php in different directory other than html
2. Upgrade will not start due to missing sk.php file after administrator login
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Could not reproduce.
I have dozens of test cases regarding upgrade and replayed all of them.
THis case is part of my test cases (sk.php in another server folder)
Results are ok.
Can you check that the folder indicated in settings.php is indeed where your sk.php file is?
