### ISSUE TITLE
How restore data backup of old version for new version?

### ISSUE THREAD

**Issue by BFCardoso** [nilsteampassnet/TeamPass#1950]
Hi,

I was using a old version of TeamPass.

TeamPass 2.1.20 © 2009 - 2014
PHP 5.3.3 (cli) (built: Aug  6 2014 05:40:05)
MySQL 5.1.73

I installed new version as below:

MySQL version 5.7.19
PHP version 7.0.23
Teampass version 2.1.27

But I can´t restore the database backup of the old version, in the new server, Is there a procedure for this?

 
### Steps to reproduce
1. I made a backup throught web interface of old version;
2. I try import the backup file in the web interface of new version TeamPass;
3. The procedure the restore backup don´t function.

### Expected behaviour

The data backup file must be restored after restore in the web interface.

### Actual behaviour

The procedure the restore backup don´t function.

### Server configuration
**Operating system**:
CENTOS 7
**Web server:**
 Apache/2.4.6 (CentOS)

**Database:**
MySQL version 5.7.19

**PHP version:**
PHP version 7.0.23

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This is not possible.

You must upgrade through all versions until the last one.
This is a major drawback of previous versions. Since 2.1.27, this will not be needed anymore as the upgrade script contains all incremental upgrades.

You will found all releases in Releases page.

**Comment by thorstenkramm** [comment]
Hi,
the new upgrade feature sounds very promissing. 
I tryed to upgrade from 2.1.20 to latest 2.1.27
