### ISSUE TITLE
Teampass 2.1.27.8 - Latency after upgrade

### ISSUE THREAD

**Issue by nirG95** [nilsteampassnet/TeamPass#1951]
Bonjour,

Suite à la mise à jour en version 2.1.27.8, nous rencontrons des problèmes de lenteur lors de l'affichage des éléments dans un répertoires. Nous n'avons pas énormément d'information pour l'instant, avec 82 dossiers et 100 éléments. 

Voici ci-dessous les tests effectués sur un dossier avec 67 éléments :

Charge CPU du processus HTTPD : 
![image](https://user-images.githubusercontent.com/17385158/31117097-d43a7cba-a828-11e7-89b2-c8cd9da1b99e.png)

Latence du chargement des pages : 
![image](https://user-images.githubusercontent.com/17385158/31117152-1f349c50-a829-11e7-9f7e-e652e76418fe.png)
![image](https://user-images.githubusercontent.com/17385158/31117164-2ed6ef0a-a829-11e7-923f-a66b539fc08d.png)
![image](https://user-images.githubusercontent.com/17385158/31117192-43489fa6-a829-11e7-884b-4a9ee79c8164.png)

Aucune erreurs dans le fichiers de logs HTTPD.

Je suis preneur d'une solution, même si je dois faire la réinstallation complète.

### Server configuration
**Operating system:**
CentOS Linux release 7.4.1708 (Core)

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Aug 23 2017 15:47:21

**Database:**
mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 5.6.31 (cli) (built: Jul  6 2017 07:30:58)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Teampass version:** 
2.1.27.8

**Teampass configuration file:**
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://smssteampass',
    'favicon' => 'http://smssteampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://smssteampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://smssteampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@mss.lan',
    'ldap_domain_dn' => 'DC=mss,DC=lan',
    'ldap_domain_controler' => 'smssdc.mss.lan',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1503396529',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '127.0.0.1',
    'email_smtp_auth' => '0',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => 'none',
    'email_server_url' => '',
    'email_from' => 'teampass@mss.lan',
    'email_from_name' => 'Teampass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '0',
    'teampass_version' => '2.1.27',
    );
```
### Client configuration
**Browser:** Firefox
**Operating system:** Windows 7

**Comment by nilsteampassnet** [comment]
C'est étonnant que ça survienne après migration.
As-tu essayé un restart du serveur ?
Combien d'objets par répertoire ?
Est-ce que les petites icones à droite de chaque objets sont affichées. Si oui, les désactiver pour réduire le nombre de requetes et voir si cela influence les perfs ?
Quelles sont les caractéristiques du serveur ?

**Comment by nirG95** [comment]
Oui le serveur a été redémarré, les items ne dépassent pas les 67 pour l'instant. 
Ca tourne sur une machine virtuelle avec 4vcpu 4Go de ram et sur une baie SAN. 
C'est vraiment après l'upgrade que nous avons eu les ralentissements. 

Il faudrait que je refasse l'install avec le drop de la DB voir ce que cela donne.

**Comment by nilsteampassnet** [comment]
Vraiment étonnant ... je ne vois pas ce qui peut ralentir de façon si significative ton serveur après cette migration. Il n'y a pas plus de requetes ... j'ai meme réduit ce nombre en sauvegardant les infos communes lors de liste plus longues.
Ce qui est sur c'est qu'il est préférable de limiter le nombre d'objets par répertoire et plutot d'augmenter le nombre de répertoire pour avoir une granularité de tri plus importante.
Peux-tu essayer de désactiver l'option `copy_to_clipboard_small_icons` qui correspond aux mini-icones ?
Cette option rajoute des requetes et de la charge mémoire ... pour voir s'il y a une différence.

**Comment by nirG95** [comment]
Je l'avais deja fait. Cela réduit un peu mais ca reste pareil. Je vais essayer de faire un backup et de drop la db et reinstaller le tt. On vera bien se que ca donne. Je clos l'issue :)

**Comment by nilsteampassnet** [comment]
J'ai fait un certain nombre d'optimisation de l'afficahge de la liste des objets dans la branche développement.
Si tu as un environement de qualif, alors il serait bien de l'esssayer pour voir si cela fait tomber la charge.
De mon coté, j'ai pu noter une amélioration significative dans la durée de réponse du serveur (et donc de l'affichage). Donc peut-etre qu'il y aura un impact sur la charge du serveur.

Je pense que oui dans la mesure ou c'est maintenant sur le "client" que se passe la génération de l'html.
