### ISSUE TITLE
Google Authenticator code is wrong

### ISSUE THREAD

**Issue by jleleux** [nilsteampassnet/TeamPass#1953]
### Steps to reproduce
1. User is setup with Google Authenticator
2. User gets code from Google Authenticator 
3. User logs into Teampass

### Expected behaviour
Google Authenticator code provides 2FA for user authentication

### Actual behaviour
User is consistently receiving message that Google Authenticator code is wrong.

### Server configuration
**Operating system**:
CentOS 7.4.1708
**Web server:**
httpd-2.4.6-67.el7.centos.2.x86_64
**Database:**
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64)
**PHP version:**
PHP 5.6
**Teampass version:** 
2.1.28
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**
IE 11 or Google Chrome  61.0.3163.100
**Operating system:**
Windows 7 Pro
#### Web server error log
```
Couldn't find any error pertaining to this
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
I'm working on getting the developer console output
```
[TP_BACKUP.zip](https://github.com/nilsteampassnet/TeamPass/files/1353093/TP_BACKUP.zip)

**Comment by nilsteampassnet** [comment]
Tested and couldn't reproduce.
All my test cases are success. Users receive by email a unique code, this code is then used in the login form and the GA flashcode is displayed. Using samrtphone and GAAuthenticator app, the user has the token to use.
Please show screen-capture at each step for example.

**Comment by andhoy** [comment]
I had the same problem on centos 7. "Server time" shown in webui, and OS time were different.
Fixed it by choosing correct timezone in the settings tab.

**Comment by jleleux** [comment]
Thanks

Jeremy Leleux
Network Systems Administrator
First National Bank of Louisiana
O: 337-788-8952 | F: 337-788-8952
jleleux@fnb-la.com | www.fnb-la.com<http://www.fnb-la.com/>

[FNB-of_LA-COLOR-NO-TAGLINE-LARGE 700x360]
