### ISSUE TITLE
Error message on first click on personnal item

### ISSUE THREAD

**Issue by jcoquery** [nilsteampassnet/TeamPass#1955]
### Steps to reproduce
1. Click on personnal folder
2. Click on an item

### Expected behaviour
No error message

### Actual behaviour
Error message appear.
If you don't change folder, and click again on the same item, the message doesn't appear again.
But if you move to another forlder and come into your personnal folder again, the error appear again if you click on an item.

### Server configuration
**Operating system:** Docker (Centos)

**Web server:** Apache

**Database:** 5.7.19

**PHP version:** 7.1.9

**Teampass version:** 2.1.27

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1359559/tp.config.txt)

### Client configuration
**Browser:** All

**Operating system:** Windows 10

![tp error](https://user-images.githubusercontent.com/30726879/31231207-7676b23c-a9e6-11e7-826c-bbd3f0ac51d9.png)

**Comment by nilsteampassnet** [comment]
Sorry I couldn't reproduce.
Can you please give me the exact version you use?
![image](https://user-images.githubusercontent.com/1197546/31240031-735ccffa-a9ff-11e7-8eaf-524bf2f38dec.png)

**Comment by jcoquery** [comment]
The version is same as your screenshot: 2.1.27.9
It looks like , but I'm not sure, that the problem appear after a new fresh install and DB import from a 2.1.27.8 version

**Comment by jcoquery** [comment]
If I replace all files with the last commited, the error change.
No more "json error" but now can't access to my personnal item. I got the message 

> Vous n'avez pas le droit de consulter ce mot de passe
> Auteur: Moi
> Restreint à: 
> 
> Demander un accès au créateur

I don't know if it help

**Comment by jcoquery** [comment]
So I think I have found what is causing this problem.
In the file sources/items.queries.php:
1) in `case "show_details_item":` section
Bellow `            // Check if actual USER can see this ITEM`
This part is causing problem:
`                (null !== $post_folder_id`
`                    && isset($_SESSION['list_restricted_folders_for_items'][$post_folder_id])`
`                    && in_array($post_id, $_SESSION['list_restricted_folders_for_items'][$post_folder_id])`
`                    && $post_restricted === '1'`
`                    && $user_in_restricted_list_of_item === true)`
If I comment the last 3 lines, no more "Vous n'avez pas le droit de consulter ce mot de passe".

But after this, the JSON error is coming back.

2) In `case "showDetailsStep2":` section:
There is the same test.
This one got different result because '$post_folder_id' is empty.
So I compare to previous version of this file which doesn't have this test and I comment the entire test. The 'if' section just after `'// check user is admin`  and the 'elseif.
No more 'JSON error.
