### ISSUE TITLE
Login credentials do not correspond (json_decode issue)

### ISSUE THREAD

**Issue by GTSLiDe** [nilsteampassnet/TeamPass#1965]
### Steps to reproduce
1. Upgrade from 2.1.27.7 to 2.1.27.9
2. Login using admin account
3. Receive the error message "Login credentials do not correspond!"

### Expected behaviour
The system should logs you in

### Actual behaviour
Receive the error message "Login credentials do not correspond!"

### Server configuration
**Operating system**: 
CentOS and MacOS

**Web server:**
Apache2

**Database:**
MYSQL 5.6.35

**PHP version:**
5.6.31

**Teampass version:** 
2.1.27.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome, Safari and Firefox
**Operating system:**
MacOS and CentOS
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

After an upgrade from 2.1.27.7 to 2.1.27.9, I was not able to login again.
After much troubleshooting I found that this code:
`$post_data = filter_input(INPUT_POST, 'data', FILTER_SANITIZE_STRING);`
in /sources/identify.php line 50, converted the array data to unreadable array which cause json_decode not able to decode it back and instead returning null.

var_dump($_POST['data']) output:
string(167) "{"login":"admin" , "pw":"admin" , "duree_session":"1000" , "screenHeight":"785" , "randomstring":"OviEU7mU9K" , "TimezoneOffset":"21600", "GACode":"" , "client":""}"

However, $post_data becomes unreadable array:

var_dump($post_data) output:

string(295) "{&#34;login&#34;:&#34;admin&#34; , &#34;pw&#34;:&#34;admin&#34; , &#34;duree_session&#34;:&#34;1000&#34; , &#34;screenHeight&#34;:&#34;785&#34; , &#34;randomstring&#34;:&#34;OviEU7mU9K&#34; , &#34;TimezoneOffset&#34;:&#34;21600&#34;, &#34;GACode&#34;:&#34;&#34; , &#34;client&#34;:&#34;&#34;}"

![identify php - teampass_prod - applicationsmamphtdocsteampass_prod 2017-10-11 13-40-20](https://user-images.githubusercontent.com/17164545/31462361-c4905c96-ae89-11e7-86bf-06e14e25470b.png)

![teampass 2017-10-11 13-42-41](https://user-images.githubusercontent.com/17164545/31462457-16dc9776-ae8a-11e7-8d34-e6662164da3f.png)

Looks like `filter_input(INPUT_POST, 'data', FILTER_SANITIZE_STRING);` converts the " to `&#34;`.

 In order to fix this, I had to convert the quotes in $data variable in prepareExchangedData function in sources/main.functions.php line 1311:
`$data = stripslashes(html_entity_decode($data));`

![monosnap 2017-10-11 13-52-07](https://user-images.githubusercontent.com/17164545/31462913-72365c00-ae8b-11e7-9959-5d49acb904c9.png)

Does anyone having this issue or is able to reproduce this issue on their side?

**Comment by nilsteampassnet** [comment]
Thank you for reporting with this good analysis.
This helps a lot.

To prevent doing several changes, the most optimized way to adapt is to add the filter FILTER_FLAG_NO_ENCODE_QUOTES to the filter_input command.

I will commit the fix today.

**Comment by nilsteampassnet** [comment]
Please use new 2.1.27.9 package by over-writing existing files.
