### ISSUE TITLE
Upgrade 2.1.27.9_old to 2.1.27.9_new fails

### ISSUE THREAD

**Issue by newburns** [nilsteampassnet/TeamPass#1967]
### Steps to reproduce
1. Upgrade 2.1.27.3. to previously released 2.1.27.9
2. Upgrade 2.1.27.9 previous to current 2.1.27.9
3. Upgrade procedure fails on database scripts

### Expected behaviour
Update should run smoothly to get to latest 2.1.27.9

### Actual behaviour
Update stops on database scripts with
```
8:48:4 - ERROR: Previous Saltkey not in database.
08:48:04 - upgrade_run_defuse_for_pwds.php - Loop #1 
```

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache 2.4 with FCGID

**Database:**
MySQL 5

**PHP version:**
```
PHP 7.0.10 (cli) (built: Nov  3 2016 08:06:03) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
**Teampass version:** 
2.1.27.9 from 2017-10-10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7

#### Web server error log
ERROR LOG IS UNRELATED. Error log is from previous 2.1.27.9 installation.
```
[Tue Oct 10 13:35:16.335038 2017] [fcgid:warn] [pid 2091] [client 166.141.55.198:64063] mod_fcgid: stderr: PHP Notice:  Undefined index: item_extra_fields in /home/security.altehost.com/public_html/sources/main.functions.php on line 1154, referer: https://security.altehost.com/index.php?page=manage_main
```

**Comment by nilsteampassnet** [comment]
Please refer to #1968 

I'm closing this one
