### ISSUE TITLE
ip-api.com use is not compatible with https

### ISSUE THREAD

**Issue by danpoltawski** [nilsteampassnet/TeamPass#1970]
### Steps to reproduce
1. Configure site https
2. Upgrade to 2.1.27.9
3. Attempt to login

### Expected behaviour
No errors experienced

### Actual behaviour
Console errors:
```
csrfprotector.js:272 Mixed Content: The page at 'https://my-teampass.domain/index.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ip-api.com/json'. This content should also be served over HTTPS.
new_send @ csrfprotector.js:272
ip-api.com/json Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

### Client configuration
**Browser:** Chrome 61.0.3163.100

**Comment by Hellnino18** [comment]
Hi,

Same problem here. And it's impossible to connect to Teampass.

**Comment by nilsteampassnet** [comment]
Correct.
I will commit a fix
