### ISSUE TITLE
Users or Folders Page just after installation

### ISSUE THREAD

**Issue by Leboubou111** [nilsteampassnet/TeamPass#1971]
### Steps to reproduce
1. juste after a fresh installation
2. no configuration step or other
3. log in admin account and click on users or folders pages

### Expected behaviour
everything else works very well

### Actual behaviour
I have an error when i click on users or folders pages
When the page want to list users or folders, an error ajax appears to a popop

> DataTables warning: table id=t_users - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### Server configuration
**Operating system**: Windows Serveur 2008 R2
**Web server:** IIS7
**Database:** MySql 5.5
**PHP version:** 7.1
**Teampass version:** 2.1.27.9
**Teampass configuration file:**
**Updated from an older Teampass or fresh install:** fresh install
PLEASE attach to this message the file `/includes/config/tp.config.php`.

`<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => 'C:/inetpub/wwwroot/pass',
    'cpassman_url' => 'https://vm-support/pass',
    'favicon' => 'https://vm-support/pass/favicon.ico',
    'path_to_upload_folder' => 'C:/inetpub/wwwroot/pass/upload',
    'url_to_upload_folder' => 'https://vm-support/pass/upload',
    'path_to_files_folder' => 'C:/inetpub/wwwroot/pass/files',
    'url_to_files_folder' => 'https://vm-support/pass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1505635655',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => 'C:/inetpub/wwwroot/pass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC'
);`

### Client configuration
**Browser:** Firefox and chrome test
**Operating system:** Windows 10 and Windows 7

#### Web server error log
```
I don't know where I can find the log server to IIS7
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Erreur de serveur
404 - Fichier ou répertoire introuvable.
La ressource que vous recherchez a peut-être été supprimée ou renommée, ou est temporairement indisponible.

to url : 
http://vm-support/pass/sources/datatable/datatable.folders.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=-1&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1508229712185
```

**Comment by Leboubou111** [comment]
Test with same version 2.1.27.9 on lamp, no problem.
I think it's PHP on IIS. I've tested PHP 5.6, 7.1, same problem.
Do you have an idea ?

**Comment by nilsteampassnet** [comment]
If it is IIS related, I will not be able to reproduce.
But using the browser console, can you please copy here the result of the query
![image](https://user-images.githubusercontent.com/1197546/31788983-d7baa91a-b510-11e7-8578-1fe8728875a1.png)

**Comment by Leboubou111** [comment]
I Nils,

![capture](https://user-images.githubusercontent.com/8314926/31791338-8a7c8058-b518-11e7-9bf2-1016a71a4a8e.JPG)

**Comment by Leboubou111** [comment]
But if I just type http://<site>/sources/datatable/datatable.users.php

![capture](https://user-images.githubusercontent.com/8314926/31791669-a3a6c01a-b519-11e7-9e36-46da79c712f5.JPG)

**Comment by nilsteampassnet** [comment]
How strange behavior ...
It is as if the path is not correct when calling this file from the Users page.
Can you please do the next try for me?

Open file `users.load.php`
Find the code
```
    //Launch the datatables pluggin
    var tableUsers = $("#t_users").dataTable({
        "order": [[ 1, "asc" ]],
        "ordering": false,
        "pagingType": "full_numbers",
        "processing": true,
        "serverSide": true,
        "ajax": {
            url: "sources/datatable/datatable.users.php",
            data: function(d) {
                d.letter = _alphabetSearch
            }
        },
```
and replace by
```
    //Launch the datatables pluggin
    var tableUsers = $("#t_users").dataTable({
        "order": [[ 1, "asc" ]],
        "ordering": false,
        "pagingType": "full_numbers",
        "processing": true,
        "serverSide": true,
        "ajax": {
            url: "<?php echo $SETTINGS['cpassman_url']; ?>/sources/datatable/datatable.users.php",
            data: function(d) {
                d.letter = _alphabetSearch
            }
        },
```

**Comment by Leboubou111** [comment]
Thanks for your help Nils,

I've changed url code to users.load.php file and now I haven't error when I click to User Page.
But, no users appears to list user page.

**Comment by Leboubou111** [comment]
It's Strange...Users has been in MySQL database

**Comment by nilsteampassnet** [comment]
Are you an admin while looking at the Users list?

**Comment by Leboubou111** [comment]
Sames Issues with Folders

![folders_page_tp](https://user-images.githubusercontent.com/8314926/31943299-99802ed4-b8c8-11e7-8922-54b139368930.JPG)

![folders_list_db-tp](https://user-images.githubusercontent.com/8314926/31943305-9c41a8b4-b8c8-11e7-8e08-2255806d758b.JPG)

**Comment by Leboubou111** [comment]
Do you have an idea Nils ?

**Comment by nilsteampassnet** [comment]
Difficult to say ... I need an access to be able to analyze the cause.
Is this possible (nils@teampass.net)

**Comment by Stoolbend** [comment]
I had the same issue installing TeamPass today. 
In my case, IIS was blocking the request as the query string was too long (as shown on the detailed error page).
I fixed it by increasing the maxQueryString config value from 2048 (default) to 4096. You can do that by going to the website in IIS Manager, click **Configuration Editor**, and then browse to the **system.webServer/security/requestFiltering** section at the top. Then click **requestLimits** in the table below and you will see the maxQueryString value.

![image](https://user-images.githubusercontent.com/1040992/32271840-a5ccbf8c-bef3-11e7-80e8-65d7360e6795.png)

**Comment by nilsteampassnet** [comment]
Thank you @Stoolbend, this tip is very interesting.

**Comment by dwscott** [comment]
It looks like I have the same symptoms on 2.1.27.10; Folders and Users are empty, though they appear to be in the database (This was working on a new install with multiple users and Keepass imported items until I connected to AD)

Not sure if this is the issue but the Firefox web console shows these errors for the tabs.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://teampass01/teampass/sources/datatable/datatable.folders.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=-1&search%5Bvalue%5D=&search%5Bregex
%5D=false&_=1510753535166. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://teampass01/teampass/sources/datatable/datatable.users.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=10&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=false&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=11&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=false&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&letter=&_=1510753552185. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by nilsteampassnet** [comment]
http://teampass.readthedocs.io/en/latest/errors/

Check that you comply to this

**Comment by dwscott** [comment]
Thanks, that’s all it was.

**Comment by pentacore** [comment]
Had the same issues and i can confirm that @Stoolbend solutions fixed it for me

**Comment by nilsteampassnet** [comment]
Thank you for your feedback.

Added this to the [Help docs](http://teampass.readthedocs.io/en/latest/errors/#users-and-folders-lists-are-empty)

**Comment by GraemeCrawford** [comment]
Just to add, I also had this issue and it was caused by the following being set to `http` as opposed to `https`, (I have haproxy in front of Teampass doing SSL offloading.

```
TeamPass location (URL)
Upload folder (URL)
Files folder (URL)
Favicon (full URL)
```

Setting those URL's to https has fixed the issue for me, not sure if I have missed something in the documentation that mentions to ensure this is set correctly.

**Comment by jowijones** [comment]
Same issue,
In my case, I changed my teampass location, so it was simply be sure that was the right URL (in my case https://mydomain/)

**Comment by Nathu2018** [comment]
hi Leboubou111  

did you manages to resolved your issue ? 

ND

**Comment by Leboubou111** [comment]
Hi ND,

Yes, I've a new fresh install on Apache to Debian Server.

It's so crazy, today I've been update to 2.1.27.11 but users and folders page are empty... :-o
But I've migred same time to https on virtualhost only.
When I checked Redirect HTTP to HTTPS box on TeamPass settings, now it's worked fine
