### ISSUE TITLE
Test Upgrade Does Not Work

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#1972]
Hello, I have TeamPass running on a virtual machine for several people in an office. I attempted to perform a test upgrade on a cloned virtual machine with a different IP. Before running the upgrade procedure I made sure to change all mentions of the old IP to the new one in both the files and database. I've tried this several times with varying results but despite changing the IP prior the upgrade never seems to work out.

It will either hang on any attempt to login or fail to load any passwords in any folder the user can access.

### Server configuration
**Operating system**: CentOS 7
**Web server:** Apache2
**Database:** 5.5.50-MariaDB
**PHP version:** 5.6.24
**Teampass version:** 2.1.27

### Client configuration
**Browser:** Chrome
**Operating system:** Windows 10

**Comment by nilsteampassnet** [comment]
Please check that all urls have been adapted.
That your clone instance has access to teampass-seckey.txt.
Ensure also that `jsUrl` variable is correct in /includes/libraries/csrfp/libs/csrfp.config.php file.
