### ISSUE TITLE
Unable to integrate LDAP 

### ISSUE THREAD

**Issue by dinesh8642** [nilsteampassnet/TeamPass#1973]
### Steps to reproduce
Current LDAP setting(dummy data):

LDAP server type: windows/Active Directory
LDAP account suffix for your domain: @DC=ad,DC=google,DC=alphabet,DC=org,DC=us
LDAP base DN for your domain: DC=ad,DC=google,DC=alphabet,DC=org,DC=us
LDAP domain controller(s): dc1001.ad.google.alphabet.org.us
LDAP port: 389
LDAPS: NO
LDAP through TLS : NO
Teampass local users only: NO
![screen shot 2017-10-19 at 4 23 22 pm](https://user-images.githubusercontent.com/16627053/31755818-34230906-b4ec-11e7-857d-cc42bfb4dae5.png)

### Expected behaviour
LDAP users to login with existing credentials.

### Actual behaviour
users unable to login with existing ldap credentials. While testing with correct credentials in LDAP tab in the ADMIN console , the only error the system shows is 'NO OPTIONS'(screenshot attached)

Unable to troubleshoot as there are no sufficient error logs.

### Server configuration
**Operating system**: docker built from the latest github code - 2.1.27

**Web server:** docker built from the latest github code - 2.1.27

**Database:** docker built from the latest github code - 2.1.27

**PHP version:** docker built from the latest github code - 2.1.27

**Teampass version:** 2.1.27

**Teampass configuration file:** docker built from the latest github code - 2.1.27

### Client configuration
**Browser:** Firefox 

**Operating system:** CentOS

#### Web server error log
```
no sufficient logs to provide/
```

#

**Comment by roru69** [comment]
@dinesh8642

Change your  "LDAP account suffix for your domain" to: "@ad.google.alphabet.org.us"

I have the same issue with "No Options", but the actual login with an AD/LDAP account works for me.

So the test results in "No Options", but when I disable maintenance mode and login as a AD/LDAP user at the normal login sceen everything works OK.

Regards,

Roru69

**Comment by bbcolo** [comment]
I had the same issue. 
There seems to be an issue with port parsing. 

As a quick fix i altered the sources/identify.php:
`495:                    'port : 636'."\n".
`

**Comment by dinesh8642** [comment]
Thank you @bbcolo @roru69 for the help. it worked.
