### ISSUE TITLE
"Change the main salt key used for encryption" broke the installation

### ISSUE THREAD

**Issue by sgalam** [nilsteampassnet/TeamPass#1974]
### Steps to reproduce
1. installed 2.1.27 release
2. all is working fine
3. click on "Change the main salt key used for encryption" from admin

### Expected behaviour
the system should change the main salt key

### Actual behaviour
a dialog alert me about the action
confirm
Processing items... 0 > 10 (Total number of items : 2)
and nothing happen. still there.

on the javascript Console i see:
Step Encrypt - 0 ; 10 ; 2
POST https://XXXX/sources/admin.queries.php 500 (Internal Server Error)

now if I try to reload the page i have a 500 error on all pages.

on the includes/ dir i see:
-rw-r--r--  1 www-data www-data  136 Oct 20 18:46 teampass-seckey.txt
-rw-r--r--  1 www-data www-data  136 Oct 20 17:41 teampass-seckey.txt.2017_10_20.1508514079

on error log:
[Fri Oct 20 18:46:11 2017] [error] [client xxxxx] PHP Warning:  mysqli_connect(): (28000/1045): Access denied for user 'teampass_admin'@'localhost' (using password: NO) in /var/www/xxxx/sources/checks.php on line 113, referer: https://XXXXXX/index.php?page=manage_settings&language=english

seems that the script changed the salt key but not updated with the new salt key the mysql passphrase.

To recover the situation I renamed the backup key teampass-seckey.txt.2017_10_20.1508514079 to teampass-seckey.txt.

All passwords saved on the folders are readable.

It's reproducible, every time that I try to change the salt key this happen.

### Server configuration
**Operating system**:
Debian 7

**Web server:**
apache2

**Database:**
mysql 5.5
**PHP version:**
php 5.6 dotdeb

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**
Step Encrypt - 0 ; 10 ; 2
POST https://XXXXXX/sources/admin.queries.php 500 (Internal Server Error)

#### Web server error log
```
[Fri Oct 20 18:46:11 2017] [error] [client xxxxx] PHP Warning:  mysqli_connect(): (28000/1045): Access denied for user 'teampass_admin'@'localhost' (using password: NO) in /var/www/xxxx/sources/checks.php on line 113, referer: https://XXXXXX/index.php?page=manage_settings&language=english

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Step Encrypt - 0 ; 10 ; 2
POST https://XXX/sources/admin.queries.php 500 (Internal Server Error)
```

**Comment by nilsteampassnet** [comment]
I confirm the bug.

I confirm also your analysis @sgalam in the sense that the data is not corrupted. But the teampass-saltkey.txt file is changed so that items are shown without password. Just rename the backup file and items passwords come back.

I will commit a fix.

**Comment by joelmdev** [comment]
I just ran into the same problem and applied the same fix before finding this issue. In my case I had just finished an upgrade from 2.1.27.10 to 2.1.27.35 before performing the "Change the main salt key used for encryption" task. The following two errors are inserted into php_errors.log as a result:

```
[26-Mar-2019 13:51:17 America/Los_Angeles] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'REDACTED' (using password: NO) in D:\home\site\wwwroot\sources\checks.php on line 142
[26-Mar-2019 13:51:17 America/Los_Angeles] PHP Fatal error:  Call to a member function set_charset() on boolean in D:\home\site\wwwroot\sources\checks.php on line 143
```

Trying to keep issues consolidated since the outcome originally listed here is precisely what I ran into; please let me know if you'd prefer I start a new issue.
