### ISSUE TITLE
Сhange standart password "teampass" in database

### ISSUE THREAD

**Issue by pavel0832** [nilsteampassnet/TeamPass#1975]
Hello.
How can I change standart password  "teampass" in database for teampass user?

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache
**Database:**
10.1.28-MariaDB
**PHP version:**
PHP 7.1.10
**Teampass version:** 
2.1.27.9

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7

**Comment by nilsteampassnet** [comment]
I dont' really understand the password you are talking about.

Is it the master saltkey you are talking about? In this case, from the settings page, tab "tasks".
But you need to use the `development` branch as this feature has a bug in 2.1.27.9.

**Comment by pavel0832** [comment]
When I installed teampass, by defaul user teampass had a "teampass" password. And now I or someone else can login into mariadb with the same "teampass" password. How I can chenge the password?

**Comment by nilsteampassnet** [comment]
The password you have entered during the installation is for the "admin" one.
So log as admin and perform a password change => http://teampass.readthedocs.io/en/latest/features/feat-prof/
