### ISSUE TITLE
Config file resetting

### ISSUE THREAD

**Issue by Uzzi** [nilsteampassnet/TeamPass#1977]
Hi, have changed tp.config.php from web.

When I releoad config, my changes aren't

ls -la /var/www/teampass
drwxrwxrwx 10 www-data www-data   4096 ott 24 14:54 includes
-rwxrwxrwx  1 www-data www-data 4812 ott 24 17:20 tp.config.php

### Server configuration
Debian Weezy

Apache/2.2.22 (Debian)

Mysql 5.7.20

PHP 5.5

Teampass version: 2.1.27.9

**Comment by nilsteampassnet** [comment]
Sorry I don't understand the protocol to reproduce.
Can you please explain step by step what you do?

**Comment by nilsteampassnet** [comment]
No news.
I'm closing it
Please reopen if needed
