### ISSUE TITLE
Can't delete personal item

### ISSUE THREAD

**Issue by roru69** [nilsteampassnet/TeamPass#1980]
### Steps to reproduce
1. Clean install of TP developement commit d064343e089192e9ea673e96a84312b83a649bee
2. Set timezone to Europe/Amsterdam
3. Enable Personal Folders, Store Personal Salt key in Cookie.
4. Enable personal items, create a local user and log in with it.
5. create a personal item, view it (OK)
6. Delete the personal item - Fails with internal server error 500

### Expected behaviour
The item should be deleted

### Actual behaviour
Fails with internal server error 500
![afbeelding](https://user-images.githubusercontent.com/9691381/31994720-f9e028ba-b981-11e7-9830-c4e020ee13e1.png)

### Server configuration
**Operating system**:

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.0

**Teampass version:** Developement commit d064343e089192e9ea673e96a84312b83a649bee

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox

**Operating system:** Debian Jessie

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.

[Wed Oct 25 12:41:53.646338 2017] [:error] [pid 11625] [client 192.168.28.5:60913] PHP Notice:  Undefined variable: SETTINGS in /var/www/mydomain.com/public_html/teampass/sources/main.functions.php on line 2138, referer: https://www.mydomain.com/teampass/index.php?page=items
[Wed Oct 25 12:41:53.646380 2017] [:error] [pid 11625] [client 192.168.28.5:60913] PHP Warning:  require_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /var/www/mydomain.com/public_html/teampass/sources/main.functions.php on line 2138, referer: https://www.mydomain.com/teampass/index.php?page=items
[Wed Oct 25 12:41:53.646389 2017] [:error] [pid 11625] [client 192.168.28.5:60913] PHP Fatal error:  require_once(): Failed opening required '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' (include_path='.:/usr/share/php') in /var/www/mydomain.com/public_html/teampass/sources/main.functions.php on line 2138, referer: https://www.mydomain.com/teampass/index.php?page=items


Tested with an Active Directory User and a Local User, same behaviour.

**Comment by roru69** [comment]
@nilsteampassnet 

You already have the credentials to test on my server.

**Comment by nilsteampassnet** [comment]
Confirmed and fixed in `development` branch.
