### ISSUE TITLE
install hang !

### ISSUE THREAD

**Issue by EricLF** [nilsteampassnet/TeamPass#1981]
### Steps to reproduce
1.linux server
2. teampass 2.1.27.9
3. launch assistant

### Expected behaviour
obtain a fresh install of teampass

### Actual behaviour
Welcome OK
•Server checks  OK
•Database connection OK
•Preparation OK
•Tables creation OK
•Finalization
      •Write the new setting.php file for your server configuration OK
      •Write the new sk.php file for data encryption OK
      •Change directory security permissions OK

"Please wait" hang near the button LAUNCH and nothing happend

### Server configuration
**Operating system**: Debian

**Web server:** Apache/2.4.10 (Debian)

**Database:**10.0.32-MariaDB-0+deb8u1 - (Debian)

**PHP version:**

**Teampass version:** 2.1.27.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1417921/tp.config.php.txt)

**Comment by nilsteampassnet** [comment]
Can you please provide the error logs?

**Comment by EricLF** [comment]
[error.teampass.log](https://github.com/nilsteampassnet/TeamPass/files/1418044/error.teampass.log)
[access.teampass.log](https://github.com/nilsteampassnet/TeamPass/files/1418045/access.teampass.log)

**Comment by EricLF** [comment]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[En savoir plus]  jquery.min.js:16:11702
	.parseJSON http://teampass.cdg44.fr/install/js/jquery.min.js:16:11702
	checkPage/<.complete http://teampass.cdg44.fr/install/install.js:127:32
	._Deferred/e.resolveWith http://teampass.cdg44.fr/install/js/jquery.min.js:16:15483
	w http://teampass.cdg44.fr/install/js/jquery.min.js:18:8572
	.send/d

**Comment by nilsteampassnet** [comment]
Hello

You have very strange errors in the log.
They all refers to encryption errors.

As it is a fresh install, I would recommend the next.
- drop Teampass from DB
- remove Teampass folder
- download from `development` branch => https://github.com/nilsteampassnet/TeamPass/archive/development.zip
- perform new install

**Comment by EricLF** [comment]
T_T same errors with the dev branch...

**Comment by nilsteampassnet** [comment]
T_T???

You must have something in your server configuration that blocks something.
Have you checked the errors in apache?

**Comment by EricLF** [comment]
many error about crypto.php..

[error.teampass.log](https://github.com/nilsteampassnet/TeamPass/files/1475755/error.teampass.log)

`[Wed Nov 15 14:32:34.067696 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP Defuse\\Crypto\\Exception\\WrongKeyOrModifiedCiphertextException:  Integrity check failed. in /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php on line 291, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067724 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP Stack trace:, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067731 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   1. {main}() /var/www/TeamPass/install/install.queries.php:0, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067741 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   2. encryptFollowingDefuse($message = 'tVceoWiaAce7spps', $ascii_key = 'def000001c5d069d6224eb4914e83c5d9b018dad49d8ed9ea30b88f67e86ff7c75a2d5986598d9b2d0601c25dd7cd6498f974f0d6d86c46c87e99c888d37ead05b830b42') /var/www/TeamPass/install/install.queries.php:1074, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067753 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   3. Defuse\\Crypto\\Crypto::encrypt($plaintext = 'tVceoWiaAce7spps', $key = class Defuse\\Crypto\\Key { private $key_bytes = '\\034]\\006\x9db$\xebI\\024\xe8<]\x9b\\001\x8d\xadI\xd8\xed\x9e\xa3\\v\x88\xf6~\x86\xff|u\xa2\xd5\x98' }, $raw_binary = *uninitialized*) /var/www/TeamPass/install/install.queries.php:95, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067769 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   4. Defuse\\Crypto\\Crypto::encryptInternal($plaintext = 'tVceoWiaAce7spps', $secret = class Defuse\\Crypto\\KeyOrPassword { private $secret_type = 1; private $secret = class Defuse\\Crypto\\Key { private $key_bytes = '\\034]\\006\x9db$\xebI\\024\xe8<]\x9b\\001\x8d\xadI\xd8\xed\x9e\xa3\\v\x88\xf6~\x86\xff|u\xa2\xd5\x98' } }, $raw_binary = FALSE) /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php:31, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067775 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   5. Defuse\\Crypto\\RuntimeTests::runtimeTest() /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php:183, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067780 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   6. Defuse\\Crypto\\RuntimeTests::testEncryptDecrypt() /var/www/TeamPass/includes/libraries/Encryption/Encryption/RuntimeTests.php:60, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067799 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   7. Defuse\\Crypto\\Crypto::decrypt($ciphertext = '\xde\xf5\\002\\000\xf96\xb7\xa4?\\0012\xee\xa4\xfe\xa53\x98Si\xae\xd6\xfd\xb9\x9d\\ni\x9ew\\003\x8bY\xfa\x98\\033\x97\xb7\xb8jl\x9df\x9b8\xe1\xa9c$\xa1/\xb6\xf8=\\017\xcb\xc2\xe4\xaef\xd9$i3\x80HX\xbfl\xcdry\xbe@\\002\xd3\xa8\xa1\xda(\x8a\x8a\xa7\x9d\\bJH\xa6\xd9\xb2\xbew\x84\x8a\\020\xca\x9cX^\x87\\026CE\xda\xe9\xa6a', $key = class Defuse\\Crypto\\Key { private $key_bytes = '2\x8c\xa9\xab\x9d\xf4f\\v/O\x9c\xab{\\027c\xac\xbe\\nr\xc9\x9f\\n\xbc\xf6\xf3\xd2W\x9f9E[\xe3' }, $raw_binary = TRUE) /var/www/TeamPass/includes/libraries/Encryption/Encryption/RuntimeTests.php:104, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.067823 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   8. Defuse\\Crypto\\Crypto::decryptInternal($ciphertext = '\xde\xf5\\002\\000\xf96\xb7\xa4?\\0012\xee\xa4\xfe\xa53\x98Si\xae\xd6\xfd\xb9\x9d\\ni\x9ew\\003\x8bY\xfa\x98\\033\x97\xb7\xb8jl\x9df\x9b8\xe1\xa9c$\xa1/\xb6\xf8=\\017\xcb\xc2\xe4\xaef\xd9$i3\x80HX\xbfl\xcdry\xbe@\\002\xd3\xa8\xa1\xda(\x8a\x8a\xa7\x9d\\bJH\xa6\xd9\xb2\xbew\x84\x8a\\020\xca\x9cX^\x87\\026CE\xda\xe9\xa6a', $secret = class Defuse\\Crypto\\KeyOrPassword { private $secret_type = 1; private $secret = class Defuse\\Crypto\\Key { private $key_bytes = '2\x8c\xa9\xab\x9d\xf4f\\v/O\x9c\xab{\\027c\xac\xbe\\nr\xc9\x9f\\n\xbc\xf6\xf3\xd2W\x9f9E[\xe3' } }, $raw_binary = TRUE) /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php:73, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.068010 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP Defuse\\Crypto\\Exception\\WrongKeyOrModifiedCiphertextException:  Bad version header. in /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php on line 236, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.068018 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP Stack trace:, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.068023 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   1. {main}() /var/www/TeamPass/install/install.queries.php:0, referer: http://teampass.cdg44.fr/install/install.php
[Wed Nov 15 14:32:34.068031 2017] [:error] [pid 15236] [client 172.16.3.250:58882] PHP   2. encryptFollowingDefuse($message = 'tVceoWiaAce7spps', $ascii_key = 'def000001c5d069d6224eb4914e83c5d9b018dad49d8ed9ea30b88f67e86ff7c75a2d5986598d9b2d0601c25dd7cd6498f974f0d6d86c46c87e99c888d37ead05b830b42') /var/www/TeamPass/install/install.queries.php:1074, referer: http://teampass.cdg44.fr/install/install.php`

**Comment by nilsteampassnet** [comment]
Can you share your screen with teamviewer?
Contact me now by email if you want

**Comment by nilsteampassnet** [comment]
I'm closing it
Please reopen if needed
