### ISSUE TITLE
Pages apart from information load slow

### ISSUE THREAD

**Issue by MSe-5-14** [nilsteampassnet/TeamPass#1991]
When you login as admin, any menu item you press from the information page is extremely slow to load (+/-30sec). when I disable Show software news and information to admins; everything loads quickly. I had a quick look through the php files and as far as i can tell the admin.queries.php (line 113) is trying to access a page that doesnt exist http://teampass.net/teampass_ext_lib.txt

### Steps to reproduce
1. enable "Show software news and information to admins"
2. go to information page
3. click on any other menu item

### Expected behaviour
On the tab information about this software, something should appear. Other menu item should load quickly

### Actual behaviour
No information is shown under information about this software and all the menu items are slow.

### Server configuration
**Operating system**:
Windows 2012 R2
**Web server:**
IIS 8.5
**Database:**
Mariadb 10.2.9
**PHP version:**
7.1.10
**Teampass version:** 
2.1.27.9
**Teampass configuration file:**

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1430991/tp.config.php.txt)

### Client configuration
**Browser:**
Firefox ESR 52.4.0 (32-bit)
**Operating system:**
Windows 7 Sp1
#### Web server error log

there are no errors in error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

![image](https://user-images.githubusercontent.com/31540586/32228635-11d522f0-be4f-11e7-996c-9209bbafe76d.png)

**Comment by nilsteampassnet** [comment]
I will check this

**Comment by MSe-5-14** [comment]
I just installed teampass on debian server and the problem does not occur.  The page just displays the line "Information about this software" and nothing else. No spinning wheel like on windows/iis... should it display something more ?

**Comment by nilsteampassnet** [comment]
YEs my testing environment is also on debian and it is the reason my tests results were ok.
Indeed for testing this, I'm using a timer and it was normal but indeed nothing is shown.

I will fix this in a  next release.
It should show the latest official version and some info regarding used libraries.
