### ISSUE TITLE
Salt Key requirements

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#1993]
is there a function to set a password policy for the salt key? When we are using a 1 for example as salt key, then it will be accepted and this is too simple in our opinion. 

Can we build a password policy and a control that looks if a user has met the password policy when that user is going to create a salt key?

**Comment by nilsteampassnet** [comment]
Is your question about the "personal saltkey"?

If yes, you are right, no policy exists and could be added.

**Comment by mreinders** [comment]
Yes, it is. So where can we add that policy?

**Comment by nilsteampassnet** [comment]
As written just below, "no policy exists and could be added" (as a Feature Request).

**Comment by mreinders** [comment]
When we adding the code, we have to reinstall the teampass app, that's possible but when the installation is finished then the proces starts again. How can we finish the installation?
