### ISSUE TITLE
Export Doesn't work

### ISSUE THREAD

**Issue by ets553** [nilsteampassnet/TeamPass#1994]
### Steps to reproduce
1. Log into Teampass
2. left-click on folder
3. left-click on three bars and select "Export Items"

### Expected behaviour
Unknown, I haven't gotten it to work.  

### Actual behaviour
A window pops up with the title "Export items" and the gear spins endlessly
![image](https://user-images.githubusercontent.com/6654718/32298872-ea5f417a-bf29-11e7-92aa-b5961d637956.png)
The "Close" button works, but the export button doesn't.
### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
5.7.20-0ubuntu0.16.04.1
**PHP version:**
7.0.22-0ubuntu0.16.04.1
**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

This produces a blank page

PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome or IE11
**Operating system:**
Server 2016
#### Web server error log
Error log is empty

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This bug has been fixed in `development` branch.
I will provide a new package soon.

**Comment by ets553** [comment]
Thank you!

**Comment by abullones** [comment]
Hello, does this issue have a workarround already?
