### ISSUE TITLE
Some settings resets to defaults

### ISSUE THREAD

**Issue by cheechmarino** [nilsteampassnet/TeamPass#1996]
### Steps to reproduce
1. Clean TeamPass 2.1.27.9 installation
2. Go to settings and set your TimeZone (except UTC)
3. Change LDAP port to 636. TimeZone will fall back to UTC
4. or enable "Encrypt file attachments". TimeZone will fall back to UTC
5. or set LDAP port to 636 and then set your TimeZone (except UTC). LDAP port will fall back to 389
6. or enable "Encrypt file attachments" and then set your TimeZone (except UTC). "Encrypt file attachments" will fall back to OFF.

### Expected behaviour
Settings are saved

### Actual behaviour
Changed setting becomes saved other two settings (maybe more) resets to defaults

### Server configuration
Debian 9.1.0
Apache/2.4.25
mysql  Ver 15.1 Distrib 10.1.26-MariaDB
PHP 7.0+49
Teampass 2.1.27.9
Fresh install

[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1440952/tp.config.zip)

### Client configuration
Chrome, Firefox
Windows 10

**Comment by cheechmarino** [comment]
Just figured out that TimeZone setting disappears from tp.conf.php when enabling "Encrypt file attachments". Basically when one of mentioned above settings is changed two others resets to defaults.

**Comment by nilsteampassnet** [comment]
I've tried a lot of changes here to reproduce but I couldn't.
But I will try to understand how this could happen.

**Comment by nilsteampassnet** [comment]
I think I have found something that could explain this.
I will commit a fix today.

**Comment by cheechmarino** [comment]
After upgrade to https://github.com/nilsteampassnet/TeamPass/commit/3f8e8f4eb0dff5c2e69a63830fb30c4028598aa3 receiving "Browser session expired" error" when logging in (no matter admin or standard user). And after that "403 Access Forbidden by CSRFProtector!"

**Comment by cheechmarino** [comment]
Tryed clen install of https://github.com/nilsteampassnet/TeamPass/commit/3f8e8f4eb0dff5c2e69a63830fb30c4028598aa3
Logged in as admin. Changed configuration: LDAP port to 636 and enabled TLS communication for LDAP.

Now Apache shows error "Got error 'PHP message: PHP Parse error:  syntax error, unexpected ''ldap_port'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/includes/config/tp.config.php on line 120\n'"

**Comment by cheechmarino** [comment]
Sorry, my mistake. Done correct upgrade to latest commit https://github.com/nilsteampassnet/TeamPass/tree/8706a1516b89d49f97c092961acf75a1af456e79 and issues was gone.

Thank You Nils!!!
