### ISSUE TITLE
JSON-Parse failed

### ISSUE THREAD

**Issue by Husky110** [nilsteampassnet/TeamPass#1997]
The issue was existent in Issue [#1935](https://github.com/nilsteampassnet/TeamPass/issues/1935) an was closed and fixed.  
To me it still remains.
I'm using the latest release-tag (2.1.27.9) on Ubuntu 16.04.3 with Apache, MySQL 5.7.20 and PHP 7.1.
Client: Chrome Version 61.0.3163.100
Got the same message after a fresh install (User is manager) - when I try to create a new folder and hit "Save" (Interface is in german), I get this (and nothing happens afterward...):
![image](https://user-images.githubusercontent.com/13180625/32123024-fb1aae34-bb62-11e7-817a-16b3a80dbdb8.png)

**Comment by nilsteampassnet** [comment]
Please provide logs and browser console responses.

I can't reproduce.

**Comment by Husky110** [comment]
Browser on Save:
![image](https://user-images.githubusercontent.com/13180625/32517534-0baff586-c407-11e7-87a2-b7cdc0a92816.png)
![image](https://user-images.githubusercontent.com/13180625/32517561-16f0540e-c407-11e7-9b15-feeed87cfa00.png)
![image](https://user-images.githubusercontent.com/13180625/32517577-2239e5b4-c407-11e7-9fe6-012dcd078b52.png)

Server on Save:
error.log
![image](https://user-images.githubusercontent.com/13180625/32517654-60976c64-c407-11e7-8303-5615fde23391.png)

**Comment by nilsteampassnet** [comment]
The error indicates that a variable "parent_id" is not defined.
But after code review, this is just not possible.
Are you sure to have updated all files?

If yes, then I would need an access to the server with Teamviewer for example.

**Comment by Husky110** [comment]
That would hardly be possible, since it's a linux-server ;)
I'm gonna write you via the contact-form on Teampass.net, so maybe we can talk in the evening via something.

**Comment by nilsteampassnet** [comment]
Closed after screensharing ;)
