### ISSUE TITLE
upgrade TeamPass-2.1.25.2 to TeamPass-2.1.27.9 missing required source file

### ISSUE THREAD

**Issue by BiRo70** [nilsteampassnet/TeamPass#1999]
### Steps to reproduce
follow the documentation directions: [Docs » Installation » Upgrade](https://teampass.readthedocs.io/en/latest//install/upgrade/)

### Expected behaviour
locate the following files
- /includes/config/settings.php
- /includes/config/tp.config.php
- /includes\libraries\csrfp\libs\csrfp.config.php

### Actual behaviour
There is no `/includes/config/` folder in `teampass_old/`
and while I can find `settings.php` and `csrfp.config.php` in the folder `/includes/`, I can't find the file `tp.config.php` anywhere.

### Server configuration
**Operating system**:
`$ lsb_release -d
Description:    CentOS Linux release 7.4.1708 (Core)`

**Web server:**
`$ httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16`

**Database:**
`$ mysql --version
mysql  Ver 14.14 Distrib 5.6.38, for Linux (x86_64) using  EditLine wrapper`

**PHP version:**
`$ php -version
PHP 5.6.31 (cli) (built: Sep 14 2017 18:12:46)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`

**Teampass version:** 
`TeamPass-2.1.25.2` to `TeamPass-2.1.27.9`
**Teampass configuration file:**
???
**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

## Note
Probably if I followed an upgrade path 2.1.25.x -> 2.1.26.x -> 2.1.27.9 I wouldn't miss the file, but I couldn't find any  .tar.gz  with the old version like in the past.
Maybe pointing git from master to something else?

While upgrading I am also trying to move TeamPass to another server which will have a different hostname.

I suppose I will encounter some issue there as well if I do not change manually the content of the csrfp.config.php and of the path records in the table teampass.teampass_misc.

Thanks for your support.

**Comment by nilsteampassnet** [comment]
Yes the guide is written for Teampass version starting at 2.1.26
As written in the 1st page

> Information
> 
> Notice that this user-guide has been written based upon 2.1.26 release.

Those files don't exist in previous versions.

You must upgrade to latest 2.1.26 and after checking every thing is okay, upgrade to 2.1.27

**Comment by BiRo70** [comment]
Thank you Nils.
Sorry I skipped the 1st page and went directly to the upgrade.
Since I can't find the archive with the latest 2.1.26, I suppose I can just git clone the old branch with the same version number, right?
Thanks again for your prompt help.

**Comment by nilsteampassnet** [comment]
You have all releases in the 'Archive' part of this github project.
Latest 2.1.26 is here => https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.26-final-3
