### ISSUE TITLE
How to recover Teampass on another server?

### ISSUE THREAD

**Issue by smartao** [nilsteampassnet/TeamPass#2000]
I'm in the following scenario
I have a production server in real time and do daily backup.
However, I need to simulate a disaster and recovery where a server failure occurs and I need to restore all as passwords on a new server.

when I restore the backup on the same server it works without problems.
But when I restore the backup on another host, all data is imported except passwords.

Is there any further steps to restore on another host?

**Comment by nilsteampassnet** [comment]
You need to ensure that you backup also the sk.php and/or teampass-seckey.txt file

**Comment by smartao** [comment]
Hi

I tried doing this and it did not work.
First, I restored the sk.php and teampass-seckey.txt files from the old server to the new one.
Then I went to teampass's web page to restore the backup, however it returned "HTTP ERROR 500".
Is there a step to a step showing how to do this?

tks!

**Comment by nilsteampassnet** [comment]
You should also adapt the variable jsUrl inside file tp.config.php

**Comment by smartao** [comment]
I checked the files (tp.config.php) and there is no difference. I believe it is because both servers have the same IP and hostname.

What I'm trying to do is:
1 - I install teampass and back up the files and shut down the server.
2 - I create a new server with the same settings (hostname and IP) and restore the backup files.

I do not understand why the restore is not working.

tks

**Comment by nilsteampassnet** [comment]
Sorry, Don't check tp.config.php file but csrfp.config.php one.

**Comment by smartao** [comment]
I tried again and it did not work, what I did was:

1 - I restore the files to your directors
sk.php
teampass-seckey.txt
csrfp.config

2 - Check if all are with the user www-data

3 - I accessed a web interface
But the continuous error: "HTTP ERROR 500".

If it worked step four would restore the database file.

Am I doing it right?

**Comment by nilsteampassnet** [comment]
If you have error 500, then 2 possibilities.
1- csrfp is blocking due to bad configuration. Solution: check consistency of data in csrfp.config.php
2- configuration issue in your apache conf.

**Comment by smartao** [comment]
Hi nilsteampassnet

There can't be some configuration in apache because when I restore the original files of the server the teampass returns to work at the same time.
This error is only occurring when I restore the old server's sk.php, teampass-seckey.txt, csrfp.config.php files.

Is there anything else I can check?

Tks!

**Comment by gimgunwoo** [comment]
hi @nilsteampassnet, I also have the same issue. Below is the apache error log when I get http 500 error.

PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoding::hexToBin() input is not a hex string. in /var/www/teampass/includes/libraries/Encryption/Encryption/Encoding.php:65\nStack trace:\n#0 /var/www/teampass/includes/libraries/Encryption/Encryption/Encoding.php(164): Defuse\\Crypto\\Encoding::hexToBin('def0000087f8bd7...')\n#1 /var/www/teampass/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF0\\x00\\x00', 'def0000087f8bd7...')\n#2 /var/www/teampass/sources/main.functions.php(401): Defuse\\Crypto\\Key::loadFromAsciiSafeString('def0000087f8bd7...')\n#3 /var/www/teampass/sources/main.functions.php(498): cryption('def50200f7b6ff4...', 'def0000087f8bd7...', 'decrypt')\n#4 /var/www/teampass/index.php(78): defuse_return_decrypted('def50200f7b6ff4...')\n#5 {main}\n  thrown in /var/www/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 65

**Comment by gimgunwoo** [comment]
I tried both fresh install and copy the whole teampass directory in an identical environment, the result is same.

**Comment by gimgunwoo** [comment]
I even tried to import a csv file from the original teampass instance, and it gets me another error.

PHP Fatal error:  Uncaught Goodby\\CSV\\Import\\Standard\\Exception\\StrictViolationException: Column size should be 1, but 2 columns given in /var/www/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php:119\nStack trace:\n#0 /var/www/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php(42): Goodby\\CSV\\Import\\Standard\\Interpreter->checkRowConsistency(Array)\n#1 /var/www/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(68): Goodby\\CSV\\Import\\Standard\\Interpreter->interpret(Array)\n#2 /var/www/teampass/sources/import.queries.php(162): Goodby\\CSV\\Import\\Standard\\Lexer->parse('/var/www/teampa...', Object(Goodby\\CSV\\Import\\Standard\\Interpreter))\n#3 {main}\n  thrown in /var/www/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php on line 119, referer: http://192.168.40.50/index.php?page=items

**Comment by nilsteampassnet** [comment]
What is the php version in this new server?
Are ou sure to have all expected extensions loaded?

**Comment by gimgunwoo** [comment]
@nilsteampassnet it's php7.0 on both VMs. All extensions are installed on the first system and it is working fine. there is only one line of the key in teampass-seckey.txt on both systems. No return, no tab and no space.

It was transferred from ubuntu 16.04 to ubuntu 16.04. I installed same versions of packages and teampass.

I just realized that the imported tables have encrypted passwords but they don't seem to be decrypted when I copied the seckey.

**Comment by nilsteampassnet** [comment]
Can we do a teamviewer session?
email me at nils@teampass.net

**Comment by gimgunwoo** [comment]
hi @nilsteampassnet, a senior in the team had solved this.

**Comment by gimgunwoo** [comment]
The solution was to just archive teampass installation and salt key directories, dump db into a sql file, copy them into another host, just untar and import the sql file, then it just works.

**Comment by nilsteampassnet** [comment]
Thank you for your feedback.
This was exactly what I have tried to explained ;)

**Comment by elvisnawa** [comment]
Hi Nils,

Can you please specify what directories to carry over to the new server when restoring a copy to another server.
I have two identical servers on debian, one is configured and the other is new and working. i used the same credetials but different IPs.

PLease detail what directories to dumb and what to change in what files.

At the moment, i copied the /teampass folder and the .sql file. however when i click on restore, the web page clickers and logs me out.

Elvis

**Comment by nilsteampassnet** [comment]
About backups, please read http://teampass.readthedocs.io/en/latest/faq/

Then adapt the path variables in table misc and also in file csrfp.config.php to fit your new server
