### ISSUE TITLE
Upgrade from 2.1.26 using containers

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#2001]
Is there documentation for performing an upgrade from 2.1.26 using containers?  It seems that the expected volume mount point was moved from /teampass to /var/www/html.  I also tried moving the volume mount to /var/www/html, but then there are still many references to /teampass in the other php files.  Is there a clean way to accomplish this?

### Steps to reproduce
1. pull new docker image
2. start container, mounting volume at /teampass

### Expected behaviour
Successful upgrade, web server displays login page

### Actual behaviour
Teampass acts like fresh install and prompts for all config information.

### Server configuration
**Operating system**:  Ubuntu 16.04.3 LTS

**Web server:** N/A

**Database:**  mariadb:latest

**PHP version:** N/A

**Teampass version:** teampass/teampass:latest container

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

#### Web server error log
```
2017-11-08 14:15:32,866 CRIT Set uid to user 0
2017-11-08 14:15:32,866 WARN No file matches via include "/etc/supervisor/conf.d/*.conf"
2017-11-08 14:15:32,887 INFO RPC interface 'supervisor' initialized
2017-11-08 14:15:32,888 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-11-08 14:15:32,888 INFO supervisord started with pid 1
2017-11-08 14:15:33,893 INFO spawned: 'php-fpm' with pid 15
2017-11-08 14:15:33,901 INFO spawned: 'nginx' with pid 16
2017/11/08 14:15:33 [notice] 16#16: using the "epoll" event method
2017/11/08 14:15:33 [notice] 16#16: nginx/1.13.5
2017/11/08 14:15:33 [notice] 16#16: built by gcc 5.3.0 (Alpine 5.3.0) 
2017/11/08 14:15:33 [notice] 16#16: OS: Linux 4.10.0-28-generic
2017/11/08 14:15:33 [notice] 16#16: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2017/11/08 14:15:33 [notice] 16#16: start worker processes
2017/11/08 14:15:33 [notice] 16#16: start worker process 17
2017/11/08 14:15:33 [notice] 16#16: start worker process 18
2017-11-08 14:15:34,979 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-08 14:15:34,979 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by nilsteampassnet** [comment]
No i don't think any documentation exists on this.
But it could be very interesting. Perhaps could you share this once you have succeed?

**Comment by nvtsgit** [comment]
Can you explain what's actually necessary from the persisted volume?  It seems like perhaps too much has been persisted since there are references to the old paths, and simply changing the mount point from /teampass to /var/www/html/www does not really work.

**Comment by aarondobbing** [comment]
Potential workaround would be to create a new dockerfile and symlink the /teampass directory to /var/www/html - Not overly pretty but from the top of my head (Having not run this in a container) - it should work? (Sorry for issue necro)
