### ISSUE TITLE
Suggestion: Set Password-maxlength to 255

### ISSUE THREAD

**Issue by Husky110** [nilsteampassnet/TeamPass#2002]
Heyho   
Just a suggestion this time...  
While I was transfering my passwords to TeamPass, I encountered the error that passwords have a maxlenth of 40 characters.  
This is not good for me, since I use hashes as passwords, which can be waaaaay longer.  
It would be realy nice to have a maxlength of 255 characters.

**Comment by nilsteampassnet** [comment]
You can define longer password if you want from the settings page.
![image](https://user-images.githubusercontent.com/1197546/32573656-fd5d3034-c4ce-11e7-98d1-11f6c48d042d.png)
Default is set to 40 for performance reasons.
Now you can higher it to 255, just consider decryption time but this should not have big impact if you have a good server.
