### ISSUE TITLE
install/upgrade_run_2.1.27.php fails (Probably misnamed function call to mysql_num_rows())

### ISSUE THREAD

**Issue by wirerydr** [nilsteampassnet/TeamPass#2003]
### Steps to reproduce
1. Start an upgrade to development commit 20b5a5a.

### Expected behaviour
Upgrade should complete successfully.

### Actual behaviour
On screen Step 4, upgrade_run_2.1.27.php fails to complte.  Instead it displays "Loop #1 is now running ..." with a spinning gear forever.
An error appears in the httpd logs:
```
[Thu Nov 09 13:34:14.496256 2017] [php7:notice] [pid 14614] [client 192.168.240.120:65462] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_num_rows() in /opt/teampass/teampass__PROD/teampass__20171109-20b5a5a/install/upgrade_run_2.1.27.php:152\nStack t
race:\n#0 /opt/teampass/teampass__PROD/teampass__20171109-20b5a5a/install/upgrade_run_2.1.27.php(199): columnExists('teampass_misc', 'id')\n#1 {main}\n  thrown in /opt/teampass/teampass__PROD/teampass__20171109-20b5a5a/install/upgrade_run_2.1.27.php on line 152, referer:
 https://www.example/tp/install/upgrade.php
```
An examination of the TeamPass codebase indicates that this is the only call to ```mysql_num_rows()``` in the entire project. However numerous calls to ```mysqli_num_rows()``` exist.  Presumably this is a simple function-name typo.

**Comment by nilsteampassnet** [comment]
Yes you are right.
I have included just now for robustifying the upgrade and introduced this mysql function instead of the mysqli.
What I don't understand is that no errors were shown during my test ...

**Comment by wirerydr** [comment]
Re-tested by upgrading to development commit b10561b, which includes your fix mentioned above.  Upgrade completed successfully - closing this issue.  Thanks for the quick fix.
