### ISSUE TITLE
Can not login after upgrade from 2.1.27 to 2.1.27.9

### ISSUE THREAD

**Issue by aostrovsky** [nilsteampassnet/TeamPass#2005]
After I've successfully upgraded I can not log.

Getting error:
Login credentials do not correspond!

Please help.

**Comment by aostrovsky** [comment]
Tried the same but with 2.1.27.8.
Same thing.

**Comment by aostrovsky** [comment]
I've tried to upgrade to 2.1.27.2 instead.
Got success and was able to login.
But all passwords has alert sign and error 'Error Encrypting password'

**Comment by aostrovsky** [comment]
With 2.1.27.9 if I put wrong password I am getting 'Number of login attempts 6'. So that means login is fine.

**Comment by nilsteampassnet** [comment]
Please use the development branch instead of 2.1.27.9.

**Comment by aostrovsky** [comment]
Ok. Thank you
Was able to upgrade 2.1.27.7.
But again I do have 'Error Encrypting password' for all items.
Will that work in Dev ?

**Comment by aostrovsky** [comment]
I've tried to install from 'development' and got 'Login credentials do not correspond'

**Comment by nilsteampassnet** [comment]
Something must be wrong somewhere in the way to proceed.
Let me have a look to help
