### ISSUE TITLE
Session runs out too early

### ISSUE THREAD

**Issue by Husky110** [nilsteampassnet/TeamPass#2007]
When I login into TP and set a Sessiontimeout for 600 minutes and I leave TP for like 1 hour and do something, I get a JS-alert "Hacking attempt" and nothing is working anymore. I have to relog in.

**Comment by srihas619** [comment]
I have the same problem as well.

**Comment by nilsteampassnet** [comment]
PLease check your PHP settings.
THis is related to your configuration of sessions on your computer.
Perhaps in relation with gc_maxlifetime

**Comment by Husky110** [comment]
Then why set the session-time-field at all?
Or why not max it out on the php-config value (since it's a numberinput)?

**Comment by nilsteampassnet** [comment]
Because this is just a suggestion of investigation.
If you could confirm that this setting has an impact, then I will implement the change.

**Comment by dwratex** [comment]
I can confirm adjusting session.gc_maxlifetime resolved this problem for us. Thanks!

**Comment by nilsteampassnet** [comment]
@dwratex, please can you explain us waht are the changes you did?

Thank you

**Comment by dwratex** [comment]
php.ini session.gc_maxlifetime defaults to 1440 seconds (24 minutes). Teampass session was always timing out before its own default, even if user was 'active' in browser.  We set to 43200 (12h) and restarted apache2.  No other changes. This seems to have returned 'control' to Teampass settings.   Thanks - dw

**Comment by nilsteampassnet** [comment]
This change has been confirmed.
Documentation was updated => http://teampass.readthedocs.io/en/latest/errors/#users-and-folders-lists-are-empty

Thank you @dwratex
