### ISSUE TITLE
Access to password item denied!

### ISSUE THREAD

**Issue by tadela** [nilsteampassnet/TeamPass#2008]
### Expected behaviour
A few days after the installation and data entry. My stickers are yellow and I click on them to write: Access to password item denied! i can't see any passwords on teampass.
https://ibb.co/fBDWtG

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
CentOS7.4.1708
**Web server:**
Apache/2.4.6
**Database:**
5.5.56-MariaDB
**PHP version:**
PHP 5.6.31
**Teampass version:** 
 2.1.27.9
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 16.04 LTS

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
After few days my passwords have yellow labels and write : Access to password item denied!

**Comment by nilsteampassnet** [comment]
hum where are the details?

**Comment by tadela** [comment]
Updated

**Comment by nilsteampassnet** [comment]
Very strange.

There must have been something done on the configuration, or you have set up a configuration in Teampass that I have not thought about.

Can you please try updating by using the development branch?

Or please provide an access by Teamviewer.

**Comment by tadela** [comment]
Hello, i updated to 2.1.27.10 version, but this not help for me.
Maybe, can you connect via teamviewer?

**Comment by zoltancsoka** [comment]
Hi, I have the same issue. The passwords were working fine and suddenly without any reason or rhyme they started to show in yellow and whatever we do, we cannot show them anymore (Access to password item denied). This morning I have upgraded to the latest version (2.1.27.16), but did not change anything. Apache logs show no error and even the access log has only 200 answers.

**Comment by nilsteampassnet** [comment]
Yes the upgrade doesn't change anything add this seems to be related to the items.
Any how it is good to have updated.

Can you provide me an access to your server ?
Please contact me at Nils@teampass.net

**Comment by zoltancsoka** [comment]
In the meantime I have analysed the DB and realised, that the personal flag was set on those items. I heve set the perso to 0 and the passwords were working again. My problem is solved.

**Comment by fabricat** [comment]
Removing the personal flag worked also for me.
I don't know if it is optimal, however this is this query I ran:
`update teampass_items set perso = 0 where perso = 1 and id_tree in (select id from teampass_nested_tree where title not like '1000%');`
