### ISSUE TITLE
Not able to change pass. 

### ISSUE THREAD

**Issue by aostrovsky** [nilsteampassnet/TeamPass#2009]
I am not able to change own password or any other user.
New user created.
Password defined.
But he can not login.

While I am changing own password getting error:
'Requested JSON parse failed.'

No errors in Apache log.
Any way to pass thru?

PHP: 5.5
Apache: 2.4
Teampass: 2.1.27

**Comment by nilsteampassnet** [comment]
You must have a configuration issue or some specific usecase.

Could we have a shared screen session?

**Comment by aostrovsky** [comment]
Sure
Let me know when you are available.

**Comment by aostrovsky** [comment]
Any chance we can look into that?

**Comment by nilsteampassnet** [comment]
Contact me at nils@teampass.net
