### ISSUE TITLE
Default Administrated by

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#2010]
Hello Nils,

We have a problem with the manager role. When a user is created managers can't manage users with their managers role. When we look in de Administrator role the user has been created nad can only be managed by the administrator role. Is it possible to change the default Administrated by function to  the Managers role?

Thanks in advance!

**Comment by nilsteampassnet** [comment]
Hello

What version do you use?

When creating a new user, you have a a field permitting to select the Managers of this new user.
By default it is set to the current Manager
![image](https://user-images.githubusercontent.com/1197546/32670562-724dbd2a-c644-11e7-83e2-526bbb35abef.png)

Thant leads to the new user added in the list of users belonging the current manager
![image](https://user-images.githubusercontent.com/1197546/32670615-9b73d1a8-c644-11e7-8156-466dbdc9c132.png)

**Comment by mreinders** [comment]
We are using the 2.1.27 branch with ldap support. When a user logs on for the first time, then he or she will be managed by the Default role administrators. Is it possiblke to select another default group?

**Comment by nilsteampassnet** [comment]
ah ok, so it means that the user is created at 1st login.
Ok I will check if I can improve this.

**Comment by nilsteampassnet** [comment]
I've implemented this change.
In LDAP tab, you now have a new select field permitting to select the default group that will administrate the newly created users.
![image](https://user-images.githubusercontent.com/1197546/32687361-abe99f10-c6ba-11e7-8a13-4a1dd027af1b.png)
