### ISSUE TITLE
Double-entries

### ISSUE THREAD

**Issue by Husky110** [nilsteampassnet/TeamPass#2012]
Sometimes I see elements twice, but when I click on one of them, only the source-element is beeing highlighted. Page reload didn't solve this issue.

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1
**Teampass version:** 
2.1.27

### Client configuration
**Browser:**
Google Chrome  62.0.3202.89
**Operating system:**
Windows 7

**Comment by Husky110** [comment]
I could resolve it, by redragging the faulty element into the folder where it is. 
Might still be a bug...

**Comment by Husky110** [comment]
Yep - it's still a bug. This happens when I add multiple elements to a new folder.

**Comment by nilsteampassnet** [comment]
Could not reproduce.
With no page refresh, I have created folder and 4 new items inside it.
![image](https://user-images.githubusercontent.com/1197546/32802123-67e88caa-c97f-11e7-9156-5559e5b125a7.png)
You must do it in a specific way ... can you please explain how to reproduce

**Comment by Husky110** [comment]
Try something like 10 or 15 items. It happens only sometimes.

**Comment by nizedk** [comment]
We see this as well. After starting up with the product and adding about 70 items in 3 folders, users often if not always see random items twice. We can now just enter the product and one of us will spot a double item if we look carefully. Examining the database confirms there is only 1 item.

2.1.27.15/docker image - mysql/5.7.22 - Chrome Version 67.0.3396.79 64bit

It appears that it might be related to the population of items the list; I get the impression that the double item appears around the point in the list where the visible items end (so if I scroll, the double item will be roughly immediately after 'the next page' of items'). I cannot do this consistently, but it has appeared like that a couple of times now, when I deliberately work with very large and very small browser windows.

Seen in Internet Explorer 11.48.17134.0 as well. So far failed to reproduce in Firefox (will update if seen)

What can we do to assist in troubleshooting?
