### ISSUE TITLE
After upgrade in 2.1.27, authentication problem

### ISSUE THREAD

**Issue by Hellnino18** [nilsteampassnet/TeamPass#2013]
Hi @nilsteampassnet ,

In reference at #1989 , I tried your new release 2.1.27.10 (from 2.1.26), and I have always the same problem. Nothing happens when I try to connect (with local user or LDAP user). 

After upgrade, I looked into teampass users table, and user_ip column doesn't still exists.

I have added by hand with : 

ALTER TABLE teampass_users ADD user_ip VARCHAR(400) NOT NULL DEFAULT 'none';

And after that the connection with both users works well. I think there is still a problem with your upgrade script. Could you see what happens plz ?

Thanks.

**Comment by Hellnino18** [comment]
If you change in your upgrade script (upgrade_run_2.1.27.php), inversion of true and false : 

```
function columnExists($tablename, $column)
{
    global $db_link;
    $checkcolumn = mysqli_query($db_link, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='{$tablename}' AND COLUMN_NAME = '{$column}';");
    if (mysqli_num_rows($checkcolumn) > 0) {
        return false;
    } else {
        return true;
    }
}
```
In : 

```
function columnExists($tablename, $column)
{
    global $db_link;
    $checkcolumn = mysqli_query($db_link, "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='{$tablename}' AND COLUMN_NAME = '{$column}';");
    if (mysqli_num_rows($checkcolumn) > 0) {
        return true;
    } else {
        return false;
    }
}
```
user_ip column is created in users table (line 588), and increment_id is also created in misc table (line 208).

With this change, I think line 620 is not good too (and maybe isn't needed) : 

```
// alter table MISC
mysqli_query(
    $db_link,
    "ALTER TABLE `".$pre."misc` ADD `id` INT(12) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);"
);
```

What do you think about this modification Nils ?

**Comment by nilsteampassnet** [comment]
You are totally right

I fix and commit this.

**Comment by nilsteampassnet** [comment]
New package of 2.1.27.10 available

**Comment by Hellnino18** [comment]
It's working now
