### ISSUE TITLE
User or folders list not appearing after upgrade to 2.1.27.10

### ISSUE THREAD

**Issue by Backstreets** [nilsteampassnet/TeamPass#2014]
### Steps to reproduce
1. Upgrade from 2.1.27.9 to 2.1.27.10
2. login with admin or any user with users managing priveleges
3. Go to Manage Users or Manage Folders

### Expected behaviour
User list or folder list should appear

### Actual behaviour
the list is empty

### Server configuration
**Operating system**:
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.6

**Web server:**
Nginx included on Teampass 2.1.27.9 oficial Docker container 

**Database:**
mysql

**PHP version:**
Php included on Teampass 2.1.27.9 oficial Docker container 

**Teampass version:** 2.1.27.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**  updated from 2.1.27.9
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Both IE11  and Chrome Versión 62.0.3202.89  have the same behaviour 

**Operating system:**
Windows 10 

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Backstreets** [comment]
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1467880/tp.config.txt)

**Comment by nilsteampassnet** [comment]
Can you provide an access by teamviwer?

**Comment by nilsteampassnet** [comment]
Contact me by email now I have a couple of minutes before lunch

**Comment by Backstreets** [comment]
give me 1 min and I'll send you the info

**Comment by nilsteampassnet** [comment]
Seen with @Backstreets 
Now fixed on the configuration.

**Comment by vanitalo** [comment]
I'm trailing a new install and have the same problem. If I access teampass via localhost I can admin all folders and users, but if I access it from another computer via IP address it doesn't show the folders ans users in the admin screens.

**Comment by Backstreets** [comment]
In my case, I was using the ip address of the server (instead of the server name) for these options on Settings page:

TeamPass location (URL)
Upload folder (URL)
 Files folder (URL)
Favicon (full URL)


ie:  we changed those from   https://x.x.x.x   to https://teampass.mycompany.com,  This last one is the address I use to open teampass on the browser.

Hope it helps!

**Comment by vanitalo** [comment]
Thanks, I think this is the issue for me as well as I installed it as https://localhost/teampass instead of a qualified domain. This is only a test install in a VirtualBox for now so I'll be sure to setup under a qualified address next time.
