### ISSUE TITLE
Double click to edit not working for items created by a different user

### ISSUE THREAD

**Issue by yavin48** [nilsteampassnet/TeamPass#2015]
### Steps to reproduce
1. Create two normal users (User1 and User2) and place them in the same group (Group1)
2. Create an item as User1 and set "restricted to" to "Group1"
3. Log in as User2 and attempt to edit the item by double clicking on it

### Expected behaviour
User2 should get the edit box when double clicking on the item

### Actual behaviour
Nothing happens when they double click. They have to select the item, and then chose "edit" from the drop down menu. This is the same if you reverse the users (have User2 create something and have User1 double click on it).

### Server configuration
**Operating system**:
sles 12 sp2
**Web server:**
Apache/2.4.23
**Database:**
mysql  Ver 15.1 Distrib 10.0.30-MariaDB
**PHP version:**
7.0.7
**Teampass version:** 
2.1.27.10
**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration
**Browser:**
Chrome and Firefox
**Operating system:**
Opensuse, Windows 7, Windows 10
#### Web server error log
There are no errors in the web logs

**Comment by sshipway** [comment]
I can confirm I have seen this too while testing.  I had thought it was caused by my switching from local passwords to LDAP and so did not report it then.

**Comment by yavin48** [comment]
The update fixed this issue. Thank you!
