### ISSUE TITLE
Not all roles visible

### ISSUE THREAD

**Issue by Husky110** [nilsteampassnet/TeamPass#2016]
Hello,

I need an urgend fix for this...  
As a sysadmin I can see 8 roles at max and not all.  
I could find nothing that would indicate a pagination.  
Pls help!
![image](https://user-images.githubusercontent.com/13180625/32881007-f6e634da-caaf-11e7-93f8-921c29188112.png)
(In the image there should be a role THO visible, but it's not...)

**Comment by nilsteampassnet** [comment]
I have fixed.
New 2.1.27.10 package available.

Only overwrite existing files
