### ISSUE TITLE
Error login for a account with admin privilege when use DUO security

### ISSUE THREAD

**Issue by Bocholand** [nilsteampassnet/TeamPass#2017]
I have activated the 2FA with DUO security.
I deleted the account 'admin' and I create other account with admin privilege.

I can login a user account.
When I login a admin account, I connect but I redirect to https://url.com/index.php?page=items and a message say 'You are not allowed to see this page.'. After, I is redirected to login page

### Steps to reproduce
1. connect to admin account
2. validate with DUO Securty
3. Message error
4. Login page

### Server configuration
Operating system:  Fedora 26
Web server : Apache/2.4.29 (Fedora)
Database : mysql  Ver 15.1
PHP version : PHP 7.1.11
Teampass version: 2.1.27.10
Updated from an older Teampass or fresh install: 2.1.27.9

**Comment by nilsteampassnet** [comment]
Yes I confirm a bug in DUO auth.
This part was not retested due to test environment broken but I didn't seen it (result was ok but not run).

I will fix it

**Comment by nilsteampassnet** [comment]
The case you are describing after authentication with DUO is normal.
Indeed an Admin cannot access the items.
Please check => http://teampass.readthedocs.io/en/latest/install/setup/#administrator-account

This by-default behavior can be changed using the protocal explained in this same page.

**Comment by Bocholand** [comment]
Thanks, I can log in as my account with admin privilege.

**Comment by gregulator85** [comment]
I also have the same problem using my domain administrator account via LDAP and DUO with the administrator role enabled.  But if I click on any of the administrator areas it takes me back to the login screen.  Is there a way to have administrator role enabled accounts redirect to /index.php?page=manage_main upon login?

![image](https://user-images.githubusercontent.com/7906169/33771936-8da9f02e-dbf8-11e7-9cb5-1f6d2cb6ebb6.png)

**Comment by nilsteampassnet** [comment]
What version of teampass do you use ?

**Comment by gregulator85** [comment]
2.1.27.10
