### ISSUE TITLE
folder personal error when creating personal item

### ISSUE THREAD

**Issue by artesin** [nilsteampassnet/TeamPass#2018]
**Steps to reproduce**

Select folder personal
 when creating personal item
create the element throwing the error
also when wanting to visualize the created item gives the same error

**Expected behaviour**

create, modify, delete, visualize the elements of the personal folder gives syntaxerror error

Actual behaviour

create, modify, delete, visualize the elements of the personal folder gives syntaxerror error

**Server configuration**

Operating system:CentOS Linux release 7.3.1611

Web server: httpd.x86_64 2.4.6

Database: mariadb 5.5.52

PHP version: 5.5.38

Teampass version: 2.1.27.0

Updated from an older Teampass or fresh install: Update from TeamPass-2.1.26-final-3

Client configuration

**Browser:**Newest Firefox

**Operating system:**Windows 7 64Bit

Logs

Web server error log

We don't have any errors in the log File

**Comment by nilsteampassnet** [comment]
Not sure to understand the reproducing steps.

Your context is that you migrated from 2.1.26 to 2.1.27.0? you should use the last one 2.1.27.10.
Restart upgrading from your backup of 2.1.26

**Comment by nilsteampassnet** [comment]
No news.
I'm closing it
Please reopen if needed

**Comment by artesin** [comment]
No, it was an installation from scratch with the latest version available for download.

I apologize for the delay but I did not get the notice of your response.

regards
