### ISSUE TITLE
mcrypt and PHP 7.2

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#2019]
Hello.

What about deprecated mcrypt for PHP 7.2?
https://blog.remirepo.net/post/2017/11/14/End-of-FTBFS-marathon

What is your future plans to deal with it? :)

Regards.

**Comment by nilsteampassnet** [comment]
Thank you for this reminder.

Teampass since 2.1.27 doesn't need mcrypt extension.
It will be kept for users with older version until PHP7.2 is fully deployed and defined as the standard version.
