### ISSUE TITLE
Mysql error with Percona XtraDB and pxc_strict_mode

### ISSUE THREAD

**Issue by electrical** [nilsteampassnet/TeamPass#2020]
With Percona XtraDB and pxc_strict_mode enabled it won't insert anything into tables that don't have indexes defined.

```
2017-11-17T09:20:22.519783Z 8 [ERROR] WSREP: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass._install) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

Can the tables be modified to have at least a primary key?

**Comment by nilsteampassnet** [comment]
yes I think so.

It will be an improvement.

**Comment by electrical** [comment]
@nilsteampassnet Seems we are still missing some keys:

- teampass_items_edition
- teampass_cache

Would you be able to add a key to them so I can continue testing?

Thanks!
```
* 14/03/2018 16:11:05 - Query: DELETE FROM `teampass_items_edition` WHERE item_id = 6<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_items_edition) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:11:01 - Query: INSERT INTO `teampass_items_edition` (`timestamp`,`item_id`,`user_id`) VALUES (1521043861, '6', '10000002')<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_items_edition) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:10:31 - Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`tags`,`url`,`id_tree`,`perso`,`restricted_to`,`login`,`folder`,`author`,`timestamp`) VALUES ('6', 'test', 'test', 'None', '0', '6', '0', '0', 'test', 'Systems', '10000002', '1521043831')<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_cache) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:09:46 - Query: DELETE FROM `teampass_items_edition` WHERE item_id = 3<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_items_edition) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:09:27 - Query: INSERT INTO `teampass_items_edition` (`timestamp`,`item_id`,`user_id`) VALUES (1521043767, '3', '10000002')<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_items_edition) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:09:05 - Query: INSERT INTO `teampass_items_edition` (`timestamp`,`item_id`,`user_id`) VALUES (1521043745, '3', '10000002')<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_items_edition) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
 * 14/03/2018 16:08:23 - Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`tags`,`url`,`id_tree`,`perso`,`restricted_to`,`login`,`folder`,`author`,`timestamp`) VALUES ('3', 'noc item 1', '', 'None', '0', '3', '0', '0', '', 'NOC', '10000002', '1521043703')<br />Error: Percona-XtraDB-Cluster prohibits use of DML command on a table (teampass.teampass_cache) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER<br />@ /sources/items.queries.php
```

**Comment by nilsteampassnet** [comment]
DO you use 2.1.27.11? or at least a recent commit of `development` branch ?

Those tables have indexes
![image](https://user-images.githubusercontent.com/1197546/37428751-85ce96c2-27cd-11e8-955c-5518ee0e6fe0.png)

![image](https://user-images.githubusercontent.com/1197546/37428764-9246c6a4-27cd-11e8-9ee3-67d4382aa2f1.png)

**Comment by electrical** [comment]
Hi, I used the latest version in the master branch. Will try out the development branch.

**Comment by electrical** [comment]
Hi,

I've deployed the development branch and still fails on the same tables.
The difference I can see is that these are keys but not Primary keys like some other tables have.

Sorry for the confusion.

**Comment by electrical** [comment]
More details:

https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#tables-without-primary-keys

**Comment by nilsteampassnet** [comment]
Can you share the last errors you get with percona?
Typically cache table has a primary key with `increment_id`

**Comment by electrical** [comment]
@nilsteampassnet  I see you have the index creation in the upgrade script ( https://github.com/nilsteampassnet/TeamPass/blob/development/install/upgrade_run_2.1.27.php#L393 ) but its not in the install.queries.php file for a fresh install.

For the items_edition table there is a KEY defined but not a PRIMARY KEY
https://github.com/nilsteampassnet/TeamPass/blob/master/install/install.queries.php#L862

**Comment by nilsteampassnet** [comment]
You are right!

Thanks

**Comment by electrical** [comment]
@nilsteampassnet Just tried out the development branch.

https://github.com/nilsteampassnet/TeamPass/commit/ed39924c807e9e16d9d29d9d01d1c879f08b85a1#diff-ce2621edef28c092ab14c7a871f3fa1eR708

introduced the 'FIRST' keyword but fails when creating the table. It hasn't been used anywhere else. Perhaps useful to remove it?
After creating the table without the 'FIRST' keyword it all worked.
I'll be doing some more testing to ensure it all works

**Comment by nilsteampassnet** [comment]
Good to read.
I don't know why I added this FIRST here as it has nothing to do here in this context.
I'm mixing with another project.

**Comment by electrical** [comment]
No worries :-)
Done some more testing and things are looking good.
One other thing i found is that the following 2 tables don't have Primary keys either:
```
export
restriction_to_roles
```

**Comment by electrical** [comment]
Looks like we can close this issue, all tables have required PRIMARY key's and install seems to have worked fine.
If I run into other DB related issues I'll create an other ticket.
Thank you for your support on fixing this!

**Comment by marcelin** [comment]
I've solve this issue using this link  https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html

You just have to type this command: mysql> SET GLOBAL pxc_strict_mode=PERMISSIVE;

**Comment by electrical** [comment]
@marcelin I know that's possible but not recommended way of doing it :-)
