### ISSUE TITLE
Teampass Connect not available for Firefox Quantum 57.0

### ISSUE THREAD

**Issue by colinreginstereproseed** [nilsteampassnet/TeamPass#2022]
Hi,

Teampass Connect not available for Firefox Quantum 57.0.

Team pass connect is not avaimable for the latest version of firefox

Thank you,
Colin

**Comment by nilsteampassnet** [comment]
I'm finishing release 2.1.27 and jump to TPC.

**Comment by Park0** [comment]
Is there a repo for Teampass Connect or anything where we can see the process / contribute?

**Comment by JulienChampseix** [comment]
@nilsteampassnet is there an update of Teampass Connect for latest version of Firefox (62.0.3) ? or plugin totally deprecated ?

**Comment by nilsteampassnet** [comment]
TPC is available for FF -> https://teampass.net/teampassconnect.html
