### ISSUE TITLE
Access to password item denied after login to TeamPass 

### ISSUE THREAD

**Issue by mserer** [nilsteampassnet/TeamPass#2026]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
After login to TeamPass Access to password item denied message appeared, while browsing folders message goes, also if I click search tab and go back to password tab message also appear. Clean installation with test folders/items, two users with manager privileges.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system:**
Ubuntu 16.04

**Web server:**
Apache/2.4.18

**Database:**
MySQL 5.7.20 

**PHP version:**
PHP 7.0.22

**Teampass version:** 
2.1.27.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Mozzila Quantum 57.0 (x64)

**Operating system:**
Ubuntu 16.04.1

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Can you do a screenshot?
Have you correctly set the rights on your user and group?
Make also screenshots of Users tab, Roles/Folders matrix

**Comment by mserer** [comment]
Thanks for reply, sceenshots in att.
![teampass_folders](https://user-images.githubusercontent.com/33900693/33162432-cace3d3c-d029-11e7-8dfb-73827cfe303c.JPG)
![teampass_login](https://user-images.githubusercontent.com/33900693/33162433-cb0fe156-d029-11e7-9b73-6d87489ffc47.JPG)
![teampass_roles](https://user-images.githubusercontent.com/33900693/33162434-cb30f3be-d029-11e7-8f59-ffbfe96fcea0.JPG)
![teampass_users](https://user-images.githubusercontent.com/33900693/33162435-cb513a98-d029-11e7-9e03-1ef0232f5995.JPG)
![teampass_users_edit_account](https://user-images.githubusercontent.com/33900693/33162436-cb8713d4-d029-11e7-93f4-da1302da0fe0.JPG)

**Comment by mserer** [comment]
This is part of log from apache2 access.log file...as I can see I have HTTP status code 200 423...

![image](https://user-images.githubusercontent.com/33900693/33163770-41a6769e-d030-11e7-949b-b4ff1b3efdf0.png)

**Comment by mserer** [comment]
explanation of 423 status code -> The server rejects the request because one of the requested resources is locked (code 423 Locked is received).

**Comment by nilsteampassnet** [comment]
Can you share the error log from apache?

**Comment by mserer** [comment]
Sure I can, but this is log event from another situation not this one...

[Thu Nov 23 06:25:02.059469 2017] [ssl:warn] [pid 5268] AH01906: 192.168.141.7:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Nov 23 06:25:02.059679 2017] [mpm_prefork:notice] [pid 5268] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Nov 23 06:25:02.059688 2017] [core:notice] [pid 5268] AH00094: Command line: '/usr/sbin/apache2'
[Thu Nov 23 08:19:44.242938 2017] [mpm_prefork:notice] [pid 5268] AH00169: caught SIGTERM, shutting down
[Thu Nov 23 08:20:48.053744 2017] [ssl:warn] [pid 1186] AH01906: 192.168.141.7:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Nov 23 08:20:50.774308 2017] [ssl:warn] [pid 1187] AH01906: 192.168.141.7:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Nov 23 08:20:50.789302 2017] [mpm_prefork:notice] [pid 1187] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Nov 23 08:20:50.789419 2017] [core:notice] [pid 1187] AH00094: Command line: '/usr/sbin/apache2'

**Comment by nilsteampassnet** [comment]
In that case it is not useful ;)

Open the brower console, select the "network" tab and try to reproduce the event.
You should see in the console a query is launched.
Please click it, select "answer" tab and we should have a set of errors.

If not, You should run this query in mysql:
`SELECT label FROM `teampass_log_system` WHERE type="error" ORDER BY date DESC`
and share the result

**Comment by mserer** [comment]
| Query: SELECT * FROM teampass_roles_title WHERE id IN ()<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1<br />@ /teampass/sources/roles.queries.php |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0,00 sec)

**Comment by nilsteampassnet** [comment]
Can you share your screen with teamviewer?
Contact me by email

**Comment by mserer** [comment]
What is your e-mail address?

**Comment by mserer** [comment]
Sorry for delayed response, as I can see problem was in one of my test entry, so I deleted entries and recreate users and tested again, message so far did not appear again.

**Comment by nilsteampassnet** [comment]
OK.
Please reopen if occurring again, could be interesting to check what happened.

**Comment by ronil21** [comment]
Hi, I have the same issue. Can you help me?

Thanks

**Comment by rodnertj** [comment]
Good afternoon, NILS, okay?

	I come through this request your help with Teampass, I created a Docker Container CentOS 7, and after downloading this container, I can no longer see the passwords of my intes, remembering that I have everything exposed on my host, bank and teampass itself, my docker-compose.yml looks like this:


version: "2"
services:
  teampass:
    image: teampass/teampass:latest
    container_name: teampass
    restart: always
    volumes:
      - "/opt/docker/scripts/teampass/teampass-instalado:/var/www/html"
      #- "/opt/docker/scripts/teampass/teampass-seckey.txt:/var/www/html/teampass-seckey.txt"
    ports:
      - "8070:80"
    environment:
      - "CATTLE_DB_CATTLE_MYSQL_HOST=192.168.0.32"
      - "CATTLE_DB_CATTLE_MYSQL_PORT=3306"
      - "CATTLE_DB_CATTLE_MYSQL_NAME=teampass"
      - "CATTLE_DB_CATTLE_USERNAME=teampass"
      - "CATTLE_DB_CATTLE_PASSWORD=Pa55@w0rd1"
    volumes:
      - "/opt/docker/data/mysql:/var/lib/mysql"

NOTE: When I start the container with the "docker-compose up d" it asks to do the whole installation.

Thanks in advance and help.

**Comment by rodnertj** [comment]
Good afternoon, NILS, okay?

I come through this request your help with Teampass, I created a Docker Container CentOS 7, and after downloading this container, I can no longer see the passwords of my intes, remembering that I have everything exposed on my host, bank and teampass itself, my docker-compose.yml looks like this:

version: "2"
services:
teampass:
image: teampass/teampass:latest
container_name: teampass
restart: always
volumes:
- "/opt/docker/scripts/teampass/teampass-instalado:/var/www/html"
#- "/opt/docker/scripts/teampass/teampass-seckey.txt:/var/www/html/teampass-seckey.txt"
ports:
- "8070:80"
environment:
- "CATTLE_DB_CATTLE_MYSQL_HOST=192.168.0.32"
- "CATTLE_DB_CATTLE_MYSQL_PORT=3306"
- "CATTLE_DB_CATTLE_MYSQL_NAME=teampass"
- "CATTLE_DB_CATTLE_USERNAME=teampass"
- "CATTLE_DB_CATTLE_PASSWORD=Pa55@w0rd1"
volumes:
- "/opt/docker/data/mysql:/var/lib/mysql"

NOTE: When I start the container with the "docker-compose up d" it asks to do the whole installation.

Thanks in advance and help.

RodnerTJ.
