### ISSUE TITLE
Fatal Error after installation 

### ISSUE THREAD

**Issue by wildgunstomcat** [nilsteampassnet/TeamPass#2027]
### Steps to reproduce
1. Install TeamPass normally
2. navigate to localhost/teampass
3. Error is given

### Expected behaviour
Teampass should start normally

### Actual behaviour
I get the following error: 

Fatal error: Uncaught Error: Call to undefined function defuse_return_decrypted() in /var/www/html/teampass/index.php:78 Stack trace: #0 {main} thrown in /var/www/html/teampass/index.php on line 78

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:** 
Apache2

**Database:**
MySQL

**PHP version:**
7.0.22

**Teampass version:** 
I'm not entirely certain, I assume the newest one. 

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:** Fresh
PLEASE attach to this message the file `/includes/config/tp.config.php`.

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://picard/teampass',
    'favicon' => 'http://picard/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://picard/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://picard/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1508774952',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0'

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10 Enterprise

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by wildgunstomcat** [comment]
Thank you guys for your help in advance. I really appreciate it. I've also considered doing a brand new HyperV of Unbuntu 16.04 and doing a totally fresh install of TeamPass but I'd rather fix this problem.

**Comment by nilsteampassnet** [comment]
HOw is this possible?
It is a basic function in Teampass defined in main.functions.php file.

My first question is, have you uploaded the complete install package?
From where did you download the package? please provide the url.

**Comment by wildgunstomcat** [comment]
Hey Nils! thanks for the fast response! 

I followed this guide: https://www.youtube.com/watch?v=C6AwhDLnj5I

In it, he says go get the master.zip file from this link: 

https://github.com/nilsteampassnet/TeamPass/archive/master.zip

I did do a fresh install on another server just to see how it worked...and it did work...but then I started getting THIS error on that server: 

Parse error: syntax error, unexpected ''disable_show_forgot_pwd_link'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/teampass/includes/config/tp.config.php on line 121

So I'm really hoping the version I installed isn't the right one and you're about to call me a dumbass.

**Comment by mserer** [comment]
From my practice please check in in /var/www/html/teampass/includes/config  tp.config.php file and search disable_show_forgot_pwd_link and check if there is comma on the end of line, if this is last line in your file remove comma and save changes and restart apache2 service. From my experience when I change settings from web, TeamPass shown blank page, manually configured file helped to me.

**Comment by nilsteampassnet** [comment]
Ok I think I have identified the reason of this.

This occurs after installation only.

I will commit the fix.

**Comment by nilsteampassnet** [comment]
Please reopen if needed.
