### ISSUE TITLE
Error on Step 3 of Fresh Install

### ISSUE THREAD

**Issue by jdipper** [nilsteampassnet/TeamPass#2028]
### Steps to reproduce
1.  Go to step 3 on install/install.php and launch.

### Expected behaviour
Step 3 should complete.

### Actual behaviour
It doesn't.  Gets as far as creating the _install table before the following error:

Notice: Undefined variable: db_link in /var/www/teampass/install/install.queries.php on line 221
Catchable fatal error: Argument 1 passed to mysqli_query() must be an instance of mysqli, null given in /var/www/teampass/install/install.queries.php on line 221

### Server configuration
**Operating system**:
Centos 7

**Web server:**
H2O

**Database:**
MariaDB

**PHP version:**
HHVM 3.18.0 / PHP 5.6.99-hhvm

**Teampass version:** 
2.1.27.10

**Teampass configuration file:**
Not generated

**Updated from an older Teampass or fresh install:**
Fresh Install.  tp.config.php does not exist.

### Client configuration
**Browser:**
Chrome

**Operating system:**
OSX

#### Web server error log
```
Notice: Undefined variable: db_link in /var/www/teampass/install/install.queries.php on line 221
Catchable fatal error: Argument 1 passed to mysqli_query() must be an instance of mysqli, null given in /var/www/teampass/install/install.queries.php on line 221
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
jquery.min.js:18 POST http://10.1.4.100/install/install.queries.php 500 (hphp_invoke)
send @ jquery.min.js:18
ajax @ jquery.min.js:18
checkPage @ install.js:183
onclick @ install.php:71
install.js:200 Uncaught TypeError: Cannot read property '0' of null
    at Object.complete (install.js:200)
    at Object.resolveWith (jquery.min.js:16)
    at w (jquery.min.js:18)
    at XMLHttpRequest.d (jquery.min.js:18)
```

#### Notes

Looks like $db_link is not defined.  Should it be using $dbTmp?

**Comment by nilsteampassnet** [comment]
> Looks like $db_link is not defined. Should it be using $dbTmp?

Yes I don't understand why this variable is still there and how it could have been pass the tests???
I will provide a fix
