### ISSUE TITLE
unable to add item without password defined (despite of "Allow item to be created without any password defined" admin. option set)

### ISSUE THREAD

**Issue by ostrochovsky** [nilsteampassnet/TeamPass#2032]
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1498431/tp.config.php.txt)
 
### Steps to reproduce
0. (Set the salt key in case of personal item)
1. Choose folder and Add item in it.
2. Fill in label and nothing else, and click Save (2 times).

### Expected behaviour
(After first click on Save), save the item or issue an error message.

### Actual behaviour
Working wheel spinning endlessly, with no additional information...

### Server configuration
**Operating system**: x86_64 GNU/Linux CentOS 7

**Web server:** Apache 2.4.6

**Database:** mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** 5.6.31

**Teampass version:** 2.1.27.9

**Teampass configuration file:** 'create_item_without_password' => '1'

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 60.0.3112.113 (Official Build) (64-bit)

**Operating system:** Ubuntu 16.04 LTS

#### Web server error log
[Thu Nov 23 09:25:45.381474 2017] [:error] [pid 25820] [client IP:52036] PHP Notice:  Undefined index: id in /var/www/html/teampass/sources/items.queries.php on line 1321, referer: https://teampass.domain.com/index.php?page=items`

#### Log from the web-browser developer console (CTRL + SHIFT + i)

STEP 1:

select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
setup @ select2.full.min.js:3
add @ jquery.js:4813
(anonymous) @ jquery.js:5651
each @ jquery.js:657
each @ jquery.js:266
on @ jquery.js:5650
c.bind @ select2.full.min.js:1
e._bindAdapters @ select2.full.min.js:2
e @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:3
each @ jquery.js:657
each @ jquery.js:266
a.fn.select2 @ select2.full.min.js:3
open_add_item_div @ index.php?page=items:3667
onclick @ index.php?page=items:1258
select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
setup @ select2.full.min.js:3
add @ jquery.js:4813
(anonymous) @ jquery.js:5651
each @ jquery.js:657
each @ jquery.js:266
on @ jquery.js:5650
c.bind @ select2.full.min.js:1
e._bindAdapters @ select2.full.min.js:2
e @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:3
each @ jquery.js:657
each @ jquery.js:266
a.fn.select2 @ select2.full.min.js:3
open @ index.php?page=items:4743
_trigger @ jquery-ui.min.js:6
open @ jquery-ui.min.js:11
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery.js:657
each @ jquery.js:266
e.fn.(anonymous function) @ jquery-ui.min.js:6
open_add_item_div @ index.php?page=items:3679
onclick @ index.php?page=items:1258
index.php?page=items:1258 [Violation] 'click' handler took 751ms
[Violation] Forced reflow while executing JavaScript took 31ms
ckeditor.js:70 [Violation] Avoid using document.write().

STEP 2:

ckeditor.js:70 [Violation] Avoid using document.write().
write @ ckeditor.js:70
setData @ ckeditor.js:649
(anonymous) @ ckeditor.js:340
i @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
setData @ ckeditor.js:246
(anonymous) @ index.php?page=items:2533
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
setup @ select2.full.min.js:3
add @ jquery.js:4813
(anonymous) @ jquery.js:5651
each @ jquery.js:657
each @ jquery.js:266
on @ jquery.js:5650
c.bind @ select2.full.min.js:1
e._bindAdapters @ select2.full.min.js:2
e @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:3
each @ jquery.js:657
each @ jquery.js:266
a.fn.select2 @ select2.full.min.js:3
(anonymous) @ index.php?page=items:5796
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

JUST AFTER LOGIN:

csrfprotector.js:272 Mixed Content: The page at 'https://teampass.d

omain.com/index.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ip-api.com/json'. This request has been blocked; the content must be served over HTTPS.
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
getJSON @ jquery.js:8265
launchIdentify @ index.php:104
onkeypress @ index.php:1095
Navigated to https://teampass.domain.com/index.php?page=items
2select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
setup @ select2.full.min.js:3
add @ jquery.js:4813
(anonymous) @ jquery.js:5651
each @ jquery.js:657
each @ jquery.js:266
on @ jquery.js:5650
bind @ jquery.js:7572
(anonymous) @ jquery-ui.min.js:6
each @ jquery.js:665
_on @ jquery-ui.min.js:6
_create @ jquery-ui.min.js:11
(anonymous) @ jquery-ui.min.js:6
_createWidget @ jquery-ui.min.js:6
e.(anonymous function).(anonymous function) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery.js:657
each @ jquery.js:266
e.fn.(anonymous function) @ jquery-ui.min.js:6
(anonymous) @ index.php?page=items:4256
fire @ jquery.js:3048
fireWith @ jquery.js:3160
ready @ jquery.js:433
completed @ jquery.js:104
jquery.js:99 [Violation] 'DOMContentLoaded' handler took 693ms
[Violation] Forced reflow while executing JavaScript took 71ms
select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
setup @ select2.full.min.js:3
add @ jquery.js:4813
(anonymous) @ jquery.js:5651
each @ jquery.js:657
each @ jquery.js:266
on @ jquery.js:5650
c.bind @ select2.full.min.js:1
e._bindAdapters @ select2.full.min.js:2
e @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:3
each @ jquery.js:657
each @ jquery.js:266
a.fn.select2 @ select2.full.min.js:3
(anonymous) @ index.php?page=items:5796
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
select2.full.min.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by nilsteampassnet** [comment]
Please upgrade to last version.

**Comment by nilsteampassnet** [comment]
No news.
I'm closing it
Please reopen if needed
