### ISSUE TITLE
Identity Operators Failing on Type

### ISSUE THREAD

**Issue by jdipper** [nilsteampassnet/TeamPass#2033]
So I am still having fun trying to get TeamPass to work, and I am not sure if it's my set up or not.

There are a lot of identity operators that are failing because the values are not the same type.  For example in sources/checks.php line 149:

`if ($data['admin'] !== '1'`

The $data variable is data from a select query on line 138:

`$data = DB::queryfirstrow(
        "SELECT login, key_tempo, admin, gestionnaire FROM ".prefix_table("users")." WHERE id = %i",
        $userId
    );`

The $data['admin'] value is (int) 1, not (string) 1.

This seems to be the case in a fair few expressions, which makes me wonder if I am doing anything wrong!  I would welcome any thoughts!

Jack

**Comment by jdipper** [comment]
For reference, I am running H2O v3.18 web server with HHVM v5.6.99.

**Comment by nilsteampassnet** [comment]
You are right, it is a work that is on-going silently to check and clean-up all the conditions referring to the type of data in DB.

Thanks
