### ISSUE TITLE
SQL error returned when role not assigned

### ISSUE THREAD

**Issue by danielhoherd** [nilsteampassnet/TeamPass#2036]
This may be related to #2026  

### Steps to reproduce

1. Create a new user without a role assigned
2. Log in as user
3. Try to do a search (failure happens here)
4. Try hitting https://teampass-server/teampass/sources/find.queries.php?sEcho=1&iColumns=6&sColumns=&iDisplayStart=0&iDisplayLength=10&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&iSortingCols=1&iSortCol_0=1&sSortDir_0=asc&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=true&bSortable_5=true&_=1511889566043

### Expected behaviour

3. Search results appear
4. JSON result is shown

### Actual behaviour

3. No search results appear. Browser throws error: "DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error."
4. SQL error is returned where JSON should be:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
        ORDER BY  label asc
        LIMIT 0, 10' at line 3 ; SELECT SQL_CALC_FOUND_ROWS *
        FROM tp_cache
        WHERE id_tree IN()
        ORDER BY  label asc
        LIMIT 0, 10
```

### Workaround

Assigning a role to the user solves this problem.

### Client configuration

- Google Chrome
- macOS 10.13

**Comment by nilsteampassnet** [comment]
I will fix this by sending à message to the user and stop the search

**Comment by nilsteampassnet** [comment]
I've checked the 2.1.27.10 version and there is such check before performing the query.
https://github.com/nilsteampassnet/TeamPass/blob/master/sources/find.queries.php#L38
So I'm wondering about the version you use, what is it?

**Comment by danielhoherd** [comment]
We are using 2.1.20, and the lines you referenced were changed in 2.1.26, so it is likely that the problem no longer exists.

I have requested that we upgrade the service to a newer version. When we do I will verify the fix and report back.

**Comment by nilsteampassnet** [comment]
Ok perfect
