### ISSUE TITLE
Feature Request: Add a 'report issue' link and/or a service information page

### ISSUE THREAD

**Issue by danielhoherd** [nilsteampassnet/TeamPass#2039]
To assist in reporting issues it would be great to see a link in the app directly to https://github.com/nilsteampassnet/TeamPass/issues/.

Also, it would be quite useful to have a service information page that users could copy/paste into a new github issue. There is already a lot of information that is requested to be filled out in the github issue template, but things like Client Browser, App Version, Server OS version, PHP version etc. could all be programmatically determined and formatted for copy-paste into new issues. This would make reporting useful information much easier.

**Comment by nilsteampassnet** [comment]
It is an idea that is interesting
