### ISSUE TITLE
LDAP Authentication is not working

### ISSUE THREAD

**Issue by fedoraflo** [nilsteampassnet/TeamPass#2043]
### Steps to reproduce
1. Configure LDAP in Webadmin:
Configuration Parameters:
LDAP server type = **Windows / Active Directory**
LDAP account suffix for your domain = **@mydomain.local**
LDAP base DN for your domain = **DC=mydomain,DC=local**
LDAP allowed user group CN = **<empty>**
LDAP domain controller(s) = **srv01.mydomain.local**
LDAP port = **389**
Use LDAP through SSL (LDAPS) = **No**
Use LDAP through TLS = **No**
Teampass local users only = **Yes**
Hide forgot password link on Home = **Yes**
2. Enable LDAP-Debugging
3. Watch the Log-File: tail -f /var/www/html/files/ldap.debug.txt

### Expected behaviour
The user is logged in successfully.

### Actual behaviour
Login credentials do not correspond!

### Server configuration
**Operating system**: Ubuntu Server 16.04 LTS - latest Updates installed

**Web server:** Server version: Apache/2.4.18 (Ubuntu), Server built:   2017-09-18T15:09:02

**Database:** mySQL 5.7.20-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** 2.1.27

**Teampass configuration file:** n/a

### Client configuration
**Browser:** Version 62.0.3202.94 (Offizieller Build) (64-Bit)

**Operating system:** Windows 7 x64

#### Web server error log 
ldap.debug.txt:
tail: files/ldap.debug.txt: file truncated
Get all LDAP params :
mode : 1
type : windows
base_dn : DC=mydomain,DC=local
search_base : 0
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @mydomain.local
domain_controllers : srv01.mydomain.local
port :
use_ssl : 0
use_tls : 0
*********

Get all ldap params :
base_dn : DC=mydomain,DC=local
account_suffix : @mydomain.local
domain_controllers : srv01.mydomain.local
port :
use_ssl : 0
use_tls : 0
*********
Create new adldap object : Success
After authenticate : Success
ldap status :

**Comment by nilsteampassnet** [comment]
Are you using latest package 2.1.27.10?

**Comment by fedoraflo** [comment]
I think so - here is the output of the changelog.md:
2.1.27
10/
 Copy password/login button are correctly hidden and shown
 Cursor is hidden on password display to permit a better visualization
 Fixed error while coping an item
 Fixed last 10 items seen list not display on page load
 Fixed display strings with quotes issue
 Fixed page About in Administration page
... etc

**Comment by fedoraflo** [comment]
Basically, it looks good:
Create new adldap object : Success
After authenticate : Success

But is it normal that the LDAP status is empty?
ldap status :

Thank you for your help.

**Comment by fedoraflo** [comment]
Just another question - I miss an option in the LDAP configuration, where I can set the username and password of a user who is authorized to browse the AD schema via LDAP ???

**Comment by yumanovaa** [comment]
Hi, I have the same problem.
**CentOS Linux release:** 7.4.1708
**Web Server version:** Apache/2.4.6 (CentOS)
**PHP:** 5.6.32
**MySQL version:** 5.7.20
**Teampass version:** 2.1.27.10
***
**ldap.debug.txt:**
```
Get all LDAP params :
mode : 1
type : windows
base_dn : DC=softwerke,DC=local
search_base :
bind_dn :
bind_passwd :
user_attribute :
account_suffix : @softwerke.local
domain_controllers : mainserver.softwerke.local
port :
use_ssl : 0
use_tls : 0
*********

Get all ldap params :
base_dn : DC=softwerke,DC=local
account_suffix : @softwerke.local
domain_controllers : mainserver.softwerke.local
port :
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Success


ldap status :

```
***
**duo.debug.txt**
```
Content of data sent 'pQO5MM/mJ1rrCamPPyQCjtOUreqIAxdRWA/TIR1lF4waU8ql8cPxx5r37wdmx0PtiRkR1HiYYRWhu7GbqiuHd4DMLeoOf1whhCRvA/dvWPvae9uJBsfHnAeEKfIrYBrBQYz0F0JuANZW0Kdvy6cqGkie0v2o4VU0Vp8/MTqihq6BJmsI+vZC6XpSjGccr5ru9SwX7ljoAsmZ/3Sr2A9ZxIE6VC00iz9UBCO7g+Tjzbb+6aLlo2LDgv9B4ebMlJwjiqxtV28='
Starting authentication of 'teampass'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified:


----
Identified : false
```
***
```SQL
SELECT * FROM teampass.teampass_log_system;
```
| id        | type           | date  | label | qui | field_1|
| ------------- |:-------------:| -----:|-----:|-----:|-----:|
| 30 | failed_auth     | 1512558855 | user_password_not_correct | 192.168.10.231 |          |
| 31 | failed_auth     | 1512559164 | user_password_not_correct | 192.168.10.231 |          |
| 32 | failed_auth     | 1512559198 | user_password_not_correct | 192.168.10.231 |          |
| 33 | failed_auth     | 1512559233 | user_password_not_correct | 192.168.10.231 |          |
| 34 | failed_auth     | 1512559238 | user_password_not_correct | 192.168.10.231 |          |
| 35 | failed_auth     | 1512559289 | user_password_not_correct | 192.168.10.231 |          |

**Comment by lolotiti06** [comment]
I have exactly the same problem. I am running a fresh installation of teampass 2.1.27.10

`base_dn : dc=XXX,DC=YYY,DC=net
account_suffix : @XXX.YYY.net
domain_controllers : MyDC.net
port : 
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Success


ldap status : `

How can we solve this issue ?

Thanks.

**Comment by nilsteampassnet** [comment]
@yumanovaa, perhaps our case is not similar as you seem to use duo. You confirm?

@lolotiti06 @fedoraflo can you share the tp.config.php file?

**Comment by nilsteampassnet** [comment]
Can you please do the next test?

* Open file sources/identify.php
* Search for
```
            // Authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                // Is user in allowed group
                if (isset($SETTINGS['ldap_allowed_usergroup']) === true) {
                    if ($adldap->user()->inGroup($auth_username, $SETTINGS['ldap_allowed_usergroup']) === true) {
                        $ldapConnection = true;
                    } else {
                        $ldapConnection = false;
                    }
                } else {
                    $ldapConnection = true;
                }
```
and replace by
```
            // Authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                // Is user in allowed group
                if (isset($SETTINGS['ldap_allowed_usergroup']) === true
                    && empty($SETTINGS['ldap_allowed_usergroup']) === false
                ) {
                    if ($adldap->user()->inGroup($auth_username, $SETTINGS['ldap_allowed_usergroup']) === true) {
                        $ldapConnection = true;
                    } else {
                        $ldapConnection = false;
                    }
                } else {
                    $ldapConnection = true;
                }
```
* Save the file
* Make a try

**Comment by yumanovaa** [comment]
@nilsteampassnet, I am do not use dou.
I am replace by
```php
            // Authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                // Is user in allowed group
                if (isset($SETTINGS['ldap_allowed_usergroup']) === true
                    && empty($SETTINGS['ldap_allowed_usergroup']) === false
                    ) {
                    if ($adldap->user()->inGroup($auth_username, $SETTINGS['ldap_allowed_usergroup']) === true) {
                        $ldapConnection = true;
                    } else {
                        $ldapConnection = false;
                    }
                } else {
                    $ldapConnection = true;
                }
```
And now everything works:
```
Get all LDAP params :
mode : 1
type : windows
base_dn : DC=softwerke,DC=local
search_base :
bind_dn :
bind_passwd :
user_attribute :
account_suffix : @softwerke.local
domain_controllers : mainserver.softwerke.local
port :
use_ssl : 0
use_tls : 0
*********

Get all ldap params :
base_dn : DC=softwerke,DC=local
account_suffix : @softwerke.local
domain_controllers : mainserver.softwerke.local
port :
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Success


ldap status : 1

```

**Comment by nilsteampassnet** [comment]
@yumanovaa thank you for the feedback.

I will commit the fix

**Comment by lolotiti06** [comment]
Même chose ici. Ca marche.
Merci encore.

**Comment by fedoraflo** [comment]
The Authentication works fine now. But the fix has some side effects:

1. As a Administrator I didn't see any Users in the User Management UI. Therefore I cannot permit access to folders, add roles to the user,... etc

2. It not possible to create a "SALT"-Key as a User. When the personal folder is loaded the title is just "Reading folder ...   NaN% "

Need some help - thank you :-)

**Comment by ishaffer2501** [comment]
I'm running into the same issue with 2.1.27.16 and I've tried replacing 

            // Authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                // Is user in allowed group
                if (isset($SETTINGS['ldap_allowed_usergroup']) === true) {
                    if ($adldap->user()->inGroup($auth_username, $SETTINGS['ldap_allowed_usergroup']) === true) {
                        $ldapConnection = true;
                    } else {
                        $ldapConnection = false;
                    }
                } else {
                    $ldapConnection = true;
                }


with
// Authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                // Is user in allowed group
                if (isset($SETTINGS['ldap_allowed_usergroup']) === true
                    && empty($SETTINGS['ldap_allowed_usergroup']) === false
                    ) {
                    if ($adldap->user()->inGroup($auth_username, $SETTINGS['ldap_allowed_usergroup']) === true) {
                        $ldapConnection = true;
                    } else {
                        $ldapConnection = false;
                    }
                } else {
                    $ldapConnection = true;
                }

in GUI results of config
Get all ldap params: 
- base_dn : OU=GROUP,DC=xxxx,DC=xxxx
- account_suffix : @xxxx.xxxx
- domain_controllers : myserver.xxxx.xxxx
- ad_port : 389
- use_ssl : 0
- use_tls : 0
*********
Create new adldap object : Success

After authenticate : Success

ldap status : Successful

Expected results are:
The user is logged in successfully.

Actual behavior:
Login credentials do not correspond!

Do you have any additional suggestions?

**Comment by ishaffer2501** [comment]
Figured out that the field "LDAP allowed user group" is useless if populated.

if you want to populate users based on a LDAP group (or AD group) in the field "LDAP base DN for your domain" use the full LDAP context of the Group you wish to use: 
Example: CN=GroupIwantToUse,OU=Security,OU=Groups,DC=DomainName,DC=DomainRoot

Used this context and LDAP integration allowed both Authentication and Authorization.

LDAP integration for my TeamPass installation is now working correctly.
