### ISSUE TITLE
Migrate from 2.1.21 to 2.1.2x - passwords losts

### ISSUE THREAD

**Issue by erwanbodere** [nilsteampassnet/TeamPass#2046]
### Steps to reproduce
1. Download v2.1.23+ (tried with 2.1.27.10, 2.1.26.20, 2.1.24.4, 2.1.23.4)
2. Copy settings.php to ${TEAMPASS_ROOT}/includes/
3. Copy sk.php to ${TEAMPASS_ROOT}/includes/
4. Launch https://teampass.domain.fr/install/upgrade.php
5. Login to https://teampass.domain.fr/
6. Display item : no password

### Expected behaviour
Continue to see all passwords

### Actual behaviour
In the migration process, passwords are decrypt/encrypt.
Passwords are not visibled in webapp.

### Server configuration
**Operating system**:
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 

**Web server:**
Apache 

**Database:**
Mysql 5.5.18

**PHP version:**
PHP Version 5.6.30-0+deb8u1

**Teampass version:** 
2.1.2X (tried with 2.1.27.10, 2.1.26.20, 2.1.24.4, 2.1.23.4)

**Teampass configuration file:**

global $lang, $txt, $k, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "xxx.xxx.xxx";
$user = "xxxx";
$pass = "xxxxx";
$database = "teampass";
$port = 3306;
$pre = "cpassman_";
$encoding = "utf8";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/home/xxxxx/teampass/includes');
require_once "/home/xxxxx/teampass/includes/sk.php";
@define('COST', '13'); // Don't change this.

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**
Firefox 45.1.0

**Operating system:**
Windows 10

#### Web server error log

Avec la version 2.1.27.10, j'obtiens le message suivant dans la méthode de décryptage :

an attack! either the wrong key was loaded, or the ciphertext has changed since it was created either corrupted in the database or intentionally modified by someone trying to carry out an attack.

**Comment by nilsteampassnet** [comment]
upgrade with 2.1.22, then 2.1.23, etc

It must work as I did this for one user

**Comment by erwanbodere** [comment]
Hi,
    I have also tried with 2.1.22 but i got the same issue.
    How can i tried on another environment. Should i patch table
      cpassman_misc ?
    Regards
    Erwan
    
    
    Le 06/12/2017 à 22:20, Nils Laumaillé a
      écrit :
    
    
      upgrade with 2.1.22, then 2.1.23, etc
      It must work as I did this for one user
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nilsteampassnet/TeamPass","title":"nilsteampassnet/TeamPass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nilsteampassnet/TeamPass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nilsteampassnet in #2046: upgrade with 2.1.22, then 2.1.23, etc\r\n\r\nIt must work as I did this for one user"}],"action":{"name":"View Issue","url":"https://github.com/nilsteampassnet/TeamPass/issues/2046#issuecomment-349778334"}}}

**Comment by erwanbodere** [comment]
I have retried :
    
      from 2.1.21 to 2.1.22 : OK
      from 2.1.22 to 2.1.23 : KO
    
    Regard
    
    
    Le 07/12/2017 à 09:37, Erwan BODERE a
      écrit :
    
    
      
      Hi,
      I have also tried with 2.1.22 but i got the same issue.
      How can i tried on another environment. Should i patch table
        cpassman_misc ?
      Regards
      Erwan
      
      
      Le 06/12/2017 à 22:20, Nils Laumaillé
        a écrit :
      
      
        upgrade with 2.1.22, then 2.1.23, etc
        It must work as I did this for one user
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view
            it on GitHub, or mute
            the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nilsteampassnet/TeamPass","title":"nilsteampassnet/TeamPass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nilsteampassnet/TeamPass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nilsteampassnet in #2046: upgrade with 2.1.22, then 2.1.23, etc\r\n\r\nIt must work as I did this for one user"}],"action":{"name":"View Issue","url":"https://github.com/nilsteampassnet/TeamPass/issues/2046#issuecomment-349778334"}}}
      
      
      
    
    
    -- 
Erwan BODERE

Service IDM / ISI
Ifremer - Centre de Brest - 29280 PLOUZANE

Tél : 02 29 00 85 42
