### ISSUE TITLE
Enable SSL, cannot see managed users or folders

### ISSUE THREAD

**Issue by egearing** [nilsteampassnet/TeamPass#2047]
When I install Teampass on Ubuntu 16.04 LTS, i

[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/1532970/tp.config.php.zip)

t works fine by going to http url for site.  Then I try to enable SSL and go to https url and go to site,login as admin and click on Mange Users, no accounts populate as they did with the http url.  Sam goes for the folders link.
### Steps to reproduce
1. sudo a2enmodssl
2. sudo service apache2 restart
3. sudo a2ensite default-ssl
4. sudo service apache2 restart
[access.log](https://github.com/nilsteampassnet/TeamPass/files/1533027/access.log)
[error.log](https://github.com/nilsteampassnet/TeamPass/files/1533030/error.log)
[error.txt](https://github.com/nilsteampassnet/TeamPass/files/1533031/error.txt)
![httpsteampass](https://user-images.githubusercontent.com/34285674/33631820-49249478-d9d1-11e7-9217-7bbe7f8a0010.JPG)
![httpteampass](https://user-images.githubusercontent.com/34285674/33631825-4d9236c8-d9d1-11e7-8f6a-8a7f7b087945.JPG)

### Expected behaviour
I should be able to see the admin, avi and otp accounts in the Managed Users portion of site. 

### Actual behaviour
Tell us what happens instead
Non of the canned accounts populate.  I still see the page with all of the letters and the search function, etc, but no accounts.. No admin account, no avi account, etc...

### Server configuration
Ubuntu Ubuntu 16.04.3 LTS

Apache/2.4.18 (Ubuntu)

mysql  Ver 14.14 Distrib 5.7.19

PHP 7.0.22-0ubuntu0.16.04.1

Teampass 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
Chrome Version 62.0.3202.94, IE 11, Firefox 57.0.1

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please refer to http://teampass.readthedocs.io/en/latest/errors/

Ensure that paths are correct and fit your server/host configuration

**Comment by egearing** [comment]
That did the trick!  I should have seen that..  I actually setup two versions and made that change, but could not for the life of me figure it out on the other..  Thanks again!

**Comment by nilsteampassnet** [comment]
you are welcome.
