### ISSUE TITLE
isset and empty check for SETTINGS

### ISSUE THREAD

**Issue by seidler2547** [nilsteampassnet/TeamPass#2049]
Hi, there a number of places (I only check LDAP because I was trying to get it to work), where `isset($SETTINGS['xxx'])` is checked, but it should be followed by `&& !empty($SETTINGS['xxx'])`. One example is `ldap_usergroup`, another `ldap_allowed_usergroup`. When these are set empty in the configuration frontend, their value is `''`, which **is** `isset`, but it doesn't make sense to check for the group name `''`.

**Comment by nilsteampassnet** [comment]
Yes you right.
But in major cases, the empty case is not useful as it is only to get its value, and empty is a correct/accepted value.
Nevertheless, I'm still improving some cases where what you identified is totally true.

Thank you
