### ISSUE TITLE
2FA Google Name Displayed field not saving to configuration

### ISSUE THREAD

**Issue by sshipway** [nilsteampassnet/TeamPass#2051]
### Steps to reproduce
1. Log in as admin and go to configuration
2. Select 2FA tab and enable Google .  Name Displayed field shows "TeamPass for ChangeMe"
3. Change Name Displayed to anything and click "save".
4. Change to different tab, then back again.  The Name Displayed field has reverted to previous value

### Expected behaviour
The changed label should be written to the tp.config.php file and become permanent

### Actual behaviour
The new Name Displayed setting was not saved to the tp.config.php file, and so reverted to previous default value.  Verified file ownerships and permissions are correct.

### Server configuration
**Operating system**: Centos 7

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 5.6

**Teampass version:**  2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresg

### Client configuration
**Browser:** Firefox

**Operating system:** Linux (Ubuntu)

**Comment by roru69** [comment]
I have the same issue on Debian 8, Php7.x, Apache and MariaDB with a fresh install of TP 2.1.27.10

**Comment by nilsteampassnet** [comment]
Thank you.

Fixed
