### ISSUE TITLE
Table columns vanish when managing roles in UI

### ISSUE THREAD

**Issue by sshipway** [nilsteampassnet/TeamPass#2052]
### Steps to reproduce
1. create two or more different roles in the UI, and several folders
2. go to Manage Roles admin page.
3. click on one of the red 'hand' icons in the table.  The Define Access popup appears
4. change the setting (e.g. to Write) and click Save
5. all the table columns but the first disappear until you leave the Manage Roles page and return

### Expected behaviour
The table should update and show the new value immediately

### Actual behaviour
All the table columns but the first disappear from the UI, until you leave the page and return.

### Server configuration
**Operating system**: Linux Centos 7

**Web server:** NGinx

**Database:** MariaDB

**PHP version:** 5.6

**Teampass version:**  2.1.27

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1541176/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh

### Client configuration
**Browser:** Firefox 45.0.2

**Operating system:** Ubuntu

#### Web server error log
```
2017/12/08 01:49:07 [error] 1868#0: *835 FastCGI sent in stderr: "PHP message: PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /data/www/teampass/includes/config/include.php on line 24" while reading response header from upstream, client: 10.0.62.66, server: aklbld04.smxemail.com, request: "POST /teampass/sources/roles.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "aklbld04.smxemail.com", referrer: "http://aklbld04.smxemail.com/teampass/index.php?page=manage_roles"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.js:5375:28
TypeError: handleObj.handler.apply is not a function
```

**Comment by nilsteampassnet** [comment]
I tried to reproduce but couldn't.

![image](https://user-images.githubusercontent.com/1197546/33802676-83d9b180-dd7c-11e7-828e-96f3421282ce.png)
I have clicked on the "red hand" for role "Test6", selected "Write" and saved.
I couldn't see that the roles columns disappeared.

Can you try to capture the answer from the server using the browser console?
* Click on keys CTRL+SHIFT+i --> this makes the console appearing.
* Select the tab `Network`
* Now do the change for a folder / role
* Observe the queries in the console --> 2 new queries have been added
![image](https://user-images.githubusercontent.com/1197546/33802715-1843c8ce-dd7d-11e7-83d5-3f9500e41df4.png)
* Click on the first
* Select tab "response" (or answer) 
* You should have a json answer like `error : no`

**Comment by sshipway** [comment]
I've followed the instructions; the first query does respond:
```
[ { "error" : "no" } ]
```
The second responds with:
```
{"new_table":"\u003Ctable\u003E\u003Cthead\u003E\u003Ctr\u003E\u003Cth\u003EFolders\u003C\/th\u003E\u003Cth style=\u0027font-size:10px;min-width:60px;\u0027 class=\u0027edit_role\u0027\u003EAdministrator\u003Cbr\u003E\u003Cspan class=\u0027fa fa-pencil fa-2x mi-grey-1\u0027 onclick=\u0027edit_this_role(1,\u0022Administrator\u0022,60)\u0027 style=\u0027cursor:pointer;\u0027\u003E\u003C\/span\u003E\u0026nbsp;\u003Cspan class=\u0027fa fa-trash fa-2x mi-grey-1\u0027 style=\u0027cursor:pointer;\u0027 onclick=\u0027delete_this_role(1,\u0022Administrator\u0022)\u0027\u003E\u003C\/span\u003E\u0026nbsp;\u003Cspan class=\u0027fa fa-magic fa-2x mi-green tip\u0027 id=\u0027img_apcfr_1\u0027 onclick=\u0027allow_pw_change_for_role(1, 1)\u0027 style=\u0027cursor:pointer;\u0027 title=\u0027Role allowed to modify all accessible items (insecure setting)\u0027\u003E\u003C\/span\u003E\u003Cdiv style=\u0027margin-top:-8px;\u0027\u003E[\u0026nbsp;Strong\u0026nbsp;]\u003C\/div\u003E\u003C\/th\u003E\u003C\/tr\u003E\u003C\/thead\u003E\u003Ctbody\u003E\u003Ctr\u003E\u003Ctd style=\u0027font-size:10px; font-family:arial;\u0027 title=\u0027ID=2\u0027\u003E applications\u003C\/td\u003E\u003Ctd align=\u0027center\u0027 style=\u0027text-align:center;background-color:#FF0000\u0027 id=\u0027tm_cell_0\u0027 title=\u0027No Access\u0027\u003E\u003Cspan onclick=\u0027openRightsDialog(1,2,0,\u0022\u0022)\u0027\u003E\u003Ci class=\u0022fa fa-hand-stop-o\u0022\u003E\u003C\/i\u003E\u003C\/span\u003E\u003Cspan style=\u0027float:right;\u0027\u003E\u003Cinput type=\u0027checkbox\u0027 title=\u0027\u0027 class=\u0027multi_folders\u0027 id=\u0027multisel_2_1\u0027\u003E\u003C\/span\u003E\u003C\/td\u003E\u003C\/tr\u003E\u003Ctr\u003E\u003Ctd style=\u0027font-size:10px; font-family:arial;\u0027 title=\u0027ID=7\u0027\u003E\u003Ci class=\u0027fa fa-sm fa-caret-right mi-grey-1\u0027\u003E\u003C\/i\u003E\u0026nbsp; XM1\u003C\/td\u003E\u003Ctd align=\u0027center\u0027 style=\u0027text-align:center;background-color:#FF0000\u0027 id=\u0027tm_cell_1\u0027 title=\u0027No Access\u0027\u003E\u003Cspan onclick=\u0027openRightsDialog(1,7,1,\u0022\u0022)\u0027\u003E\u003Ci class=\u0022fa fa-hand-stop-o\u0022\u003E\u003C\/i\u003E\u003C\/span\u003E\u003Cspan style=\u0027float:right;\u0027\u003E\u003Cinput type=\u0027checkbox\u0027 title=\u0027\u0027 class=\u0027multi_folders\u0027 id=\u0027multisel_7_1\u0027\u003E\u003C\/span\u003E\u003C\/td\u003E\u003C\/tr\u003E\u003Ctr\u003E\u003Ctd style=\u0027font-size:10px; font-family:arial;\u0027 title=\u0027ID=4\u0027\u003E certificates\u003C\/td\u003E\u003Ctd align=\u0027center\u0027 style=\u0027text-align:center;background-color:#FF0000\u0027 id=\u0027tm_cell_2\u0027 title=\u0027No Access\u0027\u003E\u003Cspan onclick=\u0027openRightsDialog(1,4,2,\u0022\u0022)\u0027\u003E\u003Ci class=\u0022fa fa-hand-stop-o\u0022\u003E\u003C\/i\u003E\u003C\/span\u003E\u003Cspan style=\u0027float:right;\u0027\u003E\u003Cinput type=\u0027checkbox\u0027 title=\u0027\u0027 class=\u0027multi_folders\u0027 id=\u0027multisel_4_1\u0027\u003E\u003C\/span\u003E\u003C\/td\u003E\u003C\/tr\u003E\u003Ctr\u003E\u003Ctd style=\u0027font-size:10px; font-family:arial;\u0027 title=\u0027ID=3\u0027\u003E devices\u003C\/td\u003E\u003Ctd align=\u0027center\u0027 style=\u0027text-align:center;background-color:#FF0000\u0027 id=\u0027tm_cell_3\u0027 title=\u0027No Access\u0027\u003E\u003Cspan onclick=\u0027openRightsDialog(1,3,3,\u0022\u0022)\u0027\u003E\u003Ci class=\u0022fa fa-hand-stop-o\u0022\u003E\u003C\/i\u003E\u003C\/span\u003E\u003Cspan style=\u0027float:right;\u0027\u003E\u003Cinput type=\u0027checkbox\u0027 title=\u0027\u0027 class=\u0027multi_folders\u0027 id=\u0027multisel_3_1\u0027\u003E\u003C\/span\u003E\u003C\/td\u003E\u003C\/tr\u003E\u003Ctr\u003E\u003Ctd style=\u0027font-size:10px; font-family:arial;\u0027 title=\u0027ID=1\u0027\u003E servers\u003C\/td\u003E\u003Ctd align=\u0027center\u0027 style=\u0027text-align:center;background-color:#008000\u0027 id=\u0027tm_cell_4\u0027 title=\u0027Write\u0027\u003E\u003Cspan onclick=\u0027openRightsDialog(1,1,4,\u0022W\u0022)\u0027\u003E\u003Ci class=\u0022fa fa-indent\u0022\u003E\u003C\/i\u003E\u0026nbsp;\u003Ci class=\u0022fa fa-edit\u0022\u003E\u003C\/i\u003E\u0026nbsp;\u003Ci class=\u0022fa fa-eraser\u0022\u003E\u003C\/i\u003E\u003C\/span\u003E\u003Cspan style=\u0027float:right;\u0027\u003E\u003Cinput type=\u0027checkbox\u0027 title=\u0027\u0027 class=\u0027multi_folders\u0027 id=\u0027multisel_1_1\u0027\u003E\u003C\/span\u003E\u003C\/td\u003E\u003C\/tr\u003E\u003C\/tbody\u003E\u003C\/table\u003E","all":1,"next":1,"previous":1,"list_of_roles":["Administrator"]}
```

Initial screen:
![screenshot from 2017-12-11 15-53-39](https://user-images.githubusercontent.com/1400897/33813884-8c84e452-de8b-11e7-8327-e71339c3e017.png)

After saving:
![screenshot from 2017-12-11 15-53-58](https://user-images.githubusercontent.com/1400897/33813886-9679adb2-de8b-11e7-8c3d-e7335f3df083.png)

**Comment by sshipway** [comment]
Have upgraded to 2.1.27.10 and the problem is still there.
Have also checked using both Chrome and Firefox, and it still happens.
Nginx error log repeatedly shows:
`
2017/12/11 03:30:37 [error] 15004#0: *141 FastCGI sent in stderr: "PHP message: PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /data/www/teampass/includes/config/include.php on line 24" while reading response header from upstream, client: 10.0.101.74, server: aklbld04.smxemail.com, request: "POST /teampass/sources/roles.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "aklbld04.smxemail.com", referrer: "http://aklbld04.smxemail.com/teampass/index.php?page=manage_roles"
`

**Comment by nilsteampassnet** [comment]
Take a look to your screenshots.
You are currently filtering using keyword 'admin'.
That's why you have just one column as it is the only one that has this word in its name.

I believe the topic is closed

**Comment by sshipway** [comment]
You are quite right.  It seems my browser is being a bit 'helpful' and filling in the field with the login username, and I had not realised it was an active filter.  Clearing the field out and all is fine.

Although this is strictly a browser issue, rather than a teampass problem, perhaps it might help to rename the filter field so that helpful browser password-management plugins do not identify this field as a username to be prepopulated?

Thanks for the help
