### ISSUE TITLE
Custom Fields - folders unchecked at second call up

### ISSUE THREAD

**Issue by go2this** [nilsteampassnet/TeamPass#2053]
Sorry, I don't speak english very well:

### Steps to reproduce
First create a custom field and assign it to one or more folders. Then:
1. Settings
2. Custom Fields
3. Push Button "Shown in folders"
4. Open the List with the selected folders (all selected folders are checked)
![checkbox1](https://user-images.githubusercontent.com/34249133/33764085-4795401e-dc13-11e7-86ff-af9947c6d7cc.jpg)

5. Select one or more folders
6. Confirm or close the window
7. Push Button "Shown in folders" again
8. Now all folders that were marked before are unchecked
![checkbox2](https://user-images.githubusercontent.com/34249133/33764086-47b06bc8-dc13-11e7-86ff-a8d9250b295c.jpg)

### Behaviour
When the window is opened for the first time, all previously selected folders are checked. In the second call, they are all unchecked

### Server configuration
**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** MariaDB

**PHP version:** 7.1.12-2

**Teampass version:** 2.1.27.10

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1542215/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7 Prof. x64

**Comment by nilsteampassnet** [comment]
Thank you

A fix will be committed.
