### ISSUE TITLE
Alter table statement is run for each table that gets created

### ISSUE THREAD

**Issue by electrical** [nilsteampassnet/TeamPass#2054]
ALTER DATABASE `teampass` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci is being run for each table at setup time

I think it should be moved into its own task/step so it only gets executed once.

https://github.com/nilsteampassnet/TeamPass/blob/master/install/install.queries.php#L316

### Steps to reproduce
1. Enable query logging on mysql instance
2. Run through the installation and view query logging

### Expected behaviour
Expected this only to be run once

### Actual behaviour
Runs for every table creation

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** Percona XtraDB

**PHP version:** 5.6.32

**Teampass version:** 2.1.27.10

**Comment by nilsteampassnet** [comment]
Correct.

Thank you for this finding.
I will commit the fix.
