### ISSUE TITLE
restricted_to of cache table has 2 different values

### ISSUE THREAD

**Issue by electrical** [nilsteampassnet/TeamPass#2055]
### Steps to reproduce
1. Use latest version
2. Create new item
3. Go to search page

### Expected behaviour
Item should show up in the table

### Actual behaviour
It doesn't.

At https://github.com/nilsteampassnet/TeamPass/blob/master/sources/main.functions.php#L1054  the restricted_to field gets the value `None` at first creation. At any edit/update it gets a value `0`.
It seems that this specific line is the only case where it still uses `None`.
My best guess is that this was missed for some reason.

**Comment by nilsteampassnet** [comment]
Thank you for sharing this.
You are right in your analysis.
This needs to be fixed.

**Comment by electrical** [comment]
Closing as its been fixed
