### ISSUE TITLE
Importing KeyPass items into private personal folders not working as expected

### ISSUE THREAD

**Issue by sshipway** [nilsteampassnet/TeamPass#2058]
### Steps to reproduce
0. Enable private personal storage on server. Ensure user exists and has personal storage folder. Log in, enter personal salt key
1. Create a keypass database with subfolders and items.  Export this to XML format ready to import.
2. Create a subfolder 'test' under the personal folder
2. Import the keypass XML into the personal subfolder 'test'.  Both 'anyone can modify' and 'anyone in same role can modify' options are not checked.
3. Note how folder 'test' appears empty
4. Use "refresh" on folders pane.  Folder 'test' now has the dropdown icon
5. Expand folder 'test'.  Select an imported subfolder
6. See that the items in the folder show the green tag and the 'no password' icon.  Selecting an item does not display it in the item frame, but you can still double-click and edit it.  No password is defined.
7. Re-enter salt key
8. View items in folder.  Now they show a 'secret agent' (admin?) icon and the 'no password' icon is gone.
9. Selecting an item does not display it in the item frame, and double-clicking edits the item, where you can see that it does have a password.

### Expected behaviour
When importing new items into the personal folder, it should not be necessary to enter the salt key again (and if it is, then you should be prompted for it).
After importing, the tree should automatically refresh.
It is not clear why items are marked with the 'secret agent' icon, and why they do not display in the item frame of the UI.  Items at the top level of the personal folder do display in the Item frame, but not any items lower.
If the personal salt key has been invalidated somehow, then items should not be displayed as "no password".

### Server configuration
**Operating system**: Linux Centos 6
**Web server:** Nginx
**Database:** Mariadb
**PHP version:** 5.6
**Teampass version:** 2.1.27.10
**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1561431/tp.config.php.txt)
**Updated from an older Teampass or fresh install:** Updated from earlier 2.1.27

### Client configuration
**Browser:** Firefox 45.0.2
**Operating system:** Ubuntu

**Comment by nilsteampassnet** [comment]
Thank you for reporting with so much details.

I have reproduced the issue and could implement a fix.
I will commit it tomorrow.

**Comment by nilsteampassnet** [comment]
Has been fixed.
Please reopen if not.

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass from admin settings page and I do not get the option to import in the folder menu. What I do?
