### ISSUE TITLE
Bug in Custom LDAP port and adLDAP

### ISSUE THREAD

**Issue by sown87** [nilsteampassnet/TeamPass#2059]
### Steps to reproduce
1.  Just try to use LDAP with a custom port other than 389 (unencrypted) or 636 (SSL)
2.  Recent version of PHP

### Expected behaviour
LDAP requests sent from TEAMPASS server to LDAP service-- can be verified using tcpdump
$ sudo tcpdump -nn -i <interface>host <ip_of_ldap_server>

### Actual behaviour
LDAP queries are always instead sent out using 389 or 636 no matter what custom port is set

### Server configuration
**Operating system**:   RHEL 7.4
**Web server:**   nginx 1.12
**Database:** mysql
**PHP version:** 7.4
**Teampass version:** 2.1.27.10

### Problem
Hi Nils!  First off, thanks for making a nice product.  Much appreciated.
Here's a bug I came across using a custom LDAP port. 

Basically, setting up a custom port in Teampass, and running it under a recent version of PHP won't work.  After troubleshooting and a bit of hacking, came up with a workaround and potential root cause.  There are actually two issues, I believe:

================
1.  For LDAP requests using anything but 'posix-search' type, the array that is passed to adLDAP is named incorrectly.   In the files the array key 'port' is sent to adLDAP
CPASSMAN_DIR/sources/identify.php
520                     'port' => $SETTINGS['ldap_port'],
CPASSMAN_DIR/sources/admin.queries.php
2158                     'port' => $SETTINGS['ldap_port'],

However, in adLDAP, the expected key name in the array should be 'ad_port', and not 'port':
CPASSMAN_DIR/includes/libraries/LDAP/adLDAP/adLDAP.php
587             if (array_key_exists("ad_port", $options)) { $this->setPort($options["ad_port"]); }

I can fix this by changing the key from 'port' to 'ad_port' in identify.php and admin.queries.php

=================
2.  The version of adLDAP included with Teampass uses an older syntax for invoking the PHP function ldap_connect()-- the custom port is a 2nd parameter passed to the function.  It should be a single parameter with URI and port separated by a colon ":".  All LDAP requests still get sent either via port 389 or 636 because of this-- even if I modify the 1. issue above.  
This is brought up in the discussion thread at http://php.net/manual/en/function.ldap-connect.php

The old version The syntax is here:

CPASSMAN_DIR/includes/libraries/LDAP/adLDAP/adLDAP.php
622         if ($this->useSSL) {
623            $this->ldapConnection = ldap_connect("ldaps://".$domainController, $this->adPort);
624         } else {
625             $this->ldapConnection = ldap_connect("ldap://".$domainController, $this->adPort);
625         }

instead, lines 623 and 625 should instead read
623             $this->ldapConnection = ldap_connect("ldaps://".$domainController .":". $this->adPort);
625             $this->ldapConnection = ldap_connect("ldap://".$domainController .":". $this->adPort);

================

By making the above modifications to 
CPASSMAN_DIR/sources/identify.php
CPASSMAN_DIR/sources/admin.queries.php
CPASSMAN_DIR/includes/libraries/LDAP/adLDAP/adLDAP.php

then the custom LDAP port works properly.

**Comment by nilsteampassnet** [comment]
Thank you for your investigation and fix proposal.

Its now merged.
