### ISSUE TITLE
LDAP authentication issue

### ISSUE THREAD

**Issue by fbosquetdenis** [nilsteampassnet/TeamPass#2061]
### Steps to reproduce
Hello,
I have some issues in connecting the teampass great product to our LDAP server.
It seems it does not work.
Any help much appreciated - Thank you !

### Expected behaviour
user should be authenticated
### Actual behaviour
not authenticated
### Server configuration
**Operating system**:
Linux teampass 3.10.0-693.5.2.el7.x86_64 #1 SMP
**Web server:**
Apache/2.4.6 (Red Hat Enterprise Linux)
**Database:**
mysqld  Ver 5.7.20 for Linux on x86_64 (MySQL Community Server (GPL))
**PHP version:**
PHP 7.0.26 (cli) (built: Nov 21 2017 15:12:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
**Teampass version:** 
 2.1.27.10
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
FRESH Install

PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 63.0.3239.84 (Official Build) (64-bit)
**Operating system:**
Mac OSX 10.10

#### Web server error log

>tail acces_log
1.1.1.86 - - [19/Dec/2017:10:46:08 +0100] "POST /sources/checks.php HTTP/1.1" 200 1 "http://teampass.SOCIETE.com/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
1.1.1.86 - - [19/Dec/2017:10:46:08 +0100] "POST /sources/identify.php HTTP/1.1" 200 94 "http://teampass.SOCIETE.com/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"

>more ldap.debug.txt 
Get all ldap params : 
base_dn : ou=People,o=SOCIETE.com,ou=SOCIETE,ou=fr,o=HOLDING
account_suffix : ou=SOCIETE,ou=fr,o=HOLDING
domain_controllers : ldap.SOCIETE.com
port : 389
use_ssl : 0
use_tls : 0
*********
Create new adldap object : Success
After authenticate : No such object
ldap status : 

>duo.debug.txt
Content of data sent 'KwLTaODfOFpCj1XzSRROxogTNNluKnI5R1JzJRwJza6tBfBOD5dpsghotC5386KwCz1EPcY5bfz4pAnbniyY54TZUiuhCD0973M7z2eUaXgZjj3htoeOFoT+kAUGD3k0XfjvLdYBUeKIAKt5FSQ84uSov4HPxf2LL4vrMpkakoTsZ5UdggZWwQM3o2FHb6sKZ/Z5EXydOdHNsbkh5+BCluWwtdwhuJlNkzNQ5vlhgslYe7dpXU0B3aO9'
Starting authentication of 'my_login'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 

Identified : false

**Comment by fbosquetdenis** [comment]
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1571206/tp.config.php.txt)

**Comment by nilsteampassnet** [comment]
I don't think this definition of usergroup is correct
`'ldap_usergroup' => 'ou=People,o=SOCIETE.com,ou=SOCIETE,ou=fr,o=HOLDING',`

A usergroup should be the name of the group in which the allowed users will be.
If no group exists then leave it empty

**Comment by fbosquetdenis** [comment]
I have been able to make it run with the POSIX LDAP Search - it is running smoothly. 
I have created a special RO account for parsing our LDAP structure 
Thank you!

**Comment by nicaiseeric** [comment]
@fbosquetdenis could you please share some details on how you solved your issue?
