### ISSUE TITLE
Import Items not working

### ISSUE THREAD

**Issue by satmartin** [nilsteampassnet/TeamPass#2062]
When i click the Import items...i can see only the below screenshot.Nothing is happening after that.Any help pls?.
![image](https://user-images.githubusercontent.com/34685842/34164313-42d88d52-e4ff-11e7-9a81-14e2791a985b.png)

**Comment by nilsteampassnet** [comment]
Please follow the template.
Reopen it once you have provided all necessary elements.

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass from admin settings page and I do not get the option to import in the folder menu. What I do?
