### ISSUE TITLE
Setting "Hide forgot password link on Home page" doesn't works

### ISSUE THREAD

**Issue by go2this** [nilsteampassnet/TeamPass#2063]
### Steps to reproduce
1. Login as Admin

2. Goto LPAD-Settings

3. Change settings for "Hide forgot password link on Home page"

4. Logout

5. "Forgot your password?" is displayed

### Behaviour
The Text "Forgot your password?" on the start page should either be displayed or not, depending on the settings.

### Server configuration
**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** MariaDB

**PHP version:** 7.1.12-2

**Teampass version:** 2.1.27.10

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1542215/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7 Prof. x64

**Comment by go2this** [comment]
I'm not a developer, but I solved it for myself:

index.php
>         // Google Authenticator code
        if (isset($SETTINGS['google_authentication']) && $SETTINGS['google_authentication'] === "1") {
            echo '
                        <div id="ga_code_div" style="margin-bottom:10px;">
                            '.$LANG['ga_identification_code'].'
                            <input type="text" size="4" id="ga_code" name="ga_code" style="margin:0px;" class="input_text text ui-widget-content ui-corner-all numeric_only" onkeypress="if (event.keyCode == 13) launchIdentify(\'', isset($SETTINGS['duo']) && $SETTINGS['duo'] === "1" ? 1 : '', '\', \''.$nextUrl.'\')" />
                        <div id="2fa_new_code_div" style="text-align:center; display:none; margin-top:5px; padding:5px;" class="ui-state-default ui-corner-all"></div>
                        <div style="margin-top:2px; font-size:10px; text-align:center; cursor:pointer;" onclick="send_user_new_temporary_ga_code()">'.$LANG['i_need_to_generate_new_ga_code'].'</div>
                        </div>';
        }
        echo '
                        <div style="margin-bottom:3px;">
                            <label for="duree_session" class="">'.$LANG['index_session_duration'].'&nbsp;('.$LANG['minutes'].') </label>
                            <input type="text" size="4" id="duree_session" name="duree_session" value="', isset($SETTINGS['default_session_expiration_time']) ? $SETTINGS['default_session_expiration_time'] : "60", '" onkeypress="if (event.keyCode == 13) launchIdentify(\'', isset($SETTINGS['duo']) && $SETTINGS['duo'] === "1" ? 1 : '', '\', \''.$nextUrl.'\')" class="input_text text ui-widget-content ui-corner-all numeric_only" />
                        </div>';
		// Forgot pwd 
		if (isset($SETTINGS['disable_show_forgot_pwd_link']) && $SETTINGS['disable_show_forgot_pwd_link'] === "0") {
			echo '
                        <div style="text-align:center;margin-top:5px;font-size:10pt;">
                            <span onclick="OpenDialog(\'div_forgot_pw\')" style="padding:3px;cursor:pointer;">'.$LANG['forgot_my_pw'].'</span>
                        </div>';
		}				
		echo '				
                        <div style="text-align:center;margin-top:15px;">
                            <input type="button" id="but_identify_user" onclick="launchIdentify(\'', isset($SETTINGS['duo']) && $SETTINGS['duo'] === "1" ? 1 : '', '\', \''.$nextUrl.'\', \'', isset($SETTINGS['psk_authentication']) && $SETTINGS['psk_authentication'] === "1" ? 1 : '', '\')" style="padding:3px;cursor:pointer;" class="ui-state-default ui-corner-all" value="'.$LANG['index_identify_button'].'" />
                        </div>
                    </div>
                </form>
                <script type="text/javascript">
                    $("#login").focus();
                </script>';
        // DIV for forgotten password

**Comment by nilsteampassnet** [comment]
Thank you
