### ISSUE TITLE
LDAP and DUO users with administrator role taken to items page then logged out

### ISSUE THREAD

**Issue by gregulator85** [nilsteampassnet/TeamPass#2064]
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1577155/tp.config.txt)
 
### Steps to reproduce
1. Configure LDAP, enroll users, assign administrator role to LDAP users
2. Configure DUO 2FA, works correctly
3. Regular LDAP users can login with Duo auth successfully and are taken to items page.  Administrator role LDAP users with Duo are also taken to items page, then forced to the login page upon clicking on any links.

### Expected behaviour
Administrator role accounts should be brought to manage main page upon successful Duo authentication.

### Actual behaviour
Administrator role LDAP users with Duo are taken to items page, then forced to the login page upon clicking on any links.  Also all links looks to resolve to index.php?=items#

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** Mysql 5.7.20

**PHP version:** 7.0.22

**Teampass version:** 2.1.27.10

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

![image](https://user-images.githubusercontent.com/7906169/34230911-8b3ed8b2-e59f-11e7-8ffc-dcba17f067c8.png)

I know there is an option to have administrators have access to items via: 
Open file include.php in folder /includes/config/
Change sentence $k['admin_full_right'] = true; to $k['admin_full_right'] = false;

But we would prefer to have a separation of roles between regular user accounts and admin accounts and not enable it through that method.  I would think it would be a simple addition to check what type of account is logging in to determine the landing page after authentication.

**Comment by nilsteampassnet** [comment]
I found why.
It's a bug related to initial way DUO/Admin users were managed.
This case was not taken into account as by default 'admin' account should not authenticate with DUO.
But of course other admin users should, so I will fix this by end of the week.

Thank you for reporting.

**Comment by nilsteampassnet** [comment]
I have committed the fix but couldn't test it as I don't have any LDAP server.
Please reopen if not fixed
