### ISSUE TITLE
email send GAUTH-code is broken when sent as user -- as admin works

### ISSUE THREAD

**Issue by RockyJLU** [nilsteampassnet/TeamPass#2065]
the link sent via email looks as follows:

`<a href="#link#">LINK</a>` 

When sent via admin-frontend it looks like:
```
----------------------
aikie5oeeH2x
----------------------
```
**User link is broken.**

**Comment by nilsteampassnet** [comment]
Can you please give the way to reproduce please?

**Comment by sshipway** [comment]
The send works for me, but only if the user in question has an email address defined.  If no email address is defined, it does not show an error and just returns without sending an email.  There is no link in the email (v2.1.27.10)

**Comment by nilsteampassnet** [comment]
@RockyJLU, Sorry but I'm not sure to understand.
It is normal to receive this kind of code as it is the one the user will need to use to get the QR for Teampass connection. THis code is used to validate that this user has access to the email.

@sshipway Yes it is correct. I have fixed it.

**Comment by RockyJLU** [comment]
Sorry for the late reply, i was on vacation.
My initial problem was misunderstood it seems, but i will elaborate on my current situation.
We are working with LDAP to manage our users and were testing the Google 2FA. So we definitely have a set e-mail for every user. When we send the mail for the very first one time password through the admin account, it works and we can set up the QR-Code.
Our problem now is that if a user tries to request that one time password on the login page themselves, we get a faulty link without any content.
Hopefully that clears up any confusion.
