### ISSUE TITLE
Read Only Users can Drag and drop items to there personal folder.

### ISSUE THREAD

**Issue by NivanthakaK** [nilsteampassnet/TeamPass#2066]
Read only users can drag and drop items to there personal folder even the role is set to only "Read". So the item will removed from the Original folder

### Steps to reproduce
1. Create new user by ticking "Is read-only" and "Personal Folder". 
2. Set the Role with a read only access right.
3.Login from some other account and create an item on that particular folder
4. Login from the RO user and enter the correct Salt Key and create new folder on the personal folder tree.
5. Drag & drop the item created on step 3 to the personal folder of the RO user
6. The item will be removed from the original folder and placed it in the private folder of the RO user.

### Expected behaviour
RO users should not be able to make any modifications to excising structure. They should not be able to drag and drop items to there personal folder.

### Actual behaviour
RO user can drag and drop item to personal folder. this is like 'Cut & Paste" items.

### Server configuration
CentOS7

**Web server:**
Apache/2.4.6

**Database:**
mysql  Ver 14.14 Distrib 5.7.20,

**PHP version:**
PHP 7.0.25
**Teampass version:** 
2.1.27.10
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh Install

**Comment by nilsteampassnet** [comment]
Yes I identified this recently and latest commit in development fix this issue.

**Comment by NivanthakaK** [comment]
Thanks a lot for the quick feedback

**Comment by nilsteampassnet** [comment]
Reopen if not fixed

**Comment by NivanthakaK** [comment]
I've checked with the latest version and the issue still exists. Also RO users can copy entire folder to other RO folders.

**Comment by nilsteampassnet** [comment]
Did you took the source from Development branch?

There is currently no version with the fix...

**Comment by NivanthakaK** [comment]
Sorry i checked on the latest release previously. 
Now I checked on Dev branch and **moving item issue is fixed**. Thank you very much.

But still  RO users can 
1. copy folders to other folders ( Ideal scenario would be to copy items to user's personal folder)

 2. Import items to folders. (This is somewhat manageable since we can disable the import feature and enable when we want to)

Thank you very much for your support

**Comment by nilsteampassnet** [comment]
Thank you for the feedback.

I've fixed point 1 and 2. RO users can only copy/import in personal ones.
