### ISSUE TITLE
items not showing

### ISSUE THREAD

**Issue by Raboo** [nilsteampassnet/TeamPass#2067]
### Steps to reproduce
1. Login to teampass

### Expected behaviour
I login to teampass and folder view is loading. I should see the items inside the folders.

### Actual behaviour
I login to teampass and folderview is loading. Instead of items I get a "Information" message saying:
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
It appears to happen during a post to `sources/items.queries.php`

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
apache 2.4.28
**Database:**
5.5.58
**PHP version:**
7.0.26
**Teampass version:** 
2.1.27 / current master
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Upgrade from 2.1.26

### Client configuration
**Browser:**
Firefox
**Operating system:**
OS X
#### Web server error log
No errors in the php error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
TypeError: obj is undefined[Läs mer] jquery.js:631:4
  each includes/js/jquery-ui/external/jquery/jquery.js:631:4
  showItemsList index.php:2330:5
  ListerItems/request< index.php:2295:21
  fire includes/js/jquery-ui/external/jquery/jquery.js:3048:10
  fireWith includes/js/jquery-ui/external/jquery/jquery.js:3160:7
  done includes/js/jquery-ui/external/jquery/jquery.js:8235:5
  callback includes/js/jquery-ui/external/jquery/jquery.js:8778:8
```

**Comment by nilsteampassnet** [comment]
Can you provide the apache log errors corresponding to this behavior?

**Comment by Raboo** [comment]
It's empty..

**Comment by Raboo** [comment]
<img width="580" alt="screen shot 2017-12-27 at 16 04 08" src="https://user-images.githubusercontent.com/1148206/34384984-c7a9cc6e-eb1f-11e7-91ea-74994b989a92.png">

**Comment by nilsteampassnet** [comment]
There must be an error while opening the items page.

* do CTRL+SHIFT +i to open the console
* select tab `Network`
* click on the last query with `items.querie.php`
![image](https://user-images.githubusercontent.com/1197546/34637707-1a1148f8-f2bc-11e7-85eb-98c5a7694424.png)
* click on tab `Response`
![image](https://user-images.githubusercontent.com/1197546/34637709-353c25e4-f2bc-11e7-8703-33884f6c5dc1.png)
* Provide the text in the `Response`

Please provide also the results of this query
```
SELECT label  FROM teampass_og_system WHERE `type` LIKE 'error'  ORDER BY `date` DESC
```

**Comment by errano** [comment]
Attached the text in the response

![cattura](https://user-images.githubusercontent.com/35180024/34645172-64972190-f33e-11e7-914a-c3b885da548e.PNG)

**Comment by nilsteampassnet** [comment]
Can you please provide the result of the querie
```
SELECT label FROM `teampass_log_system` WHERE type="error" ORDER BY date DESC
```

**Comment by errano** [comment]
here it is.

thank you for your support.

**Comment by nilsteampassnet** [comment]
Very strange the query has a negative value in the limit.

Can you provide the tp.config.php file please?

**Comment by errano** [comment]
here it is, i edited it a bit for security, if you want me to check something changed let me know.

thank you

**Comment by nilsteampassnet** [comment]
I think you missed to add the file ;)

**Comment by errano** [comment]
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1611682/tp.config.zip)

**Comment by nilsteampassnet** [comment]
I don't really see what is wrong here.

Can you try this?
* open items.load.php
* find
```
    //Evaluate number of items to display - depends on screen height
    if (parseInt($("#nb_items_to_display_once").val()) || $("#nb_items_to_display_once").val() == "max") {
        //do nothing ... good value
    } else {
        //adapt to the screen height
        $("#nb_items_to_display_once").val(Math.max(Math.round((window_height-450)/23),2));
    }
```
and replace by
```
    //Evaluate number of items to display - depends on screen height
    if (parseInt($("#nb_items_to_display_once").val()) || $("#nb_items_to_display_once").val() == "max") {
        //do nothing ... good value
    } else {
        //adapt to the screen height
        $("#nb_items_to_display_once").val("20");
    }
```
* reload the page

If something is wrong then post the new entries from `teampass_log_system` table

**Comment by errano** [comment]
I roller back to 2.1.26, i wil do an uprade in the next days again and i will let you know.

Thank you for your support.

**Comment by Raboo** [comment]
@nilsteampassnet tested your patch.
Still don't work.
The reply i get from items.queries.php is `j/NVWtvb29s=`

**Comment by errano** [comment]
Hello Nils,
i tired an upgrade again after 4 months but got the same error after the upgrade.
I've also tested your patch but got the same error, i tried on differents pc's.
Another strange thing is that if i login as admin i also cant see the users to edit or create a new one.

hope this helps.
thank you

**Comment by errano** [comment]
another thing is that if i try to export as PDF passowrd are not correct.
might be something with the salt key during upgrade?

**Comment by monisplit** [comment]
n my case I had those problems when positioning on folders, when doing a search in the bbdd table teampass_items I discovered that I had elements created with spaces in front and some characters that did not recognize well the php type Ñ, accents etc. I have done update of these elements in the bbdd and it has worked
