### ISSUE TITLE
Is there a auto type / auto fill form feature  or plugin?

### ISSUE THREAD

**Issue by pwFoo** [nilsteampassnet/TeamPass#2068]
Hi!

I' searching for a password safe with auto type / auto fill form feature. It looks like TeamPass haven't such a feature or browser plugin?

Regards

**Comment by nilsteampassnet** [comment]
I'm currently working on TeampassConnect.
It is a webbrowser interface that I'm currently entirely rewriting to fit webextension standards so that it should first work on Firefox and in a  second step in Chrome.
First version will be available in January.

**Comment by nilsteampassnet** [comment]
Closing this
