### ISSUE TITLE
Bug: Teampass 2.1.27.10, Copies a read-only folder to a read-only folder.

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2069]
Hi, 

I've just upgraded our application to the newest version of the teampass and started testing (2.1.27.10).

Screenshots bellow:
[RO_COPY.zip](https://github.com/nilsteampassnet/TeamPass/files/1587318/RO_COPY.zip)
### Steps to reproduce
1. Copy a read-only folder to a "read-only" folder to another
2.
3.

### Expected behaviour
It shouldn't copy an original read-only folder to another read-only folder.

### Actual behaviour
It creates an RW folder(originally a RO folder), into another RO folder.

### Server configuration
**Operating system**:
linux 7
**PHP version:**
PHP 7.0.20
**Teampass version:** 
2.1.27.10

**Comment by nilsteampassnet** [comment]
Fixed in development branch.

Thanks

**Comment by asgomes** [comment]
Hi Nils, 

sorry for reopening, or even to answer, but I installed the development version from yesterday, and We can't login through LDAP users, only for local, like admin.

it says "Login credentials do not correspond!" in the login page and there are no errors on error_log , and nothing special in access_log. :|
