### ISSUE TITLE
Feature question (not request) about Basic auth

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2070]
Hello, 

I found documentation about the API about Basic auth ( **http://teampass-api.readthedocs.io/api/authorization.html** )

Can basic auth be used to log in users in the regular interface also? (I have a reverse proxy that sends the users LDAP credentials as basic auth (in the HTTP header).)

Is it possible to log in the user using the Basic auth into teampass?

**Comment by nilsteampassnet** [comment]
No this is not possible.
Going through the auth UI is mandatory for a user to access the interface.

**Comment by finalbeta** [comment]
Hi Nils, is this a design choise? (Do I bother posting this as a feature request?)

I have a reverse proxy in front of the installation. This reverse proxy handles 2FA. Delegating this to the Teampass would not be wanted.

**Comment by nilsteampassnet** [comment]
I'm not sure to understand your point in fact.

I don't see the need to log users using the API, they can log in using the GUI and their internet browser.
I must have missed something ...

**Comment by finalbeta** [comment]
Hi Nils, 

In my case, the teampass server is setup behind a reverse proxy server. 
the user connects to https://reverseproxy/teampass and is asked by the reverse proxy for his (LDAP) credentials and a token (2th factor).
If the user provides the correct information. The reverse proxy forwards the following requests to the teampass backend server, the reverse proxy also send the users LDAP information as a basic auth allong with the request. This way the user only has to provide his ldap info to the reverse proxy, and not first to the reverse proxy, and then again to teampass. 

(This also allow the user to authenticate to the reverse proxy once, and the reverse proxy can forward the info to teampass, and other services also. In the end, the user only has to auth once, instaid off having to provide his ldap credentials for several differend backend servers.

**Comment by nilsteampassnet** [comment]
I'm not sure to understand the technical aspect of your network.
So it is not easy for me to be sure on how to answer you here.

I believe that if we needed a "pre-check" before authentication then the place to inject the check is correct.
You should take example of the pre-check "identify_user_with_agses" to implement your condition.

**Comment by finalbeta** [comment]
Nils, perhaps this will make it a bit clearer what I'm trying to do. 

![image](https://user-images.githubusercontent.com/22134261/35069814-a230fe0e-fbdb-11e7-9bf1-0fe0bdc198a9.png)

I want to have an option that allows me to use the value of $_SERVER['PHP_AUTH_USER'] and $_SERVER['PHP_AUTH_PW'] to log the user in to teampass. 

In my network, the PHP_AUTH_USER and PHP_AUTH_PW hold the users ldap logon and password. 
Meaning, if I can grab this in teampass, the user doesn't have to log in an extra time. 

(In the screenshot I'm including more then I need personally, but perhaps this would be a usefull addon to teampass.)

The screenshot above is what I have right now. I can read the setting from tp.config.php, but I can't yet write it. I don't yet understand how the saving of settings works. But I'll figure it out. (I think :) )

**Comment by finalbeta** [comment]
Hi Nils, 

I understand how the settings saving works (kindoff), I kept it simple: 
![image](https://user-images.githubusercontent.com/22134261/35175462-0c81e568-fd74-11e7-8864-ad2c7031a5e3.png)
When a user browses to the index page, I can parse this username and password using something like this in index.php:

>         //	Automatic login using basic auth
		if (isset($SETTINGS['use_http_request_login']) === true && $SETTINGS['use_http_request_login'] === '1' && isset($_SERVER['PHP_AUTH_USER'] === true) ) {
				if (isset($SETTINGS['remove_domain_from_login']) === true && $SETTINGS['remove_domain_from_login'] === '1' && strpos($_SERVER['PHP_AUTH_USER'], '@') !== false) {
					$username = explode("@", $_SERVER['PHP_AUTH_USER'])[0];
				}else{
					$username = $_SERVER['PHP_AUTH_USER'];
				}
				require_once 'sources/identify.php';
				// try to log in? : identifyBasicAuthUser($username, $_SERVER['PHP_AUTH_PW']);
	        }
	    }

I tried to call sources/identify.php and create a function to log the user in, but at this point, I'm failing. 

The only thing I can do to make it work is echo the username/password into the html (which is horrible since it might get cashed onto the end users system). 

I'll continue to try. If you have pointers/tips/are willing to help, feel free :)

**Comment by finalbeta** [comment]
Hi Nils, 

I've got a working setup now. ( https://github.com/finalbeta/TeamPass in master )

The following options need to be added to tp.config.php

    'enable_http_request_login' => '1',
    'force_http_request_login' => '1',
    'remove_domain_from_login_http_request' => '1',

enable_http_request_login = If the server detects login information in the header, it will use it. 
force_http_request_login = if the server detects login information in the header, it will use it, and the logon form will auto logon after  seconds. 
remove_domain_from_login_http_request = this will remove the domain part from the username. Meaning, mydomain\test or test@mydomain.tld will become "test"

![image](https://user-images.githubusercontent.com/22134261/35593699-e6548058-0610-11e8-8f80-cd2747c8cc2a.png)

So these changes allow a proxy in front of the device to pass the credentials of the already authenticated user to teampass and automatically log the user in to teampass. 
(Please note, credentials are never send in the form. )

Is this something you could consider adding to teampass? what changes would you need to have this added?

**Comment by finalbeta** [comment]
I've added support for maintenance mode. Maintenance mode now disables this feature.

**Comment by peacand** [comment]
Hi @finalbeta 

I'm interested about the job you've done on this topic. Do you still have the piece of code you made to get this scenario working ? Would you agree to share it ?

**Comment by finalbeta** [comment]
Hi Peacand, 

The code got broken in updates and in a way was not a good fit for the system, but more a hack. You can find the original commit here: https://github.com/nilsteampassnet/TeamPass/pull/2111/commits/6b3dda304ae0801dd8b3988714cf194266cd043d

(I can comment on it if needed, but we no longer use it. We are using the API now)
