### ISSUE TITLE
Search not working for items with multiple "Restricted to:" roles selected

### ISSUE THREAD

**Issue by yavin48** [nilsteampassnet/TeamPass#2071]
### Steps to reproduce
1. Create a new item and select two different Roles in "Restricted to:"
2. Using the search, attempt to find the new item

### Expected behaviour
The item should show up in the search

### Actual behaviour
The item will not show up in the search. If you remove one of the roles from the restriction, it will work. It will also work if you have multiple users selected under "Restricted to:", but not if  you have multiple Roles.

### Server configuration
**Operating system**:
sles 12 sp2
**Web server:**
Apache/2.4.23
**Database:**
mysql Ver 15.1 Distrib 10.0.30-MariaDB
**PHP version:**
7.0.7
**Teampass version:** 
2.1.27.10
**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
Chrome and Firefox
**Operating system:**
Opensuse, Windows 7, Windows 10
#### Web server error log
There are no errors in the web logs

[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1591405/tp.config.txt)

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

I will check this.

**Comment by nilsteampassnet** [comment]
Ok, I confirm the case where the item is related to several group where at least one of them is not related to the user.
Example, user belongs to groupA and groupB.
Now Item is restricted to groupB and group C.

So the user should see it in the search but it is not the case.

I will provide a fix for this.

**Comment by nilsteampassnet** [comment]
Fix committed in development branch.

Please reopen on need.
