### ISSUE TITLE
Issue - can't Import items Json error

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2072]
Hi, 

We've been trying to import items from a import.csv .

The result is a Request JSON parse failed.

### Steps to reproduce
1. select folder
2. import items
3. select file and open
4. JSON error appears and does nothing

I've tried this import file as the example, I even tried with comma separated and only with the fields describe in the 3 Screenshot.

### Expected behaviour
It should import the file to the pre-selected folder

### Actual behaviour
It drives the processe well, but it does nothing in the end.

### Server configuration
**Teampass version:** 
2.1.27.10

### Client configuration
**Browser:**
mozila
**Operating system:**
windows 10

#### Web server error log
No errors in error_log

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
File.lastModifiedDate foi descontínuado, Em alternativa, utilize File.lastModified.
plupload.full.min.js:13:29996
```
it's a warning means its discontinued.

Here are the screenshots

[Import_CSV.zip](https://github.com/nilsteampassnet/TeamPass/files/1591739/Import_CSV.zip)

**Comment by nilsteampassnet** [comment]
I couldn't reproduce.
PLease provide the file you are trying to import.

Can you also run this query
`SELECT * FROM `teampass_log_system` WHERE type="error" ORDER BY date DESC `

**Comment by asgomes** [comment]
Hi Nils, I'm sending both, This is an environment test.

I've reproduced the error and spooled the log table.

[export_teampass_log_system.zip](https://github.com/nilsteampassnet/TeamPass/files/1600472/export_teampass_log_system.zip)

**Comment by nilsteampassnet** [comment]
Perhaps an issue in your csv file.

Here is an example of how a csv file should be structured.

```
label,login,password,url,comments
"Lo'&`égan","MyLog'an","YoupiCheap","http://www.logan.fr",""
"Logan2","MyLogan2","YoupiCheap2","http://www.logan2.fr",""
"#1866-1","MyLogan2","YoupiCheap2","http://195.218.52.38",""
"#186-2","MyLogan2","YoupiCheap2","",""
```

**Comment by asgomes** [comment]
Hi,

Guess we can close this, it works fine with your csv file. 
Thanks

**Comment by nilsteampassnet** [comment]
OK thanks
