### ISSUE TITLE
Issue - Move selected Items button

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2073]
Hi,
We're using the teampass version 2.1.27.10, and we tried to move more than one file from the find menu, and we don't have any error, it says sucessful, but it does nothing.

### Steps to reproduce
1. Enter the find screen, select more than one item.
2. hit the move select files button, and select the destination folder.
3. hit OK

### Expected behaviour
It should have moved the files to the destination folder, so (copy the items and then delete the files)

### Actual behaviour
It says Ok, but it does nothing.

### Server configuration
**Teampass version:** 
2.1.27.10

**Updated from an older Teampass or fresh install:**
#### Web server error log
Logs shows nothing

Here are the screenshots.
[Bulk_Move_items.zip](https://github.com/nilsteampassnet/TeamPass/files/1591774/Bulk_Move_items.zip)

**Comment by nilsteampassnet** [comment]
Correct.
In some case, this issue could happen.
Thank you for reporting.

**Comment by nilsteampassnet** [comment]
Please reopen if not fixed.
