### ISSUE TITLE
Scripted backup change

### ISSUE THREAD

**Issue by darren-harrison** [nilsteampassnet/TeamPass#2074]
[tp.config_sanitised.zip](https://github.com/nilsteampassnet/TeamPass/files/1592355/tp.config_sanitised.zip)

### Steps to reproduce
1. Run 'php /teampass/www/backups/script.backup.php --key="<key removed>"

### Expected behaviour
A backup created

### Actual behaviour
Returns [{"error":"no_key_provided"}]
This worked in 2.1.26 but didn't use the key option. I have tried quite a number of ways of trying to pass in the parameter but none seemed to work. I tried using wget/curl but it seems this script can only be called from the command line.
After upgrading to 2.1.27, I check settings and noticed I needed to add a key to the backup settings, which I did. Then I used the same key for the script but haven't been able to get it working.

I've spent time looking for an example of using backup, but have been unable to find anything.

### Server configuration
**Operating system**: Debian 8
**Web server:**: Nginx 1.10.3
**Database:** MySQL 5.5.58
**PHP version:** 5.6.30
**Teampass version:** 2.1.27
**Updated from an older Teampass or fresh install:** Upgraded
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome
**Operating system:** Ubuntu 17.10

#### Web server error log
```
Nothing relevant
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
n/a/
```

**Comment by nilsteampassnet** [comment]
The fix was provided.

Reopen on need.

**Comment by billo33** [comment]
What is the fix for this issue?

**Comment by nilsteampassnet** [comment]
It has been committed in `development` branch.
See the commit indicated upper this message

**Comment by neryangj** [comment]
@billo33 were you able to run the script on your machine ?
I tried the below, but still says no_key_provided 

bash-4.3# php script.backup.php --key="somekey"
[{"error":"no_key_provided"}]bash-4.3#

but this works when I accessed it on browser https://xxxx.co.nz/backups/script.backup.php?key=somekey
