### ISSUE TITLE
issue: Button "delete selected Items" doesn't work.

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2075]
Hi,

We have teampass 2.1.27.10, and we're unable to delete massive item.

The button simply doesn't work.

We tried to select 2 items in the Find menu, and hit the delete selected items.

Then appears the "mass operation on Items" window with the ok and cancel button, If we hit the Ok button the "Please wait!" message appears, and it does nothing.

In the access_log we don't have much information, and none information on error_log, or doing ctrl+alt+i .

### Steps to reproduce
1. Find menu, select multiple items
2. hit delete selected items button
3.Mass operation on Items, hit OK

### Expected behaviour
It should delete the selected and corretly presented Items on the window of the mass operation Items.

### Actual behaviour
Actually it does nothing.

#### Web server error log
[29/Dec/2017:16:26:42 +0000] "POST /teampass1/sources/items.queries.php HTTP/1.1" 200 86 "http://xxxx/teampass1/index.php?page=find" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

[deletemassiveitems.zip](https://github.com/nilsteampassnet/TeamPass/files/1593492/deletemassiveitems.zip)

**Comment by nilsteampassnet** [comment]
Tahnk you, I found the reason why.

**Comment by nilsteampassnet** [comment]
Please reopen if not fixed.

**Comment by janwagners** [comment]
Hello,

we experience the same problem as mentioned by the issue creator with the same behavior. Are you sure that this issue is fixed? 

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** apache 2.4.18

**Database:** mysql 5.7.21

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**Comment by nilsteampassnet** [comment]
As you can see with previous message that this is fixed in development branch
