### ISSUE TITLE
Unable to view folders contents. Times-out with no information in error message and 2nd error message reports "Hacking Attempt".

### ISSUE THREAD

**Issue by skalups17** [nilsteampassnet/TeamPass#2076]
### Steps to reproduce
1. Login to Teampass successfully as manager and see view of whichever folder is already selected.
2. Click on any other folder and spinning gear times out with a blank error message.
3. Attempt to click again and receive "hacking attempt" error.
4. Sometimes reloading the cache during an admin login permits one click on one other folder successfully followed by results of steps 2 & 3 if there is another folder view attempt.

### Expected behaviour
Tell us what should happen

Folders and their contents should load and display contents when clicked on.

### Actual behaviour
Tell us what happens instead
Spinning gear times out and then returns and info block with no  information. A second click on the folder reports an error "Hacking attempt".

### Server configuration
**Operating system**: Microsoft Windows Server 2016 Standard

**Web server:**

WAMP server Apache 2.4.27

**Database:**

MariaDB 10.2.8

**PHP version:**

5.6.31

**Teampass version:** 
2.2.27
**Teampass configuration file:**

[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/1597565/tp.config.php.zip)
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/1597567/tp.config.php.zip)

**Updated from an older Teampass or fresh install:**. FRESH INSTALL
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox, Safari, Explorer
**Operating system:**
OS X High Sierra 10.13.1
#### Web server error log

[apache_error.log.txt](https://github.com/nilsteampassnet/TeamPass/files/1597572/apache_error.log.txt)
```
Insert your webserver log here
```

[access.txt](https://github.com/nilsteampassnet/TeamPass/files/1597633/access.txt)

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
SCRIPT5007: Unable to get property 'length' of undefined or null reference
jquery.js (631,4)

**Comment by nilsteampassnet** [comment]
Can you please ensure that those points are satisfied => http://teampass.readthedocs.io/en/latest/errors/

**Comment by skalups17** [comment]
Yes - the Teampass Settings and CSRFProtector settings were already set. The web server is apache so the IIS settings do not apply and I did change the session.gc_maxlifetime config value inside php.ini to 7200 per instructions however after this when attempting to read a folder the same errors are displaying after the operation runs for several minutes.

**Comment by skalups17** [comment]
The problem has not been solved though this is marked as 'answered'. Is there any other log or information which could help to solve the issue?

**Comment by nilsteampassnet** [comment]
* do CTRL+SHIFT +i to open the console
* select tab `Network`
* click on the last query with `items.queries.php`
![image](https://user-images.githubusercontent.com/1197546/34637707-1a1148f8-f2bc-11e7-85eb-98c5a7694424.png)
* click on tab `Response`
![image](https://user-images.githubusercontent.com/1197546/34637709-353c25e4-f2bc-11e7-8703-33884f6c5dc1.png)
* Provide the text in the `Response`

Please provide also the results of this query
```
SELECT label FROM `teampass_log_system` WHERE type="error" ORDER BY date DESC
```

**Comment by skalups17** [comment]
When I logged today to gather this data there was a flurry of backed up email login notifications (all the way from mid December 2017) that were received all at the time of this login. Then the error did not reproduce and the Teampass website is currently functioning perfectly. Seems related to something with SMTP login notifications.

**Comment by nilsteampassnet** [comment]
OK thank you for sharing this.
