### ISSUE TITLE
bug: Purge Logs not selection not working properly

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2078]
Hi,

We've the 2.1.27.10 version of teampass, and we tried to delete some logfiles, and all retrieve the same result.

We use the calendar to define with time window of log we wish to delete, and it retrieve"Purge done number of elements deleted : 0 "

and we defined a time window with a lot of incidents.

### Steps to reproduce
1.access to admin, log section
2. select the dates between we wish to delete the logs
3. purge button

### Expected behaviour
Hit should select the elements we wish to delete

### Actual behaviour
the select is not working. it says 0 elements in which range of dates we tried

### Server configuration

I assume its the select is not working properly.

Tell me if u need more information. ty
  Here are some SS:

[Purgelogs.zip](https://github.com/nilsteampassnet/TeamPass/files/1601413/Purgelogs.zip)

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Correct, there is an issue on the date format convertion that could lead to "nothing done".
I've fixed this in development branch.

Now keep in mind that the purge on tab "items" will only delete `accessed` entries. All other entries will be kept as they are part of the history of the Items.

Please reopen if not solved in our case.
