### ISSUE TITLE
Email administrators when password item is viewed sits in queue till forced sent

### ISSUE THREAD

**Issue by BiRo70** [nilsteampassnet/TeamPass#2080]
### Steps to reproduce
1. User views any password
2. no email is received
3. as TeamPass admin check the email settings and under Email tasks there are email waiting to be sent

_Additionally it seems the email is never sent if you copy the password in the clipboard.
To me it is like viewing it and should be notified.
I can't find where to set this behavior up._
![selection_20180104_121117](https://user-images.githubusercontent.com/19203891/34563198-8d5c8d6e-f149-11e7-92f7-a5cc709d7667.png)

### Expected behaviour
Admin should receive an email of password viewed and/or copied to clipboard.

### Actual behaviour
emails sits in queue until pushed

### Server configuration
**Operating system**:
CentOS Linux release 7.4.1708 (Core) 
Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd -version
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16

**Database:**
mysql --version
mysql  Ver 14.14 Distrib 5.6.38, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
php --version
PHP 5.6.32 (cli) (built: Oct 29 2017 14:02:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Teampass version:** 
2.1.27.10

**Teampass configuration file:**
[tp.config.php.gz](https://github.com/nilsteampassnet/TeamPass/files/1603232/tp.config.php.gz)

**Updated from an older Teampass or fresh install:**
updated from 2.1.25.2 to 2.1.26.3 and then to 2.1.27.10

### Client configuration
**Browser:**
Chrome and Firefox

**Operating system:**
Linux and Windows

#### Web server error log
```
[Sun Dec 31 07:45:25.231666 2017] [auth_digest:notice] [pid 35344] AH01757: generating secret for digest authentication ...
[Sun Dec 31 07:45:25.243921 2017] [lbmethod_heartbeat:notice] [pid 35344] AH02282: No slotmem from mod_heartmonitor
[Sun Dec 31 07:45:25.616812 2017] [mpm_prefork:notice] [pid 35344] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.32 configured -- resuming normal operations
[Sun Dec 31 07:45:25.616828 2017] [core:notice] [pid 35344] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
N/A

No syslog entry on server

Hi, how can I further debug this issue.
If you can point me where in the PHP code the sending of the email is triggered I can a have a look.

Thanks
r.

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Emails are sent only every 5 minutes depending on users activity in Teampass.
Indeed there is no cron defined on the server to perform this task.
So potentially some emails may not be sent fastly.

Regarding your suggestion of email sending when user copies the password in clipboard, it is correct. I have added this.

Proposal is committed in development branch.
