### ISSUE TITLE
LDAP bug, can't check connection

### ISSUE THREAD

**Issue by andreyp1986** [nilsteampassnet/TeamPass#2081]
### Steps to reproduce
1. Configure ldap connection
2. Press "Check connection"

### Expected behaviour
Message "User authenticated"

### Actual behaviour
See 'No options' message

### Server configuration
**Operating system: Debian

**Web server: Nginx

**Database: MySql

**PHP version: PHP 5.6.30

**Teampass version: Latest master branch (2.1.27.10)

### Client configuration
**Browser: Chrome
**Operating system: Windows10

sources/admin.queries.php
    case "admin_ldap_test_configuration":
        // Check
        if (null !== $post_option || empty($post_option) === true) {
            echo '[{ "option" : "admin_ldap_test_configuration", "error" : "No options", "post_option" : '.$post_option.' }]';
            break;
        }

null !== $post_option -> throw error. 
It has to be null === $post_option

**Comment by nilsteampassnet** [comment]
Yes you are absolutely right.

Thank you for sharing this.
