### ISSUE TITLE
API Question: Reading/creating folders

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2082]
Hello Nils, 

I've been playing with the API. I wish to create a folder for each "installation" I have. The installations are in a "remote db".
Since this is an automation tasks, I should rerun the task every X minutes/hours since the remote system can hold new installations at any point. This gives me a problem when using the API.

Logic would tell me that first I list the folders inside the teampass system, and then create the folders that are missing. 
However, using the API, this is a problem, since creating a folder in the API doesn't mean I can list them using the API. 
After creating the folder in the API I have to manually go into the GUI, and give a user rights to it beforce I can list them? (or am I missing something)
If I don't do this, the API will try to create the same folder each time and create duplicates? 

(PS, as I post this, I also checked this setting 
![image](https://user-images.githubusercontent.com/22134261/34674245-6df45b48-f485-11e7-9f83-0a3782e79c42.png)
However, when you are using the API, these settings are not enforced, you can still make duplicate names using the api:
![image](https://user-images.githubusercontent.com/22134261/34674449-34100c6e-f486-11e7-927b-0ba3adb62a9c.png)

Am I missing something in the API? (Or is the API missing something to make this possible)

**Comment by nilsteampassnet** [comment]
Thank you for your tests and reporting them here.

You are right, there is a bug with the folder duplicate check.

Regarding the initial point, I need to improve the API to add this possibility.
The API is more basic than the GUI and a lot of "features" are not available using it.

**Comment by finalbeta** [comment]
Ok, thanks for your quick follow up. (and great software)
I will keep an eye on this issue and test if the code gets an update for this.

**Comment by finalbeta** [comment]
Since your commit adds a feature (role enheritence), but does not solve the duplicate folder check. 
I will leave it up to you if you wish to close this issue (depends on how you want it to work). 

I have tested your code change for the role enheritance, and it works are expected, for me this is enough (and a great) change. 

Thank you!

**Comment by finalbeta** [comment]
My bad, I just saw that the code now checks for duplicate folders too and gives "err: data already exists" if you try to add a duplicate. 

I can confirm this is working and I'm closing this. (thanks again)
