### ISSUE TITLE
Access to password item denied!

### ISSUE THREAD

**Issue by phearomsin** [nilsteampassnet/TeamPass#2083]
All the users are facing this issue.
This is how you can reproduce it when you logged in to the Teampass.

### Steps to reproduce
1. Open the browser and then, new tab with incognito/private window
2. Go to http://localhost/teampass
3. Log into the server and click on Items page
4. Search for any items

### Server configuration

**Teampass version:** 
2.1.27.10

### Client configuration
**Browser:**
Chrome
Firefox

![screenshot](https://user-images.githubusercontent.com/33160904/34716064-4f6097b4-f561-11e7-83d9-1e0082cf95f9.png)

**Comment by nilsteampassnet** [comment]
Can the users access those items out of search feature ? Meaning that access id possible while selecting the item from the normal tree view.

Can you provide Tp.config.php fille ?

**Comment by phearomsin** [comment]
Yes, we can.
We cannot access the items from search feature and it always keeps showing the message " **Access to password item denied!** " when we first logged in or use new incognito/private window on the browsers to log in to the Teampass.

[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/1618689/tp.config.php.zip)

**Comment by nilsteampassnet** [comment]
Do you mean that this occurs in one of next 2 conditions?
* when using an incognito window
* when first logged in

So it means that you don't have this when:
* either using a normal window
* or once logged for the 2d time

correct?

**Comment by phearomsin** [comment]
That's all correct.

**Comment by nilsteampassnet** [comment]
I've tried on several machines and browsers but couldn't reproduce this behavior.

What kind of server do you have? linux or IIS?

**Comment by phearomsin** [comment]
I installed Teampass in linux server with:

**Operating system**:
Debian GNU/Linux 8
**Web server:**
Apache/2.4.10
**Database:**
mysql  Ver 14.14 Distrib 5.6.37
**PHP Version:**
PHP 5.6.30-0+deb8u1

**Comment by mhsasan** [comment]
What I found is a shared password item must be Musk and Visible before you share it. Also, the user you want to share the password item also be listed in the "Email Link to user" field in the item's Password and Visibility field; otherwise, you see the denial message. Hope this help.

**Comment by halobolah** [comment]
Hi 
I don't want to open new ticket so I am writing here :)

My problem is:

1. user "aga1" logged in to teampass and do something
2. user "aga1" logged out
3. user "marcin1" logged in to teampass and got an error:

![obraz](https://user-images.githubusercontent.com/28426539/57830664-149a0400-77b3-11e9-82c9-e643cacdc14c.png)

4. user "marcin1" doesn't have permissions to TEST_DQ, so why this error occurs ?
5. when user "marcin1" logged out and user "aga1" logged in to system, situation is the same - error "Access to password item denied!"

![obraz](https://user-images.githubusercontent.com/28426539/57830804-8b370180-77b3-11e9-974c-42f73476cd6e.png)

I use development branch 2.1.27.36, firefox, IE, chrome - doesn't matter

How to fi it ?? :)

**Comment by halobolah** [comment]
Hey guys, any help ??
