### ISSUE TITLE
Hacking attempt when trying to download .bak file

### ISSUE THREAD

**Issue by morrthal** [nilsteampassnet/TeamPass#2084]
### Steps to reproduce
1. Find an item with attached .bak file
2. Click the link to download the file
3. White page with "Hacking attempt..." is displayed

### Expected behaviour
The file should be downloaded.

### Actual behaviour
White page with "Hacking attempt..." is displayed

### Server configuration
**Operating system**: Ubuntu 14.0.4.5 LTS

**Web server:**

**Database:**  MySQL Ver 14.14 Distrib 5.6.31

**PHP version:** Apache/2.4.23 (Unix)

**Teampass version:** 2.1.26

### Client configuration
**Browser:** Chrome/FF/Explorer - > same behavior

**Operating system:** Windows 8.1

**Comment by morrthal** [comment]
The issue so far is limited only to .bak files, other files download fine.

**Comment by nilsteampassnet** [comment]
I've tested this on latest version and didn't had any issue
Perhaps is there in this old version an inconsistency regarding this kind of extension even if I don't understand why.
The script doesn't take into the file extension unless it is an non authorized one.

I don't really see what could be wrong here. I cannot investigate further on this old version.
