### ISSUE TITLE
Import Keepass 2.x XML fails with: Requested JSON Parse failed

### ISSUE THREAD

**Issue by Cr0wl3r** [nilsteampassnet/TeamPass#2085]
### Steps to reproduce
1. Create a new Database with Keepass 2.37
2. Create a new Entry with notes greater 500 letters (500 will work)
3. Export the keepass db as KeyPass XML (2.x)
4. Import the XML to Teampass

### Expected behaviour
Import should work without error. The description field in mysql is text and should work with 500+ letters.

### Actual behaviour
Import will fail with message: Requested JSON parse failed.
Teampass error log shows that the import tries to insert the value from the keepass notes to the teampass decription and url field and fails because value is to long for url field.

### Server configuration
**Operating system**: Ubuntu 16.04.03 LTS

**Web server: apache2**

**Database: mysql 5.7**

**PHP version: 7.0.22**

**Teampass version: 2.1.227.9** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: Google Chrome**

**Operating system: Windows 10**

### Logs

Teampass error log will show:
```
Query: INSERT INTO `teampass_cache` (`id`,`label`,`description`,`url`,`tags`,`id_tree`,`perso`,`login`,`restricted_to`,`folder`,`author`,`renewal_period`,`timestamp`) VALUES (347, 'gittest', 'qwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfd', 'qwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfghjklyxcvbnmqwertzuiopppppppasdfd', '', '218', 0, 'gittest', '0', 'New Group', '10000000', '0', 1515511373)<br />Error: Data too long for column 'url' at row 1<br />@ /sources/import.queries.php

**Comment by nilsteampassnet** [comment]
The error comes from your URL field that is too long and on which it is lacking a truncation.

I will fix this.
