### ISSUE TITLE
Custom Fields - create one Field in a category, but all custom fields are displayed

### ISSUE THREAD

**Issue by go2this** [nilsteampassnet/TeamPass#2087]
### Steps to reproduce
1. First create a custom field and assign it to a folder
![5](https://user-images.githubusercontent.com/34249133/34767954-c3c47e02-f5f9-11e7-9461-686df2dcd3f2.jpg)

2. Add a item in this folder
![10](https://user-images.githubusercontent.com/34249133/34766863-3593aa8e-f5f6-11e7-83cd-6cbf18c03fb8.jpg)

3. If you then look at the item, all custom fields are displayed.  
![20](https://user-images.githubusercontent.com/34249133/34767318-0dd906ae-f5f8-11e7-8234-1f3253bbffd1.jpg)

### Behaviour
Created an custom field in a category, but all fields of all categories are displayed.

### Server configuration
**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** MariaDB

**PHP version:** 7.1.12-2

**Teampass version:** 2.1.27.10

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1542215/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7 Prof. x64

**Comment by nilsteampassnet** [comment]
COnfirmed.

I will investigate.

**Comment by nilsteampassnet** [comment]
Fix is committed.

Please reopen on need
