### ISSUE TITLE
 Personal salt key set up/changes are faulty 

### ISSUE THREAD

**Issue by RockyJLU** [nilsteampassnet/TeamPass#2088]
Hello, 
We have following issue regarding personal salt key changes.
We are using LDAP backend and our TeamPass version is 2.1.27.10

Under this link https://teampass.readthedocs.io/en/latest/features/feat-prof/ u can find the image that i reference here:

![feat-prof-7](https://user-images.githubusercontent.com/34744855/34768187-73958d62-f5fa-11e7-8976-7a97b04549f0.png)

But our version looks like this:
![teampass-error-in-reset-salt-key](https://user-images.githubusercontent.com/34744855/34768250-aa2b800c-f5fa-11e7-932b-9098ab8f2bd4.png)

**Situation is:**
- No personal salt key set yet

**Problem is:**
- When we try to do a first ever set of the key with the option "Change your personal salt key" it doesnt work because the system wants us to give the old salt key even when none has been set yet.
- While doing the reset like in the second picture you cannot enter a new salt key like it is shown in the first picture.

**Comment by nilsteampassnet** [comment]
Ok there is some confusion here.

First, the screenshot needs to be updated inside the documentation page.

Second, if a user has never set a saltkey, he just have to set it using the menu icon `Set the saltkey`.
![image](https://user-images.githubusercontent.com/1197546/34789540-f404e0da-f63e-11e7-9c8a-f2181ea8a17c.png)

The function `Change SK` can only be used if you have previously used a personal SK to encrypt personal items.

I hope this is more clear.

**Comment by RockyJLU** [comment]
There is no option "Set the salt key" like in the screenshot. Is there a configuration i need to do manually as admin to get that option?

**Comment by nilsteampassnet** [comment]
Did you enabled "personal folders"?

**Comment by RockyJLU** [comment]
Upon enabling that, it worked. Thanks!

**Comment by nilsteampassnet** [comment]
Great.

I'm closing the ticket.
