### ISSUE TITLE
IE11 - Compabilitymode Intranet Sites - User cannot log in [Solution]

### ISSUE THREAD

**Issue by Fishy78** [nilsteampassnet/TeamPass#2089]
### Steps to reproduce
1. See #1869 

### Error description
The IE11/Egde browser setups the compability mode for intranet sites. Either the compability view must turned off or the page has to force the compability to EGDE to work fine:

Here's my diff, which is working fine now:
```
203a204
> <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

### References:
https://msdn.microsoft.com/en-us/library/ff955275(v=vs.85).aspx
https://social.msdn.microsoft.com/Forums/ie/en-US/acf1e236-715b-4feb-8132-f88e8b6652c5/how-to-overrde-compatibility-mode-for-intranet-site-when-display-intranet-sites-in-compatibility?forum=iewebdevelopment
https://blogs.msdn.microsoft.com/askie/2009/03/23/understanding-compatibility-modes-in-internet-explorer-8/

**Comment by nilsteampassnet** [comment]
Thank you.

Added
