### ISSUE TITLE
Minor bug: invalid level password persists

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2091]
Hi,

We have the latest development_version of teampass 2.1.27.10, downloaded 8th of January, 2018.

We forced an error, by changing the password for a level lower than permitted, for example, we have medium level permitted and we tried to change for a weak level.
The application blocks, and appears the error in a red background "Insufficient password strength".
After we cancel, if we try to open a new item, it comes with this error instant.

(I admit it, sometimes at the first try, i can't reproduce this, but we need to restart the login so it can clear the red background "Insufficient password strength" error.

--> 
### Steps to reproduce
1.edit an item, password separator
2. change a password for a lower strength level.
3. gives error  "Insufficient password strength".
4. access another item, comes with the same error without any reason.

### Expected behaviour
well it blocks, and the error should disappear, when we visit another item.

### Actual behaviour
The error appearrs in every item I open after the forced error.

[issue_passwod_level_strength.docx](https://github.com/nilsteampassnet/TeamPass/files/1627137/issue_passwod_level_strength.docx)
Here are the screenshots, this test visits the same edited Item, but it happens to every Item we visit.

The way to correct this, is to re-login.

Thanks once more.

**Comment by nilsteampassnet** [comment]
Thank you for reporting and for the word file.

I have checked but couldn't reproduce.
Perhaps last changes I did had a positive impact on what you are experimenting but I'm not sure.

I indeed get this warning when selection a password with compexity lower than the requested one.
Then I hit Cancel and jumped to another one that I modified with a new password (with correct level of complexity) and it get saved correctly.

**Comment by asgomes** [comment]
Hi Nils,

I reproduce the issue, when I'm editing an item, and I'm trying to change the password, for a very weak password, in the password level strength.

Imagine we have a folder that only permits a medium password level strength.
It returns a error of "insufficient password level strength", that is correct.

If I spam the save button 3 or 4 times (trying to force the weak password) , and then cancel, the red error persists, in every item, untill I relogon my user in teampass.

I hope this helps! 

Btw, I'm gettin the new development version today.
