### ISSUE TITLE
Bug role human resources

### ISSUE THREAD

**Issue by RomainLongeron** [nilsteampassnet/TeamPass#2093]
Hi 
I created several users with the role human resources but I am no tab (like the manager and administrator) that allows me to manage users. As we can see on the profile of this user.
![screenshot-2018-1-16 teampass](https://user-images.githubusercontent.com/33900818/34979394-75359a44-faa1-11e7-803b-9daee18493b1.png)
![screenshot-2018-1-16 teampass 1](https://user-images.githubusercontent.com/33900818/34979404-7a2e4708-faa1-11e7-8b62-a4297ec4475a.png)

**Comment by nilsteampassnet** [comment]
I confirm and will provide a fix.

**Comment by nilsteampassnet** [comment]
Reopen if needed

**Comment by RomainLongeron** [comment]
Okay thanks

**Comment by RomainLongeron** [comment]
Escuse me just

what is the purpose of OTV and API users and what is their basic password?

Thanks

2018-01-16 21:41 GMT+01:00 Nils Laumaillé <notifications@github.com>:
