### ISSUE TITLE
Issue on Microsoft's Edge Browser - Can't upload files on items.

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2095]
Hi,

We've been testing the recent development teampass from 2.1.27.10 from 15th of january 2018.

We tried to open the item and attach a file to it, but no window for browsing is opened on the edge browser.

### Steps to reproduce
1. Edit an Item, go to files & images.
2. Presse select button
3.

### Expected behaviour
should open the explorer window for browsing the file

### Actual behaviour
nothing happens, the window doesn't open.

### Server configuration
**Web server:**
Microsoft Edge browser

In all other browser's we tested works fine.

any information we can had?

Here are the screenshots of the test, for the example, they were taken from IE.
[IE_ss_uploadfiles.zip](https://github.com/nilsteampassnet/TeamPass/files/1638801/IE_ss_uploadfiles.zip)

**Comment by nilsteampassnet** [comment]
There is a bug in the upload library.
I will update it.

Thanks for reporting.

**Comment by nilsteampassnet** [comment]
CLosed.

Please reopen on need
