### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by RomainLongeron** [nilsteampassnet/TeamPass#2096]
Hi 
I wanted to know where were you changing the offline mode?
For my part I still have the problem where it works with very little file.
If I select 5-6 file I have this result:
![screenshot-2018-1-18 teampass off-line mode](https://user-images.githubusercontent.com/33900818/35091039-d392229c-fc3b-11e7-8313-96e1bda97f34.png)

**Comment by nilsteampassnet** [comment]
I indeed experimented this once but couldn't reproduce after refreshing the page.

Perhaps can you check what is output using the console of browser?

How many objects are exported? I'm using it very regularly by exporting in average 100 objects.

**Comment by RomainLongeron** [comment]
Just for 34 passwords it does not work
Actually I have 200 useful passwords

I checked if there are ever any pictures and no folders in these items
![screenshot-2018-1-19 teampass](https://user-images.githubusercontent.com/33900818/35141842-b20a464c-fcfc-11e7-9751-32815a02030d.png)
![sans titre](https://user-images.githubusercontent.com/33900818/35141848-b4ba4806-fcfc-11e7-8d92-e23c0abc5cbf.png)

**Comment by nilsteampassnet** [comment]
It can not be related to the numbers of items.
While comparing the source code and the error you have, it is related to the Key used.
Indeed this error is thrown only during the decryption key when the key is wrong.

But as I believe you are sure of it, I would ask you to try to export with a very simple key to check.

**Comment by RomainLongeron** [comment]
I had already tried with basic keys (for example 123) but that's not the problem.
The screen name 1 is with the right key.
The screen name 2 is with the wrong key.
![sans titre](https://user-images.githubusercontent.com/33900818/35225018-6941b624-ff87-11e7-80a0-2556c69ffe71.png)
![sans titre2](https://user-images.githubusercontent.com/33900818/35225022-6c0125f2-ff87-11e7-9187-dda8586f7824.png)

**Comment by borzel** [comment]
same situation in our instance :-|

**Comment by nilsteampassnet** [comment]
After investigations I could find that it was indeed related to amount of data exported.
I have provided a fix in Development branch.

Thanks for reporting.

**Comment by sticks221** [comment]
Hi,  I am still getting the same even with the development branch downloaded just now?  Do I need to do anything else to make the fix active?

Thank you in advance!

**Comment by nilsteampassnet** [comment]
Correct, In some cases the decryption was falling due to UTF-8 characters.
I've added a fix.

**Comment by sticks221** [comment]
Thank you but I have (I believe) applied the fixed version but still get the issue.  I installed the Development branch download yesterday as per your comment and today, I have applied the files specifically in the branch you referenced in the comment "https://github.com/nilsteampassnet/TeamPass/archive/a62382d8419d69940fb2a77a5944cee4521531a4.zip" but I still get exactly the same symptoms as described above.

Any help would be much appreciated.

**Comment by nilsteampassnet** [comment]
Can you please upgrade to 2.1.27.11 => https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.11

If it doesn't work then I'm not in good position because I've retried with my biggest database (more than 2500 items) and could get it managed.
I would need to investigate on your concrete case.

**Comment by sticks221** [comment]
It works! - thank you so much Nils, your work and assistance are very much appreciated :)
