### ISSUE TITLE
Subfolder not inheriting permissions

### ISSUE THREAD

**Issue by borisservo** [nilsteampassnet/TeamPass#2097]
Hello,

Upon creating a level 2 folder with a my user it doesn't carry permissions from the level 1, I have to login as "admin" and change its permissions for that specific role.

Should it inherit the permissions from level 1?
![screen shot 2018-01-18 at 16 15 47](https://user-images.githubusercontent.com/15837056/35108233-ec0ddfc6-fc6a-11e7-9a97-42761955a336.png)

Do I have something misconfigured? I am missing something? 

Thanks in advance.

**Comment by nilsteampassnet** [comment]
You certainly missed to enable the inheritage option

![image](https://user-images.githubusercontent.com/1197546/35112562-b45ca10c-fc7e-11e7-9610-1f8372e13bed.png)

**Comment by borisservo** [comment]
Hello @nilsteampassnet,

Thank you for the quick reply, that does the trick.

My apologies, I couldn't find that option.

Regards,

Boris
