### ISSUE TITLE
Generated password contains spaces

### ISSUE THREAD

**Issue by gulikoza** [nilsteampassnet/TeamPass#2098]
Hello,

It happens that generated passwords might contain spaces.
It has happened that space was at the beginning of the password string so it was not visible and even copy to clipboard did not work (perhaps the password string was trimmed in the application after entering it).

Space just seems like a bad character to have in password.
Perhaps there should be some option to configure which characters to exclude form generated passwords? Some characters have to be escaped (in passwords or passphrases) in some systems so having them in generated strings might cause problems.

**Comment by nilsteampassnet** [comment]
I don't know what version you use?
Why not to follow the proposed template?

The generator doesn't include space as a valid character.
```
            ->setParameter(self::PARAMETER_UPPER_CASE, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')
            ->setParameter(self::PARAMETER_LOWER_CASE, 'abcdefghijklmnopqrstuvwxyz')
            ->setParameter(self::PARAMETER_NUMBERS, '0123456789')
            ->setParameter(self::PARAMETER_SYMBOLS, '!@$%^&*()<>,.?/[]{}-=_+')
            ->setParameter(self::PARAMETER_SIMILAR, 'iIl1Oo0')
```

**Comment by gulikoza** [comment]
Hello,

Thank you for the answer.
Where is this code? I could only find similar code in TeamPass-master\includes\libraries\Encryption\PwGen\pwgen.php but not exactly like you have pasted it.

I'm testing on 2.1.27, yet selecting "secure" in the password generation dialog will generate password with a space:

Password : dE?N5nB>I lrQkxj[xnM

Quotes are also included, even if they are not listed in the code you have pasted above:

Password : Wms3-u"R${h+@W:2}lY=

**Comment by nilsteampassnet** [comment]
In `development` branch, for 2.1.27.11, pwgen has been replaced by another library.
The code shown above comes from it.
