### ISSUE TITLE
LDAP and Local accounts all broken except Admin

### ISSUE THREAD

**Issue by Mb1984** [nilsteampassnet/TeamPass#2099]
### Steps to reproduce
1. Upgrade from 10.1.27.1 to 10.1.27.10  (tried master and non master_
2. When that fails, Upgrade to 10.1.27.9
3. Also Upgraded to 10.1.27.6
4. Get stuck and create a new server using 10.1.27.10
5. Use same LDAP settings as previous version, but LDAP is broken.  
6. Create new local accounts, but can not login with them.
7. Upgrade PHP from 5.5 to 7.0, makes no difference.

### Expected behaviour
I'd expect to be able to login with ldap windows active directory account

### Actual behaviour
Logging in with local credentials responds with invalid credentials
Logging in with Windows account, wheel just spins forever, it never logs in.
If I check the login logs in teampass in the admin account, its constantly showing "user_not_exist"

### Server configuration
CentOS7
Apache 2.4
MariaDB
5.5 and also tried 7.0 (and 7.1 but I see that versions buggy).

**Teampass version:** 
2.1.27.6   2.1.27.9    2.1.27.10 
all versions contain same issue

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**  Both
PLEASE attach to this message the file `/includes/config/tp.config.php`.

[TPconfigPHP.txt](https://github.com/nilsteampassnet/TeamPass/files/1653565/TPconfigPHP.txt)

PLEASE NOTE,  I've tried ports 389 and 3268 (3268 worked on my previous instance)
Ive also tried listing domain controller my full 

name rather than IP (IP worked previous instance)

### Client configuration
**Browser:**
Tried Edge, IE. Firefox and Chrome

**Operating system:**
Windows 10

#### Log from the web-browser developer console (CTRL + SHIFT + i)

 Console is blank, shows no error

**Comment by nilsteampassnet** [comment]
PLease use `development` branch.
Then log as admin, go through each ldap setting to ensure all of them are stored.
Then retest.

**Comment by Mb1984** [comment]
I will do this tomorrow. But just to confirm, if you believe the development branch will resolve the ldap issue, do you think it will resolve the local users not being able to login as well?

I'm wondering if this isn't really an LDAP issue. Ill use the devolpment branch and let you know how it goes.
thanks

**Comment by Mb1984** [comment]
Ok I went ahead and did the upgrade.
So, now I am seeing similar issues to other upgrade attempts, mainly 10.1.27.6 where the ldap test shows invalid credentials.  (See Image 1)
![ldap](https://user-images.githubusercontent.com/35706404/35246035-460bed6c-ff93-11e7-8405-178881df0edc.png)

The credentials are valid I assure.

So next, I went in as Admin and create a local user account "test", 
I found I could log in with it only if I had LDAP disabled (which upon reading, is expected behavior).

So, it looks like this truly is an ldap issue.

**Comment by Mb1984** [comment]
Also, the blue gear doesn't seem to want to go away. It randomly will, but if I open in a new browser, it comes back.
No errors in Console
![ldap2](https://user-images.githubusercontent.com/35706404/35246694-986ed7f2-ff95-11e7-997b-f107e3af328d.png)

**Comment by roru69** [comment]
@Mb1984 

You use as "ldap_suffix" "@dc=mydomain,dc=com"

Please try: "@mydomain.com"

Regards, RoRu69

**Comment by Mb1984** [comment]
Hi,
 Ive tried this as well but with no luck. 
Ive setup a brand new instance with the latest version but the problem remains. I don't understand as it once worked perfectly with the older versions.

**Comment by Mb1984** [comment]
Would you like me to post any other config files? Is there anything else you could think of that I should try? Any LDAP plugins needed? thanks

**Comment by nilsteampassnet** [comment]
While looking to the settings, I could see that `ldap_domain_controler` and `ldap_domain_dn `settings are missing.
Can you please try to change all settings in ldap and see the "green check" appearing. Then change back to your correct values with "green check".

Then retry and share again the tp.config.php file

**Comment by Mb1984** [comment]
Hi
I went through each field and got the Green Checkmark.
I looked at the tp.config.php that I had posted and I do see the ldap_domain_controler  and ldap_domain_dn fields in it. Is this the file you were looking at?


Anyways, I'm failing with the same error.  Attached it my tp.config.php the latest.

**Comment by Mb1984** [comment]
![ldap](https://user-images.githubusercontent.com/35706404/35646906-ca3f8d5c-069e-11e8-8948-53907ef2de8e.png)

**Comment by Mb1984** [comment]
MYDOMAIN

**Comment by Mb1984** [comment]
Nils
I did as you said and received the Green Checkmarks.
I still had the same issues as before. I did see in the previous tp.config.php that it does contain ldap_domain_controler and ldap_domain_dnsettings

The new config I am adding here contains these entries as well. 

Any other thoughts? this account I am using definitely has appropriate access.
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1683301/tp.config.txt)


![ldap](https://user-images.githubusercontent.com/35706404/35647172-afd6937e-069f-11e8-8c2c-8dc3b64f9512.png)

**Comment by Mb1984** [comment]
'ldap_domain_dn' => 'dc=MYDOMAIN,dc=com',
    'ldap_domain_controler' => '10.0.2.20',

**Comment by Mb1984** [comment]
Nils, I think I got it. I took out the ****\  before my user name and tried and I got all success with the ldap user check.

I logged in now no issue.  Not sure what changed because I had tried this in previous attempts.  Somewhere along the way, we fixed it.  Thanks for your help.  

For the record, I believe I'm on the Development Branch.  Have so many snapshots I lost count
