### ISSUE TITLE
API not working in container.

### ISSUE THREAD

**Issue by lcworld** [nilsteampassnet/TeamPass#2100]
Hello

### Steps to reproduce
1. download docker-compose.yml from this folder
2. execute docker-compose up
3. configure teampass, and disable maintenance mode
4. enable API and create a key.
5. open http;//teampass/api/index.php/info/version/?apikey=...  (replace ... with key genreated in 4
    It returns HTTP error 404.

It's the same for all other items of the API.

### Expected behaviour
It should return the version in json format.

### Actual behaviour
It returns HTTP error 404

### Server configuration
Docker containers generated with docker-compose

### Client configuration
**Browser:**
All / curl in command line
**Operating system:**
All

#### Web server error log
```
172.18.0.2 - - [22/Jan/2018:23:33:28 +0000] "GET /api/index.php/info/version/?apikey=... HTTP/1.1" 404 1220 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
```

How to solve the issue ?

After some search in internet, I'm wondering if a URL rewriting is not missing in the nginx server configuration ?

**Comment by stravassac** [comment]
@lcworld like this thread
https://github.com/nilsteampassnet/TeamPass/issues/566
you can add in /etc/nginx/sites-available/default.conf
         location /api/ {
                try_files $uri $uri/ /api/index.php?$args;
       }
and in bash kill -HUP 1 (to reload)

**Comment by CayoM** [comment]
just for the record: this change doesn't seem to be in the latest docker image  from docker hub.

Anyways this doesn't seem to work for me. I keep getting a 301:

```
curl -k -XGET http://localhost:8088/api/index.php/read/folder/1?apikey=AxSdxVR76pn9P2QSYm8h6mjNAQg6sYvrDS3WXnU
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

as mentioned above, i updated the nginx config file:
```
        location /api/ {
                try_files $uri $uri/ /api/index.php?$args;
        }
```

```
teampass_1  | 172.28.0.1 - - [11/Dec/2018:10:24:34 +0000] "GET /api/index.php/read/folder/1?apikey=AxSdxVR76pn9P2QSYm8h6mjNAQg6sYvrDS3WXnU HTTP/1.1" 301 178 "-" "curl/7.47.0"
teampass_1  | 2018/12/11 10:24:34 [info] 19#19: *16 client 172.28.0.1 closed keepalive connection
teampass_1  | 10.0.2.2 - - [11/Dec/2018:10:25:15 +0000] "GET /api/index.php/read/folder/1?apikey=AxSdxVR76pn9P2QSYm8h6mjNAQg6sYvrDS3WXnU HTTP/1.1" 301 178 "-" "curl/7.59.0"
teampass_1  | 2018/12/11 10:25:15 [info] 19#19: *17 client 10.0.2.2 closed keepalive connection

```

Any idea what im doing wrong?

**Comment by s-loskutov** [comment]
Bad syntax in Dockerfile teampass/teampass:
`RUN sed -i "/^}/i \
  location /api/ {\
          try_files $uri $uri/ /api/index.php?$args;\
  }" /etc/nginx/sites-enabled/default.conf`
and API not accessible
would be:
`RUN sed -E -i '/^}/i\        location /api/ {' /etc/nginx/sites-enabled/default.conf && \
  sed -E -i '/^}/i\                try_files $uri $uri/ /api/index.php?$args;' /etc/nginx/sites-enabled/default.conf && \
  sed -E -i '/^}/i\        }' /etc/nginx/sites-enabled/default.conf `
you can use this image with fixed nginx config https://hub.docker.com/r/surfstudio/teampass
