### ISSUE TITLE
Importing item from keepass XML gives URL field as "0undefined"

### ISSUE THREAD

**Issue by sshipway** [nilsteampassnet/TeamPass#2104]
### Steps to reproduce
1. Create a keepass database entry with no URL defined
2. Export this to XML and import into Teampass
3. The Teampass URL is displayed as "0undefined"
4. Editing the entry shows a URL of "0".  Saving now displays as "0"

### Expected behaviour

A Keepass entry with no URL should be imported and displayed as a blank URL.

### Actual behaviour

The field is imported as undefined and displayed incorrectly.  Editing the field gives it a value of "0"

### Server configuration
**Operating system**:  Centos 7
**Web server:** Nginx
**Database:** Mariadb 5.5.56
**PHP version:** 5.6.32
**Teampass version:**  2.1.27.10 (development branch snapshot)
**Teampass configuration file:**

Using KeePass v2.32

**Updated from an older Teampass or fresh install:** update

### Client configuration
**Browser:** Firefox 45.0.2
**Operating system:** Linux

### Example data

This is the KeePass entry that caused the problem on loading (password and username changed for security)

```
                <Entry>
                    <UUID>sgEl40hwCEyRDvrI7VxT/g==</UUID>
                    <IconID>0</IconID>
                    <ForegroundColor />
                    <BackgroundColor />
                    <OverrideURL />
                    <Tags />
                    <Times>
                        <CreationTime>2016-01-15T09:44:23Z</CreationTime>
                        <LastModificationTime>2016-05-06T05:30:52Z</LastModificationTime>
                        <LastAccessTime>2016-05-06T05:30:52Z</LastAccessTime>
                        <ExpiryTime>2016-05-06T05:26:10Z</ExpiryTime>
                        <Expires>False</Expires>
                        <UsageCount>0</UsageCount>
                        <LocationChanged>2016-05-06T05:30:52Z</LocationChanged>
                    </Times>
                    <String>
                        <Key>Password</Key>
                        <Value ProtectInMemory="True">password</Value>
                    </String>
                    <String>
                        <Key>Title</Key>
                        <Value>Gmail</Value>
                    </String>
                    <String>
                        <Key>UserName</Key>
                        <Value>user@domain</Value>
                    </String>
                    <AutoType>
                        <Enabled>True</Enabled>
                        <DataTransferObfuscation>0</DataTransferObfuscation>
                    </AutoType>
                    <History />
                </Entry>
```

**Comment by sshipway** [comment]
Note that records that actually have URLs import correctly; it is only records with no URL that import incorrectly.

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass from admin settings page and I do not get the option to import in the folder menu. What I do?
