### ISSUE TITLE
All items are created as personal items

### ISSUE THREAD

**Issue by xFRaNeRx** [nilsteampassnet/TeamPass#2105]
### Steps to reproduce
1. Update from 2.1.26 to 2.1.27.10
2. Create an item in a shared folder

### Expected behaviour
The item should be created without the personal flag, and password should be seen by all members of role with permission on that item.

### Actual behaviour
The application asks for personal key in creation of items in shared folders
![imatge](https://user-images.githubusercontent.com/9591989/35383088-8bcd278c-01c1-11e8-88e3-3794f4937612.png)

If I put the salt key, the item is created as personal item, and nobody can see it, neither myself. I've looked in database and I've seen that value of field perso is 1. I've changed manually this flag and the i can edit the item but the password is lost.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS

**Web server:**
Apache/2.4.7 (Ubuntu)
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)

**Database:**
mysql 14.14 Distrib 5.5.57

**PHP version:**
5.5.9+dfsg-1ubuntu4.22

**Teampass version:** 
2.1.27.10

**Teampass configuration file:**
[tp.config.conf.zip](https://github.com/nilsteampassnet/TeamPass/files/1663396/tp.config.conf.zip)

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26

### Client configuration
**Browser:**
Firefox 58.0 (64 bits)

**Operating system:**
Antergos Linux
Description:    Arch Linux
Release:        rolling

#### Web server error log
There are some error logs about permissions on one directory. The log directory permission issue is solved now. Now I'm trying the api, and there are some logs about this too.

[apache2-error.log](https://github.com/nilsteampassnet/TeamPass/files/1663500/apache2-error.log)

#### Log from the web-browser developer console (CTRL + SHIFT + i)
I don't see any special log in developer console.

**Comment by nilsteampassnet** [comment]
How strange.
Can you please answer next questions?

1. You said you have upgraded. what about the "old" items? are they also impacted?
2. Only newly created items are impacted?

**Comment by xFRaNeRx** [comment]
The old items are not impacted, the are all accessible. The modifications to old items are working ok too.

The problem is only with new created items.

**Comment by xFRaNeRx** [comment]
There were many shared folders that had the personal_folder field at 1 in DB. I don't know why, this folder aren't personal folders before update. I've changed personal_folder field in DB for shared folders and now the problem is solved.
