### ISSUE TITLE
Unable to update from Teampass v. 2.1.22 to the latest version.

### ISSUE THREAD

**Issue by MoHD20** [nilsteampassnet/TeamPass#2106]
when I try to upgrade from teampass V. 2.1.22 © 2009 - 2014 to the new version TeamPass 2.1.27 
It stuck at this image:

![image](https://user-images.githubusercontent.com/12420351/35484468-de9f839e-0458-11e8-9c42-766c94af1437.png)

and I get this on error log

```
Sun Jan 28 11:21:21.892543 2018] [:error] [pid 7199] [client 192.168.0.228:62828] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you
used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/pp2d/public_html/includes/config/include.php on line 24
[Sun Jan 28 11:21:34.343475 2018] [:error] [pid 7197] [client 192.168.0.228:62836] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error file '/includes/config/tp.config.php' not exists' in /home/pp2d/public_html/sources/main.functions.php:27\nStack trace:\n#0 /home/pp2d/public_html/install/upgrade_ajax.php(45): require_once()\n#1 {main}\n  thrown in /home/pp2d/public_html/sources/main.functions.php on line 27, referer: http://pp2.fixed/install/upgrade.php
```

### Steps to reproduce
1. from version teampass V. 2.1.22  
2. Download latest package on your server
3. Unzip package into Teampass folder (could be another name) and overwrite existing files and folders,
4. Enter url http://your_domain/teampass/install/upgrade.php

### Expected behaviour
It should move on to the next screens.

### Actual behaviour
It's just stuck at the first screen.

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
apache 
**Database:**
mysql 
**PHP version:**
PHP 5.5.38

**Teampass version:** 
teampass V. 2.1.22

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
I don't have this file

**Comment by nilsteampassnet** [comment]
You cannot update from 2.1.22 directly to latest.
Indeed there is no cumulative update in old version. This has been introduced in 2.1.27.0.

So you need to go through each version with next schematic:

1. backup 2.1.22
2. upgrade to 2.1.23
3. do some trials
4. if ok, redo 1. with 2.1.23

**Comment by MoHD20** [comment]
Ok, Is there a way to export the passwords then import it on the last version?

**Comment by nilsteampassnet** [comment]
No this is not possible or you would loose all the history.
