### ISSUE TITLE
Google Authenticator code should be tied to the user

### ISSUE THREAD

**Issue by rdoursenaud** [nilsteampassnet/TeamPass#2107]
### Steps to reproduce
1. Enable Google Authenticator 2FA on two accounts or more
2. Connect with one account using the Google Authenticator code from the other

### Expected behaviour
Login with someone else's 2FA code should be refused.
Codes should be tied to the user account.

### Actual behaviour
The connection is accepted.

### Server configuration
**Operating system**: Debian 9.3

**Web server:** nginx

**Database:** MariaDB 10.1.26

**PHP version:** FPM 7.0.27

**Teampass version:** 2.1.26

**Teampass configuration file:** N.A.

**Updated from an older Teampass or fresh install:** Updated

### Client configuration
**Browser:** Any

**Operating system:** Any

### Logs

N.A.

### Remarks

I didn't test with other 2FA methods but I believe these may be affected as well.

**Comment by nilsteampassnet** [comment]
Hi @rdoursenaud 
I'm very surprised of this.
I've tested once again in 2.1.27 branch but it works smoothly and I could not reproduce.
I see you are using 2.1.26 branch but anyhow even in this version I never noticed this.
But you mean that using the 2FA code of another account than the one you are login with, works?

**Comment by rdoursenaud** [comment]
Hi @nilsteampassnet.

Thanks for checking.

After testing more thoroughly this only happens when connecting with the super admin account and using a Google Authenticator code from an user (Which happen to be manager but this don't seem relevant).

The other way around (using the super admin Google Authenticator code while logging in with the user) issues the expected error message.

I only have access to these two accounts I can test with at the moment.
I'll test with another user as soon as possible.
