### ISSUE TITLE
re-open #1883 - QR Code picture not visible

### ISSUE THREAD

**Issue by Marc-Michot-NXO-France** [nilsteampassnet/TeamPass#2108]
Hello,

I test with HEAD branch and with development branch, same issue : the QR code picture is not visible.

same issue as the closed one : https://github.com/nilsteampassnet/TeamPass/issues/1883
![image](https://user-images.githubusercontent.com/32137401/35566860-3518c7e2-05c3-11e8-810e-a6e3534e4e29.png)

is there a workaround ?

Kind Regards
Marc

**Comment by Marc-Michot-NXO-France** [comment]
Sorry I created the issue to fast :(

### Steps to reproduce
1. install teampass from 'git clone'. From HEAD branch or from development branch
2. activate GA 
3. create a folders/rights/user
4. try to connect with the user
5. the GA QR code is not visible at the login page. SO unable to pair with the mobilephone application

### Expected behaviour
GA QR code visible in order to pair with the GA application

### Actual behaviour
the GA QR code is not visible at the login page. SO unable to pair with the mobilephone application
If I ask for sending the QR code through mail under common user. The email I receive contain a link blanck.
If I ask, under admin user, to send the a temp code, throug email, when I kog with it the QR  is not visible at the login web page

### Server configuration
**Operating system**:
debian v9

**Web server:**
Apache 2.4.25 behind http reverse proxy nginx

**Database:**
mariadb 10.1.26

**PHP version:**
7.0.27

**Teampass version:** 
2.1.27 and devel

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '5',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass/',
    'cpassman_url' => 'https://localdomain/teampass/',
    'favicon' => 'https://localdomain/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'url_to_upload_folder' => 'https://localdomain/teampass/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'https://localdomain/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '1',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '1',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '1',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'french',
    'send_stats' => '1',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1514628588',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'intranet@localdomain',
    'email_from_name' => 'TeamPass EMail',
    'pwd_maximum_length' => '60',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => 'proxy-lyon',
    'proxy_port' => '3128',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => '192.168.90.36',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '1',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'copy_to_clipboard_small_icons' => '1',
    'offline_key_level' => '50',
    'ga_reset_by_user' => '1',
);


### Client configuration
**Browser:**
Firefox or Chrome in lastest version

**Operating system:**
Windows Seven

### Logs
#### Web server error log
seems no error

#### Log from the web-browser developer console (CTRL + SHIFT + i)
seems no error !

**Comment by nilsteampassnet** [comment]
You must have an error in the apache log. Can you please check?

Can you access Internet from your browser?

**Comment by Marc-Michot-NXO-France** [comment]
I'll check tomorrow the apache log.
But I don't remind having seen ans error logs :(
Yes my browser has Internet access.

Télécharger Outlook pour Android<https://aka.ms/ghei36>



De : Nils Laumaillé
Envoyé : jeudi 1 février 20:03
Objet : Re: [nilsteampassnet/TeamPass] re-open #1883 - QR Code picture not visible (#2108)
À : nilsteampassnet/TeamPass
Cc : MICHOT Marc, Author


You must have an error in the apache log. Can you please check?
Can you access Internet from your browser?

**Comment by gabrielvasilica** [comment]
I have the same issue. version is 2.1.27.11, fetched today and clean install. no error in the apache2/error.log relating to this one. still, the QR code image is absolutely missing.  
OS: Ubuntu 16.04, Apache 2.4.18, php 7.0.28

**Comment by nilsteampassnet** [comment]
The QR uses google domain.
So if it is not displayed then it means something has happen in the connection.

Enable the web console (SHIFT + CTRL + i).
Please do the process to get connected. 
Enter the temporary 2FA code.
Press ENTER

Nowin the console:

- select the tab `network`
- select last query with `identify.php`
- select tab `response`
- click the link in `value`

![image](https://user-images.githubusercontent.com/1197546/37732359-174d5c92-2d45-11e8-8842-125dd48eac22.png)

Provide the info you can see

**Comment by gabrielvasilica** [comment]
Hi,
the following have been checked: 
date/time: manually date & time synced with internet, max 1 sec delay now.
proxy access: proxy is defined , with IP and port (original), now with http://IP and port. no deny access on squid, traffic is allowed.
in all cases, the below does not change. tested with Firefox and Chrome. 
![noqrcodeff](https://user-images.githubusercontent.com/32874341/37766467-af68f4c0-2dcf-11e8-81e2-dccda637efdc.PNG)
![reponseff](https://user-images.githubusercontent.com/32874341/37766474-b487c684-2dcf-11e8-85ae-e0d32940c96f.PNG)

**Comment by nilsteampassnet** [comment]
Have you php-curl extension installed on your server?

**Comment by gabrielvasilica** [comment]
yes, it was installed just after LAMP deployment

**Comment by fsamareanu** [comment]
I'm going to add a +1 on this, running RHEL7 + Remi PHP 7.2, php curl extension as reported by phpinfo() is enabled and working, SELINUX is off. QR code image is never generated, the data:image/png is empty just like in the comment above.
I am going through a proxy to connect to the internet but according to the team managing it no request goes to it.

Chrome dev console has this to say:

[{"value" : "<img src=\"data:image/png;base64,\">", "user_admin":"", "initial_url" : "", "error" : "ga_temporary_code_correct"}]

**Comment by nilsteampassnet** [comment]
@fsamareanu thank you for sharing this information with us regarding this issue.
I will update the "Typical Errors" page.

**Comment by Johnybe** [comment]
Hi,

The problem persist in 3.0.9 version 

I'm not concerned by this fix, i can reach google dns on 443 port
https://teampass.readthedocs.io/en/latest/errors/#2-factors-authentication-qr-code-picture-not-visible

Regards
