### ISSUE TITLE
Backups doesn't work as they should.

### ISSUE THREAD

**Issue by R3m1n0X** [nilsteampassnet/TeamPass#2110]
### Steps to reproduce
1. Create a SQL-Backup (whether manually or via TP itself)(1.1. and try to copy the Salt-Key)
2. Make a fresh install
3. Try to restore the Dump

### Expected behaviour
A backup is done so that in case of a system failure, the possibility exists to restore your system.

### Actual behaviour
It is not possible to restore a backup if it does not happen on the same system. In case of incidents, this backup is extremely useless. Accepted only once: For some reason, the hard disk of the production environment fails. You try to restore the SQL backup and can't see the passwords. (They are available in the database, but are not shown in TeamPass)

### Whats the Situation?
We have two systems. One of them is our production system (System 1 - TPV 2.1.27.9), the other one(System 2) is to replace the old environment. System 1 is buggy as hell, the data integrity is getting worse and worse. Passwords disappear or users no longer have access to them. That's why we decided to replace System 1 with a new one. This is a self developed docker-based environment (with some additional functions for the System) and runs very stable and the TP-Versions are replaceable without much effort and reconfiguration.

### Server configuration
**System 1:**
**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Apache 2
**Database:**
mySQL
**PHP version:**
PHP 5.1
**Teampass version:** 
2.1.27.9

**System 1:**
**Operating system**:
Ubuntu 17.10
Docker-bases Ubuntu 17.10
**Web server:**
Apache 2
**Database:**
mySQL
**PHP version:**
PHP 7.1
**Teampass version:** 
2.1.27.10

### Client configuration
**Browser:**
Firefox, Chrome, Edge, Vivaldi
**Operating system:**
Fedora, Ubuntu, Elementary, Windows

#### Web server error log
There are no errors with the webserver i think.

### The Question
How can i transfer the SQL Data to a new TP-Instance ?

**Comment by nilsteampassnet** [comment]
The database dump is one thing.
But it requires you to provide the same saltkey.
If not, the passwords will not be decrypted.

Are you sure to provide the expected saltkey in system2?

**Comment by R3m1n0X** [comment]
I'm aware of that.

The Saltkey can be found under:
/includes/teampass-seckey.txt
Am I right about that?

I tried to replace it manually = the result was that I only got white pages with no content, which I couldn't undo.
When you press the button in TeamPass itself = only the wheel spins and nothing happens.

I've created a 3rd system for testing to rule out the possibility that it's my docker-container.
But there I have the same issues.

I can't find a way to replace the Saltkey.

**Comment by nilsteampassnet** [comment]
The saltkey is created in the folder indicated during the install.
You can check this in file settings.php in the define `SECUREPATH`.

This saltkey file must be exactely the one used in your system1.
Never try to change it.

**Comment by R3m1n0X** [comment]
> The saltkey is created in the folder indicated during the install.
> You can check this in file settings.php in the define SECUREPATH.

config.php: 
`@define('SECUREPATH', '/var/www/html/includes');
if (file_exists("/var/www/html/includes/sk.php")) {
    require_once "/var/www/html/includes/sk.php";
}`

So the Path is : /var/www/html/includes

There are the following files:
sk.php:
`<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>`

teampass-seckkey.txt:
`Includes the string`

> This saltkey file must be exactely the one used in your system1.
> Never try to change it.

I am aware of this, but how exactly do I replace it? How can I ensure a move to the second system?

Sorry, I thought it was a mistake on the part of TeamPass. But it's more like a mistake on my part.

**Comment by nilsteampassnet** [comment]
> I am aware of this, but how exactly do I replace it? 
You should not replace it.
Just copy this file from System1 to System2 with no edition and at the exact same place).

> How can I ensure a move to the second system?
Just perform a copy.

**Comment by R3m1n0X** [comment]
Hey,

I've been trying to switch the Saltkey all weekend. Unfortunately without success.

I copied the key from System 1 to System 2. I can't copy a file with the same name to the same folder, I renamed the Saltkey from System 1.
I tried this in several ways (add a ". 0",". backup", etc.). I copied the key from system 1 to the folder where the system 2 key is located.

Once, Teampass realized there was another key. (In the options a box appeared in which I could choose what I wanted to do. But after confirming, Teampass worked several hours without progress. But I could not reproduce this. I have reinstalled System 2 without exaggerating, about 40 times.

Also on the internet and in the documentation I did not find any instructions on how to proceed.
Install TP -> import DB -> Change Saltkey? Install TP -> Change Saltkey -> import DB?

Meanwhile, I think I'm doing something wrong, but I don't know what.

**Comment by R3m1n0X** [comment]
Update:

In the meantime I was able to achieve a success.

(Drop all old data = container, images, volumes, if needed)
1) Run the docker container
2) Copy the' teampass-seckkey. txt' from System 1 to System 2
3) Run the installation of TeamPass
4) Then TeamPass displays a message under Settings > Tasks (8 of 10 times)
5) Click on keep data
6) Then on the wheel
7) Teampass shows a blank page (HTTP  500)
8) And in the Apache error.log there are the following errors:
```
[Wed Feb 14 14:30:12.183646 2018] [php7:warn] [pid 24] [client 192.168.115.113:59480] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'teampass'@'172.17.0.3' (using password: NO) in /var/www/html/index.php on line 86, referer: http://192.168.115.84/index.php?page=manage_settings
[Wed Feb 14 14:30:12.183793 2018] [php7:error] [pid 24] [client 192.168.115.113:59480] PHP Fatal error:  Uncaught Error: Call to a member function set_charset() on boolean in /var/www/html/index.php:87\nStack trace:\n#0 {main}\n  thrown in /var/www/html/index.php on line 87, referer: http://192.168.115.84/index.php?page=manage_settings
```
Im wondering about the `(using password: NO)`.

It doesn't matter if I take the user "teampass" or "root". I have also previously granted the user "teampass" all authorizations via `grant all privileges on *.* to 'teampass'@'%' with grant option`.

**Comment by jumpingmushroom** [comment]
Hi!

I'm having the exact same problem with the docker container. I tried following @R3m1n0X steps, and only end up having the security key renamed in the last part of the process (Finalization) to teampass-seckey.txt.date and having a new key generated.

I am trying to restore a backup, and have tried to follow several instructions on how to do this, but I cant get the container version of teampass to work the way it should. Maybe there's a way to skip the installation and jump directly to the login?

Hope anyone can help on this.
