### ISSUE TITLE
Cannot install teampass, stuck at "Database connection" Call to undefined function mysqli_connect()

### ISSUE THREAD

**Issue by EnzovdWetering** [nilsteampassnet/TeamPass#2113]
Hi there

My installation does not go further than the "Database conenction" section, No error message is shown on this page.

When I click on "Launch" I get the following error in the apache error.log file: [Tue Feb 06 14:03:07.839684 2018] [:error] [pid 12163] [client 192.168.123.10:49794] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in 

### Steps to reproduce
1. Followed the installation guide found here: https://teampass.readthedocs.io/en/latest//install/install-linux/
2. Open a web browser and go to https://password.mydomain.com
3. On the "Welcome" tab click on "Next"
4. On the "Server checks" click on "launch" --> the output bellow is shown

Directory "/install/" is writable V
Directory "/includes/" is writable V
Directory "/includes/config/" is writable V
Directory "/includes/avatars/" is writable V
Directory "/includes/libraries/csrfp/libs/" is writable V
Directory "/includes/libraries/csrfp/js/" is writable V
Directory "/includes/libraries/csrfp/log/" is writable V
Directory "/files/" is writable V
Directory "/upload/" is writable V
PHP extension "mcrypt" is loaded V
PHP extension "mbstring" is loaded V
PHP extension "openssl" is loaded V
PHP extension "bcmath" is loaded V
PHP extension "iconv" is loaded V
PHP extension "xml" is loaded V
PHP extension "gd" is loaded V
PHP extension "curl" is loaded V
PHP version is greater or equal to 5.5.0 V
Execution time limit  V

5. Click on "Next" and configure how teampass should connect to the mysql server, mysql is hosted on the same system. so the settings are:

Host: 127.0.0.1
Database name: teampass
Login: teampass_admin
Password : mysecretpassword
Port: 3306

6. Click on Launch (Next is gray)

### Expected behaviour
go to the next screen (Preparation)

### Actual behavior
Nothing happends

### Server configuration
root@password:/etc/php/7.0/apache2# apt-get install lsb-release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lsb-release is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@password:/etc/php/7.0/apache2# lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

**Web server:**
root@password:/etc/php/7.0/apache2# apachectl -v
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 20 2017 04:37:43

**Database:**
root@password:/etc/php/7.0/apache2# mysql -V
mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
root@password:/etc/php/7.0/apache2# php -v
PHP 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa (cli) (built: Jan 17 2018 08:58:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa, Copyright (c) 1999-2017, by Zend Technologies

**Teampass version:** 
root@password:/var/www/html# cat index.php | grep version
 * @version       2.1.27

**Teampass configuration file:**
?

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
Google chrome

**Operating system:**
Mac OSX

#### Web server error log
root@password:/etc/php/7.0/apache2# tail -f /var/log/apache2/error.log 
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
[Tue Feb 06 14:00:40.039329 2018] [mpm_prefork:notice] [pid 12049] AH00169: caught SIGTERM, shutting down
Failed loading /etc/php/7.0/mods-available/opcache.so:  /etc/php/7.0/mods-available/opcache.so: cannot open shared object file: No such file or directory
[Tue Feb 06 14:00:41.161611 2018] [mpm_prefork:notice] [pid 12145] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Feb 06 14:00:41.161659 2018] [core:notice] [pid 12145] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 06 14:02:54.496847 2018] [:error] [pid 12148] [client 192.168.123.10:49789] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydomain.com/install/install.php
[Tue Feb 06 14:03:07.839684 2018] [:error] [pid 12163] [client 192.168.123.10:49794] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydomain.com/install/install.php
Insert your webserver log here
```

**Comment by thefirstben** [comment]
Hello,

You need to add this to your php.ini file :
extension=mysqli.so

**Comment by ciscoshizzel** [comment]
Hi @thefirstben 

I'm not sure in what php.ini file I shoud add extension=mysqli.so so I tested on every version (one by one) like this:

1.1 in /etc/php5/apache2/php.ini search for "extension=mysqli.so", if it is not found then add it
1.2 in /etc/php/5.6/cli/php.ini search for "extension=mysqli.so", if it is not found then add it
1.3 in /etc/php/7.0/apache2/php.ini search for "extension=mysqli.so", if it is not found then add it
1.4 in /etc/php/7.0/cli/php.ini search for "extension=mysqli.so", if it is not found then add it
1.5 in /etc/php/7.1/cli/php.ini search for "extension=mysqli.so", if it is not found then add it

2.1 service apache2 restart
1.3 Try to install teampass via https://password.mydomain.com and the same issue occurs
1.4 I get the error below in /var/log/apache2/error.log after clicking on "launch" and the GUI will not go further
`root@password:/home/beheerder# tail -f /var/log/apache2/error.log 
[Wed Feb 07 09:10:26.484927 2018] [mpm_prefork:notice] [pid 18009] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqli.so' - /usr/lib/php/20151012/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Wed Feb 07 09:10:27.557485 2018] [mpm_prefork:notice] [pid 18588] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Wed Feb 07 09:10:27.557533 2018] [core:notice] [pid 18588] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 07 09:10:35.202143 2018] [:error] [pid 18591] [client 192.168.123.6:55662] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydomain.com/install/install.php
[Wed Feb 07 09:11:22.444150 2018] [:error] [pid 18601] [client 192.168.123.6:55694] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydomain.com/install/install.php
[Wed Feb 07 09:23:34.209656 2018] [mpm_prefork:notice] [pid 18588] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysqli.so' - /usr/lib/php/20151012/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Wed Feb 07 09:23:35.287991 2018] [mpm_prefork:notice] [pid 18758] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1t configured -- resuming normal operations
[Wed Feb 07 09:23:35.288058 2018] [core:notice] [pid 18758] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 07 09:25:04.082963 2018] [:error] [pid 18774] [client 192.168.123.6:55863] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydomain.com/install/install.php
[Wed Feb 07 09:25:05.780521 2018] [:error] [pid 18773] [client 192.168.123.6:55864] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/install/install.queries.php:209\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/install.queries.php on line 209, referer: https://password.mydoamin.comvds/install/install.php`

**Comment by thefirstben** [comment]
Hello,
You are missing some teampass requisites. Did you install all the required package as instructed in Teampass doc (for example php5-mysql for php5 or php-mysqli, or php-mysqlnd ) ? If you installed the packages you should have the mysqli.so file.
Anyway it seems you have many different php installation. You need to cleanup your server and have only one install of PHP. Also your libraries are being searched in /usr/lib/php/20151012/, this is like a backup of something.

**Comment by freakynl** [comment]
Leuke nick, CiscoShizzel :)

You're missing PHP mysql extensions

apt install php-mysql
or
apt install php7.0-mysql

At least on Ubuntu, presume it will be the same on debian. Otherwise run something like:

apt search php | grep mysql

Should show you the packages required.

If you're running PHP in PHP-FPM, make sure to restart the FPM workers after installing the package (or just reboot)

**Comment by Gougedivorced** [comment]
> Hello, You are missing some teampass requisites. Did you install all the required package as instructed in Teampass doc (for example php5-mysql for php5 or php-mysqli, or php-mysqlnd ) ? If you installed the packages you should have the mysqli.so file. Anyway it seems you have many different php installation. You need to cleanup your server and have only one install of PHP. Also your libraries are being searched in /usr/lib/php/20151012/, this is like a backup of something.





https://lnkr.fun/81a06e7
