### ISSUE TITLE
Items expiring with no obvious reason

### ISSUE THREAD

**Issue by janwagners** [nilsteampassnet/TeamPass#2114]
### Steps to reproduce
1. Import a big KeePass XML File (1400 items)
2. Try to edit / access one of the items after an undefined period of time
3. Editing is not possible because teampass claims that the item is expired.

### Expected behaviour
The items can be edited or viewed forever in detail because there is no expiring feature enabled or date set.

### Actual behaviour

The imported items are expired after an undefined period of time but at the latest after one day. The green label in the password overview turns from green into orange. When I mark an item then I can see this at the bottom:  

Access to password item denied!
Author: my.user
Restricted to:

Request access to modify

When I search in the search section and click on the details of an item I can read "The item has expired". 

I already deleted our folder, role and users completely without any change. I also executed the task "Remove orphan items from database" which deleted over 11000 item. But I think that was because I imported this big Keepass XML File many times and then simply deleted the whole folder. Do you think it's the size of the import that causes the issue? 

Oddly enough other teams do not experience this problem but they have a maximum of 80 items per folder.

Server configuration

Operating system: Ubuntu 16.04.3 LTS

Web server: apache 2.4.18

Database: mysql 5.7.21

PHP version: PHP 7.0.22-0ubuntu0.16.04.1

Teampass version: 2.1.27

Teampass configuration file:

Updated from an older Teampass or fresh install: new
PLEASE attach to this message the file /includes/config/tp.config.php.

Client configuration

Browser: Firefox 58/ Chrome 64

Operating system: Win10 Enterprise

#### Web server error log
```
(Not sure if that has anything to do with the problem:

[Wed Feb 07 08:29:21.366328 2018] [:error] [pid 26723] [client x.x.x.x:59216] PHP Notice:  Undefined index: pwComplexity in /var/www/html/teampass/index.php on line 818
[Wed Feb 07 08:42:07.383793 2018] [:error] [pid 26724] [client x.x.x.x:33284] PHP Notice:  Undefined index: pwComplexity in /var/www/html/teampass/index.php on line 818, referer: https://teampass.example.com/logout.   php?user_id=10000095
[Wed Feb 07 08:50:45.526984 2018] [:error] [pid 26726] [client x.x.x.x:59318] PHP Notice:  Undefined index: pwComplexity in /var/www/html/teampass/index.php on line 818, referer: https://teampass.example.com/logout.   php?user_id=10000092
[Wed Feb 07 08:51:18.870105 2018] [:error] [pid 26726] [client x.x.x.x:59500] PHP Notice:  Undefined index: pwComplexity in /var/www/html/teampass/index.php on line 818, referer: https://teampass.example.com/logout.   php?user_id=10000089


#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by janwagners** [comment]
I checked this box before the import:

Set "anyone can modify" right on all imported items.

**Comment by nilsteampassnet** [comment]
This huge number of elements deleted is normal when I see the number of Items you have imported.
So this has nothing to do with your problem.

I must admit that I've spent a couple of time reviewing the importation code and don't understand how your problem can occurs.
I don't even see that you have enabled expiration option ... this seems particularly curious.

I don't know what have been done on the database but it seems much data exists in it ... perhaps linked to the massive imports.

I would like you to suggest to clear all restrictions on items.
For this do:
- perform a dump of your database
- run the query : truncate table teampass_restriction_to_roles;
- do a check on items

**Comment by janwagners** [comment]
Unfortunately we're running teampass already in production with many teams and folders. So when I understand you correctly this command will remove all restrictions from all folders? If this is the case I have to setup a test environment. 

We're the only team with this problem.

**Comment by janwagners** [comment]
Can you please tell me or give an example of what I should receive when I use the query:

mysql> select * from teampass_restriction_to_roles;

I'm getting this as result:

Empty set (0.00 sec)

I didn't execute the query you asked for above.

**Comment by janwagners** [comment]
Here is an example from a folder with no problems. Am I wrong or should the value of restricted_to not be "NULL" but a ROLE ID or something else?

*************************** 304. row ***************************
                       id: 10101
                    label: MySQL user
              description: Tags: [MySQL] [user]
                       pw: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                    pw_iv: NULL
                   pw_len: 0
                      url:
                  id_tree: 77
                    perso: 0
                    login: user
                  inactif: 0
            restricted_to: NULL
        anyone_can_modify: 0
                    email: NULL
             notification: NULL
                viewed_no: 0
         complexity_level: -1
auto_update_pwd_frequency: 0
auto_update_pwd_next_date: 0
          encryption_type: not_set

**Comment by nilsteampassnet** [comment]
The restricted_to set to null is correct in your case.
It is only populated if the author defines a restriction for specific users at the item level.

The fact that table `teampass_restriction_to_roles` is empty shows that no restriction is set on Items to specific roles.

The behavior you describes is more related to Item expiration.
But this setting is not enabled in your system.
Nevertheless, can you please run query
`SELECT * FROM `teampass_misc` WHERE `intitule` LIKE 'activate_expiration'`

And also
`SELECT * FROM `teampass_nested_tree` WHERE `renewal_period`!=0`

Perhaps would I need to have access to your server

**Comment by janwagners** [comment]
OK I see. Here are the results of the queries:

`mysql> SELECT * FROM teampass_misc WHERE intitule LIKE 'activate_expiration';
+--------------+-------+---------------------+--------+
| increment_id | type  | intitule            | valeur |
+--------------+-------+---------------------+--------+
|           21 | admin | activate_expiration | 0      |
+--------------+-------+---------------------+--------+
1 row in set (0.00 sec)

mysql> SELECT * FROM teampass_nested_tree WHERE renewal_period !=0;
Empty set (0.01 sec)`

I created another folder with another role last Friday and divided the import into 13 xml files with about 100 items each. Until now I was the only one with access and the items aren't expired yet. Just a few minutes ago I assigned the new role to my colleagues. We will see what happens next.

**Comment by nilsteampassnet** [comment]
Can you please run next queries (no impact on data, just counting).
```
SELECT COUNT(id) FROM `teampass_items` WHERE perso='0';
SELECT COUNT(id) FROM `teampass_items` WHERE perso='1';
```
The first will give us the number of non personal items.
The second will give us the number of personal items.

If all items are "personal" then something happens.
Do a dump of your database and run next queries
```
UPDATE `teampass_items` SET perso = '0';

UPDATE `teampass_items` AS i
INNER JOIN `teampass_nested_tree` AS n ON n.id = i.id_tree
SET i.perso = '1'
WHERE n.personal_folder = '1';
```
The 1st will force to 0 all items (not personal).
The 2d will update the personal status of each item depending on its belonging to a personal folder.

Once done, this should restore the correct status of your items and they will become accessible as before.

Now I would like to understand why. Can you remember of any thing done on Teampass before this behavior appeared?

**Comment by janwagners** [comment]
Here are the results of the queries:

`
mysql> SELECT COUNT(id) FROM `teampass_items` WHERE perso='0';
+-----------+
| COUNT(id) |
+-----------+
|      1713 |
+-----------+
1 row in set (0.01 sec)

mysql> SELECT COUNT(id) FROM `teampass_items` WHERE perso='1';
+-----------+
| COUNT(id) |
+-----------+
|      1409 |
+-----------+
1 row in set (0.01 sec)
`

So I don't believe that anyone has any personal passwords yet. So this amount of personal items looks like one of my imports from the past. 

Since I have done that we aren't experiencing any problems:

I created another folder with another role last Friday and divided the import into 13 xml files with about 100 items each. Until now I was the only one with access and the items aren't expired yet. Just a few minutes ago I assigned the new role to my colleagues. We will see what happens next.

At the moment I see no problems. So the two things that could cause the problem after my opinion is the big import file or a role/folder issue.

Do you count also deleted items with the above queries? I could execute the "Remove orphan items from database" task and see if they are still there because I deleted the folder.

**Comment by nilsteampassnet** [comment]
OK.

> Do you count also deleted items with the above queries?

Absolutely

>  I could execute the "Remove orphan items from database" task and see if they are still there because I deleted the folder.

Yes it is an idea

**Comment by janwagners** [comment]
Hey,

it happened again without doing anything unusual. 

`mysql> SELECT COUNT(id) FROM `teampass_items` WHERE perso='1';
+-----------+
| COUNT(id) |
+-----------+
|      1099 |
+-----------+
1 row in set (0.01 sec)`

I will try to fix this with the queries from you above.

**Comment by kendionne** [comment]
I am getting the same behaviour : after importation, the elements id's appear in the table teampass_restriction_to_roles. 
after I edit myself one of the imported element, the element id is removed itself from that table. 

For now what I do is truncate that table after import.

Can it be related to the option "Enable restricted-to function on items" that was enabled for a while but now disabled in my system ? or what feature is that table linked to ?
