### ISSUE TITLE
Backup does not work

### ISSUE THREAD

**Issue by zpolisensky** [nilsteampassnet/TeamPass#2115]
### Steps to reproduce
1. configure backup (just added passkey value, left the rest in default)
2. go to https://teampass.example.com/backups/script.backup.php?key=somekey
3. returs [{"error":"" , "status":"success"}]

### Expected behaviour
Backup file should be created in backup folder.
Manual backup works fine.

### Actual behaviour
Backup file is not created. Apache error log reports:
PHP Warning:  unlink(/var/www/html/backups/bck_teampass-1518002046.sql): No such file or directory in /var/www/html/backups/script.backup.php on line 113
PHP Warning:  rename(/var/www/html/backups/bck_teampass-1518002046.encrypted.sql,/var/www/html/backups/bck_teampass-1518002046.sql): No such file or directory in /var/www/html/backups/script.backup.php on line 116

### Server configuration
**Operating system**: 
Debian 9 Stretch

**Web server:**
 Apache/2.4.25 (Debian)

**Database:**
5.5.5-10.1.26-MariaDB-0+deb9u1

**PHP version:**
7.0.27-0+deb9u1

**Teampass version:** 
2.1.27.10

**Updated from an older Teampass or fresh install:**
fresh install of Teampass

**Comment by nilsteampassnet** [comment]
your tp.config.php please?

**Comment by zpolisensky** [comment]
Sorry, here it is.
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1710069/tp.config.zip)

**Comment by nilsteampassnet** [comment]
Ok, you identified a bug.

I will fix and commit it.

Thanks

**Comment by zpolisensky** [comment]
Thank you!

**Comment by zpolisensky** [comment]
Just FYI - I replaced script.backup.php from development branch and it throw "500 internal server error" because of wrong path to sources and includes folder. When I deleted ".." (line 22; 23 and 26) from path it works just fine.

Apache2 log:
[Wed Feb 14 14:05:23.400351 2018] [:error] [pid 2825] [client 192.168.11.196:56777] PHP Warning:  require_once(/var/www/html../sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/html/backups/script.backup.php on line 22
[Wed Feb 14 14:05:23.400415 2018] [:error] [pid 2825] [client 192.168.11.196:56777] PHP Fatal error:  require_once(): Failed opening required '/var/www/html../sources/SplClassLoader.php' (include_path='.:/usr/share/php') in /var/www/html/backups/script.backup.php on line 22
[Wed Feb 14 14:09:48.522559 2018] [:error] [pid 2826] [client 192.168.11.196:57203] PHP Warning:  require_once(/var/www/html../includes/libraries/Database/Meekrodb/db.class.php): failed to open stream: No such file or directory in /var/www/html/backups/script.backup.php on line 23
[Wed Feb 14 14:09:48.522713 2018] [:error] [pid 2826] [client 192.168.11.196:57203] PHP Fatal error:  require_once(): Failed opening required '/var/www/html../includes/libraries/Database/Meekrodb/db.class.php' (include_path='.:/usr/share/php') in /var/www/html/backups/script.backup.php on line 23

**Comment by nilsteampassnet** [comment]
Thank you.
