### ISSUE TITLE
Insufficient password strength when creating Offline Mode

### ISSUE THREAD

**Issue by rceaai** [nilsteampassnet/TeamPass#2116]
### Steps to reproduce
0. Enable Offline Mode in admin config.
1. Click Menu->Offline Mode
2. Select arbitrary folders
3. Enter a complex encryption key for the backup

### Expected behaviour
Tell us what should happen
Not sure yet - this hasn't worked yet for me. But I presume that I'd be able to create an offline backup.

### Actual behaviour
Tell us what happens instead
I'm prompted, very briefly, with an error message that reads: Insufficient password strength!

### Server configuration
**Operating system**:  Both Debian and FreeBSD

**Web server:** Apache in Debian, and nginx in FreeBSD

**Database:** mysql in both cases.

**PHP version:** 7.0 in both

**Teampass version:** 2.1.27. I've tried using both cloning the repo and downloading the Release tarball from https://github.com/nilsteampassnet/TeamPass/releases 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'm/d/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/usr/local/www/teampass/html',
    'cpassman_url' => 'https://tp.testnet.lan',
    'favicon' => 'https://tp.testnet.lan/favicon.ico',
    'path_to_upload_folder' => '/usr/local/www/teampass/html/upload',
    'url_to_upload_folder' => 'https://tp.testnet.lan/upload',
    'path_to_files_folder' => '/usr/local/www/teampass/html/files',
    'url_to_files_folder' => 'https://tp.testnet.lan/files',
    'activate_expiration' => '1',
    'pw_life_duration' => '120',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1514396393',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'mail.testnet.lan',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'tp_admin@testnet.lan',
    'email_auth_pwd' => 'yabbadabbadoo',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => '',
    'email_from' => 'tp_admin@testnet.lan',
    'email_from_name' => 'TeamPass Admin',
    'pwd_maximum_length' => '65',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '240',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/usr/local/www/teampass/backups',
    'bck_script_filename' => 'tp_backup',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '1',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/Los_Angeles',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '1',
    'offline_key_level' => '50',
    'ga_reset_by_user' => '1',
    'settings_offline_mode' => '1',
);

### Client configuration
**Browser:**  Chrome/Firefox/Firefox Dev

**Operating system:** Windows 10

#### Web server error log
```
There are no entries in either the access or error logs when trying to create a backup.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
No logs displayed in console of any browser when trying to create a backup.
```

**Comment by nilsteampassnet** [comment]
I can see that the offline password requires at least `Medium` level.
Is it the case?

I've just tried with your settings and didn't experimented any problem.

**Comment by rceaai** [comment]
Yes, it indicated that the password I provided is 'Very heavy', and indeed it is a very complicated passphrase.  I'd be happy to troubleshoot this, but I'm not getting anything in either the webserver logs or the browser console.  Might there be a $debug variable that I could enable with regard to generating an offline backup?

**Comment by nilsteampassnet** [comment]
Can you provide your passphrase you entered for encrypting the offline file?
Perhaps is there an invalid character?

**Comment by rceaai** [comment]
Well, I tried using a different password just now:  `+zTfM2hHgc$*`, and it worked.  I tried again using the password I entered previously (I don't want to divulge that), and again it prompted me with the error "Insufficient password'.

Apparently your suggestion of an invalid character was the cause; must've been one of these: `._#`

**Comment by nilsteampassnet** [comment]
Thank you.
Bug was identified.
Quick fix:
Open file `items.offline.php`
Replace
````
        if ($("#offline_pw_strength_value").val() < $("#min_offline_pw_strength_value").val()) {
```
by
````
        if (parseInt($("#offline_pw_strength_value").val()) < parseInt($("#min_offline_pw_strength_value").val())) {
```
