### ISSUE TITLE
[Q] List of tags?

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#2117]
Hello.

Is there any place at webGUI where can I find listings of used tags? Maybe clickable? :)

Regards.

**Comment by nilsteampassnet** [comment]
Hello

No this currently doesn't exists.
Maybe an idea for improvement.

Thanks

**Comment by KB7777** [comment]
Hello.

@nilsteampassnet 
Another nice to see features about tags:
* group edit (marking with ^C)
* folder tagging

No i have zylions objects at TeamPass imported from KeePass without tags. Adding it is very hard :)

Regards.
