### ISSUE TITLE
Empty user at Keepass file is not empty after import

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#2118]
Hi.

After import from Keepass, where two items has no user filled, TeamPass shows the user field filled by random (I think) string.
The string is  <Value ProtectInMemory="True">"random (I think) string"</Value> from KeePass XML file.

Is it safe?

Regards.

**Comment by nilsteampassnet** [comment]
I have seen this.
You mean that the field User should be empty but is filled with a random value?
What kind of value?

**Comment by KB7777** [comment]
Yes.
Ok, I looked at this further. This is password from history of the item with no username set at the KeePass.

**Comment by nilsteampassnet** [comment]
I'm not sure to understand.
Can you do a screenshots to share that?

**Comment by KB7777** [comment]
Ok, once again :)

1. Create KeePass (latest stable; 2.38) empty password database.
2. Create an item with title "test_empty_username", without username with password "Password1".
3. Change "Password1" to "Password2".
4. Save database.
5. Export database to file using format KeePass XML (2.x).
6. Import file to TeamPass.

What you get?
You get imported item with label "test_empty_username", with account "Password1" and with username "Password2".

What you should get?
You should get imported item with label "test_empty_username", with blank username and with password "Password2".

**Comment by nilsteampassnet** [comment]
I could reproduce and fix it.

Thanks
