### ISSUE TITLE
Error upgrading server, then upgrading Teampass

### ISSUE THREAD

**Issue by bcwhittle** [nilsteampassnet/TeamPass#2120]
### Steps to reproduce
1. Upgraded Ubuntu server to 18.04
2. Teampass seemed broken, so downloaded and put in place 2.1.27 (over .26)
3. Ran upgrade.php

### Expected behaviour
I assume everything should work

### Actual behaviour
I cannot log in with the admin account.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache 2

**Database:** MySQL 5.7.20-lubuntu1

**PHP version:** 7.1.11-0ubuntu2

**Teampass version:** 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** updated
PLEASE attach to this message the file `/includes/config/tp.config.php`.
    'ldap_mode' => '0',

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
[Mon Feb 12 13:46:30.726925 2018] [php7:notice] [pid 64878] [client 127.0.0.1:33404] PHP Notice:  Undefined index: HTTP_HOST in /var/www/html/TeamPass-master/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 508
[Mon Feb 12 13:46:30.727135 2018] [php7:notice] [pid 64878] [client 127.0.0.1:33404] PHP Notice:  Undefined variable: SETTINGS in /var/www/html/TeamPass-master/index.php on line 58
[Mon Feb 12 13:46:30.727249 2018] [php7:warn] [pid 64878] [client 127.0.0.1:33404] PHP Warning:  require_once(/includes/config/settings.php): failed to open stream: No such file or directory in /var/www/html/TeamPass-master/index.php on line 58
[Mon Feb 12 13:46:30.727288 2018] [php7:error] [pid 64878] [client 127.0.0.1:33404] PHP Fatal error:  require_once(): Failed opening required '/includes/config/settings.php' (include_path='.:/usr/share/php') in /var/www/html/TeamPass-master/index.php on line 58

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by bcwhittle** [comment]
I tried and was able to install a fresh installation, but could not find a way to import the database from my previous install. Is there a way to do that?

**Comment by nilsteampassnet** [comment]
No there is no easy way as your "old" database is in the format 2.1.26.

I believe that in the "old" instance, you just have some inconsistency issues.
As you can see in your errors, the server can't find some files, so it must be that the config files are not consistent, please check.
You can eventually need this => http://teampass.readthedocs.io/en/latest/errors/

**Comment by bcwhittle** [comment]
I looked at the errors page in the docs, and checked to be sure the csrfp.config.php file looks correct.

The settings file is in place, as indicated in the log, teampass/includes/config/settings.php.
But I'm not sure what the (include_path='.:/usr/share/php') is on that line.

Where should it be getting the HTTP_HOST information?

**Comment by nilsteampassnet** [comment]
HTTP_HOST is a variable from Server.

Try to restart your httpd service.

**Comment by bcwhittle** [comment]
I tried restarting the service (and the server), and no change. After some digging in the information on httpd, I tried renaming HTTP_HOST to SERVER_NAME because httpd docs indicated that sometimes HTTP_HOST is not set.

The result was  the error: 
PHP Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in . . . csrfprotector.php and identify.php

**Comment by nilsteampassnet** [comment]
Do you have package php-cli?

**Comment by bcwhittle** [comment]
I thought I did. I did not after all, so I installed it.

I restarted Apache, and it did not change the reading of the session data.

**Comment by nilsteampassnet** [comment]
Can you please do this next try.

Open file `index.php`
Replace 
```
// Include files
require_once $SETTINGS['cpassman_dir'].'/includes/config/settings.php';
require_once $SETTINGS['cpassman_dir'].'/includes/config/include.php';
require_once $SETTINGS['cpassman_dir'].'/includes/libraries/protect/SuperGlobal/SuperGlobal.php';
$superGlobal = new protect\SuperGlobal\SuperGlobal();


// initialize session
$_SESSION['CPM'] = 1;
if (isset($SETTINGS['cpassman_dir']) === false || $SETTINGS['cpassman_dir'] === "") {
    $SETTINGS['cpassman_dir'] = ".";
    $SETTINGS['cpassman_url'] = $superGlobal->get("REQUEST_URI", "SERVER");
}
```
by
```
$superGlobal = new protect\SuperGlobal\SuperGlobal();


// initialize session
$_SESSION['CPM'] = 1;
if (isset($SETTINGS['cpassman_dir']) === false || $SETTINGS['cpassman_dir'] === "") {
    $SETTINGS['cpassman_dir'] = ".";
    $SETTINGS['cpassman_url'] = $superGlobal->get("REQUEST_URI", "SERVER");
}
// Include files
require_once $SETTINGS['cpassman_dir'].'/includes/config/settings.php';
require_once $SETTINGS['cpassman_dir'].'/includes/config/include.php';
require_once $SETTINGS['cpassman_dir'].'/includes/libraries/protect/SuperGlobal/SuperGlobal.php';
```

**Comment by bcwhittle** [comment]
I am trying to change v26 so that I can access the data again, or be able to run the upgrade script for v27. It looks like the above code is from the index in v27. Will this help me run v27 and access the data from v26?

**Comment by bcwhittle** [comment]
Is there a way to retrieve/view the data from MySQL without v26 completely running? I have the SALT from the v26 settings. Then I could create a *new* instance of v27, and move the data over manually.

**Comment by nilsteampassnet** [comment]
It is possible but very complicated. Encryption is used at several places and you may miss some data.
I would really recommend to update through Teampass process.

The error you are facing makes me more think about an inconsistency on the configuration server/teampass. So that you may face it at any other moment.

**Comment by ImNtReal** [comment]
Let me know if you'd prefer me to open a separate issue. I don't see any problems with functionality, but I have the same error about HTTP_HOST not existing in the array. Interestingly, if I just run phpinfo(), I can see HTTP_HOST is what I expect it to be. Any idea how I can troubleshoot why it isn't showing up in my $_SERVER array there?
