### ISSUE TITLE
Suddenly, items are no longer accessible

### ISSUE THREAD

**Issue by jcoquery** [nilsteampassnet/TeamPass#2123]
### Steps to reproduce
1. I do not know. Everything worked well for a few months and now the items are no longer accessible.
No changes were made between when it was OK and now.
This morning, I saw items become "orange" progressively

### Expected behaviour
Access to items

### Actual behaviour
No right to access items

### Server configuration
**Operating system**:
Docker (Centos)
**Web server:**
Apache
**Database:**
5.7.19
**PHP version:**
7.1.9
**Teampass version:** 
2.1.27

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1731095/tp.config.txt)

### Client configuration
**Browser:**
All

**Operating system:**
Windows 10
<img width="526" alt="2018_02_16_12_17_02_teampass" src="https://user-images.githubusercontent.com/30726879/36305415-bc5962cc-1313-11e8-973e-8f2166b96758.png">

**Comment by nilsteampassnet** [comment]
How strange.
Have those items being created by you?
Who has rights on this folder (what roles)?
Is your account associated to one of those roles?
Did someone edit those items?

**Comment by jcoquery** [comment]
Created by me or not, all items have the same problem
My account is assocated to some role, but the problem appears for everyone
Nobody edit the items
No change on TP.

This morning it was fine, few time after, some items became "orange" without reconnexion.

**Comment by jcoquery** [comment]
after analisys, every items have the value 'perso' set to 1 in the teampass_item table.
But nobody has change this.
How is it possible?

**Comment by nilsteampassnet** [comment]
I don't understand how it can be possible.
No maintenance operations were done using Teampass admin interface?

Here are 2 queries to run to update the status of the items.
```
UPDATE `teampass_items` SET perso = '0';

UPDATE `teampass_items` AS i
INNER JOIN `teampass_nested_tree` AS n ON n.id = i.id_tree
SET i.perso = '1'
WHERE n.personal_folder = '1';
```

**Comment by gwstj** [comment]
I had the same problem. It happened to me twice.

1) After upgrading from 2.1.26 -> 2.1.27.10. I fixed it by revert the database from a backup and doing the upgrade again. (Changing a user login name was involved, too).

2) Probably after changing the login name of a user. The user authenticates via ldap.

**Comment by jcoquery** [comment]
Now I can reproduce the problem.
If a user member of "domain administrators", without pre-created Teampass account, logon to Teampass, he can view everything and the items became "personnal", so the others users can't see items no more

**Comment by jcoquery** [comment]
oh, I did more tests.
No need to be member of "domain administrators".
If somebody, without pre-created Teampass account, log on to Teampass with his AD account, items become "personnal"

**Comment by ethantq** [comment]
I had this also. Just ran the mysql scripts to fix everything. I can confirm that I can not recreate this issue with the version TeamPass-883c57a2772543827dedb7dbe622c1318b8a2949 that I downloaded from issue [#2035](https://github.com/nilsteampassnet/TeamPass/issues/2035)

**Comment by jcoquery** [comment]
After an upgrade to the last development branch, this issues doesn't appear anymore

**Comment by nilsteampassnet** [comment]
Thank you for your feedback
