### ISSUE TITLE
Unable to search for IDs

### ISSUE THREAD

**Issue by dhorn67** [nilsteampassnet/TeamPass#2124]
### Steps to reproduce
1. Login to TeamPass 2.1.27.10 
2. Attempt to search anything
3.

### Expected behaviour
Tell us what should happen
Looking of a user ID should return the list of IDs

### Actual behaviour
Tell us what happens instead
You can a gold bar with an X that disappears in a few seconds and another box below it labeled Information and a close button at the bottom.  No items returned.

### Server configuration
**Operating system**: Windows 2012r2

**Web server:** Apache 2.4.27

**Database:** MySQL 5.7.19

**PHP version:** 5.6.31

**Teampass version:** 2.1.27.10

**Teampass configuration file:** not sure where to get this?

**Updated from an older Teampass or fresh install:** New Install
PLEASE attach to this message the file `/includes/config/tp.config.php`.
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1732616/tp.config.zip)

### Client configuration
**Browser:** IE, Chrome, Firefox all have this issue

**Operating system:** WIndows 10

#### Web server error log
```
Insert your webserver log here
[apache_error.log](https://github.com/nilsteampassnet/TeamPass/files/1732626/apache_error.log)

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I don't understand what you try to search for ... user IDs?
From what search place?
Provide screenshots please

**Comment by dhorn67** [comment]
Ok, sure.  I need to find the userID root.  In our previous version of TeamPass we simply typed in the name as shown below.

[cid:image001.png@01D3AA1E.5AF40A40]

In this version we get this now.

[cid:image002.png@01D3AA1E.5AF40A40]

I believe the search capability was working when I first setup this new version and it stopped as we migrated all of our accounts in to it.  We thought it had something to do with either an ID or PW being blank.  We have since added NoID or NoPW on the accounts like this but this is still our search result.

Thanks,
David

**Comment by nilsteampassnet** [comment]
Sorry no images are uploaded when answering by email.
Please use github website.

**Comment by dhorn67** [comment]
![search](https://user-images.githubusercontent.com/36549052/36445800-e9e1ddee-1644-11e8-87ec-b7c69dab317b.png)
![search1](https://user-images.githubusercontent.com/36549052/36445817-f7d37584-1644-11e8-9f16-56aebf5deff1.png)

**Comment by nilsteampassnet** [comment]
You must have errors.
Please do
1- do a new search
2- run this query 
`SELECT label FROM `teampass_log_system` WHERE `type` = 'error' ORDER BY `date` DESC`
3- provide its result

**Comment by dhorn67** [comment]
search did not return anything?

![search2](https://user-images.githubusercontent.com/36549052/36487604-f8f6c5ae-16e6-11e8-9085-2c9693e88dee.png)
