### ISSUE TITLE
All created Passwords inside folder in root level are flagged as private 

### ISSUE THREAD

**Issue by mbrogies** [nilsteampassnet/TeamPass#2125]
### Steps to reproduce
1. Create a new password with you useraccount in an accessible sharedfolder  at root level
2. Log off
3. Take another user and try to access it

### Expected behaviour
New created passwords inside folder should be accessible by everyone

### Actual behaviour
Passwords are flagged with a yellow tag. This password aren't accessible by any user expect the creator.

Within phpmyadmin you can see that the created password is set with "perso" = "1"

### Server configuration
**Operating system: Debian 8 Jessie**

**Web server: Apache 2.4.10**

**Database: MariaDB 10.0.32**

**PHP version:5.6.33 with Zend Engine 2.6.0 + Zend OPcache 7.0.6**

**Teampass version: 2.1.27 ** 

**Teampass configuration file:
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1736573/tp.config.php.txt)
**

**Updated from an older Teampass or fresh install: fresh install**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:Chrome**

**Operating system: Win10**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I've tried to reproduce but impossible ...

**Comment by Auschie** [comment]
Hi,
i've the same problem.

When you enable small icons to the item list, you can copy the user and password of an item, but editing is impossible by any user.

**Server**
Server OS: Debian 9
Web server: Apache 2.4.25
Database: MariaDB 10.1.26
PHP Version: 7.0.27 Zend Engine v3.0.0 + Zend OPcache v7.0.27

Fresh install, Teampss 2.1.27.10
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1743293/tp.config.php.txt)


**Clients**
OS: Windows 10 Pro 1703/1709 x64
Browser: Firefox 58.0.x
