### ISSUE TITLE
Unable to configure remote password reset

### ISSUE THREAD

**Issue by alanward99** [nilsteampassnet/TeamPass#2126]
### Steps to reproduce
1. Select Server
2. Update server password
3. The ssh user is root 
4. The root password is correct
5. Press the Start Button

### Expected behaviour
Teampass should connect to the remote server using SSH as the root user using the existing password, update the password, save the password in Teampass and then close the SSH connection

I tested

### Actual behaviour
We get the following error:

Error: Parsing URL failed.
Ensure the URL is well written!

Using the Open In A New Window link I can open a session to the remote server and login.

The URL is like this ssh://Server IP Address I can also SSH to the remote server from the Teampass server

### Server configuration
**Operating system**:   CentOS 6.9

**Web server:** Apache 2.2.15

**Database:** Maria DB 10.1.30-1

**PHP version:**  php56w-5.6.32-1.w6.x86_64

**Teampass version:** 2.1.27.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this message the file `/includes/config/tp.config.php`.

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1737612/tp.config.php.txt)

### Client configuration
**Browser:**  Firefox 58.0.1

**Operating system:** Windows 7 64 Bit

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Unfortunately the PHP function used requires a valid domain to be parsed correctly.
For it, an IP is not a valid url that expects a domain.

This could be improved in the future.

**Comment by alanward99** [comment]
Sorry I thought I had responded to this:

I put the fully qualified name in the URL and got the same problem. Am I missing something?

Alan

**Comment by nilsteampassnet** [comment]
Can you provide the url you stored?

**Comment by alanward99** [comment]
This is an example of the URL:

ssh://BMC-VL-NAG1

Alan

**Comment by asantar0** [comment]
@nilsteampassnet @alanward99 
In version 2.1.27.31 the error also persists. The key is updated on the server correctly, but the error message appears on the teampass page and does not update it in the teampass database.
﻿
<img width="609" alt="screen shot 2019-01-10 at 14 59 23" src="https://user-images.githubusercontent.com/24227371/50987419-5c98d980-14e8-11e9-9041-797e0bdcd021.png">
