### ISSUE TITLE
Grant access with simple folder copy 

### ISSUE THREAD

**Issue by Minimoi-14** [nilsteampassnet/TeamPass#2127]
Hello.

Potential problem : 
Initial : User can view 1 folder with 3 subfolders (only 2 with access rights); This user does not have access to the third.

### Steps to reproduce
1. Create a folder with 3 subfolders (eg. :  Parent  (Sub1, Sub2, Sub3)
2. Give full access to a user on Parent, Sub1, Sub2) and forbit access to Sub3
3. Login with user, check your rights, you did see Parent with 2 subfolders
4. Copy Parent folder in another folder
5. Refresh page

You can see it in video : [https://youtu.be/AFFcP_gUgVs ](url)

### Expected behaviour
User can't see Sub3 after copy, permissions fully copied.

### Actual behaviour
Permissions of the parent folder (my settings) are applied, now I have got access to subfolder 3 with all elements. This is a simple way to get hidden passwords

### Server configuration
**Operating system**:
Debian 9

**Web server:**
Teampass docker (lastest)

**Database:**
MariaDB latest

**PHP version:**
With teampass docker

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install (docker)
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox 58.0.2

**Operating system:**
Windows 10 pro

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This is true.
One condition was not correct.
I did a fix and will commit it.

Thanks for reporting
