### ISSUE TITLE
Not able to come out of maintenance mode

### ISSUE THREAD

**Issue by tabrez-shaikh** [nilsteampassnet/TeamPass#213]
Very frustrating:
It shows 
"Maintenance mode has been activated. Only Administrators can log in."

And not able to login. 

User is not root its a user created for that database which has all the access to that particular database.

Also the installation was error less.

I saw include.php and settings.php but no option to disable maintenance mode. 

Also tried forum but not able to post tread it says invalid signature.

Please tell me what to do?

**Comment by albarki** [comment]
Hi, I upgraded from 2.1.26-final-3 to [TeamPass 2.1.27.36] and not able to login with admin even after I disabled the maintance mode using the database mentioned above:
```
# USE [teampass_db_name];
# UPDATE [teampass_db_prefix]misc SET valeur = 0 WHERE intitule = "maintenance_mode" AND type = "admin";`
```
