### ISSUE TITLE
Question about a feature

### ISSUE THREAD

**Issue by elkekou** [nilsteampassnet/TeamPass#2132]
Hi,

i don't post a bug, but a question, so sorry if it's not the good place.
i'm trying your application, in ordre to deploy it at work, and it's really great.

I'm looking for a feature that i did not find. So perhaps i'm looking in wrong direction, or it does not exist.

I want to let possibility of restrict password view to some person for my users. But i also want to set a "super role" for a short list of people which can access to all non personnal password? Is there a way to do it?

Thank you for helping.

**Comment by nilsteampassnet** [comment]
Hello

If you want to allow users to restrict access to their items to other Roles or Users, you need to enable those 2 options
![image](https://user-images.githubusercontent.com/1197546/36643508-90efed32-1a4c-11e8-8aff-8c79b075b976.png)

For your 2d case, I would recommend to define a specific Role for which you allow access to all folders you want and you associate the short list of users to it.

I hope this fits your need.

**Comment by elkekou** [comment]
Hi,

thank you for helping.
I found settings to enable the first case. On other and the second case work like a charm.

But when i tried to mix the 2 case this does not work :
1- i create with standard user an item and i restrict view to me only.
2- i login with a membre of the role wit acces to all folders, but it does not see. I just see message telling "Request access to modify".

So i does not know how to deal with this case. Because i need a group of people wich can see all password of superuser (system and application) in case of great emergency when owner of system is not on site and central authentication does not work.
Is it possible? If it not possible i think maybe i can create a "stored procedure" un mariadb, which add on every item (not personnal one) the id of my group in field "restricted_to".

**Comment by elkekou** [comment]
Hi nils,

what do you think about my question?

Lionel.

**Comment by nilsteampassnet** [comment]
1st what you describe is logic.
If you restrict an item to yourself, then anyone else will not be allowed to access it.

If it is only in case of emergency, you should allocate your "superuser" to a special Group (called "SuperUser" for example).
If your superuser is not here at any moment, allocate any substitute user to this "SuperUser" Goup.
By doing so, this substitute will access all the expected Items.

Or you can allocate all substitute users to this group for all time.

**Comment by elkekou** [comment]
Ok thank you for answer i'll do like you said.
