### ISSUE TITLE
Couldn`t login using IE

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2133]
### Steps to reproduce
1.Open Teampass from IE
2.Try to Log-In with credentials

### Expected behaviour
Redirect to site with password

### Actual behaviour
Nothing Happens.
From FF all fine.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
 Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.23 (cli) (built: Feb  8 2018 21:59:47)
**Teampass version:** 
2.1.27.10

### Client configuration
**Browser:**
IE
**Operating system:**
Windows 10 1709 build 16299.248
#### Web server error log
```
[Sun Feb 25 06:53:55.740545 2018] [mpm_prefork:notice] [pid 1099] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.22 OpenSSL/1.0.1f configured -- resuming normal op$
[Sun Feb 25 06:53:55.740565 2018] [core:notice] [pid 1099] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 27 22:30:27.112840 2018] [mpm_prefork:notice] [pid 1099] AH00169: caught SIGTERM, shutting down
[Tue Feb 27 22:30:28.172691 2018] [mpm_prefork:notice] [pid 50139] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.23 OpenSSL/1.0.1f configured -- resuming normal o$
[Tue Feb 27 22:30:28.172727 2018] [core:notice] [pid 50139] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 27 22:34:32.254380 2018] [mpm_prefork:notice] [pid 50139] AH00169: caught SIGTERM, shutting down
[Tue Feb 27 22:34:50.209912 2018] [mpm_prefork:notice] [pid 1192] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.23 OpenSSL/1.0.1f configured -- resuming normal op$
[Tue Feb 27 22:34:50.211094 2018] [core:notice] [pid 1192] AH00094: Command line: '/usr/sbin/apache2'

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
SCRIPT1002: Syntax error
agses.jquery.js (493,76)

SCRIPT1028: Expected identifier, string or number
teampass.local (622,33)

SCRIPT438: Object doesn't support property or method 'querySelector'
nprogress.js (228,5)

SCRIPT438: Object doesn't support property or method 'addEventListener'
csrfprotector.js (333,1)
```

**Comment by nilsteampassnet** [comment]
Just tested
![image](https://user-images.githubusercontent.com/1197546/36994888-c5b2521e-20b2-11e8-828a-b61f87494bf0.png)

> Microsoft Edge 41.16299.248.0

> Microsoft EdgeHTML 16.16299

**Comment by reginfo** [comment]
Strange, I`m having exact the same version. 
But Still not working on it. 

I cleaned cache, try using in-private mode - still the same. 
I do not use any blocking software.

**Comment by nilsteampassnet** [comment]
I close it.
Reopen on need
