### ISSUE TITLE
Dev branch: HTTP header logon questions/changes

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2134]
Dear Nils, 

You've merged a commit of mine ( https://github.com/nilsteampassnet/TeamPass/pull/2111 ) 
I've been testing with the dev branch now and a few things need to be changed. (I do apologize)
I want to make a new pull request, but I have some questions first.

A new parameter should be added in upgrades and in the default tp.config.php

    'enable_http_request_login' => '0',

I'm not sure how to handle that in the commit. 

And a logic error was made inside the js that triggers the logon. When the user is denied, every second a logon attempt is made again and the counter goes negative. 

In index.php, the javascript should be changed to: 
  

```
 echo    '<script>
                        var seconds = 1;
                        function updateLogonButton(timeToGo){
                                    document.getElementById("but_identify_user").value = "' . $LANG['duration_login_attempt'] . ' " + timeToGo;
                                }
                                $( window ).on( "load", function() {
                                    updateLogonButton(seconds);
                                    setInterval(function(){
                                                seconds--;
                                                if(seconds == 0){
                                                        launchIdentify(\'', isset($SETTINGS['duo']) && $SETTINGS['duo'] === "1" ? 1 : '', '\', \''.$nextUrl.'\', \'', isset($SETTINGS['psk_authentication']) && $SETTINGS['psk_authenticatio$
                                                }
                                                if(seconds >= 0){
                                                        updateLogonButton(seconds);
                                                }
                                        }, 1000);
                                });
                </script>';
```

Is this something you can change? Do you want me to create a new pull request? (if so, how do I hande the change in tp.config.php?)

**Comment by nilsteampassnet** [comment]
I have added the parameter during the commit I did.

I will do the changes you expect in index.php

Thank you
