### ISSUE TITLE
Cannot import Keepass xml files. 

### ISSUE THREAD

**Issue by elakson** [nilsteampassnet/TeamPass#2135]
hello

I love your excellent product. But there is a little issue. I dunno if i've screwed something up. All i get is
Error: -600, Message: File size error., File: BITCHSLAP-db-KeePass.xml when i try to import a keepass database. I have putted the correct roles on the user as it seems. Running the latest version.

And the logs says nothing. Do you have any suggestions?

**Comment by elakson** [comment]
ok, i notice that it is the size. is there a restiction on how big the file can be? i tried a 10MB file , even that did not go thru but a file that was a little bit over 7MB went through. Is this the issue? limitation on filesize?

**Comment by nilsteampassnet** [comment]
Yes currently the limitation is defined at 10Mo for à keepass import file. 
So you must have a small error file.

I believe this can be in increased but it is not an option. I will complete this answer with the détail

**Comment by nilsteampassnet** [comment]
Edit file `items.import.php`
Search for
```
            container : "upload_container_kp",
            max_file_size : "10mb",
```

Replace `10mb` by another value.

Please make a feedback.

**Comment by elakson** [comment]
Thanks for suggestion, it helped me out :) , keep up the good work
