### ISSUE TITLE
Ldap authentication not working in TeamPass 2.1.27.10

### ISSUE THREAD

**Issue by Ramasudhastv** [nilsteampassnet/TeamPass#2137]
Please find the configuration details and the log files .

Error getting when ldap login : Login credentials do not correspond! 

[root@server TeamPass]# cat ./files/duo.debug.txt

Content of data sent 'DgBgpDAWnlq8Hie2RIdvX9XYEqTW3ebjjhGAxj8GoIZSlLmpvWBQPjeAnyTdEawL2V1IIaZlBmmbLDd7EiqGpjaWC8dDwAovODh+STWcox5k1azWv3baQ3W8Nvk6BgFTSYLPOrM34V71ZJjrwp8ovDYzGAsM5Ixhz46/Hw0FdJH3qnjQE9m0PSodyroelEuuhi1iUxS9OnmqzRiZ/1XaZ+ncXg0SoNWKJxuohKSjAhACbLPupBKhMqDAjaiRQ14pf3Rl1CIcBk4ZupD5X0PqCagfvCdz2jpyLbs/PhO9'
Starting authentication of 'user@domain.com'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified:

----
Identified : false

[root@Server TeamPass]# cat ./files/ldap.debug.txt
Get all LDAP params :
mode : 1
type : posix
base_dn : dc=domain,dc=com
search_base : 0
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @domain.com
domain_controllers : domain1,domain2
port : 389
use_ssl : 0
use_tls : 0
*********

Get all ldap params :
base_dn : dc=domain,dc=com
account_suffix : @domain.com
domain_controllers : domain1,domain2
port : 389
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success

After authenticate : Invalid credentials

ldap status :

[root@Server TeamPass]#
----------------

[root@server TeamPass]# cat includes/config/tp.config.php
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'https://$hostname/TeamPass',
    'favicon' => 'https://$hostname/TeamPass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'url_to_upload_folder' => 'https://$hostname/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'https://$hostname/TeamPass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'posix',
    'ldap_suffix' => '@domain.com',
    'ldap_domain_dn' => 'dc=domain,dc=com',
    'ldap_domain_controler' => 'server1,server2',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '1',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1517672087',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'ldap_port' => '3268',
);
[root@server TeamPass]#

**Comment by Ramasudhastv** [comment]
It is working . issue was with my ldap configuration .

**Comment by nilsteampassnet** [comment]
Thank you for your feedback
