### ISSUE TITLE
LDAP TLS not working with Active Directory

### ISSUE THREAD

**Issue by jcoquery** [nilsteampassnet/TeamPass#2138]
### Steps to reproduce
Enable TLS in LDAP options.
Test the configuration

### Expected behaviour
Authentication with LDAP TLS

### Actual behaviour
Work only without TLS

### Server configuration
**Operating system**:
Docker (Centos)
**Web server:**
Apache
**Database:**
5.7.19
**PHP version:**
7.1.9
**Teampass version:** 
2.1.27

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1731095/tp.config.txt)

### Client configuration
**Browser:**
All

**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Your tp.config doesn't show that TLS is enabled.

If you are new user of Teampass, I would recommend to migrate to latest version from development branch.
LDAP has been improved.
You may find some help in https://teampass.readthedocs.io/en/latest/install/ldap/

**Comment by jcoquery** [comment]
I'm already in the larest development branch.
The tp.config file doesn't show tls enabled because my users needs to authenticate and it works without tls.
I tried to set ldapdebug to 1 but the log file doesn't show more informations than then connection test on ldap config page.
I'm in a docker environment, but I have installed openldap client to test directly from shell and it works after adding  the 'root ca' certificate in the ldap.conf file.
How can I have more debug information? There is something to do to add the 'root ca' certificate in the teampass conf or nginx config?

**Comment by jcoquery** [comment]
All my appologies, it seems somebody on did changes on the server during the same time than me.
So, after a full verification of the server configuration (ldap.conf and teampass) and complete restart, it works.
Just a comment, it sould be usefull to implement a more verbose debug for this kind of connection.
Thanks

**Comment by nilsteampassnet** [comment]
No problem. This happens.

Regarding your suggestion, I will
