### ISSUE TITLE
Error in releasing directory

### ISSUE THREAD

**Issue by Theeus1579** [nilsteampassnet/TeamPass#2139]
### Steps to reproduce
1. Create server Fedora (LAMP);
2. Installing TeamPass (wget Teampass 2.1.27);
3. Validate the diretories.

### Expected behaviour
The directory is validate by TeamPass for liberate for modify and install
### Actual behaviour
The TeamPass don't validate the directory. I'm using code "chmod 777" in the directories, but it did not work.
### Server configuration
**Operating system**:
Fedora 27
**Web server:**
Apache 2.2.15
**Database:**

**PHP version:**
7.1.15
**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Fedora 27
#### Web server error log
```March 8, 2018
 14:57 PCI: Fatal: No config space access function found kernel
 Reiniciar
 05:09 Failed to start dnf makecache. systemd
 03:45 Can't find sendmail at /usr/sbin/sendmail, not mailing output anacron
 02:08 Failed to start dnf makecache. systemd
March 7, 2018
 23:07 Failed to start dnf makecache. systemd
 17:04 teste02 : user NOT in sudoers ; TTY=unknown ; PWD=/run/user/1001 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged sudo
 16:56 PCI: Fatal: No config space access function found kernel
 Reiniciar
 16:49 fatos : user NOT in sudoers ; TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged sudo
 16:48 Credentials cache I/O operation failed [sssd[krb5_child[3791]]] 2 
 16:47 Credentials cache I/O operation failed [sssd[krb5_child[3789]]] 2 
 16:47 Credentials cache I/O operation failed [sssd[krb5_child[3781]]] 2 
 14:55 fatos : user NOT in sudoers ; TTY=pts/0 ; PWD=/var/www/html ; USER=root ; COMMAND=/bin/chmod 777 as sudo
 14:52 fatos : user NOT in sudoers ; TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged sudo
 14:36 PCI: Fatal: No config space access function found kernel
 Reiniciar
 03:38 Can't find sendmail at /usr/sbin/sendmail, not mailing output anacron

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Here you have a server configuration issue.

I believe this is due to the fact that your apache user is not part of the user groups allowed to access those folders.

You should check consistency of groups and users access rights over your folders.

**Comment by nilsteampassnet** [comment]
Please reopen on need
