### ISSUE TITLE
Moving subfolder to root level not possible

### ISSUE THREAD

**Issue by mbrogies** [nilsteampassnet/TeamPass#2140]
### Steps to reproduce
1. Open Teampass -> Mark folder 
2. Select Move folder
3. Select Root

### Expected behaviour
The folder should be moved to the root level

### Actual behaviour
Teampass says "i need to select a folder

### Server configuration
**Operating system**: LINUX

**Web server:** APACHE

**Database:** 5.5.5-10.0.32-MariaDB-

**PHP version:** 5.6.33.0

**Teampass version:**  2.1.27
--

**Teampass configuration file:**

### Client configuration
**Browser:** Chrome 64 / Chromium 64

**Operating system:** Windows 10 / Arch Linux

**Comment by nilsteampassnet** [comment]
Correct.

Thank you
