### ISSUE TITLE
Reading folder ...    NaN%  Error

### ISSUE THREAD

**Issue by neryangj** [nilsteampassnet/TeamPass#2141]
### Steps to reproduce
Dont know how to reproduce the issue

### Expected behaviour
Will see Folder hierarchy 

### Actual behaviour
 Reading folder ...   NaN% 

### Server configuration
**Operating system**: Ubuntu 16.04.4

**Web server:** 

**Database:**
5.7.21

**PHP version:** 
7.1.9

**Teampass version:** 
2.1.27

![reading nan](https://user-images.githubusercontent.com/30711079/37267348-98582ace-2624-11e8-9bb5-90b93efb5801.JPG)

**Comment by nilsteampassnet** [comment]
Please forward the errors from Apache and inside the web console

**Comment by neryangj** [comment]
reinstalled teampass
