### ISSUE TITLE
2.1.27.10 - teampass can't use the search in the password menu, for the first time.

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2144]
Hi,

I have 2.1.27.10 version of teampass, and We recently implemented https.

We login in teampass, and when we login for the first time, We can't use the search in the password menu to see the details of the items, after we made a search, the search goes fine, but when we click the item to see its details, appears the "waiting tool" spinning.

And after that we can't see any item details, we need to refresh to see the details of any items.
----------------------------------------------------------------------------------------------------
Conclusions:
If I use the search in the "password" menu, it does the search but doesn't access the details of any item, when clicked.(because we have the spinning tool), so we need to refresh to get the things going normal.

If I login for the first time, and go directly to an Item, it displays fine, and if we use the search box after it, it goes fine.

### Steps to reproduce
1.login
2. password menu (the one with the folder tree) make a search for na item(the one on the right on top of the listing item)
3.select the Item to check the details
(endless spinning tool appears)

### Expected behaviour
We should see the details of the selected item

### Actual behaviour
appears the spinning tool and nothing happens

### Server configuration
**Operating system**:
linux
**Teampass version:** 
2.1.27.10
### Client configuration
**Browser:**
ALL
tested mainly on mozilla - anonymous mode

#### Web server error log
::1 - - [14/Mar/2018:12:33:32 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.20 (internal dummy connection)"
#### Log from the web-browser developer console (CTRL + SHIFT + i)
can't add anything here, probably for my unexperience.

here's a SS of the actual scene.
![imagem](https://user-images.githubusercontent.com/1770475/37404136-dc840028-2788-11e8-8f03-b924beae11c2.png)

Ty.

**Comment by nilsteampassnet** [comment]
Was this working prior to move to https?

Did you changes all expected configuration items and paths?

http://teampass.readthedocs.io/en/latest/errors/

**Comment by asgomes** [comment]
Hi Nils,

sorry for the delay on this answer, But I somehow lost it's track.

I'm not 100% sure, but this is the way I usually use the teampass, when I made a search, and I don't recall to have this.

I've consulted that page when I was configuring the https. I'm attaching my tp.config.file.

**Comment by nilsteampassnet** [comment]
Please capture the error when you do your search as explained http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console
