### ISSUE TITLE
Drag and drop item without permission

### ISSUE THREAD

**Issue by elkekou** [nilsteampassnet/TeamPass#2145]
Hi,

i'm have a "bug" or a bad configuration ;).
There is some item created limited to a short list of user in a folder i can see.
The item is mark with red flag, but what i does not understand is i can drag and drop this item wherever i want including my personnal storage. 
So could you help me to see what i missed

**Comment by nilsteampassnet** [comment]
Please use the provided template.

You don't even provide the version ... not easy to help in such case.

**Comment by elkekou** [comment]
Sorry i forgot this, i'm using teampass 2.1.27.10 on centos 7.4 with apache.

But i saw a buggix https://github.com/nilsteampassnet/TeamPass/issues/2066 in your today's release so i'll try update tomorrow.

**Comment by nilsteampassnet** [comment]
Yes please upgrade to 2.1.27.11 (https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.11)

**Comment by elkekou** [comment]
Hi,
it's now working like a charm, thank you for your job Nils.
