### ISSUE TITLE
0 Objects Found

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#2147]
### Steps to reproduce
1. Open Teampass and search somethink in upper right box
2. Result 0 objects found
3.

### Expected behaviour
We can found items

### Actual behaviour
No items found

### Server configuration
**Operating system**: Windows 2008 R2

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.6.3.1

**Teampass version:**  2.1.27.11

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:* All

**Operating system:** All

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please report your issue with details.
You can imagine that such basic case has been tested successfully.
So if if doesn't work for you, then I need details to investigate.

Since 2.1.27.11, please use the integrated report generator
http://teampass.readthedocs.io/en/latest/faq/#how-to-report-a-bug
