### ISSUE TITLE
All passwords was lost.

### ISSUE THREAD

**Issue by EdsonRSJr** [nilsteampassnet/TeamPass#2148]
### Steps to reproduce
1. Login on Teampass
2. Choose any registry
3. Click Copy-Password

### Expected behaviour
In my last access to the portal I observed that some passwords has not been shown on the system neither copied to the clipboard.

### Actual behaviour
I can't retrieve any password from Teampass.

### Server configuration
**Operating system**:
 - Debian Stretch 9.4

**Web server:**
 - Apache/2.4.29

**Database:**
 - MySQL (MariaDB 10.0.32)

**PHP version:**
 - PHP 7.0.27
**Teampass version:** 
 - Teampass 2.1.17.10

**Teampass configuration file:**
[settings.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1819365/settings.php.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1819287/tp.config.php.txt)

### Client configuration
**Browser:**
I tried to access whith Chrome/Mozilla/IE/Edge

**Operating system:**
Mac OS X and Windows

#### Web server error log
[error.log](https://github.com/nilsteampassnet/TeamPass/files/1819298/error.log)

Insert your webserver log here

#### Log from the web-browser developer console (CTRL + SHIFT + i)
[Web Console.txt](https://github.com/nilsteampassnet/TeamPass/files/1819325/Web.Console.txt)

Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
THis is a known bug on 2.1.27.10 that until now couldn't be reproduced, but it doesn't appear in newest version. (#2123)

The solution is to run those 2 queries
```
UPDATE `teampass_items` SET perso = '0';

UPDATE `teampass_items` AS i
INNER JOIN `teampass_nested_tree` AS n ON n.id = i.id_tree
SET i.perso = '1'
WHERE n.personal_folder = '1';
```

The 1st will force to 0 all items (not personal).
The 2d will update the personal status of each item depending on its belonging to a personal folder.

Important: as any manipulation of the database, it is required to perform a backup before

**Comment by EdsonRSJr** [comment]
So, I ran those commands and saw that no changes are made on DB and the issue remains.

I can login, I can copy Login name, but I can't copy the password, the clipboard remains with the last item copied.


Is there any information can I sent to you?

Thanks for the help.

<img width="1109" alt="screen shot 2018-03-16 at 15 24 58" src="https://user-images.githubusercontent.com/37444664/37538512-98809050-292f-11e8-9a5c-bf36a9df2328.png">

**Comment by nilsteampassnet** [comment]
I woul dneed an access to your server.

mail me at nils@teampass.net

**Comment by arregi** [comment]
Hello:

I have same issue. I can copy it in tree view. But If I get a item to edit it, in the password tab, I can't copy password.
The copy button do nothing. 

Server configuration
Operating system*: Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64
Web server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.5
Database: 5.5.64-MariaDB
PHP version: 7.4.5
Teampass version: 2.1.27.36

Thanks

**Comment by EdsonRSJr** [comment]
I've had a problem in my server and I done a restore, but unfortunately I forgot to save the crypto file that contains the key to decrypt all passwords stored at DB. This diagnosis was made by Nils and I forgot to close this case.

I've had to rebuild another one from the scratch.

**Comment by paulojrsti6** [comment]
I can't make the button to copy the password work, copy the login works but the password does not, nor editing the password does not appear, but with administrator user yes
