### ISSUE TITLE
timezone after update to 2.1.27.11

### ISSUE THREAD

**Issue by cgermanb** [nilsteampassnet/TeamPass#2149]
hi,

I update to 2.1.27.11 and now I have session timeout, i find this solution:

https://github.com/nilsteampassnet/TeamPass/issues/1583

but i dont have =
         $_SESSION['fin_session'] = $userTime + $dataReceived['duree_session'] * 60;

in httpd log i can see the problem with timezone, but i dont known what change.

date, timedatctl and hwclock i can see the correct time, but in the web page is other hours.

in php.ini the timezone is correct.

i dont known what more change.

regards
Carlos

**Comment by cgermanb** [comment]
now, timezone error disappeared.
i have in httpd log : Undefined index: copyright in /var/html/teampass/index.php on line 841

**Comment by nilsteampassnet** [comment]
How strange.

Concerning the error, it is also very strange as this constant is defined inside includes/config/includes.php file.
Can you please check that `$SETTINGS_EXT['copyright'] = "2009 - ".date('Y');` is in this file?

If not, please reperform an upload of the files.

**Comment by cgermanb** [comment]
thanks for reply,

in my server the file name is include.php without S, Will that be?

inside the file appear the constant and the line too

**Comment by cgermanb** [comment]
also appears banner indicating maintenance mode

**Comment by nilsteampassnet** [comment]
So I believe that it was an old error in your log.

If you have the maintenance mode enabled, you need to disable it from the admin settings page.

**Comment by cgermanb** [comment]
but i can access, when i try acces but return to login page

**Comment by cgermanb** [comment]
thank you, i can access, increase the expiration time and get access!

**Comment by nilsteampassnet** [comment]
ok good
