### ISSUE TITLE
DB upgrade fails on mysql5.5 due to SQL syntax error

### ISSUE THREAD

**Issue by aokunev** [nilsteampassnet/TeamPass#2150]
DB modification failed during teampass upgrade from 2.1.27.3 to 2.1.27.11 on stage3. 
the error found  in ./install/upgrade_run_2.1.27.php related to following line:
ALTER TABLE teampass_misc  CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT");

mysql client showed same error during manual execution. It might be limitation of mysql5.5 related to primary key constraint or autoincrement. 

mysql> ALTER TABLE teampass_misc  CHANGE "id" "increment_id" INT(12) NOT NULL AUTO_INCREMENT;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"id" "increment_id" INT(12) NOT NULL AUTO_INCREMENT' at line 1

=== following SQL run manually fixed the problem and allowed to complete upgrade.

ALTER TABLE teampass_misc modify id int(12) not null;
ALTER TABLE teampass_misc DROP PRIMARY KEY;
ALTER TABLE teampass_misc change id increment_id INT(12);
ALTER TABLE teampass_misc modify increment_id int(12) not null AUTO_INCREMENT;
ALTER TABLE teampass_misc add PRIMARY KEY(increment_id);

thanks, Andrey

**Comment by nilsteampassnet** [comment]
thank you for reporting.
Perhaps is this related to this old version of mysql but anyway I will investigate

**Comment by antoweb** [comment]
Hi,
i encountered the same issue but resolved making uograde with step:

Before from 2.1.27.3 to 2.1.27.10 and tha from 2.1.27.10 to 2.1.27.11

And works good!
