### ISSUE TITLE
Changing personal salt key loses personal passwords

### ISSUE THREAD

**Issue by srvMelchior** [nilsteampassnet/TeamPass#2157]
### Steps to reproduce
1. Create a new user with personal folder
2. Log in with new user & set new user password
3. Select "Set the salt key" and type in the inital key
4. Select the personal folder, open the menu and click on "Add item"
5. Type in a label & password and click on "Save"
6. The password is hidden as ***** with the option to show as plain text.
7. Choose "My profile" and further select the task "Change my personal salt key"
8. The initial salt key is visible as plain text next to "Old salt key :"
9. Type in a new salt key and the confirmation, click on "Change"
10. The progress display changes from 0% to 50% to 100% to "Done"
11. Select the earlier created item

### Expected behaviour
The password is still hidden as ***** with the option to show as plain text.

### Actual behaviour
The password is gone

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache/2.4.18 (2017-09-18T15:09:02)

**Database:** 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** TeamPass-2.1.27.10.

**Teampass configuration file:**
[settings.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833641/settings.php.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833643/tp.config.php.txt)

### Client configuration
**Browser:** Firefox Quantum 57.0.2 (64-Bit)

**Operating system:** Windows 7 SP1

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This could not be reproduced in 2.1.27.11.

I encourage you to update.

**Comment by nilsteampassnet** [comment]
Reopen if needed

**Comment by srvMelchior** [comment]
Updated, could not reproduce, thank you for the feedback :)
