### ISSUE TITLE
Login with LDAP credentials broken after Update to 2.1.27.11

### ISSUE THREAD

**Issue by fr33mi1nd** [nilsteampassnet/TeamPass#2158]
### Steps to reproduce
1. Install TeamPass 2.1.27.9 in Docker
2. Setup LDAP User Sync
3. Login successfully with LDAP credentials
4. Update TeamPass to 2.1.27.11
4. Try Login with LDAP credentials
5. Fail

### Expected behaviour
Users should be able to successfully log in using his LDAP credentials

### Actual behaviour
The User gets one of two error Messages. Either "Login credentials do not correspond!" or "Login credentials incorrect!"

### Server configuration
**Operating system**:
* Ubuntu 16.04.3 LTS

**Web server:**

**Database:**
* MySQL 5.7.20

**PHP version:**
* 7.1.9

**Teampass version:** 
* 2.1.27.11

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1837388/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
* Update from 2.1.27.9 to 2.1.27.11

### Client configuration
**Browser:**
* Google Chrome 65.0.3325.162 x64
* Safari 11.0.3 (13604.5.6)

**Operating system:**
* Windows 10
* macOS 10.13.3 (17D102)
* Ubuntu Linux 16.04

#### Web server error log
```
172.20.0.2 - - [22/Mar/2018:09:55:44 +0000] "GET /includes/css/passman.css HTTP/1.1" 200 7579 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:09:55:44 +0000] "GET /includes/js/select2/css/select2.min.css HTTP/1.1" 200 15195 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:09:55:44 +0000] "GET /includes/libraries/Authentication/agses/agses.css HTTP/1.1" 200 328 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:11:51:59 +0000] "POST /sources/checks.php HTTP/1.1" 200 11 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:11:51:59 +0000] "POST /sources/identify.php HTTP/1.1" 200 105 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:11:53:57 +0000] "GET /includes/js/jquery-ui/images/ui-bg_glass_100_f8f8f8_1x400.png HTTP/1.1" 200 259 "<internal_url>:21443/includes/js/jquery-ui/jquery-ui.theme.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:11:53:57 +0000] "POST /sources/checks.php HTTP/1.1" 200 11 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
172.20.0.2 - - [22/Mar/2018:11:53:58 +0000] "POST /sources/identify.php HTTP/1.1" 200 105 "<internal_url>:21443/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
none present
```

**Comment by fr33mi1nd** [comment]
[webui_ldaptest.txt](https://github.com/nilsteampassnet/TeamPass/files/1841067/webui_ldaptest.txt)
[ldap.debug.txt](https://github.com/nilsteampassnet/TeamPass/files/1841068/ldap.debug.txt)

**Comment by nilsteampassnet** [comment]
Difficult to help you remove the configuration of LDAP.
But can you please run this mysql query `SELECT * FROM `teampass_misc` WHERE `intitule` = 'ldap_port' ` and give the result

**Comment by fr33mi1nd** [comment]
`mysql> SELECT * FROM teampass_misc WHERE intitule= 'ldap_port';
+--------------+-------+-----------+--------+
| increment_id | type  | intitule  | valeur |
+--------------+-------+-----------+--------+
|          116 | admin | ldap_port | 389    |
+--------------+-------+-----------+--------+
1 row in set (0.04 sec)`

I can't find the variable 'ldap_port' in includes/config/tp.config.php. should it be in there? I did no configuration changes after updating Teampass.

**Comment by fr33mi1nd** [comment]
Thanks for your quick Support. This solved the Issue. Strange that the Application broke without configuration changes.
