### ISSUE TITLE
Missing backslash in acount name

### ISSUE THREAD

**Issue by xcorella** [nilsteampassnet/TeamPass#2161]
### Steps to reproduce
1. Save new item with account name contains backslash 
2. Show it 
![show_account](https://user-images.githubusercontent.com/9573919/37820689-badd31ce-2e81-11e8-8cac-8e7d92650168.PNG)
3. And edit again this item - in input missing backslash 
![edit_account](https://user-images.githubusercontent.com/9573919/37820719-d1a7b35c-2e81-11e8-8918-0c354f7aa5e6.PNG)

### Expected behaviour
If you edit item account with backslash, show corrent account name with backslash

### Actual behaviour
Show account name without backslash, but account name is contain backslash

### Server configuration
**Operating system**:
Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-6-amd64
**Web server:**
Apache/2.4.25 (Debian)
**Database:**
 Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 7.0.27-0+deb9u1
**Teampass version:** 
2.1.27.10
**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1840817/tp.config.php.txt)
**Updated from an older Teampass or fresh install:**
Fresh install 2.1.27.10

### Client configuration
**Browser:**
Google Chrome 65, Firefox 59, 64bit
**Operating system:**
Windows 10 Enterprise 1709

**Comment by nilsteampassnet** [comment]
I will investigate

Thanks

**Comment by nilsteampassnet** [comment]
Fixed in last commit in development branch.
Will be added to package 2.1.27.11

**Comment by xcorella** [comment]
Thanks a lot :-)
