### ISSUE TITLE
Wrong permissions on first LDAP login

### ISSUE THREAD

**Issue by darrais** [nilsteampassnet/TeamPass#2162]
Hi,

I'm having an issue with LDAP authentication and the automatic creation of new users. 

On the first login, the user is automatically registered in the local TeamPass database and its personal folder is created (TeamPass is configured to do as such). 

The problem is, when the user is created and logins for the first time, he is granted with "read" permissions on all folders ever created. The permissions are rectified when the user refreshes the browser, being now able to only access its personal folder.

### Steps to reproduce
1. Configure LDAP authentication;
2. Authenticate with a new user (that is not yet created locally in TeamPass);
3. Wait for the user to be created and login.

### Expected behaviour
The new user should only have permissions to access its personal folder.

### Actual behaviour
The user is granted with "read" permissions on all folders. After refreshing the browser, the permissions are rectified and the user is given the correct access privileges.

### Server configuration
**Operating system**:
CentOS (Linux)

**Teampass version:** 
2.1.27.10

### Client configuration
**Browser:**
ALL (Tested mainly with Google Chrome)

**Comment by nilsteampassnet** [comment]
This is a bug fixed in 2.1.27.11.

PLease update.
