### ISSUE TITLE
Mstsc and putty connections from WebGUI

### ISSUE THREAD

**Issue by maiconstedille** [nilsteampassnet/TeamPass#2163]
Is there any possibility of invoking the terminal service (mstsc) or ssh (putty) connection through webGUI, so that when clicking the link it opens those connection programs on the computer? Not a problem, just a hint of a new function.

**Comment by nilsteampassnet** [comment]
This feature already exists.

Please read http://teampass.readthedocs.io/en/latest/features/feat-remote/

**Comment by maiconstedille** [comment]
is it possible to do this also for rdp (mstsc)?
