### ISSUE TITLE
Info tab is not working if behind a proxy

### ISSUE THREAD

**Issue by BirdOfPrey2608** [nilsteampassnet/TeamPass#2167]
### Steps to reproduce
1. Log in as admin
2. Select tab 4 (index.php?page=manage_main#tabs-4)
3. There is no information displayed if TeamPass is behind a proxy (but proxy is set in settings tab)

### Expected behaviour
The desired information should be displayed.

### Actual behaviour
There is no information displayed.

### Server configuration
**Operating system:** Debian GNU/Linux 9.4 (stretch)

**Web server:** apache2 (2.4.25-3+deb9u3)

**Database:** mariadb-server-10.1 (10.1.26-0+deb9u1)

**PHP version:** php (1:7.0+49)

**Teampass version:** 2.1.27.10

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:** Updated

### Client configuration
**Browser:** any

**Operating system:** any

#### Web server error log
...
PHP Warning:  file_get_contents(https://teampass.net/utils/teampass_info.json): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/TeamPass_2.1.27.10/sources/admin.queries.php on line 104
...

### Suggested solution
The problem seems to be at line 103 of the file /sources/admin.queries.php
There is no proxy statement in the array for $content, my workaround solution to this is to add this manually:
...
102                // Get info about Teampass
103                $context = stream_context_create(array('http' => array('ignore_errors' => true, 'proxy'=>'IP:PORT')));
104                $json = file_get_contents('https://teampass.net/utils/teampass_info.json', false, $context);
...

**Comment by nilsteampassnet** [comment]
Thank you for the solution.
