### ISSUE TITLE
API for adding users is not working

### ISSUE THREAD

**Issue by BirdOfPrey2608** [nilsteampassnet/TeamPass#2168]
### Steps to reproduce
1. Set an API key
2. Create a https link to add user
3. Enter link in Browser

### Expected behaviour
The user is added.

### Actual behaviour
The answer in the browser is {"err":"Empty Login given"}.
The user is not added.

### Server configuration
**Operating system:** Debian GNU/Linux 9.4 (stretch)

**Web server:** apache2 (2.4.25-3+deb9u3)

**Database:** mariadb-server-10.1 (10.1.26-0+deb9u1)

**PHP version:** php (1:7.0+49)

**Teampass version:** 2.1.27.10

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:** Updated

### Client configuration
**Browser:** any

**Operating system:** any

#### Web server error log
...
PHP Notice:  Undefined variable: link in /var/www/html/TeamPass_2.1.27.10/api/functions.php on line 901
PHP Warning:  mysqli_escape_string() expects parameter 1 to be mysqli, null given in /var/www/html/TeamPass_2.1.27.10/api/functions.php on line 901
...

### Suggested solution
The variable $link seems not to be available to the function rest_get(). My workaround to this is to add

...
global $link;
...

to the function rest_get() at line 280.

**Comment by nilsteampassnet** [comment]
Thank you for the solution
