### ISSUE TITLE
Cannot generate Personal Salt Key

### ISSUE THREAD

**Issue by samsilver1977** [nilsteampassnet/TeamPass#2169]
### Steps to reproduce
1. I can't set personal Salt Key. After a user has been created, I only have the option to CHANGE or RESET Personal Salt Key although I never set any. Could this be a bug? Reseting the Personal Salt key is not always functioning.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64

**Web server:** nginx/1.10.3

**Database:** 5.7.21

**PHP version:** 7.0.27-0+deb9u1

**Teampass version:** 2.1.27.11

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 65.0.3325.181

**Operating system:** Windows - 64bits

#### Web server error log
```
Undefined index: path - /var/www/html/sources/main.queries.php (1270)
```

**Comment by nilsteampassnet** [comment]
Did you use the "set personal saltkey" feature?

![image](https://user-images.githubusercontent.com/1197546/37993029-9e545fca-320d-11e8-832e-82fd8655506c.png)

**Comment by samsilver1977** [comment]
No! I can only see change and reset. I can't change it because I never set it. If I also click on reset, nothing happens.
![teampass_salt](https://user-images.githubusercontent.com/37831926/38015078-ff27a1ce-326a-11e8-9da5-176c53fd1625.png)

**Comment by nilsteampassnet** [comment]
You are showing the User dialogbox.
Setting the saltkey is not done on this dialog.

It is done through the menu icon as shown on my previous screenshot.

**Comment by samsilver1977** [comment]
Good Morning Nils,

The dialog to set the Personal Salt Key like that on your screenshot is not showing. Do i need any extra config?

**Comment by nilsteampassnet** [comment]
Did you enabled the personal folder?

![image](https://user-images.githubusercontent.com/1197546/38269226-4141692c-3780-11e8-8623-a22317e05d04.png)

**Comment by samsilver1977** [comment]
Yes I did

Mit freundlichen Grüßen
SV Werder Bremen GmbH & Co KG aA

Samuel Okoh
IT
[SV Werder Bremen - Lebenslang grün weiß]
[cid:image003.png@01D3CBFA.AEFA7B30]



Telefon:

+49 (421) 43459 1191<tel:+49421434591191>

Mobil:

+49 (1520) 8964445<tel:+4915208964445>

E-Mail:

samuel.okoh@werder.de<mailto:Samuel.Okoh@werder.de>

Website:

www.werder.de

Facebook:

www.facebook.com/werderbremen<http://www.facebook.com/werderbremen>

Twitter:

www.twitter.com/werderbremen<http://www.twitter.com/werderbremen>





Franz-Böhmert-Str. 1c - 28205 Bremen
Franz-Böhmert-Straße 1c - 28205 Bremen - Telefon 0421/43 45 90 - Fax 0421/49 35 55 - E-Mail info@werder.de<mailto:info@werder.de>
SV Werder Bremen GmbH & Co KG aA - Vorsitzender des Aufsichtsrates: Marco Bode
Amtsgericht Bremen HRB 21775 - Ust-Identnummer De 813837844 - Steuer-Nr. 460/102/02165
Komplementärin: Werder Verwaltungs GmbH
Geschäftsführung: Klaus Filbry (Vorsitzender), Frank Baumann, Dr. Hubertus Hess-Grunewald
Amtsgericht Bremen HRB 21538 - Steuernummer 460/102/02173
Bevor Sie diese Mail ausdrucken, prüfen Sie bitte, ob dies wirklich nötig ist.
Umweltschutz geht uns alle an!
Von: Nils Laumaillé <notifications@github.com>
Gesendet: Dienstag, 3. April 2018 20:48
An: nilsteampassnet/TeamPass <TeamPass@noreply.github.com>
Cc: Okoh, Samuel <Samuel.Okoh@werder.de>; Author <author@noreply.github.com>
Betreff: Re: [nilsteampassnet/TeamPass] Cannot generate Personal Salt Key (#2169)


Did you enabled the personal folder?

[image]<https://user-images.githubusercontent.com/1197546/38269226-4141692c-3780-11e8-8623-a22317e05d04.png>

**Comment by nilsteampassnet** [comment]
Please do a screenshot of this menu as I did?

Have you enabled the Personal Folder option for the user?
Refer to http://teampass.readthedocs.io/en/latest/manage/manage-users/

**Comment by samsilver1977** [comment]
Yes I did enable the Personal Folder.

Kind regards,
SV Werder Bremen GmbH & Co KG aA

Samuel Okoh
IT
[SV Werder Bremen - Lebenslang grün weiß]
[cid:image002.png@01D3D0B0.4A7094F0]



Telephone:

+49 (421) 43459 1191<tel:+49421434591191>

Mobile phone:

+49 (1520) 8964445<tel:+4915208964445>

E-Mail:

samuel.okoh@werder.de<mailto:Samuel.Okoh@werder.de>

Website:

www.werder.de

Facebook:

www.facebook.com/werderbremen<http://www.facebook.com/werderbremen>

Twitter:

www.twitter.com/werderbremen<http://www.twitter.com/werderbremen>





Franz-Böhmert-Str. 1c - 28205 Bremen
Franz-Böhmert-Straße 1c - 28205 Bremen - Telefon 0421/43 45 90 - Fax 0421/49 35 55 - E-Mail info@werder.de<mailto:info@werder.de>
SV Werder Bremen GmbH & Co KG aA - Vorsitzender des Aufsichtsrates: Marco Bode
Amtsgericht Bremen HRB 21775 - Ust-Identnummer De 813837844 - Steuer-Nr. 460/102/02165
Komplementärin: Werder Verwaltungs GmbH
Geschäftsführung: Klaus Filbry (Vorsitzender), Frank Baumann, Dr. Hubertus Hess-Grunewald
Amtsgericht Bremen HRB 21538 - Steuernummer 460/102/02173
Von: Nils Laumaillé <notifications@github.com>
Gesendet: Mittwoch, 4. April 2018 19:05
An: nilsteampassnet/TeamPass <TeamPass@noreply.github.com>
Cc: Okoh, Samuel <Samuel.Okoh@werder.de>; Author <author@noreply.github.com>
Betreff: Re: [nilsteampassnet/TeamPass] Cannot generate Personal Salt Key (#2169)


Please do a screenshot of this menu as I did?

Have you enabled the Personal Folder option for the user?
Refer to http://teampass.readthedocs.io/en/latest/manage/manage-users/
