### ISSUE TITLE
2FA Reset Link Can Be Abused

### ISSUE THREAD

**Issue by jannero** [nilsteampassnet/TeamPass#2172]
### Steps to reproduce
1. Enable Google Authenticator 2FA
2. Enable 2FA reset link (to allow users to login for the first time); note that users are authenticated through LDAP
3. Go to login page
4. Insert **any** (existing) username
5. Leave password field empty
6. Click link 'I need a new QR code. Please send me by email a temporary Identication Code.'

### Expected behaviour
The password of the user should be verified before the 2FA token of the user is reset

### Actual behaviour
The user's 2FA token is reset, i.e. the user's existing 2FA token does not work anymore

The user has temporary OTP in his/her email which he can use but he needs to update 2FA token to get the generated OTP to work again

So any client that can access the login page of TeamPass with 2FA Google Authenticator 2FA enabled with reset link can force users that have already taken 2FA into use to reconfigure 2FA.

I have not tried other supported 2FA implementations so the issue might exist also there.

We can, naturally, just deny the usage of reset link but then every time new user starts to use TeamPass, admin (or manager) needs to send the first OTP for the user when he is about to login.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
PHP 7.2

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Firefox or Chrome

**Operating system:**
Linux

**Comment by roru69** [comment]
I have a similar setup 2(.1.27.11) and I can confirm that you only need your username to get a new 2FA code. The message "An e-mail has been sent to email@address.com... Check your mailbox" appears.

If your 2FA code needs to be reset I agree that a password is needed. Furthermore i don't think that the e-mail address should be (completely) visible. This is another possible vunrebility. 

Regards,

Roru69

**Comment by nilsteampassnet** [comment]
Yes confirmed.
I will provide an improvement for this.

Thank you for reporting

**Comment by nilsteampassnet** [comment]
Reopen on need
