### ISSUE TITLE
LDAP integration not working with Active Directory which also uses O365

### ISSUE THREAD

**Issue by Richigeht** [nilsteampassnet/TeamPass#2173]
### Steps to reproduce
1. Configure LDAP accordingly
2. Test user auth - you will get an auto error.
3.

### Expected behaviour
It should login successfully...

### Actual behaviour
It does not work but that is kind of "Normal", also for other application we had to change the way we are searching LDAP and use sAMAccountName to get it working. 
### Server configuration
**Operating system**: Debian Stretch

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP7.0 with LDAP

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Can you please do those manual changes?

in file `sources/identify.php`, replace
```
                      array('dn', 'mail', 'givenname', 'sn')
```
by
```
                      array('dn', 'mail', 'givenname', 'sn', "samaccountname")
```

and replace
```
                                array('dn')
```
by
```
                                array('dn', 'samaccountname')
```

**Comment by Richigeht** [comment]
Great that works, thanks a lot! 

Maybe you can add a configurable option for this in future? 

Have a nice day!

**Comment by nilsteampassnet** [comment]
Thank you for the feedback.

I don't believe that it is required to add an option as this is just another attribute inside filter.
