### ISSUE TITLE
Problems with the "Help Button"

### ISSUE THREAD

**Issue by UserI404** [nilsteampassnet/TeamPass#2176]
Hello Community,

if i hover over a help button there stands always `"<span style=.....>"` or `"<br>".`
It is the same at a automatic email.
Are there some problems with php extensions?

![br](https://user-images.githubusercontent.com/36761738/38028299-da423af4-3292-11e8-99d4-ceee3bc7cda2.PNG)

Please, can someone help me?
Thanks!!!

**Comment by nilsteampassnet** [comment]
No this is pure translation string issue.
You may participe to improving translations through https://poeditor.com/projects/view?id=16418
I have done some fixes.
