### ISSUE TITLE
Table 'teampass.teampass_restriction_to_roles' doesn't exist

### ISSUE THREAD

**Issue by ajurna** [nilsteampassnet/TeamPass#2178]
### Steps to reproduce
1. Fresh install 2.1.27.11
2. Setup folder user and group
3. give group permissions to folder
4. give user permissions to group
5. try to log in as user and get error.
    Table 'teampass.teampass_restriction_to_roles' doesn't exist2KC7WpeXl5dufP2hmn8f9KlExlBen5P8pOvFUCExzXG3cOc8z5mx6x09+6qkjN4V2Ie5JaeNhjik6t2ogllsIa9INzatqPXJ4ug8rLrU2eckcUfqUo3g8ktp5Yfnxnxl48wHfA1NQUyhpePRz6VA/ldXVEhyIMqDPw==

### Expected behaviour
User should be able to log in and see the empty folder

### Actual behaviour
blank page with error message
    Table 'teampass.teampass_restriction_to_roles' doesn't exist2KC7WpeXl5dufP2hmn8f9KlExlBen5P8pOvFUCExzXG3cOc8z5mx6x09+6qkjN4V2Ie5JaeNhjik6t2ogllsIa9INzatqPXJ4ug8rLrU2eckcUfqUo3g8ktp5Yfnxnxl48wHfA1NQUyhpePRz6VA/ldXVEhyIMqDPw==

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql 5.7

**PHP version:** 7

**Teampass version:** 2.1.27.11

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
```
Query: SELECT i.id_tree, r.item_id FROM teampass_items as i INNER JOIN teampass_restriction_to_roles as r ON (r.item_id=i.id) WHERE r.role_id=1 ORDER BY i.id_tree ASC<br />Error: Table 'teampass.teampass_restriction_to_roles' doesn't exist<br />@ /
```
from the application when logged in as administrator

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by ajurna** [comment]
i just replicated this issue with the docker image. not sure what i'm doing wrong.

**Comment by olibet** [comment]
Same here. I reinstalled TeamPass today and now hae this issue.
A fresh install 2 days ago didn't show this problem.
I followed the exact same steps.

**Comment by olibet** [comment]
I tried from a 'private window' and it worked. Looks like a cache problem...

**Comment by gaglimax** [comment]
I have exactly the same issue.. 3 days ago, it worked and yesterday, after installing Teampass again from scratch, I have this blank page with this error when I log with a user.

**Comment by nilsteampassnet** [comment]
Thank you for complétion the use cases. It helps a lot.
I will investigate and provide a fix

**Comment by ajurna** [comment]
Any ideas to resolve it. I checked the db and the table it's referencing doesn't exist. 
What tag should i use to get a stable install?

**Comment by Nijubi** [comment]
Hi,

I ran into the same issue. Clean install, after creating users, groups and folders - users are not able to login. Found a workaround that lets me login;

Manually create the SQL-Table " _$pre_ _restriction_to_roles " with the following columns:

- **id**: integer | primary key | auto increment
- **role_id** : integer
- **item_id** : integer

Where _'$pre'_ is your own defined prefix for the SQL tables in your teampass database. (by default this is teampass)

I created mine as following;

 `CREATE TABLE 'teampass'.'teampass_restriction_to_roles' ( 'id' INT NOT NULL AUTO_INCREMENT , 'role_id' INT NOT NULL , 'item_id' INT NOT NULL , PRIMARY KEY ('id')) ENGINE = InnoDB;`

Worked for me, hope this works for you too..

**Comment by nilsteampassnet** [comment]
Yes @Nijubi is right, it is a mistake of mine when adding the primary index to this table.
The proposes fix is correct.
I have fixed it too.
