### ISSUE TITLE
Access denied on password items in Firefox, while Chrome works as expected

### ISSUE THREAD

**Issue by daerogami** [nilsteampassnet/TeamPass#2185]
### Steps to reproduce
1. Login to teampass on firefox as a manager with access to passwords

### Expected behaviour
Showing passwords on login
Working in Chrome: 
![tpchrome](https://user-images.githubusercontent.com/2267600/38289694-7c9de976-37a5-11e8-8562-1f7ca2adbcff.png)

### Actual behaviour
Access denied and only the two folders under root display with no password items
Not working in FF (same user as chrome screenshot):
![tpfirefox](https://user-images.githubusercontent.com/2267600/38289700-89d97024-37a5-11e8-9cc1-914e31907e89.png)

### Server configuration
**Operating system:** Azure (Windows)

**Web server:** IIS 10.0

**Database:** MySQL

**PHP version:** 5.6.33

**Teampass version:** 2.1.27

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/1874450/tp.config.zip)

**Updated from an older Teampass or fresh install:** Fresh

### Client configuration
**Browser:** Firefox `59.0.2 (64-bit)`

**Operating system:** Windows 10 - Version 10.0.16299 Build 16299

#### Log from the web-browser developer console (CTRL + SHIFT + i)
No entries in console log and no 401s or 403s

**Comment by nilsteampassnet** [comment]
Can you please install the latest release?

I'm using it every day on those 2 webbrowsers.

**Comment by daerogami** [comment]
@nilsteampassnet I think this was just a case of PEBCAK.
If I had expanded those folders I would have realized everything was there.
