### ISSUE TITLE
Not Login by Ldap in Teampass 2.1.27.11

### ISSUE THREAD

**Issue by dma-vitch** [nilsteampassnet/TeamPass#2186]
Steps to reproduce

    Install TeamPass 2.1.27.11 in Docker
    Configure Ldap OpenLDAP search based
    Setup LDAP User Sync
    Login successfully with LDAP credentials
    Try Login with LDAP credentials
    Fail

Expected behaviour

Users should be able to successfully log in using his LDAP credentials
Actual behaviour

The User gets two error Messages. Either "Login credentials incorrect!" or "Login credentials do not correspond!"
Server configuration

Operating system:

    Centos 7.4 

Database:

    MySQL 5.7.21

PHP version:

    7.1.9

Teampass version:

    2.1.27.11

In attach logs ldap debug
In search filter is not passed  login account
[debug_ldap.txt](https://github.com/nilsteampassnet/TeamPass/files/1875370/debug_ldap.txt)

**Comment by nilsteampassnet** [comment]
What is the tp.config.php file?
Why not to use the bug template (refer to http://teampass.readthedocs.io/en/latest/faq/#how-to-report-a-bug)?

It is not possible that username is not sent.
There mus be errors generated in the server or through the web console (refer to http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console).

**Comment by dma-vitch** [comment]
It's strange after three reinstallations and reconfiguration has worked.
And fresh install worked fine.
Sorry, thanks. In the future I will use the new functionality to generate a template forissue

**Comment by nilsteampassnet** [comment]
Really surprising.

> Sorry, thanks. In the future I will use the new functionality to generate a template forissue
No problem ;)
