### ISSUE TITLE
Admin can login - user cannot login

### ISSUE THREAD

**Issue by Richigeht** [nilsteampassnet/TeamPass#2187]
### Steps to reproduce
1. Fresh installation of Teampass
2. make new users
3. try to login

### Expected behaviour
Tell us what should happen
even with password reset i cannot login successfully.
### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**
apache 2.4
**Database:**

**PHP version:**
5.6
**Teampass version:** 
2.1.27.11
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Have removed the Maintenance mode?

Please refer to http://teampass.readthedocs.io/en/latest/install/setup/#allow-users-to-get-connected

**Comment by Richigeht** [comment]
Hello
Yes I removed the maintenance mode and get with every account besides admin account credentials are wrong still. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by nilsteampassnet** [comment]
Can you please download the latest package https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.11

Overwrite the existing files, and perform upgrade.
I believe you are facing a bug that was corrected a couple of days before.

**Comment by Richigeht** [comment]
Hi
I did overwrite them with cp -av indeed. 
Shall I maybe start install from scratch again?

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by nilsteampassnet** [comment]
Did you run install/upgrade.php after ?

**Comment by Richigeht** [comment]
Yes, Sir. Otherwise I wouldn’t have raised the ticket. 
Sorry I should have pointed that out maybe?

I also have another installation with php7 and no issues. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet
