### ISSUE TITLE
(Google) 2FA Does Not Work With LDAP (Windows / Active Directory)

### ISSUE THREAD

**Issue by jannero** [nilsteampassnet/TeamPass#2189]
### Steps to reproduce
1. Install fresh TeamPass
2. Configure LDAP authentication (we are using Windows / Active Directory for LDAP backend)
3. Configure email server
4. Configure 2FA: enable Google 2FA and allow users to reset his/her 2FA code
5. Open login page
5.1. Write username and correct password
5.2. Click *I need a new QR code. Please send me by email a temporary Identication Code* link

### Expected behaviour
You will receive temporary token so that you can activate 2FA for your account

### Actual behaviour
Error message "Login credentials do not correspond!" is shown to user.

### Other notes
The reset works if you first login as the user before you enable 2FA

For local users 2FA reset link works for the first login.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Teampass version:** 2.1.27.11

**Teampass configuration file:** not relevant

**Updated from an older Teampass or fresh install:** not relevant

### Client configuration
**Browser:** Chrome and Firefox

**Operating system:** Linux

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
Response body for the request generated by clicking the reset 2FA token link:
```
[{"error" : "no_user"}]
```

**Comment by nilsteampassnet** [comment]
Can the user be authenticated without 2FA enabled ?

This authentication configuration was tested with search-posix LDAP.

**Comment by jannero** [comment]
If 2FA is disabled first time login succeeds as I stated above. So yes he can.

**Comment by nilsteampassnet** [comment]
I believe I understood your use case.

In fact it doesn't work if the user has never get logged once inside teampass.
Meaning that no account exists for him in the database.

Yes in this case, this doesn't work and has never worked.

So I need to improve this.

**Comment by nilsteampassnet** [comment]
I have fixed this case.
Commit will be done in `development` branch and part of 2.1.27.12

Please reopen on need
