### ISSUE TITLE
slow login/authentication page

### ISSUE THREAD

**Issue by elkekou** [nilsteampassnet/TeamPass#2190]
### Steps to reproduce
1. Enter valid credential of user (ldap) and wait long time to login
2. Enter valid credential of super admin and never work
3.

### Expected behaviour
Login quickly like in previous version 2.1.27.10

### Actual behaviour
Since upgrade to 2.1.27.11, login sometimes really long sometimes does not work.

Checked my ldap log, and teampass seems to waiting very long time (near a minute) before sending auth request to ldap.
In setting interface (ldap tab) when i make ldap test response is immediate.
So problem seems to be before teampass try authentication function.

### Server configuration
**Operating system**: Centos 7.4

**Web server:** httpd 2.4.6-67

**Database:** mariadb

**PHP version:** php7.0.27-1.ius.centos7

**Teampass version:** Latest pre-relase (2018/0/06) 2.1.27.11

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** firefox / chromium

**Operating system:** cnetos 7

#### Web server error log
nothing except this strange line (which does not seems to be linked to problem ) :
 PHP Notice:  Undefined index: pwComplexity in /var/www/html/teampass/index.php on line 881

**Comment by elkekou** [comment]
Only "email user when user password is changed" was enabled, but i disabled it and no change.

The mail setup is working (tested with teampass feature "send yourself ...").
really does not understand what happen.

**Comment by nilsteampassnet** [comment]
Can you please use the developer tools from your browser to identify what are the network queries that are too longs?

**Comment by elkekou** [comment]
Hi,

in fact my problem was link to the fact that my computer have no internet
access.
In the source code of teampass i found a line which make a request to guess
which country i come but without internet access i have to wait for
timeout. So i comment out this line and my teampass work like a charm.

For now i'm not at work so i cannot be more precise about which line in
which file i comment out.


Lionel.

Le jeu. 15 nov. 2018 à 20:10, Nils Laumaillé <notifications@github.com> a
écrit :

**Comment by nilsteampassnet** [comment]
Yes this issue was fixed in 2.1.27.27.

Please upgrade the latest.
