### ISSUE TITLE
Problem with administrator accousnt password

### ISSUE THREAD

**Issue by AdamFrosta** [nilsteampassnet/TeamPass#2191]
Hello,

We are trying to reset the password for our administrator account in Teampass, while we are recieving the email with the directions for reset, pressing send me the password button on the page does nothing. We have tried this several times, whit no result.

Thank you

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
You have received a 2d email with the subject `[TeamPass] Your password step 2`.
This one contains your new password.

**Comment by AdamFrosta** [comment]
Hello,

The problem is we have not recieved the 2nd mail. We have cheked the 
filters and firewalls and nada. Besides, we did recieve the 1st email so 
this shloud be configured correctly.

Thanks
Adam Czarnecki
IT Specialist

FRoSTA sp. z o.o.
ul. Witebska 63
85-778 Bydgoszcz
tel.: +48 52 3606797 
faxmail: +48 52 5670876
fax: +48 52 567 08 02
mobile: +48 506125874 
www.frosta.pl

FRoSTA sp. z o.o., ul. Witebska 63, 85-778 Bydgoszcz; NIP 113-20-55-642, 
Sąd Rejonowy w Bydgoszczy, XIII Wydział Gospodarczy KRS 0000060990
Kapitał zakładowy (wpłacony w całości): 35 000 000 zł

Niniejsza wiadomość może zawierać informacje poufne. Jeżeli nie są Państwo 
upoważnieni do otrzymania tej informacji bardzo prosimy o natychmiastowy 
kontakt z nadawcą zwrotną pocztą elektroniczną oraz o usunięcie tej 
wiadomości bez wcześniejszego skopiowania. Wszelkie formy 
nieautoryzowanego wykorzystania, publikacji, reprodukcji, powielenia czy 
udostępnienia niniejszej wiadomości są zabronione. 
This message may contain confidential information. If you are not 
authorized to receive this information please advise the sender 
immediately by reply e-mail and delete this message without making any 
copies. Any form of unauthorized use, publication, reproduction, copying 
or disclosure of the e-mail is not permitted. 




Od:     Nils Laumaillé <notifications@github.com>
Do:     nilsteampassnet/TeamPass <TeamPass@noreply.github.com>, 
DW:     AdamFrosta <adam.czarnecki@frosta.pl>, Author 
<author@noreply.github.com>
Data:   2018-04-10 20:31
Temat:  Re: [nilsteampassnet/TeamPass] Problem with administrator accousnt 
password (#2191)



You have received a 2d email with the subject [TeamPass] Your password 
step 2.
This one contains your new password.

**Comment by nilsteampassnet** [comment]
As the request form is not filled in, I can't make any assumptions on your context.
I did test and it works and is improved with the commit attached to this ticket.
My proposal is that you update once 2.1.27.12 will be released.
