### ISSUE TITLE
Global Search shows "n Results found", but they're not displayed in the resultlist

### ISSUE THREAD

**Issue by fedoraflo** [nilsteampassnet/TeamPass#2195]
### Steps to reproduce
1. Klick on the search button
2. Search for a string e.g. "Administrator"

### Expected behaviour
Display the found results

### Actual behaviour
Search is proceeded and the status table says "n results found", but they're (search results) not shown in the result list.

### Server configuration
**Operating system**: Ubuntu Server 16.04 LTS - latest Updates installed
**Web server:** Server version: Apache/2.4.18 (Ubuntu), Server built: 2017-09-18T15:09:02
**Database:** mySQL 5.7.20-0ubuntu0.16.04.1
**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
**Teampass version:** 2.1.27
**Teampass configuration file:** n/a

### Client configuration
**Browser:** Google Chrome Version 65.0.3325.181 (Offizieller Build) (64-Bit)
**Operating system:** Windows 7 x64

#### Web server error log
No errors occurred.

#### Log from the web-browser developer console (CTRL + SHIFT + i)
No errors occurred.

**Comment by nilsteampassnet** [comment]
In what page do you initiate the search?

Can you provide the results form the query using this tip => http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by nilsteampassnet** [comment]
Please reopen on need.
