### ISSUE TITLE
API create item fails when Base64 encoding contains "/"

### ISSUE THREAD

**Issue by MariusPad** [nilsteampassnet/TeamPass#2196]
Using the https://teampass.readthedocs.io/en/latest/api/api-write/ add item guide, there is an issue when the base64 encoding contains "/"
### Steps to reproduce
1. Generate a new password (outside TeamPass env)
2. Encode using -base64 the following: label;password;description;folder id;login;email;url;tags;any one can modify"
3. Call TeamPass <teampass_url>/api/index.php/add/item/<base64_string>?apikey=<valid_api_key>"

### Expected behaviour
Item should be created

### Actual behaviour
IF base64 encoding contains "/" character, the API call fails with {"err":"Item definition not complete"} error. I suppose the TeamPass server interprets the "/" as URL delimiter

### Server configuration
**Operating system**:
Local API client and TeamPass are Ubuntu
**Web server:**
Apache/2.4.7 
**Database:**
mysql  Ver 14.14 Distrib 5.5.59
**PHP version:**
php5.5.9-1ubuntu4.24
**Teampass version:** 
TeamPass 2.1.27.11  

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26

### Client configuration
curl -k "https://<teampass_url>/api/index.php/add/item/<base64_string>?apikey=<valid_api_key>"

### Question
Is there any possibility to overcome (by using URL and filename safe calls, replace "/" with other character) or we should take care of generating "/" free base64 hashes?

Thanks

**Comment by nilsteampassnet** [comment]
I should add this detail in the documentation.
Indeed, your base64 encoded string should not contain any slash (/).

Substitution characters:

* **` + `** should be converted to **` - `**
* **` / `** should be converted to **` _ `**

I will provide an evolution also of the API.

**Comment by MariusPad** [comment]
Many thanks Nils. So, in a future release, TeamPass will support character substitution as above?

**Comment by nilsteampassnet** [comment]
This means that the improvment has been included in the code committed in
development branch.

So it can already be used if you take the api file out of it and paste it
on your Teampass instance.

----
*Nils @ teampass.net <http://teampass.net>*
*Teampass *- *A collaborative passwords manager*
Visit Teampass.net
Any bug? Please report in Github repository
<https://github.com/nilsteampassnet/TeamPass>
Any feature request? Propose and vote at userEcho
<http://teampass.userecho.com>​
Support? please post at Reddit <https://www.reddit.com/r/TeamPass/>​
Need help? Read the Doc <http://teampass.readthedocs.io/en/latest/>



2018-04-11 10:42 GMT+02:00 MariusPad <notifications@github.com>:
