### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by g3l0l4** [nilsteampassnet/TeamPass#2200]
### Steps to reproduce
1. Log into Teampass via Active Directory
2. Select a folder with many elements
3. "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" alert is thrown

### Expected behaviour
Teampass should show me elements in the folder.

### Actual behaviour
An alert with an error message is thrown: 

![imagen](https://user-images.githubusercontent.com/17069911/38662462-a852af58-3e34-11e8-9a5e-b66c74dfe96e.png)

### Server configuration
**Operating system**:
Suse Linux
**Web server:**
Apache 2.4.27
**Database:**
MySQL 5.5.25 (in other server)
**PHP version:**
PHP 7.1.8
**Teampass version:** 
Teampass 2.1.27.11
**Teampass configuration file:**
global $lang, $txt, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "myServer";
$user = "myUser";
$pass = "myPassword";
$database = "teampass";
$port = 3306;
$pre = "teampass_";
$encoding = "";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/routeTo/Teampass/keys');
if (file_exists("/routeTo/Teampass/keys/sk.php")) {
    require_once "/routeTo/Teampass/keys/sk.php";
}
@define('COST', '13'); // Don't change this.                                         

**Updated from an older Teampass or fresh install:**
Updated from another version of Teampass.
### Client configuration
**Browser:**
Mozilla Firefox
**Operating system:**
Windows 10
#### Web server error log
```
[ssl:warn] [pid 5218] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[mpm_prefork:notice] [pid 5218] AH00163: Apache/2.4.27 (Unix) OpenSSL/1.0.2j-fips configured -- resuming normal operations
[core:notice] [pid 5218] AH00094: Command line: '/routeTo/Apache24/bin/httpd -f /routeTo/Apache24/conf/httpd.conf'
[ssl:warn] [pid 10302] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[mpm_prefork:notice] [pid 10302] AH00163: Apache/2.4.27 (Unix) OpenSSL/1.0.2j-fips configured -- resuming normal operations
 [core:notice] [pid 10302] AH00094: Command line: '/routeTo/Apache24/bin/httpd -f /routeTo/Apache24/conf/httpd.conf'
[ssl:warn] [pid 13785] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[mpm_prefork:notice] [pid 13785] AH00163: Apache/2.4.27 (Unix) OpenSSL/1.0.2j-fips configured -- resuming normal operations
[core:notice] [pid 13785] AH00094: Command line: '/routeTo/Apache24/bin/httpd -f /routeTo/Apache24/conf/httpd.conf'
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
fWzQWq2tra0=
```
Thrown in jquery.js
Route in network tab -->
http://routeToTeampass/sources/items.queries.php
```

**Comment by nilsteampassnet** [comment]
Please provide the error by following http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by g3l0l4** [comment]
We have solved this issue, the problem was that we had strange characters in our elements data. The characters that throws error are characters like Ç· and characters with tilde.
Thank you.
