### ISSUE TITLE
Google 2FA in combination with Active directory doesn't work

### ISSUE THREAD

**Issue by roru69** [nilsteampassnet/TeamPass#2203]
### Steps to reproduce
1. Install fresh Teampass (developement 12-04-2018)
2. Log in as administrator (OK)
3. Configure and test LDAP connectivity (OK)
4. Configure SMTP (OK)
5. Enable Google 2FA (OK)
6. Disable Maintenance mode (OK)
7. Log in as Active directory user and click on the link: I need a new QR code. Please send me by email a
    temporary Identication Code. -> A message appears that the email has been sent. (OK)
8. Open mail and copy/paste temporary 2FA code into the teampass loginscreen. (OK)
9. press OK and the QR code is shown -> import this into the Google Authenticator app (OK)
10. Use the Google Authenticator app to generate 2FA code and insert this into the 2FA field in
     Teampass.
11. Press "enter" on the loginscreen -> 2FA code is wrong (Not OK)
12. Log in as Admin
13. Goto the user management page and find the user that was created and couldn't login.
13. Click on the button "Email Google Authentication to user" -> Shows error: "User not found"

### Expected behaviour
User should be able to log in because he has a valid 2FA code.

### Actual behaviour
Gets a message that the Google Authenticator code is wrong.

### Server configuration
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3 (2017-12-13)

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Mar 31 2018 09:39:03
Server's Module Magic Number: 20120211:37
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

**Database:**
MySQL versie: 5.5.5-10.0.32-MariaDB-0+deb8u1

**PHP version:**
7.0x
**Teampass version:** 
2.1.27.12 - 12-4-2018
**Teampass configuration file:**

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows Server 2012R2 

#### Web server error log
```
[Thu Apr 12 11:21:32.158040 2018] [:error] [pid 26241] [client 192.168.28.5:61422] PHP Notice:  Undefined index: pwComplexity in /var/www/mydomain.com/public_html/teampass/index.php on line 912, referer: https://www.mydomain.com/teampass/index.php
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

```
Insert the log here and especially the answer of the query that failed.


```

**Comment by nilsteampassnet** [comment]
Hello @roru69 

I could not reproduce the issue you have regarding the user issue with 2FA code.
If I follow steps from 1 to 13, I have no problem.

At step 14, you are right, a test performed here was wrong and did the fix for it.

**Comment by roru69** [comment]
I will do a "new" clean install and test again with the latest developement version. Will report back today!

**Comment by nilsteampassnet** [comment]
Please reopen on need.

**Comment by roru69** [comment]
Keep it closed. Found wat was wrong. Time on the server was off by 1.30 minutes. That is why i couldn't get a correct 2FA code. Problem solved!
