### ISSUE TITLE
Password copy - cryptic log entry using syslog

### ISSUE THREAD

**Issue by Guirlande** [nilsteampassnet/TeamPass#2204]
### Steps to reproduce
1. Copy the password of an item through any mean with syslog enabled

### Expected behaviour
Upon clicking the copy button dedicated to the password field (lock in item list or canvas on the left of the eye hiding the password), a comprehensive log entry should be generated.
E.g : 

```
Apr 12 11:26:53 teampass: action=copy attribute=pw itemno=7 user=MyUser itemname="My Item Title"
```

SQL talking, the teampass_items.label field should be present in the message for easier identification.

### Actual behaviour
The generated log only specifies the item ID, thus requiring an SQL request to know specifically which item was accessed. It renders the use of syslog to centralize the logs harder (integration with ElasticSearch would lose a lot of interest).

### Server configuration
**Operating system**:
RedHat 7.4 (Maipo)

**Web server:**
httpd-2.4.25-9

**Database:**
mariadb-5.5.56-2

**PHP version:**
php-5.5.21-5

**Teampass version:** 
2.1.27.11 (cloned from repo on 27th of March)

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1902217/tp.config.txt)

### Client configuration
**Browser:**
Google Chrome 65

**Operating system:**
Windows 10

### Web Server Log
```
[... RELEVANT ENTRY ONLY ...]
[12/Apr/2018:11:27:04 +0200] "POST /sources/items.logs.php HTTP/1.1" 200 - "https://teampass-tst.example.org/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

```

**Comment by Guirlande** [comment]
Label is added in pull request : https://github.com/nilsteampassnet/TeamPass/pull/2199
I still think the message might be refactored to be easily handled by log analysis softwares.

**Comment by nilsteampassnet** [comment]
Please reopen on need.
