### ISSUE TITLE
PHP mod mcrypt was removed with php 7.2

### ISSUE THREAD

**Issue by keros** [nilsteampassnet/TeamPass#2205]
### Steps to reproduce
Tested on Ubuntu 18.04 (beta)
Install Apache with php 7.2 (default on this release)
php-mcrypt is no longer available (was deprecated with php 7.1).
try to install teampass -> Server checks -> PHP extension "mcrypt" is loaded   Extension mcrypt is not loaded!

### Expected behaviour
Teampass should not need mcrypt on php 7.2

### Actual behaviour
try to install teampass -> Server checks -> PHP extension "mcrypt" is loaded   Extension mcrypt is not loaded!

### Server configuration
Ubuntu 18.04 (beta)
apache 2.4.29
mysql 5.7.21
PHP 7.2.3
git master (2.1.27)

**Comment by keros** [comment]
My current workaround (install mcrypt for 7.2 over pecl):
apt install libmcrypt-dev libreadline-dev php-dev
pecl install mcrypt-1.0.1
Add "extension=mcrypt.so" to php.ini

But please don't use this as a general solution, we need a fix for the deprecated/removed module ;)

**Comment by nilsteampassnet** [comment]
This work is already in work in development branch

Thank you

**Comment by nssiddique** [comment]
Does Teampass works on CentOS 8? I can't pass server check step.
Thanks
