### ISSUE TITLE
New ldap user and ad password change

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#2206]
Hello Nils,

When I add a user within the ldap group in my AD, the user won’t be log on automaticly. 

Thereby, when a user changes his password then he has to log on with his old password. Is there a solution for these two problems?

**Comment by nilsteampassnet** [comment]
I need to check this.
But a fix will be provided in 2.1.27.12.
Thanks

**Comment by nilsteampassnet** [comment]
Committed in development branch
