### ISSUE TITLE
delete personal folder - backup solution not complete working

### ISSUE THREAD

**Issue by nexosone** [nilsteampassnet/TeamPass#2212]
Hi Nils,

we need your support. One of our colleagues had deleted their personal folder. As known the complete folder structure is broken and not visible. Therefore we don't have acces to our password.

Teampass Version: 2.1.26 and Mysql (no bin log enabled)
In the webserver errorlog are no errors visible.

I've looked into the database and i've seen the items are still present, but there is only one folder in the nested.tree table visible. I tried to restore the table from an older backup (some folders could be missing). After this restore we can see the old folder (without the missing ones, but is ok) but they are empty. After this i looked into the items table again and saw the column inactif which were set to 1 for all items. I assumed it were not active and changed it to 0 . Now all passwords were listed in the folders.
After this we get the error message for all items:

![image](https://user-images.githubusercontent.com/16033030/38877842-d8b969d2-425f-11e8-8302-44ca96422715.png)

After this steps we take we have now no clue how we can fix our teampass, please help.

Thanks in advance!
 
Could this be in relation with our error? We don't know if the error was before.

![image](https://user-images.githubusercontent.com/16033030/38878015-453c335a-4260-11e8-8162-b4b81c8a1dbe.png)

**Comment by nilsteampassnet** [comment]
You can skype me @ nils.teampass

Or email me nils@teampass.net
