### ISSUE TITLE
Teampass installation - mcrypt not loaded error

### ISSUE THREAD

**Issue by vpulacode** [nilsteampassnet/TeamPass#2214]
### Steps to reproduce
1. Go to http://localhost/_teampass folder_/install/install.php
2. Click on "Launch" button in the Server Checks wizard step

### Expected behaviour
The elements should all show a green tick mark

### Actual behaviour
Tell us what happens instead
•PHP extension "mcrypt" is loaded   Extension mcrypt is not loaded! error

### Server configuration
Windows 2008

**Web server:** 
Apache 2.4.33
**Database:**
MySQL 5.7.21
**PHP version:**
7.2.4
**Teampass version:** 
2.1.27
**Teampass configuration [file:**]
[](url)
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
IE
**Operating system:**
Windows 2008
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
you are using php 7.2.4 for whic mcrypt is deprecated.
you must use development branch ... yet no release is done for this advanced version.
do you use 2.1.27.11?

**Comment by vpulacode** [comment]
Used the master... As you recommended, should I use the dev branch, instead? Also, which Php version do you recommend?

**Comment by nilsteampassnet** [comment]
REopen on need
