### ISSUE TITLE
rdp file with object parameters

### ISSUE THREAD

**Issue by maiconstedille** [nilsteampassnet/TeamPass#2217]
A feature suggestion:
Based on the connection parameters such as url, username and password, would it be possible to create an option to generate an rpd file with these parameters?
When defining in the url as rpd:// or mstsc:// when the user clicks on the link, the rdp file is downloaded with the parameters defined in the object, with IP and port in the URL, username and password in the above fields.

**Comment by nilsteampassnet** [comment]
can you share a rdp file for example?

interesting idea ;)

**Comment by maiconstedille** [comment]
[example_rdp.txt](https://github.com/nilsteampassnet/TeamPass/files/1924974/example_rdp.txt)

an attached rdp file is attached. I had to rename its extension to txt so I could attach it here, but just change it to .rdp and it will work. I could not get it to save the password in the file, so I do not think it's possible to send the password in the parameters. But the IP address and user, would already help a lot.
