### ISSUE TITLE
500 Error after intall

### ISSUE THREAD

**Issue by nicholasashley** [nilsteampassnet/TeamPass#2223]
### Steps to reproduce
1. Install the software on centos 7 php 5.6
2.
3.

### Expected behaviour
Should see the login screen

### Actual behaviour
500 Error

[Mon Apr 23 07:30:44.406739 2018] [:error] [pid 11538] [client 62.252.8.234:63868] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /home/vault/public_html/sources/main.functions.php on line 2226

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Apache 2.4

**Database:**
Maria DB

**PHP version:**
5.6

**Teampass version:** 
Latest (Cant see the version)

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by lachmex** [comment]
same problem here...
[Mon Apr 23 11:35:52 2018] [error] [client 10.12.6.192] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /disk/syspass_test/sources/main.functions.php on line 2226

**Comment by thiyagu114** [comment]
Same problem here too!

**Error Log**
[:error] [pid 32667] [client 10.47.120.67:53070] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/html/teampass/sources/main.functions.php on line 2226

**HTTPD Version**
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16

**PHP Version**
PHP 5.6.35 (cli) (built: Mar 30 2018 08:28:49)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by 80kk** [comment]
Also on Slackware 14.2: 

**Error Log:**
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/htdocs/teampass/sources/main.functions.php on line 2226

**HTTPD Version:**
Server version: Apache/2.4.29 (Unix)
Server built:   Oct 25 2017 11:48:56

**PHP Version:**
PHP 5.6.35 (cli) (built: Mar 29 2018 21:45:41) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by nilsteampassnet** [comment]
Indeed Teampass is developed and tested using PHP version 7.0.23, 7.1.9 and 7.2.2.
I removed version 5.6 but I should not have.
This error is related to php 5.6 which only accepts null value in this case.

I will provide the fix.

Reopen on need
