### ISSUE TITLE
Generate Password without option = error message

### ISSUE THREAD

**Issue by go2this** [nilsteampassnet/TeamPass#2224]
### Steps to reproduce
1. Add item

2. Deselect all password options
![2018-04-23 12_35_50-teampass](https://user-images.githubusercontent.com/34249133/39121898-61a302fc-46f3-11e8-957b-fedb0fdbf0d3.jpg)

3. Press Generate
![2018-04-23 12_36_20-teampass](https://user-images.githubusercontent.com/34249133/39121904-67a9ef44-46f3-11e8-988e-513b15beaff8.jpg)

### Server configuration
**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** MariaDB

**PHP version:** 7.1.16-1

**Teampass version:** 2.1.27.12

**Teampass configuration file:** 
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1937755/tp.config.txt)

**Updated from an older Teampass or fresh install:** upgrade

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7 Prof. x64

**Comment by nilsteampassnet** [comment]
I cannot reproduce.

Can you please provide me the server answer by following instructions => http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

Thanks

**Comment by go2this** [comment]
![2018-05-01 12_32_09-teampass](https://user-images.githubusercontent.com/34249133/39470084-fdec5c3c-4d3b-11e8-8efa-4f1519346d1e.jpg)

![2018-05-01 12_33_01-teampass](https://user-images.githubusercontent.com/34249133/39470091-0523db1a-4d3c-11e8-8a8d-f38f40e39c0d.jpg)

**Comment by janjanson84** [comment]
I have the same issue. Password generation does not work at all. Apache Log schows the following error:

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Expected positive integer' in /var/www/html/teampass/includes/libraries/PasswordGenerator/Generator/ComputerPasswordGenerator.php:128\nStack trace:\n#0 /var/www/html/teampass/sources/main.queries.php(1007): PasswordGenerator\\Generator\\ComputerPasswordGenerator->setLength(0)\n#1 /var/www/html/teampass/sources/main.queries.php(53): mainQuery()\n#2 {main}\n  thrown in /var/www/html/teampass/includes/libraries/PasswordGenerator/Generator/ComputerPasswordGenerator.php on line 128
