### ISSUE TITLE
how the Backup & restore  in work in case of it server crashed 

### ISSUE THREAD

**Issue by Nathu2018** [nilsteampassnet/TeamPass#2225]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
You should backup:

* database --> daily
* file `teampass-seckey.txt` --> once (or if changed)
* file `sk.php` --> once
* file `includes\libraries\csrfp\libs\csrfp.config.php` --> once
* folder `upload` --> daily
