### ISSUE TITLE
Does this Application support 2FA using RSA 

### ISSUE THREAD

**Issue by Nathu2018** [nilsteampassnet/TeamPass#2226]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Do you mean 2FA using SecurID?

Currently Teampass handles Google 2FA, AGSES , DUO Security and Yubico keys.

You could participate to to https://teampass.userecho.com/communities/1/topics/22-support-for-saml-authentication
