### ISSUE TITLE
Upgrade from 2.1.27.10 -> 2.1.27.12

### ISSUE THREAD

**Issue by xcorella** [nilsteampassnet/TeamPass#2232]
I try upgrade teampass from 2.1.27.10 to last 2.1.27.12. But update failed.

### Steps to reproduce
1. Download last 2.1.27.12
2. Extract
3. Run ugprage

### Expected behaviour
Upgrade teampass

### Actual behaviour
Stuck in upgrade process on step 4 in script "upgrade_run_defuse_for_pwds.php - Loop #1 is now running"

### Server configuration
Operating system:
Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-6-amd64
Web server:
Apache/2.4.25 (Debian)
Database:
Ver 15.1 Distrib 10.1.26-MariaDB
PHP version:
PHP 7.0.27-0+deb9u1
Teampass version:
2.1.27.10
Teampass configuration file:
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1951065/tp.config.php.txt)
Updated from an older Teampass or fresh install:
upgrade from 2.1.27.10

### Client configuration
Browser:
Google Chrome 65, Firefox 59, 64bit
Operating system:
Windows 10 Enterprise 1709
#### Web server error log
Browser:
Google Chrome 65, Firefox 59, 64bit
Operating system:
Windows 10 Enterprise 1709

Insert your webserver log here
Thu Apr 26 11:50:36.449938 2018] [:error] [pid 112258] [client 94.112.242.230:53358] PHP Fatal error:  Uncaught Error: Class 'Defuse\\Crypto\\Key' not found in /var/www/teampass/sources/main.functions.php:386\nStack trace:\n#0 /var/www/teampass/sources/main.functions.php(499): cryption('def50200b4cd70f...', 'def000003691483...', 'decrypt')\n#1 /var/www/teampass/install/upgrade_run_defuse_for_pwds.php(41): defuse_return_decrypted('def50200b4cd70f...')\n#2 {main}\n  thrown in /var/www/teampass/sources/main.functions.php on line 386, referer: https://teampass.602.cz/install/upgrade.php

**Comment by maiconstedille** [comment]
Same problem. Difference is just that the operating system is CentOS 7

**Comment by manusfreedom** [comment]
I got the same error, I fixed the upgrade by comment following line in sources/main.functions.php (363-367):
```
    // load PhpEncryption library
//    if (isset($SETTINGS['cpassman_dir']) === false || empty($SETTINGS['cpassman_dir']) === true) {
        $path = '../includes/libraries/Encryption/Encryption/';
//    } else {
//        $path = $SETTINGS['cpassman_dir'].'/includes/libraries/Encryption/Encryption/';
//    }
```
Uncomment them after upgrade.

**Comment by xcorella** [comment]
Any progress in this bug?

**Comment by nilsteampassnet** [comment]
No unfortunately as I cannot reproduce and understand why this is thrown.
I believe it is related to data existing inside the database.
So without this specific environment, it is mostly impossible to reproduce on my servers.

**Comment by manusfreedom** [comment]
So after some update, this problem (for me) was from a change of the website url (from .local to a .com) and change the root directory.
To fix you need to modifiy all impacted config in table (teampass_misc) of database and config files (includes/config/settings.php, includes/config/tp.config.php, includes/libraries/csrfp/libs/csrfp.config.php).

**Comment by borzel** [comment]
Solved it by creating a smybolic link from `/var/www/html/teampass` to `/var/www/html`

**Comment by borzel** [comment]
After the successfull upgrade I checked my settings. The paths in the database were wrong... :-/

My co-worker moved the installation without changeing the paths in the Teampass settings.
