### ISSUE TITLE
No users to manage when using LDAP/AD

### ISSUE THREAD

**Issue by AlfWa** [nilsteampassnet/TeamPass#2233]
I configured a newly installed version 2.1.27.12 on a fully patched CentOS7 server with PHP5.5 from webtatic with Active Directory. I followed to installation and configuration steps and I can login with my AD account but as admin, I don't see any users to manage or to add to groups.

Am I missing something or is there a real bug here?

Many thanks, Alf.

**Comment by nilsteampassnet** [comment]
It is normal.
The users will be created when they will connect the first time to Teampass.

Reopen on need
