### ISSUE TITLE
Can't upload files.

### ISSUE THREAD

**Issue by 80kk** [nilsteampassnet/TeamPass#2235]
Each time when I am trying to upload file, I am getting error in Apache log:

[Mon Apr 30 11:48:34.956608 2018] [ssl:info] [pid 1974] (70007)The timeout specified has expired: [client 10.70.1.113:55180] AH01991: SSL input filter read failed.

Everything else is working fine.
 
### Steps to reproduce
1. Login as user
2. Click on password
3. Select file  to upload and try to upload it.

### Expected behaviour
It should upload the file and show it on the list.

### Actual behaviour
It won't upload file, it shows progress bar for the very short period of time instead.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.56

**PHP version:** 7.0.30

**Teampass version:** 2.1.27.12

**Teampass configuration file:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '5',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://teampass.domain.net',
    'favicon' => 'https://teampass.domain.net/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'url_to_upload_folder' => 'https://teampass.domain.net/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://teampass.domain.net/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1522153561',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '25mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip,bz2,gz,gzip',
    'upload_otherext' => 'sql,xml,json,conf,rb,yml,yaml,sh,cnf',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '1024',
    'upload_imageresize_height' => '768',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/London',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '70',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',

**Updated from an older Teampass or fresh install:** No
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Any

**Operating system:** Any

#### Web server error log
```
[Mon Apr 30 11:48:34.956608 2018] [ssl:info] [pid 1974] (70007)The timeout specified has expired: [client 10.70.1.113:55180] AH01991: SSL input filter read failed.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
```

**Comment by nilsteampassnet** [comment]
Seems to be a server issue related to SSL parameter.
You should ensure that all parameters regarding https on your server are correctly set.

Perhaps some other users can help in such configuration?
