### ISSUE TITLE
Version 2.1.27 LDAP User passwords being recorded in logging 

### ISSUE THREAD

**Issue by DaveP97** [nilsteampassnet/TeamPass#2238]
### Steps to reproduce
1.Any user Logs in 
2.Look logs /var/www/html/teampass/includes/libraries/csrfp/log/*.log
3.Inside User's log in passwords are shown, included when LDAP is enabled

### Expected behaviour
Password should be either encrypted or not shown

### Actual behaviour
user's passwords are showing up 

### Server configuration
**Operating system**:
Ubuntu 16.04.4 LTS
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
 7.1.16
**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox/Chrome/Safari/IE/etc
**Operating system:**
All
### Logs
{"login":"admin","pw":Passwordhere","duree_session":"60", 

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
Is there a way you can censor this? as this issue gives the Teampass server admin access to everyone's domain passwords. Is a massive security flaw and will no allow us to actually sue the platform.

Current csrfp.config.php
`<?php
/**
 * Configuration file for CSRF Protector z
 */

return array(
    "CSRFP_TOKEN" => "362471cb5b8b093c457360599308c58f2ab07c01d3b8c38ca2",
    "logDirectory" => "../log",
    "failedAuthAction" => array(
        "GET" => 1,
        "POST" => 1),
    "errorRedirectionPage" => "",
    "customErrorMessage" => "",
    "jsPath" => "../js/csrfprotector.js",
    "jsUrl" => "http://mydomain.com/teampass/includes/libraries/csrfp/js/csrfprotector.js",
    "tokenLength" => 50,
    "disabledJavascriptMessage" => "This site attempts to protect users against <a href=\"https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29\">
   Cross-Site Request Forgeries </a> attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work correctly for you.
    See details of your web browser for how to enable JavaScript.",
    "verifyGetFor" => array("*type=duo_check*", "*upload.attachments.php*", "*upload.files.php*", "*type=ga_generate_qr*")
);

`

**Comment by nilsteampassnet** [comment]
Thank you for reporting this.
I didn't noticed it before.
As a quick fix, you can open file `var/www/html/teampass/includes/libraries/csrfp/csrfp.csrfprotector.php` and remove the next block of code.
```
            if (self::$requestType === "GET") {
                            $log['query'] = $_GET;
            } else {
                            $log['query'] = $_POST;
            }
```

I will commit this change today, and will investigate deeper after.

**Comment by nilsteampassnet** [comment]
Please reopen on need.
