### ISSUE TITLE
[2.1.27.12] After update the is n Users in Manage Users

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2239]
### Steps to reproduce
1. Log as Admin user
2. Open Manage Users

### Expected behaviour
Lits all Users

### Actual behaviour
No users inside
![error](https://user-images.githubusercontent.com/4628571/39486196-fc9c466a-4d83-11e8-9f5b-ef7920aa6698.jpg)

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.23 (cli) (built: Feb 8 2018 21:59:47)
**Teampass version:** 
2.1.27.11

### Client configuration
**Browser:**
IE, FF, EDGE
**Operating system:**
Windows 10 ENT 1709
#### Web server error log
```
[Tue May 01 21:03:35.046871 2018] [:error] [pid 44382] [client 192.168.10.5:64343] PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/html/teampass/users.php on ine 75 and defined in /var/www/html/teampass/sources/main.functions.php on line 2230, referer: https://<URL>/index.php?page=manage_folders
[Tue May 01 21:03:38.784852 2018] [:error] [pid 44383] [client 192.168.10.5:64344] PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/html/teampass/users.php on line 75 and defined in /var/www/html/teampass/sources/main.functions.php on line 2230, referer: https://<URL>/index.php?page=manage_users
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
```
Manage Roles:
![error1](https://user-images.githubusercontent.com/4628571/39486485-00cbe55a-4d85-11e8-9ba3-46eae0535acd.jpg)
Manage Users:
![error2](https://user-images.githubusercontent.com/4628571/39486490-05ada1b2-4d85-11e8-9218-926e96c9b867.jpg)

**Comment by nilsteampassnet** [comment]
This issue is related to php 5.x.

Quick fix, in /sources/main.functions.php, 
replace
`function cleanText(string $string, string $type = null)`
by
`function cleanText($string, $type = null)`

**Comment by reginfo** [comment]
Thanks, 

It did the trick.
