### ISSUE TITLE
While updating 2.1.27.7 -> .12: ERROR: An error appears when adding increment_id user_ip to table misc! Incorrect table definition; there can be only one auto column and it must be defined as a key!

### ISSUE THREAD

**Issue by sandman42** [nilsteampassnet/TeamPass#2241]
### Steps to reproduce
1. Upgrade from 2.1.27.7 to 2.1.27.12
2. Go to http://YOUR_IP/teampass/install/upgrade.php
3. At step 4 when I click on launch I have "ERROR: An error appears when adding increment_id user_ip to table misc! Incorrect table definition; there can be only one auto column and it must be defined as a key!"

### Expected behaviour
It should continue

### Actual behaviour
I get an error "ERROR: An error appears when adding increment_id user_ip to table misc! Incorrect table definition; there can be only one auto column and it must be defined as a key!"

### Server configuration
**Operating system**:
Debian linux jessie
**Web server:**
Apache 2.4.10-10
**Database:**
5.5.60-0+deb8u1
**PHP version:**
5.6.33-0+deb8u1
**Teampass version:** 
2.1.27.12
**Teampass configuration file:**
settings.php:

<?php
global $lang, $txt, $k, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "localhost";
$user = "teampass_root";
$pass = "REMOVED";
$database = "teampass";
$port = 3306;
$pre = "teampass_";
$encoding = "utf8";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/var/www/html/teampass/includes');
if (file_exists("/var/www/html/teampass/includes/sk.php")) {
    require_once "/var/www/html/teampass/includes/sk.php";
}
@define('COST', '13'); // Don't change this.

tp.config.php:

<?php
    global $SETTINGS;
    $SETTINGS = array (
        'max_latest_items' => '10',
        'enable_favourites' => '1',
        'show_last_items' => '1',
        'enable_pf_feature' => '0',
        'log_connections' => '1',
        'log_accessed' => '1',
        'time_format' => 'H:i:s',
        'date_format' => 'd/m/Y',
        'duplicate_folder' => '0',
        'item_duplicate_in_same_folder' => '0',
        'duplicate_item' => '0',
        'number_of_used_pw' => '3',
        'manager_edit' => '1',
        'cpassman_dir' => '/var/www/html/teampass',
        'cpassman_url' => 'REMOVED_IP/teampass',
        'favicon' => 'REMOVED_IP/teampass/favico.ico',
        'path_to_upload_folder' => '/var/www/html/teampass/upload',
        'url_to_upload_folder' => 'http://REMOVED_IP/teampass/upload',
        'path_to_files_folder' => '/var/www/html/teampass/files',
        'url_to_files_folder' => 'http://REMOVED_IP/teampass/files',
        'activate_expiration' => '0',
        'pw_life_duration' => '0',
        'maintenance_mode' => '0',
        'enable_sts' => '0',
        'encryptClientServer' => '1',
        'cpassman_version' => '2.1.27',
        'ldap_mode' => '0',
        'ldap_type' => '0',
        'ldap_suffix' => '0',
        'ldap_domain_dn' => '0',
        'ldap_domain_controler' => '0',
        'ldap_user_attribute' => '0',
        'ldap_ssl' => '0',
        'ldap_tls' => '0',
        'ldap_elusers' => '0',
        'ldap_search_base' => '0',
        'richtext' => '0',
        'allow_print' => '0',
        'roles_allowed_to_print' => '0',
        'show_description' => '1',
        'anyone_can_modify' => '0',
        'anyone_can_modify_bydefault' => '0',
        'nb_bad_authentication' => '0',
        'utf8_enabled' => '1',
        'restricted_to' => '0',
        'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '1',
        'enable_user_can_create_folders' => '1',
        'insert_manual_entry_item_history' => '0',
        'enable_kb' => '0',
        'enable_email_notification_on_item_shown' => '1',
        'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => 'http://REMOVED_IP/teampass/includes/images/logo.jpg',
        'custom_login_text' => '',
        'default_language' => 'english',
        'send_stats' => '0',
        'get_tp_info' => '1',
        'send_mail_on_user_login' => '0',
        'nb_items_by_query' => 'auto',
        'enable_delete_after_consultation' => '0',
        'enable_personal_saltkey_cookie' => '0',
        'personal_saltkey_cookie_duration' => '31',
        'email_smtp_server' => 'REMOVED',
        'email_smtp_auth' => '1',
        'email_auth_username' => 'REMOVED',
        'email_auth_pwd' => 'REMOVED',
        'email_port' => '25',
        'email_security' => 'none',
        'email_server_url' => 'http://REMOVED_IP/teampass',
        'email_from' => 'teampass@REMOVED.DOMAIN',
        'email_from_name' => 'Teampass',
        'pwd_maximum_length' => '40',
        '2factors_authentication' => '0',
        'delay_item_edition' => '0',
        'allow_import' => '1',
        'proxy_ip' => '',
        'proxy_port' => '',
        'upload_maxfilesize' => '10mb',
        'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
        'upload_imagesext' => 'jpg,jpeg,gif,png',
        'upload_pkgext' => '7z,rar,tar,zip',
        'upload_otherext' => 'sql,xml',
        'upload_imageresize_options' => '1',
        'upload_imageresize_width' => '800',
        'upload_imageresize_height' => '600',
        'upload_imageresize_quality' => '90',
        'use_md5_password_as_salt' => '0',
        'ga_website_name' => 'TeamPass for ChangeMe',
        'api' => '0',
        'subfolder_rights_as_parent' => '1',
        'show_only_accessible_folders' => '1',
        'enable_suggestion' => '0',
        'otv_expiration_period' => '7',
        'default_session_expiration_time' => '60',
        'duo' => '0',
        'enable_server_password_change' => '0',
        'ldap_object_class' => '0',
        'saltkey_ante_2127' => 'REMOVED',
        'menu_type' => 'context',
        'google_authentication' => '0',
        'bck_script_path' => '/var/www/html/teampass/backups',
        'bck_script_filename' => 'bck_cpassman',
        'syslog_enable' => '0',
        'syslog_host' => 'localhost',
    'timezone' => 'Europe/Rome',
    );
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
UPDATE
### Client configuration
**Browser:**
Firefox 59.0.2
**Operating system:**
Windows 7
#### Web server error log
No errors in log.
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by sandman42** [comment]
```
mysql> describe teampass_misc;

+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(12)      | NO   | PRI | NULL    | auto_increment |
| type     | varchar(50)  | NO   |     | NULL    |                |
| intitule | varchar(100) | NO   |     | NULL    |                |
| valeur   | varchar(500) | NO   |     | none    |                |
+----------+--------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

**Comment by nilsteampassnet** [comment]
OK

PLease open file install/upgrade_run_2.1.27.php

Replace
````
// alter table MISC - rename ID is exists
$res = addColumnIfNotExist(
    $pre."misc",
    "increment_id",
    "INT(12) NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (`increment_id`)"
);
if ($res === true) {
    // Change name of field
    mysqli_query($db_link, "ALTER TABLE `".$pre."misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT");
} elseif ($res === false) {
    echo '[{"finish":"1", "msg":"", "error":"An error appears when adding increment_id to table misc! '.mysqli_error($db_link).'!"}]';
    mysqli_close($db_link);
    exit();
}
```
by
````
// Change name of field
mysqli_query($db_link, "ALTER TABLE `".$pre."misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT");
```

**Comment by sandman42** [comment]
Which one? Here's .zip install dir content:

```
6 -rw-r--r-- 1 root root 35823 mag  2 22:30 upgrade.php
16 -rw-r--r-- 1 root root 12908 mag  2 22:30 upgrade_run_2.1.26.php
40 -rw-r--r-- 1 root root 37051 mag  2 22:30 upgrade_run_2.1.27.php
40 -rw-r--r-- 1 root root 37650 mag  2 22:30 upgrade_run_db_original.php
 4 -rw-r--r-- 1 root root  3849 mag  2 22:30 upgrade_run_defuse_for_categories.php
 4 -rw-r--r-- 1 root root  4049 mag  2 22:30 upgrade_run_defuse_for_custfields.php
 8 -rw-r--r-- 1 root root  6964 mag  2 22:30 upgrade_run_defuse_for_files.php
 8 -rw-r--r-- 1 root root  7098 mag  2 22:30 upgrade_run_defuse_for_files_step2.php
 4 -rw-r--r-- 1 root root  4054 mag  2 22:30 upgrade_run_defuse_for_logs.php
 4 -rw-r--r-- 1 root root  3854 mag  2 22:30 upgrade_run_defuse_for_pwds.php
12 -rw-r--r-- 1 root root 10051 mag  2 22:30 upgrade_run_encryption_pwd.php
 4 -rw-r--r-- 1 root root  3500 mag  2 22:30 upgrade_run_encryption_suggestions.php
 8 -rw-r--r-- 1 root root  7757 mag  2 22:30 upgrade_run_final.php
 4 -rw-r--r-- 1 root root  1612 mag  2 22:30 upgrade_scripts_manager.php
```

**Comment by nilsteampassnet** [comment]
As written in my previous message, it is `install/upgrade_run_2.1.27.php`

**Comment by nilsteampassnet** [comment]
Please reopen on need.

**Comment by illimitati** [comment]
its work for me
