### ISSUE TITLE
Upload file on import or attach fails.

### ISSUE THREAD

**Issue by eduardocuervo** [nilsteampassnet/TeamPass#2247]
### Steps to reproduce
1. Import file with password, tryed with csv and with XML Keepas, with same result.
2. Select the file.
3. Press import button

### Expected behaviour
Passwords get imported

### Actual behaviour
Tell us what happens instead
Error 500. Reading error logs and the source code files wich are refered there, seems that filename is not properly put into the variable, as it seems thjat "name" variable is not set

### Server configuration
**Operating system**: Linux zabbix 3.19.0-80-generic #88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017 x86_64

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** 5.5.60-0ubuntu0.14.04.1

**PHP version:** 5.5.9-1ubuntu4.24

**Teampass version:** 2.1.27.12

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>/teampass
'favicon' => 'https://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'spanish',
'send_stats' => '1',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1522484792',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '10.10.10.10',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '',
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => 'teampass@mydomain.com',
'email_from_name' => 'Teampass',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Madrid',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '1',
'offline_key_level' => '60',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'ldap_allowed_usergroup' => 'nfor',
'ldap_new_user_role' => '1',
'use_http_request_login' => '1',
'settings_offline_mode' => '1',
'can_create_root_folder' => '1',

```

fresh install
### Client configuration

**Browser:** Chrome - 66.0.3359.139

**Operating system:** Windows Server 2008 R2 / 7 - 32bits

#### Web server error log

[Mon May 07 09:20:03.640227 2018] [:error] [pid 23285] [client 10.12.7.161:56259] PHP Catchable fatal error:  Argument 1 passed to getFileExtension() must be an instance of string, string given, called in /var/www/html/teampass/sources/upload/upload.files.php on line 175 and defined in /var/www/html/teampass/sources/main.functions.php on line 2211, referer: https://10.12.6.223/teampass/index.php?page=items
[Mon May 07 09:20:03.660979 2018] [:error] [pid 22706] [client 10.12.7.161:56268] PHP Fatal error:  Uncaught exception 'LogicException' with message 'Cannot use SplFileObject with directories' in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php:56\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(56): SplFileObject->__construct('/var/www/html/t...')\n#1 /var/www/html/teampass/sources/import.queries.php(162): Goodby\\CSV\\Import\\Standard\\Lexer->parse('/var/www/html/t...', Object(Goodby\\CSV\\Import\\Standard\\Interpreter))\n#2 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php on line 56, referer: https://10.12.6.223/teampass/index.php?page=items
[Mon May 07 09:20:22.885732 2018] [:error] [pid 3172] [client 10.12.7.161:56312] PHP Catchable fatal error:  Argument 1 passed to getFileExtension() must be an instance of string, string given, called in /var/www/html/teampass/sources/upload/upload.files.php on line 175 and defined in /var/www/html/teampass/sources/main.functions.php on line 2211, referer: https://10.12.6.223/teampass/index.php?page=items

```

**Comment by nilsteampassnet** [comment]
This is a know issue with PHP below 7.x.

The fix was provided.
Please download new 2.1.27.12 package and overwrite existing files.
Or Quick fix, in /sources/main.functions.php,
replace
`function cleanText(string $string, string $type = null)`
by
`function cleanText($string, $type = null)`

**Comment by eduardocuervo** [comment]
Hi:
I'm afraid it's not the same issue. I already have that patch applied. 
This is related with getFileExtension function not receiving the name of the uploaded file in the 175 line of upload.files.php
$ext = strtolower(getFileExtension($_REQUEST["name"]));
Maybe that $_REQUEST is not filled correctly? 
Kind regards,

**Comment by nilsteampassnet** [comment]
I think you don't have the latest package I made of 2.1.27.12.
Quick fix, in /sources/main.functions.php,
replace
`function getFileExtension(string $file)`
by
`function getFileExtension($file)`

**Comment by eduardocuervo** [comment]
So right! Thank you, i'd just updated cleantext function.
Regards.

**Comment by nilsteampassnet** [comment]
Great!
