### ISSUE TITLE
[2.1.27.12] Item suggestion is not available from Regular User

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2248]
### Steps to reproduce
1. Log as Regular User

### Expected behaviour
See Item suggestion Icon

### Actual behaviour
No tem suggestion Icon
![capture](https://user-images.githubusercontent.com/4628571/39698163-5f76afc4-51fc-11e8-8587-32f363f1fab3.PNG). 

Is is available only, if user have manage rights. 
If was fixed some time ago #1625. Please check.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.23 (cli) (built: Feb 8 2018 21:59:47)
**Teampass version:** 
2.1.27.12

### Client configuration
**Browser:**
IE, FF, EDGE
**Operating system:**
Windows 10 ENT 1709
#### Web server error log
```
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
```

**Comment by nilsteampassnet** [comment]
Indeed by design it is only visible by read-only users.

Is there a business need for a "normal" user to have access to suggestion pages?

**Comment by reginfo** [comment]
It will be Great, because we used it before and it was fixed by some code changes. Not it gone.

**Comment by nilsteampassnet** [comment]
OK I will commit the change.

For a quick fix, edit file `index.php`
and replace 
```
        && ($session_user_read_only === '1' || $session_user_admin === '1' || $session_user_manager === '1')
```
by
```
        && ($session_user_admin === '1' || $session_user_manager === '1')
```
