### ISSUE TITLE
Managed Users is empty after upgrade to 2.1.27.12 from 2.1.24

### ISSUE THREAD

**Issue by ubun3t** [nilsteampassnet/TeamPass#2251]
### Steps to reproduce
1. After upgrade from 2.1.24 to 2.1.27.12 directly this section not showing nothing.

### Expected behaviour
See and manage exists users. 

### Actual behaviour
![captura de pantalla de 2018-05-08 08-33-01](https://user-images.githubusercontent.com/16337441/39742023-4cb15146-529c-11e8-97d6-9730e42b0153.png)

### Server configuration
**Operating system**:
Debian8
**Web server:**
Apache 2.4.10-10+deb8u12
**Database:**
Mysql 5.5.60-0+deb8u1
**PHP version:**
5.6.33+dfsg-0+deb8u1
**Teampass version:** 
2.1.27.12
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox, Chrome
**Operating system:**
Linux Mint 18
#### Web server error log
```
[error]: PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/html/teampass/users.php on line 75 and defined in /var/www/html/teampass/sources/main.functions.php on line 2230, referer: https://teampass.xxxxx.es/index.php?page=items

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Have you migrating version by version?

**Comment by ubun3t** [comment]
Hi, nop. I did upgrade directly from 2.1.24. This is wrong ?

**Comment by ubun3t** [comment]
ok, but now I have 2.1.27.12 version with this problem and more than 500 items and the problem above
How can I resolve it? Please don't tell me fresh install and input all items manually... :)

Thanks!

**Comment by nilsteampassnet** [comment]
Can you provide the errors ?

**Comment by ubun3t** [comment]
When I do click on "Manger Users" the only error that I see (error log from apache2): 

[:error] [pid 13643] [client myIP:59070] PHP Catchable fatal error:  Argument 1 passed to cleanText() must be an instance of string, string given, called in /var/www/html/teampass/users.php on line 75 and defined in /var/www/html/teampass/sources/main.functions.php on line 2230, referer: https://teampass.xxxxx.es/index.php?page=items

**Comment by nilsteampassnet** [comment]
You didn't download the latest 2.1.27.12 package.
This is fixed bug

**Comment by ubun3t** [comment]
ok, many thanks  for your help Nil. I have upgraded to 2.1.27.14 and now all web interface are working well. 

Only one thing more, in recent version when I do a search for name or anything other field from items, the results if this "name o surname" is present in many items, I can't see the folder where tis item is. Before, 2.1.24 for axmple, in the results I can see the folder where belong it. 

Do you understand me? 

Thanks again!

**Comment by nilsteampassnet** [comment]
Good news!

Concerning your point, is it this you are talking about?
![image](https://user-images.githubusercontent.com/1197546/40196820-f136bb9e-5a11-11e8-9ca8-f960c12ff8e9.png)

**Comment by ubun3t** [comment]
Hi Nil, yes!!

**Comment by ubun3t** [comment]
Hi, How can I see that? 
Thanks!

**Comment by nilsteampassnet** [comment]
The folder is shown if there is enough "place" for it to be displayed.
So if the label of your item is too big then the folder path will not be have enough place to be shown.

Can you put a screencapture so that i understand your point?

**Comment by ubun3t** [comment]
Hi Nil, 
It  isn't a place problem because folders name are short, like : "Active Directory", "Mail"...
In this picture you can see all items after query but not showing : active directory or mail or whatever . I

![captura de pantalla de 2018-05-24 12-07-11](https://user-images.githubusercontent.com/16337441/40479356-9fd2d2a8-5f4b-11e8-959a-2e29dbd65ce7.png)

**Comment by nilsteampassnet** [comment]
You seem to have an error with Cache table.

PLease reload cache table
![image](https://user-images.githubusercontent.com/1197546/40505669-4846c28e-5f95-11e8-8cbc-9cfdf8048a42.png)

May occurred after upgrade.

**Comment by ubun3t** [comment]
Hi Nil, after run this command all seems to be ok. 
Thanks a lot for your help.
