### ISSUE TITLE
teampass.net website has been unreachable for over a day

### ISSUE THREAD

**Issue by psy-q** [nilsteampassnet/TeamPass#2252]
http://www.teampass.net/ has been refusing connections for some time just as we were evaluating team password safes, which doesn't inspire confidence.

Is there any information about what's going on?

**Comment by nilsteampassnet** [comment]
How strange!
When have you experimented this loose of service?
I didn't received any warning from the registrar.
Can I also ask you the context of accessing this url? (was it from the admin page, the footer, ???)

**Comment by nilsteampassnet** [comment]
Really strange because I don't see any failure.
I could access yesterday and today also.
Domain is correctly handled and no errors are shown.
Web files are hosted on Github
And finally the redirection is managed via Cloudflare where a cache system is enabled to prevent against server loose of connection.
So, I really don't understand.

You still can't reach the domain?
Can you try with https://www.teampass.net

**Comment by psy-q** [comment]
Now it's working. I must have been an issue with Cloudflare. I will keep an eye on it over the next few days, thanks!

**Comment by psy-q** [comment]
It is unreachable again from Switzerland:

```
rca@NL-07364:~$ telnet www.teampass.net 80
Trying 104.31.77.26...
Trying 104.31.76.26...
Trying 2400:cb00:2048:1::681f:4d1a...
Trying 2400:cb00:2048:1::681f:4c1a...
telnet: Unable to connect to remote host: Network is unreachable
rca@NL-07364:~$ telnet www.teampass.net 443
Trying 104.31.77.26...
Trying 104.31.76.26...
Trying 2400:cb00:2048:1::681f:4d1a...
Trying 2400:cb00:2048:1::681f:4c1a...
telnet: Unable to connect to remote host: Network is unreachable
rca@NL-07364:~$ traceroute www.teampass.net
traceroute to www.teampass.net (104.31.77.26), 30 hops max, 60 byte packets
 1  10.128.128.3 (10.128.128.3)  21.378 ms  21.238 ms  20.465 ms
 2  10.254.0.129 (10.254.0.129)  19.047 ms  19.053 ms  19.339 ms
 3  10.254.1.5 (10.254.1.5)  18.678 ms  18.944 ms  19.291 ms
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
(etc.)
```

Using both the university network and an LTE provider.

**Comment by nilsteampassnet** [comment]
Strange, I did a ping with no issue
I did also a tracert successfully
![image](https://user-images.githubusercontent.com/1197546/40010261-7f753608-57a4-11e8-9936-66177fe0791b.png)
So perhaps it is blocked by a firewall somewhere

**Comment by psy-q** [comment]
That would be fairly strange but not impossible, I've tried from the country's official nationwide higher education and research network and from two of our biggest ISPs, none of it worked. 

The only success I've had so far was through Tor (!) using a US IP. You mentioned the redirection is done via Cloudflare, is there a support address there that I could contact?

**Comment by nilsteampassnet** [comment]
If it works from Tor then the site is accessible ... at least I think.
But this sounds really strange as I don't see any issue on the admin pages of cloudflare.
But I noticed some attacks (attacks are IPs blocked by cloudflare ... perhaps your ip is in an non authorized range of IPs).
From what country are you?

https://support.cloudflare.com/hc/en-us

**Comment by psy-q** [comment]
I'm in Switzerland. I've found one ISP where it works, it's one that is peered with Germany via Frankfurt:

```
traceroute to www.teampass.net (104.31.76.26), 30 hops max, 60 byte packets
 1  xxxxxxx (192.168.2.1)  0.336 ms  0.429 ms  0.576 ms
 2  xxxxxxx (192.168.1.1)  2.987 ms  5.065 ms  5.104 ms
 3  10.136.59.230 (10.136.59.230)  12.119 ms  12.211 ms  12.211 ms
 4  172.16.20.6 (172.16.20.6)  22.119 ms  22.938 ms  22.984 ms
 5  172.16.20.5 (172.16.20.5)  23.574 ms  23.647 ms  25.562 ms
 6  212.25.27.149 (212.25.27.149)  24.878 ms  22.748 ms  22.732 ms
 7  zelja.zh.as8758.net (212.25.27.105)  29.463 ms  24.961 ms  24.771 ms
 8  atm6-0-1057.ar3.zrh.ch.colt.net (212.23.244.241)  18.752 ms  18.729 ms  19.672 ms
 9  212.36.135.25 (212.36.135.25)  24.951 ms  24.303 ms  25.261 ms
10  212.36.135.25 (212.36.135.25)  25.213 ms  24.318 ms  25.108 ms
11  de-cix-frankfurt.as13335.net (80.81.194.180)  27.337 ms  27.378 ms  28.519 ms
12  104.31.76.26 (104.31.76.26)  28.599 ms  29.574 ms  29.662 ms
```

But via LTE on the Salt (formerly Orange) network:
```
traceroute to www.teampass.net (104.31.77.26), 30 hops max, 60 byte packets
 1  www.huaweimobilewifi.com (192.168.8.1)  1.176 ms  1.167 ms  1.317 ms
 2  100.99.44.1 (100.99.44.1)  26.614 ms  26.901 ms  27.405 ms
 3  * * *
```

And on the research network via the Zürich hub:
```
traceroute to www.teampass.net (104.31.76.26), 30 hops max, 60 byte packets
 1  * * *
```

Telnet is also not successful:
```
telnet teampass.net 80
Trying 104.31.77.26...
Trying 104.31.76.26...
Trying 2400:cb00:2048:1::681f:4d1a...
Trying 2400:cb00:2048:1::681f:4c1a...
telnet: Unable to connect to remote host: Network is unreachable
```

I have tried to contact Cloudflare but they don't want to be contacted, it seems I need to sign up for an account before they let me send them a message. The best I can do is try to contact someone from the research network to see what's going on here, but since it also happens for "normal" people on non-research networks it must be something bigger.

**Comment by psy-q** [comment]
Talked to our NOC, apparenlty those addresses were the source of malicious activity and were blocked. And it seems some large ISPs subscribe to the same blocklist, so that explains that :)
