### ISSUE TITLE
Google Authenticator not working

### ISSUE THREAD

**Issue by PiotrIr** [nilsteampassnet/TeamPass#2253]
### Steps to reproduce
1. Enable Google two-factor authentication and User can reset his 2FA code
2.1. Try to login using code generated by administrator
2.2. Try to use "I need a new QR code. Please send me by e-mail a temporary Identification Code".

### Expected behaviour
Login to the Teampass website

### Actual behaviour
2.1 Stuck on "Please identify yourself"
2.2 Error message "Login credential do not correspond"

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0.28

**Teampass version:** 2.1.27

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1984204/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Goggle Chrome, Opera, Ms Edge

**Operating system:** Windows 10

#### Web server error log
```
[error.log](https://github.com/nilsteampassnet/TeamPass/files/1984206/error.log)
[access.log](https://github.com/nilsteampassnet/TeamPass/files/1984207/access.log)


Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by PiotrIr** [comment]
Hi Nils,
Thank you for your reply.
Unfortunately I'm on the latest version. I've just even reinstalled the server and the same effect :-(

**Comment by nilsteampassnet** [comment]
Yes you are right.
There is a logical issue in the code source.

I will provide the fix in 2.1.27.13

Quick fix:
Open file `main.queries.php`
Replace
```
            // check the given password
            if ($counter === 0
                || (isset($pwd) === true && isset($data['pw']) === true && $pwd !== $data['pw'])
            ) {
                // not a registered user !
                if ($counter === 0) {
                    logEvents('failed_auth', 'user_not_exists', "", stripslashes($login), stripslashes($login));
                } else if ($pwdlib->verifyPasswordHash($pwd, $data['pw']) === false) {
                    logEvents('failed_auth', 'user_password_not_correct', "", stripslashes($login), stripslashes($login));
                }
                echo '[{"error" : "no_user"}]';
            } else {
```
by
```
            // Do treatment
            if ($counter === 0) {
                // Not a registered user !
                logEvents('failed_auth', 'user_not_exists', "", stripslashes($login), stripslashes($login));
                echo '[{"error" : "no_user"}]';
            } else if (isset($pwd) === true
                && isset($data['pw']) === true
                && $pwdlib->verifyPasswordHash($pwd, $data['pw']) === false
            ) {
                // checked the given password
                logEvents('failed_auth', 'user_password_not_correct', "", stripslashes($login), stripslashes($login));
                echo '[{"error" : "no_user"}]';
            } else {
```

**Comment by PiotrIr** [comment]
This is working, thank you Nils!

**Comment by PiotrIr** [comment]
Hi Nils,
Sorry for bothering you again, but it is working for user only. When I try to login as admin, it sends me the code to my e-mail, however when I login it doesn't show the QR code - it just login. Could you advise please?
Could you also tell me when are you planing to release version 2.1.27.13?

**Comment by nilsteampassnet** [comment]
No problem, you don't bother me ;)
This is the normal behavior.
There is no 2FA on admin by design.

I've planned 2.1.27.13 to be ready this weekend.
