### ISSUE TITLE
AD users cannot log in with successful AD connection

### ISSUE THREAD

**Issue by whositwhatnow** [nilsteampassnet/TeamPass#2255]
We are using AD auth,  in the LDAP setup the conenction is successful.  When i try to login with a user in our allowed group I get user cannot be identified.  

LDAP server type Windows / Active Directory 
LDAP account suffix for your domain |  @test.ad.com
LDAP base DN for your domain |  DC=test,DC=ad,DC=com
LDAP allowed user group |  CN=testgroup, OU=Group,DC=test,DC=ad,DC=com
LDAP domain controller(s) |  testad1.com, testad2.com
LDAP port |  389
Use LDAP through SSL (LDAPS) | No
Use LDAP through TLS | No
Teampass local users only | No
Local and LDAP users | Yes

DUO.log
Starting authentication of 'testuser'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 

AD users cannot login

Config:
TeamPass 2.1.27.12
Centos 7
PHP 7.1

**Comment by rjbwtr** [comment]
I'm also seeing this from running the docker deployment. Image SHA: 9e0df5843836

```
Starting authentication of 'rjbwtr'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
```

ldap.debug.txt shows the following:

```
Get all LDAP params :
mode : 1
type : windows
base_dn : ou=Employees,ou=Example Users,dc=example,dc=com
search_base : 0
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @example.com
domain_controllers : ds.example.com:636
ad_port :
use_ssl : 1
use_tls : 0
*********

Get all ldap params :
base_dn : ou=Employees,ou=Example Users,dc=example,dc=com
account_suffix : @example.com
domain_controllers : ds.example.com:636
ad_port :
use_ssl : 1
use_tls : 0
*********

Create new adldap object :


After authenticate :


ldap status :

```

We have an older TeamPass deployment that doesn't exhibit this behaviour with the same config in the admin UI:

```
Get all LDAP params :
mode : 1
type : windows
base_dn : ou=Employees,ou=Example Users,dc=example,dc=com
search_base :
bind_dn :
bind_passwd :
user_attribute : 0
account_suffix : @example.com
domain_controllers : ds.example.com:636
port :
use_ssl : 1
use_tls : 0
*********

Get all ldap params :
base_dn : ou=Employees,ou=Example Users,dc=example,dc=com
account_suffix : @example.com
domain_controllers : ds.example.com:636
port :
use_ssl : 1
use_tls : 0
*********

Create new adldap object : Success


After authenticate : Success


ldap status : 1
```

I cannot see anything obviously wrong with the configuration.

**Comment by whositwhatnow** [comment]
@rjbwtr what version is your older deployment>?

**Comment by rjbwtr** [comment]
@whositwhatnow older deployment is running 2.1.27.10.

**Comment by whositwhatnow** [comment]
Thanks I'm going to roll back and try that version out. I still can't figure out why I can't authenticate.

**Comment by whositwhatnow** [comment]
Well got it to work, i dont get how this is interpreting the AD values but this works for me:

LDAP server type Windows / Active Directory 
LDAP account suffix for your domain |  @test.ad.com
LDAP base DN for your domain |  DC=test,DC=ad,DC=com
**LDAP allowed user group |  testgroup (this was causing the issue, didnt need to add full distinguished name, just name of group filter.)**
LDAP domain controller(s) |  testad1.com, testad2.com
LDAP port |  389
Use LDAP through SSL (LDAPS) | No
Use LDAP through TLS | No
Teampass local users only | No
Local and LDAP users | Yes
