### ISSUE TITLE
Yubico forced for everyone

### ISSUE THREAD

**Issue by manusfreedom** [nilsteampassnet/TeamPass#2256]
### Steps to reproduce
1. Enable Yubico authentication
2. Login using Google Authenticator

### Expected behaviour
Able to login

### Actual behaviour
Please provide your Yubico identifiers

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.33

**Database:** MariaDB 10.2

**PHP version:** 7.2.5

**Teampass version:** 2.1.27.12 

### Client configuration
**Browser:** Opera last version

**Operating system:** Windows 10 1709

**Comment by nilsteampassnet** [comment]
Yes it is normal, if you enable Yubico, then Yubico is expected.

How do you see this to work? perhaps did I miss a business case.

**Comment by manusfreedom** [comment]
In small company, we can't force a device for each employee, so we only force to use 2FA but not the device/technology to do it. So we need to able enable Google Authenticator and Yubico (and maybe other in future), but let people choose what they want to use.

**Comment by nilsteampassnet** [comment]
This makes sense.
I'm taking this into account.

**Comment by nilsteampassnet** [comment]
DOne.
Reopen on need.

**Comment by sebastienlapoux** [comment]
@nilsteampassnet thanks a lot! We're testing.
