### ISSUE TITLE
Not possible to add private folder later?

### ISSUE THREAD

**Issue by 80kk** [nilsteampassnet/TeamPass#2264]
I can't find an option to add/create private folder for users that have been created without that option ticket during creation. 

### Steps to reproduce
1. Create user without private folder.
2. Edit user and try to add option for having private folder

### Expected behaviour
It should be possible to add private folder later.

### Actual behaviour
Option not available.

### Server configuration
CentOS 7.5

**Web server:**
Apache 2.4.6
**Database:**
MariaDB

**PHP version:**
7.0.30

**Teampass version:** 
Latest

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Any

**Operating system:**
Linux/Any

#### Web server error log
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

```

**Comment by nilsteampassnet** [comment]
You need to run a task

![image](https://user-images.githubusercontent.com/1197546/40074951-682d552a-587b-11e8-9180-c7c561630f70.png)
