### ISSUE TITLE
Reopen #2241

### ISSUE THREAD

**Issue by sandman42** [nilsteampassnet/TeamPass#2267]
This reopens #2241 

Sorry for being late.

I've done what you've told me to do. Now, after going to http://my_teampass_ip/teampass/install/upgrade.php inserting admin user and password (I've put teampass in maintenance mode), and clicking lauch it shows me a grey moving left-right-left progress bar and stays in this state indefinitely (it's one hour)

**Comment by nilsteampassnet** [comment]
Please update using latest package 2.1.27.14

**Comment by sandman42** [comment]
Done, but same problem. I've run http://localhost/teampass/install/upgrade.php and http://my_ip/teampass/install/upgrade.php..

I haven't edited upgrade_run_2.1.27.php. Shall I edit it?


Shall I use http://localhost/teampass/install/upgrade_run_2.1.27.php instead of http://localhost/teampass/install/upgrade.php?

**Comment by nilsteampassnet** [comment]
You should just launch upgrade.php
Now if the spinner keep showing then there is an error in the apache error log.
Can you please check for it ?

**Comment by sandman42** [comment]
Hi, 

after 10 minutes run with the spinner always present, this is error.log:

`[Mon May 21 15:14:57.547136 2018] [mpm_prefork:notice] [pid 7673] AH00169: caught SIGTERM, shutting down
[Mon May 21 15:14:58.702681 2018] [mpm_prefork:notice] [pid 16333] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Mon May 21 15:14:58.702777 2018] [core:notice] [pid 16333] AH00094: Command line: '/usr/sbin/apache2'

and this access.log:

`::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/install.css HTTP/1.1" 200 832 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/upgrade.js HTTP/1.1" 200 1615 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/js/jquery.min.js HTTP/1.1" 200 32411 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/js/aes.min.js HTTP/1.1" 200 6268 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/images/76.gif HTTP/1.1" 200 5726 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/images/error.png HTTP/1.1" 200 951 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:17 +0200] "GET /teampass/install/js/jquery-ui.min.js HTTP/1.1" 200 48532 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /teampass/includes/js/functions.js HTTP/1.1" 200 3651 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /teampass/includes/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 7390 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /teampass/includes/images/canevas/logo.png HTTP/1.1" 200 5001 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /teampass/includes/images/canevas/bg_home.jpg HTTP/1.1" 200 1032 "http://localhost/teampass/install/install.css" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /teampass/includes/images/canevas/footer_all.png HTTP/1.1" 200 578 "http://localhost/teampass/install/install.css" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:18 +0200] "GET /favicon.ico HTTP/1.1" 404 500 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:16:29 +0200] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 200 574 "http://localhost/teampass/install/upgrade.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/ HTTP/1.1" 302 299 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/install.php HTTP/1.1" 200 3438 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/css/install.css HTTP/1.1" 200 897 "http://localhost/teampass/install/install.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/css/overcast/jquery-ui-1.10.3.custom.min.css HTTP/1.1" 200 5683 "http://localhost/teampass/install/install.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/install.js HTTP/1.1" 200 3413 "http://localhost/teampass/install/install.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/images/information-white.png HTTP/1.1" 200 991 "http://localhost/teampass/install/install.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/css/overcast/images/ui-bg_flat_55_c0402a_40x100.png HTTP/1.1" 200 488 "http://localhost/teampass/install/css/overcast/jquery-ui-1.10.3.custom.min.css" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:45 +0200] "GET /teampass/install/css/overcast/images/ui-bg_flat_55_eeeeee_40x100.png HTTP/1.1" 200 503 "http://localhost/teampass/install/css/overcast/jquery-ui-1.10.3.custom.min.css" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
::1 - - [21/May/2018:15:20:46 +0200] "GET /teampass/install/css/overcast/images/ui-bg_glass_60_eeeeee_1x400.png HTTP/1.1" 200 537 "http://localhost/teampass/install/css/overcast/jquery-ui-1.10.3.custom.min.css" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"`
`

**Comment by nilsteampassnet** [comment]
Please https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by sandman42** [comment]
I have this error:
`document.getElementById("res_step1_error").innerHTML = "File settings.php does not exist in folder includes/! If it is an upgrade, it should be there, otherwise select install!";document.getElementById("loader").style.display = "none";`

**Comment by nilsteampassnet** [comment]
You have not Teampass installed.
Something is wrong on the configuration.
Can You describe what you did and the History of your instance ?

**Comment by sandman42** [comment]
I have a working 2.1.27.7 in /opt, with a symbolic link in /var/www/html:

`0 lrwxrwxrwx 1 root root    22 mag 18 10:02 teampass -> /opt/TeamPass-2.1.27.7`

I downloaded .14, and unzipped in /opt so I have the following situation:

`    4 drwxr-xr-x 10 root root     4096 mag 14 20:51 TeamPass-2.1.27.14
    4 drwxr-xr-x  9 root root     4096 ago 30  2017 TeamPass-2.1.27.7
`
Then I did a ln -sfn /opt/TeamPass-2.1.27.14 to run it.
Have I to unzip the .14 into the .7 overwriting the files?

**Comment by nilsteampassnet** [comment]
I believe some mix occurred while doing upgrade or install.

Download latest package
Then check the definition of table `misc`, remove any index.
Then run upgrade.

**Comment by aqustiq** [comment]
I had this problem too so I'll put here steps to do:
1. Extract new version of Teampass in separate folder.
2. Move/copy from old version folder to new version folder:
./includes/sk.php
./includes/teampass-seckey.txt
./includes/config/settings.php
./includes/config/tp.config.php
3. Open in browser: https://your-url/install/upgrade.php and finish upgrade.

Hope this will help.
