### ISSUE TITLE
Cannot login after sucessfull first admin login

### ISSUE THREAD

**Issue by Arnaud-Burn** [nilsteampassnet/TeamPass#2269]
### Steps to reproduce
1. Fresh Install
2. First Log In as admin
3. Log Out

### Expected behaviour
It should allow the connection and acces to Teampass.

### Actual behaviour
It's telling that connection infos are not correct, even for the admin account with which I was just connected.

### Server configuration
**Operating system**: 
Windows Server 2016

**Web server:** 
Apache 2.4.33

**Database:**
MariaDB 10.2.14

**PHP version:** 
5.6.35

**Teampass version:** 
2.1.27.14

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** 
Fresh Instal

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** 
Firefox

**Operating system:** 
Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Arnaud-Burn** [comment]
In the connection log, it says "User_not_exist" but it's correctly in the database "Teampass_users".
for both, "admin" and "rnaud" accounts

**Comment by nilsteampassnet** [comment]
don't you have any apache errors?

**Comment by Arnaud-Burn** [comment]
I've just found those 4 lines in the apache error log file but don't really think it's causing this error
[Thu May 17 09:56:35.617448 2018] [authz_core:error] [pid 3068:tid 1120] [client 10.7.13.253:47735] AH01630: client denied by server configuration: C:/wamp64/www/
[Thu May 17 09:56:35.711213 2018] [authz_core:error] [pid 3068:tid 1120] [client 10.7.13.253:47735] AH01630: client denied by server configuration: C:/wamp64/www/favicon.ico
[Thu May 17 09:56:35.758781 2018] [authz_core:error] [pid 3068:tid 1120] [client 10.7.13.253:47735] AH01630: client denied by server configuration: C:/wamp64/www/favicon.ico
[Thu May 17 09:56:41.532366 2018] [authz_core:error] [pid 3068:tid 1120] [client 10.7.13.253:47742] AH01630: client denied by server configuration: C:/wamp64/www/teampass

But I've found this error line into the php error log file:
[17-May-2018 11:15:22 Europe/...] PHP   1. {main}() C:\wamp64\www\teampass\index.php:0

[17-May-2018 11:15:24 Europe/...] PHP Notice:  Undefined index: 2fa_authentication_selector in C:\wamp64\www\teampass\index.php on line 749

**Comment by nilsteampassnet** [comment]
Ive provided a New package that fix the issue regarding the last attire you have.
Please install it or upgrade

**Comment by Arnaud-Burn** [comment]
Thank you, it's now working with the new package.
