### ISSUE TITLE
password

### ISSUE THREAD

**Issue by abdoulayeAziz** [nilsteampassnet/TeamPass#2270]
Bonjour,

J'aimerai savoir à quoi sert le champ mot de passe et visibilité?

Merci

![t](https://user-images.githubusercontent.com/34244825/40185757-abf3f2fe-59f3-11e8-8cde-c4ab05a9e945.PNG)

**Comment by nilsteampassnet** [comment]
Pas sur de comprendre non plus.
Il n'y a pas de champs "mot de passe et visibilité"... est-ce de l'onglet que l'on voit sur la capture d'écran dont vous parlez ?
Si tel est le cas, il vous permet de définir le mot de passe porté par l'objet que vous créez.

**Comment by abdoulayeAziz** [comment]
Bonjour,

Je parle bien du mot de passe sur l'onglet que vous voyez sur la capture d'écran.
Par exemple si je crée un répertoire Nutanix qui doit contenir un fichier avec mes mots de passe de l’environnement Nutanix alors le mot de passe sur l'objet sert à quoi?

**Comment by nilsteampassnet** [comment]
Dans teampass, il n'y a pas de "fichier". On parle d'Objet.
Chaque objet a pour vocation de porter les informations (incluant le mdp) pour un "élément" comme par exemple "Nutanix".
Si "Nutanix" est un élément comme un site web qui se nécessite un login et un mdp alors il faut créer un Objet qui vous permettra de sauvegarder les infos de cet élément (et dans ce cas vous utilisez le champ mdp pour enregistrer ce mdp).
Maintenant si "Nutanix" est par exemple un "container" dans la mesure ou vous avez par exemple plusieurs comptes utilisateurs, alors il faudra créer un répertoire "Nutanix" et autant d'Objets que de comptes utilisateurs.

Est-ce plus clair?
Décrivez moi votre besoin pour que je vous aide.

**Comment by abdoulayeAziz** [comment]
Bonjour,

Nous avons différents environnements le but étant de centraliser tous les
mots de passe. J'ai créé des répertoires  (objet ) et j'ai mis les mots de
passe dans un fichier Word pour chaque environnement. Après ce là je
telecharge dans teampass chaque fichier Word pour chaque répertoire. Mais
en créant les objets un mot de passe est demandé c'est l'utilité de ce
dernier que j'aimerais savoir.
Merci

Le sam. 19 mai 2018 07:47, Nils Laumaillé <notifications@github.com> a
écrit :

**Comment by abdoulayeAziz** [comment]
Bonjour,
Avez vous compris mon besoin?

**Comment by abdoulayeAziz** [comment]
Bonjour,
En PJ l’arborescence de mes répertoires de mes différents environnements. Chaque objet contient un fichier word qui stocke les mots de passe. J'aimerai savoir s'il y a d'autres moyens pour que tu teampass gère mes mots de pass.


![team](https://user-images.githubusercontent.com/34244825/40354037-3c52f620-5db3-11e8-8911-35996d75d04f.PNG)

**Comment by nilsteampassnet** [comment]
eh bien oui
Teampass est fait pour gérer chaque objet de façon unique.
Ainsi chaque "mdp" présent dans votre fichier word devient un objet créé dans le répertoire qui va bien.

Par exemple
![image](https://user-images.githubusercontent.com/1197546/40444417-aa651262-5ec9-11e8-9ebf-c31788c73117.png)

**Comment by abdoulayeAziz** [comment]
merci beaucoup, je comprends de mieux en mieux.
