### ISSUE TITLE
An error appears. Answer from Server cannot be parsed! Returned data undefined.

### ISSUE THREAD

**Issue by IronWolve** [nilsteampassnet/TeamPass#2271]
### Steps to reproduce
1.  When adding multiple items to a folder, 2nd item pops up with 
"An error appears. Answer from Server cannot be parsed! Retrurn Data Undefined"

### Expected behavior
No Error Message

### Actual behavior
Pop up with error message

### Server configuration
**Operating system**:
Centos 7.5

**Web server:**
Nginx 1.14

**Database:**
Mariadb 10.2

**PHP version:**
Remi 7.2 - default system install

**Teampass version:** 
Git clone of current, 2.1.27.14

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/2014520/tp.config.txt)

### Client configuration
**Browser:**
Both latest Firefox and Chrome

**Operating system:**
Linux

I deleted and reinstalled, git pulled /var/www/teampass directory, the teampass database and even tried both php7.1.x and php7.2 versions.   

If I hit refresh on the browser between add new items, it works fine, its only when I'm adding multiple items.  Could be a browser issue?  Not seeing items in logs about error.

Looks like same bug as #2193 but a fresh install didnt fix the issue.

**Comment by nilsteampassnet** [comment]
I will investigate more deeper
Thank you

**Comment by nilsteampassnet** [comment]
I have investigated but couldn't reproduce it. I could create as many items I want inside the same folder without the need to refresh the browser page.
Would it be possible to follow instructions described [here](https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console) to get the exact error?

**Comment by IronWolve** [comment]
Just the response from items.queries.php? 

nSoIW97e3t7r1tCIDteggC/OJ6SPj0WsJmAako1T4ZFcsNDBoW8LOUDe/QAaU3ylGOs8AhRg52IvR8x5jNhxq6eueSHoUYseLv73m7n/HOrINWbznS50GxEvuQ82IIAzY9/p4zVIoo1iXCQhIhfShvi+1tpOSJF41GmMlh1umIWY4Nzo2NzJofIOkUghl3T8Lffh0NujhzYBFIxfpDALuQ==

**Comment by nilsteampassnet** [comment]
Don't you have errors in the apache log?

**Comment by IronWolve** [comment]
Nginx, nothing in the logs, I have full debug off, it appears to be the app, not the browser.  Let me try switching to apache and see if there is any difference.
