### ISSUE TITLE
Problems when Upgrade from 2.1.27.11 -> Latest

### ISSUE THREAD

**Issue by xpico** [nilsteampassnet/TeamPass#2273]
I try upgrade teampass from 2.1.27.11 to 2.1.27.12. But update failed. In the first step when insert admin username and password and click on the launch button, it gets stuck.

### Steps to reproduce
1. Create a dump of my database
2. zip my current teampass folder
3. Download 2.1.27.12
4. Unzip teampass2.1.27.12 into teampass folder
5. Run in the browser http://my_domain/install/upgrade.php

### Expected behaviour
Upgrade teampass

### Actual behaviour
In the first step when insert admin username and password and click on the launch button, it gets stuck.

### Server configuration
**Operating system**:
Debian GNU/Linux 9 (stretch)
**Web server:**
Apache/2.4.25 (Debian)
**Database:**
Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 7.0.27
**Teampass version:** 
2.1.27.11
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2022565/tp.config.php.txt)

### Client configuration
**Browser:**
Google Chrome Versión 66.0.3359.139 (Build oficial) (64 bits)
FirefoxESR 52.8.0 (64 bit)
**Operating system:**
Mac OS X 10.10.5
#### Web server error log
There isn't any error on /var/www/apache2/error.log

#### Log from the web-browser developer console (CTRL + SHIFT + i)

![captura de pantalla 2018-05-21 a las 14 36 04](https://user-images.githubusercontent.com/23553027/40308709-66f73294-5d07-11e8-86eb-fee28837cf95.png)

**Comment by nilsteampassnet** [comment]
Directly upgrade to latest please.

**Comment by xpico** [comment]
I try to directly upgrade to the latest 2.1.27.15 but have the same problem.

This is the console error log:
![captura de pantalla 2018-05-24 a las 15 09 47](https://user-images.githubusercontent.com/23553027/40487525-bcf1e586-5f64-11e8-9761-00c6cf6f952d.png)

upgrade.js line 59 is this: eval(xhrObject.responseText);

**Comment by xpico** [comment]
@nilsteampassnet there is no way to pass the first step. Any solution or any recommendation?

Thanks

**Comment by mrlocke** [comment]
Exactly same problem here upgrading to **2.1.27.26**.

**OS**: Debian GNU/Linux 8.10
**Browser**: Firefox 60.0.1
**Teampass old version**: 2.1.26

Stuck on first page, same console error:
![screenshot from 2018-06-06 16 09 22](https://user-images.githubusercontent.com/3625505/41043592-8fa7f710-69a4-11e8-9034-7b505d33eb2d.png)

Any idea on what can it be?

**Comment by mrlocke** [comment]
@nilsteampassnet  Any idea, why this may happen?

**Comment by mrlocke** [comment]
@nilsteampassnet 

I've done some debugging: The error comes from the next line:
`eval(xhrObject.responseText)`

So, I've dumped the value of the above:
`'enable_attachment_encryption' => '0',
document.getElementById("res_step0").innerHTML = "";document.getElementById("but_next").disabled = "";document.getElementById("res_step0").innerHTML = "User is granted.";document.getElementById("step").value = "1";document.getElementById("user_granted").value = "1";document.getElementById("loader").style.display = "none";document.getElementById("but_next").disabled = "";`

And I guess the problem is in the quotes around _enable_attachment_encryption_.

**Comment by mrlocke** [comment]
Changing the line 59 to:
`eval(xhrObject.responseText.replace("'enable_attachment_encryption'","enable_attachment_encryption"));`
allows to proceed, but now stuck on step 4.
