### ISSUE TITLE
Import from csv-list includes items that are marked as already imported

### ISSUE THREAD

**Issue by srvMelchior** [nilsteampassnet/TeamPass#2274]
### Steps to reproduce
- select import
- browse and select valid csv file
- mark any random item
- click import (A)
--> marked items from import (A) are imported
--> imported items from (A) are striked, their box is greyed out, can not be interacted with
- select any other item
- click import (B)

### Expected behaviour
- items marked for (B) are imported

### Actual behaviour
-  both items marked for (B) and those previously striked out (A) are imported. The (A) import exists twice now.

Since already imported items can not be deselected, I am required to load the list again and lose reference for which items are already imported.

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache/2.4.18 (2017-09-18T15:09:02)

**Database:** 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** TeamPass-2.1.27.11.

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:** Firefox Quantum 59.0.3 (64-Bit)

**Operating system:** Windows 7 SP1

**Comment by nilsteampassnet** [comment]
Thanks

Could reproduce and fix
