### ISSUE TITLE
Search result list does not display login information

### ISSUE THREAD

**Issue by srvMelchior** [nilsteampassnet/TeamPass#2275]
### Steps to reproduce
- one or more items that can be searched for
- type search term and execute
- click on one single item in the list of results
--> login information is shown
- type the same search term into the search bar and start the same search
- click on the same single item as before

### Expected behaviour
- login information is shown

### Actual behaviour
- login information is not shown

### Workaround
Click on any other item to show those login details, then the first item will be shown once it is clicked
The problem here is that a result list of only one item has no other item, which is difficult to resolve for some users.

### Sidenote
After I start a search, the first click into the folder menu on the left is entirely dismissed

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache/2.4.18 (2017-09-18T15:09:02)

**Database:** 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** TeamPass-2.1.27.11.

**Teampass configuration file:**
[settings.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833641/settings.php.txt)

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833643/tp.config.php.txt)

### Client configuration
**Browser:** Firefox Quantum 59.0.3 (64-Bit)

**Operating system:** Windows 7 SP1

**Comment by nilsteampassnet** [comment]
I'm not sure to understand from what location do you perform the search.
If you do the search from the "Find" page (url =/index.php?page=find) then indeed you have the login shown.
![image](https://user-images.githubusercontent.com/1197546/40388426-cfad751a-5e0f-11e8-9167-f6ab39269586.png)

Now if you search from the "Items" page (url = /index.php?page=items) using the quick search field, indeed you will not have the login shown.
But you can use the icon button to copy it in clipboard
![image](https://user-images.githubusercontent.com/1197546/40388516-0ff6caa4-5e10-11e8-9d64-893708b7b0f0.png)

But all this is normal and as designed.

**Comment by srvMelchior** [comment]
Thanks for the feedback. Indeed I was searching from the items page with the searchbar in the upper right corner. In this example I have a folder Test with 4 items inside.
![1_neutral](https://user-images.githubusercontent.com/37624279/40412928-e1425f24-5e74-11e8-9c33-5f372d022ab1.PNG)
When I search for the term "mein" I find two of those items. At this stage I already notice that I am missing the icons at the right end of each line. I do not know why.
![2_search](https://user-images.githubusercontent.com/37624279/40412720-62fe2bde-5e74-11e8-89de-ff85796c8e09.PNG)
When I select one of these items (in this case the upper one) the lower white panel displays the login information:
![3_select](https://user-images.githubusercontent.com/37624279/40412721-631e6c0a-5e74-11e8-9c32-14dbe5802cc1.PNG)

Now when I repeat step 2, the white panel is emptied and the result list is build again. But when I select the upper item again, the white panel stays empty. Only when I select the lower item will the panel be filled, after which I can once more select and display the upper item as well.

One thing to note, when an item is selected the font in the result list changes to italics. When I can not select an item, my click is apparently dismissed, as the font stays normal. As such, it's hard to show with a screenshot.
