### ISSUE TITLE
Item path shown in search result list is wrong/does not update --> can affect search results

### ISSUE THREAD

**Issue by srvMelchior** [nilsteampassnet/TeamPass#2276]
### Steps to reproduce
- Have a root-level folder "A" and inside one 1st-level Folder "A >> B"
- Import from .csv one item into Folder A
- search for the item
--> result shows item with the Path "A"
- Import the same item into Folder B
- search for the item

### Expected behaviour
--> result list shows item with the Path "A"
and
--> result list shows item with the Path "A >> B"

### Actual behaviour
--> result list shows item with the Path "A"
and
--> result list shows item with the Path "B"

Move Item from B into A so that it exists twice there.
--> Path does not update, still shows "B"

### Workaround
- Copy any single item once
--> Paths get updated
--> result list shows item with the Path "A >> B"

The real problem appeared in concunction with my other issue: https://github.com/nilsteampassnet/TeamPass/issues/2274
Since the import list is broken for me and imported everything twice and thrice, I preferred to import everything into one new Import folder and move the items from there to their target folder. The users could access and view the items there. It seems that the search function uses the above mentioned shown path when deciding if a user can find a certain item using the search bar. Since my users had no access to the import folder and the items had the outdated import-folder-path associated with them, the search result did not display these items, even though the users could manually open the folder the items actually exist inside and view them.

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache/2.4.18 (2017-09-18T15:09:02)

**Database:** 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** TeamPass-2.1.27.11.

**Teampass configuration file:**
[settings.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833641/settings.php.txt)

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833643/tp.config.php.txt)

### Client configuration
**Browser:** Firefox Quantum 59.0.3 (64-Bit)

**Operating system:** Windows 7 SP1

**Comment by nilsteampassnet** [comment]
Can you rebuild the cache table?

![image](https://user-images.githubusercontent.com/1197546/40388271-55eb2858-5e0f-11e8-8e7f-1ceb8bdd348f.png)

I need to investigate and check deeper the move feature to ensure cache table is correctly updated ...

**Comment by srvMelchior** [comment]
Reloading the cache table appears to update the paths that are not displayed correctly. New imports are nevertheless still affected.
