### ISSUE TITLE
Import fails when Login: / Account: has a backslash inside of it

### ISSUE THREAD

**Issue by srvMelchior** [nilsteampassnet/TeamPass#2277]
### Steps to reproduce
- create valid .csv file
- try to import into teampass
--> list of items that can be imported is shown
- close import window
- add entry to .csv file that has a "\" backslash inside the username/login/account
- try to import into teampass

### Expected behaviour
- list of items that can be imported is shown

### Actual behaviour
- Import fails with "Requested JSON parse failed."

### Workaround
- replace all backslashes with placeholders that are manually exchanged with a backslash afterwards

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache/2.4.18 (2017-09-18T15:09:02)

**Database:** 10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** TeamPass-2.1.27.11.

**Teampass configuration file:**
[settings.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833641/settings.php.txt)

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1833643/tp.config.php.txt)

### Client configuration
**Browser:** Firefox Quantum 59.0.3 (64-Bit)

**Operating system:** Windows 7 SP1

**Comment by nilsteampassnet** [comment]
Thanks.
Could reproduce and fix

![image](https://user-images.githubusercontent.com/1197546/40440251-da3586f4-5ebd-11e8-91df-714bafe247a0.png)

**Comment by srvMelchior** [comment]
Since your example screenshoot features a forward-slash " / ", does it also work with a backslash " \ " ?

**Comment by nilsteampassnet** [comment]
Yes it works

Just after import
![image](https://user-images.githubusercontent.com/1197546/41496417-fdb3671a-713f-11e8-97b0-27b2cd5d8465.png)

And after edition (just added an email)
![image](https://user-images.githubusercontent.com/1197546/41496420-1474c8b8-7140-11e8-9ba1-f405fbd77273.png)

Please reopen if needed
