### ISSUE TITLE
Google Authentication no link 

### ISSUE THREAD

**Issue by Nigvek** [nilsteampassnet/TeamPass#2279]
### Steps to reproduce
1. install teampass 2.1.27.11
2. try to use Google authenticator didn't send link in email
3. upgrade to teampass 2.1.27.15 (because of those issue: #2253  #2266 )
4. go on users administration
5. click on "send google auth"
6. message "no user found"
7. Use with this user send me again google auth
6. getting an email with no link

### Expected behaviour
I should have a link 

### Actual behaviour
I've got no link and if I use admin interface it didn't work at all "no user found".
google auth value is 1 in my config file and table teampass_misc 
Maybe I miss something in google auth but it seems pretty straight forward

### Server configuration
**Operating system**:Debian9

**Web server:**Apache 2.4.25

**Database:**Mariadb

**PHP version:**7.0.27-0+deb9u1

**Teampass version:** 
[teampassconf.txt](https://github.com/nilsteampassnet/TeamPass/files/2031399/teampassconf.txt)

**Teampass configuration file:**
2.1.27.15

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**Mozilla Firefox 59.0.2

**Operating system:**Win10 pro

#### Web server error log
log level to notice and nothing releavent

**Comment by nilsteampassnet** [comment]
I can confirm the first bug related to admin 2fa code sending, stupid bad copy paste.

For the 2d point, I cannot reproduce. Perhaps didn't I understood the step 7
![image](https://user-images.githubusercontent.com/1197546/40439766-3fd69428-5ebc-11e8-852c-85cfdfc28f19.png)

**Comment by Nigvek** [comment]
For my first test i clicked on the red rectangle then I get the window "Information"
![french_teampass_01](https://user-images.githubusercontent.com/22056780/40484898-4d8f3e84-5f5d-11e8-9d4f-29b6e28b3a50.png)

For my second test i clicked as you said on your picture and this is the result:
![french_teampass_04](https://user-images.githubusercontent.com/22056780/40484953-77c6c1f4-5f5d-11e8-9415-23ac5842c505.png)
![french_teampass_03](https://user-images.githubusercontent.com/22056780/40484960-7b6d8c16-5f5d-11e8-98c1-e177b60d4d75.png)

On the table teampass_users i can see ga and ga_temporary_code.

I just have to copy ga_temporary_code or ga (I don't understand why not allways the same (maybe after disable and enable again GA)) used it in "identification code" and get a QRCode.
After, you just have to scan it with your smartphone as usually.
By this way I work around this minor bug.

I'm not sure, but I think I've read in one issue that for administrator GA is disable by design (anti lock-out?), but I can. I've probably misunderstood, I'm not fluent in english. 
Is it possible to disable GA for 1 user? Did I miss this option if it exist?

If you need more information or if you need me to test some release I would be happy to help.
Your teampass is a great tool, thank you for all your work.

**Comment by nilsteampassnet** [comment]
I finally understand thank to your screencapture.
The French message is not correct and needs to be adapted.

**Comment by nilsteampassnet** [comment]
No feedback, I consider closed
