### ISSUE TITLE
After backup restore, all passwords are blank

### ISSUE THREAD

**Issue by maiconstedille** [nilsteampassnet/TeamPass#2280]
### Steps to reproduce
1.Install new server, with mariadb, php, apache and all requirements for teampass
2. install teampass (same version of teampass that is running on the server where the backup was done)
3. restored old teampass backup on that new server

### Expected behaviour
normal access to all objects

### Actual behaviour
All objects do not have the password field filled in. (Prints below)

### Server configuration
**Operating system**: Linux teampass.*****.net 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.5

**Database:** 5.5.56-MariaDB

**PHP version:** 7.2.5

**Teampass version:** 2.1.27.11

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/teampass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/files/favicon.ico',
'path_to_upload_folder' => '/var/www/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'ldap_type' => 'windows',
'ldap_suffix' => '@***.net',
'ldap_domain_dn' => 'dc=****,dc=net',
'ldap_domain_controler' => '**..****.net',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '1',
'restricted_to_roles' => '1',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => 'https://***.*****.com.br/files/logo_***.png',
'custom_login_text' => 'Por favor, identifique-se',
'default_language' => 'portuguese_br',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1524572481',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '10.51.100.3',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '',
'email_port' => '25',
'email_security' => '',
'email_server_url' => 'https://<anonym_url>',
'email_from' => '****',
'email_from_name' => '***',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '1',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '1',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'America/Sao_Paulo',
'enable_attachment_encryption' => '0',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'copy_to_clipboard_small_icons' => '1',
'ldap_allowed_usergroup' => 'Teampass',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 66.0.3359.181

**Operating system:** Windows - 64bits

#### Web server error log
```
Undefined index: path - /var/www/teampass/sources/main.queries.php (1281)
```

#### Teampass 10 last system errors
```
 * 16/10/2017 10:16:28 - Query: INSERT INTO `teampass_users` (`login`,`pw`,`email`,`name`,`lastname`,`admin`,`gestionnaire`,`can_manage_all_users`,`personal_folder`,`fonction_id`,`groupes_interdits`,`groupes_visibles`,`last_pw_change`,`user_language`,`encrypted_psk`) VALUES ('diego.oliveira', '$2y$10$mR05Uk4c3kBg0T7Y8UkJvuGKwSv5aZM7Qpr2c4YJ2F5VJYTjF6T6e', NULL, '***', '****', '0', '0', '0', '0', '', '', '', 1508148988, 'portuguese', '')<br />Error: Column 'email' cannot be null<br />@ /teampass/sources/identify.php
 * 16/10/2017 10:13:03 - Query: INSERT INTO `teampass_users` (`login`,`pw`,`email`,`name`,`lastname`,`admin`,`gestionnaire`,`can_manage_all_users`,`personal_folder`,`fonction_id`,`groupes_interdits`,`groupes_visibles`,`last_pw_change`,`user_language`,`encrypted_psk`) VALUES ('****', '$2y$10$.4oU.wsCj.qQqkJOBqrxgur7HiEF9ZeQ1Sv3M4ZqgkHBZWKoYAZbu', NULL, '***', '****', '0', '0', '0', '0', '', '', '', 1508148783, 'portuguese', '')<br />Error: Column 'email' cannot be null<br />@ /teampass/sources/identify.php
 * 16/10/2017 10:12:55 - Query: INSERT INTO `teampass_users` (`login`,`pw`,`email`,`name`,`lastname`,`admin`,`gestionnaire`,`can_manage_all_users`,`personal_folder`,`fonction_id`,`groupes_interdits`,`groupes_visibles`,`last_pw_change`,`user_language`,`encrypted_psk`) VALUES ('***', '$2y$10$JPP01zYFkFcNyR9kGodWi.xWsg0O1HFIgsJns9vrpK0xMbpUVDbqW', NULL, '***', '***', '0', '0', '0', '0', '', '', '', 1508148775, 'portuguese', '')<br />Error: Column 'email' cannot be null<br />@ /teampass/sources/identify.php
 * 09/10/2017 01:01:31 - Query: INSERT INTO `teampass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1507510891, NULL, '1', '6')<br />Error: Column 'label' cannot be null<br />@ /teampass/sources/users.queries.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
Note:
I would like to know if there is any different procedure to restore the backup to another server.
I changed some fields that contained the company name and people by ****
![capturar](https://user-images.githubusercontent.com/23699877/40486754-8fc7f28e-5f38-11e8-9628-59aaca854101.PNG)
![capturar2](https://user-images.githubusercontent.com/23699877/40486788-abe1ab68-5f38-11e8-8ae3-042036b5d9c6.PNG)

**Comment by nilsteampassnet** [comment]
Did you copy teampass-seckey.txt to the folder respecting your settings?

**Comment by maiconstedille** [comment]
I copied it, but I did this during the installation of teampass on this new server, I do not know if the time is right. What is the procedure to restore the backup to another server? I could not find this in the documentation

**Comment by nilsteampassnet** [comment]
If you are performing a restore of your source server to a new destination server, why do you "re-install" teampass on the new?
You just re-build an environment and copy database and files to the new destination server. So there is no need to install or update.
So if you copied the saltkey file on the new server and performed a new install, then the salteky was regenerated.
Now I hope you have a copy of the saltkey ... but teampass should have performed a copy of the initial file (in the same folder as where you have set the saltkey file)

**Comment by maiconstedille** [comment]
I again restored the backup to the database and copied the files from the site as well as the teampass-seckey.txt and sk.php files. Everything worked, I was able to view all of them and everything is ok in version 2.1.27.10.
But I tried to upgrade and I could not. I tried it for version 2.1.27.11, 2.1.27.12 and also for version 2.1.27.16 (the last one). All of them have the following error:
![capturar](https://user-images.githubusercontent.com/23699877/40632515-31856a92-62be-11e8-9af5-e42aa89041a3.PNG)

PHP Version 7.2.6
5.5.56-MariaDB MariaDB Server
CentOS Linux release 7.5.1804 (Core)

Do you know what it can be?

**Comment by maiconstedille** [comment]
completing the information, it follows the log that appears during the upgrade in the apache log:

PHP Fatal error:  Uncaught Error: Class 'Defuse\\Crypto\\Key' not found in /var/www/teampass/sources/main.functions.php:386\nStack trace:\n#0 /var/www/teampass/sources/main.functions.php(499): cryption('def50200151ac9a...', 'def0000063dec0d...', 'decrypt')\n#1 /var/www/teampass/install/upgrade_run_defuse_for_pwds.php(41): defuse_return_decrypted('def50200151ac9a...')\n#2 {main}\n  thrown in /var/www/teampass/sources/main.functions.php on line 386, referer: https://csl.energytelecom.com.br/install/upgrade.php

**Comment by ashraff100689** [comment]
we migrated teampass to new server, but the passwords are empty.

unable to locate teampass-seckey.txt file on old server.

**Comment by kaidlokhandwala** [comment]
Hi @nilsteampassnet 

Our existing TeamPass server has crashed and now it can not be restored now, But we have DB backup of TeamPass.

**Question:** Is it possible to restore with just DB backup **OR** I must have teampass-seckey.txt and sk.php file from source server(not possible in my case) for successful restore?

Thank you..
