### ISSUE TITLE
Old tags not working

### ISSUE THREAD

**Issue by KB7777** [nilsteampassnet/TeamPass#2282]
Hello.

I am after upgrade from 2.1.27.11 -> 2.1.27.16
When I click on tag -> 0 objects find.
While I am sure and I see that some items has this tag.
When I click edit item -> click save -> click on tag -> it shows only edited item not all items with this tag.

With 2.1.27.11 tags works as expected.

Regards.

**Comment by nilsteampassnet** [comment]
I will investigate

**Comment by nilsteampassnet** [comment]
I did some tries on 2.1.27.16 and couldn't reproduce.

When adding tag "test" to a set of items and then adding it to last one, I can click on it and it shows the full list of items with this tag.

**Comment by nilsteampassnet** [comment]
I would need an access to server to perform some test.

Possible? Contact me at nils@teampass.net
