### ISSUE TITLE
Problem loading folder tree

### ISSUE THREAD

**Issue by g3l0l4** [nilsteampassnet/TeamPass#2283]
### Steps to reproduce
1. Have a really large tree (more than 3000 folders...)
2. Log-in to teampass

### Expected behaviour
The tree should load faster because my server has enough power to do it

### Actual behaviour
The tree takes a long time to load.

### Server configuration
**Operating system**:
SUSE Linux Enterprise Server 12 SP1
**Web server:**
Apache 2.4.27
**Database:**
MySQL 14.14 Distrib 5.5.25
**PHP version:**
PHP 7.1.8
**Teampass version:** 
2.1.27.11

### Client configuration
**Browser:**
Mozilla Firefox
**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
What is a "long time" in terms of seconds?

Ensure this option is disabled
![image](https://user-images.githubusercontent.com/1197546/40779696-39015186-64d6-11e8-9725-62f546b2d042.png)

Is the account needing to access those 3000 folders?

Nevertheless I will investigate one how to make this better managed in next version.

**Comment by g3l0l4** [comment]
Between 8 and 15 seconds and I have this options disabled. All accounts need to see all folders... I think it´s just because I have a lot of folders and it needs a long time to render them... but don´t know exactly...

**Comment by johnnygrr1177** [comment]
Apache 2.4.27
