### ISSUE TITLE
Is it possible to restore teampass if I lost teampass-seckey.txt

### ISSUE THREAD

**Issue by SyuKira** [nilsteampassnet/TeamPass#2285]
I have a teampass environment under docker which I can extract all the front-end and database files. Now I want to transfer teampass to a single vm, I tried to restore but failed. This is the steps:

Server configuration

Operating system:
Centos 7.3

Web server:
http-2.4.6

Database:
Mysql-5.7.16

PHP Version:
5.6.36

Teampass Version:
Original docker: 2.1.16
Target vm: 2.1.27.16

Steps:
I installed a fresh teampass on vm and then restored the database and sk.php, I could execute sql query in teampass database successfully, but on web I login failed, it told me  
"Login credentials do not correspond!".

What I am confused is  "teampass-seckey.txt" this string is not involved in any of the file under the front-end path, does this mean my environment doesn't need this file?

And What I want to know is, now I got front-end files, sk.php and database files, is it possible to restore the whole environment on another server?

Thanks in advance:)

**Comment by nizedk** [comment]
The product cannot decode passwords from the database without the content of the teampass-seckey.txt - that file, as well as your database backup, is the most important items to to backup/restore-check on before going into production.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
