### ISSUE TITLE
database backup

### ISSUE THREAD

**Issue by cdgITteam** [nilsteampassnet/TeamPass#2286]
Hello, I'm a new teampass user (release 2.1.27.11 to 2.1.27.16). I use mysqldump+crontab to backup teampass database (mariadb) every night. The passwords seem to be encrypted in the dump. Is it the case ? in AES256 ?

What are the difference with the 2 methods (in teampass): 
- Manual database backup and restore ? 
- Optional backup script ?

What do you recommend ? Is there a documentation to use optional backup script ?

Thanks to help me.

**Comment by nilsteampassnet** [comment]
Yes the passwords are encrypted in DB.

If you have defined your own cron don't use the option in Teampass. This option is à help to the création of the DB backup cron.

**Comment by cdgITteam** [comment]
Thank you for your reply.
