### ISSUE TITLE
I don't see the file tree

### ISSUE THREAD

**Issue by sdieste** [nilsteampassnet/TeamPass#2288]
Hi,

i use the version 2..1.27.16 (new installed). I cannot see the file tree on the left side (see the screenshot). I didn't found anything in the documentation if i missed some configuration or something else. I tried different browsers (IE and Chrome).

What's the cause?

Sebastian
![teampass](https://user-images.githubusercontent.com/22171736/40969673-c8f47c60-68b8-11e8-89a1-58431c018ee5.PNG)

**Comment by nilsteampassnet** [comment]
You are logged with an administrator account.
Please create user account and get connected with it.
In the documentation you have the définition of the type of accounts.

**Comment by sdieste** [comment]
Perfect: thank you so much!
