### ISSUE TITLE
email validation does not work for .church root domain

### ISSUE THREAD

**Issue by mmance** [nilsteampassnet/TeamPass#2289]
My email is "mmance@spiritkeepers.church".  Your validation barks at me and tells me it is invalid.  I have to add the .com to users emails in order to create them, but that is not their email.

Consider a better regex for validation.

**Comment by mmance** [comment]
I will probably manually edit users emails in database to avoid validation.

**Comment by nilsteampassnet** [comment]
I need to check the conditions inside the library.

Will investigate

**Comment by nilsteampassnet** [comment]
What version do you use?

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
