### ISSUE TITLE
Error 404 when checking API version on browser

### ISSUE THREAD

**Issue by neryangj** [nilsteampassnet/TeamPass#2292]
I already implemented resolution on issue #2100 but still encountered the error
[tp,config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2082957/tp.config.php.txt)

### Steps to reproduce
1.  Enabled API feature and run version command from teampass.readthedocs.io
http://neri.example.com/api/index.php/info/version?apikey=somekey

### Expected behaviour
Display API version

### Actual behaviour
Error: 404
Looks like we can't find that page

### Server configuration
**Operating system**: 16.04.3

**Web server:**  nginx/1.13.7

**Database:** 5.7.20

**PHP version:** 7.1.9

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

**Comment by nilsteampassnet** [comment]
I cannot reproduce in 2.1.27.16 with api version 2.1.1

![image](https://user-images.githubusercontent.com/1197546/41496398-40120874-713f-11e8-9e9e-74f4eeba9bec.png)

Try to upgrade as a first solution
