### ISSUE TITLE
Remove Copy Password optin

### ISSUE THREAD

**Issue by npore7** [nilsteampassnet/TeamPass#2293]
Can we have an option to login directly to URL without being copy password from team pass to the web browser.

**Comment by nizedk** [comment]
That would assume a uniform way of logging in to a random website; less than a single percent (my guess) of modern web sites use basic auth.

You would need detailed (and continously updated) information, pr website, about their login form, and they would need to not check referrers on login. It's my impression that very few sites are like in that way.

A plugin is better suited for this behavior; as it works in the browser with insight into fields; TP is 'another website' in that relation.

**Comment by npore7** [comment]
Hi team,

 

Just let me know can we remove copy password to clipboard option as we think this is security concern and no one should see password.

 


  


Nagesh Pore
Network & System Administrator 

Tel: +91 22 3948 4000 | Extn.: 4083/4084
Mobile: +91 9821217366

cid:image001.jpg@01CFD8D5.D4376EB0


 <http://www.smarteinc.com> www.smarteinc.com 


1101, Vishwaroop IT Park, Sector: 30A, 
Vashi, Navi Mumbai 400703 – India

 <https://www.linkedin.com/company/smarte-inc> cid:image002.jpg@01CFD8D5.D4376EB0   <https://twitter.com/smarteinc> cid:image003.png@01CFD8D5.D4376EB0    <https://www.facebook.com/SMARTeInc> cid:image004.jpg@01CFD8D5.D4376EB0

**Comment by nilsteampassnet** [comment]
Yes you can as it is an option.

From settings page, find the next option
![image](https://user-images.githubusercontent.com/1197546/41227920-d4d944ee-6d76-11e8-86e1-fe685dc6717b.png)

**Comment by npore7** [comment]
Hi,

 

I don’t want any of user can view password so can we remove view password option from password tab and 

 

Also user get directly login without putting user name & password on the web.

 



 


  


Nagesh Pore
Network & System Administrator 

Tel: +91 22 3948 4000 | Extn.: 4083/4084
Mobile: +91 9821217366

cid:image001.jpg@01CFD8D5.D4376EB0


 <http://www.smarteinc.com> www.smarteinc.com 


1101, Vishwaroop IT Park, Sector: 30A, 
Vashi, Navi Mumbai 400703 – India

 <https://www.linkedin.com/company/smarte-inc> cid:image002.jpg@01CFD8D5.D4376EB0   <https://twitter.com/smarteinc> cid:image003.png@01CFD8D5.D4376EB0    <https://www.facebook.com/SMARTeInc> cid:image004.jpg@01CFD8D5.D4376EB0

**Comment by nilsteampassnet** [comment]
I don't really understand your need.

You mean that you don't want the "password" field? You would like to remove this field ... did I well understood?

Point 2, you want user to access the Items without being identified, correct?

**Comment by npore7** [comment]
Hi Nil, 

 

What is the price for teampass connector if we want to procure?

 


  


Nagesh Pore
Network & System Administrator 

Tel: +91 22 3948 4000 | Extn.: 4083/4084
Mobile: +91 9821217366

cid:image001.jpg@01CFD8D5.D4376EB0


 <http://www.smarteinc.com> www.smarteinc.com 


1101, Vishwaroop IT Park, Sector: 30A, 
Vashi, Navi Mumbai 400703 – India

 <https://www.linkedin.com/company/smarte-inc> cid:image002.jpg@01CFD8D5.D4376EB0   <https://twitter.com/smarteinc> cid:image003.png@01CFD8D5.D4376EB0    <https://www.facebook.com/SMARTeInc> cid:image004.jpg@01CFD8D5.D4376EB0

**Comment by nilsteampassnet** [comment]
Please reopen on need.

**Comment by npore7** [comment]
Hi nil,

 

We won’t be able to find out the delete user option in Team pass.

 


  


Nagesh Pore
Network & System Administrator 

Tel: +91 22 3948 4000 | Extn.: 4083/4084
Mobile: +91 9821217366

cid:image001.jpg@01CFD8D5.D4376EB0


 <http://www.smarteinc.com> www.smarteinc.com 


1101, Vishwaroop IT Park, Sector: 30A, 
Vashi, Navi Mumbai 400703 – India

 <https://www.linkedin.com/company/smarte-inc> cid:image002.jpg@01CFD8D5.D4376EB0   <https://twitter.com/smarteinc> cid:image003.png@01CFD8D5.D4376EB0    <https://www.facebook.com/SMARTeInc> cid:image004.jpg@01CFD8D5.D4376EB0
