### ISSUE TITLE
Teampass 2.1.27.16 - no edit possible if an folder added in the Allowed Folders

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#2295]
### Steps to reproduce
1. Open Teampass
2. Go to my folder that is in my "Allowed Folders" menu
3. I can create a new Item
4. Now I can not edit or delete the new Item

### Expected behaviour
We hade the following problem with the Version 2.1.27.10 and updated to the new Version 2.1.27.16 and the problem was not fixed.
We add the Test Folder to a user (Allowed Folders).
![image](https://user-images.githubusercontent.com/26093484/41156674-34db6e5e-6b23-11e8-9891-4501b90c2dee.png)

We can see with the user the folder and can create a Item in the test folder.
![image](https://user-images.githubusercontent.com/26093484/41156785-9bdce9e8-6b23-11e8-8ead-30ff7065aed8.png)

### Actual behaviour
We can now not edit or. delete my new Items.
We had following Messages:
![image](https://user-images.githubusercontent.com/26093484/41156824-ce7dc124-6b23-11e8-80b2-77b28bcc594f.png)

### Server configuration
**Operating system**: CentOS Linux release 7.4.1708

**Web server:** httpd 2.4.6

**Database:** mariadb 5.5.56

**PHP version:** 5.5.38

**Teampass version:**  2.1.27.16

### Client configuration
**Browser:** Newest Firefox

**Operating system:** Windows 10 64Bit

#### Web server error log
```
No error in the Log
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
I Open the developer console but we do not have any error message.
We Only the following correct message:
```
![image](https://user-images.githubusercontent.com/26093484/41157494-37a6f358-6b26-11e8-9aa8-c0ff08094c18.png)

**Comment by christovamps** [comment]
Hello.
Same problem. Both to edit and delete.

**Comment by christovamps** [comment]
Hi,
Updated to TeamPass 2.1.27.17, same problem.

**Comment by christovamps** [comment]
Hi,
Reapplied all permissions in "Manage Roles" and it worked.
Strange having to do this. This had not happened after an upgrade.
thank you.

**Comment by asantar0** [comment]
Hi christovamps, I have the same problem you had. Can you detail how you found the solution? Images can be very useful.
Regards

Agustín

**Comment by nilsteampassnet** [comment]
I think I have understood the case.

I will provide a fix for this.
