### ISSUE TITLE
support for login through http header

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2298]
### Steps to reproduce
1. Enable http authentication in config through gui
2. Setting does nothing
3. Manually enable it inside the config, broken logon window

### Expected behaviour
Automatic authentication using http headers was merged in https://github.com/nilsteampassnet/TeamPass/pull/2111 (and further changed afterwards)

### Actual behaviour
The config setting is still available, but other parts of code are missing after upgrading to 2.1.27.16
Enabling it manually in the config still changes the logon window, but logging on no longer works. 

Hi Nils, 

A while ago some code was merged (and changed further afterwards) in https://github.com/nilsteampassnet/TeamPass/pull/2111

Right now the setting is still there and part of it still works, but it seems the javascript to autmatically log on, and simply logging on no longer works. 
I assume a later patch removed part of this process. (There seems to be a new logon button)
Can I do something to help fix this?

**Comment by nilsteampassnet** [comment]
You are using latest release I assume.

You certainly right in your analysis as I changed this button and some elements arround.
But I've tried to keep this feature that I cannot test.
But it seems that I failed.

Of course you can help by having a quick investigation inside the code.
I will also check.

**Comment by nilsteampassnet** [comment]
I think I found the error.
While doing some code "beautifuling" to permit better reading, I removed a negative condition.
In index.php, change
```
    if (isset($SETTINGS['enable_http_request_login']) === true
        && $SETTINGS['enable_http_request_login'] === '1'
        && isset($_SERVER['PHP_AUTH_USER']) === true
        && (isset($SETTINGS['maintenance_mode']) === false
            && $SETTINGS['maintenance_mode'] === '1')
    ) {
```
to
```
    if (isset($SETTINGS['enable_http_request_login']) === true
        && $SETTINGS['enable_http_request_login'] === '1'
        && isset($_SERVER['PHP_AUTH_USER']) === true
        && !(isset($SETTINGS['maintenance_mode']) === true
            && $SETTINGS['maintenance_mode'] === '1')
    ) {
```

**Comment by nilsteampassnet** [comment]
Please reopen if not fixed

**Comment by tiredofit** [comment]
This feature doesn't seem to be working properly on 2.1.27.36 - Cannot set in the Web Admin for it to be enabled. When I set it and refresh the page the option disables again.

In tp.config it seems to be properly set.

`'use_http_request_login' => '1',`

**Comment by finalbeta** [comment]
Unfortunately, this feature was broken a long way back. I have not revisited it because I'm short on time and because the logon process should be changed beyond what I could provide myself. 
It might be best to remove any residual code at the moment./

**Comment by tiredofit** [comment]
Darn - Was sort of hoping that it could be used within our authentication for Single Sign on. Maybe it will reappear in 3.0
