### ISSUE TITLE
XML import didn't work

### ISSUE THREAD

**Issue by UserI404** [nilsteampassnet/TeamPass#2300]
Hello,

i would like to import a xml file from KeePass into TeamPass.

![grafik](https://user-images.githubusercontent.com/36761738/41276972-25917c9e-6e26-11e8-8934-0a618f8c6ccb.png)

But there is a http Error at the upload process.
Can someone help me please?

**Comment by nilsteampassnet** [comment]
What version of teampass?
It is a library code that is more related to server configuration.
Perhaps can you try to higher the max upload size?
![image](https://user-images.githubusercontent.com/1197546/41496175-a897431a-7139-11e8-8bf4-73c83322e39e.png)
Check also that value fits the one defined in your apache settings.

Also check that the upload settings in apache in general.

**Comment by UserI404** [comment]
I solved the problem with csv. thank you!
