### ISSUE TITLE
The Manage Main Page not load

### ISSUE THREAD

**Issue by rodrigograssi** [nilsteampassnet/TeamPass#2301]
### Steps to reproduce
1. In the profile of the admin change your language to Portuguese Brazil.
2. Logout
3. Login

### Expected behaviour
The Manage Main Page not load. Is show hacking attempt message.

### Actual behaviour

When I return the default language from admin to English (through SQL command) the main management page loads correctly.

### Server configuration
**Operating system**: Linux web 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1 (2018-04-28) x86_64

**Web server:** Apache/2.4.10 (Debian)

**Database:** 5.5.60-0+deb8u1

**PHP version:** 5.6.33-0+deb8u1

**Teampass version:** 2.1.27.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/TeamPass-2.1.27.16',
'cpassman_url' => 'http://<anonym_url>
'favicon' => 'http://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/TeamPass-2.1.27.16/upload',
'url_to_upload_folder' => 'http://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/TeamPass-2.1.27.16/files',
'url_to_files_folder' => 'http://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'portuguese_br',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1526245516',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '',
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/TeamPass-2.1.27.16/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'America/Sao_Paulo',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 67.0.3396.79

**Operating system:** Linux - 64bits

#### Web server error log
```
Undefined index: path - /var/www/TeamPass-2.1.27.16/sources/main.queries.php (1343)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
There must be an error in the BR language file.

I will check this.

**Comment by nilsteampassnet** [comment]
I cannot reproduce.
I changed the language in the admin user profile to Portuguese Br and it works as it should.

![image](https://user-images.githubusercontent.com/1197546/41496084-032f1a4e-7137-11e8-91f4-b3ef0b345b90.png)

![image](https://user-images.githubusercontent.com/1197546/41496092-3be1b482-7137-11e8-98af-10ba5e788e19.png)

Can you attach the portuguese_br.php file?

**Comment by danieldmarques** [comment]
Hi

I have the same problem when changing the language to Portuguese Brazil
.My version is 2.1.27.13

Attached portuguese_br.php file
[portuguese_br.zip](https://github.com/nilsteampassnet/TeamPass/files/2149224/portuguese_br.zip)

**Comment by nilsteampassnet** [comment]
Take the language file from ["master"](https://github.com/nilsteampassnet/TeamPass/blob/master/includes/language/portuguese_br.php)

**Comment by danieldmarques** [comment]
Hi

I replaced the file, restarted the httpd and it did not work

**Comment by danieldmarques** [comment]
Any suggestion?

**Comment by nilsteampassnet** [comment]
Find the error in the log.
And I will help you

**Comment by danieldmarques** [comment]
Hi

Follow the log

`[Tue Jul 10 09:38:40.291289 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/includes/config/include.php on line 24, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294610 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 79, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294630 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 80, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294639 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 81, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294646 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 82, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294654 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 83, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294662 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 84, referer: https://teampass.premierit.com.br/index.php
[Tue Jul 10 09:38:40.294669 2018] [:error] [pid 20939] [client 131.255.237.2:63650] PHP Notice:  Undefined variable: LANG in /var/www/html/sources/core.php on line 85, referer: https://teampass.premierit.com.br/index.php
`

**Comment by danieldmarques** [comment]
Hi @nilsteampassnet 
How are you?

Can you help me with the problem?

**Comment by luizmeireles** [comment]
Hello... I have the same problem here... Can anybody help me ?

**Comment by luizmeireles** [comment]
![b39cae09-cd07-479a-bcae-45d0a9722c1b](https://user-images.githubusercontent.com/15821989/51401007-8aa19d80-1b28-11e9-9f29-ef76fb6c137f.jpeg)
