### ISSUE TITLE
Search for items consistently returns 0 results, or wrong results - cache table not updated with all items

### ISSUE THREAD

**Issue by nizedk** [nilsteampassnet/TeamPass#2303]
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2097228/tp.config.php.txt)

### Steps to reproduce
1. add a number of items to teampass
2. search for know item using either description or label content
3. hit enter / press search

### Expected behaviour
The search result popup should display the number of matched items

### Actual behaviour
The popup says '0 objects found'
OR (depending on query string)
The popup returns 1 or more incorrect search results, not containing any part of the search string.

(note: All items can be manually found and read)

### Server configuration
Ubuntu 18.04

**Web server:**
Builtin nginx in teampass docker image

**Database:**
MySQL 5.7.22 official docker image

**PHP version:**
The one in teampass docker image

**Teampass version:** 
2.1.27.15

**Teampass configuration file:**
attached

**Updated from an older Teampass or fresh install:**
Fresh started out fresh from Docker image and clean database.

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox 60.0.2 x64 / Chrome 67.03396.87 x64

**Operating system:**
Win10 x64 1803

#### Web server error log
```
No actual errors; output from 'docker logs containername' includes stderr which is redirected to /dev/stderr; only the webservers request are visible
2.2.2.2 - - [13/Jun/2018:07:56:27 +0000] "GET /sources/find.queries.php?type=search_for_items&sSearch=Hest&key=D6.....(redacted)...............................uM HTTP/1.1" 200 167 "https://teampass.domain.tld/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
2.2.2.2 - - [13/Jun/2018:07:56:38 +0000] "GET /sources/find.queries.php?type=search_for_items&sSearch=Hest&key=D6.....(redacted)...............................uM HTTP/1.1" 200 167 "https://teampass.domain.tld/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
2.2.2.2 - - [13/Jun/2018:07:56:44 +0000] "GET /sources/find.queries.php?type=search_for_items&sSearch=Uno&key=D6.....(redacted)...............................uM HTTP/1.1" 200 167 "https://teampass.domain.tld/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
2.2.2.2 - - [13/Jun/2018:07:57:03 +0000] "GET /sources/find.queries.php?type=search_for_items&sSearch=Word&key=D6.....(redacted)...............................uM HTTP/1.1" 200 760 "https://teampass.domain.tld/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

The console does not show any error when querying and displaying the 0-object or the false-result; it appears that everything, browserwide, works fine; it's the supplied answer from the server that's incorrect.

**Comment by nilsteampassnet** [comment]
Can you try to rebuild the cache table from the tab 'tasks' inside settings page?

**Comment by nizedk** [comment]
I have done that a few times with no success prior to this; sorry for not mentioning.

**Comment by nilsteampassnet** [comment]
Did some tests and I cannot reproduce.

As example
![image](https://user-images.githubusercontent.com/1197546/41496107-a03205d6-7137-11e8-800e-19ff400dd136.png)

Even if you are using a previous version, I don't see how this search is wrong.
What type of account and access has your user in teampass?

**Comment by nizedk** [comment]
Hi Nils,

The user has Write access to all of the items on all folders; can read and edit them without problems; only the search is not working as intended.

I have attached the permissions view; all items that are giving weird search results are in 2. to bottom rows, and the user experiencing them are all in the middle column, so I would guess that there are full permissions.

![2018-06-18 10_26_34-teampass_frosted](https://user-images.githubusercontent.com/13115493/41526036-36bb0ac8-72e3-11e8-8459-eebad57637a7.png)

**Comment by nilsteampassnet** [comment]
Can you provide the server "response" when performing a search?
![image](https://user-images.githubusercontent.com/1197546/41618751-64339336-7404-11e8-86cb-3492a85d40e5.png)

**Comment by nizedk** [comment]
Sure;

![image](https://user-images.githubusercontent.com/13115493/41767852-038a0e4e-760b-11e8-8866-7da07ec13f5d.png)

**Comment by nizedk** [comment]
Any news, or anything I can do to contribute?

**Comment by nilsteampassnet** [comment]
Here I don't understand.
And no errors in the apache log?

I would need an access to your server to do some checks. Possible? Contact me nils@teampass.net

**Comment by nizedk** [comment]
I've found out what appears to be a problem;

I have a set of folders with in total 70+'ish items. However, the first two folders created has a sum of 52 items.

The teampass_cache table in the database has 52 rows. The missing items are not in the cache tables rows.

By Moving items into newly created folders, I can affect the number of cached rows (add 4 more rows), but I cannot work out what is the 'damaged' item. 

Could you consider adding some debug/log statements to the part of TeamPass that creates/updates/regenerates the cache, to do it one at a time and may 'pre: item' and 'done: item' so we can deduce which password item is the cause?

**Comment by nizedk** [comment]
Hi Nils, could you please have a look at what I wrote regarding the cache table?

I'm not able to give access to the affected server as it is; i thing my discovery may help uncovering the problem.

**Comment by nizedk** [comment]
Hi @nilsteampassnet - could you have a look at this; i still believe the the code that populates the cache table runs into an exception with some of our items.

**Comment by nizedk** [comment]
Theres no need to look at the issue, I found a solution to the problem.

**Comment by nilsteampassnet** [comment]
What was the solution you found ?
Can you please share as I don't understand what could happen in your issue.
Thank you

**Comment by nizedk** [comment]
It was correct, that one of the items in the password list had some form of character that stopped the cache table filling/building.

As we moved all of the entries out of TeamPass, we renamed them to track the progress. At some point, it started working again. We didn't notice which item in particular was the one that caused the error, but we had many items with special characters, as text and content was copied from various sources into the fields of TeamPass.

My advice is still, as suggested previously, to add a possibility of a verbose log regarding the population of each item in the cache table; "Population cache with item #17, $name..." " and then "#17 populated." so that you can troubleshoot what caused the error if it aborts/fails when you rebuild the cache table manually.

I would advice to make a simple check after rebuild of the cache table; rows in cache table should == number of items in the product, or else - an error has occurred.
