### ISSUE TITLE
File uploading does not work

### ISSUE THREAD

**Issue by jeresund** [nilsteampassnet/TeamPass#2305]
### Steps to reproduce
1. Edit an item where you have write permissions.
2. Select any file with permitted format.
3. Click start file upload
Dialogue text changes from 
"[-] filename.jpg (98 kb)" 
to
"filename.jpg (98 kb)"
4. Click save.
5. No file in the item description.

### Expected behaviour
File should be uploaded.

### Actual behaviour
Nothing happens.

### Server configuration
**Operating system**:
Debian 9.2
4.9.0-4-amd64  SMP Debian 4.9.51-1

**Web server:**
apache2/stable,stable,now 2.4.25-3+deb9u3 amd64

**Database:**
maria/stable 1.3.5-4.1 amd64

**PHP version:**
php/stable 1:7.0+49 all

**Teampass version:** 
2.1.27.16

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2102886/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
fresh 2.1.27.0, updated to 2.1.27.16

### Client configuration
**Browser:**
Any.

**Operating system:**
Windows 10

#### Web server error log
`[Wed Jun 13 ...] [:error] [pid x] [client x.x.x.x:x] PHP Notice:  Undefined index: file in /teampass/sources/upload/upload.attachments.php on line 204, referer: https://site.com/index.php?page=items`

#### Log from the web-browser developer console (CTRL + SHIFT + i)
---- main.queries.php ----
`Status Code: 200 OK`

Request headers:
```
POST /sources/main.queries.php HTTP/1.1
Host: ***/teampass
Connection: keep-alive
Content-Length: 202
Accept: application/json, text/javascript, */*; q=0.01
Origin: https://***/teampass
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://***/teampass/index.php?page=items
Accept-Encoding: gzip, deflate, br
Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: KEY_PHPSESSID=***; PHPSESSID=***; ***=***; jstree_select=19
```

Response headers:
```
HTTP/1.1 200 OK
Date: Thu, 14 Jun 2018 13:44:40 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Content-Length: 41
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

Form data:
```
size: 25
capital: true
numeric: true
ambiguous: true
reason: item_attachments
duration: 30
```

Response:
`[{"token" : "EBJQ4BTGRa6weW2T5vzv2UkUg"}]`
---- ----

---- upload.attachments.php ----

Request headers:
```
POST /sources/upload/upload.attachments.php HTTP/1.1
Host: ***/teampass
Connection: keep-alive
Content-Length: 101635
Origin: https://***/teampass
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary55l5re1kirp3x2Yn
Accept: */*
Referer: https://***/teampass/index.php?page=items
Accept-Encoding: gzip, deflate, br
Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: KEY_PHPSESSID=***; PHPSESSID=***; ***=***; jstree_select=19
```

Resonse headers:
```
HTTP/1.1 200 OK
Date: Thu, 14 Jun 2018 13:44:40 GMT
Server: Apache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Last-Modified: Thu, 14 Jun 2018 13:44:40 GMT
Cache-Control: post-check=0, pre-check=0
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 218
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```

Response:
```
{"jsonrpc" : "2.0", "error" : {"code": 120, "message": "File exceeds the maximum allowed size"}, "id" : "id"}
{"jsonrpc" : "2.0", "error" : {"code": 112, "message": "File size outside allowed lower bound"}, "id" : "id"}
{"jsonrpc" : "2.0", "error" : {"code": 121, "message": "No upload found in $_FILES for Filedata"}, "id" : "id"}
{"jsonrpc" : "2.0", "error" : {"code": 114, "message": "Invalid file name: ."}, "id" : "id"}
{"jsonrpc" : "2.0", "error" : {"code": 103, "message": "Failed to move uploaded file."}, "id" : "id"}
```

---- ----

**Comment by nilsteampassnet** [comment]
I think you have an issue in the server configuration.
I would recommend you to investigate in the upload settings of apache and especially about the TEMP folder.

**Comment by jeresund** [comment]
Indeed it was. 
In the /etc/php/7.0/apache2/php.ini config file the option "file_uploads" was set to off. 
I had no idea that this was also needed to be changed and haven't come across any references to it in any of my searches.

This is solved.

**Comment by nilsteampassnet** [comment]
thank you for feedback
