### ISSUE TITLE
DataTables warning: table id=t_users - Invalid JSON response.

### ISSUE THREAD

**Issue by SinanAEM** [nilsteampassnet/TeamPass#2306]
### Steps to reproduce
1.Log into teampass as admin
2.trying to manage users & folders
3.i get an error and I can't see any objects

### Expected behavior
simply I should see the folders & users I already have, i verified that because i checked that the information is stored in the database but it can't be displayed

### Actual behavior
I get an error : 
" DataTables warning: table id=t_users - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1 "

### Server configuration
**Operating system**:
Centos 7 - > 3.10.0-862.3.2.el7.x86_64
**Web server:**
Apache httpd -> httpd-2.4.33-3
**Database:**
mysql - > mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version:**
PHP 5.6.36
**Teampass version:** 
TeamPass 2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
`
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.mellanox.com/teampass',
    'favicon' => 'https://teampass.mellanox.com/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.mellanox.com/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.mellanox.com/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@mtl.com',
    'ldap_domain_dn' => 'dc=mtl,dc=com',
    'ldap_domain_controler' => 'mtldc1.mtl.com',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'http://www.4rfv.com/4rfv_news_images/nevion_scripts/0LJTQCZUYLMQ_0.jpg',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1516109162',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'labmailer.labs.mlnx',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@mellanox.com',
    'email_from_name' => 'Mellanox IT Password Manager',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '1',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Asia/Jerusalem',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'can_create_root_folder' => '1',
    'enable_massive_move_delete' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'ldap_port' => '3268',
);
`

#### Web server error log

```

[Mon Jun 18 10:51:06.723540 2018] [autoindex:error] [pid 31155:tid 139719698470656] [client 193.47.165.17:38604] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php,index.php) found, and server-generated directory index forbidden by Options directive
[Mon Jun 18 10:51:09.352298 2018] [autoindex:error] [pid 31158:tid 139719690077952] [client 193.47.165.18:33356] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php,index.php) found, and server-generated directory index forbidden by Options directive
[Mon Jun 18 10:51:10.804496 2018] [:error] [pid 31154:tid 139719488751360] [client 193.47.165.19:50986] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/teampass/includes/config/include.php on line 24, referer: https://teampass.mellanox.com/teampass/index.php?page=manage_folders
[Mon Jun 18 10:51:11.774075 2018] [autoindex:error] [pid 31661:tid 139719926691584] [client 193.47.165.17:38688] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php,index.php) found, and server-generated directory index forbidden by Options directive

Insert your web server log here
```
193.47.165.17 - - [18/Jun/2018:10:57:01 +0300] "GET /" 403 4650 "-" "-"
193.47.165.18 - - [18/Jun/2018:10:57:04 +0300] "GET /" 403 4650 "-" "-"
193.47.165.17 - - [18/Jun/2018:10:57:06 +0300] "GET /" 403 4650 "-" "-"
193.47.165.18 - - [18/Jun/2018:10:57:09 +0300] "GET /" 403 4650 "-" "-"
193.47.165.17 - - [18/Jun/2018:10:57:12 +0300] "GET /" 403 4650 "-" "-"
193.47.165.18 - - [18/Jun/2018:10:57:14 +0300] "GET /" 403 4650 "-" "-"
193.47.165.17 - - [18/Jun/2018:10:57:16 +0300] "GET /" 403 4650 "-" "-"
193.47.165.18 - - [18/Jun/2018:10:57:19 +0300] "GET /" 403 4650 "-" "-"
193.47.165.17 - - [18/Jun/2018:10:57:21 +0300] "GET /" 403 4650 "-" "-"
193.47.165.18 - - [18/Jun/2018:10:57:24 +0300] "GET /" 403 4650 "-" "-"

**Comment by nilsteampassnet** [comment]
Please provide the response from server

http://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

Note: have you checked the errors you have in your log `AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php,index.php) found, and server-generated directory index forbidden by Options directive `

**Comment by nilsteampassnet** [comment]
No answer.

Please reopen on need.
