### ISSUE TITLE
Teampass Upgrade - 2.1.23 to 2.1.27

### ISSUE THREAD

**Issue by jtbw911** [nilsteampassnet/TeamPass#2309]
### Steps to reproduce
1. Follow proper upgrade procedure for each version.
2. N/A
3. N/A

### Expected behaviour
Upgrade should be successful through all steps, Teampass accessible with passwords preserved.

### Actual behaviour
Upgrade from 2.1.23 through 2.1.25 (version by version) is successful. Upgrade from 2.1.25 to 2.1.26 ends up with a "blank" page in the second step (after the permission verification page) of the install. The "Launch" button is still visible; but, there are no instructions or action items; and, the "Next" button never becomes available. My assumption is that this is the SQL database connection verification page; but, I am unsure of that.

I have verified required packages, file/folder permissions, and MySQL connectivity. I did have to change my package install from php56w-mysqli to php56w-mysqlnd in order for 2.1.24 to install properly and have the "fetch_all" function.

### Server configuration
CentOS 6.5

**Web server:**
Apache - Latest
**Database:**
MySQL on separate server - Latest
**PHP version:**
PHP 5.6
**Teampass version:** 
2.1.25
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** All Browsers

**Operating system:**

#### Web server error log
```
No apparent issues in the Apache audit log - full audit mode. This seems to be occurring at the Teampass code level.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I would need an access to your server.
Possible? contact me at nils@teampass.net
