### ISSUE TITLE
Passwords not visible after upgrade from 2.1.26-final-3 to 2.1.27-xx

### ISSUE THREAD

**Issue by Mr-Ed** [nilsteampassnet/TeamPass#2311]
### Steps to reproduce
1. Upgrade working teampass installation
2. Check passwords - not visible

### Expected behaviour
Tell us what should happen
- Passwords visible :-) 

### Actual behaviour
Tell us what happens instead
- Password field in item view is blank

Upgrade runs through fine, no errors reported. Have tried upgrading from 2.1.26-final-3 to 2.1.27.0, 2.1.27.1, and directly up to 2.1.27.16 - all do the same, no errors reported but no passwords visible. (Snapshots are wonderful!)

After the upgrade password hashes are visible in the 'pw' column of the cpassman_items table, and a new column of 'encryption_type' is present, with all entries having the value 'defuse'. 

From messing about, if I edit the 'sources/items.queries.php' file, and at line 1077 I modify this:
```
            $pw = @$pw['string'];
            if (!isUTF8($pw)) {
                $pw = '';
            }
```

to this:
 ```
           $pw = @$pw['string'];
            if (!isUTF8($pw)) {
                $pw = 'TestPW';
            }
```

... then every password shows as 'TestPW'. So I wonder if in one of the upgrade processes it's not converted to UTF8 properly?

### Server configuration
**Operating system**: OpenSUSE 42.3

**Web server:** Apache 2.4.23

**Database:** MySQL 5.6.40

**PHP version:** 5.5.14-100

**Teampass version:** 2.1.26-final-3

**Updated from an older Teampass or fresh install:** Upgrade - initial install 2.1.10, upgraded incrementally via 2.1.13, 2.1.15, etc. 

### Client configuration
**Browser:** Various - tested with Chrome, FireFox, IE 

**Operating system:** Windows 10

#### Web server error log
No errors reported to web server log during upgrade or testing after upgrade.

**Comment by Mr-Ed** [comment]
Anonymised tp.config.php attached

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2115319/tp.config.php.txt)

**Comment by nilsteampassnet** [comment]
I did a new test.
Upgrading from 2.1.26 directly to 2.1.27.16 with no specific issue.

Have you tested the password when you are in 2.1.26?
Perhaps the corruption comes from an upgrade done before 2.1.26?

One point is that I decided to not overwrite the folder "2.1.26".
I renamed the  old one from "2.1.26" to "2.1.26-old"
Unzipped new package and renamed it "2.1.26"
Then copied folders "upload" and "files" from "old" to "new"
Then copied file "/includes/config.settings.php" from "old" to "new".

**Comment by Mr-Ed** [comment]
2.1.26 definitely works - we've got 20-odd people using it. All passwords visible and correct, and we can add and update items.

(Well, I say works - we can't create new folders, it fails with a JSON error - but I'm hoping the upgrade to .27 will sort that!)

Have tried what you suggested with renaming the folder and copying the config files to a clean tree - it's running the update directly to 2.1.27.16 now, will report back when it's done - in an hour or so.

Thanks for the quick response!

**Comment by Mr-Ed** [comment]
Hi again,

still the same I'm afraid - after the upgrade passwords aren't visible in the web UI, but hashes are still present in the database.

One new thing is an error in the apache error log sometime during the upgrade:
[Wed Jun 20 10:42:18.288757 2018] [php5:error] [pid 5854] [client 192.168.254.54:64347] PHP Warning:  chmod(): Operation not permitted in /srv/www/htdocs/pwman/sources/main.functions.php on line 2283, referer: http://chen2/pwman/install/upgrade.php

This didn't appear in the version 27.0, 27.1 or 27.2 upgrades I've tried. I'm not sure what it's trying to chmod, but I've been through and done a recursive chmod 0777 myself before starting the upgrade, on the following folders:
backups
files 
includes
install
uploads

Probably a bit overkill but I wanted to make sure I'd not missed anything!

Are there any new dependencies in version 27 to allow for the defuse encryption? Can't see anything in the docs...

Cheers

**Comment by Mr-Ed** [comment]
Been messing about a bit - if I edit an item with a missing password in the upgraded database, that edit sticks - so it does look like it's something to do with the re-encryption.

Something else I've just realised - in the release notes it says "you will also need to copy the saltkey into a password filed. It will be saved inside your database." - I didn't get prompted for this during the upgrade process, and I can't find the salt key anywhere in the database.  Where should it live?

**Comment by Mr-Ed** [comment]
Aha - found it. It's the same issue as in https://github.com/nilsteampassnet/TeamPass/issues/1798

The sk.php file was being cleared and in previous attempts ended up containing just:
```
<?php

?>
```

When I set the permissions on that file to 550 as suggested in the above issue, the file was left intact and the upgrade worked - all passwords visible.

**Comment by manwe** [comment]
Tried this, checked that sk was not set to blank during the upgrade but still can't see items. I see folders but can't see items when upgrading from 2.1.26 to 2.1.27

**Comment by Wrightie** [comment]
I'm having the same issue (passwords fields are blank).
I checked and my sk.php was clean and contained just:

```
<?php

?>
```

I tried to chown sk.php to 750 (as mentioned in #1798; used 750 better than 550 to hopefully get a better result), then ran an upgrade to v2.1.27.35.
The upgrade worked flawlessly, but I got no result: passwords are still blank.
What am I missing?

**Comment by dang89** [comment]
I'am having the same issue. ugrade from 2.1.26-final-3 to 2.1.27.36.
i have folders but not the passwords.
somebody find a solution?
