### ISSUE TITLE
API Issue adding folder on root.

### ISSUE THREAD

**Issue by asgomes** [nilsteampassnet/TeamPass#2312]
Hi we have a 2.1.27.12 version of Teampass.

I am trying to add a folder through the rest api with root folder (id=0) as a parent and it fails with error message 
{"err":"No destination folder provided"}.

*Steps to reproduce
Invoke add folder api like:
https://teampass.pt/api/index.php/add/folder/TestFolder;60;0;0;0?apikey=mykeyhereeeEEe

*Expected behaviour
Folder should be created with success message.

*Actual behaviour
Folder creation fails with message:
{"err":"No destination folder provided"}.

Problem:

Arguments validation fails on  string ("TestFolder;60;0;0;0") unexpectedly fails when 2nd parameter "parent folder id" is 0,
because PHP method Empty returns false when the parameter is "0".
(similar to https://github.com/nilsteampassnet/TeamPass/issues/1796 but in parent folder)

on file:
Teampass/api/functions.php
1030. if (--> empty($params[2]) <--) {
1031.	rest_error('NO_DESTINATION_FOLDER');
1032. }

**Comment by nilsteampassnet** [comment]
Strange but did the fix.

**Comment by asgomes** [comment]
Hi Nils,

thanks in advance, where should I find this fix? 

Is it ok to apply in 2.1.27.12?

thanks
