### ISSUE TITLE
SQL error in API near user name

### ISSUE THREAD

**Issue by mayeulk** [nilsteampassnet/TeamPass#2314]
The following API call returns an error:                    

wget -O saved_pw_teampass.json http://127.0.0.1/teampass/api/index.php/read/userpw/myuser?apikey=myAPIkeyXXXX24NPwwzzxvtM9F77LmvehDrNA
cat saved_pw_teampass.json              
The error:
  "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''myuser''' at line 3B/wsWwsLCw[shortened]"
  Note the 2 opening single quotes and the 3 closing single quotes.
The bug seems to be an extra single quote line 418 of functions.php, see:
https://github.com/nilsteampassnet/TeamPass/blob/454057eb49c52ac885e32fb3810e402b9019f8a4/api/functions.php#L418

**Comment by mayeulk** [comment]
Patch here: https://github.com/mayeulk/TeamPass/blob/master/api/functions.php

**Comment by nilsteampassnet** [comment]
Thank you
