### ISSUE TITLE
Restricted access to teampass

### ISSUE THREAD

**Issue by Pio2390** [nilsteampassnet/TeamPass#2316]
I´ve installed teampass on CentOS 6.9 and it works properly.
By adding users on teampass it works fine too but the issue happens to the client side by trying to see the users list.
There is no difference on that described behavior either on http or https protocol. I also tried the most known browsers and couldn´t detect any difference.

### Server configuration
**Operating system**: CentOS 6.9

**Web server:** http , https

**Database:** MySQL vertion 14.14 Distrib 5.1.73

**PHP version:** 5.6.36

**Teampass version:** 2.1.27.16

**Teampass configuration file:** /var/www/html/teampass/includes/config/tp.config.php

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Mosilla Firefox ; Chrome
**Operating system:** CentOS 6.9

#### Web server error log
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Loading failed for the <script> with source “http://localhost/teampass/includes/libraries/csrfp/js/csrfprotector.js”.
```

**Comment by nilsteampassnet** [comment]
I believe there is an inconsistency between the teampass urls in the configuration files.

Take a look to https://teampass.readthedocs.io/en/latest/errors/#error-403-500-blank-page

It will help you to set them correctly.

**Comment by Pio2390** [comment]
well i am using CentOS 6.9 so i don´t have a IIS server. So i can´t use the steps shown in the Users and Folders lists are empty (https://teampass.readthedocs.io/en/latest/errors/#error-403-500-blank-page).
how can i fix this?

**Comment by Pio2390** [comment]
@nilsteampassnet

**Comment by nilsteampassnet** [comment]
You need to check the 2 § before this one.
Ensure consistency between your settings and the url inside CSRFProtector settings.

**Comment by nilsteampassnet** [comment]
I would need an access to server to perform some test.

Possible? Contact me at nils@teampass.net

**Comment by Pio2390** [comment]
Thank you a lot Nils.
I´ll close the Issue now.
