### ISSUE TITLE
Cannot set group filter search based posix

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#2317]
Hello Nils,

I've changed the ldap configuration to search based posix without a group filter. But I want to use a group filter to monitor users who have permissions to logon. When I change the filter to the destination group, users can't logon, but they are member of that global security group.

The used syntax is described as shown: 
CN=Teampass,OU=Group,OU=Security Groups,DC=domain,DC=local

Do I have to change my syntax or are there problems with the code? I have installed the latest development branch (27.1.27.17).

**Comment by nilsteampassnet** [comment]
My knowledge regarding ldap is not very good.
I can provide you an example of my ldap test environment server that may helps you.

![image](https://user-images.githubusercontent.com/1197546/42121926-41aa1b40-7c39-11e8-9275-7568be53c20c.png)

**Comment by janjanson84** [comment]
Same issue here. When I use the test function I got the right groups back ( like cn=teampass,ou=Groups,dc=company,dc=de)

If I use this string and put it into the field "LDAP group to search", users cannot login.

I used wireshark to sniff LDAP traffic and teampass successfully gets the right groups. There must be an error inside Teampass which prevents it from matching these groups.
