### ISSUE TITLE
Failed to migrate teampass to another server

### ISSUE THREAD

**Issue by LaLa-Zhou** [nilsteampassnet/TeamPass#2321]
Hi,

  In the past I ran teampass in docker with version 2.1.26 and now I for some reason the docker was broken and I tried to migrate teampass to a server. What I have is the apache document root directory, mysql database ibd&frm files, a backup file(using web backup module). And this is the steps I tried to restore teampass:

1. unzip the last 2.1.26 version to the new server and do the fresh install.
2. modify the sk.php from the old file and restore the database by backup file.
3. update teampass_misc table to adjust to the new server url&path.
4. the admin password has been changed and I can login, but I have to disable ldap to enable other user login, otherwise it told me "Login credentials do not correspond!".
5. login teampass by other users and I can see the item tree, each item shows normally except password label, it just looked blank. I also did the "Repair password prefix" but didn't work. What should I do now?

**Comment by SyuKira** [comment]
![2018-07-03-16-06-48](https://user-images.githubusercontent.com/39798633/42206944-35e31272-7edb-11e8-9a71-e0546e4272cb.png)
![2018-07-03-16-05-28](https://user-images.githubusercontent.com/39798633/42206947-360e1b8e-7edb-11e8-8586-a135e7fa6186.png)

just like the above, some items even don't show anything, But I can find the password data from database:
mysql> select id,label,description,pw from teampass_items where label like '%test database%';
+-----+---------------+-------------+----------------------------------+
| id  | label         | description | pw                               |
+-----+---------------+-------------+----------------------------------+
| 187 | test database |             | 9fe5070fcd3e40fbce0f293be85947ca |
+-----+---------------+-------------+----------------------------------+

**Comment by lekpamartin** [comment]
Hi,

It seems that, you havre wrong salt-key. 

You need to copy from old server to new one : minimum files
-TEAMPASS-SALT-KEY-REP
- TEAMPASS-SOURCE-REP/includes/config/settings.php
- TEAMPASS-SOURCE-REP/includes/config/tp.config.php

I use version 2.1.27, in TEAMPASS-SALT-KEY-REP, you have thoses files : 
- sk.php
- teampass-seckey.txt
