### ISSUE TITLE
Upgrade path from 2.1.15

### ISSUE THREAD

**Issue by rayholtz** [nilsteampassnet/TeamPass#2323]
We are currently running Teampass v2.1.15 on an Ubuntu 14.04 server.  I want to upgrade to the latest version.  Is that OK to do to upgrade straight to 2.1.27.x? Or do I need to stair step through multiple versions?
Thanks,
Ray

**Comment by y-master** [comment]
Hello, I have the same request to upgrade from 2.1.20. What is the right way to do this ?

**Comment by nilsteampassnet** [comment]
You should upgrade version by version.
When you have upgraded to 2.1.26 latest package, you can upgrade with latest 2.1.27 as this version integrates an "incremental" upgrade.
