### ISSUE TITLE
Importing csv: Requested JSON parse failed.

### ISSUE THREAD

**Issue by Grem66** [nilsteampassnet/TeamPass#2327]
### Steps to reproduce
1. Create csv, login has "\" (backslash) in it, eg. "domain\admin"
```
label,login,password,url,comments
"Test Admin","domain\admin","password",,"domain.local"
```
2. Import CSV, get error: Requested JSON parse failed.
3. Manually create new item, same domain\admin for login
4. Item is saved. 
5. Preview pane shows login as: domain\admin
6. Opening/editing item shows login as: domainadmin
![preview test](https://user-images.githubusercontent.com/40968151/42425219-1772e622-836e-11e8-8853-7cf1dd953200.JPG)
![preview edit](https://user-images.githubusercontent.com/40968151/42425220-1a392e2a-836e-11e8-86ac-d1a34723cb97.JPG)

### Expected behaviour
When item is encapsulated with quotes, it should be imported as is, without failure
Full edit of item should show backslash

### Actual behaviour
Import fails
Preview pane and full edit don't show the same information
Using "/" (slash) works as expected

### Server configuration
**Operating system**:
Ubuntu 16.04.3
**Web server:**
Apache/2.4.18
**Database:**
Mysql Ver 14.14 Distrib 5.7.21
**PHP version:**
7.0.25-0ubuntu0.16.04.1
**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Fresh Install
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/2174229/tp.config.php.zip)

### Client configuration
**Browser:**
Chrome 67.0.3396.99 (Official Build) (64-bit)
**Operating system:**
Windows 10 1709 Build 16299.492
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
You are not using the latest.
It is a fixed bug

**Comment by Grem66** [comment]
Thanks and Apologies. Didn't realise about the 4th number in versioning.
