### ISSUE TITLE
Edition not possible. This Item is presently edited!

### ISSUE THREAD

**Issue by BFCardoso** [nilsteampassnet/TeamPass#2330]
Hi,
I was using a old version of TeamPass.

TeamPass 2.1.20 © 2009 - 2014
PHP 5.3.3 (cli) (built: Aug 6 2014 05:40:05)
MySQL 5.1.73

I need to edit the pass item on TeamPass, but the error message below:

Edition not possible. This Item is presently edited!

What do I have to do?

<!--

Steps to reproduce
I alredy saw the issues #271 and #365 and already select tab called
"Database", and check the list "Items in edition" (or something similar).
In this list you can release a lock if not automatically released, but the problem persists yet.

Actual behaviour
I don´t edit the password item.

Server configuration
Operating system:
CENTOS 7
Web server:
Apache/2.4.6 (CentOS)

Database:
MySQL version 5.7.19

PHP version:
PHP version 7.0.23

**Comment by nilsteampassnet** [comment]
Admin can clear édition lock through page Utilities.

**Comment by nilsteampassnet** [comment]
Any news?

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
