### ISSUE TITLE
Double entry in password list if ü / ä / ö is used in description

### ISSUE THREAD

**Issue by GitSlash2018** [nilsteampassnet/TeamPass#2333]
### Steps to reproduce
1. add a entry with ü / ö / ä in its description

### Expected behaviour
the entry is appearing once in the list

### Actual behaviour
the entry is appearing twice in the list, if u rename it to (ü to use) the second entry disappears

### Server configuration
**Operating system**: Linux XXXXXX 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
**Web server:** Apache/2.4.25 (Debian)
**Database:** 5.5.5-10.1.26-MariaDB-0+deb9u1
**PHP version:** 7.0.30-0+deb9u1
**Teampass version:** 2.1.27.16

### Client configuration
**Browser:** Chrome - 67.0.3396.99
**Operating system:** Windows - 64bits

**Comment by nilsteampassnet** [comment]
Can you provide a screenshot because I cannot reproduce?

![image](https://user-images.githubusercontent.com/1197546/42676283-da048f9a-8677-11e8-8c3f-4665ae363d20.png)

**Comment by GitSlash2018** [comment]
Sry Nils I can’t reproduce it now. See it as solved until I post again. Thanks anyway for your great work!
