### ISSUE TITLE
error adding entry with the same name then another entry in a different folder

### ISSUE THREAD

**Issue by GitSlash2018** [nilsteampassnet/TeamPass#2334]
### Steps to reproduce
1. add an entry with the same name then another entry in a different folder - error (entry already exist)
2. add entry with different name -> save: OK
3. edit entry to the name u originally name wanted: OK works

### Expected behaviour
no problem by adding the entry 

### Actual behaviour
see "Steps to reproduce"

### Server configuration
**Operating system**: Linux XXXXXX 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
**Web server:** Apache/2.4.25 (Debian)
**Database:** 5.5.5-10.1.26-MariaDB-0+deb9u1
**PHP version:** 7.0.30-0+deb9u1
**Teampass version:** 2.1.27.16

### Client configuration
**Browser:** Chrome - 67.0.3396.99
**Operating system:** Windows - 64bits

**Comment by nilsteampassnet** [comment]
Thank you
I will investigate

**Comment by nilsteampassnet** [comment]
Fixed
