### ISSUE TITLE
Removes "/" from passwords imported from keepass

### ISSUE THREAD

**Issue by N3RG4L** [nilsteampassnet/TeamPass#2336]
### Steps to reproduce
1. Create passwords in keepass containing "/"
2. Import to TeamPass
3. Teampass deletes the "/"

### Expected behaviour
Password should be as it was on keepass (with "/" included)

### Actual behaviour
All "/" signs got deleted from the imported password

### Server configuration
**Operating system**:  Ubuntu 16.04 (phusion/baseimage   docker)

**Web server:** :  Apache 2.4.18 (Ubuntu)

**Database:** : MySQL 5.6.35

**PHP version:** : PHP 7.0.22-0ubuntu0.16.04.1

**Teampass version:** : 2.27.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** : Updated from 2.26.13
PLEASE attach to this message the file `/includes/config/tp.config.php`.

global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/teampass/www',
    'cpassman_url' => 'https://teampass.companyname.net',
    'favicon' => 'https://teampass.companyname.net/favicon.ico',
    'path_to_upload_folder' => '/teampass/www/upload',
    'url_to_upload_folder' => 'https://teampass.companyname.net/upload',
    'path_to_files_folder' => '/teampass/www/files',
    'url_to_files_folder' => 'https://teampass.companyname.net/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => '0',
    'ldap_suffix' => '@sampl.ch',
    'ldap_domain_dn' => 'DC=sampl,DC=ch',
    'ldap_domain_controler' => getenv('LDAP_SERVER'),
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '1',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtpinternal.companyname.net',
    'email_smtp_auth' => 'false',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => 'none',
    'email_server_url' => 'https://teampass.companyname.net',
    'email_from' => 'noreply@companyname.net',
    'email_from_name' => 'NoReply',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/teampass/www/backups',
    'bck_script_filename' => 'bck_cpassman',
    'settings_offline_mode' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'timezone' => 'Europe/Paris',
    'saltkey_ante_2127' => 'DSu9XWVmTexBjncZ',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'teampass_version' => '2.1.27',
    'migration_to_2127' => '0',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;st',
	'send_stats_time' => '1506605131',
    'agses_authentication_enabled' => '0',
    'otv_is_enabled' => '0',
    );

### Client configuration
**Browser:** : Chrome  61.0.3163.100

**Operating system:** : Windows 10

#### Web server error log
``` No errors
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I performed tests on 2.1.27.17 (in development still) and couldn't reproduce.

![image](https://user-images.githubusercontent.com/1197546/42676441-8077f452-8678-11e8-9a1e-195d1dcd4c4d.png)

Several changes were introduced with Keepass import feature since 2.1.27.9.

Please update
