### ISSUE TITLE
Passwords not showing TeamPass 2.1.27.16

### ISSUE THREAD

**Issue by jeffgege** [nilsteampassnet/TeamPass#2337]
**Steps to reproduce:**
Upgrade to the newest version from TeamPass 2.1.26
Once upgrade is completed check passwords

**Expected behaviour:**
Passwords to show correctly

**Actual behaviour:**
A blank password shows up. I did notice in issue #2311 that they had a similar issue. my sk.php had not been cleared. I also saw the same thing that he saw with changing the isUTF8 function and that seems to be where it is failing. I did notice that my database was not UTF8 after the upgrade. I have changed that as well. Still no success. 

**Server configuration:**
Operating system: Centos 7.5

Web server: Apache 2.4.6

Database: MySQL 5.7.22

PHP version: 7.2.7

Teampass version: 2.1.27.16

Updated from an older Teampass or fresh install: Upgrade - initial install 2.1.23, upgraded incrementally 

**Client configuration:**
Browser: Various - tested with Chrome, FireFox, IE

Operating system: Windows 10

**Logs:**
Web server error log
No errors reported to web server log during upgrade or testing after upgrade.

**Comment by nilsteampassnet** [comment]
Did you checked your passwords after each increment upgrade?
This could permit to identify at what moment the encryption is broken.

**Comment by sphynx7033** [comment]
I know it did work with 2.1.25.2 I may have skipped 2.1.26. Would this be the cause of my issue?

**Comment by nilsteampassnet** [comment]
No but it would help to understand when the failure occurred.

What is sure, is that if you missed to upgrade to 2.1.26 before starting update of 2.1.27.16 then it is for sure an issue because before 2.1.27 there was no "incremental" upgrade process

**Comment by manwe** [comment]
In my case I just run the upgrade from 2.1.23 --> 2.1.24 --> 2.1.25 --> 2.1.26 --> 2.1.27
Checked the passwors during all the process and I only see blank/not found items in the last 2.1.27 version. 
Reverting to 2.1.26 from now.

**Comment by nilsteampassnet** [comment]
Thank you for details.
Before upgrading to latest 2.1.27, run the SQL query: ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;

**Comment by manwe** [comment]
It was set already. 

I tried the upgrade again and somehow it worked. I don't get it but thank you very much.
