### ISSUE TITLE
Incorrect api update/add item parameters decoding

### ISSUE THREAD

**Issue by spo0okie** [nilsteampassnet/TeamPass#2341]
### Steps to reproduce
1. Use instruction for adding or updating item thru API: &lt;label&gt;;&lt;password&gt;;&lt;description&gt;;&lt;folder id&gt;;&lt;login&gt;;&lt;email&gt;;&lt;url&gt;;&lt;tags&gt;;&lt;any one can modify&gt; send as a series of semicolon separated base64 encoded strings. The separator symbol is the semicolon ;. Each parameter is base64-encoded separately.
2. Get error in response because teampass expect one base64-encoded string of all parameters imploded with semicolon delimiter: $params = explode(';', Urlsafe_b64decode($GLOBALS['request'][2]));

### Expected behaviour
As in instruction teampass must expect each parameter to be encoded separately

$params = explode(';', $GLOBALS['request'][2]);
foreach ($params as $idx => $value) $params[$idx]=Urlsafe_b64decode($value);
- that works

### Actual behaviour
teampass got empty array after explode of empty string after unsucessful base64 decode

$params = explode(';', Urlsafe_b64decode($GLOBALS['request'][2]));

so i got error and nothing happens

if leave all as it is in code and change instruction only to send single base64-encoded string of implode of parameters - we can't send any parameters with semicolon in it, password for example

## platform independent

**Comment by nilsteampassnet** [comment]
Thank you for this.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
