### ISSUE TITLE
Can't browse LDAP users

### ISSUE THREAD

**Issue by itopsmanager** [nilsteampassnet/TeamPass#2342]
### Steps to reproduce
1. Log in as Admin
2. Try to create a user that already exists in Active Directory so I can grant him/her roles.

### Expected behaviour
I would expect Teampass to allow me to grant roles and groups to Active Directory users, but I can not see them in the user list.

### Actual behaviour
When displaying the user list, Active Directory users do not show up. 

### Server configuration
**Operating system**:
Centos 7.5
**Web server:**
Apache 2.4.6
**Database:**
AWS RDS MariaDB
**PHP version:**
PHP 7.2.7
**Teampass version:** 
 2.1.27.16
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
No currently this is not possible.
LDAP users are added only when the user gets logged to Teampass the 1st time.
