### ISSUE TITLE
Disable "Forgot Password?" link feature not working 

### ISSUE THREAD

**Issue by Roger-Amorim** [nilsteampassnet/TeamPass#2347]
### Steps to reproduce
1. Disable showing "forgot password" link feature on LDAP Option
2. Check it On
3. Check login screen.

### Expected behaviour
"Forgot password?" link should been hidden on the login screen

### Actual behaviour
"Forgot password?" link keep showing on the login screen.

### Server configuration
**Operating system**:
Ubuntu 16
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
PHP 7.0
**Teampass version:** 
2.1.27.16
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome/Firefox
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Confirmed.
Fix will be provided.
