### ISSUE TITLE
Unable to tie TeamPass with LDAP

### ISSUE THREAD

**Issue by mzakhan** [nilsteampassnet/TeamPass#2348]
Hey Nils,

I am facing issues while hooking up LDAP users authentication with TeamPass.  I tried doing so with both LDAP server types (_Search Based and Non Search Based_). It throws messages **“No such object”** and **“Not possible to get connected with this user”**. In point of fact,  the user with which I am authenticating does exist into LDAP and working well with other applications. 

Can you please confirm what could be the reason here. Appreciate your response in this regards.

Thanks!
Zohaib

### Expected behaviour
Teampass should authenticate users with LDAP

### Actual behaviour
LDAP users aren't authenticating with LDAP thru TeamPass

### Server configuration
**Operating system**: CentOS Linux release 7.2.1511

**Web server:** httpd-2.4.6-40.el7.centos.4.x86_64

**Database:** Server version: 5.5.50-MariaDB MariaDB Server

**PHP version:** PHP 5.6.36

**Teampass version:** TeamPass 2.1.27.16

### Client configuration
**Browser:** Google Chrome

**Operating system:** : Microsoft Widows 7

### Logs
![image](https://user-images.githubusercontent.com/41421686/42931642-aeb3bfbe-8b59-11e8-9268-d61f71b42707.png)

**Comment by mzakhan** [comment]
Please update.

Thanks!

**Comment by nilsteampassnet** [comment]
Can't you use OU to distingues the multiple entities?

**Comment by ozawa-hi** [comment]
There's a bug in the LDAP page's "Test current configuration".
When using OpenLDAP, leave the "LDAP account suffix for your domain" empty.
This will cause the test to fail, but I've found that users on LDAP will actually be able to login to TeamPass.
