### ISSUE TITLE
Recommendation for password import

### ISSUE THREAD

**Issue by fbrokanlou** [nilsteampassnet/TeamPass#2352]
Hi
I newly installed TeamPass 2.1.27.16 and everything works fine. Now I need to import old passwords which are stored in a database. 
These old passwords are belong to different directories (a tree of folders/sub_folders). 
Columns of the Password's Table:  Pass_ID, Folder_ID, Login_Name, Password, Description
Columns of Folder's Table: Folder_ID, ParentFolder_ID, Folder_name, Description

This old database contains 150 top level folders (level 0), each including between 5 to 50 subfolders (level 1). and Each of this subfolders has about 1 to 20 passwords.

Current feature of importing passwords in TeamPass works per folder, which means I have to create all folders and subfolders manually first, then repeat importing passwords into each folder via separate csv files.

Is there any efficient and automated way to do this, please? Any feedback is appreciated.
Best,

**Comment by nilsteampassnet** [comment]
No currently such approach is not possible.
I don't see any other way than creating manually the folder structure and import the items by csv through the GUI.
But you can program this using the API.

**Comment by fakhraddinJ** [comment]
Hi Nils
**Using API now I can read folders and items.** but adding items/folders not working.  I get following responses when try adding:

- adding folder: {"err":"No data exists","code":"NO_DATA_EXIST"}
- adding item: {"err":"Item definition not complete"} 

I have checked URL and parameters carefully, but still get these errors. I have added screenshots to this post.
I am using following URL structures (as mentioned [here](https://teampass.readthedocs.io/en/latest/api/api-write/)):

- **for adding folders:** <url to teampass>/api/index.php/update/folder/<folder_id>/<title>;<complexity_level>;<renewal_period>?apikey=<valid api key>
- **for adding items:** <url to teampass>/api/index.php/add/item/<label>;<password>;<description>;<folder id>;<login>;<email>;<url>;<tags>;<any one can modify>?apikey=<valid api key>

Any feedback is appreciated, please.

![add-folder-teampass-err](https://user-images.githubusercontent.com/10628912/43258883-b41d98be-90d4-11e8-86b4-cc8bfaf67482.jpg)
![add-item-teampass-err](https://user-images.githubusercontent.com/10628912/43258884-b43b98fa-90d4-11e8-90f4-37e82471211a.jpg)

**Comment by nilsteampassnet** [comment]
Great.
Perhaps can you share your work regarding this topic?

**Comment by fakhraddinJ** [comment]
Hi 
I used instructions [here](https://teampass.readthedocs.io/en/latest/api/api-write/) to create new folders and import passwords, automated using python script and curl .

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass from admin settings page and I do not get the option to import in the folder menu. What I do?
