### ISSUE TITLE
I can´t export 

### ISSUE THREAD

**Issue by nacher1894** [nilsteampassnet/TeamPass#2356]
when I try to export I have this problem:

![image](https://user-images.githubusercontent.com/17115086/43407525-472c3d5c-941f-11e8-887e-02898f924200.png)

Teampass 2.1.27 2009-2018

**Comment by nilsteampassnet** [comment]
Please capture the errors --> https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console
