### ISSUE TITLE
Password visible in plaintext without click on the eye icon

### ISSUE THREAD

**Issue by francescovisi** [nilsteampassnet/TeamPass#2359]
### Steps to reproduce
1. click on a folder on the right to list the items
2. select one of the item in the center panel
3. open the developer tools of the browser ( like press F12 on firefox)
4. search for "hid_pw" and get the password
example: `<td>
                        &nbsp;
                        <div id="id_pw" style="float:left; cursor:pointer; width:300px;"><i class="fa fa-eye fa-border fa-sm tip tooltipstered"></i>&nbsp;&nbsp;<i class="fa fa-asterisk"></i>&nbsp;<i class="fa fa-asterisk"></i>&nbsp;<i class="fa fa-asterisk"></i>&nbsp;<i class="fa fa-asterisk"></i>&nbsp;<i class="fa fa-asterisk"></i></div>
                        <input id="hid_pw" value="password1" type="hidden">
                        <input id="pw_shown" value="0" type="hidden">
                    </td>` the div shows the asterisk but the password is already visible

### Expected behaviour
the password should be requested via AJAX when the eye icon is pressed and simultaneously write the audit log entry

### Actual behaviour
the password is requested before clicking the eye icon and then is visible by view the html source code

### Server configuration
**Teampass version:** latest (2.1.27.16)

**Teampass configuration file:** 
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/2248755/tp.config.php.zip)

**Updated from an older Teampass or fresh install:** NO, FRESH INSTALLED
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** firefox,chrome,all

**Operating system:** windows

**Comment by nilsteampassnet** [comment]
Yes by design it works as you describe.
The proposed solution is the implemented in the future 3.x version.

I will not improve on current 2.x because this is not a security issue as this user has access to the password.

**Comment by francescovisi** [comment]
yes it's not a security issue as you said but i lost the auditing feature because now i'm not 100% sure that some user will see the password without click on the eye icon.

there is any ETA for the 3.x version?

**Comment by nilsteampassnet** [comment]
A beta will be available in October.

Final is expected end of this year.
