### ISSUE TITLE
Show logs without any auth.

### ISSUE THREAD

**Issue by lukasz-schab** [nilsteampassnet/TeamPass#2360]
### Steps to reproduce
1. Go to TeamPass home page (set CPM variable in session)
2. Go to /sources/datatable/datatable.logs.php?action=failed_auth # Or other action 

### Expected behaviour
Hacking atempt information

### Actual behaviour
Every one can see our log.

I think no other information is needed..

**Comment by nilsteampassnet** [comment]
Correct

Thank you

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
