### ISSUE TITLE
Error handler - show error before "encryption"

### ISSUE THREAD

**Issue by lukasz-schab** [nilsteampassnet/TeamPass#2363]
### Steps to reproduce
1. Go to home page
2. Go to TeamPass/sources/datatable/datatable.users.php

### Expected behaviour
Hide error in pseudo encrypted version

### Actual behaviour
Show full error due to 
includes/libraries/Database/Meekrodb/db.class.php:1081 
_echo $params['error'];_

**PHP version:**
5.6

**Teampass version:** 
2.1.27.16 

**Updated from an older Teampass or fresh install:**
Fresh

**Comment by lukasz-schab** [comment]
Pseudo encryption - $_session['key'] is showed on every page loaded. Every one can decrypt such error..

**Comment by nilsteampassnet** [comment]
Thank you for reporting but I don't understand what is the point, can you do a screenshot?

What is the interest to browse on this file?
