### ISSUE TITLE
Incorrect import into personal folder

### ISSUE THREAD

**Issue by bobhydrm** [nilsteampassnet/TeamPass#2367]
### Steps to reproduce
1. Import from KeePass XLM with subfolders into personal folder
2.
3.

### Expected behaviour
In MySQL database .. subfolders in personal folders should have property "personal_folder" set to 1 after import from keepass info "personal folder". 

### Actual behaviour
In MySQL database .. subfolders in personal folders have property "personal_folder" set to 0 after import from keepass. So this folders are incorrectly showed. 

### Server configuration
**Operating system**: Linux vxxxxxxISVScact 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64

**Web server:** Apache/2.4.10 (Debian)

**Database:** 5.5.60-0+deb8u1

**PHP version:** 5.6.36-0+deb8u1

**Teampass version:** 2.1.27.16

**Comment by nilsteampassnet** [comment]
Confirmed

Fix provided

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
