### ISSUE TITLE
API is a vulnerability issue writing passwords.

### ISSUE THREAD

**Issue by rseabra** [nilsteampassnet/TeamPass#2370]
The API has everything as a GET including **writing** new passwords. This patch very quickly adds support to POST.

I've written a short amount of code in #2369 that quickly add support to POST, working around this security vulnerability that would leave passwords easily discoverable on a web server's logs.

Even if not accepted, please fix this issue as it's a very bad issue. BASE64 on top of values hides nothing, really.

**Comment by rseabra** [comment]
The pull request: https://github.com/nilsteampassnet/TeamPass/pull/2369

**Comment by nilsteampassnet** [comment]
Thank you for this discovery.

The proposed idea to add the possibility to use POST is interesting, i will merge this in a first time.

The GET method is also kept but I would encourage users to prevent Apache loging the accesses with specific URL like `https://<teampass>/api/index.php$`.
This could be done using `SetEnvIf` condition.
Something like
````
SetEnvIf Request_URI https://<teampass>/api/index.php$ preventApiLogging
CustomLog teampassApi.log common env=!preventApiLogging
```

Note: Base64 is not used for hiding the exchanged data but to "escape" the data.

**Comment by rseabra** [comment]
You're welcome.

I have some ideas on how to improve it is like to try to do them in the week end.

Eg, in post body have
apikey=....&cmd=...

This way we can get rid of the API key in the access logs as well.

It will probably be time to change API version, at least when the GETs get removed for writing stuff.

Best regards,
Rui

On August 9, 2018 7:15:29 AM GMT+01:00, "Nils Laumaillé" <notifications@github.com> wrote:
>Thank you for this discovery.
>
>The proposed idea to add the possibility to use POST is interesting, i
>will merge this in a first time.
>
>The GET method is also kept but I would encourage users to prevent
>Apache loging the accesses with specific URL like
>`https://<teampass>/api/index.php$`.
>This could be done using `SetEnvIf` condition.
>Something like
>````
>SetEnvIf Request_URI https://<teampass>/api/index.php$
>preventApiLogging
>CustomLog teampassApi.log common env=!preventApiLogging
>```
>
>Note: Base64 is not used for hiding the exchanged data but to "escape"
>the data.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nilsteampassnet/TeamPass/issues/2370#issuecomment-411648706

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
