### ISSUE TITLE
Setting "Number of items to retrieve per query" to Max

### ISSUE THREAD

**Issue by danl18** [nilsteampassnet/TeamPass#2379]
### Steps to reproduce
1. Set "Number of items to retrieve per query" option to max (was set to auto, which was working)
2. log in as a standard user
3.

### Expected behaviour
Should log in without issue
### Actual behaviour
Logs in with a immediate prompt of title "Information" but no contents in pop up window.  Clicking close then goes to the tree view of the password list, of which has no contents under folders and has the label ErrorNaN% as a title for the item list.  Every navigation action makes the information box pop up.

### Server configuration
CentOS 6.10

**Web server:**
Apache/2.2.15

**Database:**
MariaDB/MySQL

**PHP version:**
PHP 7.1.20, have used other versions like 5.6 with the same issue

**Teampass version:** 
2.1.27.17

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh Install
file `/includes/config/tp.config.php`:
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/TeamPass',
    'cpassman_url' => 'https://teampass',
    'favicon' => 'https://teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/TeamPass/upload',
    'url_to_upload_folder' => 'https://teampass/upload',
    'path_to_files_folder' => '/var/www/TeamPass/files',
    'url_to_files_folder' => 'https://teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '',
    'ldap_suffix' => '',
    'ldap_domain_dn' => '',
    'ldap_domain_controler' => '',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '1',
    'anyone_can_modify_bydefault' => '1',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1531756314',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'max',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '30',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/Chicago',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '',
    'can_create_root_folder' => '1',
    'enable_massive_move_delete' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'bck_script_key' => '',
    'ldap_allowed_usergroup' => '',
    'ldap_new_user_role' => '0',
);

### Client configuration
Chrome and IE

**Operating system:**
Windows 10

#### Web server error log
No errors in reference to this issue.  Just SSL cert CA errors cause i am using a self signed
Insert your webserver log here
192.168.100.110 - - [17/Aug/2018:10:42:59 -0500] "GET /includes/js/jquery-ui/images/ui-bg_glass_100_f8f8f8_1x400.png HTTP/1.1" 200 259
192.168.100.110 - - [17/Aug/2018:10:42:59 -0500] "GET /includes/js/jquery-ui/images/ui-bg_inset-hard_75_999999_1x100.png HTTP/1.1" 200 247
192.168.100.110 - - [17/Aug/2018:10:43:00 -0500] "POST /sources/identify.php HTTP/1.1" 200 94
192.168.100.110 - - [17/Aug/2018:10:43:00 -0500] "POST /sources/checks.php HTTP/1.1" 200 1
192.168.100.110 - - [17/Aug/2018:10:43:00 -0500] "POST /sources/identify.php HTTP/1.1" 200 100
192.168.100.110 - - [17/Aug/2018:10:43:00 -0500] "GET /index.php?page=items HTTP/1.1" 200 324293
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 31000
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/select2/css/select2.min.css HTTP/1.1" 200 15180
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/libraries/Authentication/agses/agses.css HTTP/1.1" 200 328
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/nprogress/nprogress.css HTTP/1.1" 200 1458
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/css/passman.css HTTP/1.1" 200 7580
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/radioforbuttons/bootstrap-buttons.min.css HTTP/1.1" 200 15611
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jstree/themes/default/style.css HTTP/1.1" 200 30525
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/multiselect/jquery.multiselect.css HTTP/1.1" 200 1622
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/css/items.css HTTP/1.1" 200 3286
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/multiselect/jquery.multiselect.filter.css HTTP/1.1" 200 325
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jquery-ui/jquery-ui.min.css HTTP/1.1" 200 30044
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jquery-ui/jquery-ui.structure.min.css HTTP/1.1" 200 14769
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jquery-ui/jquery-ui.theme.min.css HTTP/1.1" 200 13794
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/tooltipster/css/tooltipster.css HTTP/1.1" 200 9043
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jstree/jquery.cookie.js HTTP/1.1" 200 4371
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/jstree/jstree.min.js HTTP/1.1" 200 126740
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/multiselect/jquery.multiselect.filter.js HTTP/1.1" 200 6327
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/clipboard/clipboard.min.js HTTP/1.1" 200 10112
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/tinysort/jquery.tinysort.min.js HTTP/1.1" 200 1852
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/verimail/verimail.min.js HTTP/1.1" 200 8461
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/bgiframe/jquery.bgiframe.min.js HTTP/1.1" 200 2537
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/ckeditor/ckeditor.js HTTP/1.1" 200 367851
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/ckeditor/adapters/jquery.js HTTP/1.1" 200 3002
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/js/multiselect/jquery.multiselect.min.js HTTP/1.1" 200 10654
192.168.100.110 - - [17/Aug/2018:10:43:01 -0500] "GET /includes/images/photo.jpg HTTP/1.1" 200 1086
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/images/canevas/fond_items_tree.png HTTP/1.1" 200 482
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/images/canevas/lock_open.png HTTP/1.1" 200 8143
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/images/canevas/tree_lock.png HTTP/1.1" 200 13459
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "POST /sources/main.queries.php HTTP/1.1" 200 640
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "POST /sources/items.queries.php HTTP/1.1" 200 425
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/js/jstree/themes/default/32px.png HTTP/1.1" 200 3121
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/js/jstree/themes/default/throbber.gif HTTP/1.1" 200 1720
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/js/jquery-ui/images/ui-icons_70b2e1_256x240.png HTTP/1.1" 200 4430
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /sources/tree.php HTTP/1.1" 200 2783
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/js/jquery-ui/images/ui-bg_glass_35_dddddd_1x400.png HTTP/1.1" 200 254
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "GET /includes/js/jquery-ui/images/ui-bg_flat_0_eeeeee_40x100.png HTTP/1.1" 200 220
192.168.100.110 - - [17/Aug/2018:10:43:02 -0500] "POST /sources/items.queries.php HTTP/1.1" 200 1128
192.168.100.110 - - [17/Aug/2018:10:43:06 -0500] "POST /sources/main.queries.php HTTP/1.1" 200 61

#### Log from the web-browser developer console (CTRL + SHIFT + i)
[DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"pw1" class=​"input_text text ui-widget-content ui-corner-all simplePassMeterInput" aria-controls=​"pw1_simplePassMeter">​
index.php?page=items:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"pw2" id=​"pw2" class=​"input_text text ui-widget-content ui-corner-all">​
index.php?page=items:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"edit_pw1" class=​"input_text text ui-widget-content ui-corner-all simplePassMeterInput" style=​"width:​390px;​" aria-controls=​"edit_pw1_simplePassMeter">​
index.php?page=items:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"edit_pw2" class=​"input_text text ui-widget-content ui-corner-all" style=​"width:​390px;​">​
jquery.js:631 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery.js:631)
    at showItemsList (index.php?page=items:2515)
    at Object.success (index.php?page=items:2480)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at done (jquery.js:8235)
    at XMLHttpRequest.callback (jquery.js:8778)

**Comment by nilsteampassnet** [comment]
I confirm this issue.

Thanks

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
