### ISSUE TITLE
cannot save changed item

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#2383]
### Steps to reproduce
1. Choose item
2. Edit item
3. Save item

### Expected behaviour
Item was saved

### Actual behaviour
Message "This item already exists!"

### Server configuration
**Operating system:** SLES 12 SP3

**Web server:** Apache/2.4.23 (Linux/SUSE)

**Database:**  mysql  Ver 15.1 Distrib 10.0.35-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:** PHP 7.0.7

**Teampass version:** 2.1.27.19

**Updated from an older Teampass or fresh install:** Updated from 2.1.27.16

**Comment by nilsteampassnet** [comment]
Fixed in Development branch this morning.

**Comment by Rookie1261** [comment]
Is there a date for the next stable version?
