### ISSUE TITLE
Import of .csv file fails when modified to support header with 5 labels. 

### ISSUE THREAD

**Issue by rondmjr** [nilsteampassnet/TeamPass#2384]
### Steps to reproduce
1. Export to .csv from existing server.
2. Modify .csv per instruction for import. Configure .csv for header for 5 columns (`Label` , `Login` , `Password` , `URL` , `Comments`), use commas as field separator 
3. Select Browse CSV File, select file to upload from list. 
4. Receive pop-up Internal Server Error 500.

### Expected behaviour
Migrating from old Teampass server to new server. Exported .csv file to import. Imported data is not aligned in proper fields when imported. Expect import to place fields in .csv into correct fields in TeamPass. 

### Actual behaviour
All data from .csv loaded into Description field. When file is modified per instruction the import fails. 
### Server configuration
**Operating system**:
Ubuntu Server 16.04.5 LST
**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2302635/tp.config.php.txt)

**Database:**
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Teampass version:** 
Teampass 2.1..27.16
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chomium
**Operating system:**
Debian 9
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Can you provide an example of your csv file?

**Comment by rondmjr** [comment]
Good Afternoon,
I've attached the modified file and the original export. I did one folder.
[print_out_csv_1534768134_d025e39df2d65ef.csv(Modified).txt](https://github.com/nilsteampassnet/TeamPass/files/2303217/print_out_csv_1534768134_d025e39df2d65ef.csv.Modified.txt)
[print_out_csv_1534782896_41c740aac7415bf.csv(ORIG).txt](https://github.com/nilsteampassnet/TeamPass/files/2303218/print_out_csv_1534782896_41c740aac7415bf.csv.ORIG.txt)

**Comment by fsamareanu** [comment]
Hello,

This worked for me on .17:

Label,Login,Password,URL,Comments
"mylabel","myuser","supersecretpassword","This is a super secret password (this value is optional)"
"mylabel2","myuser2","cantguessthis","This is an even more secret password (this value is optional)"

**Comment by rondmjr** [comment]
@fsamareanu... Well, I figured everything needed quotes. No quotes in the header. Ok, I a few different options, but not that. Let me give that a whirl. Thanks for the info.

Regards,

**Comment by rondmjr** [comment]
Good Morning All,
Worked like a charm. Sample file loaded. Life is good. No quotes in the header and the file was imported to the correct fields. Thanks.

Regards,

**Comment by fsamareanu** [comment]
I would keep this open as either a documentation fix and/or a request to improve the error message (get something like "incorrect file formatting" instead of a non-descriptive 500.
