### ISSUE TITLE
Admin unable to login Google 2FA enabled

### ISSUE THREAD

**Issue by steven792** [nilsteampassnet/TeamPass#2386]
### Steps to reproduce
1. Login local admin user account and select "I need QR code"
2. Email received and code entered
3. admin can never login

### Expected behaviour
Tell us what should happen

expect to get a QR code to setup google 2FA for first time

### Actual behaviour
Tell us what happens instead

Site just spins at "Please identify yourself" for many minutes before timeout

### Server configuration
**Operating system**:
Linux (AWS Linux 2) 4.14.62-70.117.amzn2.x86_64 #1 SMP Fri Aug 10 20:14:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Web server:**
httpd (apache2.4)

**Database:**
MariaDB 
Server version: 10.2.10-MariaDB MariaDB Server
**PHP version:**
PHP 7.2.5 (cli) (built: May 29 2018 19:08:12)

**Teampass version:** 
2.1.27.19
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

Fresh install
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2312605/tp.config.php.txt)

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox or Chrome
**Operating system:**
MacOS High Sierra
#### Web server error log
```
Insert your webserver log here
```
logs just say user password is wrong... but I disable 2FA and it works fine.
Never get QR code just link to get code sent in email

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by br0c0l1** [comment]
Same exact issue here (described perfectly by Steven) even with a standard non-admin account. Here is what the nginx error logs say:

2018/08/26 15:42:03 [error] 796#796: *1824 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function Authentication\TwoFactorAuth\Providers\Qr\curl_init() in /var/www/html/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php on line 12" while reading response header from upstream, client: [ip address], server: _, request: "POST /sources/identify.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[ip address]", referrer: "https://[ip address]"
