### ISSUE TITLE
Teampass upgrade failed 2.1.26 to 2.1.27 - Missing teampass_keys table

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#2387]
### Steps to reproduce
1. Put team-pass site in maintenance mode
2. Backup current teampass folder
3. Unzip new teampass folder (2.1.27)
4. Copy settings.php, tp.config.php, backups/files/upload folders to new directory
5. Start /install/upgrade.php script.

### Expected behaviour
Upgrade finish all steps

### Actual behaviour
Tell us what happens instead

Upgrade errors and stops here:
16:1:52 - ERROR: Table 'teampass.teampass_keys' doesn't exist
16:01:52 - upgrade_run_encryption_pwd.php - Loop #13 

Upon checking the database it really is missing this table, I couldn't find the DDL for this table online or in the builds anywhere to create it manually so not sure why it is checking for it. It is definetly not in my existing 2.1.26 version database.

Also the upgrade note mentions to backup this file: teampass-seckey.txt  but I don't have this file, not sure if it will cause issues later down the track with the upgrade.

Regards,
Aleks

**Comment by nilsteampassnet** [comment]
What package of 2.1.26 are you using?

**Comment by aleks001** [comment]
I’m not sure, how do I check ? I’veaways just downloaded from the main branch whatever the latest version is. So i would always get a file like Teampass-master.zip instead of teampass-master_2.1.26.11.zip

**Comment by aleks001** [comment]
I have checked this and I'm trying to upgrade from (I believe) 2.1.26-patch-1 to 2.1.27.19

**Comment by aleks001** [comment]
I have found more information on the problem. This seems to only be affecting items in the teampass database that have really long pw strings in the teampass_items table. I'm not sure why we have a bunch of these random long entries.

The upgrade logs gets stuck as follows:
-----
Item : 402
Item is correctly encrypted
No re-encryption needed as passwords already using latest encryption protocol.


-----
Item : 411

And the missing teampass_keys error is displayed in the error log. I actually cant even find these entries in the password tool, it looks like old things that might have been deleted.

As an example
selecting id, label and pw from teampass_items here is an example of a good and bad entry:
**good:**
|  401 | Some_USER   | ccf25745a1128e8335d2cd77e37f4992

**bad:**
|  416 | Bad_User |                                                                                  | Vm82WkxOcHBlNGNnNVdJVkFrdlc5aThKQjlDK0krOUd1MVBTMHUzT3Fpb03BDdbC65WN2weqZmQ1ZTc3NGFkY2JhNzE5MDE3NTBlMGIxYWE4NTI2NjExMjU4M2ExNWJlNDQ0YjRmNzRhMmQwOGY0ZWYxM2FjYWNmZzdndXVpZmxmZms1YXgxMWt1emJmeDd0M3p5Z25pbmxwaWt5NjhjZjc0cDF0M3Z1OXkxZGJ4YnRrN3VyY2c=
