### ISSUE TITLE
Option to use the login password as personal salt key

### ISSUE THREAD

**Issue by Shimonojo** [nilsteampassnet/TeamPass#2388]
### Steps to reproduce
1. Install TeamPass
2. Configure LDAP 
3. Insert this code : https://github.com/nilsteampassnet/TeamPass/pull/361/commits/ecae58da4b7d82f605554b52046495206cbd4a34

### Expected behaviour
Use the login password as personal salt key

### Actual behaviour
The option does not work, 

### Server configuration
**Operating system**: Windows Server 2008 R2

**Web server: XAMPP Version: 7.2.5

**Database: PhpMyAdmin Version : 4.8.0.1

**PHP version:  7.2.5 

**Teampass version: 2.1.27.16

**fresh install

**Comment by nilsteampassnet** [comment]
I don't know what is this commit.
At least not performed by me and is very old.
It is not a good idea to do this in an case as if you change the password then it will not propagate the change inside the  personal items which will brake the encryption password.

**Comment by Shimonojo** [comment]
Good morning,

Okay, thanks for that answer, 

Users want direct access to their directories without using a personal salt key, 

I only found three solutions: 

- Use the login password as personal salt key

- Create a role and a file for each person

- Remove personal salt key but I don't think it's possible 

Thank you again, 

Have a nice day,
