### ISSUE TITLE
Search item/folders with API using label

### ISSUE THREAD

**Issue by samamuel** [nilsteampassnet/TeamPass#2392]
### Expected behaviour
Possibility to get the ID of an item or folder using a label throw API search

### Actual behaviour
You can only search item using ID of a folder or item, but if you don't now the ID of your folder/item you are blocked. Otherwise, as you don't show subfolders (issue #2307 ) it's complicated to navigate with API in a complexe tree folder

### Server configuration
**CentOS 7**:

**Web server:**
httpd
**Database:**
Maria DB

**PHP version:**
PHP 7
**Teampass version:** 
2.1.27.10

**Comment by nilsteampassnet** [comment]
Yes sure.
Keep in mind that the returned item ID may have those characteristics:
- several items may share a part of the same label --> the return should be in array format
- check that user is allowed to access the find item

Send the PR once you have initiated a change on 'development' branch

Thanks
