### ISSUE TITLE
php warning in logs

### ISSUE THREAD

**Issue by fsamareanu** [nilsteampassnet/TeamPass#2395]
### Steps to reproduce
1. Login in TeamPass 2.1.27.20
2. Check error log
3. You'll find a notice saying PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://url/index.php

### Expected behaviour
Tell us what should happen
No notice should be in the logs
### Actual behaviour
Tell us what happens instead
Notice appears in the logs
### Server configuration
**Operating system**:
RHEL 7.5
**Web server:**
httpd-2.4.6-80.el7_5.1.x86_64
**Database:**
mariadb-server-5.5.60-1.el7_5.x86_64
**PHP version:**
php 7.2
**Teampass version:** 
2.1.27.20
**Teampass configuration file:**
Not needed
**Updated from an older Teampass or fresh install:**
Upgraded from 2.1.27.16
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Not needed
### Client configuration
**Browser:**
Chrome 68.0.3440.75
**Operating system:**
Windows 10
#### Web server error log
```[Mon Aug 27 11:01:34.357137 2018] [php7:notice] [pid 5168] [client 10.15.5.236:62646] PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://teampass.domain/logout.php?user_id=9999994
[Mon Aug 27 11:01:40.364150 2018] [php7:notice] [pid 5169] [client 10.15.5.236:62654] PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://teampass.domain/index.php
[Mon Aug 27 11:04:48.948338 2018] [php7:notice] [pid 5167] [client 10.15.5.236:62920] PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://teampass.domain/logout.php?user_id=1
[Mon Aug 27 16:34:15.800162 2018] [php7:notice] [pid 5167] [client 10.15.5.236:62678] PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://teampass.domain/index.php
[Mon Aug 27 16:37:19.586800 2018] [php7:notice] [pid 5169] [client 10.15.5.236:63075] PHP Notice:  Undefined index: pwComplexity in /var/www/html/index.php on line 945, referer: https://teampass.domain/logout.php?user_id=1
```
Insert your webserver log here
```10.15.5.236 - - [27/Aug/2018:16:36:26 +0400] "GET /includes/js/jquery-ui/images/ui-bg_glass_100_f8f8f8_1x400.png HTTP/1.1" 200 259
10.15.5.236 - - [27/Aug/2018:16:37:19 +0400] "GET /logout.php?user_id=1 HTTP/1.1" 200 192
10.15.5.236 - - [27/Aug/2018:16:37:19 +0400] "GET /index.php HTTP/1.1" 200 73983
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Could not reproduce but I will robustify this.
