### ISSUE TITLE
LDAP not working since update to 2.1.27.17

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#2397]
I do not see any try to connect to LDAP server with TCPdump and I get this error in failed login log:

Date | Label | User
28/08/2018 10:28:39 | user_password_not_correct - myuser | 1.1.1.1

Using the "Test current configuration" on LDAP configuration page I get an error "No user credentials"

With "Teampass local users only" If I disable LDAP authentication user is able to log in with local credentials, with LDAP authentication enabled it doesn't log in with any password (local or ldap)

Without "Teampass local users only"  If I disable LDAP authentication user is able to log in with local credentials, with LDAP authentication enabled it doesn't log in with any password (local or ldap)

There are no errors in apache log.

**Comment by alarido** [comment]
I have been trying to change all ldap configurations one by one and I got an error with the port, so I decided to look if there where configuration in the DB for the ldap_port and it wasn't there so I inserted it:

insert into misc (increment_id,type,intitule,valeur) values ('11111111', 'admin','ldap_port','1111')

Thing is that GUI was showing a port configured, but it wasn't in the database.

Once ldap_port was inserted in the database it started working again.

**Comment by alexpnvieira** [comment]
I have the same problem!

I am using version 2.1.27.20 and the LDAP AD integration does not work.

I did the communication tests and the result was positive. but when I tried to access the main login page the authentication was failed.

How can I fix this?

Tanks in advanced.

--------------------------------------------------
Bellow result of teste LDAP connection
--------------------------------------------------

Get all ldap params:
- base_dn : DC=xxxxxx,DC=local
- account_suffix : @xxxxxx.local
- domain_controllers : xxxxxx.local
- ad_port : 389
- use_ssl : 0
- use_tls : 0
*********
Create new adldap object : Success

After authenticate : Success

ldap status : Successfull

**Comment by alarido** [comment]
I just tried to upgrade from my previous version to 2.1.27.20 directly and adding the ldap port to the misc table works for me.

My problem was no connection to ldap server was made, checked with a packet capture in teampass server, "Test current configuration" wasn't working also, if test is working for you then problem is different from mine, but there are already some tickets about AD/LDAP problems in other issues with workarounds:

https://github.com/nilsteampassnet/TeamPass/issues/2368
https://github.com/nilsteampassnet/TeamPass/issues/2377

**Comment by fsamareanu** [comment]
@alarido: to clarify, are you using a custom LDAP port? I tried replicating your issue on a fresh install and I'm not able to reproduce with standard ports (ssl and non-ssl).

**Comment by alarido** [comment]
No, I was using a default port, sorry for the 1111 it was just an example.

The "ldap_port" entry in "misc" table didn't exist and without it once I finished upgrade from 2.1.27 to 2.1.27.17 or 2.1.27.20 LDAP authentication didn't work, just inserting this row into the database made it work again and fix the problem.

It's really really strange. My theory is that in older versions if row does not exist it uses default port, but on one of the new versions if checks the row, if it exists but is empty uses default port, if it exists and has a value uses the value, but if it doesn't not exists there is an exception and authentication fails.
