### ISSUE TITLE
New LDAP account has full access when they log in for the first time

### ISSUE THREAD

**Issue by Feydib** [nilsteampassnet/TeamPass#2401]
### Steps to reproduce
1. Configure LDAP Authentication with a default role that contains no access to folders
2. Log in with a LDAP user
3. You can see the whole tree  and passwords
4. Log out, then log in again. User has fall under his role and see only folders that he is authorized to access

### Expected behaviour
At the first login, the user must not see all folders and password. This is a security issue

### Actual behaviour
The user should get access rights defined by the default role

### Server configuration
**Operating system**:
CentOS  7.5.1804
**Web server:**
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.20
**Database:**
5.5.56-MariaDB
**PHP version:**
7.1.20
**Teampass version:** 
2.1.27 master branch
**Teampass configuration file:**
    'ldap_mode' => '1',
    'ldap_type' => 'posix-search',
    'ldap_suffix' => '@dc=my,dc=domain,dc=local',
    'ldap_domain_dn' => 'OU=Users,OU=Enterprise,DC=my,DC=domain,DC=local',
    'ldap_domain_controler' => 'ldap.my.domain.local',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => 'OU=Users,OU=Enterprise,DC=my,DC=domain,DC=local',
    'ldap_port' => '389',

**Updated from an older Teampass or fresh install:**
Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Tested with IE 11.2363 and Chrome 68.0.3440.106
**Operating system:**
Windows 10 Pro
#### Web server error log
No web error

Insert your webserver log here
Nothing interesting as user correctly log in

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
How strange.
This is an old bug that was solved and no change was done on authentication feature.
I'm very surprised. What is the complete release installed on your server?

**Comment by Feydib** [comment]
I downloaded the master branch. I get exact version is 2.1.27.19 which is shown at the bottom of the home page...

**Comment by Feydib** [comment]
I just upgraded to the latest Tag release (2.1.27.21) and unfortunately I fall exactly under the same problem.

**Comment by pathim** [comment]
I have the same problem using the docker image (version 2.1.27.21).
After a new ldap user logs in there are some entries in the teampass_items table that have the "perso" entry set to 1. Which entries are affected seems to be random.
Also the problems seems to go away if I disable personal passwords.

**Comment by toorzilla** [comment]
Duplicate/return of #1677 , indeed... This is huge :/

**Comment by Feydib** [comment]
Hi,
Just tested to remove personal folder option and I confirm that it "fix" this problem. Until this bug is resolved, this is a workaround...

**Comment by nilsteampassnet** [comment]
So sad!

I need to reinvestigate but thank you for pointing out this workarround, it gives also a new hint for investigation.

**Comment by nilsteampassnet** [comment]
I think I have fixed this issue.

Commit is done in 2.1.27.24

**Comment by thefirstben** [comment]
Hello,

We are having the same problem here in the latest version : 2.1.27.36 (not a fresh install).
A new LDAP user on his first connection (and first connection only), sees all personal folders, the encrypted content is not seen, but name, description etc. are seen.
