### ISSUE TITLE
Update 2.1.20 -> 2.1.27 not working

### ISSUE THREAD

**Issue by steffenabel** [nilsteampassnet/TeamPass#2402]
### Steps to reproduce
I'm trying to upgrade from 2.1.20 to the current version.
During the upgrade process the upgrade hangs on "upgrade_run_defuse_for_pwds.php - loop #1 is now running".
The server logs show an error, see below.
I suppose that the problem is the missing teampass-seckey.txt file. 
I dont have this file, the old version didn't need it.
If i create this file and fill it, the error is slightly different, but it still exists.

### Expected behaviour
The upgrade proceeds.

### Actual behaviour
The upgrade hangs, the server logs show this error:

PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /var/www/vhosts/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /var/www/vhosts/teampass/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF0\\x00\\x00', false)\n#1 /var/www/vhosts/teampass/sources/main.functions.php(386): Defuse\\Crypto\\Key::loadFromAsciiSafeString(false)\n#2 /var/www/vhosts/teampass/install/upgrade_run_defuse_for_pwds.php(121): cryption('', false, 'encrypt')\n#3 {main}\n  thrown in /var/www/vhosts/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168,

### Server configuration
**Operating system**:
Debian 7.11

**Web server:**
Apache 2

**Database:**
Mysql 5.5

**PHP version:**
PHP 5.6

**Teampass version:** 
2.1.20 to 2.1.27

**Comment by nilsteampassnet** [comment]
You need to upgrade version by version until being in 2.1.26 latest.
Then you can go to latest 2.1.27 as only since this version the upgrade is "cumulative"

**Comment by steffenabel** [comment]
Upgrading through all the versions worked.
I had some issues in each version, but finally I'm at the newest version.
Thanks.
