### ISSUE TITLE
You are not allowed to do that!

### ISSUE THREAD

**Issue by alexpnvieira** [nilsteampassnet/TeamPass#2407]
### Steps to reproduce
1. Add the item - It's ok!
2. When I click in edit (pencil icon) error appears. 
3. Error message "You are not allowed to do that!"

### Expected behaviour

Delete or edit item with sucessfull.

### Actual behaviour
Error during delete or edit item.

### Server configuration
**Operating system**:

CentOS Linux release 7.5.1804 (Core)

**Web server:**

Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59

**Database:**

 5.5.60-MariaDB 

**PHP version:**

PHP 5.6.37

**Teampass version:** 

2.1.27.20

**Teampass configuration file:**

> <?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/TeamPass',
    'cpassman_url' => 'http://xx.xx.xx.xx',
    'favicon' => 'http://xx.xx.xx.xx/favicon.ico',
    'path_to_upload_folder' => '/var/www/TeamPass/upload',
    'url_to_upload_folder' => 'http://xx.xx.xx.xx/upload',
    'path_to_files_folder' => '/var/www/TeamPass/files',
    'url_to_files_folder' => 'http://xx.xx.xx.xx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@chupa.local',
    'ldap_domain_dn' => 'DC=chupa, DC=local',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '1',
    'anyone_can_modify_bydefault' => '1',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '1',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '1',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1532909578',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'Ln9K8a3UmqvZG3YvdPYg7rsUYTY3eNdTX7GsPGPQ',
    'enable_massive_move_delete' => '1',
    'can_create_root_folder' => '1',
);

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

Firefox 61.0.2 (64-bit)

Chrome Versão 68.0.3440.106 (Versão oficial) 64 bits

**Operating system:**

Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by asantar0** [comment]
I have the same problem! Exactly. @alexpnvieira

**Comment by asantar0** [comment]
@nilsteampassnet Could you see this bug in detail?

**Comment by asantar0** [comment]
Assign permission to anyone to edit the items and the same message continues to appear. 
![screen](https://user-images.githubusercontent.com/24227371/50560647-a9f39a80-0ce1-11e9-9761-1cbe4b31139b.png)

**Comment by nilsteampassnet** [comment]
Does this appear on personal or public items?
Does this happens on all items?
What operation was performed on this item before this occurs?
Please provide details on how to reproduce with details? what are the rights of the user on the folder in which the items were created?
Thank you

**Comment by asantar0** [comment]
> Does this appear on personal or public items?
> Does this happens on all items?
> What operation was performed on this item before this occurs?
> Please provide details on how to reproduce with details? what are the rights of the user on the folder in which the items were created?
> Thank you

@nilsteampassnet 
1. Appear in public items
2. Yes. This happens on all items.
3. No operation was performed previously. The only thing that was done was the creation of the item.
4.The right of the users is the Manager for all
![screenshot_20190109_095133](https://user-images.githubusercontent.com/24227371/50900594-6e00b980-13f4-11e9-807c-26f66b06ec0f.png)
  The items was created for the same user.

Regards!

**Comment by nilsteampassnet** [comment]
Can you please start but installing the last version?
Then we will go deeper in investigation

**Comment by asantar0** [comment]
Hi @nilsteampassnet! With the last version work perfectly. What is still not working is the remote change of keys to servers. 
https://github.com/nilsteampassnet/TeamPass/issues/2126

Thank you.

Regards

**Comment by baydeniz1** [comment]
After upgrading to 3.0.1 latest, I can not Edit any old items. No problem on New Item + edit and saving.

But Old Items are can not be changed by any user.

**Comment by baydeniz1** [comment]
+ I just noticed that all the Passwords on Old Items are gone.
