### ISSUE TITLE
Password complexity not enforced

### ISSUE THREAD

**Issue by SergeDV** [nilsteampassnet/TeamPass#2408]
### Steps to reproduce
1. regular user, no manager permissions
2. create an item in a folder that has "Medium" as minimal password complexity and options to create or update passwords that do not meet minimal password complexity requirements are both set to "No"
3. enter a simple password in the password field ("Very weak")
4. save the new item: the simple password is accepted

### Expected behaviour
The user should not be allowed to save the new item and receive a message that the password complexity is not met

### Actual behaviour
The new item is accepted and saved

### Server configuration
**Operating system**: 
SUSE Linux Enterprise Server 12 SP2
**Web server:**
apache2-2.4.23-29.6.1
**Database:**
mysql-community-common-5.7.16-1
**PHP version:**
php5-5.6.34-1.1
**Teampass version:** 
2.1.27.21
**Teampass configuration file:**
**Updated from an older Teampass or fresh install:**
Update
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Waterfox 56
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2361248/tp.config.php.txt)
![tp1](https://user-images.githubusercontent.com/40470858/45223611-fee54e00-b2b7-11e8-90bb-3620ffc431ef.png)
![tp2](https://user-images.githubusercontent.com/40470858/45223610-fee54e00-b2b7-11e8-95ae-ceba6c219dae.png)

**Comment by nilsteampassnet** [comment]
I need to investigate.

**Comment by nilsteampassnet** [comment]
After investigation, it only happens if you have enabled option "Allow item to be created without any password defined".
I need to improve by adding a complementary test if the password field is populated.

**Comment by SergeDV** [comment]
Hello Nils,

Thank you very much for your quick reaction and for the resolution of this problem.

Greetings

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
