### ISSUE TITLE
Updating 2FA for DUO Security is cutting off last letter of IKEY, SKEY and HOST

### ISSUE THREAD

**Issue by phaelon74** [nilsteampassnet/TeamPass#2412]
### Steps to reproduce (Fresh Install)
1. Login to Teampass as Admin
2. Go to Settings
3. Enable 2FA with DUO Security
4. Log out of Admin, and then in with a user and Duo Security will work
5. Log back in as admin, remove it, log out
6. Log in as a brand new user with DUO security 2FA disabled, then log out
7. Log back in as admin, re-enable 2FA
8. Click save SK.php
9. Generate new AKEY
10. Click Save SK.php
11. Log out
12. Log back in as a user with DUO Security
13. Error happens
14. Login as Admin, and in 2FA last digit is being cut off all three

### Expected behaviour
Pass through to Duosecurity should happen

### Actual behaviour
this error:
"ERROR The application secret key passed to sign_request() must be at least 40 characters.
DUO Security authentication is loading ... Please wait. "

### Server configuration
**Operating system**: Linux - Ubuntu 16.04

**Web server:** - Apache 2

**Database:** MySQL

**PHP version:** 7.0

**Teampass version:** 2.1.27.22

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox and Google Chrome

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Looking in the Firefox Web Developer Console, looks like something is busted in the Teampass code when you execute in this way:

{…
error: "
misc: "1 ; 1
<prototype>: {…}
__defineGetter__: function __defineGetter__()
__defineSetter__: function __defineSetter__()
__lookupGetter__: function __lookupGetter__()
__lookupSetter__: function __lookupSetter__()
constructor: function Object()
hasOwnProperty: function hasOwnProperty()
isPrototypeOf: function isPrototypeOf()
propertyIsEnumerable: function propertyIsEnumerable()
toLocaleString: function toLocaleString()
toSource: function toSource()
toString: function toString()
​​
valueOf: function valueOf()
jquery.js line 612 > eval:195:17
{"akey":"REMOVED", "ikey":"REMOVED", "skey":"REMOVED", "host":"REMOVED"}
```
Here's the consed one:
Object { error: "", misc: "1 ; 1" }
jquery.js line 612 > eval:195:17
{"akey":"REMOVED", "ikey":"REMOVED", "skey":"REMOVED", "host":"REMOVED"}

**Comment by nilsteampassnet** [comment]
Thank you for your report.

I will check this and come back with a fix if needed.

**Comment by nilsteampassnet** [comment]
So I've tried but couldn't reproduce even by following strictly your protocol.

THis is from the admin page
![image](https://user-images.githubusercontent.com/1197546/45703014-7e560580-bb73-11e8-99a2-aa2539e47a87.png)

This is what is written in the sk.php file
![image](https://user-images.githubusercontent.com/1197546/45703074-9ded2e00-bb73-11e8-9c53-77670f8d101a.png)

I don't see any deviation or string truncation.

Perhaps you could show me this with a screensharing session?

**Comment by phaelon74** [comment]
Thank you so much @nilsteampassnet for looking into this.  I blew that VPS away to rebuild and utilize Google Authenticator instead.  I never got google authenticator working cause I didn't have email setup.  I have Google Authenticator working now, so I don't want to mess with my newly built rocking box.

Let's do this, close this one and I will stand up an additional VPS and see if I can get this broken again.  If I do I'll come back to this thread and reopen it.  Sounds good?

**Comment by nilsteampassnet** [comment]
Yes this is good for me.

**Comment by nmatese** [comment]
I am having this exact issue when trying to configure Duo 2FA

**Comment by davidcustard** [comment]
Me too. I just opened a new issue.
