### ISSUE TITLE
Teampass not logging user login correctly

### ISSUE THREAD

**Issue by g3l0l4** [nilsteampassnet/TeamPass#2413]
### Steps to reproduce
1. Click at Views button
2. Click at Logs
3. Click at Connections

### Expected behaviour
I should be able to view recent connections

### Actual behaviour
There are only 26 items and they are from april.

### Server configuration
**Operating system**:
Suse linux 12.1
**Web server:**
Apache 2.4
**Database:**
Mysql 14.14
**PHP version:**
PHP 7.1.8
**Teampass version:** 
2.1.27.22

### Client configuration
**Browser:**
Mozilla Firefox
**Operating system:**
Windows 10
#### Log from the web-browser developer console (CTRL + SHIFT + i)
No error thrown...
sources/datatable/datatable.logs.php?action=connections&token=*********Echo=1&iColumns=3&sColumns=,,&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=desc&iSortingCols=1&_=1537511274003

**Comment by nilsteampassnet** [comment]
Is the option enabled?

![image](https://user-images.githubusercontent.com/1197546/46032164-2a12ce80-c0fb-11e8-864b-e128b7698c05.png)

**Comment by g3l0l4** [comment]
OMG so sorry about my incompetence, I understood a different meaning in my language... that solved the "problem"
