### ISSUE TITLE
Problem with single search result

### ISSUE THREAD

**Issue by aszhitarev** [nilsteampassnet/TeamPass#2414]
Hello! Thanks for product! But i have a problem with a search result.
Technical enviorment:
OS: Windows server 2008 r2
WebServer: apache 2.4.34
PHP:  5.6.29
MySQL: 5.5.5-10.1.34-MariaDB
TeamPass: 2.1.27

Client environment:
OS: Windows 7 pro 64
Browser: Google chrome 69, Internet Explorer 11

Steps for problem:
1 - login as user
2 - click on search panel
3 - write search query
4 - important! we must get one result of search! i.e. in list of result one item.
5 - item of list not select by clicking
if elements in list more than one, then both elements selecting

**Comment by nilsteampassnet** [comment]
Sorry I don't understand.

Can you please perform screenshots to explain the problem?

**Comment by aszhitarev** [comment]
Thank for reply!
Ok? let's try
![image](https://user-images.githubusercontent.com/27902084/46064233-8fa4a080-c177-11e8-8ed0-ce8965c4aace.png)
we have a entry, ok?

And then let's try to search
![image](https://user-images.githubusercontent.com/27902084/46064391-ead69300-c177-11e8-967a-3210295a3442.png)

Found! Cool! But i can't to click on this item!

If in search result more than one result, they selecting
![image](https://user-images.githubusercontent.com/27902084/46064522-47d24900-c178-11e8-8e31-f2b6b69d1618.png)

I hope you understanding me
