### ISSUE TITLE
Search function cant find anything if the string is stored in URL field

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#2417]
### Steps to reproduce
1. Create new item and store something in filed URL, like
URL : | http://www.example.com
2. Search the string "example" in the upper right box "Search"
3. Cant find anything

### Expected behaviour
I cant find result

### Actual behaviour
No result found

### Server configuration
**Operating system**:
Windows 2008 R2

**Web server:**
Apache 

**Database:**
mysql

**PHP version:**
5.6

**Teampass version:** 
2.1.27.22

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I followed what you wrote but couldn't reproduce.

![image](https://user-images.githubusercontent.com/1197546/45964531-5f012180-c026-11e8-8ff0-203206145e71.png)

Can you try to connect as admin and do the next
![image](https://user-images.githubusercontent.com/1197546/45964588-86f08500-c026-11e8-9d40-18d658dfe12c.png)

Then connect with you user account and try again.

PLease tell us the result.

**Comment by antoweb** [comment]
Ok. Sorry after open the item then re-save it the search works good. Thanks for help.
