### ISSUE TITLE
Integrate Audit logs with SIEM

### ISSUE THREAD

**Issue by Jorixine** [nilsteampassnet/TeamPass#2421]
Hi!

Actually this is not an issue nor a bug.

I just installed the tool and we really like it. We are looking forward to integrate the logs to our SIEM system.
It is able to reach the DB with JDBC so my thinking is:
Creating a view that contains both administrative and password/items related information.

Is this already solved ? I searched through the tickets but didn't find anything.

Would be great for a feature request as well. I assume more than one of you is using a SIEM and having these events in it could give us great added value.

Thanks!

**Comment by fsamareanu** [comment]
We use IBM Qradar as SIEM tool and we send audit events to it via syslog setting in teampass.

**Comment by Jorixine** [comment]
hey fsamareanu!

Actually I am a QRadar Specialist....

As far as I've seen the configuration only allows you to send **errors** via syslog. Is there any other config I haven't seen?

I've been working on this and created a view with the data for tp_log_items and checking the table tp_log_system I see that the data structure is not quite nice... So created a script (I am a poor programmer anyway) that will read the data and create another table with the data in the correct places and with human readable date and information.

Let me know if you have found another configuration I might have missed to send ALL audit data to QRadar (items information and login/logout/user creation/modification/etc).

If someone wants to see what I have done please tell me and I'll share my work.

**Comment by fsamareanu** [comment]
Howdy. Each logon, password reveal is sent to local syslog which we then forward to our @siem_ip. I don't remember doing anything special at all in the app.

**Comment by Jorixine** [comment]
Great!

I'll have a look at that as well... Did you create a Custom DSM ?

**Comment by fsamareanu** [comment]
The Qradar part is beyond me as that's managed by our Security team. I just send the logs :)
I'll post my teampass config tomorrow if you still need it. Let me know.

**Comment by Jorixine** [comment]
I just verified, you are correct... It sends everything that is in the DB.

I thought it only send errors since in the config says 'send errors to syslog server'.

Gonna create a DSM for it and will ditch the work I've done the past two days :D

**Comment by fsamareanu** [comment]
You should probably close this then. Happy monitoring :)
