### ISSUE TITLE
Access to password item denied!  when a new ldap user login

### ISSUE THREAD

**Issue by lxm065** [nilsteampassnet/TeamPass#2422]
### Steps to reproduce
1.Configure LDAP Authentication
2.login a user (A) create some items and passwords,the items are green.(A can see his items)
3.one day after,a new user (B) login from ldap.
4.then the items  created by A,now turn from green to orange(A can't see the passwords any more),"Access to password item denied!"

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
CentOS Linux release 7.4.1708
**Web server:**
httpd
**Database:**
mysql
**PHP version:**
PHP 7.2.10
**Teampass version:** 
TeamPass-2.1.27.23
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
chrome
**Operating system:**
win10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Skouat** [comment]
I encounter the same issue.
And thanks to you... now I understand why all my passwords are denied.
What type of LDAP do you used?

**Comment by Skouat** [comment]
If we export a folder, all passwords are exported with any issue.
After that it is possible to delete and import the folder in order to recover access to all exported items.

@nilsteampassnet if you have some clues, I can check on it.
