### ISSUE TITLE
Unable to import keepass XML (Can't read the file! It must be a KeePass file.)

### ISSUE THREAD

**Issue by xanox1** [nilsteampassnet/TeamPass#2423]
### Steps to reproduce
1. Export keepass XML2.x from keepass (version 2.35)
2. Try and import the XML

### Expected behaviour
The file should be uploaded and imported

### Actual behaviour
The following error appears: 
Can't read the file! It must be a KeePass file.

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.0.32 (cli) (built: Sep 11 2018 13:20:19) ( NTS )

**Teampass version:** 
TeamPass 2.1.27.23

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/2427953/tp.config.txt)

**Updated from an older Teampass or fresh install:**
Fresh install

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 

**Operating system:**
Windows 10

#### Web server error log
```
No errors in error log.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
If you need any more info please let me know, I'm happy to provide.

**Comment by nilsteampassnet** [comment]
Just tested, and could not reproduce.
Keepass exported file has been generated with 
![image](https://user-images.githubusercontent.com/1197546/46222505-d6012780-c350-11e8-955f-1cb37f361600.png)
Are the rights correctly set on folder `files`? Indeed this error may be generated if Apache can't upload the file inside this folder.

**Comment by xanox1** [comment]
Thanks for checking. 

I did actually use that way of exporting the file. The file is quite large tho, 25MB. 
I have adjusted the config so it will accept the file but then I got this error.

About the rights:
I think so, the permissions on the files folder are as following:
drwxrwxrwx.  2 apache root   4096 Sep 28 13:41 files

Is there a way to find out why it does not accept the file in more detail?

I will test with a clean database with just a couple of entries at the root to see if it has to do with the complicity of the way the database is set up with all the subfolders in it.

**Comment by xanox1** [comment]
Oh, it seems it does accept the test database just fine.

Is there a restriction on what items are allowed (attachments, amount of subfolders) or a limit to the number of items? 

Thanks for any help in this.

**Comment by 80kk** [comment]
> Oh, it seems it does accept the test database just fine.
> 
> Is there a restriction on what items are allowed (attachments, amount of subfolders) or a limit to the number of items?
> 
> Thanks for any help in this.

I am afraid that this is normal behaviour of TeamPass import tool. I had the same issue in the past on my beginning with TeamPass, but my Keepass import/export file was 45MB big. Also I have tried to change max_upload_file_size, tricks with php configuration but with no luck. Later I found that if you export Keepass in small chunks like 10MB/each then Keepas will import them.

**Comment by nilsteampassnet** [comment]
Have you change the max size in Teampass?

![image](https://user-images.githubusercontent.com/1197546/46426030-a893ef80-c73d-11e8-950b-49131bee0bd5.png)

**Comment by 80kk** [comment]
> Have you change the max size in Teampass?
> 
> ![image](https://user-images.githubusercontent.com/1197546/46426030-a893ef80-c73d-11e8-950b-49131bee0bd5.png)

Of course. I started from that. For some reason it won't import files bigger than. I don't know where is the limit, but I found that it is able to import Keepass in smaller chunks.
