### ISSUE TITLE
failed upgrade from 2.1.27.10 to 2.1.27.23

### ISSUE THREAD

**Issue by Shert** [nilsteampassnet/TeamPass#2424]
### Steps to reproduce
1. upgrade from 2.1.27.10 to 2.1.27.23
2.
3.

### Expected behaviour
login should give no error and folders/objects should be shown

### Actual behaviour
login gives an error and folders/objects are not displayed

### Server configuration
**Operating system**: Linux ism.costa.esa 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:** 5.5.5-10.2.18-MariaDB-10.2.18+maria~stretch-log

**PHP version:** 7.0.30-0+deb9u1

**Teampass version:** 2.1.27.23

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/TeamPass',
'cpassman_url' => 'http://<anonym_url>/TeamPass
'favicon' => 'http://<anonym_url>/TeamPass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/TeamPass/upload',
'path_to_files_folder' => '/var/www/html/TeamPass/files',
'url_to_files_folder' => 'http://<anonym_url>/TeamPass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => 'posix',
'ldap_suffix' => '',
'ldap_domain_dn' => 'ou=people,dc=tiscali,dc=sys',
'ldap_domain_controler' => '127.0.0.1',
'ldap_user_attribute' => '',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '1',
'ldap_search_base' => '',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1515918667',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => 'admin',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml,pem',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '61',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '',
'bck_script_path' => '/var/www/html/TeamPass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '1',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '1',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'UTC',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '1',
'disable_show_forgot_pwd_link' => '1',
'ldap_port' => '389',
'ldap_bind_dn' => '',
'ldap_bind_passwd' => '<removed>'
'ldap_usergroup' => '',
'copy_to_clipboard_small_icons' => '1',
'teampass_version' => '2.1.27',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
);
```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 69.0.3497.92

**Operating system:** Linux - 64bits

#### Web server error log
Mon Oct 01 08:15:25.472924 2018] [:error] [pid 20770] [client 10.39.253.219:33798] PHP Notice:  Undefined index: pwComplexity in /var/www/html/TeamPass/index.php on line 818, referer: https://ism.costa.esa/TeamPass/index.php

```
Constant COST already defined - /var/www/html/TeamPass/includes/config/settings.php (19)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

index.php?page=items:1494 Mixed Content: The page at 'https://ism.costa.esa/TeamPass/index.php?page=items' was loaded over HTTPS, but requested an insecure image 'http://ism.costa.esa/TeamPass/includes/avatars/97675c61043dc5159bae7424e87ea55d_thumb.png'. This content should also be served over HTTPS.
jquery.js:8706 Mixed Content: The page at 'https://ism.costa.esa/TeamPass/index.php?page=items' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ism.costa.esa/TeamPass/profile.php?key=hzLCPC7Z9qDGvAnfpebjT8sZ2BnVyWpZMxxEp9EvTFGZEZ6Asu'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.js:8706
index.php?page=items:1371 Uncaught ReferenceError: ClipboardJS is not defined
    at HTMLDocument.<anonymous> (index.php?page=items:1371)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at Function.ready (jquery.js:433)
    at HTMLDocument.completed (jquery.js:104)
index.php?page=items:1 Mixed Content: The page at 'https://ism.costa.esa/TeamPass/index.php?page=items' was loaded over HTTPS, but requested an insecure favicon 'http://ism.costa.esa/TeamPass/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
jquery.js:5095 Uncaught TypeError: ((jQuery.event.special[handleObj.origType] || {}).handle || handleObj.handler).apply is not a function
    at HTMLInputElement.dispatch (jquery.js:5095)
    at HTMLInputElement.elemData.handle (jquery.js:4766)

Insert the log here and especially the answer of the query that failed.
```

**Comment by GitSlash2018** [comment]
Exactly the same problem here Update from TeamPass 2.1.27.16 to .23. When I go back to the Teampass folder from .16 I can see my folder and entries again.

**Comment by nilsteampassnet** [comment]
What are the errors you get during upgrade?
The errors here are coming from "normal" pages.

Can you check if you have field "encryption_type" existing in table `items`?

**Comment by Shert** [comment]
Hi,
the upgrade goes smoothly, no error is shown and the table items contains a filed encryption_type,
here is a table show 
````
desc teampass_items;
+---------------------------+--------------+------+-----+---------+----------------+
| Field                     | Type         | Null | Key | Default | Extra          |
+---------------------------+--------------+------+-----+---------+----------------+
| id                        | int(12)      | NO   | PRI | NULL    | auto_increment |
| label                     | varchar(500) | NO   |     | NULL    |                |
| description               | text         | YES  |     | NULL    |                |
| pw                        | text         | YES  |     | NULL    |                |
| pw_iv                     | text         | YES  |     | NULL    |                |
| pw_len                    | int(5)       | NO   |     | 0       |                |
| url                       | varchar(500) | YES  |     | NULL    |                |
| id_tree                   | varchar(10)  | YES  |     | NULL    |                |
| perso                     | tinyint(1)   | NO   |     | 0       |                |
| login                     | varchar(200) | YES  |     | NULL    |                |
| inactif                   | tinyint(1)   | NO   |     | 0       |                |
| restricted_to             | varchar(200) | YES  | MUL | NULL    |                |
| anyone_can_modify         | tinyint(1)   | NO   |     | 0       |                |
| email                     | varchar(100) | YES  |     | NULL    |                |
| notification              | varchar(250) | YES  |     | NULL    |                |
| viewed_no                 | int(12)      | NO   |     | 0       |                |
| complexity_level          | varchar(3)   | NO   |     | -1      |                |
| auto_update_pwd_frequency | tinyint(2)   | NO   |     | 0       |                |
| auto_update_pwd_next_date | varchar(100) | NO   |     | 0       |                |
| encryption_type           | varchar(20)  | NO   |     | not_set |                |
+---------------------------+--------------+------+-----+---------+----------------+
````

**Comment by nilsteampassnet** [comment]
can you provide the extract of one row please?

**Comment by GitSlash2018** [comment]
Hello,
like I said I have the same problem. The also upgrade goes smoothly, no error is shown and the table items contains a filed encryption_type. In every row it says "defuse" for encryption_type.

What other information do u need?

**Comment by nilsteampassnet** [comment]
can you provide the extract of one row please?

**Comment by GitSlash2018** [comment]
I would love to but I'm not sure what you mean and how I do it?

**Comment by Shert** [comment]
hi I hope this is what it's needed
''
select * from teampass_items limit 1 offset 13\G
*************************** 1. row ***************************
                       id: 30
                    label: XXlnxYYYY
              description: Generico server Linux di bordo<br />XX = codice nave (es : fa = favolosa)<br />YYY = funzione (es: dam1)<br />&nbsp;
                       pw: def502008fdaa0fec69eee3cc857aab0789a6a8d6fa19d4fc949d601de3adaf82cd7a69066296fde7e1b723bb2352234d2950a5a339ccf2f76c1d7f0e5bce47558978bbab126ef2417a088188e69afcfd472fe3e8ccc7e0360ec
                    pw_iv: 
                   pw_len: 0
                      url: 
                  id_tree: 1
                    perso: 0
                    login: root
                  inactif: 1
            restricted_to: 
        anyone_can_modify: 0
                    email: 
             notification: NULL
                viewed_no: 19
         complexity_level: 26
auto_update_pwd_frequency: 0
auto_update_pwd_next_date: 0
          encryption_type: not_set
1 row in set (0.00 sec)
''

**Comment by Shert** [comment]
here is an example of a freshly created object : 
''
 select * from teampass_items limit 1 offset 70\G
*************************** 1. row ***************************
                       id: 87
                    label: test-for-case#2424
              description: 
                       pw: def502005c23e2e4b37b06cc2d9731d91f3746849a87120173432ab6d68375e4693ac1932bd4d21ab34e4ecd55ed930ad4761735e18bb9f50bd824d086af8146aeb5bf0cf842789696ca93d456b3cebff994a4e2aeb5bcd38924
                    pw_iv: 
                   pw_len: 0
                      url: http://localhost
                  id_tree: 18
                    perso: 0
                    login: testlogin
                  inactif: 0
            restricted_to: 
        anyone_can_modify: 0
                    email: null@gmail.com
             notification: NULL
                viewed_no: 2
         complexity_level: 23
auto_update_pwd_frequency: 0
auto_update_pwd_next_date: 0
          encryption_type: not_set
1 row in set (0.00 sec)
''

**Comment by nilsteampassnet** [comment]
Can you explain what is the problem exactly?
Is it that you can access to item but you don't see the password anymore?
Provide a screen capture please.

**Comment by GitSlash2018** [comment]
No I can't see any folder or item. Here is how it looks like. Like we said the upgrade goes smoothly, no error is shown.
![teampass](https://user-images.githubusercontent.com/41113371/46880680-a0c50100-ce49-11e8-83b7-046914412c15.png)

**Comment by nilsteampassnet** [comment]
When in this status, please provide the console info (see https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console to know how to).

Have you tried to clear the cache of your browser too?

**Comment by GitSlash2018** [comment]
I feel stupid now. Clearing the cache of the browser worked! Thanks for your patience!

**Comment by nilsteampassnet** [comment]
Nice to read.
Indeed one new warning shown in the last page of the upgrade is to clear the browser cache.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.

**Comment by Shert** [comment]
I will try the browsr cache cleaning and let you know ,
thank you for the support everybody

M.

**Comment by Shert** [comment]
Hello,
I just want to say thank you for the support, even in my case the 
error was on my side  cause I did not clean the browser cache.

Thanks for your patience!
M.

**Comment by nilsteampassnet** [comment]
No problem ... good to read.
