### ISSUE TITLE
Teampass Admin account can log in without 2 factor code, others users cant

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#2426]
I've enabled 2 factor authentication in Teampass 2.1.27.22 and it is working correctly. However the admin user can log in without supplying a 2 factor auth code or even putting in a random number. How do I make it so that the admin user also can't log in without a valid 2 google 2 factor auth code ?

**Comment by nilsteampassnet** [comment]
This has been implemented by design to prevent a blocking situation where the admin couldn't log in.
The admin user can't access to passwords and for this reason, this choice could be acceptable.
Now if you want to have this enabled it would require simple code changes that I can detail here

**Comment by aleks001** [comment]
I thought that's why you did it but the admin user is still a risk. Because you can create users with the admin user, you can create a new user, give it access to whatever folders, turn of 2 factor auth and there you go now you have a user that has access to everything. Maybe I didn't setup our system properly, but I couldn't see a way you can restrict the admin user from granting rights to other groups and folders ?

If you can tell me how to force admin to use 2 factor auth like other users in the code that would be great and then i can just make that a custom setup for our install. I do understand though why you let admin login without a code as i almost locked myself out of once accidentally as our server didn't have internet access and couldn't generate a QR image.

**Comment by nilsteampassnet** [comment]
Yes you are right.
I could add easily an option to propagate this on the admin too.

**Comment by aleks001** [comment]
I think thats a good idea. I would add it as an option and add a warning to day something like “Make sure you test another account with 2 factor auth before enabling for admin as you could lock yourself out of the system permanently”.
