### ISSUE TITLE
[2.7.27.23] Can't login with LDAP (Group was found : false)

### ISSUE THREAD

**Issue by Albanosdes** [nilsteampassnet/TeamPass#2428]
### Expected behaviour
After configuring ldap, I should have been able to login with ldap credentials.

### Actual behaviour
`Login credentials do not correspond!`

### Server configuration
**Operating system**: Debian 9.5 Stretch 64bits

**Web server:** Apache/2.4.25

**Database:** 10.1.26-MariaDB

**PHP version:** PHP 7.0.30

**Teampass version:**  2.7.27.23

![ldap3](https://user-images.githubusercontent.com/12948248/46528759-da6b9a00-c894-11e8-84a4-aa3703a751fc.png)

I've tried several setup :
- suffix : `dc=imperium-gaming,dc=fr`
- suffix : `@dc=imperium-gaming,dc=fr`
- search base : `dc=imperium-gaming,dc=fr`
- search base : `cn=users, ou=Users, dc=imperium-gaming,dc=fr`
- LDAP group to search : `ou=Groups,dc=imperium-gaming,dc=fr`
- LDAP group to search : `ou=Users,dc=imperium-gaming,dc=fr`
etc...

#### LDAP debug :
```
Get all LDAP params : 
mode : 1
type : posix-search
base_dn : dc=imperium-gaming,dc=fr
search_base : ou=Users,dc=imperium-gaming,dc=fr
bind_dn : cn=xxxx,dc=imperium-gaming,dc=fr
bind_passwd : xxxx
user_attribute : uid
account_suffix : dc=imperium-gaming,dc=fr
domain_controllers : ldap.imperium-gaming.fr
ad_port : 389
use_ssl : 0
use_tls : 0
*********

LDAP URIs : ldap://ldap.imperium-gaming.fr:389 
LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=test)(objectClass=posixAccount))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [givenname] => Array
                (
                    [count] => 1
                    [0] => test
                )

            [0] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => test
                )

            [1] => sn
            [count] => 2
            [dn] => cn=test test,ou=Users,dc=imperium-gaming,dc=fr
        )

)

User was found. cn=test test,ou=Users,dc=imperium-gaming,dc=fr\nSearch groups appartenance : ou=Users,dc=imperium-gaming,dc=fr
Results : Array
(
    [count] => 0
)

Group was found : false
```

**Comment by nilsteampassnet** [comment]
I'm surprised of the format of the "Group to search".
You need to indicate the name only of the Group from which the users allowed to log in Teampass.
So if in your LDAP, you have defined a group called "TeampassGroup" then you need to indicate in this field only this group name.

**Comment by Albanosdes** [comment]
I was also surprised by your response as the help box shows the following :
![capture d ecran 1](https://user-images.githubusercontent.com/12948248/46553305-7caf7000-c8dd-11e8-9ae0-112e05684c41.png)

But ok, I tried : 
![capture d ecran 2](https://user-images.githubusercontent.com/12948248/46553325-8a64f580-c8dd-11e8-9395-420aa5656896.png)

But without success.

debug :

```Get all LDAP params :
mode : 1
type : posix-search
base_dn : dc=imperium-gaming,dc=fr
search_base : ou=Users,dc=imperium-gaming,dc=fr
bind_dn : cn=readonly,dc=imperium-gaming,dc=fr
bind_passwd : readonly
user_attribute : uid
account_suffix : ou=Users,dc=imperium-gaming,dc=fr
domain_controllers : ldap.imperium-gaming.fr
ad_port : 389
use_ssl : 0
use_tls : 0
*********

LDAP URIs : ldap://ldap.imperium-gaming.fr:389
LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=test)(objectClass=posixAccount))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [givenname] => Array
                (
                    [count] => 1
                    [0] => test
                )

            [0] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => test
                )

            [1] => sn
            [count] => 2
            [dn] => cn=test test,ou=Users,dc=imperium-gaming,dc=fr
        )

)

User was found. cn=test test,ou=Users,dc=imperium-gaming,dc=fr\nSearch groups appartenance : ou=Users,dc=imperium-gaming,dc=fr
Results : Array
(
    [count] => 0
)

Group was found : false
```

As you can see there is no difference in the debug log, or am I missing something?

**Comment by nilsteampassnet** [comment]
You can check this example https://teampass.readthedocs.io/en/latest/install/ldap/

If there is mistakes in the strings, please participate to the changes through [poeditor](https://poeditor.com/projects/view?id=16418);

**Comment by Albanosdes** [comment]
I did start with the documentation, and it did not help to resolve my issue, that's why I'm here nils :)

**Comment by nilsteampassnet** [comment]
The cn is strange, it seems to be "test test" with a white space.
I don't know is this is allowed in ldap. I thought that uid should always be in "one word".

**Comment by Albanosdes** [comment]
No more success. I also tried to edit the cn of my test user to have only "test", but no more success.
I rather say that it is a classic openldap server, the only specificity is that it a docker image. But I already linked my openvpn server with 4 others services (github, dokuwiki for examples) without much issues.
```
search_base : ou=Users,dc=imperium-gaming,dc=fr                                                                                                                                                 
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [givenname] => Array
                (
                    [count] => 1
                    [0] => test
                )
            [0] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => test
                )
            [1] => sn
            [count] => 2
            [dn] => cn=test,ou=Users,dc=imperium-gaming,dc=fr
        )
)
User was found. cn=test,ou=Users,dc=imperium-gaming,dc=fr\nSearch groups appartenance : ou=Users,dc=imperium-gaming,dc=fr
Results : Array
(
    [count] => 0
)
Group was found : false
```
With : search_base to dc=imperium-gaming,dc=fr
```
search_base : dc=imperium-gaming,dc=fr
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [givenname] => Array
                (
                    [count] => 1
                    [0] => test
                )
            [0] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => test
                )
            [1] => sn
            [count] => 2
            [dn] => cn=test,ou=Users,dc=imperium-gaming,dc=fr
        )
)
User was found. cn=test,ou=Users,dc=imperium-gaming,dc=fr\nSearch groups appartenance : dc=imperium-gaming,dc=fr
Results : Array
(
    [count] => 0
)
Group was found : false
```

**Comment by nilsteampassnet** [comment]
But in the ldap, did you declare users inside a specific group?

**Comment by Albanosdes** [comment]
Holy shit, that was it... my user was not in my group -.-
My apologies for losing your time, I was sure I did add my user to my group, but I was obviously wrong...

Consider this topic closed.

**Comment by nilsteampassnet** [comment]
Could you share your definitive ldap settings in this post for example to other users (mask sensitive data of course)?

**Comment by Albanosdes** [comment]
Here you go :
![capture_d_ecran_3_](https://user-images.githubusercontent.com/12948248/47284563-1a968080-d5e8-11e8-8ac8-c0bb547e8512.png)

**Comment by nilsteampassnet** [comment]
Thank you so much ... I'm sure this will help users ;)
