### ISSUE TITLE
TeamPassConnect doesn´t connect to TeamPass Server

### ISSUE THREAD

**Issue by dennis-tl** [nilsteampassnet/TeamPass#2429]
### Steps to reproduce
1. Add License information and credentials in Teampass connect
2. Save the settings

### Expected behaviour
TeamPassConnect doesnt connect to the server. All Information (License and Credentials) are set. In TeamPass API using is on.
Message after save: Credentials needed to grant access

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux alfa3212 4.9.44-040944-generic x86_64 

**Web server:**
Apache

**Database:**
MySQL 5.7.19

**PHP version:**
7.0.27

**Teampass version:**
2.1.27.23

### Client configuration
**Browser:**
Firefox 62.0.2

**Operating system:**
Windows 10 Professional 64 Bit

**Comment by nilsteampassnet** [comment]
Can you please install the latest version of the extension from https://teampass.net/teampassconnect.html?
