### ISSUE TITLE
New created folders cannot be seen

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#2430]
### Steps to reproduce
1. Logged on teampass a user or manager creates a folder.
2. User get a JSON error and cannot see the folder created
3. Login as admin you see the folders have been created without permissions, inherit permissions for new created folder on or off has the same behaviour.

### Expected behaviour
Folder should be created without error, user should be able to see the folder and permission should have been applied to it (inherited)

### Actual behaviour
Folder is created without permissions, user cannot see the folder, and user get a JSON error creating the folder.

#### Browser popup error
"Requested JSON parse failed."

#### Web server error log
```
No error logs in web server.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
No errors
```

**Comment by nilsteampassnet** [comment]
Can you please follow the template to describe your issue?
I'm missing a lot of information such as version.

**Comment by alarido** [comment]
Sorry, you are right, I forgot.

I tried to create a folder inside other existing folder just now (not root folder) where I have all permissions, it failed.



### Server configuration
**Operating system**: Linux urahara1 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64

**Web server:** Apache

**Database:** 5.5.5-10.0.36-MariaDB

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.23

**Teampass configuration file:**
```
'migration_to_2127' => 'done',
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '0',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '12',
'manager_edit' => '1',
'teampass_dir' => '/folder',
'teampass_url' => 'https://domain/cpassman',
'favicon' => 'https://domain/favicon.ico',
'activate_expiration' => '0',
'pw_life_duration' => '60',
'maintenance_mode' => '0',
'teampass_version' => '2.0rc4',
'ldap_mode' => '1',
'richtext' => '0',
'allow_print' => '0',
'anyone_can_modify' => '0',
'nb_bad_authentication' => '10',
'utf8_enabled' => '1',
'restricted_to_roles' => '0',
'custom_logo' => 'https://domain/logo.gif',
'custom_login_text' => 'Login',
'send_stats' => '0',
'send_stats_time' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'enable_kb' => '0',
'copy_to_clipboard_small_icons' => '1',
'enable_user_can_create_folders' => '1',
'ldap_suffix' => '@domain.local',
'ldap_domain_dn' => 'dc=domain,dc=local',
'ldap_domain_controler' => 'ldap1.domain.local',
'timezone' => 'Europe/Madrid',
'show_description' => '1',
'menu_type' => 'context',
'cpassman_dir' => '/folder',
'cpassman_url' => 'https://<anonym_url>
'cpassman_version' => '2.1.27',
'restricted_to' => '0',
'default_language' => 'spanish',
'send_mail_on_user_login' => '0',
'enable_send_email_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_email_notification_on_item_shown' => '0',
'path_to_upload_folder' => '/folder/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'path_to_files_folder' => '/folder/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'pwd_maximum_length' => '40',
'email_smtp_server' => 'smtp.domain.com',
'email_smtp_auth' => '0',
'email_auth_username' => 'false',
'email_auth_pwd' => '<removed>'
'email_from' => 'teampass@domain.com',
'email_from_name' => 'TeamPass',
'email_port' => '25',
'insert_manual_entry_item_history' => '1',
'email_post' => '25',
'delay_item_edition' => '30',
'allow_import' => '0',
'proxy_port' => '0',
'ldap_elusers' => '1',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml,pcf,vpn,exe,msi,tgz',
'upload_imageresize_options' => '0',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'anyone_can_modify_bydefault' => '0',
'enable_sts' => '1',
'can_create_root_folder' => '0',
'encryptClientServer' => '0',
'tree_counters' => '0',
'ldap_type' => 'windows',
'use_md5_password_as_salt' => '0',
'get_tp_info' => '1',
'ga_website_name' => '',
'item_extra_fields' => '0',
'settings_offline_mode' => '0',
'offline_key_level' => '90',
'item_duplicate_in_same_folder' => '1',
'ldap_user_attribute' => '0',
'roles_allowed_to_print' => '',
'email_security' => 'none',
'enable_email_notification_on_user_pw_change' => '0',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'email_server_url' => '',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '120',
'enable_attachment_encryption' => '0',
'bck_script_filename' => 'backupfile',
'bck_script_path' => '/folder/backups',
'duo' => '0',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'google_authentication' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'teampass_version' => '2.1.27',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'send_statistics_items' => '',
'agses_authentication_enabled' => '0',
'otv_is_enabled' => '0',
'enable_massive_move_delete' => '1',
'saltkey_ante_2127' => '13',
'ldap_port' => '389',
);
```

**Updated from an older Teampass or fresh install:**

### Client configuration (I've tried Chrome, Firefox, IE, etc. too)

**Browser:** Opera - 56.0.3051.36

**Operating system:** Windows - 64bits

### Logs

#### Web server error log
```
no errors
```

#### Teampass 10 last system errors
```
 * 14/10/2018 09:38:52 - Query: INSERT INTO `teampass_misc` (`type`,`intitule`,`valeur`) VALUES ('complex', 1143, '0')<br />Error: Duplicate entry '0' for key 'PRIMARY'<br />@ /sources/folders.queries.php
 ``

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
new_open @ csrfprotector.js:248
```

**Comment by alarido** [comment]
I get the JSON error even with "admin" user, inherit permissions  configuration is the same you are showing:

![image](https://user-images.githubusercontent.com/1955581/46914699-2b6c4400-cfa1-11e8-8234-abf31f4eda69.png)

I do not see errors in console or webserver, just a popup:

![image](https://user-images.githubusercontent.com/1955581/46914720-72f2d000-cfa1-11e8-8ae2-31b5fda63cea.png)
![image](https://user-images.githubusercontent.com/1955581/46914740-b0575d80-cfa1-11e8-888c-c5e168d62dd8.png)

Folder is created without permissions:
![image](https://user-images.githubusercontent.com/1955581/46914755-00362480-cfa2-11e8-98dd-ac2c5c166605.png)
![image](https://user-images.githubusercontent.com/1955581/46914762-18a63f00-cfa2-11e8-933f-b89e8c5eb72d.png)

What I do see is an error using the report a bug button:
 * 14/10/2018 11:09:09 - Query: INSERT INTO `teampass_misc` (`type`,`intitule`,`valeur`) VALUES ('complex', 1147, '0')<br />Error: Duplicate entry '0' for key 'PRIMARY'<br />@ /sources/folders.queries.php

**Comment by alarido** [comment]
I think I found the problem with this error in mind I did some digging.

I checked misc table and there was no AUTO_INCREMENT in increment_id column:
...
> show create table teampass_misc;
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table            | Create Table                                                                                                                                                                                                                                                                                                                           |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| teampass_misc | CREATE TABLE `teampass_misc` (
  `increment_id` int(12) NOT NULL DEFAULT '0',
  `type` varchar(50) NOT NULL,
  `intitule` varchar(100) NOT NULL,
  `valeur` varchar(500) NOT NULL DEFAULT 'none',
  PRIMARY KEY (`increment_id`),
  KEY `idx_type` (`type`),
  KEY `idx_intitule` (`intitule`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
...

I decided to alter table to include it, but I got an error:
...
> alter  table teampass_misc modify column increment_id INT auto_increment;
ERROR 1062 (23000): ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '1' for key 'PRIMARY'
>
...

I looked if there was an id = 0 in that table, and there was:
...
> select * from teampass_misc where increment_id=0 limit 10;
+--------------+-------+-------------------+--------+
| increment_id | type  | intitule          | valeur |
+--------------+-------+-------------------+--------+
|            0 | admin | migration_to_2127 | done   |
+--------------+-------+-------------------+--------+
1 row in set (0.00 sec)
...

So I deleted it, altered the table to include AUTO_INCREMENT and created the deleted registry again:
...
> delete from teampass_misc where increment_id=0;
Query OK, 1 row affected (0.01 sec)

> alter  table teampass_misc modify column increment_id INT auto_increment;
Query OK, 2079 rows affected (0.24 sec)
Records: 2079  Duplicates: 0  Warnings: 0

>
> insert into teampass_misc (type, intitule, valeur) values ("admin", "migration_to_2127", "done");
Query OK, 1 row affected (0.02 sec)

>
...


Now it works

**Comment by alarido** [comment]
Thanks for your help, without you asking I would never have solved the problem, regarding why it happened I have no idea.

**Comment by nilsteampassnet** [comment]
Thanks for your feedback, I will have an eye on it too
