### ISSUE TITLE
Empty item URL automatically fills with 'https://'

### ISSUE THREAD

**Issue by izomorph** [nilsteampassnet/TeamPass#2432]
TeamPass 2.1.27.23
Firefox 60.2, IE 11

If create or edit item with empty URL field it automatically fills with 'https://' and link icon appears. URL must remains empty and without link. It confuse users.

**Comment by nilsteampassnet** [comment]
Yes I confirm.
This was not my best idea ever.
I will commit a fix

**Comment by izomorph** [comment]
thank you
