### ISSUE TITLE
No "export" option in 2.1.27.7

### ISSUE THREAD

**Issue by sandman42** [nilsteampassnet/TeamPass#2433]
Hi,

since my 2.1.27.7 is messed up I'm trying to reinstall a fresh one (.23) from scratch.

How can I export and reimport the whole password folders, since I haven't export available?

Thanks

**Comment by nilsteampassnet** [comment]
Difficult to answer because "what is messed up"?
What do you accept to loose?
Otherwise why not to upgrade?

**Comment by nilsteampassnet** [comment]
can you please send me the mysql structure of table misc?

**Comment by sandman42** [comment]
`mysql> describe teampass_misc;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(12)      | NO   | PRI | NULL    | auto_increment |
| type     | varchar(50)  | NO   |     | NULL    |                |
| intitule | varchar(100) | NO   |     | NULL    |                |
| valeur   | varchar(500) | NO   |     | none    |                |
+----------+--------------+------+-----+---------+----------------+
`

**Comment by sandman42** [comment]
Hi, any news?

Thanks

**Comment by Toki127** [comment]
Hi, 
Exactly same case for me. Trying to upgrade from 2.1.27.7 to last version.

ERROR: An error appears when adding increment_id to table misc! Incorrect table definition; there can be only one auto column and it must be defined as a key!

mysql> describe teampass_misc;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(12)      | NO   | PRI | NULL    | auto_increment |
| type     | varchar(50)  | NO   |     | NULL    |                |
| intitule | varchar(100) | NO   |     | NULL    |                |
| valeur   | varchar(500) | NO   |     | NULL    |                |
+----------+--------------+------+-----+---------+----------------+

Thanks :)
