### ISSUE TITLE
Changing Teampass MySQL DB access user and password

### ISSUE THREAD

**Issue by maubertin** [nilsteampassnet/TeamPass#2434]
### Expected behaviour
Hi, i'd like to change the MySQL user account and mysql password used by teampass to connect to its own db. I shown this is configured in "includes/config/settings.php". 
How can I update the line "$pass = " in the config file in accordance to a new MySQL credentials ?

### Actual behaviour
Unable to change MySQL user/pass

### Server configuration
**Operating system**:
GNU Linux Centos 7.5

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
7.1

**Teampass version:** 
2.1.27
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
fresh install.

**Comment by nilsteampassnet** [comment]
You can indicate your password in clear text.
It will be taken into account.

**Comment by maubertin** [comment]
Thank you very much Nils. It works. 

Is there a way to avoid clear text, just like it is done during initial installation ? I mean to define the new password not in clear text ?

Again, thank you.

**Comment by amelie-excent** [comment]
Hello, I'm also interested to encrypt the password in the settings.php file. 
Is there a way to do that ? 
Thanks

**Comment by askmike1** [comment]
Is it possible yet to update settings.php to use a new database user/password and have the password be encrypted instead of plain-text?
