### ISSUE TITLE
Undefined variable: user_id in api/functions.php

### ISSUE THREAD

**Issue by simon6162** [nilsteampassnet/TeamPass#2436]
A minor bug when calling delete/item/<id> via the API - note i have no request[3] element, shows the following returned answer.

> <br />\n<b>Notice</b>:  Undefined variable: user_id in <b>/teampass/api/functions.php</b> on line <b>2646</b><br />\n{"status":"OK"}

My fix was to move the "user_id = API_USER_ID" to before the check for request[3] so that its always defined. 

My git checkout was 
d4f9637c (HEAD -> master, tag: 2.1.27.23, origin/master, origin/development, origin/HEAD) 2.1.27

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
