### ISSUE TITLE
Installation fails when populating database with tables

### ISSUE THREAD

**Issue by SergeDV** [nilsteampassnet/TeamPass#2437]
I have a Linux host running SLE 12 SP2. On it I have already 3 instances of Teampass running. Now I want to create a 4th instance. So I do like before: copy the software from repo to new directory, recursively change permissions on directory, create /etc/teampass-xxx directory with right permissions, create new database in MySQL and grant permissions to it for the teampass user, modify NGINX/APACHE2 combo for new instance, and then point my web browser to the new instance. I fill in the fields of the installation wizard, until it comes to step 5: "Tables creation". Then it hangs on the message "Now populating database" and nothing happens. In the DB, the _install table is properly created, but no other tables are created.

### Server configuration
**Operating system**:
SLE 12 SP2
**Web server:**
NGINX/APACHE2
**Database:**
MySQL
**PHP version:**
5.6
**Teampass version:** 
2.1.27.10/2.1.27.21

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Waterfox, IE11
**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
You must have errors in the apache logs.
Can you please provide them?

**Comment by SergeDV** [comment]
Hello Nils,

There is nothing in the Apache error log, and not in the NGINX error log. We use NGINX as a reverse proxy frontend to the Apache HTTP backend. This works fine for the other 3 instances of Teampass that run on this host.

Greetings

**Comment by SergeDV** [comment]
Hi Nils,

Is there an option I can set to make the installation process more verbose? Maybe this way we can figure out what goes wrong? For the moment, I cannot find any error message anywhere and I do not know what it is trying to do behind the scenes.

Greetings
