### ISSUE TITLE
Feature Request - More restriction when it comes to the API

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#2440]
Currently if you have the key for the API integration the most you can restrict is to an IP address and if you spoof that IP address and get the key you can call every single password in the TEAMPASS system. Would be good if the API can be restricted to users and or folders in the future.

Regards,
Aleks

**Comment by maubertin** [comment]
So, +1... 👍

**Comment by maubertin** [comment]
This issue should now be close. The features is provide in version 2.1.27.24

**Comment by nilsteampassnet** [comment]
Yes it has been committed inside `development` branch and will be added in 2.1.27.24 (released next week-end)
