### ISSUE TITLE
Incorrect german text for home_personal_saltkey_button

### ISSUE THREAD

**Issue by mherbertde** [nilsteampassnet/TeamPass#2441]
### Steps to reproduce
1. German language
2. Select personal menu
3. View the label for "home_personal_saltkey_button"

### Expected behaviour
Button should have correct text. Recommend: 'Ihr Salt-Schlüssel ändern!'

### Actual behaviour
Button has incorrect text. The label means something completely unrelated to changing the salt.

### Server configuration
**Operating system**: Linux test 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64

**Web server:** Apache/2.4.29 (Ubuntu)

**Database:** 5.7.23-0ubuntu0.18.04.1

**PHP version:** 7.2.11-1+ubuntu18.04.1+deb.sury.org+1

**Teampass version:** 2.1.27.23

**Teampass configuration file:**
```
(unnecessary)
```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 69.0.3497.100

**Operating system:** Windows - 64bits

#### Web server error log
```

```

#### Teampass 10 last system errors
```
(unrelated to this problem)
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Thank you for your input.

Translations are managed via [poeditor](https://poeditor.com/projects/view?id=16418), you are very welcome to participate and provide optimization.
