### ISSUE TITLE
Problem with Upgrade

### ISSUE THREAD

**Issue by pedrodaltoe1** [nilsteampassnet/TeamPass#2443]
We have installed version 2.1.27 of teampass for some time, but we want to make it a HA, so we need to reinstall from 0.

We upgraded from the current environment to 2.1.27.23;
We backed up the teampass-seckey.txt, sk.php, and csrfp.config.php files
We backed up the database under Settings> Backup

In the new environment already in 2.1.27.23
We adjusted Timezone through the Web-gui
We replace the files teampass-seckey.txt, sk.php and csrfp.config.php
We set the jsUrl variable to the new environment.
We receive "HTTP ERROR 500"

In the apache logs we can see the errors below

[Tue Oct 16 16:14:03.347629 2018] [:error] [pid 10908] [client 10.55.3.52:50208] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /var/www/html/index.php on line 84
[Tue Oct 16 16:14:03.347652 2018] [:error] [pid 10908] [client 10.55.3.52:50208] PHP Fatal error:  Call to a member function set_charset() on boolean in /var/www/html/index.php on line 85

### Server configuration
**Operating system**: red hat Linux

**Web server:  Apache/2.4.6

**Database:** mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64)

**PHP version:** PHP 5.6.38

### Client configuration
**Browser:** Chrome last version

**Operating system:** Windows 10

**Comment by Andrei-Paul** [comment]
It looks like your TP instance can't connect to MySQL (MariaDB?) Server. It tries to connect to it via **localhost**, using the **mysql** root user with **NO password**.

Are you sure the MySQL connection settings in www/includes/config/settings.php are correct?

**Comment by pedrodaltoe1** [comment]
Very thanks about your help.

When I checked the file in new machine, I saw the user and Password was not the same what was in old machine..

Now works fine, very very thanks about your time.
