### ISSUE TITLE
Login credentials do not correspond! LDAP

### ISSUE THREAD

**Issue by M1k13** [nilsteampassnet/TeamPass#2444]
### Expected behaviour
I should log in with an existing user from LDAP and the user will be showed in Teampass web browser.
passwords are not expired btw.

### Actual behaviour
When i try to log in it says "Login credentials do not correspond!"
In the Teampass logs it says user_not_exists.
But the

### Server configuration
CentOS 7

httpd 2.4.6-80.el7

MariaDB version 5.5.60
PHP version  7.0.27
Teampass version  2.1.27

### Client configuration
**Browser:**
Chrome, FF

**Operating system:**
Centos 7

**LDAP in web browser says:**
LDAP bind : Bound
Search filter (group): memberUid=boris
Results : Array
(
[count] => 3
[0] => Array
(
[count] => 0
[dn] => cn=meander,cn=groups,cn=compat,dc=promea,dc=org
)

[1] => Array
(
[count] => 0
[dn] => cn=mail,cn=groups,cn=compat,dc=promea,dc=org
)

[2] => Array
(
[count] => 0
[dn] => cn=geb_group_pedagogisch_beleid,cn=groups,cn=compat,dc=promea,dc=org
)

)

Find user in Group: 
Search filter : (&(uid=boris)(objectClass=person))
Results : Array
(
[count] => 1
[0] => Array
(
[mail] => Array
(
[count] => 1
[0] => boris@promea.org
)

[0] => mail
[givenname] => Array
(
[count] => 1
[0] => Boris
)

[1] => givenname
[sn] => Array
(
[count] => 1
[0] => Ruski
)

[2] => sn
[uid] => Array
(
[count] => 1
[0] => boris
)

[3] => uid
[count] => 4
[dn] => uid=boris,cn=users,cn=accounts,dc=promea,dc=org
)

)

Successfully connected

**But when i try to log in with the Ldap user it says Login credentials do not correspond! **

**duo.debug.txt:**
Identified : 4oP2oFvI0z

Content of data sent '+wC+r4WFyFuPdZp0601YvoW/BkVjUzmKwC3vCVSokHQ1ynOmZdMsD21Of6BsPawMBpix6IHchHPx9Jy8wkaU8S99DJoU1J7VgC5ZGmrMMtSQ57VayLgJJ9LpRiuNbiHjCjf2ru3nENBclX3ns/9hwXSbUkm/3gmzB3tfAss1u9bB8/S+bRdYBsGBqEZZpENX3sY5XR9bNNSEdrtHqwvhYwuXz9jpvqo1EMFnBJJOYOshDcQtJ9p9zRTx4UmlXWYXPMlCWds0TI5YPoY='
Starting authentication of 'boris'
LDAP status: 1
USer exists: 0
Content of data sent 'IAAjvu+GyFtlizvjg+drOo6UJoVqBBgtMiMMf5RjelPJfdaOpp/clnRCaSFUklHmSUf87IpbH9XX/OzZewVdfwdXLAkxE6WRdDJLfqSNi+IjIPUGMsDfGQyraARPLvr+InLvwiXUykEWqtrX0krlHIYU+P6MtpeCkU0bSORfDxlOpfpl8WvXG/Ly8jPzijv0QwoAhTlV2BiIkYAZLeSvfmzmDvUW6NLwDkn0/rxc2zPtQzyn6W8+tHE9nsmS4xZoZ9f2lC2MQ9EO1BiM'
Starting authentication of 'admin'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: eEHnQPEDGQWHG4AmvHEMDspCdr9QVGVpeX2vSjfe6mgGeb7ZYv
Preparing to identify the user rights

**Comment by M1k13** [comment]
ldap.debug


LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=boris)(objectClass=Person))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [mail] => Array
                (
                    [count] => 1
                    [0] => boris@promea.org
                )

            [0] => mail
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Boris
                )

            [1] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => Ruski
                )

            [2] => sn
            [count] => 3
            [dn] => uid=boris,cn=users,cn=accounts,dc=promea,dc=org
        )

)

User was found. uid=boris,cn=users,cn=accounts,dc=promea,dc=org\nSearch groups appartenance : dc=promea,dc=org
Results : Array
(
    [count] => 3
    [0] => Array
        (
            [count] => 0
            [dn] => cn=meander,cn=groups,cn=compat,dc=promea,dc=org
        )

    [1] => Array
        (
            [count] => 0
            [dn] => cn=mail,cn=groups,cn=compat,dc=promea,dc=org
        )

    [2] => Array
        (
            [count] => 0
            [dn] => cn=geb_group_pedagogisch_beleid,cn=groups,cn=compat,dc=promea,dc=org
        )

)

Group was found : false

**Comment by nilsteampassnet** [comment]
I don't see what is wrong here.
Do you know if the password of this user contains special characters such as \, & or similar?

**Comment by nilsteampassnet** [comment]
Just saw your new comment.

This makes me think to #2428 

Check that your user is in the correct group inside the ldap.
Check that `LDAP group to search` is filled with the same group as the user one.

**Comment by M1k13** [comment]
It doesn’t. The name is just boris, also tried it with the name test(test is not in any groups and boris is) same results.


LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=boris)(objectClass=Person))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [mail] => Array
                (
                    [count] => 1
                    [0] => boris@promea.org
                )

            [0] => mail
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Boris
                )

            [1] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => Ruski
                )

            [2] => sn
            [count] => 3
            [dn] => uid=boris,cn=users,cn=accounts,dc=promea,dc=org
        )

)

User was found. uid=boris,cn=users,cn=accounts,dc=promea,dc=org\nSearch groups appartenance : dc=promea,dc=org
Results : Array
(
    [count] => 3
    [0] => Array
        (
            [count] => 0
            [dn] => cn=meander,cn=groups,cn=compat,dc=promea,dc=org
        )

    [1] => Array
        (
            [count] => 0
            [dn] => cn=mail,cn=groups,cn=compat,dc=promea,dc=org
        )

    [2] => Array
        (
            [count] => 0
            [dn] => cn=geb_group_pedagogisch_beleid,cn=groups,cn=compat,dc=promea,dc=org
        )

)

Group was found : false

**Comment by M1k13** [comment]
The password is just password so nope

**Comment by M1k13** [comment]
I just made user ‘test’ in de group ‘ipausers’ in LDAP . In teampass it searches for the same group. In LDAP the group type is Non-POSIX. But I get the same results.

LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=testt)(objectClass=Person))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [mail] => Array
                (
                    [count] => 1
                    [0] => testt@promea.org
                )

            [0] => mail
            [givenname] => Array
                (
                    [count] => 1
                    [0] => test9
                )

            [1] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => test
                )

            [2] => sn
            [count] => 3
            [dn] => uid=testt,cn=users,cn=accounts,dc=promea,dc=org
        )

)

User was found. uid=testt,cn=users,cn=accounts,dc=promea,dc=org\nSearch groups appartenance : dc=promea,dc=org
Results : Array
(
    [count] => 0
)

Group was found : false


And then I tried ‘boris again who also is in ‘ipausers’ and some other groups.

LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=boris)(objectClass=Person))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [mail] => Array
                (
                    [count] => 1
                    [0] => boris@promea.org
                )

            [0] => mail
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Boris
                )

            [1] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => Ruski
                )

            [2] => sn
            [count] => 3
            [dn] => uid=boris,cn=users,cn=accounts,dc=promea,dc=org
        )

)

User was found. uid=boris,cn=users,cn=accounts,dc=promea,dc=org\nSearch groups appartenance : dc=promea,dc=org
Results : Array
(
    [count] => 3
    [0] => Array
        (
            [count] => 0
            [dn] => cn=meander,cn=groups,cn=compat,dc=promea,dc=org
        )

    [1] => Array
        (
            [count] => 0
            [dn] => cn=mail,cn=groups,cn=compat,dc=promea,dc=org
        )

    [2] => Array
        (
            [count] => 0
            [dn] => cn=geb_group_pedagogisch_beleid,cn=groups,cn=compat,dc=promea,dc=org
        )

)

Group was found : false

**Comment by M1k13** [comment]
I’m using Freeipa btw

**Comment by M1k13** [comment]
One it works when I remove LDAP group to search:  'cn=ipausers,cn=groups,cn=accounts,dc=promea,dc=org’
Dont understand how that is possible.
Does teampass also imports the groups from ldap.

**Comment by M1k13** [comment]
Sorry last msg had typo's

Oke it works when I remove LDAP group to search:  'cn=ipausers,cn=groups,cn=accounts,dc=promea,dc=org’
Dont understand how that is possible.
Does teampass also imports the groups from ldap?? or only users?

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
