### ISSUE TITLE
Cannot login as admin after upgrade

### ISSUE THREAD

**Issue by rcalrl** [nilsteampassnet/TeamPass#2445]
### Steps to reproduce
1.Update from 2.1.26-final-3 to 2.1.27.23
2.Try to login as admin

### Expected behaviour
Login succesful

### Actual behaviour
Login credentials do not correspond! Message is displayed

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache 2.4.6

**Database:** mariadb-server-5.5.60

**PHP version:** 5.5.38 

**Teampass version:** 2.1.27.23

**Teampass configuration file:**
       'max_latest_items' => '10',
        'enable_favourites' => '1',
        'show_last_items' => '1',
        'enable_pf_feature' => '1',
        'log_connections' => '0',
        'log_accessed' => '1',
        'time_format' => 'H:i:s',
        'date_format' => 'd/m/Y',
        'duplicate_folder' => '1',
        'item_duplicate_in_same_folder' => '0',
        'duplicate_item' => '1',
        'number_of_used_pw' => '3',
        'manager_edit' => '1',
        'cpassman_dir' => '/var/www/html/teampass',
        'cpassman_url' => 'http://teampass-server/teampass',
        'favicon' => 'http://teampass-server/teampass/favico.ico',
        'path_to_upload_folder' => '/var/www/html/teampass/upload',
        'url_to_upload_folder' => 'http://teampass-server/teampass/upload',
        'path_to_files_folder' => '/var/www/html/teampass/files',
        'url_to_files_folder' => 'http://teampass-server/teampass/files',
        'activate_expiration' => '0',
        'pw_life_duration' => '0',
        'maintenance_mode' => '0',
        'enable_sts' => '0',
        'encryptClientServer' => '1',
        'cpassman_version' => '2.1.26',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '',
    'ldap_domain_dn' => '',
    'ldap_domain_controler' => '',
        'ldap_user_attribute' => '0',
        'ldap_ssl' => '0',
        'ldap_tls' => '1',
        'ldap_elusers' => '1',
        'richtext' => '0',
        'allow_print' => '0',
        'roles_allowed_to_print' => '0',
        'show_description' => '1',
        'anyone_can_modify' => '0',
        'anyone_can_modify_bydefault' => '0',
        'nb_bad_authentication' => '0',
        'utf8_enabled' => '1',
        'restricted_to' => '0',
        'restricted_to_roles' => '0',
        'enable_send_email_on_user_login' => '0',
        'enable_user_can_create_folders' => '0',
        'insert_manual_entry_item_history' => '0',
        'enable_kb' => '0',
        'enable_email_notification_on_item_shown' => '0',
        'enable_email_notification_on_user_pw_change' => '1',
        'custom_logo' => '',
        'custom_login_text' => '',
        'default_language' => 'english',
        'send_stats' => '0',
        'get_tp_info' => '1',
        'send_mail_on_user_login' => '0',
        'nb_items_by_query' => 'auto',
        'enable_delete_after_consultation' => '0',
        'enable_personal_saltkey_cookie' => '0',
        'personal_saltkey_cookie_duration' => '31',
        'email_smtp_server' => 'mail-server',
        'email_smtp_auth' => '0',
        'email_auth_username' => '',
        'email_auth_pwd' => '',
        'email_port' => '25',
        'email_security' => 'none',
        'email_server_url' => 'http://teampass-server/teampass',
        'email_from' => 'teampass@mail-server',
        'email_from_name' => 'Teampass',
        'pwd_maximum_length' => '40',
        '2factors_authentication' => '1',
        'delay_item_edition' => '0',
        'allow_import' => '0',
        'proxy_ip' => '',
        'proxy_port' => '',
        'upload_maxfilesize' => '10mb',
        'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
        'upload_imagesext' => 'jpg,jpeg,gif,png',
        'upload_pkgext' => '7z,rar,tar,zip',
        'upload_otherext' => 'sql,xml',
        'upload_imageresize_options' => '1',
        'upload_imageresize_width' => '800',
        'upload_imageresize_height' => '600',
        'upload_imageresize_quality' => '90',
        'use_md5_password_as_salt' => '0',
        'ga_website_name' => 'TeamPass for IT',
        'api' => '0',
        'subfolder_rights_as_parent' => '1',
        'show_only_accessible_folders' => '1',
        'enable_suggestion' => '1',
        'otv_expiration_period' => '7',
        'default_session_expiration_time' => '15',
        'duo' => '0',
        'send_stats_time' => '0',
        'tree_counters' => '0',
        'item_extra_fields' => '0',
        'enable_attachment_encryption' => '0',
        'copy_to_clipboard_small_icons' => '1',
        'settings_offline_mode' => '0',
        'offline_key_level' => '70',
        'bck_script_filename' => 'bck_cpassman',
        'bck_script_path' => '/var/www/html/teampass/backups',
        'can_create_root_folder' => '0',
        'syslog_enable' => '0',
        'syslog_host' => 'localhost',
        'syslog_port' => '514',
        'timezone' => 'Europe/Madrid',
        'menu_type' => 'context',
        'enable_server_password_change' => '0',
        'ldap_object_class' => '0',
    'google_authentication' => '1',
**Updated from an older Teampass or fresh install:** upgraded from 2.1.26.17

### Client configuration
**Browser:** Chrome 70.0.3538.67

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by rcalrl** [comment]
The upgrade finishes without errors.

The column id doesn't exist:
ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;                                                                               
ERROR 1054 (42S22): Unknown column 'id' in 'teampass_misc'

**Comment by nilsteampassnet** [comment]
can you please provide the structure of table `teampass_misc`?
At least, check if field `increment_id` exists.

When login as admin, please provide the error from the console (see https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console)

**Comment by rcalrl** [comment]
I don't know why but this time I can login normally after the upgrade, all the steps have been the same as the last times.

There was no increment_id filed in the teampass_misc table in 21.26 installation.
