### ISSUE TITLE
User can create folders but not access after page refersh -- admin needs to allow access

### ISSUE THREAD

**Issue by Erdyke** [nilsteampassnet/TeamPass#2447]
### Steps to reproduce
1. Give non admin user folder creation rights.
2. Have new user create new folder.  You'll see the folder.  Refresh the page.  Folder is gone.
3. You must go in with admin to allow folder read/write for that role.  

### Expected behaviour
This is unexpected especially because folders are sub folders where the user already has access.  The rights should be initialized to the same as the parent folder right?

### Actual behaviour
Rights are initialized to none.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
Mysql

**PHP version:**
7.2

**Teampass version:** 
2.1.27.3

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
FF 62.0.3

**Operating system:**
Ubuntu 18.04

**Comment by Erdyke** [comment]
[tp.config .php.txt](https://github.com/nilsteampassnet/TeamPass/files/2503228/tp.config.php.txt)

**Comment by nilsteampassnet** [comment]
Have you enabled option ` New sub-folders inherit permissions from parent folder `?

**Comment by Erdyke** [comment]
Didn't know that was an option.  I assumed that allowing inheritance would be the default implementation.  Thanks.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
