### ISSUE TITLE
No working LDAP type windows / active directory (TeamPass 2.1.27.23) 

### ISSUE THREAD

**Issue by rjbarros** [nilsteampassnet/TeamPass#2448]
### Steps to reproduce
1. configure my domain server
2. Perform a test with a domain user and everything comes out success
3. When I intend to enter a teampass with a domain user, it tells me that login credentials do not correspond.

### Expected behaviour
I should be able to enter with my domain user if everything goes right in the test.

### Actual behaviour
when I try to login with a domain user, the login credentials do not correspond

### Server configuration
**Operating system**: Centos 7.5

**Web server:** Apache/2.4.34

**Database:**MySQL version: 5.6.42

**PHP version:**5.6.37 

**Teampass version:**  2.1.27.23 [

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[Confg.zip](https://github.com/nilsteampassnet/TeamPass/files/2508062/Confg.zip)

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10 Pro

#### Web server error log
[error_log.zip](https://github.com/nilsteampassnet/TeamPass/files/2508070/error_log.zip)

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
PLease check https://teampass.readthedocs.io/en/latest/install/ldap/

Check also #2428

**Comment by rjbarros** [comment]
with that solution is the same, another recommendation?
