### ISSUE TITLE
Can't add item with the same name if already exists somewhere else

### ISSUE THREAD

**Issue by 80kk** [nilsteampassnet/TeamPass#2449]
### Steps to reproduce
1. Create an item in directory X
2. Try to create item with the same label in directory Y
3. You'll get an error saying that "this item already exists!"

### Expected behaviour
It should not be a problem to add items with the same labels under different folders.

### Actual behaviour
Error saying that the item already exists.

### Server configuration
**Operating system**: CentOS 7.5.1804

**Web server:** Apache 2.4.6

**Database:** 5.5.60-MariaDB

**PHP version:** 7.0.30

**Teampass version:** 2.1.27.19

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Updated from older
PLEASE attach to this issue the file `/includes/config/tp.config.php
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/2511257/tp.config.txt)

`.

### Client configuration
**Browser:** FireFox and Chrome

**Operating system:** Linux 

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by 80kk** [comment]
I have also found that I can't edit items. The error message is the same: "Item already exists!"

**Comment by nilsteampassnet** [comment]
> It should not be a problem to add items with the same labels under different folders.

Perhaps in your use-case but for other users, this might be an error.
So an option exists for this, just enabled it and it will fit your "use-case".

![image](https://user-images.githubusercontent.com/1197546/47527515-fb774780-d8a2-11e8-946a-89488c627e4f.png)

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
