### ISSUE TITLE
Add new user while ldap enabled - just spins

### ISSUE THREAD

**Issue by nneul** [nilsteampassnet/TeamPass#2450]
### Steps to reproduce
1. Configure ldap enabled server
2. Try to pre-add a user with info matching ldap prior to them logging in

### Expected behaviour
User gets added. (Apparently this used to work in a previous update, but broke at some unknown time.)

Wishlist functionality (yes, I know this is a feature request): Allow me to enter a userid from LDAP and just have it populate a new account as if they had logged in themselves. 

### Actual behaviour
Does the single post - gets a 'field avatar does not have a default value' mixed in the post response. UI sits on 'Please wait' with spinner.

### Server configuration
**Operating system**:
ubuntu 16

**Web server:**
apache 2.4.18 ubuntu

**Database:**
mariadb 10.3.8

**PHP version:**
7.0.32

**Teampass version:** 
d4f9637c860f1502cc9bcb92a7005bd9f67181ea 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 68 linux

**Operating system:**
ubuntu 16.04 x86_64

### Logs
No log errors.

#### Log from the web-browser developer console (CTRL + SHIFT + i)
Field 'avatar' doesn't have a default valuepvrQW...bunch of encoded content...

**Comment by nilsteampassnet** [comment]
I believe this is a duplicate #2438 

Execute the SQL queries written inside it and it should fix this issue.

**Comment by nneul** [comment]
Excellent, yes, that fixed it. Thank you!
