### ISSUE TITLE
account creation... password sent in email is "undefined"

### ISSUE THREAD

**Issue by philippebaque** [nilsteampassnet/TeamPass#2453]
### Steps to reproduce
1. create an account
2.
3.

### Expected behaviour
the mail received contain information about account name and password (generated by the platform)...
### Actual behaviour
The password noticed in the email is "undefined", it is defined but its the word "undefined"
I was believing a joke.... not, its really this one.

### Server configuration
**Operating system**: debian 9.4

**Web server:** apache 2.4

**Database:** mariadb

**PHP version:** 7.1

**Teampass version:**  2.1.27.23

**Teampass configuration file:**
![capture d ecran de 2018-10-30 08-08-08](https://user-images.githubusercontent.com/1191710/47701908-a8dbb980-dc1b-11e8-9853-81e19554a29e.png)

**Comment by nilsteampassnet** [comment]
Correct

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
