### ISSUE TITLE
Update from 2.1.27.23 to 2.1.27.24 doesn't work

### ISSUE THREAD

**Issue by edelmanns** [nilsteampassnet/TeamPass#2454]
### Steps to reproduce
1. Downlaod 2.1.27.24
2. Start Update 
3. Some Error will shown in ssl_error_log at the last step 

### Expected behaviour
The updtae will stop at the last step.

### Actual behaviour
change upgrade_run_2.1.27.php at line 1059

Line 1056 till 1059 original:

mysqli_query(
    $db_link,
    "ALTER TABLE `".$pre."nested_tree` CHANGE `nleft` `nleft` INT(11) NULL DEFAULT NULL, CHANGE `nright` `nright` INT(11) NULL DEFAULT NULL, CHANGE `nlevel` `nlevel` INT(11) NULL DEFAULT NULL;"
);"
 ^^

change:
mysqli_query(
    $db_link,
    "ALTER TABLE `".$pre."nested_tree` CHANGE `nleft` `nleft` INT(11) NULL DEFAULT NULL, CHANGE `nright` `nright` INT(11) NULL DEFAULT NULL, CHANGE `nlevel` `nlevel` INT(11) NULL DEFAULT NULL;"
);
^^

After change the update will done.

#### Web server error log
```
[Tue Oct 30 08:44:00.849698 2018] [php7:emerg] [pid 120634] [client 10.1.13.11:57881] PHP Parse error:  syntax error, unexpected 'CREATE' (T_STRING) in /var/www/html/teampass/install/upgrade_run_2.1.27.php on line 1066, referer: https://internurl/teampass/install/upgrade.php
```

**Comment by nilsteampassnet** [comment]
Thank you
