### ISSUE TITLE
Unable to login after upgrade from 2.1.27.23 => 2.1.27.25

### ISSUE THREAD

**Issue by steven792** [nilsteampassnet/TeamPass#2455]
### Steps to reproduce
1. Clean upgrade from 2.1.27.23 to 2.1.27.25
2. Attempt login with user or admin account fails
3.

### Expected behaviour
Tell us what should happen
Expecting to be able to login

### Actual behaviour
Tell us what happens instead
recieve : Login credentials do not correspond!  error for all users
### Server configuration
**Operating system**:
AWS Linux 2
**Web server:**
apache
**Database:**
MySQL
**PHP version:**
7.2.5
**Teampass version:** 
2.1.27.25
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by steven792** [comment]
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.shift7digital.com/teampass',
    'favicon' => 'https://teampass.shift7digital.com/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.shift7digital.com/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.shift7digital.com/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@shift7digital.com',
    'ldap_domain_dn' => 'dc=shift7digital,dc=local',
    'ldap_domain_controler' => '10.1.6.25',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '1',
    'ldap_tls' => '1',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://teampass.shift7digital.com/teampass/custom/Password_Keeper.png',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1532379129',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '120',
    'email_smtp_server' => 'email-smtp.us-east-1.amazonaws.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => ‘XXXXXXXXXXXXXXXXXXXXX’,
    'email_auth_pwd' => ‘XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX’,
    'email_port' => '587',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'teampass@shift7digital.com',
    'email_from_name' => 'Shift7 Password Keeper',
    'pwd_maximum_length' => '60',
    'google_authentication' => '1',
    'delay_item_edition' => '15',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,pem,crt,key',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for Shift7 Digital',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/New_York',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => ‘xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx’,
    'copy_to_clipboard_small_icons' => '1',
    'ldap_allowed_usergroup' => '',
    'ldap_new_user_role' => '',
    'item_creation_templates' => '0',
    'ga_reset_by_user' => '1',
    'teampass_version' => '2.1.27',
    'admin_2fa_required' => '1',
);

**Comment by nilsteampassnet** [comment]
can we have a screen sharing session with Teamviewer?
Contact me nils@teampass.net

**Comment by nilsteampassnet** [comment]
Bug identified when only one 2FA method is set.
New commit to come

**Comment by nilsteampassnet** [comment]
Can you please be more explicit?

Where did you clicked? What happened?

**Comment by nilsteampassnet** [comment]
I can't reproduce it.
Could we perform a teamviewer session to check what is the error?
