### ISSUE TITLE
Slow login when users has no internet connection

### ISSUE THREAD

**Issue by LemonLight** [nilsteampassnet/TeamPass#2456]
### Expected behaviour
Login using local/active directory in 5 sec

### Actual behaviour
Login using local/active directory in > 1 minutes...

### Server configuration
**Operating system**:
Ubuntu 18.04.1 LTS
**Web server:**
Apache/2.4.29
**Database:**
MariaDB 10.1.34
**PHP version:**
7.2.10
**Teampass version:** 
2.1.27.23

### Client configuration
**Browser:**
Internet Explorer 11, Google Chrome 69, Firefox 62.0.2
**Operating system:**
Win7,10

Hi !

I have an issue while logging using local or Active Directory... During my investigations, I saw that pressing Login button, my client try to connect to ipapi.co... But, all my users have not Internet connection, so they can not access to the ipapi.co. So it makes the login very very slow (more than a minute regarding the browser...).

Is there a way to disable this check to ipapi.co ? 

Thanks in advance.

**Comment by LemonLight** [comment]
Hi Nils!

Thanks for your update (2.1.27.27), it solved the problem.

However, now, when I login, have an "information" window that appear which is empty. I close it and then appears a new one with the following message :
"An error appears. Answer from Server cannot be parsed!
Returned data: undefined"...

And then the server closes the session

**Comment by nilsteampassnet** [comment]
How sad.

I've done several tests without issue as you describe.

Can you please reproduce and get the answer from the server using the web console and following [instructions](https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console)

**Comment by LemonLight** [comment]
Hello @nilsteampassnet 

Sorry for no responding... I was at school and took in lot of project...
I recently upgraded to 2.1.27.29 and it seems to fix the issue :) 

Thanks for you fast update !
