### ISSUE TITLE
Items folder automatically changes to the personal one

### ISSUE THREAD

**Issue by Benny1988** [nilsteampassnet/TeamPass#2458]
### Steps to reproduce
1. Search for an item
2. Click on the orange key on the result entry (Edit)
3. Wait 2 Seconds - Folder change from original to personal automatically

### Expected behaviour
Folder should not be changed automatically

### Actual behaviour
Items folder automatically changes to the personal one

### Server configuration
**Operating system**:
Debian Wheezy

**Web server:**
Apache/2.2.22 (Debian)

**Database:**
MySQL 5.5.60-0+deb7u1

**PHP version:**
PHP 5.5.38-1~dotdeb+7.1

**Teampass version:** 
2.1.27.23

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox 63

**Operating system:**
Xubuntu 18.10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I can't reproduce on latest.

After performing a search inside the Items page, when I click on the orange key icon, the edit dialogbox is shown without any redirection.

![image](https://user-images.githubusercontent.com/1197546/47904978-37ec0a00-de86-11e8-9bfd-980a0e6f64cf.png)

**Comment by Benny1988** [comment]
Hello Nils,

maybe I did not express myself correctly. I attach a screenshot. There you see "Ordner" (in english folders) "Clients". There, the folder is automatically changed for some entries. That's stupid, because then the entry disappears from the public part and slips into the personal.

![screenshot](https://user-images.githubusercontent.com/8710347/47906168-f315a280-de88-11e8-89cd-4565708498ab.png)

**Comment by nilsteampassnet** [comment]
Ok thank you.

SO I have tried too but couldn't reproduce.
I've enabled PersonalFolder option for the users, tried editing an existing one or creating a new one but could not observe your behavior.
Perhaps solved in more recent releases?

**Comment by Benny1988** [comment]
I updated to 2.1.23.29 but the problem still occurs :(

**Comment by nilsteampassnet** [comment]
I finally could reproduce your steps and the issue.

I will commit a fix in the development branch.

Then in 2.1.27.30

**Comment by Benny1988** [comment]
I updated to 2.1.27.30 and the problem  still exists. :-(

**Comment by Benny1988** [comment]
Any ideas?

**Comment by nilsteampassnet** [comment]
Should be ok now in release 2.1.27.33

PLease confirm

**Comment by Benny1988** [comment]
Yes .. it looks like it works.
