### ISSUE TITLE
"You are not allowed to do that!" on Item I am in fact in the group which is restricted to.

### ISSUE THREAD

**Issue by 80kk** [nilsteampassnet/TeamPass#2459]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
It should be possible to edit the item I have created and I am in the group which the item is restricted to. In fact no one from the group can't edit the item. Item has an orange tag.

### Actual behaviour
"You are not allowed to do that!" message appears.

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB

**PHP version:** 7.0.30

**Teampass version:** 2.1.27.19

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please provide the configuration you have set so that I can reproduce

**Comment by 80kk** [comment]
```
