### ISSUE TITLE
Install procedure failing on Ubuntu 16.04 - mariadb - php 7

### ISSUE THREAD

**Issue by fudcompliance** [nilsteampassnet/TeamPass#2461]
### Steps to reproduce
1. perform install procedure on ubuntu 16.04 , with stock php package 7.0.32-0ubuntu0.16.04.1
2. the install procedure says it's been completed successfully
3. error "Table 'teampass.teampass_users' doesn't exist9lrdW+Li4uK+9T1HUE0ZW5d2nzaUP3YYy26uuTA4ECKFSkEkl8yDiVZ9oikT2U+vDmDQTuh0GH9U1w2jSkOYilZBYd2oxu1BBrVJ61GjtmVM3n3MHEuEuuz4XxTA1WyyoPypSyU7ocl4cw==" is displayed accessing login page

### Expected behaviour
Install procedure should succeed

### Actual behaviour
Following error is displayed: "Table 'teampass.teampass_users' doesn't exist9lrdW+Li4uK+9T1HUE0ZW5d2nzaUP3YYy26uuTA4ECKFSkEkl8yDiVZ9oikT2U+vDmDQTuh0GH9U1w2jSkOYilZBYd2oxu1BBrVJ61GjtmVM3n3MHEuEuuz4XxTA1WyyoPypSyU7ocl4cw==" is displayed accessing login page

### Server configuration
**Operating system**: Ubuntu Linux 16.04

**Web server:** Apache 2.4.18-2ubuntu3.9

**Database:** MariaDB 10.1.37+maria-1~xenial

**PHP version:** PHP 7.0.32-0ubuntu0.16.04.1 

**Teampass version:** 2.1.27.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox 63.0 (64-bit)

**Operating system:** Linux

#### Web server error log
[Fri Nov 02 18:51:37.457494 2018] [:error] [pid 2160] [client 192.168.99.80:36122] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429, referer: http://giano2.kelyon.net/install/install.php
[Fri Nov 02 18:51:41.747508 2018] [:error] [pid 2160] [client 192.168.99.80:36122] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429
[Fri Nov 02 18:51:45.762302 2018] [:error] [pid 2160] [client 192.168.99.80:36122] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429
[Fri Nov 02 18:53:22.012843 2018] [:error] [pid 2371] [client 192.168.99.80:51972] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429
[Fri Nov 02 18:56:19.523052 2018] [:error] [pid 2140] [client 192.168.99.80:52076] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429
[Sat Nov 03 09:23:18.226451 2018] [:error] [pid 2159] [client 192.168.99.80:41662] PHP Notice:  Undefined index: key in /var/www/teampass/sources/main.functions.php on line 1429

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2544764/tp.config.php.txt)


```

**Comment by phhp3001** [comment]
I have the same problem. Teampass did not create the users and admin table during installation.

**Comment by nilsteampassnet** [comment]
This is fixed in development branch.

I will create a new release to fix this.

**Comment by phhp3001** [comment]
@nilsteampassnet Which version does not have this problem?

**Comment by Mattyx** [comment]
I'm stuck here too.
Is there a workaround to solve that issue? Do I have to install an older release?

Thanks

**Comment by nilsteampassnet** [comment]
Please install latest version 2.1.27.28

**Comment by phhp3001** [comment]
Where can I download it? The latest release available on github is 2.1.27.27.

**Comment by nilsteampassnet** [comment]
My fault. Didn't created the release.
Now available https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.27.28

**Comment by phhp3001** [comment]
@nilsteampassnet Thank you very much, I will install this version.

**Comment by phhp3001** [comment]
@nilsteampassnet It worked perfectly, thank you.
