### ISSUE TITLE
Export of credentials (What happens to the exported file?)

### ISSUE THREAD

**Issue by finalbeta** [nilsteampassnet/TeamPass#2469]
### Steps to reproduce
1. Export a CSV or PDF file. 
2. Save the export link.
3. Log out. 
4. Download the exported file without issues. 

### Expected behaviour
The exported file should not be publicly available, the file should be really temporary.

### Actual behaviour
The file is put on the server and remains publicly available.
Perhaps this is a config issue on my side. But what does Teampass do to "remove this export?"

**Comment by nilsteampassnet** [comment]
This is a configuration issue.
As recommended in the tooltip.
![image](https://user-images.githubusercontent.com/1197546/48159445-801b8a00-e2d5-11e8-864d-387b1ca27a52.png)

There is no automatic way to delete a file on a trigger such as 'after user has downloaded the file'. Such a trigger has too much unknown events.

So different technics exist at "intance level":
1- define the files folder outside the www domain of your server (the best according to me)
2- create a cron that will delete a file older than 5 minutes (for example) in this folder

**Comment by finalbeta** [comment]
Hi Nils, thanks for the response. 

I don't understand how putting the folder outside the webroot path, and then using a rewrite / redirection adds anything to security. (I may not understand the concept, but it seems to add to complexity only?)

**Comment by finalbeta** [comment]
Hi Nils, the thing I actually want to get at, is that moving the temp folder away from the www folder is a very sane thing to do. 
However, it should be implemented at the webapplication level. 

For example, a secure flow could be. 
User presses a button/link ( Starts a POST with the required parameters to know what to export). 
Server validates the rights.
Teampass generates a file inside the temporary folder. 
Teampass serves the generated file in the response. 
 ```
$exportname = "secured_export.pdf"
$fp = fopen($tmpOutputFile, 'rb');
header('Content-Type: application/octet-stream');
header("Content-Transfer-Encoding: Binary");
header("Content-disposition: attachment; filename=\"" . $exportname. "\"");
header("Content-Length: " . filesize($tmpOutputFile));
fpassthru($fp);
unlink( $tmpOutputFile );
}
exit;
```
In most cases, you could probably output the result of the pdf library directly to the output stream, that way you would not even have a tmp file. 

Using the above way means that when triggering/accessing the export file, the users rights are validated. No temporary file is ever publicly available and no files are left on the filesystem. 

Perhaps something like this could be a feature request, because for a password manager, the way it is now perhaps is not the best way?

**Comment by nilsteampassnet** [comment]
Putting the file outside the www domain protects the file from being accessed through url (even the folder itself).

The described process is the current one. Take a look to `sources/downloadFile.php`

**Comment by finalbeta** [comment]
Hi Nils, sry for my slow response. I needed some time to test this.

When I go to the admin area and I backup the database. The URL takes me through /sources/download.php, and my download is secured like you said. I can move the path outside the webdirectory and download.php handles the download. 

When I export credentials, the /sources/download.php url is not used, but the file is directly downloaded through the URL like /files/print_out_pdf.... . Or do I need to change the "Files folder (URL)" in the settings to /sources/download.php to make use of the download.php? (This is not required for a database backup)

**Comment by finalbeta** [comment]
Just to confirm: 
If you backup the db through the admin panel. You run " case "admin_action_db_backup":" in 
https://github.com/nilsteampassnet/TeamPass/blob/master/sources/admin.queries.php
That outputs the result as: 
` echo '[{"result":"db_backup" , "href":"sources/downloadFile.php?name='.urlencode($filename).'&sub=files&file='.$filename.'&type=sql&key='.$_SESSION['key'].'&key_tmp='.$_SESSION['key_tmp'].'&pathIsFiles=1"}]';`

Looks OK. 

If you export credentials in the regular user interface, you use :
https://github.com/nilsteampassnet/TeamPass/blob/master/sources/export.queries.php , 
Under: 'case "finalize_export_pdf":' the pdf is created, it's finally created and the url is returned as 
`echo '[{"text":"<a href=\''.$SETTINGS['url_to_files_folder'].'/'.$pdf_file.'\' download>'.$LANG['pdf_download'].'</a>"}]';`
That code doesn't use sources/downloadFile.php.

**Comment by finalbeta** [comment]
Hi Nils, do you agree with my conclusions?

**Comment by nilsteampassnet** [comment]
Hello

Yes you are right.
I will change this.
For information, this has totally changed in 3.0 branch to make it safer.
