### ISSUE TITLE
Unsent mails, please help

### ISSUE THREAD

**Issue by mathzen** [nilsteampassnet/TeamPass#2470]
Well I encounter exactly the same problem as in this thread : 
https://github.com/nilsteampassnet/TeamPass/issues/2171

But the solution isn't detailed, so here I am... Thanks in advance !

### Steps to reproduce
1. share and request mails are sent instantly and properly
2. other mail queued are sent after manually triggered

### Server configuration
**Operating system**: 
Windows 2012 R2

**Web server:** 
Apache 2.4.23

**Database:**
MySQL 5.7.14

**PHP version:**
7.0.10

**Teampass version:** 
2.1.26

**Teampass configuration file:**
<?php
    global $SETTINGS;
    $SETTINGS = array (
        'max_latest_items' => '10',
        'enable_favourites' => '1',
        'show_last_items' => '1',
        'enable_pf_feature' => '0',
    'log_connections' => '0',
        'log_accessed' => '1',
        'time_format' => 'H:i:s',
        'date_format' => 'd/m/Y',
        'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '0',
        'manager_edit' => '1',
        'cpassman_dir' => 'C:/wamp/www/TeamPass',
        'cpassman_url' => 'http://localhost/TeamPass',
        'favicon' => 'http://localhost/TeamPass/favico.ico',
        'path_to_upload_folder' => 'C:/wamp/www/TeamPass/upload',
        'url_to_upload_folder' => 'http://localhost/TeamPass/upload',
        'path_to_files_folder' => 'C:/wamp/www/TeamPass/files',
        'url_to_files_folder' => 'http://localhost/TeamPass/files',
        'activate_expiration' => '0',
        'pw_life_duration' => '0',
        'maintenance_mode' => '0',
        'enable_sts' => '0',
        'encryptClientServer' => '1',
        'cpassman_version' => '2.1.26',
        'ldap_mode' => '0',
        'ldap_type' => 'windows',
        'ldap_suffix' => 'secret',
        'ldap_domain_dn' => 'secret',
        'ldap_domain_controler' => 'secret',
        'ldap_user_attribute' => '0',
        'ldap_ssl' => '0',
        'ldap_tls' => '0',
        'ldap_elusers' => '0',
        'ldap_search_base' => '0',
        'richtext' => '0',
        'allow_print' => '0',
        'roles_allowed_to_print' => '0',
        'show_description' => '1',
        'anyone_can_modify' => '0',
        'anyone_can_modify_bydefault' => '0',
        'nb_bad_authentication' => '0',
        'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '1',
    'enable_send_email_on_user_login' => '1',
        'enable_user_can_create_folders' => '0',
        'insert_manual_entry_item_history' => '0',
        'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '1',
    'enable_email_notification_on_user_pw_change' => '0',
        'custom_logo' => '',
        'custom_login_text' => '',
        'default_language' => 'english',
        'send_stats' => '0',
        'get_tp_info' => '1',
        'send_mail_on_user_login' => '0',
        'nb_items_by_query' => 'auto',
        'enable_delete_after_consultation' => '0',
        'enable_personal_saltkey_cookie' => '0',
        'personal_saltkey_cookie_duration' => '31',
        'email_smtp_server' => 'secret',
        'email_smtp_auth' => '',
        'email_auth_username' => '',
        'email_auth_pwd' => '',
        'email_port' => '25',
        'email_security' => '',
        'email_server_url' => '',
        'email_from' => 'teampass-hmn@aphp.fr',
        'email_from_name' => 'Teampass HMN',
        'pwd_maximum_length' => '40',
        'google_authentication' => '0',
        'delay_item_edition' => '0',
        'allow_import' => '0',
        'proxy_ip' => 'secret',
        'proxy_port' => '8080',
        'upload_maxfilesize' => '10mb',
        'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
        'upload_imagesext' => 'jpg,jpeg,gif,png',
        'upload_pkgext' => '7z,rar,tar,zip',
        'upload_otherext' => 'sql,xml',
        'upload_imageresize_options' => '1',
        'upload_imageresize_width' => '800',
        'upload_imageresize_height' => '600',
        'upload_imageresize_quality' => '90',
        'use_md5_password_as_salt' => '0',
        'ga_website_name' => 'TeamPass for ChangeMe',
        'api' => '0',
    'subfolder_rights_as_parent' => '0',
        'show_only_accessible_folders' => '0',
        'enable_suggestion' => '0',
        'otv_expiration_period' => '7',
        'default_session_expiration_time' => '60',
        'duo' => '0',
        'enable_server_password_change' => '0',
        'ldap_object_class' => '0',
        'bck_script_path' => 'C:/wamp/www/TeamPass/backups',
        'bck_script_filename' => 'bck_cpassman',
        'syslog_enable' => '0',
        'syslog_host' => 'localhost',
        'syslog_port' => '514',
        'timezone' => 'Europe/Paris',
        'menu_type' => 'context'
    );

```

**Comment by nilsteampassnet** [comment]
Please enable this option
![image](https://user-images.githubusercontent.com/1197546/48160266-acd0a100-e2d7-11e8-9f06-cfdc0f8eeb69.png)

I know the english string is not really good.
I will update is to `Send scheduled mails on user login`.

**Comment by mathzen** [comment]
This option is already enabled... Maybe the problem is relative to this cron task ?
```
mysql> SELECT * from teampass_misc where type = "cron";
+--------------+------+----------------+--------+
| increment_id | type | intitule       | valeur |
+--------------+------+----------------+--------+
|           62 | cron | sending_emails | 0      |
+--------------+------+----------------+--------+
1 row in set (0.00 sec)
```

**Comment by nilsteampassnet** [comment]
Can you do the next test?

- open web-browser,
- enable the developer web-console
- select tab 'network'
- log in Teampass with a normal user
- around 8 seconds after being connected, you should see 2 new queries send through the file `main.queries.php`
![image](https://user-images.githubusercontent.com/1197546/48224033-e9180600-e398-11e8-8505-7f91400588e5.png)
- select the first one
- new tabs will appear, click the one called "parameters"
- you should see `type | send_waiting_emails`
![image](https://user-images.githubusercontent.com/1197546/48224112-267c9380-e399-11e8-989c-862a1a3c7ce2.png)

If you don't found this query, then it means this option is not enabled.

If you found it, please click on tab "answer" or "response", and paste here the content of the tab.

**Comment by mathzen** [comment]
Ok I can see "send_wainting_emails" in the parameters tab, but the answer tab is completely empty.

**Comment by mathzen** [comment]
Excuse me I didn't have time to attend to this issue recently... What else can I do to diagnose the problem ? 
Thank you for the assistance.

**Comment by nilsteampassnet** [comment]
Don't you have an error in the logs such as max execution time?

**Comment by mathzen** [comment]
Ok I found a solution, thank you for your help, this thread can be closed.
