### ISSUE TITLE
Logging into TeamPass takes time with both LDAP and Local account

### ISSUE THREAD

**Issue by asmiah** [nilsteampassnet/TeamPass#2475]
### Steps to reproduce
1. navigate to our instance of teampass
2. try to login with a local or ldap account
3. login process takes up to 30-40 seconds

### Expected behaviour
When I first setup the server this was instantaneous, not sure what's gone wrong.

### Actual behaviour
Takes a long time to login

### Server configuration
CentOS 7

**Web server:**
HTTPD

**Database:**
phpMyAdmin (mysql)

**PHP version:**
7.0.32

**Teampass version:** 
2.1.27.16

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/2580637/tp.config.zip)

### Client configuration
**Browser:**
Issue persists across all browsers

**Operating system:**
Issue persists on all OS Win 10 and MacOS

#### Web server error log
```

[Wed Nov 14 12:00:46.980532 2018] [suexec:notice] [pid 973] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Nov 14 12:00:47.078769 2018] [auth_digest:notice] [pid 973] AH01757: generating secret for digest authentication ...
[Wed Nov 14 12:00:47.080988 2018] [lbmethod_heartbeat:notice] [pid 973] AH02282: No slotmem from mod_heartmonitor
[Wed Nov 14 12:00:47.892065 2018] [mpm_prefork:notice] [pid 973] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.32 configured -- resuming normal operations
[Wed Nov 14 12:00:47.892125 2018] [core:notice] [pid 973] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Are your users connected to internet?

If not, this issue is known (#2456), you will have to upgrade.

**Comment by asmiah** [comment]
Hi Nils,

Thanks for your response.

I had followed the discussion in the issue mentioned and upgraded to your latest version: 2.1.27.29 and I got the same issue as LemonLight mentioned in (#2456 )

I was also getting issues post login, the login worked and then the folders would not load this was in Chrome and Firefox.

I also indeed got a blank information box followed by the page crashing and a pop up saying "Hacking Attempt" 

The issues seem to disappear in Edge and IE upon first login but after a while of clicking around same issues appeared.

I've reverted back to previous version for now: 2.1.27.16

Please can you advise?

**Comment by nilsteampassnet** [comment]
I'm very surprised because 2.1.27.29 fixes this issue.

All users that have migrated from 2.1.27.27 to 2.1.27.29 don't have any more this issue.

I would recommend to migrate and clear cache.

**Comment by asmiah** [comment]
Thanks Nils, when you say clear cache - do you mean browser cache?

Anything else to look out for/do when an upgrade has been carried out?

**Comment by nilsteampassnet** [comment]
no nothing else.
