### ISSUE TITLE
reopen issue #2474 a manager can't view users

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#2478]
this reopen issue #2474 

here is my configuration:
a manager has the "responsibilty" of a role:
![param_admin](https://user-images.githubusercontent.com/10242259/48773983-349baf80-ecc9-11e8-9ae3-c49111ad5de3.png)

some users are managed by this manager:
![users_bug](https://user-images.githubusercontent.com/10242259/48769991-60b13380-ecbd-11e8-857e-f45324ce1a6f.jpg)

and the manager cannot see them in the "admin users" tab:
![bug_admin](https://user-images.githubusercontent.com/10242259/48770034-7aeb1180-ecbd-11e8-9efb-660773fcff57.jpg)

as I said, this configuration was working in release 2.1.27.7

**Comment by nilsteampassnet** [comment]
Can you try to display 100 objets?

**Comment by sfrlaurent** [comment]
Yes, you’re right.
I have 181 users , a few of them are in the role I’m testing. With 100 items display, I can see the users managed by the given manager who are in the 100 first users.
Cordialement,
Patrick LAURENT


De : Nils Laumaillé [mailto:notifications@github.com]
Envoyé : mardi 20 novembre 2018 18:49
À : nilsteampassnet/TeamPass <TeamPass@noreply.github.com>
Cc : LAURENT, Patrick <patrick.laurent@sfr.com>; Author <author@noreply.github.com>
Objet : Re: [nilsteampassnet/TeamPass] reopen issue #2474 a manager can't view users (#2478)


Can you try to display 100 objets?

**Comment by sfrlaurent** [comment]
I'm not an expert in php but I did a change in datatable.users.php :

replace the test on line 129 :
 if (isset($_SESSION['is_admin']) === false
    && isset($_SESSION['user_can_manage_all_users']) === false

by the old test I  found in the older release:

if (!$_SESSION['is_admin'] && !$_SESSION['user_can_manage_all_users']) {

and it's OK now
