### ISSUE TITLE
Allowed Folder limitation

### ISSUE THREAD

**Issue by harryaccu** [nilsteampassnet/TeamPass#2479]
So far, I was able to add new items and add its access to specific users. Now, when I added new item and tried to give its permission to specific user, it keeps loading. The user already has access to 85 folders. This 86th folder's permission is not getting applied for this user. Is there any limitation or do I need to tweak any setting to give him more than 85 folders' permission?
![allowed-folder-limit](https://user-images.githubusercontent.com/45239226/48854954-1fae4180-edd9-11e8-8d94-8ebcde35ea57.png)

**Comment by nilsteampassnet** [comment]
No there is no such limitation hard coded.
On my test server, I'm using more than 200 folders.

Can you please follow instruction in this [page](https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console) to get the error returned by the server when performing this operation?

**Comment by harryaccu** [comment]
It says this:

Data too long for column 'groupes_visibles' at row 1SZf/W6qqqqoI6s77iOGXkcO8KDs5CUJPTC8oM2UgWkFQcK1dJyLAJDwK6pLTf5510Fe1bFMZBLacYm7icOEvF0yueYpCinA4gxOq33TW9s4wmCORGJOZICxQwNA7oJEUNH3IPCRleMxqtbur

**Comment by harryaccu** [comment]
I was able to figured out. If any one faces the same issue, here is what I did:

- Found out the "groupes_visibles" colum in users table under the database which was created for this project.
- Increased the length of this colum from Varchar(255) to Varchar (1000).

This has fixed the issue. Now, I am able to allow more folders to any user.
