### ISSUE TITLE
Login problem after upgrade

### ISSUE THREAD

**Issue by codedge** [nilsteampassnet/TeamPass#2480]
After upgrading from 2.1.27.16 to 2.1.27.29 we cannot login anymore. Only the spinner icon with the text "Please identity yourself" ist shown.

![teampass](https://user-images.githubusercontent.com/4409904/49027609-db3bf080-f1a0-11e8-9902-3878d46e1a5c.png)

### Steps to reproduce
1. Update to 2.1.27.29
2. Try to login again
3. Error

### Expected behaviour
The login should be possible without error.

### Actual behaviour
Only the spinner is shown.

### Server configuration
**Operating system**: Debian 9

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 7.1

**Teampass version:**  2.1.27.29

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
[Mon Nov 26 17:17:10.978885 2018] [php7:error] [pid 10421] PHP Fatal error:  Cannot declare interface PasswordGenerator\\RandomGenerator\\RandomGeneratorInterface, because the name is already in use in /home/www/tp/releases/20180723183219/src/includes/libraries/PasswordGenerator/RandomGenerator/RandomGeneratorInterface.php on line 5
```

**Comment by ST-aus-D** [comment]
Greetings
A former colleague placed the above issue. Meanwhile we managed to update to `2.1.27.33` successfully :)
First there was s similar error as the above mentioned. But we still managed to login with regular users. After an Apache restart everything is working fine now -- without any notable errors.

----

I would suggest to close this topic as: **"somehow resolved"** :)
Thank you very much.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
