### ISSUE TITLE
Search results not more showing complete folder path

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#2481]
### Steps to reproduce
1. make a search in the upper/right box
2. The results not show more the result item complete path but only the item
3. Before the 2.1.27.29 update the serach result show complete path

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Windows 

**Web server:**
Apache 

**Database:**
Mysql

**PHP version:**

**Teampass version:** 
2.1.27.29

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome/Firefox

**Operating system:**
Windows

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by antoweb** [comment]
![image](https://user-images.githubusercontent.com/32364871/49085951-92913f80-f253-11e8-80a1-37adc6e7a240.png)

**Comment by antoweb** [comment]
![image](https://user-images.githubusercontent.com/32364871/49085976-a177f200-f253-11e8-9795-fb68dd468482.png)

**Comment by nilsteampassnet** [comment]
Perhaps an issue with the cache table.
Can you please reload it?
![image](https://user-images.githubusercontent.com/1197546/49106608-ed428f80-f283-11e8-9aa8-018c94e41ea0.png)

**Comment by antoweb** [comment]
Thanks Nils 
work!
Bye
