### ISSUE TITLE
Login Function Breaks after Initial Uses; No graphics;  Cannot Login

### ISSUE THREAD

**Issue by C0mpl1anceArch1tects** [nilsteampassnet/TeamPass#2484]
### Steps to reproduce

1.	Fresh install of Teampass, pulled from Github by PLESK automatic deployment.
2.	Install per install instructions.  Go through browser-based setup fine and configure.   Domain works fine, https: setup properly.
3.	Use system immediately after install and works fine.  Do some setup.  Multiple logins and log outs and using different roles (admin, Manager, and R/O). Screens showed graphics properly. Checked usage of multiple functions and seemed everything is working.
4.	Leave overnight (bizarrely) and login changes to all text (no graphics) at some point.  Impossible to login.   Image shown.   Multiple attempts to fix (permissions review and change, evaluation of config files, etc., checked multiple browsers (Firefox, IE 11 and Chrome, along with Safari on iPhone – all the same).  Checked latest errors and specifically csrfProtector – file settings were set properly.  Also checked csrfp.config.php file for urls and they were correct.
5.	I uninstalled and RE-installed with a new pull twice but it keeps happening – after initial couple of successful logins, I go away and something breaks and login is broken – doesn’t make sense.

![image](https://user-images.githubusercontent.com/42744482/49174614-c1bbb580-f314-11e8-8b08-f07a95d0c4ce.png)

### Expected behaviour
The login should not have changed.   The installation should’ve kept working as I left it.

### Actual behaviour
Screen is shown as above – unable to login.

### Server configuration
Ubuntu 16.04.5 LTS‬ 
Nginx
Plesk

**Web server:**
Apache (not sure version)

**Database:**
MySQL

**PHP version:**
7.0.32

**Teampass version:** 
 2.1.27.29
**Teampass configuration file:**

[tp.config.php.docx](https://github.com/nilsteampassnet/TeamPass/files/2626216/tp.config.php.docx)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
FRESH INSTALL

### Client configuration
**Browser:**
Multiple browsers -- Firefox, Chrome, IE 11 (PC), Safari iPhone
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
Not sure how to do this - multiple log filess -- can pull but not sure which you need.

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
I'm hoping this is it.
![image](https://user-images.githubusercontent.com/42744482/49176326-99ce5100-f318-11e8-8131-2db41787a0a3.png)

**Comment by nilsteampassnet** [comment]
Please refresh your local webbrowser cache.
