### ISSUE TITLE
When press profile picture, it show error msg 

### ISSUE THREAD

**Issue by silv3r1314** [nilsteampassnet/TeamPass#2488]
### Steps to reproduce
1. everytime I press profile it show error while loading 
2.
3.

### Expected behaviour

After fresh install team pass, when I try to set email, it keep on fail. I realize I miss out the profile email haven configure. Once I press the profile it keep on prompt this error message 

### Actual behaviour
Fail to configure email address 

### Server configuration
**Operating system**:
Windows 10 pro 
**Web server:**
Wamp server 
**Database:**
phpMyAdmin 4.8.3
**PHP version:**
php 7.2.12

**Teampass version:** 
 2.1.27.29 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
You have an issue in your url or path somewhere.
Please read https://teampass.readthedocs.io/en/latest/errors/#error-403-500-blank-page
Please share your urls and paths and jUrl variable value.
