### ISSUE TITLE
No Folders tree and key manager

### ISSUE THREAD

**Issue by olegtarasenko** [nilsteampassnet/TeamPass#2490]
Perhaps, I didn't understand full usage of this servers app.
But after installation/configuration I don't see Folder tree or key manager icon, so I can't import xml, etc.
I've created folders, users, roles but no key management. 

I have TeamPass 2.1.27.29.
Ubuntu server 18.04
PHP 7.0.32-4

**Comment by nilsteampassnet** [comment]
HAve you followed https://teampass.readthedocs.io/en/latest/install/setup/

Check the pages inside this documentation website.

For importing, you need to enable this feature.

**Comment by olegtarasenko** [comment]
Ran Initial setup pages, now it is OK. Thank you for prompt support!
