### ISSUE TITLE
Upgrade error bck_script_key

### ISSUE THREAD

**Issue by saddy001** [nilsteampassnet/TeamPass#2494]
### Steps to reproduce
1. Upgrade Teampass with the upgrade script.php

### Expected behaviour
No errors should occur

### Actual behaviour
Updater hangs at step upgrade_run_defuse...php
See description at bottom

### Server configuration
**Operating system**:
Win 10

**Web server:**
IIS

**Database:**
MariaDB

**PHP version:**

**Teampass version:** 
2.1.27.29 -> 2.1.27.30

The upgrade process modifies the file tp.config.php where the key "bck_script_key" is contained. If this key contains a ' (single quote), which is the case here, it is not valid php anymore, since the array values are quoted with single quotes too. Can be fixed e.g. by replacing the array quote chars with " (double quote). If the password can contain double quotes too (not the case here) then this is not a solution. If replaced with double quotes, of course this char ist then forbidden in the other values too.

**Comment by nilsteampassnet** [comment]
Yes you are right, I missed this case.
Indeed the tp.config.php file is rebuilt at the end of the upgrade and the value is not sanitized.
I'm fixing this.
Thank you.

**Comment by saddy001** [comment]
Thanks. For Teampass to work again, I replaced the quote chars. But the upgrade script stopped at the *defuse*-step. Although everything seems to work now, are there other important steps of the update script after this step that I'm missing now?

**Comment by nilsteampassnet** [comment]
What are the errors you get at defuse-step?

Normally this step is not needed as you are updating from .29.

**Comment by saddy001** [comment]
I think a syntax error from tp.config.php was raised.
