### ISSUE TITLE
Customer fields 

### ISSUE THREAD

**Issue by edelmanns** [nilsteampassnet/TeamPass#2497]
Installed TeamPass Version: 2.1.27.24 

### Steps to reproduce
1. Login as admin
2. Settings/Customer Fields
3. Create a new category and a new field
  
![grafik](https://user-images.githubusercontent.com/44601068/49858749-1d4a7080-fdf6-11e8-987e-0594ad9f57d2.png)
  

Login as non Admin to modify an existing item.

Enter in the new field: domain\account
After saving will shown correctly.
Now change the Item an go back to the changed item.

### Expected behaviour
The entry should shown like domain\account

### Actual behaviour
The entry will shown like domain&#92;account

Thanks

**Comment by edelmanns** [comment]
Sorry i see the actaul behaviour is wrong the entry is like "domain&amp...&ampaccount"

**Comment by nilsteampassnet** [comment]
Confirmed.

Thank you
