### ISSUE TITLE
Unable to update 2.1.26 to 2.1.27

### ISSUE THREAD

**Issue by mrglobule** [nilsteampassnet/TeamPass#2498]
### Steps to reproduce
1. upgrade 2.1.25 to 2.1.26 ok
2. upgrade 2.1.26 to 2.1.27 KO
3. stay block on step 4
upgrade_run_defuse_for_pwds.php - Loop #1 is now running ... 

### Expected behaviour
Tell us what should happen

### Actual behaviour
upgrade_run_defuse_for_pwds.php - Loop #1 is now running ... 

### Server configuration
**Operating system**:
Debian 8
**Web server:**
	Apache/2.4.10
**Database:**
MySQL 	5.5.62
**PHP version:**
PHP Version 5.6.38-0+deb8u1
**Teampass version:** 
2.1.26
**Teampass configuration file:**
????
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Updated from 2.1.25
### Client configuration
**Browser:**
Chrome Version 69.0.3497.81
**Operating system:**
Windows 7
#### Web server error log
```
[Thu Dec 13 13:35:29.753964 2018] [:error] [pid 14353] [client 133.1.25.16:53826] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF0\\x00\\x00', false)\n#1 /var/www/html/teampass/sources/main.functions.php(386): Defuse\\Crypto\\Key::loadFromAsciiSafeString(false)\n#2 /var/www/html/teampass/install/upgrade_run_defuse_for_pwds.php(121): cryption('EJf1yLkD', false, 'encrypt')\n#3 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: http://133.1.25.179/teampass/install/upgrade.php

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
upgrade_run_defuse_for_pwds.php:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Regards

**Comment by nilsteampassnet** [comment]
Did you upgrade to 2.1.26-final-3?
What 2.1.27 package do you used?

**Comment by mrglobule** [comment]
Thanks for replying,
I upgrade to 2.1.26.20 ? the package i can find
I downloaded the master branch for 2.1.27

**Comment by nilsteampassnet** [comment]
Some tips --> https://teampass.readthedocs.io/en/latest/install/upgrade/#upgrade-from-very-old-versions
Update to 2.1.26-final-3 (https://github.com/nilsteampassnet/TeamPass/releases/tag/2.1.26-final-3)
Then upgrade to latest 2.1.27 (https://github.com/nilsteampassnet/TeamPass/releases)
