### ISSUE TITLE
Weird folders on first login with LDAP user

### ISSUE THREAD

**Issue by Emi94** [nilsteampassnet/TeamPass#2499]
### Steps to reproduce
1. Configure LDAP auth
2. Login with an LDAP user for the first time on Teampass

### Expected behaviour
User should see his personal folder and other ones if he has access

### Actual behaviour
User sees some weird folders
![image](https://user-images.githubusercontent.com/11816318/49942862-266b3880-feef-11e8-8666-63f75888b951.png)
After a relogin, he sees the correct folders

### Server configuration

**Teampass version:** 2.1.27.30

**LDAP server type:** Windows / Active Directory

**Comment by nilsteampassnet** [comment]
COnfirmed.

I have provided a fix. Delivered in next release.

**Comment by andreas-tr** [comment]
Did you have released the bugfix?
