### ISSUE TITLE
see_item syntax error on Win2012 Edge 

### ISSUE THREAD

**Issue by nikdoof** [nilsteampassnet/TeamPass#2504]
### Steps to reproduce
1. Open Search in Edge on Windows 2012
2. Click the "eye" icon, calling `see_item`

### Expected behaviour

Popup window with the password details appear

### Actual behaviour

No action

### Server configuration
**Operating system**:

RHEL 7.6

**Web server:**

Apache 2.4

**Database:**

MariaDB

**PHP version:**

5.4.5

**Teampass version:** 

2.1.27

### Client configuration
**Browser:**

Edge

**Operating system:**

Windows 2012

## Solution

In `sources/find.queries.php`, the `$restrictedTo` value can be passed into the generated HTML as an empty string rather than undefined, resulting in a JS snippet of `see_item(x,x,x,x,)` due to the JS engine in Edge/Win2012 this is a syntax error and ignored. Defining `$restrictedTo` to `undefined` on empty resolves the issue.

**Comment by nilsteampassnet** [comment]
I don't know what is Windows 2012, are you talking about Windows Server 2012?

Now using Edge and Windows 10, there is no issue to use this eye icon
Before clicking
![image](https://user-images.githubusercontent.com/1197546/50305880-73718080-0494-11e9-925f-0ad4c96ea0d6.png)

On click
![image](https://user-images.githubusercontent.com/1197546/50305902-7c625200-0494-11e9-8f31-91fa272d270c.png)

Unfortunatelly I have no way to fix this issue.
New version 3.0 is in development, it could be checked during this time.

**Comment by nikdoof** [comment]
Yes, Windows Server 2012, works on Windows 10 without issue, hence tagging this issue rather than just an Edge issue as a Windows Server 2012 and Edge Issue.

Testing on the actual affected OS would be a start at reproducing the issue 🤷‍♀️
