### ISSUE TITLE
Can't copy or move from the personal folder

### ISSUE THREAD

**Issue by radoslawch** [nilsteampassnet/TeamPass#2506]
### Steps to reproduce
1. Create an item in the personal folder.
2. Try to copy the item to a public folder.
3. Try to move the item to a public folder.

### Expected behaviour
- Item should be copied and moved to a public folder, be accessible to all users able to read that folder, and shouldn't require a saltkey.

### Actual behaviour
- Item isn't copied with "Requested JSON parse failed." alert.
- Item is moved but is unaccessible with a yellow label and an error:
```
Access to password item denied!
Author: username
Restricted to: 
```
Even an administrator can't edit its access restrictions which means the password is lost.

### Server configuration

*Providing any information I can (I don't know server's details as a user), sorry there's no more now.*

**Operating system**: Ubuntu

**Updated from an older Teampass or fresh install:** originally installed 01.2016 and updated a few times up to current version.

### Client configuration
**Browser:** Firefox 64 (64-bit)

**Operating system:** Windows 10 Pro

**Comment by nilsteampassnet** [comment]
I don't know what version you are using. Certainly an old one because in latest this works.
I suggest you to upgrade to latest in a qualification environment to perform your tests.
