### ISSUE TITLE
Send new Password

### ISSUE THREAD

**Issue by chmich** [nilsteampassnet/TeamPass#2507]
Hi Nils,

i have TeamPass 2.1.27.9 and i am missing the Function: Send new Password to the user, so that a mail is sent to the user with a new initial password.

Is there a function in the current release?
i could not found it in the changelog.

Thanks, 
Christian

**Comment by nilsteampassnet** [comment]
Hello

In the login page, a link should be displayed.

![image](https://user-images.githubusercontent.com/1197546/50890936-790b1800-13fb-11e9-9384-f8ea37b50932.png)
This link permits your user to reset his password.

If it is not displayed, then it means you have enabled LDAP.
With LDAP enabled, the link is removed by default but you can make it shown back by enabling this feature.
![image](https://user-images.githubusercontent.com/1197546/50891093-d7d09180-13fb-11e9-81f6-d835fe0b5a51.png)

I hope this will help

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.

**Comment by chmich** [comment]
Sorry, maybe my question was not clear:
I meant a button on the Admin-Page where i administrate the user-list, and there a button: "Resend Password to the user", which is the same functionality like the "Forgot-Password"

**Comment by nilsteampassnet** [comment]
Oh ok, so I checked, and I found something wrong in the code.
Of course if you have option "Email user when user password is changed" enabled, an email should be send when changing the password in Users page.
I identified a case in which this email was not send.
I will provide a fix.

Thank you for this.
