### ISSUE TITLE
ISO Latin characters are represented as HTML code. i.e. \ (backslash) becomes &#92; in password / account fields

### ISSUE THREAD

**Issue by J4ck1ntheb0x** [nilsteampassnet/TeamPass#2512]
Despite several reports this issue with incorrect representation of the backslash in login/account/password fields is still not fixed in v.2.1.26 (!!!)

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This is fixed in latest 2.1.27.
![image](https://user-images.githubusercontent.com/1197546/50887496-9936d900-13f3-11e9-8257-1b40e6e97244.png)

I don't maintain old versions.
