### ISSUE TITLE
2FA Google Authenticator Error Docker

### ISSUE THREAD

**Issue by ciscoshizzel** [nilsteampassnet/TeamPass#2516]
### Steps to reproduce
1. Install teampass using the example docker-compose file found here: https://github.com/nilsteampassnet/TeamPass/blob/master/docker-compose.yml

2. After the installation is complete, login with the administrator account, create a new user, configure mail settings and enable google 2fa.

3. Logout with the admin account, enter the username and password of the user account that was created in step 2, and click on "I need a new QR code. Please send me by email a temporary Identication Code" 

4. Open the mail that was send to the user, and manually add the Identication code to Google Authenticator (In earlier versions of Teampass we could scan an QR code, In this version however that does not seem to work.

5. After the Identication code is added to Google authenticator, enter the 6 digit authentication code that is displayed by Google Authenticator in the 2FA field at the login page of teampass.

6. Click on "Log In" --> The message "The Google Authenticator code is wrong" is displayed.

Keep in mind that the code Identification code was copied and pasted, and we tried this with multiple users without success.

### Expected behaviour
- After clicking on "Log In" actually being able to login.
- QR code is received in the mail of the user instead of an "Identication code" that has to be entered manually 

### Actual behaviour
- Not being able to login when Google Authenticator 2FA is enabled

### Server configuration
**Operating system**:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-29-generic x86_64)

**Web server:**
Whatever is included in Docker teampass/teampass

**Database:**
Docker mysql/mysql-server:5.7

**PHP version:**
Whatever is included in Docker teampass/teampass

**Teampass version:** 
2.1.27.32

**Teampass configuration file:**
Where can I find this?

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Safari 12.0.2
Chrome 71.0.3578.98 (Official Build) (64-bit)

**Operating system:**
macOS Mojave version 10.14.2

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I tested Google mfa before releasing this version.
And did it also now and it works.

Just some precision concerning the behavior.
What you describe is normal, there is no QR sent by email.
When you request a Google MFA code, it sends by email a temporary code.
This code is used to confirm that you are the correct user.

Use this code in the Google MFA field, this will popups a QR code.
Flash this QR and enter the random Google MFA code to get connected.

**Comment by ciscoshizzel** [comment]
Hi Nils,

Thank you for your quick response!
We got it working now, I'm used to an older version of Teampass where the QR code was send directly to the mail address of the user, so I thought we hit a bug when we only received a text string. Turns out, I didn't read the instructions in the mail well enough.

Sorry for bothering you, Have a nice weekend!
