### ISSUE TITLE
Unable to login since 2.1.27.28

### ISSUE THREAD

**Issue by manusfreedom** [nilsteampassnet/TeamPass#2517]
Able to fix it by revert the lines of load.php of this commit https://github.com/nilsteampassnet/TeamPass/commit/2e04d8e4a08941a04ad18d464292552a4f62338f

### Steps to reproduce
1. Upgrade to 2.1.27.28 or above
2. Try to login

### Expected behaviour
Able to login (admin, users,...)

### Actual behaviour
Unable to login at all, without any error in my log

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.37

**Database:** MariaDB 10.3

**PHP version:** PHP 7.2.13

**Teampass version:** 2.1.27.28 to 2.1.27.32

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** 2.1.27.27

### Client configuration
**Browser:** All

**Operating system:** All

#### Web server error log
```
No erreor log...
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Nothing
```

**Comment by nilsteampassnet** [comment]
I believe this is related to settings for LDAP connection.

PLease have a look on https://teampass.readthedocs.io/en/latest/install/ldap/

Connect as admin and adapt. Provide the ldap debug  file

**Comment by manusfreedom** [comment]
I validated my LDAP settings and no problem.
I just added account_suffix to be sure.

```
Get all LDAP params :
mode : 1
type : posix-search
base_dn : 0
search_base : ou=people,dc=mydomain,dc=com
bind_dn : uid=teampass-auth,ou=people,dc=mydomain,dc=local
bind_passwd : ************
user_attribute : uid
account_suffix : dc=mydomain,dc=com
domain_controllers : ldap.mydomain.local,myserver001.mydomain.local,myserver002.mydomain.local
ad_port : 636
use_ssl : 1
use_tls : 0
*********

LDAP URIs : ldaps://ldap.mydomain.local:636 ldaps://myserver001.mydomain.local:636 ldaps://myserver002.mydomain.local:636
LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=firstname.lastname)(objectClass=customAccount))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Firstname
                )

            [0] => givenname
            [sn] => Array
                (
                    [count] => 1
                    [0] => Lastname
                )

            [1] => sn
            [mail] => Array
                (
                    [count] => 3
                    [0] => firstname.lastname@mydomain.com
                )

            [2] => mail
            [count] => 3
            [dn] => uid=firstname.lastname,ou=people,dc=mydomain,dc=com
        )

)

User was found. uid=firstname.lastname,ou=people,dc=mydomain,dc=com\n
```

**Comment by nilsteampassnet** [comment]
Is this solved?

**Comment by manusfreedom** [comment]
Not solved.
