### ISSUE TITLE
Empty response in utilities -> Renewal follow-up

### ISSUE THREAD

**Issue by terwarf** [nilsteampassnet/TeamPass#2519]
### Steps to reproduce
1. Goto utilities
2. Goto Renewal follow-up
3. Submit the form

### Expected behaviour
I should get a list.

### Actual behaviour
I get a blank page.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 7.2

**Teampass version:** 2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** updated

The form passes the parameter "type" = "generate_renewal_listing" to sources/views.queries.php .
But in the switch statement in this file i only find "generate_renewal_pdf" .

**Comment by nilsteampassnet** [comment]
Yes I know this bug.

Didn't yet found a solution. I will.
