### ISSUE TITLE
Error with Automatic password change on remote server

### ISSUE THREAD

**Issue by asantar0** [nilsteampassnet/TeamPass#2521]
### Steps to reproduce
1.I enable the function to change the remote key
2.The change is successful on the server
3.But in Teampass the key is not updated to the new one that was updated

### Expected behaviour
The key in the teampass database should be changed to the new one

### Actual behaviour
The key is updated on the server but not in the teampass database

![screenshot_20181228_090155](https://user-images.githubusercontent.com/24227371/51251317-ca755300-1977-11e9-9564-d90350a388c1.png)

### Server configuration
**Operating system**: Debian 9.6

**Web server**: Apache2 2.4.25-6

**Database**: MariaDB 10.1.37-0

**PHP version**: PHP 7.0.33

**Teampass version**: 2.1.27.31

**Teampass configuration file**:

$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'https://xxx.xxx',
    'favicon' => 'https://xxx.xxx/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'url_to_upload_folder' => 'https://xxx.xxx/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'https://xxx.xxx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '1',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '1',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'XXX',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1544483364',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '30',
    'email_smtp_server' => 'xxx.xxx',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'xxx@xxx.xxx',
    'email_from_name' => 'XXXXXXX',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '1mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '1',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'XXX.XXX.XXX.XXX',
    'syslog_port' => 'XXX',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'XXX/XXX/XXX',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'XXX',
    'admin_2fa_required' => '0',
);

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser**: Firefox 60 and Google Chromium

**Operating system**: Debian 9.6

#### Web server error log
NOT APPEAR

#### Insert your webserver log here
NOT APPEAR

**Comment by asantar0** [comment]
@nilsteampassnet ?

**Comment by asantar0** [comment]
@nilsteampassnet Solution for that?

**Comment by nilsteampassnet** [comment]
No sorry didn't get the time to work on this. I will

**Comment by asantar0** [comment]
@nilsteampassnet Any news about it?

**Comment by asantar0** [comment]
@nilsteampassnet Does still this bug exist in Teampass?

**Comment by asantar0** [comment]
Hello @nilsteampassnet, any news about this?
