### ISSUE TITLE
SESSION EXPIRES

### ISSUE THREAD

**Issue by angelitodiaz1** [nilsteampassnet/TeamPass#2524]
### Steps to reproduce
1. LOGIN WITH ADMIN
2. RECURSIVE LOGOUT SESSION EXPIRES
3.

### Expected behaviour
MAKE LOGIN WELL

### Actual behaviour
WRONG ACCESS, NOT LOGIN, SESSION EXPIRES

### Server configuration
**Operating system**:
CENTOS

**Web server:**

**Database:**

**PHP version:**
7.2

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by angelitodiaz1** [comment]
really, I do not access because when login, system logout inmediately.

**Comment by Wrightie** [comment]
Same here.
When I login, TeamPass logs in and immediately logs out.
Using version 2.1.25.
Already set session.gc_maxlifetime=7200, but got the same result.
Tried with multiple browsers and tried cleaning the browser cache.
Teampass is running on a dedicated VM based on Alpine Linux + Apache 2.4 + PHP 5.
It worked fine till last use, which was about last week.
Thank you for your help.

**Comment by Wrightie** [comment]
Made a new test and cheched logs.
Following is some content extracted from /var/log/apache2/error.log:

_[Wed Jan 30 11:47:45.306105 2019] [:error] [pid 30774] [client 192.168.1.100:57686] PHP Warning:  file_put_contents(/www/includes/libraries/csrfp/libs/csrf/../../js/csrfprotector.js): failed to open stream: Permission denied in /www/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 164, referer: http://[mysite]/index.php
[Wed Jan 30 11:47:52.771021 2019] [:error] [pid 30786] [client 192.168.1.100:57698] PHP Warning:  file_put_contents(/www/includes/libraries/csrfp/libs/csrf/../../js/csrfprotector.js): failed to open stream: Permission denied in /www/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 164, referer: http://[mysite]/index.php?page=items
**[Wed Jan 30 11:47:53.630511 2019] [:error] [pid 30775] [client 192.168.1.100:57701] PHP Notice:  Undefined variable: debug in /www/error.php on line 20, referer: http://[mysite]/index.php?session=expired
[Wed Jan 30 11:47:53.630536 2019] [:error] [pid 30775] [client 192.168.1.100:57701] PHP Notice:  Undefined index: session in /www/error.php on line 24, referer: http://[mysite]/index.php?session=expired**
[Wed Jan 30 11:47:53.630550 2019] [:error] [pid 30775] [client 192.168.1.100:57701] PHP Warning:  fputs() expects parameter 1 to be resource, null given in /www/error.php on line 26, referer: http://[mysite]/index.php?session=expired
[Wed Jan 30 11:47:53.640111 2019] [:error] [pid 30775] [client 192.168.1.100:57701] PHP Warning:  file_put_contents(/www/includes/libraries/csrfp/libs/csrf/../../js/csrfprotector.js): failed to open stream: Permission denied in /www/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 164, referer: http://[mysite]/index.php?session=expired
[Wed Jan 30 11:47:53.744078 2019] [:error] [pid 30775] [client 192.168.1.100:57701] PHP Warning:  file_put_contents(/www/includes/libraries/csrfp/libs/csrf/../../js/csrfprotector.js): failed to open stream: Permission denied in /www/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 164, referer: http://[mysite]/index.php_

Hope this will help fixing the code.
Thank you for your help.

**Comment by nilsteampassnet** [comment]
This is not a problem related to Teampass but from the configuration.
As you can see in your logs, Apache cannot access to some files.
Please ensure that access rights are correct as described in https://teampass.readthedocs.io/en/latest/install/install-linux/#set-folders-permissions

**Comment by Wrightie** [comment]
Thank you for your tip, it solved the permission issues, but not the session ones.
This is my new log:

_[Sat Feb 02 12:17:16.265110 2019] [:error] [pid 31902] [client 192.168.1.100:56258] PHP Notice:  Undefined variable: debug in /www/error.php on line 20, referer: http://[mysite]/index.php?session=expired
[Sat Feb 02 12:17:16.265154 2019] [:error] [pid 31902] [client 192.168.1.100:56258] PHP Notice:  Undefined index: session in /www/error.php on line 24, referer: http://[mysite]/index.php?session=expired
[Sat Feb 02 12:17:16.265173 2019] [:error] [pid 31902] [client 192.168.1.100:56258] PHP Warning:  fputs() expects parameter 1 to be resource, null given in /www/error.php on line 26, referer: http://[mysite]/index.php?session=expired_

As you'll see, it's the same content I made bold in my older post; don't know if these warnings are related to the strange behaviour about the log-in/kick-out.
Please help me with this; tell me if there are some additional infos that can help you.
Thank you in advance.

**Comment by Wrightie** [comment]
Thought it was a version issue, so I ended up upgrading step-by-step to v2.1.27.33 (current version).
No problems upgrading, but I finally det the same issue: I can get in (I can see for a second the admin page), but I'm suddenly kicked out.
No more errors logged, so the upgrade solved the warnings I reported in my older posts.
Really, I can't access my passwords; please help.
Thank you.

**Comment by nilsteampassnet** [comment]
Yes there must have been a change somewhere in the configuration of the server related the session / time.

In you previous log, I'm surprised to see the `debug` variable and `fputs()` instruction. There is no such data inside error.php file, are you sure to use the original files?

**Comment by Wrightie** [comment]
Yep, the the `debug` variable and `fputs()` instruction were related with a previous version (<2.1.23).
Warnings disappeared when I updated TeamPass to the latest version (2.1.27).

By the way, the issue was probably related to some server issue, as it disappeared today after a server reboot.
You can mark the issue as solved; I suggest you to put this issue in the common errors wiki page, as I'm not the only one who experienced it.
Thank you for your time and effort, Nils.
Keep up the good work.

**Comment by ruliane** [comment]
From my experience, default_session_expiration_time should not :
1. be greater than 1440 (24 h)
2. be a multiple of 1440 (24 h)

Doing the former would cause the actual expiration time to be a modulo 24 h
Doing the latter would cause some early logout (especially with Chrome)
