### ISSUE TITLE
You are not allowed to see this page. 

### ISSUE THREAD

**Issue by luizmeireles** [nilsteampassnet/TeamPass#2525]
### Steps to reproduce
1.Open teampass
2. Change language or sing in with same user in 2 or more hosts
3. refresh the page or click on logoff

### Expected behaviour
That I can sing in on the teampass

### Actual behaviour
TeamPass shows : You are not allowed to see this page and side of that "Hacking attempt.."
### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache Service
**Database:**
Maria DB
**PHP version:**
7.0
**Teampass version:** 
2.1.27.29
**Teampass configuration file:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://172.20.2.97/teampass',
    'favicon' => 'http://172.20.2.97/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://172.20.2.97/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://172.20.2.97/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => '0',
    'ldap_suffix' => '',
    'ldap_domain_dn' => '',
    'ldap_domain_controler' => '',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1545228263',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'K4Q9JRPV4brfJhhGMa7WkEqfwBMpDM8eT3tN2VYE',
    'admin_2fa_required' => '1',
    'ldap_new_user_role' => '',
);

### Client configuration
ANY

**Operating system:**
ANY

#### Web server error log
[Fri Jan 18 11:48:29.560181 2019] [:error] [pid 3436] [client 172.20.2.43:48424] PHP Notice:  Undefined variable: LANG in /var/www/html/teampass/sources/core.php on line 85, referer: http://172.20.2.97/teampass/index.php
![b39cae09-cd07-479a-bcae-45d0a9722c1b](https://user-images.githubusercontent.com/15821989/51394018-fdeee380-1b17-11e9-95f0-b6e579a698a3.jpeg)

**Comment by luizmeireles** [comment]
![b39cae09-cd07-479a-bcae-45d0a9722c1b](https://user-images.githubusercontent.com/15821989/51400862-37c7e600-1b28-11e9-9277-81515bb377d3.jpeg)

**Comment by joelcpinheiro** [comment]
the error happening to me, this is the error when i update language to portuguese-br, [Thu Jan 31 12:38:16.037042 2019] [:error] [pid 194] [client 192.168.50.200:8272] PHP Notice:  Undefined variable: LANG in /var/www/html/teampass2/sources/core.php on line 85,
In the lin5 85, show the code "$link->set_charset($encoding);", my database charset encoding are uft8;

after update the language tha ocurred this error.

**Comment by L3V14TH4N** [comment]
I resolved by inserting a new administrator user in the mysql:
INSERT INTO teampass_users (login,pw,fonction_id) VALUES ('**user**','**<hash_password>**','**1**');
