### ISSUE TITLE
ERROR EN PROGRAMA TEAMPASS

### ISSUE THREAD

**Issue by Tasegure** [nilsteampassnet/TeamPass#2526]
Tengo  una  cuenta bloquada y cuando accedo como adminstrador no me aparecen los  usuarios del sistema. 
![img-20190121-wa0000](https://user-images.githubusercontent.com/46887394/51463810-79dd6b80-1d64-11e9-8be5-d5fd2dfc79cc.jpg)

 
Por favor contactad con nosotros para solucionar el problema, Gracias
![sin titulo](https://user-images.githubusercontent.com/46887394/51463772-5b777000-1d64-11e9-96da-5361f0049883.png)

**Comment by nilsteampassnet** [comment]
Can you please try using English language?
If you cannot reproduce this error, it is related to the language.
What language do you use?
