### ISSUE TITLE
Local authentication override

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#253]
It would be good to have the ability to flag a particular user for local authentication only.  
That way one might be able to create multiple local admin accounts which are not in LDAP, since TeamPass prohibits two people from using the same account concurrently.

My quick hack to solve this was to update main.queries.php and replace code as follows:

```
 $username == "admin"    ->   preg_match('/^admin(\.[\w]+)?$/',$username)
 $username != "admin"    ->   !preg_match('/^admin(\.[\w]+)?$/',$username)
```

This allows any user created with an "admin." prefix to bypass LDAP authentication.  
Using a "local." prefix is an alternative option, but a flag in the user's account would be much cleaner.

**Comment by hexxamillion** [comment]
This really would be nice but I no longer see this code in version 2.1.22 so this does not work for me.
