### ISSUE TITLE
Import csv fails / same format as export 

### ISSUE THREAD

**Issue by magrossm** [nilsteampassnet/TeamPass#2530]
Steps to reproduce

    Export to .csv from existing server.
    Modify entries with the same headers but different values for the them
    Select Browse CSV File, select file to upload from list.
    Import succesful but line just added as name of entry (see attached pics)

Expected behaviour

Migrating from old Teampass server to new server. Exported .csv file to import. Imported data is not aligned in proper fields when imported. Expect import to place fields in .csv into correct fields in TeamPass.
Actual behaviour

All data from .csv loaded into Label field. When file is modified per instruction the import fails.
Server configuration

Operating system:
Windows 2016 
Web server:
Server version: Wampserver 3.1.0 64 bit x64 – Apache 2.4.27 – PHP 5.6.31, 7.0.23, 7.1.9 – MySQL 5.7.19

Teampass version:
Teampass 2.1.27.30
Teampass configuration file:

Updated from an older Teampass or fresh install:
PLEASE attach to this issue the file /includes/config/tp.config.php.
Client configuration

Browser:
Chomium
Operating system:
Windows 7
Logs
Web server error log
![2019-01-28 11_53_36-teampass](https://user-images.githubusercontent.com/21271625/51832032-e7087800-22f3-11e9-8681-8e32c92b5a30.png)
![2019-01-28 11_54_03-teampass](https://user-images.githubusercontent.com/21271625/51832033-e7087800-22f3-11e9-92f7-c3bebd41cda2.png)

Insert your webserver log here

Log from the web-browser developer console (CTRL + SHIFT + i)

Insert the log here and especially the answer of the query that failed.

**Comment by manwe** [comment]
You need to adapt your exported csv. Import expects other columns. It happened to me when migrating from old teampass system to a new one.
