### ISSUE TITLE
Folder Tree is not displayed right

### ISSUE THREAD

**Issue by LucasJaiser** [nilsteampassnet/TeamPass#2531]
Hi,

the product was working fine till now. At the time we have more then 300 folders.
the Order of the folders is right but the level wehre is is displayed is not right. All folders are displayed on the same Level.

Does anybody have an idea on how to solve that problem?

### Expected behaviour
All folders got sorted in a specific level.

### Actual behaviour
All folders are displayed in the same Level

### Server configuration
Windows 8:

Web server:  Apache 2.4.18

Database: MySQL

PHP version: 7.0.4

Teampass version: 2.1.26

Updated from an older Teampass or fresh install: First install with some configurations.

### Client configuration
Browser: Chrome 71

Operating system: Windows 10

**Comment by nilsteampassnet** [comment]
Does this occurred after something done?
Changed a setting? created a new folder? moved a folder? anything that could explain a "rebuild" of the nested tree in database.

Can you try to create a new folder from the admin page

**Comment by LucasJaiser** [comment]
I think a colleague did something and didnt told me what.
All users with a different role could see the tree normal. 
I created a new Role with den same rights and it worked again.

Thanks for the Help.

**Comment by DocteurB** [comment]
I've the same problem , only the people who can see one folder (and the sub-folder) have this issue.

We have detroy it and rebuild it but we don't understand what hapened (only a-z and A-Z was used for the description)
