### ISSUE TITLE
Set PHP Session name

### ISSUE THREAD

**Issue by terwarf** [nilsteampassnet/TeamPass#2533]
### Steps to reproduce
1. Always present

### Expected behaviour
Login should work

### Actual behaviour
Random things

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.2 

**Teampass version:** 2.1.27.33

**Updated from an older Teampass or fresh install:** updated

Tempass doesn't set a session name, so PHP uses the default name "PHPSESSID" (this is also the name of the cookie).
When there are other services installed on the Server, that also use sessions (and don't set the name), this leads to overwriting data from other services (or teampass loosing the login).

This may explain some of the bugreports i'm seeing here.

Proposed solution: add 
```
session_name('teampass_session');
```
before each call to 
```
session_start();
```

And thank you for this nice project ;)

**Comment by rodehoed** [comment]
@terwarf  your are so right. It was causing very strange behaviour at our side too. 

We fixed it by:
`find . -type f -iname '*.php' -exec sed -i 's/session_start();/session_start(["name" => "TeamPass"]);/g' {} \;`
