### ISSUE TITLE
Syntax error in share permissions

### ISSUE THREAD

**Issue by lokko666** [nilsteampassnet/TeamPass#2534]
Hi everyone

Teampass works correctly except the share permissions button. But, when I press the button with an user administrator who has no users, works fine. Only fails when there are users to show

For this, I think the problem is that it does not correctly receive the users list.

### Steps to reproduce
1. Press button to share permissions
2.
3.

### Expected behaviour
Show a list of users to share permissions

### Actual behaviour
Pressing the button gives an error and then the window appears but without users
![tp](https://user-images.githubusercontent.com/47172936/51968699-e64a2000-2472-11e9-86c2-4ddd1b55e669.jpg)
![tp2](https://user-images.githubusercontent.com/47172936/51969377-8a809680-2474-11e9-93d2-83ddab6d289d.jpg)

### Server configuration
**Operating system**: Windows NT 10.0 build 14393 (Windows Server 2016) AMD64

**Web server:** Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/5.6.35

**Database:** 5.7.21

**PHP version:** 5.6.35

**Teampass version:** 2.1.27.33

**Updated from an older Teampass or fresh install:**
updated to 33 from 23

### Client configuration

**Browser:** Chrome - 71.0.3578.98

**Operating system:** Windows - 64bits```

**Comment by nilsteampassnet** [comment]
Ok I could reproduce.
New version will be delivered.

**Comment by lokko666** [comment]
Thank you very much Nils!!!!
