### ISSUE TITLE
low 40bit RC4 - pdf export?

### ISSUE THREAD

**Issue by trustbyte** [nilsteampassnet/TeamPass#2536]
### Steps to reproduce
1. export to PDF
2. write in the password
3. open with acrobat reader

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** TeamPass 2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
Why does the export to PDF uses the lowest possible encryption method? 40 bit RC4?
at least that says Acrobat Reader. is it so?
if it is so, why not use 128 RC4 or the better 256 AES?

from tcpdf: "document encryption up to 256 bit and digital signature certifications;"


thank you!

```

**Comment by trustbyte** [comment]
okey, i looked a bit under the hood.
Teampass uses Gibberish for the encryption part ( https://github.com/mdp/gibberish-aes, which is deprecated, by the way)

so tcpdf is used to write the pdf itself but the encryption is done by the Gibberish, right?

someone else can confirm the RC4 encryption?

**Comment by nilsteampassnet** [comment]
Thank you for your highlight.
I've changed the PDF encryption to AES 256 bit by using dedicated option of TCPDF.
I was not aware of this option but our ticket permitted me to get deeper in this library.
I will commit the fix today.

Gibberish is not used for PDF encryption. It is for offline mode.

In branch 3, this is totally changed.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
