### ISSUE TITLE
First time run blank page php parse error

### ISSUE THREAD

**Issue by matrix200** [nilsteampassnet/TeamPass#2543]
### Steps to reproduce
1. Open page for the first time
2. 
3.

### Expected behaviour
Initial configuration page?

### Actual behaviour
Blank page displayed

### Server configuration
**Operating system**:
Centos 6.10
**Web server:**
Apache 2.2.15
**Database:**
Mysql 5.1.73

**PHP version:**
php-5.3.3-49
**Teampass version:** 
2.1.27.33
**Teampass configuration file:**
Nothing yet?
**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Palemoon 28.3.1 (32bit)
**Operating system:**
Windows 7 64bit
#### Web server error log
```
Insert your webserver log here
``[Fri Feb 08 12:54:09 2019] [error] [client myip] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/teampass/index.php on line 706
`

#### Log from the web-browser developer console (CTRL + SHIFT + i)
NA
Insert the log here and especially the answer of the query that failed.
`NA`

**Comment by dromaniuk** [comment]
such brackets are allowed in further versions of PHP, but not in php 5.3... Holly molly it's deprecated so far... 
Just upgrade it to a new version. May work.

**Comment by matrix200** [comment]
Well, in the meantime, I decided to bite the bullet and upgrade to php 5.6.
Problem solved ;)

**Comment by dromaniuk** [comment]
> Well, in the meantime, I decided to bite the bullet and upgrade to php 5.6.
> Problem solved ;)

I'd recommend to migrate right to php7.2/7.3 xD
At least they are stable and supported)
