### ISSUE TITLE
how can I set/change administrator account password strength  - Urgent  help required - Also need under stand complexity lever 

### ISSUE THREAD

**Issue by Nathu2018** [nilsteampassnet/TeamPass#2545]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Nathu2018** [comment]
Please help  need urgent..

**Comment by nilsteampassnet** [comment]
As an account with privilege 'admin' can redefine his account, it is difficult ot force.
Nevertheless what you can do is to create a role called 'administrators' for which you set the minimum password strength to the value you want, and associate the admin accounts to this role.
THis should do the trick.

The complexity level is calculated relying on a library called simplepassmeter that uses the combination of letters to define a value from 0 to 100. The levels correspond to an obtained value.
