### ISSUE TITLE
cannot create user

### ISSUE THREAD

**Issue by Rookie1261** [nilsteampassnet/TeamPass#2547]
### Steps to reproduce
1. Login as admin
2. create new user
3. "Please wait!" doesn't come to an end

### Expected behaviour
a new user should exist

### Actual behaviour
"Please wait!" doesn't come to an end

### Server configuration
**Operating system**:
"SUSE Linux Enterprise Server 12 SP4"

**Web server:**
Apache/2.4.23 (Linux/SUSE)

**Database:**
mysql  Ver 15.1 Distrib 10.2.21-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP Version 7.0.7

**Teampass version:** 
2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome, Firefox, IE

**Operating system:**
macOS, Windows 10

#### Web server error log
No timed matching entries in the Apache error_log

**Comment by nilsteampassnet** [comment]
There must be an error in the log.
Or at least catch, the console error following instruction https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by Rookie1261** [comment]
`Field 'latest_items' doesn't have a default value5CZlXGFhYWGTSgvqZhzAv6b27BuO13BjoYnrp6xU/GieDS0flcz5TbyLaNbEer/MCLtDttXCRT30Qtk79dvSFbg4r7zGJlY7It9Y+/YbanMs3+I/TgHFW6AglXqhuOvPFSsocnxw6UkrbHKTcYg=`

**Comment by Rookie1261** [comment]
Is there any progress? I need to create new users.

**Comment by Rookie1261** [comment]
Is there any progress?

**Comment by nilsteampassnet** [comment]
ANy log to provide?

**Comment by Rookie1261** [comment]
No, there is no log. But I followed your hint and found an error message in Firefox. I published this error directly here. Since then there has been no reaction.

> There must be an error in the log.
> Or at least catch, the console error following instruction https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

> `Field 'latest_items' doesn't have a default value5CZlXGFhYWGTSgvqZhzAv6b27BuO13BjoYnrp6xU/GieDS0flcz5TbyLaNbEer/MCLtDttXCRT30Qtk79dvSFbg4r7zGJlY7It9Y+/YbanMs3+I/TgHFW6AglXqhuOvPFSsocnxw6UkrbHKTcYg=`

**Comment by Rookie1261** [comment]
I set up a new server and restored a Teampass backup. The error is migrating with it. Now I try to import the whole structure (items, folders) on a new installation. Unfortunately I get an error 500 when importing a CSV (Browse CSV file).

`PHP Fatal error: Uncaught Goodby\\CSV\\Import\\Standard\\Exception\\StrictViolationException: Column size should be 1, but 2 columns given in`

What options do I have for transferring folders and items?

**Comment by Rookie1261** [comment]
Solution
`alter table teampass_users modify latest_items varchar(1000) NULL;`

Many thanks to myself.

**Comment by rhodix-ewillems** [comment]
I had the same issue and managed to solve it with the following query:
`alter table teampass_users modify favourites varchar(1000) NULL;
alter table teampass_users modify latest_items varchar(1000) NULL;
`

**Comment by Whalurkun** [comment]
Hey @Rookie1261 I have the same problem as you described in the opening post. The fix you provided with altering the table was the to fix the initial cannot create user table or was that for you to be able to import your old backup?

**Comment by Rookie1261** [comment]
Hi Whalurkun, it fixes the initial problem.

**Comment by Whalurkun** [comment]
You're the man Rookie1261. I ran your fix + rhodix-ewillems's query and it works like a charm. 

Thanks for the turboquick reply!

**Comment by rvnz45** [comment]
thank you @rhodix-ewillems 
solved my problem :)
