### ISSUE TITLE
New LDAP Logins with Duo 2FA enabled do not get created

### ISSUE THREAD

**Issue by CraigTolley** [nilsteampassnet/TeamPass#2548]
### Steps to reproduce
1. Enable LDAP authentication (Windows/AD)
2. Enable 2FA using Duo
3. Log in using an AD user that is enrolled in Duo, that has not accessed TeamPass before

### Expected behaviour
User is logged in and the defined role set in the LDAP configuration is applied

### Actual behaviour
Taken back to the login screen. Endless cycle

### Server configuration
**Operating system:** Ubuntu 18.04 LTS

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.2

**Teampass version:** 2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** No
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Internet Explorer, FireFox

**Operating system:** Windows 7, Windows Server 2008

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I need to check this.

Than kyou for reporting.
