### ISSUE TITLE
LDAP Passwords in plain text in /var/log/apache2/error.log

### ISSUE THREAD

**Issue by CraigTolley** [nilsteampassnet/TeamPass#2549]
### Steps to reproduce
1. Enable LDAP Authentication
2. Enable Duo Authentication
3. Generate error by attempting to login with an LDAP user not in the TeamPass database

### Expected behaviour
Error should be logged, but not contain sensitive information

### Actual behaviour
Error is logged and contains username and password

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache 2

**Database:** MySql

**PHP version:** 7.2

**Teampass version:**  2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
[Mon Feb 11 19:13:13.825496 2019] [proxy_fcgi:error] [pid 1250:tid 140591769798400] [client 192.168.16.52:60030] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'SplClassLoader' not found in /var/www/html/sources/main.functions.php:2577\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2417): ldapPosixAndWindows('**USERNAME**', '**PASSWORD**', Array)\n#1 /var/www/html/sources/identify.php(134): connectLDAP('**USERNAME**', '**PASSWORD**', Array)\n#2 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2577\n', referer: http://serverhostname/index.php?type=duo_check&baf671768a5818bb9c8518244fbaae8684847a143c7067d134=de66c8ed10bd7cd05c7de002ea66d1de3f54b7b15fdc302432&post_type=duo


#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
This is a php error not handled by teampass.
You should have display_errors = off in your PHP.ini anyway to avoid this problem.

Nevertheless you found a defect.
In file `sources/main.functions.php` at line 2577 you should add the next 2 lines.

```
    //load ClassLoader
    include_once $SETTINGS['cpassman_dir'].'/sources/SplClassLoader.php';
```

I will fix this in next release;
