### ISSUE TITLE
Cannot access URL/link to item when not logged in

### ISSUE THREAD

**Issue by janpekar** [nilsteampassnet/TeamPass#2550]
### Steps to reproduce
1. Copy URL to item into clipboard
2. Logout from teampass
3. Open URL - it will redirect you to login page and after login you will not get to the item you requested

### Expected behaviour
I expect, that after login I will continue to the item I linked. 

### Actual behaviour
You will get to the item, when you are already logged in, but not when you enter through login dialog.

### Server configuration
**Teampass version:** 
3.0.0

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
Firefox/Chrome

**Operating system:**
Linux

**Comment by nilsteampassnet** [comment]
If you are not logged in Teampass, you cannot access to its items.

I don't really understand the point. Can you please be more precise?

**Comment by janpekar** [comment]
I know, but when I login I expect, that app will continue to the item that was in URL.
Now the item in URL is forgotten at login page. I need to click again to the URL (after I'm already logged in browser) and app will than open the item. So I need to open URL twice.

**Comment by nilsteampassnet** [comment]
I see you are using 3.0.0. This one is still not released.
It is a development branch so many things are not working as in 2 branch.

**Comment by marcelloc** [comment]
what is the status of teampass 3.0? devel, beta, release?

**Comment by nilsteampassnet** [comment]
It is in between devel and beta ;)
It was almost read for becoming beta but I decided to implement new encryption system based upon user public/private keys and not relying anymore on a saltkey.
This change has a big impact on many part of the software.
