### ISSUE TITLE
Export password list to file

### ISSUE THREAD

**Issue by willtebourre** [nilsteampassnet/TeamPass#2553]
Hello.

My export to CVS not working.
When I click on the download file. I receive an error message like this:

Not Found

The requested URL /files/print_out_csv_1550585938_b87a6d752ff20a3.csv was not found on this server.

I have check the rights on the folder file and is writable.

I have change the line at //save the file on the export.query file regarding an issues post on it.
But is not working.
Could you please help me?

Server configuration
Operating system:
CentOS 7.3

Web server:
Server version: Apache/2.4.6 (CentOS)

Database:
mysql Ver 15.1 

PHP version:
PHP 5.6.3 

Teampass version:
2.1.23

Client configuration

Browser:
Chrome, Firefox

Operating system:
Windows 10

**Comment by nilsteampassnet** [comment]
This is a very old version. 
I would recommend to check the apache logs to find any error related to export.

**Comment by willtebourre** [comment]
Thank you for your respond.
I want to migrate my old teampass to version 2.1.27 
and in addition to the dump I want to export the list.
otherwise what should I do to upgrade my version?
The only logs found is : 
 "GET /items.export.php?key=v65z4p8LL/Tt.L4Qc3Lm5UpnSOWJHx3ZBdygd6k5XEudJ9Oe2/ HTTP/1.1" 200 13965
- [21/Feb/2019:10:13:48 +0100] "GET /items.export.php?key=v65z4p8LL/Tt.L4Qc3Lm5UpnSOWJHx3ZBdygd6k5XEudJ9Oe2/ HTTP/1.1" 200 13965
- [21/Feb/2019:10:13:55 +0100] "POST /sources/export.queries.php HTTP/1.1" 200 159
 - [21/Feb/2019:10:13:56 +0100] "GET /files/print_out_csv_1550740435_90b07f4d6ec1c70.csv HTTP/1.1" 404 248
