### ISSUE TITLE
Issue Migrating DB to a new server.

### ISSUE THREAD

**Issue by Jeff8682** [nilsteampassnet/TeamPass#2554]
### Steps to reproduce
1. Fresh install of teampass(2.1.27.33)
2. Copy DB over from existing installation(prior teampass version 2.1.27.9)
3. Log in as user and click any entry (password is blank for all)
    -if we copy over and update the following files sk.php, teampass-seckey.txt, settings.php and tp-config.php from the old server then we are just served a blank page when trying to access anything.

### Expected behaviour
Tell us what should happen
Password would show under each entry 
### Actual behaviour
Tell us what happens instead
Blank password
### Server configuration
**Operating system**:
Red Hat Enterprise Linux Server release 7.5 (Maipo)
**Web server:**
httpd-2.4.6-88.0.1.el7.x86_64
**Database:**
 MariaDB-10.3.12-centos73-x86_64-server
**PHP version:**
php 5.6
**Teampass version:** 
 2.1.27.33
**Teampass configuration file:**
<?php
global $lang, $txt, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "localhost";
$user = "teampass_admin";
$pass = *************
$database = "teampass2";
$pre = "teampass_";
$port = 3306;
$encoding = "";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/var/www/html/teampass/includes');
if (file_exists("/var/www/html/teampass/includes/sk.php")) {
    require_once "/var/www/html/teampass/includes/sk.php";
}

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://10.50.230.100/teampass',
    'favicon' => 'http://10.50.230.100/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://10.50.230.100/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://10.50.230.100/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@accruent.com',
    'ldap_domain_dn' => 'dc=accruent,dc=com',
    'ldap_domain_controler' => '10.50.2.11',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1507398784',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'accruent-com.mail.protection.outlook.com',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => 'none',
    'email_server_url' => '',
    'email_from' => 'infrastructure@accruent.com',
    'email_from_name' => '[ITO] Infrastructure',
    'pwd_maximum_length' => '40',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,ppk,pem',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '0',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Accruent TeamPass',
    'api' => '1',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '3',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass_2_12_19',
    'syslog_enable' => '1',
    'syslog_host' => '10.50.4.95',
    'syslog_port' => '9514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'bck_script_key' => '',
);

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
[Tue Feb 19 19:51:36.347273 2019] [:error] [pid 13383] [client 10.50.200.33:54544] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/sources/checks.php on line 142, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.347560 2019] [:error] [pid 13383] [client 10.50.200.33:54544] PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 208, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.384155 2019] [:error] [pid 11860] [client 10.50.200.33:54542] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/teampass/includes/config/include.php on line 24, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.386374 2019] [:error] [pid 11860] [client 10.50.200.33:54542] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/sources/checks.php on line 142, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.386636 2019] [:error] [pid 11860] [client 10.50.200.33:54542] PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 208, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.387094 2019] [:error] [pid 11860] [client 10.50.200.33:54542] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/sources/admin.queries.php on line 62, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.433586 2019] [:error] [pid 13384] [client 10.50.200.33:54543] PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/teampass/includes/config/include.php on line 24, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.437783 2019] [:error] [pid 13384] [client 10.50.200.33:54543] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/sources/checks.php on line 142, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.438149 2019] [:error] [pid 13384] [client 10.50.200.33:54543] PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 208, referer: http://10.50.230.100/teampass/index.php?page=manage_main
[Tue Feb 19 19:51:36.438876 2019] [:error] [pid 13384] [client 10.50.200.33:54543] PHP Warning:  mysqli_connect(): Headers and client library minor version mismatch. Headers:50560 Library:100136 in /var/www/html/teampass/sources/admin.queries.php on line 62, referer: http://10.50.230.100/teampass/index.php?page=manage_main

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Ijstree.min.js:5 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
(anonymous) @ jstree.min.js:5
VM397:1 XHR finished loading: POST "http://10.50.230.100/teampass/sources/items.queries.php".
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
AfficherDetailsItem @ index.php?page=items:3662
onclick @ index.php?page=items:1
VM397:1 XHR finished loading: POST "http://10.50.230.100/teampass/sources/items.queries.php".
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
showDetailsStep2 @ index.php?page=items:4057
(anonymous) @ index.php?page=items:3992
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
XMLHttpRequest.send (async)
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
AfficherDetailsItem @ index.php?page=items:3662
onclick @ index.php?page=items:1
VM397:1 XHR finished loading: POST "http://10.50.230.100/teampass/sources/main.queries.php".
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
refreshListLastSeenItems @ index.php?page=items:470
(anonymous) @ index.php?page=items:4121
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
XMLHttpRequest.send (async)
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
showDetailsStep2 @ index.php?page=items:4057
(anonymous) @ index.php?page=items:3992
fire @ jquery.js:3048
fireWith @ jquery.js:3160
done @ jquery.js:8235
callback @ jquery.js:8778
XMLHttpRequest.send (async)
(anonymous) @ VM397:1
new_send @ csrfprotector.js:272
send @ jquery.js:8706
ajax @ jquery.js:8136
jQuery.(anonymous function) @ jquery.js:8282
AfficherDetailsItem @ index.php?page=items:3662
onclick @ index.php?page=items:1
```

**Comment by nilsteampassnet** [comment]
Several points here.

- You cannot just move the database. I must be upgraded in regards to the teampass version you are using.
So you need to use the feature upgrade on your 2.1.27.33 version.

- Regarding your errors (please rewrite the message, it is very difficult to read as it is), you have some server errors related to php and mysql mismatching errors.

**Comment by Jeff8682** [comment]
I was able to finally get the upgrade to complete successfully.  Thank you for your help though.
