### ISSUE TITLE
Docker Install

### ISSUE THREAD

**Issue by sylou59** [nilsteampassnet/TeamPass#2556]
Hello,
I tried to install TeamPass on my server with Docker-compose.yml but it's not working.
All installation is ok, docker ps -a all docker process are UP but when i can't join TeamPass with my browser...
Port : 80 / 443 / 9000 are open
Nothing happen i don't know why
Firewall down

Server CentOS

Regards,
Sylvain

**Comment by nilsteampassnet** [comment]
Mu knowledge of Docker is very poor.
Can someone help here?

**Comment by Karmashkin** [comment]
here fast example:
https://github.com/Karmashkin/teampass-alpine
