### ISSUE TITLE
Error when using search menu

### ISSUE THREAD

**Issue by barbosajonas** [nilsteampassnet/TeamPass#2557]
### Steps to reproduce
1. Click the binoculars icon
2. Show search menu
3.

### Expected behaviour
Show search menu and itens

### Actual behaviour
Error message:  DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache / 2.4.29 (Ubuntu)
**Database:**
5.7.22-0ubuntu18.04.1
**PHP version:**
7.2.5-0ubuntu0.18.04.1
**Teampass version:** 
2.1.27.29
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome
Mozila Firefox
Internet Explorer
**Operating system:**
Windows Seven Professional 64Bits
Windows 10
#### Web server error log
```
Insert your webserver log here

[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/2894340/tp.config.zip)
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/2894342/tp.config.zip)
DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Can you please follow isntruction from https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console and share the error

**Comment by sfrlaurent** [comment]
hello
I have exactly the same trouble.
once the message appeared, I klicked on OK and the search is possible by adding some letters into the search box. Is it possible the number of items could be the cause of the trouble ?
no error message is chown in the response into the browser console.

**Comment by barbosajonas** [comment]
I was able to solve the problem recreating the table in mysql, but I had to register all entries again.
