### ISSUE TITLE
Unable to install Teampass

### ISSUE THREAD

**Issue by g3l0l4** [nilsteampassnet/TeamPass#2562]
### Steps to reproduce
1. Install all requirements
2. Access to IP/teampass
3. Get a deformed installation page

### Expected behaviour
Get the installation page and install teampass

### Actual behaviour
Get this page and i´m unable to install -->
![image](https://user-images.githubusercontent.com/17069911/53939617-eeb9fa00-40b3-11e9-8252-02b06c5f1d27.png)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP 7.0

**Teampass version:** Latest

**Updated from an older Teampass or fresh install:** Fresh install

### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** Windows 10

**Comment by nilsteampassnet** [comment]
Perhaps an issue with the browser cache.

PLease clear cache and retry.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
