### ISSUE TITLE
Unable to add item via API

### ISSUE THREAD

**Issue by g3l0l4** [nilsteampassnet/TeamPass#2563]
### Steps to reproduce
1. Try to add item via API
2. Error is raised

### Expected behaviour
An item is added to the teampass database

### Actual behaviour
I get an error

### Server configuration
**Operating system**: SUSE Linux 12.1

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Teampass version:** 2.1.27.22

### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** Windows 10

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function rest_error() in /Teampass/api/functions.php:841
Stack trace:
#0 /Teampass/api/index.php(42): restGet()
#1 {main}
  thrown in <b>/Teampass/api/functions.php</b> on line <b>841</b><br />

```

**Comment by nilsteampassnet** [comment]
Correct.

I will fix this.
