### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by halobolah** [nilsteampassnet/TeamPass#2564]
### Steps to reproduce
1. I added new user: test
2. I assigned the role to a user
3. The user can edit end delete items

### Expected behaviour
User can edit but not delete items

### Actual behaviour
User can edit and delete items

### Server configuration
**Operating system**: Linux server 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips

**Database:** 5.5.5-10.2.22-MariaDB

**PHP version:** 7.3.2

**Teampass version:** 2.1.27.33

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '5',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>/
'favicon' => 'https://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '1',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'ldap_type' => 'windows',
'ldap_suffix' => '@xxx',
'ldap_domain_dn' => 'dc=xxx,dc=com,dc=pl',
'ldap_domain_controler' => 'DNS_IPs',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '1',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '1',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => '',
'send_stats_time' => '1548508954',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => 'mail_server',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => 'teampassit@xxx.pl',
'email_from_name' => 'TeamPass',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => 'proxy_IP',
'proxy_port' => 'proxy_port',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '2',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/timezone',
'enable_attachment_encryption' => '0',
'personal_saltkey_security_level' => '0',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '60',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'copy_to_clipboard_small_icons' => '1',
'ldap_new_user_role' => '',

```

**Updated from an older Teampass or fresh install:** fresh installation

### Client configuration

**Browser:** IE - 11.0, Firefox

**Operating system:** Windows - 64bits

#### Web server error log
```
Constant SECUREPATH already defined - /var/www/html/teampass/includes/config/settings.php (15)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Did you enabled "delete" privilege on the role to which the user is associated?

Please provide screenshots.

**Comment by halobolah** [comment]
![obraz](https://user-images.githubusercontent.com/28426539/54112329-34ddc900-43e6-11e9-962a-b29c03eadbbe.png)

**Comment by halobolah** [comment]
I added another 3 new users:

![obraz](https://user-images.githubusercontent.com/28426539/54112525-a9b10300-43e6-11e9-9dba-919e2ec4fff2.png)

and the situation is:
- testowy3 - can edit and delete
- testowy4 - can edit but not delete :)
- temp1 - can edit and delete 

Users added in the same time :) strange

**Comment by halobolah** [comment]
Hi

Any ideas ??

**Comment by nilsteampassnet** [comment]
Ok found the bug.
It was quite vicious ... I will provide a fix in 2.1.27.35

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.

**Comment by halobolah** [comment]
Hi

I'm trying a new release 2.1.27.35 but is not working correctly. Now users have roles with permissions:

![obraz](https://user-images.githubusercontent.com/28426539/54523923-e8a80100-4970-11e9-8ec7-b07277598242.png)


and can't delete but can edit - this is correct, but when I change them on:

![obraz](https://user-images.githubusercontent.com/28426539/54523873-c910d880-4970-11e9-8db5-0dff99ab3eda.png)

they can't delete too :)

![obraz](https://user-images.githubusercontent.com/28426539/54524008-1a20cc80-4971-11e9-8e66-5b6abe7f8578.png)


I think now we have opposite situation to earlier problem :) Can you check it ?? Maybe I'm doing something wrong ??

**Comment by picardflo** [comment]
Hi,

I confirm a have the same symptoms on fresh install of 2.1.27.35.
I can't remove items on my folders.

Here is my settings

**Roles :**  
![image](https://user-images.githubusercontent.com/23116016/56026659-e8ebb000-5d14-11e9-984a-a5f65a21c5e1.png)

**Users :** 
![image](https://user-images.githubusercontent.com/23116016/56026693-fe60da00-5d14-11e9-974a-a975202d26a5.png)

**Symptoms :** 
![Peek 2019-04-12 11-22](https://user-images.githubusercontent.com/23116016/56026938-75966e00-5d15-11e9-990a-7fbbd3045f62.gif)

Would I have forgotten something?

**Comment by halobolah** [comment]
Hi I think you do everything correct, but here is some permissions logic problem, I created new Issue: https://github.com/nilsteampassnet/TeamPass/issues/2571 but is still not resolved.

We'll waiting :)

**Comment by halobolah** [comment]
Hi, is someone working on this problem ??
