### ISSUE TITLE
Settings not appear

### ISSUE THREAD

**Issue by sarelol** [nilsteampassnet/TeamPass#2566]
### Steps to reproduce
1. Access to settings
2. 
3.

### Expected behaviour
Hello, 

I do not see the Settings option in the window. Neither with administrator nor with admin.
And I can not change god mode to any user either. I need to be able to access the Settings tab.

Does somebody knows why it could be?

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux hvta1hg006.local 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

**Web server:** Apache

**Database:** 5.5.5-10.3.12-MariaDB-log

**PHP version:** 7.1.8

**Teampass version:** 2.1.27.33

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'spanish',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1549280473',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'UTC',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'can_create_root_folder' => '1',
'enable_massive_move_delete' => '1',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 72.0.3626.121

**Operating system:** Windows - 64bits

#### Web server error log
```
Undefined index: path - /var/www/html/teampass/sources/main.queries.php (1353)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by sarelol** [comment]
![Imagen 336](https://user-images.githubusercontent.com/48451750/54146467-54014880-4430-11e9-8e8b-6f61a0934146.png)

**Comment by sarelol** [comment]
![Imagen 336](https://user-images.githubusercontent.com/48451750/54146526-7004ea00-4430-11e9-969e-27e8061b9f95.png)
![Uploading Imagen 335.png…]()

**Comment by sarelol** [comment]
![Imagen 335](https://user-images.githubusercontent.com/48451750/54146560-86ab4100-4430-11e9-8301-f1fd909c05b3.png)

**Comment by sarelol** [comment]
Hi nilsteampassnet,

With admin acount neither we can view settings. I'm afraid that the admin user has been removed privileges.
![Imagen 337](https://user-images.githubusercontent.com/48451750/54184713-944fdd80-44a7-11e9-876a-1fb7e0b28472.png)

**Comment by giveen** [comment]
I was able to do this as well, on accident, I gave "Read Only" to the admin account, and now after logging in, I cannot get to settings either.

**Comment by sarelol** [comment]
Hello Giveen,

You need to do the following:

1. You must enter BBDD
 mysql -u root -p APP001

2. List the tables and see those that are related to users or groups of users.
MariaDB [APP001]> show tables;
+ ------------------------------- +
| Tables_in_APP001 |
+ ------------------------------- +
| teampass_api |
| teampass_automatic_del |
| teampass_cache |
| teampass_categories |
| teampass_categories_folders |
| teampass_categories_items |
| teampass_emails |
| teampass_export |
| teampass_files |
| teampass_items |
| teampass_items_change |
| teampass_items_edition |
| teampass_kb |
| teampass_kb_categories |
| teampass_kb_items |
| teampass_languages ​​|
| teampass_log_items |
| teampass_log_system |
| teampass_misc |
| teampass_nested_tree |
| teampass_otv |
| teampass_restriction_to_roles |
| teampass_rights |
| teampass_roles_title |
| teampass_roles_values ​​|
| teampass_suggestion |
| teampass_tags |
| teampass_templates |
| teampass_tokens |
**| teampass_users |**
+ ------------------------------- +
30 rows in set (0.000 sec)


3. View the columns in the table to see if there are any that refer to the user group or administration.

MariaDB [APP001]> desc teampass_users;
+------------------------+---------------+------+-----+-------------+----------------+
| Field                  | Type          | Null | Key | Default     | Extra          |
+------------------------+---------------+------+-----+-------------+----------------+
| id                     | int(12)       | NO   | PRI | NULL        | auto_increment |
| login                  | varchar(50)   | NO   | UNI | NULL        |                |
| pw                     | varchar(400)  | NO   |     | NULL        |                |
| groupes_visibles       | varchar(1000) | NO   |     | NULL        |                |
| derniers               | text          | YES  |     | NULL        |                |
| key_tempo              | varchar(100)  | YES  |     | NULL        |                |
| last_pw_change         | varchar(30)   | YES  |     | NULL        |                |
| last_pw                | text          | YES  |     | NULL        |                |
| admin                  | tinyint(1)    | NO   |     | 0           |                |
| fonction_id            | varchar(1000) | YES  |     | NULL        |                |
| groupes_interdits      | varchar(1000) | YES  |     | NULL        |                |
| last_connexion         | varchar(30)   | YES  |     | NULL        |                |
| gestionnaire           | int(11)       | NO   |     | 0           |                |
| email                  | varchar(300)  | NO   |     | none        |                |
| favourites             | varchar(1000) | YES  |     | NULL        |                |
| latest_items           | varchar(1000) | YES  |     | NULL        |                |
| personal_folder        | int(1)        | NO   |     | 0           |                |
| disabled               | tinyint(1)    | NO   |     | 0           |                |
| no_bad_attempts        | tinyint(1)    | NO   |     | 0           |                |
| can_create_root_folder | tinyint(1)    | NO   |     | 0           |                |
| read_only              | tinyint(1)    | NO   |     | 0           |                |
| timestamp              | varchar(30)   | NO   |     | 0           |                |
| user_language          | varchar(50)   | NO   |     | 0           |                |
| name                   | varchar(100)  | YES  |     | NULL        |                |
| lastname               | varchar(100)  | YES  |     | NULL        |                |
| session_end            | varchar(30)   | YES  |     | NULL        |                |
| isAdministratedByRole  | tinyint(5)    | NO   |     | 0           |                |
| psk                    | varchar(400)  | YES  |     | NULL        |                |
| ga                     | varchar(50)   | YES  |     | NULL        |                |
| ga_temporary_code      | varchar(20)   | NO   |     | none        |                |
| avatar                 | varchar(1000) | YES  |     | NULL        |                |
| avatar_thumb           | varchar(1000) | YES  |     | NULL        |                |
| upgrade_needed         | tinyint(1)    | NO   |     | 0           |                |
| treeloadstrategy       | varchar(30)   | NO   |     | full        |                |
| can_manage_all_users   | tinyint(1)    | NO   |     | 0           |                |
| usertimezone           | varchar(50)   | NO   |     | not_defined |                |
| agses-usercardid       | varchar(50)   | NO   |     | 0           |                |
| encrypted_psk          | text          | YES  |     | NULL        |                |
| user_ip                | varchar(400)  | NO   |     | none        |                |
| user_ip_lastdate       | varchar(50)   | YES  |     | NULL        |                |
| user_api_key           | varchar(500)  | NO   |     | none        |                |
| yubico_user_key        | varchar(100)  | NO   |     | none        |                |
| yubico_user_id         | varchar(100)  | NO   |     | none        |                |
+------------------------+---------------+------+-----+-------------+----------------+
43 rows in set (0.001 sec)


4. See the value of the "admin" field to see if it was 1 or 0 since it is a Boolean field.

MariaDB [APP001]> select id,login,admin from teampass_users where login="admin";
+----+-------+-------+
| id | login | admin |
+----+-------+-------+
|  1 | admin |     0 |
+----+-------+-------+
1 row in set (0.000 sec)


5. Make the modification of that field for that user and modify it from 0 to 1.

MariaDB [APP001]> update teampass_users set admin=1 where id=1;
Query OK, 0 rows affected (0.001 sec)
Rows matched: 1  Changed: 1  Warnings: 0



6. Check that the field has changed.

MariaDB [APP001]> select id,login,admin from teampass_users where login="admin";
+----+-------+-------+
| id | login | admin |
+----+-------+-------+
|  1 | admin |     1 |
+----+-------+-------+
1 row in set (0.000 sec)

**Comment by giveen** [comment]
> Hello Giveen,
> 
> You need to do the following:
> 


Thats kinda what I just said.
