### ISSUE TITLE
Add New User

### ISSUE THREAD

**Issue by vandersonrenan** [nilsteampassnet/TeamPass#2567]
### Steps to reproduce
1. Manage Users
2. Add new User
3. Save

The problem occurs when creat a new user.
When I click save, it stays in please wait and nothing happens.

Network > users.queries.php > response: 

Field 'favourites' doesn't have a default value3CCJXLu7u7uJBHNbOw8XMYW8v9NQ449dOOAaw+eyxTHVB105GeQuu4qHWu4ObmpVUwLixn8y57U7DFEUIj26UMDydyw/5SC5Q3JKNeyumChIqpWrxEzPVe5oHeOSmd90Ky8nFrgih+Zhc81Z

### Server configuration
**Operating system**:
Oracle Linux 7.5

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.6.38

**Teampass version:** 
2.1.27.23

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows 10 x64
[teampass.zip](https://github.com/nilsteampassnet/TeamPass/files/2962227/teampass.zip)

**Comment by richard-diederen** [comment]
I ran into the same issue. It appears that the database fields of favourites and latests-items in the users table does not permit NULL values while they are supplied during user creation.
To solve this issue, run the following SQL commands on the teampass database:

```
ALTER TABLE `teampass`.`teampass_users` 
CHANGE COLUMN `favourites` `favourites` VARCHAR(1000) NULL DEFAULT NULL ,
CHANGE COLUMN `latest_items` `latest_items` VARCHAR(1000) NULL DEFAULT NULL ;
```

Then it will work again.

Regards,

Richard.

**Comment by vandersonrenan** [comment]
Thanks, but doesn't work yet.
A new error on the Response of users.queries.php

"**Field 'avatar' doesn't have a default** valuen/u1XEtLS0vJ6/fT5uU3FPJOF0HebVISa3kmmptQ5E4P+gpXHrBrZnZPgMGQSJ4uFKo6h+TkvKfoL38lUaCTQO7w7mV7qoH3EpnoMth5QWgJr7NmzVqaa0KkOPdTwg2dUmB42LT/YUE="
