### ISSUE TITLE
Items logs error

### ISSUE THREAD

**Issue by vandersonrenan** [nilsteampassnet/TeamPass#2568]
1. Utilities
2. Logs
3. Items

The page does not load and displays the error, after processing "DataTables warning: table id=t_items - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

### Server configuration
**Operating system**:
CentOS 7.5

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.6.38

**Teampass version:** 
2.1.27.23

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows 10 x64

Request URL: https://teampass.angeloni.com.br/sources/datatable/datatable.logs.php?action=items&token=VH373aXzAZGdDgvEYyyVWeZ3tPj487SvcLr6AYaqR7t5uNCLaB&sEcho=1&iColumns=5&sColumns=%2C%2C%2C%2C&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&sSearch=&bRegex=false&iSortCol_0=0&sSortDir_0=desc&iSortingCols=1&_=1552491683112
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 10.199.10.112:443
Referrer Policy: no-referrer-when-downgrade
[teampass.zip](https://github.com/nilsteampassnet/TeamPass/files/2962254/teampass.zip)

**Comment by edelmanns** [comment]
Hello,

same error in 2.1.27.24

![grafik](https://user-images.githubusercontent.com/44601068/62186360-4bb99380-b366-11e9-8c9d-b25fa7bb54fd.png)
