### ISSUE TITLE
directory permissions are completely insecure

### ISSUE THREAD

**Issue by computersalat** [nilsteampassnet/TeamPass#2569]
### Steps to reproduce
1. Read the docu for installation
you will find:
```
chmod -R 0777 teampass/includes/config
chmod -R 0777 teampass/includes/avatars
chmod -R 0777 teampass/includes/libraries/csrfp/libs
chmod -R 0777 teampass/includes/libraries/csrfp/log
chmod -R 0777 teampass/includes/libraries/csrfp/js
chmod -R 0777 teampass/backups
chmod -R 0777 teampass/files
chmod -R 0777 teampass/install
chmod -R 0777 teampass/upload
```

**ARE YOU SERIOUS ?**
Who or what needs read/write access to which directory ?
Sorry, but this is far away from being professional ...

**Comment by nwildner** [comment]
+1 on this.

When I installed, i've set 750 permissions to the top folder recursively and changed the ownership to apache. This second step is another thing missing at the install docs. 

    chmod -R 750 /var/www/teampass
    chown -R apache:apache /var/www/teampass

**Comment by nilsteampassnet** [comment]
You are right, I didn't updated the documentation.
If you see any missing topic in the documentation, you can do a pull request to suggest an evolution.
I would be really happy to accept it.

**Comment by Kyogre** [comment]
After 3 years I see still the same 0777 permissions in https://documentation.teampass.net/#/install/installation

**Comment by pstevens71** [comment]
Hey, I tried 750 permissions and I keep getting permission denied from the web browser.  The lowest I can make the permissions is 751 for it to work is that still ok?

**Comment by Kyogre** [comment]
> I keep getting permission denied from the web browser

where did you get that? What action on which page? Can you provide a screenshot?

**Comment by pstevens71** [comment]
Just on the login page, the main index page.  If I set permissions to 750 for the files and folders I get permission denied in the browser.  I experimented to see how low I could make the permissions and still get access.  755 works too, but then I lowered to 751 and it works.  750 however, does not let me even into the login page.

**Comment by pstevens71** [comment]
OK after a couple of days that my browser cache cleared, can't access the CSS files with 751.  Had to change permissions to 755.  I think that's the lowest I can go with everything still working.  I have another installation on a different server and I ran into the same issue and 755 was the lowest I could go and still have it work in the browser.  Is 755 secure enough?

**Comment by Kyogre** [comment]
Today tried to setup teampass with `nginx` and found out, that for such combination only
`chown -R apache:nginx /var/www/teampass && chmod -R 770 /var/www/teampass`
make teampass to work properly.
