### ISSUE TITLE
Empty info window

### ISSUE THREAD

**Issue by cachmc** [nilsteampassnet/TeamPass#2570]
### Steps to reproduce
1.  Raised a new server
2.  Set up a new instance of TeamPass
3.  Recovered mysql database
4.  Copied configuration files from the old server (settings.php, tp.config.php, sk.php, teampass-seckey.txt)

### Expected behaviour
Tell us what should happen

TeamPass should work the same way as before.

### Actual behaviour
Tell us what happens instead

All data is recovered, passwords are in TeamPass. But TeamPass is slow when you first try to download information from the database. 

I click on the folder, about 30-40 seconds the red gear turns. An empty information window appears, and then the folders open quickly. 

I am trying to add a new element or edit an old one - I am waiting for the empty information window again and only then I can work.

### Server configuration
**Operating system**: Ubuntu 18.04.02 Server x64

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.25

**PHP version:** PHP 7.2.15-0ubuntu0.18.04.1

**Teampass version:** TeamPass 2.1.27.33 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
![2019-03-15_12-04-50](https://user-images.githubusercontent.com/48583929/54420333-c4eb7d80-471a-11e9-9f64-9b84d5ae9bfc.png)

    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'memcache.local' => '\OC\Memcache\APCu',
    'cpassman_url' => 'http://password.****.local',
    'favicon' => 'http://password.****.local/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'url_to_upload_folder' => 'http://password.****.local/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'http://password.****.local/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@terfit.local',
    'ldap_domain_dn' => 'DC=terfit,DC=local',
    'ldap_domain_controler' => '*******',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '1',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0','restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'russian',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;st$
    'send_stats_time' => '1530371155',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.yandex.ru',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'alerts@terfit.ru',
    'email_auth_pwd' => 'd9yW@bAzHVTN',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => '',
    'email_from' => 'alerts@terfit.ru',
    'email_from_name' => 'alerts@terfit.ru',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '30',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
 'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '720',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Moscow',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '1',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '80',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '0',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'ldap_new_user_role' => '2',
    'can_create_root_folder' => '0',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '1',
    'max_last_items' => '15',
);

### Client configuration
**Browser:** Chrome 72.0.3626.121

**Operating system:** Windows 10 Pro x64

#### Web server error log
```
[Fri Mar 15 06:25:42.044335 2019] [mpm_prefork:notice] [pid 18921] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Fri Mar 15 06:25:42.044384 2019] [core:notice] [pid 18921] AH00094: Command line: '/usr/sbin/apache2'

Insert your webserver log here
```
empty

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
teampass-error.log

[Fri Mar 15 10:38:45.980032 2019] [php7:notice] [pid 62852] [client 192.168.77.247:56895] PHP Notice:  Undefined index: admin_2fa_required in /var/www/teampass/sources/identify.php on line 386, referer: http://password.***.local/index.php
[Fri Mar 15 10:49:41.492547 2019] [php7:notice] [pid 63810] [client 192.168.77.247:58526] PHP Notice:  Undefined index: admin in /var/www/teampass/sources/users.queries.php on line 120, referer: http://password.***.local/index.php?page=manage_users
[Fri Mar 15 10:49:43.661761 2019] [php7:notice] [pid 63810] [client 192.168.77.247:58526] PHP Notice:  Undefined index: admin in /var/www/teampass/sources/users.queries.php on line 134, referer: http://password.***.local/index.php?page=manage_users
[Fri Mar 15 10:49:43.666356 2019] [php7:notice] [pid 63810] [client 192.168.77.247:58526] PHP Notice:  Undefined index: manager in /var/www/teampass/sources/users.queries.php on line 135, referer: http://password.***.local/index.php?page=manage_users
[Fri Mar 15 10:50:22.252323 2019] [php7:notice] [pid 63712] [client 192.168.77.247:58642] PHP Notice:  Undefined index: admin_2fa_required in /var/www/teampass/sources/identify.php on line 386, referer: http://password.***.local/

teampass-requests.log

192.168.77.247 - - [15/Mar/2019:11:40:27 +0300] "GET /sources/tree.php HTTP/1.1" 200 3311 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:27 +0300] "POST /sources/items.queries.php HTTP/1.1" 200 3174 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:28 +0300] "POST /sources/items.queries.php HTTP/1.1" 200 8271 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:29 +0300] "POST /sources/items.queries.php HTTP/1.1" 200 1330 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:31 +0300] "POST /sources/main.queries.php HTTP/1.1" 200 365 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:32 +0300] "POST /sources/main.queries.php HTTP/1.1" 200 558 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:35 +0300] "POST /sources/main.queries.php HTTP/1.1" 200 338 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:35 +0300] "POST /sources/main.queries.php HTTP/1.1" 200 303 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
192.168.77.247 - - [15/Mar/2019:11:40:56 +0300] "POST /sources/items.queries.php HTTP/1.1" 200 3173 "http://password.***.local/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
::1 - - [15/Mar/2019:11:41:02 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.29 (Ubuntu) (internal dummy connection)"

**Comment by cachmc** [comment]
![2019-03-15_12-04-50](https://user-images.githubusercontent.com/48583929/54420360-dd5b9800-471a-11e9-83c1-fa92fdb2537d.png)

**Comment by nilsteampassnet** [comment]
Perhaps do you have some errors in the configuration file.
Have you adapted correctly to new server?

**Comment by giveen** [comment]
I have seen this issue with a fresh install.

**Comment by nilsteampassnet** [comment]
This makes me think to url mismatch somewhere.

Please check all url paths in settings page, in settings.php file, in tp.config.php file, in csrfp.config.php, ...
Check https://teampass.readthedocs.io/en/latest/errors/#csrfprotector-settings

As new server, check that you have the same php extensions.

**Comment by cachmc** [comment]
I checked all the config files, everywhere is the correct address. All PHP extensions are installed as written in this manual. But still the page is very long in the status of waiting.

![2019-04-01_11-48-39](https://user-images.githubusercontent.com/48583929/55315093-414cc300-5474-11e9-913a-dbd242abbdc6.png)

**Comment by UryDanko** [comment]
I think I had similar issue during one of upgrades. Check config files (/includes/config/tp.config.php and includes/libraries/csrfp/libs/csrfp.config.php) that all urls are correct. Pay attention for / and http/https

**Comment by cachmc** [comment]
I checked this config several times. Everything is correct.

![2019-05-20_11-21-29](https://user-images.githubusercontent.com/48583929/58007054-14bb3c00-7af2-11e9-8558-15192662199b.png)

**Comment by nicolass67** [comment]
Hi all, 

I have the same issue. 
I'm running a fresh and last version of teampass on a debian 10 server (php7.3). 
In my php logs (debug mode) when it happens I can see : 

`PHP Notice:  Undefined index: admin_2fa_required in <path>/teampass/sources/identify.php on line 386`

If you have any hint to debug this. 

Regards, 

Nicolas.

**Comment by franck56590** [comment]
Hi

All urls are rights for me but same problem.
Did someone find where the problem is ?

regards
