### ISSUE TITLE
Permissions problem 2

### ISSUE THREAD

**Issue by halobolah** [nilsteampassnet/TeamPass#2571]
Sorry but I don't now how to reopen my previous ticket #2564, so I have to create new one:

Hi

I'm trying a new release 2.1.27.35 but is not working correctly. Now users have roles with permissions:

![obraz](https://user-images.githubusercontent.com/28426539/54524844-358cd700-4973-11e9-87cb-a066e38e511f.png)

and can't delete but can edit - this is correct, but when I change them on:

![obraz](https://user-images.githubusercontent.com/28426539/54524876-43425c80-4973-11e9-8283-50e1721114fa.png)

they can't delete too :)

![obraz](https://user-images.githubusercontent.com/28426539/54525163-de3b3680-4973-11e9-959a-f3cd00e2a280.png)

I think now we have opposite situation to earlier problem :) Can you check it ?? Maybe I'm doing something wrong ??

**Comment by nilsteampassnet** [comment]
Ok I identified the defect.
Terrible problem of logic ...
I believe I have fixed it after several set of tests.
You can use the development branch. It only includes this fix and tell me.

**Comment by halobolah** [comment]
Hi

I run development branch and I think now my problem is resolved :)

but I found two situation when it doesn't work properly :)

When I choose:

![obraz](https://user-images.githubusercontent.com/28426539/54741733-9e688f00-4bbf-11e9-8612-a51306a5c3c3.png)

user can delete item and edit it - if I good understand user should delete, create new item but not edit, correct me if I wrong. 

Second situation is when admin / manager select:

![obraz](https://user-images.githubusercontent.com/28426539/54742376-85f97400-4bc1-11e9-9d48-c57e590c0d25.png)

then user can do everything :)

![obraz](https://user-images.githubusercontent.com/28426539/54742428-b5a87c00-4bc1-11e9-8382-b35605a31af6.png)

![obraz](https://user-images.githubusercontent.com/28426539/54742444-bf31e400-4bc1-11e9-9c63-d5c12dd71a74.png)

but should only create new items - right ?

I think we are very close to resolve this problem :)

Thanks for great job !!! :)

**Comment by halobolah** [comment]
Hi, any ideas ? :)

**Comment by halobolah** [comment]
any comments??

**Comment by halobolah** [comment]
Hi, is someone working on this problem ??
