### ISSUE TITLE
Upgrade From  TeamPass 2.1.17 to latest

### ISSUE THREAD

**Issue by ifenice81** [nilsteampassnet/TeamPass#2573]
I have a Teampass 2.1.17 installation on Centos 6.3 and it is working, I download the new version of Teampass, put it in /var/www/pwdmanager/teampass/ and launch /install/upgrade.php, but the page is all white and in the logs I see:

[Tue Mar 19 13:15:10 2019] [error] [client 192.168XXXX] PHP Fatal error:  Class 'SessionHandler' not found in /var/www/pwdmanager/teampass/sources/SecureHandler.php on line 16

**Comment by palimm** [comment]
SessionHandler is a standard PHP class. Check your system. it might be disabled or you don't have access to it. See [SessionHandler](https://www.php.net/manual/en/class.sessionhandler.php)
