### ISSUE TITLE
personnal folder not create

### ISSUE THREAD

**Issue by EricLF** [nilsteampassnet/TeamPass#2590]
Hi !

my users needs to use Personal folder... but i don't want they use salkey but their ldap password..
I don't find where i must activate this properties
could you help me ?
if i just  configure "Personal folders with private password storage" to no they just dont have personal forder ...

Best regards,

Eric

Personal folders are a private location for individual user passwords. Password items are encrypted by a users salt key (more secure) **or by their password (easier)**. Enabling this feature does not create the actual folders for existing users - you must also run the create personal folders task.

**Comment by mkrsn** [comment]
This is imho not possible. The word "Private" says it already... It is not private when a Admin is having access to it :)

If you want semi-personal Folder you can workaround this a bit. You can Create for each User a normal folder. Than give this every User access to his folder. Not beautiful but this would solve your Problem.
