### ISSUE TITLE
QR Code image does not display

### ISSUE THREAD

**Issue by Calanon** [nilsteampassnet/TeamPass#2594]
Teampass 2.1.27.35
Ubuntu 16.04
PHP7
Apache2
When a user enters the QR code key to request the QR code image the image is not displayed, only a placeholder.

Any clue?

**Comment by nilsteampassnet** [comment]
Can you have a look to https://teampass.readthedocs.io/en/latest/errors/#2-factors-authentication-qr-code-picture-not-visible

**Comment by Calanon** [comment]
> Can you have a look to https://teampass.readthedocs.io/en/latest/errors/#2-factors-authentication-qr-code-picture-not-visible

Thanks it was the reason, no firewall rule enabled
