### ISSUE TITLE
Unable open a folder after update to 2.1.27.35

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#2596]
### Steps to reproduce
After an update to 2.1.27.35 when opening a folder obtain a popup empty. In php_error_log we see:
[17-Apr-2019 12:02:10 Europe/Rome] PHP   1. {main}() C:\wamp64\www\teampass\sources\items.queries.php:0

[17-Apr-2019 12:02:45 Europe/Rome] PHP Notice:  Undefined index: accessLevel in C:\wamp64\www\teampass\sources\items.queries.php on line 2722

[17-Apr-2019 12:02:45 Europe/Rome] PHP Stack trace:

[17-Apr-2019 12:02:45 Europe/Rome] PHP   1. {main}() C:\wamp64\www\teampass\sources\items.queries.php:0

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by antoweb** [comment]
Now we receive error:
An error appears. Answer from Server cannot be parsed!

Returned data:
undefined

**Comment by antoweb** [comment]
On the top we see:
Error   
Search
NaN%

**Comment by nilsteampassnet** [comment]
From what page?

**Comment by dedisoft** [comment]
Hi,

I have the same problem here.
It's on items page (/index.php?page=items).

Thanks for your help

**Comment by antoweb** [comment]
Hi Nils,
after the login frrom home page: ()/index.php?page=items)

**Comment by antoweb** [comment]
Hi Nils,
the problem occurs on multiple folders but not all

**Comment by dedisoft** [comment]
Hi,
Version 2.1.27.36 solves the problem.
Many thanks !
