### ISSUE TITLE
Unable to export in pdf/csv

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#2597]
### Steps to reproduce
1. Activate option "export to PDF or CSV enabled" and select corrected role
2. Enter in the app and try to export in pdf/csv a folder
3. We obtain an error from all browser 

### Expected behaviour
We can download a csv exported folder

### Actual behaviour
Unable to download/export folder

### Server configuration
**Operating system**: 
Windows 2008 R2

**Web server:**
Apache 

**Database:**
Mysql 

**PHP version:**
5.6

**Teampass version:** 
2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
All
**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
No errors?

**Comment by antoweb** [comment]
Hi Nils,
after choosing the folder and select csv/pdf i receive 404. Pre4ssing f12 on the browser i see:
URL richiesta:https://URL_OMITTED/teampass/files/print_out_csv_1556091105_d5d94c942fe25cc.csv
Metodo di richiesta:GET
Indirizzo remoto:10.21.20.53:443
Codice di stato:
404
Versione:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
