### ISSUE TITLE
Move teampass to another instance

### ISSUE THREAD

**Issue by UryDanko** [nilsteampassnet/TeamPass#2600]
### Steps to reproduce
1. Current version of Teampass is 2.1.27.10 (installed in VM with PHP, MySQL)
2. New version is 2.1.27.35 (Docker, GCP MySQL, K8s, attached persistence disk, mounrw)
3. BackUP DB from old Teampass
4. Copy teampass-seckey.txt, csrfp.config.php, tp.config.php, updated paths where it was necessary
4. Import DB to a new teampass. 
5. Asked for a password, next. Gear is rotating and not finishing. 
6. After long waiting have session expiration
7. Login again

### Expected behaviour
Everything is imported

### Actual behaviour
1) users are imported
2) all forlders/items are imported
3) all passwords are empty. 
from what I see, in the exported sql file table teampass_items has passwords so I can assume that they are not being imported. 

When I was trying to export all items and do import after I got 
1. 
![Teampass](https://user-images.githubusercontent.com/6039818/56425217-8d409a00-62b3-11e9-9773-8f990f33dbaf.png)

2. After I click OK and click import I get an error "you must select a folder"
3. 
![Teampass](https://user-images.githubusercontent.com/6039818/56425239-a9dcd200-62b3-11e9-8ef4-05c9564e70e3.png)

### Server configuration
Docker: teampass/teampass:2.1.27.35
Database: GoogleCloud MySQL (Second Generation)

**Updated from an older Teampass or fresh install:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'http://xxxxx',
    'favicon' => 'http://xxxxx/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'url_to_upload_folder' => 'http://xxxxx/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'http://xxxxx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => 'includes/images/canevas/logo-final-ver3_.png',
    'custom_login_text' => 'Teampass Login',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1552746657',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '2000',
    'email_smtp_server' => 'smtp.gmail.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'xxxxx',
    'email_auth_pwd' => 'xxxx',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => 'https://xxxxx',
    'email_from' => 'xxxx',
    'email_from_name' => 'xxxx',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '6000',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '25',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'sqmUcyx5tAdjnYXJNMPVHAqPb7fLB3DSLEmfVcpA',
    'admin_2fa_required' => '0',
    'can_create_root_folder' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '1',
    'ga_reset_by_user' => '1',
);

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
error during the import
"2019/04/19 11:18:01 [error] 18#18: *40 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.156.0.65, server: _, request: "POST /sources/admin.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock", host: "xxxxx", referrer: "http://xxxxxxx/index.php?page=manage_settings"
```

**Comment by nilsteampassnet** [comment]
You cannot move db from an old version to a new one.
You need to proceed with upgrade.

So clone the existing instance from old server to new one.
Ensure it works.
Then upgrade

**Comment by UryDanko** [comment]
Hi Nils,
yes, good point. So I re-did everything:
1) installed the same version, 2.1.27.10 from git
2) copy sk.php, teampass_sk.txt
3) export DB from the old instance to the new instance (with or without encryption key)
4) 
![Teampass](https://user-images.githubusercontent.com/6039818/56663918-6b765700-66a7-11e9-9113-3a47c506eeae.png)
4) log-in again
folders - imported
users - imported
all content - imported
password - empty
![Teampass](https://user-images.githubusercontent.com/6039818/56665274-053f0380-66aa-11e9-92e0-1d8157835e0d.png)

if I try to do import-export via user interface (left corner - export, select folder, save file) and I get
![p_rex_ai_says_and_Teampass](https://user-images.githubusercontent.com/6039818/56665985-61565780-66ab-11e9-9aaa-e1d6f14f7f38.png)
because in the csv file header is: 
_id;label;description;pw;login;restricted_to;perso;url;email;kb;tag_
and import dialog says that "Expected columns are: `Label` , `Login` , `Password` , `URL` , `Comments`."

**Comment by palimm** [comment]
I recently was in a similar situation, here is what I ended up doing:

1.  backup
2.  upgrade existing instance to desired version
3.  make sure everything works
4.  setup new environment
5.  clone from github to new-env and make sure the correct version is checkout out (keep in mind to use the same version as before)
6.  perform a fresh installation inside the new-env 7.  make sure it works (sometimes php modules are missing etc.)
8.  dump the old database (mysqldump)
9. replace thte new db with the old db (use mysql tools)
10. either replace new files with old files (remove new ones first) or copy over config and data files
11. make sure the host and path settings are correct in php files and db
