### ISSUE TITLE
Cannot delete any password entries/items

### ISSUE THREAD

**Issue by ITanno** [nilsteampassnet/TeamPass#2601]
### Steps to reproduce
1. Click on an existing/newly created item
2. Click 'Delete item'
3.'You are not allowed to do that'

### Expected behaviour
I have gave users permission to delete any item inside of any folders 

### Actual behaviour
Just getting the 'you are not allowed to do that' error message - I have double checked permissions etc. everything seems to be set correctly

### Server configuration
**Operating system**: Windows NT WINDC02 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586

**Web server:** Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.2.14

**Database:** 5.7.24

**PHP version:** 7.2.14

**Teampass version:** 2.1.27.35

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => 'C:/wamp/www/TeamPass-master',
'cpassman_url' => 'https://<anonym_url>/
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => 'C:/wamp/www/TeamPass-master/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => 'C:/wamp/www/TeamPass-master/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'ldap_type' => 'windows',
'ldap_suffix' => '@nt.cis',
'ldap_domain_dn' => 'dc=winfs,dc=cis',
'ldap_domain_controler' => '',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '0',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1552812020',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => 'mail',
'email_smtp_auth' => '1',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '993',
'email_security' => 'tls',
'email_server_url' => '',
'email_from' => '.com',
'email_from_name' => 'TeamPass Windows',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '90',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => 'C:/wamp/www/TeamPass-master/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '1',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/London',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '0',
'ldap_new_user_role' => '1',
'copy_to_clipboard_small_icons' => '1',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 73.0.3683.103

**Operating system:** Windows - 64bits

#### Web server error log
```
Constant SECUREPATH already defined - C:\wamp\www\TeamPass-master\includes\config\settings.php (15)
```

#### Teampass 10 last system errors
```
 * 18/04/2019 13:31:06 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`,`encryption_type`) VALUES ('DVLA Wyndham-Leigh Admin Interface', '', '', '', '', '', '109', '', '0', '', '0', '0', NULL, 'defuse')<br />Error: Column 'complexity_level' cannot be null<br />@ /sources/items.queries.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Have you checked what happens if unlog and relog?

**Comment by ITanno** [comment]
I have tried logging in/back out however, has not helped. I've also tried doing this as a few different users - no luck. 

Like I say, it doesn't appear to be local Settings/permissions

**Comment by ITanno** [comment]
After looking through previous issues, looks like this is the same problem as #2583

**Comment by UryDanko** [comment]
I've got the same (or similar) issue. 
I upgraded from 2.1.27.10 to 2.1.27.35 and the only difference I see between new and old versions is the icon in front of an entry. In the 2.1.27.10 is it 
<img width="181" alt="Teampass" src="https://user-images.githubusercontent.com/6039818/57234710-8a6ad680-7021-11e9-9414-a6dbe86cddb8.png">
and in the 2.1.27.35 it is 
<img width="238" alt="Teampass" src="https://user-images.githubusercontent.com/6039818/57234774-aa9a9580-7021-11e9-9033-44786f4add90.png">

re-login doesn't help

**Comment by jkruid** [comment]
Same here - not able to delete items. The issue seems to exist only on subfolders. Even account with "manager" role cannot delete items.

**Comment by sandrosousa** [comment]
same here, but only for items created in root folder and this root folder was created by admin, if I create a new subfolder and add items these items i can delete.

**Comment by charles-plante** [comment]
Same here I imported a list of password and none can be move

**Comment by nilsteampassnet** [comment]
I believe I found something and reworked the accesslevel definition.

Can someone test this fix using latest `development` branch? Thank you

**Comment by sandrosousa** [comment]
> I believe I found something and reworked the accesslevel definition.
> 
> Can someone test this fix using latest `development` branch? Thank you

yes, now i can delete any items.

**Comment by UryDanko** [comment]
Confirmed. After upgrade to fresh development branch I can create/edit/delete/move items. Same with folders.

However items still have black flag in front of them
![Teampass](https://user-images.githubusercontent.com/6039818/58414090-a7bc1f00-807a-11e9-8d9d-339de78bbfde.png)
why is it? What does it mean?

**Comment by jkruid** [comment]
Confirmed. Works for us a well. Thanks for fiing this so quickly.

**Comment by escalibur16** [comment]
> Confirmed. After upgrade to fresh development branch I can create/edit/delete/move items. Same with folders.
> 
> However items still have black flag in front of them
> ![Teampass](https://user-images.githubusercontent.com/6039818/58414090-a7bc1f00-807a-11e9-8d9d-339de78bbfde.png)
> why is it? What does it mean?

I have exactly the same issue 
How did you do to upgrade to fresh development branch?

**Comment by UryDanko** [comment]
> git pull
?  :)   

but I didn't find yet what does this black flag mean :(
