### ISSUE TITLE
teampassconnect licence

### ISSUE THREAD

**Issue by jboissat** [nilsteampassnet/TeamPass#2604]
Hello
I do not receive the "teampassconnect" license despite my requests
Thank you

**Comment by chrisj11235** [comment]
Hi,

I seem to be experiencing this same issue on Ubuntu 18.04 with Firefox 66.0.3, and TPC version 0.1.9. I've also tried sending the license request from a fresh install of Firefox on Windows 10, and tried both ProtonMail and GMail addresses. Neither of the email addresses have received a response, including in the Spam folders.

I'm requesting a license with the following procedure:

1. Install TPC in Firefox.
2. Press extension icon to open UI.
3. Press 'Request Trial Codes'.
4. Fill in FirstName, LastName, Company, and Email fields.
5. Press Register.

Once I've done that, nothing seems to happen. There's no change in the GUI, and I can't find any corresponding network traffic being generated when I run a packet capture.
Let me know if there's any other troubleshooting data I can provide, and thanks for making TeamPass!

**Comment by GP-S** [comment]
license (licence.teampass.net) server seems down.

**Comment by kns7** [comment]
Up! 
Is there something new regarding the Registration process?  It still does not work and the license server is still not  reachable. 
Thanks for a short update.

**Comment by davidcustard** [comment]
I'm having the same problem - not getting the "teampassconnect" license despite several requests.

Anything I should do?

**Comment by 247no2** [comment]
Hello everyone, do you have a solution for this? Without Teampass Connect Key/Code I can not connect. When I press Register, unfortunately nothing happens. I am very grateful for help.
