### ISSUE TITLE
Access denied for user "root"@"localhost"

### ISSUE THREAD

**Issue by yustmenl** [nilsteampassnet/TeamPass#2605]
### Steps to reproduce
1. try to install
2.
3.

### Expected behaviour
connection to the DB

### Actual behaviour
Stops with error, i tryed diffrent users even root but still i get the error.

![image](https://user-images.githubusercontent.com/360038/56944751-e23aa680-6b24-11e9-9117-536a3d00fda0.png)

### Server configuration
**Operating system**:
Synology DSM

**Web server:**
Apache 2.4

**Database:**
mysql

**PHP version:**
7

**Teampass version:** 
2.1.27.35

**Teampass configuration file:**
still trying to install

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
Chrome and IE

**Operating system:**
Windows 7

#### Log from the web-browser developer console (CTRL + SHIFT + i)
can't find any log

**Comment by antoweb** [comment]
If u try to connect to db instance with the following string:

mysql -u<USERNAME> -p

What happens? If get the same error message maybe you not have configured the login from localhost with password

**Comment by yustmenl** [comment]
Thanks! after trying this i got erro 1045 and from that point i found this what helped solve it
https://stackoverflow.com/questions/10299148/mysql-error-1045-28000-access-denied-for-user-billlocalhost-using-passw

**Comment by yustmenl** [comment]
forgot close
