### ISSUE TITLE
CSV Import fails with an account containing accents

### ISSUE THREAD

**Issue by Skouat** [nilsteampassnet/TeamPass#2607]
### Steps to reproduce
1. Create a CSV file with the following data:
```
Label,Login,Password,URL,Comments
"Normal account","acc_1","pass_1","","it works"
"Account with é_è","acc_2","pass_2","","it fails"
"Normal account2","acc_3","pass_3","","it fails"
```
2. From Teampass, go select "Import items" feature
3. On the CSV tab, select the file previously created.
That's all... we can see the bug from here.

### Expected behaviour
The list should provide 3 items to import

### Actual behaviour
The list provides 2 items to import instead of 3.

### Server configuration
**Operating system**: Debian 9.9

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.38

**PHP version:** 7.2.17

**Teampass version:** 2.1.27.35 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by kendionne** [comment]
It also appears that comments are not imported when they contains accents, but the line is imported, just the comment that is missing.

**Comment by ozawa-hi** [comment]
I've tested the file with TeamPass 2.1.27.36. I needed to save the csv in UTF8 and was able to import the accents without any problem.
