### ISSUE TITLE
Upgrade to TeamPass 2.1.27.35

### ISSUE THREAD

**Issue by pzbdkp** [nilsteampassnet/TeamPass#2611]
I am trying to upgrade from 2.1.26-final-3 to 2.1.27.35 (latest). I type in administrator login and password. After clicking the "launch"-button animation with black progressbar starts but nothing happens.

I've read the information on https://teampass.readthedocs.io/en/latest/install/upgrade/ and tried to execute the query below title "Upgrade to 2.1.27.(latest)".
Get an error when running this query:

> error 1054 - Unknown column 'id' in 'teampass_misc'

### Steps to reproduce
1. Upload latest release TeamPass to webserver and unzip
2. Navigate to [teampass-url]/install/upgrade.php
3. Enter Administrator login and password
4. Click launch button

### Expected behaviour
Installation should continue

### Actual behaviour
Animation (black progressbar) keeps running, but nothing happens

### Server configuration
**Operating system**:
CentOS release 6.8 (Final)
**Web server:**
Apache 2.2.15
**Database:**
MariaDB 10.1.21
**PHP version:**
7.0.16
**Teampass version:** 
2.1.26-final-3

### Client configuration
**Browser:**
Firefox 60.5.2esr (32bit)

**Comment by AlexH01001** [comment]
I've got the same problem when upgrading the teampass from 2.1.26 to 2.1.27, on the interface the loading bar with animation keeps loading but nothing happens. @pzbdkp did u manage to find a fix to your problem ? I'm interested if you solved it how did u do it... Thanks.

**Comment by pzbdkp** [comment]
Problem isn't solved yet. Restored my backup, still on 2.1.26.
Was awaiting a reply here...

**Comment by ByLsXD** [comment]
I think you're forgetting to do this:
_"When upgrading, you need to indicate a valid administrator name/password, and you will also need to copy the saltkey into a password filed. It will be saved inside your database.
**No database data are shown anymore. If the database information are changing, you need to update the file /includes/config/settings.php before starting upgrade.**
IMPORTANT NOTE for users that have migrated to 2.1.27.0 and that have file encryption option enabled

Files encryption process have completely being reworked. Before upgrading, please do the next:

- 1. open upload folder
- 2. copy existing files in a temporary folder
- 3. restore the files from a backup of a previous version (for example 2.1.26)
- 4. start upgrade"_
