### ISSUE TITLE
Dockerhub image is not beeing updated

### ISSUE THREAD

**Issue by CayoM** [nilsteampassnet/TeamPass#2614]
### Issue
after several fixes on the API/Dockerfile, it seems the problems i had in the past should be fixed with the new code, but unfortunately the Docker image from Dockerhub is already 4 months old. Is it not created automatically on changes in the master branch? How can it be triggered?

**Comment by x-drum** [comment]
Hi there,
same problem here the **latest** tag is simply not enough...
Please introduce version tags!

In general is a bad idea to deploy in a production environment using the latest tag

**Comment by olegtarasenko** [comment]
I'd tried Dockerhub image. 
But I'm getting:
```
fatal: destination path '/var/www/html' already exists and is not an empty directory.
Teampass is not configured yet. Open it in a web browser to run the install process.
```
Path doesn't exist. Do you how to fix this?

**Comment by kalexnolasco** [comment]
I have found the solution, I hope the merge to the master and that the image of docker is generated again.
You can also download the repository and make the change yourself, then create the image yourself.
It's as easy as
`docker build -t <name_image> .`
https://github.com/nilsteampassnet/TeamPass/pull/2615

**Comment by kalexnolasco** [comment]
Alternativamente he creado la imagen de teampass en mi organización.
Para descargarla
`docker pull dockerhubwdna/teampass:20190516`

De regalo os dejo un docker-compose.yml para que lo levantéis con:
`docker-compose up -d`
:)
docker-compose.yml:
<pre>
version: "2.2"
services:
  teampass:
    restart: always
    container_name: teampass
    image: dockerhubwdna/teampass:20190516
    ports:
      - 0.0.0.0:8000:80
    environment:
      VIRTUAL_HOST: localhost
    depends_on:
      - teampass_db
    volumes:
      - teampass_teampass:/var/www/html
      - /etc/localtime:/etc/localtime
  teampass_db:
    restart: always
    container_name: teampass_db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: user
      MYSQL_USER: pass_user
    volumes:
      - teampass_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime
volumes:
  teampass_teampass:
    driver: local
    driver_opts:
      type: none
      device: /data/teampass/teampass
      o: bind
  teampass_db:
    driver: local
    driver_opts:
      type: none
      device: /data/teampass/db
      o: bind
</pre>

Para lo anterior, se debe crear los directorios
`mkdir -p /data/teampass/teampass`
`mkdir -p /data/teampass/db`

Run in your browser---> http://localhost:8000  and db_name is a countarner mysql name(e.g teampass_db in this case)

**Comment by lidpee** [comment]
Hi,
After configuring email, Test email not working. Getting the following error.

Email test unsuccessful. Verify your settings (did you set your user account email address?)  undefined

I set the user email ,still getting the dame error. Any Idea ?

**Comment by kalexnolasco** [comment]
You can use  SMTP server from GMAIL https://www.digitalocean.com/community/tutorials/how-to-use-google-s-smtp-server, it has limits, but its the better solution(In my case)

**Comment by lidpee** [comment]
Hi,
Thanks for your reply,

I tried using the gmail accout only.

Regards
Dileel

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CayoM** [comment]
Bump

**Comment by CayoM** [comment]
Bump

**Comment by CayoM** [comment]
any chance a new docker image comes out? im willing to help, but unfortunately this project doesnt seem to be active at all...

**Comment by GregWoods** [comment]
They don't seem to be interested in Docker. For a user just wanting to get TeamPass up and running as quickly as possible, Docker seemed like the obvious choice. But for me, learning the basics of Docker, Azure Container Registry and Azure Container Instances is a big enough barrier for a noob. Putting up with untested and incomplete images is a showstopper.

**Comment by CayoM** [comment]
yeah, i have that feeling too. Too bad this is beeing ignored. Unfortunately we will stop evaluating this product due the lack of interest from maintainer.
