### ISSUE TITLE
SMTP Mail Settings can't configure

### ISSUE THREAD

**Issue by knidhin1** [nilsteampassnet/TeamPass#2618]
Hi,

 can't configure SMTP settings while configuring getting below error

NB:- I used docker-compose to setup teampass

Email test unsuccessful. Verify your settings (did you set your user account email address?) undefined

**Comment by daniloveras** [comment]
I have the same problem.

**Comment by finsher** [comment]
+1
I have the problem too. I get the same error message when i try to verify my settings.
I used php to set up teampass.

**Comment by finsher** [comment]
> +1
> I have the problem too. I get the same error message when i try to verify my settings.
> I used php to set up teampass.

solved for. was my own fault.

**Comment by iqbaltkj** [comment]
@finsher what is your fault? i have same issue too

**Comment by susmera-joseph** [comment]
Hi all, Any one got solution for email notification issue? I am getting same error "mail test unsuccessful. Verify your settings (did you set your user account email address?)  undefined" But the user account from which email notification is tested have email address.I am using TeamPass 2.1.27.36  2009 - 2023  .
