### ISSUE TITLE
LDAP ACTIVE DIRECTORY not import Users and Groups

### ISSUE THREAD

**Issue by hoko18** [nilsteampassnet/TeamPass#2620]
### Steps to reproduce
1. Enable users authentication through LDAP server
2.LDAP server type ActivDirectory
3. IMPORT

### Expected behaviour
Import users and Groups from Active Directory

### Actual behaviour
Not import Users or Groups

### Server configuration
 Ubuntu 16.04.6 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
Server version: 10.0.38-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
**PHP version:**
PHP 7.0.33-0ubuntu0.16.04.4 (cli) ( NTS )
**Teampass version:** 
 2.1.27.35
![image](https://user-images.githubusercontent.com/49939379/58549172-35c70f80-820b-11e9-96e4-0e853c87b43b.png)

**Comment by giveen** [comment]
It doesn't actually import the users. You have to create the user accounts, then it uses LDAP as the authentication method.

**Comment by olegtarasenko** [comment]
you don't need to create any user accounts, just try to login with your AD account, that's all!

**Comment by dedisoft** [comment]
Hi,
Using version 2.1.27.36, impossible to new users on AD to login.
LDAP is running fine, but impossible to have new users.
I've tried to create manually the new user, but not possible too.
Only existing user can log in using LDAP/AD.
Thanks

**Comment by Auschie** [comment]
Hi,
i'm using 2.1.27.36 and i have the them issue.
New AD users cannot log in, LDAP works fine, creating manually new user is impossible, existing users can log in.

**Comment by apiaser** [comment]
Hello,
I have this issue too.
Like hoko18, LDAP works fine but users can't log in. Only local users can.

This is my configuration :
TeamPass 2.1.27.36
CentOS Linux release 7.7.1908
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.11


Is there a solution ?

Thanks

**Comment by olegtarasenko** [comment]
@apiaser you should check through admin account is there any new users in TP user catalog. after everything is configured correct you would need to grant permission for login from admin console.

**Comment by apiaser** [comment]
unfortunately no new user.
In despite of the LDAP test message : Successfully connected.
I have no error in log files. 
So now I don't know where to search  .

**Comment by olegtarasenko** [comment]
prob could be the case but how do you login? try to use only SAMaccountname without @domain.

**Comment by olegtarasenko** [comment]
if you use in configuration @domain, delete @ and leave only name contoso.com

**Comment by apiaser** [comment]
I don't use @Domain, I only use my login a.piaser.

**Comment by apiaser** [comment]
I read the code and I understood why it didn't work.
In LDAP configuration, you can test current configuration with anonymous bind for search (NO "LDAP bind DN" and NO "LDAP bind password "). It works.
But it doesn't work when you log in : it doesn't bind with users credentials, it needs "LDAP bind DN" and  "LDAP bind password ".

Thanks for your help

**Comment by thomasrec** [comment]
Hello,
I have same issues, since I upgrade to 2.1.27.36.
I can't create local user neither.
I don't understand with I have issues with encoding now.
If I can help

Thanks

**Comment by Auschie** [comment]
Hey Guys,

if you cant login to TeamPass (2.1.27.36) as an Active Directory User who has not previously logged in, then you must change the following files:

sources/users.queries.php 
// Add user in DB
line: 143
```
'encrypted_psk' => '',
'favourites' => '',
'latest_items' => ''
```

sources/identify.php
// save an account in database 
line: 161
```
'encrypted_psk' => '',
'favourites' => '',
'latest_items' => '',
```

sources/identify.php
// Get user info from LDAP
line: 962
```
'encrypted_psk' => '',
'favourites' => '',
'latest_items' => '',
```


I hope this solution works for you too.

SOURCE: https://github.com/nilsteampassnet/TeamPass/issues/2691

**Comment by thomasrec** [comment]
Hello thank for your reply
I find a modification in the sql base and now the issue is solved.

**Comment by jwhitewick** [comment]
Sent via BlackBerry Hub+ Inbox for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
