### ISSUE TITLE
Utilities doesn't work correctly after upgrade

### ISSUE THREAD

**Issue by PiotrIr** [nilsteampassnet/TeamPass#2623]
### Steps to reproduce
1. Login to Teampass
2. Navigate to Utilities
3. Navigate to Items

### Expected behaviour
Tell us what should happen
I should be able to open 
### Actual behaviour
Getting error message:
1. logs -> items: DataTables warning: table id=t_items - Ajax error. For more information about this error, please see http://datatables.net/tn/7
2. On any other tab I'm getting spinning circle
![image](https://user-images.githubusercontent.com/12460359/58622961-c7df1e80-82c4-11e9-816a-40e2a6437147.png)

3. List empty - spinning circle all the time
4. Deletions: DataTables warning: table id=t_items - Ajax error. For more information about this error, please see http://datatables.net/tn/

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.2
**Teampass version:** 
2.1.27.35
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Updates

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.domain.com',
    'favicon' => 'https://teampass.domain.com/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.domain.com/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.domain.com/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '2',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;st$
    'send_stats_time' => '1523706555',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.domain.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'email@domain.com',
    'email_auth_pwd' => '****',
    'email_port' => '25',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'teampass@domain.com',
    'email_from_name' => 'Teampass',
    'pwd_maximum_length' => '100',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
   'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Teampass',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Dublin',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '60',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'tree_counters' => '1',
    'ga_reset_by_user' => '1',
    'settings_offline_mode' => '0',
    'teampass_version' => '2.1.27',
    'upload_zero_byte_file' => '0',
   'teampass_version' => '2.1.27',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'admin_2fa_required' => '1',
);

### Client configuration
**Browser:**
Chrome
**Operating system:**
W10
#### Web server error log
```
Insert your webserver log here

[Thu May 30 08:44:38.223342 2019] [:error] [pid 5364] [client IP:21351] PHP Notice:  Undefined index: accessLevel in /var/www/html/teampass/sources/items.queries.php on line 2722, referer: https://teampass.domain.com/index.php?page=items
[Thu May 30 09:04:25.372216 2019] [:error] [pid 5364] [client IP:45225] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 805, referer: https://teampass.domain.com/index.php?page=manage_views

**Comment by 009thomas** [comment]
We are using RHEL 7.5

**Comment by PiotrIr** [comment]
Hi 
Partly I've resolved the issue by increasing memory in php.ini. Now, the issue seems to be with:
1. spinning circle on all tabes
2. Deletations doesn't work. Basically when I delete something it doesn't show in the tap. The tab is empty.

Logs:
[Thu May 30 10:23:55.787256 2019] [:error] [pid 4294] [client IP:6231] PHP Notice:  Undefined index: accessLevel in /var/www/html/teampass/sources/items.queries.php on line 2722, referer: https://teampass.domain.com/index.php?page=items
[Thu May 30 10:23:55.912891 2019] [:error] [pid 4294] [client IP.2:6231]                                                                                                              eferer: https://teampass.domain.com/index.php?page=items

**Comment by nilsteampassnet** [comment]
Please upgrade to latest 2.1.27.36

**Comment by PiotrIr** [comment]
Hi Nils,
Thank you for this. It helped this way I don't have an error in logs. However I still have the issue with Deletions:
![image](https://user-images.githubusercontent.com/12460359/58696967-9af83d80-8390-11e9-8e6d-46dba3b73cb9.png)
