### ISSUE TITLE
Roles based from Active Directory /LDAP?

### ISSUE THREAD

**Issue by sarelol** [nilsteampassnet/TeamPass#2626]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by sarelol** [comment]
Is it possible to map roles in Teampass to Groups in LDAP / Active Directory? We would like to create hierarchy of permissions and as a single source of truth we want to use Active Directory. Would be great if this would support membership in multiple roles.

Thanks in advance for answer.

**Comment by schka17** [comment]
+1
we have the same requirements and it would very heplful

Regards
