### ISSUE TITLE
The problem of displaying the label

### ISSUE THREAD

**Issue by 1Doon1** [nilsteampassnet/TeamPass#2635]
The problem of displaying the label. The label is displayed in unreadable encoding. With the help of the converter I translated that for some reason the label is written with the encoding iso-8859-1, the rest of the fields are displayed without problems.

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by 1Doon1** [comment]
![teampass](https://user-images.githubusercontent.com/46049930/59750252-2b86b700-9287-11e9-991d-a02fbc28b661.jpg)

**Comment by 1Doon1** [comment]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen


### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux lnsrvteampass 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:** 5.5.5-10.1.38-MariaDB-0+deb9u1

**PHP version:** 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7

**Teampass version:** 2.1.27.36

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'http://<anonym_url>/teampass
'favicon' => 'http://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'http://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '3',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '1',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'russian',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1558167465',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'sending_emails' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '',
'email_smtp_auth' => '',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => 'admin',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '1',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Moscow',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'item_creation_templates' => '1',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Firefox - 67.0

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

### Logs

#### Web server error log
```
Constant SECUREPATH already defined - /var/www/html/teampass/includes/config/settings.php (15)
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by cosmedd** [comment]
Hi! It seems the same issue as #2625 

Did you tray the development branch? Or at least this commit:

https://github.com/nilsteampassnet/TeamPass/commit/1d1f385790a45a2c2ea42f260e09b4b1f2de1756

**Comment by 1Doon1** [comment]
> 
> 
> Hi! It seems the same issue as #2625
> 
> Did you tray the development branch? Or at least this commit:
> 
> [1d1f385](https://github.com/nilsteampassnet/TeamPass/commit/1d1f385790a45a2c2ea42f260e09b4b1f2de1756)

What do you mean by the development branch? I read the article, made requests to the database, but the problem persists.

**Comment by cosmedd** [comment]
I mean this commit from the development branch:

[https://github.com/nilsteampassnet/TeamPass/commit/1d1f385790a45a2c2ea42f260e09b4b1f2de1756](https://github.com/nilsteampassnet/TeamPass/commit/1d1f385790a45a2c2ea42f260e09b4b1f2de1756)

It worked for me, at least.

**Comment by 1Doon1** [comment]
> 
> 
> I mean this commit from the [development branch](https://github.com/nilsteampassnet/TeamPass/tree/development):
> 
> [1d1f385](https://github.com/nilsteampassnet/TeamPass/commit/1d1f385790a45a2c2ea42f260e09b4b1f2de1756)
> 
> It worked for me, at least.

 Hello, 
did as in 1d1f385, but the problem remained. Now the characters in the label are different.
![teampass](https://user-images.githubusercontent.com/46049930/60090591-8585f180-974b-11e9-8737-11e176657d58.jpg)

**Comment by reklamafia** [comment]
Try replacing:
`$html_json[$record['id']]['label'] = '-'.utf8_encode($record['label']);`
with
`$html_json[$record['id']]['label'] = mb_convert_encoding($record['label'], "UTF-8", "auto");`
in /sources/items.queries.php
