### ISSUE TITLE
Problem with acces right

### ISSUE THREAD

**Issue by qu1dam** [nilsteampassnet/TeamPass#2636]
Hello,

i notice some bug in Teampass in acces right.

For example Administrator or any other user have roles, and on some  folder have permissions to Write, and checked boxe cannot delete items.
This work, but when check box  Cannot edit items, this dont do anything, and still can edit item.
 
When both boxes selcted, user cant edit and delete item which is wrong, user than should not be able to edit or delete item.

TeamPass 2.1.27.36

**Comment by okvok** [comment]
Hello,

Confirm. This BUG must be fixed!!!!

**Comment by C-Duv** [comment]
Looks similar to #1909 (which was fixed in 2.1.27.8 if I read correctly).
