### ISSUE TITLE
Development Progress

### ISSUE THREAD

**Issue by dynamicat** [nilsteampassnet/TeamPass#2639]
Hi there,
Are you still actively developing your teampass product?  I ask because there are still quite a few bugs in the application which should be addressed in future versions.  For example:
1.  Always have to refresh the page when I want to log in after being automatically kicked out.
2.  Response times clicking from page to page is really slow.  I am guessing this is a database issue? but many people have reported this problem in the past.
3.  When you reveal the password it would be good to allow the clear view to last maybe 5 seconds.

Thanks
Chris

**Comment by giveen** [comment]
I'm wondering if something is happening to him IRL as his last commit to v 3.0 was May 24, 2019

**Comment by nilsteampassnet** [comment]
Yes I'm back, I was really ill ... I'm now on the good direction.

The 3 issues listed are taken into consideration for teampass 3 branch.

**Comment by Calanon** [comment]
When will teampass 3 be released?

**Comment by nilsteampassnet** [comment]
Version 3.0.0.0 should be proposed end of september. It will be more for testing purpose and get feedback from testing users.
Then v3.1 will be released 1 or 2 months after.

**Comment by askmike1** [comment]
@nilsteampassnet Is there any updated timeline for TeamPass 3.0?
