### ISSUE TITLE
Unwanted character set conversion

### ISSUE THREAD

**Issue by r0ble** [nilsteampassnet/TeamPass#2641]
I am upgrading from 2.1.27.7 to 2.1.27.35. During upgrade, in STEP 3, it shows: "The database seems already in UTF-8 charset".
After upgrade description in password entries shows question marks (?) instead of Polish letters.
Example
Wiki [Serwer wiki. / Zarz?dzanie: ssh://192.168.11.156 Dost?p do roota (...)]
insted of original description
Wiki [Serwer wiki. / Zarządzanie: ssh://192.168.11.156 Dostęp do roota (...)]

The same entry in database
select * from teampass_items where id = 4928 ;

| 4928 | Serwery | Serwer wiki. /<br />Zarz?dzanie:<br />ssh://192.168.11.156<br />Dost?p do roota (...)<br />Nazwa i adres serwera: <ServerName> [192.168.11.156] | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |       |      0 | http://wikiit.xx | 427     |     0 | root  |       1 |               |                 0 | wiki@xx.yy | NULL         |        11 | 42               |                         0 | 0                         | defuse          |

which before upgrade looked like that:

| 4928 | Serwery | Serwer wiki. /<br />Zarządzanie:<br />ssh://192.168.11.156<br />Dostęp do roota (...)<br />Nazwa i adres serwera: <ServerName> [192.168.11.156] | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |       |      0 | http://wikiit.xx | 427     |     0 | root  |       1 |               |                 0 | wiki@xx.yy | NULL         |        11 | 42               |                         0 | 0                         | defuse          |

The same happens when upgradeing to version 2.1.27.10
### Steps to reproduce
1. Upload appropriate release of TeamPass to webserver and unzip
2. Before starting the upgrade, run the SQL query: ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;
3. Navigate to [teampass-url]/install/upgrade.php
4. Enter Administrator login and password
5. Click launch button

### Expected behaviour
Upgrade without changing database character set

### Actual behaviour
Changed Polish characters (database character set is UTF8 before and after upgrade)

### Server configuration
**Operating system**:
Ubuntu release 16.04.6 LTS (Xenial Xerus)
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
MySql 5.7.26
**PHP version:**
7.0.33
**Teampass version:** 
2.1.27.7
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://192.168.11.156/teampass',
    'favicon' => 'https://192.168.11.156/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://192.168.11.156/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://192.168.11.156/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://192.168.11.156/teampass/logo.png',
    'custom_login_text' => '',
    'default_language' => 'english',
 'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_langu
ages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1502269574',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '1',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'aa.xx.yy',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'username',
    'email_auth_pwd' => 'pass',
    'email_port' => '587',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'mail.from@xx.yy',
    'email_from_name' => 'TeamPass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
 'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Warsaw',
    'copy_to_clipboard_small_icons' => '1',
    'settings_offline_mode' => '1',
    'teampass_version' => '2.1.27',
    'personal_saltkey_security_level' => '0',
    'ldap_new_user_is_administrated_by' => '0',
    'ldap_port' => '389',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'admin_2fa_required' => '1',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    );

### Client configuration
**Browser:**
Firefox Quantum 67.0.4 (64bits)
**Operating system:**
Windows 10

**Comment by ozawa-hi** [comment]
The following thread fixed this problem for me.
https://github.com/nilsteampassnet/TeamPass/issues/2681
