### ISSUE TITLE
The secret value of "bck_script_key" is not masked in the output of the bug report

### ISSUE THREAD

**Issue by cnotin** [nilsteampassnet/TeamPass#2647]
### Steps to reproduce
1. Login
2. Go to personal profile
3. Click to "Report a bug"
4. The displayed content, under the "Server configuration" section, discloses the value of the `bck_script_key` which, I suppose, should be secret

### Expected behaviour
The value of this key must be removed, like for `bck_script_passkey`.

### Actual behaviour
The secret value of this key is disclosed.

**Comment by cnotin** [comment]
For more context, see that these users' "bck_script_key" values are disclosed in these bug reports:
https://github.com/nilsteampassnet/TeamPass/issues/2345
https://github.com/nilsteampassnet/TeamPass/issues/2188

In other cases, it is masked, for example:
https://github.com/nilsteampassnet/TeamPass/issues/2398
But I do not know why...

**Comment by nilsteampassnet** [comment]
Thank you.
This value was indeed not automatically hidden.

**Comment by cnotin** [comment]
Closed by 3ebe8ce
