### ISSUE TITLE
Correction Code to TeamPass v3.0

### ISSUE THREAD

**Issue by Leboubou111** [nilsteampassnet/TeamPass#2649]
I've tried TeamPass v3.0 and I've already correction.

1. 
To the first Install script, "avatars" folder missing to include folder.
-> Create it, and OK !

2.
After installation, first loggin to admin user, blank page with two php error.
On index.php, line 781 :
-> When you called [cpassman_dir], delete the "." before "/" folder
Exemple : 

- include $SETTINGS['cpassman_dir'].'**.**/pages/'.$mngPages[$_GET['page']];

replace to :

- include $SETTINGS['cpassman_dir'].'/pages/'.$mngPages[$_GET['page']];

Lines to change it under /index.php
- 781
- 784
- 794 

And, after change it, admin page appears correctly.

3.
On admin page, add css code : 
overflow-x: hidden; 

This is my first test... I adjust this issue if I find an another bug.

**Comment by Leboubou111** [comment]
@nilsteampassnet 

Are you OK ?
Several months not any news... We're worried.

**Comment by nilsteampassnet** [comment]
@Leboubou111 

Yes I'm back ...
I've restarted the development after a long disease period.

**Comment by nilsteampassnet** [comment]
Thank you for your feedback.

**Comment by Leboubou111** [comment]
@nilsteampassnet 
Happy to read this.
The WebUI to TeamPass 3 really better. It's an essential point.

Again, thanks a lot for your time to development.

**Comment by Leboubou111** [comment]
> For what html element, this is requested?

For body... I think.
Sorry but I deleted TeamPass 3 because doesn't works.

I think you're a french user ?

**Comment by atiosnor** [comment]
> @Leboubou111
> 
> Yes I'm back ...
> I've restarted the development after a long disease period.


When will the bug be fixed?  
"search button"  ------->>>>
DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by nilsteampassnet** [comment]
> I think you're a french user ?

Yes I am


@atiosnor 
What ticket id please?

**Comment by Leboubou111** [comment]
> 
> 
> > @Leboubou111
> > Yes I'm back ...
> > I've restarted the development after a long disease period.
> 
> When will the bug be fixed?
> "search button" ------->>>>
> DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

I had a similar problem with IIS 7 and a older PHP version : https://github.com/nilsteampassnet/TeamPass/issues/1971

**Comment by atiosnor** [comment]
> > > @Leboubou111
> > > Yes I'm back ...
> > > I've restarted the development after a long disease period.
> > 
> > 
> > When will the bug be fixed?
> > "search button" ------->>>>
> > DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
> 
> I had a similar problem with IIS 7 and a older PHP version : #1971

I solved this problem by removing spaces in element url
example:
"       http://" - leads to an error
"http://" - removing the spacebar - earned

**Comment by atiosnor** [comment]
> > I think you're a french user ?
> 
> Yes I am
> 
> @atiosnor
> What ticket id please?

I solved this problem by removing spaces in element url
example:
"       http://" - leads to an error
"http://" - removing the spacebar - earned

**Comment by Leboubou111** [comment]
> @ Leboubou111
> 
> Oui je suis de retour ...
> J'ai repris le développement après une longue période de maladie.

*FR VERSOIN*
@nilsteampassnet : Veux tu de l'aide pour le développement de la v3 ?
J'ai quelques connaissances en HTML/CSS/JS si besoin. Mais que très peu en PHP.

*EN VERSION*
@nilsteampassnet : Do you want something help for v3 dev ?
I've some experience to HTML/CSS/JS if needed. Otherwise, very lite un PHP.

**Comment by Leboubou111** [comment]
@nilsteampassnet Nous n'avons plus de nouvelle... Tout se passe bien ? As-tu abandonné le projet ?

**Comment by khmermega** [comment]
Having the same issue.
