### ISSUE TITLE
Editing user

### ISSUE THREAD

**Issue by chmich** [nilsteampassnet/TeamPass#2657]
Hi,

Version 2.1.27.9

If i want to modify a existing user, all values are blank and i always have to insert all values anew.
is this already fixed?
i could not find that bugfix in release-notes.

many thanks!
Christian

![image](https://user-images.githubusercontent.com/31048265/61573085-dcf85280-aaa8-11e9-9ecb-9fd30e5c0bfe.png)

**Comment by nilsteampassnet** [comment]
This must be something related to this old version.
It is not existing in latest at least.
