### ISSUE TITLE
Google 2FA QR code is not displayed if using a proxy

### ISSUE THREAD

**Issue by FerencSpala** [nilsteampassnet/TeamPass#2662]
### Steps to reproduce
1. Install / upgrade to the latest version
2. Set up the proxy on the admin interface
3. enabled 2FA on the admin interface
4. get the temporary access code during the first login
5. enter the code (wait for the QR code to pop up)

### Expected behaviour
The QR code should be displayed on the screen.

### Actual behaviour
If your server is behind the proxy, the QR code will not be displayed.
I found the reason of it though. The CURLOPT_PROXY option was not set in the code.
The code that is responsible for downloading the Google QR code is using BaseHTTPQRCodeProvider.getContent function from
includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php

When it sets up the curl parameters, it does not set the proxy:
```
curl_setopt_array($curlhandle, array(
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_DNS_CACHE_TIMEOUT => 10,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => $this->verifyssl,
            CURLOPT_USERAGENT => 'TwoFactorAuth',
        ));
```

After I added our proxy IP and port, it started working. I wasn't sure how to access the proxy config values that I set on the admin interface, so I just hard-coded the IP and port in the PHP file to make it work:
```
curl_setopt_array($curlhandle, array(
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_DNS_CACHE_TIMEOUT => 10,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => $this->verifyssl,
            CURLOPT_USERAGENT => 'TwoFactorAuth',
            CURLOPT_PROXY => '192.168.100.11:3128'
        ));
```
Once I added the CURLOPT_PROXY option, it started to work.
Recommended solution -- adding this option to the code and use the proxy IP and port that is saved in the config.

### Server configuration
**Operating system**: Debian 9

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.38

**PHP version:** PHP 7.0.33

**Teampass version:** TeamPass 2.1.27.36

**Teampass configuration file:** n/a

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`. n/a

### Client configuration
**Browser:** n/a

**Operating system:** n/a

#### Web server error log
```
n/a
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
n/a
```

**Comment by nilsteampassnet** [comment]
Thank you so much.

I will do the change
