### ISSUE TITLE
No access after logout

### ISSUE THREAD

**Issue by hg-fm** [nilsteampassnet/TeamPass#2664]
We recently upgraded to 2.1.27.36.

If i create a folder now and place the password in it, after logout and login again, it says "access to item denied" and we can't see the folder and password anymore.

#2659 # Steps to reproduce
1. Login, create folder and password in it
2. Logout
3. Login again, folder and password is gone

### Expected behaviour
Folder and password should be still accessible

### Actual behaviour
Folder and password get lost

### Server configuration
**Operating system**:
Ubuntu 16.04.6 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
mysql-server-core-5.7 / 5.7.27-0ubuntu0.16.04.1

**PHP version:**
7.0.33-0ubuntu0.16.04.6

**Teampass version:** 
2.1.27.36

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu 16.04

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I've performed several test to reproduce but I couldn't.
What is the role of this user?
Can the user create a new item in an existing folder? and is it viewable after logout/login sequence?

**Comment by hg-fm** [comment]
The user has the "manager" role.
New items in existing folders persist.

Thank you!
