### ISSUE TITLE
Exclude user from 2 factor auth

### ISSUE THREAD

**Issue by geosone** [nilsteampassnet/TeamPass#2666]
Could there be added an option to add specific users to disable 2 factor auth.

at the moment only Admin is excluded .

adding a checkbox at the user account modify page would be great.

**Comment by geosone** [comment]
could you tell me what file or mysql change i can do to add exclude users from 2FA

**Comment by mzs114** [comment]
I had similar issue(maybe different for you), for example, without a smartphone and just a standard browser(Chromium, or Firefox) how will the user use 2FA? I then came across a nice 2fa addon for both the browsers. Named authenticator, I use it personally. 
https://github.com/Authenticator-Extension/Authenticator

**Comment by geosone** [comment]
i have solved it by adding this users to the sam list as the admin account so no 2fa for them.
at the moment i am checking if it is possible to add the apache auth infront of teampass and allow this auth without 2fa.
