### ISSUE TITLE
upgrade from TeamPass-2.1.26-final-2 to TeamPass-2.1.27.36

### ISSUE THREAD

**Issue by dang89** [nilsteampassnet/TeamPass#2670]
Hello,
i am trying to upgrade teampass from 2.1.26 final2 to 2.1.27.36 but there is inconsistency by following the docs(https://teampass.readthedocs.io/en/latest/install/upgrade/) beacuase on version 2.1.26Final2(upgrade on 2017) i don't have the same struture of table teampass_misc.

mysql> select * from teampass_misc limit 5;
| type  | intitule          | valeur |
+-------+-------------------+--------+
| admin | max_latest_items  | 20     |
| admin | enable_favourites | 1      |
| admin | show_last_items   | 1      |
| admin | enable_pf_feature | 0      |
| admin | log_connections   | 0      |
+-------+-------------------+--------+
5 rows in set (0.00 sec)

AND APPLYING Upgrade to 2.1.27.(latest): 

mysql> ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;
ERROR 1054 (42S22): Unknown column 'id' in 'teampass_misc'

And if i trying to do upgrade all fields passwords are empty after upgrade.

How to fix it?

**Comment by nilsteampassnet** [comment]
Please read the page to the end.
You could see that you need to upgrade to 2.1.26-final-3
Then run a query before upgrading to latest one ;)

**Comment by dang89** [comment]
Thank you for the answer.
but the upgrade from 2.1.26-final 2 to 2.1.26-final-3 it does not imply any modification for database.

And the upgrade from 2.1.26-final-3 to 2.1.27.36 with the query "ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;", i will have the same issue on database.

**Comment by dugniewski** [comment]
If I am executing the script "ALTER TABLE` teampass_misc` CHANGE `id`` increment_id` INT (12) NOT NULL AUTO_INCREMENT; " I automatically lose the ability to manage the list of available folders.
How can you fix this problem?
