### ISSUE TITLE
Password recovery "Forgot your password?" don't do anything

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#268]
When I try to recover a password clicking "Forgot your password? " recovery mechanism It doesn't do anything 

I tried firefox, chrome, opera, IE on a fresh clean install of teampass.

Thanks in advance.

**Comment by girishkg** [comment]
I am still seeing this in **"TeamPass 2.1.26  2009 - 2016".** 
I am able to receive the password reset link through mail to my mailbox like (https://192.168.126.47/index.php?action=password_recovery&key=Oojeithee5eibahr4eePhaetoosho3kai2leitoom8taizae9e&login=ggangaiah) 

But when click on the link, it just opens up "https://192.168.126.47/index.php?page=items" page instead providing password reset page.

**Comment by bembol** [comment]
Hi is there finally the fix for #268

**Comment by aokunev** [comment]
Hello, looks like the commit does not include the fix for the problem with generating an email with the new password. There are only spaces removed, 2016 update and single fix to change || to &&.  

https://github.com/nilsteampassnet/TeamPass/commit/8306f3f4d143c80a04d8a40ab2c0fb69075fe02e

regards, Andrey

**Comment by ChristianSedlmair** [comment]
Hi, i've installed 2.1.27.
Password-Recovery don't do anything, like described here on the top
May it be that the above fix is not included in this Version?
Regarding to Andrey's Link ist should be fixed in 2.1.26...?

**Comment by nilsteampassnet** [comment]
This is fixed in the development branch.
Release will be 2.1.27.8

**Comment by chmich** [comment]
Thank you, Nils, you help us a lot with your program!
Now, it works fine.

Can i post a idea on this way?
I would vote for a new password-type without control- or special-chars and better redable.
Example: Hh6p.ZuBQ.eqn3.s1tyr
Benefits: Secure transportable, selectable by double-click and if you have to type it, its easier.

In one case, by copy&Paste a " changed to %. I can not tell you how this was caused, i can not reconfigure this but it was.

Further, i had one Problem:
Update to 2.1.27.8:
All Steps worked, but then:
http://your_domain/teampass/install/upgrade.php
=> Enter Admin-pw => Bar ran left and right, but nothing more happens (more than 10 mins)
i had to delete the complete TeamPass, install it completly new

But, now, it runs, i'm happy.
Best Regards
Christian
