### ISSUE TITLE
[Teampass v3.0.0.0] fresh install leads into Table 'teampass.teampassDEMOV3_users' doesn't exist 

### ISSUE THREAD

**Issue by cummie** [nilsteampassnet/TeamPass#2682]
### Steps to reproduce
	1. fresh install with the  github 3.0.0.0 branch on the given system below 
	2. Installation finished without an error
	3. After clicking the Url to open the page I get this fault: Table 'teampass.teampassDEMOV3_users' doesn't exist

### Expected behaviour
I expected the login page

### Actual behaviour
Loading the page leads to a white page with a single line error message:
Table 'teampass.teampassDEMOV3_users' doesn't exist 

I had a look into the database, and I missed the table users 

### Server configuration
**Operating system**: Linux tis.pass 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.6

**Database:** 5.5.60-MariaDB

**PHP version:** 7.3.6

**Teampass version:** 3.0.0.0

**Teampass configuration file:**
```

**Updated from an older Teampass or fresh install:**

Fresh installed!

### Client configuration

**Browser:** Chrome - 77.0.3865.90

**Operating system:** Windows - 64bits

### Logs

#### Web server error log
```

#### Teampass 10 last system errors
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by cummie** [comment]
Dear Nils,
I did a fresh install with the version 3.0.0.0 include commit cf785ce, but after an installation without error message I still get this error, when I open the login page:
 Table 'teampass.teampassDEMOV3_users' doesn't exist

Kindly regards,
cummie

**Comment by Jatzoo** [comment]
Problem related to #2720.

**Comment by cummie** [comment]
Hi,
I found a point where the symptoms changes:
In my first scenario I used CentOS 7.7 with minimal installation and after finishing the teampass setup I got this error Table 'teampass.teampass_users' doesn't exist.
Then I tried the same with CentOS 8.0 and now I am a step further.
I get the login screen, but I can not login with the admin user.
Kindly regards
