### ISSUE TITLE
Permissions not inherited when user creates a sub-folder

### ISSUE THREAD

**Issue by vasilykolosov** [nilsteampassnet/TeamPass#269]
When a user is granted access to a folder individually (not with a role), and he or she creates a subfolder, it's not visible or accessible, until explicitly granted rights via User Management panel. 

Steps to reproduce:
1. Create a user
2. Create a folder
3. Add the folder as accessible by user via User Management panel
4. Log in as a user
5. Enter the test folder
6. Create a new subfolder

Result: new subfolder is created, but is not visible 
Desired behaviour: new subfolder is created and is immediately visible and accessible by user

**Comment by ASGAlex** [comment]
This bug still exists :-(
