### ISSUE TITLE
DataTables warning: table id=t_folders - Invalid JSON

### ISSUE THREAD

**Issue by isco1988** [nilsteampassnet/TeamPass#2702]
[](### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: -amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:** 5.5.5-10.1.38-MariaDB-0+deb9u1

**PHP version:** 7.2.13-1+0~20181207100540.13+stretch~1.gbpf57305

**Teampass version:** 2.1.27.36

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
mozila and chrome 
**Operating system:**
DEBIAN 9.0
```


```
Insert the log here and especially the answer of the query that failed.
```
DataTables warning: table id=t_folders - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
)

**Comment by ozawa-hi** [comment]
I've also seen this error to occur when the session timed out and I do some operation on the stilled opened TeamPass page. If I refresh the page to make sure that I'm still in before conducting any operation, I'm not seeing this error.
