### ISSUE TITLE
Subfolders never Indent

### ISSUE THREAD

**Issue by kirkmcdaniel** [nilsteampassnet/TeamPass#2707]
1. I create a folder
    ie Test
2. I create a subfolder 
   I expect

           test
                    folder2

but I get this

test
folder2 when I view the folders with a user

Version 2.1.26
Ubuntu

**Comment by ozawa-hi** [comment]
Are you logged in as non-admin? I'm currently using 2.1.27.36 and subfolders are being indented when I login as non-admin.
When I logged in as an admin, subfolders has a sideways triangle to the right of the name.
I'm using Ubuntu 18.04.

**Comment by kirkmcdaniel** [comment]
interesting enough , I am using an admin account, let me try a non admin
but I have another instance 2.1.29 and it shows folders for the admin user

I

**Comment by kirkmcdaniel** [comment]
Nope , did not work..
I removed the admins role from my account and see all folders as equal weight

I do not see any indent or any sidways or sideways triangle

note: I am using AD authentication though

**Comment by ozawa-hi** [comment]
Can you paste a screen image? Authentication shouldn't matter. It just checks the password and create new user if the user doesn't exist.

**Comment by kirkmcdaniel** [comment]
hello I had to blank out some stuff
but the KA folder is a subfolder of OT


![teampassimage](https://user-images.githubusercontent.com/29588972/67810990-f2422d00-fa58-11e9-9c0c-143be330d588.JPG)

**Comment by kirkmcdaniel** [comment]
![Untitled](https://user-images.githubusercontent.com/29588972/67811177-709ecf00-fa59-11e9-9469-9ca95462dd90.png)

**Comment by ozawa-hi** [comment]
If you can, can you version up to 2.1.27.36? I'm not having indent problem with this version.
If you're using Chrome, hit the F12 key to bring up a source of the page.
Subfolders should be nested within the parent folder and have class "jstree-children".
Something like below:
<ul role="group" class="jstree-children">
  <li role="treeitem" title="ID [3] " aria-selected="false" aria-level="2" aria-labelledby="fld_3" id="li_3" class="jstree-node jstreeopen jstree-leaf">

**Comment by kirkmcdaniel** [comment]
Yes, I will let you know afterwards, Thank You
