### ISSUE TITLE
admin and user cannot login into teampass

### ISSUE THREAD

**Issue by skrawi99** [nilsteampassnet/TeamPass#2712]
hello,

no admin or user can login in my teampass.
only a gear in a view show by attemp to login...

![image](https://user-images.githubusercontent.com/57102531/67692475-7ab0c700-f9a0-11e9-8ca0-9d280f729e92.png)

Version is 2.1.27, installed on a qnap NAS.
Lost password function is ok.

can someone help us?

**Comment by ajadi** [comment]
Greetings! We also have this problem, but according to my observations, only if php-ldap is used. Can this be fixed somehow?

**Comment by mnkq** [comment]
please check your web server error log
if cause of error is php session permisio denied then you must change php-fpm configuration  to
session.save_path = /tmp

dont forget to restart php-fpm service and webserver
i hope it will fix your problem
