### ISSUE TITLE
 Set up Google 2FA

### ISSUE THREAD

**Issue by zJeanMiliodas** [nilsteampassnet/TeamPass#2715]
What should be done to set up Google 2FA in TeamPass.

1nd - I activate the Google 2FA option in the TeamPass admin panel.

2nd-  I download the application on my smarphone.

- Now the app is requesting a key. But in TeamPass they have no keys.

I was able to authenticate by DUO. But I would like to authenticate through Google.

**Comment by BeleK0ss** [comment]
Send qr request you can in the user manager, next to the user login icon qr code. After that, the user's e-mail (must be registered in the user's profile) will be sent a code that you need to enter on the main teampass page, when you enter your login and password, clicking "Login" will display a QR code, which should be scanned by the application through your smartphone

**Comment by c11goncalves** [comment]
Hi. I've sucessfully configured google authentication for all users. I was wandering if it is possible to have some users using google authentications and other use Yubico authentication

**Comment by c11goncalves** [comment]
Hi. I've sucessfully configured google authentication for all users. I was wandering if it is possible to have some users using google authentications and other using Yubico authentication or no 2FA at all.
