### ISSUE TITLE
Which PHP Version should be used? 71 oder 72 or 73 or 74 ?

### ISSUE THREAD

**Issue by jokr-k499** [nilsteampassnet/TeamPass#2719]
I tried to install with php version 7.4.0.r4, but this seems not to work.
Which version is the currently recommended php version ?

**Comment by ozawa-hi** [comment]
I have TeamPass 2.1.27.36 running on  PHP 7.2.19 on Ubuntu 18.04

**Comment by tiredofit** [comment]
I have Teampass running on PHP 7.3.11 - Alpine without issue.

**Comment by pb1212** [comment]
I have TeamPass 2.1.27 running PHP 7.3.7 on Windows Server 2016 - all working great
