### ISSUE TITLE
restore backup teampass can't load

### ISSUE THREAD

**Issue by Jana1102** [nilsteampassnet/TeamPass#2721]
Hi, restore backup teampass can't load.

Backup 2.1.24 to restore 2.1.27.  I download sql 2.1.24 when I try to restore to 2.1.27 does not load.

![tellla](https://user-images.githubusercontent.com/57626675/68759225-0d32a680-05ee-11ea-9746-55c489729ba4.png)

**Comment by ozawa-hi** [comment]
Have you tried the steps mentioned in the following thread?
https://github.com/nilsteampassnet/TeamPass/issues/2000

**Comment by Jana1102** [comment]
can't find teampass-seckey.txt file version 2.1.24

**Comment by ozawa-hi** [comment]
Skip down to gimgunwoo's comment on Feb 17, 2018
