### ISSUE TITLE
 Backup Restore

### ISSUE THREAD

**Issue by osnilima001** [nilsteampassnet/TeamPass#2726]
Hello, I am trying to restore my backup to a new server, have the bank .sql files, teampass-seckey.txt, includes \ libraries \ csrfp \ libs \ csrfp.config.php. What should I do to make backup restore work? When I go up the new server and replace the files Teampass stops opening and generates an error

**Comment by PatrickF11** [comment]
Hi, i have the exact same problem.
After replacing the files i'm getting the error:
<a href="https://ibb.co/xsYFY9f"><img src="https://i.ibb.co/xsYFY9f/Untitled-picture.png" alt="Untitled-picture" border="0"></a>

**Comment by PatrickF11** [comment]
Hi, are there any new ideas?

**Comment by PatrickF11** [comment]
Happy new year Nils,

unfortunately  the problem persists. I'm still not able to backup our "old" server and move to the new one. Any help is highly appreciated.
