### ISSUE TITLE
Options LDAP Active Directory - Strong(er) autentication required

### ISSUE THREAD

**Issue by chepakoi** [nilsteampassnet/TeamPass#2728]
### Expected behaviour
I should connect to my Active Directory

### Actual behaviour
I try but when I test I have this message "Create new adldap object : success
After anthenticate : Strong(er) authenticate required
ldap status : Not possible to get connected with this user
### Server configuration
Linux : centos-release-7-7.1908.0.el7.centos.x86_64

Apache : httpd-2.4.6-90.el7.centos.x86_64

Mysql : mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1

PHP : PHP 5.6.40

Teampass version :  2.1.27.36 

Configuration file : 
'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '86400',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => 'michael.rogue_adm',
    'bck_script_path' => '/var/www/Teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '3hfFxEL4ysDUSLcnxUVEwR5a5AnNfW8cLHArP3cw',
    'admin_2fa_required' => '1',
    'ldap_usergroup' => 'CN=GG_Teampass,OU=Groupes Globaux,OU=RBC,DC=rbc,DC=adds',
    'ldap_allowed_usergroup' => 'CN=GG_Teampass,OU=Groupes Globaux,OU=RBC,DC=rbc,DC=adds',
    'ldap_bind_dn' => 'uid=michael.rogue_adm,OU=Informatique,OU=RBC,DC=rbc,DC=adds',
    'ldap_bind_passwd' => 'CAPROBOCATH76000$',

thankx a lot.

**Comment by ozawa-hi** [comment]
Answer to the following question may help you.
https://serverfault.com/questions/497562/ldap-cant-perform-an-authenticated-bind-windows-server-2008-r2-using-php-apac/497928#497928

**Comment by chepakoi** [comment]
Thx for your mail.
Unfortunately, I can't put

   - Negotiate Signing (Network security: LDAP client signing requirements)
   -

   No signing requirements (Domain Controller: LDAP server signing
   requirements)

for some security reasons.

Does Teampass can communicate with Active Directory if "Domain Controller:
LDAP server signing requirements" is configure on"require the signature"
without configure LDAPS ?


<http://http://rogueinformatique.eu/>

*Michaël Rogue*



06 14 31 62 70





Courrier électronique strictement confidentiel et exclusivement adressé au
destinataire. Si vous n'êtes pas ce destinataire, tout usage de ce message
est strictement interdit. Veuillez avertir l'expéditeur de l'erreur et
détruire ce courrier.


Le sam. 7 déc. 2019 à 01:13, Hitoshi Ozawa <notifications@github.com> a
écrit :
