### ISSUE TITLE
Not able to configure email server and send email

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#2742]
Hi TeamPass team.

I'm using official docker image and when I try to configure email server I get this message **"Email test unsuccessful. Verify your settings (did you set your user account email address?)  undefined"**.

I've already confirmed that "admin" user has email address configured.

![image](https://user-images.githubusercontent.com/51119521/72007995-a4545d00-3231-11ea-93e9-df28f952bfc4.png)

### Steps to reproduce
1. Go to Setting - Email - Email server configuration
2. Fill out all the needed information related to mail server
3. Click on "Send yourself a test email"

### Expected behaviour
An email should be sent as a test

### Actual behaviour
The message "Email test unsuccessful. Verify your settings (did you set your user account email address?)  undefined" is showed.

### Server configuration
TeamPass docker Image latest

**Updated from an older Teampass or fresh install:**
[...]
    'enable_send_email_on_user_login' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'sending_emails' => '0',
    'email_smtp_server' => 'mail.server.com',
    'email_smtp_auth' => '0',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'contato@mail.server.com',
    'email_from_name' => 'TeamPass Team',
[...]

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu

#### Web server error log
```
No logs
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[{"result":"email_test_conf", "error":"error_mail_not_send"}]
```

**Comment by ropesca** [comment]
Actually I just realize it's not only a docker problem. When I install TeamPass directly on a Debian system, I get the same error.

Any idea what is going on?

![image](https://user-images.githubusercontent.com/51119521/72176659-9df2ec00-33bd-11ea-86a5-0114fe4b86be.png)

**Comment by ropesca** [comment]
Hi all.

Has anyone successfully configured the email server to send messages?

Thanks.

**Comment by br0c0l1** [comment]
Hi repesca,

I have it working with my personal gmail account on the latest release. It's not running within a container but directly on the system with nginx and the latest php. What are you using for a local mail server? Postfix or Exim?

**Comment by ropesca** [comment]
Hello.
I'm using postfix on my mail server. But the errors appears to be local:
"Email test unsuccessful. Verify your settings (did you set your user account email address?) undefined".

I've already confirmed that "admin" user has email address configured.

**Comment by br0c0l1** [comment]
I apologize for the delay, but did you find anything in particular in the postfix logs located at /var/log/mail.err? Might also help to check that actual users table for the teampass DB and ensure the value is in fact listed for the admin user account.

Can you also provide a bit more detail on how you configured postfix when you first installed and configured it?
