### ISSUE TITLE
Upgrade 2.1.23 -> 2.1.23.4: stuck at step1 with scrolling animation

### ISSUE THREAD

**Issue by glx42** [nilsteampassnet/TeamPass#2747]
### Steps to reproduce
1. wget release 2.1.23.4 + unpack in /var/www/teampass/
2. copy settings.php from previous version to /var/www/teampass/includes/
3. backup saltkey in /etc/httpd/conf.d/saltkey
4. follow upgrade to 2.1.23.4 steps in https://teampass.readthedocs.io/en/latest/install/upgrade/
5. Run SQL query: ALTER TABLE `teampass_misc` ADD `id` INT(12) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
6. Rename the file /install/upgrade_ajax.php by /install/upgrade_ajax_original.php
7. Get the file upgrade_ajax_for_2.1.23.4.php, store it in folder /install and rename it /install/upgrade_ajax.php
8. chown -R apache:apache /var/www/teampass/
9. /etc/init.d/httpd restart
10. Clear browser history
11. run install/upgrade.php in browser
12. click next on the "before starting" page
13. click launch on the "Step 1 - check server" page

### Expected behaviour
Finish the upgrade from 2.1.23 to 2.1.23.4

### Actual behaviour
The scroll animation keeps scrolling in the "Step 1 - check server" page

### Server configuration
CentOS release 6.10

Apache/2.2.15

mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

PHP 5.5.38 (cli) (built: Jul 21 2016 12:51:12)

Teampass version 2.1.23

### Client configuration
Google Chrome / Firefox / Safari

MacOS Mojave

#### Web server error log
[Fri Feb 07 16:11:54 2020] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Feb 07 16:11:54 2020] [notice] Digest: generating secret for digest authentication ...
[Fri Feb 07 16:11:54 2020] [notice] Digest: done
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysqlnd.so' - /usr/lib64/php/modules/pdo_mysqlnd.so: undefined symbol: php_pdo_register_driver in Unknown on line 0
[Fri Feb 07 16:11:54 2020] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.5.38 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Fri Feb 07 16:12:50 2020] [error] [client 192.168.10.88] File does not exist: /var/www/teampass/favicon.ico, referer: https://teampass.mydomain.com/install/upgrade.php
[Fri Feb 07 16:14:18 2020] [notice] caught SIGTERM, shutting down
[Fri Feb 07 16:14:18 2020] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Feb 07 16:14:19 2020] [notice] Digest: generating secret for digest authentication ...
[Fri Feb 07 16:14:19 2020] [notice] Digest: done
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysqlnd.so' - /usr/lib64/php/modules/pdo_mysqlnd.so: undefined symbol: php_pdo_register_driver in Unknown on line 0
[Fri Feb 07 16:14:19 2020] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.5.38 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming normal operations

[root@tp ~]# tail -f -n 30 /var/log/httpd/access_log
192.168.10.88 - - [07/Feb/2020:16:08:58 +0100] "GET / HTTP/1.1" 302 311 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0"

VM157:7 Uncaught SyntaxError: Unexpected token '<'
    at XMLHttpRequest.xhr_object.onreadystatechange (upgrade.js:49)
xhr_object.onreadystatechange @ upgrade.js:49
XMLHttpRequest.send (async)
(anonymous) @ VM146:1
httpRequest @ upgrade.js:71
Check @ upgrade.php:82
onclick @ upgrade.php:171

**Comment by illimitati** [comment]
have the same issue but on step 4.
HTTP ERROR 500 PHP Fatal error:  Call to undefined function cryption() /var/www/teampass/install/upgrade_ajax.php on line 1899
