### ISSUE TITLE
Teampass for Android and IOS

### ISSUE THREAD

**Issue by sudip-bs** [nilsteampassnet/TeamPass#2768]
Hello,
I am running TeamPass 2.1.27.36 on my Ubuntu 18.04 server with apache as webserver and was wondering how to connect my users to the android and IOS applications?
Also, can users use browsers extension to access the application rather than web-based? if yes kindly guide me through the setup process.
Please guide me to install Teampass on android and IOS for teampass users.

Thanks,

**Comment by davkpl** [comment]
There is no usable option for that yet. The project develop very slow so I wouldn't count for it in next few years either.
