### ISSUE TITLE
+++ STATUS of the project +++

### ISSUE THREAD

**Issue by borzel** [nilsteampassnet/TeamPass#2770]
Hello ALL,

what's the status of Teampass? The Website talks about commercial support, but there is no sign of progress here at github... is it a dead project?

Can we as community continue the development?

**Comment by ortizleo** [comment]
Seems that this project is dead. @nilsteampassnet 
Version 2.1.27.36 is so slow with LDAP and make it unusable. Issue #2637 describe it.
Also, sysPass is a good alternative.

**Comment by CodeNinja1337** [comment]
The application looks great for my purposes but i need at least support for mobile which should be in V3 but this is never released...

I downloaded the V3.0.0 branch but cant even install it.. Sad as this package has lots of potential...

**Comment by giveen** [comment]
Yeah, I'm going to have to go to my boss and let him know that we need to pursue a different project as the development on this has died and there is several vulnerabilities in this project that have not been addressed.

**Comment by PiotrIr** [comment]
I love teampass, the way how it is designed, how does it work. Sadly the project seems to be dead ;-( But I understand - no profits, no reason to continue development....

**Comment by poddmo** [comment]
Hi Nils,
This is the team password manager the open source world needs. We really admire your work over the years on this. I can't help but think that you need more hands to clear up all the open issues. I'm sorry I can't help directly, but might I suggest you reach out to everyone that has offered a pull request and ask them to help triage the issues queue? The pull requesters are already across the code style and shown an interest in helping. It would be great to see your vision and hard work evolve into a flourishing community project.
Kind regards and thanks

**Comment by giveen** [comment]
@poddmo To be frank, this project is more than likely dead. I suspect that the dev is either way to busy with his work, or......since he is in France, possibly loss his life.

**Comment by julian70400** [comment]
Why he would loss his life because of living in France ? :D I do, and still alive and do not understand why I sould'nt.

Well, is another similare project or fork ?

**Comment by giveen** [comment]
You musn't be paying attention @julian70400 that there is a global pandemic going on right now. 29,000 have died in France.

**Comment by borzel** [comment]
It not dead: https://github.com/nilsteampassnet/TeamPass/tree/development

**Comment by Emi94** [comment]
@borzel I think you meant this: https://github.com/nilsteampassnet/TeamPass/tree/teampass_3.0 (last commit is 29 Nov 2020)

The last commit on development branch is from 18 Aug 2019.
