### ISSUE TITLE
Email Test Unsuccessful

### ISSUE THREAD

**Issue by donpakundo** [nilsteampassnet/TeamPass#2789]
Hi sirs/maams,

Can somebody please help me, I can't send test email. Encountering error "Email test unsuccessful. Verify your settings (did you set your user account email address?)  undefined"

![image](https://user-images.githubusercontent.com/66285678/84670449-bb257b00-af58-11ea-9849-52dc0ee6cb37.png) 

But I have already set account email address

![image](https://user-images.githubusercontent.com/66285678/84670874-40a92b00-af59-11ea-8685-344983ab71bb.png)

I have installed my TeamPass in Centos7. Do I need to install anything else in my Centos7 so that email could work? If yes, can you please help to give me instructions/configuration. Thank you.

**Comment by doubledoze** [comment]
Hi ! I have the same problem with same error... And I don't have solution.

**Comment by phil4096** [comment]
For a normal personal gmail account, both the "mail server username" and "from email address" will need to be your gmail email address.  Google (nor any public smtp server) will not send emails as any other user.  Google is probably rejecting this.

**Comment by iqbaltkj** [comment]
@phil4096 Thanks, now i am able to send email using sendgrip.
