### ISSUE TITLE
Some folders added via API having 0 as nleft and nright values.

### ISSUE THREAD

**Issue by lomiranda** [nilsteampassnet/TeamPass#2797]
### Steps to reproduce
1. Add hundreds of folders via API

### Expected behaviour
All folders should be added correctly.

### Actual behaviour
Some folders are added with 0 as values on both nleft and nright fields. Every folder added after the first with this issue have its path messed up.

### Server configuration
**Operating system**:
CentOS Linux release 7.8.2003 (Core)

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.2.30

**Teampass version:** 
2.1.27.36

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/4899232/tp.config.zip)

**Updated from an older Teampass or fresh install:**
Fresh install.

**IMPORTANT:**
I have added some functions on the functions.php to get the path tree of a folder, so I could import the folders from remote Teampass to the "Main Teampass". It worked well until we passed 1.000 folders.

**Comment by felipe2606** [comment]
Good Morning,
I faced the same problem when I changed the **/teampass/includes/libraries/Tree/NestedTree/NestedTree.php** line 426 by adding "mysqli_query ($ link, $ query, MYSQLI_ASYNC);". After removing the MYSQLI_ASYNC the Teampass starts to work correctly.
