### ISSUE TITLE
Stuck at "Please Identify yourself" for most, Working fine on 2 PC's

### ISSUE THREAD

**Issue by Iwan-sr** [nilsteampassnet/TeamPass#2802]
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/4962063/tp.config.php.txt)

### Steps to reproduce
1. Teampass configured with ldap 
2. Team has been using a while
3. 

### Expected behaviour
Users should be able to login 

### Actual behaviour
When login in we get It is stuck at "Please identify yourself" 
From 2 PC's it is possible to log in using multiple browsers. The rest of the pc's in the netwerk are not able to log into teampass. 

### Server configuration
Centos 7
Apache 2.4.6
Mariadb 5.6
PHP 5.6
TeamPass 2.1.27.36

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
Chrome, Brave, firefox

Windows 10 pro

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by winnerccie** [comment]
hi，my friend，do you  slove this question now？ i meet this question as you and i install by docker
