### ISSUE TITLE
Unable to complete server checks

### ISSUE THREAD

**Issue by UmairAliShah** [nilsteampassnet/TeamPass#2804]
### Steps to reproduce
1. Launch Amazon Linux 2 server, install LAMP (Apache/httpd, Mysql, PHP)
2. Access http://machine_ip/TeamPass/install/install.php
3. Start installation

### Expected behavior
Server Checks should be passed as I have installed the latest PHP version 7.2

### Actual behaviour
Servers Check are failed and not proceeded for further configurations, facing an error **[ERROR] Answer from server is empty**

### Server configuration
**Operating system**:
Amazon Linux AMI 2

**Web server:**
Apache/2.4.43 ()

**Database:**
10.2.10-MariaDB

**PHP version:**
PHP 7.2.31

**Teampass version:** 
master branch

### Client configuration
**Browser:**
Chrome

#### Web server error log
```
[29/Jul/2020:09:25:32 +0000] "POST /TeamPass/install/install.queries.php HTTP/1.1" 500 - "machine_DNS/TeamPass/install/install.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
```

I have installed the latest PHP version and all extensions that are required but server checks are unable to pass, facing issue on browser **[ERROR] Answer from server is empty** 
The exact apache logs are shared above.

![Screenshot from 2020-07-29 14-53-33](https://user-images.githubusercontent.com/29089198/88786013-6017b280-d1ab-11ea-8ae6-e85521ef347d.png)

Any Idea?

**Comment by SXI-XLayer** [comment]
I am having the same problem on a Ubuntu Server running Apache and Mysql

**Comment by algira37** [comment]
Move files to /var/www/html with    mv /TeamPass* /var/www/html/
After that:
chown -R www-data.www-data /var/www/html/

**Comment by SXI-XLayer** [comment]
Thank you.  I did manage to do this by accident and got it working.  I also had some caching issues on my browser that I had to sort out.

**Comment by algira37** [comment]
Great news!
