### ISSUE TITLE
2FA with google does not work

### ISSUE THREAD

**Issue by dbsilva84** [nilsteampassnet/TeamPass#2813]
### Steps to reproduce
1. Log in on the system
2. Enable 2 FA with google
3. I send the e-mail message with the link to open 2FA code
4. I receive a blank link on the e-mail and I can't login using 2FA
5. I also enable the option to the user can reset the code and I have the same behavior.

### Expected behaviour
I expected to see or to receive the code to login using 2FA with google.

### Actual behaviour
I receive an e-mail with a blank link to the code and at the logon screen I don't see any code to scan either.

### Server configuration
**Operating system**: RHEL 7.5

**Web server: Running at docker/openshift

**Database: 5.5.5-10.2.25-MariaDB-1:10.2.25+maria~bionic

**PHP version: 7.1.9

**Teampass version: 2.1.27.36

**Teampass configuration file: Running at docker/openshift

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: Google chrome

**Operating system: Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by pedroramalhoti** [comment]
I have a same problem. I receive an e-mail with a blank link to the code.

**Comment by JoaoClaudioSantos** [comment]
see  #2885

**Comment by jefersonsds** [comment]
Good afternoon

In my case, it was a problem with the variable in the file that sends the message: language in file includes/language/portuguese_br.php

In file english.php it works, in file /portuguese_br.php has error.

I changed the line in includes/language/portuguese br.php:
/** 'email_ga_text' => 'Hello<br><br>Please click on this <a href=\'#link#\'>LINK</a> and scan it with the Google Authenticator app to get your OTP credential for Teampass.<br /><br />Greetings! ', **/

and replaced with:
'email_ga_text' => 'Hello,<br><br>This is a generated email from Teampass passwords manager.<br><br>Your administrator is expecting you to use TwoFactor authentication to get connected to Teampass.<br>For your first connection to Teampass with TwoFactor, please use the code you will find below in the "Identication code" field:<br><br>----------------------<br>#2FACode#<br>----------------------<br><br>You will then have the opportunity to set up your one-time credentials for Teampass password manager.<br><br>Greetings',

and it worked
