### ISSUE TITLE
2.1.23 upgrade

### ISSUE THREAD

**Issue by kast88x** [nilsteampassnet/TeamPass#2817]
i have 2.1.23 teampass version
how to upgrade it to 2.1.27?
in upgrade manual in first i need to upgrade to 2.1.23.4 version but i don't see this version on github. 
there is only the earliest version 2.1.25.2 after 2.1.23

**Comment by BorjaCandela** [comment]
Check this page

https://github.com/nilsteampassnet/TeamPass/tags?after=2.1.24.3

**Comment by kast88x** [comment]
thanks

downloaded archive 2.1.23.4
performed the operations as indicated in this paragraph https://teampass.readthedocs.io/en/latest/install/upgrade/#upgrade-to-21234
overwritten my working directory 2.1.23 with files from 2.1.23.4
then i go to the update page
press launch button and after that the update gets stuck at "Step 1 - Check server"
a load spinner appears and nothing happens

there are no errors in the httpd error.log 

permissions on the teampass direcory set to chmod 777

php 5.3
mysql 5.6

**Comment by BorjaCandela** [comment]
Im having the same issue with the upgrade from 2.1.20 to 2.1.21
Also the update to 2.1.18 to 2.1.20 gives me an error 500 with blank page

**Comment by tsingletonacic** [comment]
> thanks
> 
> downloaded archive 2.1.23.4
> performed the operations as indicated in this paragraph https://teampass.readthedocs.io/en/latest/install/upgrade/#upgrade-to-21234
> overwritten my working directory 2.1.23 with files from 2.1.23.4
> then i go to the update page
> press launch button and after that the update gets stuck at "Step 1 - Check server"
> a load spinner appears and nothing happens
> 
> there are no errors in the httpd error.log
> 
> permissions on the teampass direcory set to chmod 777
> 
> teampass in docker container
> centos 6.9
> php 5.3
> mysql 5.6

I am also encountering the issue

If I check the browser log, I see this 

VM31:6 Uncaught SyntaxError: Unexpected token '<'
    at XMLHttpRequest.xhr_object.onreadystatechange (upgrade.js:49)
xhr_object.onreadystatechange @ upgrade.js:50
XMLHttpRequest.send (async)
httpRequest @ upgrade.js:72
Check @ upgrade.php:82
onclick @ upgrade.php:171

xhr_object.responseText 
[responseText.txt](https://github.com/nilsteampassnet/TeamPass/files/5283155/responseText.txt)
content in attach
