### ISSUE TITLE
ùpgrade error, upgrade_run_final.php file missing

### ISSUE THREAD

**Issue by bdonfouet** [nilsteampassnet/TeamPass#2818]
### Steps to reproduce
1. download the version 3 from the teampass_3.0 branch 
2.unzip the package and begin the upgrade

### Expected behaviour
teampass 2.1.27 should upgrade to teampass 3.0

### Actual behaviour
the upgrade process stuck on "upgrade_run_final.php - Loop #1 is now running....".
and that file don't exist in the teampass_3.0 branch.
Apache error.log file also show that the file can'z be found!

### Server configuration
**Operating system: debian 9.13

**Web server: Apache 2.4.25

**Database:mariadb 10.5.5

**PHP version: 7.4.10

**Teampass version: 2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install: updated from an older teampass
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: firefox

**Operating system:ubuntu 20.04

#### Web server error 
```
[php7:error] [pid 11476] [client x.x.x.x:52370] script '/var/www/html/clone-teampass/install/upgrade_run_final.php' not found or unable to stat, referer: https://myreverse_proxy.com/clone-teampass/install/upgrade.php
```

![teampass3_upgrade_error](https://user-images.githubusercontent.com/7920931/95018660-7c2f4880-0661-11eb-9f91-cdff199f51e5.png)

[teampass_tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/5323427/teampass_tp.config.txt)

**Comment by bdonfouet** [comment]
hi to all,
any hint to solve this?

regards

**Comment by jmechalas** [comment]
upgrade_run_final.php is in the master branch, though I had to add:

```
require_once 'tp.functions.php';
require_once 'libs/aesctr.php';
```

To get it to run. Not that it worked, but it's one step closer than I was.

**Comment by m4x91** [comment]
Hello @nilsteampassnet 

Same problem on upgrade to 3.0.0.7 (fresh june install) to 3.0.0.8 ( Ubuntu 20.04 -- MariaDB 10.3.29 -- PHP7.4.3 )

PHP error : script '/var/www/html/teampass/install/upgrade_run_final.php' not found or unable to stat, referer: https://IP/teampass/install/upgrade.php

Try with upgrade_run_final.php file on master branch but not working

Uncaught Error: Call to undefined function defuse_return_decrypted() in /var/www/html/teampass/install/upgrade_run_final.php:47\nStack trace:\n#0 {main}\n  thrown in /var/www/html/teampass/install/upgrade_run_final.php on line 47, referer: https://IP/teampass/install/upgrade.php

Merci d'avance :)

**Comment by filisteus** [comment]
There is no way to update teampass installations have to start from scratch? I have a teampass 2.1.27.36 where passwords don't appear
