### ISSUE TITLE
[3.0.0.0] Table 'teampass_users' doesn't exist

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2826]
### Steps to reproduce
1. Fresh Installation of 3.0.0.0

### Expected behaviour
See Login page

### Actual behaviour
Empty screen with error : Table 'teampass.teampass_users' doesn't exist

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mysql  Ver 14.14 Distrib 5.7.32
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.0
**Teampass configuration file:**
Fresh Install
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://127.0.0.1/teampass',
    'favicon' => 'http://127.0.0.1/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://127.0.0.1/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.0',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1602189881',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '4LC8mQqeyTEAXYgkLgDU4RqEfprXCZMAGHtk74Ky',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 Ent 20H4
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Well ... new install on my side and no issue.
The only difference I see is that I'm on a windows server and you on Linux.
No error during installation ?

**Comment by reginfo** [comment]
No errors as I can see. 

If I try to manually execute sql query from phpmyadmin for creating teampass_users I get an error:
```
#1101 - BLOB, TEXT, GEOMETRY or JSON column 'public_key' can't have a default value
```
If I make changes to 
```
`public_key` TEXT NOT NULL,
```
Then I receive next error:
```
#1101 - BLOB, TEXT, GEOMETRY or JSON column 'private_key' can't have a default value
```
Only after table can be created. 

After Installation rerun, no entrees are in teampass_users table.

**Comment by nilsteampassnet** [comment]
Interesting. So I believe it's more related to mysql setup.
Would really be interesting to know option could lead to this warning.
On my side, I don't perform any change and I use MariaDB.

**Comment by reginfo** [comment]
Hmmm.

I just reinstall all from scratch (New VM) using MariaDB. The same behaviour. 
```
Table 'teampass.teampass_users' doesn't exist
```

**Comment by nilsteampassnet** [comment]
What are the options defined in your `sql-mode` parameter in file `my.ini` or `my.cnf` ?

**Comment by reginfo** [comment]
Is it what you are asking about?
I didn`t find anything related to sql-mode in all files.

```
root@teampass31:/etc/mysql# cat my.cnf
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.

#
# This group is read both both by the client and the server
# use it for options that affect everything
#
[client-server]

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```
```
root@teampass31:/etc/mysql# cat mariadb.cnf
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.

#
# This group is read both both by the client and the server
# use it for options that affect everything
#
[client-server]

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```

```MariaDB [(none)]> SHOW VARIABLES LIKE 'sql_mode';
+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| sql_mode      | NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------+
1 row in set (0.00 sec)
```
```
root@teampass31:/etc/mysql# ls -lah
total 32K
drwxr-xr-x  4 root root 4.0K Nov  8 09:03 .
drwxr-xr-x 97 root root 4.0K Nov  8 08:55 ..
drwxr-xr-x  2 root root 4.0K Nov  8 09:09 conf.d
-rw-------  1 root root  277 Nov  8 08:48 debian.cnf
-rwxr-xr-x  1 root root 1.5K Oct 12 16:24 debian-start
-rw-r--r--  1 root root  869 Oct 12 16:24 mariadb.cnf
drwxr-xr-x  2 root root 4.0K Nov  8 09:09 mariadb.conf.d
lrwxrwxrwx  1 root root   24 Nov  8 08:47 my.cnf -> /etc/alternatives/my.cnf
-rw-r--r--  1 root root  839 Aug  3  2016 my.cnf.fallback
root@teampass31:/etc/mysql# ls -lah conf.d/
total 16K
drwxr-xr-x 2 root root 4.0K Nov  8 09:09 .
drwxr-xr-x 4 root root 4.0K Nov  8 09:03 ..
-rw-r--r-- 1 root root    8 Aug  3  2016 mysql.cnf
-rw-r--r-- 1 root root   55 Aug  3  2016 mysqldump.cnf
root@teampass31:/etc/mysql# ls -lah mariadb.conf.d/
total 24K
drwxr-xr-x 2 root root 4.0K Nov  8 09:09 .
drwxr-xr-x 4 root root 4.0K Nov  8 09:03 ..
-rw-r--r-- 1 root root  733 Oct 12 16:24 50-client.cnf
-rw-r--r-- 1 root root  336 Oct 12 16:24 50-mysql-clients.cnf
-rw-r--r-- 1 root root 1.1K Oct 12 16:24 50-mysqld_safe.cnf
-rw-r--r-- 1 root root 3.7K Oct 12 16:24 50-server.cnf
```

**Comment by nilsteampassnet** [comment]
Did a change in the structure of the table to prevent the usage of default value on TEXT fields.
Can you install it to check please?

**Comment by reginfo** [comment]
I have checked, now it s working. 
Thanks! 

About new version, there is some changes in User generating process? 
When I create new user, it receives new e-mail with login details, but without password.
![Capture](https://user-images.githubusercontent.com/4628571/98462586-fcdfe800-21bd-11eb-97bd-ccf52951d0aa.PNG)
So user can`t login. 
Admin also couldn`t affect this password creation, only to reset it to Random and user will not remember it. 

I will use LDAP, but I will test it later. Just for now wanted to understand the behaviour or regular use. 

P.S. There is a typo in "Change Login Password" - 
![Capture1](https://user-images.githubusercontent.com/4628571/98462673-a4f5b100-21be-11eb-9d24-ac43db082f36.PNG)

**Comment by nilsteampassnet** [comment]
Thank you for the feedback.
I've fixed the empty password in email.

I will fix the others too ... regarding LDAP, it's has been a while I've coded it and didn't yet checked it.
