### ISSUE TITLE
[3.0.0.2] Bug 1

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2827]
### Steps to reproduce
1.Login to Admin

### Expected behaviour 
Web Page opens

### Actual behaviour
Right Bottom corner show error.
![Error Login](https://user-images.githubusercontent.com/4628571/98570002-9e009880-22bb-11eb-9885-15807ab7b5c3.jpg)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Should be fixed.

Thank you 👍
