### ISSUE TITLE
[3.0.0.2] Bug 2 - Email

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2828]
### Steps to reproduce
1.Login to Admin
2. Select Setting -> Email
3. Change "SMTP security type" to "None"

### Expected behaviour 
Setting is saved

### Actual behaviour
Setting is not saved after refresh. It stays as TLS.

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Should be fixed. Please reopen if not.

Thank you 👍
