### ISSUE TITLE
[3.0.0.2] Bug 3 - Attachment

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2829]
### Steps to reproduce
1. Try to attach an attachment to item

### Expected behaviour
File is attached

### Actual behaviour
Error
![Attachment](https://user-images.githubusercontent.com/4628571/98571961-c093b100-22bd-11eb-94f2-217ade4bc17c.jpg)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

#### Web server error log
```
[Mon Nov 09 19:02:37.273290 2020] [php7:error] [pid 59114] [client xx.xx.xx.xx:1561] PHP Fatal error:  Uncaught Error: Call to undefined function handleUploadError() in /var/www/html/teampass/sources/upload.attachments.php:58\nStack trace:\n#0 {main}\n  thrown in /var/www/html/teampass/sources/upload.attachments.php on line 58, referer: http://xx.xx.xx.xx/teampass/index.php?page=items
[Mon Nov 09 19:02:37.333469 2020] [php7:error] [pid 59119] [client xx.xx.xx.xx:1562] PHP Fatal error:  Uncaught Error: Call to undefined function handleUploadError() in /var/www/html/teampass/sources/upload.attachments.php:58\nStack trace:\n#0 {main}\n  thrown in /var/www/html/teampass/sources/upload.attachments.php on line 58, referer: http://xx.xx.xx.xx/teampass/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Uncaught TypeError: ((k.event.special[o.origType] || {}).handle || o.handler).apply is not a function
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.v.handle (jquery.min.js:2)

Uncaught TypeError: Cannot read property 'menu' of undefined
    at HTMLInputElement.<anonymous> (index.php?page=items:5088)
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.v.handle (jquery.min.js:2)

Failed to load resource: net::ERR_EMPTY_RESPONSE

Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (index.php?page=items:6881)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)

POST http://xx.xx.xx.xx/teampass/sources/upload.attachments.php net::ERR_EMPTY_RESPONSE
plupload.full.min.js:15 
```

**Comment by nilsteampassnet** [comment]
The 2 errors in the Web server error log are showing that there is no available session.
The thing is WHY?
In my case, it works smoothly so I believe something is not enough robust somewhere.
Could you post here the result of the console once the file is tried to be uploaded?

**Comment by reginfo** [comment]
This one? 
[1604946917502 - 2.log](https://github.com/nilsteampassnet/TeamPass/files/5512616/1604946917502.-.2.log)

**Comment by nilsteampassnet** [comment]
@reginfo, Can you perform a try with latest 3.0.0.3?
It doesn't solve the issue but should remove the 2 fatal errors observed in Web server error log.
We could then have a better feedback related to the issue you are facing.

**Comment by reginfo** [comment]
Hi, 

Installed latest 3.0.0.4. 
Seems problem is fixed. I can attach an attachment. 

Only when I open new item from console I receive next error:
```
index.php?page=items:6873 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (index.php?page=items:6873)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
(anonymous) @ index.php?page=items:6873
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
showDetailsStep2 @ index.php?page=items:6860
(anonymous) @ index.php?page=items:6816
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
Details @ index.php?page=items:6354
(anonymous) @ index.php?page=items:4245
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Are you also interesting in console error outputs?

**Comment by nilsteampassnet** [comment]
Good news.

> Are you also interesting in console error outputs?
Yes I am.

Thank you
