### ISSUE TITLE
[3.0.0.2] Bug 4 - Type in invitation email link

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2830]
### Steps to reproduce
1.Create new user

### Expected behaviour 
New user receives a new e-mail with correct link in 

### Actual behaviour
Welcome email link is incorrect, opens browser without page.
![Link Err](https://user-images.githubusercontent.com/4628571/98573966-06517900-22c0-11eb-95a3-16f541423bcd.jpg)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Should be fixed. Please reopen if not.

Thank you 👍
