### ISSUE TITLE
[3.0.0.2] Bug 5 - Popup after user deleting

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2832]
### Steps to reproduce
1.Login to Admin
2. Disable User
3. Delete User

### Expected behaviour 
User is deleted

### Actual behaviour
User is deleted but popup still continue to apear for delete aproval
![User Delete](https://user-images.githubusercontent.com/4628571/98575790-4a457d80-22c2-11eb-8489-f06468e44cde.PNG)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.2

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Should be fixed. Please reopen if not.

Thank you 👍
