### ISSUE TITLE
Cannot change own login password

### ISSUE THREAD

**Issue by DataWorm** [nilsteampassnet/TeamPass#2833]
[
### Steps to reproduce
1. Create a new user account
2. Login to the new user account
3. Go to profile

### Expected behaviour
I expected to have an option to change the password of my newly created user. According to the (possibly outdated) documentation, I should have a list of tasks that contains the option to change the password.

### Actual behaviour
Profile shows options to change my name, profile picture etc, but there are no options available to change passwort or list executable actions...

### Server configuration
**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Teampass version:** 3.0.0.5

**Teampass configuration file:**

[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/5541840/tp.config.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Chiller2019** [comment]
Yeahr, we need this, this is very important!!!!

**Comment by nilsteampassnet** [comment]
User can now change his password.

Notice that a user authenticated through LDAP will not have this possibility.
