### ISSUE TITLE
[3.0.0.6] Style problem when creating new user

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2834]
### Steps to reproduce
1.Login to Admin
2. Try to create new user

### Actual behavior
Under "Create new folder and role called" there is square in the middle of page. 
![Capture](https://user-images.githubusercontent.com/4628571/99181432-3624d480-2737-11eb-8a39-842bffe64513.PNG)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.6

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by thiagowarwick** [comment]
Where do I set the password for a new user? Is there no "password" field when creating a new user?

**Comment by nilsteampassnet** [comment]
thank you @reginfo, it is now fixed

@thiagowarwick no password is defined by admin. It is generated and send to user by email.

**Comment by thiagowarwick** [comment]
Sorry, friend,
I was unable to send a password to a created user.

[image: image.png]

Em sáb., 21 de nov. de 2020 às 11:43, Nils Laumaillé <
notifications@github.com> escreveu:
