### ISSUE TITLE
[3.0.0.6] Console error when creating new password

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2835]
### Steps to reproduce
1.Login as user
2. Create new item
3. When password is entered and push <TAB> on keyboard there is console error

### Expected behaviour 
No error

### Actual behavior
Uncaught TypeError: ((S.event.special[o.origType] || {}).handle || o.handler).apply is not a function
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.v.handle (jquery.min.js:2)
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.6

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
In fact, it is not when you create a password.
It is an error I've seen since a long time for which I still haven't identified the root cause.
It doesn't seem to have any impact on the usability.
It happens on mouse over UI elements.
I'm still investigating ...
