### ISSUE TITLE
Strange behaviour whilst installing TeamPass 

### ISSUE THREAD

**Issue by Patron77** [nilsteampassnet/TeamPass#2836]
Hi,
I tried to install the last version of TeamPass [v.2.1.7] on a new install of a Linux system. I could not as it hangs at step2.
Increasing the max execution time limit and/or disabling that step or the session did not make any difference. [mcrypt also present. version 2.5.8 and support enabled]
So, I tried the new beta version 3 [3.0.0.6] to see if it works.
This version also stops at that stage with the 'Next' button greyed out. However, if you ignore that and just press the Start button, [again and again] then the install carries on, populates the database and finishes the job.
This is stange to me. Can you shed some light on this, please?
My system is:
Linux CentOS 7.8, Kernel 3.10.0-11 27
Php version is 7.3.24
Apache version is 2.4.6
MySql version is  8.0.22 
[NB.: I have not tested this installation as yet, however. So, I cannot tell you if everything included in this beta version is actually behaving as it should...]
Thanks.

**Comment by nilsteampassnet** [comment]
THere must be some errors in the console.
Can you share?

**Comment by Patron77** [comment]
Hi,
Sorry, do not understand what you mean by 'errors in the console.' This is a desktop pc with the above system.
Also, what would you like me to add? Share what?
Please tell me what you need specifically.
Thanks.

**Comment by timonych** [comment]
@Patron77 
You should open nginx error.log to find the problem.
As for me - I have installed TeamPass on Alpine Linux with Nginx and PHP7-FPM. I have a such problem. Workaround is install additional php7-session and php7-mbstring.

**Comment by reginfo** [comment]
> 'errors in the console.'

In browser click "CTRL+SHIFT+i". it will open developer options. 
Choose console and see error output. 
![2020-11-22_21h12_51](https://user-images.githubusercontent.com/4628571/99914644-88ea2780-2d07-11eb-821b-f09602907cd7.png)
