### ISSUE TITLE
[v3] User Encryption problem 

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#2837]
### Steps to reproduce
1.Fresh Install
2.Log in as admin
3.Configure Emails
4.Edit admin data (Name, Last Name, email address, select default Roles) -> Submit
5.On admin email sends an email with temporary encryption code. 
![Temporary Enc code](https://user-images.githubusercontent.com/4628571/99998774-da59eb80-2dc7-11eb-85eb-4753b6306402.PNG)
6.Exit from admin account
7. Login as  admin
8. We see new message "Your attention is required". We asked to use current password and encryption key from email
![Capture](https://user-images.githubusercontent.com/4628571/99998893-0b3a2080-2dc8-11eb-9323-6e793382aca4.PNG)
9. Enter Current Password and encryption key -> Launch

### Expected behaviour
Error, that password is incorrect
![2020-11-23_20h12_16](https://user-images.githubusercontent.com/4628571/99999177-6ec44e00-2dc8-11eb-8fc1-a2d8c5770637.png)

### Actual behaviour
need to be all ok

But If I enter in "Your temporary encryption code" current password - than I receive DONE. 
![2020-11-23_20h13_58](https://user-images.githubusercontent.com/4628571/99999192-771c8900-2dc8-11eb-914a-f2f914b779c3.png)
 
### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB
**PHP version:**
PHP 7.2.24
**Teampass version:** 
3.0.0.6

**Updated from an older Teampass or fresh install:**
Fresh Install

### Client configuration
**Browser:**
EDGE
**Operating system:**
Windows 10 20H2

**Comment by nilsteampassnet** [comment]
Interresting ... and fixed.
I'm now considering that an admin cannot access items by any mean.
THis role is just an administrative one.
