### ISSUE TITLE
Export to PDF or CSV enabled but there is no possibility to export in the item tree menu

### ISSUE THREAD

**Issue by pacotinto** [nilsteampassnet/TeamPass#2839]
### Steps to reproduce
1. Logged in as Administrator
2. Menu Options
3. Option Export to PDF or CSV enabled set to YES

### Expected behaviour
In the item tree menu should be a possibility to export items

### Actual behaviour
There is no menu

### Server configuration
**Operating system**: Ubuntu 16.04.7 LTS

**Web server:** Apache/2.4.46 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.32, for Linux (x86_64)

**PHP version:** PHP Version 7.4.12

**Teampass version:** 3.0.0.6

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/5588248/tp.config.txt)

**Updated from an older Teampass or fresh install:** fresh installation

### Client configuration
**Browser:** Firefox Browser 78.5.0esr (32-Bit) as well as Google Chrome 87.0.4280.66 (64-Bit)

**Operating system:** Windows10

#### Log from the web-browser developer console (CTRL + SHIFT + i)

**Comment by nilsteampassnet** [comment]
An admin cannot import or export data.
This is reserved to users.
Nevertheless, I identified an error at this level and fixed it.

**Comment by pacotinto** [comment]
THANK YOU VERY MUCH for the prompt handling!!!!
