### ISSUE TITLE
can't found the option to import file  in the folder menu after installation

### ISSUE THREAD

**Issue by fafadi** [nilsteampassnet/TeamPass#2844]
Hello i have a problem to import file in the app
I enabled the option to import CSV and Keepass from admin settings page and 
I do not get the option to import in the folder menu. 
when i try to import, there's no import option as seen on the documentation
1.Fresh install and Login as user
2.Create users with diferent permissions
3.try to import

### Expected behaviour

System let's you upload a csv file or another type of file 

### Actual behaviour

no IMPORT option anywhere 
**Operating system**: Centos 8

**Web server:** Apache/2.4.6 

**Database:** mysql  Ver 15.1 Distrib 5.5.68-MariaDB

**PHP version:** PHP 7.2.34 

**Teampass version:** 3.0.0.5

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 

**Operating system:** Windows and Linux

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Similar to #2839

**Comment by fafadi** [comment]
yes i had followed the same steps on the documentation ! i disabled maintenance mode ! i have created a standard  user but when i am trying to log on i get the message "credentials do not correspond "
