### ISSUE TITLE
Getting error when trying to upgrade (DB part)

### ISSUE THREAD

**Issue by whositwhatnow** [nilsteampassnet/TeamPass#2848]
I am getting an error when attempting to do an upgrade using the upgrade.php method. 

ERROR: 

07:44:36 - ERROR: An error appears when adding field Encrypted to table OTV! BLOB, TEXT, GEOMETRY or JSON column 'encrypted' can't have a default value!
07:44:36 - upgrade_run_3.0.0.php - Loop #1 

MySQL 5.7.32
Teampass 3.0.0.7

**Comment by JabadoI** [comment]
Did you ever find how to fix this? I am having the same issue.
