### ISSUE TITLE
Can't found user password for loggin 

### ISSUE THREAD

**Issue by fafadi** [nilsteampassnet/TeamPass#2850]
### Steps to reproduce
1.Login as admin
2.Create a new user
3.Try to log in 

### Expected behaviour
Tell us what should happen
Admin can generated user passerword and use it for login 
Actual behaviour
i can create user but i can not log in
Operating system: Centos 8

Web server: Apache/2.4.6

Database: mysql Ver 15.1 Distrib 5.5.68-MariaDB

PHP version: PHP 7.2.34

Teampass version: 3.0.0.5

Teampass configuration file:

Updated from an older Teampass or fresh install:
PLEASE attach to this issue the file /includes/config/tp.config.php.

Client configuration
Browser: Chrome

Operating system: Windows and Linux

Logs
Web server error log
Insert your webserver log here
Log from the web-browser developer console (CTRL + SHIFT + i)
Insert the log here and especially the answer of the query that failed.

**Comment by sephra-dev** [comment]
I had a similar Issue, you may look into my post: https://github.com/nilsteampassnet/TeamPass/issues/2847
