### ISSUE TITLE
New user gets full access on his first session opening

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#2852]
### Steps to reproduce
1. set authentication to LDAP
2. open a session for a new user that does not have any allowed right anywhere

### Expected behaviour
The user has a blank password / some password (depending on the rights allowed)

### Actual behaviour
the new user has a view on folders (without the names, but with a numeric code instead) and entries he should not be able to have. (like domain admin account). If he disconnects / reconnects he can't see them anymore.

### Server configuration
**Operating system**: Debian 7

**Web server:** Apache2

**Database:** Mysql 5.5.38

**PHP version:** 5.5.38

**Teampass version:**  2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox

**Operating system:** windows 10

#### Web server error log
(no error within logs)

[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/5643153/tp.config.php.zip)
![2020-12-04 14_44_36-Teampass](https://user-images.githubusercontent.com/56827787/101172057-f15ad200-3640-11eb-8fae-fbbdb5bea039.jpg)

**Comment by sephra-dev** [comment]
I also have this issue, A new user can see every entry. No passwords are shown but everything else like details, URLs, login user and even attachments...
