### ISSUE TITLE
Teampass gets stuck on upgrade_run_defuse_for_pwds.php with 500 error

### ISSUE THREAD

**Issue by edschr** [nilsteampassnet/TeamPass#2855]
### Steps to reproduce
1. Upgrade from 2.1.26.17 to 2.1.27.36 hangs at **upgrade_run_defuse_for_pwds.php - Loop #1 is now running ...** .

### Expected behaviour
Upgrade completion

### Actual behaviour
hangs at **upgrade_run_defuse_for_pwds.php - Loop #1 is now running ...** 
jquery.min.js:18 POST https://tp.<redacted>/TeamPass-2.1.26.14/install/upgrade_run_defuse_for_pwds.php 500 (Internal Server Error)
[{"finish":"1" , "error":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2"}]

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
mysql 5.7
**PHP version:**
php 5.6
**Teampass version:** 
2.1.26.17

**Teampass configuration file:**
tp.config.php
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://tp.<redacted>/,
    'favicon' => 'https://tp.<redacted>/favico.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'url_to_upload_folder' => 'https://tp.<redacted>/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://tp.<redacted>/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '60',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.26',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '10',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://tp/logo_teampass.jpg',
    'custom_login_text' => 'Monitored Access',
    'default_language' => 'english',
    'send_stats' => 'false',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.my_domain.com',
    'email_smtp_auth' => 'false',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => 'none',
    'email_server_url' => 'http://<redacted>',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '45',
    '2factors_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '1',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '0.1',
    'default_session_expiration_time' => '60',
    'duo' => '1',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0'
);
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10

#### Web server error log
nothing showing in the error log
Insert your webserver log here
/var/log/apache2/access.log
[10/Dec/2020:19:27:24 +0000] "POST /TeamPass-2.1.26.14/install/upgrade_run_defuse_for_pwds.php HTTP/1.1" 500 351 "https://tp.<redacted>/TeamPass-2.1.26.14/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
jquery.min.js:18 POST https://tp.<redacted>/TeamPass-2.1.26.14/install/upgrade_run_defuse_for_pwds.php 500 (Internal Server Error)
[{"finish":"1" , "error":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2"}]

**Comment by geysonsantana** [comment]
Hi. Execute the following commands to make sure that the permissions are be fine:

# chmod -R 755 /var/www/html/teampass
# chown -R apache:apache /var/www/html/teampass

...and re-launch the upgrade.

**Comment by edschr** [comment]
ok this has been done, but still getting the 500 error. Could it be to do with the apache2/php configuration?

**Comment by edschr** [comment]
I have tried with an earlier version and it installs, however I cannot see the passwords, only for the logged in user.
