### ISSUE TITLE
user w/o rights can delete, ... the tree root

### ISSUE THREAD

**Issue by ghost** [nilsteampassnet/TeamPass#288]
user w/o rights can delete, ... the tree root

the patch would be to disable all id=0 dropdown values 
in items.php

all <option value="0">---</option> 
to <option value="0"  disabled="disabled">---</option>

and 

all <option value="0">-choisir-</option>
to <option value="0"  disabled="disabled">-choisir-</option>

**Comment by atelopus76** [comment]
I managed recreate this (or similar) by misstake while testing 2.1.22 a few weeks ago.

A regular user with private folders activated. Had issues with creating private keys in the top level of private folder and in frustration/misstake the user tried to delete the root level of their private key. It resulted in that all keys in the private folder disapeared, but also all keys in the real teampass DB. The user should not had rights to do that. User was only able to create keys in subfolders.

I still have that VM available for a few days if you are interested in looking into it. It's not possible to reach the server over internet though.

Ubuntu 14.04.1 LTS
Apache/2.4.7 (Ubuntu)
mysql: 5.5.43-0ubuntu0.14.04.1
php 5.5.23-1+deb.sury.org~trusty+2 (cli) (built: Mar 24 2015 10:58:52)
------ 
 
I have installed a new clean server with Ubuntu 14.04.2 LTS and a clean install of Teampass 2.1.23 and will test it to see if I can recreate the issue there.
