### ISSUE TITLE
version 3.0.0.7 /  You are not allowed to do that!

### ISSUE THREAD

**Issue by siam-tcc** [nilsteampassnet/TeamPass#2882]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

When I enabled google2step funcstion and then asked the user to signin and click to send the QR Ccode, I received a message like this "Coution .. You are not allowed to do that!".

after I created new user then click "Email Google Authentication User" its was show "Coution .. You are not allowed to do that!"
Using admin as the creator of the new user.

what shoud i do ?

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29
**Database:**
5.7.33
**PHP version:**
7.2
**Teampass version:** 
3.0.0.7
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
google chrome
**Operating system:**
windows10

#### Web server error log
```
Insert your webserver log here
```
PHP Warning:  setcookie() expects parameter 3 to be integer, array given in /var/www/html/teampass/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 372,

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by amelentjev** [comment]
Quick fix: in /sources/main.queries.php at line 415 change FILTER_SANITIZE_NUMBER_INT to FILTER_SANITIZE_STRING
