### ISSUE TITLE
2FA Google Authenticator error QRCODE

### ISSUE THREAD

**Issue by brunoaumaxs** [nilsteampassnet/TeamPass#2895]
good evening!
I deployed Teampass authenticated with AD but I can't activate 2FA google.
I enable the configuration, but when I receive the email the link is empty, I can't generate the QRCode to enable it in my google authenticator

![image](https://user-images.githubusercontent.com/60828751/111708799-42c05300-8825-11eb-8e52-1626140fe9ca.png)

![image](https://user-images.githubusercontent.com/60828751/111708909-7a2eff80-8825-11eb-84d4-77663416b31a.png)

![image](https://user-images.githubusercontent.com/60828751/111708992-9a5ebe80-8825-11eb-8c32-66fa4f0d8760.png)

**Comment by JoaoClaudioSantos** [comment]
See  #2885
