### ISSUE TITLE
Can't Copy Passwords

### ISSUE THREAD

**Issue by Dreadlocke12** [nilsteampassnet/TeamPass#2900]
I recently installed (for testing purpose) the beta Teampass Version 3.0.0.7 and it seems I can't copy any passwords or view them after creating a new entry. It is possible to copy usernames but not passwords.
Host System is Ubuntu Server 20.04.2 LTS.

**Comment by Dreadlocke12** [comment]
According to the Webconsole from Firefox the issue is in the index file: 
![Bildschirmfoto von 2021-04-03 21-37-37](https://user-images.githubusercontent.com/56894437/113489549-2f6be380-94c5-11eb-84c9-c81fce6febbf.png)

**Comment by nilsteampassnet** [comment]
How do you reproduce please?
THis?
![image](https://user-images.githubusercontent.com/1197546/121665302-a23aa180-caa8-11eb-97a8-4fa746c315fa.png)
or this?
![image](https://user-images.githubusercontent.com/1197546/121665670-b7173500-caa8-11eb-8e15-556af77447cc.png)
or where?

Tested on current commit and no issue on my side.
