### ISSUE TITLE
teampass30

### ISSUE THREAD

**Issue by eduardomarcial** [nilsteampassnet/TeamPass#2902]
hello,
Dockerfile >>> git clone gitlab.... not work.

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by C-Duv** [comment]
@eduardomarcial Would you care explaining the issue with clear steps and results?
