### ISSUE TITLE
LDAP User Not Showing In User List

### ISSUE THREAD

**Issue by dbrossart** [nilsteampassnet/TeamPass#2904]
Hello,

I have one LDAP user that is able to login, but their account doesn't show up under the user list like the others do. I'm unable to adjust permission due to this. If I try to create the user, it says there is a duplicate, but yet I still am unable to view the user anywhere. 

Has anyone seen this before? I'm quite unfamiliar with troubleshooting this software. This was tossed on our department after we had a downsizing, so any help is greatly appreciated.

**Comment by TH3UNKN0WN-1337** [comment]
Having the same issue. For some reason all LDAP-Users are not manageable anymore. The administrator can't see any user to edit. We're using latest 2.X.X version. It was running fine for a couple of month, but this issue is a critical one, so we switched back to Passwordsafe.
