### ISSUE TITLE
unable to see password item without a blank tab with "caution"

### ISSUE THREAD

**Issue by fafadi** [nilsteampassnet/TeamPass#2906]
Steps to reproduce
1. i have create   some folders and add new items with password
2. i have give to him the rights to access to the folders
  i tried to view the characteristic of the items but i obtain a blanc tab with close
3. i want to upload file and see all the folders

Actual behaviour
after login as simple  user , wwhen i tried to open the informations about a item i got this error 
![Capture](https://user-images.githubusercontent.com/74589465/115042113-77cace80-9ed3-11eb-96e2-b1cd94aa1ca2.PNG)

Server configuration
Operating system: Centos 8

Web server: Apache/2.4.6

Database: mysql Ver 15.1 Distrib 5.5.68-MariaDB

PHP version: PHP 7.2.34

Teampass version: 3.0.0.7

Teampass configuration file:

Updated from an older Teampass or fresh install:
PLEASE attach to this issue the file /includes/config/tp.config.php.

Client configuration
Browser: chrome

Operating system: windows

Logs
Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nabule** [comment]
same question

**Comment by nabule** [comment]
reset user roles can see password.

**Comment by nabule** [comment]
I find the reason is "Install many times, have many same role Default"。
I delete the db and reinstall，the problem is done.
I think "cation" is the same reason.
