### ISSUE TITLE
At least one task failed - Fresh install of TeamPass 3.0.0.8

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#2911]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Should be able to proceed with installation

### Actual behaviour
At least one task failed when preparing Database

### Server configuration
**Operating system**: 
Alpine Linux (Docker Container)

**Web server:** 
Apache

**Database:** 
AWS Aurora

**PHP version:** 
php7

**Teampass version:** 
3.0.0.8

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by hitenmandalia** [comment]
No Errors in apache logs.
Tables seems to get created

**Comment by hitenmandalia** [comment]
Just for more information, i re-tried the install on 3.0.0.7 and don't get the same problem, install runs fine.  Apache logs show that it never get past the install.queries.php

172.17.0.1 - - [28/Apr/2021:17:44:25 +0000] "POST /install/install.queries.php HTTP/1.1" 200 93 "http://teampass.xxxx/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.49"
172.17.0.1 - - [28/Apr/2021:17:44:26 +0000] "GET /favicon.ico HTTP/1.1" 304 - "http://teampass.xxxx/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.49"

These are the last 2 entries in the log after which i cannot progress with the install.

**Comment by hitenmandalia** [comment]
I've tried countless fresh installs and getting the same issue.  Only happens with 3.0.0.8 but 3.0.0.7 completes fine!
To get around this, I've installed 3.0.0.7 and configured it at a basic level so it gets past the DB populating stage.  Then I have downloaded the files for 3.0.0.8, removed the install folder, and copied the tp.config.php, settings.php, and teampass-seckey.txt into the directory from the 3.0.0.7 install.

**Comment by romansad** [comment]
> I've tried countless fresh installs and getting the same issue. Only happens with 3.0.0.8 but 3.0.0.7 completes fine! To get around this, I've installed 3.0.0.7 and configured it at a basic level so it gets past the DB populating stage. Then I have downloaded the files for 3.0.0.8, removed the install folder, and copied the tp.config.php, settings.php, and teampass-seckey.txt into the directory from the 3.0.0.7 install.

Please could you tell me if when you made the change. You finalized the installation with 3.0.0.7 or when you passed the instance of the creation of the tables, you copied the files of version 3.0.0.8, in addition to consulting the installation folder that you deleted is the one of 3.0.0.8, and you copied the rest of the files or did you step on 3.0.0.7 with 3.0.0.8?
