### ISSUE TITLE
LDAP error with new install of 3.0.0.8

### ISSUE THREAD

**Issue by iamlambertr** [nilsteampassnet/TeamPass#2912]
### Steps to reproduce
1. Install 3.0.0.8
2. Configure LDAP settings 
3. try tes connection 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
Error in the apache logs:
[Mon May 03 15:45:04.298426 2021] [php7:error] [pid 32001] [client 172.22.15.17:64978] PHP Fatal error:  Uncaught Error: Interface 'LdapRecord\\LdapInterface' not found in /var/www/teampass3/includes/libraries/LdapRecord/LdapBase.php:9\nStack trace:\n#0 /var/www/teampass3/sources/ldap.queries.php(175): require_once()\n#1 {main}\n  thrown in /var/www/teampass3/includes/libraries/LdapRecord/LdapBase.php on line 9, referer: http://172.18.4.92:8080/index.php?page=ldap

### Server configuration
**Operating system**:
Ubuntu server 20.04

**Web server:**
Apache 2
**Database:**
MariaDB 10.3
**PHP version:**
7.4.3

**Teampass version:** 
3.0.0.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```[Mon May 03 15:45:04.298426 2021] [php7:error] [pid 32001] [client 172.22.15.17:64978] PHP Fatal error:  Uncaught Error: Interface 'LdapRecord\\LdapInterface' not found in /var/www/teampass3/includes/libraries/LdapRecord/LdapBase.php:9\nStack trace:\n#0 /var/www/teampass3/sources/ldap.queries.php(175): require_once()\n#1 {main}\n  thrown in /var/www/teampass3/includes/libraries/LdapRecord/LdapBase.php on line 9, referer: http://172.18.4.92:8080/index.php?page=ldap
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by iamlambertr** [comment]
Config attached. Have tried various combinations for username including with the AD Object info. 
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/6416447/tp.config.php.zip)

**Comment by hitenmandalia** [comment]
getting exact same issue with 3.0.0.8

**Comment by hitenmandalia** [comment]
Still doesn't work.  Now throwing up the following error:

[Tue Jun 29 10:00:41.598116 2021] [php7:error] [pid 755] [client 172.17.0.1:41778] PHP Fatal error:  Uncaught ErrorException: ldap_connect(): Could not create session handle: Bad parameter to an ldap routine in /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php:194\nStack trace:\n#0 [internal function]: LdapRecord\\LdapBase->LdapRecord\\{closure}()\n#1 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(194): ldap_connect()\n#2 /var/www/TeamPass/includes/libraries/LdapRecord/LdapBase.php(160): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(195): LdapRecord\\LdapBase->executeFailableOperation()\n#4 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(169): LdapRecord\\Ldap->connect()\n#5 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(141): LdapRecord\\Connection->initialize()\n#6 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(99): LdapRecord\\Connection->setLdapConnection()\n#7 /var/www/TeamPass/sources/ldap.queries.php(170): LdapRecord\\Connection->__construct()\n#8 {main}\n\nNext LdapRecord\\LdapRecordException: ldap_conn in /var/www/TeamPass/includes/libraries/LdapRecord/LdapRecordException.php on line 26, referer: http://localhost/index.php?page=ldap
