### ISSUE TITLE
Authentication by password strange

### ISSUE THREAD

**Issue by 73erln91** [nilsteampassnet/TeamPass#2915]
### Steps to reproduce
1. create user, let user set password
2. authenticate with correct username and correct password
3. try to authenticate with correct username and arbitrary (wrong) password

### Expected behaviour
After authentication with correct username and correct password the user obtains access to all allowed items. 
Authentication with correct username and arbitrary (wrong) password should fail (no login, no step behind the login mask). 

### Actual behaviour
Authentication with correct username and ARBITRARY WRONG password succeeds.
All allowed items are displayed but password are not accessible. Not sure if this is intended by design but still even without visible passwords lots of personal information may be disclosed. 

### Server configuration
**Operating system:** Debian testing Bullseye 64bit

**Web server:** Apache2 2.4.46-4

**Database:** MariaDB 10.5.9.-1

**PHP version:** 7.4.15-5

**Teampass version:** 3.0.0.8

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
updated from 3.0.0.7

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/6443238/tp.config.php.txt)

### Client configuration
**Browser:** Mozilla Firefox 88.0.1

**Operating system:** Debian testing Bullseye 64bit

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
😲Confirmed !
