### ISSUE TITLE
Same folder name with different parent: Error caught - This folder already exists!

### ISSUE THREAD

**Issue by jorisvc** [nilsteampassnet/TeamPass#2916]
### Steps to reproduce
1. Create a new folder with name "ABC" with root as parent
2. Create a second new folder with name "ABC" with a parent other then root, for example: websites

### Expected behaviour
The second folder with name "ABC" should be created under parent "websites"

### Actual behaviour
An error is shown: Error caught - This folder already exists!

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Apache
**Database:**
MariDB
**PHP version:**
7.2
**Teampass version:** 
3.0.0.7
**Teampass configuration file:**
/
**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
Microsoft Edge version 90
**Operating system:**
Windows 10

**Comment by nilsteampassnet** [comment]
Hello,
This is by default. No folder inside the tool could have the same name.
If you have to, then enable the option
![image](https://user-images.githubusercontent.com/1197546/121640787-a5289880-ca8e-11eb-8a64-912e00e45d52.png)
