### ISSUE TITLE
Question: Cleaning up item log ?

### ISSUE THREAD

**Issue by Dod9er** [nilsteampassnet/TeamPass#2932]
Hi,

this is more of a question than an issue. I would like to clean up old log-entries under Utilities/Logs/Items.
I thought that something like `truncate table teampass_log_items` would do the job, but once I truncated the table I can´t access my items anymore and get a: 
```
Access to password item denied! 
Author: API
restricted to:

request access to modify
```
No further exception in the webserver or php-log.

Seems like there is some kind of dependency, but I don´t see it.
Maybe there is a more official option to clean up the old item logs which I just didn´t see ?

**Comment by nilsteampassnet** [comment]
Hello,

As I don't know the version, I will consider for 3.x

No you should not truncate this table.
Indeed some relationships exist within entries from this table and user visibility.

Currently I have not added any tool to purge the logs.
It will be added in the future.

**Comment by Dod9er** [comment]
Hi,
thank you for your reply. Actually it is 2.1.27.36 yet, but I assume it the same situation :)

**Comment by nilsteampassnet** [comment]
Hello,
From admin panel, look at the Logs.
You should have a purge feature at the bottom of the page.
