### ISSUE TITLE
Create sk.php file - Cannot change directory permissions - please fix manually

### ISSUE THREAD

**Issue by e4rthdog** [nilsteampassnet/TeamPass#2933]
### Steps to reproduce
1. Install fresh latest version 3.0.0.7
2.
3.

### Expected behaviour
The install should complete

### Actual behaviour
On the step "Finalization" of a fresh install i get the error "Cannot change directory permissions - please fix manually" on the Step: "Create sk.php file".

### Server configuration
**Operating system**: Ubuntu 20.04.2 LTS

**Web server:** Apache/2.4.41

**Database:** mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 

**PHP version:**8.0.2

**Teampass version:** 3.0.0.7

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**fresh
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/6676743/tp.config.php.txt)

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I think I found the issue.
Problem occurs on Linux and not Windows.

Please reopen if needed
