### ISSUE TITLE
Export CSV or PDF get wrong encoding

### ISSUE THREAD

**Issue by maty974** [nilsteampassnet/TeamPass#2934]
### Steps to reproduce
1.  Export to CSV or PDF
2.
3.

### Expected behaviour
Encoding of all items must be exported as UTF-8 encoding

### Actual behaviour
All french accents or character get wrong encoding

### Server configuration
**Operating system**:
Debian GNU/Linux 10 (buster)

**Web server:**
Apache/2.4.38 (Debian)

**Database:**
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:**
PHP 7.3.14-1~deb10u1

**Teampass version:** 
2.1.26

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows & Linux

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

Hi, 

We are trying to export a previous database items to a new one on a fresh install, the only way we have is to retrieve all items from TeamPass via PDF or CSV export, as we don't have the salt key, the only problem is that the export encoding seems to be wrong with french words with accents.

Is there a way to fix this manually before export ?

Thanks for your help

**Comment by One111** [comment]
I have same issue with 2.1.27.16 and cyrillic (russian) letters
