### ISSUE TITLE
LDAP fails when trying more than one host

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#2935]
### Steps to reproduce
1. Configure multiple LDAP hosts using comma separated values
2. 
3.

### Expected behaviour
allow use of LDAP auth

### Actual behaviour
[Tue Jun 29 13:46:13.825071 2021] [php7:error] [pid 859] [client 172.17.0.1:44868] PHP Fatal error:  Uncaught ErrorException: ldap_connect(): Could not create session handle: Bad parameter to an ldap routine in /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php:194\nStack trace:\n#0 [internal function]: LdapRecord\\LdapBase->LdapRecord\\{closure}()\n#1 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(194): ldap_connect()\n#2 /var/www/TeamPass/includes/libraries/LdapRecord/LdapBase.php(160): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(195): LdapRecord\\LdapBase->executeFailableOperation()\n#4 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(169): LdapRecord\\Ldap->connect()\n#5 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(141): LdapRecord\\Connection->initialize()\n#6 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(99): LdapRecord\\Connection->setLdapConnection()\n#7 /var/www/TeamPass/sources/ldap.queries.php(170): LdapRecord\\Connection->__construct()\n#8 {main}\n\nNext LdapRecord\\LdapRecordException: ldap_conn in /var/www/TeamPass/includes/libraries/LdapRecord/LdapRecordException.php on line 26, referer: http://localhost/index.php?page=ldap

### Server configuration
**Operating system**:
Alpine Linux

**Web server:**
Apache

**Database:**
Amazon Aurora RDS (mysql 5.7)

**PHP version:**
7.4

**Teampass version:** 
3.0.0.8

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Can you please provide the hosts list (even if anonymized)?
