### ISSUE TITLE
LDAP Connection FreeIPA

### ISSUE THREAD

**Issue by Dozentz** [nilsteampassnet/TeamPass#2937]
### Server configuration
**Operating system**: Centos 7

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.4

**Teampass version:** 2.1.27.16

UPD. Status **Successfully connected**
Connection is successful through LDAP, but I cannot log in

**Comment by Heatcliff199** [comment]
A very similar problem occurred, I can not connect to the LDAP server from Freeipa
Server configuration
Operating system: Centos 7

Web server: NGINX

Database: MariaDB

PHP version: 7.2

Teampass version 3.0.0.7

only my problem is that I can't connect to the ldap server at all
