### ISSUE TITLE
Cannot install TeamPass 3.0.0.8 (docker)

### ISSUE THREAD

**Issue by DrrMrr** [nilsteampassnet/TeamPass#2952]
### Page on which it happened
http://teampass_host:9280/install/install.php
### Steps to reproduce
1. start docker compose stack and expose port for Teampass (9290:80). I cannot access to teampass any other way ???
2. copy source from https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.0.0.8.zip and extract everything to local volume
3. after restarting the container I get an error that PHP is 7.1.9 and not minimum at 7.2.0. That's why I've build a new local docker image with
`sudo docker build -t teampass/teampass:3.0.0.8 . `
from zip files and restart container
5. now I can continue with setup and when preparing the database I get an error **"At least one task has failed! Please correct and relaunch"**. This is where all the tables are created in step "Preparing database". Then I go and check into mysql database and can see that all the tables were created. But all I have is as mentioned error in bottom right and buttons "Start" (error pop up again) and Restart where can I repeat everything to current step

I this a known issue or am I installing TeamPass on docker wrong way?

### Expected behaviour
Trying to install Teampass with docker.

### Actual behaviour
Cannot finish setup because of error "At least one task has failed! Please correct and relaunch" in step "preparing database"

### Server configuration
**Operating system**: Ubuntu 20.04.2 LTS

**Web server:**1.21.1

**Database:**5.7.35

**PHP version:**7.2.10

**Teampass version:** 3.0.0.8

### Client configuration
**Browser:** Google Chrome 92.0.4515.107

**Operating system:** Windows 10 Enterprise

#### Web server log
```
[_teampass_nginx_1_logs.txt](https://github.com/nilsteampassnet/TeamPass/files/6931459/_teampass_nginx_1_logs.txt)

```
#### Teampass log
```
[_teampass_teampass_1_logs.txt](https://github.com/nilsteampassnet/TeamPass/files/6931467/_teampass_teampass_1_logs.txt)
```
#### Database log
```
[_teampass_db_1_logs.txt](https://github.com/nilsteampassnet/TeamPass/files/6931470/_teampass_db_1_logs.txt)
```

**Comment by hitenmandalia** [comment]
@DrrMrr 
Look at https://github.com/nilsteampassnet/TeamPass/issues/2947.  
I get the exact same issue.  replacing the install.queries.php with the version from 3.0.0.6 seems to fix this issue, however im not sure what is missed when doing so.

**Comment by DrrMrr** [comment]
Hi, It seems really that it is the same issue.

Can you please tell me where can I find file install.queries.php from version 3.0.0.6. I've looked everywhere in https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.0.0.6.zip and I can't find it?

**Comment by DrrMrr** [comment]
> @DrrMrr
> Look at #2947.
> I get the exact same issue. replacing the install.queries.php with the version from 3.0.0.6 seems to fix this issue, however im not sure what is missed when doing so.

Hi, It seems really that it is the same issue.

Can you please tell me where can I find file install.queries.php from version 3.0.0.6. I've looked everywhere in https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.0.0.6.zip and I can't find it?

**Comment by DrrMrr** [comment]
> @DrrMrr
> Look at #2947.
> I get the exact same issue. replacing the install.queries.php with the version from 3.0.0.6 seems to fix this issue, however im not sure what is missed when doing so.

Hi, It seems really that it is the same issue.

Can you please tell me where can I find file install.queries.php from version 3.0.0.6. I've looked everywhere in https://github.com/nilsteampassnet/TeamPass/archive/refs/tags/3.0.0.6.zip and I can't find it?

**Comment by hitenmandalia** [comment]
@DrrMrr 
If you download version 3.0.0.7 (https://github.com/nilsteampassnet/TeamPass/releases/tag/3.0.0.7) and then browse to the install directory, you will find a copy of the install.queries.php file which will work

**Comment by DrrMrr** [comment]
> @DrrMrr
> If you download version 3.0.0.7 (https://github.com/nilsteampassnet/TeamPass/releases/tag/3.0.0.7) and then browse to the install directory, you will find a copy of the install.queries.php file which will work

Thank you. Now setup can be finished. But Then I have some new issues first on login:
`Warning
: setcookie() expects parameter 3 to be integer, array given in
/var/www/html/includes/libraries/csrfp/libs/csrf/csrfprotector.php
on line
372`

and if I click top left on Teampass ling and logo (index.php?page=items) then I get error bottom right "container specified, but cannot be found".

But, I will check if anyone has already mentioned this.

Thank you and best regards

**Comment by DrrMrr** [comment]
Hi, I've removed the volume in re-created it again. Then I've:
1. used my docker image 3.0.0.8 that was build locally because of required minimum PHP version
2. copied all the data from 3.0.0.8 to my html volume and changed permissions to all files & folders to 777
3. After tables were created in mysql, then I have also replaced file install.queries.php with the one from 3.0.0.7
4. now I could finished the setup and remove install folder
5. now I get a warning in file csrfprotector.php.
![image](https://user-images.githubusercontent.com/174676/128831368-dbf7b1b7-3981-4536-b9e6-8ff2370db25c.png)

Thank you

**Comment by hitenmandalia** [comment]
@DrrMrr 
for step 3, use the install.queries.php from 3.0.0.7 to create the tables.

**Comment by DrrMrr** [comment]
I also tried that and I get the same error.

**Comment by hitenmandalia** [comment]
have you tried installing on a clean linux (or wamp) system?  not docker

**Comment by DrrMrr** [comment]
> have you tried installing on a clean linux (or wamp) system? not docker

No, that I haven't. Maybe I will try also that.
