### ISSUE TITLE
Unable to Export in TeamPass

### ISSUE THREAD

**Issue by LordGraves** [nilsteampassnet/TeamPass#2958]
### Steps to reproduce
1. Click on options next to Folders
2. Select 
3. Export Items

### Expected behaviour
Export dialog box should appear

### Actual behaviour
Error while loading https"//servername.domain/items.export.php?
key= 8ZK4GNy....ect.

### Server configuration
RHEL 7

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5.68

**PHP version:**
7.4

**Teampass version:** 
2.1.27

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

[TeamPass02_Config.txt](https://github.com/nilsteampassnet/TeamPass/files/6994147/TeamPass02_Config.txt)

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
[Web_Browser_Log.txt](https://github.com/nilsteampassnet/TeamPass/files/6994154/Web_Browser_Log.txt)

[1:07 PM] Martin, Robert L
    
This is the culprit right at the end of a long, long log. 
SEC7120: Origin https://servername not found in Access-Control-Allow-Origin header.
index.php
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
index.php
Not connect.
Verify Network.
SCRIPT5009: 'exportItemsToFile' is undefined
index.php (6423,17)

**Comment by Moltivie** [comment]
@nilsteampassnet do we have a follow-up on how this issue got resolved?
