### ISSUE TITLE
Installation completion error

### ISSUE THREAD

**Issue by DubovskoySergey** [nilsteampassnet/TeamPass#2962]
### Steps to reproduce
1. Start the installation http://your_domain/teampass/
2. During the installation, go to the Preparing database page.
3. Click on the start button to create tables in the database.

To solve the problem, I forcibly edited the html code of the NEXT button, removing the disabled="disabled"attribute from it.

### Expected behaviour
The NEXT button must be activated to complete the installation.

### Actual behaviour
I got an error on this page:

> "At least one task has failed!"
Scrinshot https://ibb.co/sJP1Ccb

### Server configuration
**Operating system**:
Centos 7
**Web server:**
 Apache/2.4.6 (CentOS)
**Database:**
 5.5.68-MariaDB MariaDB Server
**PHP version:**
PHP 7.4.23
**Teampass version:** 
3.0.8
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Yandex Browser 21.8.1.468 (64-bit)
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by relkai** [comment]
I assume you don't have a `teampass_otv` table in your database now.
I had the same problem before. Your version of MariaDB doesn't seem to accept a default value for a field of the type "text" and therefore doesn't create this table.
A had this problem with MariaDB-10.1.x. After updating to MariaDB-10.3.x, the installation was successful and the missing table created.

**Comment by DubovskoySergey** [comment]
> I assume you don't have a `teampass_otv` table in your database now.
> I had the same problem before. Your version of MariaDB doesn't seem to accept a default value for a field of the type "text" and therefore doesn't create this table (the field `teampass_otv.encrypted` is a text field with a default value defined).
> A had this problem with MariaDB-10.1.x. After updating to MariaDB-10.3.x, the installation was successful and the missing table created.

well, thank you. I'll test this theory. Tell me more backup from version 2 will be able to install in version 3?

**Comment by relkai** [comment]
I have no idea, because I just discovered TeamPass and directly installed the 3.x version.
But I'm pretty sure, @nilsteampassnet has some more insights.
