### ISSUE TITLE
Version 3.0.0.8 is missing upgrade_run_final.php in install directory

### ISSUE THREAD

**Issue by turekg** [nilsteampassnet/TeamPass#2972]
Trying to update version from 3.0.0.7 (to get LDAP fix) but update hands at 
`14:40:02 - upgrade_run_final.php - Loop #1 is now running ...`
It turns out that this script does not exist in the distribution!
Please fix

**Comment by ChuckStrusz** [comment]
Sadly, I'm pretty sure this project has died.

**Comment by mazeugs** [comment]
Same problem on my side.

**Comment by m4x91** [comment]
Same problem...
Need to resolve the empty "Caution" dialog appears when opening an item!
