### ISSUE TITLE
TeamPass 3.0.0.8: Mail to User not sent after admin change User's password

### ISSUE THREAD

**Issue by Anth0nyME** [nilsteampassnet/TeamPass#2992]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1. Select user
2. Select "Change login password"
3. Press "mail to user"

Nothing happends and no way to debug it. As mail server, "localhost" with postfix used. No new entries at maillog, queue empty. **Test from "Emails" page always successful**.

### Expected behaviour

Mail with new password must be sent to User

### Actual behaviour
Nothing happends

**Comment by Anth0nyME** [comment]
![Capture](https://user-images.githubusercontent.com/33858023/146189798-c7ce7bce-47f0-48c7-a656-ed616bd7cecd.JPG)

**Comment by nilsteampassnet** [comment]
Confirmed and fixed.
