### ISSUE TITLE
TeamPass 3.0.0.8: "password" field empty at Item after user changes password

### ISSUE THREAD

**Issue by Anth0nyME** [nilsteampassnet/TeamPass#2993]
### Page on which it happened
index.php?page=items

### Steps to reproduce
1. Create new, ordinar User
2. Create an item from User, fill the "password" field
3. Admin reset User's password
4. User change new random password to his own
5. Go to item - NO password, field is empty
 

### Expected behaviour
After pressing to eye, asterisks must be replaced by password field content - password itself.

### Actual behaviour
Field "password" is empty after user passsword changed

### Server configuration
**Operating system**: Linux Rocky 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 20:49:28 UTC 2021 x86_64

**Web server:** nginx/1.20.2

**Database:** 5.5.5-10.6.5-MariaDB-log

**PHP version:** 8.0.13

**Teampass version:** 3.0.0.8

**Comment by Anth0nyME** [comment]
![img_1](https://user-images.githubusercontent.com/33858023/146197335-b5e01628-9a97-4458-b585-495bc9812cf5.PNG)
![img_2](https://user-images.githubusercontent.com/33858023/146197374-a72ab292-9651-4969-832b-c95e2699e907.PNG)

**Comment by elmarbransch** [comment]
I did not upgrade, but I was unable to view or copy passwords. There are stars next to the Password label, clicking on the star or clicking on the eye shows either stars again or an empty field. Copy Password also does not have an effect. Then I changed the users passwords a couple of times and after a few tries the passwords are showing up again.

**Comment by nilsteampassnet** [comment]
I believe I found the reason one and now should be fixed.
please reopen if not.
