### ISSUE TITLE
Translation Project unavaiable

### ISSUE THREAD

**Issue by LU1ZINH0** [nilsteampassnet/TeamPass#3000]
Hi!

The Translation Project for 3.0.9 available in the last release is unavailable in POEDITOR. Please check when possible! https://poeditor.com/projects/view?id=433631

When opening from the link, it gives an error 404.

**Comment by nilsteampassnet** [comment]
Oh damned!
I fixed it I believe, can you confirm please?
Becoming  contributor to v3 : https://poeditor.com/join/project?hash=0vptzClQrM

**Comment by jokerby** [comment]
_Maybe you should also replace the links in the release descriptions :)_
