### ISSUE TITLE
Errors upgrading from 2.1.27.36 to 3.0.0.09 (same with 3.0.0.10)

### ISSUE THREAD

**Issue by gmontequi** [nilsteampassnet/TeamPass#3001]
### Steps to reproduce

1. Download Teampass 3.0 from github
2. Extract to Teampass server folder overwriting existing
3. Create manually private_key, publick_key (users table) and encrypted (otv table) columns as text. Otherwise, upgrade fails.
4. Run upgrade.

### Expected behaviour

The expected behaviour is that Teampass should upgrade to version 3.0 after all checks successfully complete.

### Actual behaviour

With 3.0.0.9 and 3.0.0.10

Upgrade fails here:

10:13:44 - User 10000000 - Creating keys until 100 ... 
10:13:44 - Users public / private keys were generated if needed 
10:13:42 - User id 10000004 done 
10:13:41 - User id 10000003 done 

Error in apache log:

[Thu Jan 13 10:13:44.885696 2022] [php7:error] [pid 28607] [client xxxxxxxxx:59382] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/sources/main.functions.php:2645\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2645): base64_encode()\n#1 /var/www/html/install/upgrade_run_3.0.0_users.php(291): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2645, referer: https://xxxxxxxxx/install/upgrade.php

private_key and public_key for all users are filled (Not for OTV and API users).
sk.php and teampass-seckey.txt files exists.

This is the main error. Then, playing with private keys, i have been able to complete the upgrade, but not emails with private code where sent so users can not see the passwords. Try to reset the passwords from admin users panel but no luck. No passwords are shown.
As the upgrade did not finish by their own and i have modified the private keys all this test are not valid for me...

### Server configuration
Operating system: Ubuntu 20.04.3

Web server: Apache/2.4.41 (Ubuntu)

Database: MySQL Ver 8.0.27-0ubuntu0.20.04.1

PHP version: PHP: 7.4.3

**Teampass version: 3.0.0.09 and 3.0.0.10

**Teampass configuration file:

**Updated from an older Teampass or fresh install: Updated from an older Teampass 

PLEASE attach to this issue the file `/includes/config/tp.config.php`: Attached.

### Client configuration
**Browser: chorme and edge

**Operating system: windows10

#### Web server error log
```
[Thu Jan 13 10:13:44.885696 2022] [php7:error] [pid 28607] [client xxxxxxxxx:59382] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/sources/main.functions.php:2645\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2645): base64_encode()\n#1 /var/www/html/install/upgrade_run_3.0.0_users.php(291): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2645, referer: https://xxxxxxxxx/install/upgrade.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by gmontequi** [comment]
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/7861689/tp.config.txt)

**Comment by jrubenc** [comment]
Same bug I reported in https://github.com/nilsteampassnet/TeamPass/issues/2998

**Comment by gmontequi** [comment]
Yes, but in my case, i have errors during the upgrade...

**Comment by jrubenc** [comment]
Well actually I also had to manually fix some stuff DB related for the upgrade to be able to go through... but not what you pointed out there certainly.

**Comment by michaldejmek** [comment]
@jrubenc What change did you have to make to get past the "Now sending new users password by email ." step?

**Comment by nilsteampassnet** [comment]
So I restarted testing upgrade from 2.1.27.36 with a big database.
The step where it fails in your case, I couldn't reproduce
The issue seems to occur when the upgrade process tries to create the items keys for your 1st user.
The error you get indicates that the admin private key hasn't been decrypted correctly.
But I see a small typo error in the code.
Could you please do this change.

File ./install/upgrade_run_3.0.0_users.php
Find
```
            $adminPrivateKey = decryptPrivateKey($adminPwd, $adminQuery['private_key']);
            if ($adminPrivateKey === null) {
```
change to
```
            $adminPrivateKey = decryptPrivateKey($adminPwd, $adminQuery['private_key']);
            if ($adminPrivateKey === false) {
```

File ./sources/main.functions.php
Find
```
 *
 * @return string
 */
function decryptPrivateKey(string $userPwd, string $userPrivateKey): string
{
    if (empty($userPwd) === false) {
        include_once '../includes/libraries/Encryption/phpseclib/Crypt/AES.php';
        // Load classes
        $cipher = new Crypt_AES();
        // Encrypt the privatekey
        $cipher->setPassword($userPwd);
        return base64_encode($cipher->decrypt(base64_decode($userPrivateKey)));
    }
    return false;
}
```
change to
```
 *
 * @return string|bool
 */
function decryptPrivateKey(string $userPwd, string $userPrivateKey)
{
    if (empty($userPwd) === false) {
        include_once '../includes/libraries/Encryption/phpseclib/Crypt/AES.php';
        // Load classes
        $cipher = new Crypt_AES();
        // Encrypt the privatekey
        $cipher->setPassword($userPwd);
        return base64_encode($cipher->decrypt(base64_decode($userPrivateKey)));
    }
    return '';
}
```

Rerun upgrade.
This should generate a break during upgrade process and confirm that an error occurs due to bad privatekey encryption.
Based on this, I will be able to investigate more.

One thing, in your users list, do you have names or lastnames with special characters such as é, è, ö, etc. ?

**Comment by gmontequi** [comment]
Hi Nils,

Many thanks for your answer. I have done the changes in the code but same result.

            $adminPrivateKey = decryptPrivateKey($adminPwd, $adminQuery['private_key']);
            if ($adminPrivateKey === false) {

and

function decryptPrivateKey(string $userPwd, string $userPrivateKey)
{
    if (empty($userPwd) === false) {
        include_once '../includes/libraries/Encryption/phpseclib/Crypt/AES.php';
        // Load classes
        $cipher = new Crypt_AES();
        // Encrypt the privatekey
        $cipher->setPassword($userPwd);
        return base64_encode($cipher->decrypt(base64_decode($userPrivateKey)));
    }
    return '';
}


Apache error:


[Fri Jan 14 09:30:42.543480 2022] [php7:error] [pid 32341] [client xxxxxxxxxxx:51468] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/sources/main.functions.php:2644\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2644): base64_encode()\n#1 /var/www/html/install/upgrade_run_3.0.0_users.php(291): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2644, referer: https://xxxxxxx/install/upgrade.php

The upgrade process fails at the same step than before:

09:30:44 - User 10000000 - Creating keys until 100 ... 
09:30:44 - Users public / private keys were generated if needed 
09:30:40 - User id 10000004 done 
09:30:35 - User id 10000003 done 
09:30:32 - User id 10000002 done 
09:30:30 - User id 10000001 done 
09:30:26 - User id 10000000 done 

We have 5 users and yes, some of then have characters like "Nuñez", "García" but user with id "10000000" which is my user, does not have special characters.

thank you!

**Comment by gmontequi** [comment]
One thing to also note is that during the upgrade, it seems to freeze in phase:

09:28:10 - upgrade_run_3.0.0_files.php - Loop #1 is now running ... 

No errors but to activity at os level but by simply clicking the start button again, it restarts with the logs phase:

09:29:15 - upgrade_run_3.0.0_logs.php - Loop #1 is now running ... 

And then the files upgrade phase is done correctly and upgrade continues with the process:

09:30:44 - User 10000000 - Creating keys until 100 ... 
09:30:44 - Users public / private keys were generated if needed 
09:30:40 - User id 10000004 done 
09:30:35 - User id 10000003 done 
09:30:32 - User id 10000002 done 
09:30:30 - User id 10000001 done 
09:30:26 - User id 10000000 done 
09:30:26 - upgrade_run_3.0.0_files.php - Loop #1 
09:30:25 - upgrade_run_3.0.0_suggestions.php - Loop #1 
09:30:25 - upgrade_run_3.0.0_fields.php - Loop #1 
09:30:25 - upgrade_run_3.0.0_logs.php - Loop #5 
09:30:07 - upgrade_run_3.0.0_logs.php - Loop #4 

best regards,

**Comment by gmontequi** [comment]
Hello! Any update?

thank you!

**Comment by gmontequi** [comment]
Hello! With the latest version of teampass downloaded today, the upgrade process is OK (I just only have to add "encrypted" field to otv table manually) but no mails have been sent to the users.
I have logged in with admin user, tested email and it is working fine but i have not received the emails for the users in order to log in.
If i try to reset a user password from users panel, i have the error:

[Wed Jan 26 12:38:27.740886 2022] [php7:error] [pid 217760] [client 88.6.135.28:2782] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/sourcack trace:\n#0 /var/www/html/sources/main.functions.php(2655): base64_encode()\n#1 /var/www/html/sources/main.queries.php(1850): decryptUserObjectKey()\n#2 /var/www/html/sources/main.queries.php(1689): contiep1()\n#3 /var/www/html/sources/main.queries.php(434): continueReEncryptingUserSharekeys()\n#4 /var/www/html/sources/main.queries.php(74): mainQuery()\n#5 {main}\n  thrown in /var/www/html/sources/main.funct: https://xxxxxxxxxxx/index.php?page=users

thank you!

**Comment by gmontequi** [comment]
![image](https://user-images.githubusercontent.com/90802409/151162071-e3a82097-7db3-4cb2-a9d2-132b9354948a.png)

No public nor private keys created for users...should this fields be NULL?

**Comment by gmontequi** [comment]
Hi @nilsteampassnet 

Before trying to upgrade to the latest version, I wanted to clean up the database. My current version is 2.1.27.36.
One thing that I found curious is the amount of records (100695) in the **keepass_log_items** table. In spite of having in the options that it does not register logs, I see that it stores in that table a record for each created item, for each seen item, for each changed password...etc so the table is enormous. My database occupies 8Mb at the moment; Deleting that table, it occupies 1,5Mb so that table is enormous.
I have tried to do a cleanup from the teampass administration console but, having so many records, it gives a JSON error and it doesn't work. Therefore, I have done it at the database level. However, if I delete ALL the records of the table keepass_log_items, then I can't see any passwords. It gives an error xxxxxx
Passwords are only shown if in the keepass_log_items table you keep all records whose "action"='at creation'.

![image](https://user-images.githubusercontent.com/90802409/154815404-3a06883f-b19a-4c62-a684-828db11da448.png)

Once you perform the upgrade, if you login with a "normal" user, I see the folders and items but NOT the passwords so I understand that the encryption process is missing. 

![image](https://user-images.githubusercontent.com/90802409/154815169-143e59af-ac0a-4468-841a-a06a605e0e2f.png)

To force it, with the **admin** user, I change the password of the normal user and then the encryption process starts. First step is the encryp of the items but it fails:

![image](https://user-images.githubusercontent.com/90802409/154815206-5984cdaa-f1f9-4fb1-afdf-d6ed9c86e0f2.png)

Console:

[Sat Feb 19 20:21:21.470516 2022] [php7:error] [pid 605379] [client 185.227.212.189:53661] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/sources/main.functions.php:2731\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2731): base64_encode()\n#1 /var/www/html/sources/main.queries.php(1854): decryptUserObjectKey()\n#2 /var/www/html/sources/main.queries.php(1690): continueReEncryptingUserSharekeysStep1()\n#3 /var/www/html/sources/main.queries.php(408): continueReEncryptingUserSharekeys()\n#4 /var/www/html/sources/main.queries.php(74): mainQuery()\n#5 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2731, referer: https://xxxxx/index.php?page=users


But, if I login with another newly created test (administrator role) user and try to reset the password of the normal user the behavior is different. Te encryption of the items is OK but it fails with the logs:

![image](https://user-images.githubusercontent.com/90802409/154815802-1bb51a8a-4abc-48b6-8c59-a9dacaf162cf.png)

Console:

[Sat Feb 19 20:19:51.432882 2022] [php7:error] [pid 605353] [client 185.227.212.189:53606] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to decryptUserObjectKey() must be of the type string, null given, called in /var/www/html/sources/main.queries.php on line 1946 and defined in /var/www/html/sources/main.functions.php:2721\nStack trace:\n#0 /var/www/html/sources/main.queries.php(1946): decryptUserObjectKey()\n#1 /var/www/html/sources/main.queries.php(1706): continueReEncryptingUserSharekeysStep2()\n#2 /var/www/html/sources/main.queries.php(408): continueReEncryptingUserSharekeys()\n#3 /var/www/html/sources/main.queries.php(74): mainQuery()\n#4 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2721, referer: https://xxxxxx/index.php?page=users

So...i dont know what to do!
Any idea?

Best regards,







 (and does it well) but then it tries to encrypt the logs and that step fails, so I can't do anything.

**Comment by fapgomes** [comment]
Hi,

 I've the some problem, if I try to change an user password, i've this error in logs:

```
[13-Mar-2022 14:32:10 Europe/Lisbon] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2737
Stack trace:
#0 /var/www/html/teampass/sources/main.functions.php(2737): base64_encode()
#1 /var/www/html/teampass/sources/main.queries.php(1862): decryptUserObjectKey()
#2 /var/www/html/teampass/sources/main.queries.php(1716): continueReEncryptingUserSharekeysStep1()
#3 /var/www/html/teampass/sources/main.queries.php(408): continueReEncryptingUserSharekeys()
#4 /var/www/html/teampass/sources/main.queries.php(74): mainQuery()
#5 {main}
  thrown in /var/www/html/teampass/sources/main.functions.php on line 2737
```

There are any fix or someting that I can do to help to correct this issue?

Best Regards,

**Comment by fapgomes** [comment]
Do you have a solution for this @gmontequi ? You close this issue...

**Comment by gmontequi** [comment]
A workaround...

The best way to avoid the error is to convert the user with which you have created the items in administrator from the user management console and then, in the upgrade wizard, put that user in the "teampass administrator" part. Then during the upgrade the encryption keys will be generated for that user and will be applied later to the items and the process will not fail. In my case at least, I had to, once the upgrade was done, enter the user administration console (with my user, not admin) and change the password for each one of them. That makes the items to be encrypted again with the keys and it will work without problems. At least this is the only solution I have found. Whenever I upgraded with the admin user I had the same error as you. Once I did the upgrade with my user (previously converting it to admin) it worked without problems.

Best regards,

**Comment by fapgomes** [comment]
But I've the same error when add a new user. Fail when I try to create a new one, with the same error. This works for you @gmontequi ?

**Comment by gmontequi** [comment]
yes! But you can create a new user before the upgrqade and then try to perform the upgrade with the new (administrator) user created.

br,

**Comment by fapgomes** [comment]
But then you're unable to add more users....
