### ISSUE TITLE
Upgrading from 2.1.27.36 to 3.0.0.9 - ERROR: Unknown column 'increment_id' in 'field list'

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3004]
### Steps to reproduce
1. Upgrade from 2.1.27.36 to 3.0.0.9. 
2. Download ver 3.0.0.9, copy all files to /var/www/html/pass folder
3. Run install/upgrade.php
4. Login as Administrator
5. Check elements
6. Create database dump
7. Database Updates

### Expected behaviour
Update Database

### Actual behaviour
An error occurred. Please check and relaunch.
**14:45:12 - ERROR: Unknown column 'increment_id' in 'field list'**
14:45:12 - upgrade_run_3.0.0_logs.php - Loop #1 
14:45:12 - upgrade_run_3.0.0_passwords.php - Loop #11 
14:45:12 - upgrade_run_3.0.0_passwords.php - Loop #10 

### Server configuration
**Operating system**:
Debian GNU/Linux 11 (bullseye)

**Web server:**
Apache/2.4.52 (Debian)

**Database:**
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:**
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )

**Teampass version:** 
3.0.0.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Upgrade
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/7888711/tp.config.php.txt)

### Client configuration
**Browser:**
Any browser

**Operating system:**
Any OS

**Comment by wease1** [comment]
MariaDB [dbpass]> show COLUMNS  from dbpass_log_items;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| id_item         | int(8)       | NO   | MUL | NULL    |       |
| date            | varchar(50)  | NO   |     | NULL    |       |
| id_user         | int(8)       | NO   |     | NULL    |       |
| action          | varchar(250) | YES  |     | NULL    |       |
| raison          | text         | YES  |     | NULL    |       |
| raison_iv       | text         | YES  |     | NULL    |       |
| encryption_type | varchar(20)  | NO   |     | not_set |       |
+-----------------+--------------+------+-----+---------+-------+

**Comment by nilsteampassnet** [comment]
I don't understand how this can be possible.
Field `increment_id` exists in table log_items already in TP V2.
Also, it is required in previous upgrade loops.
How can it be deleted between the 2 upgrade steps ... some kind of mystery here!

**Comment by nilsteampassnet** [comment]
Perhaps can we have more debug date from the web console.
While performing this upgrade can you follow instructions from
https://teampass.readthedocs.io/en/latest/faq/ chapter `How to capture query error from the browser console?`

**Comment by wease1** [comment]
debug data from the web console:  **[{"finish":"1" , "error":"Unknown column 'increment_id' in 'field list'"}]**

how I updated:
1. I had an old version 2.1.27.10
2. I installed version 2.1.27.36 on a separate server
3. created a dump from version 2.1.27.10 using   mysqldump -h 127.0.0.1 dbpass > dump_db_.sql
4. Uploaded a dump on a new server with the version 2.1.27.36
5. started updating to version 3.0.0.9

now I'm looking at how the table looks on the old server:
MySQL [dbpass]>  show COLUMNS  from dbpass_log_items;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| id_item         | int(8)       | NO   | MUL | NULL    |       |
| date            | varchar(50)  | NO   |     | NULL    |       |
| id_user         | int(8)       | NO   |     | NULL    |       |
| action          | varchar(250) | YES  |     | NULL    |       |
| raison          | text         | YES  |     | NULL    |       |
| raison_iv       | text         | YES  |     | NULL    |       |
| encryption_type | varchar(20)  | NO   |     | not_set |       |
+-----------------+--------------+------+-----+---------+-------+
7 rows in set (0.00 sec)

**Comment by nilsteampassnet** [comment]
ok so it means that you perhaps have not the correct DB structure as no upgrade was performed between x.10 to x.36.
And this explains why there are some inconsistencies in the DB.
You should compare the structure of tables in X.10 and x.36 to adapt manually.

**Comment by wease1** [comment]
In which version was the update with the modernization of the database tables ? I'm thinking of making an update starting from this version

**Comment by wease1** [comment]
I'm add column **increment_id**  to table **log_items** and update process is continued. But now it does not end at the step **"sending new users password by email"**. I dоn't configure the mail settings in old DB version. 
How can I disable sending emails in configuration files or in the database?

**Comment by wease1** [comment]
thank you,  im successful upgrade from 2.1.27.10 to 3.0.0.16
