### ISSUE TITLE
Install folder not being removed after installation

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#3008]
### Steps to reproduce
1. Setup Ubuntu and MariaDB 
2. Go through installation steps
3. Once install is complete, Installation starts again when clicking on "move to home page"
4.  manually removed Install folder, then get a Not Found (URL still trying to load install page)

### Expected behaviour
Expect to see login page for teampass

### Actual behaviour
installation page appears if install folder not deleted, or Not found if install folder manually removed

### Server configuration
**Operating system**:  Ubuntu

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.4

**Teampass version:** 3.0.0.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:**

#### Web server error log
I see the following error in apache log
```
[Wed Jan 19 17:29:33.010860 2022] [php7:error] [pid 17084] [client 172.17.0.1:49862] PHP Fatal error:  Uncaught Error: Class 'Defuse\\Crypto\\Exception\\WrongKeyOrModifiedCiphertextException' not found in /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php:364\nStack trace:\n#0 /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php(113): Defuse\\Crypto\\Crypto::decryptInternal()\n#1 /var/www/TeamPass/includes/libraries/Encryption/Encryption/RuntimeTests.php(100): Defuse\\Crypto\\Crypto::decrypt()\n#2 /var/www/TeamPass/includes/libraries/Encryption/Encryption/RuntimeTests.php(61): Defuse\\Crypto\\RuntimeTests::testEncryptDecrypt()\n#3 /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php(259): Defuse\\Crypto\\RuntimeTests::runtimeTest()\n#4 /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php(39): Defuse\\Crypto\\Crypto::encryptInternal()\n#5 /var/www/TeamPass/install/install.queries.php(149): Defuse\\Crypto\\Crypto::encrypt()\n#6 /var/www/TeamPass/install/install.queries.php(1284): encryptFollowingDefuse()\n#7 {main}\n  thrown in /var/www/TeamPass/includes/libraries/Encryption/Encryption/Crypto.php on line 364, referer: http://localhost/install/install.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Folder removal is OS and rights dependent.
If you remove it manually, please clear your browser cache.
The blank page will not be after clearing the cache.

**Comment by hitenmandalia** [comment]
chmod -775 on TeamPass folder
chown apache:apache on TeamPass folder
Install directory still not being removed

Manually removed Installation folder.  Opened new private browser window using different brower, browse to localhost (as its installed locally as a docker container) and get redirected to http://localhost/install/install.php.  not sure what im doing wrong?  any help would be appreciated

**Comment by hitenmandalia** [comment]
Just reverted back to install 3.0.0.9 and do not get this problem.  Only happening to me when using 3.0.0.10

**Comment by gmontequi** [comment]
Yes, 3.0.0.10 is always redirecting to install/install.php...something is wrong. 3.0.0.09 is ok.

**Comment by hitenmandalia** [comment]
dont believe so.  All I suggest, is install 3.0.0.9 and then upgrade to 3.0.0.10.  Seemed to work for me

**Comment by marmotte32** [comment]
hello team :)
same issue here with 3.0.0.10
I thought this bug could come from the : Absolute path to SaltKey = /var/teampass
but even with blank defaut path, after install finish it loops to reinstall :(
I will install 3.0.0.9

**Comment by carlosmatthews** [comment]
same issue with Debian.

**Comment by carlosmatthews** [comment]
hi it wokrs for me 
`rm -rf` install folder and i can log with the admin account ! 
extract to: https://teampass.userecho.com/en/communities/1/topics/14-admin-login

**Comment by Kyogre** [comment]
yeah! Executing manually `rm -rf /var/www/teampass/install` worked for me.

**Comment by nilsteampassnet** [comment]
Install process tries to remove the install folder.
A message is also displayed
![image](https://user-images.githubusercontent.com/1197546/218250352-0758528e-eba5-4936-84e8-a878dd48706a.png)

This ticket is closed

**Comment by nguyenquangtruong** [comment]
Woks

> hi it wokrs for me `rm -rf` install folder and i can log with the admin account ! extract to: https://teampass.userecho.com/en/communities/1/topics/14-admin-login

Works for me as well. Tks all.

**Comment by bladerock5** [comment]
Ubuntu 22.04
rm -rf /var/www/html/TeamPass/install
logon web
