### ISSUE TITLE
Can't purge log item (any version 2 or 3)

### ISSUE THREAD

**Issue by ServiceMRE** [nilsteampassnet/TeamPass#3011]
### Steps to reproduce
1. Go to log -> items
2.
3.

### Expected behaviour
Items logs appears and after date range selection, can delete log

### Actual behaviour
Ajax error.
If I add a limit to the SQL request, the logs appears, but I can't delete them.
There is a timeout specified somewhere? The table log_items have arrount 40000 lines.

And I saw that only line with the action colums cointaining "at_shown" should be deleted.
There is no way to delete the lines with other values?

### Server configuration
**Operating system**:
linux
**Web server:**
nginx 1.18
**Database:**
mariaddb latest, or mysql 5.7
**PHP version:**
7.4.9 or 7.1

**Comment by nilsteampassnet** [comment]
I did some fix on purge in latest commit.
The timeout is defined on your server.
I would need the error to investigate on this.
Please follow https://teampass.readthedocs.io/en/latest/faq/ chapter `How to capture query error from the browser console?`

You can select the type of log you want to delete
![image](https://user-images.githubusercontent.com/1197546/150917547-42803ba2-ca23-4200-8974-da2136f079c2.png)

**Comment by ServiceMRE** [comment]
I have this, just when I click on Items
![image](https://user-images.githubusercontent.com/78038849/150952730-2d898b02-fd20-4849-a602-ecf6f9351e93.png)

I know the the time out are defined on the server, but the same SQL request run with phpmyadmin is working, so it's not a server configuration.

**Comment by nilsteampassnet** [comment]
thnak you.
Please clicl OK on the dialogbox then look to the console.
The errors are shown once you hit the OK button

**Comment by nilsteampassnet** [comment]
Can you please use the latest commit ?
I did some fixes that should fix your issue.

**Comment by ServiceMRE** [comment]
There is no error in the console after clicking on the dialog box.
Tests made with the latest commit.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/78038849/150980544-54438849-7cd1-4cf9-ab6a-e36f68fc5995.png">

**Comment by nilsteampassnet** [comment]
ok I think I understood.
It happens when there is no data to treat.
I will fix
