### ISSUE TITLE
Password strength not accepted by server on item save

### ISSUE THREAD

**Issue by manusfreedom** [nilsteampassnet/TeamPass#3051]
1. Create or Edit an item in folder with "Very Strong" requirement
2. Set the password to get Very Strong or Heavy check
3. Save

### Expected behaviour
Correctly check the password strength (JS and server must be sync)

### Actual behaviour
Unable to save.

JS: 56
Folder on server: 70

**Teampass version:** 3.0.0.10 (upgraded from 2.x)

![image](https://user-images.githubusercontent.com/2192016/155155919-6e5be4ec-259d-4283-901a-201b5e1f43d0.png)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
