### ISSUE TITLE
Reinstalling TeamPass

### ISSUE THREAD

**Issue by stojc998** [nilsteampassnet/TeamPass#3059]
### Steps to reproduce
1. Removing TeamPass from Ubuntu
2. Reinstalling it 
3.

### Expected behaviour
Acess to TeamPass wit same users and credentials, and all password should be there.

### Actual behaviour
Blank screen.

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4.41

**Database:** MariaDB Server version: 10.3.32-MariaDB-0ubuntu0.20.04.1

**PHP version:** PHP 7.4.3

**Teampass version:** 3.0

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
HI,

I am testing the scenario where I have to move the TeamPass to another server. If I move the original TeamPass folder and the original database it works fine. But when I try to make a fresh install of TeamPass on the new server with the original database and teampass-seckey.txt file the whole thing goes blank and I cant do anything. Any idea what could be wrong.

**Comment by nilsteampassnet** [comment]
I don't really see the interest of this 2d scenario.
If you have the backup of your DB and folder, then no need to reinstall.
The install process doesn't care of existing data.
Eventually you should do an upgrade 
But once again I don't see the use case you want to try.

**Comment by stojc998** [comment]
Thank you for the feedback. I missunderstud a few  things and realised a few days ago that the second scenarion was pointles.
So the problem is solved, you can close this thicket.
