### ISSUE TITLE
New ldap user can't log in 

### ISSUE THREAD

**Issue by romo2650** [nilsteampassnet/TeamPass#3060]
### Steps to reproduce
1. Clean installation version 3.0.0.11
2. Configure ActiveDirectory by user admin
3. Login with domain user 

### Expected behaviour
Access as a new account and have your personal folder. 

### Actual behaviour
When you enter credentials, it only checks with local users. With whireshark it does not log traffic against ad. 

### Server configuration
**Operating system**: Centos 8

**Web server:** Apache/2.4.52

**Database:** MariaDB 10.3.28

**PHP version:**  php 7.4

**Teampass version:** 3.0.0.11

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/TeamPass',
    'cpassman_url' => 'https://192.168.1**.***',
    'favicon' => 'https://192.168.1**.***/favicon.ico',
    'path_to_upload_folder' => '/var/www/TeamPass/upload',
    'path_to_files_folder' => '/var/www/TeamPass/files',
    'url_to_files_folder' => 'https://192.168.1**.***/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.11',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '@caf.local',
    'ldap_domain_dn' => 'ou=Usuarios,ou=*****,dc=***,dc=local',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'cn',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => 'ou=Usuarios,ou=*******,dc=***,dc=local',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1643447427',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'w75krjUs*********',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ldap_hosts' => '192.168.1**.**',
    'ldap_bdn' => 'ou=Usuarios,ou=****,dc=***,dc=local',
    'ldap_username' => 'cn=****,ou=Usuarios,ou=****,dc=***,dc=local',
    'ldap_password' => 'S****',
    'settings_ldap_user_dn_attribute' => 'dn',
    'ldap_user_object_filter' => '',
    'ldap-test-config-username' => '*****',
    'ldap-test-config-pwd' => '*******',
    'ldap_dn_additional_user_dn' => '',
);

#### Web server error log
```
No show errors in the log file.
```

**Comment by jcsa1986** [comment]
I am having the exact same behavior. Fresh install 3.0.0.12

**Comment by ryazantseff** [comment]
Confirm, the same issue. Fresh install 3.0.0.11

**Comment by nilsteampassnet** [comment]
Have you added the AD user inside Teampass?
![ad1](https://user-images.githubusercontent.com/1197546/156912938-4ec873b8-4c87-4a99-ba64-bc4bc7ea6db3.png)

It is required to add the user in Teampass before.
Click on right button
![ad_2](https://user-images.githubusercontent.com/1197546/156913012-38bfa93d-303d-41ee-8f5b-d27f61002880.png)

Then select the user to be added in Teampass
![ad3](https://user-images.githubusercontent.com/1197546/156913037-a8234e51-b006-416b-9f16-7fa2a2f6840c.png)

**Comment by romo2650** [comment]
Can't they be created automatically like in previous versions? Do you plan to add this feature?

**Comment by nilsteampassnet** [comment]
> Can't they be created automatically like in previous versions? Do you plan to add this feature?

It is not a good practice from my point of view because it can have big drawbacks (AD can contain thousands of users, all AD users should perhaps not have access to Teampass, etc.). All companies have different strategies.
What I could improve in the future is a selection with a checkbox to synchronize massively.

**Comment by nilsteampassnet** [comment]
I'm closing this ticket.
