### ISSUE TITLE
Error after upgrade to 3.0.0.9 or 11 --- identify.php 500 Internal Server Error

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3062]
### Steps to reproduce
1. Upgrade from 2.1.27.36 to 3.0.0.11.
2. Login as Administrator or Username

### Expected behaviour
Login to Admin or User interface

### Actual behaviour
login not complete and few errors error:  
1.  CreateRandomString not defined
2. Status Code: 500 Internal Server Error
jquery.min.js:2 POST /sources/identify.php 500 (Internal Server Error)

### Server configuration
**Operating system**: Debian GNU/Linux 11 (bullseye)

**Web server:** Apache/2.4.52 (Debian)

**Database:** mysql Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:** PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )

**Teampass version:**  3.0.0.9 or 3.0.0.11

**Teampass configuration file:**  

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`. [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8154152/tp.config.php.txt)

### Client configuration
**Browser:**  ANY

**Operating system:** ANY

#### Web server error log
```
Insert your webserver log here
```
[teampass_error.log](https://github.com/nilsteampassnet/TeamPass/files/8154175/teampass_error.log)
[teampass_access.log](https://github.com/nilsteampassnet/TeamPass/files/8154177/teampass_access.log)

#### Log from the web-browser developer console (CTRL + SHIFT + i)

```
Insert the log here and especially the answer of the query that failed.
```
 
[IE11-NetworkData.xml.txt](https://github.com/nilsteampassnet/TeamPass/files/8154258/IE11-NetworkData.xml.txt)
 
[teampassHAR-chrome.zip](https://github.com/nilsteampassnet/TeamPass/files/8154290/teampassHAR-chrome.zip)

**Comment by wease1** [comment]
I have one more question - what is the right and proper way to upgrade from TeamPass 2.1.27.10   to last release? 
I'm doing  2.1.27.10  to 2.1.27.36 and 3.0.0.11

**Comment by nilsteampassnet** [comment]
Thank you for reporting.

Can you please share the console logs when this occurs?
To know how to do this, please read https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by nilsteampassnet** [comment]
The error you get
`
    CreateRandomString not defined
    Status Code: 500 Internal Server Error
    jquery.min.js:2 POST /sources/identify.php 500 (Internal Server Error)
`
is for me related to a browser cache issue.
Indeed this function is indeed included in file functions.js.
So if this error is shown then perhaps the broswer cache is not refreshed.

**Comment by wease1** [comment]
thank you,  im successful upgrade from 2.1.27.10 to 3.0.0.16
