### ISSUE TITLE
pace-progress top-right corner blue triangle problems 

### ISSUE THREAD

**Issue by dmotelica** [nilsteampassnet/TeamPass#3066]
pace-progress top-right corner blue triangle keeps showing in Firefox  97.0.1.
the good thing is it disappears in Google Chrome after 2 sec on every page. This is OK.

Could you check this, please?
Thanks.

### Server configuration
Linux CentOS 7.9

**Web server:**
Apache 2.4.6

**PHP version:**
7.4

**Teampass version:** 
3.0.0.12 fresh install

### Client configuration
**Browser:**
Firefox 97.0.1

**Comment by nilsteampassnet** [comment]
How strange.
Testing environment is in same FF version and never noticed any similar behavior.
Have you tried to clear the cache or in a private window?

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by dmotelica** [comment]
Merci beaucoup  Nils!

**Comment by larafj** [comment]
I'm having the same issue.

**Server configuration**
Linux Ubuntu 22.04.1 LTS
**Web server:**
Apache 2.4.52
**PHP version:**
8.1.2-1ubuntu2.8
**Teampass version:**
3.0.0.22 
**Client configuration**
Browser:
Firefox 107.0 (64-bit)

Thanks!
