### ISSUE TITLE
Error after installing the version 3.0.0.13

### ISSUE THREAD

**Issue by jm01b** [nilsteampassnet/TeamPass#3067]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

![image](https://user-images.githubusercontent.com/99717498/156994739-8bfb2c98-a537-4e12-943f-bcdbd0a2cb2c.png)

**Comment by abg-dev** [comment]
Seeing the same problem. Fresh install. 

PHP 7.4.28 + Apache-2.4.6-97 + MariaDB-10.4.15 on Centos 7.9

**Comment by jm01b** [comment]
The issue came after a fresh install.
With version 3.0.0.12 Active Directory users can't log in, but ldap connection seems to be fine. I installed the version 3.0.0.13 and this showed up.

PHP 7.4.28 + Apache-2.4.6-97 + MariaDB-10.4.15 on Oracle Linux 8.5

**Comment by hitenmandalia** [comment]
sames issue with fresh install of 3.0.0.13

**Comment by phil4096** [comment]
Found the problem !  Before installing, edit install/install.queries.php - at line 990 remove "[0]" after "$tmp" .  The mysqli_num_rows() returns an integer, not an array.

**Comment by haseeb-basil-pl** [comment]
Yes, thank you that worked for me

**Comment by jm01b** [comment]
It worked for me too. Thanks

**Comment by nilsteampassnet** [comment]
> Found the problem ! Before installing, edit install/install.queries.php - at line 990 remove "[0]" after "$tmp" . The mysqli_num_rows() returns an integer, not an array.

Absolutely! Thank you @phil4096

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
