### ISSUE TITLE
LDAP Configuration 3.0.0.13 and logging

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3068]
### Steps to reproduce
Fresh install 3.0.0.13 (from source)
1. Trying to populate ldap configuration

### Expected behaviour
LDAP config show users and groups

### Actual behaviour
Always get Error 34 - invalid dn syntax

### Server configuration
**Operating system**:
RHEL8

**Web server:**
Apache httpd-2.4.37
**Database:**

mysql 8.0.26

**PHP version:**
7.4.19

**Teampass version:** 
3.0.0.13

**Teampass configuration file:**
Not needed

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 20.04

### Logs
No logs at all are written
Files are created, but not populated

My ldap config looks like this:
Hosts: ldap.example.com 
LDAP port: 636
Base DN: dc=example,dc=com
Username: empty (anonymous access)
Password: empty (anonymous access)
User Distinguished Name: empty
User name attribute: uid;cn
Additional User DN: 
User Object Filter: (&objectClass=person)(cn=*))
LDAP server type: OpenLDAP
Use LDAP through SSL (LDAPS): yes
Use LDAP through TLS: no

I always get the above error, regardless of entries
Also the documentation lacks with Branch 3
Finding an error is hard, when no logs are written :-(

**Comment by nilsteampassnet** [comment]
Well you have the log error which is
`Error 34 - invalid dn syntax`

The issue doesn't come from Teampass but the configuration.
There would have been an error in the log if an issue not managed occurred which is not the case here.
For what I can see, it is not possible to have an empty user DN

**Comment by useronkel** [comment]
Updated to 3.0.0.14
I've tried to enter dn and uid and memberUid, nothing worked.
Always 'Error 34 - invalid dn syntax'
I'll investigate a little further to find the error ;-)

**Comment by useronkel** [comment]
I'll gave up....
Couldn't find any errors in ldap configuration.
Simplified Configuration:
Base DN: dc=com
Username: technical user with full dn
Password: password
User Distinguished Name: tested with empty, uid, dn, cn, and combinations
User name attribute: uid;cn;sn;mail
Additional User DN: empty

LDAP server type: OpenLDAP
Use LDAP through SSL (LDAPS): yes
User Object Filter:
-> (|(&(objectClass=person)(uid=*))(&(objectclass=posixGroup)(memberUid=*) ) )
-> (&(objectClass=person)(uid=*))
Tested this config with Apache Dierctory Studio.
All configs are correct and gave me the expected results.
I don't have any other idea, what is going wrong...

**Comment by useronkel** [comment]
It was too late and I needed those money....

nvm, I should set a username/password to test anything ;-)
