### ISSUE TITLE
Upgrading from 2.x to 3.0.0.13 - syslog port int expected

### ISSUE THREAD

**Issue by AndreBusse** [nilsteampassnet/TeamPass#3073]
### Steps to reproduce
1. Upgrade to 3.0.0.13 without errors
2. Try to login as admin or user -> Nothing happens
3.

### Expected behaviour
It should login

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: Debian 10

**Web server:** Apache

**Database:** 5.5.5-10.3.31-MariaDB-0+deb10u1

**PHP version:** 7.4.27

**Teampass version:** 3.0.0.13

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Update
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Edge + Firefox

**Operating system:** Win 10

#### Web server error log
[Thu Mar 10 18:26:05.483083 2022] [php7:error] [pid 8258] [client ...:52596] PHP Fatal error:  Uncaught TypeError: socket_sendto() expects parameter 6 to be int, string given in /var/www/html/sources/main.functions.php:1673\nStack trace:\n#0 /var/www/html/sources/main.functions.php(1673): socket_sendto()\n#1 /var/www/html/sources/main.functions.php(1730): send_syslog()\n#2 /var/www/html/sources/identify.php(1617): logEvents()\n#3 /var/www/html/sources/identify.php(332): identifyDoInitialChecks()\n#4 /var/www/html/sources/identify.php(197): identifyUser()\n#5 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 1673, referer: https://teampass.../

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especiall
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8229873/tp.config.php.txt)
y the answer of the query that failed.
```





### Comment, temporary solution

If I change the named parameter to a int value "514" for syslog I can login...
Line change 1673 to a static port:
socket_sendto($sock, $syslog_message, strlen($syslog_message), 0, $host, 514 );

I did not yet search for the paramter source. What / Where to check?
Because this is a test migration I have the source system online while testing.

**Comment by nilsteampassnet** [comment]
Can you please do the next change.

- Open file ./sources/main.functions.php`
- Find
```
    socket_sendto($sock, $syslog_message, strlen($syslog_message), 0, $host, $port);
```
- Replace by
```
    socket_sendto($sock, (string) $syslog_message, strlen($syslog_message), 0, (string) $host, (int) $port);
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
