### ISSUE TITLE
Pre 3.0.0.14 issues

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3076]
Items I recognized:
In includes/config/tp.config.php
The lines with
    'ldap-test-config-username' => '',
    'ldap-test-config-pwd' => '',
won't be nulled, when fields are cleared.
After updating to current master, login no longer possible
In Webconsole an error appears:
Error 404: https://teampass-url/includes/js/CreateRandomString.js
The requested URL was not found on this server.

**Comment by nilsteampassnet** [comment]
I forgot to commit a new file.
And fixed the problem seen.
