### ISSUE TITLE
Cant off maintenance mode

### ISSUE THREAD

**Issue by sferg007** [nilsteampassnet/TeamPass#3078]
### Steps to reproduce
1.Install MariaDB, PHP and Apache
2.Install Teampass
3.Cant off maintenance mode

### Expected behaviour
Maintenance mode is off and I can login via newly created user

### Actual behaviour
When I try to turn off the maintenance mode it turns back on after a few minutes.

### Server configuration
**Operating system**: Ubuntu 20.04 on Proxmox

**Web server:** Apache 2.4.41

**Database:** MariaDB 10.3.34

**PHP version:** 7.4

**Teampass version:** 3.0.0.14

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
```
No errors in the log
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/8239231/tp.config.zip)

**Comment by nilsteampassnet** [comment]
Confirmed and fixed.
Please run upgrade process.

**Comment by sferg007** [comment]
Thanks a lot! You super fast ! :)

**Comment by sferg007** [comment]
Sorry, but i dont get it. I copy new install folder in my teampass directory and go to http://my_teampass_ip/teampass/install/upgrade.php But in the end I again cant off maintenace mode :(
