### ISSUE TITLE
LDAP Syncronization not working

### ISSUE THREAD

**Issue by jcsa1986** [nilsteampassnet/TeamPass#3088]
### Steps to reproduce
1. Configure LDAP settings
2. Go to Users and select LDAP syncronization button
3. Click on List users

### Expected behaviour
App should pull the users from our AD and list them

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.28

**Teampass version:** 3.0.0.14

**Teampass configuration file:** 
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/8265936/tp.config.txt)

**Updated from an older Teampass or fresh install:** Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** Windows 11

#### Web server error log
```
_There is no error related to this action on httpd (Apache) error logs_
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
{error: false, entries: Array(0), ldap_groups: Array(0), teampass_groups: Array(1)}
entries: []
error: false
ldap_groups: []
teampass_groups: [{…}]
[[Prototype]]: Object

_Not sure how to know which query failed..._
```
I have tried every new release since 3.0.0.10 from fresh install, also the Docker image, I've tried upgrading from one version to another, the outcome is always the same. We are not yet on production, we are just trying the software because it looks exactly what we need but LDAP is the option we need the most.

One thing I'm not sure might be the problem is that we have an Apache proxy on front of the app, so we access it https://teampass.mydomain ... Here are the httpd config we are using:

First a redirect:
```
<VirtualHost *:80>
    ServerName teampass.mydomain
    Redirect / https://teampass.mydomain
</VirtualHost>
```

Then the SSL config:
```
<VirtualHost *:443>
     SSLEngine On
     SSLCertificateFile /etc/letsencrypt/live/mydomain/cert.pem
     SSLCertificateKeyFile /etc/letsencrypt/live/mydomain/privkey.pem
     SSLCertificateChainFile /etc/letsencrypt/live/mydomain/fullchain.pem

     ServerAdmin somebody@mydomain
     ServerName teampass.mydomain
     DocumentRoot /var/www/html/teampass
     <Directory "/var/www/html/teampass">
     AllowOverride All
     Options Indexes FollowSymLinks MultiViews
     Require all granted
     </Directory>
     ErrorLog /var/log/httpd/teampass_error.log
     CustomLog /var/log/httpd/teampass_access.log combined
</VirtualHost>
```
Here are some screenshots of what happens:
![image](https://user-images.githubusercontent.com/32680659/158636526-2d7c888e-112b-46c2-ac5d-8c153ea632c8.png)
![image](https://user-images.githubusercontent.com/32680659/158636118-037b7e15-16f6-492b-b765-746f84246886.png)

**Comment by nilsteampassnet** [comment]
Duplicate of #3070

**Comment by jcsa1986** [comment]
Didn't thought it was the same issue... but reading some of the asnwers on #3070 I fixed our problem. Using samacountname and distinguishedname on lower case made the app list the users of LDAP, but now we are not able to create them.

Thank you. I will close this issue and continue to keep track of #3070
