### ISSUE TITLE
DataTables warning: table id=search-results-items - Invalid JSON response in SEARCH

### ISSUE THREAD

**Issue by gmontequi** [nilsteampassnet/TeamPass#3108]
### Steps to reproduce
1. Enter the search window (menu "Search")
2. type a search term into the search field
3.

### Expected behaviour

After entering the search term and click "Enter" all search results should be displayed.

### Actual behaviour
After entering any key a message "DataTables warning: table id=search-results-items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1" is displayed.
If you confirm the popup, the results of the search are displayed.
If you subsequently search for something else, the pop up with the same message appears again.

### Server configuration
**Operating system**:Ubuntu 20.04.3

**Web server:**Apache/2.4.41 (Ubuntu)

**Database:**10.5.13-MariaDB

**PHP version:**PHP: 7.4.3

**Teampass version:** 3.0.0.14 (branch 29/03/2022)

**Teampass configuration file:**

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '0',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://XXXXXXx',
    'favicon' => 'https://XXXXXXx/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'url_to_upload_folder' => 'https://XXXXXXx/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://XXXXXXx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.14',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '["2"]',
    'show_description' => '1',
    'anyone_can_modify' => '1',
    'anyone_can_modify_bydefault' => '1',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'LogoIbsap.png',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1553523109',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.gmail.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => '',
    'email_auth_pwd' => ',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '5',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '600',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/googledrive/Backups_keepass',
    'bck_script_filename' => 'bck_keepass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Madrid',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'def50200317daeb6056e6ce60edfae8c77a70886684340645779e506ecaad5b6f2967f56dea9e73689f26c39422931d2e62f89fbc2f94294680a2d15da382f318bef
5074483fd9b56c29cbb83030f3344e94cbd578a072193d331b8ca72f7e3255c4820201e8c2bab0ab5c3042ac3dbb0a32f28d9bb8f5f9fd6a8',
    'admin_2fa_required' => '0',
    'can_create_root_folder' => '1',
    'enable_massive_move_delete' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'teampass_version' => '2.1.27',
    'password_overview_delay' => '4',
    'roles_allowed_to_print_select' => '[2]',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'email_debug_level' => '0',
);

**Updated from an older Teampass or fresh install:** Updated from 2.1.27.36
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome and edge

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
@nilsteampassnet

**Comment by gmontequi** [comment]
![image](https://user-images.githubusercontent.com/90802409/160607180-f4173002-7a07-4c26-82d7-bd194d167536.png)

Example.

**Comment by Health-TT** [comment]
do you have a solution ?

**Comment by WMedDougJaquays** [comment]
For us on 3.0.0.18 (latest merge available as of right now) on SLES12sp5 using php7.4.6 the error only pops up for certain 1 or 2 character strings. Other 1-2 character strings just filter the list down as expected. Even if we get the error and you click accept, typing in the next character usually filters the list properly for us.

Examples from our installation:
b,f,g,p,v,x,y,2,3,4,6,7,9 all give the error. The rest of the alphabet and numbers do not.
ab,ag,al,an,ap,ar,as,at,be,bs all give the error. The rest of a[a-z,0-9] and b[a-z,0-9] do not.
I couldn't find any 3+ character strings that cause the error.

**Comment by zieba88** [comment]
@gmontequi I solve this same issue by editing tp.config.php
look for this:

change from:
 'cpassman_url' => 'https://teampass3.yourdomain.com/teampass',

change to:
'cpassman_url' => 'https://teampass3.yourdomain.com/',

Hope this helps!
Marcin
