### ISSUE TITLE
the first time you log in, other users' personal folders are visible

### ISSUE THREAD

**Issue by Devastate-D** [nilsteampassnet/TeamPass#3121]
### Steps to reproduce
good afternoon, there may be a bug, I'm using ldap authentication.
The new user, when logging in for the first time, sees the personal folders and passwords of other users, which are displayed as user ids, even if a personal password is set.
If you refresh the page immediately, the folders of other users disappear, and the user folder changes its name from the user id to the correct domain user name.

### Server configuration
**Operating system**: openSUSE Tumbleweed

**Web server:** Apache/2.4.52 

**Database:** 10.6.5-MariaDB MariaDB

**PHP version:** 7.4.27

**Teampass version:**  2.1.27.36

**Teampass configuration file:** 
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/srv/www/htdocs/teampass',
    'cpassman_url' => 'http://10.12.22.221',
    'favicon' => 'http://10.12.22.221/favicon.ico',
    'path_to_upload_folder' => '/srv/www/htdocs/teampass/upload',
    'url_to_upload_folder' => 'http://10.12.22.221/upload',
    'path_to_files_folder' => '/srv/www/htdocs/teampass/files',
    'url_to_files_folder' => 'http://10.12.22.221/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@EXAMPLE.COM',
    'ldap_domain_dn' => 'DC=EXAMPLE,DC=COM',
    'ldap_domain_controler' => 'XXX.XXX.XXX.XXX',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '1',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '636',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '1',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '1',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_login_text' => '',
    'default_language' => 'russian',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1640514905',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/srv/www/htdocs/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '1',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'admin_2fa_required' => '1',
    'ldap_allowed_usergroup' => '',
    'use_http_request_login' => '0',
    'yubico_authentication' => '0',

### Client configuration
**Browser:**  Chrome 99.0.4844.84 

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Devastate-D** [comment]
#2805 
---------- START CODE BLOCK BELOW -----------

if (empty($persoFld['id']) === false && DB::count() > 0) {
if (in_array($persoFld['id'], $listAllowedFolders) === false) {
array_push($_SESSION['personal_folders'], $persoFld['id']);
array_push($listAllowedFolders, $persoFld['id']);
array_push($_SESSION['personal_visible_groups'], $persoFld['id']);

                // get all descendants
                // FIX get only children
                $ids = $tree->getDescendants($persoFld['id'], false,true);
                foreach ($ids as $ident) {
                    if ((int) $ident->personal_folder === 1) {
                        array_push($listAllowedFolders, $ident->id);
                        array_push($_SESSION['personal_visible_groups'], $ident->id);
                        array_push($_SESSION['personal_folders'], $ident->id);
                    }
                }
            }
        }
---------- END CODE BLOCK BELOW -----------

The actual change is quite simple. its only one line in that block and only one word
$ids = $tree->getDescendants($persoFld['id'], false,**true**);

In my original version that line ended
['id'], false);

after adding true, personal folders stopped being visible, it works for me

**Comment by EverNaughty** [comment]
> #2805 ---------- START CODE BLOCK BELOW -----------
> 
> if (empty($persoFld['id']) === false && DB::count() > 0) { if (in_array($persoFld['id'], $listAllowedFolders) === false) { array_push($_SESSION['personal_folders'], $persoFld['id']); array_push($listAllowedFolders, $persoFld['id']); array_push($_SESSION['personal_visible_groups'], $persoFld['id']);
> 
> ```
>             // get all descendants
>             // FIX get only children
>             $ids = $tree->getDescendants($persoFld['id'], false,true);
>             foreach ($ids as $ident) {
>                 if ((int) $ident->personal_folder === 1) {
>                     array_push($listAllowedFolders, $ident->id);
>                     array_push($_SESSION['personal_visible_groups'], $ident->id);
>                     array_push($_SESSION['personal_folders'], $ident->id);
>                 }
>             }
>         }
>     }
> ```
> 
> ---------- END CODE BLOCK BELOW -----------
> 
> The actual change is quite simple. its only one line in that block and only one word $ids = $tree->getDescendants($persoFld['id'], false,**true**);
> 
> In my original version that line ended ['id'], false);
> 
> after adding true, personal folders stopped being visible, it works for me

Hello here, after editing this, did you do something more ? Restart the server or any service ?

**Comment by Devastate-D** [comment]
> > #2805 ---------- START CODE BLOCK BELOW -----------
> > if (empty($persoFld['id']) === false && DB::count() > 0) { if (in_array($persoFld['id'], $listAllowedFolders) === false) { array_push($_SESSION['personal_folders'], $persoFld['id']); array_push($listAllowedFolders, $persoFld['id']); array_push($_SESSION['personal_visible_groups'], $persoFld['id']);
> > ```
> >             // get all descendants
> >             // FIX get only children
> >             $ids = $tree->getDescendants($persoFld['id'], false,true);
> >             foreach ($ids as $ident) {
> >                 if ((int) $ident->personal_folder === 1) {
> >                     array_push($listAllowedFolders, $ident->id);
> >                     array_push($_SESSION['personal_visible_groups'], $ident->id);
> >                     array_push($_SESSION['personal_folders'], $ident->id);
> >                 }
> >             }
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ---------- END CODE BLOCK BELOW -----------
> > The actual change is quite simple. its only one line in that block and only one word $ids = $tree->getDescendants($persoFld['id'], false,**true**);
> > In my original version that line ended ['id'], false);
> > after adding true, personal folders stopped being visible, it works for me
> 
> Hello here, after editing this, did you do something more ? Restart the server or any service ?
after fixing the code, nothing needs to be reloaded.
