### ISSUE TITLE
Cannot modify entries after upgrade from 2.1.27.37 to 3.0.0.14

### ISSUE THREAD

**Issue by ewheelerinc** [nilsteampassnet/TeamPass#3122]
### Steps to reproduce
1. Update from Teampass 2.1.27.37 to 3.0.0.14
2. Run user key conversion
3. Try to modify an existing entry with a user that has appropriate permissions

### Expected behaviour
Entry should be successfully updated

### Actual behaviour
Error occurs indicating inappropriate permissions:

"Expected level of security not reached!"

### Server configuration
**Operating system**: Oracle Linux 8

**Web server:** Apache 2.4.37

**Database:** MariaDB

**PHP version:** 10.3.28

**Teampass version:** 3.0.0.14

**Teampass configuration file:**
[tp.config.php.gz](https://github.com/nilsteampassnet/TeamPass/files/8429433/tp.config.php.gz)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox 91.5.0esr

**Operating system:** Linux

#### Web server error log
No log output was generated in this process

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
CHANGED FIELDS index.php:5699:47
Array []
​
length: 0
​
<prototype>: Array []
index.php:5700:47
SAVING DATA index.php:5853:55
Object { anyone_can_modify: 0, complexity_level: 26, description: "[REDACTED]", diffusion_list: [], folder: 64, email: "", fields: [], folder_is_personal: 0, id: 251, label: "[REDACTED]", … }
​
anyone_can_modify: 0
​
complexity_level: 26
​
description: "[REDACTED]"
​
diffusion_list: Array []
​
email: ""
​
fa_icon: ""
​
fields: Array []
​
folder: 64
​
folder_is_personal: 0
​
id: 251
​
label: "[REDACTED]"
​
login: "[REDACTED]"
​
pw: "[REDACTED]"
​
restricted_to: Array []
​
restricted_to_roles: Array []
​
tags: ""
​
template_id: NaN
​
to_be_deleted_after_date: ""
​
to_be_deleted_after_x_views: ""
​
uploaded_file_id: ""
​
url: ""
​
user_id: 10000001
​
<prototype>: Object { … }
index.php:5854:55
RETURNED DATA index.php:5897:63
Object { error: true, message: "Expected level of security not reached!" }
​
error: true
​
message: "Expected level of security not reached!"
​
<prototype>: Object { … }
index.php:5898:63
```

**Comment by nilsteampassnet** [comment]
What is the level of complexity requested by the folder in which the item you are modifying in?
![image](https://user-images.githubusercontent.com/1197546/162138125-f8b9cbb1-dfda-494d-bba3-d1ae2352cece.png)

**Comment by ewheelerinc** [comment]
The password strength is Medium, but above where it says "Required password strength", the strength itself is missing
![Screenshot at 2022-04-11 10-03-54](https://user-images.githubusercontent.com/1338867/162792680-71f58dfb-e9b9-41fa-aabf-aa6399825310.png)
.

**Comment by ewheelerinc** [comment]
How might we resolve the issue of the missing required password strength, assuming that is what is causing us issues?

**Comment by ewheelerinc** [comment]
We were able to resolve the issue by flattening password strength requirements across the board. We used this SQL command to do so, since there was not an easy way to apply the change to all items in a directory:

UPDATE teampass_misc SET valeur = 0 WHERE type = 'complex';
