### ISSUE TITLE
Encoding error in password (v 3.0.0.16)

### ISSUE THREAD

**Issue by loutremaline** [nilsteampassnet/TeamPass#3126]
### Steps to reproduce
1. Change a existing password to a new one containing at least one accented character.
2. View or copy the new updated password.

### Expected behaviour
The accented character is correctly encoded.

### Actual behaviour
The accented character is incorrectly encoded.

### Server configuration
**Operating system**: Custom docker image

**Web server:** NGinx

**Database:** MariaDB 10.3.34

**PHP version:** 8.0.13

**Teampass version:** 3.0.0.16

**Updated from an older Teampass or fresh install:** updated from 2.1.27.36 (no problem) to 3.0.0.14 (encoding problem) to 3.0.0.16 (encoding problem)

### Client configuration
**Browser:** Latest Chrome and latest Firefox

**Operating system:** Linux Mint

![Capture d’écran du 2022-04-11 11-44-17](https://user-images.githubusercontent.com/61687727/162716335-f82e6349-688f-4d3c-88d8-daf4008b30a0.png)

![Capture d’écran du 2022-04-11 11-45-11](https://user-images.githubusercontent.com/61687727/162716371-b7e8b022-55a0-4368-a74a-57159e4f3e8f.png)

**Comment by dagr2** [comment]
I was able to fix it by changing two lines in pages/items.js.php

Line 3567: atob(data.password) --> atob(data.password).utf8Decode()
Line 4331: (data.pw) --> (data.pw).utf8Decode()

**Comment by loutremaline** [comment]
I replayed my test case after adding the 2 changes and it works. Thanks.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
