### ISSUE TITLE
Password Items are not loading while being logged as an AD User

### ISSUE THREAD

**Issue by AMS-VITS** [nilsteampassnet/TeamPass#3139]
### Steps to reproduce
1. Logging to Teampass as an AD synchronized user.
2. Open an imported / or created folder
3. Try to open a password entry (or to try to copy a password)

### Expected behaviour
As an AD logged user, to be able to retrieve password entries and copy passwords if needed.

### Actual behaviour
As an AD logged user, while trying to open a password Entry it gets stuck with a miniwindow saying "Loading item...". All permissions have been checked and the user should be able to see the passwords.

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache
**Database:**
5.5.5-10.3.34-MariaDB
**PHP version:**
7.4.3
**Teampass version:** 
3.0.0.17
**Teampass configuration file:**
<VirtualHost *:80>
     ServerAdmin XXXX
     DocumentRoot /var/www/html/TeamPass
     ServerName XXXX

     <Directory /var/www/html/TeamPass>
          Options FollowSymlinks
          AllowOverride All
          Require all granted
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/teampass_error.log
     CustomLog ${APACHE_LOG_DIR}/teampass_access.log combined

</VirtualHost>

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (

     'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'http://172.24.7.4/TeamPass',
    'favicon' => 'http://172.24.7.4/TeamPass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'http://172.24.7.4/TeamPass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.17',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'cn',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',

     'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlv>
    'send_stats_time' => '1648022428',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '10.34.98.27',
    'email_smtp_auth' => '0',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@viseo.com',
    'email_from_name' => 'VISEO - TeamPass',
        'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Viseo PMS Teampass',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',

    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '25fErR7np28z8FhQ7V6LsUtLc6qve3qfEkxPzTgD',
    'admin_2fa_required' => '0',
    'password_overview_delay' => '10',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '1',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ldap_hosts' => '172.22.1.4',
    'ldap_bdn' => 'DC=viseoamsiberia,DC=onmicrosoft,DC=com',
    'ldap_username' => 'CN=Join Domain,OU=AADDC Users,DC=viseoamsiberia,DC=onmicrosoft,DC=com',
    'ldap_password' => 'Viseoadmin2022.',
    'ldap_user_object_filter' => '(&(objectCategory=person)(objectclass=user)(mail=*))',
    'ldap_user_dn_attribute' => 'distinguishedName',
    'ldap_dn_additional_user_dn' => 'OU=AADDC Users',
    'ga_reset_by_user' => '0',
);

### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Win10
#### Web server error log
```
Couldn't see an error
Insert your webserver log here
```
Couldn't see an error
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

Thank you in advance for your help. If you need something else from our side do not hesitate to ask.

Kind regards

**Comment by AMS-VITS** [comment]
Closed

**Comment by AMS-VITS** [comment]
Had an error and just reopened the case.

**Comment by nilsteampassnet** [comment]
@AMS-VITS 
Please try to reproduce and follow instructions in [](https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console) in order to share the answer from the server?
Perhaps will we have some data to understand your case.

**Comment by AMS-VITS** [comment]
Hello Nils,

I have been doing tests and it looks like when I synchronize a new user from the Azure AD it's encryption code is not beign generated on the first try (it gets stuck generating keys but it does not anything). 

Then, when I delete the user and resynchronize it again the encryption code gets generated properly and I am able to load the password items.

At this moment I am a bit busy with other work endeavours but I will try to reproduce the error trying to capture the query errors with the link you have sent me. 

Thank you for your time!

**Comment by AMS-VITS** [comment]
Hello Nils, 

Fortunately I've been having time during this morning in order to check what you've sent me with the instructions. The test have been performed while trying to open a password item. Logs are the following:

Response
-------------
This request has no response data available.

Headers
----------
Request URL: http://172.24.7.4/TeamPass/sources/items.queries.php
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 172.24.7.4:80
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-cache, must-revalidate
Connection: close
Content-Length: 3
Content-Type: text/html; charset=utf-8
Date: Wed, 04 May 2022 11:12:48 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache/2.4.41 (Ubuntu)
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9,en;q=0.8,ru;q=0.7,fr;q=0.6
Connection: keep-alive
Content-Length: 281
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: KEY_teampass_session=yeP5eyrEZg1iTsVrG0eZyz98SpjXLRsI9zV1uJTC7mKxwn%2Fjp2vXhE%2BYn6Ayrqz8o2MxCks2s0%2FbCwifEvy7Yg%3D%3D; teampass_session=qoqn0fag33nbj9hf07g0svi6sh; jstree_select=136
Host: 172.24.7.4
Origin: http://172.24.7.4
Referer: http://172.24.7.4/TeamPass/index.php?page=items
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
X-Requested-With: 

I look forward to hear from you. If you need something else do not hesitate to ask me.

Kind regards,

**Comment by AMS-VITS** [comment]
Hello @nilsteampassnet ,

I think I can provide more info about the Teampass' Server issues that we are experiencing.

Probably we are having issues related to the User's Encryption codes that are being generated. The steps that I am doing are the following 

1 - Synchronize LDAP
2 - Add User from Azure AD
3 - Teampass tries to generate it's encryption code (It gets stuck in loop...)
4 - I refresh the web
5-  I assign the role that belongs tothe user
6 - Generates it's encryption code (Now it's all good)
7 - Log into the server as the new user. I put my password and Encryption Code (all good)
8 - I browse some password folders and items
9 - After some browser stuff Teampass says the following:
            - We need to renecrypt your keys to fit the privileges corresponding to your account and rights.
10 - After putting my password and encryption code it gets stuck there and I cannot access password items anymore

Do not hesitate to ask me if you need me to test something and give you any kind of logs.

Any help is appreciated. 

Kind regards,

**Comment by rrgadeev** [comment]
you need to set up mail, keys are sent to email

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
