### ISSUE TITLE
Search does not work v3.0.0.16

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3140]
### Page on which it happened
index.php?page=search#

### Steps to reproduce
1. Click SEARCH button 
![image](https://user-images.githubusercontent.com/12623112/165901626-c50e367b-5164-4137-9f95-a7b762fca5b1.png)

2. Open right windows
3.

### Expected behaviour
Open right windows 

### Actual behaviour
popup window with error 
![image](https://user-images.githubusercontent.com/12623112/165901684-5ee011a0-7038-4c70-8835-7fae35e3284f.png)

DataTables warning: table id=search-results-items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### Server configuration
**Operating system**: Linux teampass 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64

**Web server:** Apache/2.4.53 (Debian)

**Database:** 5.5.5-10.5.15-MariaDB-0+deb11u1

**PHP version:** 7.4.28

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/pass',
'cpassman_url' => 'http://<anonym_url>
'favicon' => 'http://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/pass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/pass/files',
'url_to_files_folder' => 'http://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '["1"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '9',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1512900881',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '20mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '1000',
'upload_imageresize_height' => '900',
'upload_imageresize_quality' => '99',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '600',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/pass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '1',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '1',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Moscow',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'max_last_items' => '20',
'enable_massive_move_delete' => '0',
'copy_to_clipboard_small_icons' => '1',
'offline_key_level' => '25',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'admin_2fa_required' => '1',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'password_overview_delay' => '9',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'maintenance_mode' => '0',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 93.0.4577.63

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

#### Web server error log
```
Undefined index: path - /var/www/pass/sources/main.queries.php (1106)
```

#### Teampass 10 last system errors
```


#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

teampassDevelopLog
[teampassDevelopLog.zip](https://github.com/nilsteampassnet/TeamPass/files/8638120/teampassDevelopLog.zip)

**Comment by nilsteampassnet** [comment]
@wease1 
Can you please follow https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console and provide the server output for analysis.
I believe a character is badly encoded somewhere which corrupts the server answer.
Can you also search in your items if you can see kind of strange characters?
Thank you

**Comment by wease1** [comment]
developer tools save lo
[teampassDevelopLog.zip](https://github.com/nilsteampassnet/TeamPass/files/8638115/teampassDevelopLog.zip)
g

**Comment by nilsteampassnet** [comment]
@wease1 
Thank you for the file but I have no error in this file.
You need to provide me this just after facing the issue (no page refresh) to keep the requests

**Comment by nilsteampassnet** [comment]
@wease1 
Thank you for the file.
Each time you do a search you have this derror dialogbox poping out?

**Comment by nilsteampassnet** [comment]
@wease1 
I provided a fix.
Can you plese give a try?

**Comment by wease1** [comment]
select * from dbpass_items where id = 1927 ;
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------+-------+--------+------+---------+-------+-------+---------+---------------+-------------------+-------+--------------+-----------+------------------+---------------------------+---------------------------+-----------------+---------+
| id   | label                                                                                                                                                                | description | pw                       | pw_iv | pw_len | url  | id_tree | perso | login | inactif | restricted_to | anyone_can_modify | email | notification | viewed_no | complexity_level | auto_update_pwd_frequency | auto_update_pwd_next_date | encryption_type | fa_icon |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------+-------+--------+------+---------+-------+-------+---------+---------------+-------------------+-------+--------------+-----------+------------------+---------------------------+---------------------------+-----------------+---------+
| 1927 |        Ð£Ñ‡ÐµÑ‚Ð½Ð°Ñ� Ð·Ð°Ð¿Ð¸Ñ�ÑŒ SA SQL Ð½Ð° Ð½Ð¾Ð²Ñ‹Ñ… Ñ�ÐµÑ€Ð²ÐµÑ€Ð°Ñ… (srv-01-erp-dev, srv-01-erp-prd)                                                                |             | 0Z73tBx3aQIE6PIRDevuWQ== |       |      0 |      | 514     |     0 | sa    |       0 |               |                 0 |       |              |        17 | 61               |                         0 | 0                         | teampass_aes    | NULL    |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+--------------------------+-------+--------+------+---------+-------+-------+---------+---------------+-------------------+-------+--------------+-----------+------------------+---------------------------+---------------------------+-----------------+---------+

**Comment by wease1** [comment]
Thnx. Im rename Label of this item  in UTF-8 encoding and all work good

**Comment by wease1** [comment]
and replace files  search.js.php and find.queries.php from the 3.0.0.17 release, all work good
