### ISSUE TITLE
php 8.0 requirement

### ISSUE THREAD

**Issue by SlyRab** [nilsteampassnet/TeamPass#3147]
Main.function.php contains union type of declaration. It has been avaible since php 8.0
I spend my whole day to understand why it's not working :(

ustal sho pizdec

**Comment by Nachtlichtermeer** [comment]
same here

last working commit vor PHP 7.4 ist 5bf2933b4feb5beb0e05c1d113ff4c6b7d80144d

**Comment by nilsteampassnet** [comment]
I've removed until now the specific PHP8 syntax.
