### ISSUE TITLE
Fresh Install on centos 7.9 php 7.4.29 no error on install but cant login , only "in pregress " message

### ISSUE THREAD

**Issue by maxnux-ar** [nilsteampassnet/TeamPass#3151]
### Steps to reproduce
1.Fresh Install no error ,
2.
3.

### Expected behaviour
Tell us what should happen
cant login
### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
cento 7.9
**Web server:**
apache 2.4.6
**Database:**
mariaDb 15.1

**PHP version:**
7.4
**Teampass version:** 
.17
**Teampass configuration file:**

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

#### Web server error log

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/TeamPass/sources/main.queries.php on line 196, referer: https://tp.srv.local
[Thu May 05 18:06:18.153795 2022] [php7:error] [pid 62952] [client 190.1.53.11:35570] PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/TeamPass/sources/identify.php on line 827, referer: https://tp.srv.localcat 

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8636085/tp.config.php.txt)

**Comment by maxnux-ar** [comment]
if i copy that files "main.queries.php , identify.php" from previus install , git clone , now work ?????????????

**Comment by lanaparadinha** [comment]
same error here!
[Fri May 06 09:28:07.894676 2022] [php7:error] [pid 23076] [client 172.31.200.3:55361] PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/teampass/sources/identify.php on line 827, referer: http://192.168.231.7/

**Comment by lanaparadinha** [comment]
Resolved in [#3129](https://github.com/nilsteampassnet/TeamPass/issues/3129)

**Comment by maxnux-ar** [comment]
i made a  new install and error persist

> Resolved in [#3129](https://github.com/nilsteampassnet/TeamPass/issues/3129)

**Comment by lanaparadinha** [comment]
you read issue 3129?
i file /var/www/foo/htdocs/teampass/sources/identify.php
remove "coma"
     $userInfoLogin,
     $userInfoLastConnection,
     $username,
-    $SETTINGS**,**
+    $SETTINGS
 ) : array
 {
     $rows = DB::query(

In file /var/www/foo/htdocs/teampass/sources/tree.php
remove "coma"

     array $session_groupes_visibles,
     array $listFoldersLimitedKeys,
-    array $listRestrictedFoldersForItemsKeys**,**
+    array $listRestrictedFoldersForItemsKeys
 ): bool
 {

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
