### ISSUE TITLE
LDAP Sync not working (again) with latest commit

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3155]
### Steps to reproduce
1. Setting LDAP config
2. Testing authentication -> Success
3. Try to add user with ldap synchronization fails

### Server configuration
**Operating system**:
RHEL8

**Web server:**
Apache

**Database:**
mySQL8

**PHP version:**
7.4.19

**Teampass version:** 
[Latest Commit](https://github.com/nilsteampassnet/TeamPass/commit/9a1f954af42c53705ce71ed39436315f4affb228)
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
#### Web server error log
```
[09-May-2022 22:07:13 UTC] PHP Fatal error:  Uncaught ErrorException: ldap_search(): Search: Invalid DN syntax in ./includes/libraries/LdapRecord/Ldap.php:235
Stack trace:
#0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}(2, 'ldap_search(): ...', '/shortended', 235, Array)
#1 shortended/includes/libraries/LdapRecord/Ldap.php(235): ldap_search(Resource id #7, ',ou=users,dc=ec...', '(uid=*)', Array, false, 0, 0, 0)
#2 shortended/includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}()
#3 shortended/includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\Ldap->executeFailableOperation(Object(Closure))
#4 shortended/includes/libraries/LdapRecord/Query/Builder.php(656): LdapRecord\Ldap->search(',ou=users,dc=ex...', '(uid=*)', Array, false, 0)
#5 shortended/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\Query\Builder->LdapRecord\Query\{closure}(Ob in shortended/includes/libraries/LdapRecord/LdapRecordException.php on line 26
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
host | <shortended>
filename | /sources/users.queries.php
```
Insert the log here and especially the answer of the query that failed.
```
Status 500
Internal Server Error
Version HTTP/1.1

```

**Comment by nilsteampassnet** [comment]
The error shows : Search: Invalid DN syntax

**Comment by useronkel** [comment]
Sry, of course ;-)
```
    'ldap_mode' => '1',
    'ldap_type' => 'OpenLDAP',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'uid',
    'ldap_ssl' => '1',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '636',
    'richtext' => '0',
    'ldap_and_local_authentication' => '1',
    'ldap_hosts' => 'ldap.example.com,bck.ldap.example.com',
    'ldap_bdn' => 'ou=users,dc=example,dc=com',
    'ldap_username' => '',
    'ldap_new_user_role' => '51',
    'ldap_password' => '',
    'ldap_user_object_filter' => '(&(objectClass=person)(uid=*))',
```

**Comment by nilsteampassnet** [comment]
ldap_username and ldap_password are filled in in your settings, correct?

Shouldn't 'ldap_bdn' => 'ou=users,dc=example,dc=com', be 'ldap_bdn' => 'ou=users,dc-ldap,dc=example,dc=com',?

**Comment by useronkel** [comment]
Hi.
Nope, the base dn is correct (not my fault to be stat stupid ;-)) 
We do not need username and password to access the ldap, it's an anon access from special hosts (mine included).
I'll start from scratch, perhaps there is something I did wrong

**Comment by useronkel** [comment]
Unfortunately the same error appears also with latest commit.
Exactly the same error message.
If I try to test an authentication, all went well, user is authenticated.
When I try to use the sync feature, the error appears

**Comment by nilsteampassnet** [comment]
@useronkel 
In latest commit, there was no change on sync feature.
Latest change on this part was done the 30 April.
You get the exact same error ?

**Comment by useronkel** [comment]
Hi Nils.
There is a similar msg now, that is slightly different from the first:
```
Fatal error: Uncaught ErrorException: ldap_search(): Search: Invalid DN syntax in .../includes/libraries/LdapRecord/Ldap.php:235
Stack trace:
#0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}()
#1 .../includes/libraries/LdapRecord/Ldap.php(235): ldap_search()
#2 .../includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}()
#3 .../includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\Ldap->executeFailableOperation()
#4 .../includes/libraries/LdapRecord/Query/Builder.php(656): LdapRecord\Ldap->search()
#5 .../includes/libraries/LdapRecord/Connection.php(394): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#6 .../includes/libraries/LdapRecord/Connection.php(352): LdapRecord\Connection->runOperationCallback()
#7 .../includes/libraries/Ld in .../includes/libraries/LdapRecord/LdapRecordException.php on line 26
```
In trace #4 there is now no content in call Ldap->search(), in my first msg there was an other information inside the ():
```
#4 shortended/includes/libraries/LdapRecord/Query/Builder.php(656): LdapRecord\Ldap->search(',ou=users,dc=ex...', '(uid=*)', Array, false, 0)
```

Beside this, the same error appears if I try to sync users from ldap

**Comment by useronkel** [comment]
Found it :-)
In Line 2458 you are assembling the query for the sync:
```
                ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
```
but it will fail, if the ldap_dn_additional_user_dn is empty (it's set, but empty).
Changing the line to:
```
                ->in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
```
fixes the problem and all users are listed

**Comment by jonildosantos** [comment]
> >in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])



> Found it :-) In Line 2458 you are assembling the query for the sync:
> 
> ```
> ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> ```
> 
> but it will fail, if the ldap_dn_additional_user_dn is empty (it's set, but empty). Changing the line to:
> 
> ```
> ->in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> ```
> 
> fixes the problem and all users are listed

This fix work for me!
Thanks!

**Comment by useronkel** [comment]
-> fixed with [#3258](https://github.com/nilsteampassnet/TeamPass/issues/3258)

**Comment by aphillips-DES** [comment]
> Found it :-) In Line 2458 you are assembling the query for the sync:
> 
> ```
> ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> ```
> 
> but it will fail, if the ldap_dn_additional_user_dn is empty (it's set, but empty). Changing the line to:
> 
> ```
> ->in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> ```
> 
> fixes the problem and all users are listed

Where does this change need to be made? I get the "500 (Internal Server Error)" when clicking "LDAP synchronization" it just continues to say in progress

**Comment by useronkel** [comment]
> > Found it :-) In Line 2458 you are assembling the query for the sync:
> > ```
> > ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but it will fail, if the ldap_dn_additional_user_dn is empty (it's set, but empty). Changing the line to:
> > ```
> > ->in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes the problem and all users are listed
> 
> Where does this change need to be made? I get the "500 (Internal Server Error)" when clicking "LDAP synchronization" it just continues to say in progress

Hi.
As mentioned earlier: The error comes from .../sources/user.queries.php but was fixed.
I'll get no error furthermore. There are still other bugs, but they won't affect the running server (for me)

**Comment by LaiaRos** [comment]
> 

That works for me too, thanks!

**Comment by useronkel** [comment]
> > 
> 
> That works for me too, thanks!

You are very welcome :-)
