### ISSUE TITLE
[3.0.0.17] Tree Loading stuck

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#3158]
### Steps to reproduce
1.Login as user
2.View Tree

### Expected behaviour
View Folders

### Actual behaviour
Folders Loading stuck

<img width="730" alt="Screenshot 2022-05-12 170724" src="https://user-images.githubusercontent.com/4628571/168094380-33d1fb74-bb7d-428a-b07e-becf23e8ce94.png">

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache/2.4.41 (Ubuntu)
**Database:**
mysql  Ver 15.1 Distrib 10.7.3-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
PHP 7.4.3
**Teampass version:** 
version 3.0.0.17
**Teampass configuration file:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.txt](https://github.com/nilsteampassnet/TeamPass/files/8679688/tp.txt)

**Updated from an older Teampass or fresh install:**
Fresh

### Client configuration
**Browser:**
Chrome, Edge
**Operating system:**
Windows 11
#### Web server error log
```
Thu May 12 13:47:59.634232 2022] [php7:error] [pid 2891] [client 192.168.xx.58:63893] PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/Teampass/sources/tree.php on line 224, referer: http://192.168.xx.89/Teampass/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
DevTools failed to load source map: Could not load content for http://192.168.xx.89/Teampass/plugins/summernote/summernote-bs4.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

GET http://192.168.xx.89/Teampass/sources/tree.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
_load_node @ jstree.min.js:2
load_node @ jstree.min.js:2
init @ jstree.min.js:2
a.jstree.create @ jstree.min.js:2
(anonymous) @ jstree.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.jstree @ jstree.min.js:2
(anonymous) @ index.php?page=items:3209


```

**Comment by well-souza** [comment]
Same problem here

**Comment by chrysochos** [comment]
Remove the comma at the end of line 224 of  /var/www/html/teampass/sources/tree.php

    array $listRestrictedFoldersForItemsKeys

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by 4ku** [comment]
Still have this issue

**Comment by CrazyNeo89** [comment]
I have this problem on version 3.0.0.18
Teampass error log:
PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/TeamPass/sources/tree.php>

On string 
array $listRestrictedFoldersForItemsKeys 
No comma

Please help.

**Comment by tdtmusic2** [comment]
Same issue here, also 3.0.0.18. This is the error in the log:

`[Tue Jun 21 11:32:42.688796 2022] [proxy_fcgi:error] [pid 39719] [client 10.1.0.122:2076] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: loadTreeStrategy(): Argument #2 ($userTreeLastRefresh) must be of type int, null given, called in /var/www/html/TeamPass/sources/tree.php on line 134 and defined in /var/www/html/TeamPass/sources/tree.php:1023\nStack trace:\n#0 /var/www/html/TeamPass/sources/tree.php(134): loadTreeStrategy()\n#1 {main}\n  thrown in /var/www/html/TeamPass/sources/tree.php on line 1023', referer: http://10.1.0.105/TeamPass/index.php?page=items
`

**Comment by carlosmatthews** [comment]
same issue here. Log Apache
`[Wed Jun 29 10:37:36.233677 2022] [proxy_fcgi:error] [pid 3299:tid 140711257114368] [client 10.68.18.20:2159] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /var/www/html/teampass/sources/tree.php:957\nStack trace:\n#0 /var/www/html/teampass/sources/tree.php(957): array_keys()\n#1 /var/www/html/teampass/sources/tree.php(756): prepareNodeData()\n#2 /var/www/html/teampass/sources/tree.php(680): handleNode()\n#3 /var/www/html/teampass/sources/tree.php(846): recursiveTree()\n#4 /var/www/html/teampass/sources/tree.php(680): handleNode()\n#5 /var/www/html/teampass/sources/tree.php(205): recursiveTree()\n#6 {main}\n  thrown in /var/www/html/teampass/sources/tree.php on line 957', referer: http://10.68.16.200/index.php?page=items
