### ISSUE TITLE
After fresh install there are missing variables in tp.config.php

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3169]
Hi.
After a full new install including a database wipe and setting all options new, there is a little problem.
The variables ldap_username and ldap_password are not set in tp.config.php.
With my installation, there is no need to provide a username and a password to connect to the ldap, the access is anonymous. Therefore the corrosponding fields in the ldap setup are empty.
When I now try to check credentials, following notice is upcoming:
```
Notice: Undefined index: ldap_username in .../sources/users.queries.php on line 2408
Notice: Undefined index: ldap_password in .../sources/users.queries.php on line 2409
```
The same notices appear, if I try to add users with ldap synchronization.

**Comment by nilsteampassnet** [comment]
I missed them.
I will add
Thanks

**Comment by useronkel** [comment]
Fixed, ty :-)
