### ISSUE TITLE
Unable to create a user

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3174]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1. Create New User
2. Error with Caution
3.

### Expected behaviour
Error with Caution
![image](https://user-images.githubusercontent.com/12623112/169509154-cc67d1d1-8016-448e-80e2-7b23da9a46cf.png)

### Actual behaviour
New Usew Created

### Server configuration
**Operating system**: Linux teampass 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64

**Web server:** Apache/2.4.53 (Debian)

**Database:** 5.5.5-10.5.15-MariaDB-0+deb11u1

**PHP version:** 7.4.28

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/pass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/pass/upload',
'url_to_upload_folder' => 'http://pass.naukanet.ru/upload',
'path_to_files_folder' => '/var/www/pass/files',
'url_to_files_folder' => 'http://pass.naukanet.ru/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'sAMAccountName',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '["1"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '9',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1512900881',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '20mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '1000',
'upload_imageresize_height' => '900',
'upload_imageresize_quality' => '99',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '600',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/pass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '1',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '1',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Moscow',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'max_last_items' => '20',
'enable_massive_move_delete' => '0',
'copy_to_clipboard_small_icons' => '1',
'offline_key_level' => '25',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'admin_2fa_required' => '1',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'password_overview_delay' => '9',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'maintenance_mode' => '0',
'ldap_hosts' => '10.1.3.150',
'ldap_bdn' => 'ou=ToProxy, cn=ToProxy,dc=nauka,dc=net',
'ldap_username' => 'jasperid',
'ldap_password' => 'aNCeYncoUToR22',
'ldap_dn_additional_user_dn' => 'ou=ToProxy; cn=ToProxy',
'duo_ikey' => 'Admin',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 93.0.4577.63

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

### Logs
teampass_error.log

[Fri May 20 13:31:52.735875 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include(../../../config/tp.config.php): failed to open stream: No such file or directory in /var/www/pass/includes/libraries/Database/Meekrodb/db.class.php on line 979, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:31:52.735961 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/includes/libraries/Database/Meekrodb/db.class.php on line 979, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:31:52.735995 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /var/www/pass/sources/main.functions.php on line 1519, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:31:52.736004 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/sources/main.functions.php on line 1519, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:31:52.736027 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/pass/sources/main.functions.php on line 1530, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:31:52.736035 2022] [php7:warn] [pid 124932] [client 192.168.21.55:61031] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/sources/main.functions.php on line 1530, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332039 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include(../../../config/tp.config.php): failed to open stream: No such file or directory in /var/www/pass/includes/libraries/Database/Meekrodb/db.class.php on line 979, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332097 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/includes/libraries/Database/Meekrodb/db.class.php on line 979, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332129 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /var/www/pass/sources/main.functions.php on line 1519, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332139 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/sources/main.functions.php on line 1519, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332160 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/pass/sources/main.functions.php on line 1530, referer: http://pass.naukanet.ru/index.php?page=users
[Fri May 20 13:34:06.332167 2022] [php7:warn] [pid 124948] [client 192.168.21.55:63329] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/php') in /var/www/pass/sources/main.functions.php on line 1530, referer: http://pass.naukanet.ru/index.php?page=users

#### Web server error log
```
Undefined index: path - /var/www/pass/sources/main.queries.php (1106)
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especiall
[teampassUserCreate.zip](https://github.com/nilsteampassnet/TeamPass/files/8738637/teampassUserCreate.zip)
y the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Fresh install?
Use latest 3.0.0.17
