### ISSUE TITLE
Import KeePass with '\' caracter 

### ISSUE THREAD

**Issue by Health-TT** [nilsteampassnet/TeamPass#3175]
Hi,

I have a probleme with import XML file (exported KeePass).

Many entries have a caractere "\". This entries is not integrated in TeamPass.

Not visible in Password and when search entrie i have JSON error 👍 
![image](https://user-images.githubusercontent.com/105799666/169524014-5637f4a7-e081-41ed-9881-23935df12491.png)

do you have any idea for debug that ?

**Comment by nilsteampassnet** [comment]
It is an old heritage that has no more any need.
I have removed them.

Please reopen this ticket on need.

**Comment by Health-TT** [comment]
Hi,

I have a problem.

In KeePass, when a folder contains an empty folder and a key after, TP do not import ce folder.
Problem on the recurse function.

![image](https://user-images.githubusercontent.com/105799666/169814780-eadbb08e-d663-42e5-8417-e89e6f97dcbb.png)


The search menu is not fonctionnal when a searshing one entry with '\' caractere  --> Error JSON

i found the good entrie when i devellop the folder in the password menu.

would you like a new issue for that ?
