### ISSUE TITLE
Problems at import CSV files

### ISSUE THREAD

**Issue by c0r3dump3d** [nilsteampassnet/TeamPass#3196]
### Steps to reproduce
1. Imports items from CSV file

### Expected behaviour
Imports items form a CSV file well formed in accord of Teampass documentacion (https://teampass.readthedocs.io/en/latest/features/feat-impexp) :

![image](https://user-images.githubusercontent.com/5602401/171597775-1c861e2c-9058-4846-8651-304889caea42.png)

### Actual behaviour
An error ocurred and the import fails:

```
PHP Fatal error:  Uncaught TypeError: storeUsersShareKey(): Argument #5 ($objectKey) must be of type string, null given, called in /var/www/html/TeamPass/sources/import.queries.php on line 386 and defined in /var/www/html/TeamPass/sources/main.functions.php:2866
Stack trace:
#0 /var/www/html/TeamPass/sources/import.queries.php(386): storeUsersShareKey()
#1 {main}
  thrown in /var/www/html/TeamPass/sources/main.functions.php on line 2866

```

### Server configuration
**Operating system**: AlmaLinux release 8.5 (Arctic Sphynx)

**Web server:**  Apache/2.4.37 (AlmaLinux)

**Database:** 10.3.28-MariaDB MariaDB Server

**PHP version:** PHP 8.0.18

**Teampass version:** 3.0.0.17

### Client configuration
**Browser:** Brave Versión 1.39.111 Chromium: 102.0.5005.61 (Build oficial) (64 bits)

**Operating system:** Manjaro Linux

#### Web server error log
```
PHP Fatal error:  Uncaught TypeError: storeUsersShareKey(): Argument #5 ($objectKey) must be of type string, null given, called in /var/www/html/TeamPass/sources/import.queries.php on line 386 and defined in /var/www/html/TeamPass/sources/main.functions.php:2866
Stack trace:
#0 /var/www/html/TeamPass/sources/import.queries.php(386): storeUsersShareKey()
#1 {main}
  thrown in /var/www/html/TeamPass/sources/main.functions.php on line 2866
```

**Comment by romulovmarques** [comment]
Hi,

Modify this field "comment" to "description" or use fix bug  [[Import data no import comments](https://github.com/nilsteampassnet/TeamPass/issues/3159#)]. Not use ".."(quotation marks) in value an imputed.

**Comment by c0r3dump3d** [comment]
It doesn't work, I'm trying to update to 3.0.0.18 but I doesn't work.
