### ISSUE TITLE
Error when apply Manager Role to user

### ISSUE THREAD

**Issue by Devart-ltd** [nilsteampassnet/TeamPass#3204]
Hello.
In Teampass v.2.1.27 I have an error when apply Manager Role to user
Code is stuck with
```
Out of range value for column 'isAdministratedByRole'
```
error in jquery.js
![error](https://user-images.githubusercontent.com/107034241/172340777-ff77e78b-691f-4abc-8bb2-04ccfc7641ac.png)
How to fix it?

**Comment by scorpionukr** [comment]
Hi.
For fix it try change **datatype** for column **isAdministratedByRole** in Teampass DB to **INT**
`ALTER TABLE `teampass_users`
	CHANGE COLUMN `isAdministratedByRole` `isAdministratedByRole` INT(10) NOT NULL DEFAULT 0;`
