### ISSUE TITLE
ldap don't work

### ISSUE THREAD

**Issue by 1ntr0** [nilsteampassnet/TeamPass#3222]
### Steps to reproduce
1.press Users, Ldap synchronization, List users
2. list is empty
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Ubuntu 22.04

**Web server:**
![172161157-af76e74c-8890-47f7-ac32-b84e35434ddf](https://user-images.githubusercontent.com/17948582/173843427-f2ab9652-9f22-43b7-bd7a-f2cac65c141d.png)
![172161139-c1d279c6-76a7-4625-89c9-47556f45a4ba](https://user-images.githubusercontent.com/17948582/173843431-25036856-a164-486b-9a6c-6b53678579bc.png)
![172161117-142c5d9d-84e6-4c24-88dd-341c601c74d6](https://user-images.githubusercontent.com/17948582/173843432-0b7706ed-852b-4e10-87eb-a05a8cd43fbb.png)

**Database:**
mysqld  Ver 10.6.7-MariaDB-2ubuntu1 for debian-linux-gnu on x86_64 (Ubuntu 22.04)

**PHP version:**
8.1

**Teampass version:** 
3.0.0.18

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
Google Chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
G+qpYiEhISFKc+uDHcXsnk9TbQTutT489R+us6CKHaWZVE4EyAwfOtWYar/GeQideSVmm4vDtExqfusPfChnDLJ05ac98h4uW/y+9y0YoFAqnZbWY2+9IqNqR/kLDnawoG1consNYqXQcoGn2WtCRsoovQDNHGevcOlLU3O0wPJkpTROzHkJ5y91LFUvlDHbCv1bW5OkXxvgh8GvqNXpu0OedLQzSQj/atN0+65ZOUWfHCWcxCg+IlhxTXFtKxGUPN0DOpCNGIoPTHalqY/4u1e4OpbVAEzCFe8uEthXdGEzq/zchuaGzo07wVKgKkdgG7ce8vRwFsCgJaYjz0bUVCIxAwhD4A==
Insert the log here and especially the answer of the query that failed.
```

**Comment by 1ntr0** [comment]
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'http://teampass.kursk.grainrus.com',
    'favicon' => 'http://teampass.kursk.grainrus.com/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'http://teampass.kursk.grainrus.com/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.18',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1651862107',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Moscow',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'SCXnsw6FcXLMWpjxHu9rdkhFGUmBEJzgLc8dFRcy',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => 'OU=Users,OU=_Office,OU=Moscow,DC=kursk,DC=grainrus,DC=com',
    'ldap_hosts' => '10.12.13.11',
    'ldap_password' => 'password',
    'ldap_username' => 'CN=teampass_ldap,OU=Service_account,OU=Moscow,DC=kursk,DC=grainrus,DC=com',
    'api_token_duration' => '60',
);

**Comment by moutahir1** [comment]
try to ad OU= Moscow to base DN

**Comment by rrgadeev** [comment]
Там еще порядок имеет значение
https://github.com/nilsteampassnet/TeamPass/issues/3165
то есть Additional User DN нужно в правильном порядке:
Если каталог с пользователями вложен в другой, то он идет первым, вторым каталог куда он вложен. 
ou=Users,ou=Barad-dur,ou=Company 
Создай тестовый ou прямо в корне с тестовым пользователем. И да, нужна почта у пользователя, без нее никак.

**Comment by 1ntr0** [comment]
спасибо! изменил настройки, проверка на вкладке LDAP проходит, но в USERS пусто(
почта прописана
![image](https://user-images.githubusercontent.com/17948582/174252176-c37582f5-f490-4a28-aabe-a3cd27ac5733.png)

**Comment by 1ntr0** [comment]
закинул свою учетку в корень, изменил настройки под корень домена, все равно в users пусто(

изменил настройки обратно по статье 3155, не помогло(
может в ad какие-то настройки неверные?

modify https://github.com/nilsteampassnet/TeamPass/issues/3155#issuecomment-1140252644

->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])

->in(($SETTINGS['ldap_dn_additional_user_dn'] != '' ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])

**Comment by rrgadeev** [comment]
так писал жи
User name attribute: samaccountname
it works

**Comment by 1ntr0** [comment]
изменил, не помогло((
![image](https://user-images.githubusercontent.com/17948582/174274080-47ae5f7c-4589-40fd-97c7-29c398439924.png)

**Comment by rrgadeev** [comment]
Additional User DN должен быть вроде
ou=Users,ou=Barad-dur,ou=Company
оставь только ou
сделай get-ADuser testUser
из результата убери все DC, оставь только OU

**Comment by 1ntr0** [comment]
Работает!!! чувак спасибо тебе!!!

**Comment by 1ntr0** [comment]
верные настройки)
![image](https://user-images.githubusercontent.com/17948582/174285565-9bffed7b-d9d8-4065-bed1-14886bb8a6d8.png)

**Comment by rrgadeev** [comment]
пожалуйста, сам намучался. 
Там еще смотри, без почтовика не будет приходить код шифрования. Его надо будет ввести при авторизации.
Плюс еще после создания пользователя я вручную менял login на domen\login

**Comment by 1ntr0** [comment]
почту настроил, все завелось
я этого не делал - Плюс еще после создания пользователя я вручную менял login на domen\login
