### ISSUE TITLE
Upgrade from 2.1.27.36 to 3.0.0.17 won't start

### ISSUE THREAD

**Issue by roga67** [nilsteampassnet/TeamPass#3227]
### Steps to reproduce
1. Installed new Linux-Server with Apache 2.4 and PHP 7.4 as a replace for the old Teampass Server
2. Successfully restored backup from the old Teampass Server to the new Server
3. Successfully tested the new Server as admin and as normal user. All seems to be ok.
4. Donwloaded the latest release from Teampass
5. Renamed current Teampass folder to teampass.old
6. Unziped latest version and renamed to teampass
7. copied ./includes/config/settings.php, ./includes/config/tp.config.php, ./includes/librairies/csrfp/libs/csrfp.config.php, ./includes/avatars/*, ./files/*, ./upload/* from the old folder to the new one
8. ensured that the following files and folders are writable. ./includes/config/ ./includes/librairies/csrfp/libs/, ./includes/librairies/csrfp/js/, ./includes/librairies/csrfp/log/, ./includes/avatars/, ./files/, ./upload/, ./install/
9. Restart Apache Server and followed the instruction on the upgrade Page
10. Login as admin with password

### Expected behaviour
Tell us what should happen
I expected the begin of upgrade procedure

### Actual behaviour
Tell us what happens instead
a turning gear below at right side appears and nothing more happens. 

### Server configuration
**Operating system**:
Gentoo Linux

**Web server:**
Apache 2.4
**Database:**
MySQL MariaDB

**PHP version:**
PHP 7.4

**Teampass version:** 
2.1.27.36

**Teampass configuration file:**

*** OLD settings.php : ***
<?php
global $lang, $txt, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "localhost";
$user = "root";
$pass = "def502001d4ed905887349f0d0fbda5be0eacd85b779e08973260739de71c1f4e491a5d575d4ac9e271adc2eb584628e000d2e4ad6f974997820a2a
$database = "teampass";
$pre = "erz_";
$port = 3306;
$encoding = "";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/var/www/teampass/includes');
if (file_exists("/var/www/teampass/includes/sk.php")) {
    require_once "/var/www/teampass/includes/sk.php";
}

*** NEW: setting.php.2022_06_20_09_04_04 ***
<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "root");
define("DB_PASSWD", "def502001d4ed905887349f0d0fbda5be0eacd85b779e08973260739de71c1f4e491a5d575d4ac9e271adc2eb584628e000d2e4ad6f
974997820a2ad93c463e6343ed181859fd4bb32d41c4a4046dfb935c399e4164e44f4a3f9e99fe8");
define("DB_NAME", "teampass");
define("DB_PREFIX", "erz_");
define("DB_PORT", "3306");
define("DB_ENCODING", "");
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/www/teampass/includes");
define("IKEY", "");
define("SKEY", "");
define("AKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'cpassman_url' => 'http://erzteampass2.global.szh.loc',
    'favicon' => 'http://erzteampass2.global.szh.loc/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'url_to_upload_folder' => 'http://erzteampass2.global.szh.loc/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'http://erzteampass2.global.szh.loc/files',
    'activate_expiration' => '1',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@global.szh.loc',
    'ldap_domain_dn' => 'OU=ERZ,OU=OU-GLOBAL,DC=global,DC=szh,DC=loc',
    'ldap_domain_controler' => 'ldap-lb.global.szh.loc,ldap1.global.szh.loc,ldap2.global.szh.loc,ldap3.global.szh.loc,ldap4.glob
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '5',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'http://erzteampass2.global.szh.loc/logo.png',
    'custom_login_text' => '',
    'default_language' => 'german',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admin
    'send_stats_time' => '1570369980',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'erz-smtp.global.szh.loc',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@bm.erz-technet.ch',
    'email_from_name' => 'TeamPass Administrator',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '240',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Zurich',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'UNfkqGRxGRkqrfSLUzVSHFysDkAGswjyxKtcGe2J',
    'admin_2fa_required' => '1',
    'tree_counters' => '1',
    'enable_massive_move_delete' => '0',
    'ldap_allowed_usergroup' => '',
);

### Client configuration
**Browser:**
Crome Version 102.0.5005.115 (Offizieller Build) (64-Bit)

**Operating system:**
Windows 11 Pro Version 21H2 Build 22000.739

#### Web server error log
```
Insert your webserver log here
[Mon Jun 20 09:13:11.013256 2022] [php7:error] [pid 18470] [client 10.84.7.51:60779] PHP Fatal error:  Uncaught Defuse\\Crypto\\
Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/teampass/includes/libraries/Encryption/Encrypt
ion/Encoding.php:225\nStack trace:\n#0 /var/www/teampass/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\\Crypto\\E
ncoding::loadBytesFromChecksummedAsciiSafeString()\n#1 /var/www/teampass/install/tp.functions.php(44): Defuse\\Crypto\\Key::load
FromAsciiSafeString()\n#2 /var/www/teampass/install/tp.functions.php(84): defuseCryption()\n#3 /var/www/teampass/install/upgrade
_ajax.php(254): defuse_return_decrypted()\n#4 {main}\n  thrown in /var/www/teampass/includes/libraries/Encryption/Encryption/Enc
oding.php on line 225, referer: http://erzteampass2.global.szh.loc/install/upgrade.php


#### Log from the web-browser developer console (CTRL + SHIFT + i)

Insert the log here and especially the answer of the query that failed.

POST http://erzteampass2.global.szh.loc/install/upgrade_ajax.php 500 (Internal Server Error)

Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

**Comment by ricain59** [comment]
I'm in the same problem, how to resolve?

Thank you.

**Comment by roga67** [comment]
In my case the problem was the cache of the browser. I have to press ctrl + f5 to clear the browsers cache. After that it works for  me.

 

 

Von: cath ***@***.***> 
Gesendet: Dienstag, 28. Juni 2022 12:25
An: nilsteampassnet/TeamPass ***@***.***>
Cc: roga67 ***@***.***>; State change ***@***.***>
Betreff: Re: [nilsteampassnet/TeamPass] Upgrade from 2.1.27.36 to 3.0.0.17 won't start (Issue #3227)

 

Hello! can you explain how you fixed that problem?

**Comment by roga67** [comment]
In my case the problem was the cache of the browser. I have to press ctrl + f5 to clear the browsers cache. After that it works for  me.

 

 

Von: ricain59 ***@***.***> 
Gesendet: Dienstag, 28. Juni 2022 18:17
An: nilsteampassnet/TeamPass ***@***.***>
Cc: roga67 ***@***.***>; State change ***@***.***>
Betreff: Re: [nilsteampassnet/TeamPass] Upgrade from 2.1.27.36 to 3.0.0.17 won't start (Issue #3227)

 

I'm in the same problem, how to resolve?

Thank you.
