### ISSUE TITLE
[3.0.0.18] Don't see any user created on menu "Users"

### ISSUE THREAD

**Issue by klozano5** [nilsteampassnet/TeamPass#3228]
### Steps to reproduce
1. I created two users, and don't see on menu, but yes on MariaDB by command Linux.

### Expected behaviour
See all users created on menu "Users"

### Actual behaviour
Dont' see any unser on menu "Users"

### Server configuration
Ubuntu Server 22.04

Database:
MariaDB

PHP version:
8.1.2

Teampass version:
3.0.0.18

Thanks.

**Comment by abhixcode** [comment]
I faced the same issue. You may want to check out the below link.

[https://teampass.readthedocs.io/en/latest/errors/#users-and-folders-lists-are-empty](url)

**Comment by nilsteampassnet** [comment]
Perhaps browser cache issue.
PLease check the logs

**Comment by kevinsmartpm** [comment]
Hi,
I am getting the same issue,

I reset cache on browsers, and i tryied from another PC but still are not appearing the users.

They are created: 
![image](https://user-images.githubusercontent.com/108066583/175914219-f308decf-1404-4f22-b182-ce8ba820b056.png)
And they work on login:
![image](https://user-images.githubusercontent.com/108066583/175914435-ff68643d-40f2-4e1a-b7df-18e87beee491.png)

But still not on user list in the menu:
![image](https://user-images.githubusercontent.com/108066583/175914761-11c5f43f-a565-43a7-9fad-396ee6d8e571.png)

**Comment by kevinsmartpm** [comment]
Hi,
I have solved this problem seeing on the console tab what was happening, the error was with my ANTIVIRUS (KARSPERSKI).

It was blocking some traffic that it marked as "bad".

This + xampp selfsigned certificate (yes i didn`t chage it yet) it was generating this type of errors.


 sorry for the inconvenience.

**Comment by klozano5** [comment]
Hi,
In my case I solved the problem installing Teampass 3.0.0.8 on Debian 11 (before installed on Ubuntu 20.04).
Thanks to all for the help!
