### ISSUE TITLE
Folders tree not loading

### ISSUE THREAD

**Issue by tdtmusic2** [nilsteampassnet/TeamPass#3229]
### Steps to reproduce
1. Added a few empty folders
2. Opened the Items section
3. Folders tree shows "Loading..." and doens't actually load folders

### Expected behaviour
All folders should be visible

### Actual behaviour
Spinning ring with "Loading..."

### Server configuration
**Operating system**:
Ubuntu Server 20.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
8.1 (also tried with 7.4 and 8.0)

**Teampass version:** 
3.0.0.17 (also tried with 3.0.0.18)

**Teampass configuration file:**
'max_latest_items' => '10',
'enable_favourites' => '0',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html',
'cpassman_url' => 'http://<anonym_url>
'favicon' => 'http://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/html/upload',
'path_to_files_folder' => '/var/www/html/files',
'url_to_files_folder' => 'http://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.17',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1653221053',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '1',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '26',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Bucharest',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_akey' => '',
'duo_ikey' => '',
'duo_skey' => '',
'duo_host' => '',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '1',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '',
'onthefly-restore-key' => '',
'ldap_user_dn_attribute' => '',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '',
'ldap_bdn' => '',
'ldap_hosts' => '',
'ldap_password' => '',
'ldap_username' => '',

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Chrome, Firefox, MS Edge
**Operating system:**
Windows 10
#### Web server error log
[Tue Jun 21 12:37:20.729234 2022] [proxy_fcgi:error] [pid 997] [client 10.1.0.122:1762] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /var/www/html/sources/tree.php:647\nStack trace:\n#0 /var/www/html/sources/tree.php(647): array_merge()\n#1 /var/www/html/sources/tree.php(205): recursiveTree()\n#2 {main}\n  thrown in /var/www/html/sources/tree.php on line 647', referer: http://10.1.0.105/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
jquery.min.js:2          GET http://10.1.0.105/sources/tree.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
_load_node @ jstree.min.js:2
load_node @ jstree.min.js:2
init @ jstree.min.js:2
a.jstree.create @ jstree.min.js:2
(anonymous) @ jstree.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.jstree @ jstree.min.js:2
(anonymous) @ index.php?page=items:3258

```

**Comment by tdtmusic2** [comment]
I just noticed that I have a similar error when trying to upload attachments:

`122:2561] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: htmlentities(): Argument #1 ($string) must be of type string, int given in /var/www/html/sources/upload.attachments.php:459\nStack trace:\n#0 /var/www/html/sources/upload.attachments.php(459): htmlentities()\n#1 /var/www/html/sources/upload.attachments.php(242): handleAttachmentError()\n#2 {main}\n  thrown in /var/www/html/sources/upload.attachments.php on line 459', referer: http://10.1.0.105/index.php?page=items
`

**Comment by brad-dart** [comment]
I am having the same issue. 
I am mostly seeing this for users that are new or have not logged in before the upgrade.

**Comment by nahpl** [comment]
Hi,

I have the same problem. Did you find any solution?

Log error:

[Wed Jun 15 14:23:30.183464 2022] [php7:error] [pid 331923] [client 172.23.0.122:54916] PHP Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /var/www/html/TeamPass/sources/tree.php:957\nStack trace:\n#0 /var/www/html/TeamPass/sources/tree.php(957): array_keys()\n#1 /var/www/html/TeamPass/sources/tree.php(756): prepareNodeData()\n#2 /var/www/html/TeamPass/sources/tree.php(680): handleNode()\n#3 /var/www/html/TeamPass/sources/tree.php(205): recursiveTree()\n#4 {main}\n thrown in /var/www/html/TeamPass/sources/tree.php on line 957, referer: https://xxxx/index.php?page=items

**Comment by tdtmusic2** [comment]
> Hi,
> 
> I have the same problem. Did you find any solution?
> 
> Log error:
> 
> [Wed Jun 15 14:23:30.183464 2022] [php7:error] [pid 331923] [client 172.23.0.122:54916] PHP Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /var/www/html/TeamPass/sources/tree.php:957\nStack trace:\n#0 /var/www/html/TeamPass/sources/tree.php(957): array_keys()\n#1 /var/www/html/TeamPass/sources/tree.php(756): prepareNodeData()\n#2 /var/www/html/TeamPass/sources/tree.php(680): handleNode()\n#3 /var/www/html/TeamPass/sources/tree.php(205): recursiveTree()\n#4 {main}\n thrown in /var/www/html/TeamPass/sources/tree.php on line 957, referer: https://xxxx/index.php?page=items

Unfortunately no, TP is in a unusable state right now, I'll wait to see if the author replies with either a fix or a workaround.

**Comment by c0r3dump3d** [comment]
I have the same problem after update from 3.0.0.17 to 3.0.0.18:

```
[23-Jun-2022 12:19:58 Europe/Madrid] PHP Fatal error:  Uncaught TypeError: loadTreeStrategy(): Argument #3 ($userSessionTreeStructure) must be of type array, null given, called in /var/www/html/TeamPass/sources/tree.php on line 133 and defined in /var/www/html/TeamPass/sources/tree.php:1023
Stack trace:
#0 /var/www/html/TeamPass/sources/tree.php(133): loadTreeStrategy()
#1 {main}
  thrown in /var/www/html/TeamPass/sources/tree.php on line 1023
```

**Comment by croaker-1** [comment]
Similar issue. On a 3.0.0.17 instance (that has been running well nearly a month), a user reported that their folder tree would not load, only a spinning "Loading" message...two other users (one was mine) were fine. This prompted me to upgrade to 3.0.0.18 which caused my user to exhibit the same symptoms. 

JavaScript logs from login:
```
[Log] User infor (index.php, line 3308)
[Log] Object (index.php, line 3309)
[Info] Les répertoires sont chargés (index.php, line 3323)
[Log] Object (index.php, line 3324)
[Log] Object (index.php, line 2797)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (tree.php, line 0)
[Log] Object (index.php, line 1673)
[Log] TREE (index.php, line 6273)
[Log] Object (index.php, line 6274)
[Log] [60,109,111,113,110,84,48,142,94,73,51,68,70,137,33,28,74,80,141,105,10,56,42,22,128,123,101,82,131,87,88,150,134,144,139,140,147,25,26,32,104,63,78,64,115,117,148,92,116,44,18,2,39,100,119,41,35,112,106,130,67,11,124,114,91,103,89,77,90,136,120,121,118,127,36,37,85,72,30,29,52,38,31,58,79,65,96,102,19,47,133,71,12] (index.php, line 6361)
[Log] <option value="0">Root</option>***folder list redacted***</option> (index.php, line 6321)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (summernote-bs4.css.map, line 0)
```

The apache error log that correlate to the tree.php error above:
```
[Fri Jun 24 13:47:40.011292 2022] [php7:error] [pid 16333] [client 10.1.241.18:54924] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to loadTreeStrategy() must be of the type array, null given, called in /var/www/teampass/sources/tree.php on line 133 and defined in /var/www/teampass/sources/tree.php:1023\nStack trace:\n#0 /var/www/teampass/sources/tree.php(133): loadTreeStrategy()\n#1 {main}\n  thrown in /var/www/teampass/sources/tree.php on line 1023, referer: https://teampass3.ourdomain.com/index.php?page=items
```

**Comment by nilsteampassnet** [comment]
Fixed in latest commit

**Comment by brad-dart** [comment]
Hi thanks for acting so quickly. I have pulled the latest commits, but sadly still am experiencing the same behaviour. The error messages are still

[Mon Jun 27 13:52:57.012241 2022] [php7:error] [pid 91940] [client 172.16.90.4:59483] PHP Fatal error:  Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in /var/www/html/sources/tree.php:971\nStack trace:\n#0 /var/www/html/sources/tree.php(971): array_keys()\n#1 /var/www/html/sources/tree.php(770): prepareNodeData()\n#2 /var/www/html/sources/tree.php(694): handleNode()\n#3 /var/www/html/sources/tree.php(207): recursiveTree()\n#4 {main}\n  thrown in /var/www/html/sources/tree.php on line 971, referer: https://xxxx.xxxx.xxx/index.php?page=items

**Comment by c0r3dump3d** [comment]
In my case I have pulled with the latest commits and it's working correctly.

**Comment by c0r3dump3d** [comment]
I see that when I access to TP the folder tree doesn't load and I see theses messages in logs:

```
[29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1514
[29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1514
[29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(/sources/SplClassLoader.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1525
[29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1525
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include(../../../config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1514
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1514
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(/sources/SplClassLoader.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1525
[29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1525

```

But it works if I reload the page.

TeamPass version 3.0.0.18 upgrade from 3.0.0.17
Php version ==> PHP 8.0.20

**Comment by tdtmusic2** [comment]
> I see that when I access to TP the folder tree doesn't load and I see theses messages in logs:
> 
> ```
> [29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1514
> [29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1514
> [29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(/sources/SplClassLoader.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1525
> [29-Jun-2022 10:36:10 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1525
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include(../../../config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1514
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1514
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(/sources/SplClassLoader.php): Failed to open stream: No such file or directory in /var/www/html/TeamPass/sources/main.functions.php on line 1525
> [29-Jun-2022 11:15:38 Europe/Madrid] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/TeamPass/sources/main.functions.php on line 1525
> ```
> 
> But it works if I reload the page.
> 
> TeamPass version 3.0.0.18 upgrade from 3.0.0.17 Php version ==> PHP 8.0.20

Same here, updated to the last commit version and the folder tree loads, but only after page refresh.
