### ISSUE TITLE
Unable to load database backup from TeamPass v2.1.27

### ISSUE THREAD

**Issue by akaylee** [nilsteampassnet/TeamPass#3230]
### Steps to reproduce
1. Perform a backup in TeamPass v2
2. Load Backup.sql in Settings>Backup on freshly installed TeamPass v3

### Expected behaviour
Database restored from older version

### Actual behaviour
Error is produced (attaching it bellow)

### Server configuration
**Operating system**: ubuntu server 22.04

**Web server:** apache2

**Database:** mariadb

**PHP version:** 8.1

**Teampass version:** 3.0.0.18

**Updated from an older Teampass or fresh install:**

[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/8950350/tp.config.zip)

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
[{"result":"db_restore" , "message":"Defuse\Crypto\Exception\IOException: Could not read from the file in /var/www/html/teampass/includes/libraries/Encryption/Encryption/File.php:708 Stack trace: #0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/File.php(479): Defuse\Crypto\File::readBytes() #1 /var/www/html/teampass/includes/libraries/Encryption/Encryption/File.php(298): Defuse\Crypto\File::decryptResourceInternal() #2 /var/www/html/teampass/includes/libraries/Encryption/Encryption/File.php(89): Defuse\Crypto\File::decryptFileInternal() #3 /var/www/html/teampass/sources/main.functions.php(2323): Defuse\Crypto\File::decryptFileWithPassword() #4 /var/www/html/teampass/sources/main.functions.php(2230): defuseFileDecrypt() #5 /var/www/html/teampass/sources/backups.queries.php(288): prepareFileWithDefuse() #6 {main}"}]
```

**Comment by akaylee** [comment]
There is also a problem: it seems impossible to perform a restore without encryption in v3 (no messages/warnings occur and pressing "restore" does nohing), although in v2 you can export uncrypted DB.

**Comment by abhixcode** [comment]
I was trying to restore a backup (created from v3) and that too failed, popping up the same error.

`[{"result":"db_restore" , "message":"Defuse\Crypto\Exception\IOException: Could not read from the file in /var/www/html/includes/libraries/Encryption/Encryption/File.php:708 Stack trace: #0 /var/www/html/includes/libraries/Encryption/Encryption/File.php(479): Defuse\Crypto\File::readBytes() #1 /var/www/html/includes/libraries/Encryption/Encryption/File.php(298): Defuse\Crypto\File::decryptResourceInternal() #2 /var/www/html/includes/libraries/Encryption/Encryption/File.php(89): Defuse\Crypto\File::decryptFileInternal() #3 /var/www/html/sources/main.functions.php(2323): Defuse\Crypto\File::decryptFileWithPassword() #4 /var/www/html/sources/main.functions.php(2230): defuseFileDecrypt() #5 /var/www/html/sources/backups.queries.php(288): prepareFileWithDefuse() #6 {main}"}]`

**Comment by nilsteampassnet** [comment]
This is normal.
Teampass v3 database and password encryption has nothing to do with V2.
You need to go through the upgrade process.

**Comment by akaylee** [comment]
thank you!
