### ISSUE TITLE
User need temporary encryption code 

### ISSUE THREAD

**Issue by roga67** [nilsteampassnet/TeamPass#3232]
### Steps to reproduce
1. succesfully upgraded from 2.1.17.36 direct to 3.0.018
2. succesfully configured LDAP with AD
3. login as ad-user needs a temopray encryption code
![Screenshot 2022-06-22 155153](https://user-images.githubusercontent.com/45307109/175046089-68dcbdc1-104b-4e96-b700-ab6528d81111.png)

### Expected behaviour
Tell us what should happen
System should send a temporary encryption code to the specific ad-user or the admin should be able to do that

### Actual behaviour
Tell us what happens instead
User cannot login

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2.4

**Database:**
MySQL / Mariadb 10.5.13

**PHP version:**
PHP 8.0

**Teampass version:** 
3.0.0.18

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
updated from 2.1.17.36

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome 102.0.5005.115

**Operating system:**
Windows 11 Pro

#### Web server error log
```
Insert your webserver log here

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
During upgrade process, an email is sent to each user with encryption code.
Also during upgrade when step is finished admin has access to the complete list of all encryption keys.

**Comment by roga67** [comment]
After finished the upgrade when admin logged in it's also possible to have access to the complete list of all encryption keys? If yes, where can admin locate this list?

**Comment by roga67** [comment]
sorry, is there no answer to my simply questions or didn't you understand me?

**Comment by Nyphew** [comment]
> sorry, is there no answer to my simply questions or didn't you understand me?

Hi roga67

I had the same problem today :

- if you go as admin in the list of users you can reset the password of the one stuck.
- at the end of the process you will be able to send an email and/or copy the password.
- at next logon you will have to change the password.

that's it.

**Comment by roga67** [comment]
Hi Nyphew,
Thank's, that's it! 
As admin I can access the list of Users and there is an option to reset otp (one time password).  This solves my problem.
