### ISSUE TITLE
PHP error in tree.php

### ISSUE THREAD

**Issue by BelgarathS** [nilsteampassnet/TeamPass#3235]
### Steps to reproduce
1. upgdare from version 2 to 3
2. Log in

### Expected behaviour
see tree view of the panel

### Actual behaviour
tree view empty
PHP error is thrown:
PHP Fatal error:  Uncaught TypeError: loadTreeStrategy(): Argument #3 ($userSessionTreeStructure) must be of type array, null given, called in /var/www/html/pass/sources/tree.phpon line 133 and defined in /var/www/html/pass/sources/tree.php:1023\nStack trace:\n#0 /var/www/html/pass/sources/tree.php(133): loadTreeStrategy()\n#1 {main}\n  thrown in /var/www/html/pass/sources/tree.php on line 1023

### Server configuration
**Operating system**:
Ubuntu 22.04
**Web server:**
Apache 2.4.52

**Database:**
maraidb-server 10.6.7

**PHP version:**
8.1.2

**Teampass version:** 
latest as of (25-06-2022)

### Client configuration
**Browser:**
Chrome 10x 

**Operating system:**
Ubuntu
#### Web server error log
PHP Fatal error:  Uncaught TypeError: loadTreeStrategy(): Argument #3 ($userSessionTreeStructure) must be of type array, null given, called in /var/www/html/pass/sources/tree.phpon line 133 and defined in /var/www/html/pass/sources/tree.php:1023\nStack trace:\n#0 /var/www/html/pass/sources/tree.php(133): loadTreeStrategy()\n#1 {main}\n  thrown in /var/www/html/pass/sources/tree.php on line 1023

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by BelgarathS** [comment]
That has been resolved.thank you

**Comment by BelgarathS** [comment]
it seems that fix only partially fixes the issue, i.e after logging in the tree is empty and the page has to be reloaded for the tree to show up.
First time round the tree.php returns 500  - internal server error
The corresponding PHP error is:
PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'increment_id' doesn't have a default value

That does not happen on the page reload

**Comment by c0r3dump3d** [comment]
I see the same error:

```
[29-Jun-2022 10:18:56 Europe/Madrid] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/TeamPass/sources/tree.php:971
Stack trace:
#0 /var/www/html/TeamPass/sources/tree.php(971): array_keys()
#1 /var/www/html/TeamPass/sources/tree.php(770): prepareNodeData()
#2 /var/www/html/TeamPass/sources/tree.php(694): handleNode()
#3 /var/www/html/TeamPass/sources/tree.php(207): recursiveTree()
#4 {main}
  thrown in /var/www/html/TeamPass/sources/tree.php on line 971
[29-Jun-2022 10:19:09 Europe/Madrid] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/TeamPass/sources/tree.php:971
Stack trace:
#0 /var/www/html/TeamPass/sources/tree.php(971): array_keys()
#1 /var/www/html/TeamPass/sources/tree.php(770): prepareNodeData()
#2 /var/www/html/TeamPass/sources/tree.php(694): handleNode()
#3 /var/www/html/TeamPass/sources/tree.php(207): recursiveTree()
#4 {main}
  thrown in /var/www/html/TeamPass/sources/tree.php on line 971
[29-Jun-2022 10:19:36 Europe/Madrid] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/TeamPass/sources/tree.php:971
Stack trace:
#0 /var/www/html/TeamPass/sources/tree.php(971): array_keys()
#1 /var/www/html/TeamPass/sources/tree.php(770): prepareNodeData()
#2 /var/www/html/TeamPass/sources/tree.php(694): handleNode()
#3 /var/www/html/TeamPass/sources/tree.php(207): recursiveTree()
#4 {main}
  thrown in /var/www/html/TeamPass/sources/tree.php on line 971
```
