### ISSUE TITLE
Forgotten admin password.

### ISSUE THREAD

**Issue by kkensicki** [nilsteampassnet/TeamPass#3242]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**
Ubuntu
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Yes
- connect as admin
- click option
![image](https://user-images.githubusercontent.com/1197546/177480025-d5c0ae34-fef9-43f7-8d6a-5fa27c6c9299.png)
- provide old and new passwords
![image](https://user-images.githubusercontent.com/1197546/177480134-25492803-9d92-4032-a6fd-f78cb3e3bed8.png)
- done
