### ISSUE TITLE
LDAP Synchronisation still not ok on first install

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3258]
Latest commit [52df161](https://github.com/nilsteampassnet/TeamPass/commit/52df16124a14b2a2d44dac6cb3eeb5b5c57527c3)

As already mentioned in [#3155](https://github.com/nilsteampassnet/TeamPass/issues/3155) and [3236](https://github.com/nilsteampassnet/TeamPass/issues/3236) the bug for LDAP Synchronisation in adding users (ADMIN) is still present.
Due to latest updates the line has slightly changed, but it's still wrong.
In line 2491 of sources/users.queries.php
Instead of
```
->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
```
it must be
```
->in((isset($SETTINGS['ldap_dn_additional_user_dn']) && !empty($SETTINGS['ldap_dn_additional_user_dn']) ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
```

Regards

**Comment by TOH2F** [comment]
Hello,
The problem recurs in version 3.0.0.18. The list of users does not display anything while the synchro test on the LDAP menu is ok. An idea ?
