### ISSUE TITLE
Next error occurred SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by gmontequi** [nilsteampassnet/TeamPass#3276]
### Steps to reproduce
1. Logon into the web
2. Error appears: Next error occurred SyntaxError: Unexpected end of JSON input
3.

### Expected behaviour
Load folder tree

### Actual behaviour
Error: Next error occurred SyntaxError: Unexpected end of JSON input

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
![image](https://user-images.githubusercontent.com/90802409/183098725-20408db0-1189-4f02-b9b5-d78c6ce89e12.png)
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
index.php?page=items:6273 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'folders')
    at Object.success (index.php?page=items:6273:40)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
```

**Comment by gmontequi** [comment]
Used 3ca7fe7 (1 hour ago) version upgrading from 3.0.0.16

**Comment by useronkel** [comment]
Same for me, malformed UTF-8 has gone ([3272](https://github.com/nilsteampassnet/TeamPass/issues/3272)) but this is also annoying ;-)

**Comment by fermosan** [comment]
I got that too. 

index.php?page=items:6248 Uncaught TypeError: Cannot read properties of undefined (reading 'folders')
    at Object.success (index.php?page=items:6248:40)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)

**Comment by gmontequi** [comment]
Solved with latest version. [5b33821](https://github.com/nilsteampassnet/TeamPass/commit/5b3382142c2541b0ad833c0f0256c2d4016b056b)

**Comment by marcelodemirandarj** [comment]
I'm having the same problem. Fresh installation (version 3.0.0.18). The problem happens when I go to "Add a new folder". Apparently, it's an unsolved problem here. I'm almost giving up on using it, there are a lot of bugs.
