### ISSUE TITLE
Next error occurred - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by Nachtlichtermeer** [nilsteampassnet/TeamPass#3280]
### Steps to reproduce
1. Upgrade to commit 7937b4462ee3d83d8a0ac35b91d2e658fe1feebe or newer
2. Login
3. Wait some seconds

### Expected behaviour
folders and passwords should shown

### Actual behaviour
window with "Next error occurred
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" opens

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.4

**Teampass version:** 
 3.0.0.18 since 7937b4462ee3d83d8a0ac35b91d2e658fe1feebe; 83294ac828520256e93f7f23e50c684e657af048 tested too

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Updated from e0ed8ef4e44144930d4d431b705916caa460e3a0 but tested steps between

### Client configuration
**Browser:** 103.0 (64-Bit)

**Operating system:** Ubuntu 20.04

#### Web server error log
```
nothing
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Uncaught TypeError: data.html_json is undefined
    refreshVisibleFolders https://passwort-dev.foo.de/index.php?page=items:8203
    jQuery 7
    refreshVisibleFolders https://passwort-dev.foo.de/index.php?page=items:8182
    <anonymous> https://passwort-dev.foo.de/index.php?page=items:5431
    jQuery 8
    countdown https://passwort-dev.foo.de/includes/js/functions.js:67
    jQuery 9
    countdown https://passwort-dev.foo.de/includes/js/functions.js:64
    <anonymous> https://passwort-dev.foo.de/index.php?page=items:3668

```

**Comment by ErikasRaginis** [comment]
Same problem

**Comment by ronesansholding** [comment]
same problemm

**Comment by damian19820** [comment]
same problem on clean install

**Comment by brad-dart** [comment]
Is there any update on this issue?

**Comment by fermosan** [comment]
@nilsteampassnet 
Same issue here at latest commit.
Console log:
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. index.php
Uncaught TypeError: data.html_json is undefined
    refreshVisibleFolders https://teampass.net/index.php?page=items:6241
    jQuery 7
    refreshVisibleFolders https://teampass.net/index.php?page=items:6219
    <anonymous> https://teampass.net/index.php?page=items:3469
    jQuery 8
    countdown https://teampass.net/includes/js/functions.js:76
    jQuery 9
    countdown https://teampass.net/includes/js/functions.js:73
    <anonymous> https://teampass.net/index.php?page=items:1737
index.php:6241:25
    refreshVisibleFolders https://teampass.net/index.php?page=items:6241
    jQuery 7
    refreshVisibleFolders https://teampass.net/index.php?page=items:6219
    <anonymous> https://teampass.net/index.php?page=items:3469
    jQuery 8
    countdown https://teampass.net/includes/js/functions.js:76
    jQuery 9
    countdown https://teampass.net/includes/js/functions.js:73
    <anonymous> https://teampass.net/index.php?page=items:1737

![image](https://user-images.githubusercontent.com/78906279/189525836-2d636c56-532b-4df4-9b46-c1217d7ce791.png)

**Comment by nilsteampassnet** [comment]
You confirm that you run the upgrade process after using latest commit?

**Comment by fermosan** [comment]
> You confirm that you run the upgrade process after using latest commit? Please also perform a CTRL+F5 after upgrading.
@nilsteampassnet 
When you say run the upgrade process after using the latest commit you mean all over again the upgrade from teampass version 2 or rerun update script in the already teampass 3 instance ?

**Comment by ErikasRaginis** [comment]
Updating to latest commit fixed the issue for me. I checked out the new commit, restored files in the install directory (that i had deleted before) and ran install/upgrade.php. Then logged into my account and the directory tree loaded as it was supposed to.

**Comment by fermosan** [comment]
Well, this doesn't work for me. Any ideas how to further debug it ?

**Comment by brad-dart** [comment]
The latest commit does not work for me either.
This issue occurs when upgrading from prior versions and for fresh installs.
The only additional config that has been performed is ldap auth.
The tree loading fails after adding a single entry.

**Comment by fermosan** [comment]
I have ldap auth as well. Maybe the problem is related to auth type. 
@nilsteampassnet any ideas? can you reproduce with ldap auth ?

**Comment by fermosan** [comment]
Downgrading to 3.0.0.17 and restoring database all folders are visible. 
Trying to upgrade to 3.0.0.18 and the problem re-appears. 
Exporting to CSV in order to import to again to clean instance but the export is stuck to Starting...
Any ideas?

**Comment by brad-dart** [comment]
Has anyone been able to find a work around for this issue? Cheers

**Comment by brad-dart** [comment]
> > Has anyone been able to find a work around for this issue? Cheers
> 
> Upgrading to the newest version has fixed this issue for me.

Thanks for the update. Can I ask if you use ldap for auth?

**Comment by Nachtlichtermeer** [comment]
> > > Has anyone been able to find a work around for this issue? Cheers
> > 
> > 
> > Upgrading to the newest version has fixed this issue for me.
> 
> Thanks for the update. Can I ask if you use ldap for auth?

Nice, i'll try...

yes, we use LDAP

**Comment by Nachtlichtermeer** [comment]
Tested succesfully with latest commit a798c9dc9184b5b14184c93c898d727b6418f1e1
