### ISSUE TITLE
bcmath listed as openssl during install dependancy checker

### ISSUE THREAD

**Issue by paulheaney** [nilsteampassnet/TeamPass#329]
During the install of TeamPass 2.1.18 if the bcmath PHP module is not installed then an error is shown indicating openssl is not installed.  

On line 58 of install/install_ajax.php this checks for bcmath and prints that the openssl module is missing.  The same seems to be true of iconv

**Comment by zoetropeexplosn** [comment]
@nilsteampassnet Can confirm this issue persists in latest version pushed out today. Please reopen and address - installation instructions on readthedocs.io do not handle making sure several of the pre-reqs are installed or configured. This is super confusing, and I'm moderately competent navigating my Ubuntu server.
