### ISSUE TITLE
won't let you create a password

### ISSUE THREAD

**Issue by rripolles6** [nilsteampassnet/TeamPass#3295]
### Steps to reproduce
1.create new password 
2.Fill in information, the folders do not appear in details
3.Does not allow saving the password if you do not select a folder

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Linux
**Web server:**

**Database:**
Phpmyadmin
**PHP version:**
7.4
**Teampass version:** 
3.0.0.18
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google chrome
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
