### ISSUE TITLE
There is an error copying or editing the password information

### ISSUE THREAD

**Issue by rripollesg** [nilsteampassnet/TeamPass#3298]
### Steps to reproduce
1.A password is created with the folder
2.An attempt is made to copy o edit the created password and a JSON error is thrown
3.the error is SyntaxError: Unexpected end of JSON input
4. Console: https://paginaweb.com/teampass/sources/items.queries.php

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Linux
**Web server:**

**Database:**
Phpmyadmin
**PHP version:**
7.4
**Teampass version:** 
3.0.0.18
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google chrome

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
![Snag_ce74227](https://user-images.githubusercontent.com/51409066/187983774-bb7c7d86-8cc1-4c18-8653-5fe106c49f84.png)

When trying several times it has worked for me, if you can look so that this failure does not happen to anyone else, even if it is temporary
![Snag_d035336](https://user-images.githubusercontent.com/51409066/187988810-def9c4c9-0f75-44aa-a0f4-a3a6b4a7a714.png)

**Comment by nratineau** [comment]
@rripolles6 Can you try with the latest commit, making sure to run the upgrade.php from the install folder.
If you still have the issue, can you confirm/provide:
- New or Upgraded from v2?
- Your _tp.config.php_ file makgin sure to remove any login/password (LDAP, email,...)
- The log from the web-browser developer console (CTRL + SHIFT + i)
- Web server error log

Thank you :)

**Comment by rripollesg** [comment]
With the last commit, works correctly, the case is closed

Thanks for all
