### ISSUE TITLE
It does not allow you to delete the newly created root folders (vers.3.0.0.18)

### ISSUE THREAD

**Issue by ispf72** [nilsteampassnet/TeamPass#3299]
It does not allow you to delete the newly created root folders

 
### Steps to reproduce
1. create new folder1  on Root
2. refresh folder
3. select folder1
4. delete folder1

### Expected behaviour
delete folder1

### Actual behaviour
null

### Server configuration
**Operating system**:
debian11.0.4
**Web server:**
apache2
**Database:**
mariadb-server
**PHP version:**
8.1
**Teampass version:** 
34.0.0.18
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Debian11.04
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by bertoldirenzo** [comment]
I have the same issue, can't delete new items or folders

**Comment by nratineau** [comment]
@ispf72 @bertoldirenzo Had the same issue, it's a discrepancy of variables name between the php code and js.
I'll submit a PR to the project but you can solve the issue by editing the `sources/folders.queries.php` file.
Line 222 and 223 change:
```
'user_is_admin' => (int) $_SESSION['is_admin'],
'user_can_create_root_folder' => (int) $_SESSION['can_create_root_folder'],
```
to
```
'userIsAdmin' => (int) $_SESSION['is_admin'],
'userCanCreateRootFolder' => (int) $_SESSION['can_create_root_folder'],
```

**Comment by bertoldirenzo** [comment]
Ok thank you. I am going to do that

**Comment by ispf72** [comment]
Ok thank you. it works fine
