### ISSUE TITLE
Migration 2.1.27.36 to 3.0.0.17: ERROR in language strings!

### ISSUE THREAD

**Issue by ArnOCP** [nilsteampassnet/TeamPass#3303]
### Steps to reproduce
1. I have an instance of Teampass 2.1.27.36 works fine (expected a bug on csv export https://github.com/nilsteampassnet/TeamPass/issues/2997, not the problem)
2. I upgarde to 3.0.0.17, the upgrade process said OK
3. I connect to the website and have an error: ERROR in language strings!

### Expected behaviour
I connect to the website of 3.0.0.17 and ther is a warning "ERROR in language strings!"
If i connect with a standard user all the menu are "ERROR in language strings!"
I cannot connect with the admin account --> "ERROR in language strings!"

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Windows Server 2016

**Web server:** IIS

**Database:** MySQL 8.0.27

**PHP version:** 7.4.25

**Teampass version:** 30.0.17

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9494977/tp.config.php.txt)`.

### Client configuration
**Browser:** Firefox 91.13.0 esr

**Operating system:** Windows 10 20H2

#### Web server error log
```
[u_ex220906.log.txt](https://github.com/nilsteampassnet/TeamPass/files/9495220/u_ex220906.log.txt)


```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
![Teampass](https://user-images.githubusercontent.com/97297565/188592485-5e0dafbc-f70b-4f63-94c9-4a702b9966d5.png)

**Comment by nratineau** [comment]
Hi @ArnOCP Got the issue previously because of some DB column missing. Can you try update from your version v3.0.0.17 the latest commit from the master branch?
https://github.com/nilsteampassnet/TeamPass/archive/refs/heads/master.zip
Report back if you still have the issue after.
If you still have the issue even after using the latest commit. Can you enable PHP error reporting to IIS
In your php.ini set 
`error_reporting = E_ALL`
and 
`display_errors = On`
If you are not getting any PHP logs you may also have to set system.webServer->httpErrors on IIS to Detailed instead of DetailedLocalOnly if you are not browsing from the server itself. Once you got the logs make sure to revert back the change.

**Comment by ArnOCP** [comment]
Hi nratineau,
Thanks for reply.
I tried to upgrade to 3.0.0.18, but now i have an error 500 :-(
![500](https://user-images.githubusercontent.com/97297565/189592282-86733e6a-53e5-4181-9421-f68cd26ed2b6.png)

**Comment by nratineau** [comment]
@ArnOCP Hi! When are you getting the error? Which URL are you visiting?
Any logs you can provide? Have you ran the upgrade.php process to upgrade.
Any info you can provide will help :)

-Nico

**Comment by ArnOCP** [comment]
Hi, sorry for the poor message^^
I'm getting this error just after the upgrade process, when i visit the http://mydomain
Which log do you need?
Yes i ran the https://mydoamin/install/
upgrade.php and it's seems to go to the end without error???

![wrtitable](https://user-images.githubusercontent.com/97297565/189823819-a277bb25-5556-471c-9b45-8c6fea5b1a96.png)

![database](https://user-images.githubusercontent.com/97297565/189823846-ae649390-8336-491e-b2a8-10400a1c2477.png)
![upgrade](https://user-images.githubusercontent.com/97297565/189823867-31287111-614f-40f5-afa6-4c71194a292c.png)

**Comment by nratineau** [comment]
To make sure I understand. You are getting the 500 just loading the site? You are not even getting the login page?
The IIS server logs should provide some helpful info.
Eenable PHP error reporting to IIS
In your php.ini file set
`error_reporting = E_ALL`
and
`display_errors = On`
Check the logs for any PHP error trace. If you are not getting any PHP logs, from the IIS management, Configuration Editor try to set:
`system.webServer->httpErrors`  to _Detailed_ instead of _DetailedLocalOnly_

**Comment by ArnOCP** [comment]
Yes i'm getting the 500 just loading the site.
PHP report none errors????

`#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2022-09-13 09:08:57
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2022-09-13 09:08:57 MYSERVER GET / - 443 - MYIP Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:91.0)+Gecko/20100101+Firefox/91.0 - 200 0 0 140
2022-09-13 09:08:57 MYSERVER GET /favicon.ico - 443 - MYIP Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:91.0)+Gecko/20100101+Firefox/91.0 https://MySite/ 200 0 0 15`

**Comment by nratineau** [comment]
@ArnOCP Without any logs, we cannot do much. Make sure you have enabled PHP error logging in your php.ini file. Without it, IIS logs will probably not catch anything.
Try browsing teampass from the server itself, using localhost. By default IIS provide more details only to localhost.

**Comment by ArnOCP** [comment]
Here is the IIS server log, nothing in php_errors.log ????
```
#Software: Microsoft Internet Information Services 10.0

#Version: 1.0

#Date: 2022-09-13 11:36:47

#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken

2022-09-13 11:36:47 localhost GET / - 443 - localhost Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 200 0 0 93

2022-09-13 11:36:51 localhost GET /includes/core/logout.php user_id= 443 - localhost Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko https://MySite/ 200 0 0 437

2022-09-13 11:36:51 localhost GET /plugins/store.js/dist/store.everything.min.js - 443 - localhost Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko https://MySite/includes/core/logout.php?user_id= 200 0 0 62

2022-09-13 11:36:58 localhost GET /includes/core/logout.php user_id= 443 - localhost Mozilla/5.0+(Windows+NT+10.0;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko https://MySite/ 200 0 0 31
```
The IIS seems to log a 200 code for the page?

Regards,

**Comment by ArnOCP** [comment]
Good morning,
I tried the 3.0.0.19 but i still have the same page an error 500 (not generated by the server ???)
can any one helping me?
Regards,

**Comment by ArnOCP** [comment]
i found a typo in my config files.... a / is missing in the directories entries
All it's OK thanks
