### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by bokhanych** [nilsteampassnet/TeamPass#3304]
### Steps to reproduce
1. Users
2. New
3. Fill in the fields
4. Submit
5. "In progress ... " <- don't stop!

### Expected behaviour
create new user

### Actual behaviour
Notification "in progress" don't stop. User not created.

### Server configuration
**Operating system**: Ubuntu 22.04 Server

**Web server:** Apache

**Database:** mariadb

**PHP version:** 8.1

**Teampass version:** 3.0.0.18

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 

**Operating system:** Windows 10

#### Web server error log
```
[Wed Sep 07 12:05:43.255346 2022] [php:error] [pid 1558] [client 10.200.200.31:52265] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'otp_used' in 'field list' in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/html/teampass/includes/libraries/Dat
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9504621/tp.config.php.txt)
abase/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/html/teampass/sources/users.queries.php(225): DB::insert()\n#7 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://example.com/index.php?page=users
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by gabesanerd** [comment]
I've got the same error coming up,

I did an upgrade from 2.x series to 3.x, which completed successfully.

After upgrade, when I try and put in password emailed to user, cant pass the spinning cog (in process), i/o activity on server is is nothing, so not really trying to complete the process.

Tried to create new user to workaround this problem, and getting same error as above.

`[Wed Sep 07 17:15:41.132618 2022] [php:error] [pid 4633] [client 192.168.0.14:54915] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'otp_used' in 'field list' in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/html/teampass/sources/users.queries.php(225): DB::insert()\n#7 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://linuxserver.tci.tcilab.com/teampass/index.php?page=users
`

**Comment by nratineau** [comment]
@bokhanych @ispf72 @gabesanerd  Same issue as, try the workaround code edit until a new commit correct the change:
 https://github.com/nilsteampassnet/TeamPass/issues/3305

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
