### ISSUE TITLE
SyntaxError: Unexpected end of JSON input during manual new user creation

### ISSUE THREAD

**Issue by piechota1989** [nilsteampassnet/TeamPass#3305]
### Steps to reproduce
1. Setup Teampass with instructions - commit ID ccfb790d439d2013a98306608c3e877c4ffa1304
2. Login as admin
3. Add new user manually (Users -> New -> Complete all necessary data -> Submit)

### Expected behaviour
1. Creation of new user

### Actual behaviour
1. SyntaxError: Unexpected ond of JSON input during new user creation
2. No usefull logs on apache -> /var/log/apache2/

### Server configuration
**Operating system**:
Ubuntu 22.04.1 LTS

**Web server:**
apache2 v 2.4.52

**Database:**
mariadb-server v 10.6.7

**PHP version:**
7.4.30

**Teampass version:** 
3.0.0.18  (commit ccfb790d439d2013a98306608c3e877c4ffa1304)

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
Firefox and Google Chrome

#### Web server error log
```
none of interesting data for debugging
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Nie udało się załadować elementu mapy źródeł: Nie udało się wczytać treści mapy źródeł http://xxx.lan/plugins/moment/moment.min.js.map: Błąd HTTP – kod stanu: 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE w Narzędziach deweloperskich
index.php?page=users:3050 {error: false, login_exists: 0}
index.php?page=users:2838 {folder: 'not_exists', role: 'not_exists'}
index.php?page=users:3574 {user_id: undefined, login: 'test', name: 'test', lastname: 'test', email: 'test@localhost', …}
index.php?page=users:3585 false
```

**Comment by alejlange** [comment]
Today I installed this version and I am with the same problem. It is a fresh install, and I can't find any log for debug this problem

**Comment by nratineau** [comment]
@alejlange @piechota1989 Seems the issue is from the latest commit: [sources/users.queries.php](https://github.com/nilsteampassnet/TeamPass/commit/ccfb790d439d2013a98306608c3e877c4ffa1304#diff-5cfd0506488a6204d4d43c041fd4922a5c6c9a9ea51a5600de983ab263bc1902)
Until it get's corrected in another commit you can update the line 225 from
`'otp_used' => 0,`
to 
`'otp_provided' => 0,`

**Comment by alejlange** [comment]
> @alejlange @piechota1989 Seems the issue is from the latest commit: [sources/users.queries.php](https://github.com/nilsteampassnet/TeamPass/commit/ccfb790d439d2013a98306608c3e877c4ffa1304#diff-5cfd0506488a6204d4d43c041fd4922a5c6c9a9ea51a5600de983ab263bc1902) Until it get's corrected in another commit you can update the line 225 from `'otp_used' => 0,` to `'otp_provided' => 0,`

Thank you, I had to put again the folder install and follow the installation step, and now is working after changing that line

**Comment by piechota1989** [comment]
![new_bug](https://user-images.githubusercontent.com/40562553/189328124-0489921a-229c-4dd6-8ee6-ba38c1d87171.png)
Here is new bug in commit ccfb790d439d2013a98306608c3e877c4ffa1304. Issue exist during new user creation.

**Comment by nilsteampassnet** [comment]
@piechota1989 the original bug was indeed fixed (thank you @nratineau :+1: )

Regarding the second one with the numerous popups, I'll fixed it.
The impact is visual (the code display the popup is set inside a loop ... so stupid)

**Comment by piechota1989** [comment]
@nilsteampassnet Issue can be closed.

**Comment by piechota1989** [comment]
Problem solved.
