### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by MushroomSquad** [nilsteampassnet/TeamPass#3309]
hi everyone 
im trying to configure ldap in team pass
but it takes me that error "error : 49 - Invalid credentials
80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 775, v4563"
what am i doing wrong?
![image](https://user-images.githubusercontent.com/30424265/189372090-45de59d8-be47-4c9c-a051-26cb9119ca21.png)

**Comment by nratineau** [comment]
@MushroomSquad For the username, try using the Distinguished name.
Would look something like: cn=padl,dc=corp,dc=tseh85,dc=ru
Adapt to the proper path in AD where your user was created ou=<OU name>,....
Error 775 also mean the account could be locked out, make sure the account is unlocked in AD.

**Comment by MushroomSquad** [comment]
Yep
Now it connected
But ldap users folder still empty
![image](https://user-images.githubusercontent.com/30424265/189600721-8e3e49db-2bc8-47ac-aeb0-1c422086e74f.png)

**Comment by MushroomSquad** [comment]
also
when i manually create user he doesn't show 
but he exists (i can see him im maria db, only manually created users)

**Comment by mj4b** [comment]
@MushroomSquad
Try this config.

Hosts: IP or hostname
LDAP Port: 389
Base DN = OU=Group_Users,DC=example,DC=example,DC=example,DC=example
Username: CN=teampass_adm,OU=teampass,OU=Group,DC=example,DC=example,DC=example
Password: strong_password

User Distinguished Name: distinguishedname
User name attribute: samaccountname
Additional User DN: OU=Users,OU=example
User Object Filter: (&(objectCategory=Person)(sAMAccountName=*))

This works with version 3.0.0.18

**Comment by MushroomSquad** [comment]
@mj4b 
team pass already connected to ldap
but for some reasons it can't write users to db (?)
and can't display manually created users 
"users" tub is empty, but users are exist
maybe i have troubles with maria db are something else?

**Comment by mj4b** [comment]
@MushroomSquad 
you may need to change some settings in teampass.
TeamPass location (URL): if you are accessing through ip in this settings needs to be the ip address of the server, when accessing with domain name you have to enter the domain name of the server.
Favicon (full URL): the same applies here.

In this way the local users will be displayed.

**Comment by MushroomSquad** [comment]
@mj4b 
Yep 
Thanks
It's displaying now
But ldap show me "In Progress" all this time 
![image](https://user-images.githubusercontent.com/30424265/189644262-cc605e78-bc33-415e-80a1-95c5bfcf78cd.png)

**Comment by MushroomSquad** [comment]
finally synced all needed
it was soooo slow
any way
thanks all

**Comment by IG-25** [comment]
Hi everybody,
I have almost the same issue. I have configured LDAP connection. Test authetication is successfully
![image](https://user-images.githubusercontent.com/114086335/191529163-117e6edc-2794-4e7b-b7e8-adc4969d029a.png)

When I try to sync LDAP users I got an error:
![image](https://user-images.githubusercontent.com/114086335/191529683-17486651-995a-480f-9e7c-7b9ec5292625.png)

Utlilities > Logs > errors I don't see anything

**Comment by domsivickas** [comment]
I have the same issue after updating from 3.0.0.17 to 3.0.0.19. Test authetication is successful, LDAP users can log in, but LDAP sync does not work got error "Unexpected end of JSON input"
Maybe some of you have soltution  ?

**Comment by MushroomSquad** [comment]
> @MushroomSquad Try this config.
> 
> Hosts: IP or hostname LDAP Port: 389 Base DN = OU=Group_Users,DC=example,DC=example,DC=example,DC=example Username: CN=teampass_adm,OU=teampass,OU=Group,DC=example,DC=example,DC=example Password: strong_password
> 
> User Distinguished Name: distinguishedname User name attribute: samaccountname Additional User DN: OU=Users,OU=example User Object Filter: (&(objectCategory=Person)(sAMAccountName=*))
> 
> This works with version 3.0.0.18

worket for me

**Comment by domsivickas** [comment]
For me only worked if:

Hosts: IP or hostname
LDAP Port: 389
Base DN = DC=example,DC=example,DC=example,DC=example (only DC)
Username: CN=teampass_adm,OU=teampass,OU=Group,DC=example,DC=example,DC=example
Password: strong_password

User Distinguished Name: distinguishedname
User name attribute: samaccountname
Additional User DN: OU=Users,OU=example (without DC)
User Object Filter: (&(objectCategory=Person)(sAMAccountName=*))
