### ISSUE TITLE
Upgrading from Version 2.1.27 to 3.0.0.17 - Stuck on sending e-mail to users

### ISSUE THREAD

**Issue by Michalis-Chatzimichalis** [nilsteampassnet/TeamPass#3312]
### Steps to reproduce
1. Download TeamPass V3.0.0.17 zipped folder to server
2. Backup DB + Snapshot Server
3. Steps from this documentation (https://documentation.teampass.net/#/start?id=upgrading-from-2x-branch)

### Expected behaviour
Successful upgrade.

### Actual behaviour
Stuck on task "Now sending new users password by email" and then no progress. Fellow user also had the same problem (https://github.com/nilsteampassnet/TeamPass/issues/3269). All users in the TeamPass have an email. Note: Didn't have a screenshot, so I used his. Same problem though.
![grafik](https://user-images.githubusercontent.com/74407318/189613480-58733fb2-6e15-4c19-a374-268a16c65983.png)

I then refreshed the page without cache (Ctrl F5) and the step of sending mails was skipped and it went straight to the **Finalization** step to give the absolute path of the saltkey. The path given was where the teampass-seckey.txt file was copied to. After clicking Start it just kept on loading (white message with setting-icon down right). This persisted for the next 1-2h so I reverted to the snapshot of the server and to V2.1.27.36.

### Server configuration
**Operating system**: Ubuntu 20.04 LTS

**Web server**: Apache

**Database**: MariaDB 10.9.2

**PHP version:** 7.4.3

**Teampass version:** 2.1.27.36

**Teampass configuration file:** included (Some values in the tp.config file have been replaced with placeholder values.)
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9549447/tp.config.php.txt)

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 10 

#### Web server error log
```
[Wed Sep 07 17:37:28.066815 2022] [php7:warn] [pid 108706] [client ip] PHP Warning: Use of undefined constant TP_VERSION - assumed 'TP_VERSION' (this will throw an Error in a future version of PHP) in /var/www/html/folderv3/index.php on line 78
[Wed Sep 07 17:37:28.103376 2022] [php7:error] [pid 108706] [client ip] PHP Fatal error: Uncaught Error: Call to undefined function defuseReturnDecrypted() in /var/www/html/folderv3/index.php:102\nStack trace:\n#0 {main}\n thrown in /var/www/html/folderv3/index.php on line 102
[Wed Sep 07 18:58:03.139924 2022] [php7:error] [pid 108708] [client ip] PHP Fatal error: Cannot declare class protect\SuperGlobal\SuperGlobal, because the name is already in use in /var/www/html/TeamPass/includes/libraries/protect/SuperGlobal/SuperGlobal.php on line 28, referer: [https://tppm.domain.ch/install/upgrade.php]
```

**Comment by nratineau** [comment]
@Michalis-Chatzimichalis Have you tried with the latest v3.0.0.18? If not, please retry the upgrade with this version and report back :)

**Comment by Michalis-Chatzimichalis** [comment]
I'll try with the 3.0.0.18 in a couple of days. Is the described upgrade process correct (by having 3 folders in var/www/html) ?
```
/var/www/html/TeamPass -> original folder
/var/www/html/folderv2 -> copied /TeamPass contents
/var/www/html/folderv3 -> new version 3.0.0.18
```

I also saw that in the /var/www/html/TeamPass/includes/sk.php file there's nothing on the sk line. Is that okay? 
```php
<?php
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');
?>
```

I sadly didn't install the 2.1.27.36 version and the employee has left us, so I'm not entirely sure if the sk.php is valid (in its form ^) or can be created during the upgrade 🤷🏻‍♂️

**Comment by Michalis-Chatzimichalis** [comment]
With Update to 3.0.0.19 it is stuck on the very first step (loginscreen) and this is shown in the apache2 error log

```log
PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/html/folderv5/includes/libraries/Encryption/Encryption/Encoding.php:225\nStack trace:\n#0 /var/www/html/folderv5/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString()\n#1 /var/www/html/folderv5/install/tp.functions.php(44): Defuse\\Crypto\\Key::loadFromAsciiSafeString()\n#2 /var/www/html/folderv5/install/tp.functions.php(84): defuseCryption()\n#3 /var/www/html/folderv5/install/upgrade_ajax.php(224): defuse_return_decrypted()\n#4 {main}\n  thrown in /var/www/html/folderv5/includes/libraries/Encryption/Encryption/Encoding.php on line 225, referer: https://domain/install/upgrade.php
```
