### ISSUE TITLE
Error when purge errors logs

### ISSUE THREAD

**Issue by ServiceMRE** [nilsteampassnet/TeamPass#3343]
### Steps to reproduce
1. Log in admin
2. Go to Logs -> Errors
3. Try to purge

### Expected behaviour
Logs purge

### Actual behaviour
Error

**Teampass version: 3.0.0.19

Resolution: comment the line 551 -> 554 in /sources/utilities.queries.php
<img width="481" alt="image" src="https://user-images.githubusercontent.com/78038849/192815771-ccf00650-4562-4234-81f2-4bf9a3c06a19.png">

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
