### ISSUE TITLE
Option to enable/disable SSL/TLS for LDAPS connection

### ISSUE THREAD

**Issue by piechota1989** [nilsteampassnet/TeamPass#3348]
### Idea
Could you add a feature to ability to turn on and off SSL certificate verification? Currently it is hardcoded inside sourcecoude to always veryfing SSL cert, but in our company we have AD with self signed certificate, which cause unability to synchronize users from AD.

As far as I know it is hardcoded in file `sources/ldap.queries.php`:
```
             'options' => [
                 // See: http://php.net/ldap_set_option
                 DAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD
             ]
```

**Comment by nilsteampassnet** [comment]
Feature committed.
Please reopen if needed.
