### ISSUE TITLE
LDAP Sync - Invalid DN Syntax

### ISSUE THREAD

**Issue by XeungXiang** [nilsteampassnet/TeamPass#3353]
### Steps to reproduce
1. Installed Teampass
2. Configured LDAP
3. Under User menu press LDAP Syncronize

### Expected behaviour
Shows the Active Directory users under the specified OU
### Actual behaviour
Nothing happened, just showing "In progress..." box. => Check out the web server error log!
### Server configuration
**Operating system**:
Debian 11
**Web server:**
Apache 2.4.54
**Database:**
MariaDB 10.5.15
**PHP version:**
7.4
**Teampass version:** 
3.0.0.20
**Teampass configuration file:**
Not needed.
**Updated from an older Teampass or fresh install:**
Not needed
### Client configuration
**Browser:**
Firefox/Chrome
**Operating system:**
Windows 10
#### Web server error log
```
PHP Fatal error:  Uncaught ErrorException: ldap_search(): Search: Invalid DN syntax in /var/www/teampass/includes/libraries/LdapRecord/Ldap.php:235\nSt
ack trace:\n#0 [internal function]: LdapRecord\\Ldap->LdapRecord\\{closure}()\n#1 /var/www/teampass/includes/libraries/LdapRecord/Ldap.php(235): ldap_search()\n#2 /var/www/teampass/includes/libraries/LdapRecord/HandlesConnection.php(171)
: LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/teampass/includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\\Ldap->executeFailableOperation()\n#4 /var/www/teampass/includes/libraries/LdapRecord/Query/Builder.php(656): LdapR
ecord\\Ldap->search()\n#5 /var/www/teampass/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#6 /var/www/teampass/includes/libraries/LdapRecord/Connection.php(352): LdapRecord
\\Connection->runOperationCallback()\n#7 /var/www/teampass/includes/libraries/LdapRecord/Query/Builder.php(658): LdapRecord\\Connection->run()\n#8 /var/www/teampass/includes/libraries/LdapRecord/Query/B in /var/www/teampass/includes/libr
aries/LdapRecord/LdapRecordException.php on line 26, referer: https://*********.*******.******/index.php?page=users
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Not needed
```
### Resolution
https://github.com/nilsteampassnet/TeamPass/issues/3155#issuecomment-1153199341
Without this modification the **search** function in **includes/libraries/LdapRecord/Ldap.php** file receives a faulty **$dn** variable, because it starts with a comma character: ``` ,OU=*****,DC=*****,DC=***** ```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
