### ISSUE TITLE
Problem after LDAP user changes Password on 3.0.0.19 

### ISSUE THREAD

**Issue by domsivickas** [nilsteampassnet/TeamPass#3354]
1.steps to reproduce
1. Upgraded 3.0.0.18 to 3.0.0.19 Teampass
2. After User changed LDAP password 
3. Authorize with new credentials
4.  Giving error when opens password in folder
5. Can't see or copy password from folder

Expected behaviour
Shows passwords after changed LDAP password

Actual behaviour
Blank space on password cell, just showing "Coution SyntaxError: Unexpected end of JSON input"

Server configuration
Operating system:
On Docker: richarvey/nginx-php-fpm:1.10.3
Web server:
nginx 1.18.0
Database:
MariaDB 10.5.
PHP version:
7.4
Teampass version:
3.0.0.19

Client configuration
Browser:
Firefox/Chrome
Operating system:
Windows 10

NOTE: Problem solve after let generate new OTP for user that having this error. But everytime gereate after user change password is nonsense.

=
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/74267968/194033422-2cf75e56-4ec1-458b-aadf-5e7d01395ca4.png">

**Comment by nilsteampassnet** [comment]
I forgot to label this defect.
It should be fixed among latest commits.
Can you please upgrade.
Reopen if still having issue.

**Comment by antoweb** [comment]
After user change password ldap teampass need a new token otherwise password filed are empties
