### ISSUE TITLE
LDAP Synchronization/Login not working, despite proper configuration.

### ISSUE THREAD

**Issue by daniel-jurk** [nilsteampassnet/TeamPass#3377]
### Steps to reproduce
1. Login as `admin`
2. Configure and test LDAP settings
4. Turn off maintenance mode
5. Go to `Users`
6. Click on `LDAP synchronization` and click on `List users`
7. Logout of `admin`
8. Try to log in with LDAP

### Expected behaviour
The list should be updated and show all users that can be synced from the LDAP Server, in addition I should be able to log in with the credentials provided by the LDAP server

### Actual behaviour
1. When trying to list LDAP users: List stays empty with no error message.
2. On login attempt with LDAP: Login credentials do not correspond!

### Server configuration
**Operating system**: Ubuntu Server 22.04

**Web server:** Apache 2

**Database:** MariaDB 10.6.7

**PHP version:** 8.1.2

**Teampass version:**  3.0.0.20

**Teampass LDAP configuration**

![S1](https://user-images.githubusercontent.com/83063445/196664443-5ccfbdf3-69ca-4002-983b-6e3ceb6a0288.png)

**Updated from an older Teampass or fresh install:** Fresh Install

### Client configuration
**Browser:** Firefox & Chrome

**Operating system:** Fedora 36

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```php
Object { error: false, entries: [], ldap_groups: [], teampass_groups: (1) […], usersAlreadyInTeampass: [] }​
	entries: Array []
	error: false
	ldap_groups: Array []
		length: 0
		<prototype>: Array []
	teampass_groups: Array [ {…} ]
		0: Object { id: "1", title: "Default" }
			id: "1"
			title: "Default"
			<prototype>: Object { … }
		length: 1
		<prototype>: Array []
	usersAlreadyInTeampass: Array []
		length: 0
		<prototype>: Array []
	<prototype>: Object { … }
```
The Arrays are empty, which corresponds with no users being displayed.

When I tested the credentials in the LDAP configuration panel, they were accepted. The console output contained information in the arrays regarding, my credentials:

![S2](https://user-images.githubusercontent.com/83063445/196667722-66bf5195-9f6f-4c32-82d1-a34286497f02.png)

**Comment by xvisor16** [comment]
You should try adding a User Object filter in your instance i would say something like: (&(objectClass=user)(uid=*)). Replace user with the actual objectclass your specific users have. It is always best to use this in every LDAP client implementation to reduce the size of returned objects, which offcourse speeds everything up and it is generally better practice to only return items with specific values instead of all. You don't want certain security objects to show in your list.
