### ISSUE TITLE
Bugreport show LDAP-password

### ISSUE THREAD

**Issue by Nachtlichtermeer** [nilsteampassnet/TeamPass#3380]
### Steps to reproduce
1. create bugreport
2. search for 'ldap_bind_passwd'

### Expected behaviour
'***' should be shown

### Actual behaviour
real LDAP-PW is shown

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache 2.4.41
**Database:**
8.0.30
**PHP version:**
7.4.3
**Teampass version:** 
3.0.0.20 commit a798c9dc9184b5b14184c93c898d727b6418f1e1

### Client configuration
**Browser:**
Firefox 105.0

**Operating system:**
Ubuntu 20.04

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
