### ISSUE TITLE
API command authorize not recognized

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3381]
Using newest commit
Every time when I try to acess the api, the only thing that would return is:
```
Notice: Undefined offset: 4 in /var/www/html/pwdb-lab.ecofis.de/api/index.php on line 46
{"error":"Access denied"}
```
Showing debug infos, it is clear that the index of var $uri is incorrect:
```
print_r($uri) ->
Array ( [0] => [1] => api [2] => index.php [3] => authorize )
```
Changing the variable in line 46 and 51 in /api/index.php from $uri[4] to $uri[3], authorization works

After authenticating a GET-Request to api/index.php/item/inFolders?folders=19 shows the following error:
```
Bad Request
Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
```
Setting LimitRequestFieldSize to 200000 in virtual host config solved the problem
This should be part of the documentation as apache2 (in example) limits the header size to 8KB by default

**Comment by nilsteampassnet** [comment]
@useronkel 
Regarding the 1st point, thank you, the value is indeed dependent of the server uri.
I did a fix for this to make it generic.

Regarding the 2d point, thank you too. I didn't notice that specific point.
I need to read more about this practice.

**Comment by useronkel** [comment]
You are welcome :-)
