### ISSUE TITLE
Don´t Allowed Password greater 40 Characters

### ISSUE THREAD

**Issue by angelitodiaz1** [nilsteampassnet/TeamPass#3392]
### Steps to reproduce
1.Install  TEAMPASS V 3.0.0.20
2. Generated new item password with a password greater than 40 characters.

### Expected behaviour
Save Password.

### Actual behaviour
Reflect error:  "Password longer than system maximum (default 40characters)"

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 
3.0.0.20
![Screenshot_1](https://user-images.githubusercontent.com/6534435/199317311-203cb637-adb6-497f-95c5-fc501034f668.png)

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by tbalbers** [comment]
Hiya,
You've probably already solved this, but for others finding this issue:
Log in as admin user, go to Settings -> Options  and look for "Maximum password length". Here you can set the max allowed length.
@nilsteampassnet you can close this issue now :)

**Comment by angelitodiaz1** [comment]
Ohhh thx. Although is a little delayed the query. I am still testing.
