### ISSUE TITLE
Unable to list LDAP Users using LDAP Synchronization

### ISSUE THREAD

**Issue by mrocaruano** [nilsteampassnet/TeamPass#3412]
I am trying to setup LDAP with Teampass, this was my following configuration. 

Host: LDAP IP Address
LDAP Port: 636
Base DN: ou=users,dc=test,dc=com
Username: cn=admin,dc=test,dc=com
Password: testpassword
User Distiguished Name: dn
User name attribute: uid
Additional User DN: 
User Object Filter: (&(objectClass=user)(uid=*))
LDAP server type: OpenLDAP
Use LDAP through SSL (LDAPS): YES
Use LDAP through TLS: NO

When I test the current configuration, I get success, user authenticated. The issue starts when I go to Users and do LDAP Syncronuzation. It gets stuck in progress and I get the following errors in the apache2 teampass_errors.log file.

PHP Fatal error:  Uncaught TypeError: Illegal offset type in /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php:495\nStack trace:\n#0 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\\Connection->retryOnNextHost()\n#1 /var/www/html/TeamPass/sources/users.queries.php(2462): LdapRecord\\Connection->connect()\n#2 {main}\n  thrown in /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php on line 495, referer: https://IP/index.php?page=users

and on the web server console I see this:
![Screenshot from 2022-11-14 14-58-29](https://user-images.githubusercontent.com/43893495/201764836-4afb6598-fd64-41cb-9d72-7eeac8c34537.png)

Any help is appreciated!

**Comment by jonildosantos** [comment]
I have installed TeamPass yesterday and few erros was resolved by using Ubuntu 22.04.1 with mariadb 10.6+, apache 2.4+, php 8.1 and finally the collate of database to utf8, see below:

> create database teampassdb character set utf8 collate utf8_bin;

**Comment by mrocaruano** [comment]
I had to manually add my connection in /var/www/html/TeamPass/sources/users.queries.php

See screenshots, variables $username1 and $password1 were set at the top of the file. Also NOTE if you have special characters such as ", make sure you escape the character in PHP. 

Everything worked after that. You still will need to fill in the correct LDAP query information in the LDAP Interface, this was just issues connecting to LDAP Server via port 636.

![image](https://user-images.githubusercontent.com/43893495/202740483-3b7595e2-70b7-4f74-a219-0a469f50793d.png)

**Comment by CleverCircuits** [comment]
I have the same issue with Teampass 3.0.0.22
My queries.php file looks a bit different -> I couldn't understand what to add in this file and where. Could you please explain a bit what you exactly did?

Thanks

**Comment by CleverCircuits** [comment]
Here a piece of my file:

$connection = new Connection($config);

            // Connect to LDAP
            try {
                $connection->connect();
            
            } catch (\LdapRecord\Auth\BindException $e) {
                $error = $e->getDetailedError();

                echo prepareExchangedData(
                    $SETTINGS['cpassman_dir'],
                    array(
                        'error' => true,
                        'message' => "Error : ".$error->getErrorCode()." - ".$error->getErrorMessage(). "<br>".$error->getDiagnosticMessage(),
                    ),
                    'encode'
                );
                break;
            }

**Comment by CleverCircuits** [comment]
Solved thanks.

**Comment by CleverCircuits** [comment]
Check your ldap configuration.
I used the following settings:
Hosts : yourdomain.com
BASE DN : dc=yourdomain,dc=com
Username : cn=username,cn=users,dc=yourdomain,dc=com
Password : youruserpassword
User Distinguished Name : distinguishedname
User name attribute : samaccountname
Additional User DN : cn=users
User Object Filter :  (&(objectCategory=Person)(sAMAccountName=*))
LDAP server type : Active Directory
Certificate check for LDAP TLS : LDAP_OPT_X_TLS_NEVER
Local and LDAP users : YES
Newly created user is administrated by : Managers of role Administrators
Newly created user has role : Default

**Comment by CleverCircuits** [comment]
This configuration should work between Teampass and your Active directory. Once you test it and it works, then you can synchronize your active directory within teampass.

The tricky think with Teampass is that you have to create the user in teampass and once you synchronize the active directory users through ldap, then you can check the box: user ldap credentials for this user.
