### ISSUE TITLE
Problem with the password length [3.0.0.20]

### ISSUE THREAD

**Issue by roccodelux** [nilsteampassnet/TeamPass#3415]
DEFECT 
Password is too long

Hello Nils, there's a problem with passwords, which are longer then 40 characters.

Description:
It's not possible to create an entry with a password longer than 40 characters.
Can you please increase the limitation of the password length?

OS Ubuntu.
Installation to Docker

**Comment by nilsteampassnet** [comment]
@roccodelux 
Please upgrade this by default limit from the administration settings page ;)

**Comment by roccodelux** [comment]
Thanks @nilsteampassnet .
 I hadn't seen this option in the settings page 
;-)
