### ISSUE TITLE
Little Bug: Creating new folders in a row

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3420]
Latest Version (Commit 0d0b370)
Little Bug: When creating new folders in a row, you have to Refresh with click on Folders on the left side, Refresh-Button isn't doing his job ;-)
When you create more than one folder in a row, all folders are remove from the Dropdownlist and only Root is showing up.

**Comment by nilsteampassnet** [comment]
Oh yes, confirmed .. how strange!

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
