### ISSUE TITLE
FontAwesome URL isn't being rendered as expected

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3429]
### Steps to reproduce
1. Login into TeamPass.
2. Create a new item.
3. Click into Font Awesome link URI.

### Expected behaviour
Font Awesome page should be opened.

### Actual behaviour

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2974895/204044377-6e6cb8be-60a6-4daf-9eff-071d2aa751de.png">

The quotes of URL from translation isn't being rendered as expected, even it being exactly as the English one. Not sure if it's an issue related to translation or TeamPass itself.

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10087406/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** Updated from 2.1.27.36 to 3.0.0.21
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 107.0.5304.110

**Operating system:** macOS 12.6.1

#### Web server error log

No errors being reported at Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
