### ISSUE TITLE
admin interface does not work after update

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3430]
1.  updated from version 3.0.0.16 to version 3.0.0.22
2.  logged into the admin interface
3.  left menu does not work

**Operating system**: windows

**Web server:** 
Server version: Apache/2.4.54 (Debian)

**Database:**
Server version: 10.5.15-MariaDB-0+deb11u1 Debian 11

**PHP version:**
PHP 7.4.30 (cli) (built: Jul  7 2022 15:51:43) ( NTS )

**Teampass version:** 
updated from 3.0.0.16 to  3.0.0.22

**Teampass configuration file:**
[config.zip](https://github.com/nilsteampassnet/TeamPass/files/10095862/config.zip)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[config.zip](https://github.com/nilsteampassnet/TeamPass/files/10095862/config.zip)

### Client configuration
**Browser:**
Chrome last version

**Operating system:**
Windows 

### Logs

Insert your we
[teampassUserCreate.zip](https://github.com/nilsteampassnet/TeamPass/files/10095859/teampassUserCreate.zip)
bserver log here
```

#### Web server error log
```
[webLog.zip](https://github.com/nilsteampassnet/TeamPass/files/10095871/webLog.zip)

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[teampassAdmin interface.zip](https://github.com/nilsteampassnet/TeamPass/files/10095876/teampassAdmin.interface.zip)

Insert the log here and especially the answer of the query that failed.
```

**Comment by wease1** [comment]
[teampassAdmin interface.zip](https://github.com/nilsteampassnet/TeamPass/files/10095877/teampassAdmin.interface.zip)

**Comment by nilsteampassnet** [comment]
Did you performed a CTRL+F5 to clear the local browser cache?

**Comment by wease1** [comment]
Sure. And opened the browser in incognito mode and used a different IE/ Edge / firefox

**Comment by wease1** [comment]
I think the problem is in the mysql database. I created a new server with version 3.0.0.22 and after importing my database, the left menu and other buttons in the admin interface stopped working.
A long time ago, at the very beginning, I migrated version 2.1.27.11 to 3.0.0.16 and now to master release

**Comment by wease1** [comment]
Navigating through the menu in administrator mode is only possible by explicitly specifying a link in the browser's address bar, for example

/index.php?page=actions
/index.php?page=utilities.renewal
/index.php?page=api
/index.php?page=emails
/index.php?page=ldap

and etc

**Comment by Kr00t** [comment]
same problem.

**Comment by wease1** [comment]
> 

do you fixed this problem?

**Comment by wease1** [comment]
> same problem.

do you fixed this problem?

**Comment by wease1** [comment]
> same problem.

Change language to default English. Or replace your language file to english file
