### ISSUE TITLE
Unable to create a user 

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3437]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1. Creating a new user
2. Filling in the fields on the page
3. Submit button

### Expected behaviour
New user added

### Actual behaviour
The user was not created as a result of an error

![image](https://user-images.githubusercontent.com/12623112/204996810-a630f1d9-194a-4d49-9e9a-4c293a6571f3.png)

### MYSQL LOG

221201 10:53:26   4496 Connect  pass@localhost on dbpass using TCP/IP
                  4496 Query    SET NAMES latin1
                  4496 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                  4496 Query    SELECT increment_id
        FROM dbpass_sharekeys_items WHERE user_id = 1
                  4496 Quit
                  4497 Connect  pass@localhost on dbpass using TCP/IP
                  4497 Query    SET NAMES latin1
                  4497 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                  4497 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                  4498 Connect  pass@localhost on dbpass using TCP/IP
                  4498 Query    SET NAMES latin1
                  4497 Query    SELECT id, fonction_id, groupes_interdits, groupes_visibles
                FROM dbpass_users
                WHERE login = 'testtesttest'
221201 10:53:28   4497 Query    INSERT INTO `dbpass_users` (`login`,`name`,`lastname`,`pw`,`email`,`admin`,`can_manage_all_users`,`gestionnaire`,`read_only`,`personal_folder`,`user_language`,`fonction_id`,`groupes_interdits`,`groupes_visibles`,`isAdministratedByRole`,`encrypted_psk`,`last_pw_change`,`public_key`,`private_key`,`special`) VALUES ('testtesttest', 'testtesttest', 'testtesttest', '$2y$10$.08Zk0vhOrMdeI8m5gpn.eFbtvMGG1RTuaC/hGZ5FSo4usPiSHly.', 'testtesttest@test.test', 0, 0, 0, 0, 0, 'english', '1', '', '34', '0', '', 1669881208, 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBcTUzc00xcFc0MkpCQmc5cXZIcE0NCkV1MGRkbDBBaU1IQkQrMUhKU2hnanNHajFORXdoS0djSTJJT24xdTFnaFo5anBnYStvVlA1cEdwK3llaUhoaEENCm1mUDVtMUlsWFdSeHVCWnI4am5KWlptR1lVTnRMMHV5YklwZWltZjZsRWZNWFQ5M3duSUIrakY1eHhsOFdLdlUNCnpzNkphQjk2Um1rME80aWs1T3d2YjNEamZCdVZwc2JhWlJmdWF5Tmh5ckRzZSt2MFY5SWF2cndCVmt2Q2VFcUwNCjZDZU0xU2JpUW5QVUhWa01SMkRvTzFKNGJDMHF2dVFHdW9TODArM2Iva243M1krTzg4M2dQeUFSZVZhVXFaS2wNCmJxVWFDWnZZK2ZFdWtnYmY5THZzT3B5aXdmZ3JvcWRhNEdDR1puak1hdmI3bEU4UHhISks0d1BQeU03amRZbm0NCnhGeVlnbkpIZ0NpL1dpYUpIVklvOTc5MlpxTm03N2UrOHVFMXdUNjFLSjJEL1VxZWZ3WGNiaXhqODBtcFV6K0INCmk1ZkFDUHhkL1RmdnorVnZDd1dhS1ZSWG9MNEFYY0hWWnhFRktkbHNSdndPbUhyNlZZMkhXZk9hL0xEK0h3cFgNCmJmQmdMdzBGRFNsUldtanRvOC96RjVNYUlNV2ZudE1vd1M5cXdUUFhQdW15RzV4cWZnWnhWMWdDeFJpZ1BWVDUNCk1LbzMycm8yY2I1NURZdmlic2tDd244Unlob3dKMHhJQnp4ZmE0TkR6MzJFNFNxamZzdC90UkpZZmlXT2xIMnANCi95emNJYWtrVnM5aUdHNkUrYk9Pc01jRkltMURiRWpocHVzbC9lWmhmRVNMajlURWdLTWpkS3NOK0VhNGJ5SDYNCnNtY1J3c3lKZ1hmYTFmN1RvdmQyT3gwQ0F3RUFBUT09DQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=', 'T2fVN8SPO6f+B+3Y0IujAj4NFIEQPOsHBIVdZA4N6zBIhvn0fCH6hP7+mIc31RO0A+bOO6VskWE2utei7sKBpJ5z/kqPK+LYAndq+IovPIibE+9btON7UPIxaBKvIHBS799hkVZtYRE9s3u34/lowMhSd9G2MTI23fz9J8e+GOuxokf0jrAM7NTTF8wuCcsT/WL9N/Hos9gtR8wiDyPcdMW6Y3/no2lK5GxB4rrDgyG5Eb9xTBesQUpszu8Djvqor3wR5r5ByUxgeFRL4vHVcDGScW3vcN2LcDeS8eC99pc/Oi/QALdKLPPTTDnqvqf5emraf2uclvuk0auBJ5NYsKvmskCVcA6RNrr+ix6yFCSJmO8u6gk983dvoAGUZ34rW9lzdqI+PQKAhIi+k42WkEwM3MWavwWOPs/Op6jCPXhkiZT7XmYLhoHEYLld2Wq3cjiN08Bei0jOD9wcx/HpaUEDCHppMRTI6KCtvVFHgJiny22tZ2iQetyyUfDZtQqjgPWiE7+LsrlyvJxR9D6/1mBUiAh24zi/shZkIJLH1kQBpdMyEhZ9nu4zrYmoHmSzLGc4+Dmf8KRrj+N194BjeX/h6jv0uMiHSRK7xuiPY786xSRfakaAcAK+C+lHx3Cm+nGYvrR1Hr4UbvNMiDJWW06ZXKI3aTHW3jSsUP28k4xsSMZp5okoQBIl7azflpcBXKWi9/na0q8b9NafU6YoM3Mo0soQAgEKku7gN1vlY8t+MYX65rYhQKUbpdYoF/6VlcvklxF8jxRnQ3P8K/XjerAuv9pHIwGVdgXz1CLwwtS+YqlHtflxS3xaiNX2tPVYSQ0StxDlC+FlWn6C88R9VVwyc+47nCOGroBofobl2g+Y+J25ZWePZnJzVrZR9ez/Y41ZjH0r2mlaDTaxKyBIPKGF3q38G+UnycIzoxLz962eO3jUn4/E/RAZvQ0yj3h+HftUjmo4nb5bmfI7LzpY00R9Ir/GDe86m+n3Fq/BxktbdAiyY028zsrdw3iKzW9LrFtPFcWF8VBSd46N2i2oPxI8oPifFx5pqhRSZtdfmD21m71oowf1J7DOTZ+W7TTwrYjE9B/GOFjaGZ+njZVxEFYtAlFLAJSRnKe3MuRSpGsUi6Uo7cCKebjGthpWkvPhq9GgmImcYGJt7ztHjWWYKssRVNli9mBf9SsFu1IwEYHcrQ7lqMshZKNnt2Q8/7S06pKjfFN2DHsP68M9M/vmqDTUNsQ2gBOyBCqmuIsA/Kag7p1svkTxVBNF1oBmOBgw6iQfg0j/DLlNVtlkr7ga+uzdf7NnxLyImA896143qLtb1d16rJxWSC3KGuNd0tUhdJP6HQQaROzoY01ry9X0+MGni7rVNgLOgq3Bw+UXTSVs3vY976h5Q/pOGzaQ5HTuKj6OprzP8hVr7rjxAH3VU4jVXKaPLmQ7xjI4EHsnGmvNp8xjtl5PeUVvTIHRo2l8lifQACGvcX45MlQxRdU4lEEUxsnbj5LLEVHCaHKUZ6igtIW1FvXcUkDY2O+Kg5ACDiKVgU42hDkQLmDkeOJwfz74qt692T24OmPJrij4oK6g8BfQn1zXUIJOCUicF9EsbQsWhRCxCAgkJlJdukujk28jAKcp4K2H5ZrrWN9a/E3fvI2XA+w36ZZmuySlPfx4WXomum4KF94PamBXkih1N4CKFotqO8bRL/1EqT0Uw9dLLCYGUvtxAVZfTAVwdCIFXVvKhrOb604M6fdulG/ksNRZXv6F5Y59rgsrmrgSOByr+HpPtHCToGwVFkK2bu7GfXG+Kb49FQWenOLILg/Gr1AkNVK7zKyOEE9q5FW/6Yea5MZlPiwBQa3RqFdZIF3TfVzb/f7ZOj5v+Mnr1NOLDDGvXvsgX6XCumPhwwT92mwyn7AKX4uGzp1Nyrf0YIRMvLzeRGaxqfvez1bwla4Sv4qIa4X0xGl5IAEKOK8iKLvDWgf5aUOS46IeirPrdcIo6pBzwMGgVCcuCRPpoFiL9uIohvoHrWx7yQ/JiYga/9DkgRvq6FXuWKErYw8A5mkezlK8kCwT+GBJPeY15UBLIOCkVmnL8H+rUIFsemZmU4MzK7x1EnxR4z9N9U9ZxNsgSG0TyeZiqxHiliK2s1HOTRSPcW1YuSslAhpTcg8ZIErc3ajW2oL91ANKwQYa3UwhJFIw79JpojbkWBoVJVKRG8kvh00WH3TNRqAfnSYf5T0nSM3e45NsUQ4vuAK8HD/h2dCMGpS6hqF+2r7V9c0yw8M4YEjWeh26Xph/7EfQGXehD273lv1+YVeeLRnalDfy6ZLeZXAAuzFDBl+BCrGmGnztiwdSzDYoFzy8oifRcmfJ2bfBULGBG5Nq45YgN4zEcdmVT5DAFHd/ygQ83wYh99EOeAMW980+Ev5b9MfpA49un9qaP/I0lPMgtSazr0Cv0lEuZSOxCSe2HXxwPC/oS2Gz9G982cPtriCUz0XqV8QuG4ukJGFhEv2b2dZmpkTNo2DqcQmOYzXQeJmy3f6KmDJR8B0C5SpNadrC9J8yXFD2ksWDNXbCr5EH1QuC/Df7OpbIJ2s9b714wqtR/mCH4MYWJFuItx80cHpfNqHxjnXaxyrM4REipgl+JeoJNb7Q///Db4SQwAiGhx+pa3ACXE0wj5LvafBwNWF6EPyHEt+jeXvV2hlfYW1cmUOw3ZPRhwJL8PSfjTDfIXhDTPeLW7E37HZgZ1M6rtXC/0pwt+MFhtpTvAHI17raO1DpYzEWKWkVR1f225J6OLHrL6kaTDCnoRfOvvfCDzad9y6cY5Oxnq/+wYO5Bqg/gM3bJVqRBXv0btPVvLHEhtOBtyop1NGItKjn1o5pC3lXhqskoDsYzeWDyOd8NKZ0av6WBFnVyrYQb82LST6Yc5S6jVnEeeO1rX3y2CFOg6Cqt88JKrSHZ0aMhOcQ7bvLQx0v4MO8wJqOXGLGCyxuV/S5blv7m/wOXx5oHBRvLO9VM5Y4XH/epDIE7GrDD8Vc76ggERH+ljL4UJdzAaBlLmGYxdIy0xn48r5UO6pjuOmmr+FuFYBUujfi898g7qNer+inGpmyuwovD3GTMq/6xoyL/nzVXYXRPShL751n/6kkO2Smb7164tY74Dsqr1m/ytLj+31m9XUx2eFl1x/cCIrlHmvJ0p1DBUsy3WAl5CnZ85R0ODd1CcBTAeiDRTWhVgTHx4DQ16M3MeL8YVaQSvMpgSZs3d+6D4yoNZvO36NgA7RE7zvQ9lTTcKi6lK6ead0mjVlNRJxE0Rz+8vG/BRe/VkDumYql9E/mbFHTAlz1yn4UBN1ve+aRlhXsx2qEPvIyJ0p9Gr3+Op+zlqzOXg/74g+JLzXgve6/TRaUA8hIhNqo/1ZZhraV0kkYVF6iydE619ClTbGIdJk98FXQOIt9sphzuAgSSDoJk6PbMG8g4q0AXeOHndIUsmi1BiTYx2wT8XCGmztakqGQE+i4QqApnDBAYEKf2vERb7eP9nPguGKWrYzlz+ZqQj/hGds370+S1Wr7tjlSKCYGzmbiNEbZpLI2wawIMUgXhthN7YE6+s1Q8ywMkDO3msS7q3FAk2lJYWiqfuaKLe6nkwR6gEtG3I7Q9iQzsjHixkFCQwtOX8f49JgTBsZSqcrB/ku2MXGN23SajQIEmWXfoRk5OxiGRGUUG2v6RhMwuEmxH8LIkxa7ww1yJvkv3ZjsA6rG4Ynfr0Gfsv9e+qbWg7hBm7CvY/yNl/pe1H3P+02H0rDM/Kh1i8oZH+lULosoAEEjHIJKE+mriTsfbKNHdCNByZ3GGchh0Pu11CZA/9K0DLlBnLYAufGgGnzYtjJ5BzntFfIdGe0FWXH9yD8JorQro4eLHX2IlM5aYotS7Om5j2kJo5hxpmL/F7PpaxkYTYjDbj7nhbXzcZnoezovImIoikSnYgv/Ji10Rwn8Sspb6BGEWE364fApIvYMnxQ5/DDtj2sOT3ZrKbCQ0M/PymyBuYHtoMRRUeDRHB0NDBY8mlMPFOJqZVapAgd7omijczWTn/YenC4AnTWJmXHE3e2uZQyAmPoVWtGlQFnZMiPPRI49A29GQlMgATcNee4OHeLwQBacXlbuUEd/i70Jfvssa/q0d8kU8ibiTMKDdJ3fKkuDXKdj2WJ8z+/2Sdum8ZDo2QkK2GN+figa0cMHoOU7R7hTWwOGr1/EXr8Y4UgKJhqDSNJRPFX059hctqslFLdF5ef2J7/r4CeM2zd3+tPknaB5XOICtXJtngvxhDAFjQBmwY5shqvkm27L3jgX1u6+zHCtUS0QH16JVDakvmHnSuIhEqoJLfJQajPQK4kSec7KDazjia3F32XCaxTInCgOJxq41fe108E1e2BbDTPknrvOr7ErZBLWg2xpv/s5SrELm7SB0q4=', 'auth-pwd-change')
                  4498 Quit
                  4497 Quit

### Server configuration
**Operating system**: Linux pass 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

**Web server:** Apache/2.4.54 (Debian)

**Database:** 5.5.5-10.5.15-MariaDB-0+deb11u1-log

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '0',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/pass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/pass/upload',
'url_to_upload_folder' => 'http://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/pass/files',
'url_to_files_folder' => 'http://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'sAMAccountName',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '["1"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;cb_select_all;',
'send_stats_time' => '1512900881',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '20mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '1000',
'upload_imageresize_height' => '900',
'upload_imageresize_quality' => '99',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '600',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/pass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Chekc',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'max_last_items' => '20',
'enable_massive_move_delete' => '0',
'copy_to_clipboard_small_icons' => '1',
'offline_key_level' => '25',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'admin_2fa_required' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'password_overview_delay' => '9',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'maintenance_mode' => '0',
'ldap_hosts' => '',
'ldap_bdn' => '',
'ldap_username' => '',
'ldap_password' => '',
'ldap_dn_additional_user_dn' => 'o',
'duo_ikey' => 'Admin',

```

**Updated from an older Teampass or fresh install:**
2.1.27.11

### Client configuration

**Browser:** Chrome - 107.0.0.0

**Operating system:** Windows - 64bits

### Logs

[MySQLlogs.zip](https://github.com/nilsteampassnet/TeamPass/files/10130401/MySQLlogs.zip)

#### Web server error log

[logs.zip](https://github.com/nilsteampassnet/TeamPass/files/10130394/logs.zip)

```
Undefined index: path - /var/www/pass/sources/main.queries.php (1106)
```

#### Teampass 10 last system errors
```
 * 31-Mar-2022 12:49:14 - Query: SELECT folder_id, type
                FROM dbpass_roles_values
                WHERE role_id IN ()
                ORDER BY folder_id ASC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
                ORDER BY folder_id ASC' at line 3<br />@ /sources/users.queries.php * 31-Mar-2022 12:48:42 - Query: SELECT folder_id, type
                FROM dbpass_roles_values
                WHERE role_id IN ()
                ORDER BY folder_id ASC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
                ORDER BY folder_id ASC' at line 3<br />@ /sources/users.queries.php * 21-Mar-2022 17:52:12 - Query: SELECT folder_id, type
                FROM dbpass_roles_values
                WHERE role_id IN ()
                ORDER BY folder_id ASC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
                ORDER BY folder_id ASC' at line 3<br />@ /sources/users.queries.php * 09-Mar-2022 17:49:03 - Query: SELECT folder_id, type
                FROM dbpass_roles_values
                WHERE role_id IN ()
                ORDER BY folder_id ASC<br />Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
                ORDER BY folder_id ASC' at line 3<br />@ /sources/users.queries.php * 20-Sep-2021 15:39:34 - Query: INSERT INTO `dbpass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1632141574, NULL, '10000042', '10000076')<br />Error: Column 'label' cannot be null<br />@ /sources/users.queries.php * 15-Sep-2021 13:10:25 - Query: SELECT user_ip_lastdate
                    FROM dbpass_users
                    WHERE id = 10000087<br />Error: Unknown column 'user_ip_lastdate' in 'field list'<br />@ /sources/main.queries.php * 16-Jul-2021 14:33:14 - Query: INSERT INTO `dbpass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1626435194, NULL, '10000042', '10000036')<br />Error: Column 'label' cannot be null<br />@ /sources/users.queries.php * 15-Oct-2020 16:02:02 - Query: SELECT email,login FROM dbpass_users WHERE id= undefined<br />Error: Unknown column 'undefined' in 'where clause'<br />@ /sources/items.queries.php * 15-Oct-2020 16:00:35 - Query: SELECT email,login FROM dbpass_users WHERE id= undefined<br />Error: Unknown column 'undefined' in 'where clause'<br />@ /sources/items.queries.php * 14-Apr-2020 10:27:31 - Query: INSERT INTO `dbpass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1586849251, NULL, '10000042', '10000048')<br />Error: Column 'label' cannot be null<br />@ /sources/users.queries.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
[passUserCreate.zip](https://github.com/nilsteampassnet/TeamPass/files/10130358/passUserCreate.zip)


```

**Comment by nilsteampassnet** [comment]
First step, please use latest version on your server by upgrading

**Comment by wease1** [comment]
> First step, please use latest version on your server by upgrading

When upgrading to a new version, new bugs are also added to this one
1. [admin interface does not work after update #3430](https://github.com/nilsteampassnet/TeamPass/issues/3430)
2. [SyntaxError: Unexpected end of JSON input](https://github.com/nilsteampassnet/TeamPass/issues/3434)
