### ISSUE TITLE
Create User or change Password takes too long time, up to six hours

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3440]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1.  Create user or reset password 
2.  too long time, up to six hours
3. 

### Expected behaviour
Create user/Reset password

### Actual behaviour
Create user/Reset user password takes too long time, up to six hours

A lot of queries and processing of the dbpass_sharekeys_logs table where the last **object_id > 68000**
**How to speed up the process of changing the user's password?**
How to remove extra data from the dbpass_sharekeys_logs table without violating the integrity

###  MySQL query LOG for example:

4375 Query    SELECT share_key
            FROM dbpass_sharekeys_logs
            WHERE object_id = 68648 AND user_id = 1

221206 17:45:29  
 4375 Query    INSERT INTO `dbpass_sharekeys_logs` (`object_id`,`user_id`,`share_key`) VALUES (68648, 10000063, 'iDSY76n58mxbAgwdUZWAG9iJ7Ei8HVqBZ2AmbslGvVLc3gJCEWa8ZH+vKif3gpHZwVEBn7+EYEDmZrM9pOjGDsQbSP76KoxFVICfDvp/O2gYZkE3H7VLu76PvlrZCg3fP5bKWeExA/cAKrP2MVj6N8ocOjVdksT34BHbCm4EClQV2Q0xRz++ZjiuljrItPxFZnWQ+2ofeO/a76V22QDAskuWENH1/v7FYRJcKr+vBCfl86KEnUPhSBInOpe3aH6DFyMfEyGkaAL+g2IgF2PH7I8DTym5IWwULY0zejYfjghnfVD0LOFgFDRhVwqnRb2v2eB/cFVLLh5AroaJdc7ykrkVDtOseXu24iXmQwsVCSXJQCmZFALZBavU8KjKcTm7U1lC9/b4yyAaBxq4eK24mIV5DW1e4R9VekS93yZ7/yF9zvg3FPtrT5CDJHZncUdBPB08D2hJa6cUvYNZPY2Zu+3q617a/8xnyY7kKSZTsinRh8+MUXBn4y/rlSPE0E+tAp2XTXAyxJQy6DBUamD/vE3slpSlv3Pu8VqyBXk2naKCGA8OrlUh5FlTKJOQXHTF2rSVVtZrgAM80XJZYnGyvjuT8L8tntiYQpO/QQvce/SnNz2uSxw1VyxMu97Fc/PmtCCVzWh0O30pwdQmtK2JwARFpIMeMrdDvXxFvpBmxqI=')

###  count table rows

MariaDB [dbpass]> SELECT COUNT(*) FROM dbpass_sharekeys_logs;
+----------+
| COUNT(*) |
+----------+
|   396769 |
+----------+

MariaDB [dbpass]> SELECT COUNT(*) FROM dbpass_users;
+----------+
| COUNT(*) |
+----------+
|       29 |
+----------+

### Server configuration
**Operating system**: Linux pass 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

**Web server:** Apache/2.4.54 (Debian)

**Database:** 5.5.5-10.5.15-MariaDB-0+deb11u1-log

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '0',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/pass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/pass/upload',
'url_to_upload_folder' => '<anonym_url>',
'path_to_files_folder' => '/var/www/pass/files',
'url_to_files_folder' => '<anonym_url>',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'sAMAccountName',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '["1"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;cb_select_all;',
'send_stats_time' => '1512900881',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '20mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '1000',
'upload_imageresize_height' => '900',
'upload_imageresize_quality' => '99',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '600',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/pass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Moscow',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'max_last_items' => '20',
'enable_massive_move_delete' => '0',
'copy_to_clipboard_small_icons' => '1',
'offline_key_level' => '25',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'admin_2fa_required' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'password_overview_delay' => '9',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'maintenance_mode' => '0',
'ldap_hosts' => '10.1.3.150',
'ldap_bdn' => 'ou=ToProxy, cn=ToProxy,dc=net,dc=net',
'ldap_username' => 'na',
'ldap_password' => 'na',
'ldap_dn_additional_user_dn' => 'ou=ToProxy; cn=ToProxy',
'duo_ikey' => 'Admin',

```

**Updated from an older Teampass or fresh install:**
Update from2.1.27.11

### Client configuration

**Browser:** Chrome - 108.0.0.0

**Operating system:** Windows - 64bits

### Logs

[puttyPASS -sqlLOG.zip](https://github.com/nilsteampassnet/TeamPass/files/10167466/puttyPASS.-sqlLOG.zip)

**Comment by alarido** [comment]
First I suggest you try to activate scheduled tasks, it helps in some cases.

I have been experiencing the same problem in my system I have many passwords (10000), many users (100) and a big log populated after many years of use (hundreds of thousand or millions I haven't looked at it)

In a test I've conducted to upgrade from 2.1.27 in my system it takes around a week (7-8 days) with ample spare CPU and RAM, also running the machine in SSD disk storage, changing a user passwords after upgrade takes hours or even more than a days too.

New version it's more secure but does not scale well it's CPU bound (RAM and Disk speed does not seem to affect performance by a meaningful margin, only single CPU core speed does) it would be interesting to think in ways to optimize performance:
- Code optimizations in encryption/decryption performance, it's probably complex, but for every item every optimization adds up and improves overall times a lot, with many items huge time savings.
- Multi threaded approach for heavy tasks and a way to configure how many threads can be used (you usually want to save some CPU for users to be able to use the system) on all my tests it does not matter how many CPUs the server has, only one is used, so once you top up one core at 100% you cannot go faster, for example if 1 CPU takes 1 hour to do something, it should be possible to do it in 10 minutes with 6 CPUs if parallelization is used.
- If process crashes at any moment user password are not sent by email or shown to the admin in the GUI, so you have to start again and wait to see what happens.
- Nils has been working in scheduling heavy tasks that is a good idea but it does not include some situations yet:
1. Does not help with upgrades
2. When I tried in a 3.0.21 changing a user password still requires an active admin online session, that usually timeouts after 1-2 hours (session timeout) or if you are careful to extend it before hand timeouts after 24 hours (maybe browser/webserver timeout) if you have a big number of logs that task could take easily more than a day.
3. Creating a users and being able to use it is not immediate.
4. Scheduled task are CPU bound too, only one CPU is used and tasks are queued so only one task is executed at any given time.

**Comment by alarido** [comment]
Researching a bit code and encryption libs used in teampass 3.0 I realized that 3.0 requisites do not include php-gmp so I just installed it in a test system and performance improves noticeably (10x), without it PHP fall backs to use openssl and works just fine although with a huge performance hit.

It's still a lot of time to do some tasks in big systems and it would be nice to see some kind of improvement in parallelization to make better use of multiple CPU cores, especially for scheduled tasks.

I would recommend php-gmp libs as a requisite in upgrades, new installations and documentation, performance improvement is so good that should be used always.

**Comment by alarido** [comment]
I'm running another upgrade test and now that it's not so affected by encryption speed 

I realized it gets slower with every user, judging from CPU load now there is much more DB load, I think some indexes should help with this too as new tables are populated with every user the bigger they get probably makes the process slower as more data is loaded into the tables, it's still running but increase in time can be easily seen with the following times, each user takes 2 minutes more than the one before it:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JRALFA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JRALFA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



date-time | user | minutes
-- | -- | --
05/01/2022   17:31:29 | start user 1 |  
05/01/2022   17:34:55 | fully treated user 1 | 3,4
05/01/2022   17:39:43 | fully treated user 2 | 4,8
05/01/2022   17:45:54 | fully treated user 3 | 6,2
05/01/2022   17:53:30 | fully treated user 4 | 7,6
05/01/2022   18:02:29 | fully treated user 5 | 9,0
05/01/2022   18:12:49 | fully treated user 6 | 10,3
05/01/2022   18:24:27 | fully treated user 7 | 11,6
05/01/2022   18:37:23 | fully treated user 8 | 12,9
05/01/2022   18:51:45 | fully treated user 9 | 14,4
05/01/2022   19:07:57 | fully treated user 10 | 16,2
05/01/2022   19:25:19 | fully treated user 11 | 17,4
05/01/2022   19:44:04 | fully treated user 12 | 18,8
05/01/2022   20:04:13 | fully treated user 13 | 20,2
05/01/2022   20:25:42 | fully treated user 14 | 21,5
05/01/2022   20:48:37 | fully treated user 15 | 22,9
05/01/2022   21:12:24 | fully treated user 16 | 23,8
05/01/2022   21:38:05 | fully treated user 17 | 25,7
05/01/2022   22:05:03 | fully treated user 18 | 27,0
05/01/2022   22:33:38 | fully treated user 19 | 28,6
05/01/2022   23:03:29 | fully treated user 20 | 29,8
05/01/2022   23:34:35 | fully treated user 21 | 31,1
06/01/2022 0:06:57 | fully treated user 22 | 32,4
06/01/2022 0:41:10 | fully treated user 23 | 34,2
06/01/2022 1:16:46 | fully treated user 24 | 35,6
06/01/2022 1:53:37 | fully treated user 25 | 36,9
06/01/2022 2:32:37 | fully treated user 26 | 39,0
06/01/2022 3:12:17 | fully treated user 27 | 39,7
06/01/2022 3:53:02 | fully treated user 28 | 40,8
06/01/2022 4:35:18 | fully treated user 29 | 42,3
06/01/2022 5:18:31 | fully treated user 30 | 43,2
06/01/2022 6:03:28 | fully treated user 31 | 44,9
06/01/2022 6:49:50 | fully treated user 32 | 46,4
06/01/2022 7:37:56 | fully treated user 33 | 48,1
06/01/2022 8:30:25 | fully treated user 34 | 52,5



</body>

</html>

**Comment by alarido** [comment]
Enabling slow query log I see queries like this one:

SELECT share_key FROM teampass_sharekeys_items WHERE object_id = 9788 AND user_id = 1;

It't not very fast, and it does not use indexes:

SELECT * FROM teampass_sharekeys_items WHERE object_id = 9788 AND user_id = 1;
1 row in set (0,354 sec)

explain SELECT * FROM teampass_sharekeys_items WHERE object_id = 9788 AND user_id = 1;
+------+-------------+-----------------------------+------+---------------+------+---------+------+--------+-------------+
| id   | select_type | table                       | type | possible_keys | key  | key_len | ref  | rows   | Extra       |
+------+-------------+-----------------------------+------+---------------+------+---------+------+--------+-------------+
|    1 | SIMPLE      | teampass_sharekeys_items | ALL  | NULL          | NULL | NULL    | NULL | 320291 | Using where |
+------+-------------+-----------------------------+------+---------------+------+---------+------+--------+-------------+

Adding those indexes helps quite a lot

show indexes from teampass_sharekeys_items;
+-----------------------------+------------+----------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                       | Non_unique | Key_name | Seq_in_index | Column_name  | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-----------------------------+------------+----------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| teampass_sharekeys_items |          0 | PRIMARY  |            1 | increment_id | A         |      320525 |     NULL | NULL   |      | BTREE      |         |               |
+-----------------------------+------------+----------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+



alter table teampass_sharekeys_items add index (object_id) ;
alter table teampass_sharekeys_items add index (user_id) ;



explain SELECT * FROM teampass_sharekeys_items WHERE object_id = 9788 AND user_id = 1;
+------+-------------+-----------------------------+-------------+-------------------+-------------------+---------+------+------+-------------------------------------------------+
| id   | select_type | table                       | type        | possible_keys     | key               | key_len | ref  | rows | Extra                                           |
+------+-------------+-----------------------------+-------------+-------------------+-------------------+---------+------+------+-------------------------------------------------+
|    1 | SIMPLE      | teampass_sharekeys_items | index_merge | object_id,user_id | object_id,user_id | 4,4     | NULL |    1 | Using intersect(object_id,user_id); Using where |
+------+-------------+-----------------------------+-------------+-------------------+-------------------+---------+------+------+-------------------------------------------------+
1 row in set (0,000 sec)

SELECT * FROM teampass_sharekeys_items WHERE object_id = 9788 AND user_id = 1;
1 row in set (0,002 sec)



<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JRALFA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JRALFA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



date-time | user | minutes
-- | -- | --
05/01/2022 17:31 | start user 1 |  
05/01/2022 17:34 | fully treated user 1 | 3,4
05/01/2022 17:39 | fully treated user 2 | 4,8
05/01/2022 17:45 | fully treated user 3 | 6,2
05/01/2022 17:53 | fully treated user 4 | 7,6
05/01/2022 18:02 | fully treated user 5 | 9,0
05/01/2022 18:12 | fully treated user 6 | 10,3
05/01/2022 18:24 | fully treated user 7 | 11,6
05/01/2022 18:37 | fully treated user 8 | 12,9
05/01/2022 18:51 | fully treated user 9 | 14,4
05/01/2022 19:07 | fully treated user 10 | 16,2
05/01/2022 19:25 | fully treated user 11 | 17,4
05/01/2022 19:44 | fully treated user 12 | 18,8
05/01/2022 20:04 | fully treated user 13 | 20,2
05/01/2022 20:25 | fully treated user 14 | 21,5
05/01/2022 20:48 | fully treated user 15 | 22,9
05/01/2022 21:12 | fully treated user 16 | 23,8
05/01/2022 21:38 | fully treated user 17 | 25,7
05/01/2022 22:05 | fully treated user 18 | 27,0
05/01/2022 22:33 | fully treated user 19 | 28,6
05/01/2022 23:03 | fully treated user 20 | 29,8
05/01/2022 23:34 | fully treated user 21 | 31,1
06/01/2022 0:06 | fully treated user 22 | 32,4
06/01/2022 0:41 | fully treated user 23 | 34,2
06/01/2022 1:16 | fully treated user 24 | 35,6
06/01/2022 1:53 | fully treated user 25 | 36,9
06/01/2022 2:32 | fully treated user 26 | 39,0
06/01/2022 3:12 | fully treated user 27 | 39,7
06/01/2022 3:53 | fully treated user 28 | 40,8
06/01/2022 4:35 | fully treated user 29 | 42,3
06/01/2022 5:18 | fully treated user 30 | 43,2
06/01/2022 6:03 | fully treated user 31 | 44,9
06/01/2022 6:49 | fully treated user 32 | 46,4
06/01/2022 7:37 | fully treated user 33 | 48,1
06/01/2022 8:30 | fully treated user 34 | 52,5
06/01/2022 9:18 | fully treated user 35 | 48,3
06/01/2022 9:58 | fully treated user 36 | 39,9
06/01/2022 10:00 | fully treated user 37 | 1,6
06/01/2022 10:01 | fully treated user 38 | 1,6
06/01/2022 10:03 | fully treated user 39 | 1,6
06/01/2022 10:05 | fully treated user 40 | 1,6
06/01/2022 10:06 | fully treated user 41 | 1,6
06/01/2022 10:08 | fully treated user 42 | 1,6
06/01/2022 10:09 | fully treated user 43 | 1,6
06/01/2022 10:11 | fully treated user 44 | 1,6
06/01/2022 10:13 | fully treated user 45 | 1,6



</body>

</html>
