### ISSUE TITLE
[Problem] Generate new OTP code is wrong

### ISSUE THREAD

**Issue by ssudosu** [nilsteampassnet/TeamPass#3446]
If a user changes a password in LDAP I have to generate new OTP ,but when the user tries to use the new OTP code it says the code is wrong.
Has anyone had this problem?

![teampass_erro1](https://user-images.githubusercontent.com/104503132/207039047-f9034284-d1ae-431f-8714-814ac28a8662.png)

**Comment by ssudosu** [comment]
Can anyone help?
I can't get a user to access teampass if they change their password in LDAP.

**Comment by aphillips-DES** [comment]
> If a user changes a password in LDAP I have to generate new OTP ,but when the user tries to use the new OTP code it says the code is wrong. Has anyone had this problem?
> 
> ![teampass_erro1](https://user-images.githubusercontent.com/104503132/207039047-f9034284-d1ae-431f-8714-814ac28a8662.png)

I'm also getting this error when creating a new user from AD, can we get an update on this? What logs do you need? @nilsteampassnet

**Comment by nilsteampassnet** [comment]
Can you please share the version you are using.
Nevertheless I recommend to upgrade to latest commit.
That being said, when an ldap user changes his password in AD then: 
1- he connects to TP using his new password
2- when accessing an item in TP, a dialog will be shown asking to provide the old password and to confirm the new one.
![image](https://user-images.githubusercontent.com/1197546/210559384-36b59460-6ca9-4dda-90ac-f8ab4990db33.png)
3- This is done. No need to regenerate an OTP.

**Comment by ssudosu** [comment]
hello @nilsteampassnet,
I'm using version 3.0.0.19.
If the user changes the password in AD, he is no longer able to access the personal folder and see the passwords.
![TP_error1](https://user-images.githubusercontent.com/104503132/210614258-073d7926-7d3d-4243-b20a-9b645a5ce9da.png)

**Comment by nilsteampassnet** [comment]
Please upgrade

**Comment by ssudosu** [comment]
Can I use the same DB and data from the previous version?
Or do I have to do a clean install?

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
