### ISSUE TITLE
Teampass API v3: reading items details not working

### ISSUE THREAD

**Issue by amilhub** [nilsteampassnet/TeamPass#3449]
### Steps to reproduce
1. Make a API Call
2. I can do auth and show elements on folders via API
3. But i can't show any item information.

### Expected behaviour
Be able to see item information (like item username and password) 

### Actual behaviour
I can do API call with auth showing elements on folders but NOT i am able to show any item information.

For example, list elements on folder is working, like this:

http://teampass_url.com/api/index.php/item/inFolders?folders=[336]

But, trying to get some specific element information is NOT working, like:

http://teampass_url.com/api/index.php/read/items/XX?apikey=XXXXXXXXXXXXXXXXXXXXXXX

I receive a 404 Not found (and of course the item exist).

@nilsteampassnet maybe this feature is not yet implemented in API v3, please can you confirm this? 
And if this is right, any estimation about when this feature could be implemented?

In the case the API call i am doing to get item info is wrong, any kind of help on this it will be nice, i really appreciate it!

Thanks in advance.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 3.0.0.21

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by useronkel** [comment]
Hi there.
The api for v3 is simply not yet fully implemented

**Comment by nilsteampassnet** [comment]
Hello,
Indeed not yet implemented
See v3 documentation at https://documentation.teampass.net/#/api-basic
