### ISSUE TITLE
Two easy performance improvements for 3.0

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#3466]
There are some performance result of these suggestions in ticket #3440 with those simple fixes performance in upgrade from 2.7, user password change and user creation are quite noticeable, in my case an upgrade test that lasted 8-9 days was reduced to less than 3 hours.

1. Add as a requirement php-gmp again, everything works without it but encryption and decryption is much faster with that library installed to the point that tasks that rely heavily on it improve a lot.

2. Add some indexes to sharekeys tables on creation:

```
alter table <prefix>_sharekeys_items add index (object_id);
alter table <prefix>_sharekeys_items add index (user_id);
alter table <prefix>_sharekeys_logs add index (object_id);
alter table <prefix>_sharekeys_logs add index (user_id);
```

Thanks in advance

**Comment by dormancygrace** [comment]
> 1. Add as a requirement php-gmp again, everything works without it but encryption and decryption is much faster with that library installed to the point that tasks that rely heavily on it improve a lot. 

I think it's done, can you test master branch?

**Comment by alarido** [comment]
I've just tried those cases, I can't try upgrade from 2.7 today, but I will next week:

1. Clean install 3.0 master branch, forces to have php-gmp installed --> OK, install process finished --> OK, **suggested indexes are not created for new installs**.

2. Upgrade a 3.0.21 to master branch, forces to have php-gmp installed --> OK, but if a try to finish the upgrade I get some errors in apache error.log;

First try:
`  PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate column name 'code_poeditor' in /var/www/html/install/upgrade_run_3.0.0.php:1599\nStack trace:\n#0 /var/www/html/install/upgrade_run_3.0.0.php(1599): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/install/upgrade_run_3.0.0.php on line 1599`

Next tries:
`  PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate key name 'CACHE' in /var/www/html/install/upgrade_run_3.0.0.php:875\nStack trace:\n#0 /var/www/html/install/upgrade_run_3.0.0.php(875): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/install/upgrade_run_3.0.0.php on line 875`
 
I had to comment some sections to avoid errors and continue with the upgrade, and I found some mistakes in the new indexes creation, pl**ease note I didn't check why the commented code failed I just went to check the new indexes part** I think it's related to already applied patches that provoke exceptions:


```
 diff /usr/src/TeamPass/install/upgrade_run_3.0.0.php /var/www/html/install/upgrade_run_3.0.0.php
872a873
> /*
876a878
> */
1596a1599
> /*
1627a1631
> */
1633a1638
> /*
1637a1643
> */
1641c1647
<     'ALTER TABLE `' . $pre . '_sharekeys_items add index (object_id) ;'
---
>     'ALTER TABLE `' . $pre . 'sharekeys_items` add index (object_id) ;'
1645c1651
<     'ALTER TABLE `' . $pre . '_sharekeys_items add index (user_id) ;'
---
>     'ALTER TABLE `' . $pre . 'sharekeys_items` add index (user_id) ;'
1649c1655
<     'ALTER TABLE `' . $pre . '_sharekeys_logs add index (object_id) ;'
---
>     'ALTER TABLE `' . $pre . 'sharekeys_logs` add index (object_id) ;'
1653c1659
<     'ALTER TABLE `' . $pre . '_sharekeys_logs add index (user_id) ;'
---
>     'ALTER TABLE `' . $pre . 'sharekeys_logs` add index (user_id) ;'

```

Basically there is missing a quote and there is one excess underscore which is already a part of the prefix:

```
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '_sharekeys_items add index (object_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '_sharekeys_items add index (user_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '_sharekeys_logs add index (object_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '_sharekeys_logs add index (user_id) ;'
);
```


The following code works fine, but this code is susceptible of provoking exceptions also if indexes are already created before:

```
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '`sharekeys_items add index (object_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '`sharekeys_items add index (user_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '`sharekeys_logs add index (object_id) ;'
);
mysqli_query(
    $db_link,
    'ALTER TABLE `' . $pre . '`sharekeys_logs add index (user_id) ;'
);
```




Thanks for taking this to master so fast :)

**Comment by dormancygrace** [comment]
@alarido I'm not good in DB, so I can't make second part of your changes you offer =(

**Comment by alarido** [comment]
Regarding create indexes on clean install I was mistaken, in that case the indexes are created.

Looking to commits new indexes code was added by @nilsteampassnet in commit #[2ee894e](https://github.com/nilsteampassnet/TeamPass/commit/2ee894e02e1c3484cad472ebb757dad36dc4dff3)

I already suggested the fix (add missing quotes, remove excess underscores=

Appart from that php-gmp it's required, that part works perfectly fine :-)

**Comment by alarido** [comment]
Tested master branch to upgrade 2.1.27 and took 3 hours, much better that the 8-9 days it took in the tests without optimizations.

Create or update user password now takes 1.5 hours (before it was more than a day I wasn't able to finish one due to timeouts) that's mostly due to "Encrypting keys - Logs" phase, if a system has been used for quite some time there are a lots of logs (mine around 400K every 10k logs take 2 minutes to be processed)

Process is still CPU bound and uses only one core, the only optimization I can think of now is making scheduled tasks multi-threaded so in case you have a big system you can give more processing power to it.

Thanks

**Comment by nilsteampassnet** [comment]
Thank you for all this.
I have committed the suggestion sunday evening.
I did also some investigation in performing concurrent threads but not successful until related to mysql access.
I need to deep dive
