### ISSUE TITLE
LDAP sync issue

### ISSUE THREAD

**Issue by borgoncete88** [nilsteampassnet/TeamPass#3471]
### Expected behaviour
Sync AD users with LDAP

### Actual behaviour
test sync and sync doesn't work. Teampass says the password is incorrect when it is correct.

### Server configuration
**Operating system:**
Debian GNU/Linux 11 (bullseye)

**Web server:**
Apache/2.4.54

**Database:**
Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11

**PHP version:**
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )

**Teampass version:** 
Version 3.0.0.22

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10374206/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Google Chrome v.108.0.5359.125 (Build oficial) (64 bits)

**Operating system:**
Windows 10/11

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
``

**Comment by dhirmansyah** [comment]
same issue like me, I have config ldap as following. but still does not work.

`    
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '1',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'ldap_object_class' => '0',
    'ldap_new_user_is_administrated_by' => '0',
    'ldap_and_local_authentication' => '1',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '(&(objectCategory=Person)(sAMAccountName=*))',
    'ldap_bdn' => 'OU=Users,OU=Clarus,DC=clarus-it,DC=net',
    'ldap_hosts' => 'cit01ad01.clarus-it.net',
    'ldap_password' => 'xxxxxxx',
    'ldap_username' => 'CN=Teampass Users,OU=Services,OU=Users,OU=Clarus,DC=clarus-it,DC=net',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'ldap_new_user_role' => '8',
`

**Comment by borgoncete88** [comment]
Hi, after several tests, finally managed to make Teampass work fine! See below my config to help you

![image](https://user-images.githubusercontent.com/60383298/213127979-9d2842d8-60b8-4018-9d07-dce22a90d965.png)

**Comment by dhirmansyah** [comment]
thanks for your info @borgoncete88, it's solved now.
