### ISSUE TITLE
PHP function str_contains in latest commit

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3476]
Hi Nils.
In commit [#5021ecd](https://github.com/nilsteampassnet/TeamPass/commit/5021ecd5b26ba189770263ccd150ad1c719e4d72) you've used the str_contains function, but this is only for php8
php7 doesn't know this function name ;-)

I would suggest to implement a simple function as well like this:
```
if (!function_exists('str_contains')) {
  function str_contains($haystack, $needle) {
      return $needle !== '' && mb_strpos($haystack, $needle) !== false;
  }
}
```

**Comment by nilsteampassnet** [comment]
Hello @useronkel 
Thank you for your suggestion.
This code comes from a library, and I will add your suggestion.
