### ISSUE TITLE
Views > Reports page didn't report events sorted by date

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3480]
### Steps to reproduce
1. Login at Teampass.
2. Go to Views > Reports page (https://teampass.example.com/index.php?page=utilities.logs).

### Expected behaviour
Table results should be sorted by date by default.

### Actual behaviour

![teampass-results-not-sorted](https://user-images.githubusercontent.com/2974895/212476816-4fd9ddc6-34b3-48b8-9224-d6771778c99c.png)

Table results aren't shown sorted as date (I couldn't figure out which order they are sorted, it seems to be random), so newer events are sorted with older ones (there's events from 2021 shown altogether with 2022 ones). It could also changes the cursor when selecting a table header to a "clickable" one, so the user would easily known that he/she can sort the results by clicking by the table header.''

![teampass-edit](https://user-images.githubusercontent.com/2974895/212476365-af639709-c183-4447-90eb-3740ce37d39e.png)

Also, the results from the page could be sorted by "Editing started" column by default to show more recent entries at the top instead of a random order and every time I click into the "Trash" icon to remove a row from the list, it seems to loose it's current ordering.

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10087406/tp.config.php.txt)

### Client configuration
**Browser:** 109.0.5414.74

**Operating system:** Windows 10

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
