### ISSUE TITLE
Can´t create new users. Error 500 in /sources/main.queries.php when change password or generate OTP

### ISSUE THREAD

**Issue by Esware80** [nilsteampassnet/TeamPass#3481]
### Page on which it happened

https://teampass.mydomain//index.php?page=users

### Steps to reproduce
Create a new user, or change password / OTP

### Actual behaviour
When a new user is created or password / otp changed, application freeze when Encrypting Files. User is created but password or OTP is not generated and don´t send email. . Please see the information below extracted from browser debug mode.

This issue happens using admin users. 

The only one solution is a new installation but after some days issue repeats.

LDAP is not activated. Only internal users. 

jquery.min.js:2 
 POST https://teampass.mydomain//sources/main.queries.php 500 (Internal Server Error)

Request URL: https://teampass.mydomain//sources/main.queries.php
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:9000
Referrer Policy: strict-origin-when-cross-origin

![image](https://user-images.githubusercontent.com/122777240/212676823-08f2e813-42c3-40f9-bb72-0cf26a4c332d.png)

![image](https://user-images.githubusercontent.com/122777240/212677432-75849da8-6e7d-43ff-baf7-e46a1ed42729.png)

## Error information from /var/log/httpd/error_log

[Mon Jan 16 11:05:05.956257 2023] [php:error] [pid 32367] [client 10.140.48.70:53844] PHP Fatal error:  Uncaught TypeError: decryptUserObjectKey(): Argument #1 ($key) must be of type string, null given, called in /var/www/TeamPass.3.0.0.20/sources/main.queries.php on line 2390 and defined in /var/www/TeamPass.3.0.0.20/sources/main.functions.php:2829\nStack trace:\n#0 /var/www/TeamPass.3.0.0.20/sources/main.queries.php(2390): decryptUserObjectKey()\n#1 /var/www/TeamPass.3.0.0.20/sources/main.queries.php(1962): continueReEncryptingUserSharekeysStep5()\n#2 /var/www/TeamPass.3.0.0.20/sources/main.queries.php(462): continueReEncryptingUserSharekeys()\n#3 /var/www/TeamPass.3.0.0.20/sources/main.queries.php(155): keyHandler()\n#4 /var/www/TeamPass.3.0.0.20/sources/main.queries.php(77): mainQuery()\n#5 {main}\n  thrown in /var/www/TeamPass.3.0.0.20/sources/main.functions.php on line 2829, referer: https://teampass.mydomain//index.php?page=users

### Server configuration

**Operating system**: Linux  3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/8.2.1

**Database:** 5.5.68-MariaDB

**PHP version:** 8.2.1

**Teampass version:** 3.0.0.22

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/TeamPass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/opt/TeamPass/upload',
'path_to_files_folder' => '/opt/TeamPass/files',
'url_to_files_folder' => 'http://teampass.mydomain/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.22',
'ldap_mode' => '0',
'ldap_type' => '',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '1',
'custom_logo' => '',
'custom_login_text' => 'WARNING! All information contained in this portal is strictly confidential. Authorized staff only. All activity will be monitored during user session.',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1670077119',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '50',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '15',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/TeamPass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '1',
'syslog_host' => '<removed>'
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Madrid',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_ikey' => '<removed>'
'duo_skey' => '<removed>'
'duo_host' => '<removed>'
'duo_failmode' => 'secure',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '50',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '3',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => '',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '',
'ldap_bdn' => '',
'ldap_hosts' => '<removed>'
'ldap_password' => '<removed>'
'ldap_username' => '',
'api_token_duration' => '60',
'enable_tasks_manager' => '0',
'task_maximum_run_time' => '300',
'tasks_manager_refreshing_period' => '20',
'maximum_number_of_items_to_treat' => '100',
'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
'ldap_new_user_role' => '',
'max_last_items' => '10',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:**  - 

**Operating system:**  - bits

#### Web server error log
```
Constant FILTER_SANITIZE_STRING is deprecated - /var/www/TeamPass.3.0.0.20/sources/main.queries.php (119) 
```
(Important Note from reporter. Wetested replacing this value to FILTER_SANITIZE_FULL_SPECIAL_CHARS but issue persist. Same Error)

#### Teampass 10 last system errors
```
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

Console Tab

POST https://teampass.mydomain//sources/main.queries.php 500 (Internal Server Error)                   jquery.min.js:2   

Network Tab
## Headers ##

Request URL: https://teampass.mydomain//sources/main.queries.php
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:9000
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Origin: *
Cache-Control: no-cache, must-revalidate
Connection: close
Content-Length: 3
Content-Type: text/html; charset=utf-8
Date: Mon, 16 Jan 2023 10:27:18 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/8.2.1
X-Powered-By: PHP/8.2.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 1035
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: teampass_session=rep3tijtngnjcr0knb30trgkri; a20613876fd3c2029ac798c30b41eb810032abe3c2bba4d253=a0dbd56735a96b1fd93fbdc8821a091c27b1b22f261cfc0808
Host: teampass.mydomain
Origin: https://teampass.mydomain
Referer: https://teampass.mydomain//index.php?page=users
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest

##Payload##

type: 
user_sharekeys_reencryption_next
type_category: 
action_key
data: 
eyJjaXBoZXJ0ZXh0IjoidFJnUEcrU28xVWh1emk4VGFzVmo3b1IyNHVvY2V5eTJwdC9jTXVielpBd3hXeWd3R3dkOGtjRkhrK2tKNk91c05BZVp2WnpMditiNnVxRitUMEZFcWc9PSIsIml2IjoiMDU2YjFkNGY4N2NlMjQ5NzBjNjY1YzhiNmY1MGUyMzEiLCJzYWx0IjoiYmVkOGNmYjgxZjBlYzcwMmUzMjUwYWFkYjVmOWIxY2E4NmJmZTE4NjNiODMyM2I2MTBlODIwOTU4NjNjOWY4NzVmNDZkNTQwMzE3MGExNWMzYjkxMDM5OTJjODdlNzAwMGQxMjUxNzc3NTQyOGJhYzRiOTdiOWMxNzYxYWZhMmE4NTYwNTkyZjhkYTE3N2VmZDMxMjc1NDEzOThhYThjMDJkYTRlZTQ2YTcxMDhmOGJiMTZjMWM5ZTVjM2UxZjQ3ZmE1OGZiODY2OTk2MTc0MGExYTA0MjU0NDJhN2E5MDA3MGI0NmU0MDYyNGJjN2M4ZDllODBlZjQxYjFjNGRiZTU2ZTEyODAzNGFmYjA1NWU3ZWZjMmViMGJmZTM0ZTM0NjEyNzNmYzdiZmY1MjExYWY3ZmU0OTE5MjMwNmNiZGZkNmQ4YWJjMTA4YjY0OTliNDBjMTI1N2JhN2RhZGVhZDVlMTEzYmRkZjY2NGY2NzE2ODA1NWI4NGVmMWUyNzVhMjY2MDEzYjYyZGI5ZTA1NjhkZWEzMGZiZWNjNjZmZGI3NmNhM2Y5MjU1YmQyNjZiYTlhMDAyZGI2NWI2OWEwODkwNmY0NDkzODVhMzZmNmJkODg5MDU5YTBkNmQzYTJhYTI5NzU2ZWI4NmNmODA2NWJjMjRkNDE1NTI4NWVhNGQiLCJpdGVyYXRpb25zIjo5OTl9
key: 
5WRSjpdfHXwZk3LPbWVFUN2P2ydQZgBRZPaC9PMdc5Tv9NNS7r

## Initiator ##

send | @ | jquery.min.js:2
-- | -- | --
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryptionNext | @ | index.php?page=users:2621
  | (anonymous) | @ | index.php?page=users:2648
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryptionNext | @ | index.php?page=users:2621
  | (anonymous) | @ | index.php?page=users:2648
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryptionNext | @ | index.php?page=users:2621
  | (anonymous) | @ | index.php?page=users:2648
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryptionNext | @ | index.php?page=users:2621
  | (anonymous) | @ | index.php?page=users:2648
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryptionNext | @ | index.php?page=users:2621
  | (anonymous) | @ | index.php?page=users:2574
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | userShareKeysReencryption | @ | index.php?page=users:2546
  | (anonymous) | @ | index.php?page=users:1808
  | c | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | l | @ | jquery.min.js:2
  | (anonymous) | @ | jquery.min.js:2
  | load (async) |   |  
  | send | @ | jquery.min.js:2
  | ajax | @ | jquery.min.js:2
  | S.<computed> | @ | jquery.min.js:2
  | (anonymous) | @ | index.php?page=users:1776
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

## Request Initiator Chain ##

https://teampass.mydomain//index.php?page=users
           https://teampass.mydomain//plugins/jquery/jquery.min.js
                      https://teampass.mydomain//sources/main.queries.php

```
Insert the log here and especially the answer of the query that failed.
```
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
