### ISSUE TITLE
Broken CSV entries export when the field "Description" contains Enter (<br /> and <br> tag) and Lists

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3484]
### Steps to reproduce
1. Enable "Export to PDF or CSV enabled" and setup it's Roles as expected.
2. Login with the user with an authorized Role to export as PDF/CSV.
3. Go to "Export" pages and export all as CSV.

### Expected behaviour
When the "Description" field contains Enter (``<br /> tag``), Teampass should remove the "Enter" so it would export as expected.

### Actual behaviour

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2974895/212691238-d56d6c79-6141-47fd-a7ca-7875cb979a25.png">

The item was exported with the following line at the CSV:

```
162,"VPN - XXX - Fortgate (Terceirizada)","VPN: SSL-VPN
```

It's simply broken and every other information after it (like username and password) is missing from the exported CSV file.

I could filter wrong exported entries (into my case) by finding lines that do not end with one comma at the end with the following RegEx:

```
.*(?<!,)$
```
### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by eduardomozart** [comment]
It seems that only items migrated from Teampass 2.x -> Teampass 3.x is affected. When I edited the "Description" field to redo the "Enters", it saved as Paragraphs (paragraphs between ``<p></p>`` tags) and they were exported as expected. I believe that for Enters the Teampass 2.x used ``<br />`` tags instead. Not sure, but I believe this issue while parsing ``<br />`` tags maybe related to the ``cleanString`` function from main.functions.php file (as can be seen https://github.com/nilsteampassnet/TeamPass/blob/e9f7e3772b65a7dd943782418236a2ca154eecad/sources/main.functions.php).

**Comment by eduardomozart** [comment]
It seems to strip ``<br>`` tags (Shift + Enter) when exporting, only ``<br />`` tag (items "Description" migrated from Tempass 2.x) seems to fail.

Before updating the ``Description`` field:

```
210,"Switch 3Com 1910","Necess&aacute|rio alterar o campo Bits por segundo da porta COM para 38400 no Gerenciador de dispositivos para acesso Console.
```

After upgrading the ``Description`` field:

```
210,"Switch 3Com 1910","Necess?rio alterar o campo Bits por segundo da porta COM para 38400 no Gerenciador de dispositivos para acesso Console.Para habilitar a execu??o de todos os comandos, execute no terminal:_cmdline-mode onPlease input password:&nbsp|512900",(semsenha),admin,,False,,,,
```

**Comment by eduardomozart** [comment]
It also seems to fail to parse the CSV output when the item ``Description`` field contains a list created by the HTML editor available from the field, e.g.:

``
<p>Endereços externos:</p><p></p><ul><li>https://rnetworks.example.com:5001/</li><li>https://voip.example.com:5001/</li></ul><p></p>
``

CSV output:

``
225,"3CX PABX","Endere?os externos:
``

**Comment by eduardomozart** [comment]
``<br>`` strings is also broken while exporting, e.g.:

``Description`` field:

```
Virtual: 1.2.3.10/24<br>WLC1: 1.2.3.11/24<br>WLC2: 1.2.3.12/24
```

CSV output:

```
285,"Virtual Controller : 1.2.3.10/24","Virtual: 1.2.3.10/24
```

It only exports as expected when it's between ``<p>`` tags, e.g.:

``Description`` field:

```
<p>Virtual: 1.2.3.10/24<br>WLC1: 1.2.3.11/24<br>WLC2: 1.2.3.12/24</p>
```

CSV output:

```
285,"Virtual Controller : 1.2.3.10/24","Virtual: 1.2.3.10/24WLC1: 1.2.3.11/24WLC2: 1.2.3.12/24",aruba123,admin,,False,,,,
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
