### ISSUE TITLE
Accent chars isn't being handle correctly when exporting to CSV

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3485]
### Steps to reproduce
1. Enable "Export to PDF or CSV enabled" and setup it's Roles as expected.
2. Login with the user with an authorized Role to export as PDF/CSV.
3. Go to "Export" pages and export all or only a specific Folder as CSV.

### Expected behaviour
Special chars (like cecedilha - ``ç``, ``á`` and ``í``) isn't being encoded at the exported CSV file as expected.

### Actual behaviour
The file contains the UTF-8 encoding as expected, but some chars (like "cecedilha" - ``ç``, ``á`` and ``í``) is being output to the file with the following encoding:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/2974895/212695083-59f0e445-7236-4d56-9886-27886ac74f86.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2974895/212695475-0e920189-0c96-4be6-9fc4-92d038a713fa.png">

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/2974895/212696212-6c236a39-a361-461c-b15f-67d5aee31fc1.png">

```
225,"3CX PABX","Endere&ccedil|os externos:
210,"Switch 3Com 1910","Necess&aacute|rio alterar o campo Bits por segundo da porta COM para 38400 no Gerenciador de dispositivos para acesso Console.
209,"VPN - Aruba VIA","Cliente Aruba VIA est&aacute| dispon&iacute|vel para download no Portal ASP.
```

I've have the following ``.htaccess`` file at the root of my Teampass site (not sure if it maybe related to this issue or not, I created it because the DataTables translated fields wasn't showing accents and special chars at my native language [Portuguese-Brazilian]):

````
AddDefaultCharset UTF-8
````

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by eduardomozart** [comment]
It seems to me that this problem is somehow related to legacy items created at Teampass 2.x, as I could see that they were saved 

Before updating the ``Description``:

```
209,"VPN - Aruba VIA","Cliente Aruba VIA est&aacute| dispon&iacute|vel para download no Portal ASP.
```

After updating the ``Description`` field through Teampass UI (now the field is exported but accents still aren't being handled as expected:

````
209,"VPN - Aruba VIA","Cliente Aruba VIA est? dispon?vel para download no Portal ASP.VPN Server URL/IP: vpn2-via.example.com",P@$$w0rd,Us3r,,False,,,,
````

It also stored the data into DB into the following way:

![image](https://user-images.githubusercontent.com/2974895/212743461-6ad22e06-0ad4-45af-b45e-bbd851cef3ad.png)

**Comment by eduardomozart** [comment]
It seems to strip ``<br>`` tags (Shift + Enter) when exporting, only ``<br />`` tag (items "Description" migrated from Tempass 2.x) seems to fail.

Before updating the ``Description`` field:

```
210,"Switch 3Com 1910","Necess&aacute|rio alterar o campo Bits por segundo da porta COM para 38400 no Gerenciador de dispositivos para acesso Console.
``
`

After upgrading the ``Description`` field:

```
210,"Switch 3Com 1910","Necess?rio alterar o campo Bits por segundo da porta COM para 38400 no Gerenciador de dispositivos para acesso Console.Para habilitar a execu??o de todos os comandos, execute no terminal:_cmdline-mode onPlease input password:&nbsp|512900",(semsenha),admin,,False,,,,
```

**Comment by eduardomozart** [comment]
Maybe it's related to the default MySQL charset? I'm not the sysadmin of this server, so I can't change the default charset.

![2023-01-16 21_30_21-Clipboard](https://user-images.githubusercontent.com/2974895/212784802-4d10f5fe-62d0-4b49-bf16-dc0ed9c3f615.png)

**Comment by eduardomozart** [comment]
Item titles doesn't seems to be affected by this bug, most the ``Description`` field.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
