### ISSUE TITLE
API keys isn't encrypted at the database

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3487]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
API Keys should be stored into encrypted form at the DB.

### Actual behaviour
API Keys aren't encrypted at the DB (``api`` table) and any user that has access to the DB could query the API and get any password stored into it. Limiting the IP doesn't seem to be a good measure to avoid this because the IP also isn't encrypted at the DB. Also, removed/migrated API keys still seems to be shown at the ``api`` table (but not shown at the Teampass UI). I know that API is still a work in progress at Teampass 3, but I believe this issue should be checked by Teampass devs before commiting it into the Teampass source code.

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by nilsteampassnet** [comment]
Thank you
It could be done.
But api connection requires valid credentials to get the jwt auth token before using api functions.
Any how I will follow your suggestion as it is a good practice :+1:

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
