### ISSUE TITLE
Check "Select the export format type" before exporting

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3489]
### Steps to reproduce
1. Enable "Export to PDF or CSV enabled" and setup it's Roles as expected.
2. Login with the user with an authorized Role to export as PDF/CSV.
3. Go to "Export" pages and export all or only a specific Folder.

### Expected behaviour
When clicking into "Export" button, it shows an error if no filetype (PDF/CSV) is selected.

### Actual behaviour
The dropdown menu "Select the export format type" at the Export page isn't being checked if unselected before exporting and when clicking into "Export" it loads forever but no file are exported.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2974895/212736739-40241c4f-9965-496b-a370-cc1cc94e8a29.png">

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
