### ISSUE TITLE
Change items.url column to NOT NULL

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3490]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
The code should be updated to handle NULL values for URLs our URL items column should not allow an ``UPDATE`` SQL command to set it to NULL value.

### Actual behaviour
Teampass 2.x had a behaviour to autofill the URL field from an password item to add the ``https://`` prefix into it, so some password items after the migration still keeps this prefix instead of an empty value. So I've decided decided to run an "update" SQL query to change all those ``https://`` items URL to NULL, but them I started receiving the following error when attempting to export password items to CSV:

```
[16-Jan-2023 12:23:31 America/Sao_Paulo] PHP Fatal error:  Uncaught TypeError: htmlspecialchars_decode() expects parameter 1 to be string, null given in /home/robertinho/public_html/teampass/sources/export.queries.php:221
Stack trace:
#0 /home/robertinho/public_html/teampass/sources/export.queries.php(231): htmlspecialchars_decode(NULL)
#1 {main}
  thrown in /home/robertinho/public_html/teampass/sources/export.queries.php on line 221
```

Actually, this line is responsible to the URL field from CSV export (as can be seen https://github.com/nilsteampassnet/TeamPass/blob/3b35001263928671c8d9868c8b429d7f09ff8ce3/sources/export.queries.php).

I believe the code should be changed to parse NULL values or the DB schema should be changed to avoid that NULL values be set to the URL items column.

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by eduardomozart** [comment]
I believe the TeamPass code already prevented it from happening. I was referring to the DB schema, that allows NULL values to the item URL. I believe the URL Acolumn should be changed to not allow NULL values.
