### ISSUE TITLE
Quoting of "description" field of CSV Output doesn't follow RFC 4180

### ISSUE THREAD

**Issue by eduardomozart** [nilsteampassnet/TeamPass#3494]
### Steps to reproduce
1. Enable "Export to PDF or CSV enabled" and setup it's Roles as expected.
2. Login with the user with an authorized Role to export as PDF/CSV.
3. Go to "Export" pages and export all or only a specific Folder.

### Expected behaviour
Quotes inside the ``description`` field should be escaped by using double quotes ``""`` instead of ``\"``.

### Actual behaviour
The following line is a password item output at the CSV exported from Teampass:

```
id,label,description,pw,login,restricted_to,perso,url,email,kb,tag
318,"MSSQL 2017 - Qualitor - Usuário ""qualitor""","Usu?rio interno da inst?ncia \"MSSQLSERVER\" do MSSQL 2017 (server02), utilizado para conex?o da aplica??o Qualitor Web ao banco de dados do Qualitor. Para autentica??o ao banco de dados do Qualitor, ? necess?rio usar os usu?rios de dom?nio \"eduardo.mozart\", \"roberto.oliveira\" ou \"Administrator\".",Qualitor!@#,qualitor,,False,,,,
```

Please see that the ``label`` seems to follow RFC 4180, because the word ``qualitor`` is quoted twice as a way to escape it. But the ``description`` field seems to use JSON escape, because it uses ``\"`` to escape quotes, which is wrong. Opening the CSV file inside LibreOffice creates an additional unwanted column after ``eduardo.mozart`` because there's a comma there and quotes aren't being escaped correctly so the text `` \"roberto.oliveira\" ou \"Administrator\"`` is shown into another column instead of inside the ``description`` column.

At first, I opened a bug report at LibreOffice about this "issue" ([here](https://bugs.documentfoundation.org/show_bug.cgi?id=153055) you can find it, where LibreOffice devs states that it isn't parsing the column as expected because LibreOffice follow strictly the RFC 4180).

### Server configuration
**Operating system**: Linux cloud.ifantasy.com.br 3.10.0-962.3.2.lve1.5.70.el7.x86_64 #1 SMP Mon May 30 08:45:55 UTC 2022 x86_64

**Web server:** Apache

**Database:** 5.7.30 - MySQL Community Server (GPL)

**PHP version:** 7.4.30

**Teampass version:** 3.0.0.21

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10426048/tp.config.php.txt)

### Client configuration
**Browser:** 108.0.5359.124

**Operating system:** macOS 12.6.2

#### Web server error log

NO errors being reported at the Apache error log.

#### Log from the web-browser developer console (CTRL + SHIFT + i)

NO events being reported at the Chrome console log.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
