### ISSUE TITLE
Edit user form opens with missing fields after editing admin

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3506]
### Steps to reproduce
See the [video](https://user-images.githubusercontent.com/2260980/216595139-0ca238a0-d620-46bc-b649-fe8955d1ba90.mp4).
1. open Users page
2. start edit the admin > Cancel
3. start creating new user

### Expected behaviour

User definition page should open with all the fields in the form.

### Actual behaviour
User definition page opens like I want to create an admin, not the user. Thus most buttons are inactive (e.g. Priveleges checkboxes) and required fields are missing.
Workaround: refresh the page.

### Server configuration
**Operating system**: Red OS 7.3.2 (RHEL like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.22 (downloaded on 02.02.2023)

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/10578554/tp.config.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox 109.0.1 x64

**Operating system:** Windows 10 x64

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
