### ISSUE TITLE
incorrect size shown for uploaded attachment file

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3508]
### Steps to reproduce
See the [video](https://user-images.githubusercontent.com/2260980/216607537-028b5f82-be3e-492d-94ff-286d31d4ce4d.mp4).
1. edit or create an item
2. upload any file > at this step the file will be shown with correct size > Save
3. open created item > Attachments

### Expected behaviour
File shown with real size.

### Actual behaviour
File name shown with incorrect size. It is not even close to the real one.
Though if you download the file it will be downloaded fine, so file is correctly stored on the server, it is not broken.

### Server configuration
**Operating system**: Red OS 7.3.2 (RHEL like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.22 (downloaded on 02.02.2023)

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/10578554/tp.config.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox 109.0.1

**Operating system:** Windows 10 x64

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
