### ISSUE TITLE
No info about `Teampass manager` privilege in documentation

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3512]
In docs https://teampass.readthedocs.io/en/latest/manage/manage-users/ I can't find what the difference between "Manager" and "Teampass manager" privilege? No popup tip in Teampass interface either.

![teampass manager](https://user-images.githubusercontent.com/2260980/216922212-ec5e7e23-04ad-4909-8257-c410ea03cca3.png)

Would be great to fulfil such info into documentation.

**Comment by nilsteampassnet** [comment]
@Kyogre 
Yes documentation is not up to date ... it's hard to maintain all aspects ;)
Nevertheless, "Teampass manager" is a kind of Human Resources Manager where this role provides the user the same rights as a Manager but he can manage all Users independently of his/her group.
Notice that he will be also promoted to Manager role, and that he will not be able to edit existing administrators.

Note: I have open [Discussions in Github](https://github.com/nilsteampassnet/TeamPass/discussions), it could be good to use that for Q&A ;)
