### ISSUE TITLE
TeamPass restore to new environment

### ISSUE THREAD

**Issue by azizbaghirov** [nilsteampassnet/TeamPass#3516]
Hi, dear Nils!

I know this issue was raised in another ticket. But still after long troubleshooting, we are experiencing problems with backup and restoring teampass, The scenario is we want to copy all passwords and folders (everything) to new environment.
We do fresh LAMP install, with exact the same versions as the old teampass server. Then
1. We restore the the sql taken from UI with admin user to new environment but the password fields are empty.
2. We tar the whole teampass directory under /var/www/html, do database backup from terminal, then restore it all at new environment, this time we can not see users and folders (only roles). In the main page it shows information about the users folders. But actually we cant see them.
The version of teampass: 2.1.27.36

**Comment by nilsteampassnet** [comment]
I don't maintain anymore branch 2.
But if I remember well you need to also move sk.php file where its folder is defined in settings.php.
You need to adapt also all paths manually in misc table and tp.config.php.
Take also look your error.log file.

**Comment by azizbaghirov** [comment]
Hi, dear Nils!

We've got the solution. I'll write the steps in order other people to handle the problem, if someone else using this version.
1. On a new server installed LAMP, created database and a db user.
2. Downloaded tar of 2.1.27.36 version, extracted to /var/www/html
3. Set up the use of Teampass for the first time as normal, then
4. Backed up the database on the old server with admin user. (from GUI)
5. Backed up the entire Teampass directory on the old server.
6. Restored the database on the new server with admin user. (from GUI)
7. Replaced the entire Teampass directory on the new server with the files taken from the old server
8. Adapted the settings of 'TeamPass location (URL)' and other related URLs to my new server
9. Then I was able to login as other user different from admin and the passwords are visible!
10. (Additionally) If you use LDAP auth on the old server, then install php-ldap extension on the new server too, enable it.
