### ISSUE TITLE
nodeDirectDescendants in prepareNodeData should be array but is stdClass

### ISSUE THREAD

**Issue by BelgarathS** [nilsteampassnet/TeamPass#3520]
### Steps to reproduce
1. issue happens every time tree.php is called

### Expected behaviour
folders should be listed

### Actual behaviour
tree.php returns 500 error 
Uncaught Error: Object of class stdClass could not be converted to string in  sources/tree.php

### Server configuration
**Operating system**:
Ubuntu 22.04
**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
8.1.2
**Teampass version:** 
latest as of fep13 2023

#### Web server error log
```
Uncaught Error: Object of class stdClass could not be converted to string in  sources/tree.php```

**Comment by Vanger69** [comment]
I observe this error for some users after upgrading from 3.0.0.22 to 3.0.0.23.

Replacing the tree.php file from the last commit didn't solve the problem. Tell me, what files need to be replaced to solve this issue?

**Comment by nilsteampassnet** [comment]
Hum, this one is tricky.
I cannot reproduce, and seems to be related to some users.
So I believe, it is configuration dependent.
I have to spend more time on code review.

**Comment by nilsteampassnet** [comment]
@BelgarathS 
Can you please use latest commit?
Please run upgrade just after

**Comment by BelgarathS** [comment]
@nilsteampassnet 
That worked, and the issue is gone.
