### ISSUE TITLE
Post  Update from 2.1.27.36 to 3.0.0.22 not able login with any user account 

### ISSUE THREAD

**Issue by Nathu2018** [nilsteampassnet/TeamPass#3525]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
getting following error in Phperror.log

[15-Feb-2023 17:47:39 UTC] PHP Parse error:  syntax error, unexpected ')' in C:\wamp64\www\TeamPass\sources\identify.php on line 430

Next error occurred
SyntaxError: Unexpected end of JSON input

Raw answer from server:
### Server configuration
**Operating system**:

**Web server:**
2.4.27
**Database:**
5.7.19 mysql
**PHP version:**
7.1.9
**Teampass version:** 
3.0.0.22
**Teampass configuration file:**
[](url)
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Nathu2018** [comment]
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => 'C:/wamp64/www/Teampass',
    'cpassman_url' => 'https://nrc2teampassvm.am.tsacorp.com/Teampass',
    'favicon' => 'https://nrc2teampassvm.am.tsacorp.com/Teampass/UP_icon.ico',
    'path_to_upload_folder' => 'C:/wamp64/www/Teampass/upload',
    'url_to_upload_folder' => 'https://nrc2teampassvm.am.tsacorp.com/Teampass/upload',
    'path_to_files_folder' => 'C:/wamp64/www/Teampass/files',
    'url_to_files_folder' => 'https://nrc2teampassvm.am.tsacorp.com/Teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '1',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.22',
    'ldap_mode' => '0',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@am.tsacorp.com',
    'ldap_domain_dn' => 'DC=am,DC=tsacorp,DC=com',
    'ldap_domain_controler' => 'am.tsacorp.com',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '["10","13","14"]',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '15',
    'utf8_enabled' => '1',
    'restricted_to' => '1',
    'restricted_to_roles' => '1',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '1',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => 'https://nrc2teampassvm.am.tsacorp.com/Teampass/corp-logo',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1518528157',
    'get_tp_info' => '0',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '45',
    'email_smtp_server' => 'smtp.am.tsacorp.com',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'Teampassadmin@aciworldwide.com',
    'email_from_name' => 'Teampass Password  Manager',
    'pwd_maximum_length' => '30',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '20mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '\\am.tsacorp.com\fileshares\CorpIT\SFTWREPO\Teampass',
    'bck_script_filename' => 'Bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '1',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'ldap_new_user_role' => '',
    'ldap_allowed_usergroup' => '',
    'can_create_root_folder' => '0',
    'tree_counters' => '1',
    'bck_script_passkey' => 'WhuUYyRABZuFYZJzq8HNJrKgLuBFbwmzrcMqNQHM',
    'copy_to_clipboard_small_icons' => '1',
    'teampass_version' => '2.1.27',
    'admin_2fa_required' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'password_overview_delay' => '4',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '0',
    'task_maximum_run_time' => '300',
    'maximum_number_of_items_to_treat' => '300',
    'tasks_manager_refreshing_period' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
);

**Comment by nilsteampassnet** [comment]
Please check requirements
![image](https://user-images.githubusercontent.com/1197546/219279049-d55d7444-6a15-456e-84d8-6a3807228352.png)
