### ISSUE TITLE
Primary Key in API create table in install.queries.php is inconsistent

### ISSUE THREAD

**Issue by Peteraguy** [nilsteampassnet/TeamPass#3534]
### Steps to reproduce
Clean install 
During setup

### Expected behaviour
no error should be generated

### Actual behaviour
an error is generated at the database population stage 5

### Server configuration
**Operating system**:
Debian 11
**Web server:**
Apache 2.4.54
**Database:**
Mariadb 10.5.18
**PHP version:**
7.4.33
**Teampass version:** 
30.0.0.23
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
FireFox
**Operating system:**
Window 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
in install.queries.php the stage 5 api create table tries to set the field 'id' as the primary key. There is no 'id' field, there is 'increment_id' so either the auto increment field name is wrong or the primary key is wrong or possibly both. 
'CREATE TABLE IF NOT EXISTS `' . $var['tbl_prefix'] . 'api` (
                            `increment_id` int(20) NOT NULL AUTO_INCREMENT,
                            `type` varchar(15) NOT NULL,
                            `label` varchar(255) DEFAULT NULL,
                            `value` text DEFAULT NULL,
                            `timestamp` varchar(50) NOT NULL,
                            `user_id` int(13) DEFAULT NULL,
                            PRIMARY KEY (`id`),
                            KEY `USER` (`user_id`)
                            ) CHARSET=utf8;'
Correcting this in either direction allows setup to complete. The admin account can log in. However TeamPass claims database is not up to date, with inconsistences between files and configuration. The administrator should upgrade. I do not know if the correction of the api table error is responsible for the inconsistencies message.

**Comment by Peteraguy** [comment]
Whilst trying to figure out why a clean install is saying it is inconsistent and needs upgrading. I have looked at other code in upgrade_run_3.0.0.php and it would appear that increment_id is the correct field name making the primary key line wrong. install.queries.php line 1147 should read PRIMARY KEY (increment_id ),

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
