### ISSUE TITLE
Users List, Database page and Logs page don't show any data

### ISSUE THREAD

**Issue by JunkyDeveloper** [nilsteampassnet/TeamPass#3536]
### Steps to reproduce
0. Change DNS without change the url in the software
1. login as every user
2. go to page users
3. when waiting or clicking on refresh

### Expected behaviour
See current users which are in the systems

### Actual behaviour
button right corner Loading, still there after 20mins.

### Currently more behaviour which don't work
But if i want to propagate a users this list is filled withut any delay and every user is there included.
Means only the main user page don't work well.
The database tab also don't work and loads a long time with no result.
The logs tab also don't work and loads a long time without any result.

### Working pages
Password page, Roles page and folders Page work fine without any problems.

**Comment by JunkyDeveloper** [comment]
While writing this issue i found the solution.
So maybe it helps a person to find the exact same problem i wrote that issue.

It was step 0. 
I changed the url from sam.domain.de to domain.de without changing it in the settings page to domain.de.
Changing it there in the two fields solved my problem.

It took me to long to find it...

**Comment by mikepell007** [comment]
Thank you for this.  In my case I was using https://url.tld but hat "http" in the settings.
