### ISSUE TITLE
Nothing when click on log in (fresh install)

### ISSUE THREAD

**Issue by crzkwcz** [nilsteampassnet/TeamPass#3539]
Hi,

I have installed the last TeamPass on Debian 11, all fresh.
I successfuly get the log in page but nothing happens when I click on Log In button.
I have got nothing in apache2 logs.
Any idea ?
Thank you.

**Comment by JunkyDeveloper** [comment]
I think that sounds like the problem which i had with a fresh install 
My issue is #3538
So go 2 commits back or the commit which i meantioned should help and solve that bug.
If not then you have another problem

**Comment by crzkwcz** [comment]
I have just tried to replace folders.queries.php by the one available here : https://github.com/nilsteampassnet/TeamPass/blob/435469a0fbb350e231e3f9884dc2467d984840cd/sources/folders.queries.php

This does not change anyhting, I am still stuck on the log in page :-(

**Comment by JunkyDeveloper** [comment]
What i can really recommend is delete everything (database and folder structure).
Clone again. went two commits back and then make again the install.
This was my way until it worked fine on a local installation.

**Comment by crzkwcz** [comment]
Hi,
I have tried as you suggested :
"Clone again. went two commits back and then make again the install.
This was my way until it worked fine on a local installation."

Now I have got the following error : 
"some inconsistencies have been identified between files and configuration, Your administrator should perform upgrade process before you continue."

Any idea ? 

Thanks again for your help, very appreciated 👍

**Comment by JunkyDeveloper** [comment]
The @nilsteampassnet gave an update on my issue #3538 (1 hour ago)
I will test that and if i have no problems with that version maybe you can try that newest version.

**Comment by JunkyDeveloper** [comment]
In short new newest version also don't work on my side.
Did you really deleted everything from teampass before install it again?
If I didn't deleted the database i got also really undefined behaviour. So delete all files + database. (db user can stay)
That help me.

**Comment by nilsteampassnet** [comment]
Tests have been updated and run successfully on latest commit.

**Comment by crzkwcz** [comment]
Here is what I am going to do, Am I right ?

**1. Delete Database teampass in SQL :
drop database teampass;
show databases; 
--> the database is deleted

2. Delete TeamPass folder :
rm -r /var/www/html/TeamPass
--> ls /var/www/html
--> the diretory is deleted

3. Create again the database in SQL :
create database teampass;
GRANT ALL PRIVILEGES ON teampass.* TO 'teampass_admin'@'localhost';
(the user teampass_admin already exists)

4. Get TeamPass files
cd /var/www/html
git clone https://github.com/nilsteampassnet/TeamPass.git

5. Get the file folders.queries.php (v3.0.0.23) from GitHub and put it into /var/www/html/TeamPass/sources (replace the existing one)

6. Set folders permissions :
sudo chmod 0777 install/ includes/ includes/config/ includes/avatars/ includes/libraries/csrfp/libs/ includes/libraries/csrfp/js/ includes/libraries/csrfp/log/ files/ upload/

7. Go to TeamPass web interface and finish the installation_**

**Comment by JunkyDeveloper** [comment]
Looks good :/ 
Sorry, then i can't really help you

**Comment by crzkwcz** [comment]
I did all the steps as described and I can now successfuly log on :-)
This issue is solved, thank you.
(now I am dealing with a new issue... new issue is a new topic)
