### ISSUE TITLE
Create/delete folder issue

### ISSUE THREAD

**Issue by jofrey007** [nilsteampassnet/TeamPass#3572]
### Steps to reproduce
1.  Log as admin
2. Create new folder
3. Delete Folder

### Expected behaviour
New folder is created, admin is able to delete folder

### Actual behaviour
Folder is created, but page is not refreshed.
Web server issue
Mon Mar 06 13:48:32.975617 2023] [php:warn] [pid 11203] [client 10.30.0.60:58742] PHP Warning:  Undefined property: Tree\\NestedTree\\NestedTree::$id in /var/www/teampass/sources/folders.queries.php on line 711, referer: https://teampass.irsys.sk/index.php?page=folders
[Mon Mar 06 13:48:32.976793 2023] [php:error] [pid 11203] [client 10.30.0.60:58742] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'data' doesn't have a default value in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/teampass/sources/folders.queries.php(739): DB::insert()\n#7 {main}\n  thrown in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://teampass.irsys.sk/index.php?page=folders

When detele folder apache server log issue:

[Mon Mar 06 13:44:16.824071 2023] [php:warn] [pid 11202] [client 10.30.0.60:42944] PHP Warning:  Trying to access array offset on value of type null in /var/www/teampass/sources/folders.queries.php on line 965, referer: https://teampass.irsys.sk/index.php?page=folders
[Mon Mar 06 13:44:16.824169 2023] [php:error] [pid 11202] [client 10.30.0.60:42944] PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /var/www/teampass/sources/folders.queries.php:965\nStack trace:\n#0 /var/www/teampass/sources/folders.queries.php(965): json_decode()\n#1 {main}\n  thrown in /var/www/teampass/sources/folders.queries.php on line 965, referer: https://teampass.irsys.sk/index.php?page=folders

### Server configuration
**Operating system**: Debian 11

**Web server:**
Server version: Apache/2.4.54 (Debian)

**Database:**
mysql  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:**
PHP 8.1.16 (cli) (built: Feb 14 2023 18:28:06) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies

**Teampass version:** 
commit 1f91ec13a7d7f3803e3b5ff62ad95a941d60034e
Author: nilsteampassnet <nils@teampass.net>
Date:   Thu Mar 2 08:38:22 2023 +0100

    3.0.0.23

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
fresh install

### Client configuration
**Browser:**
Version 110.0.5481.178 (Official Build) (64-bit)

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by jofrey007** [comment]
Relationship with 
https://github.com/nilsteampassnet/TeamPass/issues/3575 ?

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by jofrey007** [comment]
> A fix has been committed. Please reopen if needed.

I confirm that the error for creating and deleting new directories has been fixed. However, I have directories that were created before the error was fixed. When attempting to delete such a directory, I receive an error message from the Apache server.

[Mon Mar 13 11:48:56.353829 2023] [php:warn] [pid 41563] [client 10.30.0.60:48784] PHP Warning:  Trying to access array offset on value of type null in /var/www/teampass/sources/folders.queries.php on line 967, referer: https://teampass2.irsys.sk/index.php?page=folders
[Mon Mar 13 11:48:56.353967 2023] [php:error] [pid 41563] [client 10.30.0.60:48784] PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /var/www/teampass/sources/folders.queries.php:967\nStack trace:\n#0 /var/www/teampass/sources/folders.queries.php(967): json_decode()\n#1 {main}\n  thrown in /var/www/teampass/sources/folders.queries.php on line 967, referer: https://teampass2.irsys.sk/index.php?page=folders

Is there any way to manually delete these unwanted directories (for example, directly in the database)? These are just test directories.
