### ISSUE TITLE
Help - AD group to Role Mapping

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#3578]
One of the great new features which I am trying to get working on TeamPass is the AD Group to TeamPass Role mapping.  Has anyone got this working with Active Directory?  I cannot seem to find the right config to get this to work,  AD works fine for users but im stuck with this.  I realise this is still a WIP, but just if anyone has got this working, if they could share their config, would be very helpful

**Comment by hitenmandalia** [comment]
This is my ldap config which works for users.
![image](https://user-images.githubusercontent.com/62652225/224047506-0504134f-8d71-4274-800f-d22d9613c076.png)

When trying to do the ldap sync for roles, I see the following error in the error log

![image](https://user-images.githubusercontent.com/62652225/224047088-49f1d006-04d3-4e54-8663-811bc30a81d6.png)

**Comment by nilsteampassnet** [comment]
@hitenmandalia 
A fix has been committed.
Please reopen if needed.
