### ISSUE TITLE
Create/delete folder

### ISSUE THREAD

**Issue by jofrey007** [nilsteampassnet/TeamPass#3581]
Because I am not able to reopen issue a created one new from previous

https://github.com/nilsteampassnet/TeamPass/issues/3572

           > A fix has been committed. Please reopen if needed.

I confirm that the error for creating and deleting new directories has been fixed. However, I have directories that were created before the error was fixed. When attempting to delete such a directory, I receive an error message from the Apache server.

[Mon Mar 13 11:48:56.353829 2023] [php:warn] [pid 41563] [client 10.30.0.60:48784] PHP Warning:  Trying to access array offset on value of type null in /var/www/teampass/sources/folders.queries.php on line 967, referer: https://teampass2.irsys.sk/index.php?page=folders
[Mon Mar 13 11:48:56.353967 2023] [php:error] [pid 41563] [client 10.30.0.60:48784] PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in /var/www/teampass/sources/folders.queries.php:967\nStack trace:\n#0 /var/www/teampass/sources/folders.queries.php(967): json_decode()\n#1 {main}\n  thrown in /var/www/teampass/sources/folders.queries.php on line 967, referer: https://teampass2.irsys.sk/index.php?page=folders

Is there any way to manually delete these unwanted directories (for example, directly in the database)? These are just test directories.

_Originally posted by @jofrey007 in https://github.com/nilsteampassnet/TeamPass/issues/3572#issuecomment-1465918289_

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by jofrey007** [comment]
Fix is OK :-) thank so much ;)
