### ISSUE TITLE
Infinite `In progress` loader instead of warning

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3585]
### Steps to reproduce
1. Complete installation of teampass 3.0.0.23
2. Don't delete `/var/www/teampass/install` folder
3. Try to login as admin

### Expected behaviour
Warning `Install folder has to be removed` appears.

### Actual behaviour
Infinite `In progress` loader spinning. No warning. User can't understand what is gone wrong.
Executing `rm -rf /var/www/teampass/install` helps ofcourse.

![infinite in progress](https://user-images.githubusercontent.com/2260980/224999496-8987f7d5-5434-4a46-80b6-f70d330d2819.png)

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.23 (downloaded on 14.03.2023)

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/10579571/tp.config.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox 110.0.1

**Operating system:** Windows 10 x64

#### Web server error log
\-

#### Log from the web-browser developer console
```Object { value: "", user_admin: 0, initial_url: "", pwd_attempts: 3, error: true, message: "Install folder has to be removed" }
​error: true
​initial_url: ""
​message: "Install folder has to be removed"
​pwd_attempts: 3
​user_admin: 0
​value: ""```

**Comment by Kyogre** [comment]
By the way the same behaviour if trying to login with wrong password many times.
Log:
> Object { value: "bruteforce_wait", user_admin: 0, initial_url: "", pwd_attempts: 8, error: true, message: "Login credentials incorrect!<br>Please wait 10 seconds before next attempt" }

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by Kyogre** [comment]
@nilsteampassnet I found another one case:
`Object { error: "user_not_exists", message: "Login credentials do not correspond!", pwd_attempts: 3, user_admin: 0, initial_url: "" }`

It occurs when you try to login with nonexistant username. Can you reopen the issue or make quick fix?
