### ISSUE TITLE
Can create a folder at root level checkbox won't save when user created

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3586]
### Steps to reproduce
1. Start to create a new user
2. Check the option `Can create a folder at root level`
3. Press "Submit"
4. Press "Edit" on that new user

### Expected behaviour
User created with checkbox `Can create a folder at root level` checked.

### Actual behaviour
User created with checkbox `Can create a folder at root level` unchecked. Needs to check checkbox again and submit to save checkbox successfully.
See the [video demo](https://user-images.githubusercontent.com/2260980/225020470-e5c2df9a-092a-498c-a51d-8ee582fd94b6.mp4).

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.23 (downloaded on 14.03.2023)

**Teampass configuration file:**
[tp.config 3.0.0.23 4cd9b4b.zip](https://github.com/nilsteampassnet/TeamPass/files/10969325/tp.config.3.0.0.23.4cd9b4b.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration

**Browser:** Firefox 110.0.1

**Operating system:** Windows 10 x64

#### Web server error log
\-

#### Log from the web-browser developer console (CTRL + SHIFT + i)
\-

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
