### ISSUE TITLE
No warning when trying to create item without label

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3588]
### Steps to reproduce
1. Start creating item
2. Upload some attachment
3. Don't fill label
4. Click `Save`

### Expected behaviour
Teampass shows warning about label required to be filled (label is mandatory).

### Actual behaviour
Teampass shows `Done` popup. No item created.

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.23 (downloaded on 14.03.2023)

**Teampass configuration file:**
[tp.config 3.0.0.23 4cd9b4b.zip](https://github.com/nilsteampassnet/TeamPass/files/10969325/tp.config.3.0.0.23.4cd9b4b.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration

**Browser:** Firefox 110.0.1

**Operating system:** Windows 10 x64

#### Web server error log
\-

#### Log from the web-browser developer console (CTRL + SHIFT + i)
\-

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by Kyogre** [comment]
Tested the fix, but there are still two cases, when saving is incorrectly possible:
1. Try to upload attachment > get error about label > Save
2. Select attachment but don't upload > Save
I have shown them on the [new video](https://user-images.githubusercontent.com/2260980/226342510-b97dbcc7-90e6-47a2-aa9b-76d024ebec63.mp4.

**Comment by Kyogre** [comment]
Also there is now `Provide a label` error when trying to upload any attachment despite the label is filled. [Video](https://user-images.githubusercontent.com/2260980/226372003-6eb98541-9e39-488f-b004-46e16ea6ad89.mp4).

**Comment by Kyogre** [comment]
@nilsteampassnet hi! Can you have a look at two aforementioned comments? Or do is it better if I will create 3 new separate issues?

**Comment by nilsteampassnet** [comment]
@Kyogre IT should be ok now.
Please confirm.

**Comment by Kyogre** [comment]
Thank you! Tested. All cases are now seem fixed.
