### ISSUE TITLE
Can't upload file with unknown extension despite `Upload any extension file` is checked

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3589]
### Steps to reproduce
1. Check that you have `Upload any extension file` checkbox checked.
2. Create an item.
3. Try to upload file with extension which is not specified in `extensions allowed` in "Uploads" settings.

### Expected behaviour
File with any extension uploads with success.

### Actual behaviour
Despite `Upload any extension file` enabled, file won't upload, shows `HTTP Error., File: <filename>`
See the [video demo](https://user-images.githubusercontent.com/2260980/225030714-0c79d13d-a05f-454f-a61d-0a574c01cee7.mp4).

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.23 (downloaded on 14.03.2023)

**Teampass configuration file:**
[tp.config 3.0.0.23 4cd9b4b.zip](https://github.com/nilsteampassnet/TeamPass/files/10969325/tp.config.3.0.0.23.4cd9b4b.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration

**Browser:** Firefox 110.0.1

**Operating system:** Windows 10 x64

#### Web server error log
\-

#### Log from the web-browser developer console (CTRL + SHIFT + i)
500 Internal Server Error

### Workaround
Manually write file extension in `Archive/Documents/Image/Other extensions allowed` in "Uploads" settings.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
