### ISSUE TITLE
`Please select a folder` error when creating new item after Cancel or Saving the item

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#3597]
### Steps to reproduce
1. select a folder
2. press `New item`
3. press `Cancel`
4. press `New item`

### Expected behaviour
Item creation form should open as it does if you press `New item` after clicking back arrow button.

### Actual behaviour
Error `Please select a folder` appears. See [the video](https://user-images.githubusercontent.com/2260980/225942086-7d336b80-07ca-4648-8b5b-ffe446cefe36.mp4).
Same goes for `Save` button: if I save some item, I can't create another one immediately after that until I reselect the folder.

Workaround: as I said, reselect the same folder, then press `New item`.

### Server configuration
**Operating system**: Red OS 7.3.2 (Red Hat 8.3 like)

**Web server:** Apache 2.4.5.4-1.el7.3

**Database:** MariaDB 10.10.2-2.el7 (5.5.5-10.10.2-MariaDB) + mysqlnd 7.4.33

**PHP version:** 7.4.33-1.el7

**Teampass version:** 3.0.0.23 4cd9b4b

**Teampass configuration file:**
[tp.config 3.0.0.23 4cd9b4b.zip](https://github.com/nilsteampassnet/TeamPass/files/10969325/tp.config.3.0.0.23.4cd9b4b.zip)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration

**Browser:** Firefox 111

**Operating system:** Windows 10 x64

#### Web server error log
\-

#### Log from the web-browser developer console (CTRL + SHIFT + i)
\-

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
