### ISSUE TITLE
Database upgrade runs forever on step #1

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3612]
Latest commit [1983379](https://github.com/nilsteampassnet/TeamPass/commit/1983379345e782954b426e3937fac644355e8038)

![grafik](https://user-images.githubusercontent.com/14745069/227790683-bf547553-1795-4a42-842d-f9465595610e.png)

Console shows only:
Object { finish: "0", scriptname: "upgrade_run_3.0.0.php", parameter: "user_id" }

Items in database: 128

No errors in fpm error log neither in error log of web server
Client: Firefox 111.0 Ubuntu 22.04
Server: rhel8 with php7.4.30

**Comment by nilsteampassnet** [comment]
hum ... from the web console, what is the response from upgrade_run_3.0.0.php (in network tab) please ?

**Comment by useronkel** [comment]
Hi Nils.
Version: dunno exactly, but have commit id ;-)
From https://github.com/nilsteampassnet/TeamPass
   10687c75..19833793  master     -> origin/master

But found the error in network tab: MySQL Error 2! Permission denied....
DB-User had no rights on selected database anymore....
Weird thing, but it seems it relies on my own fault :-D
