### ISSUE TITLE
Install completes, but can't add email to admin, or add users, or see folders created

### ISSUE THREAD

**Issue by EtherOrcsDAO** [nilsteampassnet/TeamPass#3638]
### Steps to reproduce
1.  Install Fresh Ubuntu 20.04
2. Install Teampass via install manual path
3. On login as Admin, most functions work, but adding email to Admin account fails "Fields need to be filled in" but all fields are filled in.  When looking at users, it looks like the following:
![image](https://user-images.githubusercontent.com/125311353/229929998-16b2a45e-ebbc-4889-b391-1b9f86206c40.png)

I can create a user, but they forever have the HourGlass next to their name, and they cannot see ANY folders, whether they create them or admin does.  And it never stops saying "Your account is being created"

### Expected behaviour
I should be able to add email to admin account.  Users should be able to see folders.

### Actual behaviour
On login as Admin, most functions work, but adding email to Admin account fails "Fields need to be filled in" but all fields are filled in.  When looking at users, it looks like the following:
![image](https://user-images.githubusercontent.com/125311353/229929998-16b2a45e-ebbc-4889-b391-1b9f86206c40.png)

I can create a user, but they forever have the HourGlass next to their name, and they cannot see ANY folders, whether they create them or admin does.  And it never stops saying "Your account is being created"

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 8.0

**Teampass version:** 3.0.3

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** FireFox

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by foc-82** [comment]
I have the same error, I noticed that there are tasks that have the status "in progress" of the type "create_user_keys"

**Comment by EtherOrcsDAO** [comment]
> I have the same error, I noticed that there are tasks that have the status "in progress" of the type "create_user_keys"

Did you install MCrypt?  I did not, as it's deprecated and shouldn't be needed, but I wonder if it's needed to get through this?

**Comment by EtherOrcsDAO** [comment]
I have done the reinstall multiple times, including a brand new install, on an upgraded Ubuntu 22.04.  PROBLEM PERSISTs.  This appears to be an error in the current release of TeamPass.

**Comment by EtherOrcsDAO** [comment]
The problem is with the Task Manager function added in 3.0.0.23.  Can confirm on raw install 3.0.0.22 and older work fine.  3.0.0.23 and newer break.  Crontab looks like job is there, but 3.0.0.23 has a field to add password on crontab create install menu that 3.0.1 and 3.0.2 do not have.  Additionally, the crontab task is added without full path to PHP.  Added path, but still no go.  In 3.0.0.23 task is GREYED OUT to off and admin account never finished creation.  I am going to revert to 3.0.0.22 and stay there until we see what the bug is.  @nilsteampassnet

**Comment by EtherOrcsDAO** [comment]
I take it back, nothing is working.  There is something about this Ubuntu build, that it is not working, at all.  This is beyond frustrating.  It's like the install is corrupt.  I can't add an email to admin, users can see folders, even when they have rights to see them, users can't setup 2FA, it's just fubar!

**Comment by EtherOrcsDAO** [comment]
I did a fresh install, with a completely different provider, and the issue persists.  All servers I am doing this on, are VPS systems atm.  I am going to try a bare metal system shortly to see if that makes a difference.

**Comment by nilsteampassnet** [comment]
@EtherOrcsDAO 
Tasks is not optional now, that's why it is enabled by default and cannot be deactivated.
Upgrade process performs the command "locate php" to get the path to php but if not, it only uses php command.
Can you please share:
* a screenshot of tab `Tasks` from menu Tabs
* the cron job added in crontab with command `crontab -l` or `sudo crontab -u www-data -l` (or whatever the user running apache)
You may also enable log for tasks to get some outputs

**Comment by EtherOrcsDAO** [comment]
These never go away, where the red arrows are, for any account:
![image](https://user-images.githubusercontent.com/125311353/230672371-b43ecd10-e963-48fa-a482-845e467dade5.png)

Here are the tasks Tab ->
![image](https://user-images.githubusercontent.com/125311353/230672464-bc8636dc-3cef-42b1-8cb7-af428b8846d5.png)

Here's from Crontab run as www-data:
![image](https://user-images.githubusercontent.com/125311353/230672584-0f378fa2-d4fe-443a-8209-393340ae63ae.png)

System is still unstable.  Logging in with a user, and adding items, previously added items ask for a previous password when going back into them.  Email cannot be added to admin from user menu but I can from upper right when logged into Admin.  Emails appear to be sent out, but never reach destination but UI says email sent successfully.

**Comment by EtherOrcsDAO** [comment]
Thanks again @nilsteampassnet .  I've been using TeamPass for years and I love the ability to host this critical need myself.

**Comment by nilsteampassnet** [comment]
Reading this, it is not the tasks handler that has an issue.
What about the apache log error, you should see many thinggs inside it.
Can you share with me please.

**Comment by nilsteampassnet** [comment]
@EtherOrcsDAO 
* Can you also check if www-data can run files in the tempass folder (is it part of the chmod group)
* Can you run `sudo grep CRON /var/log/syslog` to see if the cron job is running as expected ?
* When you have upgraded, did you run the steps until the complete end?
* Don't you have several php installed, and is /usr/bin/php tje correct one?

**Comment by EtherOrcsDAO** [comment]
> @EtherOrcsDAO
> 
>     * Can you also check if www-data can run files in the tempass folder (is it part of the chmod group)
These are the permission for top level Teampass directory and all files/folders in it:
"drwxrwxr-x 13 www-data www-data  4096 Apr  7 01:24 TeamPass"
>     * Can you run `sudo grep CRON /var/log/syslog` to see if the cron job is running as expected ?
"grep: /var/log/syslog: No such file or directory"
>     * When you have upgraded, did you run the steps until the complete end?
NO upgrade, Fresh install 
>     * Don't you have several php installed, and is /usr/bin/php tje correct one?
No sir, I tried with multiple fresh installs.  I've used PHP 7-4, 8.0, and now am using 8.1

**Comment by nilsteampassnet** [comment]
Find where the syslog of your linux is, this will permit you to see if the scheduler is correctly performed every minute by the cron.

3 things you can perform:
* Check the errors in Apache log and in web console
* Execute `php sources/scheduler.php`, check the apache logs
* Execute `php scripts/background_tasks___sending_emails.php`, check the apache logs

**Comment by EtherOrcsDAO** [comment]
@nilsteampassnet 


I had to install rsyslog, and now I have a syslog.:
`Apr  9 15:29:01 safe CRON[54999]: (www-data) CMD (/usr/bin/php /var/www/html/TeamPass/sources/scheduler.php 1>> /dev/null 2>&1 #Teampass scheduler)`

So that would tell me CRON is working fine, right?  

Your second command gave paydirt!  I had a suspicion that something was wrong with the DB, as the abnormal behavior around folder access and viewing, etc, had me thinking it might be there.  The install worked perfectly, access to the DB was fine, creation of all tables was/were fine, but something is missing maybe?

FOUND 
'username@safe:/var/www/html/TeamPass$ php scripts/background_tasks___sending_emails.php
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'eodsafe.teampass_processes_logs' doesn't exist in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()
#4 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()
#5 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()
#6 /var/www/html/TeamPass/scripts/background_tasks___functions.php(55): DB::insert()
#7 /var/www/html/TeamPass/scripts/background_tasks___sending_emails.php(59): doLog()
#8 {main}
  thrown in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 682
username@safe:/var/www/html/TeamPass$ php sources/scheduler.php
username@safe:/var/www/html/TeamPass$
'

**Comment by EtherOrcsDAO** [comment]
@nilsteampassnet 
turned this off (as I remember this from before) and now that command no longer gives an error:
![image](https://user-images.githubusercontent.com/125311353/230782239-914ac974-00ff-4c2d-aa75-482941cd9acf.png)

**Comment by nilsteampassnet** [comment]
@EtherOrcsDAO 
Table processes_logs is missing if I refer to your message ... while checking the install process, it is indeed missing ... I'm providing a fix for this.

**Comment by EtherOrcsDAO** [comment]
@nilsteampassnet I updated CRON, do you want me to do a fetch or a merge to update?

**Comment by nilsteampassnet** [comment]
I don't know how is created your teampass instance. Just get the last commit on master and run update. 👍

**Comment by NaumovAlexey** [comment]
In DB there are two missing tables: processes_logs and ldap_groups_roles. I think it's because of mistake in script that creates tables during installation.
![image](https://user-images.githubusercontent.com/35455601/231700523-1d6cfebd-f058-4ea7-a4dc-6bbdc02bc8c1.png)
There is primary key, but this row isn't creating

**Comment by EtherOrcsDAO** [comment]
> In DB there are two missing tables: processes_logs and ldap_groups_roles. I think it's because of mistake in script that creates tables during installation. ![image](https://user-images.githubusercontent.com/35455601/231700523-1d6cfebd-f058-4ea7-a4dc-6bbdc02bc8c1.png) There is primary key, but this field isn't creating

@nilsteampassnet is this what you fixed/should be good to go?  I'll most likely do a fresh install from 3.0.3 to see if it resolves it.

**Comment by nilsteampassnet** [comment]
Please update or install latest release

**Comment by EtherOrcsDAO** [comment]
K, fresh install, of 3.0.7.  Task is happy, process_log database now is created, but the account never get out of hourglass hell ->
![image](https://user-images.githubusercontent.com/125311353/232621237-411b9a75-9faa-4776-9017-fc4e3beb5c88.png)

@nilsteampassnet Is this the expected behavior?  Before I go and start putting data back into the safe, and then find it's still broken, wanted to verify this is expected or not-expected.

**Comment by EtherOrcsDAO** [comment]
@nilsteampassnet 
Looks much better now, within the system.  Thanks again for digging in and helping my dude, really appreciate it:
![image](https://user-images.githubusercontent.com/125311353/233193633-a9cb21c4-34c6-49d0-ac21-066239136f89.png)

**Comment by Arodriguesmg** [comment]
I'm going through exactly this, if anyone has a solution to run these tasks or the update procedure, send me.

**Comment by Arodriguesmg** [comment]
can anyone help me with this
