### ISSUE TITLE
500 Internal Server Error - Logout

### ISSUE THREAD

**Issue by edra10** [nilsteampassnet/TeamPass#3639]
After upgrade Teampass version 2.1.27.36 to version 3.0.0.23, after navigating through the application without errors, when we logout from Teampass, we get the error message "Failed to load resource: the server responded with a status of 500."

### Steps to reproduce
1. Make logout from teampass version 3.0.0.23.

### Expected behaviour
Redirect to login page.

### Actual behaviour
We have seen the following warnings and errors in the www-error.log file (php):
PHP Warning:  Use of undefined constant SECUREFILE - assumed 'SECUREFILE' (this will throw an Error in a future version of PHP) in /var/www/TeamPass-3.0.0.23/sources/main.functions.php on line 128
PHP Warning:  file_get_contents(/var/www/TeamPass/includes/SECUREFILE): failed to open stream: No such file or directory in /var/www/TeamPass-3.0.0.23/sources/main.functions.php on line 128
PHP Fatal error:  Uncaught Defuse\Crypto\Exception\BadFormatException: Encoded data is shorter than expected. in /var/www/TeamPass-3.0.0.23/includes/libraries/Encryption/Encryption/Encoding.php:225
Stack trace:
#0 /var/www/TeamPass-3.0.0.23/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString()
#1 /var/www/TeamPass-3.0.0.23/sources/main.functions.php(149): Defuse\Crypto\Key::loadFromAsciiSafeString()
#2 /var/www/TeamPass-3.0.0.23/sources/main.functions.php(306): cryption()
#3 /var/www/TeamPass-3.0.0.23/includes/core/logout.php(55): defuseReturnDecrypted()
#4 {main}
  thrown in /var/www/TeamPass-3.0.0.23/includes/libraries/Encryption/Encryption/Encoding.php on line 225

### Server configuration
Centos8
PHP 7.4.33
Server version: Apache/2.4.37 (centos)
10.7.8-MariaDB
TeamPass-3.0.0.23

**Comment by kevnoli** [comment]
Following a suggestion here for another issue and analysis on my server, I added `define('SECUREFILE', 'teampass-seckey.txt');` to both `includes/config/settings.php` and `/includes/config/include.php`. Adding it just to `include.php` did not work for some reason.

**Comment by edra10** [comment]
Thanks @kevnoli, the solution you mentioned worked, thank you very much!

Regards.

**Comment by naderlb** [comment]
add --> **@define('SECUREFILE', 'teampass-seckey.txt');** 
line 120 in /var/www/html/teampass/sources/main.functions.php
