### ISSUE TITLE
Invalid scheduler cron task PHP interpreter

### ISSUE THREAD

**Issue by Aldenar** [nilsteampassnet/TeamPass#3663]
### Steps to reproduce
1. Install Teampass on Debian with PHP installed
2. Run "crontab -l"
3. Check if a correct PHP interpreter executable is being used

### Expected behaviour
The command "locate" finds all files containing the pattern php in their name, including all the directories, source files and other unrelated files.

Unfortunately, the specific behavior of locate can also depend on the Linux distribution used, and so, it'd be best to implement locating the interpreter manually, as a command shell would do.

The rough idea is as such:
1 - Split the PATH environment variable by the delimiter ":"
2 - For each of the resulting components, look for a file "php"
3 - If found, check if file is a file, and if it has the execute bit set
4 - If none is found, raise an exception, as systems can only contain the FPM server component, without a cli interpreter.

Alternatively, include an obligatory configuration parameter during install pointing to the PHP interpreter binary to use.

### Actual behaviour
Current implementation of locating the PHP interpreter is faulty.
In the file install/install.queries.php, it is implemented as such:
```
exec("locate php", $phpLocation, $return);
if (count($phpLocation) > 0) {
  $phpLocation = $phpLocation[0];
} else {
  $phpLocation = 'php';
}
```
### Server configuration
**Operating system**: Debian 11 Bullseye

**Web server:** Nginx 1.13.x

**Database:** MariaDB 10.11.x

**PHP version:** PHP 8.2.x

**Teampass version:** 3.0.5

**Teampass configuration file:** 
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/11231202/tp.config.txt)

**Updated from an older Teampass or fresh install:** Fresh install

#### Automated CRON messages upon script failure: 
```
/bin/sh: line 1: /etc/php: Is a directory
```

**Comment by nilsteampassnet** [comment]
Correct, this was done too quickly.
I have added a function relying on server PATHs and PHP_BINARY environment variable.
In case of not found, an explicit message is shown to user.
