### ISSUE TITLE
Unwanted HTTP status 200

### ISSUE THREAD

**Issue by Kiwi2588** [nilsteampassnet/TeamPass#3696]
My domain is: https://bis111.vse.cz 

My web server is: Apache

The operating system my web server runs on is: Debian 11 (bullseye)

I can login to a root shell on my machine: yes

The version of my client is: certbot 2.5.0

Hello, I have a problem with unwanted HTTP status 200 visible in the picture. When I initially obtained the certificate, everything went fine but after installing the TeamPass application, this problem occurred. I would be glad for any ideas on how to fix this. Thank you in advance
![Snímek obrazovky 2023-04-30 v 18 56 42](https://user-images.githubusercontent.com/132222481/235368227-11ab3654-e692-4155-9cad-52248149eb48.png)

**Comment by useronkel** [comment]
Hi there.
I think it's not an issue with teampass, but with your apache config.
302 means a resource has been moved to an other location, which is reflected with https://bis111.vse.cz redirected to https://bis111.vse.cz/teampass/ (dev console shows this clearly)

Therefore the behavior is absolutely correct.

You can avoid this by setting the apache vhost to the dcoument root of teampass.
I guess you have something like /var/www/html/teampass in your teampassconfig, but the document root of the apache points to /var/www/html/

**Comment by Kiwi2588** [comment]
Thank you very much for this reply and I apologize that I bothered that it was not specifically about TeamPass

**Comment by useronkel** [comment]
> Thank you very much for this reply and I apologize that I bothered that it was not specifically about TeamPass

All good ;-)
Sometimes you sit in front of your monitor and doesn't see anything. No one is immune against this :-)
