### ISSUE TITLE
Cron job is not set still after configuring the crontab file

### ISSUE THREAD

**Issue by fesquerre** [nilsteampassnet/TeamPass#3705]
### Steps to reproduce
1. TeamPass login
2. Information tab
3.

### Expected behaviour
Tell us what should happen

The meesage about crontab should not appear after configuring crontab for apache user.

[root@localhost cron]# cat apache
* * * * * php /var/www/html/TeamPass/sources/scheduler.php

### Actual behaviour
Tell us what happens instead
The message is there:
Cron job is not set. Please edit crontab with your server user (usually www-data) with command crontab -u www-data -e.
Or press the button to try its creation automatically.

### Server configuration
**Operating system**:
Rocky Linux 8.7 (Green Obsidian)

**Web server:**
Server version: Apache/2.4.37 (rocky)
Server built:   Apr  6 2023 16:38:06

**Database:**
Server version: 5.5.5-10.3.35-MariaDB
Database size: 0.92MB

**PHP version:**
PHP version: 7.4.30
Memory limit: 256M
Memory usage: 576.88 KB
Maximum time execution: 360
Maximum file size upload: 100M
**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome
Versión 113.0.5672.63 (Build oficial) (64 bits

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/11412515/tp.config.zip)

**Comment by fesquerre** [comment]
In the information page I have this info:

![image](https://github.com/nilsteampassnet/TeamPass/assets/115377686/d31d846f-efcf-4f86-a2e0-f41d308e6053)

**Comment by BrunoTouze** [comment]
@fesquerre 
Me too i've added the task in crontab with the command 'crontab -u www-data -e' but still this information that the cron job is not set after login in.

Go to "Task" Menu, you can retrieved this information, then click on the add button and the check is do again.
Now, the information page can show you that the cron job is found !
;-)
