### ISSUE TITLE
JS error, when loading german language

### ISSUE THREAD

**Issue by rstlfst** [nilsteampassnet/TeamPass#3707]
### Page on which it happened
JS Error after Login, when loading   german translation, there is a unmasked/unwanted line break within a string, just before     the ending dot.
in includes/language/german.php, line 1063, the ending     ".',"  comes after an line break, what crashes the GUI.

### Steps to reproduce
1. Set language to german.
2. Log out
3. Log in again
4. Try to use side menu

### Expected behaviour
page opens after login and be useable

### Actual behaviour
start page opens an it happens nothing cuz of JS error. No clicks possible, no interaction.

### Server configuration
**Operating system**: Linux 6a4e8493df15 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64

**Web server:** nginx/1.22.1

**Database:** 10.11.2-MariaDB-1:10.11.2+maria~ubu2204

**PHP version:** 8.2.5

**Teampass version:** 3.0.7

**Teampass configuration file:**
...
'default_language' => 'german',
...
```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:**  - 

**Operating system:**  - bits

### Logs

#### Web server error log
```
 -  ()
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Fixed in commit 7e4dc820 (soon pushed)
