### ISSUE TITLE
3.0.7 e-mail test OK, admin notification OK, but can't receive a mail after creating a user

### ISSUE THREAD

**Issue by accnetdev** [nilsteampassnet/TeamPass#3714]
Hi,
Users are created but I can't log in because I don't receive the credentials by e-mail on new users e-mails.
E-mail test is OK. Connection of admin notification by e-mail OK.
Please help, I can't use TeamPass 3.0.7.
Regards.

**Comment by nilsteampassnet** [comment]
It seems to be configuration related, I don't really know how to help your in this case.

**Comment by accnetdev** [comment]
Thanks.
