### ISSUE TITLE
After upgrading from 2.1.27 to 3.0.7, private folder unreadable

### ISSUE THREAD

**Issue by Jenlain74** [nilsteampassnet/TeamPass#3719]
### Steps to reproduce
1. A user set a private salt-key on 2.1.27. the salt key is containing an ampersand ("&")
2. After upgrade to 3.0.7 (and previous version), it's not possible for this user to access is personnal folder since TP 3.0.7 is telling the salt-key is false
3. no problem for other users. I created a new user and set the same salt-key without the ampersand and after upgrade no problem. Personnal folder is readable. 

### Server configuration
**Operating system**: CentOS Linux 7 (Core)

**Web server:**Apache

**Database:**5.5.5-10.7.8-MariaDB

**PHP version:**7.4.33

**Teampass version:** 3.0.7

**Comment by nilsteampassnet** [comment]
@Jenlain74 
To help your user getting back his items, can you please perform this quick and dirty fix.
* Open file ``sources/main.queries.php
* Replace
```
                (string) filter_var($dataReceived['userPsk'], FILTER_SANITIZE_FULL_SPECIAL_CHARS),
```
* with
```
                (string) filter_var($dataReceived['userPsk'], FILTER_SANITIZE_STRING),
```

This option is deprecated wut should do the job for this time.

I will investigate how to improve this in a reliable way.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
