### ISSUE TITLE
Incorect code in file "/includes/core/login.php"

### ISSUE THREAD

**Issue by tomk91** [nilsteampassnet/TeamPass#3721]
### Steps to reproduce
1. Set "Automatic login using http header credentials "  to "Yes" (in config file  enable_http_request_login = 1) 

### Expected behaviour
I can login to Teampass

### Actual behaviour
In the file "/includes/core/login.php" there is a $superGlobal('PHP_AUTH_USER', 'SERVER') code on lines 77,  81, 82 , 83 ,84, 86,  99 and 184, it should be $superGlobal->get('PHP_AUTH_USER', 'SERVER')

Line 89 must be modified to:
`<input type="text" id="login" class="form-control" value="', filter_var($username, FILTER_SANITIZE_STRING), '" readonly>';`

### Server configuration
**Operating system:** Linux 5.15.0-71-generic https://github.com/nilsteampassnet/TeamPass/issues/78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

**PHP version:**  8.1.2-1ubuntu2.11 

**Teampass version:** 3.0.6

**Comment by nilsteampassnet** [comment]
Not sure this option is working anymore in v3.
I didn't reworked it so it is ported directly from v2.

I will check based upon your comment.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
