### ISSUE TITLE
Default value of maintenance_job_frequency (60) prevent cron task from running

### ISSUE THREAD

**Issue by Seb-sti1** [nilsteampassnet/TeamPass#3725]
### Steps to reproduce
1. Install Teampass
2. Use default [maintenance_job_frequency](https://github.com/nilsteampassnet/TeamPass/blob/master/sources/scheduler.php#L54) param

### Expected behaviour
The cron should execute with the default config

### Actual behaviour
The default parameter prevents the execution of the cron task (because not between 0 and 59)

### Server configuration
**Operating system**: Debian 11

**Web server:** Apache/2.4.56

**Database:** 10.5.19-MariaDB

**PHP version:** 8.2.5

**Teampass version:** 3.0.9

## Logs of cron task

```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid value: it should be '*' or between 0 and 59. in /var/www/html/teampass/includes/libraries/GO/Traits/Interval.php:411
Stack trace:
#0 /var/www/html/teampass/includes/libraries/GO/Traits/Interval.php(386): GO\Job->validateCronRange()
#1 /var/www/html/teampass/includes/libraries/GO/Traits/Interval.php(50): GO\Job->validateCronSequence()
#2 /var/www/html/teampass/sources/scheduler.php(54): GO\Job->everyMinute()
#3 {main}
  thrown in /var/www/html/teampass/includes/libraries/GO/Traits/Interval.php on line 411
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
