### ISSUE TITLE
Reported critical vulnerability on huntr.dev

### ISSUE THREAD

**Issue by mnqazi** [nilsteampassnet/TeamPass#3741]
https://huntr.dev/bounties/2929faca-5822-4636-8f04-ca5e0001361f/

**Comment by SrivalliKusumba** [comment]
https://huntr.dev/bounties/4b86b56b-c51b-4be8-8ee4-6e385d1e9e8a/

**Comment by mnqazi** [comment]
@nilsteampassnet Any Update?
