### ISSUE TITLE
Problem with not Running Task on create_user_keys

### ISSUE THREAD

**Issue by domsivickas** [nilsteampassnet/TeamPass#3744]
Problem with Tasks not running add new user or generating new OTP
![image](https://github.com/nilsteampassnet/TeamPass/assets/74267968/da9aa47f-7805-4057-94cb-ea5920dcb16b)

We recently updated from 3.0.0.23 to 3.0.8

And having issues with not running tasks when generating new user OTP or when adding new user from LDAP
Steps to reproduce
1. Generating user new OTP for user
2  Task completed only step 0 and step 1 others not running
3. Open users shows task in progress but user not active 

another try with new user 

1. Added new user from LDAP
2. User added can log in to web UI see passwords
3. But sheduled task not running 

Expected behaviour
Task completed and Done

Actual behaviour
Task sheduled but not running

On Builded docker image

![image](https://github.com/nilsteampassnet/TeamPass/assets/74267968/cb574818-35d2-405d-91c1-6f9e04044ab1)

**Comment by MohanadAbugharbia** [comment]
I had the exact same issue and fixed it by running the command "crond -b" in the docker container and later adding it to the "teampass-docker-start.sh" script that is run everytime the container starts.

"crond-b" starts the cron daemon in the background so that the cron jobs actually get executed.

**Comment by domsivickas** [comment]
@MohanadAbugharbia  it helped for me, now tasks is running.

**Comment by nilsteampassnet** [comment]
PR has been merged

**Comment by aTm12** [comment]
i m having this  annoying thing   i have to wait 5 mins approx for each task to finish  knowinng the crontab is working  correctly 
do i have to inrcrease maximum ram  would that fix the problem ?! 
i read all the  pull request  concerning this  topic   my docker file is updated  and has all the solutions provided  still   having the issue 

>

**Comment by Arash9703** [comment]
i am having the same issue with my teampass installed in a LAMP stack server ! 
Anyone can help me please ,  if the command to reload the crontab is the same in apche2 server ! 
Thanks 
![Trouble adding users - Travail – Microsoft​ Edge](https://github.com/nilsteampassnet/TeamPass/assets/143269985/04ad36c1-39fd-40c0-9681-41bd05251022)

**Comment by geokh** [comment]
I`m facing issue with cron jobs are not running and constructing user stays 0% as i see there old tasks in progress and they never finishes
