### ISSUE TITLE
How to know encryption level?

### ISSUE THREAD

**Issue by edra10** [nilsteampassnet/TeamPass#3766]
### Steps to reproduce
1. Upgrade Teampass from version 2.1.27 to 3.0.0.23

### Question
We need to know what is or how to see the level of encryption that I am applying after the upgrade for the storage of information in the database.

I have also seen in the documentation that says that the credentials are stored encrypted in the database using the Blowfish algorithm through the PHPPasswordLib library, I would need to clarify this point as well.

Thank you in advance,
Regards.

**Comment by nilsteampassnet** [comment]
You can find this information in [Documentation](https://documentation.teampass.net/#/install/encryption).
if you have more questions, don't hesitate

**Comment by edra10** [comment]
Thank you very much for answering Nils, with the diagrams it is very clear the process of data encryption.
Regards.
