### ISSUE TITLE
There is no "Offline mode" listed in dropdown menu in 3.0.5 fresh installation.

### ISSUE THREAD

**Issue by groisersm** [nilsteampassnet/TeamPass#3774]
### Steps to reproduce
1. Enable "Offline mode" in options, specify passwords requarements.
2. Login to Teampass as normal user
3. Click on the <tree> menu button in password section

### Expected behaviour
Offline mode should appear in dropdown menu

### Actual behaviour
No Offline mode, last items are "Delete" and "Search" 
### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Server version: Apache/2.4.56
**Database:**
 MariaDB 10.10 database server
**PHP version:**
PHP 7.4.33
**Teampass version:** 
3.0.5
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please read documentation : https://documentation.teampass.net/#/features/export?id=generalities
