### ISSUE TITLE
Many errors in apache error log

### ISSUE THREAD

**Issue by NaumovAlexey** [nilsteampassnet/TeamPass#3775]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
List of tasks doesn't open. See error like 
![image](https://github.com/nilsteampassnet/TeamPass/assets/35455601/85003bf8-4404-4dc9-9c1d-cc5ec6873813)
When try to open bug report window information doesn't load to it automatically.
And many errors in apache log (in atachment)

### Server configuration
Operating system: Linux 5.15.0-69-generic https://github.com/nilsteampassnet/TeamPass/issues/76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64

Web server: Apache/2.4.52 (Ubuntu)

Database: 8.0.32-0ubuntu0.22.04.2

PHP version: 8.1.2-1ubuntu2.11

**Teampass version:** 3.0.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
in attachment
[error.log](https://github.com/nilsteampassnet/TeamPass/files/11956827/error.log)

**Comment by AKorolkovs** [comment]
3.0.9 have too much bugs inside. I reverted back to 3.0.8 as it is more stable

**Comment by AzerusBS** [comment]
Wrong dates on Tasks page
    sources\logs.datatables.php
    line 874 from `SELECT *` to `SELECT p.*`
    line 961 from `SELECT *` to `SELECT p.*`

Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in ... sources/logs.datatables.php(879): DB::query()
    sources/logs.datatables.php 
            line 874 from `SELECT *` to `SELECT p.*`
            or line 841 replace `'created_at'` with `'p.created_at'`

PHP Warning:  Undefined array key "mbstring" in ... includes/libraries/anti-xaa/src/voku/helper/UTF8.php on line 5582
    includes\libraries\anti-xss-master\src\voku\helper\AntiXSS.php
    add line to end of public function __construct()
        `UTF8::checkForSupport();`

These solve the error mentioned.

For me after upgrade from 3.0.8, Teampass only users can't edit items in personal folder after password or OTA reset (password and OTA is accepted).
For domain users OTA code is bad.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
