### ISSUE TITLE
Please teach me how to enable cronjob task

### ISSUE THREAD

**Issue by c1thunder** [nilsteampassnet/TeamPass#3778]
Hi all,

I am using wamp with Windows 10 Pro, I have one issue in my TP. The cronjob is not working. I tried to read the documentation but i have no idea how to perform it since im quite noob. Is there any guide or video that i can follow?

Thank you in advance

**Comment by nilsteampassnet** [comment]
@c1thunder 
You need to set up a new task using the windows tasks manager.

ChatGPT answers the text below and seems good.

To run a PHP script every minute on Windows 10 Pro, you can use the Task Scheduler utility built into Windows. Here's how you can configure it:
Open the Task Scheduler by typing "Task Scheduler" into the Windows search bar and selecting the corresponding app.
In the Task Scheduler window, click on "Create Task" in the right-hand Actions pane. This will open the Create Task dialog.
In the General tab of the Create Task dialog, give your task a name and provide a description (optional).
Under the Security options, ensure that "Run whether user is logged on or not" is selected. You may need to provide administrative credentials.
Switch to the Triggers tab and click on "New" to create a new trigger.
In the New Trigger dialog, configure the following settings:
- Begin the task: On a schedule
- Settings: Daily
- Recur every: 1 days
- Start: [Choose the current date and time or a future time]
- Check the "Repeat task every" box and set it to 1 minute.
- Indefinitely: [Check the box]
Click "OK" to save the trigger settings.
Switch to the Actions tab and click on "New" to create a new action.
In the New Action dialog, configure the following settings:
- Action: Start a program
- Program/script: Browse to the location of your PHP interpreter, usually located at `C:\path\to\php\php.exe`.
- Add arguments: [Specify the path to your PHP script, e.g., C:\path\to\script.php]
Click "OK" to save the action settings.
Review the other tabs if you need to make any further configurations (e.g., Conditions, Settings).
Click "OK" in the Create Task dialog to save your task.
The Task Scheduler will now execute your PHP script every minute as per the defined trigger. Make sure your PHP script is designed to handle running in a loop and exiting appropriately, as the Task Scheduler will start a new instance of the script with each trigger.
