### ISSUE TITLE
unable to recreate user after deletion

### ISSUE THREAD

**Issue by Jenlain74** [nilsteampassnet/TeamPass#3784]
### Steps to reproduce
1. fresh install
2. ldap configuration set on Active directory
3. create a new user
4. once the user created, the icon "Task in progress - User not active" is blinking and not disappearing 
5. delete the user
6. re-create the user with same user name
7. the user is not appearing in user list

### Expected behaviour
It should be possible to recreate a deleted user

### Actual behaviour
it's not possible to recreate a user after deletion.

### Server configuration
**Operating system**: AlmaLinux 8.8 (Sapphire Caracal)

**Web server:**  Apache

**Database:** 10.3.35-MariaDB

**PHP version:** 8.2.8

**Teampass version:** 3.0.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** fresh install
PLEASE attach to this issue the file [`/includes/config/tp.config.php`.]
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/12012210/tp.config.php.txt)

### Client configuration
**Browser:**
firefox

**Operating system:**
Windows 11

**Comment by digim-s15** [comment]
same here, button with + icon just missing for that kind of users

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by nbenaissa** [comment]
Hello,
I'm having the same kind of issue.

I can't delete an users : 
- The yellow icon is still popping
- Even tried first to disable the account then to delete it but it didn't work.
- I have no messages saying that the account has been deleted
- After clicking the delete button the first time, the account disappears from the list BUT if you search it, it's not deleted and still in encryption (yellow icon)

Someone can help ? 

Regards.
