### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by rafikberzi** [nilsteampassnet/TeamPass#3788]
### Steps to reproduce
1. upgrade from version 3.0.1 to to latest 3.10

### Expected behaviour
Tell us what should happen
When logged in as a user should display my password list..
### Actual behaviour
Tell us what happens instead
logs in but no listing, php error
Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/secure/public_html/pages/items.php:411\nStack trace:\n#0 /home/secure/public_html/index.php(953): include()\n#1 {main}\n  thrown in /home/secure/public_html/pages/items.php on line 411', referer: https://site.exemple.net/index.php
### Server configuration
**Operating system**:
ubuntu 22
**Web server:**
Apache
**Database:**
Mariadb
**PHP version:**
8.2
**Teampass version:** 
3.10
**Teampass configuration file:**
**<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "secure");
define("DB_PASSWD", "123-456");
define("DB_NAME", "secure");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define('SECUREFILE', 'teampass-seckey.txt');

define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/home/secure/saltkey");
define("IKEY", "");
define("SKEY", "");
define("AKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}
**
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/home/secure/public_html/TpM',
    'cpassman_url' => 'https://secure.exemple.com/TpM',
    'favicon' => 'https://secure.exemple.com/TpM/favicon.ico',
    'path_to_upload_folder' => '/home/secure/public_html/TpM/upload',
    'url_to_upload_folder' => 'https://secure.hotello.com/TpM/upload',
    'path_to_files_folder' => '/home/secure/public_html/TpM/files',
    'url_to_files_folder' => 'https://secure.exemple.com/TpM/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '1',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.10',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '1',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => 'https://mingus-software.com/wp-content/uploads/new-menu-mobile.png',
    'custom_login_text' => 'Bienvenue - Welcome - Bienvenida ',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_customfields;',
    'send_stats_time' => '1561240688',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '1',
    'personal_saltkey_cookie_duration' => '120',
    'email_smtp_server' => 'localhost',
    'email_smtp_auth' => '0',
    'email_auth_username' => 'admin',
    'email_auth_pwd' => 'LogInn2018!!',
    'email_port' => '',
    'email_security' => 'none',
    'email_server_url' => '',
    'email_from' => 'teampass-no-reply@hemailing.com',
    'email_from_name' => 'TeamPass Hotello',
    'pwd_maximum_length' => '60',
    'google_authentication' => '0',
    'delay_item_edition' => '10',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,pem,bin',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for Hotello',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '120',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/home/secure/public_html/TpM/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/Toronto',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '1',
    'bck_script_passkey' => 'def50200430884ca05745f9cc7383a20a495afd87d363bae620051d100f3c81b0e3a0f8187b7bb767d7d34e160b372ad7f2e95a1399e71e8966fffedc4c73bf07f481c2d0ac173d488931c8cb8742ae7b04f3546b9d108cdc7e52b83200365378e4155778b9b2390e244e825cb454e4dadc79b478813a4b23ad3c713ef5147218963f',
    'admin_2fa_required' => '1',
    'copy_to_clipboard_small_icons' => '1',
    'max_last_items' => '20',
    'enable_massive_move_delete' => '1',
    'password_overview_delay' => '10',
    'roles_allowed_to_print_select' => '[1]',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '0',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'can_create_root_folder' => '1',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'maximum_number_of_items_to_treat' => '300',
    'tasks_manager_refreshing_period' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '12',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'reload_cache_table_task' => 'daily;19:57',
    'rebuild_config_file' => '',
    'purge_temporary_files_task' => 'daily;18:58',
    'clean_orphan_objects_task' => '',
    'users_personal_folder_task' => 'daily;14:11',
    'upgrade_timestamp' => '1689097607',
    'rebuild_config_file_task' => 'daily;14:10',
);

### Client configuration
**Browser:**
chrome
**Operating system:**
Macos
#### Web server error log
```

Insert your webserver log here
[Tue Jul 11 14:08:46.811629 2023] [proxy_fcgi:error] [pid 1149353] [client 66.254.60.52:65095] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 1 in /home/secure/public_html/TpM/pages/tasks.php on line 189; PHP message: PHP Warning:  Undefined array key 1 in /home/secure/public_html/TpM/pages/tasks.php on line 207', referer: https://secure.hotello.com/TpM/index.php?page=statistics
[Tue Jul 11 14:09:00.493432 2023] [proxy_fcgi:error] [pid 1149163] [client 66.254.60.52:65109] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 1 in /home/secure/public_html/TpM/pages/tasks.php on line 189; PHP message: PHP Warning:  Undefined array key 1 in /home/secure/public_html/TpM/pages/tasks.php on line 207', referer: https://secure.hotello.com/TpM/index.php?page=users

#### Log from the web-browser developer console (CTRL + SHIFT + i)



Insert the log here and especially the answer of the query that failed.
csrfprotector.js:134 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at Object._init (csrfprotector.js:134:27)
    at csrfprotector_init (csrfprotector.js:162:8)
    at csrfprotector.js:345:2
index.php:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tom-nielk** [comment]
Same issue here with brand new installation.

Current version loaded 3.0.10
Server
Ubuntu 22.04.2 LTS

PHP version: 8.1.2-1ubuntu2.13
Memory limit: 128M
Memory usage: 562.23 KB
Maximum time execution: 30
Maximum file size upload: 2M

Server version: 5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1

[Wed Jul 12 10:50:52.135368 2023] [php:error] [pid 5834] [client X:X:X:X:52064] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/TeamPass/pages/items.php:411\nStack trace:\n#0 /var/www/html/TeamPass/index.php(953): include()\n#1 {main}\n  thrown in /var/www/html/TeamPass/pages/items.php on line 411, referer: https://XXX.XX/

**Comment by nilsteampassnet** [comment]
Rooooh so stupid 🥇 
I will fix this

**Comment by nilsteampassnet** [comment]
new commit providing the fix
