### ISSUE TITLE
Login not possible with 3.0.10.0

### ISSUE THREAD

**Issue by Nachtlichtermeer** [nilsteampassnet/TeamPass#3795]
### Steps to reproduce
1. try to login

### Expected behaviour
login should work

### Actual behaviour
"in progress" is shown and loading

### Server configuration
**Operating system**:
Ubuntu 22.04
**Web server:**
Apache

**Database:**
MySQL
**PHP version:**
8.1

**Teampass version:** 
3.0.10.0 commit 6f22a379a9bc004e0285797a1043a4c08fea6006
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
updated from 3.0.9 ee4074bc5b0f8c9553bcdf311693405035dcab65

### Client configuration
**Browser:**
114.0.2

**Operating system:**
Ubuntu 22.04

#### Web server error log
```
[Thu Jul 20 14:00:39.422575 2023] [php:error] [pid 676564] [client 172.20.1.71:38306] PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'process_type' at row 1 in /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/passwort.foo.de/htdocs/teampass/sources/identify.php(756): DB::insert()\n#7 /var/www/passwort.foo.de/htdocs/teampass/sources/identify.php(114): identifyUser()\n#8 {main}\n  thrown in /var/www/passwort.foo.de/htdocs/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://passwort.foo.de/index.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
User starts auth index.php:2088:25
Get 2FA Methods answer: index.php:2572:29
Object { agses: false, google: false, yubico: false, duo: false }
index.php:2573:29
Data submitted to identifyUser: index.php:2637:29
Object { login: "mmr", pw: "foo", duree_session: "600", screenHeight: 587, randomstring: "nBhpcnIM38", TimezoneOffset: -7200, client: "", user_2fa_selection: "" }
index.php:2638:29
Session existance check: index.php:2660:33
Object { status: true }
index.php:2661:33
XHRPOST
https://passwort.foo.de/sources/identify.php
```

The problem wasn't there after upgrade yesterday and it worked this morning.
strange...

**Comment by Nachtlichtermeer** [comment]
i found the column in table teampass_processes.
this morning i generated a new OTP for a user. maybe this is the cause

**Comment by Nachtlichtermeer** [comment]
``2023-07-20T12:40:38.858952Z       10 Query    SELECT visible_folders
            FROM teampass_cache_tree
            WHERE user_id=10000000
2023-07-20T12:40:38.859194Z       10 Query    INSERT INTO `teampass_processes` (`created_at`,`process_type`,`arguments`,`updated_at`,`finished_at`,`output`) VALUES (1689856838, 'user_build_cache_tree', '{\"user_id\":10000000}', '', '', '')``

``
mysql> INSERT INTO `teampass_processes` (`created_at`,`process_type`,`arguments`,`updated_at`,`finished_at`,`output`) VALUES (1689856838, 'user_build_cache_tree', '{\"user_id\":10000000}', '', '', '');
ERROR 1406 (22001): Data too long for column 'process_type' at row 1
``

**Comment by Nachtlichtermeer** [comment]
Fix:
``
mysql> ALTER TABLE teampass_processes MODIFY process_type varchar(30) NOT NULL;
``
please fix code

**Comment by NaumovAlexey** [comment]
> Fix: `mysql> ALTER TABLE teampass_processes MODIFY process_type varchar(30) NOT NULL;` please fix code

Yes. this works

**Comment by rafa-ga** [comment]
> Fix: `mysql> ALTER TABLE teampass_processes MODIFY process_type varchar(30) NOT NULL;` please fix code

Suffered the same problem. Can confirm it works, thank you!

**Comment by Nachtlichtermeer** [comment]
after upgrade to 496d48417eba7234615678b0f16cad61f22a5251 i had to alter the column again
please fix it in code

**Comment by Nachtlichtermeer** [comment]
tested with f4b7627f1ea9eb81cf82c19cc9653ba5da64a6dd
login actually works

thanks!! :)
