### ISSUE TITLE
Undefined constant "LDAP_OPT_X_TLS_REQUIRE_CERT"

### ISSUE THREAD

**Issue by necarnot** [nilsteampassnet/TeamPass#3800]
### Steps to reproduce
1. Use TP 3.0.10 with NO LPAP SUPPORT
2. Try to query a OTP for a user
3. Witness that the OTP is not usable (refused when used by the user), AND the following appears in the logs :

[Fri Jul 28 12:09:45.406397 2023] [php:error] [pid 37615] [client 10.32.7.6:38734] PHP Fatal error:  Uncaught Error: Undefined constant "LDAP_OPT_X_TLS_REQUIRE_CERT" in /var/www/html/TeamPass/sources/users.queries.php:2558\nSta
ck trace:\n#0 {main}\n  thrown in /var/www/html/TeamPass/sources/users.queries.php on line 2558, referer: https://example.com/index.php?page=users

No LDAP support is installed amongst the php packages, and no LDAP support is set up (obviously) in no TP setup files.

Though, when trying to ask for a new OTP, I see that /var/www/html/TeamPass/sources/users.queries.php is entering into the case "get_list_of_users_in_ldap" which sounds strange, as there's no LDAP involved.

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.
