### ISSUE TITLE
"User is not allowed" error when upgrade form 3.0.7 to 3.0.9

### ISSUE THREAD

**Issue by fdelprete** [nilsteampassnet/TeamPass#3802]
### Steps to reproduce
1. Try to upgrade to latest release 3.0.9 from a 3.07
2. Download the latest tarball (3.0.9)
3. Overwrite existing files
4. Try to run /install/upgrade.php from the web browser 

### Expected behaviour
After inserting admin credentials and pressing START button you can click the NEXT button

### Actual behaviour
After inserting admin credentials and pressing START button you receive an error "User is not allowed"

### Server configuration
**Operating system**: CentOS Linux 7 (Core)

**Web server:** Apache 2.4

**Database:** 5.5.68-MariaDB

**PHP version:** 7.4

**Teampass version:** 3.0.7

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/12207281/tp.config.txt)

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
No errors
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
"User is not allowed"
 
Insert the log here and especially the answer of the query that failed.
```

**Comment by fdelprete** [comment]
Workaround: I created a new "Administrator"user and using the new credentials I performed the upgrade process without any problem.

**Comment by nilsteampassnet** [comment]
That means that your previous admin user was not defined as "administrator".
Either check in list of users or run query
`select admin from teampass_users where login = 'admin';`

**Comment by fdelprete** [comment]
Thank you for your response.
But the admin field of the "Administrator" user is correctly set to 1.
In the past I did regular updgrades of TeamPass with that user.
Please find attached the SQL record of that user.

![admin_user_teampass](https://github.com/nilsteampassnet/TeamPass/assets/2984587/b240260b-e0bc-47f8-a3bb-f6e291b9a52b)

**Comment by nilsteampassnet** [comment]
I've checked the code.
THis message appears in 2 cases: 
* missing login or pwd
* pwd is not correct
Check if you are still using the correct BD

**Comment by fdelprete** [comment]
Thank you Nil for your support.
I double checked the password.
Anyway I correctly completed the upgrade process to 3.0.9 creating a new admin user and using these credentials.
Next upgrade I'll try to investigate more, but at the moment I close this issue.
