### ISSUE TITLE
 Difficulty logging into LDAP 3.0.10

### ISSUE THREAD

**Issue by henrriqueandrade** [nilsteampassnet/TeamPass#3811]
### Steps to reproduce
1 - I configure LDAP
2 - Perform the "Successfully authenticated user" configuration test
3 - I add the user as fit in the system
4 - I wait for the task to complete
5 - Log in with AD id and password as configured

### Expected behaviour
Successful login with AD user and password

### Actual behaviour
After entering login and password, it presents a "in progress" screen and becomes stagnant on this screen

### Server configuration
**Operating system**:
- DEBIAN 12
**Web server:**
Apache2 
**Database:**
MARIA DB
**PHP version:**
PHP 8.2.7
**Teampass version:** 
3.0.10
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
![image](https://github.com/nilsteampassnet/TeamPass/assets/139490726/545e95d7-8de7-4de1-9274-6207db4a560e)

**Comment by Peteraguy** [comment]
Server version: 5.5.5-10.5.19-MariaDB-0+deb11u2

I have the same issue in update from 3.0.0.23 I have tried two routes with the same result
3.0.0.23 -> 3.0.10
3.0.0.23 -> 3.0.9 (Successful LDAP login) -> 3.0.10 (LDAP login failed)
In all cases LDAP test from admin login was fine for account that failed to login direct

I do get a malformed json error in the browser

> Next error occurred
> SyntaxError: Unexpected end of JSON input
> 
> Raw answer from server:

 I have not had chance to dig into it so don't know a lot more

**Comment by henrriqueandrade** [comment]
In my case, it is a new installation already in version 3.0.10 and the administrator enters, the local users also enter, but the LDAP users do not enter.
I also use it in version 3.0.9 and it gave the same error so I came to 3.0.10

**Comment by nilsteampassnet** [comment]
@henrriqueandrade 
Would it be possible for you to contact me by email so that we can arrange a screen share ?

**Comment by henrriqueandrade** [comment]
@nilsteampassnet I will be sending an email to contact, please send me your email.
