### ISSUE TITLE
can't add an email to admin  user (fresh install) ...Error  is fields with mandatory information are missing

### ISSUE THREAD

**Issue by aTm12** [nilsteampassnet/TeamPass#3812]
fresh install on KVM,
i can create  users they take 10 mns to  finish  but cannot receive  a password  cz no  smtp configured and to configure smtp u need email on admin  account   and i am having this problem adding email  i am attaching a pic 
![image](https://github.com/nilsteampassnet/TeamPass/assets/28742865/21a6e614-af5f-4d5f-b2a5-abf6564c91d5)
![Screenshot from 2023-08-08 08-25-59](https://github.com/nilsteampassnet/TeamPass/assets/28742865/be729247-216a-4325-98bc-8b70f7adc1f1)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
