### ISSUE TITLE
ReferenceError: Can't find variable: fieldDomPurifierLoop

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#3817]
Version 3.0.9 and 3.0.10

I can't create a new user :(

![image](https://github.com/nilsteampassnet/TeamPass/assets/18729181/f4049543-db79-4eff-93bf-29ef7e1da70f)

**Comment by nilsteampassnet** [comment]
Let's assume you have correctly copied all files inside the Teampass folder, then it can only be anu issue with the browser cache.
Please either refresh browser cache (CTRL+F5) or use a Private tab to check

**Comment by michaldejmek** [comment]
Anonymous browser helped ..

Login is not working for the user :( There is an error in the log:

2023/08/10 15:05:19 [error] 556#556: *1975 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'process_type' at row 1 in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(360): MeekroDB->query()
#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()
#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()
#6 /var/www/html/teampass/sources/identify.php(746): DB::insert()
#7 /var/www/html/teampass/sources/identify.php(113): identifyUser()
#8 {main}
  thrown in /var/www/html/teampass/includes/" while reading response header from upstream, client: 192.168.1.1, server: _, request: "POST /sources/identify.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "teampass.domain.com", referrer: "https://teampass.domain.com/teampass/index.php"
