### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by javitrillo** [nilsteampassnet/TeamPass#3820]
Im working with the version TeamPass 3.0.7

I was trying to test the API and I get this error:
"PHP Fatal error:  Uncaught Error: Failed opening required '.../TeamPass/api/inc/../Controller/BaseController.php' (include_path='.:/usr/share/php') in .../TeamPass/api/inc/bootstrap.php:38\nStack trace:\n#0 .../TeamPass/api/index.php(31): require()\n#1 {main}\n  thrown in .../TeamPass/api/inc/bootstrap.php on line 38"

The problem is the file /api/inc/bootstrap.php has "_require API_ROOT_PATH . "/Controller/BaseController.php_";, but the file BaseController.php is in "/Controller/Api/"

After resolve this manually, when I try to get a Item Detail whit the endpoint "__/api/index.php/item/get?id=_4_" I got this error:

"PHP Fatal error:  Uncaught Exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) ORDER BY i.id ASC' at line 3 in /var/www/html/TeamPass/api/Model/Database.php:51\nStack trace:\n#0 /var/www/html/TeamPass/api/Model/ItemModel.php(49): Database->select()\n#1 /var/www/html/TeamPass/api/Controller/ItemController.php(218): ItemModel->getItems()\n#2 /var/www/html/TeamPass/api/inc/bootstrap.php(58): ItemController->getAction()\n#3 /var/www/html/TeamPass/api/index.php(89): itemAction()\n#4 {main}\n  thrown in /var/www/html/TeamPass/api/Model/Database.php on line 51"

**Comment by nilsteampassnet** [comment]
Correct!
I will check this

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
