### ISSUE TITLE
Tasks manager - Done - error / bad css formatting

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#3824]
version 3.0.10 

DataTables warning: table id=table-tasks_finished - Requested unknown parameter '5' for row 2, column 5. For more information about this error, please see http://datatables.net/tn/4

![image](https://github.com/nilsteampassnet/TeamPass/assets/18729181/423afed0-3702-4084-b0b9-a73a79267ef7)

![image](https://github.com/nilsteampassnet/TeamPass/assets/18729181/da247185-be2e-4cce-8b4e-edceb8f225ab)

**Comment by nilsteampassnet** [comment]
Can you please check in apache error log, there must be an error related to this message.
Thank you

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
