### ISSUE TITLE
user cannot log out

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#3825]
version 3.0.10

If the user clicks on the "logout" button, no action is taken.  Everything works fine under the "admin" user. 

No error is displayed in the server log.

**Comment by lpascualforner** [comment]
The same thing happened to me, and it was because of the language. It had "Spanish" set. It wouldn't let me change it either, so I did a manual update of the table: "update teampass_users set user_language = 'English' where login = 'your-login';".

**Comment by michaldejmek** [comment]
@lpascualforner  The problem is the same :(

**Comment by lpascualforner** [comment]
The solution is to install the latest version. I just installed it, and works fine.

**Comment by michaldejmek** [comment]
@nilsteampassnet  and @nilsteampassnet  - latest version from git and same problem.
