### ISSUE TITLE
Cannot add user roles to export password

### ISSUE THREAD

**Issue by smekalan** [nilsteampassnet/TeamPass#3834]
### Steps to reproduce
1. In options enable Export to PDF or CSV enabled
2. Try adding one of User role to field "Export allowed by these roles (multi-select)"
3. It won't save

### Expected behaviour
After adding user role which can export passwords to the field, it should save these settings.

### Actual behaviour
After adding user role which can export passwords, the changes are not saved and the field is blank

### Server configuration
**Operating system**: Debian GNU/Linux 12 (bookworm)

**Web server:** nginx/1.22.1

**Database:** 10.11.3-MariaDB-1-log

**PHP version:** 8.2.7

**Teampass version:** 3.0.10

**Teampass configuration file:** 
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/12408550/tp.config.txt)

Browser debug console:

ncaught TypeError: currentString.replace is not a function
    at fieldDomPurifierWithWarning (functions.js:537:39)
    at HTMLSelectElement.<anonymous> (index.php?page=options:3822:17)
    at HTMLDocument.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71515)
    at HTMLSelectElement.<anonymous> (jquery.min.js:2:72110)
    at Function.each (jquery.min.js:2:3003)
    at S.fn.init.each (jquery.min.js:2:1481)
    at S.fn.init.trigger (jquery.min.js:2:72086)
    at n.select (select2.full.min.js:2:33723)

Fresh Install

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 11

EDIT: Typo
EDIT2: added error from browser console

**Comment by smekalan** [comment]
This behavior is only present in the newest teampass 3.0.9. I had another instance of teampass running at the older version 3.0.7 and there aren't any issues. So I gues it  is only in the latest build.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by mickaelpiraud** [comment]
hello @nilsteampassnet 
How can i apply the fix?
Where is it located?
I did a sudo apt-get update, in cas it is done automatically, but it doesn't know how to set it up.

**Comment by mickaelpiraud** [comment]
I update 3.0.10 on top of 3.0.9 and everything works fine now :)
