### ISSUE TITLE
error user password and task is blocked

### ISSUE THREAD

**Issue by mickaelpiraud** [nilsteampassnet/TeamPass#3837]
Hello,
When creating a user, I cannot enter a password, and I do not receive one by email either.
A task is created but it remains blocked in progress.
@nilsteampassnet 

however the cron is running fine.

**Comment by mickaelpiraud** [comment]
version ubuntu 21.04 version teampass 3.0.10

**Comment by mfraigneau** [comment]
Had the same issue in 3.0.9, the time to send email was random. For some users it took 2 hours. The most I waited was like 6 or 7 days. I didn't manage to find what is the problem.

**Comment by mickaelpiraud** [comment]
It's so difficult, if it must waited 6-7 days to a production normaly.

**Comment by mickaelpiraud** [comment]
I just tested with 3.0.9, and there is no problem. everything works better

**Comment by mickaelpiraud** [comment]
Butin version 3.0.9 the tasks are working but no showing
DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by g0lgs** [comment]
> Butin version 3.0.9 the tasks are working but no showing DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I get that on 3.0.8 too and I see this in the Developer Tools Console

![Screenshot from 2023-08-30 14-33-38a](https://github.com/nilsteampassnet/TeamPass/assets/64634584/42246e78-323c-45ca-a1fc-ee3d88fe9ca3)

**Comment by nilsteampassnet** [comment]
Can you provide any apache log error please

**Comment by mickaelpiraud** [comment]
[Thu Aug 31 08:07:21.959345 2023] [php:warn] [pid 51250] [client 192.168.189.236:61781] PHP Warning:  Undefined array key "mbstring" in /var/www/html/teampass/includes/libraries/portable-utf8-master/src/voku/helper/UTF8.php on line 5582, referer: https://192.168.189.227/teampass/index.php?page=tasks
[Thu Aug 31 08:07:41.819883 2023] [php:error] [pid 51248] [client 192.168.189.236:61821] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/teampass/sources/logs.datatables.php(879): DB::query()\n#5 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://192.168.189.227/teampass/index.php?page=tasks

**Comment by mickaelpiraud** [comment]
Personally, I would like to stay in 3.0.9 because the tasks work, it's juste that it does not display, whereas in 3.0.10 the tasks do not execute but display.

**Comment by g0lgs** [comment]
Tasks executed for me on my test install of 3.0.10 (.40) just now - I created a new 'admin' user and they completed and I can login using the new account.

**Comment by mickaelpiraud** [comment]
I update 3.0.10 on top of 3.0.9 and everything works fine now :)
