### ISSUE TITLE
Error with Share item function

### ISSUE THREAD

**Issue by yong-sheng-03** [nilsteampassnet/TeamPass#3856]
### Steps to reproduce
1. Create an item 
2. Put in an email address in the Share item function
3. Click Perform

### Expected behaviour
The item is shared without an error message. 

### Actual behaviour
The following error message appears. However, the item is still shared to the email.
<img width="402" alt="image" src="https://github.com/nilsteampassnet/TeamPass/assets/143984786/0de169c5-a638-4300-b303-5d66bef5b0e7">

### Server configuration
**Operating system**: Ubuntu 20.04.6 LTS

**Web server:** 8.0.34-0ubuntu0.20.04.1

**Database:** MySQL

**PHP version:** 8.0.30

**Teampass version:** 3.0.10

**Teampass configuration file:** 
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/12556023/tp.config.txt)

**Updated from an older Teampass or fresh install:** fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

#### Web server error log
```
No error log
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
No error log
```

**Comment by nilsteampassnet** [comment]
Fixed with latest commit ;)

**Comment by yong-sheng-03** [comment]
Confirm issue fixed with commit 3.0.10.46. Thanks
