### ISSUE TITLE
When a password is searched the open website icon doesn't generate the link

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#3865]
### Steps to reproduce
1. Log into teampass
2. Type the password you are looking for in the search field and hit enter key
3. Click the "Open Website"  icon when you hover over the password.

### Expected behaviour
Website is opened up with the correct URL

### Actual behaviour
The link is set as undefined
hostname/teampass/undefined

but if I go  through my folder structure and find the same password the 'Open Website" button works it's only when you use the search box to look for a password that the URL is set to undefined.

### Server configuration
**Operating system**:
docker php-apache 8.1 image
**Web server:**
docker php-apache 8.1 image

**Database:**
mysql 8.0.33

**PHP version:**
8.1

**Teampass version:** 
3.0.10.49
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/12604829/tp.config.php.zip)

Updated from 2.1.27.33

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 11

### Logs
No errors
#### Web server error log
No errors
```
Insert your webserver log here
no errors but this is all it generates when i click search
10.89.0.18 - - [14/Sep/2023:14:41:34 +1000] "GET /teampass/sources/find.queries.php?type=search_for_items&limited=false&search=MyPassWord&start=0&length=10&key=4XrVc6R9JrsMN9JUZSvJgkE7pKXwsGCsx7U9bTG2GsGV9gnpnJ HTTP/1.1" 200 3159 "https://myhost/teampass/index.php?page=items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
`<tr class="list-item-row is-draggable ui-draggable ui-draggable-handle" id="list-item-row_1074" data-item-key="undefined" data-item-edition="1" data-item-id="1074" data-item-sk="0" data-item-expired="0" data-item-rights="70" data-item-display="1" data-item-open-edit="1" data-item-tree-id="40" data-is-search-result="1" data-label="Enterprise%20manager%2013c%20-%20sysman"><td class="list-item-description" style="width: 100%;"><i class="fas fa-ellipsis-v mr-2 dragndrop"></i><i class="undefined mr-1"></i><span class="list-item-clicktoshow pointer" data-item-id="1074" data-item-key="undefined"><span class="list-item-row-description">Enterprise manager 13c - sysman</span></span><span class="list-item-actions hidden"><span class="fa-stack fa-clickable pointer infotip list-item-clicktoedit mr-2" title="" data-original-title="Edit"><i class="fas fa-circle fa-stack-2x"></i><i class="fas fa-pen fa-stack-1x fa-inverse"></i></span><span class="fa-stack fa-clickable pointer infotip mr-2" title="" data-original-title="Open website"><a href="undefined" target="_blank" class="no-link"><i class="fas fa-circle fa-stack-2x"></i><i class="fas fa-link fa-stack-1x fa-inverse"></i></a></span><span class="fa-stack fa-clickable item-favourite pointer infotip mr-2" title="" data-item-id="1074" data-item-key="undefined" data-item-favourited="0" data-original-title="Favorite"><i class="fas fa-circle fa-stack-2x"></i><i class="far fa-star fa-stack-1x fa-inverse"></i></span></span><br><span class="text-secondary small font-italic pointer open-folder" data-tree-id="40" "="">[DBMS &gt; ACCOUNTS]</span></td></tr>`

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
