### ISSUE TITLE
DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by fabiorandazzo** [nilsteampassnet/TeamPass#3866]
### Steps to reproduce
1. Open Task Manager
2.
3.

### Expected behaviour
No error expected

### Actual behaviour
Browser popup with error: DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### Server configuration
Ubuntu Server: 22.04.3 LTS

Apache2: 2.4.52-1ubuntu4.6

MariaDB-Server: 1:10.6.12-0ubuntu0.22.04.1

PHP: 2:8.2+93+ubuntu22.04.1+deb.sury.org+2

TeamPass version: 3.0.9

**Teampass configuration file:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'http://170.1.6.217',
    'favicon' => 'http://170.1.6.217/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'http://170.1.6.217/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.9',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;s>    
    'send_stats_time' => '1692436540',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Rome',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'UbLEjJYL4em6QuN9BySRfeBr7kgn7dYuhZBZjf74',
    'admin_2fa_required' => '0',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '1',
    'upgrade_timestamp' => '1695028540',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '59',
    'user_keys_job_frequency' => '59',
    'items_statistics_job_frequency' => '59',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
);

### Client configuration
Browser: Chrome/Edge

OS: Windows 10

#### Web server error log
```
[Mon Sep 18 11:43:05.572346 2023] [php:error] [pid 784] [client X.X.X.X:53598] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
[Mon Sep 18 11:44:05.566682 2023] [php:error] [pid 785] [client X.X.X.X:53637] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
[Mon Sep 18 11:45:05.569828 2023] [php:error] [pid 1129] [client X.X.X.X:53677] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
[Mon Sep 18 11:46:05.549419 2023] [php:error] [pid 783] [client X.X.X.X:53715] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
[Mon Sep 18 11:47:05.563036 2023] [php:error] [pid 1136] [client X.X.X.X:53750] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X./index.php?page=tasks
[Mon Sep 18 11:48:05.664422 2023] [php:error] [pid 786] [client X.X.X.X:54764] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
[Mon Sep 18 11:49:05.574361 2023] [php:error] [pid 787] [client X:X:X:X:54856] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#4 /var/www/html/sources/logs.datatables.php(873): DB::query()\n#5 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://X.X.X.X/index.php?page=tasks
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
No response in the web-browser developer console
```

**Comment by aleks001** [comment]
Download the latest commit, I had the same issue it was fixed

**Comment by fabiorandazzo** [comment]
that works, thank you

**Comment by koznov** [comment]
In latest release (3.0.10.62) error still persists. Tasks are not working:
![image](https://github.com/nilsteampassnet/TeamPass/assets/16073136/18a36f1a-fe86-4b9f-9a06-b1543963b7b1)

**Comment by cgkelleher88** [comment]
Also getting the same error on a fresh installation of 3.0.10.67
![image](https://github.com/nilsteampassnet/TeamPass/assets/62486044/611d93fc-7752-478c-b5e6-595289742893)

**Comment by nilsteampassnet** [comment]
In the log I can see that MySQL complains about Column 'created_at' is ambiguous.
In the query, the table to use is clearly identified.
Can you please do a screenshot of table 'teampass_processes' structure in your database.
Thank you

**Comment by Seb-sti1** [comment]
With 3.0.9, same error

PHP error:
```
[Tue Oct 17 22:43:41.442592 2023] [php:error] [pid 16074] [client [ip]:[port]] PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()
#4 /var/www/teampass/sources/logs.datatables.php(873): DB::query()
#5 {main}\n  thrown in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://[url]/index.php?page=tasks
```

`teampass_processes` structure:
```
MariaDB [teampass]> DESCRIBE teampass_processes;
+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| increment_id   | int(12)     | NO   | PRI | NULL    | auto_increment |
| created_at     | varchar(50) | NO   |     | NULL    |                |
| updated_at     | varchar(50) | YES  |     | NULL    |                |
| finished_at    | varchar(50) | YES  |     | NULL    |                |
| process_id     | int(12)     | YES  |     | NULL    |                |
| process_type   | varchar(20) | NO   |     | NULL    |                |
| output         | text        | YES  |     | NULL    |                |
| arguments      | longtext    | NO   |     | NULL    |                |
| is_in_progress | tinyint(1)  | NO   |     | 0       |                |
+----------------+-------------+------+-----+---------+----------------+
```

Hope it helps

**Comment by fabiorandazzo** [comment]
> In the log I can see that MySQL complains about Column 'created_at' is ambiguous. In the query, the table to use is clearly identified. Can you please do a screenshot of table 'teampass_processes' structure in your database. Thank you

now i'm currently on 3.0.10.50
this is the output of the table "Teampass_processes":
`+--------------+------------+------------+------------+-------------+------------+-----------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------+
| increment_id | created_at | started_at | updated_at | finished_at | process_id | process_type          | output | arguments                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | is_in_progress | item_id |
+--------------+------------+------------+------------+-------------+------------+-----------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------+
|            2 | 1695991091 | 1695991142 | 1695991501 | 1695991501  |       NULL | create_user_keys      |        | {"new_user_id":10000000}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|            3 | 1695991202 | 1695991321 | 1695991323 | 1695991323  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello admin,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing password is expected next time using Teampass:\u003Cbr\u003E\u003Cbr\u003E\u003Cb\u003E2gM2sdTRaDqE34PrFqYz\u003C\/b\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}                                                                   |             -1 |    NULL |
|            4 | 1696842061 | 1696842061 | 1696842421 | 1696842421  |       NULL | create_user_keys      |        | {"new_user_id":10000000}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|            5 | 1696842121 | 1696842241 | 1696842243 | 1696842243  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello admin,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing password is expected next time using Teampass:\u003Cbr\u003E\u003Cbr\u003E\u003Cb\u003E8rbJ6hkWNvYFgv4RrPu3\u003C\/b\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}                                                                   |             -1 |    NULL |
|            6 | 1696842734 | 1696842781 | 1696843141 | 1696843141  |       NULL | create_user_keys      |        | {"new_user_id":10000001}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|            7 | 1696842793 | 1696843201 | 1696843561 | 1696843561  |       NULL | create_user_keys      |        | {"new_user_id":10000002}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|            8 | 1696842841 | 1696842961 | 1696842962 | 1696842962  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello Sviluppo,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing credentials are expected next time using Teampass:\u003Cul\u003E\u003Cli\u003Elogin: svil\u003C\/li\u003E\u003Cli\u003EPassword: _rbFRjOD4-GjYnEI\u003C\/li\u003E\u003C\/ul\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}         |             -1 |    NULL |
|            9 | 1696843261 | 1696843321 | 1696843322 | 1696843322  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello Sistemi,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing credentials are expected next time using Teampass:\u003Cul\u003E\u003Cli\u003Elogin: sis\u003C\/li\u003E\u003Cli\u003EPassword: $fSDfeU_ewQC7cTB\u003C\/li\u003E\u003C\/ul\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}           |             -1 |    NULL |
|           10 | 1696843382 | 1696843441 | 1696843441 | 1696843441  |       NULL | user_build_cache_tree |        | {"user_id":10000001}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |             -1 |    NULL |
|           11 | 1696844042 | 1696844101 | 1696844101 | 1696844101  |       NULL | user_build_cache_tree |        | {"user_id":10000002}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |             -1 |    NULL |
|           12 | 1697025847 | 1697025901 | 1697026261 | 1697026261  |       NULL | create_user_keys      |        | {"new_user_id":10000003}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|           13 | 1697025962 | 1697026321 | 1697026582 | 1697026582  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello user,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing credentials are expected next time using Teampass:\u003Cul\u003E\u003Cli\u003Elogin: user\u003C\/li\u003E\u003Cli\u003EPassword: VM5hpnu5-N09cnxT\u003C\/li\u003E\u003C\/ul\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}             |             -1 |    NULL |
|           14 | 1697027888 | 1697027941 | 1697028301 | 1697028301  |       NULL | create_user_keys      |        | {"new_user_id":10000003}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|           15 | 1697028001 | 1697028361 | 1697028622 | 1697028622  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello user,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing password is expected next time using Teampass:\u003Cbr\u003E\u003Cbr\u003E\u003Cb\u003EMNqDBrHAJP9LD9xUWA74\u003C\/b\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}                                                                    |             -1 |    NULL |
|           16 | 1697028474 | 1697028481 | 1697028841 | 1697028841  |       NULL | create_user_keys      |        | {"new_user_id":10000003}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|           17 | 1697028541 | 1697028841 | 1697029103 | 1697029103  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello user,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing password is expected next time using Teampass:\u003Cbr\u003E\u003Cbr\u003E\u003Cb\u003EzufA7CrC2sXHu2RQpdsn\u003C\/b\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}                                                           		   |             -1 |    NULL |
|           18 | 1697030016 | 1697030041 | 1697030041 | 1697030041  |       NULL | user_build_cache_tree |        | {"user_id":10000001}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |             -1 |    NULL |
|           20 | 1697787061 | 1697787361 | 1697787624 | 1697787624  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello an,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing credentials are expected next time using Teampass:\u003Cul\u003E\u003Cli\u003Elogin: are\u003C\/li\u003E\u003Cli\u003EPassword: jRClYHK&amp;#0OXn$2x\u003C\/li\u003E\u003C\/ul\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}            |             -1 |    NULL |
|           21 | 1697787714 | 1697787721 | 1697788055 | 1697788055  |       NULL | create_user_keys      |        | {"new_user_id":10000003}                                                                                                                                                                                                                                                                                                                                                                                                                                                               |             -1 |    NULL |
|           22 | 1697787781 | 1697788081 | 1697788342 | 1697788342  |       NULL | send_email            |        | {"subject":"TEAMPASS - Login credentials","receivers":"x.xxx@xxx.xx","body":"Hello user,\u003Cbr\u003E\u003Cbr\u003EThis is a generated email from Teampass passwords manager.\u003Cbr\u003E\u003Cbr\u003EFollowing password is expected next time using Teampass:\u003Cbr\u003E\u003Cbr\u003E\u003Cb\u003ECupHvWqbwfyH5RNf6WSA\u003C\/b\u003E\u003Cbr\u003E\u003Cbr\u003E\u003Cbr\u003ECheers","receiver_name":""}                                                                    |             -1 |    NULL |
+--------------+------------+------------+------------+-------------+------------+-----------------------+--------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------+`
the tasks work for a few minutes, then they stop working

**Comment by loutremaline** [comment]
I have the same error on version 3.0.9 too.

`[error] 16#16: *340 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Column 'created_at' in order clause is ambiguous in /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php:682

Stack trace:

#0 /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()
#4 /xxx/TeamPass-3.0.9/sources/logs.datatables.php(879): DB::query()
#5 {main}
  thrown in /xxx/TeamPass-3.0.9/includes/libraries/Database/Meekrodb/db.class.php on line 682" while reading response header from upstream, client: x.x.x.x, server: xxxx, request: "GET /TeamPass/sources/logs.datatables.php?action=tasks_in_progress&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5`

**Comment by michaldejmek** [comment]
@nilsteampassnet  I have the same error on version 3.1.1

[error] 2830#2830: *738 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $query in /var/www/html/teampass/sources/users.datatable.php on line 187; PHP message: PHP Fatal error:  Uncaught Error: Call to a member function filter() on null in /var/www/html/teampass/sources/users.datatable.php:187


![image](https://github.com/nilsteampassnet/TeamPass/assets/18729181/926ece73-e8fc-4c4b-bf1f-391cf803f650)

**Comment by Seb-sti1** [comment]
@loutremaline updating to a newer version solved this issue for me (see my previous message). This issue appears to have been fixed in [this commit](https://github.com/nilsteampassnet/TeamPass/commit/cc6abc76aa46ed4a27736c1d2f21e432a5d54e6f#diff-20610a22d705418cc1545553b9f79bf60a1d94352f9508d2fece4687bc66661a) which means that after version 3.0.10.0 this should be fine.
_Note: the version minor (fourth number in the version) doesn't exist until [August 30, 2023](https://github.com/nilsteampassnet/TeamPass/commit/319dd2bbc2ca59c1439eb300d2638e43bf3ba7a2) so i you have version "3.0.10" you can't be sure (unless you go into the source code)._

@fabiorandazzo To be honest, I don't understand how you have this issue in 3.0.10.50, but if you provide the Apache log I can try to look into it.

@michaldejmek I don't think that is quite the same issue, but there was still a [commit](https://github.com/nilsteampassnet/TeamPass/commit/c95f2a60b08684571ca6a469b61520accacc0502#diff-5d70f3159520f3c28d5aa84c1c6c0924273225ce505ea49cecede6b52ad559bf) modifying the part appearing to cause your issue, maybe updating will solve yours too.

**Comment by michaldejmek** [comment]
@nilsteampassnet and @Seb-sti1 I have the same error on version 3.1.1.26
