### ISSUE TITLE
SQL Error when loading new password

### ISSUE THREAD

**Issue by romulopires08** [nilsteampassnet/TeamPass#3890]
### Steps to reproduce
1. New Install on Ubuntu 22.04.2
2. Login as admin

### Expected behaviour
Edit new password for a user

### Actual behaviour
Folder does not load, stays on Loading Data...

### Server configuration
**Operating system**:
Ubuntu 22.04.2

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
8.1.2

**Teampass version:** 
3.0.10

#### Web server error log
[Thu Sep 28 11:18:11.866005 2023] [php:error] [pid 6760] [client 127.0.0.1:32904] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'teampass.teampass_processes' doesn't exist in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/html/teampass/sources/main.functions.php(4068): DB::insert()\n#7 /var/www/html/teampass/sources/main.queries.php(534): handleUserKeys()\n#8 /var/www/html/teampass/sources/main.queries.php(159): keyHandler()\n#9 /var/www/html/teampass/sources/main.queries.php(76): mainQuery()\n#10 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://localhost/teampass/index.php?page=users

**Comment by m10** [comment]
i had the same problem. The issue is that during install the query is not executed successfully and the re is no proper error checking.
There is a duplicate key `started_at` in the query. https://github.com/nilsteampassnet/TeamPass/blob/2f449a8b8251849be3f021d6396a442903616dac/install/install.queries.php#L1252C30-L1252C40
Executing the query manually without the second key declaration seems to help.

**Comment by romulopires08** [comment]
Thanks for the answer @m10.  In fact, the table teampass_processes was not created during the installation maybe because started_at was duplicated in install.queries.php, so I did myself as you suggested. However it does not work.

**Comment by romulopires08** [comment]
else if ($task === 'processes') {
                        $mysqli_result = mysqli_query(
                            $dbTmp,
                            "CREATE TABLE IF NOT EXISTS `" . $var['tbl_prefix'] . "processes` (
                            `increment_id` int(12) NOT NULL AUTO_INCREMENT,
                            `created_at` varchar(50) NOT NULL,
                            `started_at` varchar(50) DEFAULT NULL,
                            `updated_at` varchar(50) DEFAULT NULL,
                            `finished_at` varchar(50) DEFAULT NULL,
                            `process_id` int(12) DEFAULT NULL,
                            `process_type` varchar(100) NOT NULL,
                            `output` text DEFAULT NULL,
                            `arguments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`arguments`)),
                            `is_in_progress` tinyint(1) NOT NULL DEFAULT 0,
DELETE THIS LINE                            `started_at` varchar(50) NULL, 
                            `item_id` INT(12) NULL,
                            PRIMARY KEY (`increment_id`)
                            ) CHARSET=utf8;"
                        );
