### ISSUE TITLE
Errors in error.log while creating item on PHP 8.2

### ISSUE THREAD

**Issue by m10** [nilsteampassnet/TeamPass#3891]
### Steps to reproduce
1. create a new item
2. check apche error log

### Expected behaviour
no errors or warning

### Actual behaviour
errors appear

### Server configuration
**Operating system**:
Debian 12

**Web server:**
apache2 2.4.57-2

**Database:**
mariadb 1:10.11.3-1

**PHP version:**
8.2

**Teampass version:** 
3.0.10

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/12768690/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:**
Firefox 119 or Chrome 118
**Operating system:**
Windows 10
#### Web server error log

```
[Fri Sep 29 17:28:54.712258 2023] [proxy_fcgi:error] [pid 20078:tid 139858320271040] [client 192.168.2.10:56220] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "to_be_deleted_after_date" in /var/www/html/sources/items.queries.php on line 240; PHP message: PHP Warning:  Undefined array key "fa_icon" in /var/www/html/sources/items.queries.php on line 242; PHP message: PHP Warning:  Undefined variable $dataDestination in /var/www/html/sources/items.queries.php on line 730; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sources/items.queries.php on line 730', referer: https://domain.local/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
no log
```

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
