### ISSUE TITLE
[ERROR] ANSWER FROM SERVER IS EMPTY. during first installation

### ISSUE THREAD

**Issue by fabiorandazzo** [nilsteampassnet/TeamPass#3906]
### Steps to reproduce
1. Fresh installation procedure
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
"[ERROR] Answer from server is empty." popup while installation procedure
![image](https://github.com/nilsteampassnet/TeamPass/assets/145347578/dba7bbf6-b689-47c8-863b-79961a431b48)

### Server configuration
**Operating system**: Linux Ubuntu 22.04.3

**Web server:** Apache2: 2.4.52-1ubuntu4.6

**Database:** MariaDB-Server: 1:10.6.12-0ubuntu0.22.04.1

**PHP version:** PHP: 2:8.2+93+ubuntu22.04.1+deb.sury.org+2

**Teampass version:** 3.0.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Edge/Chrome

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

![image](https://github.com/nilsteampassnet/TeamPass/assets/145347578/21c605c8-4e1e-48b4-bf97-970327485626)

**Comment by xavierlaviolette** [comment]
Hi, ia have the same issue. did you solve the problem ?

**Comment by xavierlaviolette** [comment]
On the teampass errors logs : 
[Fri Nov 03 16:37:00.722731 2023] [php:error] [pid 1562] [client 212.194.197.1:59082] PHP Fatal error:  Uncaught Error: Undefined constant "DB_PASSWD" in /var/www/html/teampass/sources/main.functions.php:4350\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(60): loadClasses()\n#1 /var/www/html/teampass/install/install.queries.php(114): require_once('...')\n#2 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 4350, referer: https://teampass.xxx.fr/install/install.php

**Comment by ecbcompu** [comment]
Same error here
![Screenshot_20231106_155713_2](https://github.com/nilsteampassnet/TeamPass/assets/29432898/3a0b367e-f573-43b0-9f1d-665d12c646a2)

**Comment by ZoutMax** [comment]
Same issue.
![image](https://github.com/nilsteampassnet/TeamPass/assets/150600436/c93ecbb9-0e73-43f2-baf7-c0d8af25801f)

**Comment by infrario** [comment]
Olá @fabiorandazzo 

Você já conseguiu resolver este problema?
