### ISSUE TITLE
Question to import users into Teampass

### ISSUE THREAD

**Issue by mickaelpiraud** [nilsteampassnet/TeamPass#3909]
Hello @nilsteampassnet 
How are you?
I have a quick question.
is it possible to import users into teampass with a .csv or other format.

I wish you a good day

**Comment by nilsteampassnet** [comment]
@mickaelpiraud hi!
Yes but you need to enable this feature from the admin Options page.

**Comment by mickaelpiraud** [comment]
I tested the import .csv option but i don't see anything as admin in creating users for this.

**Comment by nilsteampassnet** [comment]
@mickaelpiraud 
Oops didn't read correctly your question.
No importing users with CSV file is currently not a feature.

**Comment by mickaelpiraud** [comment]
@nilsteampassnet  Okey, thank you for that clarification
