### ISSUE TITLE
Task in progress, user not active 

### ISSUE THREAD

**Issue by Arash9703** [nilsteampassnet/TeamPass#3910]
### Steps to reproduce
1. LDAP and users synchronisation done     
2. After configuring the cronjob correctly

### Expected behaviour
Users data (Folders /  items ) and account synchronisation should be done . 

### Actual behaviour
Account in construction & account is currently being encrypting  , No data to display 

### Server configuration
![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/b41f7de5-97b4-4549-a5d7-9697ec1ca49f)

**Updated from an older Teampass or fresh install:**
Fresh install  

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

Since this problem is similar to one that others are experiencing, I am posting the comments, details, and screenshots that I have posted in :  https://github.com/nilsteampassnet/TeamPass/issues/3747#issuecomment-1773946573

[> Same problem here (v3.0.10). https://github.com/nilsteampassnet/TeamPass/issues/3747#issuecomment-1773946573](https://github.com/nilsteampassnet/TeamPass/issues/3747#issuecomment-1780954071)

https://github.com/nilsteampassnet/TeamPass/issues/3747#issuecomment-1779039351

 I hope this will help others who are facing the same issue.

 Thanks for the help

**Comment by Arash9703** [comment]
> I had the same issue[3897](https://github.com/nilsteampassnet/TeamPass/issues/3897)  you  will see the latest commit fixed it for me and there are SQL queries and commands in the ticket that will help you out.

Thanks @jeffsuncorp, working on it hope i that will solve the problem .

**Comment by jeffsuncorp** [comment]
No worries. Thanks to @nilsteampassnet as he did the work though
