### ISSUE TITLE
Unable to Update 3.0.9 to 3.0.10

### ISSUE THREAD

**Issue by kcbieng** [nilsteampassnet/TeamPass#3923]
### Steps to reproduce
1. Install Teampass 3.0.9
2. Overwrite Teampass 3.0.10 into install folder
3. navigate to /install/upgrade.php
4. follow instructions until Database Updates
5. Loop 1 hangs indefinitely

### Expected behaviour
Database updates complete successfully

### Actual behaviour
500 Error from upgrade_operations.php. PHP Error caught in log. DB server begins reporting unauthenticated host.

### Server configuration
Fresh Docker Container

**Teampass version:**
3.0.9 (Currently Installed)
3.0.10 (Upgrade Target

**Teampass configuration [file:**]

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://teampass.domain.local',
    'favicon' => 'https://teampass.domain.local/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://teampass.domain.local/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.9',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1696432049',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'qkFmsafgFgapxUxvTesT26aWnWNnje3rAaXjkTsT',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1699024049',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
);

```
### Client configuration
**Browser:**
Brave/Chrome
**Operating system:**
Windows 11
#### Web server error log
```
2023-11-03 10:35:33 teampass-db-1            | 2023-11-03 15:35:33 238 [Warning] Aborted connection 238 to db: 'unconnected' user: 'unauthenticated' host: '172.22.0.3' (This connection closed normally without authentication)
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught MeekroDBException: Unable to connect to MySQL server! Error: MySQL server has gone away in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:236"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "Stack trace:"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#0 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(896): MeekroDB->get()"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#1 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(871): MeekroDB->queryHelper(Array, Array)"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#2 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(120): MeekroDB->query('SELECT id\r\n    ...')"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#3 /var/www/html/sources/main.functions.php(4205): DB::__callStatic('query', Array)"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#4 /var/www/html/install/upgrade_operations.php(147): purgeUnnecessaryKeys(true)"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "#5 {main}"
2023-11-03 10:35:33 teampass-teampass-web-1  | [03-Nov-2023 15:35:33] WARNING: [pool www] child 42 said into stderr: "  thrown in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php on line 236"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
{finish: '0', scriptname: 'upgrade_run_3.0.0.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.0_passwords.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.0_logs.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.0_fields.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.0_suggestions.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.0_files.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_run_3.0.php', parameter: 'user_id'}
upgrade.php:653 user_id
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_operations.php', parameter: '20230604_1'}
upgrade.php:653 20230604_1
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_operations.php', parameter: 'populateItemsTable_CreatedAt'}
upgrade.php:653 populateItemsTable_CreatedAt
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_operations.php', parameter: 'populateItemsTable_UpdatedAt'}
upgrade.php:653 populateItemsTable_UpdatedAt
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_operations.php', parameter: 'populateItemsTable_DeletedAt'}
upgrade.php:653 populateItemsTable_DeletedAt
upgrade.php:654 [{…}]
upgrade.php:280 {finish: '0', scriptname: 'upgrade_operations.php', parameter: '20231017_1'}
jquery.min.js:2 
       
        
       POST https://teampass.domain.local/install/upgrade_operations.php 500 (Internal Server Error)
```

**Comment by kcbieng** [comment]
upgrade_operations.php line 142
    } elseif ($post_operation === '20231017_1') {
            // ---->
            // OPERATION - 20231017_1 - remove all existing keys
            // if item is personal and user is not owner

            purgeUnnecessaryKeys(true);
    }

main.functions.php line 4199
function purgeUnnecessaryKeys(bool $allUsers = true, int $user_id=0)
{
    if ($allUsers === true) {
        // Load class DB
        loadClasses('DB');

        $users = DB::query(
            'SELECT id
            FROM ' . prefixTable('users') . '
            WHERE id NOT IN ('.OTV_USER_ID.', '.TP_USER_ID.', '.SSH_USER_ID.', '.API_USER_ID.')
            ORDER BY login ASC'
        );
        foreach ($users as $user) {
            purgeUnnecessaryKeysForUser((int) $user['id']);
        }
    } else {
        purgeUnnecessaryKeysForUser((int) $user_id);
    }
}

/**
 * Delete unnecessary keys for personal items
 *
 * @param integer $user_id
 * @return void
 */
function purgeUnnecessaryKeysForUser(int $user_id=0)
{
    if ($user_id === 0) {
        return;
    }

    // Load class DB
    loadClasses('DB');

    $personalItems = DB::queryFirstColumn(
        'SELECT id
        FROM ' . prefixTable('items') . ' AS i
        INNER JOIN ' . prefixTable('log_items') . ' AS li ON li.id_item = i.id
        WHERE i.perso = 1 AND li.action = "at_creation" AND li.id_user IN (%i, '.TP_USER_ID.')',
        $user_id
    );
    if (count($personalItems) > 0) {
        // Item keys
        DB::delete(
            prefixTable('sharekeys_items'),
            'object_id IN %li AND user_id NOT IN (%i, '.TP_USER_ID.')',
            $personalItems,
            $user_id
        );
        // Files keys
        DB::delete(
            prefixTable('sharekeys_files'),
            'object_id IN %li AND user_id NOT IN (%i, '.TP_USER_ID.')',
            $personalItems,
            $user_id
        );
        // Fields keys
        DB::delete(
            prefixTable('sharekeys_fields'),
            'object_id IN %li AND user_id NOT IN (%i, '.TP_USER_ID.')',
            $personalItems,
            $user_id
        );
        // Logs keys
        DB::delete(
            prefixTable('sharekeys_logs'),
            'object_id IN %li AND user_id NOT IN (%i, '.TP_USER_ID.')',
            $personalItems,
            $user_id
        );
    }
}

**Comment by Nachtlichtermeer** [comment]
same here when upgrade from commit 7e50cd15fd267eb5cd3165b396526fafd27c4d10 to 429b093c75191463d0888a46ecf53d038dc03612

**Comment by rafa-ga** [comment]
Same problem when trying to upgrade from 3.0.10.81

**Comment by nilsteampassnet** [comment]
Finally, I could reproduce
I've done a first change in latest commit.

**Comment by rafa-ga** [comment]
> Finally, I could reproduce I've done a first change in latest commit.

Thanks Nils! That step now works but unfortunately the one about the SaltKey raises errors.
![SalKey error](https://github.com/nilsteampassnet/TeamPass/assets/41051597/dd74b8d2-1011-41a6-8de0-882fa9c37f62)

Regards.

**Comment by nilsteampassnet** [comment]
@rafa-ga 
Well my fault.
SHould be ok now

**Comment by Nachtlichtermeer** [comment]
problem is still there:
```[Tue Nov 14 08:55:54.093880 2023] [php:error] [pid 662] [client 172.19.11.10:55042] PHP Fatal error:  Uncaught MeekroDBException: Unable to connect to MySQL server! Error: MySQL server has gone away in /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:236
Stack trace:
#0 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(803): MeekroDB->get()
#1 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(607): MeekroDB->escape()
#2 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(793): MeekroDB->{closure}()
#3 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(891): MeekroDB->parse()
#4 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(871): MeekroDB->queryHelper()
#5 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(980): MeekroDB->query()
#6 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(120): MeekroDB->queryFirstRow()
#7 /var/www/passwort-dev.foo.de/htdocs/teampass/sources/core.php(123): DB::__callStatic()
#8 /var/www/passwort-dev.foo.de/htdocs/teampass/index.php(105): require_once(...)
#9 {main}
  thrown in /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 236```

![grafik](https://github.com/nilsteampassnet/TeamPass/assets/67371873/7175ef01-4de9-4e27-96b9-c4dbd0d94511)

**Comment by rafa-ga** [comment]
Yep, now I'm stuck in the "Database updates" step as Nachtlichtermeer comments.

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer 
Before the stack trace you should have the error it self.
Can you please share it also?

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer @rafa-ga 
Ok working on it

**Comment by Nachtlichtermeer** [comment]
very strange, in the second try there is no error in the log but it stucks in the browser at
"Performing operation 20230604_1 - Loop #1 is now running ..." too

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer 
Yes this why I didn't identified yesterday.
I could rerproduce and find the cause (I believe)
I pushed a new commit just now.

**Comment by Nachtlichtermeer** [comment]
ah, shit, the update works but after open teampass i get a white page:

`==> /var/www/passwort-dev.foo.de/logs/error.log <==
[Tue Nov 14 09:23:09.704994 2023] [php:error] [pid 828196] [client 172.20.1.71:53108] PHP Fatal error:  Uncaught MeekroDBException: Unable to connect to MySQL server! Error: MySQL server has gone away in /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:236\nStack trace:\n#0 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(803): MeekroDB->get()\n#1 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(607): MeekroDB->escape()\n#2 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(793): MeekroDB->{closure}()\n#3 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(891): MeekroDB->parse()\n#4 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(871): MeekroDB->queryHelper()\n#5 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(980): MeekroDB->query()\n#6 /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(120): MeekroDB->queryFirstRow()\n#7 /var/www/passwort-dev.foo.de/htdocs/teampass/sources/core.php(123): DB::__callStatic()\n#8 /var/www/passwort-dev.foo.de/htdocs/teampass/index.php(105): require_once('...')\n#9 {main}\n  thrown in /var/www/passwort-dev.foo.de/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 236`

**Comment by rafa-ga** [comment]
> @Nachtlichtermeer Yes this why I didn't identified yesterday. I could rerproduce and find the cause (I believe) I pushed a new commit just now.

Different error this time:

![2023-11-14 09_25_14-TeamPass Upgrade y 5 páginas más - Trabajo_ Microsoft​ Edge](https://github.com/nilsteampassnet/TeamPass/assets/41051597/3dc868d5-8eb6-4375-8dc3-334ee33f8732)

**Comment by nilsteampassnet** [comment]
I need the error from Apache please

**Comment by rafa-ga** [comment]
> I need the error from Apache please

Yeah, right!

`[php:error] [pid 110468] [client 10.22.62.23:55127] PHP Parse error:  Unmatched '}' in /var/www/html/teampass/install/upgrade_run_3.0.0.php on line 897, referer: https://10.22.0.165/install/upgrade.php`

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer 
Still can't find the reason ... working on it

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer 
Can you please do the next
In file `includes/config/settings.php`, replace
```
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
```
by
```
define("DB_SSL", false);
```
Please tell me if it works

**Comment by rafa-ga** [comment]
> @Nachtlichtermeer Can you please do the next In file `includes/config/settings.php`, replace
> 
> ```
> define("DB_SSL", array(
>     "key" => "",
>     "cert" => "",
>     "ca_cert" => "",
>     "ca_path" => "",
>     "cipher" => ""
> ));
> ```
> 
> by
> 
> ```
> define("DB_SSL", false);
> ```
> 
> Please tell me if it works

Didn't see it, I'm going to try it now.

Meanwhile I tried to update this morning. I attach the logs.

[teampass_update_apache_error_logs.txt](https://github.com/nilsteampassnet/TeamPass/files/13361747/teampass_update_apache_error_logs.txt)

Kind regards.

**Comment by rafa-ga** [comment]
With the modification of _settings.php_ I only get the following error al the end of the process:

`[php:error] [pid 1662] [client 10.22.62.23:53657] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'v.intitule' in 'where clause' in /var/www/html/teampass/install/upgrade_operations.php:409\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_operations.php(409): mysqli->query()\n#1 /var/www/html/teampass/install/upgrade_ajax.php(1194): installHandleFoldersCategories()\n#2 {main}\n  thrown in /var/www/html/teampass/install/upgrade_operations.php on line 409, referer: https://10.22.0.165/install/upgrade.php`

**Comment by Nachtlichtermeer** [comment]
> @Nachtlichtermeer Can you please do the next In file `includes/config/settings.php`, replace
> 
> ```
> define("DB_SSL", array(
>     "key" => "",
>     "cert" => "",
>     "ca_cert" => "",
>     "ca_path" => "",
>     "cipher" => ""
> ));
> ```
> 
> by
> 
> ```
> define("DB_SSL", false);
> ```
> 
> Please tell me if it works

for me it works. I'm now able to login.

I'll try the upgrade-process with this change...

**Comment by Nachtlichtermeer** [comment]
After seeing new commits i've tested the update from commit 7e50cd15fd267eb5cd3165b396526fafd27c4d10
to now 8a2972a25586d1c469648e878cc2648764cc2fef without manual changes: succesfully!

**Comment by Nachtlichtermeer** [comment]
i'll test the initial problem with the unvisible passwords...

**Comment by nilsteampassnet** [comment]
Thank you all for your help and feedback in solving this issue.

Note: last error is now fixed ;)

**Comment by rafa-ga** [comment]
Sorry to say that but I got a new error in the last step.

`[php:error] [pid 2971] [client 10.22.62.23:56529] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"{"categories":[],"complexity":{"value":"0","text":"Weak"},"visibilityRoles":...' at line 1 in /var/www/html/teampass/install/upgrade_operations.php:423\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_operations.php(423): mysqli->query()\n#1 /var/www/html/teampass/install/upgrade_ajax.php(1194): installHandleFoldersCategories()\n#2 {main}\n  thrown in /var/www/html/teampass/install/upgrade_operations.php on line 423, referer: https://10.22.0.165/install/upgrade.php`

I tried the update with the settings.php not modified. Should I change it as you mentioned before?

Thank you Nils!

**Comment by Nachtlichtermeer** [comment]
Tested with latest commit fd9d0db2f48945379657b400bef811f67a1b9cde
i can see entries of other users but not the password. after new login i can see this password

**Comment by nilsteampassnet** [comment]
@rafa-ga 
No not needed, here it is a SQL query error (in its syntax).
I'm curious to get your query.
Can you please open file `install/upgrade_operations.php`,
and find
```
        // now save in DB
        $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
            FROM ' . $pre . 'nested_tree
            WHERE id = '.$folder
        );
```
and replace by
```
        // now save in DB
        echo "DEBUG SQL: ".json_encode($arr_data)." DEBUG END";
        $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
            FROM ' . $pre . 'nested_tree
            WHERE id = '.$folder
        );
```
You should have the same error but an output, can you share it please?

**Comment by Nachtlichtermeer** [comment]
after upgrading to latest commit i cannot add new users from ldap. it stucks at 'Tasks in progress - User not active'.

**Comment by rafa-ga** [comment]
> @rafa-ga No not needed, here it is a SQL query error (in its syntax). I'm curious to get your query. Can you please open file `install/upgrade_operations.php`, and find
> 
> ```
>         // now save in DB
>         $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
>             FROM ' . $pre . 'nested_tree
>             WHERE id = '.$folder
>         );
> ```
> 
> and replace by
> 
> ```
>         // now save in DB
>         echo "DEBUG SQL: ".json_encode($arr_data)." DEBUG END";
>         $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
>             FROM ' . $pre . 'nested_tree
>             WHERE id = '.$folder
>         );
> ```
> 
> You should have the same error but an output, can you share it please?

The error log after the modification:

`[Wed Nov 15 11:13:29.094981 2023] [php:error] [pid 16202] [client 10.22.62.23:57556] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"{"categories":[],"complexity":{"value":"0","text":"Weak"},"visibilityRoles":...' at line 1 in /var/www/html/teampass/install/upgrade_operations.php:424\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_operations.php(424): mysqli->query()\n#1 /var/www/html/teampass/install/upgrade_ajax.php(1194): installHandleFoldersCategories()\n#2 {main}\n  thrown in /var/www/html/teampass/install/upgrade_operations.php on line 424, referer: https://10.22.0.165/install/upgrade.php`

![2023-11-15 11_16_14-CiCuSALTO03 - 10 22 24 36 - Conexión a Escritorio remoto](https://github.com/nilsteampassnet/TeamPass/assets/41051597/1c3077d6-2dde-4bca-a8b5-44983f0a3ed1)

**Comment by nilsteampassnet** [comment]
@Nachtlichtermeer 
Correct, just pushed a new commit

@rafa-ga 
Thank you but the output of the echo will not be inside the Apache logs but in the browser (either on the screen or in the webconsole

**Comment by rafa-ga** [comment]
> @Nachtlichtermeer Correct, just pushed a new commit
> 
> @rafa-ga Thank you but the output of the echo will not be inside the Apache logs but in the browser (either on the screen or in the webconsole

Ooops sorry. I didn't get any message in the browser but I attach de console log:

[10.22.0.165-1700044330113.log](https://github.com/nilsteampassnet/TeamPass/files/13363393/10.22.0.165-1700044330113.log)

**Comment by whosht** [comment]
> @rafa-ga No not needed, here it is a SQL query error (in its syntax). I'm curious to get your query. Can you please open file `install/upgrade_operations.php`, and find
> 
> ```
>         // now save in DB
>         $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
>             FROM ' . $pre . 'nested_tree
>             WHERE id = '.$folder
>         );
> ```
> 
> and replace by
> 
> ```
>         // now save in DB
>         echo "DEBUG SQL: ".json_encode($arr_data)." DEBUG END";
>         $mysqli2->query('UPDATE categories = "'.json_encode($arr_data).'"
>             FROM ' . $pre . 'nested_tree
>             WHERE id = '.$folder
>         );
> ```
> 
> You should have the same error but an output, can you share it please?

Copy & Paste error? I don't know much about sql but reading the syntax of UPDATE I would guess the statement is wrong. The table name shouldn't after FROM but as first parameter of UPDATE.

**Comment by nilsteampassnet** [comment]
@whosht 
Roooh you are right ... don't know what I did there.
This is the power of pair review, thank you :+1:

**Comment by rafa-ga** [comment]
Good morning. Just to inform, with the latest commit (.144) in the DB updates step I get the following error in Apache:

`[Thu Nov 16 09:29:28.216320 2023] [php:error] [pid 1460] [client 10.22.24.36:11490] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'categories":[],"complexity":{"value":"0","text":"Weak"},"visibilityRoles":"Ce...' at line 1 in /var/www/html/teampass/install/upgrade_operations.php:421\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_operations.php(421): mysqli->query()\n#1 /var/www/html/teampass/install/upgrade_ajax.php(1194): installHandleFoldersCategories()\n#2 {main}\n  thrown in /var/www/html/teampass/install/upgrade_operations.php on line 421, referer: https://10.22.0.165/install/upgrade.php`

Regards.

**Comment by nilsteampassnet** [comment]
@rafa-ga 
I did a change

**Comment by rafa-ga** [comment]
Same step, different error:

`[Thu Nov 16 10:01:46.231790 2023] [php:error] [pid 1149] [client 10.22.24.36:11911] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'teampass.teampass_' doesn't exist in /var/www/html/teampass/install/upgrade_operations.php:421\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_operations.php(421): mysqli->query()\n#1 /var/www/html/teampass/install/upgrade_ajax.php(1194): installHandleFoldersCategories()\n#2 {main}\n  thrown in /var/www/html/teampass/install/upgrade_operations.php on line 421, referer: https://10.22.0.165/install/upgrade.php`

.146

**Comment by nilsteampassnet** [comment]
@rafa-ga 
Shame on me.
Doing things too fast ...

**Comment by nilsteampassnet** [comment]
> Passwords are still only visible for other users after they login again.
I don't understand this.
Can you please provide a scenario?

> And sometimes edited entries are moved to personal folder.
Hum ... Very surprised as upgrade process doesn't have any query to change item folder.
So in other words, an item doesn't change folder during upgrade process.

**Comment by Nachtlichtermeer** [comment]
i'll look next week for errors in log.

the edited items are not moved while updating. they are moved when i edit an existing extry
and save them. Sometimes they are moved to my personal folder.

**Comment by rafa-ga** [comment]
Good morning,

After the last update I didn't get the issues we were talking before but now the language is half english half spanish (I had this last one configured).

I've tried to change to english, reboot, change to spanish, reboot and nothing changed.

Kind regards, have a nice day.

**Comment by Nachtlichtermeer** [comment]
> after upgrading to latest commit i cannot add new users from ldap. it stucks at 'Tasks in progress - User not active'.

that's gone away after upgrading to latest commit
for me the ticket could be closed. thank you!!

**Comment by kcbieng** [comment]
Same. I've updated from 3.0.9.

**Comment by e-door-ch** [comment]
Hi, doing a clean install with last version (of today), all steps works but when I reach Preparing database, I get :

mod_fcgid: stderr: PHP Fatal error: Uncaught mysqli_sql_exception: Table 'lopakonet_kbox.teampass_processes_tasks' doesn't exist in /home/httpd/vhosts/domain.tld/install/install.queries.php:1292, referer: https://domain.tld/install/install.php

mod_fcgid: stderr: Stack trace:, referer: https://domain.tld/install/install.php

mod_fcgid: stderr: #0 /home/httpd/vhosts/domain.tld/install/install.queries.php(1292): mysqli_query(Object(mysqli), 'ALTER TABLE `te...'), referer: https://domain.tld/install/install.php

mod_fcgid: stderr: #1 {main}, referer: https://domain.tld/install/install.php

mod_fcgid: stderr: thrown in /home/httpd/vhosts/domain.tld/install/install.queries.php on line 1292, referer: https://domain.tld/install/install.php
