### ISSUE TITLE
Installing fresh 3.0.10 won't work

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3926]
Creating complete new installation (erased all installations and cleared database)
On Step 2:
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    parseJSON jQuery
    doGetJson https://example.com/install/install.js:288
    jQuery 2
    doGetJson https://example.com/install/install.js:281
    checkPage https://example.com/install/install.js:149
    onclick https://example.com/install/install.php:1
```
Devconsole shows at request:
```
POST /install/install.queries.php HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: de-DE,en;q=0.8,de;q=0.5,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Content-Length: 407
Origin: https://example.com
DNT: 1
Connection: keep-alive
Referer: https://example.com/install/install.php
Cookie: teampass_session=sdhfgsfhgsdfhg
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```
and the answer is:
```
Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.1.0". 
```
On the host is php 8.0, no newer version available (rhel-8)

**Comment by nilsteampassnet** [comment]
Related to php version.
I have downgraded the libraries to fit php 7.4 but this generates some regressions in output (messages to user).
You can use latest commit.
I will very soon only be able to maintain the code on PHP 8.2 branch

**Comment by useronkel** [comment]
Now it works, 'til it comes to the database creation
The following error appears on index 3
```
[{"error" : "BLOB, TEXT, GEOMETRY or JSON column \"url\" can\"t have a default value", "index" : "3", "multiple" : "true", "table" : "cache"}]
```
The error seems to be at line 911 of install.queries.php:
```
`url` text NOT NULL DEFAULT '0',
```

Deleting the "DEFAULT '0'" works as expected :-)

**Comment by useronkel** [comment]
On Step #6 of Install (Finalization):
JSON-Error and $filename_seckey can't be renamed.
Investigating code shows on line 1371:
```
echo '[{"error" : "File `$filename_seckey` already exists and cannot be renamed
```
The backticks are wrong, so you don't see the value of $filename_seckey, only the string $filename_seckey.
Replacing the backticks with:
```
echo '[{"error" : "File '.$filename_seckey.' already exists and cannot be renamed
```
shows that the string only consists of the secure path, constant SECUREFILE is empty.
Replacing
```
$filename_seckey = $securePath . '/' . SECUREFILE;
```
with:
```
$filesecure=generateRandomKey();
define('SECUREFILE', $filesecure);
$filename_seckey = $securePath . '/' . $filesecure;
```
works fine and the configuration goes ahead and all configs are written.
This is a dirty workaround, I know :-)
