### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: htmlspecialchars_decode()

### ISSUE THREAD

**Issue by AT-SGAI-CSIC** [nilsteampassnet/TeamPass#3952]
### Steps to reproduce
1. Edit a item
2. Save a item

### Expected behaviour
 Edit a item and save the item

### Actual behaviour
After update to version 3.0.10 when I try to edit a item and save it I have this message and the edition doesn't work:
![imagen](https://github.com/nilsteampassnet/TeamPass/assets/139878963/6c9b5ef6-bc98-4bb9-9192-0bb22b1658b8)

### Server configuration
**Operating system**: AlmaLinux release 8.9 (Midnight Oncilla)

**Web server:** Apache/2.4.37 (AlmaLinux)

**Database:** 10.10.7-MariaDB

**PHP version:** PHP 8.2.13

**Teampass version:** 3.0.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Updated from 3.0.9

### Client configuration
**Browser:** Firefox 119.0.1

**Operating system:**

#### Web server error log
```
 PHP Fatal error:  Uncaught TypeError: htmlspecialchars_decode(): Argument #1 ($string) must be of type string, null given in /var/www/html/TeamPass/sources/items.queries.php:865
Stack trace:
#0 /var/www/html/TeamPass/sources/items.queries.php(865): htmlspecialchars_decode()
#1 {main}
  thrown in /var/www/html/TeamPass/sources/items.queries.php on line 865
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
```

**Comment by AT-SGAI-CSIC** [comment]
Upgrade from 3.0.9  to 3.10.0 doesn't correct the error

**Comment by Roadster850** [comment]
I'm having the same issue, I thought I was good to go with the new server until I tried to enter a new item.
Have you found a fix?

**Comment by Roadster850** [comment]
Sorry, I found the solution: https://github.com/nilsteampassnet/TeamPass/issues/3978

**Comment by AT-SGAI-CSIC** [comment]
It's working, thank you very much.
