### ISSUE TITLE
Upgrade 3.0.9 to 3.1.0 JSON error

### ISSUE THREAD

**Issue by Blubmann1337** [nilsteampassnet/TeamPass#3972]
Hi there I try to upgrade TP 3.0.9 to 3.1.0. I enter the admin user and password in upgrade process but it does not work. I got following error in explorer console:

Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

In apache log i got the following error:
[Fri Dec 08 13:22:31.933335 2023] [php:error] [pid 31487] [client 192.168.65.253:63565] PHP Fatal error:  Uncaught Error: Class "TeampassClasses\\SuperGlobal\\SuperGlobal" not found in /var/www/teampass/install/upgrade_ajax.php:33\nStack trace:\n#0 {main}\n  thrown in /var/www/teampass/install/upgrade_ajax.php on line 33, referer: https://xy.com/teampass/install/upgrade.php

Same problem from verison 3.0.9. to 3.0.10

I using PHP 8.2.13, Debian 11.8, MariaDB 10.5.21 and Apache 2.4.56

**Comment by nilsteampassnet** [comment]
@Blubmann1337 
Hum, I don't really understand why you get this error.
Class SUperGlobal is loaded at line 32 and files are inside the project.
I can't reproduce which doesn't ease to understand and debug.
Nevertheless, I did a change in the composer.json file, that changes the usage of "real files" against symilinks.
Please give a try to latest commit on master branch.

**Comment by pstevens71** [comment]
I have same problem from version 2 to version 3.1.1 same JSON error.  Gets stuck right after "start" and admin login and password.

**Comment by nilsteampassnet** [comment]
@pstevens71
Please use latest commit

**Comment by Blubmann1337** [comment]
@nilsteampassnet yeah great, thanks. That was the solution. Update starts without any error

**Comment by pstevens71** [comment]
Hmm just tried latest commit, I get further in the install, but still stops at last step.  I looked and it is creating the new settings and config files but I'm getting 500 error on jquery.min.js
