### ISSUE TITLE
Uncaught MeekroDBException: Table 'teampass.teampass_items_otp' doesn't exist in

### ISSUE THREAD

**Issue by stijnb1234** [nilsteampassnet/TeamPass#3976]
Since the update to the latest version I have this error:

Uncaught MeekroDBException: Table 'teampass.teampass_items_otp' doesn't exist in

How to fix?

**Comment by nilsteampassnet** [comment]
@stijnb1234 

My fault, I've mixed up several local branches and commits.
One update has not followed to Github.
I'm fixing this quickly.

**Comment by nilsteampassnet** [comment]
@stijnb1234 
New commit created.
With all my apologies.

**Comment by nilsteampassnet** [comment]
@stijnb1234 
This is another thing.
Please don't mix ticket subject.
Can you open a new one with complete information expected and also log from Apache.
Thank you
