### ISSUE TITLE
Upgarde 2.1.27.36 to 3.1

### ISSUE THREAD

**Issue by edelmanns** [nilsteampassnet/TeamPass#3984]
Teampass 3.1 runs on my test system without any problems.
In preparation for the update from Teampass 2.1.27.36 to 3.1.0, I transferred the 2.1 installation to a new system and created a backup of the database and imported it into another db. 
I adjusted the settings.php and tp.config.php where necessary. 

now when i call teampass i get a HTTP ERROR 500.
In the log of the webserver I see the following:
PHP Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/html/teampass/index.php on line 336

PHP 8.1.2 and a Mariadb 10.6.12 are used.

Teampass 3 shows the following messages:
Teampass database is not up to date. 

Should a now start the upgarde of teampass?

### Server configuration
**Operating system:  ubuntu 22.04

**Web server: Apache2

**Database: mariadb 10.6

**PHP version: 8.1.2

**Comment by edelmanns** [comment]
Hello,

i have started the upgrade. I using incognito chrome for this task.
After 75000 Loops an ~23 hours i´ll get "out of memory".
Without incognito the error apears earlier.
No error in the apache error log.
I have restart the upgrade.

**Comment by edelmanns** [comment]
is it possible to calculate the number of loops?

**Comment by edelmanns** [comment]
Many trys later, the upgrade is not complete. 
After 12 till 24 hours chrome will die with "out of memory".
I try with 3.1.1 again. if some trouble i´ll make a new one.

**Comment by orochimarujr** [comment]
> Many trys later, the upgrade is not complete. After 12 till 24 hours chrome will die with "out of memory". I try with 3.1.1 again. if some trouble i´ll make a new one.

May I ask how did you solve the chrome out of memory issue?
