### ISSUE TITLE
3.1.1.31 - Directories and Items won't load

### ISSUE THREAD

**Issue by deanbruhn** [nilsteampassnet/TeamPass#4005]
### Steps to reproduce
1. Log into the server with a normal user
2. Click on any directory storing password items
3. The directory never load, and a green box pops up in the lower right hand corner that says reading folder indefinitely. 

### Expected behaviour
The items should load so the user can use them or modify them 

### Actual behaviour
The items never load, and the Reading Folder message in the lower right corner spins indefinitely

### Server configuration
**Operating system**:
Debain 11

**Web server:**
Apache2 

**Database:**
Maria 10.7

**PHP version:**
8.2.14

**Teampass version:** 
3.1.1.31

**Teampass configuration file:**
root@debian:~/TeamPass-master# cat /var/www/html/includes/config/settings.php
<?php
// DATABASE connexion parameters
define("DB_HOST", "<omitted>");
define("DB_USER", "<omitted>");
define("DB_PASSWD", "<omitted>");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
//define("DB_SSL", false); // if DB over SSL then comment this line
// if DB over SSL then uncomment the following lines
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/etc/teampass/");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Attached

### Client configuration
**Browser:**
Current versions of Chrome, Firefox, and Safari

**Operating system:**
macOS Sonoma 

#### Web server error log
```
Insert your webserver log here
[Fri Jan 12 12:30:07.890493 2024] [proxy_fcgi:error] [pid 32438] [client 172.16.1.105:51337] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items
[Fri Jan 12 12:30:41.170702 2024] [proxy_fcgi:error] [pid 32412] [client 172.16.1.105:51345] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items
[Fri Jan 12 12:31:00.086199 2024] [proxy_fcgi:error] [pid 33228] [client 172.16.1.105:51355] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items
[Fri Jan 12 12:32:20.871395 2024] [proxy_fcgi:error] [pid 33229] [client 172.16.1.105:51389] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items
[Fri Jan 12 12:32:20.871395 2024] [proxy_fcgi:error] [pid 33229] [client 172.16.1.105:51389] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items


[Fri Jan 12 12:46:32.730272 2024] [proxy_fcgi:error] [pid 33323] [client 172.16.1.105:51695] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items
[Fri Jan 12 12:50:44.075030 2024] [proxy_fcgi:error] [pid 33657] [client 172.16.1.105:52270] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array in /var/www/html/sources/items.queries.php:3828\nStack trace:\n#0 /var/www/html/sources/items.queries.php(3828): setcookie()\n#1 {main}\n  thrown in /var/www/html/sources/items.queries.php on line 3828', referer: http://172.16.1.112/index.php?page=items

#### Log from the web-browser developer console (CTRL + SHIFT + i)
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/13923024/tp.config.php.txt)

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (items.queries.php, line 0)




Insert the log here and especially the answer of the query that failed.
```

**Comment by deanbruhn** [comment]
I looked at the line of code in 3.1.1.31, and it had more than 3 arguments just like the error said
setcookie('jstree_select', $inputData['id'], $arr_cookie_options, "/", "", true, true);

Then I looked at the 3.1.0 code, and the function was this
setcookie(
                'jstree_select',
                $inputData['id'],
                $arr_cookie_options
            );

So I commented the setcookie line out, and added this line in it's place 

setcookie('jstree_select', $inputData['id'], $arr_cookie_options);


The software started working and I was able to access all of the items in the server.

**Comment by deanbruhn** [comment]
None of the passwords actually are available now.

**Comment by nilsteampassnet** [comment]
Fixed the setcookie issue.
Code analysis was wrong here

**Comment by deanbruhn** [comment]
Thanks!
