### ISSUE TITLE
3.1.1.38 - Item OTP Issues

### ISSUE THREAD

**Issue by deanbruhn** [nilsteampassnet/TeamPass#4006]
### Steps to reproduce
1. Open an item
2.click edit
3.select the details tab
4.check enable OTP Code
5. put the OTP Secret Key In the field
6. click save

### Expected behaviour
The system should save the code and then be able to display the rotating code.

### Actual behaviour
I get a spinning wheel that says "Reading folder" in the Botton right corner. I am having an issue with new items being saved with an OTP code not working also, but I am not getting errors just the OTP code field on the item displays None. Not sure if this is related or another issue. 

### Server configuration
**Operating system**:
Debian 11

**Web server:**
Apache 2

**Database:**
MariaDB 10.7.8

**PHP version:**
8.2.14

**Teampass version:** 
3.1.1.38

**Teampass configuration file:**

<?php
// DATABASE connexion parameters
define("DB_HOST", "127.0.0.1");
define("DB_USER", "<omitted>");
define("DB_PASSWD", "<omitted>!");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
//define("DB_SSL", false); // if DB over SSL then comment this line
// if DB over SSL then uncomment the following lines
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/etc/teampass/");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");
if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/13924625/tp.config.php.txt)

### Client configuration
**Browser:**
Chrome, Safari

**Operating system:**
MacOS Sonoma

#### Web server error log
[Fri Jan 12 16:08:14.914239 2024] [proxy_fcgi:error] [pid 32414] [client 172.16.1.100:50796] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MeekroDBException: Field 'increment_id' doesn't have a default value in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(549): MeekroDB->query()\n#2 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()\n#3 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()\n#4 /var/www/html/sources/items.queries.php(1729): DB::__callStatic()\n#5 {main}\n  thrown in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php on line 934', referer: http://172.16.1.112/index.php?page=items

#### Log from the web-browser developer console (CTRL + SHIFT + i)
Failed to load resource: the server responded with a status of 500 (Internal Server Error) /sources/items.queries.php:1

Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
@deanbruhn 

My fault, a pure defect in DB table.
I have fixed this and updated my test cases.
