### ISSUE TITLE
Upgrade from 2.1.27.34 to 3.1.0 not possible ? 

### ISSUE THREAD

**Issue by impalaa** [nilsteampassnet/TeamPass#4034]
Hi everyone,

After a little scan with GreenBone and a red flag... I would like upgrade my Teampass version to 3.1.0.
Actually, not works. 

After download the latest version of teampass and move all files and directory to /var/www/html with `rsync -av`

i have updated this files :
/var/www/html/includes/config/settings.php to include a new format like this:

`<?php
// DATABASE connexion parameters
define("DB_HOST", "127.0.0.1");
define("DB_USER", "teampass");
define("DB_PASSWD", "MyPWD");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define("DB_SSL", false); // if DB over SSL then comment this line
// if DB over SSL then uncomment the following lines
//define("DB_SSL", array(
//    "key" => "",
//    "cert" => "",
//    "ca_cert" => "",
//    "ca_path" => "",
//    "cipher" => ""
//));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/www/html/includes");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}`

I have updated this file too /var/www/html/includes/config/tp.config.php to modify this line:
`'cpassman_dir' => '/var/www/html',`

I have modified too my db with this SQL commands:

`Update teampass_items set complexity_level='-1' where complexity_level is NULL;`
`delete from teampass_users where id ='9999999';`

Restart my apache2 service...  and upgrading not starts. (please look attachment...)
![2024-01-31 10_45_30-TeamPass Upgrade](https://github.com/nilsteampassnet/TeamPass/assets/108672697/f97d81e2-b56d-40fb-8efd-072b10dd5cf5)

Someone as an idea to upgrade my Teampass ? 

Thanks.

**Comment by impalaa** [comment]
> @impalaa Please try using latest commit, I committed some changes in upgrade protocol. Don't modify the settings.php yourself. Indeed adapt your paths and urls in misc table and tp.config.php file.
> 
> Note: at first attempt to log as admin, an error will been shown (this occurs if settings.php was not as expected). Click a second time and should be ok (as the settings file is updated during 1st attempt).

Hi @nilsteampassnet,

Not works better :( 

I have make a tar.gz of html folder.
I have dump my db.
I have downloaded with wget the lastest version of Teampass.
I have unzip and move all of folder and file with rsync -av to html/ 
I have start with https://teampass.domain.local/install/upgrade.php. 
After this step i can't click on Next and if clicking on Start, not works. 

Do you have any idea how can i upgrade my version to the latest ? 

Thanks

**Comment by impalaa** [comment]
How can i import from a CSV all of password from my oldest version to a new server with 3.1.0 installed please ?

**Comment by nantartudo** [comment]
i have same problem. trying to import tables (from 2.1 to 3.1) items_value iteams_title nested_tree and items. all tables imported successfully. folders with subfolder implemented correct. but in GUI under folders there are warnings "no value defined". Also cannot see passwords(items) in folders. any ideas how to resolve it? tryied to change in settings php securepath and securefile. if change securefile to file which i copied from 2.1. version to 3.1. GUI stops to work with 500 error. i did not updated 2.1 to 3.1. i have installed 3.1. to new rhel 8 server. as test enviroment. also have issue with ldap. when ldap user change password in AD teampass not letting user to login correctly. asking to enter last and new password. even he types correct ones teampass gives error "Bad password".
