### ISSUE TITLE
Update Translation URL in releases

### ISSUE THREAD

**Issue by Saibamen** [nilsteampassnet/TeamPass#4049]
Update URL for translation in releases

https://github.com/nilsteampassnet/TeamPass/releases/tag/3.1.0

https://poeditor.com/projects/view?id=433631 gives HTTP 404

**Comment by nilsteampassnet** [comment]
#
A fix has been committed.
Please reopen if needed.

**Comment by click0** [comment]
Up.
https://poeditor.com/projects/view?id=433631 gives HTTP 404

**Comment by Kyogre** [comment]
reported in #4121
