### ISSUE TITLE
ERROR LOGIN: current session is not consistent and needs to be refreshed

### ISSUE THREAD

**Issue by silfius** [nilsteampassnet/TeamPass#4053]
Hello!

I have installed Teampass a few weeks ago. I have noticed that when I login for the first time a day, or when I do it in a different browser, most of the time, either the MFA box does not appear or if it does appear, when I authenticate, I get the following error

`current session is not consistent and needs to be refreshed`

![image](https://github.com/nilsteampassnet/TeamPass/assets/73602363/1aa1d9d8-5824-4f7a-973a-4ffad32b2a51)

Environment: 

- Debian 12
- PHP 8.2.7
- Teampass 3.1.1.64
- Teampass_access_logs and Teampass_error_logs without any type of metion about this

Anyone can help me?

Thank you very much

**Comment by nilsteampassnet** [comment]
Can you upgrade to latest commit please?
How long the login form is not refreshed before you click on button "Log in"?
This message happens if the browser session ID is refreshed during the inactivity on login page.

**Comment by silfius** [comment]
> Can you upgrade to latest commit please? How long the login form is not refreshed before you click on button "Log in"? This message happens if the browser session ID is refreshed during the inactivity on login page.
First of all, thank you for your great work. It is a great tool!
The page does not restart until I make the first login. After that, it logs in correctly.
On the other hand, sorry, but how do I do the Commit that you indicate? The installation I did was doing a "Git clone" of the project, isn't version 3.1.1.64 the latest version?

Thank you very much in advance

**Comment by silfius** [comment]
Thanks for your help.
I did the last commit. I'm with version 3.1.1.70, but with the same random error. Sometime happens, not always. 
Attach a video with the sequence. This moment is less unusual because the 4th box for code, it isn't shows.
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.16-10_34_08.webm](https://github.com/nilsteampassnet/TeamPass/assets/73602363/b654c614-554f-4ddf-af1b-386053dc278d)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by silfius** [comment]
Thank you very much!!

**Comment by rveupen** [comment]
I have installed a complete fresh install on  Debian 12.6.

Current version loaded 3.1.2.44
PHP Version 8.2.18

I to have the exact same error when logging in the first time. 
I can reproduce the exact same error on Edge, Chrome, FireFox, Opera and Brave.
The first login session always shows:

![image](https://github.com/nilsteampassnet/TeamPass/assets/45266767/c2f63647-7e91-48ea-af31-44fc84ce5706)

Pressing Log In again (is MFA is still valid) logs me in straight away.

**Comment by kevimax** [comment]
Good morning,
I systematically have the same problem on my installation in version 3.1.1.48.

Thank you in advance for your help.

**Comment by rveupen** [comment]
I have not been able to get around this.
Waiting for a response too.
