### ISSUE TITLE
poeditor contribution link is broken in the README

### ISSUE THREAD

**Issue by dasanselmo** [nilsteampassnet/TeamPass#4055]
### Steps to reproduce
1.  click on the POEDITOR link  in the README 
(Languages strings are managed at [POEditor.com](https://poeditor.com/projects/view?id=433631).)

### Expected behaviour
See the poeditor contribution page.
https://poeditor.com/projects/view?id=433631

### Actual behaviour
404 error message

### Server configuration
**Teampass version:**  latest

### Client configuration
**Browser:** any

**Operating system:** any

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
