### ISSUE TITLE
"Error: Malformed UTF-8 data" when do nothing along time

### ISSUE THREAD

**Issue by silfius** [nilsteampassnet/TeamPass#4056]
Environment:
![image](https://github.com/nilsteampassnet/TeamPass/assets/73602363/3de0ea97-c3a2-44d4-93d8-c6a1aacc7c41)

I am having problems with a relative frequency. If you are inside Teampass, and you go to another application on your computer and spend some time, when you go back to Teampass, and try to do something, sometimes Teampass does not respond, or sometimes it shows this message.

![image](https://github.com/nilsteampassnet/TeamPass/assets/73602363/2d6ad877-5af0-437a-adbc-8cbe5fa7e4e9)

How you can see, I'm in session time:
![image](https://github.com/nilsteampassnet/TeamPass/assets/73602363/dfa1258d-3455-4e35-910f-16d516580954)

Solution: I have to relogin another time

Anyone can help me?

Thank you very much

**Comment by nilsteampassnet** [comment]
@silfius 
Yes I noticed this too.
It is related to the session id.
Depending on browser, after a period of inactivity on the page, this session id can change.
As a result, Teampass identifies that its ID and the browser one are not the same.
As a consequence, the mismatch error occurs.
I will find a way to fix this.

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by silfius** [comment]
Ok. Thank you very much!!
