### ISSUE TITLE
Moving teampass2 to a fresh new server : Error code 500 while trying to access the web interface. Saltkey issue ? 

### ISSUE THREAD

**Issue by crayt214** [nilsteampassnet/TeamPass#4126]
### Steps to reproduce
1.Install teampass 2 to a new server (for me, it was Oracle Linux 8)
2.Try to migrate your old teampass2 instance (DB dump, teampass directory & teampass saltkey tar)
3.Access the new teampass instance : http//xxx:80. note the issue with HTTP error code 500

### Expected behaviour
possibility to connect to the new instance, with all data from the old one and password

### Actual behaviour
HTTP Error 500, the only possibility to connect the new instance is to set a new saltkey but I can't use the same as the old server one.

Issue : For multiple reasons I have to move our old but working teampass2 instance to a new server.
I prepared the new server with the same components : PHP 7.4, Mariadb 10.3...
I did a mysqldump from my old server, and followed the first steps from https://teampass.readthedocs.io/en/latest/install/install-linux/ to create the new database, the user and the rights. Then I followed https://github.com/nilsteampassnet/TeamPass/issues/2000 : "The solution was to just archive teampass installation and salt key directories, dump db into a sql file, copy them into another host, just untar and import the sql file, then it just works.". So everything was in place for the new instance.
Except the fact that after rebooting the webserver, I never had the possibility to connect to teampass. Always "Error code 500".

I checked the csrfp.config, its OK

To connect to the new instance, I had to create a new saltkey from the install process. But of course, I have all of my data from the old server, except the passwords (because I don't have the good saltkey)...

Can you help me ? I didn't find any documentation about migrating a teampass instance to a new server.

I'm working on this migration only to be on a supported OS, and do the Teampass3 upgrade... :(

### Server configuration
**Operating system**: Old one : Centos8, New one : Oracle Linux 8

**Web server:** Httpd (Apache2)

**Database:** MariaDB 10.3

**PHP version:** 7.4 on both servers

**Teampass version:** 2.1.27.36

**Teampass configuration file:** 

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/14890943/tp.config.php.txt)

### Client configuration
**Browser:** Chrome

**Operating system:** Windows Server 2019

#### Web server error log
[05/Apr/2024:23:08:20 +0200] "GET /index.php?page=manage_main HTTP/1.1" 500 - "http://10.64.44.18/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.3
6"

#### Log from the web-browser developer console (CTRL + SHIFT + i)
![image](https://github.com/nilsteampassnet/TeamPass/assets/166176117/d53c2447-d9f8-47a3-9ace-6833ead5c004)

I can show you anything that can help you to investigate ... 

Thanks in advance !

**Comment by DaveWebb2** [comment]
Have you looked in the Apache error log for clues (/var/log/apache2/error.log)?

**Comment by crayt214** [comment]
Hi, I resolved my issue, it was just about changing my db password correctly in the includes/config/settings.php.
I had a log in my mariadb.log wich indicated me that my user couldn't connect to the db.
I close this issue :)

**Comment by Alpha-Zark** [comment]
> Hi, I resolved my issue, it was just about changing my db password correctly in the includes/config/settings.php. I had a log in my mariadb.log wich indicated me that my user couldn't connect to the db. I close this issue :)

Hi , how do you change this passwd ? It is a character encrypted by TeamPass. I cannot directly convert it into a plaintext password in setting.php.
