### ISSUE TITLE
Could not save item (without generate button)

### ISSUE THREAD

**Issue by janekska** [nilsteampassnet/TeamPass#4130]
### Steps to reproduce
1. Folder created with allowed "without complexity target",
2. User create new item in that folder and use his own/previous known password

### Expected behaviour
The item is saved

### Actual behaviour
User gets message: "No change performed".
The workaround:
If user hits password autogenerate button, than it can save the Item. Also when override pasword in pasword field.

### Server configuration
**Operating system**:
Ubuntu 20.04.5 LTS

**Web server:**
Apache/2.4.41 (Ubuntu)

**Database:**
MySQL

**PHP version:**
8.2

**Teampass version:** 
3.1.2

**Teampass configuration file:**
[tp.config.php (1).txt](https://github.com/nilsteampassnet/TeamPass/files/14903767/tp.config.php.1.txt)

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Microsoft Edge for Business
Version 122.0.2365.92 (Official build) (64-bit)
and
Google Chrome
Version 123.0.6312.106 (Official Build) (64-bit)

**Operating system:**
Windows 11

#### Web server error log
[error_log.txt](https://github.com/nilsteampassnet/TeamPass/files/14903775/error_log.txt)

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

```

https://drive.google.com/file/d/1bQjoD-I5Rn0Q2vleSkTVKElzw80cAxHH/view?usp=sharing

**Comment by aandrei79** [comment]
Hi!
I have the same issue. Adding new item is possible only hitting "Generate" password button. With custom password I have error: "No change was performed".

![TeamPass_version](https://github.com/nilsteampassnet/TeamPass/assets/96541089/e12b6042-891f-43d6-b50f-3228191294e7)

**Comment by SchwingSK** [comment]
Same here, fresh install using the provided docker compose.

**Comment by aandrei79** [comment]
Reinstalled using version 3.1.2.35
Problem persists.

Debian GNU/Linux 12 (bookworm)

PHP version: 8.2.18
Memory limit: 128M
Memory usage: 526.40 KB
Maximum time execution: 60
Maximum file size upload: 2M

Server version: 10.11.6-MariaDB-0+deb12u1
Database size: 0.97MB

![image](https://github.com/nilsteampassnet/TeamPass/assets/96541089/6075302f-7595-4951-a521-8e0890756a32)
