### ISSUE TITLE
Items are not show when in folder view. Can easy search and open.

### ISSUE THREAD

**Issue by aostrovsky** [nilsteampassnet/TeamPass#415]
When I creating the item in folder it does shown. But after page refresh it is gone.
I can still search and open.
But no any items shown in folder itself.
User is permitted for that folder.

![screenshot at 2013-10-01 16 11 57](https://f.cloud.github.com/assets/1371128/1245272/371cc280-2a9b-11e3-96a9-9a4af8c2ea56.png)

**Comment by ArthurGuy** [comment]
Where was the resolution to this issue as I think it's still present?
The table name keys is still being queries unquoted.
I chose not to use a table prefix which I believe is why I am experiencing this.
