### ISSUE TITLE
Zero before minutes is missing in Server time

### ISSUE THREAD

**Issue by Kyogre** [nilsteampassnet/TeamPass#4154]
### Steps to reproduce
1. In teampass options page change `Time zone` to any GMT (tested with GMT +3)
2. Wait till real time has one-digit minutes value.
3. Go to `Information` page.
4. Look at `Server time`.

### Expected behaviour
time shown like 14:02:42

### Actual behaviour
time shown like 14:2:42

![zero missing in minutes](https://github.com/nilsteampassnet/TeamPass/assets/2260980/1d65d762-cb46-4bd3-b884-7920cfd902a6)

### Server configuration
**Operating system**: RHEL 8.3

**Web server:** Doesn't matter (tried on nginx 1.25.4 and apache httpd 2.4.58)

**Database:** mariadb 10.11.6

**PHP version:** 8.1.24

**Teampass version:** 3.1.2.29

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/15090517/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install.

### Client configuration
**Browser:** doesn't matter.

**Operating system:** Windows 10

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
