### ISSUE TITLE
Fresh install error - Answer from server is empty

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#4160]
### Steps to reproduce
1. Install fresh 
2. 
3.

![image](https://github.com/nilsteampassnet/TeamPass/assets/12623112/908108bd-ac7f-46f9-835b-a6f8b016d993)

### Server configuration
**Operating system**:  Debian GNU/Linux 12 (bookworm)

**Web server:**  Apache/2.4.59 (Debian)

**Database:**  10.11.6-MariaDB-0+deb12u1 Debian 12

**PHP version:**  PHP 8.2.18 

**Teampass version:**  3.1.1

**Teampass configuration file:**   n/a,  fresh install

#### Web server error log
```
[errorApache.log](https://github.com/nilsteampassnet/TeamPass/files/15109572/errorApache.log)

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[tpassHAR.zip](https://github.com/nilsteampassnet/TeamPass/files/15109578/tpassHAR.zip)

```

**Comment by 4darkpain** [comment]
I am experiencing the same issue.

**Comment by 4darkpain** [comment]
Got error 'PHP message: PHP Warning:  include_once(/var/www/html/teampass/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/teampass/sources/main.functions.php on line 53; PHP message: PHP Warning:  include_once(): Failed opening '/var/www/html/teampass/sources/../includes/config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/teampass/sources/main.functions.php on line 53; PHP message: PHP Warning:  Undefined variable $session in /var/www/html/teampass/includes/config/settings.php on line 28; PHP message: PHP Fatal error:  Uncaught Error: Call to a member function has() on null in /var/www/html/teampass/includes/config/settings.php:28\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(4187): require_once()\n#1 /var/www/html/teampass/sources/main.functions.php(59): loadClasses()\n#2 /var/www/html/teampass/install/install.queries.php(41): require_once('...')\n#3 {main}\n  thrown in /var/www/html/teampass/includes/config/settings.php on line 28',

**Comment by nilsteampassnet** [comment]
@wease1 
Please install from latest commit

**Comment by lazarusvc** [comment]
@nilsteampassnet I getting this same issue from version 3.1.2

**Comment by nilsteampassnet** [comment]
Have you overwriten existing files and upgraded to 3.1.2 pre-release?
