### ISSUE TITLE
Unexpected Caracter in password after ugrading from 2.1.27.36

### ISSUE THREAD

**Issue by Phdhebde** [nilsteampassnet/TeamPass#4162]
Hi everyone, 

After migrading my teampass from 2.1.27.36 to 3.1.1, i faced several issues concerning the password. Its seems like an encoding problem because special character are resplace by their html name code. For example, `<` became `&lt;`.  I already try to specify the utf8 in setting.php file before upgrading. 

**Do we have an other way to change the encoding parameter ?**

After trying to change the password and replace the special encoding with the normal, a message error appear telling us that the password hasn't change. 

### Steps to reproduce
1. Having a password containing < symbol 
2. Upgrading to 3.1.1 
3. Copy the password with the special symbol

### Server configuration
**Operating system**: Debian 12.5 , kernel 6.1.85

**Web server:** Apache 2.4.59

**Database:** : mariaDB 10.11.6

**PHP version:** 8.2

**Teampass version:**  3.1.1

**Teampass configuration file:** : include/config/setting.php file 

```
define("DB_HOST", "127.0.0.1");
define("DB_USER", "xxxxxxxx");
define("DB_PASSWD", "xxxxxxxxxxxxxx");
define("DB_NAME", "xxxxxxxxx");
define("DB_PREFIX", "xxxxxxxxxx");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define("DB_SSL", false); // if DB over SSL then comment this line
// if DB over SSL then uncomment the following lines
//define("DB_SSL", array(
//    "key" => "",
//    "cert" => "",
//    "ca_cert" => "",
//    "ca_path" => "",
//    "cipher" => ""
//));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/www/teampass");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if ($session->has('system-timezone') && null !== $session->get('system-timezone')) {
    date_default_timezone_set($session->get('system-timezone'));
}
```

### Client configuration
**Browser:**
- Firefox
- Chrome
- Edge

**Operating system:**
Debian : 12.5

### LOGS

We haven't error log from the webserver

# HELP 

**Does anyone have the same problem or fix it ?**

**Comment by michaldejmek** [comment]
The upgrade from version 2.1.7.36 went smoothly .?  I am solving the problem that the upgrade does not start and in the log I see: "POST /teampass/install/upgrade_run_3.0.0.php HTTP/1.1" 500

@Phdhebde  I would look at the encoding in the DB is it in UTF-8 ???

**Comment by Phdhebde** [comment]
Yes it is
________________________________
De : Michal Dejmek ***@***.***>
Envoyé : Monday, July 29, 2024 3:36:51 PM
À : nilsteampassnet/TeamPass ***@***.***>
Cc : Maxence HAEGMAN ***@***.***>; Mention ***@***.***>
Objet : Re: [nilsteampassnet/TeamPass] Unexpected Caracter in password after ugrading from 2.1.27.36 (Issue #4162)


Sécurité : Soyez vigilant sur l’ouverture des pièces jointes ou des liens présents dans ce message si vous ne connaissez pas l’expéditeur.
Security: Be careful about opening attachments or links in this message if you don't know the sender.

The upgrade from version 2.1.7.36 went smoothly .? I am solving the problem that the upgrade does not start and in the log I see: "POST /teampass/install/upgrade_run_3.0.0.php HTTP/1.1" 500

@Phdhebde<https://github.com/Phdhebde> I would look at the encoding in the DB is it in UTF-8 ???
