### ISSUE TITLE
ERROR LOGIN: current session is not consistent and needs to be refreshed

### ISSUE THREAD

**Issue by rveupen** [nilsteampassnet/TeamPass#4174]
I have installed a complete fresh install on Debian 12.6.

Current version loaded 3.1.2.44
PHP Version 8.2.18

I to have the exact same error when logging in the first time.
I can reproduce the exact same error on Edge, Chrome, FireFox, Opera and Brave.
The first login session always shows:

![image](https://github.com/nilsteampassnet/TeamPass/assets/45266767/5180f595-9598-42e3-a0ce-4a4ac3c55340)

Pressing Log In again (if MFA is still valid) logs me in straight away.

**Comment by corentin-soriano** [comment]
PR: #4228

**Comment by rveupen** [comment]
I have updated to this version and the problem has gone away.
Doe not matter which browser I use I do not get the Caution message anymore..
Currently on this version:
Current version loaded 3.1.2.59
