### ISSUE TITLE
LDAP connection error and error 500 on the web page

### ISSUE THREAD

**Issue by doooopT** [nilsteampassnet/TeamPass#4213]
[### Page on which it happened
index.php?page=ldap)
--> 
### Steps to reproduce
1. Configure LDAP options (Active Directory)
2. Test current configuration

### Expected behaviour
Test : KO

### Actual behaviour
LDAP connection test error

### Server configuration
**Operating system**:
VMAzure
**Web server:**
Server version: Apache/2.4.52 (Ubuntu)
**Database:**

**PHP version:**
PHP 8.3.7 

**Teampass version:** 
 3.1.2. 44

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Chrome

**Operating system:**
Ubuntu 22.04

### Logs
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'http://teampassv3.cacg.com',
    'favicon' => 'http://teampassv3.cacg.com/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'http://teampassv3.cacg.com/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.1.2',
    'ldap_mode' => '1',
    'ldap_type' => 'OpenLDAP',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 
'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_te>
    'send_stats_time' => '1713191260',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'ypSsXmWfwca3hrnk8Lwtrhvek2Kzh5PcTmKnPMQg',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'samaccountname',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '(&amp;amp;(objectCategory=Person),(sAMAccountName=*))',
    'ldap_bdn' => 'DC=cacg,DC=com',
    'ldap_hosts' => 'AZAMSDC-02.cacg.com',
    'ldap_password' => '',
    'ldap_username' => 'cn=AdminServeurs Atn,cn=Users,DC=cacg,DC=com',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1715783260',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
    'enable_refresh_task_last_execution' => '1',
    'ldap_group_objectclasses_attibute' => 'top,groupOfuniquenames',
    'pwd_default_length' => '14',
    'tasks_log_retention_delay' => '30',
    'oauth2_enabled' => '0',
    'oauth2_client_id' => '',
    'oauth2_client_secret' => '',
    'oauth2_client_endpoint' => '',
    'oauth2_client_token' => '',
    'oauth2_client_scopes' => 'openid,profile,email',
    'oauth2_client_appname' => 'Login with Azure',

#### Web server error log

 webserver log 
```
PHP Fatal error:  Uncaught ErrorException: ldap_search(): Search: Operations error in /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Ldap.php:227\nStack trace:\n#0 [internal function]: LdapRecord\\Ldap->LdapRecord\\{closure}()\n#1 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Ldap.php(227): ldap_search()\n#2 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/HandlesConnection.php(170): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Ldap.php(216): LdapRecord\\Ldap->executeFailableOperation()\n#4 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(692): LdapRecord\\Ldap->search()\n#5 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(416): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#6 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(497): LdapRecord\\Connection->runOperationCallback()\n#7 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(476): LdapRecord\\Connection->retry()\n#8 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(365): LdapRecord\\Connection->tryAgainIfCausedByLostConnection()\n#9 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(681): LdapRecord\\Connection->run()\n#10 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(441): LdapRecord\\Query\\Builder->run()\n#11 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(670): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#12 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(444): LdapRecord\\Query\\Builder->getCachedResponse()\n#13 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(234): LdapRecord\\Query\\Builder->query()\n#14 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(255): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#15 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(233): LdapRecord\\Query\\Builder->onceWithColumns()\n#16 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(773): LdapRecord\\Query\\Builder->get()\n#17 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(789): LdapRecord\\Query\\Builder->first()\n#18 /var/www/html/TeamPass/sources/ldap.queries.php(175): LdapRecord\\Query\\Builder->firstOrFail()\n#19 {main}\n\nNext LdapRecord\\LdapRecordException: ldap_search(): Search: Operations error in /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/LdapRecordException.php:25\nStack trace:\n#0 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/HandlesConnection.php(183): LdapRecord\\LdapRecordException::withDetailedError()\n#1 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Ldap.php(216): LdapRecord\\Ldap->executeFailableOperation()\n#2 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(692): LdapRecord\\Ldap->search()\n#3 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(416): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#4 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(497): LdapRecord\\Connection->runOperationCallback()\n#5 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(476): LdapRecord\\Connection->retry()\n#6 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Connection.php(365): LdapRecord\\Connection->tryAgainIfCausedByLostConnection()\n#7 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(681): LdapRecord\\Connection->run()\n#8 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(441): LdapRecord\\Query\\Builder->run()\n#9 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(670): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#10 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(444): LdapRecord\\Query\\Builder->getCachedResponse()\n#11 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(234): LdapRecord\\Query\\Builder->query()\n#12 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(255): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#13 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(233): LdapRecord\\Query\\Builder->onceWithColumns()\n#14 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(773): LdapRecord\\Query\\Builder->get()\n#15 /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/Query/Builder.php(789): LdapRecord\\Query\\Builder->first()\n#16 /var/www/html/TeamPass/sources/ldap.queries.php(175): LdapRecord\\Query\\Builder->firstOrFail()\n#17 {main}\n  thrown in /var/www/html/TeamPass/vendor/directorytree/ldaprecord/src/LdapRecordException.php on line 25, referer: https://tp.....fr/index.php?page=ldap
[Tue Jun 04 14:46:14.207956 2024] [php:error] [pid 14764] [client 10.38.100.6:51710] PHP Fatal error:  Uncaught Error: Call to a member function getErrorCode() on null in /var/www/html/TeamPass/sources/ldap.queries.php:194\nStack trace:\n#0 {main}\n  thrown in /var/www/html/TeamPass/sources/ldap.queries.php on line 194, referer: https://tp.....fr/index.php?page=ldap

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
https://........../sources/ldap.queries.php 500 (Internal Server Error)

in tp.config.php I added the lines 'ldap_suffix' => '0',
    ldap_domain_dn' => '0', following : #4094 

root@AZAMSPROD-TEAMPASS:/var/www/html/TeamPass/includes/config# nc -vz 10.48.10.4 389
Connection to 10.48.10.4 389 port [tcp/ldap] succeeded!

ldapsearsh is working and the port is listening properly
@nilsteampassnet

**Comment by DaveWebb2** [comment]
When I had an error 500 it was because the csrfp.config.php file was missing from /var/www/teampass/includes/libraries/csrfp/libs and jsUrl was also not specified in that file.

**Comment by vayce-vayce** [comment]
Leave this field blank and it will work
'ldap_user_object_filter' => '',
