### ISSUE TITLE
I can delete Root folder even if I don't have permissions.

### ISSUE THREAD

**Issue by nykroy** [nilsteampassnet/TeamPass#4258]
### Steps to reproduce
1. Select folder 
2. Delete folder
3. I click on the message that indicates if I want to confirm the deletion.
4.While it is loading, I click again on the message that indicates if I want to confirm the deletion.

It seems that the second time I confirm the message, it sends the deletion data, losing the folder ID, so it interprets it as 0 (which is the root folder)

### Server configuration
**Operating system**: Debian

**Web server:**

**Database:**

**PHP version:** 

**Teampass version:** 3.1.2

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** yes

### Client configuration
**Browser:** Edge

**Operating system:**  Windows 

```

**Comment by corentin-soriano** [comment]
I reproduce. On the js side everything seems correct (I clicked 4 times), however everything is deleted:
![image](https://github.com/user-attachments/assets/1837fd82-a520-4aa6-b9b2-ad39090f7bbd)

User items view:
![image](https://github.com/user-attachments/assets/e110e80e-cf6c-4ef3-97cb-1884f77998bd)

Admin folders view:
![image](https://github.com/user-attachments/assets/b2563719-f532-49ab-9775-ae422d04a96e)

Database:
![image](https://github.com/user-attachments/assets/e0b9b119-f24f-4eca-97eb-69a4ff716d08)
