### ISSUE TITLE
Got error 'PHP message: TEAMPASS 

### ISSUE THREAD

**Issue by sysadminketra** [nilsteampassnet/TeamPass#4289]
### Steps to reproduce
I need help, when an update event is performed in the admin panel, and when there is an event to list items with passwords, an error is displayed in the log. 

### Server configuration
**Operating system**:
debian linux 12
**Web server:**
apache2
**Database:**
mariadb 10.1
**PHP version:**
8.1
**Teampass version:** 
3.1.2 

**Updated from an older Teampass or fresh install:**
teampass v2.x
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

**Operating system:**
debian 12

#### Web server error log
```
# cat /var/log/teampass/error.log
AH01071: Got error 'PHP message: TEAMPASS - Folder: 71 - User: 10000036 - access: ND - edit: - delete: ', referer: https://domain.com/index.php?page=items
AH01071: Got error 'PHP message: TEAMPASS - Folder: 39 - User: 10000048 - access: ND - edit: - delete: ', referer: https://domain.com/index.php?page=items
AH01071: Got error 'PHP message: TEAMPASS - Folder: xx - User: 100000xx - access: ND - edit: - delete: ', referer: https://domain.com/index.php?page=items
```

**Comment by nilsteampassnet** [comment]
This is due to the fact that a constant is defined to TRUE 

File includes/config/include.php

define('LOG_TO_SERVER', true);         // Defines if logs are sent to the server

Should be FALSE
