### ISSUE TITLE
New sub-folders not inherit permissions from parent folder

### ISSUE THREAD

**Issue by ivancasanovaicp** [nilsteampassnet/TeamPass#4298]
Steps to reproduce
1. Activate in configuration the option "New sub-folders inherit the permissions of the folders on which they depend."
2. User with rol X and Y creates a sub-folder "FOLDER_EXAMPLE_2" in "FOLDER_EXAMPLE" ( rol X it´s the only one who has permission to see "FOLDER_EXAMPLE")
3. Create password in the new folder "FOLDER_EXAMPLE_2". but you can see that VISIBLE BY shows Rol X and Y.

Expected behaviour
The new folder will show only Rol X.

Actual behaviour
Now new folder shows all user roles.

Server configuration

UBUNTU 22.04

**Database: MariaDB

**PHP version: 8.1.2

Teampass version: 3.1.2.45

**Comment by nilsteampassnet** [comment]
@ivancasanovaicp thank you

Should be fixed

**Comment by ivancasanovaicp** [comment]
Thanks, I tried it and it works correctly.

How did you update the table hashes in file includes/tables_integrity.json?

**Comment by nilsteampassnet** [comment]
Thank you for the feedback.

To answer your question, it is a script running before performing git commit command

**Comment by ivancasanovaicp** [comment]
Thank you for the work and time you put in.

Could you tell me how to find the script to run?

**Comment by nilsteampassnet** [comment]
It is a local script not part of the teampass github project
