### ISSUE TITLE
Infinite loop when upgrading to 3.1.2.114

### ISSUE THREAD

**Issue by gonzalodeniz** [nilsteampassnet/TeamPass#4365]
### Steps to reproduce
1. Upgrade from 3.1.2.90 to 3.1.2.114

### Expected behaviour
Successful completion of the upgrade

### Actual behaviour
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/teampass/sources/main.functions.php on line 2163

### Server configuration
**Operating system**: ubuntu 22.04

**Web server:** apache 2.4

**Database:** MariaDB10

**PHP version:** 8.2

**Teampass version:** 3.1.2.114

#### Web server error log
```
[Wed Sep 25 15:01:19.075671 2024] [php:error] [pid 14] [client 172.xx.xx.xx:42030] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/teampass/sources/main.functions.php on line 2163, referer: http://localhost:3080/teampass/install/upgrade.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Nothing
```

I think the error is in this recursive function that does not stop:

 # source/main.functions.php
Line: 2141 
function recursiveChmod(
    string $path,
    int $filePerm = 0644,
    int  $dirPerm = 0755
)

Is there any news on this point?

**Comment by gonzalodeniz** [comment]
When I have an opening, I'll make a trace.

**Comment by gonzalodeniz** [comment]
The recursiveChmod function has an error. 

Here is a trace (I remove non-relevant variables):

```
# There is a path in the code that is ‘install/install’.
recursiveChmod($path)           # $path=‘install/install’

# basename extracts the last part of the route
$path = basename($path);        # $path=‘install’; 
...
} elseif (is_dir($path)) {                # is_dir(‘install’) = True 

# scandir(‘install’) extracts the contents of ‘/install’, not ‘install/install’.
# Among your results you will again find the path ‘install/install’.
$foldersAndFiles = scandir($path);       # scandir(‘intall’) = [..., ‘install/install’.... ]

Start again at the same place. Infinite loop.
recursiveChmod($path.‘/’.$entry, $filePerm, $dirPerm);
```

Does it work for you?

**Comment by gonzalodeniz** [comment]
The solution is to rename or delete the second install folder:

```
mv install/install install/install_disable
```

**Comment by flacco** [comment]
Same here, after using a new installation off teampass 3.1.6.12 for a few hours it ends in an infinte loop.

Stefan
