### ISSUE TITLE
Problem with file upload and download

### ISSUE THREAD

**Issue by reginaldomoreno** [nilsteampassnet/TeamPass#4402]
When I upload a file and try to download it, the file gets corrupted. No matter the format, the file gets corrupted.
Tempass version: 3.1.2

**Comment by corentin-soriano** [comment]
I can't reproduce this. I tried to add "favicon.png":
![image](https://github.com/user-attachments/assets/3d096015-e37c-4f3c-9801-fb78a2b7a646)
Click on the show button:
![image](https://github.com/user-attachments/assets/acf48954-3344-417f-928d-a0b1648686fa)
Download button:
![image](https://github.com/user-attachments/assets/c135228c-1f70-40d7-9235-e0d6b21d0e66)
![image](https://github.com/user-attachments/assets/9d818d3e-d580-466d-a9c3-627ccd6e8ed1)

What is your full version number (displayed in the footer)?
Do you have any example?
Any error in your apache/nginx/php logs?
How big is your file?

**Comment by reginaldomoreno** [comment]
Hi.


[image: image.png]

[image: image.png]
After download and opened it. It looks like this.

[image: image.png]
It is a simple txt file.
No errors. Just corrupt or encrypted.


[image: image.png]


Thanks for your time.

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qua., 9 de out. de 2024 às 05:03, Corentin SORIANO <
***@***.***> escreveu:

**Comment by corentin-soriano** [comment]
Sorry but the images are not visible, can you put them back?

**Comment by B3XAL** [comment]
I have the same problem.

When the same file ( with same or changed name ) is uploaded in two different objects or passwords , the older one is always corrupted.

**Comment by corentin-soriano** [comment]
@B3XAL thanks for the clarification.
Can you try this fix? #4527

**Comment by B3XAL** [comment]
@corentin-soriano  Thank you very much!

**Comment by reginaldomoreno** [comment]
Hi.

I have updated to ver 3.1.2.146 and solved my problem. The serious problem
I have with this update is about custom fields. When I ran the update,
custom fields were corrupted.

Best regards,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em seg., 16 de dez. de 2024 às 12:40, B3XAL ***@***.***>
escreveu:
