### ISSUE TITLE
Folders created by user are show to any another user without permissions.

### ISSUE THREAD

**Issue by reginaldomoreno** [nilsteampassnet/TeamPass#4403]
Some folders created by regular users keep showing up. No matter what I do. I change it to no access and it's still showing and with full permission.

### Server configuration
**Operating system**: Linux EBS-ITTEPASS01 5.15.0-209.161.7.2.el9uek.x86_64 #2 SMP Tue Aug 20 10:44:41 PDT 2024 x86_64

**Web server:** Apache/2.4.57 (Oracle Linux Server) OpenSSL/3.0.7

**Database:** 10.5.22-MariaDB

**PHP version:** 8.2.13

**Teampass version:** 3.1.2

**Comment by corentin-soriano** [comment]
I'm not able to reproduce this issue, can you add some screenshoots of your users and role configuration?

**Comment by reginaldomoreno** [comment]
Thank you for your time.
When i did a UP date to version 3.1.2.139 the problem was fixed.
Thank you

Em qua., 9 de out. de 2024, 04:57, Corentin SORIANO <
***@***.***> escreveu:

**Comment by reginaldomoreno** [comment]
Some images

Folder Equipe-Middleware should not be showing because my user doesn't have
permissions, but it does not matter if the user has or not.
I was testing the new build 3.1.2.129 on another clone of this VM and this
problem was fixed with the new version.

[image: image.png]

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qua., 9 de out. de 2024 às 20:33, Reginaldo Moreno <
***@***.***> escreveu:

**Comment by reginaldomoreno** [comment]
Hi.

How can I disable this message or function that give me the message to
change password for LDAP users? Screenshot with message is attached

Regards,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em ter., 15 de out. de 2024 às 02:26, Nils Laumaillé <
***@***.***> escreveu:

**Comment by corentin-soriano** [comment]
Email attachment aren't pushed in github issues. You should add them directly in the issue.
I think you are talking about #4407, I noticed the bug but I don't have a fix yet.
You can repair your account by generating new keys (or restore if you saved them). Generate OTP from an admin account will also work.
Please note that only restoration allows you to maintain access to entries in your personal folder.

**Comment by reginaldomoreno** [comment]
Hi.

Sorry.
Is it about folders showing to any users or asking to change password
after applying patches? I'm confused.

Regards,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qua., 30 de out. de 2024 às 04:18, Corentin SORIANO <
***@***.***> escreveu:

**Comment by reginaldomoreno** [comment]
Is everything I publish here is public?
I can record a video with problem.

Atenciosamente,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qua., 30 de out. de 2024 às 17:20, Reginaldo Moreno <
***@***.***> escreveu:
