### ISSUE TITLE
After update from version 3.1.2.29 to 3.1.2.139 I have two problems

### ISSUE THREAD

**Issue by reginaldomoreno** [nilsteampassnet/TeamPass#4407]
Problem with manager users. 

When I try to create a user, portal still on looping and not create. 
When I try to delete a user it not work. 
When I try to edit a user, all users information appears empty.
The user can log in without any problems, execpt this message

"Your authentication password has been changed in your AD since you last get logged in in Teampass. We need to adapt your encryption key. Please provide your previous password and the current one."

You close it and work normal. Itas a annoyng message.

Oracle Linux Server 9.4

Server is connected to internet

PHP version: 8.2.13
Memory limit: 128M
Memory usage: 628.51 KB
Maximum time execution: 30
Maximum file size upload: 12M

Server version: 10.5.22-MariaDB
Database size: 19.39MB

Log
[09/Oct/2024:12:31:58 -0300] "POST /sources/users.queries.php HTTP/1.1" 500 - "https://teampass01.ebs-it.local/index.php?page=users" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"

**Comment by corentin-soriano** [comment]
`"Your authentication password has been changed in your AD since you last get logged in in Teampass. We need to adapt your encryption key. Please provide your previous password and the current one."`

You LDAP password seems to have changed.
If you download your keys, private key certainly empty.

For the creation/deletion of users I will fix it.

**Comment by reginaldomoreno** [comment]
Thank you for your time, but this message appears to the admin too. No
matter if the user is LDAP or local.
After you log in, show this message. Local ou remote user.
If you try to see the user information, all the users information is empty.

Atenciosamente,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qua., 9 de out. de 2024 às 12:59, Corentin SORIANO <
***@***.***> escreveu:

**Comment by corentin-soriano** [comment]
Can you check this in the database?
`SELECT login, auth_type, LENGTH(private_key) WHERE special = 'recrypt-private-key' OR special = 'auth-pwd-change';`

**Comment by reginaldomoreno** [comment]
Hi.

Sorry for respond after some days.
I saw that there is a new version on site and applied
Current version loaded 3.1.2.*8*
With this version, the User's interface returned to normal.
After updating, the local user did not give me an error to synchronize ldap
password. Only to remote users.
But the error about the resync password is still happening. I changed my
password 1 month ago. This VM that I'm using to test update is a clone from
my current version, so I don't have this problem about password with sysc
password. The error is attached.


When I execute this command, It gets this error below.

MariaDB [teampassdb]> SELECT login, auth_type, LENGTH(private_key) WHERE
special = 'recrypt-private-key' OR special = 'auth-pwd-change';
ERROR 1054 (42S22): Unknown column 'login' in 'field list'



Atenciosamente,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em sex., 11 de out. de 2024 às 02:31, Corentin SORIANO <
***@***.***> escreveu:

**Comment by reginaldomoreno** [comment]
Hi.
It is 3.1.2.146 now. It seems good.
Thank you

best regards.,

Reginaldo Moreno.

"Prefiro os que me criticam, porque me corrigem, aos que me elogiam, porque
me corrompem."
(Santo Agostinho)


Em qui., 14 de nov. de 2024 às 06:46, Corentin SORIANO <
***@***.***> escreveu:
