### ISSUE TITLE
missing languages from dropdown

### ISSUE THREAD

**Issue by Atoms** [nilsteampassnet/TeamPass#444]
Hello, 

installed Teampass and can't switch to any other language or even set default language... select box is empty, also table teampass_languages is empty. 

version 2.1.18

**Comment by Kyogre** [comment]
Solution from https://github.com/nilsteampassnet/TeamPass/issues/3397#issuecomment-1313850809 works for me in 3.0.0.21, but it means reinstalling Teampass from scratch.
More comfortable solution is to manually change "default_language" parameter in /var/www/teampass/includes/config/tp.config.php

Though as I see, it is [fixed](https://github.com/nilsteampassnet/TeamPass/blob/d0fc63f83442c894356157535a5d5f359498aa1b/install/install.queries.php) in the upcoming 3.0.0.22.

> added some id to fields and query executed normally

hi! By the way, can you tell how have you done that? What mysql commands had you executed to add ids?
