### ISSUE TITLE
All items are restricted in tree (Password menu)

### ISSUE THREAD

**Issue by manusfreedom** [nilsteampassnet/TeamPass#4495]
Tested with the latest Github code (master): 
I have permission on all items, but I can only see them using the tree (password).
It works with search.

sources/items.queries.php line 3926:
`$accessLevel = count($arrTmp) > 0 ? max($arrTmp) : $accessLevel;`
My max is 50 (the array has 30 because of W and 50 because of NULL/count=0) but 50 gets no permission (between lines 4227 and 4361).

NB: I think the algorithm is wrong (and not very easy to maintain) and why not use a constant (with an understandable name) instead of an int value everywhere?

**Comment by Saueee** [comment]
Do you mean it looks like this?
![grafik](https://github.com/user-attachments/assets/df2f7daa-88ca-4fe6-a96f-b12af2cfc307)
I have the same problem.

**Comment by futureweb** [comment]
I got the same Problem - almost all Passwords are shown double with one of them shown as restricted ... any ideas on how to fix this?
thx

**Comment by nilsteampassnet** [comment]
I will have a look to this

**Comment by manusfreedom** [comment]
After deploying the latest git, it's solved.

Thanks.
