### ISSUE TITLE
fresh install faillure with docker-compose 

### ISSUE THREAD

**Issue by aioaio3211** [nilsteampassnet/TeamPass#4500]
Installation made using docker-compose. Image used dormancygrace/teampass:latest
Teampass version: 3.1.2
Initial setup...
**Initial errors:**

Changed current directory to /root/.composer
Cannot use hirak/prestissimo's latest version 0.3.10 as it requires php ^5.3.2 || ^7.0 which is not satisfied by your platform.

Installation failed, deleting ./composer.json.

In RequireCommand.php line 225:

  No composer.json present in the current directory (./composer.json), this m
  ay be the cause of the following exception.

In PackageDiscoveryTrait.php line 317:

  Package hirak/prestissimo has requirements incompatible with your PHP versi
  on, PHP extensions and Composer version:
    - hirak/prestissimo 0.3.10 requires php ^5.3.2 || ^7.0 which does not mat
  ch your installed version 8.2.7.
    - hirak/prestissimo 0.3.10 requires composer-plugin-api ^1.0.0 which does
   not match your installed version 2.3.0.
---------------------
**[ERROR] Answer from server is empty.**
**Fixed by:**
**Added to make it install /var/www/html/includes/config/settings.php**
define("SECUREPATH", "/var/www/html/sk");
define("SECUREFILE", "teampass-seckey.txt"); 

After the installation is "completed" doesn't redirect to login page, if I restart the container It does but in maintenace mode. Seems the installation fails. Deactivating maintenace mode for type admin at misc table doesn't allow me to login neither.
**ERROR1: As soon as I press "next"**
![image](https://github.com/user-attachments/assets/5a620b60-ec1f-4b17-be31-3a10fcfcd3d2)

PHP Fatal error:  Uncaught MeekroDBException: Unable to connect to MySQL server! Error: No such file or directory in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:228
Stack trace:
#0 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(919): MeekroDB->get()
#1 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper(Array, Array)
#2 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(490): MeekroDB->query('UPDATE `misc` S...')
#3 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->update('misc', Array, 'type = "admin" ...')
#4 /var/www/html/sources/scheduler.php(50): DB::__callStatic('update', Array)
#5 {main}
  thrown in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php on line 228

Fatal error: Uncaught MeekroDBException: Unable to connect to MySQL server! Error: No such file or directory in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php on line 228

MeekroDBException: Unable to connect to MySQL server! Error: No such file or directory in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php on line 228

Call Stack:
    0.0002     417016   1. {main}() /var/www/html/sources/scheduler.php:0
    0.0295    4389048   2. DB::update('misc', ['valeur' => 1732723380], 'type = "admin" AND intitule = "last_cron_exec"') /var/www/html/sources/scheduler.php:50
    0.0295    4389264   3. DB::__callStatic($name = 'update', $args = [0 => 'misc', 1 => ['valeur' => 1732723380], 2 => 'type = "admin" AND intitule = "last_cron_exec"']) /var/www/html/sources/scheduler.php:50
    0.0296    4389928   4. MeekroDB->update('misc', ['valeur' => 1732723380], 'type = "admin" AND intitule = "last_cron_exec"') /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:116
    0.0297    4390368   5. MeekroDB->query('UPDATE `misc` SET `valeur`=1732723380 WHERE type = "admin" AND intitule = "last_cron_exec"') /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:490
    0.0297    4390584   6. MeekroDB->queryHelper($opts = ['assoc' => TRUE], $args = [0 => 'UPDATE `misc` SET `valeur`=1732723380 WHERE type = "admin" AND intitule = "last_cron_exec"']) /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:890
    0.0297    4390832   7. MeekroDB->get() /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:919

![image](https://github.com/user-attachments/assets/98fabcb5-9855-4061-8624-f6daeeb3baec)

ERROR 500 index.php

*******- - [27/Nov/2024:16:05:30 +0000] "GET /favicon.ico HTTP/1.1" 200 15406 "https://USEDIP/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Defuse\Crypto\Exception\WrongKeyOrModifiedCiphertextException: Integrity check failed. in /var/www/html/vendor/defuse/php-encryption/src/Crypto.php:378"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "Stack trace:"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#0 /var/www/html/vendor/defuse/php-encryption/src/Crypto.php(117): Defuse\Crypto\Crypto::decryptInternal('\xDE\xF5\x02\x00\xC2~\xCAunOJ\xDEF\x15}...', Object(Defuse\Crypto\KeyOrPassword), false)"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#1 /var/www/html/vendor/teampassclasses/sessionmanager/src/EncryptedSessionProxy.php(66): Defuse\Crypto\Crypto::decrypt('def50200c27eca7...', Object(Defuse\Crypto\Key))"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#2 [internal function]: TeampassClasses\SessionManager\EncryptedSessionProxy->read('9p4ihbh33njfe01...')"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#3 /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(172): session_start()"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#4 /var/www/html/vendor/symfony/http-foundation/Session/Session.php(59): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start()"
[27-Nov-2024 16:05:57] WARNING: [pool www] child 79 said into stderr: "#5 /var/www/html/vendor/teampassclasses/sessionmanager/src/SessionManager.p..."
******* - - [27/Nov/2024:16:05:57 +0000] "GET /index.php HTTP/1.1" 500 5 "https://USEDIP/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

At this point if i restart the container I get the following error:

Changed current directory to /root/.composer
Cannot use hirak/prestissimo's latest version 0.3.10 as it requires php ^5.3.2 || ^7.0 which is not satisfied by your platform.

Installation failed, deleting ./composer.json.

In RequireCommand.php line 225:

  No composer.json present in the current directory (./composer.json), this m
  ay be the cause of the following exception.

In PackageDiscoveryTrait.php line 317:

  Package hirak/prestissimo has requirements incompatible with your PHP versi
  on, PHP extensions and Composer version:
    - hirak/prestissimo 0.3.10 requires php ^5.3.2 || ^7.0 which does not mat
  ch your installed version 8.2.7.
    - hirak/prestissimo 0.3.10 requires composer-plugin-api ^1.0.0 which does
   not match your installed version 2.3.0.

![image](https://github.com/user-attachments/assets/d8e3498e-0223-49b8-bc08-215a1623bc77)
Maintenace mode enabled (using admin account), if I disable the maintenace mode from misc table still cannot login.

**Comment by vince-38** [comment]
I have exactly the same problem

**Comment by aioaio3211** [comment]
After the recent pull, installation seems to be working fine. @vince-38 try it now it should be fine, it worked well for me
