### ISSUE TITLE
Creating Share Keys take forever

### ISSUE THREAD

**Issue by Saueee** [nilsteampassnet/TeamPass#4524]
Latest release 3.1.3.1
I currently have the problem that newly created items never finish creating the sharekey.
They hang forever and only the creator is able to see the password.
In Admin -> Tasks -> in progress they are listed and never finish.
Same happening if you update the password.
Please let me know what information/logs you need.

![grafik](https://github.com/user-attachments/assets/41279ddc-b953-4239-992e-1d3080d50bcf)

Further the Frequency of "User keys management" shows no timestamp, so I guess its not running?
![grafik](https://github.com/user-attachments/assets/12253f87-f182-49cf-9127-9132c39cba5a)

**Comment by B3XAL** [comment]
Use this command to try to unclog it:

`/usr/bin/php /var/www/html/sources/scheduler.php`

if this works, the problem is in your cron.
