### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jamesg1992** [nilsteampassnet/TeamPass#4530]
Hi,

I have teampass version 3.1.3.1 and when i import the CSV format correctly
i select the folder to import the users

it open a popup with a spinning wheel "please wait" and in the apache2 error log there is :

PHP Fatal error:  Uncaught TypeError: htmlspecialchars_decode(): Argument #1 ($string) must be of type string, int given in /var/www/html/TeamPass/sources/import.queries.php:1065\nStack trace:\n#0 /var/www/html/TeamPass/sources/import.queries.php(1065): htmlspecialchars_decode()\n#1 [internal function]: cleanOutput()\n#2 /var/www/html/TeamPass/sources/import.queries.php(347): array_walk_recursive()\n#3 {main}\n  thrown in /var/www/html/TeamPass/sources/import.queries.php on line 1065, referer: http://teampass.xxx.xx/index.php?page=import

How to resolve this problem?

Thanks

**Comment by jamesg1992** [comment]
i have resolved the import modify import.queries.php in the line 1066

function cleanOutput(&$value)
{
    if (is_string($value)) {
        // Only decode if $value is a string
        $value = htmlspecialchars_decode($value);
    } else {
        // If not a string, convert to string (optional: or handle it differently)
        $value = (string) $value;  // Convert value to string to avoid errors
    }
}

**Comment by PawelDevOps** [comment]
Thanks a lot @jamesg1992 that helped me import my passwords from CSV file that had 720 passwords.
