### ISSUE TITLE
Disable limited search globally

### ISSUE THREAD

**Issue by jernej65** [nilsteampassnet/TeamPass#4531]
### Steps to reproduce
1. Update teampass to latest - 3.1.3.1, setup "disable limited search by default" in settings.
2. Login with user
3. Search for iteam globally, but limited search is enabled.

### Expected behaviour
Disable limited search globally for all users.

### Actual behaviour
"Disable limited search by default" in settings, but when selecting folder, limited search is checked again.

### Server configuration
**Operating system**:
Rocky Linux 9.4
**Web server:**
Nginx
**Database:**
MariaDB 10.5.16
**PHP version:**
PHP 8.1
**Teampass version:** 
3.1.3.1

**Comment by corentin-soriano** [comment]
@nilsteampassnet I think this can be closed. The fix you provided seems to work as expected.
