### ISSUE TITLE
Disable recovery key download for users.

### ISSUE THREAD

**Issue by jernej65** [nilsteampassnet/TeamPass#4532]
### Steps to reproduce
1. Login to Teampass with user
2. Download the recovery keys with that user

### Expected behaviour
Tell us what should happen
In setting i would like to have option to disable recovery keys download for users. Because i don't trust users to save the recovery key.

### Actual behaviour
Now every user must download recovery key, and save it on their PC if they don't what to have red download icon on top left corner

### Server configuration
**Operating system**:
Rocky 9.4
**Web server:**
nginx
**Database:**
MariaDB
**PHP version:**
PHP 8.1
**Teampass version:** 
3.1.3.1

**Comment by corentin-soriano** [comment]
This is a very bad idea if you use the personal folder feature as keys are the only way to recover personal passwords if the user has forgotten their login password.

If that's really what you want, you can add the `d-none` class to `#open_user_keys_management` (index.php) to hide it immediately.
```php
                    <span class="fa-stack infotip pointer hidden mr-2 d-none" title="<?php echo $lang->get('get_your_recovery_keys'); ?>" id="open_user_keys_management" style="vertical-align: top;">
```

However I think it would be better to train users to keep them in a safe place.

@nilsteampassnet your opinion on this feature?

**Comment by nilsteampassnet** [comment]
For my point of view, I would have the same advice as Corentin.
Removing this is not a good practice.
You should discipline the users to perform this task, otherwize not complaining about loosing their data in case of password loose.
But regarding Teampass, I don't think adding such option is relevant.
As suggested, you can hide it by doing the change manually inside the code

**Comment by jernej65** [comment]
Hi,
Thanks for answer. But if we have disabled personal folder feature, I think download personal keys option should be disabled? Isn't the personal key just for personal folder recovery? 
Any hints where can i disable that in code? Tnx and merry christmas!

**Comment by corentin-soriano** [comment]
You can add the d-none class to `#open_user_keys_management` (index.php) to hide the red bell.
&lt;span class="fa-stack infotip pointer hidden mr-2 **d-none**" title="<?php echo $lang->get('get_your_recovery_keys'); ?>" id="open_user_keys_management" style="vertical-align: top;">
