### ISSUE TITLE
Infinite update nested_tree nleft and nright

### ISSUE THREAD

**Issue by DobroFenix** [nilsteampassnet/TeamPass#4533]
### Steps to reproduce
1. Clear install 5.1.3.1
2. Import all LDAP users
3. Start create private folder

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Operating system:
RHEL 8

Web server:
nginx 1.14.1
Database:
MySQL 15.1

PHP version:
8.3.14 (php-fpm, user:nginx)
Teampass version:
5.1.3.1

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
No error

top:
![image](https://github.com/user-attachments/assets/b4f6bfdd-d06b-4a29-ac89-69d947075ccd)

Records are updated indefinitely:
![image](https://github.com/user-attachments/assets/9cad98f0-5cf1-4c50-83e0-6c2787c7f93d)
![image](https://github.com/user-attachments/assets/603d25cc-0a8d-4378-bc92-a6c712a2b284)
![image](https://github.com/user-attachments/assets/bea746a1-b124-4e91-9690-8b54e1b1e590)

**Comment by corentin-soriano** [comment]
Seems to be related to #4456
Can you check if this fix is present on your `vendor/teampassclasses/nestedtree/src/NestedTree.php` file?

**Comment by DobroFenix** [comment]
Yes
![image](https://github.com/user-attachments/assets/9c4205b6-61fd-4017-a2de-086e6e7f7065)

I've been waiting a long time and it seems to have stopped updating something endlessly.
