### ISSUE TITLE
Export items Offline doesn't work

### ISSUE THREAD

**Issue by blastik** [nilsteampassnet/TeamPass#457]
It stays like that forever

![image](https://f.cloud.github.com/assets/3662083/1764667/2959ead0-672a-11e3-908f-3acc82393153.png)

Thanks!
D.

**Comment by mr-gosh** [comment]
This problem still is present... in our 2.1.23 installation... :(

**Comment by nilsteampassnet** [comment]
Certainly but I don't have time to maintain each version.
I suggest to migrate to 2.1.26
