### ISSUE TITLE
V2.1.19 Offline export: Feature Request

### ISSUE THREAD

**Issue by eczema** [nilsteampassnet/TeamPass#487]
Works slowly but it works....
One useful improvement: add an anchor to each entry and use it because when a password is revealed, the browser return to the beginning of the page and for long items list, it is a little bit annoying...

**Comment by necarnot** [comment]
Hello Nils,

I'm trying to use offline mode to create an HTML file, using teampass 2.1.25 and I'm also getting 500 internal error : 
`POST http://teampass/sources/export.queries.php 500 (Internal Server Error)
send	@	jquery.js:8706
jQuery.extend.ajax	@	jquery.js:8136
jQuery.(anonymous function)	@	jquery.js:8282
generateOfflineFile	@	VM1881:84
$.dialog.buttons.Générer le fichier en mode hors ligne	@	index.php?page=items:4608
s.click	@	jquery-ui.min.js:11
jQuery.event.dispatch	@	jquery.js:5095
elemData.handle	@	jquery.js:4766`

In apache log, I see : 
192.168.xx.xx - - [08/Apr/2016:16:13:08 +0200] "GET /items.offline.php?key=fsRE1hRqsHAOYYz7qvqbxzfFLpjbeZaV6HWb1ZP0qI.ds5jW6T HTTP/1.1" 200
 11562
192.168.xx.xx - - [08/Apr/2016:16:13:24 +0200] "POST /sources/export.queries.php HTTP/1.1" 500 -

I tried to use the /usr/share/teampass/includes/libraries/csrfp/libs/csrfp.config.php modification of jsURL, but I still get the 500 error message.

I tried with Chrome and Firefox.

I double checked to max execution time of apache was 300.
I tried to check only one small folder.

I still get the same error message.

What can I check or debug to add?
