### ISSUE TITLE
Unable to create new entries

### ISSUE THREAD

**Issue by deserted** [nilsteampassnet/TeamPass#523]
I've got an odd issue as per the image below.

It occurs seemingly randomly, after a period of time.  I've created a number of folders and added items to them successfully, after completing 19 entries successfully I received this error, it applies to all folders and continues to occur after a logout/login

I've had a look at the database, no issues visible in tables.

Nothing is generated in the logs when this occurs.

Password complexity is being met (very weak required by both role and folder, weak password used)

when this first happened, I deleted folders and recreated the tree, after which it started working again, until failing on the 20th item.

The first time I was only able to create 1 item before receiving the error

![teampass error](https://f.cloud.github.com/assets/4506109/2443721/e2ce3f66-ae3d-11e3-8ad2-bed52e7d749f.png)

**Comment by VaIar** [comment]
Hi I got the same issue with fresh install of 2.1.23. I suppose somebody tried to upload .CSV. And now I can't create anything even in new folder:
![teampass_2 1 23_error](https://cloud.githubusercontent.com/assets/12380263/12494868/9c006658-c09d-11e5-84cb-366d1505bbaf.PNG)
Even I deleted all folders :(
Please help, is there any way to recover the application?

**Comment by nilsteampassnet** [comment]
Can you provide the error in apache log?

**Comment by VaIar** [comment]
With pleasure, but can't find it. I use XAMP and can't find apache2 folder in /var/log/ as well as in the /etc/ to check how apache log is configured. Do you have any ideas where to look?

**Comment by nilsteampassnet** [comment]
Most of the time in /var/log/httpd I think

Can you provide me an access with Teamviewer?

**Comment by VaIar** [comment]
Hi Nils, sorry for delay. Thanks for your willingness to help. Here you go:

ID: 953522657
Pass: 1273

I'll send you OS credentials in private message

**Comment by VaIar** [comment]
Didn't find how to send it. Use root/$ul_fUr16 i'll change it later.

**Comment by VaIar** [comment]
Are there any news?

**Comment by VaIar** [comment]
Hi Nils. I going to reinstall the teampass in case you not going to use TeamViever
