### ISSUE TITLE
2.1.19 DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#544]
I fixed this by applying the same edit I had to do on version 2.1.16.

find.queries.php
line 193
From: 
$sOutputItem .= '"'.substr(stripslashes(preg_replace('/<[^>]_>|[\t]/', '', $txt)), 0, 50).'", ';
To: 
$sOutputItem .= '"'.substr(stripslashes(preg_replace('/<[^>]_>\//|[\t]/', '', $txt)), 0, 50).'", ';

**Comment by mobilefactor** [comment]
I applied this change on Version 2.1.22 and it works!!!  Thanks!
