### ISSUE TITLE
Problem with the password length [2.1.4]

### ISSUE THREAD

**Issue by d4rknigh7** [nilsteampassnet/TeamPass#61]
Hello,

there's a problem with passwords, which are longer then 40 characters.

Description:
It's possible to create an entry with a password longer then 40 characters.
But after creating the entery it's impossible to open it.

Can you please increase the limitation of the password length?
###### 

sources/items.queries.php: 
line 91
                if(strlen($pw)>40){

line 341:
                if(strlen($pw)>40){

**Comment by agh1467** [comment]
In version 2.1.2 this is possible. I have created passwords of more than 40 in length, and also been able to retrieve them.

Has this request been taken into design of newer versions? I'm attempting to use 2.1.22 currently, but the password length limitation is a blocker.
