### ISSUE TITLE
Multi Domain LDAP

### ISSUE THREAD

**Issue by tomikais** [nilsteampassnet/TeamPass#637]
Is it possible to do multi domain login?

https://github.com/nilsteampassnet/TeamPass/pull/594

https://github.com/tomikais/TeamPass/commit/8fc4c467fe1c4065841218bf98892f42f560c270

regards, thomas

**Comment by fallen-up** [comment]
How to configure Multi Domain LDAP?
Please, see examples:
- ldap2 - works
![ldap2](https://cloud.githubusercontent.com/assets/11389898/6556220/1613d0ae-c67d-11e4-9e99-240f48e595a8.png)

- ldap1 - doesn't work
![ldap1](https://cloud.githubusercontent.com/assets/11389898/6556229/2bd27256-c67d-11e4-84ba-d574f554c3ed.png)

**Comment by fallen-up** [comment]
?
