### ISSUE TITLE
Feature Request - Additional Password Field

### ISSUE THREAD

**Issue by A1den** [nilsteampassnet/TeamPass#645]
Would it be possible to have the ability to specify that a custom field is a password field?

This is so that the field would have the ability to show/hide any additional passwords.

Many thanks!

Aiden

**Comment by ElAutoestopista** [comment]
+1 this would be great!

**Comment by nilsteampassnet** [comment]
This has been implemented a long time ago.
It is called "Categories" and is set up from the "Settings" page.
[Read more](http://teampass.net/2013-03-25-custom-categories-and-fields/)

**Comment by A1den** [comment]
So with the custom field will it allow it to be masked as with the normal password field? With the show/hide password function. 

Aiden

**Comment by ElAutoestopista** [comment]
@nilsteampassnet what we mean is, as @A1den said, if a custom field could be presented masked as the password field is, so it's necessary click on it to display content.
