### ISSUE TITLE
Can't Create Folder as User

### ISSUE THREAD

**Issue by griever2001** [nilsteampassnet/TeamPass#656]
Hi Guys,

i have a little Problem with my teampass installation. As normal User i have the dialogue to add a new folder but when i try to save it ... nothing happens.

Following Options are "on":
- Users are allowed to manage folders in allowed parent folders  
- Authorize new folder to be created at Root level

Also the the group has the permission on the folder and the user has the permission to create folders add root level.

dialogue:
![screenshot](https://cloud.githubusercontent.com/assets/8359961/3807878/bf65a4f2-1c6e-11e4-82ae-0026e973d3db.png)

The Apache Errorlog says:
<code>
[Tue Aug 05 09:02:07 2014] [error] [client 192.168.96.19] PHP Notice:  Use of undefined constant ERR_NOT_ALLOWED - assumed 'ERR_NOT_ALLOWED' in /var/www/teampass/sources/folders.queries.php on line 28, referer: https://<host>/teampass/index.php?page=items
[Tue Aug 05 09:02:07 2014] [error] [client 192.168.96.19] PHP Warning:  include(error.php): failed to open stream: No such file or directory in /var/www/teampass/sources/folders.queries.php on line 29, referer: https://<host>/teampass/index.php?page=items
[Tue Aug 05 09:02:07 2014] [error] [client 192.168.96.19] PHP Warning:  include(): Failed opening 'error.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/teampass/sources/folders.queries.php on line 29, referer: https://<host>/teampass/index.php?page=items
</code>

For example managers can add new folders.

Teampass: Branch Release_2.1.20
OS: Debian 7.5

Any Suggestions?

Regards
Kay

**Comment by DamienOReilly** [comment]
HI, I am seeing the exact same issue. My scenario is the same as:
> As normal User i have the dialogue to add a new folder but when i try to save it ... nothing happens.
> 
> Following Options are "on":
> 
> Users are allowed to manage folders in allowed parent folders
> Authorize new folder to be created at Root level
> Also the the group has the permission on the folder and the user has the permission to create folders add root level.

However the only difference is, I'm not getting anything meaningful in apache access/error logs.

How can I assist in getting this resolved?
I'm running version 2.1.23 on RedHat 6

Thanks,
Damien.

**Comment by lukasbisdorf** [comment]
I have the same behaviour like @DamienOReilly. Users can't create folders, and nothing is logged...

**Comment by giosdas** [comment]
Same Problem. You need to go on Settings Page -> Customize 
and enable this feature:
Users are allowed to manage folders in allowed parent folders
I have enable also this "Users are allowed to manage folders in allowed parent folders"
