### ISSUE TITLE
Blank screen after install

### ISSUE THREAD

**Issue by raquel3rs** [nilsteampassnet/TeamPass#659]
Hello!
I Installed succesfully but it displays a blank page when accessing the website.

Error log returns:
PHP Warning: require_once(/includes/language/english.php): failed to open stream: No such file or directory in /var/www/teampass/sources/core.php on line 71

PHP Fatal error: require_once(): Failed opening required '/includes/language/english.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/teampass/sources/core.php on line 71

But I checked and the file exists! Any help please?

Thank you!

**Comment by FacundoAcevedo** [comment]
This bug is still active.
