### ISSUE TITLE
API - User rights

### ISSUE THREAD

**Issue by manu-l** [nilsteampassnet/TeamPass#674]
Hello,

I'm trying to create a Firefox extension to auto-fill the input credentials (login+password) when navigating on Internet (like the lastpass extension but at my level: very simple).
I've added a new functionality in api/functions.php to retrieve credentials from an url.
My problem is that when calling the API, there is no right management and I give access to the entire database and not only the user database. 
In fact, I would to restrict the API scope to calling user rights (which should be logged in?)
Did you plan to develop something similar or did you already have developed it?
I've started to code a little extension that seems working and I'd like to go further.

Thanks

Below my code modification in api/functions.php (if you have an idea to restrict the available items). I inserted the following code at line 277 : 

```
elseif($GLOBALS['request'][1] == "url") {
            $required_url = $GLOBALS['request'][2];
            $json['sites'] = array();

            $response = $bdd->query("select id,label,login,pw,id_tree from ".$GLOBALS['pre']."items where url LIKE 'http%://".$required_url."'");
            while ($data = $response->fetch())
            {
                $site_array = array(
                    'id' => $data['id'],
                    'label' => utf8_encode($data['label']),
                    'login' => utf8_encode($data['login']),
                    'password' => teampass_decrypt_pw($data['pw'],SALT,$rand_key)
                );  
                array_push($json['sites'], $site_array);
            }
        }
```

**Comment by mbrodala** [comment]
I'd rather have the password optional here. If the administrator generates a separate API key for each user, this is enough authentication already. This would avoid sending cleartext passwords over the line which the user also needs to be prompted for.
