### ISSUE TITLE
Two-Factor window setting

### ISSUE THREAD

**Issue by LIV2** [nilsteampassnet/TeamPass#675]
Hi,

Most software allowing the use of TOTP tokens also allows you to set a window size, what this does is sets how many codes ahead/behind you are allowed to use and still log in.

This is because clock skew will stop people from getting in, probably not a huge issue for most people (as long as their carriers have correct clock sync) but I did have a user unable to log in due to this.

Is it possible to get such a feature added?

**Comment by affinityv** [comment]
Better to add in functionality to allow the presentation of OTP by TeamPass itself and not rely upon the GA app.  TOTP is well defined, there is a nice TrayTOTP plugin [1] for KeePass and I've coded one up in python some time ago.  I use TOTP with WP admin [3] as well, KP lets me auto-type in username/password and the TOTP number.  Looking to replace KP, need this extra functionality built-in to the password manager (not just to access it).  My only problem with KP is the Linux implementation is not working for TOTP and the whole mono based "work around" makes KP much less usable on Linux; it works really well on Windows though, but I am trying to migrate as much as possible away from M$ products or from relying on any third parties for that matter (including Google).

A fix for time skewing is to have TOTP be able to sync it's time with that of the relevant server that is expecting the TOTP number.  This is a TOTP setting for Dropbox, for example "30;6;http://dropbox.com" -- that means, 30 seconds per code, want 6 digits and time sync with the dropbox server.  The only other required setting is the actual TOTP Seed code that is specific to the user's account.

I also use QR Code Generator plugin [2] with KP -- those are the only two plugins that I would like to be implemented with TP....

[1] http://keepass.info/plugins.html#traytotp
[2] http://keepass.info/plugins.html#qrcodegen
[3] https://wordpress.org/plugins/wp-google-authenticator/
