### ISSUE TITLE
Troubles to install TP-2.1.21 on local WampServer 2.5

### ISSUE THREAD

**Issue by tigrawka** [nilsteampassnet/TeamPass#704]
Hello! Sorry if I wrote something wrong. I am try to comment on github first time. I tried to install each version from 2.1.18, but the installation has all times failed by the other reasons. Now, I load the last version from GitHub and try again.
Platform characteristic: Apache 2.4.9, PHP 5.5.12, MySQL 5.6.17
The step 1 and step 2 is successful, but step 3 I have a message
The next ERROR occurred: '/includes is not a Directory!' Please correct and relaunch.
I set value: D:\teampass\tp_21\ in the field "Absolute path to SaltKey"
Can someone help me?

**Comment by knpc** [comment]
hi,

I have tje same problem, Do you have a solution ?

Thanks

**Comment by ihbo** [comment]
Hi!

mkdir /includes
chmod 0755 /includes
chown www-data:www-data /includes

it's fix bug!

**Comment by ihbo** [comment]
For win similarly
