### ISSUE TITLE
clipboard copy issues

### ISSUE THREAD

**Issue by billu260** [nilsteampassnet/TeamPass#708]
Hi,

I recently upgraded Teampass from 2.1.18 to 2.1.20. I actually moved it to a new virtual server to avoid problems with the old version. Once upgraded, I am having trouble with the copy to clipboard buttons. The strange thing is that it works for me on some computers with some browsers but fails on other computers with the same browsers.

On the computers where it is broken, it seems to be broken for all browsers. So far I have been using it with the latest versions of Chrome, Firefox, and Palemoon. Based on previous posts by other users I thought maybe this was a Flash problem on the problem computers. I have checked and all computers are using the same browser and flash versions but only some are broken.

I do use Teampass on multiple computers or with multiple browsers on the same computer with the same login at the same time. With the 2.1.18 version, this never seemed to be an issue and I don't know if it is causing the problems now.

I am also getting various error messages in the Apache log files. I would include a sample of today's errors but I am not sure what is the best way to post them. Assuming you would like to look at the logs, what is the best way to add them to this post?

Also, if you would like more detail, please let me know what you are looking for.

Thanks,
Bill

**Comment by zuernBernhard** [comment]
Same problem here. Mostly on Linux-Boxes. Mac and Windows seem to work.
