### ISSUE TITLE
Import csv does not import

### ISSUE THREAD

**Issue by Marnijt** [nilsteampassnet/TeamPass#712]
So i'm trying to import a csv file which syntax is found to be ok but import never starts. 
I'm using:
CentOS6
TeamPass 2.1.20

Steps to reproduce:
- Enable importing as admin
- Login as normal (in my case a manager) user
- Click "Import items from file"
- Click "Browse csv file"

Then a strange thing happens and 2 open dialogs popup. So i:
- Select the same file in both dialogs (but tried al combinations like selecting the file in only the first or second dialog, etc.)
- Click "import"

I  do see a little progressbar but nothing happens. Any ideas?

**Comment by shashank-ganesha** [comment]
I seem to have the same problem with 2.1.23, my csv file is as follows

"Label","Login","Password","WebSite","Comments"
"GenericBank#1","jdoe","superS3cret","https://www.genericbank.com","Checkingaccounts,etc"

**Comment by hansellvp** [comment]
I enabled the option to import CSV and Keepass from admin settings page and I do not get the option to import in the folder menu. What I do?
