### ISSUE TITLE
Install issue 2.1.21 (ubuntu 14.04 LAMP)

### ISSUE THREAD

**Issue by techsolo** [nilsteampassnet/TeamPass#715]
Install hangs on tables creation without error on the frontend but I found this in the apache-log:

[Tue Sep 30 10:26:53.899252 2014] [:error] [pid 15652] [client 172.16.1.104:48483] PHP Fatal error:  Call to undefined function mysqli_fetch_all() in /var/www/TeamPass-Release_2.1.21/install/install.queries.php on line 164, referer: https://pm.novit/install/install.php

PHP 5.5.9+dfsg-1ubuntu4.4

With following as a reference http://stackoverflow.com/questions/11664536/fatal-error-call-to-undefined-method-mysqli-resultfetch-all

**Comment by acidocitrico** [comment]
Same problem here
I tried installing installing php5-mysqlnd (debian) but there are a lot of dependencies and it wont let me install
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 mysql-server-5.5 : Depends: mysql-client-5.5 (>= 5.5.41-0+wheezy1) but 5.5.38-0+wheezy1 is to be installed
                    Depends: mysql-server-core-5.5 (>= 5.5.41-0+wheezy1) but 5.5.38-0+wheezy1 is to be installed
                    PreDepends: mysql-common (>= 5.5.41-0+wheezy1) but 5.5.38-0+wheezy1 is to be installed
                    Breaks: mysql-server (< 5.5.41-0+wheezy1) but 5.5.38-0+wheezy1 is to be installed
 php5-mysql : Conflicts: php5-mysqlnd but 5.4.36-0+deb7u3 is to be installed
 php5-mysqlnd : Depends: php5-common (= 5.4.36-0+deb7u3) but 5.4.4-14+deb7u7 is to be installed
                Conflicts: php5-mysql but 5.4.4-14+deb7u7 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by ychoucha** [comment]
same problem, on ubuntu 14.04 LTS,
no way to install PHP function "mysqli_fetch_all" is available   Function mysqli_fetch_all is not available!

**Comment by candymanuu** [comment]
same problem on Debian 6.0.10, when trying to install TeamPass, I get to the server checks screen and receive this error:

Following elements will be checked:

Directory "/install/" is writable 
Directory "/includes/" is writable 
Directory "/includes/avatars/" is writable 
Directory "/files/" is writable 
Directory "/upload/" is writable 
PHP extension "mcrypt" is loaded 
PHP extension "mbstring" is loaded 
PHP extension "openssl" is loaded 
PHP extension "bcmath" is loaded 
PHP extension "iconv" is loaded 
PHP function "mysqli_fetch_all" is available   Function mysqli_fetch_all is not available!
PHP version is greater or equal to 5.3.0

**Comment by peppeska** [comment]
same problem

**Comment by ausiddiqui** [comment]
PHP Version 5.5.9-1ubuntu4.14 on Ubuntu 14.04 Server LTS

Edited my php.ini file to include the line: "extension=mysqli.so", verified the mysqli.so file existed in my extensions directory. Also tried using the full path of the extension directory. But each time I received the same error regarding mysqli_fetch_all:

Following elements will be checked:

Directory "/install/" is writable 
Directory "/includes/" is writable 
Directory "/includes/avatars/" is writable 
Directory "/files/" is writable 
Directory "/upload/" is writable 
PHP extension "mcrypt" is loaded 
PHP extension "mbstring" is loaded 
PHP extension "openssl" is loaded 
PHP extension "bcmath" is loaded 
PHP extension "iconv" is loaded 
PHP extension "xml" is loaded 
PHP function "mysqli_fetch_all" is available   Function mysqli_fetch_all is not available!
PHP version is greater or equal to 5.4.0 
Execution time limit  PHP "Maximum execution time" is set to 0 seconds. Please try to set to 60s at least

**Comment by GaneshKandu** [comment]
Hi, Getting Same Error
![screenshot-192 168 58 139 2016-01-11 15-12-43](https://cloud.githubusercontent.com/assets/12833130/12230338/d7b19f58-b875-11e5-9b5a-921236f0f556.png)
