### ISSUE TITLE
can't create folders

### ISSUE THREAD

**Issue by nemesis545** [nilsteampassnet/TeamPass#719]
nothing happens when i try to create a new folder from a common user, the apache's logs show this :

> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 57, referer: https://teampass.local/index.php?page=itemsa
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 59, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/folders.queries.php on line 45, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/folders.queries.php on line 47, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/index.php on line 54, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/index.php on line 56, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 57, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:25 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 59, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:33 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 57, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:33 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/checks.php on line 59, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:33 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/items.queries.php on line 65, referer: https://teampass.local/index.php?page=items
> [Fri Oct 03 15:31:33 2014] [error] [client 192.168.1.2] PHP Notice:  Undefined variable: port in /var/www/sources/items.queries.php on line 67, referer: https://teampass.local/index.php?page=item

**Comment by agh1467** [comment]
I'm running into a similar issue with respect to a user creating folders. There are no errors that appear, and the folder is not created.

I'm trying to identify what options are available to me to get some logs of the issue, but am not able to find anything other than the LogLevel in apache2.

This is on a clean install of the branch Release_2.1.22.

I'm able to create folders through folders management as admin.

**Comment by Karunamon** [comment]
I'm getting this on a clean install of 2.1.26. Logged in as the administrator user, I go to create a folder, and just get the "please wait" spinner. No web or PHP errors logged.

**Comment by Karunamon** [comment]
Disregard - this was caused by leaving the "root folder" box blank. An error would probably be more ideal here, but it's not broken :)
