### ISSUE TITLE
Export password to file

### ISSUE THREAD

**Issue by miscaandrei** [nilsteampassnet/TeamPass#731]
How can I export my passwords from teampass to a file. I want it so I can print it and save a physical copy just in case.

**Comment by skiglades** [comment]
Related to #758 

Running version 2.1.20 and hitting max execution time when exporting all available items.

PHP Fatal error: Maximum execution time of 60 seconds exceeded in C:\wamp\www\TeamPass-master\sources\main.functions.php on line 39, referer: https://hostname/teampass-master/index.php
PHP Stack trace:, referer: https://hostname/teampass-master/index.php
PHP 1. {main}() C:\wamp\www\TeamPass-master\sources\export.queries.php:0, referer: https://hostname/teampass-master/index.php
PHP 2. decrypt() C:\wamp\www\TeamPass-master\sources\export.queries.php:84, referer: https://hostname/teampass-master/index.php
PHP 3. strHashPbkdf2() C:\wamp\www\TeamPass-master\sources\main.functions.php:182, referer: https://hostname/teampass-master/index.php

**Comment by mr-gosh** [comment]
On 2.1.23 meanwhile - still the same problem... :-(

**Comment by eferlin** [comment]
The option to export passwords does not appear anywhere in TeamPass 3, even though it is enabled in the panel with the administrator user.
