### ISSUE TITLE
can't instal hangs at server checks

### ISSUE THREAD

**Issue by danbuntu** [nilsteampassnet/TeamPass#741]
I'm trying to install teampass onto an ubuntu 14.10 server

In the second screen is get the screenshot below

The next button is disabled and the launch button just says please wait and hangs.

The folder has been chmoded to 777 and as far as I know the php extensions are installed - I was expecting to see ticks or something against the items.

In the chrome developer console is can see:

Uncaught SyntaxError: Unexpected token < 

when I click launch

![image](https://cloud.githubusercontent.com/assets/688626/4700564/66c37808-584e-11e4-8edb-8fbc49595bed.png)

**Comment by thorink** [comment]
I can confirm this, too. I just want to mention, that the "Server Checks" page still hangs if mcrypt is not enabled. I use nginx and teampass version 2.1.22.

**Comment by xavier8854** [comment]
Hi, I found this old thread, koz I'm facing the very same problem.
php-mcrypt is deprecated (see https://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt) since RHEL5/CentOS5
So what is the solution ?
Cheers
Xavier
