### ISSUE TITLE
linux to windows Active Directory authentication

### ISSUE THREAD

**Issue by lanox** [nilsteampassnet/TeamPass#742]
Hi 
I have issue with my teampass authenticating with windows AD.
I have done tcpdump and I can see there is communication both way from server to AD and from AD back to teampass, however i still can't seem to login with my AD credentials.
Error message:
MYSQL error user_not_exists 
Also i have enabled openldap debug but messages are not getting logged to ldap.debug.txt

Any suggestions would be appreciated.

**Comment by cplvic** [comment]
I am using 2.1.22 fresh install. I am running into this issue after applying the patch. 
Windows 2003 AD
Sasically I have to create the user account before the user can login. Same mysql error message "user_not_exists".

**Comment by flix444** [comment]
+1 "user_not_exists" AD 2008

**Comment by VaIar** [comment]
Hi gyus. I'm not really pro in linux, but just finished Teampass setup and everything works fine besides LDAP authentication. I'm currently on Ubuntu 14.04.2 and teampass 2.1.23. If I enable LDAP authentication 
![tp_ldap](https://cloud.githubusercontent.com/assets/12380263/7553964/fdb78f5e-f71a-11e4-8bdb-c7fe30e45437.JPG)
Even my local users can't login with the error: Bad password for this account! Only admin user still works. If I disable LDAP - i can login with locla users immeditelly.

So two questions:
1. Does anybody have an Idea why local users stops working in case LDAP enabled?
2. How to apply patch above to fix an issue with LDAP users availability and message MySQLerror "user_not_exists"?

**Comment by adrianhalid** [comment]
Hi Valar,

Not sure about your question 1. I was having this issue too but not sure what resolved it.
First I deleted the offending user in Teampass.
I ensured all my LDAP settings were correct.
Turn Maintenance mode On. Save then turn off and save.
Closed all my browsers and logged in again.

But for Question 2 get the code for identify.php via the patch link below and replace it on your web server.
https://github.com/ebayer/TeamPass/blob/7fd9b541e612958e06ed5efdb523c5408730f2f4/sources/identify.php

I hope this helps.

**Comment by adrianhalid** [comment]
EBayer,
After applying the patch https://github.com/ebayer/TeamPass/blob/7fd9b541e612958e06ed5efdb523c5408730f2f4/sources/identify.php I had the following issue.

When a AD user logged in that did not exist in the Team Pass users table it correctly created the entry in the users table.

But the entire list of folders were visible. It did not restrict any access by role etc. This means that a new AD User has access to all passwords.

If they refresh the screen then the list of folders is correctly filtered.

The work around was to the option "Simplify the Items Tree by removing the Folders the user has no access to" to yes.

This seemed to fix the issue so that when a new AD user is logging in they do not automatically see all folders.

**Comment by KDennisOD** [comment]
"The work around was to the option "Simplify the Items Tree by removing the Folders the user has no access to" to yes." don't work for us.
Do you have any special options?

**Comment by adrianhalid** [comment]
We are using version 2.1.23 maybe something has changed in a newer version

**Comment by danielk76** [comment]
Hi,
I'm using TP 2.1.26 against AD ldap and all I can see is logs is user_not_exists
Does this patch mentioned above is still required for 2.1.26 version ?

**Comment by rokeno** [comment]
Can anyone tell me how to approach this patch?

I have little knowledge of php and i really don't know how to patch file identify.php.

Thanks

**Comment by aloisiobilck** [comment]
Hi Guys 
Where do I configure the password when using Windows / Active Directory?
