### ISSUE TITLE
TeamPass Offline generation not working

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#747]
The Offline Feature of Teampass is not getting to an end during exporting.

Is that a known problem or is it only my problem?

**Comment by N-Mi** [comment]
I have the same issue. I just upgraded to 2.1.23 and the problem is still here. I'm using Firefox.

**Comment by faregran** [comment]
Duplicated. See Issue 513

**Comment by mr-gosh** [comment]
duplicate of #513
