### ISSUE TITLE
export of "all" elements to an encrypted pdf not working

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#758]
the export of "all" elements to an encrypted pdf seems not to be working...

if only a few elements are selected it works, but if I try to export the whole database (for backup reasons for example) - it runs .... dead?!? (waited for over 10 minutes) without an errormessage...

**Comment by mr-gosh** [comment]
can anybody confirm this bug for 2.1.22 or is it worth an update?

**Comment by mr-gosh** [comment]
with 
count teampass_items
we get 434 Items in our database

**Comment by nilsteampassnet** [comment]
Witha  such high number of items, it is possible that max_execution_time is reached.
In 2.1.22, there has been an improvement on export feature which is to call a specific query for each item.
You can give it a try on a test domain.

**Comment by mr-gosh** [comment]
i'll do that...

**Comment by skiglades** [comment]
Running version 2.1.20 and hitting max execution time when exporting all available items.

PHP Fatal error:  Maximum execution time of 60 seconds exceeded in C:\\wamp\\www\\TeamPass-master\\sources\\main.functions.php on line 39, referer: https://hostname/teampass-master/index.php
PHP Stack trace:, referer: https://hostname/teampass-master/index.php
PHP   1. {main}() C:\\wamp\\www\\TeamPass-master\\sources\\export.queries.php:0, referer: https://hostname/teampass-master/index.php
PHP   2. decrypt() C:\\wamp\\www\\TeamPass-master\\sources\\export.queries.php:84, referer: https://hostname/teampass-master/index.php
PHP   3. strHashPbkdf2() C:\\wamp\\www\\TeamPass-master\\sources\\main.functions.php:182, referer: https://hostname/teampass-master/index.php

**Comment by mr-gosh** [comment]
so - we updated to 2.1.22 - and we still have the same problem.
we tried to export all items to html and to pdf...
we aborted the run after 10 minutes or so... :-(
we also tried to export a smaller subdirectory (with only about 150 entries) - that too failed...

**Comment by tiruser** [comment]
we are using Version 2.1.23 and have the same Problem :(
there are no entries in the Apache error log so i can't Point the Problem

i tried to Export one Folder with one Password but if i click on "Export items" i got the window "Export items" with a Spinning weel but nothing happens. i can click on "Export items" but nothing happens.
Just the button "Close" is working.

p.s.:
sorry for my bad english

**Comment by mr-gosh** [comment]
This Bug is still present in 2.1.23 - even the offline exporter doesn't finish.
also it's not possible to export just a subset of items - it never reaches finish state.
I'll try to update to 2.1.26 but I don't think this fixes it. :(

**Comment by nilsteampassnet** [comment]
please make a try.
It is successful in my test environment.
