### ISSUE TITLE
Only Managers can edit items

### ISSUE THREAD

**Issue by timbradmin** [nilsteampassnet/TeamPass#791]
Recently installed Teampass 2.1.21 on CentOS 7 and have discovered that only Managers are able to edit items.  

UPDATE: not entirely true.  Users can edit their OWN items but not each others.  Managers can edit all items.

Nothing in the Apache error log. 

Hopefully I'm missing something obvious.  I've been through all the configuration options but have been unable to figure out why. 

User has been assigned the appropriate Role and the Role has access to the folders.  

Great product by the way!  I've used older versions without issue and hoping that I can get this going at my new employer.

Thanks,

Rob

**Comment by DemisR** [comment]
Same problem with 2.1.22 .

**Comment by nilsteampassnet** [comment]
Does the role associated to the User​ have Write access on the folders
where the Items are?

**Comment by DemisR** [comment]
(Sorry for my bad English)
The user have Write access on folder. 
The button 'Edit Item' is visible but when click on them , popup does not open.
Popup appear only on self created items.

If change User to Manager , popup appear for all items.

**Comment by timbradmin** [comment]
I figured it out. 

- go to "Roles management" as an admin 
- under the Role Name there are three icons
- third icon looks like the "copy password" icon, hover over it for an explaination
- click that icon to change it green and users can edit items that they can view without requiring Manager

Hope this helps.

**Comment by DemisR** [comment]
Ok it works. Thank you, I hadn’t seen this option.

**Comment by DemisR** [comment]
I've test again with other user and not work.
User have write permissions on folder and  "copy password" icon in role is green.
