### ISSUE TITLE
Roles do not work as intended

### ISSUE THREAD

**Issue by iancustoica** [nilsteampassnet/TeamPass#792]
Hello,

I installed teampass after two years for a reevaluation by the company I work for as an inhouse password manager. However while testing a major problem became apparent: roles / folder management seem broken.

This is the process I tried:
1. Created a few folders:
   Folder01
   |
   Subfolder01-01
   Subfolder01-02
   Folder02
   |
   Subfolder02-01
   Subfolder02-02
   Folder03
2. Created a few roles:
   -basicRole (only read access to Subfolder01-02)
   -mediumRole (read access to Folder01 and Folder03 (and their subfolders) and write access to Folder02 (and it's subfolders))
   -advancedRole (write access to all Folders and their respective subfolders)
3. Created users and added them to the roles from step 02. (basic users without folder or manager / read-only customizations)
4. When logging in with a basicRole user:
   -the user cannot see anything
5. When logging in with a mediumRole user:
   -the user can only see Folder02 and it's subfolders
6. When logging in with an advancedRole user:
   -the user can only see Folder02 and Folder03 and it's subfolders

Apache error logs show 4 repeating messages:

"
[Tue Nov 25 15:13:53.747199 2014] [:error] [pid 3653] [client --ip removed--:53019] PHP Notice:  Undefined variable: usersList in /var/www/teampass/items.php on line 644, referer: http://--url removed--/index.php
[Tue Nov 25 15:13:53.747437 2014] [:error] [pid 3653] [client --ip removed--:53019] PHP Warning:  Invalid argument supplied for foreach() in /var/www/teampass/items.php on line 644, referer: http://--url removed--/index.php
[Tue Nov 25 15:13:53.747942 2014] [:error] [pid 3653] [client --ip removed--:53019] PHP Notice:  Undefined variable: usersList in /var/www/teampass/items.php on line 830, referer: http://--url removed--/index.php
[Tue Nov 25 15:13:53.748020 2014] [:error] [pid 3653] [client --ip removed--:53019] PHP Warning:  Invalid argument supplied for foreach() in /var/www/teampass/items.php on line 830, referer: http://--url removed--/index.php
"

**Comment by ashley56** [comment]
So near the top of items.php  there is a section hashed out 
// Get list of users
// Get list of roles
I removed the hashes and it fixed the PHP Warnings
However I still have the folder issue where it doesnt display correctly.

**Comment by nilsteampassnet** [comment]
Concerning the roles, this issue has been corrected in 2.1.23.

With basic user
![image](https://cloud.githubusercontent.com/assets/1197546/5635079/0893c3ca-95e6-11e4-8c04-1d793924fa46.png)

With medium user
![image](https://cloud.githubusercontent.com/assets/1197546/5635068/fa4f9938-95e5-11e4-8a4a-62d08b3a288e.png)

With advanced user
![image](https://cloud.githubusercontent.com/assets/1197546/5635092/213d495a-95e6-11e4-8e4e-9156c560757b.png)
