### ISSUE TITLE
2.1.22: Lost Access to Folders after Upgrade from 2.1.19

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#795]
After upgrading from 2.1.19 users lost access to some folders. I have to go in the User page and manually select the folders so they can access. Previously the Group membership handled this logic. If I allow a group to access a specific folder then users in that group have access to that folder.

**Comment by alarido** [comment]
In my case after applying the patch folder permissions have been fixed, but still I can't list folder contents.

**Comment by alarido** [comment]
I have upgraded to 2.1.23, but directory listing is still not working for me:

![clipboard02](https://cloud.githubusercontent.com/assets/1955581/5899282/620fc9bc-a559-11e4-87e2-aeb0d1d5049c.png)

**Comment by nilsteampassnet** [comment]
Can I access your teampass using team viewer? If ok can you send me the credentials by mail?

**Comment by alarido** [comment]
Of course, I sent you an email.

**Comment by jensdepuydt** [comment]
Here, as far as I can see, there are no issues with the upgrade from 2.1.22 (with the patch) to 2.1.23 (no patch)
