### ISSUE TITLE
Cannot add items in personal folders

### ISSUE THREAD

**Issue by xFRaNeRx** [nilsteampassnet/TeamPass#800]
Hello,

Using TeamPass 2.1.22, like in bug #796, I can't add items, now in my personal folder. The save button is grayed out, and can't be used. But this time, I can't see nothing in log file.

Thanks for your work.

**Comment by dkrey** [comment]
I've found a workaround for this here: [#875](https://github.com/nilsteampassnet/TeamPass/issues/875)

> Additionally it is necessary to authorize to have several items with the same name in admin settings. Otherwise the save button will be disabled after you insert a label (regardless it is duplicated or not).
