### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by shaolan13** [nilsteampassnet/TeamPass#801]
Hello,

I've an issue when I want to install Teampass with the new version ( 2.1.22 ).
The message says : Function mysqli_fetch_all is not available! 
But it's weird because the next line says : PHP function "mysqli_fetch_all" is available
You can see the error at this URL : http://img11.hostingpics.net/pics/813881teampassinstall.png
I'm on Debian Wheezy 7.7 with PHP5.4 . I tried on three webservers and I've this error on all these servers.

**Comment by deogracia** [comment]
Hi, same with debian 7 amd64 / php 5.439 / php5-mysql

The changes in the PR doesn't change anything. But use php5-mysqlnd was the right move.

**Comment by silvermoon18** [comment]
got the same error as well. I already modify the permission on SELinux but still getting the same error. I also followed the instructions written above and still got the same problem. Any more ideas?

**Comment by silvermoon18** [comment]
i am just doing an upgrade of my TeamPass from 2.1.19 to 2.1.23. Please help

**Comment by wforumw** [comment]
Same problem here!!

**Comment by ralias** [comment]
I'm trying to install version 2.1.23 in a production environment and I'm in the same problem. I don't want change the mysql driver:

[root@localhost public_html]# yum install php-mysqlnd -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.tedra.es
 * epel: mir01.syntis.net
 * extras: mirror.tedra.es
 * updates: mirror.tedra.es
Resolving Dependencies
--> Running transaction check
---> Package php-mysqlnd.x86_64 0:5.4.16-23.el7_0.3 will be installed
--> Processing Conflict: php-mysql-5.4.16-23.el7_0.3.x86_64 conflicts php-mysqlnd
--> Finished Dependency Resolution
Error: php-mysql conflicts with php-mysqlnd-5.4.16-23.el7_0.3.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by ralias** [comment]
Well, finally I remove php-mysql and leave php-mysqlnd. Seem it works.

**Comment by silvermoon18** [comment]
I also removed php-mysql and leave php-mysqlnd and that worked as well.

**Comment by mannes** [comment]
I was looking through the project code and the  mysqli_fetch_all function doesn't seem to be used at all? why is it required? I have had some issues with mysqlnd in the past en prefer not using it on production environments. I will try what happens if i take out this test and try install

**Comment by mannes** [comment]
Taking out the reference to mysql_fetch_all in install/install.js fixes the install. So far everything seems to work fine.
