### ISSUE TITLE
KeePass XML upload issue

### ISSUE THREAD

**Issue by Tharkis** [nilsteampassnet/TeamPass#811]
Been trying to figure this out for a couple of days now. I've got the file size limit set to 100 mb (just to test), also I've tried changing the post and upload size in the php.ini, with no results. The file itself is 14.5 mb. After I use browse to pick my file, I get the following error:

Error: -600, Message: File size error., File: 10_22_13.xml.

Any ideas?

**Comment by gooseleggs** [comment]
I have created a pull request https://github.com/nilsteampassnet/TeamPass/pull/839 to resolve this issue.  @Tharkis can manually make the changes (only about a handful) and then re-test please.  Note that you will need to delete previously imported values (or import to a different folder), as part of the import checks to see if already imported previously, and if so, skips it.

**Comment by Tharkis** [comment]
The changes in #839 fixed the import issue I was having.
