### ISSUE TITLE
Personal Folder entries duplicated

### ISSUE THREAD

**Issue by billu260** [nilsteampassnet/TeamPass#821]
Hi,

After upgrading to 2.1.22 I have a problem with my personal folder. When I click on the personal folder in the folder tree, it takes a long time to load. As it is loading, it becomes apparent that it is loading the folder contents multiple times. First you see the correct contents, then you see the list appended to the bottom of the correct contents for a second time. After a while, it seems to finish and then it resorts the folder. When the sort is done, I am left with anywhere from 3 to 6 copies of each record/row.

The information seems to be correct. It just seems to be a fetch and display issue. I have tried logging in from multiple machines with different browsers and I get the same result. I have tried clearing the browser cache multiple times but that doesn't seem to make a difference. I have tried updating and rebooting the server with no change.

I looked at the database briefly with phpmyadmin and did not see duplicates there.

This only seems to affect the personal folder. Other folders show up just fine.

Any thoughts on further troubleshooting or places to look?

**Comment by macmacy** [comment]
I have exactly the same problem.

**Comment by macmacy** [comment]
I have exactly the same problem after updating from 2.1.7 to 2.1.22.
Adding some traces to items.queries.php I found out that SQL statement issued to retrieve personal folders returns correct number of entries. 
Then, I noticed this code at items.queries.php, line 2078

            if (($items_to_display_once + $start) < $counter) { // && $items_to_display_once != "max"
                $listToBeContinued = "yes";
            } else {
                $listToBeContinued = "end";
            }

For test, I hard coded $listToBeContinued="end" regardless "if" condition. And items in personal folder started to be displayed without duplicates.

This is, of course, not a solution, but maybe this observation can be useful for @nilsteampassnet.

**Comment by hexxamillion** [comment]
I noticed that I have the same issue on 2.1.22. Good to know others are experiencing the same. Any ideas on how to solve?

**Comment by hexxamillion** [comment]
A side note is that I did not have this issue initially after upgrading to 2.1.22 but only after I tested changing SALT key. Then this happened.

**Comment by hexxamillion** [comment]
Any update on this? @nilsteampassnet - Here is my firebug output based on what you requested above.

id	1
key	Fvbhdy0FXovZHvP9vL5ZYnXmsDa8vRHwHhUZY16sqW55zMgvhw
nb_items_to_display_once	4
restricted	
start	0
type	lister_items_groupe
Source
type=lister_items_groupe&id=1&restricted=&start=0&key=Fvbhdy0FXovZHvP9vL5ZYnXmsDa8vRHwHhUZY16sqW55zMgvhw
&nb_items_to_display_once=4

**Comment by hexxamillion** [comment]
Actually..it looks like it is working fine now. I had some code commented out on items.queries.php for some reason. Sorry for the confusion.

**Comment by macmacy** [comment]
Any news about this issue? E.g. can anybody confirm updating to 2.1.23 fixes the problem?
