### ISSUE TITLE
Issues with 2.1.23 (testing)

### ISSUE THREAD

**Issue by gooseleggs** [nilsteampassnet/TeamPass#837]
Nils - was going to test the keepass import issue (#811), but loading up a 2.1.23 test environment, I have the following issues which is preventing me going further

1. Settings.php is faiing silently (because of the @ in front of @require_once in index.php.  When I remove the @, I get this error in the error_log file: PHP Parse error:  syntax error, unexpected '[', expecting ',' or ';' in /opt/git/Teampass/includes/settings.php on line 2

2. When attempting to add a user, I get these error in th event log, and an error of "No data to proceed" when attempting to add a user:
 PHP Warning:  mysqli_connect(): [2002] No such file or directory (trying to connect via unix://utf8) in /opt/git/Teampass/index.php on line 58
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /opt/git/Teampass/index.php on line 58
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_connect(): [2002] No such file or directory (trying to connect via unix://utf8) in /opt/git/Teampass/sources/main.functions.php on line 302
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /opt/git/Teampass/sources/main.functions.php on line 302
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_connect(): [2002] No such file or directory (trying to connect via unix://utf8) in /opt/git/Teampass/sources/checks.php on line 60
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /opt/git/Teampass/sources/checks.php on line 60
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /opt/git/Teampass/includes/libraries/Tree/NestedTree/NestedTree.php on line 73
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, null given in /opt/git/Teampass/includes/libraries/Tree/NestedTree/NestedTree.php on line 74
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /opt/git/Teampass/includes/libraries/Tree/NestedTree/NestedTree.php on line 158
[Thu Jan 01 21:01:58 2015] [error] [client 127.0.0.1] PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, null given in /opt/git/Teampass/includes/libraries/Tree/NestedTree/NestedTree.php on line 161

So, have not progressed through to test the keepass issue.

**Comment by nilsteampassnet** [comment]
Thank you for giving a try to 2.1.23.
Yes I 've identified an error in install process ... a bad copy-paste I can imagine.

In file /install/install.queries.php, replace
```
global \$lang, \$txt, \$k, \$pathTeampas, \$urlTeampass, \$_SESSION['settings']['pwComplexity'], \$mngPages;
```
by
```
global \$lang, \$txt, \$k, \$pathTeampas, \$urlTeampass, \$pwComplexity, \$mngPages;
```

Concerning your second point, it is problem related your linux server. You are using lampp or something similar and you perhaps have mysql.sock which is not correctly defined. Change "localhost" to address 127.0.0.1
You may need to do some searches for correcting this on the server.

Thank you if you can continu investigate :-)

**Comment by gooseleggs** [comment]
Thanks Nils.  Changing to 127.0.0.1 does in fact resolve the issue.  The interesting point is that it only showed up during adding a new user, ie the installation went without a hitch.  Maybe I will look into some day as I would expect this to at the installation.
