### ISSUE TITLE
Wipe/Start from scratch

### ISSUE THREAD

**Issue by Tharkis** [nilsteampassnet/TeamPass#842]
I know this isn't exactly an issue, but I didn't know where to ask it. What is the best way to go about starting from scratch? Can I drop the tables in the database and re-run the install or is there a better way?

**Comment by nilsteampassnet** [comment]
I would recommend to:
* copy the tables inside a new database
* extract the files in `Teampass` folder
* copy back `settings.php` file inside folder `includes`
* run upgrade
