### ISSUE TITLE
2.1.23 Fatal error

### ISSUE THREAD

**Issue by olewales** [nilsteampassnet/TeamPass#843]
Hello, I am setting up teampass for evaluation in company I work for. Stable release of 2.1.22 had some issues documented in #792 and #795 so i tried to update installation to 2.1.23. Upgrade went fine but now i cannot login into teampass and i get following error in the logs.

792 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Encryption\Crypt\aesctr' not found in /var/teampass/sources/main.functions.php on line 955

Any ideas?

**Comment by nfilus** [comment]
Hi,
I simply added the following 3 lines to main.functions.php starting at line 925:

    //Load AES
    $aes = new SplClassLoader('Encryption\Crypt', '../includes/libraries');
    $aes->register();

With this addition I was able to continue to installation update.

**Comment by olewales** [comment]
Thank you!
I was trying to figure it out myself but apparently I misunderstood how SplClassLoader works.

Unfortunatelly 2.1.23 UI is way to buggy for functional testing but at least backend is not logging fatal errors anymore.
