### ISSUE TITLE
Install Issues 2.1.22

### ISSUE THREAD

**Issue by axdxnco** [nilsteampassnet/TeamPass#844]
![screenshot from 2015-01-12 10 48 59](https://cloud.githubusercontent.com/assets/6332233/5708755/a96ec766-9a48-11e4-9c56-d06dc8fa4fe4.png)

Not sure where this is failing?!

**Comment by axdxnco** [comment]
Looks like this is not actuall an error.... The execution time limit seems to be doing an actual time check against the value? IE Waiting 60 seconds before saying te element is met?

Would be nice to see a status bar of the check or an alert that it is still checking, instead of just issueing the failed notice.

**Comment by gooseleggs** [comment]
Try the fixes as per https://github.com/nilsteampassnet/TeamPass/issues/801.  In 2.1.22 there was a numbering issue which meant that the ticks/crosses did not always line up so you may not be seeing the real issue because of this.

**Comment by madjuran** [comment]
Hello people!
I trying to install TeamPass 2.1.23 on CentOS7
I was install everything from the requirements list: 
* Apache,
* MySQL,
* PHP 5.3.0 (or higher), #5.4.16
* mcrypt PHP extension,
* openssl PHP extension,
* ldap PHP extension (if used)
and I have some errors on server check, like "Directory "/install/" is writable   Path install is not writable!" and I set chmod 777 to whole directory
![teampass](https://cloud.githubusercontent.com/assets/11291292/6850996/9b14f668-d3dc-11e4-893d-68d2b8b4835b.png)

**Comment by madjuran** [comment]
On Ubuntu works fine... with same setup

**Comment by madjuran** [comment]
it was problem with SELinux on CentOS... I just change mod from enforcing to permissive and everything is all right.

**Comment by jurcacristian** [comment]
Hi Guys. Madjuran can you please give more details about the fix ?  
Also what is the packet of xamppm or lamp that you installed ?
I've installed Lamp from : 
 https://digitz.org/blog/how-to-setup-xampp-lamp-in-centos-7/
And i put my application in /var/www/html/teampass 

I can access the install php (5.4.16) mysql is mariadb , i got the database and user setup . I lso found that php installation is missing `s.php on line 77, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.609990 2016] [:error] [pid 2729] [client 10.198.216.20:2460] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/html/teampass/sources/sessions.php on line 169, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.610021 2016] [:error] [pid 2729] [client 10.198.216.20:2460] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/teampass/sources/sessions.php on line 77, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.612240 2016] [:error] [pid 2700] [client 10.198.216.20:2461] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/html/teampass/sources/sessions.php on line 169, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.612268 2016] [:error] [pid 2700] [client 10.198.216.20:2461] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/teampass/sources/sessions.php on line 77, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.614513 2016] [:error] [pid 2782] [client 10.198.216.20:2462] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/html/teampass/sources/sessions.php on line 169, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.614542 2016] [:error] [pid 2782] [client 10.198.216.20:2462] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/teampass/sources/sessions.php on line 77, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.616794 2016] [:error] [pid 2785] [client 10.198.216.20:2463] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/html/teampass/sources/sessions.php on line 169, referer: http://10.198.218.133/teampass/install/install.php
[Mon Apr 04 16:58:53.616822 2016] [:error] [pid 2785] [client 10.198.216.20:2463] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/teampass/sources/sessions.php on line 77, referer: http://10.198.218.133/teampass/install/install.php
`
