### ISSUE TITLE
Upgrade From 2.1.19 to 2.1.22 no roles

### ISSUE THREAD

**Issue by Maexchen** [nilsteampassnet/TeamPass#845]
After the Upgrade all folders were crossed out. 
in "Roles Management" no roles werde displayed. 
If I create a new Role, nothing is displayed.
Also not working in version 2.1.21. Version 2.1.20 is ok.... 
Has anybody the same Problem?

**Comment by macmacy** [comment]
I have exactly same issues: all folders crossed-out (I will created separate issue for this) and no roles.
However, in "Users" view I can see assigned roles.
I upgraded from fro 2.1.7 to 2.1.22

**Comment by macmacy** [comment]
Found solution:

**Comment by Maexchen** [comment]
Thats it, it works!!! 

Thanks
