### ISSUE TITLE
Update from 2.1.21 to 2.1.22: Stuck in Step 1 / 500 Internal Server Error

### ISSUE THREAD

**Issue by jeanorwin** [nilsteampassnet/TeamPass#847]
Hi,
I'm trying to upgrade TP from Version 2.1.21 to 2.1.22. After clicking on "launch" in Step 1, the bar starts to signal that the system is working/checking whether all the elements are writeable. Unfortunately, it continues to do so endlessly, so I can not enter Step 2.

An analysis with FireBug shows:
"NetworkError: 500 Internal Server Error - http://192.168.178.33/install/upgrade_ajax.php"

Could you help me out here?

Best regards

Edit: When installing TP 2.1.22 from scratch into another directory and database, the installation works fine. However, as soon as the install is finished, the index.php just shows blank and FireBug reports "NetworkError: 500 Internal Server Error - http://192.168.178.33/tp2122/".

**Comment by nilsteampassnet** [comment]
ANy errors in the Apache log?

HAve you read this [page](http://teampass.net/usage/faq.html#tocAnchor-1-4)?

**Comment by jeanorwin** [comment]
Hi Nils,
thank you for your answer. Unfortunately, the apache log does not show any related errors.

I'll try the FAQ-tip with the new installation. Do I have a chance to migrate the existing 2.1.21 installation into 2.1.22 by simply using the same database or importing a previous database dump into the new database?

Regards

**Comment by jeanorwin** [comment]
UPDATE:
This is how I could fix the error:
1.) Make sure PhpMyAdmin is installed
2.) Backup your database via PhpMyAdmin (Export your old database)
3.) Backup your old TP installlation (move to DATE_TP_Backup) for example
4.) Make a clean and fresh installation of TeamPass 2.1.23, make sure to use the same table prefix(!) and USE A DIFFERENT DATABASE(!)
5.) The installation hopefully works
6.) Go into PHPMyAdmin, switch to the new database, import the old database tables
7.) Now follow the upgrade process acc. to this page http://teampass.net/installation/upgrade.html
8.) You should now be able to log in again.

NOTE: If you receive a blank window upon accessing your root directory (e.g. yourserver.com/teampass), try to access yourserver.com/teampass/index.php?page=items). You should now be on the normal login page and be able to use TP as usual. I will open new issue right now.

**Comment by uucom** [comment]
Changing the chronological order of classes in file includes/libraries/Encryption/Crypt/aesctr.php solved this for me (php inheritance issue). Problem related to: https://github.com/nilsteampassnet/TeamPass/issues/1105
