### ISSUE TITLE
Error at the end of the install

### ISSUE THREAD

**Issue by elecorre** [nilsteampassnet/TeamPass#849]
Hello and sorry for my English.

i had installed tempass on Ubuntu 14.04.

At the end of the web install, teampass remove install folder and check permission.

For check permission, i have one error : "can t change permission"

I did chmod 777 on teampass. It is good or not ?

thanks

**Comment by nilsteampassnet** [comment]
If the script cannot change the permissions, it is recommended to set 0740 on all subfolders except FIles and Upload which shall have 0777

**Comment by mattvanmater** [comment]
I am also having this problem on Ubuntu server 14.04.2, on Teampass Release 2.1.22.  I believe it is a result of the install script changing the permissions to the directories prematurely.  I have found that I have to reset the directory permissions to 777, and that partially resolves the problem, but not quite.

Here are the specific steps i'm following:
Problem occurs during the "Finalization" stage of the installation steps.
Initially, the first two checkmarks fail (path and rights for setting.php and sk.php).
I manually run chmod -R 777 /var/www/html again.
I re-run this stage by clicking on "launch"
This time the sk.php check passes, but the settings.php still fails.
Nothing I do results in the settings.php file being written. 

Some suggestions: provide debug logging that shows the _exact_ path that the install script is trying to write settings.php, and include the expected directory permissions vs what is present.  I would prefer this debug info be available in the webui, but a logfile would be ok too.

What kind of information do you need to diagnose this problem?

**Comment by QIONIS** [comment]
Hello,

I have the same error at the end of the install... 
What is the correct command to correct this error ?

Regards,

**Comment by Seemakarthik** [comment]
I have the same error in the 'Finalization' Stage. The screen show all passed, but unable to continue.

Few more details, I m installing latest version 2.1.27 as a fresh Installation on RHEL 7.2 OS

![image](https://cloud.githubusercontent.com/assets/28385156/25694577/dbccc0ec-30cc-11e7-94f0-cccecbc1502a.png)
