### ISSUE TITLE
Personal salt isn't stored or recognized (v2.1.20)

### ISSUE THREAD

**Issue by ludwigr** [nilsteampassnet/TeamPass#852]
Hello

The personal salt has not been changed, it worked in the past, not allways, but in general ...
1. Login
2. entering personal salt > click on "Save"  > Committing the message "Ready!"!
3. change page to "Passwords"
4. selecting personal forlder
5. the following message appears: (with differnt browsers, cookies enabled, differnet languages, ...)
   "Sie sollten einen persönlichen SALT Schlüssel eingeben, falls Sie persönliche Elemente anlegen möchten." or "You should enter your personal saltkey if you need to use your personal items. "
6. the number (x) behind the personal folder indicates, that the entries are still there ...

Any solution to retrieve the passwords?

**Comment by macmacy** [comment]
I have similar issue after upgrading from 2.1.7 to 2.1.22.
On one try, it behaved as described by @ludwigr.
Now, I have another behavior: I have items in my personal folder displayed few times as shown in attachment. Sometimes repeated 4, sometime 5 times. Tried with Chrome and Firefox - same results.
The password (correct one) appears only when I click first item from duplicated one. 
I have one sub-folder under my personal folder - for the subfolder, items are displayed correctly.

![teampass_personal_folders](https://cloud.githubusercontent.com/assets/1330373/5834970/5d85b63a-a163-11e4-91e0-27deac932165.png)

**Comment by ElGranLoky** [comment]
Duplicate - #803
