### ISSUE TITLE
Session Expiry +8hrs

### ISSUE THREAD

**Issue by bsdking** [nilsteampassnet/TeamPass#853]
session expiration in  08:59:09

Fresh new install on CentOS 6.6 on XenServer
PHP 5.6.4
Apache 2.1.15

Set timezone in php.ini and OS (both to America\Vancouver)
Set timezone to being the same within the application.

Any tips on how to resolve? So i do NOT have 9hr session expiry?
Also, any tips on how to set the default from 60 to a few min?

Thanks.

**Comment by nilsteampassnet** [comment]
What version do you use?
Any way, the Session expiration needs to be entirely reworked.

THe 60 minutes is hard coded today.
Can be changed in index.php file.
Find
```<input type="text" size="4" id="duree_session" name="duree_session" value="60" onkeypress```

and replace `60` by the value you want.

I will make this change possible via admin page

**Comment by gyoza** [comment]
I've noticed that even if my session is set to 10 minutes when i log into the system there is a 7 hour (left over, ?) session length in version 2.1.22

**Comment by gyoza** [comment]
Can we get any confirmation of this bug existing? First login of day, login page is set to 10 minutes, once logged in the recorded session is 7 hours 9 minutes 50 seconds.

**Comment by matdave** [comment]
I'm noticing a similar issue, it shows my server time as being 8 hours ahead of what the server and php are actually reporting.
