### ISSUE TITLE
modifying an item does'nt work

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#854]
I'm facing a strange behavior:
an item created by a user cannot be modified by another user directly by double clicking on the object.
in the same folder there are 2 possibilities:
- if the item is created by the user, a double click works.
- if the user has been created by another user, I have to click on the item, click on the folder in the folder list and click on the modify item button. And then the edit item window open and I can do the modification.
  I think there is a bug.

**Comment by sfrlaurent** [comment]
I'm doing my own reply:
the user is not a manager. That's why the modification does'nt work.
But in that case the bug is : with the click sequence I have described, the modification is possible without the manager permission.

**Comment by nilsteampassnet** [comment]
> an item created by a user cannot be modified by another user directly by double clicking on the object.
Just tried and it works (tested under 2.1.23)
U1 and U2 are normal users.
U1 and U2 have write access on folder F1.
U1 is creating an item (no specific restriction is set).
U2 can double click the item and edit it.
