### ISSUE TITLE
Teampass 2.1.22 freeze at step 1

### ISSUE THREAD

**Issue by undergl** [nilsteampassnet/TeamPass#855]
The installation freezes in the first step, pressing the LAUNCH button to check the server.
<a href="http://es.tinypic.com?ref=180wf4" target="_blank"><img src="http://i59.tinypic.com/180wf4.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by solidsnakerock** [comment]
I have the same problem.

**Comment by elecorre** [comment]
look for this :+1: 
Ran into this same problem.

Navigate to:
 cd /etc/php5/mods-available

Ensure mcrypt.ini is in that directory.

nano or vi into mcrypt.ini and ensure the following line is in there:
 extension=mcrypt.so

Enable mcrypt:
 sudo php5enmod mcrypt

Restart apache2
 sudo service apache2 restart

That got me past that hang up. Hope it works for you.

**Comment by The-Loeki** [comment]
Same problem here happened when we didn't copy over sk.php; settings tries to include but fails silently, upgrade_ajax.php just returns empty 200 OK because of it

**Comment by xEBIx** [comment]
I have got the same problem. But it makes it harder here, I am coming from 2.1.17.
Even if I try to update to 2.1.18 step 1 is freezing.

@elecorre I don't habe a mcrypt.ini as I am not running Debian, I am running Gentoo. 
Is that an issue?

**Comment by ynnsn** [comment]
Check the server response with something like firebug. If you get an "500 Internal Server Error" and no errors in the webserver error log replace in /install/upgrage_ajax.php 

error_reporting(E_ERROR | E_PARSE);
with
#error_reporting(E_ERROR | E_PARSE);
or adjust the php error_reporting.

**Comment by xEBIx** [comment]
Got it working, 
Upgrade Manual is lacking advice to copy sk.php into new folder, or copy hole config folder to new pass directory.
