### ISSUE TITLE
user can write in folder but he have read permission

### ISSUE THREAD

**Issue by galoagui** [nilsteampassnet/TeamPass#856]
Hi,

I have TeamPass 2.1.22.

I have a role with read permission on a folder. But this user can to create new keys.
This is a normal users because i want this users read to this folder and write to others.
These users should not write to this folder.

Thank you very much.

![step1](https://cloud.githubusercontent.com/assets/3602999/5876085/6b3566d8-a314-11e4-8955-b11debdf1bb0.PNG) ![step2](https://cloud.githubusercontent.com/assets/3602999/5876086/6b382864-a314-11e4-9d41-d28deabde7a2.PNG)

**Comment by nilsteampassnet** [comment]
Hello,

Are you sure this user is not related to another Role in which it has write access?

I've performed some improvement in 2.1.23, and just retested this, and it doesn't occur in the next release.

Give a try with 2.1.23 in a testing environment.

**Comment by galoagui** [comment]
Hello,

This user has rights to write in other folder, but only read in this.

I'll try new version.

**Comment by galoagui** [comment]
Hi,

I have installed the 2.1.23 version. And it works! 

is is a stable version?
