### ISSUE TITLE
Rights Management

### ISSUE THREAD

**Issue by yauckburally** [nilsteampassnet/TeamPass#858]
Hello, i think i Have a bug with Teampass.
I've installed Teampass version 2.1.22 on a Debian Wheezy and i use HTTP and HTTPS.
Actually,I've created a folder called "TestFolder" with the Admin account,then i created a role called "TestRole".
I create a user with the Manager privilege and role TestRole.
But when i log with the user i don't hace acces to the folder "TestFolder".I must give him the access to the folder manually in "Authorized Folder".
My user is a LDAP User.
Is this normal?

Other issue,i can't use the CSV export, i create a CSV,upload it and the Import button don't work,i can't click.

Thanks for reply

**Comment by nilsteampassnet** [comment]
Tested on 2.1.23 and can not reproduce.

Can you give a try to 2.1.23 in a testing environment to check?

**Comment by yauckburally** [comment]
Upgraded to 2.1.23 and the issue with roles is solved.I didn't see that a new version was out,thanks.

The import doesn't seem to work.I've got that for my CSV.

![teampass_import](https://cloud.githubusercontent.com/assets/10673947/5896562/16ca7ebe-a551-11e4-8f18-39a115d1c2c2.PNG)

I select a folder for the import destination and I click Import,but after it tells me to wait and does not import my stuff.

Thanks for your support.
