### ISSUE TITLE
Fix error in enabling Strict Transport Security during session

### ISSUE THREAD

**Issue by The-Loeki** [nilsteampassnet/TeamPass#860]
When STS is enabled, errors start appearing in the log:
`PHP Notice:  Undefined variable: cert_issuer in /var/www/intranet/TeamPass/sources/core.php on line 297`

In sources/core.php, line 295+:

``` php
    // do a check to make sure that the certificate is not self signed.
    // In apache's SSL configuration make sure "SSLOptions +ExportCertData" in enabled
    $server_cert=openssl_x509_parse($_SERVER['SSL_SERVER_CERT']);
    $cert_name=$server_cert['name'];
+    $cert_issuer="";
    foreach ($server_cert['issuer'] as $key => $value) {
        $cert_issuer .= "/$key=$value";
    }
    if (isset($cert_name) && !empty($cert_name) && $cert_name != $cert_issuer) {
```

Without declaring cert_issuer outside the foreach loop, it will not exist in the next test.

As a side note, I might be reading this code wrong, but it's hugely and overly expensive to do this each request; it'd be far more elegant to check this upon enabling the setting, and refusing to do so if it's not right.

**Comment by ignbell** [comment]
This code worked fine on my server, Thanks The-Loeki.
