### ISSUE TITLE
[2.1.23] LDAP Authentification still not working.

### ISSUE THREAD

**Issue by michmich9337** [nilsteampassnet/TeamPass#861]
Hi Nills, 

Did you correct the issues about the authentification against LDAP ? 'Cuz still have this issues since 2.1.23  upgrade. (#742)
(Or if gooseleggs can patch this version too =P )

Best Regards,

**Comment by JackFK** [comment]
please fix it :+1: 
Thanks!

**Comment by sjaredj** [comment]
I upgraded from 2.1.22 to 2.1.23 last week and my ldap authentication still worked after upgrade

**Comment by michmich9337** [comment]
@sjaredj Are you authentificating against Windows AD ?

**Comment by sjaredj** [comment]
yes

**Comment by michmich9337** [comment]
Could you please share following file :
- /index.php
- /sources/identify.php
Thanks.

**Comment by michmich9337** [comment]
@sjaredj up.

**Comment by michmich9337** [comment]
@sjaredj up.

**Comment by michmich9337** [comment]
Problem solved, Fix by this  #878
