### ISSUE TITLE
cannot have the menus with IE8

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#865]
the new interface give me a bad screen with IE8:
here it is:
![image](https://cloud.githubusercontent.com/assets/10242259/5939860/7e03a36e-a707-11e4-8c98-89960c86aad7.png)

it seems the new menus are writen in the windows
is there a parameter to modify in IE ?

thank you for the answer

**Comment by nilsteampassnet** [comment]
​What version of IE do you use?

IE11 works correctely ... it makes me think to a problem with browser
cache. Have you cleared it?​

**Comment by sfrlaurent** [comment]
thanks for the answer
I'm using IE8 version 8.0.7601.17514
yes I have cleared the cache and the behavior is the same.

**Comment by powertim** [comment]
Hi,

I have exactly the same issue on IE11.
Cache cleared and etc...
Unfortunately, I can't use TeamPass because of this state.
Any idea ?

Thanks!
