### ISSUE TITLE
Session disconnect problems

### ISSUE THREAD

**Issue by fgn-git-hub** [nilsteampassnet/TeamPass#866]
I have some strange session disconnect problems. 
I'm using LDAP auth against an AD. 
Logging in does work without problems, sometimes I have to reload twice to really login but aside from that, it's working. 
While being logged in the session timeout is counting down, but eventhough the count down didn't hit zero, the session stops to work and the system won't accept new entries or changes. I have to reload the browser and after that it shows me the login screen once more. 
How can I debug that further and what could be the cause of this behaviour?

Thank you for your answers.

**Comment by nilsteampassnet** [comment]
​What version do you use?
What timezone have you?​

**Comment by fgn-git-hub** [comment]
Version?
It started with 2.1.19 and stayed through 2.1.20/21/22/23. 
Right now updateing to 2.1.23 started the following behaviour: 
Login works and after that I get a white page shortly afterwards and I'm logged out once again. Maybe that has something to do with that login problems. 

Timezone GMT +1 CET

**Comment by fgn-git-hub** [comment]
I checked the error a bit further and it seems to be the reason that after logging in the session has expired already. How can that be possible? After that I get logged out and thrown out.

**Comment by fgn-git-hub** [comment]
Due to that problem, I can't login at all, since the last update. 
Could that be due to cache buffer or something similar?

**Comment by fgn-git-hub** [comment]
It seems an update to the latest version of php 5.6.x did the trick somehow. Maybe that helps someone else as well. Still I'm not able to login via LDAP but that could be related to another issue which has already been opend.

**Comment by fgn-git-hub** [comment]
Upgrading to 5.6.x latest, wasn't solving the problem, due to the LDAP login problems, I tried to revert to 2.1.22 and now I have the same problem again. 
Can someone tell we where the session timout data is being stored, maybe there is a way to reset it so I don't get thrown out time after time?

**Comment by fgn-git-hub** [comment]
Ok I got it solved finaly. 
It was a date/time problem, the clock of my server has been off more than a day. That caused the session to be logged off. Fixing the time fixed the problem.
