### ISSUE TITLE
Double login required (first login does not work)

### ISSUE THREAD

**Issue by jeanorwin** [nilsteampassnet/TeamPass#870]
Hi,
I've just migrated from 2.1.21 to 2.1.23 via a rather awkward way, see #868 for reference. Everything now seems to work fine, but there remains one problem so far: In order to login successfully, users have to log-in twice. Upon the first login, a page "this page has not been found" is displayed, even though the menu buttons are there as regular. However, upon clicking one of these buttons, the user is redirected to the login page again. After the second login, users can work as usual.

Note: This might be related to #866

**Comment by ArthurGuy** [comment]
I have the same problem with version 2.1.24, very irritating.
