### ISSUE TITLE
categories in folder and subfolder usage

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#872]
I plan to use categories feature to add some fields in a given folder.
I thought the subfolders created under the folder declared into the categories tab will inherit from the parent the usage of a categories setting.
It is not true.
Do I forget something to have this behavior ? Maybe a configuration item I haven't seen ?
Is there a way to do so ?

thank you for your help

**Comment by nilsteampassnet** [comment]
No this feature permits you to create your own fields that will be related
to the Items definition.
You can define those fields to be visible only the Item definition of
specific folders.

For example, you can relate "my_custom_field_A" to folder "Folder_A" so
that any Items in this folder will now have this specific custom field in
its definition.

**Comment by sfrlaurent** [comment]
OK, for me any item include the subfolders, no ?
It could be great if once the "Folder_A" has been initialised to have a new field "my_custom_field_A" added for all the items created under it, the same property exists for the subfolders of "Folder_A" and all the items created under them.
