### ISSUE TITLE
error if you click on uploaded file

### ISSUE THREAD

**Issue by galoagui** [nilsteampassnet/TeamPass#873]
Hello,

I have 2.1.23 version
i had a error when i tried to view a uploaded file. In apache2/error.log i had the next message:

 Call to undefined function prefix_table() in /var/www/teampass/sources/downloadFile.php on line 43

I have included this instruction in sources/downloadFile.php line 26:
 require_once 'main.functions.php';

Now, it works!

**Comment by nilsteampassnet** [comment]
​Absolutely correct.

Thanks for reporting it.​
