### ISSUE TITLE
Upgrade 2.1.19 to 2.1.23: Unable to login (ldap)

### ISSUE THREAD

**Issue by ynnsn** [nilsteampassnet/TeamPass#878]
Hi, 
in  #867 I already posted the error. 
I'm unable to login with ldap but the local admin works.

ErrorLog:
[Tue Feb 03 15:49:15.598452 2015] [proxy_fcgi:error] [pid 18424:tid 140155797079808] [client 10.0.200.2:33140] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: key in /srv/www/teampass/sources/main.functions.php on line 961\nPHP message: PHP Notice:  Undefined variable: ldap_suffix in /srv/www/teampass/sources/identify.php on line 166\nPHP message: PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /srv/www/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /srv/www/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\Password\Factory->verifyHash('###########', 'TsynNqjUweI9i3x...')\n#1 /srv/www/teampass/sources/identify.php(337): PasswordLib\PasswordLib->verifyPasswordHash('###########', 'TsynNqjUweI9i3x...')\n#2 /srv/www/teampass/sources/identify.php(28): IdentifyUser('69/QVEZGRkbMyxO...')\n#3 {main}\n  thrown in /srv/www/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87\n', referer: http://tp/index.php?page=items

**Comment by fsniper** [comment]
I have the same problem.

The issue is, there is a logic error about user identification with ldap. If user is identified by ldap his/her password is not registered in the db. Team pass is trying to check the password registered in the db with verifyPasswordHash near line 334. If the password is empty verifyPassword throws an exception.

 I had to workaround this issue with this patch:
```
diff --git a/sources/identify.php b/sources/identify.php
index dbf5a2e..6af1ff1 100644
--- a/sources/identify.php
+++ b/sources/identify.php
@@ -334,11 +339,15 @@ function IdentifyUser($sentData)
         }
         
         // check the given password
-        if ($pwdlib->verifyPasswordHash($passwordClear, $data['pw']) === true) {
-            $userPasswordVerified = true;
-        } else {
+       try {
+               if ($pwdlib->verifyPasswordHash($passwordClear, $data['pw']) === true) {
+                   $userPasswordVerified = true;
+               } else {
+                   $userPasswordVerified = false;
+               }
+       } catch (Exception $e) {
             $userPasswordVerified = false;
-        }
+       }
         
         // Can connect if
         // 1- no LDAP mode + user enabled + pw ok
```

**Comment by ynnsn** [comment]
Thank you! Works for me.

**Comment by fgn-git-hub** [comment]
I tried your patch as well, but I'm still getting the error. Before patching that file I just got no error in php and a spinning waiting symbol which did not stop to spin at all. 
Any ideas's what's wrong on my side?

**Comment by amorce** [comment]
Same problem for us. The fsniper patch allow users to login.

**Comment by fgn-git-hub** [comment]
@amorce so that patch did work for you?
It doesn't for me. 
How did you apply the patch?

**Comment by amorce** [comment]
I've just manually edit the sources/identity.php file.
To see if there is any LDAP problems, you can set $debugLdap = 1; at the top of the same file. It enable logging of the auth process in files/ldap.debug.txt

**Comment by djuslly78** [comment]
hello,
I want to know how to add the LDAP over teampass, I just parameterize it in the options, but can not connect to the LDAP server?
there has files modififier?

thank you in advance

**Comment by djuslly78** [comment]
hello,
I want to know how to add the LDAP over teampass, I just parameterize it in the options, but can not connect to the LDAP server?
there are files has changed?

thank you in advance

**Comment by jult** [comment]
Patch did not work for us either. Noteworthy is that in our case there does not seem to be a hash (as opposed to the error of ynnsn above):

[Wed Feb 25 11:27:29 2015] [error] [client 10.0.0.16] PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /srv/www/vhosts/tpass.xx/TeamPass-master/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /srv/www/vhosts/tpass.xx/TeamPass-master/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('mypasswordinthislog', '')\n#1 /srv/www/vhosts/tpass.xx/TeamPass-master/sources/identify.php(337): PasswordLib\\PasswordLib->verifyPasswordHash('mypasswordinthislog', '')\n#2 /srv/www/vhosts/tpass.xx/TeamPass-master/sources/identify.php(28): IdentifyUser('mqPtVCwsLCwFcm9...')\n#3 {main}\n  thrown in /srv/www/vhosts/tpass.xx/TeamPass-master/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: https://tpass.xx/index.php?page=items&session_over=true

verifyHash('mypasswordinthislog', '') <- note the nothingness in between the quotes..

**Comment by looneypantz** [comment]
Pardon my ignorance......how do you apply the patch?

**Comment by hexxamillion** [comment]
I confirmed that this does not work for me. I manually updated the identify.php as suggested.

**Comment by hexxamillion** [comment]
Curious if this the set up is for LDAP why is it looking for local db credentials anyways. The only local account I can think would be admin. This probably shouldn't even be invoked if LDAP is enabled.

**Comment by fgn-git-hub** [comment]
I have the same problem, I manually patched the identify.php file as well. 
Searched for the specific part, deleted the lines which are no longer needed, and added the lines which are supposed to be the patch. 
I get an error log with an empty '' field for the password as well. So no fix at all. At least not for me.

**Comment by nilsteampassnet** [comment]
Just saw this issue ... sorry!

Can you tell me in what case this issue happens.
Is it for all LDAP users? or is it only for new LDAP users that have NEVER been connected to Teampass before 2.1.23?

**Comment by nilsteampassnet** [comment]
I think I found the bug.

In file /sources/identify.php

Found 
```
            // authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                $ldapConnection = true;
```
and replace by
```
            // authenticate the user
            if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                $ldapConnection = true;
                //update user's password
                $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
                DB::update(prefix_table('users'),
                    array(
                        'pw' => $data['pw']
                    ),
                    "login=%s",
                    $username
                );
```
This should correct the that that LDAP users cannot get connected any more.

Secondly,
Found 
```
'pw' => $password,
```
and replace by
```
'pw' => $pwdlib->createPasswordHash($passwordClear);
```
This should correct the issue of connected for new LDAP users.

Note: just as a reminder, sorry for this issue, but as I have no knowledge on how to set up an ldap server, I cannot test. The test is only performed by code review.

**Comment by vcmartin** [comment]
found syntax error
'pw' => $pwdlib->createPasswordHash($passwordClear);
replace the ";" with a ","
'pw' => $pwdlib->createPasswordHash($passwordClear),

**Comment by nilsteampassnet** [comment]
@vcmartin Thanks, I've corrected it in my previous comment.

Anyway, did this change solved your users connection issue?

**Comment by fgn-git-hub** [comment]
I'll test that right away and get back to you asap. Thank you so far.

**Comment by intropedro** [comment]
I have tried but it dont work. I start to think that I am putting bad the ldap config. I use OpenLDAP and I put this:

LDAP server type: Posix /OpenLDAP (RFC2307)
LDAP base dn for your domain: 
- In first input: ou=mycompany,dc=es
- In second input: @ou=mycompany,dc=es
LDAP array of domain controllers: 192.168.1.5

My user in ldap:

>  dn: uid=usertest,ou=mycompany,dc=es
>  objectClass: top
>  objectClass: posixAccount
>  objectClass: shadowAccount
>  objectClass: inetOrgPerson
>  objectClass: person
>  givenName: Name1
>  sn: Name1
>  displayName: Name1
>  userPassword:
>  cn: Name1
>  mobile: 4444444
>  gecos: Name1
>  homePhone: 4444444
>  uid: mariomv
>  uidNumber: 50
>  gidNumber: 50
>  homeDirectory: /home/usertest
>  st: XXXX
>  l: XXX
>  postalCode: 50000
>  mail: usertest@mycompany.com
>  description: XXXXX
 
And I put the password this:
> # ldappasswd -Wx -D "cn=root,dc=es" -H ldap://localhost -S "uid=usertest,ou=mycompany,dc=es"

Is it correct?

**Comment by fgn-git-hub** [comment]
Thank you to you both, it's working perfectly now.

**Comment by fd4485** [comment]
Hi, I have the same issue. After upgrade I can't login from Ldap. I tried Patch, but it doesn't worked for me.

Do you have the full identify.php file that work for you please?

thanks :)

**Comment by fsniper** [comment]
I'm sorry I currently do not have access to that infrastructure. I can not provide more details. 

That patch was only intended as a workaround for my case. It can not be used for all cases. Every infrastructure, every installation may have different problems.

**Comment by hexxamillion** [comment]
Hmm.. it works now but not because of any of the suggestions above. In fact the suggestions above did not work for me at all. I recopied the identify.php from the downloaded 2.1.22 package and overwrote it. Strange.

**Comment by dusty73** [comment]
Hi, 
 I just upgraded from 2.1.17 to 2.1.23 and had the same problems above. After applying the patches the error continued, but I found where my problem was.
In sources/identify.php, during option initialization, there is this check:

            // Posix style LDAP handles user searches a bit differently
            if ($_SESSION['settings']['ldap_type'] == 'posix') {
                $ldap_suffix = ','.$_SESSION['settings']['ldap_suffix'].','.$_SESSION['settings']['ldap_domain_dn'];
            }
            elseif ($_SESSION['settings']['ldap_type'] == 'windows' and $ldap_suffix == '') { //Multiple Domain Names
                $ldap_suffix = $_SESSION['settings']['ldap_suffix'];
            }

After this check $ldap_type was empty, since in my conf ldap_type is "0". So the adLdap authentication couldn't work.
So I set the correct ldap_type ('windows', in my case) and now everything is fine.

I checked the source of version 2.1.17 and ldap_type does not exists. Maybe during the upgrade you should ask the admin to choose the ldap type.

**Comment by pojanisu** [comment]
Hi,
I'm coming from 2.1.15 to 2.1.22 and now to 2.1.23 and stumbled onto this same issue. I first did the try/catch fix and it worked in our environment. The same thing that fsniper suggested. 

Now I removed that and tried the fix Nils suggested and it seems to work fine also.

Thanks everyone!

**Comment by hexxamillion** [comment]
I thought I would try this again. The solutions still do not work for me.

**Comment by hexxamillion** [comment]
I just tested 2.1.24 just to see and this same issue exists.

**Comment by hexxamillion** [comment]
I'm still having a heck of a time with this. None of the proposed solutions work for me and I am still getting 'Unsupported Password Hash Supplied' in my apache log with the password in clear text rather than hashed. What is the purpose of the identify php class anyways? If we have ad/ldap configuration setup why does it need an addition piece?

**Comment by codeman1161** [comment]
Mine is working greate 2.1.23. One thing I did that was stupid that was causing it not to work was when logging in I was using the full user.name@mydomain.com and was getting that error. as soon as I just used the username without the "@domainname.com" everything worked great. I have gotten in the habbit of typing that. Just mentioning this thinking maybe someone else is doing the same. in version 2.1.23 the identify.php file is exactly how it should be according to nilsteampassnet comments above.

**Comment by mpbunch** [comment]
Issue persists:
[Wed Feb 21 20:52:06.003955 2018] [:error] [pid 29775] [client 134.174.140.195:58206] PHP Fatal error:  Uncaught DomainException: Unsupported Password Hash Supplied in /var/www/html/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/html/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('teampass', 'teampass')\n#1 /var/www/html/sources/identify.php(861): PasswordLib\\PasswordLib->verifyPasswordHash('teampass', 'teampass')\n#2 /var/www/html/sources/identify.php(233): identifyUser('teampass')\n#3 {main}\n  thrown in /var/www/html/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: https://teampass.domain.com
