### ISSUE TITLE
Download attachments error in 2.1.23

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#879]
I got error "PHP Fatal error:  Call to undefined function prefix_table() in /path/to/teampass/sources/downloadFile.php on line 43" when trying to download a file, and fixed importing main.functions.php

```
diff original/sources/downloadFile.php fixed/sources/downloadFile.php
20a21,22
> require_once $_SESSION['settings']['cpassman_dir'].'/sources/main.functions.php';
> 
```

**Comment by nilsteampassnet** [comment]
See #887

Thanks for posting
