### ISSUE TITLE
View logs error redeclared function getBits in 2.1.23

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#880]
I got error "PHP Fatal error:  Cannot redeclare getBits() (previously declared in /path/to/teampass/sources/main.functions.php:20) in /path/to/teampass/sources/main.functions.php on line 28, referer: http://myteampass/index.php?page=manage_views" when trying to see logs.

I fixed it with the following change:

```
diff original/views_logs.php fixed/views_logs.php
38c38
< include $_SESSION['settings']['cpassman_dir'].'/sources/main.functions.php';
---
> require_once $_SESSION['settings']['cpassman_dir'].'/sources/main.functions.php';
```

**Comment by alarido** [comment]
Same problem with "views_database.php" fixed using require_once instead of include.

**Comment by nilsteampassnet** [comment]
Thanks for reporting
