### ISSUE TITLE
All Folders deleted by any user - just delete the personal folder.

### ISSUE THREAD

**Issue by danislav** [nilsteampassnet/TeamPass#883]
Version: 2.1.22
If a user deletes his personal folder - the result is that All the folders get deleted from the database.
Only a restore the nested_tree table from backup can save you: you need the original id;s
I suppose it's a wrong "where" clause which selects all the folders.

**Comment by onbalt** [comment]
I can confirm this issue.

**Comment by jyemeier** [comment]
I can also confirm this issue.
