### ISSUE TITLE
Problems with quotes for links in Description field

### ISSUE THREAD

**Issue by nelleee9** [nilsteampassnet/TeamPass#884]
When adding a link into Description of an item links get broken due to quotes handling - see the attached image.
(version 2.1.23, tested in Chrome)
![links-quotes](https://cloud.githubusercontent.com/assets/10302624/6078233/03da8870-ae08-11e4-826e-8335fca6de25.png)

**Comment by guindous** [comment]
Confirmed same bug on version 2.1.25
