### ISSUE TITLE
2.1.23 - Personal Folder only read permission

### ISSUE THREAD

**Issue by ElGranLoky** [nilsteampassnet/TeamPass#890]
After install 2.1.23:
- Enable Personal Folder.
- Run script to populate personal folders in the db.
- Create Personal SaltKey for the user.
- Enter the personal saltkey, and the folder personal folder active, but always with read permission.

**Comment by gerymcfree** [comment]
I have the same issue. I also find out that new user (created after update) has not a personal folder at all.

**Comment by ElGranLoky** [comment]
Maybe need to run the script for create the personal folder for the new users.

**Comment by gerymcfree** [comment]
I took a look on the database and it seems that the value "personal folder" for the new user is set to 1 (means "enable" if I am not mistaken) therefore there must be another thing to fix.

**Comment by jensdepuydt** [comment]
I think this is similar to the issues reported in #875

**Comment by Enedrog** [comment]
Hello,

I have the same issue that ElGranlocky, permissions of personal folders are read only .

I've modify index.php, items.queries.php and main.functions.php as in #875 but i don't work. I've the menu for the salt key and the personal folder seem to be write and read permissions, the save button will be disabled after you insert a label.

In the admin setting, i've tried the saltkey in cookie's option but it did not work at all.

----
Translate in French:

Bonjour,

J'ai le même problème que ElGranLocky, j'ai essayé d'activer l'option des répertoires personnels.

Les répertoires sont bien créés, mais il y a un oeil devant le nom du répertoire, signifiant la lecture seule.Les utilisateurs ne peuvent pas créer d'objet ni créer de répertoire.
J'ai donc essayé les solutions apportées dans le bug #875 mais sans succès.
J'ai bien le menu pour entrer la salt key qui apparaît, j'arrive également à obtenir le formulaire pour créer un nouveau mot de passe, mais dès que je renseigne l'intitulé le bouton Enregistrer se grise.

Merci pour l'aide que vous pourrez m'apporter.
