### ISSUE TITLE
Impossible to connect after a fresh install

### ISSUE THREAD

**Issue by wiseflat** [nilsteampassnet/TeamPass#896]
Hi,

I'm migrating an old version of teampass (debian squeeze, php5.3.3, php-mysql apache2, mysql) to teampass 2.1.22 (centos, httpd, php55, php55-mysqlnd, mysql).

I have a lot of problems but at least I 'm opening this ticket for the last one of them.

Firstly, I was not able to access to the web interface because of this error :

```
 mysqli_fetch_all" is available function mysqli_fetch_all is not available!
```

I found the issue and upgrade php5.3.3 to php55 + php55-mysqlnd.
Then I was able to access to the web interface and follow the wizard to set up teampass.

But, when I want to connect it says : 

```
 Maintenance mode has been activated. Only Administrators can log in.
```

I followed this issue https://github.com/nilsteampassnet/TeamPass/issues/213
I changed the flag in mysql to change the maintenance mode

But, when I try to connect, I come back to the login page : 

```
 Your session has expired or you are not correctly identified!
```

I have only one user for the moment : admin

Nothing special in the httpd logs :

==> /var/log/httpd/error_log <==
httpd[4004]: User logged in - 1 - 2015/02/12 12:08:39 172.16.10.6 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0

Can anyone tell me what's wrong ?

Cheers
ps : it's a good soft anyway :-)

**Comment by fbourasse** [comment]
Hi, 

I think there is a problem with the "Session duration (minutes)" on the login page : try to increase it to 60000.

Best regards,
Florent

**Comment by stoneagerebel** [comment]
I have the same issue on the latest version. 
Increasing session duration to 60000 works. 
Would like a proper fix though.

**Comment by nilsteampassnet** [comment]
What time zone are you in ?
Is the server correctly set up to fit the user's one ?

**Comment by eking22** [comment]
Aaaahhh, I see

It was my server time. After i setup ntp, the session duration worked on 600.

Thank you
