### ISSUE TITLE
2.1.23 csv import not working

### ISSUE THREAD

**Issue by palimm** [nilsteampassnet/TeamPass#897]
I tried a very simple csv file with the following content:
"testLabel", "testUser", "testPass", "",""
All I get is a Please wait message.

The following message can be found in the apache error log:

PHP Notice:  Undefined variable: prevLevel in /home/web902/html/items.import.php on line 111

**Comment by atsp** [comment]
Same here with 2.1.23
Images/files are uploaded with no issues.

**Comment by poetimp** [comment]
I am getting the same thing. Was a solution ever found?

**Comment by DavidBruchmann** [comment]
testPass never is encrypted therefore it might not work necause all chars
beside e and a additionally to the length of the string are wrong.
I never had a look in the code but that's my first simple analysis.

**Comment by poetimp** [comment]
I actually just found the problem and corrected it. I had the sight accessed via https but configured all of the links in the admin settings as http. Once I corrected the admin setting to be https on all of the links it worked like a charm.
