### ISSUE TITLE
New folder incorrect permissions (read-only) 2.1.23

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#900]
Steps to reproduce:
1) Inherit folder permissions: enabled
2) Enable RW permision in a folder for a role.
3) Log on as user of this role.
4) Create a new folder in the RW folder.
5) The new folder has permissions for the same roles, but the permissions for this role are RO but it should be RW, write permission is not inherited.

Thanks in advance

**Comment by djfjeff** [comment]
I have the same problem with 2.1.22. It was working fine with 2.1.21, the new folder would have write access.

Now, even with my user configured as a manager with full access to all folder, if I create a new sub-folder, it is strike and I cannot add anything to it. I must log as an admin and adjust the permission...

**Comment by brazhin** [comment]
I have the same problem. There are forecasts of when it will be decided?

**Comment by redcl0ud** [comment]
In 2.1.23, the correction needs to be made in folders.queries.php at line 396.

array(
  'role_id' => $record['role_id'],
  'folder_id' => $newId,
  'type' => $record['type']
)

**Comment by ssticsistemas** [comment]
In 2.1.23, after adding the line "'type' => $ record ['type']" in file folders.queries.php , users can not create subfolders.
Any ideas
Thank you
