### ISSUE TITLE
Useful commit messages and Branches

### ISSUE THREAD

**Issue by Kiina** [nilsteampassnet/TeamPass#903]
I have 2 little suggestions for improving this Git Repo. First is that you should use more meaningful commit messages. If you see 5 commit named "2.1.22" it doesn't help you. A commit message should describe what this change does. For example: "Add multi-selection for folders deletion" which is currently in the commit body. Second what it up with all these branches? 
You use tags and releases which is great. So why would you ever need a branch of an old Version that is merged into the current release? And your main branch should be named master.

These changes would improve the clarity of the repo.

**Comment by nilsteampassnet** [comment]
​Thanks ... I will try to improve myself.

I don't master Git as I would like to​. But I will try.
