### ISSUE TITLE
Folder in russian

### ISSUE THREAD

**Issue by AlexanderTikhonov** [nilsteampassnet/TeamPass#904]
Hi, I give a russian name to a folder (with UTF8), for example "Учебная работа", then after update page I get the name "Учебна..." Whats wrong?

**Comment by nilsteampassnet** [comment]
​Can you paste a screenshot please?​

**Comment by nilsteampassnet** [comment]
OK I see what you mean.
If folder name too long, then it is truncated.

Perhaps not a good idea ... I will remove this

**Comment by Null-Kelvin** [comment]
It's still here in 2.1.23 master
http://savepic.su/5491918.jpg

**Comment by Null-Kelvin** [comment]
Still in 2.1.23 master
http://savepic.su/5491918.jpg
