### ISSUE TITLE
Exporting to CSV

### ISSUE THREAD

**Issue by reuvygroovy** [nilsteampassnet/TeamPass#905]
is there a way to export passwords to CSV?

**Comment by nilsteampassnet** [comment]
​Yes sure ... you need first to enable the "export" feature.
Then from the Items page, in the menu on top of the folders tree, you
should have the entry for exporting the Items.
Select either csv or pdf format.​

**Comment by reuvygroovy** [comment]
Where is the option?

I only see in the settings menu:

Enable importing data from CVS/KeyPass files

For importing

**Comment by nilsteampassnet** [comment]
It is not clearly identified for CSV.
![image](https://cloud.githubusercontent.com/assets/1197546/6358352/256a7196-bc6b-11e4-91c1-75652df21692.png)

Then
![image](https://cloud.githubusercontent.com/assets/1197546/6358367/52ac6790-bc6b-11e4-9348-11d9017cec91.png)

**Comment by reuvygroovy** [comment]
I only see these buttons.

[cid:image001.png@01D05721.74FEFE70]

Where do I find the button and/or how can I export the items?

**Comment by reuvygroovy** [comment]
Is this a button only from a specific version onwards?

From: ראובן סינגר (LREUVEN)
Sent: Thursday, March 5, 2015 8:51 AM
To: 'nilsteampassnet/TeamPass'; nilsteampassnet/TeamPass
Subject: RE: [TeamPass] Exporting to CSV (#905)

I only see these buttons.

[cid:image001.png@01D05C23.92A82C10]

Where do I find the button and/or how can I export the items?

**Comment by klementrempus** [comment]
Hello,

I am unable to see the export option. I have enabled "Enable printing items to PDF file" with "YES". I only see the import optios, in the field "Define the roles that are allowed to print items" there are all the roles listed, but i haven't found a way to select or enable some of the roles, clicking, double clicking or pressing any keys does nothing, do the users from the list have to be selected additionally or are those all the users listed who should have the option to export? Please see screenshots.

![1](https://user-images.githubusercontent.com/39908729/40916253-5d4cdf02-67ff-11e8-965c-c1574aee1e89.png)

![2](https://user-images.githubusercontent.com/39908729/40916254-5d689d78-67ff-11e8-93b6-56a9a57381e5.png)

Thank you,

BR, Klemen

**Comment by cnolick** [comment]
@klementrempus  I have similar problem.  @nilsteampassnet, Maybe there is another way API ? I want consolidate 2 servers, but i don't know how this do ?

**Comment by mayeulk** [comment]
@klementrempus and @cnolick   Do you have the latest teampass? I can see the correct export options in   127.0.0.1/teampass/index.php?page=manage_settings   under the "Options" tab, running 
TeamPass 2.1.27.16  (the version number is written at the bottom of each page)
