### ISSUE TITLE
How to use TeamPass 2.1.23 

### ISSUE THREAD

**Issue by jathanblackred** [nilsteampassnet/TeamPass#906]
Hi. I installed TeamPass 2.1.23  and being in the web interface as admin, I do not find how to create or import items in nowhere. I only see that it is possible to create and manage folders by user assigment. I was looking exhaustively for some introduction or guide to learn how to create the shared passwords that I want use with my sysadmins partners in the work. Can some tell me how to create or assign the desired passwords to be used through Teampass please?

**Comment by nilsteampassnet** [comment]
First you should read http://teampass.net/installation/getting-started.html
Then you need to login with a non administrative user and start creating items.

**Comment by jathanblackred** [comment]
Hello nilsteampassnet. Thank you very much for your quick response. You really helped me with what I needed to start enjoying the virtues of Teampass :) I checked during the past days the documentation of the project, but I did not see this essential part in the link that you shared me until now ja:

    Remember that an Administrator has no access to Items.

Now it all makes sense. Today as I was dedicating to create the directories structure of my work servers and their items. Teampass has a very nice operation besides being so nice aesthetically. Teampass fascinates me a lot. Congratulations for this great Free Software project. You and all the developers do an awesome work. I will make a proposal for a financial donation for my company to support Teampass. I hope they take me into account and if not, I will make a small donation at least. What methods to money transfers does the project have? Thanks a lot.

**Comment by jathanblackred** [comment]
On 24/02/15 08:58, Nils Laumaillé wrote:
> First you should read http://teampass.net/installation/getting-started.html
> Then you need to login with a non administrative user and start creating
> items.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilsteampassnet/TeamPass/issues/906#issuecomment-75720232>.
> 
Hello Nils. Thank you very much for your help. Have a nice day.

-- 
Por favor evita enviarme adjuntos en formato de word o powerpoint, si
quieres saber porque lee esto:
http://www.gnu.org/philosophy/no-word-attachments.es.html
¡Cámbiate a GNU/Linux! http://getgnulinux.org/es

**Comment by nilsteampassnet** [comment]
Thank you!
For sure any donation is very welcome.
Please visit page http://teampass.net/donation.html.

**Comment by jathanblackred** [comment]
On 27/02/15 07:05, Nils Laumaillé wrote:
> Thank you!
> For sure any donation is very welcome.
> Please visit page http://teampass.net/donation.html.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilsteampassnet/TeamPass/issues/906#issuecomment-76348561>.
> 
Hello Nils. How was your weekend? Sorry for answer until now. Thank you
very much for the link. I hope make the donation in the next days. Regards.

-- 
Por favor evita enviarme adjuntos en formato de word o powerpoint, si
quieres saber porque lee esto:
http://www.gnu.org/philosophy/no-word-attachments.es.html
¡Cámbiate a GNU/Linux! http://getgnulinux.org/es
