### ISSUE TITLE
Copy a child directory with their subdirectories structure to another parent directory

### ISSUE THREAD

**Issue by jathanblackred** [nilsteampassnet/TeamPass#907]
Hello. Working today with Teampass and made a mistake in the location of a child directory into a wrong parent directory, I searched how to copy or move this child directory with its subdirectories to the right parent directory, but I found that is only possible copy items. Is there a some way for copy a directory with its subdirectories and all their contents to a different parent directory in the Teampass web interface without editing the corresponding tables in MySQL?. Thank you.

**Comment by nilsteampassnet** [comment]
The feature "Move a folder" was indeed missing.
I've added it in last commit in "development" branch.

**Comment by jathanblackred** [comment]
Thank you very much for your answer Nils. Sure it will be a very nice new function for Teamspass :)
