### ISSUE TITLE
item view empty for some folders

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#909]
in some folders, the item detail view is empty.
I don't know if there is a limit in the name length of a folder or some other limitations which can explain the behavior.
I'm not sure it is coming from the length but maybe another reason ?

**Comment by sfrlaurent** [comment]
after checking the behavior, I can explain a little bit more:
if the header of the item list window (the grey window upper right of the folders windows) in using only one line, everything is OK.
if the header needs 2 lines, (because of a long folder name or a big amount of subfolders) the detail windows on the bottom is empty.
Is there a way to fix this bug ?

**Comment by sfrlaurent** [comment]
here is a view of the trouble:
![detail_bug](https://cloud.githubusercontent.com/assets/10242259/6409805/772c7250-be68-11e4-8a7b-06f6f84f7a2f.png)

**Comment by sstefanovic** [comment]
I'm having same issue. For me it happened after upgrade from 2.1.20 to 2.1.23.
The problem shows up only on my laptop, and doesn't for others, so we can say it is probably a client-side issue. So I tried 4 different browsers, tried changing user agent in FF...

If you double click on item detail, it will open up edit-window where you can see actual password, but that's not solution but workaround.

The funniest part is that worked normal for me before the upgrade on same laptop. I dont know what to think...

**Comment by sfrlaurent** [comment]
I agree it’s a client side issue.
But the reason seems to be the length of the string in the title of the item list window.
I also tried on different browsers or different desktops and the result is the same when the title becomes too long to be written on a single line.
I did a small modification into the items.css file :
Replacing min-height: 20px; by height: 20px; on line 92
And now it’s ok. Not very nice when the line is long but OK.

**Comment by sstefanovic** [comment]
That actually solves the issue... Thanks.

**Comment by WolfgangEibner** [comment]
Actually this is caused by the items_list div above the detail view. It has an height which is computed from screen height. If the items_path div needs more space this height leads to the disappearing detail view.

In my opinion the height on the items_list div isn't needed at all - at maximum a min-height with e.g. 100px could be nice.

So... a better workaround seems to be commenting out line 2277 in items.load.php:
`//$("#items_list").height(window_height-440);`
