### ISSUE TITLE
Backslashes in accounts are not copied to clipboard

### ISSUE THREAD

**Issue by sschuett** [nilsteampassnet/TeamPass#910]
If I there is a backslash within an account (e.g. "abc\def") the backslash will be omitted when using the paintbrush symbol to copy it to the clipboard, resulting in "abcdef" instead of "abc\def".

This occurs in version 2.1.23 but was also the case in former versions.
Tested with Google Chrome.

**Comment by elxinside** [comment]
I still see this issue in version 2.1.25.
