### ISSUE TITLE
Cant login after Installation

### ISSUE THREAD

**Issue by detroxx92** [nilsteampassnet/TeamPass#911]
OS: Ubuntu Server 14.10
Teampass Version: (master) 26.02.2015 14:30

I've installed Teampass followed in here http://teampass.net/installation/installation.html

After i installed teampass i try to login with admin and my given password. But after i click login i get redirected to this index.php?page=items&session_over=true.

includes/settings.php is created.
The sk.php has a salt without special chars.
Tables are created (working with mysql root user)
chmod -R 777 over Teampass directory and Teampass-salt directory

Log:
apache2[7496]: User logged in - 1 - 2015/02/20 06:49:10 172.16.19.19 (Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko)

I tried to install it 5 - 7 Times, to exclude any installation errors i made. Everytime the same result.

**Comment by jeanorwin** [comment]
We have exactly the same problem, affecting both current and new users. Some current users can suddenly no longer log in (alternatively, instead a "Page can not be found" page appears after login and the user has to log in again, resulting in the same page and so on). Newly created users can also not log in.
