### ISSUE TITLE
'Announce this item by email' fails?

### ISSUE THREAD

**Issue by cormack12** [nilsteampassnet/TeamPass#913]
Hi.

I've recently set up TeamPass and I really like it. Just putting final config. and test on before implementing it. I've set up LDAP and the SMTP hosts. I receive email notification to email accounts when they are set up. I added a password item to the folder to test it, and it added it but gave me an error when using the button described in the title.

The item actually saves, and the button opens a context sensitive window with registered users who I wish to email. Any ideas where to start troubleshooting? The error is:

An error appears. Answer from Server cannot be parsed!
Returned data:

**Comment by nilsteampassnet** [comment]
I confirm the issue.
This happens is you select a user for who no email address is set in
Teampass.
Next commit will include a fix.

In file ./sources/items.queries.php, find
```
                        // send email
                        foreach (explode(';', $dataReceived['diffusion'])
as $emailAddress) {
                            // send it
                            @sendEmail(
                                $LANG['email_subject'],

$LANG['email_body_1'].mysqli_escape_string($link,
stripslashes(($_POST['label']))).$LANG['email_body_2'].$LANG['email_body_3'],
                                $emailAddress,

$txt['email_body_1'].mysqli_escape_string($link,
stripslashes($label)).$txt['email_body_2'].$_SESSION['settings']['email_server_url'].'/index.php?page=items&group='.$dataReceived['categorie'].'&id='.$newID.$txt['email_body_3']
                            );

```
replace by
```
                        // send email
                        foreach (explode(';', $dataReceived['diffusion'])
as $emailAddress) {
                            if (!empty($emailAddress)) {
                                // send it
                                @sendEmail(
                                    $LANG['email_subject'],

$LANG['email_body_1'].mysqli_escape_string($link,
stripslashes(($_POST['label']))).$LANG['email_body_2'].$LANG['email_body_3'],
                                    $emailAddress,

$txt['email_body_1'].mysqli_escape_string($link,
stripslashes($label)).$txt['email_body_2'].$_SESSION['settings']['email_server_url'].'/index.php?page=items&group='.$dataReceived['categorie'].'&id='.$newID.$txt['email_body_3']
                                );
                            }
```

**Comment by cormack12** [comment]
Thanks, will test later. Great support!

**Comment by simonkey007** [comment]
Everything works fine when I try to announce only one user from the list but when I picked two or more users from the list I get this error:

POST http://usatrip.pl/teampass/sources/items.queries.php 500 (Internal Server Error)

jQuery.ajaxTransport.send jquery.js:8706 
jQuery.extend.ajax jquery.js:8136
jQuery.each.jQuery.(anonymous function) jquery.js:8282
EditerItem index.php?page=items:2061 
$.dialog.buttons.Save index.php?page=items:3499
e.widget._createButtons.e.isEmptyObject.e.isArray.i.length.e.each.s.click jquery-ui.min.js:11
jQuery.event.dispatch jquery.js:5095
jQuery.event.add.elemData.handle jquery.js:4766
