### ISSUE TITLE
csv and pdf export in teampass 2.1.23 still not working

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#915]
both export functions don't work.
the csv is exporting just the headers and no contents
the pdf is not getting finished

both tested with an folder with an huge amount from 2 (two) entries... ;-)

**Comment by rdoursenaud** [comment]
Confirmed here.
PDF is issued but no text is embedded.
Only the table and what looks like reservation blocks for the text.

**Comment by rdoursenaud** [comment]
CSV works for me though…

**Comment by kilyanhawk** [comment]
Hello, for export pdf of the elements, the column password is shifted making the information unreadable.
CSV export work fine.
version : 2.1.23
