### ISSUE TITLE
Error message in Search view

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#918]
We get an error message pop-up when entering the Search field with too less data, from the third or fourth character - the error message is gone away...

```
DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.
```

**Comment by hexxamillion** [comment]
I had to apply the same fix as I did for 2.1.19. Documented in issue: https://github.com/nilsteampassnet/TeamPass/issues/544

Only for 2.1.22 the line I edited was 213. This find works for me now without error.
