### ISSUE TITLE
Are we able to display Read Only folders without strike-through?

### ISSUE THREAD

**Issue by AndyMacP** [nilsteampassnet/TeamPass#919]
I understand that the Strike-Through indicates the folders are Read Only but the strike through makes it difficult to read folder names. Is there any way to have folder Read Only without being presented with the Strike-Through? Maybe set a background color much like the colors used in Roles Management - that would be also acceptable.

**Comment by nilsteampassnet** [comment]
In 2.1.23, no "strike-through" is used any more ;-)

**Comment by suniltantry** [comment]
How do we disable this in 2.1.22. or is there a work around. It is really annoying when you see the strike through and also could be misleading.

Kindly suggest.

**Comment by AndyMacP** [comment]
as root:



cd /var/www/teampass



grep line-through –r *



For each result, edit the file, and change line-through to “none”.



or,



sed –i ‘s/line-through/none/g’ home.load.php<http://home.load.php<http://home.load.php%3chttp:/home.load.php>> items.load.php items.php



Log in as a read-only user & test.
