### ISSUE TITLE
password field empty

### ISSUE THREAD

**Issue by bene1988** [nilsteampassnet/TeamPass#922]
Hi,

i got an issue regarding the current master Version of Teampass. I upgraded from Teampass 2.0 and the upgrade process was successful. Everything seems to be fine, except that my passwords are blank. I read about this issue before, but there were no solutions provided. I cannot see any errors, except of one Warning in my nginx logs:

"PHP message: PHP Warning:  mcrypt_decrypt(): Key of size 19 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported in /var/www/teampass/sources/main.functions.php on line 127"

If you need anything, please let me know, i got time for testing, too.

**Comment by nilsteampassnet** [comment]
Really? You were using version 2.0 ????
Not sure the migration of encryption protocol since this version works ... there is certainly some adaptation to be done in the upgrade script.
How many Items managed?

**Comment by bene1988** [comment]
Yes i am using 2.0. There are 216 items managed.Do you have an idea how to upgrade them?
