### ISSUE TITLE
Dynamic generation/Duplicate structure tree

### ISSUE THREAD

**Issue by michmich9337** [nilsteampassnet/TeamPass#930]
Hi;

Is there a way to create a structure tree dynamically or by copying an existing one, and possibly keep rights on these ?

eg : 

Service1
    - Dir1
    - Dir2
    - Dir3
Service2
    - Dir1
    - Dir2
    - Dir3
[...]
ServiceN
    - Dir1
    - Dir2
    - Dir3

Thanks,

**Comment by nilsteampassnet** [comment]
THis currently doesn't exist.
It is a good feature request ;-)
Added to todolist

**Comment by michmich9337** [comment]
Okay thanks, i'm working on it on my freetime. 
If i get something good , i'll send it :-)
