### ISSUE TITLE
HTML mails shown as text only

### ISSUE THREAD

**Issue by GordonFreemem** [nilsteampassnet/TeamPass#931]
Hi,

i've installed TeamPass (2.1.23) for evaluation und ran into a small issue.

HTML-mails are schown as text only and the $_SESSION['settings']['cpassman_url'] variable is not resolved:

```
Hallo,<br><br>das Passwort für 'Testeintrag' wurde geändert.<br /><br />Sie können es <a href='".@$_SESSION['settings']['cpassman_url']."/index.php?page=items&group=1&id=1'>HIER</a> einsehen.<br /><br />Gruß 
```

the same in other languages:

```
Bonjour,<br><br>Le mot de passe de l'élément 'Testeintrag' a été mis à jour.<br /><br />Vous pouvez le vérifier <a href='".@$_SESSION['settings']['cpassman_url']."/index.php?page=items&group=1&id=1'>ICI</a><br /><br />Salutation 
```

Other mail-templates show the correct link but do have the same problem with html:

```
Hallo,<br><br><u><myusername></u> teilt Ihnen hiermit das Element <b>Testeintrag</b><br> mit. Zum Öffnen klicken Sie, bitte, <a href="https://<MYURL>/index.php?page=items&group=1&id=1">LINK</a>.<br><br>Mit freundlichen Grüßen. 
```

I have configured localhost without authentication and let postfix handle the delivery to our Exchange server.

My environment:
- CentOS7
- nginx (1.6.2)
- php (5.4.16) (via php-fpm)
- users via ldap
- Client Outlook (2013)

**Comment by theraser** [comment]
The same problem occurs when sending "Your account creation"-mails. In this case the English version is working fine, but with the German one it looks like this:

>```Hallo,<br><br>Der Administrator hat Ihr Benutzerkonto für TeamPass eingerichtet <br>Sie können sich mit folgenden Benutzerdaten anmelden:<br>- Benutzername: [...]<br>- Passwort: [...]<br><br>Zur Anmeldung klicken Sie, bitte, auf <a href="http://[...]/teampass">LINK</a> .<br><br>Auf Wiedersehen.```

**Comment by xavier95** [comment]
Salut,

Y a t'il un update pour ce problème ?

Merci par avance.

**Comment by xavier95** [comment]
Update french.php (line 181) : 
``'email_body_item_updated' => 'Bonjour,<br><br>Le mot de passe de l\'élément \'#item_label#\' a été mis à jour.<br><br>Vous pouvez le vérifier <a href='.@$_SESSION["settings"]["cpassman_url"].'/index.php?page=items&group=#item_category#&id=#item_id#>ICI</a><br><br>Salutation',``

Update english.php (line 181) : 
``'email_body_item_updated' => 'Hello,<br><br>Password for \'#item_label#\' has been updated.<br /><br />You can check it <a href='.@$_SESSION["settings"]["cpassman_url"].'/index.php?page=items&group=#item_category#&id=#item_id#>HERE</a><br /><br />Cheers',``
