### ISSUE TITLE
install probléme - Json.pars

### ISSUE THREAD

**Issue by ychoucha** [nilsteampassnet/TeamPass#932]
Hello, when i try to install i have a start page probleme : 
i m using ubuntu apache mysql

![teampass_pb](https://cloud.githubusercontent.com/assets/301074/6686538/c1f069ac-cca2-11e4-89c6-60c4a400e3bb.jpg)
what do u think please ?

**Comment by nilsteampassnet** [comment]
What are the answers from the queries?
One of them shall contain the error message

**Comment by ychoucha** [comment]
ok so on appache log i see that : 

'''
[Thu Mar 19 08:18:53.319457 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.319602 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.327880 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.327959 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.329826 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.329888 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.331161 2015] [:error] [pid 24603] [client 192.168.1.51:49804] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.331223 2015] [:error] [pid 24603] [client 192.168.1.51:49804] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.333563 2015] [:error] [pid 24605] [client 192.168.1.51:49805] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.333635 2015] [:error] [pid 24605] [client 192.168.1.51:49805] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.339144 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.339143 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.339251 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.339395 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.345472 2015] [:error] [pid 24605] [client 192.168.1.51:49805] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.345536 2015] [:error] [pid 24605] [client 192.168.1.51:49805] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.346514 2015] [:error] [pid 22020] [client 192.168.1.51:49806] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.346695 2015] [:error] [pid 22020] [client 192.168.1.51:49806] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.347969 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.348066 2015] [:error] [pid 22921] [client 192.168.1.51:49802] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.349662 2015] [:error] [pid 24603] [client 192.168.1.51:49804] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.349723 2015] [:error] [pid 24603] [client 192.168.1.51:49804] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.351729 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.351790 2015] [:error] [pid 22022] [client 192.168.1.51:49803] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.353383 2015] [:error] [pid 22021] [client 192.168.1.51:49807] PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in /var/www/TeamPass/sources/sessions.php on line 168, referer: http://srvTeamPass/TeamPass/install/install.php
[Thu Mar 19 08:18:53.353476 2015] [:error] [pid 22021] [client 192.168.1.51:49807] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/TeamPass/sources/sessions.php on line 77, referer: http://srvTeamPass/TeamPass/install/install.php
'''

**Comment by ychoucha** [comment]
to fix this :   

sudo apt-get install php5-mcrypt
sudo php5enmod mcrypt
sudo service apache2 restart


and now that's works.
need to found how to make it wokrks on https and fix  :
