### ISSUE TITLE
Encoding problem, upgrade 2.1.21 to 2.1.23

### ISSUE THREAD

**Issue by Null-Kelvin** [nilsteampassnet/TeamPass#933]
Upgrade script broke all cyrillic descriptions in database.

Was: Не разлогиниваться
After step 4: ?? ???????????????

Newly created descriptions work fine

**Comment by iddqd2** [comment]
And how do you solve problem with labels in categories?
А как решили проблему с кодировкой в названиях папок в дереве слева при просмотре паролей? (issue парой постов выше от меня)
