### ISSUE TITLE
2.1.22 - Missing Folders that have Write Access To

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#934]
I upgraded from 2.1.16 to 2.1.22. I noticed that all folders permissions that were initially write access changed to Read only access. I have updated them to Write but some of the folder are not visible for users that have write access to them. They do not show up at all on the tree.

**Comment by nilsteampassnet** [comment]
Can you give me the setup you made so that I can reproduce?

**Comment by hexxamillion** [comment]
Currently I have not made any special setups. I simply executed the upgrade and those were the results after the upgrade. The thing I found that I had to do was change the folders there were for some reason made read only back to write. Many of the shared folders that users have access to under the role are simply not visible from the tree at all. Which is strange because the roles management displays them as they should.

**Comment by hexxamillion** [comment]
It appears issue 900 has the same thing for upgrading to 2.1.23. https://github.com/nilsteampassnet/TeamPass/issues/900

**Comment by hexxamillion** [comment]
I reinstalled 2.1.22 and the folders are visible now. Maybe something odd happened during the upgrade the first time. The folders still created as read-only for some reason instead of the correct permissions. I just went through as admin and reset the permissions from read-only to write. It's all good now.
