### ISSUE TITLE
Upload file size

### ISSUE THREAD

**Issue by bal0o** [nilsteampassnet/TeamPass#935]
When i try to upload a 89MB XML into the import process i get a "Error: -600, Message: File size error., File: Current.xml" - I have modified the upload_max_filesize property in php.ini and changed the max filesize in the config options but it still comes up with the error. Can anyone help as to what I am missing?

**Comment by bal0o** [comment]
found the hardcoded file size entry and changed it and it now uploads - doesn't detect it as a keypass file, but uploads now..

**Comment by silfius** [comment]
> found the hardcoded file size entry and changed it and it now uploads - doesn't detect it as a keypass file, but uploads now..

Thanks for your note! Could you tell me where I can modify this setting? 
Thank you very much.
