### ISSUE TITLE
Can't connect to TP after fresh install

### ISSUE THREAD

**Issue by Benji7790** [nilsteampassnet/TeamPass#940]
I can't connect to TeamPass after a fresh install.

I found a workaround but it's not clean...

<b>The problem:</b> When I put the admin login and password, it keeps loading.

I have check the firebug console and see that <i>http://localhost/teampass/sources/identify.php</i> return a 500 error.

So i put these lines on it:

> error_reporting(E_ALL);
> ini_set('display_errors', 'On');

After that, in firebug console, i see these lines:

> <b>Fatal error</b>:  Uncaught exception 'ReflectionException' with message 'Class PasswordLib\Password\Implementation._SHA256 does not exist' in /var/www/teampass/includes/libraries/PasswordLib/Core/AbstractFactory.php:50
> Stack trace:
> # 0 /var/www/teampass/includes/libraries/PasswordLib/Core/AbstractFactory.php(50): ReflectionClass-&gt;__construct('PasswordLib\Pas...')
> # 1 /var/www/teampass/includes/libraries/PasswordLib/Password/Factory.php(104): PasswordLib\Core\AbstractFactory-&gt;registerType('implementations', 'PasswordLib\Pas...', '._SHA256', 'PasswordLib\Pas...')
> # 2 [internal function]: PasswordLib\Password\Factory-&gt;registerImplementation('._SHA256', 'PasswordLib\Pas...')
> # 3 /var/www/teampass/includes/libraries/PasswordLib/Core/AbstractFactory.php(77): call_user_func(Array, '._SHA256', 'PasswordLib\Pas...')
> # 4 /var/www/teampass/includes/libraries/PasswordLib/Password/Factory.php(118): PasswordLib\Core\AbstractFactory-&gt;loadFiles('/var/www/teampa...', 'PasswordLib\Pas...', Array)
> # 5 /var/www/teampass/includes/libraries/Passwo in <b>/var/www/teampass/includes/libraries/PasswordLib/Core/AbstractFactory.php</b> on line <b>50</b><br />

So the workaround I found is to put this code in <i>includes/libraries/PasswordLib/Core/AbstractFactory.php</i> between lines 49 and 50:

> $class = str_replace('._', '', $class);

And now it works.

**Comment by ctwebru** [comment]
You God!!! Thanks :)
