### ISSUE TITLE
LDAP authentication works, but doesn't

### ISSUE THREAD

**Issue by Smokemonster8** [nilsteampassnet/TeamPass#941]
I have installed the latest version of TeamPass.  When I try to authenticate against an OpenLDAP server, I can see in the ldap debug log that binding is sucessful as both the bind search user and as my own user account, but then I still get the error "user_not_exists".

I looked through the code a bit, and I can see that it should be creating a user in the teampass database when it finds one in LDAP but not in teampass, however, this bit is preventing any of that from happening and throwing this error.  In sources/identify.php at line 179:

$counter = DB::count();
    if ($counter == 0) {
        echo '[{"value" : "error", "text":"user_not_exists"}]';
        exit;
    }

So if it does not find a user in teampass, it exists with an error.  But there is clearly code right below this to create a new user from a valid LDAP user.

Also, the installer really screws permissions and probably should not do that.  It is not desirable.  The source code is already freely available, why try to protect it after installing?  A config file or data in MySQL is what should be protected.  If you use something like mod_suphp, I have to re-permission every file and directory after running the installer.

I have also tried using the freshest code by checking it out from git, and now the LDAP bind credential settings have no description.

This LDAP implementation seems very broken and should be very easy to fix.  I am exicted to try an use this project but I am having a hard time over coming this issue.  If I have time, maybe I will try to fix and contribute, but my plate is pretty full right now.

**Comment by nilsteampassnet** [comment]
Correction in /sources/identify.php

* Remove
```
    if ($counter == 0) {
    	echo '[{"value" : "error", "text":"user_not_exists"}]';
    	exit;
    }
```
* Find 
```
    // check GA code
    if (isset($_SESSION['settings']['2factors_authentication']) && $_SESSION['settings']['2factors_authentication'] == 1 && $username != "admin") {
```
* Just before this, copy the next code
```
    // Check if user exists (and has been created in case of new LDAP user)
    $data = DB::queryFirstRow("SELECT * FROM ".prefix_table("users")." WHERE login=%s_login",
	    array(
	    		'login' => $username
	    )
    );
    $counter = DB::count();
    if ($counter == 0) {
    	echo '[{"value" : "error", "text":"user_not_exists"}]';
    	exit;
    }

```

Please give a feedback
