### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by brestows** [nilsteampassnet/TeamPass#942]
How to reset admin password ?

**Comment by l33one** [comment]
mysql -u root -p
use teampass;
select login, pw from teampass_users where login = 'anyloginexists';
update teampass_users set pw = 'resultpreviouslyselect' where login = 'admin';

**Comment by constenlasandra** [comment]
I change the admin PW but I still can not login. 
Do I have to activate the maintenance Mode? how? i´m just a Manager user and I don´t have a settings button...
thank you :-)

**Comment by eddriesen** [comment]
Just to anyone else scratching their head over this (and finding nothing else but this issue to fix)
If you ave another known user where you do know the password to.

To clarify @l33one 's steps;

mysql -u root -p
use teampass;
select login, pw from teampass_users where login = 'ANYUSERWHEREPASSWORDISKNOWN';
#youll get a salted key under the "pw" table cell, copy this key!
update teampass_users set pw = 'SALTEDPASSWORDCOPIEDINPREVIOUSSTEP' where login = 'admin';

after this , you wil be able to log in with "admin" and the users password.

Cheers! (Sorry for reviving an old thead)
