### ISSUE TITLE
User's authorization won't work.

### ISSUE THREAD

**Issue by brestows** [nilsteampassnet/TeamPass#943]
After the update for 2.1.23 the user's authorization isn't working both through LDAP and locally through Mysql. There is an error in the log file
[error] [client 192.168.0.190] PHP Warning:  implode(): Invalid arguments passed in /home/apache/teampass/sources/users.queries.php on line 624
 [error] [client 192.168.0.190] PHP Warning:  implode(): Invalid arguments passed in /home/apache/teampass/sources/users.queries.php on line 634

**Comment by roncioiu** [comment]
I have the exact same problem, the error I get is:

[error] 1745#0: *53 FastCGI sent in stderr: "PHP message: PHP Warning:  implode(): Invalid arguments passed in /var/www/sources/users.queries.php on line 634" while reading response header from upstream,
