### ISSUE TITLE
I cannot make OTV working

### ISSUE THREAD

**Issue by sfrlaurent** [nilsteampassnet/TeamPass#944]
Maybe I'm wrong but everytime I try to use a OTV link, the link ask me to connect with a tempass account.
I thought the link was accessible to everyone. Once and in a given time but without account in teampass . Am i wrong ?
I don't know where to search error if any . I'm using 2.1.23 version of teampass.
thanks for your help.

**Comment by iddqd2** [comment]
Same thing. Link should be accessible to everyone without registration.

**Comment by argonlens** [comment]
Also the same problem , @nilsteampassnet  please can you give us a hint how to solve this ? 
Beside of this problem - great work !

**Comment by nilsteampassnet** [comment]
Yes it is right. Otv link should be visible by any one. 
I will have a look to this

**Comment by toptnc** [comment]
Same here. OTV links shows login page, but even login the password is not showed.
Looking at otv.php I have seen a bug in Line 32
main.functions.php is in sources dir, not in includes dir. This is how it should be.

    require_once $_SESSION['settings']['cpassman_dir'].'/sources/main.functions.php';

anyway, fixing that does not fix the OTV links.

I have inspected html code generated with an OTV link and can see the password code inside, but it isn't showed.
Here can you see an example of html generated by OTV link with teampass 2.1.23.

http://pastebin.com/Cx1VpGY6

**Comment by toptnc** [comment]
I have seen the bug. This script at head section makes browser jump to login screen if your browser tries to load a URL without a "page=" argument. I suggest to include a "otv=" argument check.

        <script type="text/javascript">
            if (window.location.href.indexOf("page=") == -1) {
                if (window.location.href.indexOf("session_over=true") == -1) {
                    location.replace("http://pass-pre.jclm.es/index.php?page=items");
                } else {
                    location.replace("http://pass-pre.jclm.es/index.php?page=items&session_over=true");
                }
            }

**Comment by toptnc** [comment]
I have fixed it with this change at Line 127 in index.php

   if (window.location.href.indexOf("page=") == -1 && window.location.href.indexOf("otv=") == -1) {
