### ISSUE TITLE
Cyrillic labels. Again.

### ISSUE THREAD

**Issue by iddqd2** [nilsteampassnet/TeamPass#948]
Labels for folders broken.
Items in folders with broken labels is not shown.
When exporting broked folder to pdf all items in resulting file shows correctly
![image](https://cloud.githubusercontent.com/assets/1087286/7002508/6f6fa85a-dc65-11e4-9e6e-39f99e0fc006.png)

**Comment by djvnsk** [comment]
Same thing.

**Comment by iddqd2** [comment]
When it would be solved?
