### ISSUE TITLE
Bad HTLM email template

### ISSUE THREAD

**Issue by powertim** [nilsteampassnet/TeamPass#956]
Hi,

I received a password notification by email (Exchange server) like this:

_Bonjour,&lt;br>&lt;br>Le mot de passe de l'élément 'Administrateur local NEW Windows Server' a été mis à jour.&lt;br />&lt;br />Vous pouvez le vérifier &lt;a href='".@$_SESSION['settings']['cpassman_url']."/index.php?page=items&group=1&id=1'>ICI&lt;/a>&lt;br />&lt;br />Salutation_

Seems to be a culture problem because in English, I received:

_Hello,_

_Password for 'Administrateur local NEW Windows Server' has been updated._

_You can check it HERE_

_Cheers_

Could you help me to fix it please ?

Thanks.

**Comment by chikini** [comment]
hi, 
i have the same issue,
any help?
thk

**Comment by Dirk23** [comment]
Same here. Not fixed with 2.1.23

Please fix it!

Thnx

**Comment by avsavchenko** [comment]
2.1.26 final 2
Same here
Hallo,<br><br>Der Administrator hat Ihr Benutzerkonto für TeamPass eingerichtet <br>Sie können sich mit folgenden Benutzerdaten anmelden:<br>- Benutzername: ***<br>- Passwort: ***<br><br>Zur Anmeldung klicken Sie, bitte, auf <a href="http://a.b.c.d/teampass">LINK</a> .<br><br>Auf Wiedersehen.
Thx
