### ISSUE TITLE
LDAP authentication still doesn't work

### ISSUE THREAD

**Issue by Anim-IT** [nilsteampassnet/TeamPass#972]
Hi
I've installed TeamPass in version 2.1.23 and wanted to implement  LDAP authentication but it doesn't work.
TeamPass can ask my DC's , getting answer and than should create user in database but instead doing it I have answer "user not exists " 
After checking many similar issues I founded problem in sources/identify.php which doesn't create user for LDAP authentication. 
I'm not so familiar with PHP code to fix it myself so anyone can help me to fix it so I can use LDAP feature in my organisation  ?

Tom

**Comment by fm81** [comment]
+1, same problem here

**Comment by baudette** [comment]
I had the same trouble and I created every user in teampass without 
password and all my user can now log into teampass with the ldap passwd. 
I had only 10-15 users who use teampass so it was not a big issue for me.

**Comment by Anim-IT** [comment]
Tried solution with blank passwords but then I think I hit another wall that login screen hungs up waiting for response from DC . I had to increase security level of my DC and I turned off anonymously querying DCs so can't check if it works .

**Comment by hrupprecht** [comment]
+1, same problem here too

**Comment by fwsjohn** [comment]
+1 - need to add option for authenticated AD bind/search

**Comment by michmich9337** [comment]
Hello @Anim-IT , @fm81 , @baudette , @hrupprecht , @fwsjohn  

It was a discussion about this problem some month ago, their is the way to correct this. 
(According you are authentificate against Windows AD)

### In file /sources/identify.php

1. Replace at line 215 
from 
<pre>
    if ($counter == 0) {
        echo '[{"value" : "error", "text":"user_not_exists"}]';
        exit;
    }
</pre>
to 
<pre>
    if ($counter == 0 && $ldapConnection == false) {
        echo '[{"value" : "error", "text":"user_not_exists"}]';
        exit;
    }
</pre>

2. Then surround with a try - catch block at line 336 : 
from 
<pre>
        // check the given password
        if ($pwdlib->verifyPasswordHash($passwordClear, $data['pw']) === true) {
            $userPasswordVerified = true;
        } else {
            $userPasswordVerified = false;
        }
</pre>
to 
<pre>
        // check the given password
        try {
            if ($pwdlib->verifyPasswordHash($passwordClear, $data['pw']) === true) {
               $userPasswordVerified = true;
            } else {
              $userPasswordVerified = false;
            }
        } catch (Exception $e) {
            $userPasswordVerified = false;
        }
</pre>

Let me known if it works.
Best Regards
