### ISSUE TITLE
Can't install TeamPass

### ISSUE THREAD

**Issue by silvermoon18** [nilsteampassnet/TeamPass#975]
I am just new to teampass and centos but i am making a test server if teampass is what we need. I followed the instruction that i found on the net about teampass installation but i cannot open the page http://ipaddress/teampass/install/install.php. It says the link was not found in the server. I checked the /var/www directory and saw the teampass file. I open the teampass folder and there's install and install.php file. I gave chmod -R 777 teampass permission but still no luck. My Apache, MYSQL, and PHP are working after i did some test. So I am kinda lost of what will be my next step. Please help!!!

**Comment by agh1467** [comment]
This may be due to an selinux issue denying access to the new files that don't have a context set. Easy fix is disable selinux. Proper fix is setting the correct conext on the new files. If that doesn't turn out to be the issue, post some log messages or something. Your description of the issue isn't very clear.

**Comment by silvermoon18** [comment]
I was able to access http://ipaddress/teampass/install/install.php. Now I am on the page of checking elements. I am using CentOS and I tried the following:
![teampass](https://cloud.githubusercontent.com/assets/12426101/7613827/581a32d8-f993-11e4-939c-7458d6538df7.JPG)
What am I doing wrong here?

**Comment by agh1467** [comment]
It's checking to see if the path displayed is writable by the apache process.

https://github.com/nilsteampassnet/TeamPass/blob/Release_2.1.22/install/install.queries.php#L69

Under normal circumstances an error will be displayed on the page, see line 72 where is appends " is not writable!" to the error string.

This could also be an selinux issue as it can deny write access aside from the traditional DAC permissions.

**Comment by silvermoon18** [comment]
hello agh1467 my teampass is up now. You were right it was the SELinux permission. I enable the SELinux permission in sysconfig file and that solved the problem. 
I was able to install everything and now got a new problem. 
default login admin admin is not working. 
I checked my mysql user and i can't find that user.
