### ISSUE TITLE
Looks like "Send not sent emails" doesn't work

### ISSUE THREAD

**Issue by dominicblade** [nilsteampassnet/TeamPass#976]
I turned on the option enable_send_email_on_user_login, emails appear in the MySQL table "emails" with the status "not sent", and they do not go.
I've normally receive emails on item change - it works fine.
please guide me where to dig

UPDATE

As I understand the challenge of the case "send_wainting_emails" going through the POST from home.load.php, it also connected from home.php, which is not used 2.1.23
Perhaps it is reasonable to make a POST request from core.php

**Comment by ianco1** [comment]
Version 2.1.26

Send Email backlog is not reporting the backlog as the SQL statement is selecting on 'not_sent' rather that 'not sent' which is what is written to the table.
Pressing the start button does not send the emails either.

With a quick search of the source it appears the following files need updated
admin_settings.php
sources/admin.queries.php
