### ISSUE TITLE
Plugins for Browsers

### ISSUE THREAD

**Issue by luizkim** [nilsteampassnet/TeamPass#977]
It would be great if there were a plug-in for browsers , like this:
http://www.teampassword.com/

**Comment by nilsteampassnet** [comment]
​I agree ... it is an old idea I have, but until now I did not been able to
work on this subject.

It will come for sure.​

**Comment by churusaa** [comment]
Sorry to raise the dead, but do you know if there are any existing projects to build a plugin for TeamPass for Chrome and/or Firefox, etc...?  I'm considering starting development on this, and want to be sure I'm not reinventing any parts of the wheel I'll need. I could also contribute directly here if that'd be better. I am a novice, more of a language tourist than a pro at any one language, but I'd like to help in any way I can.

**Comment by luizkim** [comment]
I do not really know of any similar project. It would really be very interesting to have something like the one described, since I use the web version of TeamPass. Any help will be appreciated.

**Comment by nilsteampassnet** [comment]
Check for Teampass-Connect on Firefox extension portal

**Comment by teamfighter** [comment]
Some news about chrome extension? That the only thing that prevent my company to use teampass

**Comment by Ilya-Kuchaev** [comment]
Apologizes. But it's still the actual question.

**Comment by YannMaurer** [comment]
Yeap Chrome extension is still actual, especially as Firefox Quantum does not suppport Teampass-Connect anymore

**Comment by steven792** [comment]
any news on this as a possibility for chrome?

**Comment by yoyokko** [comment]
> any news on this as a possibility for chrome?
FYI, works like a charm
https://github.com/koios-sh/teampass-browser

Usage in Chinese: https://zhuanlan.zhihu.com/p/83952921
I'll translate to en asap.
