### ISSUE TITLE
Authenticated AD binding?

### ISSUE THREAD

**Issue by fwsjohn** [nilsteampassnet/TeamPass#980]
My organization doesn't allow for anonymous Active Directory binding/lookups, is there a way to add a resource account to use when binding or doing the auth look up so I can have ad users authenticate?

adding a AD user and password field for Authenticated AD binding

**Comment by hexxamillion** [comment]
I have the same scenario.

**Comment by hexxamillion** [comment]
I think this can be configured in the adLDAP.php file. 
\includes\libraries\LDAP\adLDAP\adLDAP

Lines 97,97 -ish

/**
    * Optional account with higher privileges for searching
    * This should be set to a domain admin account
    *
    * @var string
    * @var string
    */
    protected $_ad_username=NULL;
    protected $_ad_password=NULL;

**Comment by fwsjohn** [comment]
ok still not working…. What about importing a csv of users? would make things a bit simpler

not ideal but it gets me there.

**Comment by baudette** [comment]
I use teampass with
          samba4 AD and its working very nice. 
          
          
    
       
    
    On 26/05/2015 5:35 PM, fwsjohn wrote:
    
    ok still not working…. What about importing a csv of
      users? would make things a bit simpler
      
      not ideal but it gets me there.
      
      
      > On May 21, 2015, at 10:31 AM, hexxamillion
      <notifications@github.com> wrote:
      > 
      > I think this can be configured in the adLDAP.php file. 
      > \includes\libraries\LDAP\adLDAP\adLDAP
      > 
      > Lines 97,97 -ish
      > 
      > /**
      > * Optional account with higher privileges for searching
      > * This should be set to a domain admin account
      > *
      > * @var <https://github.com/var> string
      > * @var <https://github.com/var> string
      > */
      > protected $_ad_username=NULL;
      > protected $_ad_password=NULL;
      > 
      > —
      > Reply to this email directly or view it on GitHub
<https://github.com/nilsteampassnet/TeamPass/issues/980#issuecomment-104345559>.
      > 
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by wyrucz** [comment]
Authenticating against AD is working in general. The user has to exist in the Database though since automatic adding of Users does (for some reason) not work (TeamPass will throw a user_not_exist error box).

**Comment by adrianhalid** [comment]
TeamPass will throw a user_not_exist error box is address under
https://github.com/nilsteampassnet/TeamPass/issues/742
