### ISSUE TITLE
How can we view Access Log from Database?

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#981]
The view log for accessed items, how can that data be viewed from the database? What table does it reside? I want to be able to monitor for specific items that are accessed and be notified. Teampass at the moment only has ability to view the logs from gui. To automate I need to access from another means like database.

..unless a new feature is added to item edit form to add to a watchlist for access and send email when accessed and by whom and include time date stamp.

**Comment by Anim-IT** [comment]
It's in  (your_prefix_table)_log_items  , where you have id_item, id_user and action done on accessed items.

**Comment by hexxamillion** [comment]
Thanks!

**Comment by hexxamillion** [comment]
The date format is not very friendly. Any idea on converting this date format from the log_items table?

Example:
id     |     date         | id_user |   action    | raison
------|------------------|------------|--------------|----------
148 | 1340379831 | 123       | at_shown |

**Comment by hexxamillion** [comment]
Nevermind. I figured this is unix timestamp. I converted it accordingly.

**Comment by nilsteampassnet** [comment]
Can be closed?

**Comment by hexxamillion** [comment]
Sure.

Regards,

Hector
(Sent from mobile)
