### ISSUE TITLE
Teampass combined with wiki server..is it advisable?

### ISSUE THREAD

**Issue by silvermoon18** [nilsteampassnet/TeamPass#984]
Hi, 

Is it advisable to install teampass in our wiki server? or it is highly recommended to install Teampass in a standalone server?

Please advise. 

Thank you.

**Comment by nilsteampassnet** [comment]
You can install on a server with other elements on it.
Just ensure a specific sub-domain in httpd.conf file

**Comment by silvermoon18** [comment]
Good to hear that. Thank you

**Comment by gyoza** [comment]
I run mediawiki and teampass on the same system without problems.
