### ISSUE TITLE
Cannot access Teampass in cloned VM

### ISSUE THREAD

**Issue by mccgtech** [nilsteampassnet/TeamPass#987]
Hello,

We want to upgrade from 2.9.1 to 2.9.22, we are currently running TP on Linux in VMWare. We want to test the upgrade first so we cloned the VM to a test environment.

Before the upgrade we cannot log into Teampass in the cloned VM, Teampass sees the user's accounts in MySQL but not the passwords. Keeps saying "wrong password for this account", if you put in an invalid user account it says the "the user account does not exist" so it sees the user accounts...

The cloned VM is identical with the same MAC address. Any help on this would be appreciated.

**Comment by michmich9337** [comment]
Hello mccgtech,

Are the VMs avec the same IP address ?
If false, you have to change to the IP in `database` . `your-prefix_misc`

**Comment by mccgtech** [comment]
Hello Mich,

The IP and MAC are the same, the DB is set to local host 127.0.0.1. Where exactly is "database . your-prefix_misc"? 

Thanks!

**Comment by michmich9337** [comment]
Hello mccgtech,

When you connect to database, you have a database "teampass"
In this database you have some table with a prefix 'teampass_' (by default) then you have one, called  'misc'

However, if the VMs are the same , i guess there is other thing.
