### ISSUE TITLE
teampass 2.1.23 child folder inherit properties of parent?

### ISSUE THREAD

**Issue by bcwhittle** [nilsteampassnet/TeamPass#989]
I recently installed 2.1.23, and really like the looks of this for my small company to use. As I am setting it up, though, I have encountered a behavior which seems strange to me. As a user with full permissions on all folders, I create a folder as a child to another folder. But then I cannot add anything to that folder until I log out, log in as admin, give myself full permission on the folder, log out, and log back in as myself.

I have turned on "New sub-folder inherits rights from parent folder"
and "Users are allowed to manage folders in allowed parent folders".

Am I missing something here?

**Comment by kracoucas** [comment]
Hello,
I have the same issue with my fresh teampass installation.
All new folders are in read only mode. Admin rights modification is mandatory to allow users to create new objects in the folder.
Regards

**Comment by nilsteampassnet** [comment]
What is the path from which you downloaded 2.1.23?

If not, can you check from [development branch](https://github.com/nilsteampassnet/TeamPass/tree/development) which contains last commits?

If I remember well this should be corrected.

Note: I will have to delete this 2.1.23 branch.

**Comment by bcwhittle** [comment]
I *think* I downloaded it from this link: https://github.com/nilsteampassnet/TeamPass/archive/master.zip

That was on the website under the 2.1.23 release.
If it helps, the zip file shows (on my linux server) a file size of 7788878.

Does that help?

**Comment by nilsteampassnet** [comment]
Hum after quickly check the code, I did not commit a change I've made.

Can you make this change:
* open file /sources/folders.queries.php
* find 
```
                    foreach ($rows as $record) {
                        //add access to this subfolder
                        DB::insert(
                            prefix_table("roles_values"),
                            array(
                                'role_id' => $record['role_id'],
                                'folder_id' => $newId
                           )
                        );
                    }
```
* and replace by
```
                    foreach ($rows as $record) {
                        //add access to this subfolder
                        DB::insert(
                            prefix_table("roles_values"),
                            array(
                                'role_id' => $record['role_id'],
                                'folder_id' => $newId,
                            	'type' => $record['type']
                           )
                        );
                    }
```

**Comment by bcwhittle** [comment]
I made that change on my server. What do I need to do to get it to allow access to the personal folders?

**Comment by bcwhittle** [comment]
Sorry for my last response . . . I was thinking this was addressing something else. Now I’m good.

**Comment by nilsteampassnet** [comment]
Did this change fixes the issue?

**Comment by bcwhittle** [comment]
Yes, it seems to work as expected. Thank you!

**Comment by bcwhittle** [comment]
I am not sure whether or not this problem is related, but here is my situation:
I give user C access to folder Clients/company2 and Clients/company2/SQL.
Then I create a new folder Clients/company2/mysql.
User C does not have access to the new folder until I log in as an administrator, go to users and add this new folder to the User.

Is there a setting which is supposed to cause this? I assumed that a user would be able to see any new folders created under a folder to which they already have access.

**Comment by nilsteampassnet** [comment]
WHy not to use Roles here to manage more easily the access of your users?

I confirm that if you just handle the access of UserA to a folder from the "users page", then in this case, if another user creates a new subfolder, then UserA will not have access to it.
Indeed, specific access from user profil should be considered as a "exception setting".

It is really recommended to use Roles for a better access control.

Nevertheless, I could certainly improve this behavior if requested by users.
