### ISSUE TITLE
Installation doesn't work (Encryption\Crypt\aesctr::decrypt problem)

### ISSUE THREAD

**Issue by Allmektiger** [nilsteampassnet/TeamPass#990]
Hello!

I try to install teampass 2.1.23 (and 2.1.22 before with the same results).
I can't pass step 3 (database connection), because of function 
Encryption\Crypt\aesctr::decrypt 
in file install.queries.php can't decrypt post data.

It return something like that:
string(62) "�����2a�%/(�_j+�0�   ��z��.юP5�7�N3gu�?->/    O\�Ƕd��%ٸ��j"
or
string(72) ")�Ƴ+�:s���I#۷�������@��j�1����߾I���U��7�[۠�[�N�N
���./�3���nn�"
With the absolutely same form data it returns different results.

Meanwhile javascript Aes function seems working fine.
I try that
var test = aes_encrypt(data);
alert (Aes.Ctr.decrypt(test, "cpm", 128));
and it return correct json-text.

Server: CentOS 5.8, php 5.4.40.

Why Encryption\Crypt\aesctr::decrypt may return wrong results?

**Comment by Allmektiger** [comment]
As i may see, step 2 with checking system also doesn't work because of incorrect working of Encryption\Crypt\aesctr::decrypt.

When i press button Launch it renamed to Next, but in section "Following elements will be checked" nothing happens. I.e. no green or red symbols.

**Comment by Allmektiger** [comment]
For testing i put next code:

require_once '../includes/libraries/Encryption/Crypt/aesctr.php';  // AES Counter Mode implementation
$string = "some string";
echo "<pre>$string</pre>";
$encrypt = Encryption\Crypt\aesctr::encrypt($string, "cpm", 128);
echo "<pre>$encrypt</pre>";
$decrypt = Encryption\Crypt\aesctr::decrypt($encrypt, "cpm", 128);
echo "<pre>$decrypt</pre>";

It returns next results:

some string
4kCAVQAAAAAsxq6RFsvFZyGLgw==
��6M��

some string
LEGAVT8/Pz+6yxjooLhdpdpz2Q==
so��%�

some string
MkGAVbW1tbXvAzjUjCGrY0KBLQ==
s�t�^<

Why?

**Comment by Allmektiger** [comment]
Continue my experiments...
I use js-decrypt function to php-encripted string:
echo "<script type='text/javascript'>alert(Aes.Ctr.decrypt('$encrypt', "cpm", 128));</script>";
And it always return fine string "some string".

After that i began comparision between php and js function and i saw next:

PHP: $ciphertext = base64_decode($ciphertext); // vK�UNNNNf�,��]+��
JS: ciphertext = Base64.decode(ciphertext); // vKUNNNNf²,±]+ÀÂ

PHP: $ciphertext = $ct; // f�,��]+��
JS: ciphertext = ct; // f²,±]+ÀÂ

Is this encoding problem? How it solving?

**Comment by Allmektiger** [comment]
And why php base64_decode and js Base64.decode work different?

**Comment by Allmektiger** [comment]
Lol...
After refreshing multiple times code
$string = "some string";
echo "$string";
$encrypt = Encryption\Crypt\aesctr::encrypt($string, "cpm", 128);
echo "$encrypt";
$decrypt = Encryption\Crypt\aesctr::decrypt($encrypt, "cpm", 128);
echo "$decrypt";

$decrypt take next values:
some strin
some�
some sY�>[
some sto�
so�}�[
sNEC���
some s��,
su/ͲQ�=
some string <<<<<<<<<!!!!!!!!!!!!!
som�W�
some strin
some st�
]eޠw
some string <<<<<<<<<!!!!!!!!!!!!!
c�՞�j:
&3mYiy�K
5�`��
��ֵ(k
,���hd
�+ۋ�

Wtf... 20 times and only 2 correct decrypts...

**Comment by Allmektiger** [comment]
Hmmm...
I try next

$ciphertext = $ctrTxt . implode('', $ciphertxt);
echo "before: $ciphertext";
$ciphertext = base64_encode($ciphertext);

$ciphertext = base64_decode($ciphertext);
echo "after: $ciphertext";

This give similar strings.
But js-base64_decode function give another result on php-64encoded string...

**Comment by nilsteampassnet** [comment]
For me, it is related to the data you are entering in step3 (database credentials).
Indeed if it is the encryption library that fails, it means that it should have failed also at step2 of the installation, which is not the case (if I've well understood the point).

Can you try some simple credentials (simple string)?

**Comment by Allmektiger** [comment]
As i write before

> As i may see, step 2 with checking system also doesn't work because of incorrect working of Encryption\Crypt\aesctr::decrypt.
> When i press button Launch it renamed to Next, but in section "Following elements will be checked" nothing happens. I.e. no green or red symbols.

All what i entered at step 3 is:
localhost
psw
psw
123456

**Comment by Allmektiger** [comment]
Interesting. I try to install teampass on another server with php 5.3, and all function work fine...
But unfortunately i must install on php 5.4...

**Comment by DavidBruchmann** [comment]
looks like you saved the file not as utf-8 without BOM but as ANSI.
Check all involved files i.e. install.queries.php how they are saved and
change if not UTF-8 without BOM.

Bestr Regards,
David

**Comment by Allmektiger** [comment]
I thinking about it firstly, but no. All files has encoding UTF-8 without BOM, mode: Unix (LF).
install.php
install.queries.php
install.js
aes.min.js
jquery.min.js
aes.php
aesctr.php

This bug in php 5.4, but not at php 5.3.
Now i try to upgrade to php 5.5 and test on it.

**Comment by DavidBruchmann** [comment]
Whats about character-encoding from and to the database?

Best Regards,
David

**Comment by Allmektiger** [comment]
Utf-8 general_ci, but this is not DB problem. 

Next code

> $string = "some string";
> $encrypt = Encryption\Crypt\aesctr::encrypt($string, "cpm", 128);
> $decrypt = Encryption\Crypt\aesctr::decrypt($encrypt, "cpm", 128);
> echo "$decrypt";

Return results like

> some strin
> some��
> some sY�>[
> some sto�
> so��}�[
> s��NEC����

**Comment by nilsteampassnet** [comment]
I don't really understand what you are facing.
It sounds to be related to the server itself with a kind of incompatibility of the encryption library.
But how to investigate, I don't have any idea.
I will tru to found time on the provider's website

**Comment by 2amedia** [comment]
i have this problem too.
PHP Version 7.0.16
CentOS 7
