### ISSUE TITLE
Folders table truncated by some action. Passwords still on database

### ISSUE THREAD

**Issue by lastcron** [nilsteampassnet/TeamPass#993]
Ver 2.1.22 on Ubuntu 14.0 LTS

Suddenly today all folders are missing from all users. I checked the database and the folders table is empty.  Password are still on database.

Here is what caused it:

A user updated his salt key and after loggin out and back in  all folders and passwords were deleted. They were still on the trash can and they were restored, but all the folder structure did not get restored.

I can still access the passwords using the lookup window but there are no folders in the database tables.

Any Ideas

**Comment by nilsteampassnet** [comment]
This one is tricky. 
What version? 
The user has only get logged?
