### ISSUE TITLE
Feature Request: Set Default Role

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#997]
Can there be an option in the admin settings to set a default role for new accounts? Currently default is no role. It would be nice to at least assign them to a General role that only enables personal folders but no access to any other folders.

**Comment by jgrantredfuse** [comment]
I would really like to see this functionality also.  I am using ldap and it seems anyone with an ldap account by default see everything which makes teampass useless to me unless I can find a way to block what users see by default.
